### ISSUE TITLE
[Translation] No Japanese translations in the documentations?

### ISSUE THREAD

**Issue by dshukertjr** [felangel/bloc#1015]
First of all, thank you for such a great work with this library! I love it and use it everyday. 

I was wondering if there is someone working on a Japanese translation of this documentation. If not, could I do it?

**Comment by felangel** [comment]
Hi @dshukertjr 👋 
Thanks for opening an issue and for the positive feedback!

No one is working on Japanese translations at the moment and it would be amazing if you took the lead on that 👍
