### ISSUE TITLE
Error with Firabase login transformEvents

### ISSUE THREAD

**Issue by MatyasK** [felangel/bloc#1016]
I'm following the Firabase login example, but I have an error in my bloc files. 
![image](https://user-images.githubusercontent.com/15628788/78935790-b4d4d780-7aad-11ea-8ac0-c6dad36084da.png)

and my imports are:

`import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:meta/meta.dart';
import 'package:ruhatar/helpers/validators.dart';
import 'package:ruhatar/repositories/user_repository.dart';
import 'bloc.dart';
import 'dart:async';
import 'package:rxdart/rxdart.dart';
`
I can't find any difference to the example and the issue exist in login, authentication and register blocs.

**Comment by felangel** [comment]
Hi @MatyasK 👋 
Thanks for opening an issue!

What version of `bloc` and `flutter_bloc` are you using?

**Comment by MatyasK** [comment]
I have these versions:
`dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+8
  google_sign_in: ^4.0.0
  firebase_auth: ^0.15.0+1
  flutter_bloc: ^3.2.0
  equatable: ^1.0.0
  meta: ^1.1.6
  rxdart: ^0.23.1
  font_awesome_flutter: ^8.4.0`

Thank you very much for the quick response :)

**Comment by MatyasK** [comment]
I fixed it by adding the latest version from github manually, but the correct version is available from pub.dev?

**Comment by felangel** [comment]
@MatyasK the documentation is using the dev release so you can updated your `pubspec.yaml` to
```yaml
bloc: 4.0.0-dev.1
flutter_bloc: 4.0.0-dev.1
```

**Comment by felangel** [comment]
Closing for now and sorry for the inconvenience! Let me know if you have any other questions 👍

**Comment by MatyasK** [comment]
Thank you very much! :)

**Comment by MatyasK** [comment]
I just found a new issue, if I run it on my phone if the debugger is connected the app is unresponsive if I close the app and run it again without the debugger it works. Any other flutter application without the firebase login is working fine.
