### ISSUE TITLE
Bloc documentation on testing - wrong examples?

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#1023]
I am reading the docs, and arrived at testing. Here (https://bloclibrary.dev/#/testing), we can see an example for the counter bloc:

    blocTest(
      'emits [0, 1] when CounterEvent.increment is added',
      build: () => counterBloc,
      act: (bloc) => bloc.add(CounterEvent.increment),
      expect: [0, 1],
    );

In my case, however, the initial state is never emitted, and the expected `Iterable` must be `[1]` for the test to pass. Here is my (slightly different) bloc:

    class CounterBloc extends Bloc<CounterEvent, int> {
      @override
      int get initialState => 0;

      @override
      Stream<int> mapEventToState(CounterEvent event) async* {
        if (event is CounterIncremented) {
          yield state + 1;
        } else {
          yield state - 1;
        }
      }
    }

Has the implementation changed and the docs haven't caught up, or is my code somehow invalid?

**Comment by felangel** [comment]
Hi @wujek-srujek 👋 
Thanks for opening an issue!

Good catch! The implementation was updated to ignore the initialState by default (unless you set `skip: 0`. I'll make sure to update the docs 👍

**Comment by felangel** [comment]
Fixed in https://github.com/felangel/bloc/commit/da9ba7e352bedae2e28a6ce6083c56c41b027ccb. You should be able to refresh and see the latest implementation 👍
