### ISSUE TITLE
Update Examples to Adhere to Naming Conventions

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#1024]
The documentation mentions naming conventions here: https://bloclibrary.dev/#/blocnamingconventions. However, most of the tutorials (except todos) do not comply with the conventions. Do you think it would be a good idea to refactor the examples to showcase correct, convention-compliant code?

**Comment by felangel** [comment]
Hi @wujek-srujek 👋 
Thanks for opening an issue!

Yup but unfortunately that isn't the highest priority item for me at the moment so if you have some spare time and would like to help update naming I would really appreciate it 👍
