### ISSUE TITLE
get Value from BlocProvider in InitState

### ISSUE THREAD

**Issue by kartzhai** [felangel/bloc#1028]
hi sorry i just new and still learning your package.
in provider to get value on initstate as simple like below :
initState() {
  super.initState();
  print(Provider.of<Foo>(context).value);
}

how on flutter_package to get the value?

if i have class like below 

class idcompanybloc extends Bloc<String, String>{

  @override
  String get initialState => '';

  @override
  Stream<String> mapEventToState(String idcompany) async* {
    yield idcompany.toString();
  }
}

thank you

i have put on stackoverflow : https://stackoverflow.com/questions/61043649/blocprovider-inside-initstate-that-receive-value-from-blocbuilder

**Comment by felangel** [comment]
Hi @kartzhai 👋 
Thanks for opening an issue!

You can access the current state of the bloc like:

```dart
BlocProvider.of<MyBloc>(context).state;
```

or via the shorthand

```dart
context.bloc<MyBloc>().state;
```

Hope that helps 👍

**Comment by kartzhai** [comment]
THANKS ALOT BRO!!! you r a live saver!!
it work so good right now. thanks alot!

**Comment by velchev** [comment]
context.bloc<MyBloc>().state;  - seems I don't have bloc in the context? can someone give example of this approach?

**Comment by felangel** [comment]
> context.bloc().state; - seems I don't have bloc in the context? can someone give example of this approach?

It’s `context.read<MyBloc>()` in more recent versions.

**Comment by DevloperAnuj** [comment]
> > context.bloc().state; - seems I don't have bloc in the context? can someone give example of this approach?
> 
> It’s `context.read<MyBloc>()` in more recent versions.

Should we Need to close it in dispose ? if yes then how to do it in efficient way ?
and thanks for the awesome package like this.

**Comment by felangel** [comment]
> > > context.bloc().state; - seems I don't have bloc in the context? can someone give example of this approach?
> > 
> > 
> > It’s `context.read<MyBloc>()` in more recent versions.
> 
> Should we Need to close it in dispose ? if yes then how to do it in efficient way ? and thanks for the awesome package like this.

Typically whichever component creates the bloc is responsible for closing (disposing) it. This is usually automatically handled for you if you use BlocProvider (with create). Since calling context.read doesn’t create the bloc (it just looks up the nearest instance in the widget tree), you don’t need to worry about disposing it. Hope that helps 👍
