### ISSUE TITLE
elements get destroyed after navigation and comming back to the screen

### ISSUE THREAD

**Issue by samsheldin** [felangel/bloc#1029]
https://github.com/samsheldin/doc ,,, here's the link and I have given you access

login==9008544200,, password 123456 ,
after login it will take you to a screen where there are 3 tabs ,, in the first tab after response if you click on the list "coach now", you'll be navigated to a new page ,, if you press back button or close that page ,, u can see all the ui elements destroyed or invisible, can you help me y this is happening?  @felangel @tenhobi

**Comment by felangel** [comment]
Hi @samsheldin 👋
Thanks for opening an issue!

I took a look at the repo and didn’t see any dart code. Has all the code been pushed?

**Comment by samsheldin** [comment]
yes

**Comment by felangel** [comment]
Can you share a link to the main.dart file? I don’t see any dart code in the repo.

**Comment by samsheldin** [comment]
please wait uploading it now,,sorry

**Comment by samsheldin** [comment]
i'll share the file git seems kind of messy

**Comment by samsheldin** [comment]
@felangel @tenhobi  Hi ,, i have uploade a zip file of the project pls check it out..

**Comment by samsheldin** [comment]
Hi @felangel  i think i have found the error and  it's happening because of the state change during navigation,,, could suggest a better way to navigate after looking at the code

**Comment by felangel** [comment]
@samsheldin have you taken a look at https://bloclibrary.dev/#/recipesflutternavigation?

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions or provide a link to a sample app and I'm more than happy to continue the conversation 👍

**Comment by samsheldin** [comment]
i have done this and it gives me an error

**Comment by samsheldin** [comment]
https://github.com/samsheldin/doc ,   i have follewed a similar pattern but it gets destreoyyed
