### ISSUE TITLE
State update can't be shown in UI using v0.6.0

### ISSUE THREAD

**Issue by X-Wei** [felangel/bloc#103]
The state update is not referenced in the UI.

**To Reproduce**
1. git clone https://github.com/ResoCoder/flutter-bloc-library-tutorial.git
2. Run the app: when clicking on the buttons, the UI updates the counter as expected.
3. Update the flutter_bloc version to 0.6.0 in pubspec.yaml
4. Re-run the app: when clicking on the button, the counter isn't updated.

**Comment by felangel** [comment]
Hey thanks for bringing this up! 

In more recent versions of bloc immutable state is enforced so in mapEventToState you cannot update the currentState and yield it. You need to always yield a new state.

Have you looked at https://felangel.github.io/bloc/#/coreconcepts? I highly recommend reading through it if you haven’t already. 

I also commented on the YouTube video that goes along with that tutorial and asked the author if he can update the code and he hasn’t yet. I’ll try to open a PR today to make his project work with the latest bloc version. 

Does that help?

**Comment by X-Wei** [comment]
I changed to yielding a new State in mapEventToState(), and now it works.
Many thanks to your prompt response ! Highly appreciated !
