### ISSUE TITLE
Navigation example on the bloclibrary.dev DDos my server

### ISSUE THREAD

**Issue by heshaShawky** [felangel/bloc#1031]
**Describe the bug**
I have followed the instructions in 

> https://bloclibrary.dev/#/flutterinfinitelisttutorial

 for how to implement an infinite scroll using flutter_bloc lib and it worked fine as from the logical point ( scroll more data ), but I faced an issue that for single scroll I could makeover 100 requests to my server at once!!!!!!!!

**To Reproduce**
I guess what cases this issue is the following snippet of code: 
```dart
void _onScroll() {
    final maxScroll = _scrollController.position.maxScrollExtent;
    final currentScroll = _scrollController.position.pixels;
    if (maxScroll - currentScroll <= _scrollThreshold) {
      _postBloc.add(Fetch());
    }
  }
```
The following code send an event **if** `maxScroll - currentScroll <= _scrollThreshold`, So if user keep playing and not moving his hand I get more that 50 request at least per one page

**Expected behavior**
Should send only one request per scroll, also in scrolling down not up again as it now behavior because of this condition `maxScroll - currentScroll <= _scrollThreshold`

Problem 2: 
I wanna reset the bloc every time it triggered like it was the first time as I'm making a search bloc and wanna be paginated too with the same query text.

**Comment by felangel** [comment]
Hi @heshaShawky 👋 
Thanks for opening an issue!

Did you follow the tutorial exactly? You should have overridden `transformEvents` in the bloc to debounce the events which would solve the first problem you described.

Regarding problem 2, I'm not sure I fully understand the request. If you really want to reset the bloc, you can always define a `ResetEvent` and have the bloc reset the state whenever the `ResetEvent` is added but in my opinion that is a bit of an anti-pattern and is usually an indicator that your bloc is being provided too high in the widget tree.

Let me know if that helps 👍

**Comment by heshaShawky** [comment]
> Hi @heshaShawky 👋
> Thanks for opening an issue!
> 
> Did you follow the tutorial exactly? You should have overridden `transformEvents` in the bloc to debounce the events which would solve the first problem you described.
> 
> Regarding problem 2, I'm not sure I fully understand the request. If you really want to reset the bloc, you can always define a `ResetEvent` and have the bloc reset the state whenever the `ResetEvent` is added but in my opinion that is a bit of an anti-pattern and is usually an indicator that your bloc is being provided too high in the widget tree.
> 
> Let me know if that helps 👍

Thanks, the First problem solved, my mistake :"D

The second problem, let me explain I'm doing a search included navigation as your tutorial explain,  So when the event runs the first time the state becomes `SearchLoaded` as it should, 

But because of that, I can't operate the search again as I need every time I run the event the state be `SearchInitial` as default then `SearchLoaded`

```dart
@override
Stream<SearchState> mapEventToState(
  SearchEvent event,
) async* {
  final currentState = state;

  print('CurrentState: ' + currentState.toString());
  
  if (event is SearchPosts) {
    yield SearchInitial();

    try {
      if ( currentState is SearchInitial && !_hasReachedMax(currentState)) {
        print(event.query);
        // if (currentState.posts.isEmpty) {
          yield SearchLoading();
          final List<Post> posts = await postsRepostiry.search(event.pageNo, event.query);
          // yield SearchFinished();
          yield SearchLoaded(
            posts: posts,
            hasReachedMax: false
          );
          return;
        // }
      }

      if ( currentState is SearchLoaded ) {
        
        final List<Post> posts = await postsRepostiry.search(event.pageNo, event.query);

        yield posts.isEmpty
          ? currentState.copyWith(hasReachedMax: true)
          : SearchLoaded(
            posts: currentState.posts + posts,
            hasReachedMax: false,
          );
      }
      // yield SearchInitial();
    } catch (e) {
      yield SearchError(e.toString());
    }
  
  }
}
```

**Comment by felangel** [comment]
@heshaShawky thanks for providing more context. In that case, you can either avoid extending `Equatable` or add a `lastUpdated` property to your `SearchLoaded` state like:

```dart
class SearchLoaded extends SearchState {
  SearchLoaded({DateTime lastUpdated, ...}) : lastUpdated = lastUpdated ?? DateTime.now();
  final DateTime lastUpdated;
  ...
}
```

**Comment by heshaShawky** [comment]
Sorry But why I have to add the `lastUpdated` field, what am I gonna use it for? 

> @heshaShawky thanks for providing more context. In that case, you can either avoid extending `Equatable` or add a `lastUpdated` property to your `SearchLoaded` state like:
> 
> ```dart
> class SearchLoaded extends SearchState {
>   SearchLoaded({DateTime lastUpdated, ...}) : lastUpdated = lastUpdated ?? DateTime.now();
>   final DateTime lastUpdated;
>   ...
> }
> ```

**Comment by felangel** [comment]
It'll ensure that when you yield a `SearchLoaded` state, even if the results are the same the lastUpdated time will be different so it will be a different state and you won't need to yield intermediate states just to trigger a state change.

**Comment by heshaShawky** [comment]
Sorry, I don't understand how is the last update time will make a difference?!

What and Where the condition gonna be in the bloc! as I can't think of a scenario using the last search time to differentiate between a new search ( triggered event on every new input ) or scrolling to navigate in a results

My Current bloc
```dart
final currentState = state;
if (event is SearchPosts) {
  yield SearchInitial();
  try {
    if (currentState is SearchInitial && !_hasReachedMax(currentState)) {
      yield SearchLoading();
      final List<Post> posts =
          await postsRepostiry.search(event.pageNo, event.query);
      yield SearchLoaded(posts: posts, hasReachedMax: false);
      return;
    }

    if (currentState is SearchLoaded) {
      final List<Post> posts =
          await postsRepostiry.search(event.pageNo, event.query);

      yield posts.isEmpty
          ? currentState.copyWith(hasReachedMax: true)
          : SearchLoaded(
              posts: currentState.posts + posts,
              hasReachedMax: false,
            );
    }
    // yield SearchInitial();
  } catch (e) {
    yield SearchError(e.toString());
  }
}
```

**Comment by felangel** [comment]
@heshaShawky it will happen automatically. Internally bloc ignores duplicate states so by having a lastUpdated property which always changes you're always going to have a different search loaded state.

**Comment by heshaShawky** [comment]
> @heshaShawky it will happen automatically you don't have to do anything. Internally bloc ignores duplicate states so by having a lastUpdated property which always changes you're always going to have a different search loaded state.

It's not working for me! now behavior is after the first search ( the first letter in the field ) starts adding the new search results at the end of the data list because of this snippet ( after first search the state changes to be SearchLoaded ) and I added the last updated data.  

So it's kinda navigation on searching :"D not deleteing the old one and reset when new search triggered
```dart 
    if (currentState is SearchLoaded) {
      final List<Post> posts =
          await postsRepostiry.search(event.pageNo, event.query);

      yield posts.isEmpty
          ? currentState.copyWith(hasReachedMax: true)
          : SearchLoaded(
              posts: currentState.posts + posts,
              hasReachedMax: false,
            );
    }
 
```

**Comment by heshaShawky** [comment]
I have fixed this by making another event for just navigation beside the searching one, 


**So the final code is:** 
```dart
@override
Stream<SearchState> mapEventToState(
  SearchEvent event,
) async* {
  final currentState = state;

  if (event is SearchPosts) {
    if (event.query.isEmpty) {
      yield SearchInitial();
    } else {
      if ( currentState is SearchInitial && !_hasReachedMax(currentState) ) {
        yield SearchLoading();
        _pageNo = 1;
        try {
          final List<Post> posts = await postsRepostiry.search(_pageNo, event.query);
          yield SearchLoaded(posts: posts, hasReachedMax: false);
        } catch (e) {
          yield SearchError(e.toString());
        }
      }
    }
  } else if (event is SearchNextPageResults) {
    try {
      _pageNo++;
      if (currentState is SearchLoaded) {
        final List<Post> posts = await postsRepostiry.search(_pageNo, event.query);
        yield posts.isEmpty
            ? currentState.copyWith(hasReachedMax: true)
            : SearchLoaded(
                posts: currentState.posts + posts, hasReachedMax: false);
      }
    } catch (e) {
      yield SearchError(e.toString());
    }
  }

}
```
