### ISSUE TITLE
How to control the cancellable debounce in never version of 3.2.0

### ISSUE THREAD

**Issue by newbieflutter** [felangel/bloc#1038]
In the previous version all this while I have been running this function.

```
Future apiVerify(String userEmail, String userPhoneNumber) async {
    /
    var future = verifyRepository.getVerify(userEmail:userEmail,userPhoneNumber: userPhoneNumber).catchError((err) {
      //print("api_bloc:Error is " + err.toString());
      if(err is AuthError){
        //print("Auth error"+err.message);
        errorType =  "AuthError";
        errorMessage = err.message;
      }
      else if(err is UnknownError){
        //print("Auth error"+err.message);
        errorType =  "UnknownError";
        errorMessage = err.message;
      }
      else if(err is Error4xx){
        //print("Auth error"+err.message);
        errorType =  "Error4xx";
        errorMessage = err.message;
      }
      else{
        errorType =  "Error4xx";
        errorMessage = "Generic Error";
      }
      
    });

    cancelableCall = CancelableOperation.fromFuture(future);
    return cancelableCall.valueOrCancellation(null);
  }
```
then I have this function below. I manage to settle all the old depreciation example the dispatch etc but this is where I am stuck now.
```
@override
  Stream<RegisterApiEvent> transformEvents(Stream<RegisterApiEvent> events) {
    return (events as Observable<RegisterApiEvent>)
        // cancel any running
        .asyncMap((event) async {
          await cancelableCall?.cancel();
          return event;
        })
        // means emit this even not faster than once in 420ms
        .debounce(Duration(milliseconds: 50))
        // just log
        .map((s) {
          print(s);
          print("releasing after debounce");
          return s;
        });
  }
```
How to enable the debouncing in the newer version so that it does not cause user to able to keep calling the api ?

**Comment by felangel** [comment]
Hi @newbieflutter 👋
Thanks for opening an issue!

Have you taken a look at https://github.com/felangel/bloc/issues/524#issuecomment-573978217? Also can you please specify the exact version of bloc you’re using? Thanks!

**Comment by newbieflutter** [comment]
Hi Felangel,
                  I am using this version now flutter_bloc: ^3.2.0. I have looked into the comment #524 but its not working it shows error too. For temporary I have commented that part but my bloc is still working. I am not too sure on this lines cancelableCall = CancelableOperation.fromFuture(future);
    return cancelableCall.valueOrCancellation(null);. Actually even that part of the codes are commented still my words are working why ya ?

**Comment by felangel** [comment]
What error does it show?

**Comment by newbieflutter** [comment]
Hi Felangel,
                    I have fixed most of it. I am not too sure on this part.

Stream<RegisterApiState> transformEvents(
    Stream<RegisterApiEvent> events,
    Stream<RegisterApiState> Function(RegisterApiEvent event) next,
  ) {
      final nonDebounceStream =
        events.where((event) => event is! RegisterApiEvent);
      final debounceStream = events
        .where((event) => event is RegisterApiEvent)
        .debounceTime(Duration(milliseconds: 300));
      return super.transformEvents(MergeStream([nonDebounceStream, debounceStream]), next);
  }

I am not too sure on this part. In both part I just put the RegisterApiEvent ? Is that correct cause it seems to refer to some specific event ?

```
 final nonDebounceStream =
        events.where((event) => event is! RegisterApiEvent);
```

 ```
final debounceStream = events
        .where((event) => event is RegisterApiEvent)
        .debounceTime(Duration(milliseconds: 300));
```

**Comment by felangel** [comment]
@newbieflutter yup that looks correct 👍

**Comment by newbieflutter** [comment]
Hi Felangel,
                    I am still not clear the difference between this two lines. How do we decide which event is to be debounce and which does not need debounce ?

```
final nonDebounceStream =
        events.where((event) => event is! RegisterApiEvent);
```
```
final debounceStream = events
       .where((event) => event is RegisterApiEvent)
       .debounceTime(Duration(milliseconds: 300));
```

**Comment by felangel** [comment]
Hi @newbieflutter when you debounce it means you are ignoring those events for a period of time. It's common to debounce events when a user is typing so that you give the user time to stop typing before processing the event. I would highly recommend reading up on [debounceTime](https://rxjs-dev.firebaseapp.com/api/operators/debounceTime) and trying some examples.

In the snippets you've provided, the code is saying, if an Event is not a `RegisterApiEvent` then don't debounce (don't ignore/skip events) but if it is a RegisterApiEvent then when we get a RegisterApiEvent, ignore all consecutive RegisterApiEvents that occur within 300 milliseconds of the initial RegisterApiEvent.

Hope that helps 👍
