### ISSUE TITLE
Remove trailing "_bloc" from name when using IntelliJ IDEA plugin

### ISSUE THREAD

**Issue by anisalibegic** [felangel/bloc#1040]
**Is your feature request related to a problem? Please describe.**
When I'm creating a new bloc using plugin mentioned in the title I often forget that the plugin will add `_bloc` and after creating a bloc named `my_bloc` I will get:

![image](https://user-images.githubusercontent.com/12012869/79116652-5ba8c480-7d89-11ea-9b89-c094b0123209.png)
![image](https://user-images.githubusercontent.com/12012869/79116770-9f9bc980-7d89-11ea-90b8-6dbb64f13d65.png)
![image](https://user-images.githubusercontent.com/12012869/79116823-bfcb8880-7d89-11ea-8081-3adcbed12c5c.png)

**Describe the solution you'd like**
- `my_bloc_bloc.dart` should be `my_bloc.dart`
- `my_bloc_state.dart` should be `my_state.dart`
- `my_bloc_event.dart` should be `my_event.dart`
- `MyBlocBloc` should be `MyBloc`
- `MyBlocState` should be `MyState`
- `MyBlocEvent` should be `MyEvent`

**Comment by theDarkBoffin** [comment]
Hi @anisalibegic, isn't that kind of intuitive?
It would be perfectly fine if you give 'my' as your bloc name instead of 'my_bloc'. Isn't it?

**Comment by anisalibegic** [comment]
I believe it should support both ways, with and without `_bloc`.
- If bloc's name ends with `_bloc` then don't add another one
- If bloc's name does not end with `_bloc` then add one

> It would be perfectly fine if you give 'my' as your bloc name instead of 'my_bloc'. Isn't it?

That's really not the point... I know I can just type `my` but you have to handle other situations, not just one like in this case.

**Comment by theDarkBoffin** [comment]
Yeah, I agree. Although I think one would learn to not add `_bloc` once he knows what goes wrong, it shouldn't be much of a pain to handle the case where the string ends with `_bloc`.
