### ISSUE TITLE
Flutter Listview Data Sync

### ISSUE THREAD

**Issue by FatihAydin52** [felangel/bloc#1045]
I want to listen for updates of items in listview. For example, I list my news in listview. When I open the news details page and add the news back to favorites, it is not seen in the listview that the news are in the favorites. Because the data was not renewed. I don't want to retrieve the data from the server again. How can I solve it to be the best performing? Listening etc.

**Comment by felangel** [comment]
Hi @FatihAydin52 👋 
Thanks for opening an issue!

If the favorites are tracked locally, then you can just update your NewsBloc state to add an `isFavorite` property to each news item. Then you can add a `ItemFavorited` event to the `NewsBloc` from the `NewsDetails` page and update the `isFavorite` property for the correct news item.

Hope that helps!
