### ISSUE TITLE
How to use multi flutter bloc in one page together 

### ISSUE THREAD

**Issue by tazik561** [felangel/bloc#1049]
I am trying to learn and use flutter bloc in other to i created a project that listen to user location and also get some coordinates from service and show this coordinates in map as a marker. So this is myApp method:

```
    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          title: 'Material App',
          home: MultiBlocProvider(providers: [
            BlocProvider<FoursquareBloc>(create: (context) => sl<FoursquareBloc>()), //bloc page to get corrdinate
            BlocProvider<LocationBloc>(create: (context) => sl<LocationBloc>()), // bloc page to listen to change user location
          ], child: HomeFoursquareScreen()),
        );
      }
    }
```

`HomeFoursquareScreen` page shows map:

   ```
  Widget build(BuildContext context) {
        return BlocBuilder<LocationBloc, LocationState>(builder: (context, state) {
          if (state is LocationLoadingState) {
            return Center(child: CircularProgressIndicator());
          } else if (state is LocationLoadedState) {
            print("LocationLoadedState");
            intMapCoordinate =
                LatLng(state.location.latitude, state.location.longitude);
          } else if (state is UserLocationListeningState) {
            _controller.move(
                LatLng(state.location.latitude, state.location.longitude), 15.0);
          }
          return FlutterMap(
            mapController: _controller,
            options: MapOptions(
              center: intMapCoordinate,
              zoom: 13.0,
            ),
            layers: [
              TileLayerOptions(
                  urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
                  subdomains: ['a', 'b', 'c']),
            ],
          );
        });
      }
```

I am confused because i don't know how could i use `FoursquareBloc` to get coordinates to showing as a marker in the map?

This is `LocationBloc`

```
    class LocationBloc extends Bloc<LocationEvent, LocationState> {
      var location = Location();
      StreamSubscription<LocationData> _locationSubscription;
      LocationData currentLocation;
      @override
      LocationState get initialState => LocationLoadingState();
    
      @override
      Stream<LocationState> mapEventToState(
        LocationEvent event,
      ) async* {
        if (event is GetCurrentLocation) {
          yield* _mapToGetCurrentLocationState();
        } else if (event is StartListeningForLiveLocation) {
          yield* _mapToStartListeningUserLocation();
        }else if (event is AddLiveUserLocation) {
          yield UserLocationListeningState(event.location);
        }
        
      }
```

and this is `FoursquareBloc`:

```
    class FoursquareBloc extends Bloc<FoursquareEvent, FoursquareState> {
      final FoursquareRepository repo;
      FoursquareBloc(this.repo);
    
      @override
      FoursquareState get initialState => Empty();
    
      @override
      Stream<FoursquareState> mapEventToState(
        FoursquareEvent event,
      ) async* {
        if (event is GetVenuesByUserEvent) {
          yield Loading();
          try {
            final result = await repo.getVenuesByUser(event.lat, event.lng);
            yield Loaded(result);
          } on Exception catch (e) {
            yield Error(e.toString());
          }
        }
      }
    }

```
Does it again call  BlocBuilder<FoursquareBlo> under `BlocBuilder<LocationBloc, LocationState>(builder: (context, state)` or i have to call `FoursquareBlo` inside LocationBloc by using LocationBloc constructor?

**Comment by felangel** [comment]
Hi @tazik561 👋 
Thanks for opening an issue!

You can use a BlocBuilder to re-render the map with a correct marker location whenever the location changes. Why do you need `FoursquareBloc` to render a marker based on location? Doesn't your `LocationBloc` already have the location as part of its state?

It would be helpful if you could put together a sample application which illustrates the problem you're facing so that I can reproduce your issue locally and provide more valuable suggestions/feedback.

In general, if you have `BlocBuilder<LocationBloc, LocationState>(...)` then the builder will only be called for state changes within `LocationBloc`. If you also want to react to state changes in `FoursquareBloc`, then you'd need to add another `BlocBuilder<FoursquareBloc, FoursquareState>(...)`.

Hope that helps 👍

**Comment by tazik561** [comment]
LocationBloc just using to get user's geo location and show user location on the map but FoursquareBloc connected to the `"https://api.foursquare.com` server and get some coordination base on user location .
After that i want to show Those coordinates as a marker on map.
In addition to this issue, I want t o show a horizontal list view on a map according   Those coordinates.
look this image : https://pasteboard.co/J3YfG9Q.png
I want to make like this image.
It is general to hide a widget according state? 

for example when the coordinates not received by bloc, I hide the list view blow the image  and when the coordinates fetched and the state changed I visible list and show data?

**Comment by felangel** [comment]
@tazik561 you can render different widgets based on the state of you `FourSquareBloc` like:

```dart
@override
Widget build(BuildContext context) {
  return BlocBuilder<LocationBloc, LocationState>(
    builder: (context, locationState) {
      if (locationState is LocationLoadingState) {
        return const Center(child: CircularProgressIndicator());
      } else if (locationState is LocationLoadedState) {
        return _MyMap(locationState.location);
      } else {
        return const Text('oops...something went wrong);
      }
    },
  );
}

class _MyMap extends StatelessWidget {
  const _MyMap({Key key, @required this.location}) : super(key: key);

  final Location location;

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<FourSquareBloc, FourSquareState>(
      builder: (context, foursquareState) {
        // here you have access to the location from `LocationBloc`
        // as well as the foursquareState from `FourSquareBloc`
        // and you can return a correctly configured `FlutterMap`.
        return FlutterMap(...);
      }
    );
  },
)
```

Also, if you are going to execute side-effects like `_controller.move(...)`, those should be done using `BlocListener` instead of `BlocBuilder.

Hope that helps 👍

**Comment by tazik561** [comment]
Thank you .

**Comment by felangel** [comment]
You can use a BlocListener and if the state is an Error use showDialog to show an alert.

**Comment by tazik561** [comment]
Thanks, but when we added  map in LocationLoadedState ,every time LocationLoadedState changed whole the map is recreated .it is normal or there is a solution?
