### ISSUE TITLE
Error: No named parameter with the name 'seedValue'.

### ISSUE THREAD

**Issue by MorLightJ** [felangel/bloc#106]
**I downloaded the "flutter_weather" example from here.And  run "flutter packages get", I got an error after I run "flutter run"**

_flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following _CompileTimeError was thrown attaching to the render tree:
flutter: 'package:bloc/src/bloc.dart': error: line 24 pos 44:
flutter: file:///Users/xxxxx/flutter/.pub-cache/hosted/pub.dartlang.org/bloc-0.7.8/lib/src/bloc.dart:24:44:
flutter: Error: No named parameter with the name 'seedValue'.
flutter:     _stateSubject = BehaviorSubject<State>(seedValue: initialState);
flutter:                                            ^^^^^^^^^
flutter:     _stateSubject = BehaviorSubject<State>(seedValue: initialState);

**I don't understand what  this problem means. Someone who knows??  Please help me**

**Comment by dhar619** [comment]
Hey @MorLightJ, just now took a clone and it works like charm. Worth to check by doing a `flutter clean` and get packages again. Also check the bloc package path in `pubspec.yaml` file 
`flutter_bloc:
    path: ../../packages/flutter_bloc`
My bloc package version in external libraries when I get packages is `bloc-0.9.3`.
Hope these findings may help you. Cheers!

**Comment by MorLightJ** [comment]
@dhar619 I ran "flutter clean"，and get packages again. The same error..
How can I upgrade the bloc version at this path "file:///Users/xxxxx/flutter/.pub-cache/hosted/pub.dartlang.org/bloc-0.7.8/lib/src/bloc.dart:24:44:" ?

**Comment by dhar619** [comment]
@MorLightJ I am new to flutter mate, still digging on it. My path is `flutter_bloc: path: ../../packages/flutter_bloc` The package came from the repo https://github.com/felangel/bloc/tree/master/packages/flutter_bloc

**Comment by felangel** [comment]
@MorLightJ try deleting your .packages and pubspec.lock and then running flutter packages get.

Let me know if that helps.

**Comment by Ogiwara-CostlierRain464** [comment]
Same issue, works on my mac, but not in CI.

**Comment by felangel** [comment]
@Ogiwara-CostlierRain464 did you try running flutter clean first?

**Comment by Ogiwara-CostlierRain464** [comment]
Does `flutter clean` step is required for CI?

**Comment by felangel** [comment]
I'm just going to publish an update of flutter_bloc and angular_bloc that forces the latest bloc version which should solve everyone's problems. Give me 5 mins and it should be ready.

**Comment by Ogiwara-CostlierRain464** [comment]
By adding `bloc: ^0.9.3` to pubspec.yaml, it works!

**Comment by felangel** [comment]
@Ogiwara-CostlierRain464 yeah something weird is happening with the pubspec version resolution. flutter bloc requires bloc ^0.9.0 which should take the latest 0.9.x but it seems like it's not working as expected for some people.

**Comment by Ogiwara-CostlierRain464** [comment]
So I was using `flutter_bloc: ^0.6.2`,and
local machine was using `bloc-0.9.3`but CI was using other version of bloc.

**Comment by felangel** [comment]
Please update to the latest version of `flutter_bloc` and `angular_bloc` and things should be back to normal.

```yaml
  dependencies:
    flutter_bloc: ^0.6.3
```

```yaml
  dependencies:
    angular_bloc: ^0.4.3
```

**Comment by felangel** [comment]
@MorLightJ can everyone please confirm that things are working? I'll keep this open until then.

**Comment by Ogiwara-CostlierRain464** [comment]
I'm running CI at [here](https://app.bitrise.io/build/66f9ab40b147a794)

**Comment by Ogiwara-CostlierRain464** [comment]
...and also at [here](https://dev.azure.com/yushiogiwara/penmark-app/_build/results?buildId=36)

(former is building android on Bitrise, latter is building ios on Azure Pileline)

**Comment by dhar619** [comment]
@felangel works like a charm at my end. Thanks! 👍

**Comment by Ogiwara-CostlierRain464** [comment]
It's working, Thanks!👍

**Comment by felangel** [comment]
Closing this for now @MorLightJ if you're still having trouble just let me know! 👍

**Comment by MorLightJ** [comment]
Thanks, It works.
