### ISSUE TITLE
Test bloc with debounce time in transformEvents 

### ISSUE THREAD

**Issue by caiogranero** [felangel/bloc#1061]
Hi :)

I followed the pattern in [firebase login tutorial](https://bloclibrary.dev/#/flutterfirebaselogintutorial?id=login-bloc) and now i'm trying to test my bloc.

I override the transformEvents with this method:

```
@override
  Stream<AppointmentTypeFormState> transformEvents(Stream<AppointmentTypeFormEvent> events,
      Stream<AppointmentTypeFormState> Function(AppointmentTypeFormEvent) next) {
    final nonDebounceStream = events.where((event) {
      return (event is! NameChanged && event is! DurationChanged);
    });
    final debounceStream = events.where((event) {
      return (event is NameChanged || event is DurationChanged);
    }).debounceTime(Duration(milliseconds: 300));

    return super.transformEvents(
      nonDebounceStream.mergeWith([debounceStream]),
      next,
    );
  }
``` 

and i make my test like this but i got error, the events NameChanged and DurationChanged are not processed before Save() has being called:

```
blocTest(
  'should submit the form',
  build: () async {
    return AppointmentTypeFormBloc()
      ..add(NameChanged(name: "Consulta"))
      ..add(DurationChanged(duration: Duration(hours: 1)));
      ..add(DescriptionChanged(description: "Alguma descrição para o atendimento"));
      ..add(PriceChanged(price: 200.0));
      ..add(VisibleToPatientsChanged(visibleToPatients: true));
      ..add(ReceivementMethodChanged(receivementMethods: [TestEntityHelper.receivementMethod()]));
  },
  act: (bloc) {
    return bloc.add(Save());
  },
  expect: [],
);
```

So i change for this:

```
blocTest(
  'should submit the form',
  build: () async {
    var bloc = AppointmentTypeFormBloc()..add(NameChanged(name: "Consulta"));

    return Future.delayed(Duration(milliseconds: 500), () {
      bloc.add(DurationChanged(duration: Duration(hours: 1)));
      return Future.delayed(Duration(milliseconds: 500), () {
        bloc.add(DescriptionChanged(description: "Alguma descrição para o atendimento"));
        bloc.add(PriceChanged(price: 200.0));
        bloc.add(VisibleToPatientsChanged(visibleToPatients: true));
        bloc.add(ReceivementMethodChanged(receivementMethods: [TestEntityHelper.receivementMethod()]));
        return Future.delayed(Duration(seconds: 2), () => bloc);
      });
    });
  },
  act: (bloc) {
    return bloc.add(Save());
  },
  expect: [],
);
```

Basically i delayed all event because the debounce time in transformEvents override and now it works.

Is there a better way to solve this?

**Comment by felangel** [comment]
Hi @caiogranero 👋 
Thanks for opening an issue!

You can use the `wait` property on `blocTest` to handle this.

```dart
blocTest(
  '...',
  build: () async => AppointmentTypeFormBloc(),
  act: (bloc) => bloc.add(...),
  wait: const Duration(milliseconds: 300),
  expect: [...],
);
```

Hope that helps 👍

**Comment by Valentin-Seehausen** [comment]
Hey @felangel I do not only love your libraries, but I also admire your support. Thanks! :-)

May I use this thread to ask you a question: Why did you decide to use debounce? Would not throttle be better. The user would not need to wait an additional 500ms for the first load event, and also the user would not need to rest for 500ms for the infinite list to load more posts.

**Comment by Valentin-Seehausen** [comment]
And as an answer to this thread, I have to adjust my tests like this. Be aware that this is actually a race condition.

```

    test('should return hasReachedMaximun when receiving an empty list',
        () async {
      emitsExactly(
          newsPostsBloc,
          [
            NewsPostsLoaded(newsPosts: newsPosts1),
            NewsPostsLoaded(newsPosts: newsPosts1 + newsPosts2),
            NewsPostsLoaded(
                newsPosts: newsPosts1 + newsPosts2, hasReachedMax: true),
          ],
          duration: Duration(milliseconds: 3000));
      newsPostsBloc.add(NewsPostsFetch());
      await Future.delayed(const Duration(milliseconds: 501));
      newsPostsBloc.add(NewsPostsFetch());
      await Future.delayed(const Duration(milliseconds: 501));
      newsPostsBloc.add(NewsPostsFetch());
    });
```

**Comment by felangel** [comment]
Hi @Valentin-Seehausen 👋 
You can definitely use `throttle` instead of `debounce` if it makes more sense for the use-case 👍 
Can you please provide a link to a sample app which illustrates the problem you're facing?
Have you tried using [bloc_test](https://pub.dev/packages/bloc_test) with a `wait`?

**Comment by Valentin-Seehausen** [comment]
Hi, sorry I was not precise enough. The above code is working and was a proposed solution.

I have tried `bloc_test` with await, but I don't use `bloc_text`, because it does not have the scope of the other tests, i.e. the variables declared in the `before` statement can't be accessed. Is that expected behaviour?

Also will `bloc_test` wait for several Events to finish after the throttling / debouncing?
