### ISSUE TITLE
Update to rxdart 0.24.0 

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [felangel/bloc#1073]

**Comment by felangel** [comment]
Hi @ThinkDigitalSoftware 👋
Thanks for opening an issue!

rxdart will be removed in the 4.0.0 release which should be out in the next few days 👍

**Comment by ThinkDigitalSoftware** [comment]
Awesome, thanks!

**Comment by felangel** [comment]
@ThinkDigitalSoftware `v4.0.0` is out now 🎉

**Comment by ThinkDigitalSoftware** [comment]
> @ThinkDigitalSoftware `v4.0.0` is out now 🎉 

Awesome! Gonna go check out the Changelog
