### ISSUE TITLE
BlocProviderTree

### ISSUE THREAD

**Issue by felangel** [felangel/bloc#108]
**Is your feature request related to a problem? Please describe.**
```dart
BlocProvider(
  bloc: blocA,
  child: BlocProvider(
    bloc: blocB,
    child: ChildA(),
  ),
);
```
More details in #15 

**Describe the solution you'd like**
```dart
BlocProviderTree(
  blocProviders: [
    BlocProvider<BlocA>(bloc: blocA),
    BlocProvider<BlocB>(bloc: blocB),
  ],
  child: ChildA()
);
```

**Comment by Sh1d0w** [comment]
+1 for the proposed solution. It will make code much more readable, especially if you have a lot of Bloc's that you want to be globally accessible.

**Comment by ThinkDigitalRepair** [comment]
I like it as well

**Comment by Sach97** [comment]
I didn't dive into the code yet but couldn't be possible to take advantages of the new new [multi provider package](https://pub.dartlang.org/packages/provider#multiprovider)? The Consumer part is interesting to as it would permit (I hope) to get the state anywhere down the widget tree without repeating each time BlocProviderOfContext etc.

**Comment by felangel** [comment]
@sach97 thanks for the link. It looks like it will be very similar to the multiprovider.

**Comment by felangel** [comment]
`BlocProviderTree` is now available in `flutter_bloc v0.7.0`

**Comment by craiglabenz** [comment]
I'm possibly being dense, but I'm curious how you'd recommend handling the `BlocBuilder`, which requires specific event and state classes. Consider:

```dart
@override
Widget build(BuildContext context) {
  return BlocProviderTree(
    blocProviders: [
      BlocProvider<AuthenticationBloc>(bloc: authenticationBloc),  // implies `AuthenticationEvent` and `AuthenticationState`
      BlocProvider<OnboardingBloc>(bloc: onboardingBloc), // implies `OnboardingEvent` and `OnboardingState`
    ],
    child: MaterialApp(
      home: BlocBuilder<AuthenticationEvent, AuthenticationState>(
        bloc: authenticationBloc,
        builder: (BuildContext context, AuthenticationState state) {
          if (state is Unauthenticated) {  // an AuthenticationState class, somewhat obviously
            return LoginPage();
          }
          // What about OnboardingEvent instances?
        }
      ),
    ),
  );
}
```

Am I thinking about this correctly?

Thanks so much!

**Comment by felangel** [comment]
Hey @craiglabenz 👋 

In general, I would recommend wrapping the UI that depends on a particular bloc state in a BlocBuilder. If a part of the UI depends on state from multiple blocs you can either have nested BlocBuilders or you can have a new bloc which composes the states from the two blocs into a new state which the presentation layer would consume via a single BlocBuilder. Hope that makes sense and great question! 👍

**Comment by craiglabenz** [comment]
Thanks @felangel. Thanks for that - so much of Flutter makes obvious sense, but I've been leaning on lots of tutorials to get a sense of how to correctly glue all the different pages together. Lots of those tutorials have a single global piece of routing, which I was representing in my snippet above. I think my question is mostly about how to use `flutter_bloc` to handle when a user swaps to a completely different part of the app (like, for example, finishing onboarding and entering the main app area). There are so countless isolated examples of logging in or interacting with some data or whatever else, but rarely two completely isolated parts of an app in a single example, with some structural glue code also demonstrated.

Anyway, thanks for your answer! I'm going to take a stab at wiring up some structural navigation code with your answer in mind :smile:

**Comment by felangel** [comment]
@craiglabenz I think the closest example of a complete app with "structural glue" is the [Todos App](https://felangel.github.io/bloc/#/fluttertodostutorial). Let me know if you have any other questions along the way; I'm happy to help 😄

**Comment by SelanDeemantha** [comment]
@felangel,  how can we use multiple bloc in BlocBuilder ? As an example, if I want to render the UI based on sign_in bloc, scrolling_fetching_data bloc and flter bloc status, how can we handle that scenrio, can you provide me a example?

**Comment by RollyPeres** [comment]
@SelanDeemantha you can simply nest multiple `BlocBuilder`s. Although the fact that you need 3 blocs to build some widget means that you're probably not structuring your blocs properly. You might want to re-think your blocs.

**Comment by SelanDeemantha** [comment]
@RollyPeres, ok  I got your point. You mean we should use single bloc for a widget right? Anyway we need to use the user sign in state along the app, so at lest we have to use two blocs together, isn't it?

**Comment by RollyPeres** [comment]
You would usually aim to have a single bloc per feature.
As for the user state you will mostly need that inside other blocs to be able to make requests that depend on the currently signed in user. You can either inject your auth bloc/user bloc in those blocs or you can grab your current user data straight from a user repository. It all depends on how you handle authentication.

**Comment by SelanDeemantha** [comment]
Agreed with you, I think it will be a good solution, I think injecting auth bloc and nested BlocBuilder will solve my issue. If you can provide me an example it will be grateful.

**Comment by RollyPeres** [comment]
You can have a look at the [documentation](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication) on this topic.
