### ISSUE TITLE
Implementing selections from a list in a multi step wizard

### ISSUE THREAD

**Issue by lockykeaney** [felangel/bloc#1083]
This isn't really a bug, but more of a lack of information on how to implement BLoC correctly for my use case. I have been searching for similar examples for months now, but nothing really goes into much more than displaying a widget with the data, or the counter/todo app.

**Use Case**
I am trying to make a multi step wizard. The user starts the wizard, and API fetches a list items and the user selects 1 before moving onwards. The second screen uses the selection from the previous screen to fetch from another API end point create a list of new items to select from. There are a few more steps and at the end the selections are saved to the device.

For each list, the user should select an item and it is highlighted in the list so they can change there mind, then a floating button will add that to the state.

(I have cut down the examples to only account for the first step)

I imagine there are 2 events for each step, a `get` and a `set`. At the moment they are: 

```
class FetchRoutes extends OnboardingEvent {
  List<Object> get props => [];
}
```
Populates the list (works fine, same as the examples)
```
class SelectRoute extends OnboardingEvent {
  final RouteModel selectedRoute;
  const SelectRoute({@required this.selectedRoute})
      : assert(selectedRoute != null);
  @override
  List<Object> get props => [selectedRoute];
}
```

For states I'm starting to get hazier, there is the classic:
```
class RoutesLoaded extends OnboardingState {
  final List<RouteModel> routes;
  const RoutesLoaded({@required this.routes}) : assert(routes != null);
  @override
  List<Object> get props => [routes];
}
```
And I have inital object that I am looking to populate:
```
class OnboardingNewJourney extends OnboardingState {
  final RouteModel selectedRoute;
  final StopModel selectedStop;
  const OnboardingNewJourney({this.selectedRoute, this.selectedStop});
  @override
  List<Object> get props => [selectedRoute, selectedStop];
}
```
The `SelectRoute` event would then update the `selectedRoute` value and I could then use the ID from that in the next step (fetching the stops on that route). I get this idea from web development (React + Redux, vuex)

In the Bloc I have tried to turn this process into a setter like this:
```
if (event is SelectRoute) {
      try {
        // print(event.selectedRoute.routeName);
        OnboardingNewJourney(selectedRoute: event.selectedRoute);
        final List<RouteModel> routes = await ptvRepository.fetchRoutes();
        yield RoutesLoaded(routes: routes);
      } catch (_) {
        yield OnboardingError();
      }
    }
```

Now it gets to where I can't find any good examples or tutorials. 
The event `SelectRoute`,should that yield a whole new state (`RoutesWithSelected`) that returns the the routes and the selected route so it can be displayed properly (with the selection highlighted)? 
Should this be in a StatefulWidget and the Bloc only does that API calls? State is updated on the screen and then added to the device at the end? 
Can the previous state be accessed by the bloc so the API does not have to get shared again? Can state be shared between throughout the bloc?
Should the `OnboardingNewJourney` which holds all the data from the steps be in it's own Bloc?

I realize this is not a bug or a feature request (maybe some more advanced documentation) but I've been pulling my hair out because of this for more than a month now and needed to ask before I gave up and tried something else entirely.

The repo can be found [here](https://github.com/lockykeaney/flutter-ptv) that would give more context to my issue. I have tried so many things and for so long that I don't even know what I'm trying to do anymore.

**Comment by felangel** [comment]
Hi @lockykeaney 👋 
Thanks for opening an issue!

I added a [flutter_wizard](https://github.com/felangel/bloc/tree/master/examples/flutter_wizard) example app to illustrate one way to setup a multi-step wizard.

Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
