### ISSUE TITLE
Using Bloc with a HashMap does not Register a Change

### ISSUE THREAD

**Issue by georgiossalon** [felangel/bloc#1084]
I am writing a scheduling app for employees with Flutter.

For this case, I chose the Bloc architecture and the table_calendar package for Flutter.

In order to assign shifts to the calendar, I need a HashMap<DateTime, List< dynamic> >. The dynamic in my case is a Shift object.

I have already read the Flutter Firestore Todos Tutorial and created a small test project in order to see if the reading of Firestore data is working. For a normal List<Shift> everything is working fine. For a HashMap<DateTime, List<dynamic>> I am stuck with a problem.

When I manually change a property within a shift document in Firebase, the Code does not find a change and thus the app does not update. The App will update the UI only after restarting it.

I have found that the problem lies within the **shifts_state.dart** file (equivalent to todos_state of the tutorial). In particular, at the line  ` List<Object> get props => [shiftsMap];` where the code is compering the current State with next State.

When I am running the code for the List<Shift> case, the code jumps to the **shifts_state.dart** class, where it compares the current with the next state. This all happens after finishing with the **_mapShiftsUpdateToState** method found within the **shifts_bloc.dart**.

When I am running the Map< DateTime, List< Shift>> case, the **shiftsMap** in the **shifts_state.dart** is for the current and next method the falsely the same. I guess there must be a problem with the comparison.

[https://github.com/georgiossalon/schedulingapp](url)

My code can be found in Github under the **bloc_with_map** branch.

**Comment by felangel** [comment]
Hi @georgiossalon 👋 
Thanks for opening an issue!

I believe the problem is your `shiftsMap` is using `DateTime` as a key which does not override `==` and cannot be compared by value.

I opened a [pull request](https://github.com/georgiossalon/schedulingapp/pull/1) to fix this by using a modified `_shiftsMap` which converts the `DateTime` objects into their Iso8601 representation.

Hope that helps 👍

**Comment by georgiossalon** [comment]
Unfortunately, the change did not have any effect.

**Comment by felangel** [comment]
@georgiossalon can you give me steps to reproduce the issue? I wasn’t able to run the app locally so it was difficult for me to debug.

**Comment by georgiossalon** [comment]
@felangel For the case with the map, the code after finishing the **_mapShiftsUpdateToState** method instead of going to the **shifts_state.dart** class, it directly jumps to the **simple_bloc_delegate.dart** class into the **onTransition** method. This does not happen with the non-map case. 

In the non-map case, the code enters the **shifts_state.dart** one more time after finishing with the **_mapShiftsUpdateToState**  method found in the **shifts_bloc.dart** class. At this step the code goes to the following line `List<Object> get props => [shifts];` to compare the states. After the comparison is finished then it jumps to the **simple_bloc_delegate.dart** class into the **onTransition** method and after some more code which is identical the UI gets updated. 

In the end, I chose to use the normal List<Shift> implementation and convert it to a map when I need it. Thus, I do not have to write an unnecessary over-complicated Bloc Map for my calendar that does not properly work.

**Comment by felangel** [comment]
@georgiossalon thanks for the update and glad you found a solution. If you'd like, feel free to share a sample app which reproduced the previous issue with the Map and I'm happy to take a look 👍

**Comment by georgiossalon** [comment]
@felangel sure I would if I knew what you mean. I am pretty new to the developing world so bear with me. The whole code is within the GitHub repository posted above. So what more do I have to do to reproduce the issue?

**Comment by felangel** [comment]
@georgiossalon can you give me steps for how to run your app (I believe I tried running on iOS and it was crashing) as well as steps for once it’s running how to reproduce the issue? Thanks!

**Comment by georgiossalon** [comment]
@felangel If I remember right, the code runs only in android devices. For iOS, I still have to implement it which I did not do yet since I have a Windows PC. Also, you need a Firestore Database to retrieve the data. The .json file providing access to my personal database is intentionally not uploaded. Other than that, I did not do anything special on the setup. Please inform me if I can help you with further info.
