### ISSUE TITLE
No effects to the UI While Keyboard is active

### ISSUE THREAD

**Issue by heshaShawky** [felangel/bloc#1091]
**Describe the bug**
I'm working on a comment section for a blog app! and I made an event for adding a comment, But It's not working as it should be, the current behavior is while the keyboard is active the new comment not showing up, But If  I closed the keyboard after I made the comment the comment appears on the list

**To Reproduce**
The Event: 
```dart
abstract class CommentsEvent extends Equatable {
  const CommentsEvent();

  @override
  List<Object> get props => null;
}

class FetchComments extends CommentsEvent {
  final int articleId;

  FetchComments(this.articleId);
}

class AddComment extends CommentsEvent {
  final String content;

  AddComment(this.content);

  @override
  List<Object> get props => [content];
}
```

The Bloc:
```dart
class CommentsBloc extends Bloc<CommentsEvent, CommentsState> {
  final CommentsRepository commentsRepository;

  CommentsBloc(this.commentsRepository);

  @override
  CommentsState get initialState => CommentsInitial();

  @override
  Stream<CommentsState> mapEventToState(
    CommentsEvent event,
  ) async* {
    final currentState = state;
    
    if (event is FetchComments) {
      try {
        yield CommentsLoading();
        final comments =
            await commentsRepository.getCommentsByArticle(event.articleId);
        yield CommentsLoaded(comments);
      } catch (e) {
        yield CommentsFailure(e.toString());
      }
    }

    if ( event is AddComment ) {
      if ( currentState is CommentsLoaded ) {
        final comments = currentState.comments;
        comments.add(Comment(
          content: event.content,
          createdAt: DateTime.now().toString(),
          user: User(
            id: 1,
            image: null,
            username: 'hesham',
            role: 'admin'
          )
        ));

        yield CommentsLoaded(comments);
      }
    }
  }
}
```
The UI Form
```dart
return Material(
  child: Directionality(
      textDirection: TextDirection.rtl,
      child: TextField(
        decoration: InputDecoration(
            hintText: 'اكتب تعليق...',
            prefixIcon: IconButton(
                icon: FaIcon(FontAwesomeIcons.paperPlane),
                onPressed: () {
                  BlocProvider.of<CommentsBloc>(context)
                      .add(AddComment('This is a comment'));
                }),
            suffixIcon: FaIcon(FontAwesomeIcons.solidComment),
            contentPadding: EdgeInsets.all(10),
            border: OutlineInputBorder(
                borderSide: BorderSide(color: Colors.white))),
      )));
```

**Expected behavior**
The comments list should be updated while the keyboard is active or whatever on the event been triggered

**Comment by felangel** [comment]
Hi @heshaShawky 👋
Thanks for opening an issue!

It looks like the problem is your bloc is mutating (modifying the existing list of comments) rather than creating a new instance.

If you update

```dart
final comments = currentState.comments;
```

to

```dart
final comments = List.from(currentState.comments);
```

I think you’ll find the problem will be resolved.

Let me know if that helps 👍

**Comment by heshaShawky** [comment]
I have updated the code as you said and pops an error
```bash
type 'List<dynamic>' is not a subtype of type 'List<Comment>'
```
and I fixed the error by putting type to list
```dart
final comments = List<Comment>.from(currentState.comments);
```

The error gone but now the list never changes whatever the keyboard on/off, 

I have logged the comments I noticed that after your modifications that it's adding just the first comment to the list then logging the same results.

Before It's adding the data to the list ( been printed on the console ) but the UI not rebuilding after the event been triggered.

**Comment by felangel** [comment]
Can you please share the link to the github repo? I’m happy to take a look and open a PR with fixes.

**Comment by heshaShawky** [comment]
Here a sample ( [repo](https://github.com/heshaShawky/Adding-new-item-to-the-list-issue-repository) ) I made with the exact problem I have. 

Click on the button **add a comment** The UI not going to rebuild too. 

But the new comment has been added to list if you took a look on the console as I'm printing the comments list on the console every time the event been triggered ( By pressing the button )

**Comment by RollyPeres** [comment]
`yield CommentsLoaded([...currentState.comments, Comment(...)]);`

**Comment by heshaShawky** [comment]
> `yield CommentsLoaded([...currentState.comments, Comment(...)]);`

it worked thanks for the answer and the explaining.

**Comment by heshaShawky** [comment]
> `yield CommentsLoaded([...currentState.comments, Comment(...)]);`
> 
> I've opened a PR with the fix: [heshaShawky/Adding-new-item-to-the-list-issue-repository#1](https://github.com/heshaShawky/Adding-new-item-to-the-list-issue-repository/pull/1)
> As a general rule please stay away from mutating existing state and create new objects.

I'm facing again the same problem, how do I change the data inside the state without this issue happen again.

In my situation now I'm trying to map/edit the list of posts if I like one of them update the array, I know that map makes a new array, but I can't think of another way to do it.

So what is best practice in this? 

```dart
if (event is LikePost) {
  if ( currentState is PostsLoaded ) {
    

    yield currentState.copyWith(posts: [...currentState.posts.map((post) {
      if (post.id == event.articleId) {
        post.isLiked = true;
        print(post)
      }

      return post;
    }).toList()]);
  }
} 
```

**Comment by felangel** [comment]
@heshaShawky you can do something like:

```dart
yield currentState.copyWith(
  posts: posts.map(
    (post) => post.id == event.articleId ? post.copyWith(liked: true) : post,
  ),
);
```

Hope that helps 👍
