### ISSUE TITLE
Update website version and Docs

### ISSUE THREAD

**Issue by jeanluc243** [felangel/bloc#1098]
**Describe the bug**
Update flutter Bloc version on [https://bloclibrary.dev/](https://bloclibrary.dev/), actual version is 4.0.0
- also add new features Docs and how to use it

**Comment by felangel** [comment]
Hi @jeanluc243 👋
Thanks for opening an issue!

I believe the docs should all be updated and you might just be loading a cached version. Can you try refreshing/cleaning cache and let me know if that helps?

Thanks!

**Comment by jeanluc243** [comment]
It works... Extremely thanks

Le lun. 27 avr. 2020 à 15:14, Felix Angelov <notifications@github.com> a
écrit :
