### ISSUE TITLE
How to create a new instance of bloc so that events are fired again?

### ISSUE THREAD

**Issue by rakeshh025** [felangel/bloc#1099]
Hey @felangel , I'm a huge fan of your library and I suggest this to everyone who works in Flutter. This may be a silly question. Kindly excuse me, if so. I want to initialize bloc instance everytime a tap event event occurs.

**To Reproduce**
I have developed a sample app to reproduce the issue. Here's the [link](https://github.com/rakeshh025/flutterBlocFiring) to the repo
1. Launch the app
2. You will see 2 bottom navigation bar items. 
3. Tap on second item in bottom nav (the one with star icon)
4. A loading indicator will be shown on the UI and then some dummy data will be populated on the UI.
5. Tap on first item again.
6. Tap on the second item in the bottom nav again. Now I want to load the page completely from the beginning. (from loading etc.). But mapEventToState is not firing again. 

**Expected behavior**
I want to load the page completely from the beginning  on tapping the second item in the bottom nav bar
 
Please help.

Code snippet :

```
class HomeScreen extends StatefulWidget {
  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  int currentIndex = 0;
  final GlobalKey<NavigatorState> summaryTabNavKey = GlobalKey<NavigatorState>();
  final GlobalKey<NavigatorState> favoritesTabNavKey = GlobalKey<NavigatorState>();

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
        tabBar: CupertinoTabBar(
          activeColor: Colors.orange,
          inactiveColor: Colors.white,
          backgroundColor: Colors.blue,
          items: <BottomNavigationBarItem>[
            BottomNavigationBarItem(
              icon: Icon(Icons.home),
            ),
            BottomNavigationBarItem(
              icon: Icon(Icons.star_border),
            ),
          ],
          onTap: (index) {
            // back home only if not switching tab
            //if(currentIndex == index) {
            switch (index) {
              case 0:
                summaryTabNavKey.currentState.popUntil((r) => r.isFirst);
                break;
              case 1:
                favoritesTabNavKey.currentState.popUntil((r) => r.isFirst);
                break;
            }
            //}
            currentIndex = index;

          },
        ),
        tabBuilder: (BuildContext context, int index) {
          return CupertinoTabView(builder: (BuildContext context) {
            switch (index) {
              case 0:
                return CupertinoTabView(
                  navigatorKey: summaryTabNavKey,
                  builder: (BuildContext context) {
                    return Summary();
                  },
                );
                break;
              case 1:
                return CupertinoTabView(
                  navigatorKey: favoritesTabNavKey,
                  builder: (BuildContext context) {
                    return BlocProvider<FavouritesBloc>(
                      create: (BuildContext context) =>
                      FavouritesBloc()..add(UserReachesFavouritesPageEvent(noOfItems:2,pageNumber: 1)),
                      child: FavouritesPage(),
                    );
                  },
                );
                break;
            }
            return Container();
          });
        });
  }
}

```

**Comment by felangel** [comment]
Hi @rakeshh025 👋 
Thanks for opening an issue!

I believe the issue is the `FavoritesPage` and `Summary` are not unmounted when you change tabs so the `create` will not be invoked again. In this case, I would recommend lifting the BlocProvider up higher and calling add in the `onTap` of `CupertinoTabBar`.

Let me know if that helps 👍

**Comment by rakeshh025** [comment]
@felangel , like how? Can you please provide the code snippet?

**Comment by felangel** [comment]
@rakeshh025 I've opened a [pull request](https://github.com/rakeshh025/flutterBlocFiring/pull/1) with a fix. Hope that helps 👍

**Comment by rakeshh025** [comment]
@felangel That works like a charm! Thanks :)

**Comment by rakeshh025** [comment]
@felangel , How to do it if it's a MultiBlocProvider? The below throws an exception :

return MultiBlocProvider(
                      providers: <BlocProvider>[
                        BlocProvider.value(
                        value: favouritesBloc,
                        child: FavouritesPage(),),
                        BlocProvider<ScrolleventnotifierBloc>(
                          create: (BuildContext context) =>
                              ScrolleventnotifierBloc(),
                        ),
                      ],
                      child: FavouritesPage()),
                    );

**Comment by RollyPeres** [comment]
@rakeshh025 remove the child with FavoritesPage from `BlocProvider.value`, the child needs to be passed to `MultiBlocProvider` as you're doing below.

**Comment by rakeshh025** [comment]
@RollyPeres When I did so and try to access Bloc in favorites page, it throws exception.

**Comment by RollyPeres** [comment]
You mind sharing a link to a repo showcasing your issue @rakeshh025 ?

**Comment by embashbaz** [comment]
I am new to this library but here is my question and use case. Is it possible to create a blueprint for injecting depencies and then, just having a simpler way of creating a brand new instance of a bloc without manually passing the dependencies again.

My use case is, I have a list and every item widget need to fetch data to display, they all send the same type of event and consume the same type of state. I tought the behaviour of BlocProvider.of<BlocX>(context).add(EventA()) should allow one to create a new instance but it actually get the instance attached to the global context.
