### ISSUE TITLE
Need lifecycle on bloc

### ISSUE THREAD

**Issue by lyquocnam** [felangel/bloc#11]
hi author, i want to place some components in bloc and dispose them when bloc destroyed.
i hope `initState()` and `dispose()` featured will be support

**Comment by felangel** [comment]
Hi @lyquocnam, the `Bloc` class currently has a `dispose` method that you can override. Regarding `initState` Blocs do not extend `StatefulWidget` so there is no such that as `initState` the closest thing to `initState` is `initialState` which can be overridden to provide the initial state that the bloc will return to the presentation layer. Does this answer your question? Thanks!

**Comment by lyquocnam** [comment]
oh i see, thanks for this help author, nice work !
