### ISSUE TITLE
Direct Navigation vs Route Navigation

### ISSUE THREAD

**Issue by csarigumba** [felangel/bloc#1100]
@felangel, thanks for this awesome library! I'd like to ask your feedback for my query below.

I'm confused whether I should implement a `Route navigation` or `Direct navigation` in my application? Below is my sample code.

```
return MaterialApp(
      home: BlocBuilder<AuthenticationBloc, AuthenticationState>(
        builder: (BuildContext context, AuthenticationState state) {
          if (state is AuthenticationUninitialized) {
            return SplashScreen();
          }

          if (state is AuthenticationAuthenticated) {
            return MultiBlocProvider(
              providers: [
                BlocProvider<HomeBloc>(
                  create: (context) => HomeBloc(),
                ),
                BlocProvider<PedometerBloc>(
                  create: (BuildContext context) {
                    return _pedometerBloc..add(PedometerStarted());
                  },
                ),
                BlocProvider<BreakBloc>(
                  create: (BuildContext context) {
                    return _breakBloc;
                  },
                ),
              ],
              child: HomePage(),
            );
          }

          if (state is AuthenticationUnauthenticated) {
            return LoginScreen(userRepository: widget.userRepository);
          }

          if (state is AuthenticationLoading) {
            return LoadingScreen();
          }

          return SplashScreen();
        },
      ),
      routes: {
        '/notification': (context) => NotificationScreen(),
        '/break': (context) {
          return BlocProvider.value(value: _breakBloc, child: BreakScreen());
        },
      },
    );
  }
```

Basically, the application that I'm building has the following pages.

* Login (authenticate so that it can access home screen)
* Home (able to access different page (notification, settings page, etc.)

Please advice and again thank you for this awesome library!

**Comment by felangel** [comment]
Hi @csarigumba 👋 
Thanks for opening an issue!

In this case, I would recommend going with a route based approach. I highly recommend taking a look at this [example](https://github.com/felangel/fresh/tree/master/example) for inspiration.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by paktalin** [comment]
Hi, @felangel ! I was also wondering about the same question and discover that your link is no longer available. Could you fix it please? 🙂
