### ISSUE TITLE
How to show total length of items in the cart, on different screens ?

### ISSUE THREAD

**Issue by Rammehar** [felangel/bloc#1105]
Hello felangel, 
I follow your shopping cart example to create a Courses Shopping App.
I have list of courses of my home page. 
on click on the course, the course detail screen will open and there a button ADD TO Cart is available to add the course in the cart. 

Only Authenticated user can see his/her cart.
I don't find any example, how to show the length of selected courses on every screen ?
Should I trigger CardLoaded event on every screen. 
I am attaching my codes. any help will be highly appreciated.
thank you.

here is my code of cart Bloc

https://github.com/Rammehar/fluttershoppingapp.git

![image](https://user-images.githubusercontent.com/8978743/80528547-bc541600-89b3-11ea-9cf4-3a7cd18663c1.png)

![image](https://user-images.githubusercontent.com/8978743/80528465-96c70c80-89b3-11ea-9c5f-eca1029324e2.png)
![image](https://user-images.githubusercontent.com/8978743/80528595-d130a980-89b3-11ea-808d-ed7ec781ae72.png)

**Comment by heshaShawky** [comment]
You just on each screen write your `BlocBuilder<BLOC, STATE>` and the `state.data.length` within.

**Comment by felangel** [comment]
Hi @Rammehar 👋 
Thanks for opening an issue!

As @heshaShawky pointed out, you can just wrap the shopping cart icon widget in a BlocBuilder like:

```dart
BlocBuilder<CartBloc, CartState>(
  builder: (context, state) {
    // here you have access to the cart state so you can check the number of items
    // and return the Icon with the correct badge
 },
)
```

Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to add additional comments/questions and I'm happy to continue the conversation 👍
