### ISSUE TITLE
Conditional Stream Operations for Events

### ISSUE THREAD

**Issue by jensencelestial** [felangel/bloc#1107]
Good Day,

Thank you for creating and maintaining this wonderful library. I have a question about how to implement specific Stream operators based on certain events using `transformEvents`, in the example below:

```dart
@override
Stream<FooState> transformEvents(
  Stream<FooEvent> events,
  Stream<FooState> Function(FooEvent) next,
) {
  return super.transformEvents(
    events.debounce(const Duration(milliseconds: 500)),
    next,
  );
}
```

All events are being debounced, but how to implement it in a way that its only being debounced for certain events, while for the rest you use `switchMap` or similar operators?

Thanks!

**Comment by RollyPeres** [comment]
Hi @jensencelestial !

Thanks for showing interest in this library! ✨

Here's an example of treating events preferentially when dealing with a typeahead search box:

```
 @override
  Stream<Transition<FooEvent, FooState>> transformEvents(
      Stream<FooEvent> events, transitionFn) {
    final defferedEvents = events
        .where((e) => e is FooEvent1 || e is FooEvent2)
        .debounceTime(const Duration(seconds: 2))
        .distinct()
        .switchMap(transitionFn);
    final forwardedEvents = events
        .where((e) => e is! FooEvent1 && e is! FooEvent2)
        .asyncExpand(transitionFn);
    return forwardedEvents.mergeWith([defferedEvents]);
  }
```
Please notice it uses the latest version of bloc, which is `4.0.0`. Hope it gives you a good starting point 👍

**Comment by jensencelestial** [comment]
Thank you! It seems to be approach that I'm looking for.

Will this be applicable to pre `4.0.0` versions, specifically `3.1.0`?. Looks like the method signature of `transformEvents` changed.

**Comment by RollyPeres** [comment]
For pre `4.0.0` you can use:

```
  @override
  Stream<FooState> transformEvents(
    Stream<FooEvent> events,
    Stream<FooState> Function(FooEvent) next,
  ) {
    final deferredEvents = events
        .where((e) => e is FooEvent1 || e is FooEvent2)
        .debounceTime(const Duration(milliseconds: 500))
        .distinct()
        .switchMap(next);

    final forwardedEvents =
        events.where((e) => e is! FooEvent1 && e is! FooEvent2).asyncExpand(next);
    return forwardedEvents.mergeWith([deferredEvents]);
  }

```

**Comment by felangel** [comment]
Thanks so much @RollyPeres for taking the time to answer! 💯 

@jensencelestial closing for now but feel free to comment with any additional questions 👍

**Comment by jensencelestial** [comment]
Thank you very much! Works fine on my end :).
