### ISSUE TITLE
BlocProvider provided bloc is not canceling stream subscription.

### ISSUE THREAD

**Issue by Zedorff** [felangel/bloc#1109]
I've got the main page with bottom navigation.

Each page is a StatefulWidget with my BaseState which extends flutters State.
Each state has a bloc object which is provided in initState method via BlocProvider.of(context).
Each bloc has a StreamController which emits errors from the onError method of a bloc and other places like network response failures etc.
State listens to this stream in initState method and disposes of subscription in dispose method which I guess is the correct behavior.

This issue is that while I'm switching from page to page via bottom navigation, the second time I'm visiting it I'm getting 
`Bad state: Stream has already been listened to.` 

While creating bloc directly in initState like this is totally fine.

  ```
@override
  void initState() {
    super.initState();
    bloc = provideBloc();
    _exceptionSubscription = bloc.exceptionStream.listen(_onException);
    onInitState();
  }

@override
  void dispose() {
    _exceptionSubscription?.cancel();
    bloc.onDispose();
    onDispose();
    super.dispose();
  }
```

Could you please give me an advice of what I'm doing wrong

**Comment by RollyPeres** [comment]
Hello @Zedorff !

You get that error because dart streams are single subscription by default and you're trying to re-subscribe to an already subscribed stream; even though you cancel your subscription, you still can't resubscribe to it.

I also find a bit non-conventional the way you're trying to handle errors with bloc.
With bloc you would usually have the error be reflected in the actual state, the part which concerns the UI that is.

If you're looking for a more unified way of dealing with errors with regards to analytics, logging, etc, I highly recommend having a look at `BlocDelegate` which allows you to do exactly that.

**Comment by Zedorff** [comment]
Hello @RollyPeres !
Thanks for the quick response.

I've come to flutter from Android development, and It's pretty straightforward for me to use such kind of a universal error handling in base classes :)

Thanks for pointing me to BlocDelegate seems like it's a lifesaver in my situation.

**Comment by Zedorff** [comment]
@RollyPeres 
The only one question left is how should I connect BlocDelegate to the UI?
For example for showing a dialog when an error occurs?
Could you please point me to the right direction

**Comment by RollyPeres** [comment]
@Zedorff Glad you found my suggestion helpful.
You can have a look at existing examples at: https://github.com/felangel/bloc/tree/master/examples
I'll point you to an existing one I found now which shows a snackbar when an error occurs: https://github.com/felangel/bloc/blob/393aa72b42f8d343a233cac5d62baef168bede7d/examples/flutter_firebase_login/lib/register/register_form.dart

In bloc the error is reflected in the state itself either as a property or even as a separate class extending the base state class. This choice is made based on your requirements. And this error property/class would contain only what concerns the UI, eg: an error message.
The actual error would be handled by the bloc delegate and would maybe log it somewhere.

**Comment by Zedorff** [comment]
@RollyPeres thanks in advice!

So there is no way to show a dialog with a simple error message in one place across the whole app?
I'm asking this because in my opinion handling error state in each page is pretty boilerplate, so I'm looking for a solution which could show a dialog with an error message when an error occurs in the bloc for the simple errors, but if I need to do something more complex I'm going to use state for sure.

**Comment by Zedorff** [comment]
Got your point :)
Thanks for all your help!
