### ISSUE TITLE
Any example of this BLoC with CRUD operation local DB like SQFlite?

### ISSUE THREAD

**Issue by rrifafauzikomara** [felangel/bloc#1113]
Hi @felangel 

Did you have an example of that?

**Comment by sheriffyusuf** [comment]
Here you go. https://github.com/sheriffyusuf/flutter-playground , don't be concerned about the name of the repository, but it contains a todo_app under the lib folder that contains exactly what you want.

**Comment by georgiossalon** [comment]
The following youtube tutorial helped me: [Database Storage in Flutter using Sqflite](https://youtu.be/E4yRzqChFxY)

**Comment by felangel** [comment]
Hi @rrifafauzikomara 👋 
Thanks for opening an issue!

You can also check out the [todos example](https://github.com/felangel/bloc/tree/master/examples/flutter_todos).

Hope that helps 👍
