### ISSUE TITLE
[Silly Question]

### ISSUE THREAD

**Issue by Gene-Dana** [felangel/bloc#1119]
Hi there! I was just wondering, why do you use _ instead of context?

**Comment by felangel** [comment]
Hi @Gene-Dana 👋 
Thanks for opening an issue!

`_` is convention for when a parameter is not needed.

> Exception: An unused parameter can be named _, __, ___, etc. This happens in things like callbacks where you are passed a value but you don’t need to use it. Giving it a name that consists solely of underscores is the idiomatic way to indicate the value isn’t used.

[Effective Dart Docs](https://dart.dev/guides/language/effective-dart/style#dont-use-a-leading-underscore-for-identifiers-that-arent-private)
