### ISSUE TITLE
Passing a Blocs state to another Bloc

### ISSUE THREAD

**Issue by kieronwiehahn** [felangel/bloc#1123]
Building from your Firebase Login example, I am trying to include a reset password page that on failure returns you back to the login screen that then shows a snack bar saying "Reset Failed"

how do you pass state from one Bloc to another

**Comment by masfranzhuo** [comment]
Maybe you could use BlocListener to listen to the bloc state change in reset password page. If the state if failure for reset password, then you could navigate it back to the login page. In the navigation you could pop screen with argument `Navigator.pop(context, 'Reset Failed');`

**Comment by felangel** [comment]
Hi @kieronwiehahn 👋 
Thanks for opening an issue!

You can handle bloc-to-bloc communication either by directly injecting blocA into blocB as described [here](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication) or by using a BlocListener as @masfranzhuo mentioned to subscribe to `blocA` and notify `blocB` like:

```dart
BlocListener<BlocA, StateA>(
  listener: (context, state) {
    // notify `BlocB` in response to changes in `BlocA`
    context.bloc<BlocB>().add(...);
  },
  child: ...
)
```

Hope that helps 👍

**Comment by kieronwiehahn** [comment]
Thanks Guys. will give it a try 👍
