### ISSUE TITLE
Expect to add webview-based browser example

### ISSUE THREAD

**Issue by jet10000** [felangel/bloc#1126]
Expect an example of a browser based on webview and bloc.

https://pub.dev/packages/webview_flutter

Features include opening URLs, gesture-based forward and backward functions, and some other functions. Similar simplified firefox focus, but not as many tabs as chrome.

https://play.google.com/store/apps/details?id=org.mozilla.focus&hl=en_US

I tried to try, but I don't know how to do it.

**Comment by felangel** [comment]
Hi @jet10000 👋 
Thanks for opening an issue!

I'm not sure I understand the request. Can you please explain how those features are related to bloc? Thanks 👍

**Comment by jet10000** [comment]
I see some examples of bloc in the documentation. I recently wanted to use flutter and bloc to implement a simple webview-based browser. I expect an example to guide me.

**Comment by heshaShawky** [comment]
> I see some examples of bloc in the documentation. I recently wanted to use flutter and bloc to implement a simple webview-based browser. I expect an example to guide me.

This is a UI Matter not related to Bloc pattern ( no logic here it's just a widget ), just add the webview wodget to your widgets tree.

**Comment by heshaShawky** [comment]
> I see some examples of bloc in the documentation. I recently wanted to use flutter and bloc to implement a simple webview-based browser. I expect an example to guide me.

This is a UI Matter not related to Bloc pattern ( no logic here it's just a widget ), just add the webview wodget to your widgets tree.

**Comment by felangel** [comment]
As @heshaShawky I'm not sure I understand how bloc is related to this. The [webview package](https://pub.dev/packages/webview_flutter) handles it all for you.

**Comment by felangel** [comment]
Closing this since it's unclear what the desired outcome of this issue is or how it relates to bloc. Feel free to comment with additional information and I'm happy to continue the conversation 👍
