### ISSUE TITLE
[question] How does hasReachedMax changed its value in example infinite list?

### ISSUE THREAD

**Issue by duomoteng** [felangel/bloc#1127]
Hello, I am working on an app that need to fetch data from dB. I use the code from the example “infinite list”. 

However , I got a is a problem. Although after fetching, the state is in `PostLoaded` but the `circle indicators ` doesn’t not disappear. I tried to debug, I found the reason might be the `hasReachedMax`  doesn’t turn to true, if the posts in my dB is less than 20. I want to solve the bug, but I didn’t find the code that change the `hasReachedMax` to `true`.

I guess it might be this code below, but I failed to understand it. I know that `is` is used to check type, and `&&` means and, but still don’t understand? Can you translate it to me?
```dart
bool _hasReachedMax(PostState state) =>
      state is PostLoaded && state.hasReachedMax;
```

**Comment by felangel** [comment]
Hi @duomoteng 👋 
Thanks for opening an issue!

The code that updates `hasReachedMax` can be found at https://github.com/felangel/bloc/blob/025322c8dc7e54706fc82e4351041feb6463c041/examples/flutter_infinite_list/lib/bloc/post_bloc.dart#L42.

In this case, `hasReachedMax` is set to true if a subsequent page is requested and no results are returned.

Hope that helps! 👍
