### ISSUE TITLE
[Feature Request] Give BlocBuilders a BlocProvider variable to access the bloc it references

### ISSUE THREAD

**Issue by hawkinsjb1** [felangel/bloc#1143]
This isn't a big issue but I often find myself having to store BlocProviders in a variable to avoid typing it out every-time, and when writing logic directly under a BlocBuilder, it feels a bit odd having to call a separate BlocProvider method to access the bloc in question. I am wondering if it would make sense, and feel a bit better, for BlocBuilders to automatically provide a Provider to the bloc it is referencing like so:

`BlocBuilder<BlocA, BlocAState>(builder: (context, state, bloc) {  ... }`

as I find myself creating this 'bloc' variable most of the time anyway. BlocProvider still makes sense to use further down the widget tree, but when I am working directly under the 'builder' function, a provider call seems unnecessary.

**Comment by RollyPeres** [comment]
I think it would make `builder` too verbose.
When tree is properly broken down into widgets, I found most of them won't need the bloc itself.
Most of the time your builder would look like `builder: (_, state, __) { ... }` which is unnecessarily verbose.

**Comment by felangel** [comment]
I agree with @RollyPeres which is why I didn’t include the bloc in the first place. If you really want to minimize lines of code and bloc lookups you can do:

```dart
@override
Widget build(BuildContext context) {
  final myBloc = context.bloc<MyBloc>();
  return BlocBuilder(
    bloc: myBloc,
    builder: (context, state) {...}
  );
}
```

This reduces the number of lookups to one and you have access to the bloc instance.

If you’re going for fewest lines of code:

```dart

@override
Widget build(BuildContext context) {
  final myBloc = context.bloc<MyBloc>();
  return BlocBuilder<MyBloc, MyState>(
    builder: (context, state) {...}
  );
}
```

At the end of the day it’s one line of code to access a bloc and the time complexity is O(1) so I agree with @RollyPeres that it seems odd to force it into builder and listener. It will make the remaining usages of the builder and listener more verbose unnecessarily.

Thoughts?

**Comment by hawkinsjb1** [comment]
I don't disagree that it is simple enough to spend one line of code to store the bloc provider into a variable, and also I am only referring to cases where the builder is NOT explicitly passed a bloc and rather retrieves it from the context (because at this point there hasn't been a need to explicitly create a bloc reference). It just seems like deferring to the context to provide you with a bloc reference which the bloc builder is already retrieving behind-the-scenes is unnecessarily decoupling the relationship between the builder and its bloc in favor of the 'context-provider' concept. 

Again, this isn't an ease of use optimization because as you said things can be handled in one-line and context look-ups are O(1), its more of a 'work-flow' observation that it just feels off having to go back to the context to 'find' the bloc as opposed to referring directly to the BlocBuilder which is all you really care about in the 'builder' function.

Its probably less useful to most other people as I am accessing bloc-level values more-so than most use-cases so I understand that the added verbosity is a net-negative. The only reasonable way this could've been added would be if the builder function supported optional values but oh well i'm just pointing out minor workflow inconveniences in a super polished package.

**Comment by felangel** [comment]
@hawkinsjb1 it's definitely valuable feedback! I'll leave this open for now so we can all continue to think about ways to potentially improve this 👍

**Comment by felangel** [comment]
@hawkinsjb1 closing this for now but feel free to reopen if you have any additional comments/feedback 👍
