### ISSUE TITLE
BlocBuilder is not called when inside of a dynamic list builder

### ISSUE THREAD

**Issue by shamilovtim** [felangel/bloc#1147]
**Describe the bug**
I pass the BlocProvider down from my main method and I can see in my devtools that it's attached. However setting a breakpoint inside the BlocBuilder I see that the inside of it is never called. Not even a `print('test')` will execute inside of my BlocBuilder on initial screen mount. I've tried just about every ticket or article and can't figure out why this is happening. Any help is appreciated! 

Debugging things I've seen:
1. in the bloc  if (event is GetCycles)  does get called (seen via breakpoint)
2. as I step through my breakpoints I see most of the logic inside of the bloc being triggered. just no builder or UI updates.

Provider:
```dart
            return BlocProvider(
              create: (context) => CyclesBloc(HTTPCycleRepository()),
              child: CupertinoTabView(
                builder: (context) => TrendsScreen(),
              ),
            );
```

Screen:
```dart
class TrendsScreenState extends State<TrendsScreen> {
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final cyclesBloc = BlocProvider.of<CyclesBloc>(context)..add(GetCycles());
  }

  @override
  Widget build(context) {
    return SliverSafeArea(
        top: false,
        sliver: SliverList(
          delegate: SliverChildBuilderDelegate(
            (context, index) {
              BlocBuilder<CyclesBloc, CyclesState>(
                builder: (context, state) {
                  print('test');
                  if (state is CyclesInitial) {
                    return buildInitial();
                  } else if (state is CyclesLoading) {
                    return buildLoading();
                  } else if (state is CyclesLoaded) {
                    return Container(
                      color: Color(0xffeaf1f6),
                      child: Column(
                        children: <Widget>[
                          TrendsCyclesChart(state.cycles[index]),
                          SizedBox(height: 12),
                        ],
                      ),
                    );
                  } else if (state is CyclesError) {
                    return Text('There was an error');
                  } else {
                    print('reached end');
                    return Text('Nothing');
                  }
                },
              );
            },
            childCount: 3,
          ),
        ),
      )
    ];
```

Bloc:
```dart
class CyclesBloc extends Bloc<CyclesEvent, CyclesState> {
  final CycleRepository cycleRepository;

  CyclesBloc(this.cycleRepository);

  @override
  CyclesState get initialState => CyclesInitial();

  @override
  Stream<CyclesState> mapEventToState(
    CyclesEvent event,
  ) async* {
    yield CyclesLoading();
    if (event is GetCycles) {
      try {
        final response = await cycleRepository.fetchCycleList();
        final cycleList = CycleList.fromJson(response.data);

        yield CyclesLoaded(cycleList.cycles);
      } on NetworkError {
        yield CyclesError('Couldnt fetch cycles');
      }
    }
  }
}
```

State:
```dart
abstract class CyclesState extends Equatable {
  const CyclesState();
}

class CyclesInitial extends CyclesState {
  const CyclesInitial();

  @override
  List<Object> get props => [];
}

class CyclesLoading extends CyclesState {
  const CyclesLoading();

  @override
  List<Object> get props => [];
}

class CyclesLoaded extends CyclesState {
  final List<Cycle> cycles;
  const CyclesLoaded(this.cycles);

  @override
  List<Object> get props => [cycles];
}

class CyclesError extends CyclesState {
  final String message;
  const CyclesError(this.message);

  @override
  List<Object> get props => [message];
}
```

Event:
```dart
part of 'cycles_bloc.dart';

abstract class CyclesEvent extends Equatable {
  const CyclesEvent();
}

class GetCycles extends CyclesEvent {
  const GetCycles();

  @override
  List<Object> get props => [];
}
```

**Expected behavior**

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

**Additional context**

**Comment by felangel** [comment]
Hi @shamilovtim 👋 
Thanks for opening an issue!

Can you please share a link to a sample app which illustrates the issue you're facing so I can debug it locally? Thanks 👍

**Comment by shamilovtim** [comment]
Hi @felangel. Is there a suggested tool for sharing the code with you? Something similar to Expo Snack maybe?

**Comment by felangel** [comment]
@shamilovtim can you create a github repository?

**Comment by shamilovtim** [comment]
Hey @felangel I figured out what's causing it. My BlocBuilder is in a `SliverList: delegate: SliverChildBuilderDelegate()`. As soon as I moved it out of the SliverList it worked. Do you know what the rule of thumb is for using Bloc with dynamic lists like this? The relevant code is below.

```dart
  List<Widget> buildCycleTab() {
    return [
      SliverSafeArea(
        top: false,
        sliver: SliverList(
          delegate: SliverChildBuilderDelegate(
            (context, index) {
              BlocBuilder<CyclesBloc, CyclesState>(
                builder: (context, state) {
                  print('test');
                  print(state);
                  if (state is CyclesInitial) {
                    return buildInitial();
                  }
                  if (state is CyclesLoading) {
                    return buildLoading();
                  }
                  if (state is CyclesLoaded) {
                    return Container(
                      color: Color(0xffeaf1f6),
                      child: Column(
                        children: <Widget>[
                          TrendsCyclesChart(state.cycles[index]),
                          SizedBox(height: 12),
                        ],
                      ),
                    );
                  } else if (state is CyclesError) {
                    return Text('There was an error');
                  } else {
                    print('reached end');
                    return Text('Nothing');
                  }
                },
              );
            },
            childCount: 3,
          ),
        ),
      )
    ];
  }
```

**Comment by shamilovtim** [comment]
Solution:

Moved BlocBuilder to the top of my build method and put the state into a variable. That way I can use the state elsewhere outside of BlocBuilder. Not sure if I'm going to need setState but haven't noticed if I need it yet. 

```dart
class TrendsScreenState extends State<TrendsScreen> {
  int currentSegment = 0;
  var _state;

  @override
  Widget build(context) {
    return BlocBuilder<CyclesBloc, CyclesState>(
      builder: (context, state) {
        _state = state;
       return ...
  }
...
}
```

**Comment by felangel** [comment]
Glad you figured it out but I think it’s worth noting you shouldn’t need to store state as a private member variable. Just wrap the parts of you build that need access to state in a BlocBuilder and you should be good 👍

**Comment by shamilovtim** [comment]
@felangel That's what I'd normally do but in this instance but the issue here is 1) Slivers and 2) individual build methods make this difficult. Are you suggesting using multiple blocbuilders and/or passing state around as a parameter rather than storing it in variable?

**Comment by felangel** [comment]
You can either have one BlocBuilder at the root of your build method and you don’t need to track state internally in the widget or if you want more fine-grain control only wrap the widgets that need to update in their own BlocBuilders (you can use conditions as well to optimize how often they rebuild).

**Comment by shamilovtim** [comment]
Hey @felangel could you clarify something for me? I wasn't sure if you were implying in your second to last message that storing the state of a Bloc in a variable of a stateful widget is a bad thing:

> you shouldn’t need to store state as a private member variable

Is there any particular reason for that? Because it stops us from using pure functions?

I've moved forward by passing the state around as a parameter. e.g.:

BlocBuilder((state)
BuildWidgetA((state)
  BuildWidgetA1((state)
    BuildWidgetA1-1(state)
)
)

The reason I didn't want to keep using BlocBuilders everywhere is that it would require me to test the state everywhere to see if it's loaded. This would result in a lot of extra and useless code in deeply nested methods. If I pass it as a parameter then I know in a deeply nested method that it could never be an errorstate or a loadingstate because the parent method that called it was already a reaction to a loadedstate. 

In other tools I am not used to passing parameters deeply like this. Usually I would use a provider, or in the case of Redux I can get the stateful variable anywhere I want with `useSelector`. Is there no simple way using BloC of simply reaching out to the global state and saying "give me this property" without all of the parameter drilling?

**Comment by felangel** [comment]
Hey @shamilovtim you can definitely achieve that but you'll likely need to refactor your state. Rather than having something like:

```dart
abstract class MyState {}
class Initial extends MyState {}
class Loading extends MyState {}
class Success extends MyState {
  Success(this.data);
  final data;
}
```

You can represent your state like:

```dart
enum Status { initial, loading, success, failure }
class MyState {
  MyState({this.data, this.status = Status.initial});
  final data;
  final Status status;
}
```

Then you can access the data via

```dart
context.bloc<MyBloc>().state.data;
```

Hope that helps 👍

**Comment by shamilovtim** [comment]
Thanks for the explanation Felix I think I'm going to refactor to use the internal variable. Looks very clean.
