### ISSUE TITLE
Loading Dailog when page initialization / Save

### ISSUE THREAD

**Issue by GaneshSingaravelu** [felangel/bloc#1149]
Hi!

I have a screen, which shows a button. If I press it, an async job is started. During this time, I want to show an AlertDialog with a spinning wheel. If that job is finished, i will dismiss the dialog or show some errors. Here is my (simplified) code:

     Scaffold(
        body: Container(
          child: BlocListener<FactorystateBloc, FactorystateState>(
            bloc: factoryBloc,
            listener: (context, state) {              
              if (state.isError) {
                CustomProgressBar.hide();
                _alertMessage.errorMessage(
                    context, "Error", "this is error message");
              }
            },
            child: BlocBuilder<FactorystateBloc, FactorystateState>(
                bloc: factoryBloc,
                builder: (context, state) {
                  if (state.isLoading) {
                    return  CustomProgressBar.show("Loading...", context);     
                  }
                  if(state.isSave){
                       return CustomProgressBar.show("Saving...", context);           
                  } 
                  else {
                    return body(context, state);
                  }
                }),
          ),
        ),
      )

The build will be triggered when the job status is changed or if there are errors. So far, so good, but if I run this code, I got this error message:

This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.

I/flutter (13152): The widget on which setState() or markNeedsBuild() was called was:
I/flutter (13152):   Overlay-[LabeledGlobalKey<OverlayState>#85b0d]
I/flutter (13152): The widget which was currently being built when the offending call was made was:
I/flutter (13152):   BlocBuilder<FactorystateBloc, FactorystateState>
I/flutter (13152): setState() or markNeedsBuild() called during build.

So, the repaint of the screen will be overlap somehow. I am not sure how to fix this. It feels like I am using this completely wrong. What is the preferred way to handle this kind of interaction (trigger "long" running task, show progress indicator and possible errors)?

Thanks,
Ganesh

**Comment by felangel** [comment]
Hi @GaneshSingaravelu 👋 
Thanks for opening an issue!

You should move the side-effects (showing the overlay) into BlocListener as well. Also in this case you can use a `BlocConsumer` instead of nesting a `BlocBuilder` inside a `BlocListener`.

```dart
Scaffold(
  body: BlocConsumer<FactorystateBloc, FactorystateState>(
    listener: (context, state) {
      if (state.isError) {
        CustomProgressBar.hide();
        _alertMessage.errorMessage(context, "Error", "this is error message");
      } else if (state.isSave) {
        CustomProgressBar.show("Saving...", context);
      } else if (state.isLoading) {
        CustomProgressBar.show("Loading...", context);
      }
    },
    builder: body,
)
```

Hope that helps 👍
