### ISSUE TITLE
Bloc Dispatch Stops Working Once API returns an Error 

### ISSUE THREAD

**Issue by adewaleafolabi** [felangel/bloc#115]
**Describe the bug**
Bloc does not dispatch event once the API Client returns an error. When dispatch method is called no error is reported and mapState is never fired

Git URL ``` https://github.com/adewaleafolabi/portfolio ```

**Comment by felangel** [comment]
@adewaleafolabi I took a look and I'm not sure how to reproduce the issue you're having. Can you please give more detailed steps for how to reproduce the issue?

I was able to force an exception and the bloc seems to be working fine.
<img width="523" alt="screen shot 2019-02-26 at 6 21 32 pm" src="https://user-images.githubusercontent.com/8855632/53456271-65d7fa00-39f3-11e9-854f-5b033be2adc5.png">

**Comment by adewaleafolabi** [comment]
To reproduce the error:
I supplied a wrong password, the API then returns a 401. Clicking on the login button again is supposed to dispatch a login event, but this time no request to the API is made, no call to mapEventState is called either. Thank you

**Comment by felangel** [comment]
@adewaleafolabi ah so I wasn’t supposed to use the mock backend?

**Comment by adewaleafolabi** [comment]
@felangel I've added a screen cast to show the error, also I've modified the mock_api to return a 401 on login. The event doesn't fire the second time after the first error.

[![capturebf02b81a4ea90898.gif](https://s2.gifyu.com/images/capturebf02b81a4ea90898.gif)](https://gifyu.com/image/3x6x)

**Comment by felangel** [comment]
@adewaleafolabi I was able to reproduce this only when running in debug mode (`webdev serve`) however running in release mode (`webdev serve --release`) behaves as expected.

**Comment by adewaleafolabi** [comment]
This helps running webdev serve with the release flag does work. I'd raise this issue with dartdevc Thank you

**Comment by KanybekMomukeyev** [comment]
Same here, after fail API, mapEventToState not even called.
