### ISSUE TITLE
BlocListener is not listening for states in widget test case, when using await or Future in Bloc file.

### ISSUE THREAD

**Issue by ashishkumart** [felangel/bloc#1150]
**Describe the bug**
I am using a `BlocListener` and `BlocBuilder` in a simple registration page, on click of a button I am adding an event `CreateAccountPressedEvent(data)`. In bloc file, I am delaying and yielding the state `AccountCreatedState`. 

The problem is that the test case failed when I am using `await Future.delayed(Duration(milliseconds: 200));` in the bloc. If I remove this statement then the test case passed and the BlocListener called as well.

I also used `await tester.runAsync(() async { // test });` but Listener didn't get called.

**Expected behavior**
BlocListener should be called so that the code written for the particular state could be covered in the test coverage.

**Screenshots**
_Bloc File_
![main_bloc](https://user-images.githubusercontent.com/26221013/81477035-f71b4100-9232-11ea-843d-73b10d57462d.jpg)

_Widget Test Case_
![image](https://user-images.githubusercontent.com/26221013/81477097-7741a680-9233-11ea-990a-218d1174e9a0.png)

_UI/Page_
![image](https://user-images.githubusercontent.com/26221013/81477144-c091f600-9233-11ea-88b2-52fb8d275f3e.png)

**Logs **
`Testing started at 8:30 PM ...
C:\flutter\bin\flutter.bat --no-color test --machine --plain-name "calls listener on single state change" test\widget_test.dart
Shell: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
Shell: The following TestFailure object was thrown running a test (but after the test had completed):
Shell:   Expected: <1>
Shell:   Actual: <0>
Shell: 
Shell: When the exception was thrown, this was the stack:
Shell: #0      fail (package:test_api/src/frontend/expect.dart:153:30)
Shell: #1      _expect (package:test_api/src/frontend/expect.dart:147:3)
Shell: #2      expect (package:test_api/src/frontend/expect.dart:59:3)
Shell: #3      expect (package:flutter_test/src/widget_tester.dart:234:3)
Shell: #4      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///C:/Users/TiwariA/Documents/projects/widget_test_demo/test/widget_test.dart:87:11)
Shell: (elided 12 frames from package dart:async and package stack_trace)
Shell: ════════════════════════════════════════════════════════════════════════════════════════════════════
`

**Flutter Doctor**
C:\Users\TiwariA\Documents\projects\widget_test_demo>flutter doctor -v
[√] Flutter (Channel unknown, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17763.1192], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (3 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\TiwariA\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 81.0.4044.129
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!

------------

Please help me with this.
Thank You!

**Comment by felangel** [comment]
Hi @ashishkumart 👋 
Thanks for opening an issue!

Can you please share a link to a sample project which illustrates the issue so that I can run/debug it locally? Thanks 👍

**Comment by ashishkumart** [comment]
Hi @felangel,
Thanks for the quick reply!
Here is the link of the repository https://github.com/ashishkumart/widgetTestDemo

Thank You

**Comment by felangel** [comment]
Hey @ashishkumart 👋 
I opened a [pull request](https://github.com/ashishkumart/widgetTestDemo/pull/1) with a fix. You just needed to add an `await tester.pump();` in order to allow a frame for the widget to settle.

Hope that helps 👍

**Comment by ashishkumart** [comment]
Thanks @felangel 
I think you have run the another test case "renders child properly".

I am stuck in the last one that is "calls listener on single state change".
The issue is that listener is not getting called and I am not able to test the code that is written in side listener.

**Comment by ashishkumart** [comment]
Hi @felangel 👋,

Please let me know if anything required from my end, because it's very important to me to cover UI code, that is written/called in the listener.

Thank You

**Comment by felangel** [comment]
@ashishkumart sorry for the delay and for misunderstanding! I opened another [pull request](https://github.com/ashishkumart/widgetTestDemo/pull/2) to fix the last test. Hope that helps 👍
