### ISSUE TITLE
Add an example to the doc showing how to consume a graphql api with flutter_bloc

### ISSUE THREAD

**Issue by lexprimost** [felangel/bloc#1153]
**Is your feature request related to a problem? Please describe.**
i have a graphql api that i want to consume with my flutter app using flutter_bloc. i considered using the graphql_flutter. https://pub.dev/packages/graphql_flutter. but there a lot ui based boilerplate that i cant manage to imagine how to implement with flutter_bloc. 

**Describe the solution you'd like**
if you can add in your free time a simple example on how to consume a simple graphql api like you did with firebase with flutter_bloc, that will be super!.
 
**Additional context**
You can use any existant graphql api such https://api.graphql.jobs/ to illustrate your example

**Comment by nixis-institute** [comment]
Hi i'm new to bloc but i have tried implemented graphql api with bloc

first create a connection with api

```dart
import 'dart:async';
import 'package:flutter/cupertino.dart';
import 'package:graphql_flutter/graphql_flutter.dart';

final server_url = "http://127.0.0.1:8000";
final HttpLink httpLink = HttpLink(
  uri: server_url+'/graphql/',
);
GraphQLClient clientToQuery() {
  return GraphQLClient(
    cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
    link: httpLink as Link,
  );
}

```
we'll called this connection in our repository file as below


```dart

import 'dart:async';

import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:app_name/Graphql/Queries.dart';
import 'package:app_name/Graphql/services.dart';
import 'package:app_name/models/productModel.dart';



class SubProductRepository{

  GraphQLClient client = clientToQuery();
  
  Future<List<SubProductModel>> getSubProductByRepository(String id) async {
      QueryResult result = await client.query(
        QueryOptions(
          documentNode: gql(getProductByParentId),
          variables: {
            "id":id
          }
        )
      );

    if(!result.hasException){

      // from here you can write your own logic 

      var data = result.data["productByParentId"]["edges"];
      List<ProductImage> img=[];
      
      List<SubProductModel> prdModelList=[];
      Map e = new Map();
      
      
      for(int i=0;i<data.length;i++)
      {
        img=[];
        data[i]["node"]["productimagesSet"]["edges"].forEach((e)=>{
            img.add(
              ProductImage(
                e["node"]["id"],
                e["node"]["largeImage"], 
                e["node"]["normalImage"], 
                e["node"]["thumbnailImage"]
                
                )
            )
        });

        if(e.containsKey(data[i]["node"]["size"]))
        {
          e[data[i]["node"]["size"]].add(
            SubProduct(data[i]["node"]["id"], 
            "", 
            data[i]["node"]["listPrice"], 
            data[i]["node"]["mrp"],
            data[i]["node"]["instock"], 
            data[i]["node"]["qty"],
            img,
            data[i]["node"]["size"], 
            data[i]["node"]["color"])
          );
        }
        else{
          e[data[i]["node"]["size"]] = [
            SubProduct(data[i]["node"]["id"], 
            "", 
            data[i]["node"]["listPrice"], 
            data[i]["node"]["mrp"],
            data[i]["node"]["instock"], 
            data[i]["node"]["qty"],
            img,
            data[i]["node"]["size"], 
            data[i]["node"]["color"])
          ];
        }

      }

      e.forEach((key,value)=>{
        prdModelList.add(
          SubProductModel(
            size: key,
            product: value
          )
        )
      });

      prdModelList;
      return prdModelList;
    }

  }
}
```

here is my query

```graphql
String getProductByParentId ="""
query x(\$id:ID!){
  productByParentId(id:\$id)
  {
    edges{
      node{
        id
        listPrice
        mrp
        size
        color
        qty
        productimagesSet{
          edges{
            node{
              id
              largeImage
              normalImage
              thumbnailImage
            }
          }
        }
      }
    }
  }
}
""";
```
json response look like below

```json
{
  "data": {
    "productByParentId": {
      "edges": [
        {
          "node": {
            "id": "U3ViUHJvZHVjdE5vZGU6MQ==",
            "listPrice": 800,
            "mrp": 1200,
            "size": "S",
            "color": "#000000",
            "qty": 89,
            "productimagesSet": {
              "edges": [
                {
                  "node": {
                    "id": "SW1hZ2VOb2RlOjQ=",
                    "largeImage": "product/large/SBOF-5265Navy-3.jpg",
                    "normalImage": "product/normal/SBOF-5265Navy-3.jpg",
                    "thumbnailImage": "product/thumbnail/SBOF-5265Navy-3.jpg"
                  }
                }
              ]
            }
          }
        },
        {
          "node": {
            "id": "U3ViUHJvZHVjdE5vZGU6Mg==",
            "listPrice": 600,
            "mrp": 1300,
            "size": "M",
            "color": "#000000",
            "qty": 14,
            "productimagesSet": {
              "edges": [
                {
                  "node": {
                    "id": "SW1hZ2VOb2RlOjU=",
                    "largeImage": "product/large/HP-SH-111-BLK-1-3.jpg",
                    "normalImage": "product/normal/HP-SH-111-BLK-1-3.jpg",
                    "thumbnailImage": "product/thumbnail/HP-SH-111-BLK-1-3.jpg"
                  }
                }
              ]
            }
          }
        },
        {
          "node": {
            "id": "U3ViUHJvZHVjdE5vZGU6Mw==",
            "listPrice": 1000,
            "mrp": 1600,
            "size": "L",
            "color": "#000000",
            "qty": null,
            "productimagesSet": {
              "edges": [
                {
                  "node": {
                    "id": "SW1hZ2VOb2RlOjY=",
                    "largeImage": "product/large/HP-SH-111-BLK-1-3_XMXhPId.jpg",
                    "normalImage": "product/normal/HP-SH-111-BLK-1-3_FGj5hjC.jpg",
                    "thumbnailImage": "product/thumbnail/HP-SH-111-BLK-1-3_M63955T.jpg"
                  }
                }
              ]
            }
          }
        },
        {
          "node": {
            "id": "U3ViUHJvZHVjdE5vZGU6MjI=",
            "listPrice": 100,
            "mrp": 600,
            "size": "S",
            "color": "#808080",
            "qty": 21,
            "productimagesSet": {
              "edges": []
            }
          }
        }
      ]
    }
  }
}

```






my bloc.dart file 
don't confuse with colorPicker and sizePicker it is just a map variable which map color code with color name and size code with size name, such as M mean Medium or S mean Small size

```dart

import 'dart:async';
import 'package:bloc/bloc.dart';
import 'package:flutter/material.dart';
import 'package:graphql_flutter/graphql_flutter.dart';
import 'package:meta/meta.dart';
// import 'package:app_name/BLOC/subproducts_bloc/subproduct_repository.dart';
import 'package:app_name/Graphql/Queries.dart';
import 'package:app_name/Graphql/services.dart';
import 'package:app_name/models/productModel.dart';
import 'repositories.dart';
part 'subproduct_event.dart';
part 'subproduct_state.dart';

class SubproductBloc extends Bloc<SubproductEvent, SubproductState> {
  final SubProductRepository repository;
  SubproductBloc({this.repository});

  @override
  SubproductState get initialState => SubproductInitial();

  @override
  Stream<SubproductState> mapEventToState(SubproductEvent event,) async* {
    var currentState = state;
    if(event is OnSubProducts){
      yield* _mapSubProductLoadedToState(event);
    }

    if(event is OnAddSubProduct){
      if(currentState is LoadSubProduct){

        yield* _mapSubProductAddedToState(event);
      }
      
    }

    // TODO: implement mapEventToState
  }
  Stream<SubproductState> _mapSubProductLoadedToState(event) async* {
      
      try{
        yield SubProductsLoading();
        final product  = await repository.getSubProductByRepository(event.id);
        List<String> _totalSizes=[];
        sizePicker.forEach((k,v)=>{
          _totalSizes.add(k)
        });
      
        product.forEach((element) =>{
        _totalSizes.contains(element.size)==true?_totalSizes.remove(element.size):null
       });


      yield LoadSubProduct(products: product,sizes: _totalSizes);   
      }
      catch(_){
        yield FailureSubProduct();
      }    
  }

  Stream <SubproductState> _mapSubProductAddedToState(event) async*{
        List<String> _totalSizes =[];
        sizePicker.forEach((k,v)=>{
          _totalSizes.add(k)
        });

        final product = await repository.createProduct(event.id,event.size,event.color,event.qty,event.mrp,event.listPrice);
        _totalSizes.remove(event.size);
        
        yield LoadSubProduct(products: (state as LoadSubProduct).products ,sizes:  _totalSizes );
  
  }

}
```

event file 

```dart
part of 'subproduct_bloc.dart';

@immutable
abstract class SubproductEvent {}

class OnSubProducts extends SubproductEvent{
  String id;
  OnSubProducts(this.id);
  @override
  // TODO: implement props
  List<Object> get props => null;
}

class OnAddSubProduct extends SubproductEvent{
  String id;
  String size;
  String color;
  String qty;
  String mrp;
  String listPrice;
  OnAddSubProduct(this.id,this.size,this.color,this.qty,this.mrp,this.listPrice);
  @override
  // TODO: implement props
  List<Object> get props => [null];  
}


```

state file
```dart
part of 'subproduct_bloc.dart';

@immutable
abstract class SubproductState {
  const SubproductState();
}

class SubproductInitial extends SubproductState {}

class SubProductsLoading extends SubproductState{}
class NavigateToPrevious extends SubproductState{}

class FailureSubProduct extends SubproductState{}



class LoadSubProduct extends SubproductState{
  final List<String> sizes;
  final List<SubProductModel> products;

  const LoadSubProduct({
    this.products,
    this.sizes
  });

  @override
  List<Object> get props => [products,sizes];  
}
```

Presentation layer code would be similar as all bloc examples

**Comment by lexprimost** [comment]
hey 

> Hi i'm new to bloc but i have tried implemented graphql api with bloc
> 
> first create a connection with api
> 
> ```dart
> import 'dart:async';
> import 'package:flutter/cupertino.dart';
> import 'package:graphql_flutter/graphql_flutter.dart';
> 
> final server_url = "http://127.0.0.1:8000";
> final HttpLink httpLink = HttpLink(
>   uri: server_url+'/graphql/',
> );
> GraphQLClient clientToQuery() {
>   return GraphQLClient(
>     cache: OptimisticCache(dataIdFromObject: typenameDataIdFromObject),
>     link: httpLink as Link,
>   );
> }
> ```
> 
> we'll called this connection in our repository file as below
> 
> ```dart
> import 'dart:async';
> 
> import 'package:graphql_flutter/graphql_flutter.dart';
> import 'package:app_name/Graphql/Queries.dart';
> import 'package:app_name/Graphql/services.dart';
> import 'package:app_name/models/productModel.dart';
> 
> 
> 
> class SubProductRepository{
> 
>   GraphQLClient client = clientToQuery();
>   
>   Future<List<SubProductModel>> getSubProductByRepository(String id) async {
>       QueryResult result = await client.query(
>         QueryOptions(
>           documentNode: gql(getProductByParentId),
>           variables: {
>             "id":id
>           }
>         )
>       );
> 
>     if(!result.hasException){
> 
>       // from here you can write your own logic 
> 
>       var data = result.data["productByParentId"]["edges"];
>       List<ProductImage> img=[];
>       
>       List<SubProductModel> prdModelList=[];
>       Map e = new Map();
>       
>       
>       for(int i=0;i<data.length;i++)
>       {
>         img=[];
>         data[i]["node"]["productimagesSet"]["edges"].forEach((e)=>{
>             img.add(
>               ProductImage(
>                 e["node"]["id"],
>                 e["node"]["largeImage"], 
>                 e["node"]["normalImage"], 
>                 e["node"]["thumbnailImage"]
>                 
>                 )
>             )
>         });
> 
>         if(e.containsKey(data[i]["node"]["size"]))
>         {
>           e[data[i]["node"]["size"]].add(
>             SubProduct(data[i]["node"]["id"], 
>             "", 
>             data[i]["node"]["listPrice"], 
>             data[i]["node"]["mrp"],
>             data[i]["node"]["instock"], 
>             data[i]["node"]["qty"],
>             img,
>             data[i]["node"]["size"], 
>             data[i]["node"]["color"])
>           );
>         }
>         else{
>           e[data[i]["node"]["size"]] = [
>             SubProduct(data[i]["node"]["id"], 
>             "", 
>             data[i]["node"]["listPrice"], 
>             data[i]["node"]["mrp"],
>             data[i]["node"]["instock"], 
>             data[i]["node"]["qty"],
>             img,
>             data[i]["node"]["size"], 
>             data[i]["node"]["color"])
>           ];
>         }
> 
>       }
> 
>       e.forEach((key,value)=>{
>         prdModelList.add(
>           SubProductModel(
>             size: key,
>             product: value
>           )
>         )
>       });
> 
>       prdModelList;
>       return prdModelList;
>     }
> 
>   }
> }
> ```
> 
> here is my query
> 
> ```graphql
> String getProductByParentId ="""
> query x(\$id:ID!){
>   productByParentId(id:\$id)
>   {
>     edges{
>       node{
>         id
>         listPrice
>         mrp
>         size
>         color
>         qty
>         productimagesSet{
>           edges{
>             node{
>               id
>               largeImage
>               normalImage
>               thumbnailImage
>             }
>           }
>         }
>       }
>     }
>   }
> }
> """;
> ```
> 
> json response look like below
> 
> ```json
> {
>   "data": {
>     "productByParentId": {
>       "edges": [
>         {
>           "node": {
>             "id": "U3ViUHJvZHVjdE5vZGU6MQ==",
>             "listPrice": 800,
>             "mrp": 1200,
>             "size": "S",
>             "color": "#000000",
>             "qty": 89,
>             "productimagesSet": {
>               "edges": [
>                 {
>                   "node": {
>                     "id": "SW1hZ2VOb2RlOjQ=",
>                     "largeImage": "product/large/SBOF-5265Navy-3.jpg",
>                     "normalImage": "product/normal/SBOF-5265Navy-3.jpg",
>                     "thumbnailImage": "product/thumbnail/SBOF-5265Navy-3.jpg"
>                   }
>                 }
>               ]
>             }
>           }
>         },
>         {
>           "node": {
>             "id": "U3ViUHJvZHVjdE5vZGU6Mg==",
>             "listPrice": 600,
>             "mrp": 1300,
>             "size": "M",
>             "color": "#000000",
>             "qty": 14,
>             "productimagesSet": {
>               "edges": [
>                 {
>                   "node": {
>                     "id": "SW1hZ2VOb2RlOjU=",
>                     "largeImage": "product/large/HP-SH-111-BLK-1-3.jpg",
>                     "normalImage": "product/normal/HP-SH-111-BLK-1-3.jpg",
>                     "thumbnailImage": "product/thumbnail/HP-SH-111-BLK-1-3.jpg"
>                   }
>                 }
>               ]
>             }
>           }
>         },
>         {
>           "node": {
>             "id": "U3ViUHJvZHVjdE5vZGU6Mw==",
>             "listPrice": 1000,
>             "mrp": 1600,
>             "size": "L",
>             "color": "#000000",
>             "qty": null,
>             "productimagesSet": {
>               "edges": [
>                 {
>                   "node": {
>                     "id": "SW1hZ2VOb2RlOjY=",
>                     "largeImage": "product/large/HP-SH-111-BLK-1-3_XMXhPId.jpg",
>                     "normalImage": "product/normal/HP-SH-111-BLK-1-3_FGj5hjC.jpg",
>                     "thumbnailImage": "product/thumbnail/HP-SH-111-BLK-1-3_M63955T.jpg"
>                   }
>                 }
>               ]
>             }
>           }
>         },
>         {
>           "node": {
>             "id": "U3ViUHJvZHVjdE5vZGU6MjI=",
>             "listPrice": 100,
>             "mrp": 600,
>             "size": "S",
>             "color": "#808080",
>             "qty": 21,
>             "productimagesSet": {
>               "edges": []
>             }
>           }
>         }
>       ]
>     }
>   }
> }
> ```
> 
> my bloc.dart file
> don't confuse with colorPicker and sizePicker it is just a map variable which map color code with color name and size code with size name, such as M mean Medium or S mean Small size
> 
> ```dart
> import 'dart:async';
> import 'package:bloc/bloc.dart';
> import 'package:flutter/material.dart';
> import 'package:graphql_flutter/graphql_flutter.dart';
> import 'package:meta/meta.dart';
> // import 'package:app_name/BLOC/subproducts_bloc/subproduct_repository.dart';
> import 'package:app_name/Graphql/Queries.dart';
> import 'package:app_name/Graphql/services.dart';
> import 'package:app_name/models/productModel.dart';
> import 'repositories.dart';
> part 'subproduct_event.dart';
> part 'subproduct_state.dart';
> 
> class SubproductBloc extends Bloc<SubproductEvent, SubproductState> {
>   final SubProductRepository repository;
>   SubproductBloc({this.repository});
> 
>   @override
>   SubproductState get initialState => SubproductInitial();
> 
>   @override
>   Stream<SubproductState> mapEventToState(SubproductEvent event,) async* {
>     var currentState = state;
>     if(event is OnSubProducts){
>       yield* _mapSubProductLoadedToState(event);
>     }
> 
>     if(event is OnAddSubProduct){
>       if(currentState is LoadSubProduct){
> 
>         yield* _mapSubProductAddedToState(event);
>       }
>       
>     }
> 
>     // TODO: implement mapEventToState
>   }
>   Stream<SubproductState> _mapSubProductLoadedToState(event) async* {
>       
>       try{
>         yield SubProductsLoading();
>         final product  = await repository.getSubProductByRepository(event.id);
>         List<String> _totalSizes=[];
>         sizePicker.forEach((k,v)=>{
>           _totalSizes.add(k)
>         });
>       
>         product.forEach((element) =>{
>         _totalSizes.contains(element.size)==true?_totalSizes.remove(element.size):null
>        });
> 
> 
>       yield LoadSubProduct(products: product,sizes: _totalSizes);   
>       }
>       catch(_){
>         yield FailureSubProduct();
>       }    
>   }
> 
>   Stream <SubproductState> _mapSubProductAddedToState(event) async*{
>         List<String> _totalSizes =[];
>         sizePicker.forEach((k,v)=>{
>           _totalSizes.add(k)
>         });
> 
>         final product = await repository.createProduct(event.id,event.size,event.color,event.qty,event.mrp,event.listPrice);
>         _totalSizes.remove(event.size);
>         
>         yield LoadSubProduct(products: (state as LoadSubProduct).products ,sizes:  _totalSizes );
>   
>   }
> 
> }
> ```
> 
> event file
> 
> ```dart
> part of 'subproduct_bloc.dart';
> 
> @immutable
> abstract class SubproductEvent {}
> 
> class OnSubProducts extends SubproductEvent{
>   String id;
>   OnSubProducts(this.id);
>   @override
>   // TODO: implement props
>   List<Object> get props => null;
> }
> 
> class OnAddSubProduct extends SubproductEvent{
>   String id;
>   String size;
>   String color;
>   String qty;
>   String mrp;
>   String listPrice;
>   OnAddSubProduct(this.id,this.size,this.color,this.qty,this.mrp,this.listPrice);
>   @override
>   // TODO: implement props
>   List<Object> get props => [null];  
> }
> ```
> 
> state file
> 
> ```dart
> part of 'subproduct_bloc.dart';
> 
> @immutable
> abstract class SubproductState {
>   const SubproductState();
> }
> 
> class SubproductInitial extends SubproductState {}
> 
> class SubProductsLoading extends SubproductState{}
> class NavigateToPrevious extends SubproductState{}
> 
> class FailureSubProduct extends SubproductState{}
> 
> 
> 
> class LoadSubProduct extends SubproductState{
>   final List<String> sizes;
>   final List<SubProductModel> products;
> 
>   const LoadSubProduct({
>     this.products,
>     this.sizes
>   });
> 
>   @override
>   List<Object> get props => [products,sizes];  
> }
> ```
> 
> Presentation layer code would be similar as all bloc examples

hey man thank you very much , this will help me a lot. i appreciate that

Do you have an example for using mutations too?

**Comment by lexprimost** [comment]
hey man thank you very much , this will help me a lot. i appreciate that

Do you have an example for using mutations too?

**Comment by nixis-institute** [comment]
@lexprimost mutate also works in similar way
i also called this function in above example in bloc file with repostory.createProduct(....)

```dart
//query
String createSubProductQuery ="""
mutation x(\$id:ID!,\$size:String!,\$color:String!,\$qty:String!,\$mrp:String!,\$list:String!){
  createSubProduct(id:\$id,size:\$size,color:\$color,qty:\$qty,mrp:\$mrp,listPrice:\$list){
    subProduct{
      id    ,
      mrp  ,  
      listPrice,     
      size,    
      color, 
      qty,   
    }
  }
}
""";




Future<SubProductModel> createProduct(id,size,color,qty,mrp,list) async {
  QueryResult result = await client.mutate(
    MutationOptions(
      documentNode: gql(createSubProductQuery),
       variables: {
         "id":id,
         "mrp":mrp,
         "list":list,
         "color":color,
         "size":size,
         "qty":qty
       },
    )
  );
  if(!result.hasException){
    // here your logic
    var data = result.data["createSubProduct"]["subProduct"];  
    return SubProductModel(
        size: data["size"],
        product: [
          SubProduct(data["id"], 
          "", 
          data["listPrice"], 
          data["mrp"], 
          false,  
          data["qty"], 
          [], 
          data["size"], 
          data["color"]
   )
  }
}
```

i think this would help you

**Comment by lexprimost** [comment]
thank you one more time !

**Comment by felangel** [comment]
@lexprimost added a [basic graphql example](https://github.com/felangel/bloc/tree/master/examples/flutter_graphql_jobs) 👍
