### ISSUE TITLE
Quick question about using BLoC with shared_preferences

### ISSUE THREAD

**Issue by samuelobe** [felangel/bloc#1155]
Hey Felix! First of, I want to thank you for your prompt responses and the work you do for BLoC! But, I have returned with yet another question. My Flutter app currently uses BLoC for dark mode functionality and it works beautifully. I would like to use shared_preferences to save the dark mode setting. Since the initialState getter cannot be async, is there a work around to load my dark mode setting data as soon as the app launches? Thanks in advance.

Here is my code for better context:

```
import 'dart:async';

import 'package:bloc/bloc.dart';
import 'package:flutter/material.dart';

import '../../theme/theme.dart' as theme;

enum ThemeEvent { toggle }

class ThemeBloc extends Bloc<ThemeEvent, ThemeData> {
  @override
  ThemeData get initialState => theme.lightMode;

  @override
  Stream<ThemeData> mapEventToState(ThemeEvent event) async* {
    switch (event) {
      case ThemeEvent.toggle:
        yield state == theme.darkMode ? theme.lightMode : theme.darkMode;
        break;
    }
  }
}
```

**Comment by felangel** [comment]
Hi @samuelobe 👋
Thanks for opening an issue and for the positive feedback!

The initialState must be synchronous so you can have an ThemeLoadInProgress state and in your BlocBuilder if the state is ThemeLoadInProgress show a splash screen or loading indicator.

Another option is to read from shared preferences before calling runApp and injecting the initial theme into the ThemeBloc via constructor.

Yet another option is to use hydrated_bloc and you don’t have to worry about it 😛

Hope that helps 👍

**Comment by samuelobe** [comment]
Awesome! I'll try those. Thanks mate!
