### ISSUE TITLE
Flutter 1.17 and bloc 4.00 update: Transform isn't a valid override

### ISSUE THREAD

**Issue by Luppakorva** [felangel/bloc#1159]
Being a complete novice I can't seem to figure this out. I had: 

`Stream<ActivityEvent> transform(Stream<ActivityEvent> events) {
    return (events as Observable<ActivityEvent>)
        .debounce(Duration(milliseconds: 500));
  }`

In earlier version which worked perfect, however now I'm getting both: 

- Transform not being valid override 
- Observable isn't a type so it can't be used in an 'as' expression

Any help would be much appreciated, at total loss why this happens (have tried to read the change logs but not skilled enough to get it)

**Comment by felangel** [comment]
Hi @Luppakorva 👋 
Thanks for opening an issue!

There are two transforms in v4.0.0 (`transformEvents` and `transformTransitions`).

In your case, you can replace your code with:

```dart
  @override
  Stream<Transition<ActivityEvent, ActivityState>> transformEvents(
    Stream<ActivityEvent> events,
    TransitionFunction<ActivityEvent, ActivityState> transitionFn,
  ) {
    return super.transformEvents(
      events.debounceTime(const Duration(milliseconds: 500)),
      transitionFn,
    );
  }
```

Hope that helps 👍

**Comment by Luppakorva** [comment]
Thank you so much for the quick reply and sorry to bother with a follow up,

events.debounceTime is not playing ball, instead getting:

> error: The method 'debounce' isn't defined for the type 'Stream'.


 
Any chance you could hint me to right direction why this happens?

**Comment by felangel** [comment]
You need to make sure you add rxdart as a dependency and import it.

**Comment by Luppakorva** [comment]
Many many thanks! You saved my night :).
