### ISSUE TITLE
Cannot use WidgetsBindingObserver with stateless widget

### ISSUE THREAD

**Issue by schatekar** [felangel/bloc#1160]
Apologies this is not a bug but a question seeking direction. 

I am having to manage app life cycles and I am following [this official guide](https://flutter.dev/docs/get-started/flutter-for/android-devs#how-do-i-listen-to-android-activity-lifecycle-events). As you can see the example uses a `StatefulWidget` so it has `initState` and `dispose` methods available where `WidgetsBindingObserver` is added and removed respectively. 

Since, the guidelines with Bloc is to use `StatelessWidget` how do we get `WidgetsBindingObserver` to work, especially where do we add and remove observers?

**Comment by RollyPeres** [comment]
Hi @schatekar ! 👋

It is perfectly fine to use a `StatefulWidget`. Bloc recommends using `StatelessWidget`s unless you have some extra UI state to maintain.
