### ISSUE TITLE
BlocProvider udpate value

### ISSUE THREAD

**Issue by kartzhai** [felangel/bloc#1162]
hi team,

sorry i kindly new and like to know how to update the state inside Class without context.
here for example :

class totalearnamountbloc extends Bloc<String, String>{

  @override
  String get initialState => '0';

  @override
  Stream<String> mapEventToState(String totalearnamount) async* {
    yield totalearnamount.toString();
  }
}

class a (){
  BlocProvider.of<totalearnamountbloc>(context).add("Test udpate");
}

on class a will error cause no context there.
please your advice. 
thank you

**Comment by RollyPeres** [comment]
Hi @kartzhai ! 👋

You would need to inject the bloc into your class.

```
class Test {
    Test(Bloc<String, String> bloc): _bloc = bloc;
    final Bloc<String, String> _bloc;

    void addNewText() {
        _bloc.add("Test udpate");
    }
}
```

**Comment by kartzhai** [comment]
i try this but seems not work.

a(Bloc<String,String> totalcashamountbloc): a = totalearnamountbloc ;

class a(){
}

on different dart file and not inside statefull or stateless widget.

**Comment by felangel** [comment]
@kartzhai you need to access the bloc via context and inject it into the class.

Where are you creating an instance of class a in relation to your widget tree?

**Comment by kartzhai** [comment]
ops sorry guys! put on the wrong places. it work but let me try and review several time.
btw i think i have 3-4 bloc to update. then i just need to inject them all inside class right?

**Comment by kartzhai** [comment]
guys sorry, i found some issue again. i like to update the bloc inside abloc class

for example : 

class abloc extends Bloc<List<String>, List<Modal>>{

  abloc (Bloc<String,String> totalcashamountbloc): totalcashamountbloc = totalcashamountbloc;
  Bloc<String, String> totalcashamountbloc;
  
  @override
  // TODO: implement initialState
  List<Modal> get initialState => [];

  @override
  Stream<List<Modal>> mapEventToState(List<String> event) async* {
    // TODO: implement mapEventToState

    List<Modal> list=[];

    try {

      final response = await http.post(xxxxx,
          body: {
          xx
          });
      final data = jsonDecode(response.body);
      if (data.length != 0) {
totalcashamountbloc .add("Test udpate");
      } else {
        
      }
    } catch (e) {
      print("");
      print(e);
    }

    yield ListEODClosing;
  }
}


but i try to create the BlocProvider like below:
        BlocProvider<viewtransactioneodblocbloc>(
          create :(context) => viewtransactioneodblocbloc(),
        ),

the error mention 1 positional argument expected but 0 found,

please your advice

**Comment by RollyPeres** [comment]
Please have a look at [bloc-to-bloc communication](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication)

**Comment by felangel** [comment]
Closing this for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by kartzhai** [comment]
thankyou RollyPeres and felangel. i think need to learn more again.

thanks alot.

**Comment by RollyPeres** [comment]
Don't we all?
