### ISSUE TITLE
How to initial an event on app started 

### ISSUE THREAD

**Issue by heshaShawky** [felangel/bloc#1164]
**Describe the bug**
I'm trying to initiate an event on the app starting to get the dynamic links works fast as I possible, I tried to do it that way but didn't work for me don't know why!! the more weird part is that same way I have approached working with auth bloc and posts bloc too. 

So I don't know what the difference here!  and why the event not been triggered!

```dart
providers: [
  // this is working fine 
  BlocProvider(create: (_) => PostsBloc(PostsRepostiryImpl())..add(FetchPosts())),
  
  // this is not working 
  BlocProvider(create: (_) => ShareBloc(_navigatorKey)..add(OnDynamicLinkInitial()) ),
]
```

I made a sample [here](https://github.com/heshaShawky/Adding-new-item-to-the-list-issue-repository) that the **test_bloc** have the same problem ( the event not triggered )

**Comment by felangel** [comment]
Hi @heshaShawky 👋 
Thanks for opening an issue!

By default, blocs are creating lazily (only if they are requested). As a result, the create will only get called when the bloc is requested via `BlocProvider.of<PostsBloc>(context)`.

If you want the create to be called immediately, you can set `lazy: false` like:

```dart
providers: [
  // this is working fine 
  BlocProvider(create: (_) => PostsBloc(PostsRepostiryImpl())..add(FetchPosts())),
  
  // this is not working 
  BlocProvider(lazy: false, create: (_) => ShareBloc(_navigatorKey)..add(OnDynamicLinkInitial()) ),
]
```

Hope that helps 👍
