### ISSUE TITLE
Listview pagination issue.

### ISSUE THREAD

**Issue by cgowthamanmca** [felangel/bloc#1168]
**Describe the bug**
when using normal mobile pagination correctly working but when using tablet loading issue occurred  can you check below video.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/34183706/81780820-c7ab5380-9514-11ea-8248-ce80625b7de9.gif)

**Comment by felangel** [comment]
Hi @cgowthamanmca 👋 
Thanks for opening an issue!

Thanks for bringing this up. This is likely happening because the content never fills the screen height so the scrolling offset never triggers a fetch event. I'll try to update this shortly 👍

**Comment by carmas123** [comment]
@cgowthamanmca I solve this issue with a simple trick:

Use AfterLayoutMixin ( https://pub.dev/packages/after_layout ) and add this code into 
overrided method: `void afterFirstLayout(BuildContext context);`
`Future.microtask(() => _postBloc..add(PostFetched()));`

the result code is like this:

```
 @override
  void afterFirstLayout(BuildContext context) {
    // Fix bug in n infinite list with less items of page size or with bigger device height
    Future.microtask(() => _postBloc..add(PostFetched()));
  }
```

I hope it will be useful to you

**Comment by felangel** [comment]
This has been fixed in https://github.com/felangel/bloc/commit/069f16b0027bb0d8eacaa84b334bc8b30d686bd8 🎉
