### ISSUE TITLE
Simplify Event / State / Bloc generation

### ISSUE THREAD

**Issue by fvisticot** [felangel/bloc#117]
Each time we need to create a bloc we need:
- create a bloc file to manage the import
- create the event file
- create the state file
- create the bloc file

It would be nice:
- To create the 4 files automatically from a template

Simplify the State generation:
Most of the time the bloc needs  to manage the same kind of State:
- Loading / Success / Failure
How to simplify this work if we have several blocs to manage ?

Simplify the Builder fonction
We always need to make a "IF" with all available state (Loading / Success / Failure)
- Any idea to simplify this code and unify the failure / loading for all blocs
- Using hooks ?

**Comment by felangel** [comment]
@fvisticot I am planning on extending the VSCode extension to generate the files for you and you will also get the snippet generation for the bloc itself. It can also create the scaffold for `mapEventToState` but you will need to provide all of the `Events` in advance.

Regarding the `Loading/Failure/Success` I think this is common but definitely not always going to be the case so I wouldn't want to make assumptions in the template about how the bloc will be used. 

Thoughts?

**Comment by felangel** [comment]
Created #118 to capture the VSCode extension enhancement.
