### ISSUE TITLE
Direct transition to specific state

### ISSUE THREAD

**Issue by MoSamir** [felangel/bloc#1170]
business require sometimes transition to specific state without dispatching event .
as example if user logout ,
authentication bloc can start the process of logging out with server and yiel to the corresponding state
while user information bloc which caches the data locally can , can directly yiel to its initial state without dispatching new event , or disposing the old bloc and recreating it again

**Comment by felangel** [comment]
Hi @MoSamir 👋
Thanks for opening an issue!

I’m not sure I understand the question. You can yield a state immediate without waiting for an asynchronous process to finish.

**Comment by MoSamir** [comment]
@felangel thanks for quick response , 
but my question is more related to something like 
blocInstance.yeild(state) directly from anywhere in the UI or any other layer without the need to dispatch event then handle this event and yeil to the state in mapEventToState

**Comment by felangel** [comment]
@MoSamir that violates the whole paradigm. The only way to update a bloc’s state is by adding an event.

**Comment by MoSamir** [comment]
@felangel  well it make sense for sure ,I was trying to find a way to revert back to previous state without adding additional non-logic events

**Comment by RollyPeres** [comment]
@MoSamir there's also `onTransition` which you can override 🤫

**Comment by felangel** [comment]
@MoSamir reverting to a previous state is logic haha 😛
