### ISSUE TITLE
blocTest emits only one state when overriding transformEvents with switchMap

### ISSUE THREAD

**Issue by mmakmw** [felangel/bloc#1172]
**Describe the bug**
If we override `tranformEvents` in the bloc like this,

```dart
@override
Stream<State> transformEvents(events, next) {
  return events.switchMap(next);
}
```

then `blocTest` always emits only one state.

`tranformEvents` with `switchMap` works correctly and as expected in the real application. We just can't get the tests working.

**Example**

```dart
blocTest(
  'emits TestStateStuffLoaded when TestLoadStuff is added',
  build: () async => TestBloc(useEventsSwitchMap: false),
  act: (bloc) => bloc.add(TestLoadStuff()),
  skip: 0,
  expect: [
    TestStateInitial(),
    TestStateStuffLoaded(Stuff()),
  ],
);
```

This test fails since the result is only one state: `TestStateInitial()`.

The test passes if we do not override `tranformEvents`.

**Additional information**
We have recreated the problem in a small sample app: [flutter_bloc_test_app.zip](https://github.com/felangel/bloc/files/4628596/flutter_bloc_test_app.zip)

Bloc versions: `flutter_bloc: 4.0.0` and `bloc_test: 5.1.2`.

If you need more information please let us know.

Please have a look.

**Comment by felangel** [comment]
Hi @mmakmw 👋 
Thanks for opening an issue!

You need to add a `wait` to your `switchMap` test because with `switchMap` when the bloc is closed, you lost the pending events.

```dart
    blocTest(
      'emits TestStateStuffLoaded when TestLoadStuff is added',
      build: () async => TestBloc(useEventsSwitchMap: true),
      act: (bloc) => bloc.add(TestLoadStuff()),
      skip: 0,
      wait: const Duration(milliseconds: 500),
      expect: [
        TestStateInitial(),
        TestStateStuffLoaded(Stuff()),
      ],
    );
```

Hope that helps 👍
