### ISSUE TITLE
angular_bloc ^4.0.0 seems to be not compatible with angular ^6.0.0-alpha

### ISSUE THREAD

**Issue by charlieaboumoussa** [felangel/bloc#1174]
Resolving dependencies...
Because angular_bloc >=3.0.0-dev.1 depends on angular ^5.3.0 and angular_app depends on angular ^6.0.0-alpha, angular_bloc >=3.0.0-dev.1 is forbidden.
So, because angular_app depends on angular_bloc ^3.0.0, version solving failed.

**Comment by felangel** [comment]
Hi @charlieaboumoussa 👋 
Thanks for opening an issue!

I have published [v5.0.0-dev.1](https://pub.dev/packages/angular_bloc/versions/5.0.0-dev.1) which is compatible with angular v6.0.0-alpha+1. Hope that helps 👍
