### ISSUE TITLE
Calling child bloc from parent

### ISSUE THREAD

**Issue by karthikeyanp307** [felangel/bloc#1179]
**Describe the bug**
In my application with flutter_bloc, I am having tab bar main page that has two tabs loading Screens A and Screen B. Screen A has list of values. I need to filter these values based on user selection for which I am having filter screen attached to the main page as end drawer. When I change this filter and click on apply, the Screen A list needs to be filtered accordingly.  

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Tab bar main page'. This loads 2 tabs - Screen A and Screen B
2. Click on filter in the main page to filter out values in Screen A list
3. On applying the filter, the Filter Screen is unable to call the Screen A bloc event. 
4. Due to which the filter is not getting applied.

**Expected behavior**
Filter need to call the Screen A bloc event without having the Screen A Bloc as singleton. With singleton bloc the screen does not reload while navigating from different screen via navigation menu.

**Screenshots**

**Logs **
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.17.0 at /Applications/Flutter/flutter
    • Framework revision e6b34c2b5c (12 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kpitchai/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone 11 • A7572DAB-CC54-4A89-8855-AAAFEE8CCB6D • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

**Additional context**
As this is going to be like accessing the child bloc from parent bloc, will it be possible. Please share me with the information if there are any to resolve this issue.

**Comment by felangel** [comment]
Hi @karthikeyanp307 👋 
Thanks for opening an issue!

Sounds like you need to adjust the scope of your blocs. The rule of thumb is a bloc should be provided at the closest common ancestor widget of the widgets that need it. In this case, you likely need to lift your bloc above screens A and B so that both screens have access.

Hope that helps 👍

If you're still having trouble, please share a link to a sample app which illustrates the issue and I'm happy to take a look and create a pull request with any suggestions.

**Comment by karthikeyanp307** [comment]
Hi @felangel,

Thanks for your reply. With this do you mean to say the main page bloc should have the functionalities of both the Screen A and Screen B instead of having separate bloc for Screen A and B. Please clarify.

**Comment by felangel** [comment]
No problem! I mean since the filtering of data is a cross cutting concern the state of the filter needs to be lifted higher so that ScreenA and ScreenB have access. This is why it’s not necessarily always 1 bloc per screen. Let me know if that helps 👍

**Comment by karthikeyanp307** [comment]
Hi @felangel ,

Thanks again. Now I tried having common bloc for all the three screens such as,

* Tab View - Main Page --> Main_Page & Main_Form
* Tab 1 - Screen A --> ScreenA_Page & ScreenA_Form
* Tab 2 - Screen B --> ScreenB_Page & ScreenB_Form

* Main_Bloc
* Main_Event
* Main_State

I am using page and form similar to https://github.com/felangel/bloc/tree/master/examples/flutter_login/lib/login and I am providing the bloc to the form from all the pages via,

BlocProvider(
        create: (context) {
          return MainBloc();
        },
        child: Form_Name(),
      )

By doing this functionality works similar to having the individual blocs for each screens.

The filter with end drawer is part of Main Screen. When tried to trigger an event, it's received in the Main_Bloc and state are being called correctly. But the Screen A is not getting changed based on the state change from filter. 

Each of the forms has builds the Widget with,

return BlocListener<LoginBloc, LoginState>(
      listener: (context, state) {},
      child: BlocBuilder<LoginBloc, LoginState>(
             builder: (context, state) {}
      ),
    );

Hope this is clear. Let me know whether handling of blocs in these screens is fine or anything needs to be changed. Do I want to pass the bloc instance from Main Page to the Screen A and Screen B. If so, how to do that ? Please clarify.

Thanks.

**Comment by felangel** [comment]
Hi @karthikeyanp307 it's hard to say without seeing the code. You can provide the bloc instance two ScreenA and ScreenB using a BlocProvider at the nearest common ancestor. I'm going to close this issue for now since I don't feel like I have enough information to give additional recommendations.

Feel free to post a link to a sample application and I'm more than happy to take a look and give more concrete suggestions/feedback 👍

**Comment by karthikeyanp307** [comment]
Hi @felangel - Have shared my sample code in https://github.com/karthikeyanp307/flutter. Please advice regarding filter functionality in home page. Thanks.
