### ISSUE TITLE
VSCode Extension for Bloc Generation

### ISSUE THREAD

**Issue by felangel** [felangel/bloc#118]
**Is your feature request related to a problem? Please describe.**
Currently the VSCode extension for bloc just supports snippets for creating a bloc but it doesn't:
- Create the bloc state file
- Populate the bloc states
- Create the bloc event file
- Populate the bloc events
- Create the bloc file
- Populate the bloc
- Create the bloc barrel
- Populate the bloc barrel (with all exports)

**Describe the solution you'd like**
A full-blown VSCode extension that:
- asks for the bloc name (`Todo`)
- asks for the bloc events (`Add, Remove`)
- asks for the bloc states (`Loading, Loaded, Failure`)

And then generates:
```sh
 bloc
    ├── bloc.dart
    ├── todo_bloc.dart
    ├── todo_event.dart
    └── todo_state.dart
```

```dart
// bloc.dart
export './todo_bloc.dart';
export './todo_event.dart';
export './todo_state.dart';
```

```dart
// todo_bloc.dart

import 'package:bloc/bloc.dart';
import './bloc/bloc.dart';

class TodoBloc extends Bloc<TodoEvent, TodoState> {
  @override
  int get initialState => // TODO: Implement Initial State;

  @override
  Stream<TodoState> mapEventToState(TodoState currentState, TodoEvent event) async* {
    if (event is AddTodoEvent) {
      yield* _mapAddTodoEventToState(currentState, event);
    } else if (event is RemoveTodoEvent) {
      yield* _mapRemoveTodoEventToState(currentState, event);
    } else {
      yield currentState;
    }
  }
  
  Stream<TodoState> _mapAddTodoEventToState(
    TodoState currentState,
    AddTodoEvent event,
  ) async* {
    // TODO: Handle AddTodoEvent
  }

  Stream<TodoState> _mapRemoveTodoEventToState(
    TodoState currentState,
    AddTodoEvent event,
  ) async* {
    // TODO: Handle RemoveTodoEvent
  }
}
```

```dart
// todo_state.dart

abstract class TodoState {}

class LoadingTodoState extends TodoState {}

class LoadedTodoState extends TodoState {}

class FailureTodoState extends TodoState {}

```

```dart
// todo_event.dart

abstract class TodoEvent {}

class AddTodoEvent extends TodoEvent {}

class RemoveTodoEvent extends TodoEvent {}
```

**Additional context**
#117

**Comment by GiancarloCode** [comment]
Hello
Because normally apps have more than 1 bloc, I think the following structure should be generated:

A full-blown VSCode extension that:

- asks for the bloc name (Todo)
- asks for the bloc events (Add, Remove)
- asks for the bloc states (Loading, Loaded, Failure)

And then generates:

```
├── blocs
    ├── blocs.dart
    ├── todo
        ├── todo.dart
        ├── todo_bloc.dart
        ├── todo_event.dart
        └── todo_state.dart
```
```dart
// blocs.dart
export 'todo/todo.dart';
```

**And when we want to add new bloc:**

A full-blown VSCode extension that:

- asks for the bloc name (Theme)
- asks for the bloc events (Change)
- asks for the bloc states (Theme)

And then the blocs folder have:
```
├── blocs
    ├── blocs.dart
    ├── theme
        ├── theme.dart
        ├── theme_bloc.dart
        ├── theme_event.dart
        └── theme_state.dart
    ├── todo
        ├── todo.dart
        ├── todo_bloc.dart
        ├── todo_event.dart
        └── todo_state.dart
```
And add at the end of line of ```blocs.dart```

```dart
// blocs.dart
export 'todo/todo.dart';
export 'theme/theme.dart';
```

___

**Also you recommend use [Equatable](https://pub.dartlang.org/packages/equatable), and I used too, so you can create the next flow**

A full-blown VSCode extension that:

- asks for the bloc name (Todo)
- asks for the bloc events (Add, Remove)
- asks for the bloc states (Loading, Loaded, Failure)
- **asks for use Equatable (Select: Yes/No)**

So now, if the user select Yes for use Equatable, Event and State files are like this:
```dart
// todo_state.dart
import 'package:equatable/equatable.dart';

abstract class TodoState extends Equatable {
  TodoState([List props = const []]) : super(props);
}

class LoadingTodoState extends TodoState {}

class LoadedTodoState extends TodoState {}

class FailureTodoState extends TodoState {}
```
```dart
// todo_event.dart
import 'package:equatable/equatable.dart';

abstract class TodoEvent extends Equatable {
  TodoEvent ([List props = const []]) : super(props);
}

class AddTodoEvent extends TodoEvent {}

class RemoveTodoEvent extends TodoEvent {}
```

___
Thank you and congratulations for your great work with this library.

**Comment by felangel** [comment]
v0.2.0 of the [Bloc VSCode Extension](https://marketplace.visualstudio.com/items?itemName=FelixAngelov.bloc) is published 🎉

**Comment by agordeev** [comment]
@felangel Thanks for the awesome lib and extension. I actually came to this issue from the search. It is unclear to me how the extension could help if I want to have more than one bloc (which is 99.999% of the cases I suppose)? Renaming each file doesn't seem a good solution.
@GiancarloCode suggested a good approach. It'd be great to know your thoughts about that.

**Comment by felangel** [comment]
@agordeev thanks for the input. I would generally recommend structuring your project by feature and not by component type. That way instead of having a blocs directory you would have a bloc directory in the necessary feature directories. Let me know if that makes sense. I have also been meaning to make the vscode extension more configurable via a bloc_options.yaml (or something similar) so that might be a case where we can make this behavior customizable. Thoughts?

**Comment by agordeev** [comment]
@felangel clearly makes sense, thanks for your prompt answer. I didn't think that way (feature-based architecture), will try. 

Wouldn't it be better to have extension settings instead of `bloc_options.yaml`?

**Comment by felangel** [comment]
No problem! Yeah we could do extension settings but it’d be nice to be able to have a configuration per repo so that different projects can have different structures/preferences and to be able to reuse the configuration for the intellij plugin as well 😛
