### ISSUE TITLE
[Question] Single API with multiple blocks?

### ISSUE THREAD

**Issue by matanshukry** [felangel/bloc#1191]
Imagine an app where we have 2 blocs:
- settings regarding the app (such as areas open to the user, etc)
  - API #1: `GET /settings` - return current settings
  - API #2: `PUT /settings` - update settings (admin only)
  - .. other apis ...
- user info (login info)
  - API #1: `GET /user/@me` - get current user
  - ... other apis ..

We then create 2 blocs, 1 for each of the above.

Since both `Settings.#1` and `UserInfo.#1` need to be called when the app start, we have a single API that return both of these calls, such as `GET /init`.

Since the APIs calls are made inside the bloc, which ever bloc you decide to put it in (settings vs user info), you won't be able to access the other one.

How can one implement it then?

**Comment by RollyPeres** [comment]
Hi @matanshukry 👋

If you feel you need to have access to other bloc's state within the first one, have a look at [bloc-to-bloc communication](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication).

**Comment by felangel** [comment]
As always, thanks @RollyPeres for taking the time to answer! 🙏 

@matanshukry closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by matanshukry** [comment]
Sorry for the late response.

@RollyPeres that paged actually helped - I wasn't familiar with it; Thanks!

@felangel thanks for the support as well!
