### ISSUE TITLE
Use the instance of a bloc as a parameter of a function

### ISSUE THREAD

**Issue by spiritualprogrammer1** [felangel/bloc#1194]
I have a problem when I want to use the instance of a block as a parameter to a function:

  ` class SettingPage extends StatefulWidget {
  static const routeName = '/setting';

  @override
  _SettingPageState createState() => _SettingPageState();
}`

`class _SettingPageState extends State<SettingPage> {
  final double fontSize1 = 15;
  final double fontSize2 = 15;
  final double paddingTop1 = 20;
  final double paddingLeft = 20;
  final double iconSize = 23;
  String image ;
  Uint8List bytes ;
  final GlobalKey<ScaffoldState> _scaffoldKey = new GlobalKey<ScaffoldState>();
  User userShared ;
  String bio_shared = null;
  String username_shared = null;
 String contact_shared =  null ;

  getUserShared() async {

    final SharedPreferences prefs =  await SharedPreferences.getInstance();

    dynamic user    = prefs.getString("user") ;
    print("user:$user");
    user =  json.decode(user) ;
    print("userss:$user");
    userShared  = User.fromMap(user);
    print('bytessss: ${userShared.imageUrl}');
     setState(() {
       if(userShared.imageUrl != null) {
        // bytes = base64Decode(userShared.imageUrl);
       }
       if(userShared.contact != null && userShared.contact.length !=0){
         contact_shared = userShared.contact;
       }
       if(userShared.bio != null && userShared.bio.length !=0){
         bio_shared = userShared.bio;
       }
       if(userShared.username != null && userShared.username.length !=0 ){
         username_shared = userShared.username;
       }

       print("username_shared : $username_shared");
     });
  }

  Widget _snackSample(String libelle, Color colors) => SnackBar(
    content: Text(
      "$libelle",
      style: TextStyle(
          color: Colors.black,
          fontSize: 15,
          fontWeight: FontWeight.bold
      ),
      textAlign: TextAlign.center,
    ),
    duration: new Duration(seconds: 4),
    backgroundColor: colors,
  );

  @override
  void initState() {
    // TODO: implement initState
    getUserShared() ;
    print('settings');
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    MediaQueryData mediaQueryData = MediaQuery.of(context);
    ScreenUtil.init(context, height: 760, width: 360, allowFontScaling: false);

    UserBloc _userbloc = BlocProvider.of<UserBloc>(context);

    return  BlocListener<UserBloc,UserState>(
      listener: (context,state) {
        if(state.loading) {
          Center(
            child: CircularProgressIndicator() ,
          ) ;
        } else if(state.isSuccess) {
          /*********En l'imbriquant dans le rappel de addPostFrameCallback, vous dites essentiellement quand le widget a terminé la construction, puis exécutez le code de navigation.*******/
          final bar = _snackSample("Modification effectuée",Colors.cyan);
          _scaffoldKey.currentState.showSnackBar(bar);
        }
        else if(state.isFailure) {
          final bar = _snackSample("une erreur s'est produite",Colors.redAccent);
          _scaffoldKey.currentState.showSnackBar(bar);
        }
        else if(state.isErrorConnectionServer) {
          final bar = _snackSample('Oupss!! Veuillez contactez les administrateurs ',Colors.red);
          _scaffoldKey.currentState.showSnackBar(bar);
        }
      }  ,
      child: BlocProvider.value(value: _userbloc,
      child: Scaffold(
          key: _scaffoldKey,
          backgroundColor: mDark,
          body: SafeArea(
              child: Stack(
                children: <Widget>[
                  Container(
                    color: Colors.white,
                    child: CustomScrollView(
                      slivers: <Widget>[
                        SliverPersistentHeader(
                          pinned: true,
                          floating: true,
                          delegate: MyDynamicHeader(bytes,userShared),
                        ),
                        SliverToBoxAdapter(
                          child: Container(
                            color: Colors.white,
                            height: ScreenUtil().setHeight(220),
                            padding: EdgeInsets.only(top: ScreenUtil().setSp(paddingTop1)),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: <Widget>[
                                Padding(
                                  padding: EdgeInsets.only(left: ScreenUtil().setSp(paddingLeft)),
                                  child: Row(
                                    children: <Widget>[
                                      Text("Compte", style: TextStyle(color: mBlue, fontSize: fontSize2),),
                                    ],
                                  ),
                                ),
                                Spacer(),
                                Column(
                                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: <Widget>[
                                    wid1( contact_shared != null ? "$contact_shared": "Vous n'avez pas de contact", "Touchez pour changer de numéro", (){
                                    }),
                                    myDiv(),
                                    wid1( "@username", username_shared == null ? "Nom d\'utilisateur" : "$username_shared" , (){
                                      Navigator.pushNamed(context, EditOnePage.routeName,  arguments: username_shared );
                                    }),
                                    myDiv(),
                                    wid1("Votre Bio!" ,bio_shared == null ?  "Bio" : "$bio_shared", (){
                                      Navigator.pushNamed(context, BioPage.routeName);
                                    }),
                                  ],
                                )
                              ],
                            ),),
                        ),
                        SliverToBoxAdapter(
                          child: Container(color: Colors.grey.withOpacity(0.2),width: MediaQuery.of(context).size.width,height: ScreenUtil().setHeight(14),),
                        ),
                        SliverToBoxAdapter(
                          child: Container(
                            height: ScreenUtil().setHeight(280),
                            color: Colors.white,
                            padding: EdgeInsets.only(top: ScreenUtil().setSp(paddingTop1)),
                            child: Column(
                              children: <Widget>[
                                Padding(
                                  padding: EdgeInsets.only(left: ScreenUtil().setSp(paddingLeft), bottom: ScreenUtil().setSp(10)),
                                  child: Row(
                                    children: <Widget>[
                                      Text("Paramètres", style: TextStyle(color: mBlue, fontSize: ScreenUtil().setSp(fontSize1)),),
                                    ],
                                  ),
                                ),
                                Expanded(
                                  child: Column(
                                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                                    children: <Widget>[
                                      wid2(Icons.notifications, "Sons et notifications", (){
                                        Navigator.pushNamed(context, SoundNotifPage.routeName);
                                      }),
                                      wid2(Icons.lock, "Confidentialité", (){
                                        Navigator.pushNamed(context, ConfidPage.routeName);
                                      }),
                                      wid2(Icons.pie_chart, "Langue", (){

                                      }),
                                      wid2(Icons.help, "Aide", (){
                                      }),
                                    ],
                                  ),
                                )
                              ],
                            ),
                          ),
                        )
                      ],
                    ),
                  ),
                  Positioned(
                    top: 115,
                    right: 20,
                    child: Container(
                      height: ScreenUtil().setHeight(60),
                      width: ScreenUtil().setWidth(60),
                      child: IconButton(
                          icon: Icon(Icons.add_a_photo, color: mDark,), onPressed: (){
                        show(context,_userbloc);
                      }),
                      decoration: BoxDecoration(
                          shape: BoxShape.circle,
                          color: Colors.white,
                          boxShadow: [BoxShadow(color: mDark, blurRadius: 1, offset: Offset(0, 1))]
                      ),
                    ),
                  )
                ],
              )
          )
      ),),
    );
  }

  Widget wid1(String one, String two, Function fn){
    return Row(
      children: <Widget>[
        Material(
          color: Colors.transparent,
          child: InkWell(
            splashColor: Colors.grey.withOpacity(0.3),
            onTap: (){
              fn();
            },
            child: Container(
                width: MediaQuery.of(context).size.width,
                padding: EdgeInsets.only(top: ScreenUtil().setSp(5), left: ScreenUtil().setSp(paddingLeft)),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Text(one, style: TextStyle(color: Colors.black, fontSize: ScreenUtil().setSp(fontSize1)
                    ),),
                    SizedBox(height: ScreenUtil().setHeight(5),),
                    Text(two, style: TextStyle(color: Colors.grey.withOpacity(0.9), fontSize: ScreenUtil().setSp(fontSize1)),),
                    SizedBox(height: ScreenUtil().setHeight(7),),
                  ],
                )
            ),
          ),
        )
      ],
    );
  }
  Widget wid2(IconData icon, String text, Function fn){
    return  Material(
      color: Colors.transparent,
      child: InkWell(
        splashColor: Colors.grey.withOpacity(0.3),
        onTap: (){
          fn();
        },
        child: Container(
          padding: EdgeInsets.only(top: ScreenUtil().setSp(5), left: ScreenUtil().setSp(paddingLeft)),
          width: MediaQuery.of(context).size.width,
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              Icon(icon, color: Colors.grey.withOpacity(0.9), size: ScreenUtil().setSp(iconSize),),
              SizedBox(width: ScreenUtil().setWidth(20),),
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Padding(
                      padding: EdgeInsets.only(bottom: ScreenUtil().setSp(20)),
                      child: Text(text, style: TextStyle(color: Colors.black, fontSize: ScreenUtil().setSp(15)),),
                    ),
                    myDiv2()
                  ],
                ),
              )
            ],
          ),
        ),
      ),
    );
  }

  Widget wid3(ImageSource ims, IconData icon , String text , UserBloc userBloc ,{ Color color1 = mDark, Color color2 =  Colors.black}){
    return  Material(
      color: Colors.transparent,
      child: InkWell(
        splashColor: Colors.grey.withOpacity(0.3),
        onTap: (){
      getImage(ims,userBloc);
        },
        child: Container(
          padding: EdgeInsets.only(left: ScreenUtil().setWidth(15)),
          alignment: Alignment.centerLeft,
          width: MediaQuery.of(context).size.width,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              Icon(icon, color: color1, size: ScreenUtil().setWidth(23),),
              SizedBox(width: ScreenUtil().setWidth(35),),
              Expanded(
                child:  Container(
                  alignment: Alignment.centerLeft,
                  child: Text(text, style: TextStyle(color: color2, fontSize: 18),),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
  Widget wid4(IconData icon, String text, { Color color1 = mDark, Color color2 =  Colors.black}){
    return  Material(
      color: Colors.transparent,
      child: InkWell(
        splashColor: Colors.grey.withOpacity(0.3),
        onTap: (){

        },
        child: Container(
          padding: EdgeInsets.only(left: ScreenUtil().setWidth(15)),
          alignment: Alignment.centerLeft,
          width: MediaQuery.of(context).size.width,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.start,
            children: <Widget>[
              Icon(icon, color: color1, size: ScreenUtil().setWidth(23),),
              SizedBox(width: ScreenUtil().setWidth(35),),
              Expanded(
                child:  Container(
                  alignment: Alignment.centerLeft,
                  child: Text(text, style: TextStyle(color: color2, fontSize: 18),),
                ),
              )
            ],
          ),
        ),
      ),
    );
  }
  Widget myDiv({double value = 20}){
    return Container(color: Colors.grey.withOpacity(0.6),
      margin: EdgeInsets.only(left: 20),
      height: ScreenUtil().setHeight(0.5), width: MediaQuery.of(context).size.width - value,);
  }
  Widget myDiv2({double value = 20}){
    return Container(color: Colors.grey.withOpacity(0.6),
      height: ScreenUtil().setHeight(0.5),);
  }
  Future getImage(ImageSource source,UserBloc userBloc) async {
    /******on pique une image ici********/
    File nouvelleIMage = await ImagePicker.pickImage(source: source);
    String base64Image = base64Encode(nouvelleIMage.readAsBytesSync());
    print('base64:$base64Image');
    if(nouvelleIMage != null){
      setState (()  {
        bytes = base64Decode(base64Image);
        image  = base64Encode(nouvelleIMage.readAsBytesSync()) ;
      });
    }
    userBloc.add(updatePictureEvent(image: image));

  }
  void show(BuildContext ctx,UserBloc userBloc){
    showModalBottomSheet(context: ctx, builder: (_){
      return GestureDetector(
         onTap: (){},
         behavior: HitTestBehavior.opaque,
         child: Container(
           padding: EdgeInsets.only(bottom: ScreenUtil().setSp(10)),
           decoration: BoxDecoration(
             color: Colors.white,
           ),
           height: MediaQuery.of(context).size.height / 4,
           child: Column(
             children: <Widget>[
               Padding(
                 padding: EdgeInsets.only(left: ScreenUtil().setWidth(15), top: ScreenUtil().setHeight(10), bottom: ScreenUtil().setHeight(20)),
                 child: Row(
                   children: <Widget>[
                     Text("Choose a photo",
                       style: TextStyle(color: Colors.black, fontSize: ScreenUtil().setSp(18), fontWeight: FontWeight.bold, fontFamily: "Popins",),),
                   ],
                 ),
               ),
               Expanded(
                 child: Column(
                   mainAxisAlignment: MainAxisAlignment.spaceBetween,
                   children: <Widget>[
                     Expanded(child:  wid3( ImageSource.camera, Icons.photo_camera, "Take a photo",userBloc)),
//                    Expanded(child:  wid3(ims: ImageSource.gallery,icon:Icons.photo,userBloc: _userbloc,text:  "Upload from gallery" )),
                     Expanded(child:  wid4(Icons.delete_outline,"Remove photo", color1: Colors.red, color2: Colors.red)),
                   ],
                 ),
               )
             ],
           ),
         ),
       );
    });
  }
}`

the following error this product : 
![erros](https://user-images.githubusercontent.com/46725719/82280174-d0b97c00-997d-11ea-9fe5-d05cfa4ea912.PNG)

I want to use an instance of Userbloc in the function  **show (context, _userbloc)**; then use this parameter _userbloc in another function which is in in show (context, _userbloc), the function is **wid3 (ImageSource ims, IconData icon, String text, UserBloc userBloc, {Color color1 = mDark, Color color2 = Colors.black })**

**Comment by RollyPeres** [comment]
Hi @spiritualprogrammer1  👋

I'd advice against passing the bloc as parameter all over the place. Instead you should retrieve the bloc using `context`.

**Comment by felangel** [comment]
Hi @spiritualprogrammer1 👋 
Thanks for opening an issue!

As @RollyPeres mentioned, you should prefer to provide a single instance of a bloc at the closest common ancestor of all widgets that need it and then you can access the bloc from anywhere in the subtree via `context.bloc<UserBloc>()`.

You can also take a look at the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess) for more details and examples 👍
