### ISSUE TITLE
State not rebuilding.

### ISSUE THREAD

**Issue by CoderAssets** [felangel/bloc#1197]
Everything works fine in the starting but QuestionWidget has a button that triggers the GetQuestion event but the QestionWidget is not rebuilt. Or am I doing something wrong here?? I also tried removing equatable.

 Widget build(BuildContext context) {
    return Scaffold(
      body: MultiBlocListener(
        listeners: [
          BlocListener<QuestionholderBloc, QuestionholderState>(
            listener: (context, state) {
              if (state is NoQuestions) {
                _dbbloc.add(GetQuestions());
              } else if (state is HasQuestions) {
                _statusbloc.add(GetQuestion());
              }
            },
          ),
          BlocListener<DatabaseBloc, DatabaseState>(
            listener: (context, state) {
              if (state is Loaded) {
                _statusbloc.add(SetQuestions(questionsToSet: state.questions));
              }
            },
          ),
        ],
        child: BlocBuilder<QuestionholderBloc, QuestionholderState>(
          builder: (context, state) {
            if (state is QuestionLoaded) {
              return QuestionWidget(question: state.question);
            } else {
              return CircularProgressIndicator();
            }
          },
        ),
      ),
    );
  }
}

This is what I get after clicking the button but the widget is not rebuilt.

I/flutter (26863): Instance of 'GetQuestion'
I/flutter (26863): Transition { currentState: Instance of 'QuestionLoaded', event: Instance of 'GetQuestion', nextState: Instance of 'QuestionLoaded' }

**Comment by RollyPeres** [comment]
Hi @CoderAssets 👋

What exactly do you mean by the widget is not rebuilt ? `builder` is not executed or the value of `question` inside `QuestionWidget` doesn't change ?

**Comment by CoderAssets** [comment]
My plan is to rebuild entire QuestionWidget but no visible changes. I guess builder is not exeuted.

**Comment by RollyPeres** [comment]
@CoderAssets can you share a gist or a repo with your issue ?

**Comment by CoderAssets** [comment]
Not using equatable. Is there a chance that the build may not have happened because I was passing the same question. I just realized that the question was the same as the previous one.

**Comment by CoderAssets** [comment]
[https://github.com/CoderAssets/triviaIQ](url)

this is my project

**Comment by RollyPeres** [comment]
That's precisely why I asked you regarding builder or widget value.

Glad you found the problem 👍

**Comment by CoderAssets** [comment]
Thanks for your help.
