### ISSUE TITLE
Using common bloc for different screens

### ISSUE THREAD

**Issue by karthikeyanp307** [felangel/bloc#1205]
Hi @felangel ,

This is related to issue -Using common bloc for different screens #1179. I have shared my sample code in https://github.com/karthikeyanp307/flutter. Please advice regarding filter functionality in home page. Thanks.

**Comment by felangel** [comment]
Hi @karthikeyanp307 👋 
I've opened a [pull request](https://github.com/karthikeyanp307/flutter/pull/1) with the necessary fixes. The main issue was you were creating multiple instances of `HomeBloc` instead of having a single `HomeBloc` at the closest common ancestor of the widgets that needed it.

**Comment by karthikeyanp307** [comment]
Hi @felangel ,

Thanks for sharing me with this info. I will try this and let you know. 

Thanks.

**Comment by karthikeyanp307** [comment]
Hi @felangel ,

Tried this and now the filter functionality works fine. But now I am facing different issue. 

Since both these tabs shares common bloc, the state changes made wrt to one tab is affecting the other. For example, as the pages are build based on state changes made to BlocBuilder there is an issue while rendering the screens. 

Will it be possible to ignore or restrict few state changes at tab level i.e., state changes related to Screen A needed to be restricted to Screen B. Are there any other alternative to resolve this issue. Please help.

Thanks.

**Comment by RollyPeres** [comment]
@karthikeyanp307 you can speicfy a `condition` on each `BlocBuilder` based on the fields you're interested in.
