### ISSUE TITLE
Support for 'MultiBlocConsumer'

### ISSUE THREAD

**Issue by duomoteng** [felangel/bloc#1206]
It is very convenient to have `MultiBlocProvider` and `MultiBlocListener`. It would be better to have `MultiBlocConsumer`.

**Comment by RollyPeres** [comment]
Hi @duomoteng 👋

Thanks for your feature request. This is already discussed in https://github.com/felangel/bloc/issues/538 so please check it out and feel free to post your thoughts there, so we can keep things centralized. Thanks 👍

**Comment by felangel** [comment]
Closing this as a duplicate of #538 as @RollyPeres mentioned 👍
