### ISSUE TITLE
Bloc State 

### ISSUE THREAD

**Issue by GaneshSingaravelu** [felangel/bloc#1212]
Hi, 
I am using single state concept in my project like (your below example). It is very easy and useful for me. But i want to know **What is purpose**, **How to use** and **Where to use** of "copyWith" function. Can you please give me some sample code for that.

Example code:

`
class NewCarState {
  final List<String> brands;
  final String brand;

  final List<String> models;
  final String model;

  final List<String> years;
  final String year;

  const NewCarState({
    @required this.brands,
    @required this.brand,
    @required this.models,
    @required this.model,
    @required this.years,
    @required this.year,
  });

  bool get isComplete => brand != null && model != null && year != null;

  factory NewCarState.initial() => NewCarState(
        brands: <String>[],
        brand: null,
        models: <String>[],
        model: null,
        years: <String>[],
        year: null,
      );

  factory NewCarState.brandsLoading() => NewCarState(
        brands: <String>[],
        brand: null,
        models: <String>[],
        model: null,
        years: <String>[],
        year: null,
      );

  factory NewCarState.brandsLoaded({
    @required List<String> brands,
  }) =>
      NewCarState(
        brands: brands,
        brand: null,
        models: <String>[],
        model: null,
        years: <String>[],
        year: null,
      );

  factory NewCarState.modelsLoading({
    @required List<String> brands,
    @required String brand,
  }) =>
      NewCarState(
        brands: brands,
        brand: brand,
        models: <String>[],
        model: null,
        years: <String>[],
        year: null,
      );

  factory NewCarState.modelsLoaded({
    @required List<String> brands,
    @required String brand,
    @required List<String> models,
  }) =>
      NewCarState(
        brands: brands,
        brand: brand,
        models: models,
        model: null,
        years: <String>[],
        year: null,
      );

  factory NewCarState.yearsLoading({
    @required List<String> brands,
    @required String brand,
    @required List<String> models,
    @required String model,
  }) =>
      NewCarState(
        brands: brands,
        brand: brand,
        models: models,
        model: model,
        years: <String>[],
        year: null,
      );

  factory NewCarState.yearsLoaded({
    @required List<String> brands,
    @required String brand,
    @required List<String> models,
    @required String model,
    @required List<String> years,
  }) =>
      NewCarState(
        brands: brands,
        brand: brand,
        models: models,
        model: model,
        years: years,
        year: null,
      );

  NewCarState copyWith({
    List<String> brands,
    String brand,
    List<String> models,
    String model,
    List<String> years,
    String year,
  }) {
    return NewCarState(
      brands: brands ?? this.brands,
      brand: brand ?? this.brand,
      models: models ?? this.models,
      model: model ?? this.model,
      years: years ?? this.years,
      year: year ?? this.year,
    );
  }
}`

Thanks,
**Ganesh. S**

**Comment by RollyPeres** [comment]
Hi @GaneshSingaravelu 👋

`copyWith` is a pattern used when working with immutable objects; it allows to create a new instance while also preserving unspecified values from an existing instance.

```
yield state.copyWith(brand: 'brand new brand(couldn't help myself)');
```

This will create a new instance of `NewCarState` with your new specified brand AND will also copy all other existing values from the previous instance.

Hope it makes sense 👍
