### ISSUE TITLE
Architecture best practices

### ISSUE THREAD

**Issue by RocketVick** [felangel/bloc#1213]
Hello @felangel!
My question is about blocs and states design.
I have pet-project which contains the following use-cases:
- **first screen**: infinite scroll in which the items contain the **main** information about any Perfomance (name, date, cover image) etc. You can tap the item and then will opened second screen.
- **second screen**: this screen contains **detailing info** about concrete tapped Perfomance. detailing info begin request by id from remote server when user tap item on first screen. also this screen allow to switch "isFavorite" flag.
- **third screen**: this screen contains list of favorite Perfomances. this screen allow remove item from favorite and move to second screen for detail info.

I don't understand how I should design my blocs and states. 
How many blocs I should create for this use-cases?

My last state realization looks like:

abstract class PerfomancesState extends Equatable {
  final DateTime timestamp;

  PerfomancesState() : timestamp = DateTime.now();

  @override
  List<Object> get props => [timestamp];
}

class PerfomancesInitial extends PerfomancesState {}

class PerfomanceDetailsPending extends PerfomancesState {}

class PerfomancesLoadedSuccess extends PerfomancesState {
  final List<Perfomance> perfomances;
  final List<PerfomanceDetails> perfomancesDetails;
  final bool hasReachedMax;
  final bool isLoadingBatch;

  PerfomancesLoadedSuccess(
      {this.perfomances,
      this.perfomancesDetails,
      this.hasReachedMax,
      this.isLoadingBatch});

  PerfomancesLoadedSuccess copyWithNewBatch(List<Perfomance> batch) {
    return copyWith(
        perfomances: this.perfomances + batch, isLoadingBatch: false);
  }

  PerfomancesLoadedSuccess copyWithRefresh(List<Perfomance> perfomances) {
    return PerfomancesLoadedSuccess(
        perfomances: perfomances,
        perfomancesDetails: List<PerfomanceDetails>(),
        hasReachedMax: false,
        isLoadingBatch: false);
  }

  PerfomancesLoadedSuccess copyWithDetails(PerfomanceDetails details) {
    return copyWith(
        perfomancesDetails: List.from(this.perfomancesDetails)..add(details));
  }

  PerfomancesLoadedSuccess copyWith(
      {List<Perfomance> perfomances,
      List<PerfomanceDetails> perfomancesDetails,
      bool hasReachedMax,
      bool isLoadingBatch}) {
    return PerfomancesLoadedSuccess(
        perfomances: perfomances ?? this.perfomances,
        perfomancesDetails: perfomancesDetails ?? this.perfomancesDetails,
        hasReachedMax: hasReachedMax ?? this.hasReachedMax,
        isLoadingBatch: isLoadingBatch ?? this.isLoadingBatch);
  }

  @override
  List<Object> get props => [
        perfomances,
        perfomancesDetails,
        hasReachedMax,
        isLoadingBatch,
        timestamp
      ];

  @override
  String toString() =>
      'PerfomancesLoadedSuccess { perfomances: ${perfomances.length}, details: ${perfomancesDetails.length}, isMax: $hasReachedMax, isLoading: $isLoadingBatch, timestamp: $timestamp }';
}

class PerfomancesLoadFailure extends PerfomancesState {}

**And bloc:**

class PerfomancesBloc extends Bloc<PerfomancesEvent, PerfomancesState> {
  final PerfomanceRepository perfomanceRepository;
  final int batchSize;

  PerfomancesBloc({this.perfomanceRepository, this.batchSize});

  @override
  PerfomancesState get initialState => PerfomancesInitial();

  @override
  Stream<PerfomancesState> mapEventToState(PerfomancesEvent event) async* {
    if (event is FetchBatch)
      yield* _mapFetchBatch(event);
    else if (event is RefreshPerfomances)
      yield* _mapRefreshPerfomances(event);
    else if (event is FetchPerfomanceDetails)
      yield* _mapFetchPerfomanceDetails(event);
    else if (event is SwitchIsFavorite) yield* _mapSwitchIsFavorite(event);
  }

  Stream<PerfomancesState> _mapFetchBatch(FetchBatch event) async* {
    try {
      if (state is PerfomancesInitial) {
        final dtoBatch =
            await perfomanceRepository.fetchBatch(event.startIndex, batchSize);
        yield PerfomancesLoadedSuccess(
            perfomances: dtoBatch.map((e) => Perfomance.fromDto(e)).toList(),
            perfomancesDetails: List<PerfomanceDetails>(),
            hasReachedMax: false,
            isLoadingBatch: false);
        return;
      }
      if (state is PerfomancesLoadedSuccess) {
        yield (state as PerfomancesLoadedSuccess)
            .copyWith(isLoadingBatch: true);
        final batch = await this
            .perfomanceRepository
            .fetchBatch(event.startIndex, batchSize);
        if (batch.isEmpty) {
          yield (state as PerfomancesLoadedSuccess)
              .copyWith(hasReachedMax: true, isLoadingBatch: false);
          return;
        }
        yield (state as PerfomancesLoadedSuccess).copyWithNewBatch(
            batch.map((element) => Perfomance.fromDto(element)).toList());
      }
    } catch (_) {
      yield PerfomancesLoadFailure();
    }
  }

  Stream<PerfomancesState> _mapRefreshPerfomances(
      RefreshPerfomances event) async* {
    try {
      if (state is PerfomancesLoadedSuccess) {
        final batch = await this.perfomanceRepository.fetchBatch(0, batchSize);
        yield (state as PerfomancesLoadedSuccess).copyWithRefresh(
            batch.map((element) => Perfomance.fromDto(element)).toList());
      }
    } catch (_) {
      yield PerfomancesLoadFailure();
    }
  }

  Stream<PerfomancesState> _mapFetchPerfomanceDetails(
      FetchPerfomanceDetails event) async* {
    try {
      if (state is PerfomancesLoadedSuccess) {
        final beforeLoadState = state as PerfomancesLoadedSuccess;
        yield PerfomanceDetailsPending();
        final detailsDto = await this
            .perfomanceRepository
            .fetchPerfomanceDetails(event.perfomanceId);
        yield beforeLoadState.copyWithDetails(PerfomanceDetails.fromDto(detailsDto));
      }
    } catch (e) {
      print(e);
      yield PerfomancesLoadFailure();
    }
  }

  Stream<PerfomancesState> _mapSwitchIsFavorite(SwitchIsFavorite event) async* {
    try {
      if (state is PerfomancesLoadedSuccess) {
        final currentState = (state as PerfomancesLoadedSuccess);
        final updatedPerfomance = currentState.perfomances
            .firstWhere((element) => element.id == event.perfomanceId)
            .switchIsFavorite();
        final updatedList = currentState.perfomances
            .map((e) => e.id == event.perfomanceId ? updatedPerfomance : e);
        yield (state as PerfomancesLoadedSuccess)
            .copyWith(perfomances: updatedList);
        perfomanceRepository.updatePerfomance(updatedPerfomance.toDto());
      }
    } catch (_) {
      yield PerfomancesLoadFailure();
    }
  }
}

I don't like this idea because my state is responsible for two screen. And if an error will occurred  while fetching concrete perfomance details then will transition to state "PerfomancesLoadFailure" and app will lost state PerfomancesLoadedSuccess this loaded information. Is it ok if I add all data fields in base state and inherit other state?

What is the best practice to design blocs/states in app in which main use-case is fetching list of items with main info and fetching details info after tapping. 

thank you in advance!

**Comment by felangel** [comment]
Hi @RocketVick 👋 
Thanks for opening an issue!

Based on the information you shared, I think a good place to start would be to have three blocs:
- `PerformancesBloc`
- `PerformanceDetailsBloc`
- `FavoritePerformancesBloc`

The `PerformancesBloc` could be similar to the `PostsBloc` which is implemented in the [infinite list example](https://github.com/felangel/bloc/tree/master/examples/flutter_infinite_list).

The `PerformanceDetailsBloc` could just have states like:

```dart
@immutable
abstract class PerformanceDetailsState {}

class PerformanceDetailsInitial {}

class PerformanceDetailsLoadInProgress {}

class PerformanceDetailsLoadSuccess {
  // various details which are shown on the details screen
}

class PerformanceDetailsLoadFailure {}
```

The `FavoritePerformancesBloc` could have states like:

```dart
@immutable
abstract class FavoritePerformancesState {}

class FavoritePerformancesInitial {}

class FavoritePerformancesLoadInProgress {}

class FavoritePerformancesLoadSuccess {
  FavoritePerformancesLoadSuccess({this.performances = const <String>[]});
  final List<String> performances; // list of favorite performance ids
}

class FavoritePerformancesLoadFailure {}
```

Hope that helps 👍

**Comment by RocketVick** [comment]
@felangel thanks for the answer!

My first version of my app contained three blocs as you recommend. But I ran into one problem.

If I will use three different blocs for one business entity, I will should notify blocs about changes. And I think this can lead to a lot of confusion.

Example:
If I switch flag "isFavorite" on the second screen using **FavoritePerformancesBloc**, I have to do some dependency between this bloc and any others. Because I need to show some "favorite label" on items list on first screen.

I think this situation is similar with [Flutter Todos Tutorial](https://bloclibrary.dev/#/fluttertodostutorial). This app has shared TodosBloc which manage all changes in todo list and any bloc can to subscribe on TodosBloc state changes  (FilteredTodosBloc as example). 
Your Todos App is great, but I really don't understand how design my blocs correctly.

I think there are two ways:
first - continue to creating three different blocs with relative subscription (I mean listening states).
second - create one shared bloc (like TodosBloc) and other blocs will listen it.

But it all doesn't fit in my head.

I will be very grateful for the answer!
