### ISSUE TITLE
[Design Question] Many changeable items inside a changeable list

### ISSUE THREAD

**Issue by matanshukry** [felangel/bloc#1215]
I have a list of items I'm querying from the server. The list can be updated in 1 of these 2 ways:
- a new item is added
- an existing item is updated

Currently what I'm doing, bloc-size:
- Using a single bloc with list of items. When either of above changes happen I'm modifying the existing array and yielding the same state with the same array.

Currently what I'm doing,  ui-size:
- widget A (the item widget):
  - A stateful widget that is based on an item (using index and the initial item)
  - using a listener, when the list updates, I'm checking the saved variable against the item from the state (using the index), and if they are different I'm updating the widget state (setState)

- Widget B (the list widget):
  - a stateful widget that created the list of items to a Listview, using bloc provider
  - each widget in the listview is widget A
  - in init state, I'm saving the length of the current list in the state
  - using listener, when the list updates I'm updating the length if it's different (setState)

Notes about current design:
- Widget A can change most up to 5 times. 90% of the times it will change only once, and it's going to be only a few seconds after creating.
- There could be a lot of items
- An alternative design would be to create a custom bloc and a BlocProvider for *each* item in widget A, which sounds really bad considering the amount of items and the frequency of their changes

Is there a better way to design such a case?

**Comment by RollyPeres** [comment]
Hi @matanshukry 👋

Did you check out the [infinite list example](https://github.com/felangel/bloc/tree/master/examples/flutter_infinite_list) ?

Feel free to comment if you need further guidance 👍

**Comment by matanshukry** [comment]
@RollyPeres I didn't before, but it doesn't change anything.

The main difference between my case and the Infinite List is every item on my list can also change, while in the infinite list only the list it self can change (more items).

Also, note in my current design I'll be using a single array.
The infinite list will keep creating new arrays as new posts arrive.
 
So if you reached 1000 posts and want to fetch another 20: an array of size 1120 will be created (depending on + operator implementation, but that's the best case scenario)

**Comment by RollyPeres** [comment]
You should be using immutable objects instead of mutating existing ones, especially if you're planning to use bloc. `ListView` will render the visible items only, so performance wise is not going to have an impact. When you need to update an item just yield a new state with a new list where you replace the proper item.

**Comment by matanshukry** [comment]
@RollyPeres just because `ListView` will render only the visible items it doesn't mean it won't impact your app. Correct me if I'm wrong, but creating and destroying new arrays, specially large ones, is probably gonna cause a GC sooner or later.

Also, you're focusing on the least important part of it; even if I do use immutable list and recreate the large array, there is still the issue of the items.

Creating a BlocProvider + BlocBuilder (at least) for every item will add to the widget tree (and again to the memory). 

To me it sounds like a lot of extra memory, and when the amount of items could be large (and in my case it could be), it doesn't sound like a good way to do things.

Correct me if I'm wrong / missing something?

**Comment by felangel** [comment]
Hi @matanshukry 👋 
Thanks for opening an issue!

I have created a [gist](https://gist.github.com/felangel/ec84a91260b1085b9a8bcf83df5939c2) where a single bloc is used to manage the state of a List of elements (1000+). Items can be added or the entire list can be updated and I have not experienced any performance issues. The entire UI is not rebuilt and creating/copying lists is definitely more expensive than mutating a single list but I would argue that it's not significant and doesn't outweigh the advantages of using immutable state.

Are you experiencing performance issues with `ListView.builder` within a `BlocBuilder`? If so would it be possible for you to share a link to a sample app which reproduces the issue? Thanks 👍

**Comment by matanshukry** [comment]
@felangel the gist is still missing a crucial part of the case I'm describing: a bloc for *each* item.
That is, imagine the itemBuilder proeprty to be something like this:

```
itemBuilder: (context, index) {
  return BlocBuilder<ListItemBloc, ListItemState>(
    builder: (context, itemState) {
      if (itemState is ItemStateUpdating) {
        return CircularProgressIndicator();
      }

      Icon icon;
      if (itemState is ItemStateGood) {
        icon = Icon(Icons.check);
      } else {
        icon = Icon(Icons.eye);
      }
      return ListTile(leading: icon, title: Text(state.items[index]));
    }
  },
```

Also, you said you haven't experienced any performance issues, but I think you're talking about the gist it self, which is a very minimal and not realistic case of a real life app; the performance issues will probably start to show up when the app will consume (and "move") more memory.

**Comment by felangel** [comment]
@matanshukry each `BlocBuilder` is a `StatefulWidget` under the hood so it shouldn't be that expensive to rebuild. It would be best if you could share an example with performance problems and we can take a look at how we can optimize it rather than trying to prematurely optimize. Thoughts?

**Comment by RollyPeres** [comment]
@matanshukry I understand your concerns, but dart and flutter are optimized for many short lived objects, and that's achieved especially with the way their GC was implemented. So I wouldn't worry about 1000 length list. I would be worried about this aspect if their GC was implemented like for example the C# one.
I would personally not add a dedicated bloc for every item.

**Comment by matanshukry** [comment]
@RollyPeres How would you do it then? recreate the list and use index/map for the item? or something else?

@felangel not really. That is, I can't share my actual app as an example. I'll try to find the time to create something, but I'm not sure if it's going to happen soon. If you want to close the issue in the meantime I understand; I'll comment again and reopen when I have more info

**Comment by RollyPeres** [comment]
@matanshukry a single bloc with an immutable collection. You should just replace the proper item with a new updated instance. You can use `List`, `Map` or even `Set` to store the items, really up to your needs.

**Comment by felangel** [comment]
@matanshukry sounds good! I'll close this for now but if you have a chance to create an example app I'm happy to revisit this 👍
