### ISSUE TITLE
Using common bloc for different screens #1205

### ISSUE THREAD

**Issue by karthikeyanp307** [felangel/bloc#1220]
Hi @felangel ,

Tried this and now the filter functionality works fine. But now I am facing different issue.

Since both these tabs shares common bloc, the state changes made wrt to one tab is affecting the other. For example, as the pages are build based on state changes made to BlocBuilder there is an issue while rendering the screens.

Will it be possible to ignore or restrict few state changes at tab level i.e., state changes related to Screen A needed to be restricted to Screen B. Are there any other alternative to resolve this issue. Please help.

Thanks.

**Comment by felangel** [comment]
Hi @karthikeyanp307 👋 
Thanks for opening an issue!

If you want to keep the states independent then I would suggest having a separate bloc for each tab rather than trying to manage independent states with the same bloc.

Hope that helps! 👍
