### ISSUE TITLE
Question: how can I pass states variables from parent state to extended states classes?

### ISSUE THREAD

**Issue by hackerunet** [felangel/bloc#1222]
Hi there, this is really a question, regarding flutter_bloc and dart inheritance, I cannot see how to pass a value from a parent state to a child class state.
For example, I have a bloc with an event handler:
````
if (event is FormSubmitted) {
    yield FormSubmitted;
}
if (event is FormUpdated) {
    yield FormUpdated;
}
````
so, How can I change the state from FormSubmitted to FormUpdated and preserve some values declared in FormSubmitted state? how can I passed them to the child state FormUpdated?

**Comment by RollyPeres** [comment]
Hi @hackerunet 👋

When working with forms is recommended to use a single class as state. If you need to track down some additional status, you could have an enum as a field on the state class. 
e.g.: `enum FormStatus { initial, updated, submitted }`

Hope that helps 👍

**Comment by hackerunet** [comment]
can you please maybe illustrate with an example? I really have tried to understand how to manage states using enums, but I don't get it yet...

**Comment by felangel** [comment]
Hi @hackerunet 👋
Thanks for opening an issue!

Please check out the [form validation example](https://github.com/felangel/bloc/tree/master/examples/flutter_form_validation) as a reference.

Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍
