### ISSUE TITLE
BlocProvider not recreating the bloc

### ISSUE THREAD

**Issue by mancj** [felangel/bloc#1223]
**Describe the bug**
BlocBuilder's create method called only once, at the first time the widget is created. Can't recreate it.

**To Reproduce**

First, you can see [this sample repository](https://github.com/mancj/flutter_bloc_sample), to reproduce the behaviour.

I have the [ResponsiveContainer](https://github.com/mancj/flutter_bloc_sample/blob/master/lib/responsive_container.dart), which is used to split the screen to the master/detail flow on tablets.

The ListScreen.dart is subscribed to the bloc state with `BlocBuilder`. When user taps the list item, DetailScreen must rebuild, to change the detail page. You can find this [logic here](https://github.com/mancj/flutter_bloc_sample/blob/a65496dc33f3e02dcb3ebe9a685e17e328e2ff2b/lib/list_screen.dart#L36).

Then I expect the DetailScreen to create new DetailBloc and add the DetailEvent, to redraw the detail page. But it is not happening. BlocProvider's create method called only once at the first time.

Is this expected logic or i am doing something wrong? How to force the BlocBuilder to recreate?

_Thank you for your help!_

**Comment by RollyPeres** [comment]
Hi @mancj ✌

Not exactly sure what you're trying to achieve there, but I tried to follow your line of thoughts and opened this [PR](https://github.com/mancj/flutter_bloc_sample/pull/1)

Just as a side note you have direct access to your `ListBloc` directly in the details page so you could use a `BlocBuilder<ListBloc, ListState>`. But I assumed you're trying to mimic if there's 2 separate blocs. Alternatively you could even inject the list bloc into your details bloc and listen to it's state.

Hope that gives you some ideas 👍

**Comment by mancj** [comment]
@RollyPeres thank you, this is really good information, that i didn't know.

The possible problem now, is that on mobile phones this DetailScreen will be open as separate route. But i think i can solve this, so i tried to create the DetailBloc inside the DetailScreen and not the parent ListScreen.
And also i want to understand the reason why the BLoC isn't recreating.

**Comment by felangel** [comment]
Hi @mancj 👋 
Thanks for opening an issue!

BlocProvider's create is only called once when the widget is mounted. Rebuilds will not trigger a recreation of the bloc by design. You can think of the `BlocProvider's` create like `initState`. In order for `create` to be invoked again, the `BlocProvider` itself would need to be unmounted from the widget tree and remounted.

**Comment by mancj** [comment]
Thanks @felangel! I'm new to flutter, so now my knowledge is not enough to fully understand this  lifecycle. But i got the main idea, closing the issue for now 😌

**Comment by nandoys** [comment]
> Hi @mancj 👋 Thanks for opening an issue!
> 
> BlocProvider's create is only called once when the widget is mounted. Rebuilds will not trigger a recreation of the bloc by design. You can think of the `BlocProvider's` create like `initState`. In order for `create` to be invoked again, the `BlocProvider` itself would need to be unmounted from the widget tree and remounted.

how can i achieve this ? to unmount and remount BlocProvider's ??

**Comment by felangel** [comment]
> > Hi @mancj 👋 Thanks for opening an issue!
> > BlocProvider's create is only called once when the widget is mounted. Rebuilds will not trigger a recreation of the bloc by design. You can think of the `BlocProvider's` create like `initState`. In order for `create` to be invoked again, the `BlocProvider` itself would need to be unmounted from the widget tree and remounted.
> 
> Hi @felangel how can i achieve this ? to unmount and remount BlocProvider's ??

To re-create the bloc, you will need to unmount the BlocProvider (meaning the part of the widget tree that the BlocProvider is in will need to be removed) and then re-mount it. Also note that by default `create` is called lazily but if you want you can change that behavior by setting `lazy: false`. Hope that helps 👍

**Comment by memishood** [comment]
@mancj If you want to recreate it, you can give `UniqueKey()` to the view so it will always create since it will look different widget
