### ISSUE TITLE
Communication between blocs

### ISSUE THREAD

**Issue by clicksocial** [felangel/bloc#123]
**Is your feature request related to a problem? Please describe.**

Is there any documentation or recommendation for communication between blocs beside having dependencies between them? The point is to keep blocs independent of each other and use streams to allow them to communicate with each other.

While we can use the BlocDelegate to trigger certain blocs to do certain things, but obviously this is not the best solution.

**Describe the solution you'd like**
There should be a mechanism for one bloc to listen to another bloc by registering a handler to handle when a state change in that bloc.

**Describe alternatives you've considered**
- Solution 1: Add a dependency to another bloc 
- Solution 2: Enable bloc to listen to state changes from another bloc

**Additional context**

**Comment by felangel** [comment]
@clicksocial thanks for opening an issue for this. If you don't a bloc to have a direct dependency on another bloc you can always inject the stream that you want the bloc to react to. 

For example, if we want BlocA to react to state changes in BlocB, we can always do something like:

```dart
class BlocA extends Bloc<BlocAEvent, BlocAState> {
  final Stream<BlocBState> stateStream;
  StreamSubscription stateSubscription;

  BlocA(this.stateStream) {
    stateSubscription = stateStream.listen((state) {
      if (state is ...) {
        // do something
      }
    });
  }

  ...
  
  @override
  dispose() {
    stateSubscription.cancel();
    super.dispose();
  }
}
```

We can then pass the state stream of BlocB into BlocA like:
```dart
final blocA = BlocA(blocB.state);
```

I would also recommend looking at the [Todos Application](https://github.com/brianegan/flutter_architecture_samples/blob/master/bloc_library/README.md) for a more concrete example (`FilteredTodosBloc` reacts to state changes in `TodosBloc`).

Does that answer your question? 👍

**Comment by clicksocial** [comment]
Hi @felangel , 

This looks like its going to work. I'll give it a try.

Thanks for your timely response!

Quan

**Comment by felangel** [comment]
@clicksocial no problem! Closing this for now but feel free to comment if you're having trouble or have additional questions 👍

**Comment by JoeMartin2001** [comment]
```
class OrderBloc extends Bloc<OrderEvent, OrderState> {
  final SocketService socketService = injector.get<SocketService>();
  final OrderRepo orderRepo;
  final Stream<OrderInfoState> orderInfoStream;
  StreamSubscription orderInfoBlocSubscription;

  OrderBloc({@required this.orderRepo, @required this.orderInfoStream})
      : assert(orderRepo != null),
        super(OrderLoadingState()) {
    orderInfoBlocSubscription = orderInfoStream.listen((state) {
      if (state is OrderLoadedState) {
        print('hello from costructor. yeahhhhh');
      }
    });
  }

  @override
  Stream<OrderState> mapEventToState(
    OrderEvent event,
  ) async* {
    if (event is OrderLoadEvent) {
      yield OrderLoadingState();
      try {
        final List<Order> _loadedOrderList = await orderRepo.getAllOrders();
        yield OrderLoadedState(loadedOrders: _loadedOrderList);
      } catch (e) {
        print(e);
        yield OrderErrorState();
      }
    }
  }

  @override
  Future<void> close() {
    orderInfoBlocSubscription.cancel();
    return super.close();
  }
}
```

**Comment by JoeMartin2001** [comment]
Hi, Felix Angelov. Can you review my code? It is not working. Am I doing it right?

**Comment by JoeMartin2001** [comment]
```
        BlocProvider<OrderBloc>(
          create: (context) => OrderBloc(
              orderRepo: _orderRepo, orderInfoStream: orderInfoBloc.stream)
            ..add(OrderLoadEvent()),
        ),
```

**Comment by narcodico** [comment]
@JoeMartin2001 make sure your order info bloc is created thus emitting at least the initial state.
There's also a chance your order bloc listens to your order info bloc but the latter one doesn't emit any new states after listening.

**Comment by JoeMartin2001** [comment]
Thanks I will try that
