### ISSUE TITLE
Mention note on using equatable within the docs

### ISSUE THREAD

**Issue by pradt** [felangel/bloc#1231]
**Describe the bug**
Just wondering whether you could update the documents around BlocBuilder and make a note about using equatable, I've just spent a couple of days trying to work out why my BlocBuilder was only triggering once, and failed to trigger for any subsequent yields. 

The issue was that I was using equatable and I didn't populate the list with the fieldnames in the state class. I read the documentation several times and created the sample apps to work out what I was doing wrong. Hoping this can save someone else time if they run into a similar situation.

**Comment by felangel** [comment]
Hi @pradt 👋
Thanks for opening an issue and sorry for the inconvenience! Have you taken a look at the [FAQs](https://bloclibrary.dev/#/faqs?id=state-not-updating)? It should be covered there and maybe we just need to make sure it’s easier to discover. Let me know what you think 👍

**Comment by felangel** [comment]
Closing this for now but feel free to comment and let me know what you think and I'm happy to continue the conversation 👍

**Comment by pradt** [comment]
hi, I had completely missed the FAQ section not sure how. It covers exactly what I was looking for. thanks

**Comment by rravithejareddy** [comment]
@pradt  Can your show how did you Used equatable class with list properties?
https://bloclibrary.dev/#/faqs?id=when-to-use-equatable
