### ISSUE TITLE
 Error handling from the server

### ISSUE THREAD

**Issue by zakiroof** [felangel/bloc#1232]
Hello.
How can i implement backend validation?
For an example I took User Repository from "Flutter Login Tutorial". During authorization, the server can return the following response:

```
{
  "username": [
    "Invalid login"
  ],
  "password": [
    "Too short password"
  ]
}
```
How can I handle these errors. And assign TextFormField?

**Comment by felangel** [comment]
Hi @zakiroof 👋 
Thanks for opening an issue!

You can just expose the validation error from the `UserRepository` by throwing a custom ValidationException like:

```dart
class RegisterValidationException implements Exception {
  const RegisterValidationException({
    this.usernameErrors = const <String>[],
    this.passwordErrors = const <String>[],
  });

  final List<String> usernameErrors;
  final List<String> passwordErrors; 
}
```

Then you can throw these custom exception from the `UserRepository` whenever a validation error occurs on the backend:

```dart
final validationError = RegisterValidationError.fromJson(body);
throw RegisterValidationException(
  usernameErrors: validationError.username,
  passwordErrors: validationError.password,
);
```

Now in the bloc you can catch this exception and emit an error state depending on the values:

```dart
try {
  await _userRepository.register(...);
  yield RegistrationSuccess();
} on RegisterValidationException catch (error) {
  yield RegistrationFailure(
    usernameError: error.usernameErrors.isNotEmpty ? error.usernameErrors.first : null,
    passwordError: error.passwordErrors.isNotEmpty ? error.passwordErrors.first : null,
  );
}
```

Then in the UI you can handle rendering the appropriate errors by wrapping your `TextFormField` widgets in a `BlocBuilder`

```dart
BlocBuilder<RegisterBloc, RegisterState>(
  builder: (context, state) {
    return TextFormField(
      decoration: InputDecoration(
        errorText: state is RegistrationFailure ? state.usernameError : null,
      ),
      ...
  },
);
```

Hope that helps 👍
