### ISSUE TITLE
Using Rx.combineLatest2 for 2 different Blocs

### ISSUE THREAD

**Issue by mohammadne** [felangel/bloc#1237]
Hi

in my case I have 2 different Blocs and I want to combine them together like :
```Rx.combineLatest2(positionBloc.state, disableBloc.state, (a, b) => null)```
and says:
```The argument type 'PositionState' can't be assigned to the parameter type 'Stream<dynamic>'```
```The argument type 'DisableState' can't be assigned to the parameter type 'Stream<dynamic>'```

so what can I do here for combining ?
also is it possible to add ```CombineBlocs``` to existing widget in this awesome library ?

Thanks.

**Comment by RollyPeres** [comment]
Hi @mohammadne 👋

The bloc itself is a `Stream<State>` so you should be combining the blocs and not their state.
`Rx.combineLatest2(positionBloc, disableBloc, (a, b) => null)`

Alternatively you could inject some bloc into some other bloc as showcased [here](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication).

**Comment by felangel** [comment]
Thanks @RollyPeres for taking the time to answer! 🙏 

@mohammadne closing this for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
