### ISSUE TITLE
How can I cancel event in bloc?

### ISSUE THREAD

**Issue by RomanSoviak** [felangel/bloc#1238]
I have two events, execution of PrepareEpubBook event lasts 10-15 sec. During this execution, I call from UI CancelBookPreparing event, but this event executes only after PrepareEpubBook event finishes.

`if (event is CancelBookPreparing) {
  _cancelToken.cancel();
  yield BookOpeningCancel();
}  else if (event is PrepareEpubBook) {
  ...
    await _downloadBook(event.bookData.downloadURL, bookPath);
  ...`
How can I cancel execution of PrepareEpubBook event and make CancelBookPreparing event? Or How can I run CancelBookPreparing event during PrepareEpubBook event?

**Comment by RollyPeres** [comment]
Hi @RomanSoviak 👋

You could override `transformEvents` and use `switchMap` instead of the default `asyncExpand`. This will drop the previous event when a new event is entering bloc.

**Comment by RomanSoviak** [comment]
@RollyPeres thanks!

**Comment by LiamKarlMitchell** [comment]
This advice seems out of date, can use event transformers.
import 'package:bloc_concurrency/bloc_concurrency.dart';

restartable - process only the latest event and cancel previous event handlers

However this wouldn't actually cancel say a web request using a cancellation token or anything, but it would process only the latest event and that might be good enough.

**Comment by narcodico** [comment]
Mate, the question was about cancelling an EVENT not a request.
