### ISSUE TITLE
How do I combine stream?

### ISSUE THREAD

**Issue by jezsung** [felangel/bloc#1240]
```
@override
  Stream<CustomState> mapEventToState(CustomState event) async* {
    yield* StreamGroup.merge([otherStream, _mapUIEventToState(event)]);
}

Stream<CustomState> _mapUIEventToState(AuthEvent event) async* {
...
}
```

I want to do something like the above but it doesn't work after the first call. How do I group or merge streams?

**Comment by RollyPeres** [comment]
Hi @jezsung 👋

Have you taken into consideration injecting the other stream into your bloc as showcased [here](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication) ?

**Comment by jezsung** [comment]
@RollyPeres Thanks for sharing that but it doesn't meet my use case. I just want to simply combine streams from other libraries such as FirebaseAuth or Firestore with my own business logic. I want to keep them in a single bloc.

**Comment by RollyPeres** [comment]
FirebaseAuth and Firestore are data sources and should not be directly consumed within blocs but rather in repositories. The repositories should then be injected into blocs where you can manually subscribe to your streams and add events to the bloc itself based on incoming data. For that, see the link I previously shared.

If you don't like the recommended way then you could make use of `rxdart` with `Rx.combineLatest2(someBloc, someStream, (blocState, someStreamData) { ... })`
