### ISSUE TITLE
Getting  build function returned null issue on first time then it works fine 

### ISSUE THREAD

**Issue by mahisingh1** [felangel/bloc#1244]
@override
  Widget build(BuildContext context) {
    return Container(
      height: MediaQuery.of(context).size.height,
      width: MediaQuery.of(context).size.width,
      color: Colors.white,
      child: Scaffold(
        body: BlocBuilder<RestaurantBloc, RestaurantState>(
            builder: (context, state) {
          if (state is RestaurantInitialState) {
            _shimmerList();
          } else if (state is Loading) {
            _shimmerList();
          } else if (state is RestaurantMenuFetched) {
            return _menuListItem(state.response);
          } else if (state is Failed) {
            return buildErrorUi(state.message);
          } else {
            return buildErrorUi(StringResources.somethingWentWrong);
          }
        }
        ),
      ),
    );
  }

**Comment by felangel** [comment]
Hi @mahisingh1 👋 
Thanks for opening an issue!

Can you please describe the problem you're having more clearly and provide a link to a complete application that reproduces the issue? Thanks 👍

**Comment by mahisingh1** [comment]
I am working with Bloc . I have provided bloc builder to widget , now the problem is on the very first time it shows Build function returns null after that is works perfectly.

**Comment by felangel** [comment]
@mahisingh1 what is the `initialState` of your bloc?

**Comment by mahisingh1** [comment]
Ohh! Thanks i thought it return from the internal methods :D
