### ISSUE TITLE
Easily retrieving bloc

### ISSUE THREAD

**Issue by loicgeek** [felangel/bloc#1246]
Add that code to new bloc snippet:
`import 'package:flutter_bloc/flutter_bloc.dart';`

  `static $1Bloc of(BuildContext context) {
    return BlocProvider.of<${1:Subject}Bloc>(context);
  }`

>Intead of using BlocProvider.of<$1Bloc>(context), we could use $1Bloc.of(context)

**Comment by shamnex** [comment]
Hmmm. 

I think think the bloc extension method on the BuildContext is the cleanest:

`final bloc = context.bloc<MyBloc>();
`
Or even using type inference: 

`final MyBloc bloc = context.bloc();`

**Comment by loicgeek** [comment]
> Hmmm.
> 
> I think think the bloc extension method on the BuildContext is the cleanest:
> 
> `final bloc = context.bloc<MyBloc>(); `
> Or even using type inference:
> 
> `final MyBloc bloc = context.bloc();`

Wow, i didn't know about that, thanks
