### ISSUE TITLE
Documentation: Naming conventions and Tutorial discrepency

### ISSUE THREAD

**Issue by suragch** [felangel/bloc#1248]
I'm going through the tutorials. I came to the [Timer tutorial](https://bloclibrary.dev/#/fluttertimertutorial). In there we are told to name the events `Start`, `Pause`, `Resume`, `Reset`, and `Tick`. 

However, according to the [naming conventions](https://bloclibrary.dev/#/blocnamingconventions), I would expect the names to be `TimerStarted`, `TimerPaused`, `TimerResumed`, `TimerReset`, and `TimerTicked`. 

The state names in the Timer tutorial seem fine to me, but they also don't conform to the naming conventions.

I haven't gone through all the tutorials yet so I don't know if other tutorials follow the naming conventions or not.

I'm sure everyone can choose for themselves whether or not to follow the naming conventions, but it seems like it would make the documentation better if it were self-consistent.

**Comment by fotiDim** [comment]
I noticed the same inconsistency with State names. 
In the documentation it states
```
State should be one of the following: Initial | Success | Failure | InProgress and initial states should follow the convention: BlocSubject + Initial.
```

In the weather example there is a state named `WeatherLoaded` when that should be an event name.
Also `Loading` instead of `InProgress` is used.

It would be nice to update the examples using the recommended naming scheme as this confuses newcomers into the library.

**Comment by felangel** [comment]
Hi @fotiDim 👋
Thanks for opening an issue!

I’m in the process of updating the names in the tutorials to align. Should have it done this weekend at the latest 👍

**Comment by felangel** [comment]
I believe all of the documentation and examples should adhere to the naming conventions. Please feel free to comment if you find anything I missed 👍

**Comment by suragch** [comment]
Thank you, Felix! That will make it more clear for a lot of people.

**Comment by fotiDim** [comment]
That is great! When can we except the website to update?
