### ISSUE TITLE
variable is not defined in BlocBuilder in main class

### ISSUE THREAD

**Issue by tazik561** [felangel/bloc#1249]
I am trying to use Flutter bloc in my project.After creating State and Event class in State i have a `LanguageLoad` class:

    abstract class LanguageState extends Equatable {
      const LanguageState();
      @override
      List<Object> get props => [];
    }
    
    class LanguageInitial extends LanguageState {}
    
    class LanguageLoad extends LanguageState {
      final Locale locale;
      LanguageLoad(this.locale);
      @override
      List<Object> get props => [locale];
    }
After creating bloc class i am using in main class:

        void main() {
          WidgetsFlutterBinding.ensureInitialized();
          runApp(
            BlocProvider(
                create: (_) => LanguageBloc()..add(LanguageLoadStarted()),
                child: MyApp()),
          );
    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return BlocBuilder<LanguageBloc, LanguageState>(
          builder: (context, languageState) => MaterialApp(
            debugShowCheckedModeBanner: false,
            locale: languageState.locale, // locale is not defined
    }

But I don't know why locale is not defined in `locale: languageState.locale` ?

**Comment by felangel** [comment]
Hi @tazik561 👋 
Thanks for opening an issue!

You need to first check to make sure that the `languageState` is of type `LanguageLoad`.

```dart
BlocBuilder<LanguageBloc, LanguageState>(
  builder: (context, languageState) {
    if (languageState is LanguageLoad) {
      return MaterialApp(
        locale: languageState.locale,
        ...
      ),
    }
    // handle LanguageInitial state
  },
)
```

Hope that helps 👍
