### ISSUE TITLE
Documentation issue in infinite list sample

### ISSUE THREAD

**Issue by solshark** [felangel/bloc#1250]
https://bloclibrary.dev/#/flutterinfinitelisttutorial

Comment beneath one of the code sample states: 

> Again, *we are overriding toString* for an easier to read string representation of our event. Again, we are extending Equatable so that we can compare instances for equality.

But actual code above has no `toString` override.
 

<img width="924" alt="Screenshot 2020-06-06 at 15 13 18" src="https://user-images.githubusercontent.com/107233/83943919-5ce5f300-a808-11ea-96d5-6217486b2d6e.png">

**Comment by felangel** [comment]
Hi @solshark 👋
Thanks for opening an issue!

Will definitely make sure this is addressed along with #1248 today/tomorrow 👍
