### ISSUE TITLE
The recommended way of using flutter bloc 

### ISSUE THREAD

**Issue by EngAddow** [felangel/bloc#1268]
Here I want to ask what is better not issue really!

I have been searching different state managements in flutter and I lastly decided to go with flutter bloc
but when I read the articles and watch some tutorials I got different ways of using this bloc for example some people just create one bloc file and use streams for streaming and sinking events and data while others create three files 1 for events, 1 for states and one for the bloc to map events to states and no use of streams . The question is which way is preferred for bloc pattern?

**Comment by RollyPeres** [comment]
Hi @EngAddow 👋

The first way you're mentioning is actually the vanilla bloc which is different from `flutter_bloc` approach which was built to deal with the downsides of vanilla bloc.

I'd recommend you start by reading through [docs](https://bloclibrary.dev/#/gettingstarted). You could also check out the [examples](https://github.com/felangel/bloc/tree/master/examples).

Hope that clears things out for you 👍

**Comment by EngAddow** [comment]
> Hi @EngAddow 👋
> 
> The first way you're mentioning is actually the vanilla bloc which is different from `flutter_bloc` approach (second way) which was built to deal with the downsides of vanilla bloc.
> 
> I'd recommend you start by reading through [docs](https://bloclibrary.dev/#/gettingstarted). You could also check out the [examples](https://github.com/felangel/bloc/tree/master/examples).
> 
> Hope that clears things out for you 👍


Thank you very much, I am reading the docs now and I got it says wee need two dependencies
`dependencies:
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
`
but in my case I just installed 
`dependencies:
  flutter_bloc: ^4.0.0`

and everything is working fine for now
so what is the difference?

**Comment by RollyPeres** [comment]
It's working because `flutter_bloc` depends on `bloc` so flutter will take care of making it available.

**Comment by felangel** [comment]
@EngAddow in more recent versions `flutter_bloc` exports `bloc` which is why the `bloc` dependency is not critical but it's good to have in my opinion because it makes things more explicit.

**Comment by felangel** [comment]
Closing for now but feel free to comment if you have any additional questions and I’m happy to continue the conversation 👍

**Comment by EngAddow** [comment]
Thank you very much  I hope you make tutorials of real apps using flutter bloc.

**Comment by EngAddow** [comment]
> @EngAddow in more recent versions `flutter_bloc` exports `bloc` which is why the `bloc` dependency is not critical but it's good to have in my opinion because it makes things more explicit.

I will insha aAlah
