### ISSUE TITLE
When string results are equal to expected results show warning to implement deep equal 

### ISSUE THREAD

**Issue by ride4sun** [felangel/bloc#1275]
this feature request is related to Issue #1269

When the string results are equal but the test fails this is very likely related that the result comparison is based on a reference equal and not content (deep) equal. bloc test should show a warning to remind the programmer to implement a == operator or to use https://pub.dev/packages/equatable or implement `Comparable<T>`  (dart core)  in their data class.

**Comment by felangel** [comment]
This will be included in `bloc_test v7.0.4` 🎉
