### ISSUE TITLE
Change text color outside of blocbuilder, according bloc state

### ISSUE THREAD

**Issue by tazik561** [felangel/bloc#1283]
I have a page as a main Navigation page to show 2 pages with tap on text widget.

This is my widget tree:

        return Scaffold(
          body: Column(
              children: <Widget>[
                 Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: <Widget>[
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: <Widget>[
                              InkWell(
                              onTap: () =>
                                            BlocProvider.of<NavigationBloc>(context).add(PageTapped(index: 1)),
                                        child: Text("Archive"))),
                              ),
                              InkWell(
                              onTap: () => BlocProvider.of<NavigationBloc(context).add(PageTapped(index: 0)),
                                          child: Text("All")))),
                            ],
                          ),
                     BlocBuilder<NavigationBloc, NavigationState>(
                      builder: (context, archiveState) {
                    if (archiveState is PageLoading) {
                      return Center(child: CircularProgressIndicator());
                    }
                    if (archiveState is AllPageLoaded) {
                      return AllImagePage();
                    }
                    if (archiveState is ArchivePage) {
                      return ArchiveImagePage();
                    }
                    return Container();
                  })

The both pages is loaded and there is no problem about it.But in 

    InkWell(
      onTap: () =>BlocProvider.of<NavigationBloc>(context).add(PageTapped(index: 1)),
      child: Text("Archive"))),
    ),
Part i want to change text color when tapped on it! So in order to i declared a variable called `int _currentIndex = 0;` and in this part inside blocbuilder i do :

     if (archiveState is AllPageLoaded) {
         setState(() {
              _currentIndex = 0;
         });
         return AllImagePage();
      }
I want according to _currentIndex is selected, change `Text` color but i got error:
>This NavigationPage widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.

I know this error what is it, but how can i solve my scenario?Change color of text when they are tapped?

**Comment by felangel** [comment]
Hi @tazik561 👋
Thanks for opening an issue!

You can use multiple BlocBuilders in different parts of your UI in order to rebuild them based on state changes in the same bloc. In this case, you can just wrap the part of the UI in which you want to update the text color with another BlocBuilder.

If you’re able to share a link to a sample app which illustrates the problem, I’m happy to open a pull request with the suggested changes 👍

Let me know if that helps 😊

**Comment by tazik561** [comment]
I use bloc listener to this problem and it work googd.Is it wrong?

            BlocListener<NavigationBloc, NavigationState>(
              listener: (context, state) {
                if (state is AllPageLoaded) {
                  setState(() {
                    _currentIndex = 0;
                  });
                }
                if (state is ArchivePage) {
                  setState(() {
                    _currentIndex = 1;
                  });
                }
              },

**Comment by felangel** [comment]
Instead of using `setState` and keeping track of `_currentIndex` you can just wrap the part of your UI that uses `_currentIndex` in a `BlocBuilder` and react to state changes directly.
