### ISSUE TITLE
MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in

### ISSUE THREAD

**Issue by Mo-rema07** [felangel/bloc#1284]
I followed the tutorial on https://bloclibrary.dev/#/flutterfirebaselogintutorial. The email and password login and register features work perfectly, however when I press the sign_in_with_google button I get

`MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in`

How do I solve this? 
I ran `flutter run -v` and got the following file
[error.log](https://github.com/felangel/bloc/files/4765710/error.log)

**Comment by RollyPeres** [comment]
Hi @Mo-rema07 👋

It looks like your plugin is not injected in the platform side. Make sure you `flutter clean`, quit your IDE and re-run your app. Just a simple hot reload/restart won't do it.

**Comment by felangel** [comment]
Thanks as always @RollyPeres for taking the time to answer!

@Mo-rema07 closing this for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍

**Comment by Mo-rema07** [comment]
> Hi @Mo-rema07 
> 
> It looks like your plugin is not injected in the platform side. Make sure you `flutter clean`, quit your IDE and re-run your app. Just a simple hot reload/restart won't do it.

@RollyPeres I ran `flutter clean`, closed my IDE, restarted the app, and still got the same error.

**Comment by RollyPeres** [comment]
Can you share a sample app ?

**Comment by Mo-rema07** [comment]
> Can you share a sample app ?

https://github.com/Mo-rema07/shades

**Comment by RollyPeres** [comment]
It seems your plugin was not registered as already mentioned.
If you compare https://github.com/Mo-rema07/shades/blob/master/android/app/src/main/kotlin/org/teal/shades/MainActivity.kt

to the official example: https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/example/android/app/src/main/java/io/flutter/plugins/googlesigninexample/EmbeddingV1Activity.java

although the default native language is different, you'll still notice you're missing the plugin registration.

Try removing the package and re-adding it, close the IDE and start your project again.
Make sure the plugin gets registered.

**Comment by Paul74** [comment]
@narcodico I have a very similar issue, from a PC that sits behind a proxy/firewall so I can't cast pub get. All is working except for this error.
What do you mean by "plugin not registered"? How can I register it by hand?
Thank you.

**Comment by langfield** [comment]
> It seems your plugin was not registered as already mentioned. If you compare https://github.com/Mo-rema07/shades/blob/master/android/app/src/main/kotlin/org/teal/shades/MainActivity.kt
> 
> to the official example: https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/example/android/app/src/main/java/io/flutter/plugins/googlesigninexample/EmbeddingV1Activity.java
> 
> although the default native language is different, you'll still notice you're missing the plugin registration.
> 
> Try removing the package and re-adding it, close the IDE and start your project again. Make sure the plugin gets registered.

Both of these links are dead.
