### ISSUE TITLE
Help/Question on using MultiBlocProvider does not rebuild widget.

### ISSUE THREAD

**Issue by chitgoks** [felangel/bloc#1288]
I got to using BlocProvider ok but later on, has forced me to use MultiBlocProvider because i have many bloc providers this time.

My problem is that while the bloc provider works ok, the widget does not rebuild after yield is called.

This is how my multiblocprovider looks like

```
@override
Widget build(BuildContext context) {
    return  MultiBlocProvider(
      providers: [
        BlocProvider<AgapeBloc>(create: (context) => AgapeBloc()),
        BlocProvider<ClientBloc>(create: (context) => ClientBloc()),
        BlocProvider<ClientStateListBloc>(create: (context) => ClientStateListBloc()),
        BlocProvider<LeadSourceListBloc>(create: (context) => LeadSourceListBloc()),
      ],
      child: MaterialApp(
         title: tr('app_name'),
        theme: themeProvider.getDarkMode() ? dark: light,
        home: _isLogged ? HomeScreen() : LoginScreen(),
      ),
    );
  }
```

Inside HomeScreen I call on some bloc provider events e.g.

`
BlocProvider.of<AgapeBloc>(context).add(AgapeEvent.get);`

which gets data from backend. it works ok but after yield is called, no rebuild happens. am i missing something? This is how the bloc provider looks like
```
class AgapeBloc extends Bloc<AgapeEvent, Agape> {

  @override
  Agape get initialState => Agape();

  @override
  Stream<Agape> mapEventToState(AgapeEvent event) async* {
    switch (event) {
      case AgapeEvent.get:
        Response res = await Web.getAgape();
        yield Agape.fromJson(res.data);
        break;
      case AgapeEvent.put:
        Response res = await Web.updateAgape(state.toJson());
        yield Agape.fromJson(res.data);
        break;
    }
  }

}

enum AgapeEvent { get, put }
```

**Comment by ram231** [comment]
Have you tested it with the debugger? And how did you handle it in your Bloc builder?

**Comment by chitgoks** [comment]
that's the problem :D i didnt use blocbuilder. i couldnt. it always gives a compile time error message e..g

Compiler message:
lib/screen/client_list_screen.dart:21:24: Error: 'ClienstBloc' isn't a type.
    return BlocBuilder<ClienstBloc, Client>(
                       ^^^^^^^^^^^
lib/screen/client_list_screen.dart:21:12: Error: Type argument 'invalid-type' doesn't conform to the bound 'Bloc<dynamic, S>' of the type variable 'B' on 'BlocBuilder'.
 - 'Bloc' is from 'package:bloc/src/bloc.dart' ('/C:/flutter/.pub-cache/hosted/pub.dartlang.org/bloc-4.0.0/lib/src/bloc.dart').
Try changing type arguments so that they conform to the bounds.
    return BlocBuilder<ClientBloc, Client>(

I have no idea why. my ClientBloc more or less contains the same code as AgapeBloc. if I use AgapeBloc in the BlocBuilder, the compile time error message disappears.

Here is my code for client bloc

```
class ClientBloc extends Bloc<ClientEvent, Client> {

  @override
  Client get initialState => Client();

  @override
  Stream<Client> mapEventToState(ClientEvent event) async* {
    switch (event) {
      case ClientEvent.get:
        Response res = await Web.getClient('');
        yield Client.fromJson(res.data);
        break;
      case ClientEvent.newly:
        yield Client();
        break;
      case ClientEvent.post:
        Response res = await Web.addClient(state.toJson());
        yield Client.fromJson(res.data);
        break;
      case ClientEvent.put:
        Response res = await Web.updateClient(state.toJson());
        yield Client.fromJson(res.data);
        break;
    }
  }

}

enum ClientEvent { get, newly , post, put }
```

**Comment by chitgoks** [comment]
i found the bug. just weird. my imported file is Client.dart instead of client.dart

i have no idea how android studio renamed it to Client.dart with a capital C.
