### ISSUE TITLE
Italian localization of the documentation

### ISSUE THREAD

**Issue by albertodev01** [felangel/bloc#1306]
I see that the official documentation (https://bloclibrary.dev) has been internationalized in many languages but Italian is not there.

May I ask if I could help translating the contents into italian?

**Comment by felangel** [comment]
Hey @albertodev01 👋 

There isn't an Italian translation in progress that I know of. That would be amazing! Let me know if there's anything I can help with and thanks for offering to contribute, I really appreciate it! 🙏  💙

**Comment by albertodev01** [comment]
Which are the next steps if I wanted to help? 😃 
I guess there's a file I need to localize?

**Comment by felangel** [comment]
Check out the [contributing to documentation](https://github.com/felangel/bloc/blob/master/CONTRIBUTING.md#contributing-to-documentation) steps and let me know if anything is unclear.

**Comment by albertodev01** [comment]
It's all good thank you! 
I'll do my best for a good localization

**Comment by felangel** [comment]
Closing this for now since there hasn't been much activity recently and there have been significant documentation updates. Feel free to create new issues to track the progress of each section, thanks! 🙏

**Comment by Giovanni-Fantin** [comment]
Do you have any news?
