### ISSUE TITLE
Do you have any idea to use multi bloc instances of same class type？

### ISSUE THREAD

**Issue by YukiKamada** [felangel/bloc#1314]
Thank you for wondeful bloc lib.
I was so impressed.

Now I worry about that there is any idea to use multi bloc instances of same class type.
What I would like to do is like below.
1.add tabs to flutter_infinite_list of your sample.
2.in tab page, I would like to show only post of same user.
   For example, 1st tab page shows onlye user1 posts, 
   and 2nd tab page shows only user2 posts.

I think above two tab page can use same bloc class, setting user id to bloc.
But I noticed that I could not use two blocs of same class type at once.

Do you have any idea to implement this using your bloc library?

**Comment by RollyPeres** [comment]
Hi @YukiKamada 👋

For your specific use case it will work to specify multiple blocs of the same type, because you'll be scoping them to different sub-trees.

```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  runApp(TabBarDemo());
}

class TabBarDemo extends StatelessWidget {
  final List<String> users = ['YukiKamada', 'Felix', 'Rolly'];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: users.length,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                for (final user in users) Tab(text: user),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              for (final user in users)
                BlocProvider<PostsBloc>(
                  create: (_) => PostsBloc(userId: user),
                  child: _TabPage(),
                ),
            ],
          ),
        ),
      ),
    );
  }
}

class _TabPage extends StatelessWidget {
  const _TabPage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<PostsBloc, PostsState>(
      builder: (_, state) {
        return Center(
          child: Text('Posts for ${state.userId}'),
        );
      },
    );
  }
}

// * events
@immutable
abstract class PostsEvent {}

// * states
@immutable
class PostsState {
  const PostsState({@required this.userId});

  final String userId;
}

// * bloc
class PostsBloc extends Bloc<PostsEvent, PostsState> {
  PostsBloc({@required this.userId});

  final String userId;

  @override
  PostsState get initialState => PostsState(userId: userId);

  @override
  Stream<PostsState> mapEventToState(
    PostsEvent event,
  ) async* {
    // TODO: implement mapEventToState
  }
}

```

**Comment by YukiKamada** [comment]
Hi @RollyPeres 

Thank you for your help.

I understand bloc scope is import!
I also wonder that parent widget(top of widget tree, like appBar) can not access bloc by BlocProvider.of.
Is this correct?

**Comment by RollyPeres** [comment]
It can't access `PostsBloc` with that setup. But you'd manage users in a different bloc anyways, which you can provide on top of the screen.

**Comment by YukiKamada** [comment]
Thanks for your quickly answer!
I'll reconsider widget tree and bloc archtecture of my app.
