### ISSUE TITLE
Question: global state/provider/data

### ISSUE THREAD

**Issue by sergeyplishka** [felangel/bloc#1315]
Thank you for good library.
I am new in flutter and mobile dev., so sorry for such question.
I need to store global objects (different cached info, data, user settings) and have global methods (utils) in the whole app scope and have access to it from any place of code (any bloc).
How I should do this?
Maybe make static class with static properties and methods or there is a way using repository or data provider? Or make one block and inject in globally?
What app structure to use in this case?
What is the best way you think? And how to use it in your bloc lib approach?
You have no examples for this or I have not found it...
Thank you for great job!

**Comment by RollyPeres** [comment]
Hi @sergeyplishka 👋

It all depends on the type of data you need and whether you only need it globally available or also cached.
For example user details could be made available through a global `AuthenticationBloc`. Please check out this [example](https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login) for an actual implementation.

If you need to provide some data through a bloc and also cache that data you could make use of `HydratedBloc` which will automatically cache your state. This is a good choice for something like `SettingsBloc`.

Hope that helps 👍

**Comment by sergeyplishka** [comment]
Thank you for advise.
Where global blocks are stored?
Should it be initialized in build method or BlockProvider will keep it alive?
Do you know where to get examples?

**Comment by RollyPeres** [comment]
The bloc instance is cached by the `BlocProvider` between rebuilds(through `provider`). You should initialize each bloc based on where it's needed, usually at the lowest common ancestor widget of all the sub-trees that need access to it.

You can find a lot of examples [here](https://github.com/felangel/bloc/tree/master/examples) 👍

**Comment by sergeyplishka** [comment]
So I can have a lot of blocs and provide it in root widget, then use necessary if I need in any child widget. Are these blocks cached even between switching between application in Android/iOS?
My questing is - can I not worry about necessity to reload all data if user switching between applications?

**Comment by RollyPeres** [comment]
I wouldn't recommend creating all blocs as global ones, it's between to scope them exactly where it's needed.

Blocs are cached during application lifetime, unless we are talking about `HydratedBloc` which caches between application startups too(aka when you kill an app and you start it again).

**Comment by sergeyplishka** [comment]
Excellent! Thanks for support! This ticket can be closed.
Have a good day, guys.
