### ISSUE TITLE
Lack of examples for nesting blocs and complex apps.

### ISSUE THREAD

**Issue by 1g0rrr** [felangel/bloc#1316]
Hi, I can't find how to deal with nested blocs in documentation and in examples list. Spend a lot of time but made sort of Frankenstein.
For example, if I have a todo app where tasks - also need to be blocs:

![Image 3](https://user-images.githubusercontent.com/51457/85024193-72e7a200-b17e-11ea-9315-e9b499e5b2f2.jpg)

Here is a couple of the problems I encountered. Can we discuss it?
1. I want to manipulate with all tasks from TodosListBloc. To make this, I decided to create an array of TaskBloc-s right inside TodosListBloc. I can't create TaskBloc with regular BlocProvider because I need some link to it in TodosListBloc. And "BlocProvider.of" - can't grab something which is lower in the widget tree.
Is this a good idea to create an array of blocks right inside another bloc?

2. Each time when database updates I download JSON. So according to it, It's necessary to create a new array of TaskBlocs each time database gets updated.
Is this a good idea to create this array of blocks many times on every database update? If so how I can safely delete the old array of blocs?

3) Any tips on how to architect the app from the image in general?

**Comment by 1g0rrr** [comment]
I made a sample app to show this:
https://github.com/1g0rrr/architecture_training_no_repo
I can transform it into a complete example after finding best solution.

**Comment by felangel** [comment]
Hi @1g0rrr 👋
Thanks for opening an issue!

You can check out [this todos app](https://github.com/felangel/bloc_todos) for a more complex example with a bloc for each todo item. Let me know if that helps 👍

**Comment by felangel** [comment]
@1g0rrr can you take a look at the app I linked above and let me know if that helps? Thanks 🙏

**Comment by 1g0rrr** [comment]
@felangel Of course. I’ve been doing this since yesterday. This is exactly what I need. There are also many good code tricks to follow.
It is strange that I did not find it on my own. I was looking in bloclibrary.dev in Tutorial section, in this repo in the examples folder and in google by 'flutter nested blocs' query and not found your link. )
Perhaps it could be placed inside tutorials.

**Comment by felangel** [comment]
Awesome! Glad it helped and I’ll try to incorporate it into the tutorials when I have time 👍
