### ISSUE TITLE
[Feature Request] Hydrated blocs with different storages in the same app

### ISSUE THREAD

**Issue by ncuillery** [felangel/bloc#1317]
**Is your feature request related to a problem? Please describe.**
I have some hydrated blocs that use the default temp folder (as a cache for my information coming the network: perform the fetching request only if the data is older than 12 hours).
But I also would like to use a hydrated bloc using the shared preferences storage to store my user preferences such as language, newsletter optin, etc.
I can't do that because, if I implement a custom storage in a BlocDelegate, all my blocs will use this storage.

**Describe the solution you'd like**
I guess one solution would be to not using BlocDelegate for implementing custom storage. Or improve the BlocSupervisor/BlocDelegate API to allow multiple BlocDelegates.

**Additional context**
I think I'd have the same problem if I already use a SimpleBlocDelegate for logging purpose and I want to write an other BlocDelegate for custom hydrated bloc storage.

**Comment by felangel** [comment]
Hi @ncuillery 👋 
Thanks for opening an issue!

I moved this issue to the hydrated_bloc repository and will start brainstorming some potential solutions 👍

**Comment by ncuillery** [comment]
Thanks! Didn't realized hydrated_bloc has its own repo 🤦

**Comment by felangel** [comment]
No worries haha!
