### ISSUE TITLE
Question: Tab Change BlocBuilder Even with AutomaticKeepAliveClientMixin

### ISSUE THREAD

**Issue by chitgoks** [felangel/bloc#1319]
I wish to ask since there is no posting in any closed issues 
Tab changes with no rebuild happen if you apply AutomaticKeepAliveClientMixin.

However, when I integrate BlocBuilder it keeps rebuilding when i change tab. And no, it's not because condition property is called. It does not get called. it goes right ahead to rebuilding the widget again.

Thoughts?

**Comment by RollyPeres** [comment]
Hi @chitgoks 👋

`AutomaticKeepAliveClientMixin` doesn't affect rebuilding, all it does in your case is making sure the widget doesn't get disposed when switching tabs.

`BlocBuilder` is not responsible for rebuilds triggered by flutter itself, which is the case when you're switching tabs.

Hope that helps 👍

**Comment by chitgoks** [comment]
hi rolly thank you for getting back. much appreciated.

using AutomaticKeepAliveClientMixin without blocbuilder, works. the widget does not rebuild when switching tabs. putnin some print() in build and it doesnt print so it works.

im confused why when i insert BlocBuilder it rebuilds. this looks like its all flutter but hopefully can shed light why it behaves like this wyen blocbuildet is used?

**Comment by chitgoks** [comment]
i think i get your point. probably because on tab change i call setState to keep track of the tab controller status

hence the rebuild. closing this.
