### ISSUE TITLE
Firebase phone Auth with Flutter_bloc Incompatible logic process

### ISSUE THREAD

**Issue by leenorshn** [felangel/bloc#1320]
You make the firebase email/password login logic very clear and easy. But when I try to use flutter_bloc with firebase PhoneAuth it become hard and confused 😕 . The step to define Events and State.
Can you please explain it?

**Comment by felangel** [comment]
Hi @leenorshn  👋
Thanks for opening an issue!

I can definitely add phone authentication to the example but in the meantime can you provide more information around what you are stuck on and what you have tried? Thanks 👍

**Comment by felangel** [comment]
@leenorshn can you please provide more information or have you been able to resolve the issue?

**Comment by felangel** [comment]
Closing for now since I don't have enough information to help. Please feel free to comment with additional information and I'm happy to continue the conversation 👍
