### ISSUE TITLE
Add built in wrappers for BlocProvider + BlocConsumer/BlocBuilder...

### ISSUE THREAD

**Issue by VictorUvarov** [felangel/bloc#1321]
**Is your feature request related to a problem? Please describe.**
I and some other developers prefer to have a skeleton outline of each view in one file.
For example a `home_view.dart`

```dart
class _HomeView extends StatelessWidget {
  const _HomeView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<HomeViewBloc, HomeViewState>(
      bloc: HomeViewBloc(),
      builder: (BuildContext context, HomeViewState state) {
        return Scaffold(
          appBar: AppBar(
            title: Text(S.of(context).homeViewTitle),
          ),
          body: state.map(
            loading: (_) => HomeViewLoading(
              key: WidgetKeys.loading,
            ),
            loaded: (loaded) => HomeViewLoaded(
              key: WidgetKeys.loaded,
              user: loaded.user,
            ),
            error: (_) => HomeViewError(
              key: WidgetKeys.error,
            ),
          ),
        );
      },
    );
  }
}
```

However this becomes a problem when adding something that uses the bloc to add an event directly in the `builder` method.
For example a FloatingActionButton:
```dart
class _HomeView extends StatelessWidget {
  const _HomeView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<HomeViewBloc, HomeViewState>(
      bloc: HomeViewBloc(),
      builder: (BuildContext context, HomeViewState state) {
        return Scaffold(
          appBar: AppBar(
            title: Text(S.of(context).homeViewTitle),
          ),
          body: state.map(
            loading: (_) => HomeViewLoading(
              key: WidgetKeys.loading,
            ),
            loaded: (loaded) => HomeViewLoaded(
              key: WidgetKeys.loaded,
              user: loaded.user,
            ),
            error: (_) => HomeViewError(
              key: WidgetKeys.error,
            ),
          ),
          floatingActionButton: FloatingActionButton(
            key: WidgetKeys.refresh_button,
            child: Icon(Icons.refresh),
            onPressed: () {
              final bloc = context.bloc<HomeViewBloc>(); // This fails, because this context doesn't have the bloc yet
              bloc.add(HomeViewEvent.reloadUser());
            },
          ),
        );
      },
    );
  }
}
```
The simplest solution has been to just separate the view into its own widget and wrap with with a `BlocProvider`:
```dart
class HomeView extends StatelessWidget {
  const HomeView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider<HomeViewBloc>(
      create: (context) => HomeViewBloc(),
      child: _HomeView(),
    );
  }
}

class _HomeView extends StatelessWidget {
  const _HomeView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<HomeViewBloc, HomeViewState>(
      bloc: context.bloc<HomeViewBloc>(),
      builder: (BuildContext context, HomeViewState state) {
        return Scaffold(
          appBar: AppBar(
            title: Text(S.of(context).homeViewTitle),
          ),
          body: state.map(
            loading: (_) => HomeViewLoading(
              key: WidgetKeys.loading,
            ),
            loaded: (loaded) => HomeViewLoaded(
              key: WidgetKeys.loaded,
              user: loaded.user,
            ),
            error: (_) => HomeViewError(
              key: WidgetKeys.error,
            ),
          ),
          floatingActionButton: FloatingActionButton(
            key: WidgetKeys.refresh_button,
            child: Icon(Icons.refresh),
            onPressed: () {
              final bloc = context.bloc<HomeViewBloc>();
              bloc.add(HomeViewEvent.reloadUser());
            },
          ),
        );
      },
    );
  }
}
```

**Describe the solution you'd like**
I am wondering if it would be feasible to add another widget or factory constructor to `BlocConsumer` / `BlocBuilder` to make these widgets wrap whatever widget comes in with a `BlocProvider<Bloc>(create: (context) => Bloc())` and expose a builder like this:
```dart
BlocConsumerWrapped<Bloc, BlocState>(
  builder: (BuildContext context, Bloc bloc, BlocState state){
    return ...;
  },
)
```

**Describe alternatives you've considered**
- Wrapping each view with a BlocProvider
- Writing the wrapper for BlocConsumer and BlocProvider
- Wrap views in builders where needed

**Additional context**
This is inspired from @FilledStacks on Youtube with his [Stacked](https://github.com/FilledStacks/stacked/blob/master/packages/stacked/lib/src/view_model_builder.dart) package that wraps provider to conform to MVVM architecture but without two way binding between the view and view model. There is a ViewModelBuilder that wraps `ChangeNotifierProvider` from the provider package and adds the provided `ChangeNotifier` to the builder method.

**Comment by VictorUvarov** [comment]
I'm not sure if this is the best way of implementing these wrappers, but here is my `BlocProviderBuilder`
```dart
class BlocProviderBuilder<B extends Bloc<dynamic, S>, S>
    extends BlocBuilderBase<B, S> {
  /// The [builder] function which will be invoked on each widget build.
  /// The [builder] takes the `BuildContext`, the provided [bloc] and current [state] and
  /// must return a widget.
  /// This is analogous to the [builder] function in [StreamBuilder].
  final Widget Function(BuildContext context, B bloc, S state) builder;

  const BlocProviderBuilder({
    Key key,
    @required this.builder,
    B bloc,
    BlocBuilderCondition<S> condition,
  })  : assert(builder != null),
        super(key: key, bloc: bloc, condition: condition);

  @override
  Widget build(BuildContext context, S state) {
    return BlocProvider(
      create: (c) => bloc,
      child: builder(context, bloc, state),
    );
  }
}
```
`BlocProviderConsumer` will follow the same logic

**Comment by RanaOsamaAsif** [comment]
+1 For this. 

I'm also trying to integrate Bloc in my flutter application and wrapping a widget in a BlocBuilder or BlocConsumer is one thing but providing the bloc to that widget to dispatch events gets kinda cumbersome using the BlocProvider procedure specially for small widgets such as a button which is a part of a hierarchy of a large widget tree.

**Comment by felangel** [comment]
Hi @VictorUvarov 👋
Thanks for opening an issue!

I wouldn’t recommend the first approach because you should ideally not create and consume a bloc in the same widget. By keeping the creation and consumption internal to a widget you make it a lot harder to widget test as you are unable to inject a mock bloc for the widget to use. In addition, in the first snippet you are creating a new bloc in the build and passing it to BlocBuilder which means each time your widget is rebuilt, the bloc will be recreated and your old state will be lost.

I would highly recommend providing the bloc to the widget that needs it so that your code is a lot more testable. Also, if you really want to accomplish this you can just use a Builder widget to create a new BuildContext and the lookup will work.

```dart
Builder(
  builder: (context) {
    return FloatingActionButton(
      onPressed: () => context.bloc<MyBloc>(),
    );
  }
)
```

Let me know if that helps 👍

**Comment by VictorUvarov** [comment]
I see so having the bloc separate from the widget would be the best solution for mocking the bloc?
```dart
class HomeView extends StatelessWidget {
  const HomeView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider<MockHomeViewBloc>(
      create: (context) => MockHomeViewBloc(),
      child: _HomeView(),
    );
  }
}
```

**Comment by felangel** [comment]
Yes and I would recommend using a different naming convention like `HomePage` for the parent and `HomeView` for the child. This way the `HomePage` is responsible for providing the correct blocs to `HomeView` and `HomeView` is responsible for consuming the bloc and building the correct UI.

```dart
class HomePage extends StatelessWidget {
  const HomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => MyBloc(),
      child: HomeView(),
    );
  }
}

class HomeView extends StatelessWidget {
  const HomeView({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<MyBloc, MyState>(
      builder: (context, state) { ... }
    );
  }
}
```

Then you can widget test `HomePage` to make sure that it renders `HomeView` and you can widget test `HomeView` by providing a fake bloc like:

```dart
class MockMyBloc extends MockBloc<MyEvent, MyState> implements MyBloc {}

group('...', () {
  MyBloc bloc;
  
  setUp(() {
    bloc = MockMyBloc();
  });

  testWidgets('...', (tester) async {
    when(bloc.state).thenReturn(SomeState());
    await tester.pumpWidget(
      BlocProvider.value(value: bloc, child: HomeView()),
    );
  });
});
```

Hope that helps! Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
