### ISSUE TITLE
Ensure bloc1 data is available before bloc2 action is run

### ISSUE THREAD

**Issue by chitgoks** [felangel/bloc#1326]
hi. i cant give a good title but hopefully the explanation can help you understand.

i have bloc1 and bloc2. where bloc1 needs some data in bloc2.

if possible bloc1 will wait executing its action until the bloc2 state data has been populated?

right now i can think of calling bloc2 action and then bloc1 action sequentially since they both call await futures.

but im not sure if this is a good approach.

**Comment by RollyPeres** [comment]
Hi @chitgoks 👋

You could have a `BlocListener` where you listen for bloc2 state and whenever the proper state is emitted, let's say `Bloc2DataLoaded` you could add an event on bloc1 e.g.: `context.bloc<Bloc1>().add(Bloc2DataSuccessfullyLoaded());`

Hope that makes sense 👍

**Comment by chitgoks** [comment]
hi ro
