### ISSUE TITLE
Question regarding API request

### ISSUE THREAD

**Issue by jaydangar** [felangel/bloc#1330]
This is another Question regarding sending API request from bloc.

```
return BlocProvider(
      create: (context) {
        NetworkCallBloc _networkingBloc = NetworkCallBloc();
        **_networkingBloc.add(FetchDataEvent());**
        return _networkingBloc;
      }
```

As you can see here, I am calling api in creation of the bloc, which is by using FetchDataEvent() function, is it okay to use it? or is there any better alternative for putting a code to call api request?

**Comment by RollyPeres** [comment]
Hi @jaydangar 👋

A more concise way would be:

```
BlocProvider(
      create: (_) => NetworkCallBloc()..add(FetchDataEvent())
)
```

**Comment by felangel** [comment]
Hi @jaydangar 👋 
Thanks for opening an issue!

This approach is totally fine but there are a couple of things to note:

1. By default blocs are creating `lazily` so the `create` method won't actually get executed until the bloc is looked up either by `BlocProvider.of<NetworkCallBloc>(context)` or by a `BlocBuilder`/`BlocListener`/`BlocConsumer`. If you want `create` to be executed immediately, set `lazy` to false like:

```dart
BlocProvider(
    lazy: false,
    create: (_) => NetworkCallBloc()..add(FetchDataEvent())
    child: ...
)
```

2. As @rollyperes mentioned you can make it more concise by chaining the add 👍 

Hope that helps!

Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 😄

**Comment by jaydangar** [comment]
Great didn't thought of it, thanks. And is it good practice to do api call within bloc creation???

**Comment by jaydangar** [comment]
Great @felangel @RollyPeres and thanks for the response.

**Comment by felangel** [comment]
@jaydangar typically your bloc should be named after a feature or use-case and depend on one or more repositories. The repositories should consume one or more data-providers or API clients. You can read more about this in the [architecture docs](https://bloclibrary.dev/#/architecture).

**Comment by jaydangar** [comment]
@felangel , I didn't understand the presentation layer part. It says AppStarted event will be triggered when I start my application, but what if I need to fetch data on start of the page?? can you kindly elaborate on this?

**Comment by RollyPeres** [comment]
> And is it good practice to do api call within bloc creation???

Bloc works by adding events to it and these events can be translated into API calls and/or bloc state/s.
Bloc is not opinionated about what you should do as a result of an event hitting bloc.

**Comment by felangel** [comment]
@jaydangar same thing applies to page loads. You can have a feature bloc like `FavoritesBloc` and add an event like `FavoritesStarted` when the page is created (within the `create` of the `BlocProvider`).

**Comment by jaydangar** [comment]
@felangel Thanks, I got my all the answers.
