### ISSUE TITLE
Listener Not Calling for Pull to Refresh if the data is not changed.

### ISSUE THREAD

**Issue by spike04** [felangel/bloc#1343]
Hi there,

I tried the example of pull-to-refresh from weather example and implemented it to pull the list of data from the server with a fixed set of data. Implementation was straight forward and also implemented the _refreshCompleter login in BlocConsumer.

While trying to perform Pull to refresh operation, Log shows that request was made successfully but since the data was the same as before, BlocComsumer was not called hence the refresh indicator kept on show. Later I tried the API call for Refresh with different page numbers providing new sets of data, the example worked and the refresh indicator was gone as aspected. 

Is there any workaround or a solution, cause refresh Indicator is stuck if the data does not change.

**Comment by felangel** [comment]
Hi @spike04 👋 
Thanks for opening an issue! Blocs ignore duplicate states internally so if you wish to have the state always be emitted you can either avoid extending Equatable or add a property like `DateTime lastUpdate` to your weather model.

Hope that helps 👍
