### ISSUE TITLE
Boilerplate reduce

### ISSUE THREAD

**Issue by GoltVik** [felangel/bloc#1344]
**Is your feature request related to a problem? Please describe.**
When you use BlocProvider, BlocBuilder/Consumer/Listener can get Bloc from BuildContext and handle State changes, but if you want to add Even you still need to get it from the BuildContext `BlocProvider.of<Bloc>(context)`.

If you not providing Bloc you need to handle creation and closing by yourself.

In this cases the are a lot of boilerplate code what can be hidden in State itself.

**Describe the solution you'd like**
My solution is BlocState and ProvidedBlocState.
This actually State classes but with Bloc inside what you can use to handle state and add events.

**BlocState** provide bloc field with Bloc of this widget and stateBloc function to create it. 
BlocState handles creation in `initState` method and closing in `dispose` method.

**ProvidedBlocState** provide bloc field with actually Bloc too, but State getting Bloc from BuildContext under the hood. 
BlocState don't need to handle creation and closing because BlocProvider handles it.

**Describe alternatives you've considered**
As alternative this functionality can be implemented as a BlocMixin.

PR for this: https://github.com/felangel/bloc/pull/1342

**Comment by felangel** [comment]
Hi @GoltVik 👋 
Thanks for opening an issue!

Can you please provide an example of a scenario that you're describing and hope to improve with the PR? It would really help me to see the current implementation that you have in order to better understand the context 👍

**Comment by GoltVik** [comment]
Hi @felangel 👋

Sure ! This is simple counter page with provided Bloc with BlocProvider

```
class CounterPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Counter')),
      body: BlocBuilder<CounterBloc, int>(
        builder: (_, count) {
          return Center(
            child: Text(
              '$count',
              style: const TextStyle(fontSize: 24.0),
            ),
          );
        },
      ),
      floatingActionButton: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              child: const Icon(Icons.add),
              onPressed: () =>
                  context.bloc<CounterBloc>().add(CounterEvent.increment),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              child: const Icon(Icons.remove),
              onPressed: () =>
                  context.bloc<CounterBloc>().add(CounterEvent.decrement),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              backgroundColor: Colors.red,
              child: const Icon(Icons.error),
              onPressed: () => context.bloc<CounterBloc>().add(null),
            ),
          ),
        ],
      ),
    );
  }
}
```
and this is with how its looks like with ProvidedBlocState:

```
class CounterPage extends StatefulWidget {
  @override
  _CounterPageState createState() => _CounterPageState();
}

class _CounterPageState extends ProvidedBlocState<CounterPage,CounterBloc> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Counter')),
      body: BlocBuilder<CounterBloc, int>(
        builder: (_, count) {
          return Center(
            child: Text(
              '$count',
              style: const TextStyle(fontSize: 24.0),
            ),
          );
        },
      ),
      floatingActionButton: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              child: const Icon(Icons.add),
              onPressed: () => bloc.add(CounterEvent.increment),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              child: const Icon(Icons.remove),
              onPressed: () => bloc.add(CounterEvent.decrement),
            ),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              backgroundColor: Colors.red,
              child: const Icon(Icons.error),
              onPressed: () => bloc.add(null),
            ),
          ),
        ],
      ),
    );
  }
}
```

Everytime when you want to add Event you need to get it from BuildContext `context.bloc<CounterBloc>()` with State you just using `bloc`

**Comment by felangel** [comment]
@GoltVik Thanks for sharing! I'm wondering how would you go about writing widget tests for the `CounterPage` with this approach? It seems like the widget is too tightly coupled with the bloc. Thanks 👍

**Comment by ram231** [comment]
How can you share this with other pages(scaffold)?

**Comment by GoltVik** [comment]
@felangel , good case for BlocState is Flutter package with widgets. Creating widgets it's good to have explicit bloc to each widget and you don't need to be provided into widget tree.  

The problem with BlocProvider is that BlocProvider child don't have BuildContext with provided bloc and you need to use builder widgets like LayoutBuilder to get BuildContext with bloc.

So with BlocState you don't need to get bloc from context or use proxy widgets, just use bloc where you want :)

**Comment by felangel** [comment]
@GoltVik I totally understand but there are several problems I see:

- This approach is not very testable; the creation of the bloc is done internally so there's not an easy way to write a widget test with a `MockBloc`.
- How would this approach scale with multiple blocs (if my widget needs `BlocA` and `BlocB`)?

**Comment by GoltVik** [comment]
@felangel 

- Actually BlocState provides a creation method called `stateBloc(BuildContext context)` so you can easily provide `MockBloc`

- But yes, this approach not suits for multiple blocs  🤔
