### ISSUE TITLE
[Question] Listen to a bloc globally while having access to the Navigator

### ISSUE THREAD

**Issue by andresemartinez** [felangel/bloc#1345]
Hi Felix, first of all tnks for this awesome library!! And for taking the time to help us.

I'm trying to handle all the 401 and 403 of any http request globally, because if that happens i need to redirect to the login page. I was thinking of using a global AuthenticationBloc to achive this but i'm stuck on where tu put the BlocListener. I could add the BlocListener<AuthenticationBloc> as parent of the MaterialApp but then I don't have access to the context that has de Navigator, or i could add it to every route, wich i think doesnt scale easily.

A simplified viersion of my code:

```
class AuthenticationBloc extends Bloc<AuthenticationEvent, AuthenticationState> {
    final AuthenticationRepository authenticationRepository;

    AuthenticationBloc({
        @required this.authenticationRepository,
    }) : assert(authenticationRepository != null);
    
    @override
    AuthenticationState get initialState => UninitializedState();
   
    @override
    Stream<AuthenticationState> mapEventToState(AuthenticationEvent event) async* {
        if (event is AppStartedEvent) {
            yield* _mapAppStartedToState();
        } else if (event is LoggedInEvent) {
            yield* _mapLoggedInToState();
        } else if (event is LoggedOutEvent) {
            yield* _mapLoggedOutToState();
        } else if (event is AuthenticationExpiredEvent) {
            yield* _mapAuthenticationExpiredToState();
        }
    }
}
```

```
BlocListener<AuthenticationBloc, AuthenticationState>(
    listener: (BuildContext context, AuthenticationState state) {
        if (state is UnauthenticatedState) {
            Navigator.of(context).pushNamedAndRemoveUntil(LoginPage.pageRoute, (_) => false);
        }
    },
   child: SomeOtherPage(),
}
```

So when any repository throws an AuthenticationExpiredException then the bloc that called that repository sends an AuthenticationExpiredEvent to the AuthenticationBloc and the listener Navigates to the LoginPage.

Can you think of a configuration that could handle this situation whitout having to repeat that listener in every page?

Tnks in advance.
Andrés.

**Comment by felangel** [comment]
Hi @andresemartinez 👋 
Thanks for opening an issue and for the positive feedback!

I would highly recommend taking a look at the [fresh_dio example](https://github.com/felangel/fresh/tree/master/packages/fresh_dio/example) for an example 👍 

Let me know if you have any questions 😄
