### ISSUE TITLE
how should bloc to bloc updates be handled? 

### ISSUE THREAD

**Issue by QAQyzk** [felangel/bloc#1346]
I want to update BlocA's state from BlocB. BlocB can have many different events and when the output state of the event is LoadSuccess, it should call update function to update state in BlocA. One way I can think of is add the update function at end of every event in BlocB, is there any better way I can handle this?

**Comment by felangel** [comment]
Hi @QAQyzk 👋 
Thanks for opening an issue!

The simplest way would be to use a `BlocListener`:

```dart
BlocListener<BlocB, BlocBState>(
  listener: (context, state) {
    if (state is LoadSuccess) {
      // trigger update in BlocA
      context.bloc<BlocA>().add(...);
    }
  },
  child: ...
)
```

Hope that helps 👍

**Comment by QAQyzk** [comment]
Hi @felangel

Thank you! That work like a charm!

Just a additional question, is it possible to do it within the bloc class? So that I don't need to handle the update in the widget tree. 
For example, use the LoadSuccess state constructor to perform the update like this:
```
class LoadSuccess extends BlocB {
  final VoidCallback updateFunction;
  
  LoadSuccess({this.updateFunction}) {
    if (updateFunction != null) {
      updateFunction();
    }
  }
}
```
or this is considered to be a bad practice?

**Comment by ncuillery** [comment]
@QAQyzk I think that kind of logic doesn't belong to the state which is really just a data holder. But you can achieve what you want outside the widget tree: your BlocA can be a constructor argument of BlocB. So you have access to BlocA inside BlocB.

See https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication

Note: the example below shows BlocA listening to BlocB state's change and updating, but you can totally have BlocB firing a BlocA event.

**Comment by QAQyzk** [comment]
@ncuillery Thanks for your help. I agree that state shouldn't handle logics, but when I tries to firing the update function from BlocB I found myself need to call the same update function everytime I add a new event that can trigger a load success state. So I think I will do what felangel suggest to update BlocA.
