### ISSUE TITLE
Adding multiBlocBuilder interface

### ISSUE THREAD

**Issue by mohammadne** [felangel/bloc#1347]
if it is possible , please add ```MultiBlocBuilder``` like ```MultiBlocProvider```.
I think it is necessary.

and then we can have sth like ```Rx.combine```

**Comment by felangel** [comment]
Hi @mohammadne 👋
Thanks for opening an issue!

This is a duplicate of https://github.com/felangel/bloc/issues/538 so I will close this but feel free to continue the discussion on the original issue, thanks 🙏
