### ISSUE TITLE
Specify a bloc scoped to a single widget

### ISSUE THREAD

**Issue by anasmano** [felangel/bloc#1350]
Hello,
 
I wanted to provide a bloc that will be scoped to a single widget and isn't accessible via a parent BlocProvider

final _blocA = blocA()

BlocBuilder<BlocA, BlocAState>(
  bloc: _blocA, // provide the local bloc instance
  builder: (context, state) {
    // return widget here based on BlocA's state
  }
)

My question is 
Should the _blocA be closed every time the widget is disposed?

Thanks.

**Comment by felangel** [comment]
Hi @anasmano 👋 
Thanks for opening an issue!

In this case, I would recommend making a StatefulWidget and managing the bloc like so:

```dart
class MyWidget extends StatefulWidget {
  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  final _bloc = MyBloc();

  @override
  void dispose() {
    _bloc.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) { ... }
}
```

Hope that helps 👍
