### ISSUE TITLE
Event is fired again

### ISSUE THREAD

**Issue by DeadlyMissile** [felangel/bloc#1352]
Hey there! 

So I have a row of buttons that animate when I click on them and they call an event that rebuilds a part of  my widget. I noticed that when I click on my button the second time (ie after it called the event) it will still call the event and so on. Should I be doing something about this or is Bloc smart enough to not rebuild the widget?

**Comment by felangel** [comment]
Hi @DeadlyMissile 👋 
Thanks for opening an issue!

Bloc will not rebuild the UI if the state emitted is the same as the previous state of the bloc. You can verify this by overriding `onTransition` and printing the transition

```dart
@override
void onTransition(Transition transition) {
  print(transition);
  super.onTransition(transition);
}
```

Let me know if that helps 👍

**Comment by DeadlyMissile** [comment]
I love you Felix
