### ISSUE TITLE
add event with dialog result

### ISSUE THREAD

**Issue by lironiz** [felangel/bloc#1355]
hi,
I have an alertDialog that returns a value. I want to add an event to my bloc with this value.

  ```
BlocListener<SymptomFormBloc, SymptomFormState>(
          listener: (context, state)  {        
           if(state is ShowDialog) {
              CustomDialog().show(context).then((value) =>
                  BlocProvider.of<SymptomFormBloc>(context).add(DialogResult(value)));
            }
              
          },
        )

```
I understand it's probably a context issue, so I tried to pass a different context to the dialog and the provider, but it's still not working, I get a "Looking up a deactivated widget's ancestor is unsafe". 
any thoughts?
thanks

**Comment by felangel** [comment]
Hi @lironiz 👋 
Thanks for opening an issue!

The following should work:

```dart
BlocListener<SymptomFormBloc, SymptomFormState>(
  listener: (context, state) async {
    if (state is ShowDialog) {
      final result = await CustomDialog().show(context);
      context.bloc<SymptomFormBloc>().add(DialogResult(result));
    }
  },
  child: ...
);
```

If you're still having trouble can you please share a link to a sample app on github which reproduces the issue? Thanks 👍

**Comment by pblinux** [comment]
Hi @felangel 

I'm having a similar problem with dialogs. I have a StatefulWidget and at some point I need to call my `action ()` method. Before calling the dialog, I can access the bloc without problems but after calling it, I get an error: 
`context! = Null ': is not true.` :thinking: 

```dart
void _action() async {
  print(context.bloc<MainBloc>().state.email); // prints the email
  final result = await _showDialog();
  print(context.bloc<MainBloc>().state.email); // throws exception
}
```
Is there a case where the context does not have the bloc available after using a dialog? 

Thank you
