### ISSUE TITLE
Test async Expect values like image fixtures

### ISSUE THREAD

**Issue by lunaticcoding** [felangel/bloc#1358]
**Is your feature request related to a problem? Please describe.**
Currently the expect field takes an iterable. I have an imageFixture that loads a local file and I want to use this fixture in my expect statement. 

**Describe the solution you'd like**
I extended the bloc_test to take an optional expectAsync field which takes an async function returning Future<Iterable>

**Describe alternatives you've considered**
Using normal tests. 

**Additional context**

**Comment by felangel** [comment]
Hi @lunaticcoding 👋 
Thanks for opening an issue!

See my comment on the PR https://github.com/felangel/bloc/pull/1359#issuecomment-651824689

**Comment by felangel** [comment]
Closing this
