### ISSUE TITLE
Migration guide to 5.0.0

### ISSUE THREAD

**Issue by Zazo032** [felangel/bloc#1378]
**Is your feature request related to a problem? Please describe.**
Migration from 4.0.1 to 5.0.0

**Describe the solution you'd like**
Provide some steps for different use cases

The specific case is, we have some code like this:

```dart
class SampleBloc extends Bloc<SampleEvent, SampleState> {
  String data;

  @override
  SampleState get initialState {
    data = 'initial data';
    if (hasExtraData)
      data += 'extra data';
    return SampleState(data);
  }
}
```

However, there's no trivial change to migrate that code. We have successfully migrated other `initialState` where it just returns a state, to provide them to `super` the constructor of the class.

**Comment by felangel** [comment]
Hi @Zazo032 👋 
Thanks for opening an issue!

I'm working on a formal migration guide and am aiming to have it published tomorrow. In the meantime for your use-case I would recommend the following:

```dart
class SampleBloc extends Bloc<SampleEvent, SampleState> {
  SampleBloc({String data, bool hasExtraData})
      : super(SampleState('initial data ${hasExtraData ? 'extra data' : ''}'));
}
```

Let me know if that helps 👍

**Comment by RollyPeres** [comment]
Hi @Zazo032 👋

Another approach besides the one suggested by @felangel is:

```
class SampleBloc extends Bloc<SampleEvent, SampleState> {
  final String data;

  SampleBloc(this.data): super((){
    if (hasExtraData)
      data += 'extra data';
    return SampleState(data);
}());
}
```

**Comment by Zazo032** [comment]
Both of those solutions is giving me the following analyzer error:

```
The instance member 'data' can't be accessed in an initializer. Try replacing the reference to the instance member with a different expression.
```

Note that, in that case, `data` cannot be passed as a parameter as it's computed within the `SampleBloc` class.

**Comment by felangel** [comment]
@Zazo032 can you please provide a sample bloc which more closely represents how your bloc is currently implemented?

**Comment by Zazo032** [comment]
@felangel I can privately send you a small real code snippet to the email on your profile, is that ok?

**Comment by felangel** [comment]
@Zazo032 can you make a private repository and invite me instead?

**Comment by Zazo032** [comment]
Done! I uploaded the conflicting file for the migration.

**Comment by felangel** [comment]
Got the invite but it’s really late here so I’ll take a look first thing in the morning! 😴

**Comment by Zazo032** [comment]
Thanks! No hurries 😊

**Comment by felangel** [comment]
@Zazo032 I've created `migrated_bloc.dart` to illustrate how I would refactor your bloc 👍 
Also, for more information regarding migrating to v5.0.0 check out the [migration guide](https://bloclibrary.dev/#/migration).

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄
