### ISSUE TITLE
My item variable become null when i save my page or hot reloading

### ISSUE THREAD

**Issue by tazik561** [felangel/bloc#1380]
I have this bloc in my page:
```
class CategoriesPage extends StatelessWidget {
  List<CategoriesItem> catItems;
  List<CategoryItem> selectedCatItems;
```
     BlocBuilder<CategoriesBloc, CategoriesState>(
                builder: (context, state) {
              if (state is CategoriesInitial) {
                return Center(
                  child: CircularProgressIndicator(),
                );
              } else if (state is CategoriesStarted) {
                catItems = state.catItems;
              } else if (state is SelectedCategoryState) {
                selectedCatItems = state.catItems;
              }
              return Column(
                children: <Widget>[
                  Container(
                    height: 80,
                    color: Colors.green[500],
                    child: ListView.builder(
                      scrollDirection: Axis.horizontal,
                      shrinkWrap: true,
                      itemCount: catItems == null ? 0 : catItems.length,
                      itemBuilder: (context, index) {
                        return Row(
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: <Widget>[
                            InkWell(
                              onTap: () {
                                BlocProvider.of<CategoriesBloc>(context)
                                    .add(CategoryEvent(catItems[index].id));
                              },
                              child: Container(
                                  width: 100,
                                  height: 40,
                                  alignment: Alignment.center,
                                  decoration: BoxDecoration(
                                    borderRadius: BorderRadius.circular(8.0),
                                    color: Colors.green[300],
                                  ),
                                  child: Row(
                                    mainAxisAlignment:
                                        MainAxisAlignment.spaceAround,
                                    children: <Widget>[
                                      Icon(
                                        catItems[index].prefixIcon,
                                        color: Colors.white,
                                      ),
                                      Text(
                                        catItems[index].title,
                                        style: TextStyle(color: Colors.white),
                                      )
                                    ],
                                  )),
                            ),
                            SizedBox(
                              width: 16.0,
                            )
                          ],
                        );
                      },
                    ),
                  ),
                  Expanded(
                    child: ListView.builder(
                      itemCount:
                          selectedCatItems == null ? 0 : selectedCatItems.length,
                      itemBuilder: (context, index) {
                        return Container(
                          child: Row(
                            children: <Widget>[
                              Image.asset(
                                selectedCatItems[index].image,
                                width: 60,
                                height: 80,
                                fit: BoxFit.cover,
                              )
                            ],
                          ),
                        );
                      },
                    ),
                  )
                ],
              );
            }),

When app is started `CategoriesStarted` state return list of categories and i show this data in listview `Axis.horizontal`.After tap on one item i call `CategoryEvent` event and i got `SelectedCategoryState` state to get category information.

Everything is good till i do hot reload,When i save my page `catItems` is become null and my `horizontal` listview is gone!!!

Why catItems is become null ?and how can i fix that?

I also change my code to this https://pastebin.ubuntu.com/p/dCWMnsN2GQ/  but i still have  problem.when i tapped on TopCatList item, bloc  return Text('Something went wrong!');  on TopCatList class

**Comment by felangel** [comment]
Hi @tazik561 👋 
Thanks for opening an issue!

I believe the problem is you're maintaining state inside of a `StatelessWidget` which you should never do. What is happening is when you do a hot restart, the CategoriesPage is rebuilt and the `catItems` and `selectedCatItems` become null.

You should always reference the bloc state rather than maintaining duplicate state in your widget.

```dart
return BlocBuilder< CategoriesBloc, CategoriesState>(
  builder: (context, state) {
    if (state is CategoriesLoadSuccess) {
       final catItems = state.catItems;
       final selectedCatItems = state.selectedCatItems;
      // return correct widget here without storing state as separate member variables
    }
  },
)
```

Hope that helps 👍

**Comment by tazik561** [comment]
Thanks .
I have 2 state `CategoriesStarted` and `SelectedCategoryState`. When this page loaded `CategoriesStarted` load top horizontal categories.When user tap on one categoriy item bloc change it's state to `SelectedCategoryState` .till now every thing is ok.imagin i save again my page now last state is `SelectedCategoryState` and when `BlocBuilder<CategoriesBloc, CategoriesState>(` called again `CategoriesStarted` never called and `catItems` inside this state become null so it cause top  horizontal categories become disappear. 

In your code `selectedCatItems = state.selectedCatItems;` never fiiled when app is started. It is initialized when other state `SelectedCategoryState` accured.
Whit this two state how can i fix my broblem?
