### ISSUE TITLE
Is there a way to make sure that all Sink instances are correctly closed?

### ISSUE THREAD

**Issue by 0dysseas** [felangel/bloc#1381]
First off, let me just thank you for this immensely helpful piece of software you've created. It makes writing apps in Flutter a breeze.

Now, I have a question regarding BLOC memory leaks. It's well-known that the VS Code linter is erroneously displaying "Close instances of dart.core.Sink" messages. I know the way around this but I was wondering if there's also a way to test/make sure that my BLOCs are not leaking memory and that all `StreamController`  resources are correctly closed (i.e. freeing their resources) ?

**Comment by felangel** [comment]
Hi @0dysseas 👋 
Thanks for opening an issue and for the positive feedback, I really appreciate it!

Regarding your question, as you mentioned, the linter has a lot of false positives and is unreliable so unfortunately I am unaware of any tool which ensures Sinks are closed 😞 

The good news is as long as all blocs are created by a BlocProvider, you should have nothing to worry about 👍 

```dart
// GOOD
BlocProvider(
  create: (context) => MyBloc(),
  child: ...
)

// BAD
final bloc = MyBloc();
BlocProvider.value(
  value: bloc,
  child: ...
)
```

If you create blocs manually within `StatefulWidgets` then you need to also be sure to manually call `close` in the `dispose` override

```dart
class MyWidget extends StatefulWidget {
  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  final _bloc = MyBloc();

  @override
  Widget build(BuildContext context) { ... }

  @override
  void dispose() {
    _bloc.close();
    super.dispose();
  }
}
```

Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍
