### ISSUE TITLE
How to mock and test error when listening to a stream

### ISSUE THREAD

**Issue by VictorUvarov** [felangel/bloc#1382]
**Is your feature request related to a problem? Please describe.**
I'm having a hard time finding examples of mocking errors that come from a stream that the bloc is being listened to. 

**Describe the solution you'd like**
I would like to know how to mock a stream error when the bloc is listening to a stream. Example
```dart
_subscription = _someRepository.stream$.listen(
    _onUpdated,
    onError: _onError,
);
``` 
How would I mock the above?
I want to do something like this, but it seems wrong
```dart
when(_someRepository.stream$).thenAnswer((_) => Stream.value(Error()));
```

**Describe alternatives you've considered**
I've seen examples where the `_onUpdated` function would add a new event like 
```dart
add(SomePageEvent.updated());
```
not sure if I should also do the same for errors
```dart
add(SomePageEvent.errorUpdating());
```
**Additional context**

**Comment by felangel** [comment]
Hi @VictorUvarov 👋 
Thanks for opening an issue!

You should just be able to do something like:

```dart
when(_someRepository.stream$).thenAnswer((_) => Stream.error(Exception('some error')));
```

Hope that helps 👍
