### ISSUE TITLE
Why BLoC constructor must have a super declared

### ISSUE THREAD

**Issue by wailashraf71** [felangel/bloc#1388]
After updating to `flutter_bloc: ^5.0.0` I got errors on my whole 30 blocs tells me to declare a super:

> The superclass 'Bloc<ExampleEvent, ExampleState>' doesn't have a zero argument constructor.  Try declaring a zero argument constructor in 'Bloc<ExampleEvent, ExampleState>', or explicitly invoking a different constructor in 'Bloc<ExampleEvent, ExampleState>'.

Should I update every constructor manually, or this is just a bug?

**Comment by felangel** [comment]
Hi @wailashraf71 👋
Thanks for opening an issue!

This is not a bug. In v5.0.0 initialState was removed in favor of passing the initial state to super. Check out the [migration guide](https://bloclibrary.dev/#/migration) for more information 👍

**Comment by wailashraf71** [comment]
Oh, now I see thank you! hope you add the migration guide to the package on [pub.dev](pub.dev) change log😄

**Comment by felangel** [comment]
@wailashraf71 yup I can add it to the changelog 👍
It’s also on the home page at [bloclibrary.dev](https://bloclibrary.dev).
