### ISSUE TITLE
The superclass doesn't have a zero argument constructor.

### ISSUE THREAD

**Issue by gbond007** [felangel/bloc#1389]
The superclass 'Bloc<MyFormEvent, MyFormState>' doesn't have a zero argument constructor.
Try declaring a zero argument constructor in 'Bloc<MyFormEvent, MyFormState>', or declaring a constructor in MyFormBloc that explicitly invokes a constructor in 'Bloc<MyFormEvent, MyFormState>'. ???

**Comment by RollyPeres** [comment]
Hi @gbond007 👋

Starting with `v5.0.0` of bloc library the `initialState` was removed in favor of passing it to the `super` contructor.
Please have a look at the [migration guide](https://bloclibrary.dev/#/migration) 👍

**Comment by Brabalawuka** [comment]
> Hi @gbond007 👋
> 
> Starting with `v5.0.0` of bloc library the `initialState` was removed in favor of passing it to the `super` contructor.
> Please have a look at the [migration guide](https://bloclibrary.dev/#/migration) 👍

Yes but will there be an update to the Intellij Plugin so the constructore will be using the 5.0 version?

**Comment by gbond007** [comment]
Thanks so much.

**Comment by felangel** [comment]
> > Hi @gbond007 👋
> > Starting with `v5.0.0` of bloc library the `initialState` was removed in favor of passing it to the `super` contructor.
> > Please have a look at the [migration guide](https://bloclibrary.dev/#/migration) 👍
> 
> Hi RollyPeres,
> 
> Thanks for the answer!
> However will there be an update to the Intellij Plugin so the constructor will be using the 5.0 version?

Working on the IntelliJ update hopefully jetbrains will cooperate 😛🤞
