### ISSUE TITLE
How to use debounce timer with states

### ISSUE THREAD

**Issue by adar2378** [felangel/bloc#1390]
**Describe the bug**
I have this situation, where users can update the cart by pressing the add/remove button, so I added a debounce timer on the event stream.
The problem I'm facing with this,
 - Customer adds product 1, then between the denounce timer s/he adds another product, hence I'm losing the event where the user added product 1. I want to make sure that the debounce timer added only when the products are different.
- And when yielding the states, I want to add a denounce timer also. How can I do that?

Here's the debounce timer for events:
```
 @override
  Stream<Transition<CloudCartBlocEvent, CloudCartBlocState>> transformEvents(
      Stream<CloudCartBlocEvent> events, transitionFn) {
    return super.transformEvents(
        events.debounceTime(
          Duration(
            milliseconds: 250,
          ),
        ),
        transitionFn);
  }
```

**Comment by RollyPeres** [comment]
Hi @adar2378 👋

You probably want to `throttleTime` cart events instead of `debounceTime`.

As for debouncing states you can override `transformTransitions`:

```
 @override
  Stream<Transition<Event, State>> transformTransitions(
    Stream<Transition<Event, State>> transitions,
   ) {
    return transitions.debounceTime(Duration(seconds: 1));
  }
```

Hope that helps 👍

**Comment by felangel** [comment]
Thanks as always @RollyPeres!
@adar2378 closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍
