### ISSUE TITLE
Blocs will ignore duplicate states doubt

### ISSUE THREAD

**Issue by vitor-gyant** [felangel/bloc#140]
Hi,

I've a use case where the user clicks on a button but if a given validation does not pass then the state will remain the same however, I'd like to show an alert dialog always. For example, login form where the user does not input a valid email but presses the recover password button.

I know there are other approaches in terms of UX that could avoid this need but for me, having the bloc filtering duplicated state transitions for this case does not allows me to implement the desired behaviour.

So, my questions is: I'm using the Bloc pattern incorrectly here or the duplicate filter should be optional on the bloc ?

thanks in advance,

**Comment by felangel** [comment]
Hi @vitor-gyant thanks for opening an issue!

You should be able to accomplish this; however you need to make sure you are not extending Equatable in your states and that you are yielding a new state instance in your bloc. Let me know if that helps. If not, it’d be great if you could share a sample app that exhibits the problem you’re having and I can take a look 👍

**Comment by vitor-gyant** [comment]
Thanks @felangel  for the quick reply.

So basically by not extending from Equatable I'd only loose the compare functionality which implicitly will disable the filter. Is this the correct interpretation ?

Thanks,

**Comment by felangel** [comment]
@vitor-gyant no problem!

Yes, if you don't extend `Equatable` and yield a new instance of the state it will be interpreted as being different based on the way Dart equality comparisons work. Check out the [Dart Documentation](https://www.dartlang.org/guides/language/language-tour#equality-and-relational-operators) for more information about this. 👍 

Closing this for now but feel free to comment with additional questions if they arise and I'll reopen it.

**Comment by bardiarastin** [comment]
@felangel Hi, so much thanks for awesome project, I have a bloc which yields multiple states of the same type but with different payloads. the bloc builder will not rebuild my widgets unless I omit extending from Equatable then everything works fine. 
I guess we should add this as a point in docs write below this part in 
https://felangel.github.io/bloc/#/coreconcepts?id=states
![image](https://user-images.githubusercontent.com/20615964/62461879-4069cc00-b79b-11e9-963f-f83a15f520ef.png)
I would be happy to make a PR for this if it seems okay to you.

**Comment by felangel** [comment]
Hi @bardiarastin thanks for the positive feedback!

Regarding your question, can you share your state class implementation? I'm guessing you're not passing the properties to the super class. You should be able to have everything work as expected when extending `Equatable`.
