### ISSUE TITLE
[Information] Interbloc communication

### ISSUE THREAD

**Issue by geovin89** [felangel/bloc#1401]
For the Firebase login tutorial, I felt it is good to abstract field validation logic to a different bloc so that it can be reused by Register use case as well. 

1. Are there any examples out there that demonstrate interbloc communication?

1. What do you think about the idea? or should I stick to how it is done in the tutorial and keep it simple (but less DRY)

1. Additionally, is interbloc communication common?

P.S. I tried finding some examples but couldn't. I did see [Tregan's example](https://github.com/Tregan/bloc_sample/blob/master/lib/login/login_bloc.dart) which kind of uses it.

**Comment by DevNico** [comment]
The current approach is: https://bloclibrary.dev/#/architecture?id=bloc-business-logic-layer

**Comment by geovin89** [comment]
Cool thanks. (I should have just searched for bloc to bloc comm. instead of interbloc comm.)

Do you have a timeline on when BlocStreamListenerMixin will be available in the bloc library.
https://github.com/felangel/bloc/issues/765#issuecomment-573368016

**Comment by felangel** [comment]
Hi @geovin89 👋 
Thanks for opening an issue!

We decided against that approach because the benefits didn't seem worthwhile. If you have any additional feedback on the topic feel free to add a comment to the thread 👍 

Thanks @DevNico for taking the time to answer! I really appreciate it 🙏

**Comment by geovin89** [comment]
Thanks for the info!
