### ISSUE TITLE
Can you have too much bloc´s?

### ISSUE THREAD

**Issue by RoXioTD** [felangel/bloc#1404]
Hey,
I was wondering about what the suggested scenario is for creating new bloc´s:
* should you create an bloc for every single scenario in your app
 or 
* should you create lesser bloc´s and summarize similar scenario´s

Another question is whether it is bad or unperformant to have several `BlocProvider`, `BlocListener` and `BlocBuilder` in your widget tree or is this a normal scenario for larger apps?

**Comment by RollyPeres** [comment]
Hi @RoXioTD 👋

You'd usually create a bloc/screen or feature depending on your needs. Your blocs should be specialized and not deal with multiple responsibilities.

It's perfectly fine to have multiple bloc related widgets in your tree.

For a better understanding I'd advise you to have a look at the [official examples](https://github.com/felangel/bloc/tree/master/examples) and [bloc's official documentation](https://bloclibrary.dev/#/gettingstarted) ✌
