### ISSUE TITLE
buildWhen work wrong

### ISSUE THREAD

**Issue by devonsunday** [felangel/bloc#1413]
**Describe the bug**
buildWhen is wrong 

**To Reproduce**
1. In BlocBuilder, set buildWhen: (previous, current) => false,
2. error: funcion builder all run when state change.

**Expected behavior**
just run builder function when buildWhen return true.

see details in this video: https://drive.google.com/file/d/1jUx3sw5A-nt1WuYM1pYnzXIM2y9Y7V5q/view?usp=sharing

**Screenshots**
![image](https://user-images.githubusercontent.com/65029229/86908628-09d1c980-c141-11ea-80f3-56c8ad9e1710.png)

**Logs **
[flutter] flutter doctor -v
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.17.5 at C:\src\flutter
    • Framework revision 8af6b2f038 (8 days ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\dangn\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\dangn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.12.1

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Sorry! my english is bad.**

**Comment by felangel** [comment]
Hi @devonsunday 👋 
Thanks for opening an issue!

This is expected behavior because there are two reasons for a `BlocBuilder` to rebuild:

1. The bloc state changed
2. Flutter marked the widget as needing to be rebuilt.

`buildWhen` will prevent builds triggered by 1 but not by 2. In this case, when the language changes, the whole widget tree is likely being rebuilt which is why the `BlocBuilder` is rebuilt despite `buildWhen`.

Hope that clarifies things 👍

**Comment by dIvYaNshhh** [comment]
But how to avoid this issue?
Any best practice where we are using BlocConsumer Or BlocBuilder?
For me, I have a Dialog where I am using the same bloc with the previous page, when data is rendered into the bloc, it also re-rendered the previous page data as well.

**Comment by erlangparasu** [comment]
@dIvYaNshhh 

try checking state using additional substate class + `buildWhen`. Eg. :

```dart
@freezed
class PsvInspectionSummaryState with _$PsvInspectionSummaryState {
  factory PsvInspectionSummaryState.initial() = _Initial;
  factory PsvInspectionSummaryState.loaded({
    MySubStateA? substateA,
    MySubStateB? substateB,
  }) = _Loaded;
}
```

then use buildWhen to check the substates
