### ISSUE TITLE
Why switch to cubit ?

### ISSUE THREAD

**Issue by mzafer** [felangel/bloc#1414]
What is the reason to replace stream with cubit ?  And is there any benefit of doing that ? I did see that question raised in another issue as well but could not find an answer. 

Thanks

**Comment by felangel** [comment]
Hi @mzafer 👋
Thanks for opening an issue!

I think it https://github.com/felangel/cubit/issues/69 might answer your questions. Let me know 👍

**Comment by mzafer** [comment]
Thanks, yes that issue helps. Somehow missed that when I was looking earlier.
