### ISSUE TITLE
Back navigation inside flow pages and providers for flow pages

### ISSUE THREAD

**Issue by omidraha** [felangel/bloc#1432]
Hi @felangel,

I have these pages in my architecture:

1. Init 
  This page is splash screen.
2. Intro
  This page is introduce page.
3. Auth
  This page is authentication page. 
 This page is flow of registration page and verification page.
4. Home
  This page is home page.

In all pages, I need `InitBloc`, it is a general bloc I use in `main.dart`  to route the `user`  to the specific page according to the current situation of user (stored in db) even user reopen the app:
* `UserIsNotExist`, go to Init Page.
*  `UserIsRegistering`,  go to Auth Page.
* ` UserVerified`,  go to Home Page.
* ...

The `Auth` flow consist of two `registration` and `verification`  pages.
In the  `registration`  page I need `RegisterBloc` and in the  `verification`  page I need  both `RegisterBloc` and `VerifyBloc` blocs.

In The `Home` page, I need only `HomeBloc` and also optional  `InitBloc`.

Now this is [sample_auth](https://github.com/omidraha/sample_auth) for that, but I have two issues with that:

1. I would like in the `verification` page, User can back to the registration page with back button of phone. But when I pressed the back button, `Intro` pages shown. (It seems `Registration` page is not pushed on the stack)

2. In the `Verification` page, when I navigate to the `Home` page, it's not work and show the `Registration` page instead, beacuse I used `onGenerateRoute` approach you mentioned [here](https://github.com/felangel/bloc/issues/1341#issuecomment-650206074) and main route is ignored.

Thanks a lot as all your codes and your active community.

**Comment by YeungKC** [comment]
Hi, @omidraha 

could you provide your a minimal reproducible code sample how are you using it and describe desired result?
use https://codepen.io/ is a good choice.

**Comment by omidraha** [comment]
Hi,
I said on the above post.

This  [sample_auth](https://github.com/omidraha/sample_auth) is for minimal reproducible code.

And my problems are:


1. I would like in the `verification` page, User can back to the registration page with back button of phone. But when I pressed the back button, `Intro` pages shown. (It seems `Registration` page is not pushed on the stack)

2. In the `Verification` page, when I navigate to the `Home` page, it's not work and show the `Registration` page instead, beacuse I used `onGenerateRoute` approach you mentioned [here](https://github.com/felangel/bloc/issues/1341#issuecomment-650206074) and main route is ignored.

**Comment by YeungKC** [comment]
Hi, @omidraha 

Sorry, I didn’t see it before, I cloned the project later to check it out.

**Comment by YeungKC** [comment]
Hi, @omidraha 

Use Navigator.of(context, rootNavigator: true) can solve the problem, this problem has nothing to do with bloc.

@felangel close the issue, plz

**Comment by omidraha** [comment]
Hi,
I tired now, and you right this ` Navigator.of(context, rootNavigator: true) ` [fixed](https://github.com/omidraha/sample_auth/commit/39b3253be6f2230ad84606cb0ea95ba04ca1349f#diff-4c42cf463d593cb6f22abed23b42d716L29) the  `2` problem,
But how about first one:

1. I would like in the `verification` page, User can back to the registration page with back button of phone. But when I pressed the back button, `Intro` pages shown. (It seems `Registration` page is not pushed on the stack)

**Comment by YeungKC** [comment]
Hi, @omidraha 

Use `WillPopScope` to control the route can fix.

**Comment by omidraha** [comment]
Hi,
I tried it, but because of both `registration` and `verification` pages are in one [nested](https://github.com/omidraha/sample_auth/blob/master/lib/main.dart#L54) navigation, and because I used `onGenerateRoute` approach you mentioned [here](https://github.com/felangel/bloc/issues/1341#issuecomment-650206074) to have two `bloc` on this [auth](https://github.com/omidraha/sample_auth/blob/master/lib/pages/auth/auth.dart#L8) flow, It seems both `registeration` and `verification` pages are in the stack as one route name, and I can't separate them on `onWillPop` method.

**Comment by omidraha** [comment]
@YeungKC 
Can you please pull  [sample_auth](https://github.com/omidraha/sample_auth) and refactor route navigation section to work with the `1` problem.
I tried many ways and pushed some changes, but not work yet.

**Comment by omidraha** [comment]
Finally I [fixed](https://github.com/omidraha/sample_auth/commit/c6893853943ab5f22581aa034c5917f9997375b5) it.
Thanks.
