### ISSUE TITLE
Can I use cubits in collections?

### ISSUE THREAD

**Issue by Renesanse** [felangel/bloc#1440]
My question is: Can I use cubit in collections inside domain layer? For example:
```dart
final users = [User(), User()];
```
Where User class extending cubit.
Well, I figure out, that I should dispose all users(cubits) before deleting them due avoid memory leaks. It is a little bit overhead for me. Also, in my opinion, you can close cubit if nobody listening to it, but I think will be very important to check this implementation of this behavior for widgets in ListView for example. I mean reinit cubit flow if new listeners came.

**Comment by felangel** [comment]
Hi @Renesanse 👋 
Thanks for opening an issue!

Yeah as you mentioned, it's important to call `close` on the `Cubit` when it is not longer needed. When using `CubitProvider`, this behavior is automatically handled for you. If you were to have the list of `Cubits` be managed by a `StatefulWidget` then you could handle closing them all when the widget is disposed 👍 

```dart
class MyStatefulWidget extends StatefulWidget<_MyState> {
  @override
  State<MyStatefulWidget> createState() => _MyState();
}

class _MyState extends State<MyStatefulWidget> {
  List<User> _users;
  
  @override
  void initState() {
    super.initState();
    _users = _initUsers();
  }

  @override
  void dispose() {
    for (final user in _users) {
      user.close();
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) { ... }
}
```

Hope that helps 👍
