### ISSUE TITLE
How to get the state of multiple filter (complex filter) in Bloc.

### ISSUE THREAD

**Issue by rravithejareddy** [felangel/bloc#1443]
Take flutter_todos example where you just using two filters but I want complex filter like rating(4 and above, 3 and above), cost(100to200$, 200to 300$), where user can use multiple states to retrieve items. In example you just passing enum.value in super funtion something like

FilteredTodosBloc({@required this.todosBloc})
      : super(
          todosBloc.state is TodosLoadSuccess
              ? FilteredTodosLoadSuccess(
                  (todosBloc.state as TodosLoadSuccess).todos,
                  VisibilityFilter.all,
                )
              : FilteredTodosLoadInProgress(),
        )

In case of complex filter I want to use class object with list items, how to use this in super(), which is asking for only static fields and how to fill class from UI send the state back to bloc, I am from .net background where I can pass by simple model class with get sets, it seems complex to use here, can you provide a simple example on this, which would be great a help.
![Screenshot (118)_LI](https://user-images.githubusercontent.com/29831966/87223722-cc697800-c39c-11ea-81e1-ac44efd9e4fc.jpg)

**Comment by felangel** [comment]
Hi @rravithejareddy 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app or snippet which illustrates the issue you're having? Thanks 👍

**Comment by rravithejareddy** [comment]
I am following your examples on flutter. here the link for sample app I am following
https://github.com/felangel/bloc/tree/master/examples/flutter_todos.

In this app you are using of simple enum filter.

`enum VisibilityFilter { all, active, completed }`

Instead of this, I want use complex filter like different sections having checkboxes. user can select multiple filters same time, Some thing like in below 
![filter](https://user-images.githubusercontent.com/29831966/87236931-1ab65f80-c40d-11ea-9c01-81c2a20d6c52.png)
 
For this I tried Class model with get sets, but I am facing few issues like putting class model in super function in filtered_bloc, which is asking for static fields and filling class model from UI like in sample your are just taking active filter as input to state, but I want to take class object as input in state and back to UI according to the event.

`class FilteredCropsBloc extends Bloc<FilteredCropsEvent, FilteredCropsState> {
  final CropsBloc cropsBloc;
  StreamSubscription cropsSubscription;
   static Filter filter = new Filter(); 
    filter.type = all;                                       // filter is model calss which I wan to pass from state instead of enum as in your 
                                                                                  example it's visual filter model.

  FilteredCropsBloc({@required this.cropsBloc})
      : super(
    cropsBloc.state is CropsLoadSuccess
        ? FilteredCropsLoadSuccess(
      (cropsBloc.state as CropsLoadSuccess).crops,
      filter,
    )
        : FilteredCropsLoadInProgress(),
  )`

**Comment by felangel** [comment]
@rravithejareddy you need to make your filter `immutable` and add a `const` constructor.

```dart
class Filter {
  const Filter(this.quantity, this.grade, this.type);

  const Filter.initial() : this(const <int>[], const <int>[], '');

  final List<int> quantity;
  final List<int> grade;
  final String type;
}
```

Then you can create a const default instance for your initial state like:

```dart
FilteredCropsBloc({@required this.cropsBloc})
  : super(FilteredCropsLoadSuccess(const Filter.initial(), ...);
```

Hope that helps 👍

**Comment by rravithejareddy** [comment]
But unable to add item to list in UI, I am using something like filter.cropTyoe.add("pulses") but it's giving me error as unmodifiable list. Then how can add items and send back to bloc.

**Comment by rravithejareddy** [comment]
Hi felangel,

Can you please reply to #1443 comment.

Thanks
Ravi Theja

**Comment by felangel** [comment]
@rravithejareddy can you please share a link to a sample app which illustrates the issue? It's very difficult for me to help without being able to see the complete source code. Thanks!

**Comment by rravithejareddy** [comment]
These are files which support my question
[https://github.com/rravithejareddy/question](url)

Here I am facing two issues 
![Screenshot (127)](https://user-images.githubusercontent.com/29831966/91786098-7be7fb80-ec24-11ea-95be-23d6ed0285bb.png)

1) In on change function I am unable to add "string of cropType" directly to filter.croptype list (which is from state), it giving me error as unmodifiable list, instead I am taking local List<string>  and pushing in to state.filter.

`onChanged: (value) {
              if (value) {
                _selected.add(key);
               // cropName.add("redGram");
               // cropName.add("greenGram");
                widget.filter.cropType = _selected;
               // widget.filter.cropName = cropName;
                widget.onSelected(widget.filter);
              }
              else{
                _selected.remove(key);
                widget.filter.cropType = _selected;
                widget.onSelected(widget.filter);
              }
            },`

2) when I hit few checkbox list filter which doesn't return any crops from the bloc, but it's not rebuilding the tree, but I have to check checkbox through the state.filter, since it's not rebuilding I am unable to show the checkmark.

In flitered_crops_bloc 
`List<Crop> _mapCropsToFilteredCrops(
      List<Crop> crops, Filter filter) {

    return crops.where((crop) {
      if (crop.grade > filter.grade.length && crop.quantity > filter.quantity.length
       && filter.cropType.contains(crop.cropType))//&& filter.cropName.contains(crop.cropName)  ){
      {  return true;
      }
      else{
       return false;
      }
    }).toList();
  }` 

if this method not returning an any crops my tree is not rebuilding but I want to show filter checkbox checked from the state.filter.

![Screenshot_20200901-073747](https://user-images.githubusercontent.com/29831966/91786843-2b719d80-ec26-11ea-8a16-461074e06dfd.jpg)

**Comment by rravithejareddy** [comment]
Please reply to my comment

**Comment by felangel** [comment]
@rravithejareddy can you please update the github repo to include all the files necessary to run the example? Thanks!

**Comment by rravithejareddy** [comment]
But it depended on local mongodb, still I will send you

**Comment by felangel** [comment]
Can you please create a very simple flutter app to demonstrate the issue? It would be best to have a super simple example rather than a large application.

**Comment by rravithejareddy** [comment]
I just created sample app please find link below
https://github.com/rravithejareddy/flutter_mysample_app

In this if hit right top corner burger button it will open filter.
when I add pulses in to filter it's giving me back crops which are pulses
type.
when i add oilandseeds in to filter filtered_crops_bloc is not
returning any crops because there is no oilandseed croptypes, that's fine,
but it's not rebuilding the tree, because of that I am unable to show
checked mark on checkbox.

<List<Crop> _mapCropsToFilteredCrops(

    List<Crop> crops, Filter filter) {

  return crops.where((crop) {
    if (crop.grade > filter.grade.length && crop.quantity >
filter.quantity.length
     && filter.cropType.contains(crop.cropType))//&&
filter.cropName.contains(crop.cropName)  ){
    {  return true;
    }
    else{
     return false;
    }
  }).toList();
}>


I knew this because of this method is not returning ay crops but I am
dependent on filter as well, that filter is required me at filter page to
show which one is checked. How to rebuild the tree even though cropslist is
null.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/03/20,
03:17:45 PM

**Comment by rravithejareddy** [comment]
Did you get my issue?

**Comment by rravithejareddy** [comment]
@felangel/bloc
<reply@reply.github.com> If you
see my repo it's not working when I extend filter with Equatable. Can you
please look into that once.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
09/09/20,
01:11:18 PM

**Comment by mikededo** [comment]
The `Filter` class is not extending `Equatable`, which I believe it should.

**Comment by rravithejareddy** [comment]
If I extend filter class with Equatable, Ui is not rebuilding with
oilandseeds filter.

**Comment by mikededo** [comment]
I will see what I can find 😉

**Comment by mikededo** [comment]
After looking and testing your app I've found the problem you had. It is not because `Filter` extended `Equatable` but because you were modifying the object when creating a new one. Let me explain:  
When you were creating an item from the named constructor `fromAddedItem` and removing an item with `fromRemovedItem`, you were doing the following:

```dart
this.cropType.add(cropType);
this.cropName.add(cropName);
this.quantity.add(quantity);
this.grade.add(grade);
```

You were adding an item to the list and then returning the list with this new added item. This looks inoffensive, yet it was causing the `Equatable` error. Why? Because you were using the `Filter` that comes from the bloc, and Dart works by reference, which means that, since the `Filter` was not being cloned, you were modifying the state directly. 
Then, when you were sending a new event to the bloc, with the modified filter, the state had already been modified and the comparison between the state and the yielded one was true, since they both had the same `Filter` object.

I have solved this by creating new lists, so the ones that are in the `Filter` are not modified. Here's an snippet:

```dart
List<String> cropTypes = List.of(this.cropType);
if (newCropType != null) {
  cropTypes.add(newCropType);
}

/// ...

return Filter(
  cropTypes,
  /// ...
}
```

As I already told you, this is a solution that can work with small projects but I would definetely not recommend you creating classes like so. I will make a pull request with the updated changes. 

As a final recommendation, I would tell you to learn how to debug even if it is only by printing in the console. If you did so, you would probably have seen that the state was already being modified! You can always learn from mistakes 😃

✌️
