### ISSUE TITLE
Firebase Login tutorial needs to be updated

### ISSUE THREAD

**Issue by kentonraiford** [felangel/bloc#1448]
Hi,

I've used bloc before but am now learning how to use it based on this package structure. The [Firebase Login tutorial](https://bloclibrary.dev/#/flutterlogintutorial) is outdated. Could you update it when you get a chance? It would be helpful to new folks trying to learn.

**Comment by felangel** [comment]
Hi @kentonraiford 👋
Thanks for opening an issue!

Yup I’m in the processing of doing this (see #1445)
Closing this as a duplicate but expect to see the tutorials and doc updates in the next day or so 👍
