### ISSUE TITLE
UnitTesting flutter weather example

### ISSUE THREAD

**Issue by MattisBrizard** [felangel/bloc#145]
Hello,

Is that possible for you to show me how to unit test the flutter weather bloc ?

Thanks

**Comment by felangel** [comment]
@MattisBrizard Hi 👋 

I will definitely try to add some examples of how to unit test the weather bloc. Is there anything in particular that you're having trouble with?

There are currently examples of how to test blocs at:
- https://felangel.github.io/bloc/#/testing
- https://medium.com/flutter-community/unit-testing-with-bloc-b94de9655d86
- https://github.com/brianegan/flutter_architecture_samples/tree/master/bloc_library/test

Let me know if that helps and I will try to prioritize adding some bloc tests to the weather app in the next few day! Thanks 👍

**Comment by MattisBrizard** [comment]
@felangel Hi, thanks for answering !

Actually I have a project that is similar to your flutter weather app in term of implementation and I would like to know how I can test the bloc part in this situation. I read your medium article but my test don't pass.
So an example would help me so much.

Thanks 👍

**Comment by felangel** [comment]
@MattisBrizard no problem! I'll try my best to add some tests either by this evening or sometime tomorrow! I'll let you know as soon as they're available 😄

**Comment by MattisBrizard** [comment]
@felangel Thanks a lot and very good job for the package. 👏

**Comment by felangel** [comment]
@MattisBrizard just added tests for `WeatherBloc` which you can find [here](https://github.com/felangel/bloc/blob/master/examples/flutter_weather/test/blocs/weather_bloc_test.dart).

Hope that helps! 👍

**Comment by MattisBrizard** [comment]
Hi @felangel, thank you for the quick answer, it helped me a lot 👍
