### ISSUE TITLE
CounterPage demo can not run

### ISSUE THREAD

**Issue by vergilw** [felangel/bloc#1458]
**Describe the bug**
the CounterPage demo got a compile error in REAME. 
i copy the REAME demo code to my IDE, and input `flutter run`.
then i got a compiler error below:

**Logs **
flutter: The following assertion was thrown building _BodyBuilder:
flutter:         CubitProvider.of() called with a context that does not contain a Cubit of type CounterBloc.
flutter:         No ancestor could be found starting from the context that was passed to
flutter: CubitProvider.of<CounterBloc>().
flutter:
flutter:         This can happen if the context you used comes from a widget above the CubitProvider.
flutter:
flutter:         The context used was: BlocBuilder<CounterBloc, int>(dirty, state:
flutter: _CubitBuilderBaseState<CounterBloc, int>#f3f25(lifecycle state: created))

Paste the output of running `flutter doctor -v` here.
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-CN)
    • Flutter version 1.17.5 at /Users/fiber/Development/flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fiber/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/fiber/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/fiber/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • 02953733-8492-4AB8-BF6A-E1924F706019 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

**Additional context**
dependencies:
  flutter_bloc: ^5.0.1
  bloc: ^5.0.1

**Comment by felangel** [comment]
Hi @vergilw 👋 
Thanks for opening an issue!

The README is just outlining conceptually outlining how to use `BlocBuilder` as an example

> Lets take a look at how to use `BlocBuilder` to hook up a `CounterPage` widget to a `CounterBloc`.

You can refer to the [complete example](https://pub.dev/packages/flutter_bloc/example) which should compile and run properly.

Hope that helps and sorry for any inconvenience! 👍

**Comment by ariona** [comment]
I am new to flutter, and still learning about bloc. I tried to copy the counter source code but got errors

```
Compiler message:
lib/main.dart:16:17: Error: Type 'Cubit' not found.
  void onChange(Cubit cubit, Change change) {
                ^^^^^
```

**Comment by felangel** [comment]
@ariona are you using v6.0.0?

**Comment by ariona** [comment]
yes.. is there any changes to the api?

**Comment by felangel** [comment]
@ariona yup but Cubit is part of v6.0.0. Can you share a link to the exact code you’re trying to run?

**Comment by ariona** [comment]
i am following the  counter tutorial

**Comment by felangel** [comment]
Can you create a GitHub repo or gist that illustrates the issue you’re facing?

**Comment by ariona** [comment]
I figure it out by reading the migration guide and some digging into the issue. 
I think all the demo should be updated to the current version to prevent the confusion.

**Comment by felangel** [comment]
@ariona which demo are you running? Can you provide a link to the code? All demos should be up-to-date.

**Comment by felangel** [comment]
if it's <https://bloclibrary.dev/#/fluttercountertutorial> that will be updated shortly and I apologize for the inconvenience

**Comment by ariona** [comment]
I tested this https://github.com/felangel/Bloc/tree/master/packages/flutter_bloc/example yesterday. Did you update it yesterday?

**Comment by felangel** [comment]
@ariona it's been updated regularly. Is the latest version working for you?
