### ISSUE TITLE
Question, reemit the last event

### ISSUE THREAD

**Issue by rafaelmpessoa** [felangel/bloc#1462]
Hello,

It's possible to reemit the last event on my bloc with the same previous arguments?

Example:
I have a bloc that fetches some network data but somethings the network can fail. When fails the user will see a Widget that has "Try Again" button that when clicked has to emit the last event on my bloc.

**Comment by felangel** [comment]
Hi @rafaelmpessoa 👋 
Thanks for opening an issue!

By default blocs don't keep track of all events added. You would have to modify your bloc to keep track of the events and then re-add them. You could do something like:

```dart
class MyBloc extends Bloc<MyEvent, MyState> {
  MyBloc() : super(InitialState());

  MyEvent _previousEvent;

  @override
  void onEvent(MyEvent event) {
    _previousEvent = event;
    super.onEvent(event);
  }

  @override
  Stream<MyState> mapEventToState(MyState state) async* {
    if (event is TryAgain) {
      add(_previousEvent);
    }
    ...
  }
}
```

Hope that helps 👍
