### ISSUE TITLE
Does it ever make sense for events to be Equatable?

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#1469]
Not really a bug, I think, I would just really appreciate your input on this.

I understand the reason states need to override the `operator==` method or use `Equatable`, but I fail to see the reason why it should be the case for events. When I call the same event multiple times, no equality comparison or filtering happens by default, as it does for states. It is best visible in the counter tutorial: https://bloclibrary.dev/#/fluttercountertutorial?id=counter-events - the event is an enum (so firing e.g. `increment` multiple times actually uses the same instance, which is always equal to itself), end firing the same event multiple times keeps incrementing or decrementing the value, depending on the event. This is a proof that equality doesn't apply to events by default, right?

Our codebase (one that you know very, very well, at a renowned car producer ;d) is full of events that extend `Equatable`. Also, pretty much all event types in your tutorials are also `Equatable`. Why is that? When does it apply? I think I can safely drop `extends Equatable` from my events and it will work all the same.

**Comment by felangel** [comment]
Hi @wujek-srujek 👋 
Thanks for opening an issue!

In many cases, whether or not events are `Equatable` makes no difference; however, it does matter when you are overriding `transformEvents` (for example when applying `distinct`) and also makes it easier to write tests in many cases because you can do things like:

```dart
// If MyEvent is not Equatable, this will not work
verify(myBloc.add(MyEvent(value: 'some-value'))).called(1);
```

Hope that helps answer your question 👍

**Comment by wujek-srujek** [comment]
Hi. Yes, I know `transformEvents` may use it, that's why I wrote 'by default not comparison / filtering is applied'. Good point about the tests, but we don't write them like this (at least in my feature module).
That clears a lot of things up, thank you very much.
