### ISSUE TITLE
Should state of Bloc emit only distinct state if listen this state stream? (Question)

### ISSUE THREAD

**Issue by ruan65** [felangel/bloc#147]
In my app I have "Claim list screen" and "Add claim screen".

After adding new Claim on the "Add claim screen" the App navigates to "Claim list screen" where I want
to see the new claim in the list immediately.

To achieve this behavior in GlobalBloc I dispatch event GlobalMessage.NEED_UPDATE_CLAIM_LIST

Claim list should listen to it and updates.

But it updates list only once (I do not transform state stream to be distinct)
Code:

ClaimListBloc(this._globalBloc) {
    _createClaimStreamSubscription = _globalBloc.state.listen((state) {
      if (state is GlobalMessageState) {
        switch (state.message) {
          case GlobalMessage.NEED_UPDATE_CLAIM_LIST:
            loadClaims();
            break;
        }
      }
    });
  }

So to get every update I need after every message to update dispatch 
 an empty event like this _globalBloc.dispatch(GlobalEmptyEvent());

This code works fine

ClaimListBloc(this._globalBloc) {
    _createClaimStreamSubscription = _globalBloc.state.listen((state) {
      if (state is GlobalMessageState) {
        switch (state.message) {
          case GlobalMessage.NEED_UPDATE_CLAIM_LIST:
            loadClaims();
            // to avoid distinct stream
            _globalBloc.dispatch(GlobalEmptyEvent());
            break;
        }
      }

The question is why it is initially distinct?
Can I have a better solution (avoid empty events)?

**Comment by felangel** [comment]
Hi @ruan65 👋 

Thanks for opening an issue! Bloc will not trigger a state change if the currentState == the yielded state in mapEventToState. Are you able to share the GlobalBloc code as well as the code for GlobalBlocState? My guess is you’re not yielding a new instance of the state in mapEventToState. This could also happen if you’re using equatable for your GlobalBlocState.

I would recommend making sure you’re yielding a new instance of state in mapEventToState and that you are not extending Equatable in your state class in order to get the desired behavior. 

Let me know if that helps 👍

**Comment by ruan65** [comment]
Yes, Felix, all state classes I have used were @equtable. I removed this annotation - it does not help.
Also, it looks like I am yielding a new state instance every time.

GlobalBloc
https://gist.github.com/ruan65/edd7a450849d8609ceb5caebf1ddfd83
GlobalState
https://gist.github.com/ruan65/56e1226f09d10670edef4b5721fb5783

And the **line 29** in CreateClaimBloc class makes difference (if it commented the subscription in my question getting GlobalMessageState only ones)

https://gist.github.com/ruan65/263fe840e43c4d29c314bf192e41915b

**Comment by felangel** [comment]
@ruan65 thanks for the code snippets and additional information. Everything looks fine to me from the code you’ve shared. Are you able to share a sample app with the problem you’re having so I can run it locally and help debug the issue? Thanks!

**Comment by felangel** [comment]
@ruan65 closing this for now since I need more information to debug the issue. If you are able to share a sample app with the problem you're having I'm happy to take a look 👍

**Comment by ruan65** [comment]
Felix, unfortunately, I can not - I am not an owner (It is company app (auth, NDA etc.))

But I have an idea. I guess that todo example in Bloc repo is not 100% correct since it is using global bloc for creating to-do items on AddEditScreen (passing callback about creating the item to it).

AddEditScreen can have its own bloc (scoped to this screen)

I'll try to find spare time to rewrite the example and you'll evaluate it (or it will have a similar problem or not)

**Comment by felangel** [comment]
@ruan65 sounds good!
