### ISSUE TITLE
Can not get bloc working with streamController and not yield

### ISSUE THREAD

**Issue by ride4sun** [felangel/bloc#1472]
**Describe the bug**
I abstracted the pub location package into a bloc. First I tried to listen to the location events but the `yield` statement did not get executed. Then I used `await for` and I could not cancel the subscription because there was none. 

I filed a question on Stackoverflow for that here:
https://stackoverflow.com/questions/62926257/how-can-i-cancel-a-await-for-in-a-flutter-dart-bloc

The current version (3) is using a StreamController.stream which is returned by `mapEventToState`. I can fire the first event which is starting the location package (start) to send events location events I see in the UI. Then the next event is supposed to `stop` the bloc sending events.  Unfortunately, the stop event never gets to the 
`mapEventToState` method override. I don't see an exception or error code and I had no luck with the debugger going through the bloc base class. The bloc has only three events start, stop, changeUnits
and is actually pretty simple. I would like to publish the bloc on pub when I get it working.
 
The complete source code with an UI example is available here:
https://github.com/ride4sun/location_bloc.git

I also posted the bloc code below. Any help or hint would be appreciated.

**Logs **
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.17.5 at c:\sdks\flutter
    • Framework revision 8af6b2f038 (2 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\ride4\AppData\Local\Android\sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 32-bit edition (version 1.45.1)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 3.10.2

[√] Connected device (1 available)
    • moto g power • ZF6523C4GL • android-arm64 • Android 10 (API 29)

```
import 'dart:async';
import 'dart:developer';

import 'package:bloc/bloc.dart';
import 'package:location/location.dart' as ploc;
import 'package:location_bloc/bloc/location_event.dart';
import 'package:location_bloc/bloc/location_state.dart';
import 'package:location_bloc/extensions/extensions.dart';
import 'package:location_bloc/model/model.dart' as mo;

enum gpsError {
  noError,
  permissionDenied,
  permissionDeniedNeverAsk,
}

class LocationBloc extends Bloc<LocationEvent, LocationState> {
  LocationBloc(LocationState initialState) : super(initialState);

  final location = ploc.Location();
  final StreamController<LocationState> stateController =
      StreamController<LocationState>(onListen: () {
    //debugger(when: true);
  }, onPause: () {
    //debugger(when: true);
  }, onResume: () {
    //debugger(when: true);
  }, onCancel: () {
    //debugger(when: true);
  });

  StreamSubscription _locationSubscription;
  mo.UnitSystem _system = mo.UnitSystem.Metrics;

  @override
  void onError(Object error, StackTrace stackTrace) {
    super.onError(error, stackTrace);
    debugger(when: true);
  }

  @override
  Stream<LocationState> mapEventToState(LocationEvent event) {
    event.when(
      setUnitSystem: (args) => _setUnitSystem(args),
      start: (_) => _start(),
      stop: (_) => _stop(),
    );

    return stateController.stream;
  }

  _setUnitSystem(SetUnitSystem args) async {
    _system = args.unitSystem;
    if (state is SendData)
      stateController.add(
        LocationState.sendData(
          location: updateLocation(
            await location.getLocation(),
          ),
        ),
      );
  }

  Future _start() async {
    if (_locationSubscription.isNotNull) return;
    ploc.PermissionStatus permission = await location.hasPermission();
    if (permission != ploc.PermissionStatus.granted) {
      permission = await location.requestPermission();

      if (permission != ploc.PermissionStatus.granted) {
        stateController.add(LocationState.error(
            info: 'Location Service has no permission. '
                'Please check settings',
            results: gpsError.permissionDenied));
        return;
      }
    }

    bool enabled = await location.serviceEnabled();

    if (enabled.isFalse) {
      bool enabled = await location.requestService();
      if (enabled.isFalse) {
        stateController.add(
          LocationState.error(
              info: 'Location not active.'
                  'Please check your settings',
              results: gpsError.permissionDenied),
        );
        return;
      }
    }

    await ploc.Location()
        .changeSettings(accuracy: ploc.LocationAccuracy.high, interval: 1);

    _locationSubscription = location.onLocationChanged.listen(
      (data) {
        if (location.isNotNull) {
          stateController.add(
            LocationState.sendData(
              location: updateLocation(data),
            ),
          );
        }
      },
    );

    _locationSubscription.onError((err) async {
      await _handleError(err);
      await _locationSubscription.cancel();
      _locationSubscription = null;
    });

    //send one initial update to change state
    stateController.add(
      LocationState.sendData(
        location: updateLocation(
          await ploc.Location().getLocation(),
        ),
      ),
    );
  }

  Future _handleError(dynamic error) async {
    if (error.code == 'PERMISSION_DENIED') {
      stateController.add(LocationState.error(
          info: 'Permission Denied', results: gpsError.permissionDenied));
    } else if (error.code == 'PERMISSION_DENIED_NEVER_ASK') {
      stateController.add(LocationState.error(
          info: 'Permission Denied',
          results: gpsError.permissionDeniedNeverAsk));
    } else {
      stateController.add(LocationState.error(
          info: 'Could not get Location ',
          results: gpsError.permissionDeniedNeverAsk));
    }
  }

  Future _stop() async {
    await _locationSubscription?.cancel();
    _locationSubscription = null;
    stateController.add(LocationState.stoped());
  }

  mo.Location updateLocation(ploc.LocationData data) => mo.Location(
      altitude: mo.Altitude.fromMeters(value: data.altitude, system: _system),
      speed: mo.Speed.fromMeterPerSecond(value: data.speed, system: _system),
      accuracy: mo.Length.fromMeters(value: data.accuracy, system: _system),
      heading: data.heading,
      latitude: data.latitude,
      longitude: data.longitude,
      speedAccuracy:
          mo.Length.fromMeters(value: data.speedAccuracy, system: _system));
}
```

**Comment by RollyPeres** [comment]
Hi @ride4sun 👋

Your initial approach to listen to location was the right one.
Instead of yielding you should just add an event to the bloc with the incoming data as payload.
```
locationStream.listen((location) => add(LocationState.locationChanged(location)));
```
Handling that event will allow you to yield new states.

Hope that helps 👍

**Comment by ride4sun** [comment]
Oh man - I could have thought about that. Thanks @RollyPeres . Any ideas why the current version does not work?

**Comment by ride4sun** [comment]
you mean an event instead of a state, right? 
`locationStream.listen((location) => add(LocationEvent.locationChanged(location)));`

This would expose this event also to the consumer which is the UI. It for sure works but not really clean for the consumer of that package. It would also leak the location package into the UI which I really like to avoid. Do I miss something?

**Comment by RollyPeres** [comment]
If you're creating a package out of this bloc then it's up to you what you export.
You can easily create the event as private so package users won't be able to add it.

`const factory LocationEvent._locationChanged() = _LocationChanged;`

**Comment by ride4sun** [comment]
I update the lib as you suggested in the `yield` branch
https://github.com/ride4sun/location_bloc.git

It works as expected but I generate the Types with the `super enum` (pretty cool) and have not a good way to make than private (I guess I can make the privat after the generation)

Would you mind reviewing the package @RollyPeres ? I would like to hear your comments.

**Comment by felangel** [comment]
@ride4sun another option is to avoid exporting the events at all.

```dart
library bloc;

export 'package:location_bloc/bloc/location_bloc.dart';
export 'package:location_bloc/bloc/location_bloc_observer.dart';
export 'package:location_bloc/bloc/location_event.dart'; // do not export the events
export 'package:location_bloc/bloc/location_state.dart';
```

Then you can expose public methods on the bloc to add the events internally:

```dart
void start() => add(LocationEvent.start());
```

Closing this for now since it sounds like your original question has been addressed but happy to continue the conversation if you have any other additional questions 👍

**Comment by ride4sun** [comment]
Yes, I could do that but it still feels like we dancing around the real issue that I can not listen to streams inside the bloc without creating internal events to myself. Does that no feel like an odd workaround to you. The use case that I pass in any stream to a bloc sounds very common to me.

I think the real problem is that `listen` does not work with `yield` and 'await for' I can not cancel later on.
I am still looking for a better more sustainable workaround. 
Any more ideas. I implemented the event to myself on the yield branch. I still feel not better ;)

**Comment by felangel** [comment]
@ride4sun can you share a simple example of what you mean when you say `listen` does not work with `yield` and `await` for? I'm not sure I completely understand the issue, thanks 🙏

**Comment by ride4sun** [comment]
I think the Stackoverflow post is hopefully explaining it: 
Does it make sense?

https://stackoverflow.com/questions/62926257/how-can-i-cancel-a-await-for-in-a-flutter-dart-bloc

**Comment by RollyPeres** [comment]
@ride4sun I'm sorry I'm extremely caught up will try to have a look in the following days but can't promise anything.

As for your issue with yield, that's just how dart works.
It's quite simple: in order to yield from on data callback you would need it to return a stream, which is not the case since it returns void. Also .listen returns a stream subscription instead of a stream, so it's simply impossible to do what you want, like you want.

I'd suggest you do some reading on async generators to further help you understand how and where you can use them.👍

**Comment by ride4sun** [comment]
> @ride4sun another option is to avoid exporting the events at all.
> 
> ```dart
> library bloc;
> 
> export 'package:location_bloc/bloc/location_bloc.dart';
> export 'package:location_bloc/bloc/location_bloc_observer.dart';
> export 'package:location_bloc/bloc/location_event.dart'; // do not export the events
> export 'package:location_bloc/bloc/location_state.dart';
> ```
> 
> Then you can expose public methods on the bloc to add the events internally:
> 
> ```dart
> void start() => add(LocationEvent.start());
> ```
> 
> Closing this for now since it sounds like your original question has been addressed but happy to continue the conversation if you have any other additional questions

Not exporting the events is probably the cleanest approach together with the internal event. Thanks!.

**Comment by ride4sun** [comment]
> @ride4sun I'm sorry I'm extremely caught up will try to have a look in the following days but can't promise anything.
> 
> As for your issue with yield, that's just how dart works.
> It's quite simple: in order to yield from on data callback you would need it to return a stream, which is not the case since it returns void. Also .listen returns a stream subscription instead of a stream, so it's simply impossible to do what you want, like you want.
> 
> I'd suggest you do some reading on async generators to further help you understand how and where you can use them.

Yes need to brush up on that generator stuff. Thanks for your help. Firing internal events when you want to listen to another stream still feels odd to me, though

**Comment by RollyPeres** [comment]
The whole bloc concept revolves around adding events which are then turned into states, nothing odd about that.
If you don't like the concept then maybe have a look at cubit, which doesn't have the concept of events but you can instead use methods to trigger state changes.

**Comment by ride4sun** [comment]
I am not mind the concept at all. I actually like it. What I don't like is
that u add internal events as a workaround because I am not able to listen
to a stream inside an event. Sounds more like a dart shortcoming to me.

**Comment by felangel** [comment]
@ride4sun you can listen to a stream when you receive an event but you can't yield from within the closure.

**Comment by ride4sun** [comment]
@felangel yes that is my problem and I am now aware of it and I can use the workaround to send events from within the closure to the bloc.  I also could use a streamController and return that stream from the `mapEventToState` method (is that recommended?) Or I could use the `await for` if I don't need to cancel the stream. I am just wondering what the cleanest workaround is to handle a stream inside a bloc (could be another bloc).
