### ISSUE TITLE
flutter_shopping_cart example

### ISSUE THREAD

**Issue by batwicket** [felangel/bloc#1479]
The ["Naming Conventions"](https://bloclibrary.dev/#/blocnamingconventions) section of the bloc library documentation suggests naming Events using the past tense and States using the present tense.

The [flutter_shopping_cart example](https://github.com/felangel/bloc), as [recommended in the FAQ](https://bloclibrary.dev/#/faqs?id=project-structure), uses LoadCatalog as an Event. It potentially results in a transition to a CatalogLoaded state. Perhaps the Event/State could be renamed to CatalogLoadRequested/CatalogLoadSuccess, respectively, to remain consistent with the recommendations.

**Comment by felangel** [comment]
Hi @batwicket 👋 
Thanks for opening an issue!

I have updated this in https://github.com/felangel/bloc/commit/81053c91745657e9dcf9b0d088d1d9be55e60e68. Thanks again for calling this out 🙏
