### ISSUE TITLE
A mergration guild from v4.0.0 to v5.0.0

### ISSUE THREAD

**Issue by heshaShawky** [felangel/bloc#1485]
**Describe the bug**
I'm using flutter_bloc on some production apps, and I got a notification from the BLOC add-on in the VS Code that I have to update to V5, I thought it would be under hood updates but I see there a lot of breaking changes ( a lot of errs of missing/undefined classes ...etc ). 

So I think we need a guide for how to migrate the code from V4 ( as an example ) to V5 ( as now ) and what actually has been changed when any new update comes in in the future.

**Comment by felangel** [comment]
Hi @heshaShawky 👋 
Thanks for opening an issue!

Yup, check out the [migration guide](https://bloclibrary.dev/#/migration) and let me know if you have any questions 👍
