### ISSUE TITLE
BlocProvider run only first time

### ISSUE THREAD

**Issue by z3v0k** [felangel/bloc#1487]
Hi, I have my providers in Main, only runs the first time after login success, I need run it always after login success, can you help me :(

![image](https://user-images.githubusercontent.com/7059212/87876653-04317a80-c9b0-11ea-9447-14407c132fd6.png)

**Comment by warriorCoder** [comment]
@z3v0k .. there could be a few different reasons for your issue, but the first one that comes to mind is that you are trying to yield the same state and are using equitable, meaning that the state hasn't actually changed so no new state will be yielded.

Can you share a project that shows the problem you're having?

**Comment by felangel** [comment]
Hi @z3v0k 👋 
Thanks for opening an issue!

`BlocProvider` only executes `create` once when the widget is mounted in the widget tree (think of it like `initState`).
If you want that event to be added after a login success then you should use a `BlocListener`, listen for a `LoginSuccess` and then add the event like:

```dart
BlocListener<LoginBloc, LoginState>(
  listener: (context, state) {
    if (state is LoginSuccess) {
      context.bloc<PollsBloc>().add(LoadPolls());
    }
  },
  child: ...
```

Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
