### ISSUE TITLE
[VSCode] Generate freezed boilerplate

### ISSUE THREAD

**Issue by Jomik** [felangel/bloc#1492]
**Is your feature request related to a problem? Please describe.**
I have to write down the freezed boilerplate.

**Describe the solution you'd like**
Similar to Equatable, would be awesome to just add freezed.
```dart
import 'dart:async';

import 'package:bloc/bloc.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:meta/meta.dart';

part 'home_bloc.freezed.dart';
part 'home_event.dart';
part 'home_state.dart';

class HomeBloc extends Bloc<HomeEvent, HomeState> {
  HomeBloc() : super(HomeState.initial());

  @override
  Stream<HomeState> mapEventToState(
    HomeEvent event,
  ) async* {
    // TODO: implement mapEventToState
  }
}
```
```dart
part of 'home_bloc.dart';

@freezed
abstract class HomeState with _$HomeState {
  const factory HomeState.initial() = HomeInitial;
}
```
```dart
part of 'home_bloc.dart';

@freezed
abstract class HomeEvent with _$HomeEvent {
  const factory HomeEvent.refreshed() = HomeRefreshed;
}
```

**Describe alternatives you've considered**
Manually writing it 👎

**Comment by QAQyzk** [comment]
I have writen a vscode extension that can just do that [freezed_bloc](https://marketplace.visualstudio.com/items?itemName=QAQyzk.freezed-bloc).

**Comment by felangel** [comment]
@QAQyzk thanks for sharing, that's awesome 🎉 
What are your thoughts in migrating your extension into the current bloc extension in order to consolidate the snippets/tooling?

Curious to hear if others have an opinion one way or another one this.

**Comment by QAQyzk** [comment]
@felangel I would love to see the function integrated to the bloc extension! But I'm not entirely sure how to add contribute to the repo, is there anything I can follow?
