### ISSUE TITLE
BlocBluider with initial event or async function the return a event

### ISSUE THREAD

**Issue by marcusedu** [felangel/bloc#1496]
**Is your feature request related to a problem? Please describe.**
When I use BlocBuilder in stateless widget sometime need to send a event to build some state without user interaction.
Actually I transform `stateless` to `stateful` and write my logic in `initState()`

**Describe the solution you'd like**
```dart
BlocBuilder<SomeBloc, SomeState>(
  bootBuilder: (BuildContext context) async { // this must function runonce 
    // some async logic whit this context
    return SomeNewEvent(anyArgs);
  },
  builder: (context, state) => SomeWidgetToBuild(),
```

**Comment by felangel** [comment]
Hi @marcusedu 👋 
Thanks for opening an issue!

You can add the event asynchronously when the bloc is created:

```dart
BlocProvider(
  create: (context) {
    final bloc = SomeBloc();
    someAsyncRequest().then((value) => bloc.add(SomeEvent(value));
    return bloc;
  },
  child: ...
);
```

`create` is very similar to `initState` in a `StatefulWidget` and is called only once when the widget is mounted.

Hope that helps 👍
