### ISSUE TITLE
What warrants a Bloc?

### ISSUE THREAD

**Issue by QoLTech** [felangel/bloc#150]
I'm curious as to what warrants a bloc.

Should I use a Bloc for each page? I've run into a few instances where I think it would be easier to have multiple blocs per page. For example, I have a DropDownButton and that changes my state and based on it, different TextFormFields are shown. The rest of my page has completely independent logic from those widgets. Is it worth it to create a bloc that takes care of that piece of functionality on the page, or just keep the page-wide bloc?

**Comment by felangel** [comment]
@QoLTech great question! A bloc is a business logic component so any time you have a new piece of business logic that is not related to an existing bloc, I would recommend creating a new bloc.

This has multiple benefits including:
- State changes only re-render the part of the page that they affect
- Unrelated functionality is separated making it more reusable
- Smaller, more specialized blocs are usually easier to test and understand

Let me know if that helps and again great question! 💯

**Comment by felangel** [comment]
@QoLTech closing for now but feel free to comment with any additional questions and I'm happy to reopen it. 👍
