### ISSUE TITLE
How can I get currentState and Stream<state> in version 5.00 and above

### ISSUE THREAD

**Issue by hayashi-tz** [felangel/bloc#1504]
Dear Developer,

I would like to ask one thing, How can I get currentState and Stream<State> as like 0.10.1 in new version 5.0.0 and above.

I used very old version 0.10.1 in my app, that's why I would like to upgrade my app bloc library version to 5.0.1.

But unfortunately, I couldn't found currentState and Stream<State> in version 5.0.1.

```
  /// Returns [Stream] of [State]s.
  /// Consumed by the presentation layer.
  Stream<State> get state => _stateSubject.stream;

  /// Returns the [State] before any [Event]s have been `dispatched`.
  State get initialState;

  /// Returns the current [State] of the [Bloc].
  State get currentState => _stateSubject.value;

```
Could you please kindly support me? 

Thanks in advance.

**Comment by felangel** [comment]
Hi @hayashi-tz 👋 
Thanks for opening an issue!

You can access the current state of the bloc like:

```dart
final bloc = MyBloc();
final currentState = bloc.state;
```

You can listen to the stream of states via:

```dart
final bloc = MyBloc();
final subscription = bloc.listen((state) { ... });
```

Hope that helps 👍
