### ISSUE TITLE
Provide initial value to the BlocBuilder

### ISSUE THREAD

**Issue by ShiinaManatsu** [felangel/bloc#1511]
## Want initial value to prevent null state when BlocBuilder fist time built
For multiple page that use the same stream will have a null state when they build first time, and refresh child after bloc updated.
## How I fix that for now
The solution now I made is to keep a state last time I updated, and in each widget which will use that bloc will be update in the ```init()``` method by the last state in the stream, and next fetch the new state.
This can be used as a "Fake Initial value" to prevent initial null state and I can get visual what data I have so far and don't need to wait for the new fetch

``` dart
void updateUserBloc() {
  if (userinfo != null) {
    userInfoBloc.update(Future.value(userinfo));
  }

  userInfoBloc.update(memberApi.queryByIdUsingPOST());
}

ResultBase<UserInfo> userinfo;
```

**Comment by Jomik** [comment]
What does your `UserInfoBloc` look like? It sounds like you are not providing it with an initial state?

**Comment by ShiinaManatsu** [comment]
> What does your `UserInfoBloc` look like? It sounds like you are not providing it with an initial state?

It's basically we have a login screen and it will update the bloc user info and the home widget can show the states. Please have look on the bloc that I basically copy and modified from the examples.

But is the ```RxBlocBuilder``` can take an initial value? I don't see that from the implementation.

In each new widget that we may want to update the user info I will call to update it, and without the incoming user info, the ```RxBlocBuilder``` will have a null state.

## My bloc
``` dart
abstract class UserInfoBlocEvents {
  void update(Future<ResultBase<UserInfo>> userInfo);
}

abstract class UserInfoBlocStates {
  Stream<ResultBase<UserInfo>> get userinfo;

  @RxBlocIgnoreState()
  Stream<LoginStatus> get isLoggedIn;

  @RxBlocIgnoreState()
  Stream<bool> get isLoading;

  @RxBlocIgnoreState()
  Stream<String> get errors;

  //  We need to keep a token where some method won't return a token
  @RxBlocIgnoreState()
  Stream<UserToken> get userToken;
}

@RxBloc()
class UserInfoBloc extends $UserInfoBloc {
  @override
  Stream<ResultBase<UserInfo>> _mapToUserinfoState() {
    return _$updateEvent
        .switchMap((x) => x.asResultStream())
        .setResultStateHandler(this)
        .whereSuccess();
  }

  @override
  Stream<String> get errors => errorState.skip(1).map((exception) {
        String msg = exception.toString();
        if (msg.contains('Exception:')) msg = msg.replaceAll('Exception:', '');
        return msg;
      });

  @override
  Stream<bool> get isLoading => loadingState;

  @override
  Stream<LoginStatus> get isLoggedIn {
    var stream = states.userinfo.asBroadcastStream();

    var fail = stream
        .where((x) => x?.success == false)
        .switchMap((_) => Future.value(LoginStatus.NotLogin).asStream());

    var success = stream
        .where((x) => x?.success == true && x?.code == 200)
        .where((x) => x?.result != null)
        .where((x) => x?.result?.token != null)
        .switchMap((_) => Future.value(LoginStatus.LoggedIn).asStream());

    return fail.mergeWith([success]).startWith(LoginStatus.NotLogin);
  }

  @override
  Stream<UserToken> get userToken => states.userinfo
      .asBroadcastStream()
      .where((x) => x?.result?.token != null)
      .switchMap((x) => Future.value(x.result.token).asStream());

  /// Closes the [Event] and [State] [Stream]s.
  @mustCallSuper
  void dispose() async {
    await _$updateEvent.drain();
    _$updateEvent.close();
    super.dispose();
  }
}

/// Status determines the application login status
enum LoginStatus { 
```

## How I use the ```RxBlocBuilder```

``` dart
RxBlocBuilder<UserInfoBlocType, ResultBase<UserInfo>>(
state: (bloc) => bloc.states.userinfo,)
```

**Comment by Jomik** [comment]
Hmm, I did not know there was an `RxBloc` package.
I think you are in the wrong GitHub repo. This is for the Bloc package, https://bloclibrary.dev/.
Are you looking for https://github.com/Prime-Holding/FlutterRxBloc ?

**Comment by ShiinaManatsu** [comment]
> Hmm, I did not know there was an `RxBloc` package.
> I think you are in the wrong GitHub repo. This is for the Bloc package, https://bloclibrary.dev/.
> Are you looking for https://github.com/Prime-Holding/FlutterRxBloc ?

Oh god, I'm open an issue at the wrong chrome tab :)
Sorry for the bother~
