### ISSUE TITLE
Hydrated_bloc and Hive

### ISSUE THREAD

**Issue by mintymac** [felangel/bloc#1515]
Thank you for all of your work.  

I was recently considering Hydrated_bloc and I was wondering what @felangel and the team thought about a possible deprecation of Hive, based on this: [The Future of Hive](https://github.com/hivedb/hive/issues/246)

Thoughts?  Thank you.

**Comment by felangel** [comment]
Hi @mintymac 👋 
Thanks for opening an issue and for the positive feedback!

We are aware of the possible deprecation of Hive v1.0 and the plan is to evaluate v2.0 once it is stable to determine a migration strategy. We will try to minimize any breaking changes (`hydrated_bloc` abstracts the hive implementation) and handle any data migration so that as a developer the upgrade is smooth and seamless.

Hope that helps! Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍

**Comment by mintymac** [comment]
Of course!  The position is understandable, I have just begun to have issues with packages not being updated, path is one.  Have a good one!

**Comment by felangel** [comment]
@mintymac I think the intention is for the existing package to continue to be maintained 🤞 https://github.com/hivedb/hive/issues/246#issuecomment-662425202

Thanks, you too!

**Comment by omidraha** [comment]
I suggest [sqflite](https://github.com/tekartik/sqflite.).
Stable, reliable, basic, fast, clean.

**Comment by orsenkucher** [comment]
@omidraha @mintymac 
In my opinion Hive 2.0 is an honorable undertaking from Hive's team, all things should evolve with time😉 
However this doesn't mean old things will break, and current Hive is mature and fits our current requirements. 
So once Hive 2.0 is released, we'll proceed with migration

---
Hive also did some [benchmarking](https://pub.dev/packages/hive#benchmark) against [sqflite](https://github.com/tekartik/sqflite)

And we benchmarked it against [sembast](https://pub.dev/packages/sembast)([here](https://cdn.discordapp.com/attachments/649743869474373643/726742085990088734/Screenshot_20200628-131019.jpg)) and [moor_ffi](https://pub.dev/packages/moor_ffi)([here](https://cdn.discordapp.com/attachments/649743869474373643/726741872109944882/Screenshot_20200628-130522.jpg))

Hive is superior in my opinion😛

**Comment by omidraha** [comment]
In fact, before I [immigrated](https://github.com/hivedb/hive/issues/246#issuecomment-663647198), I try all of them:

- [sembast](https://pub.dev/packages/sembast)
- [sembast_sqflite](https://pub.dev/packages/sembast_sqflite)
- [sqflite](https://pub.dev/packages/sqflite)
- [streamqflite](https://pub.dev/packages/streamqflite)
- [sqlbrite](https://pub.dev/packages/sqlbrite)
- [sqlcool](https://pub.dev/packages/sqlcool)
- [moor](https://pub.dev/packages/moor)
- [moor_flutter](https://pub.dev/packages/moor_flutter)
- [moor_ffi](https://pub.dev/packages/moor_ffi)
- [floor](https://pub.dev/packages/floor)
- [objectdb](https://pub.dev/packages/objectdb)
- [objectbox](https://pub.dev/packages/objectbox)
- [hive](https://pub.dev/packages/hive)
- [hive_flutter](https://pub.dev/packages/hive_flutter)

But, in my experience [sqflite](https://pub.dev/packages/sqflite) is faster and is straightforward and there is nothing hidden issues inside.

I think [this](https://github.com/isar/isar/issues/2),  pursues these great and efficient goals, and I hope that other developers of these above packages will come to their aid.
Maybe a joint package with the cooperation and experience of all of above packages developers.

**Comment by orsenkucher** [comment]
@omidraha yeah, [this](https://github.com/isar/isar/issues/2) as well as [this](https://github.com/isar) in general, is very exciting stuff👌
Glad you found a solution that suits your needs
