### ISSUE TITLE
[DISCUSSION] Allow to access bloc properties from initial state

### ISSUE THREAD

**Issue by agordeev** [felangel/bloc#1519]
We've removed `initialState` property from bloc. Instead, we pass it as a constructor parameter to `super`. That made some complexities, as it's impossible to access class members in initializers. Imagine a bloc that holds `CalendarController`. The calendar always presents on the screen, therefore it always needs a controller. However, with the current version of the library I'm unable to pass the controller to `CalendarInitial` state: 

>Only static members can be accessed in initializers.

Are there any workarounds? Is it only me who faces this problem? :)

**Comment by felangel** [comment]
Hi @agordeev 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the problem you are facing? I'm guessing this is related/similar to https://github.com/felangel/bloc/issues/1378

**Comment by agordeev** [comment]
@felangel Thanks. That's exactly the same problem. There's no solution provided, though. The migration guide says nothing about how to handle that.

**Comment by felangel** [comment]
@agordeev there are two solutions provided:
https://github.com/felangel/bloc/issues/1378#issuecomment-653409984
https://github.com/felangel/bloc/issues/1378#issuecomment-653411203

If those don't help please share a link to a sample app which illustrates the issue and I'm happy to open a pull request with a fix 👍

**Comment by agordeev** [comment]
Unfortunately, the solutions provided consider to get controllers from outside. In many ways it's more convenient to create them in bloc directly.

**Comment by felangel** [comment]
@agordeev can you provide a link to a sample app which illustrates the previous setup you had? Thanks 👍
