### ISSUE TITLE
Use diferent type of blocs on BlocProvider.of<type>

### ISSUE THREAD

**Issue by MeliGualaX** [felangel/bloc#1520]
Hello, im facing a trouble, and i think that is a limitation...

I got a Map map = {1: BlocA, 2: BlocB, 3:BlocC } are like 20 of these... 
Then i got an input and i need to use one of them, I do not know which one I will have to use until the imput is executed.
And what i want is to provide de type on BlocProvider thats allow me to do something like this: 

var bloc = BlocProvider.of<map[1]>(context);  // where map[1] = BlocA
bloc.add(function).

i am missing something or i am doing some wrong or the current approach doesn't allow this?

How could I achieve this?

Thanks!

**Comment by felangel** [comment]
Hi @MeliGualaX 👋 
Thanks for opening an issue!

I would not recommend maintaining a map of blocs/indexes like that. Instead, I would recommend creating the widgets that rely on the blocs and wrapping each widget in its own BlocProvider (with a new Bloc instance):

```dart
ListView.builder(
  builder: (context, index) {
    return BlocProvider(
      create: (_) => MyBloc(),
      child: MyListItem(...),
    );
  },
);
```

This way each instance of `MyListItem` can access its own instance of `MyBloc` via `BlocProvider.of<MyBloc>()`. Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by fedeakd** [comment]
Hello, I have taken this example but when using this, I re-build the widget with its pad and I lose its state
