### ISSUE TITLE
Deploy Intellij Plugin

### ISSUE THREAD

**Issue by felangel** [felangel/bloc#153]
Once #152 is done we need to deploy the plugin so that it is publicly available to install through the Intellij plugins search.

**Comment by felangel** [comment]
@jorgecoca created this is to track the work to deploy the Intellij Plugin

**Comment by jorgecoca** [comment]
Submitted the plugin, it might take up to two days to be approved: https://plugins.jetbrains.com/plugin/12129-bloc-code-generator
