### ISSUE TITLE
Bloc does not emit Initial value 

### ISSUE THREAD

**Issue by srinivas-codezyng** [felangel/bloc#1541]
Hi

I noticed that initial value is not emitted by the bloc in v6.0.1.
It does emit in v5.0.
Please let me know if this behaviour is changed in v6.0.1 library. 
for eg : I have created a simple LanguageBloc:

```

enum LanguageEventName{ setLanguage }

class LanguageEvent{
  final LanguageEventName name;
  final Language value;

  const LanguageEvent({this.name, this.value});
}

class LanguageBloc extends Bloc<LanguageEvent,Language>{

  LanguageBloc(Language initialState) : super(Language.english);

  @override
  Stream<Language> mapEventToState(LanguageEvent event) async *{
    switch(event.name){
      case LanguageEventName.setLanguage :
        yield event.value;
    }
  }

}


```

I did write a simple unit test around this LangauageBloc . Here is the unit test : 
```

blocTest('emits English as default when the default language set is English',
      build: () => LanguageBloc(Language.english),
      expect: [Language.english]
  );
```
test  fails with following error: 
```

 Language bloc emits English as default when the default language set is English [E]                                                                                                                                                                               
  Expected: [Language:Language.english]
    Actual: []
     Which: shorter than expected at location [0]
```

Let me know if I am missing out something here.

Thanks,
Srinivas

**Comment by felangel** [comment]
Hi @srinivas-codezyng 👋
Thanks for opening an issue!

This was an intentional breaking change made in v6.0.0 and is documented in the [migration guide](https://bloclibrary.dev/#/migration?id=%e2%9d%97bloc-does-not-emit-last-state-on-subscription).

You can test the initial state via a regular test

```dart
test(‘initial state is correct’, () {
  expect(
    LanguageBloc(Language.english).state,
    Language.english,
  );
});
```

Hope that helps! 👍

**Comment by felangel** [comment]
duplicate of https://github.com/felangel/bloc/issues/1512 and https://github.com/felangel/bloc/issues/1518.
