### ISSUE TITLE
Question: Do I have to create a bloc for each part on my app? What it the best practices?

### ISSUE THREAD

**Issue by heshaShawky** [felangel/bloc#1544]
**The question or the confusing is:**
I'm developing an **E-commerce Mobile app**, using flutter with **Bloc** as a **Design pattern** and your **flutter_bloc** ( _Thanks for that really helped_ ) package for simplifying things.

My question is: **do I have to create a bloc of each part of my app? is this the best practice for using the BLOC as a design pattern?**

For example, at **my App** on the **Home Screen** there are some sections like **best sellers and offers** ...etc, d**o I have to create a separate bloc for each section** ( _fetching the data handling the error ...etc_ )?

The sections are identical logically and user interface, the difference only on the category or the data.

So I guess that way will be there a lot of **repeated code** as well a **lot of files** and still can't do it all at once using the same bloc logically.

**Comment by felangel** [comment]
Hi @heshaShawky 👋 
Thanks for opening an issue!

I would highly recommend creating a bloc per feature. If you are fetching best sellers and offers together in the home screen then you can have a single bloc to manage fetching all of the data needed and model your state to contain both the best sellers and offers.

Hope that helps 👍
