### ISSUE TITLE
[question] Any plans to bring back ReplayCubit?

### ISSUE THREAD

**Issue by m-vellinga** [felangel/bloc#1545]
Good day!

Followed the merging of cubit into bloc very closely as I really like both and the ability to mix and match them is great.

Was wondering if you have any plans to bring back ReplayCubit in some shape or form?

Keep up the great work!

**Comment by felangel** [comment]
Hi @m-vellinga 👋 
Thanks for opening an issue and for the positive feedback -- I really appreciate it!

Regarding, your question I'm planning to have `ReplayCubit` and `ReplayBloc` exported by `package:replay_bloc` very soon. Should hopefully be available by this weekend 🤞

**Comment by m-vellinga** [comment]
Awesome! Thanks for the swift response.

If I can be of assistance in any shape or form I'd be happy to help where I can (docs/reviewing most likely).

**Comment by felangel** [comment]
Closing this since [replay_bloc](https://pub.dev/packages/replay_bloc) is now available and includes `ReplayCubit` and `ReplayBloc` 🎉
