### ISSUE TITLE
Bloc Library Timer Tutorial Incorrect Syntax

### ISSUE THREAD

**Issue by bfbenf** [felangel/bloc#1547]
The tutorial at https://bloclibrary.dev/#/fluttertimertutorial seems to have a syntax error due to an update in the bloc package.

In the UI tutorial where the action buttons are being built. The BlocBuilder uses named parameter "condition" which is being flagged as not a named parameter.  Reading your documentation and the tutorial text below I believe this should be "buildWhen" instead. 

Code: 

          BlocBuilder<TimerBloc, TimerState>(
            condition: (previousState, state) =>
                state.runtimeType != previousState.runtimeType,
            builder: (context, state) => Actions(),

**Comment by felangel** [comment]
Hi @bfbenf 👋 
Thanks for opening an issue!

I'm currently in the process of rewriting all of the tutorials and will get to the timer as soon as possible. In the meantime you can refer to the [example](https://github.com/felangel/Bloc/tree/master/examples/flutter_timer) to work through an discrepancies. Sorry for the inconvenience!

**Comment by bfbenf** [comment]
Thanks! No Problem, thanks for the very detailed tutorials so far.
