### ISSUE TITLE
[Feature request] Add support for Web platform for HydratedBloc

### ISSUE THREAD

**Issue by no1seman** [felangel/bloc#1548]
Hi,

since Flutter for Web is in beta state it would be great to add support for persistent BLOC's for Web applications.
It's quite easy to make custom Storage via plugin, but threre is a problem: Storage() class .read() method has 'dynamic' return type and it's synchronous while MethodChannel() class .invokeMethod() method has Future<T> return type and it's asynchronous so it's a little bit tricky to syncronyze sync and async code.

Thanks in advance.

**Comment by felangel** [comment]
Hi @no1seman 👋 
Thanks for opening an issue!

`hydrated_bloc v6.0.1` has flutter_web support 🎉
