### ISSUE TITLE
[Question] Difference between creating package or importing files

### ISSUE THREAD

**Issue by henryla92** [felangel/bloc#1549]
Hi,

I was just reading the new tutorial on the login flow and noticed that the authentication repository was created as a package instead of importing it as a library file. 

I was just wondering what are the benefits of using it as a package and would this be the correct way to do it for other repositories as well?

Thanks!

**Comment by RollyPeres** [comment]
Hi @henryla92 👋

This is done mostly for reusability. It's advisable to create your repositories as packages as long as there's a chance you might need to share them.

**Comment by felangel** [comment]
Hi @henryla92 👋 
Thanks for opening an issue!

As @RollyPeres mentioned, creating repositories as standalone packages makes it much easier to reuse the code across projects and also enforces a strict separation of concerns and explicit dependencies. Having repositories as packages makes it a lot easier to maintain a layered architecture where each layer has a single responsibility and also ensures that the dependency graph of your application stays clean (application only depends on repository, repository only depends on data providers).

Other benefits of this approach include being able to test and develop the repositories independently of the application.

Hope that helps 👍

**Comment by henryla92** [comment]
Thank you both for the very helpful explanations! 👍
