### ISSUE TITLE
Unused class Cart in Flutter_shopping_cart. 

### ISSUE THREAD

**Issue by leenorshn** [felangel/bloc#1555]
Hello Sir. I find that you don't use the Class Cart, Witch role this class must do.
I'm work on a shopping project like this https://github.com/leenorshn/e-commerce_bloc.git but I would like to use a Cart with Flutter_bloc but I don't know how! it can be really good if you explain more. I would have many features to do with Cart.
Please help me

**Comment by felangel** [comment]
Hi @leenorshn 👋 
Thanks for opening an issue and bringing this up!

It has been fixed in https://github.com/felangel/bloc/commit/99c5e4d9d2a12f7829dbf41ef871e1d5e936ca92 👍
