### ISSUE TITLE
How to Update Stream with Sqflite added record? 

### ISSUE THREAD

**Issue by JulianSwales** [felangel/bloc#1558]
I've been using the awesome flutter_firestore_todo, however I have a sqflite database instead of a firebase backend... So I'm attempting to adapt it.. I'm lost on one area which I've not found any matching info... 

I have this: 
```
@override
  Stream<ChecklistState> mapEventToState(
    ChecklistEvent event,
  ) async* {
    if (event is LoadChecklists) {
      yield* _mapLoadChecklistToState();
    } else if (event is AddChecklist) {
      yield* _mapAddChecklistToState(event);
    } else if (event is ChecklistsUpdated) {
      yield* _mapChecklistsUpdatedToState(event);
    }
  }

  Stream<ChecklistState> _mapLoadChecklistToState() async* {
    print('Stream: _mapLoadChecklistToState');
    _checklistSubscription?.cancel();
    _checklistSubscription = _checklistRepository.checklists().listen(
          (checklists) => add(ChecklistsUpdated(checklists)),
        );
  }

  Stream<ChecklistState> _mapAddChecklistToState(AddChecklist event) async* {
    _checklistRepository.addNewChecklist(
        event.jobSiteValue, event.equipmentValue, event.dateValue, event.list);
  } 
```

Which all works well... The one issue is in the mapAddChecklistToState, after it's done the addNewChecklist, I want to invoke the LoadChecklists so that the view gets the updated list. How would one go about getting the updates passed to the view? 

In the firebase example firebase seems to be taking care of the stream.. And in the non firebase example it's just a list, so the result gets added to the list.. The sqflite I need to load the new set of `data...`
Thanks.

**Comment by felangel** [comment]
Hi @JulianSwales 👋 
Thanks for opening an issue!

Can you elaborate a bit on why the current approach doesn't work? When you call `add(AddChecklist)` the `addNewChecklist` should emit a new event on the `checklists` stream right? This should then trigger `add(ChecklistUpdated)` with the new list which you can then yield via:

```dart
Stream<ChecklistState> _mapChecklistsUpdatedToState(ChecklistsUpdated  event) async* {
  yield event.checklists;
}
```

Let me know if that helps 👍

**Comment by JulianSwales** [comment]
@felangel 
Thank you for taking the time to look at my question. 
I'm lost on the statement "should emit a new event on the checklist stream"  That's what I've been struggling with. How would that occur? AddNewChecklist is a subroutine deep inside in a database class referenced by the checklist repository. I'm not sure I understand how such a routine would access the Bloc to add an event. Hence why I've been stuck. I know I can yield a state. Just not sure how to emit an event. 
So far all the access to bloc have been in widgets. So I'm sure I'm just not understanding some fundamental here. 
This whole journey with bloc had been one constant lightbulb moment. 😎
Thanks.

**Comment by felangel** [comment]
@JulianSwales as long as when you call `addNewChecklist` it updates `checklists` on the `_checklistRepository` then everything should work in the current state because of:

```dart
_checklistSubscription = _checklistRepository.checklists().listen(
  (checklists) => add(ChecklistsUpdated(checklists)),
);
```

You don't need to add events from inside your database class the above approach should work just fine 👍

**Comment by JulianSwales** [comment]
@felangel I've put up a demo app with my code in it... You can find it here: 
https://github.com/JulianSwales/bloctest

When you run the App, Click the Checklists button.. You will see two items.. Click the + floating action button and add a record.. Just select and on the ok lines just pick ok for the 3 records, then hit submit..It takes you back to the checklist screen, but doesn't update the list with the new record.. if you go out and back in it's there.. 

So, I'm doing something wrong, but can't figure out what.. I understand the theory behind bloc, and have been slowly getting the hang of the implementation, but this one has finally stymied me.. Thanks.

**Comment by felangel** [comment]
@JulianSwales I just took a look and there are several problems:

1. You should not extend Equatable when you are using `dynamic` so I would highly recommend having a `CheckList` class which also extends `Equatable` and making your `ChecklistLoaded` state specify the type:

```dart
class ChecklistsLoaded extends ChecklistState {
  final List<CheckList> checkLists; // this cannot be `List<dynamic>` because that is not `Equatable`

  ChecklistsLoaded(this.checkLists);

  @override
  String toString() => 'ChecklistsLoaded { displayName: $checkLists }';

  @override
  List<Object> get props => [checkLists];
}
```

2. The larger issue though is you are not using a `BlocBuilder` to update the UI when the bloc state changes so currently the bloc state is changing correctly but in the UI you are using setState and managing the checklist totally independently of the bloc.

Closing for now but hope that helps 👍
