### ISSUE TITLE
Best practices for blocbuilder and bloclistener with Location Service

### ISSUE THREAD

**Issue by MdeBruin93** [felangel/bloc#1561]
Hi @felangel ,

This is more like a question rather than an actual issue, however I'm struggling with implementing a Location Listener service in Flutter that will update the UI using a blocbuilder with a bloclistener.

What I want to do is, whenever a person presses a button the user should be taken to a screen that displays a Google maps (got this one working already). For now it just shows the location of Google for the example of the Location package, but it should eventually display the location of the user.
The thing I'm struggling with is getting this location (somehow the BLoC initialization event never fires to request permission) and updating the location whenever the OnLocationChange event of the location package fires.

I've attached my own app, maybe you could give me an hint on how to fix it.

Thanks in advance

[bens.zip](https://github.com/felangel/bloc/files/5010837/bens.zip)

**Comment by felangel** [comment]
Hi @MdeBruin93 👋 
Thanks for opening an issue!

You can have your bloc subscribe to the location stream and update it's state like:

```dart
subscription = _locationStream.listen((location) => add(LocationChanged(location)));
```

Then you can yield a new location state in response to a `LocationChanged` event like:

```dart
LocationState _mapLocationChangedToState(LocationChanged event) {
  return LocationState(coordinates: event.coordinates);
}
```

Then you can use a `BlocListener` to move the camera in response to location changes like:

```dart
BlocListener<LocationBloc, LocationState>(
  listener: (context, state) {
    _mapController?.animateCamera(
      CameraUpdate.newLatLng(state.coordinates),
    );
  },
  child: ...
);
```

Hope that helps get you on the right track 👍 

Closing for now but feel free to comment with additional questions 👍
