### ISSUE TITLE
MultiBloc provider and MultiBloc listener issue

### ISSUE THREAD

**Issue by chethanjkulkarni** [felangel/bloc#1565]
I have an app, which has 3 pages that communicate with each other. I have wrapped the first widget with MultiBlocProvider 
![Screen Shot 2020-08-03 at 1 25 43 AM](https://user-images.githubusercontent.com/30331156/89131150-44543980-d528-11ea-9e0a-b188b9dbed41.png)

I have also wrapped the first widget with BlocConsumer and it works fine.

![Screen Shot 2020-08-03 at 1 27 31 AM](https://user-images.githubusercontent.com/30331156/89131187-841b2100-d528-11ea-9512-618efa769809.png)

In my second screen ```details.dart```, I have wrapped it using a ```MultiBlocListener``` as your [Counter and Random example](https://github.com/tadaspetra/bloc_examples/tree/master/003_multiple_blocs)

![Screen Shot 2020-08-03 at 1 29 48 AM](https://user-images.githubusercontent.com/30331156/89131237-d4927e80-d528-11ea-97b7-a7daf80976ca.png)

When I move to this page using ```Navigator.push( ... )``` from my first page, I get the following error

![Screen Shot 2020-08-03 at 1 34 14 AM](https://user-images.githubusercontent.com/30331156/89131311-72864900-d529-11ea-926f-68758373a93d.png)

_Originally posted by @chethanjkulkarni in https://github.com/felangel/bloc/issues/74#issuecomment-667718435_

**Comment by felangel** [comment]
Hi @chethanjkulkarni 👋 
Thanks for opening an issue!

This is because when you navigate to a new route (`Navigator.of(context).push(...)`), the new `BuildContext` doesn't have access to the previous widgets. To solve this you can wrap your `MaterialPageRoute` in a `BlocProvider.value` to re-provide the existing bloc to the new route:

```dart
ListTile(
  onTap: () {
    Navigator.of(context).push(MaterialPageRoute(
      builder: (_) {
        return BlocProvider.value(value: context.bloc<InvoiceBloc>(), child: Details(...));
      }
  },
)
```

You can refer to the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=anonymous-route-access) for more information 👍

**Comment by chethanjkulkarni** [comment]
How do I pass multiple BlocProviders inside ```Blocprovider.value()```, because when I try to access the one of the bloc provided in MultiBlocProvider in the third page, I get the same error mentioning that the current bloc has no ancestor of previous bloc ?

**Comment by felangel** [comment]
You can use `MultiBlocProvider` with `BlocProvider.value` like:

```dart
MultiBlocProvider(
  providers: [
    BlocProvider.value(value: context.bloc<InvoiceBloc>()),
    BlocProvider.value(value: context.bloc<InvoiceDetailsBloc>()),
    BlocProvider.value(value: context.bloc<EditInvoiceBloc>()),
  ],
  child: Details(...),
);
```

**Comment by chethanjkulkarni** [comment]
Thank you @felangel . All working fine now

**Comment by chethanjkulkarni** [comment]
Hi, @felangel 
I am using a bloc across 4 different screens(stacked one after another), and quite weird, when I change the state at 4th screen, my first screen doesn't get updated according to the new state
Note: I am not creating new context for every navigation, but passing the same context using
```
BlocProvider.value(
     value: BlocProvider.value<ProfileBloc>(context),
     child: ...
)
```
Is there something I am doing wrong here ?
