### ISSUE TITLE
how to do if initstate need async

### ISSUE THREAD

**Issue by hu70258tao** [felangel/bloc#1567]
some initstate need get data from http or shared_preferences ，how to do it ?

**Comment by RollyPeres** [comment]
Hi @hu70258tao 👋

You can simply initialize bloc with a default value for the state and add an event upon bloc creation that will result in fetching state from http/prefs + yield the new state.

Hope that helps 👍

**Comment by hu70258tao** [comment]
i get it, send initecent,and do  http during deal this event ?

**Comment by felangel** [comment]
@hu70258tao yup add an event, immediately trigger a loading state, then once the request completes update the state 👍
