### ISSUE TITLE
[Question] How to use mockito verify while testing blocs?

### ISSUE THREAD

**Issue by nerder** [felangel/bloc#157]
Hello

I would like to understand a little bit how can i use `verify` while testing a bloc. I wasn't able to find any example around and all my attempt have failed, leaving me no other options that put my `verify` checks into the `tearDown` statement which of course is not optimal. 

The issue I encounter is basically that when the test runs, the `verify` method have been called before `mapEventToState` resulting in make my test fail.

### Code example

*auth_bloc.dart*
```dart
import 'package:bloc/bloc.dart';
import 'package:checkin/src/blocs/auth/auth_event.dart';
import 'package:checkin/src/blocs/auth/auth_state.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:meta/meta.dart';

class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final FirebaseAuth auth;

  AuthBloc({
    @required this.auth
  });

  @override
  AuthState get initialState => AuthUninitialized();

  @override
  Stream<AuthState> mapEventToState(AuthState currentState, AuthEvent event) async* {
    /*
     ...
    */
    if (event is LoggedOut) {
      this.auth.signOut();
      yield AuthUnauthenticated();
    }
  }
}
```

*auth_bloc_test.dart*
```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:mockito/mockito.dart';
import 'package:checkin/src/blocs/auth/bloc.dart';
import 'package:test/test.dart';

class MockFirebaseAuth extends Mock implements FirebaseAuth {}
class MockFirebaseUser extends Mock implements FirebaseUser {}

void main() {
  group('AuthBloc', () {
    AuthBloc authBloc;
    MockFirebaseAuth firebaseAuth;

    setUp(() {
      firebaseAuth = MockFirebaseAuth();
      authBloc = AuthBloc(auth: firebaseAuth);
    });
    
    group('dispatch LoggedOut', () {
      setUp(() {
        authBloc.dispatch(LoggedOut());
      });

      //@TODO: not a good solution
      tearDown(() {
        verify(firebaseAuth.signOut()).called(1);
      });
      test("the final state should be AuthAuthenticated and pass the current user", () {
        final expectedState = [
          AuthUninitialized(),
          AuthUnauthenticated(),
        ];

        expectLater(
          authBloc.state,
          emitsInOrder(expectedState),
        );
      });
    });
 });
}
```

**Comment by felangel** [comment]
Hey @nerder 👋 

Great question! You can do the verification in the `then` of the `expectLater` like:

```dart
expectLater(authBloc.state, emitsInOrder(expectedState)).then(() {
  verify...
});
```

You can check out a todos app that is fully tested at the [flutter_architecture_samples](https://github.com/brianegan/flutter_architecture_samples/tree/master/bloc_library) for more details.

Hope that helps! 👍

**Comment by nerder** [comment]
Amazing! Thank you so much for the fast reply and for this library, it makes coding with Blocs SO smooth!

**Comment by haroldolivieri** [comment]
> Hey @nerder 👋
> 
> Great question! You can do the verification in the `then` of the `expectLater` like:
> 
> ```dart
> expectLater(authBloc.state, emitsInOrder(expectedState)).then(() {
>   verify...
> });
> ```
> 
> You can check out a todos app that is fully tested at the [flutter_architecture_samples](https://github.com/brianegan/flutter_architecture_samples/tree/master/bloc_library) for more details.
> 
> Hope that helps! 👍

`then()` waits for a `FutureOr<T>` so you need to set the returning type `<T>`, in this case, `<void>`. And you need to declare the callback param, so you need to add, at least `_` :

```dart
expectLater(authBloc.state, emitsInOrder(expectedState)).then<void>((_) =>  verify(repository.foo()).called(1));
```

Can be pretty obvious but I spent some time to figure it out, helping others to do not.

**Comment by apieceofcode1801** [comment]
Sorry because of commenting on this closed issue. 
But I have a failed test using mockito`expectLater` with the array of States and I have no idea about this failure.
Please help to review it.
Implemented code:
```
on<GetTriviaForRandomNumber>((event, emit) async {
      emit(Loading());
      final result = await getRandomNumberTrivia(NoParams());
      result.fold(
          (failure) => emit(Error(message: _mapFailureToMessage(failure))),
          (trivia) => emit(Loaded(trivia: trivia)));
    });
```
Testing code:
```
test('''should emit [Loading, Error] with a proper
    message for the error when getting data fails''', () async {
      // arrange
      when(mockGetRandomNumberTrivia(any))
          .thenAnswer((_) async => Left(CacheFailure()));
      // assert later
      final expected = [
        Empty(),
        Loading(),
        Error(message: cacheFailureMessage)
      ];
      expectLater(bloc.state, emitsInOrder(expected));
      // act
      bloc.add(GetTriviaForRandomNumber());
    });
```
The testing fails:
```
Expected: should do the following in order:
          • emit an event that Empty:<Empty()>
          • emit an event that Loading:<Loading()>
          • emit an event that Error:<Error(Cache Failure)>
  Actual: Empty:<Empty()>
   Which: was not a Stream or a StreamQueue
```
Thanks!

**Comment by Safal-Shrestha-SS** [comment]
> 

Use: 
``expectLater(bloc.stream),emitsInOrder(expected);``
and remove Empty() from the expected variable. Initial state can be tested separately.

**Comment by claresudbery** [comment]
In case like me you're using `blocTest`, the structure looks a little different, and you can verify expectations on mocks using the following syntax:

```dart
blocTest('Does a thing',
    build: () => MyBloc(),
    setUp: () {
        when(
            () => mockMyService.doThing(
                user.id!,
            ),
        ).thenAnswer((_) => Future.value());
    },
    act: (bloc) {
        bloc.add(Myevent(user: user,),);
    },
    expect: () => [
        const MyState(),
    ],
    verify: (_) {
        verify(
            () => mockMyService.doThing(
                user.id!,
            ),
        ).called(1);
    },
);
```
