### ISSUE TITLE
Rename Cubit to Bloc, and the current Bloc to EventBloc or similar with Bloc keyword

### ISSUE THREAD

**Issue by CurrySenpai** [felangel/bloc#1570]
Related to https://github.com/felangel/bloc/issues/1560 

Hello, I suggested this is discord a few days ago

Why not rename 
* `Cubit` to `Bloc`
* And the current `Bloc` to another related to bloc like `EventBloc` or similar with `Bloc` keyword,

I think using cubit is the right decision for most cases, but the name is confusing if the bloc pattern is being implemented.

It would be an important change for current users, but I think it would help a lot of new users to use the bloc pattern, they would start using `Bloc` (previously `Cubit`), and if they have complex cases use the `EventBloc` (the current bloc), the api would be more related to the bloc pattern.

For example for now it sounds strange that the `BlocBuilder` receives a cubit

although felix said
> Also cubit isn’t technically a bloc
Because there is no event sink so it’d be a bit misleading to name it Bloc imo

although technically it is true due to the implementation, we can see that `Cubit` is a short/easy way to use `Bloc` in some cases 

Check https://github.com/felangel/bloc/issues/1427

<details>
<summary>Bloc</summary>

```dart
class MyBloc extends Bloc<MyState, MyState> {
  MyBloc(): super(MyState.initial());

  @override
  Stream<State> mapEventToState(MyState state) async* {
    yield state;
  }

  void someAction() {
    final nextState = _getNextState();
    add(nextState);
  }
}
```
</details>

<details>
<summary>Cubit</summary>

```dart
class MyBloc extends Cubit<MyState> {
  MyBloc(): super(MyState.initial());

  void someAction() {
    final nextState = _getNextState();
    emit(nextState);
  }
}
```
</details>

Which is why I think it would be worth considering it as a `bloc` despite not complying with the rule
> Inputs and outputs are simple Stream/Sinks only

Related to https://github.com/felangel/bloc/issues/1560 
Since now we can use the same `BlocListener`, BlocBuilder`, and `BlocConsumer` for `Bloc` (previously `Cubit`) and `EventBloc` or similar with `Bloc` keyword (previously `Bloc`) without having any confusion with names

**Comment by felangel** [comment]
Hi @CurrySenpai 👋 
Thanks for opening an issue!

I would really prefer not to do this because:

1. It's extremely disruptive -- every resource/article/tutorial/example that previously used `Bloc` will no longer make sense and it will be very confusing in my opinion.

2. It's not accurate -- a `Cubit` is not a `Bloc` (there is no event sink) so it is misleading and will lead to more confusion.

Closing this for now in favor of continuing this discussion in #1560
