### ISSUE TITLE
[Discussion] How to test event added in bloc?

### ISSUE THREAD

**Issue by Dexter-C** [felangel/bloc#1571]
Hi 
First of all great framework and tooling, here is what I have

`

    @override
      Stream<GalleryState> mapEventToState(GalleryEvent event) async* {
        if (event is LoadGallery) {
          yield* _mapLoadEventToState(event);
        }

        if (event is UploadGallery && state is GalleryLoaded) {
          yield* _mapUploadEventToState(event);
        }
      }

`

now I need to upload after gallery is loaded, this is how I did it
`

    Stream<GalleryState> _mapLoadEventToState(GalleryEvent event) async* {
        yield GalleryLoading();

        try {
          final List<Asset> res = await galleryRepository.loadAssets();
          yield GalleryLoaded(assetList: res);
          this.add(UploadGallery());
        } catch (error) {
          exceptionBloc.add(ThrowLoadException());
        }
      }

`

as you can see, I use ` this.add(UploadGallery());` in load bloc to trigger upload bloc, this works as expect, however I'm not sure how to test this event with blocTest. any suggestion?

**Comment by felangel** [comment]
Hi @Dexter-C 👋 
Thanks for opening an issue and for the positive feedback!

To test this you can do something like:

```dart
blocTest(
  '...',
  build: () => GalleryBloc(),
  act: (bloc) => bloc.add(GalleryLoaded()),
  wait: Duration.zero, // wait one extra event-loop iteration for the second add to be processed
  expect: [
    GalleryLoading(),
    GalleryLoaded(...),
    // whatever states are emitted as a result of UploadGallery
  ],
);
```

Hope that helps 👍
