### ISSUE TITLE
onError in the BlocObserver doesn't take the Bloc

### ISSUE THREAD

**Issue by 0Vipin0** [felangel/bloc#1579]
**Describe the bug**
I was implementing the latest version for the Bloc Todos app. I found one anomaly in the BlocObserver that onError only takes the Cubit as a parameter but Bloc is not there. So, I want to ask is this intentional or any kind of bug @felangel ?

**To Reproduce**
1. Change the previous Bloc Delegate with the Bloc Observer.
2. onError will autmatically give error in the dart analysis.

**Expected behavior**
It should be able to handle Cubit and Bloc both.

**Logs **
error: 'SimpleBlocObserver.onError' ('void Function(Bloc<dynamic, dynamic>, Object, StackTrace)') isn't a valid override of 'BlocObserver.onError' ('void Function(Cubit<dynamic>, Object, StackTrace)'). (invalid_override at [bloc_todo] lib\bloc\bloc_delegate.dart:17)

**Comment by felangel** [comment]
Hi @0Vipin0 👋 
Thanks for opening an issue!

This is intentional because all `Blocs` are also `Cubits` 👍

**Comment by andesappal** [comment]
Hi @felangel! What should I do here?
![image](https://user-images.githubusercontent.com/54340176/121762415-1bb7ab80-cb0c-11eb-9d54-ae04a753b920.png)

**Comment by felangel** [comment]
@andesappal please refer to https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/lib/app/bloc_observer.dart
