### ISSUE TITLE
Issue with expectLater in flutter tests when two blocs update at the same time since update from 4.0.0 to 6.0.1

### ISSUE THREAD

**Issue by obshksw** [felangel/bloc#1581]
So I wanted to upgrade bloc from 4.0.0 to 6.0.1 but a lot of my tests are now broken.

For example I have a test similar to this:
```
test("", () async {
      _hubConnectionMock.fakeConnect();

      await expectLater(_subroomManager.activeSubRoomBloc, emitsThrough(isA<SubRoomActiveState>()));
      await expectLater(_chatManager.chatBloc, emitsThrough(isA<ChatInitializedState>()));
    });
```

Basically I want to test that when I connect, my two blocs are initialized. This used to work, but now fails because it never goes past the second await expectLater.

I recreated a full working sample:
```
abstract class TestEvent {}
class TestInitEvent extends TestEvent {}
abstract class TestState {}
class TestUnInitState extends TestState {}
class TestInitState extends TestState {}
class TestBloc extends Bloc<TestEvent, TestState> {
  TestBloc() : super(TestUnInitState());

  @override
  Stream<TestState> mapEventToState(TestEvent event) async* {
    if (event is TestInitEvent) {
      yield TestInitState();
    }
  }
}

    test('Test broken test', () async {
      Bloc<TestEvent, TestState> bloc1 = TestBloc();
      Bloc<TestEvent, TestState> bloc2 = TestBloc();
      bloc1.add(TestInitEvent());
      bloc2.add(TestInitEvent());
      await expectLater(bloc1, emits(isA<TestInitState>()));
      await expectLater(bloc2, emits(isA<TestInitState>()));
    });
```

Is it related to "Bloc does not emit last state on subscription" ? 

I can fix it by validating the second bloc with a simple expect, but it feels weird to assume that if my first bloc is updated then the second is.

or I could do:
```
if (bloc2.state is! TestInitState) {
        await expectLater(bloc2, emits(isA<TestInitState>()));
      }
```
But it's kinda ugly haha!

Maybe it's a test package issue, but it happens only after this dependency update.

**Comment by obshksw** [comment]
Update: Everything is working as expected in 5.0.1.

**Comment by felangel** [comment]
Hi @obshksw 👋 
Thanks for opening an issue and yes this is expected because in v6.0.0 blocs no longer emit the latest state upon subscribing. You should be able to adjust your test to look like:

```dart
test('Test broken test', () {
      Bloc<TestEvent, TestState> bloc1 = TestBloc();
      Bloc<TestEvent, TestState> bloc2 = TestBloc();
      expectLater(bloc1, emits(isA<TestInitState>()));
      expectLater(bloc2, emits(isA<TestInitState>()));
      bloc1.add(TestInitEvent());
      bloc2.add(TestInitEvent());      
    });
```

This way you will start listening for changes because actually adding the events. Hope that helps 👍

**Comment by obshksw** [comment]
> Hi @obshksw 👋
> Thanks for opening an issue and yes this is expected because in v6.0.0 blocs no longer emit the latest state upon subscribing. You should be able to adjust your test to look like:
> 
> ```dart
> test('Fixed test', () {
>   Bloc<TestEvent, TestState> bloc1 = TestBloc();
>   Bloc<TestEvent, TestState> bloc2 = TestBloc();
>   expectLater(bloc1, emits(isA<TestInitState>()));
>   expectLater(bloc2, emits(isA<TestInitState>()));
>   bloc1.add(TestInitEvent());
>   bloc2.add(TestInitEvent());      
> });
> ```
> 
> This way you will start listening for changes before actually adding the events. Hope that helps 👍

Thank you for your reply and the help @felangel, I appreciate it! :)
Although it does fix this test example, it does not really fix my actual problem... 
Some tests validates the values in my state with an `expect`, so I need `await expectLater`, and then can't put it before the events.

Any idea how to resolve that?

**Comment by felangel** [comment]
@obshksw any reason why you're not using `blocTest`?

**Comment by obshksw** [comment]
No reason in particular, I just never used it/noticed it. I'll look into it, but from what I understand, it doesn't seem it would fix my problem anyway for my integration tests! But I guess I could refactor the tests and make it work? 

Unfortunately, I don't really have more time to work on this right now, certainly not for a refactor haha! :) 

I'll stay at 5.0.1 for now and will see to plan more time in the future to migrate this.

Thanks for your help!
