### ISSUE TITLE
I can longer find BlocDelegate class

### ISSUE THREAD

**Issue by mwenechac** [felangel/bloc#1583]
I can no longer find the BlocDelegate class after upgrading to version 6. What has replaced it, if there is any replacement. I used it like so previously:

class SimpleBlocDelegate extends BlocDelegate {
  @override
  void onEvent(Bloc bloc, Object event) {
    print('onEvent $event');
    super.onEvent(bloc, event);
  }

  @override
  onTransition(Bloc bloc, Transition transition) {
    print('onTransition $transition');
    super.onTransition(bloc, transition);
  }

  @override
  void onError(Bloc bloc, Object error, StackTrace stackTrace) {
    print('onError $error');
    super.onError(bloc, error, stackTrace);
  }
}

**Comment by RollyPeres** [comment]
Hi @mwenechac 👋

It was renamed to `BlocObserver`. You can check out the [migration guide](https://bloclibrary.dev/#/migration) for more details.

If you encounter additional problems migrating your code, feel free to comment and I'll help you further 👍

**Comment by mwenechac** [comment]
Great. Thanks
