### ISSUE TITLE
[proposal] Publish "bloc" on "open-vsx"

### ISSUE THREAD

**Issue by iapicca** [felangel/bloc#1588]
Hi,
please consider helping developers on [VSCodium](https://github.com/VSCodium/vscodium) and [eclipse theia](https://theia-ide.org/) 
to have a smoother experience publishing this super-useful extension on [open-vsx](https://open-vsx.org/)
(it doesn't seem a time consuming task [link](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions))
Thank you

**Comment by felangel** [comment]
Hi @iapicca 👋 
Thanks for opening an issue!

I've published the [extension](https://open-vsx.org/extension/FelixAngelov/bloc) 👍

**Comment by iapicca** [comment]
rated ;)
