### ISSUE TITLE
question: What is the best way to edit a single item on the list? 

### ISSUE THREAD

**Issue by heshaShawky** [felangel/bloc#1592]
**The Questions:**
What is the best way to edit a single item on the array using the bloc? What I'm doing now is changing the whole array on an event like for example user click on the **like** button for a **post** I change the whole array with a lot of mapping and through back as a new array to the state and feel I run kinda complex code for a simple thing.

```dart
Stream<PostsState> _mapLikePostToState(LikePost event, PostsState currentState) async* {
  if ( currentState is PostsLoaded ) {
    final sp = await SharedPreferences.getInstance();

    dynamic postsLikedByUser = sp.getString('likedList');
    postsLikedByUser = jsonDecode(postsLikedByUser);

    yield currentState.copyWith(
      posts: currentState.posts.map(
        (post) {
          if (post.id == event.articleId) {
            if (post.isLiked) {
              postsLikedByUser.remove(post.id);
              sp.setString('likedList', postsLikedByUser.toString());
              
              return post.copyWith(isLiked: false, likesCount: post.likesCount - 1);
            }

            if ( postsLikedByUser != null ) {
              
              postsLikedByUser.add(post.id);
              sp.setString('likedList', postsLikedByUser.toString());
              postsRepostiry.likePost(event.articleId);
            }

            return post.copyWith(isLiked: true, likesCount: post.likesCount + 1);
          }

          return post;
        },
      ).toList(),
    );
  }
}
```

**Comment by felangel** [comment]
Hi @heshaShawky 👋 
Thanks for opening an issue!

I would recommend using the solution described in https://github.com/felangel/bloc/issues/1091#issuecomment-622668426. Let me know if that helps 👍

**Comment by heshaShawky** [comment]
> Hi @heshaShawky 👋
> Thanks for opening an issue!
> 
> I would recommend using the solution described in [#1091 (comment)](https://github.com/felangel/bloc/issues/1091#issuecomment-622668426). Let me know if that helps 👍

That's what I'm doing as my sample code above, but I feel is perform badly, as I have for example ads on the list as ( web views ) when doing this the whole list will refresh as well my web views too.

**Comment by felangel** [comment]
@heshaShawky can you provide a sample app which illustrates the issue? Why are the ads nested inside the BlocBuilder if they don't need to be rebuilt in response to state changes?

**Comment by heshaShawky** [comment]
> @heshaShawky can you provide a sample app which illustrates the issue? Why are the ads nested inside the BlocBuilder if they don't need to be rebuilt in response to state changes?

because I wanna show my ads on the posts list, and normally the posts whole list wrapped by the BlocBuilder<PostsBloc, PostsState> to build the posts list I got from the API.

**Comment by heshaShawky** [comment]
Any thoughts?

**Comment by RollyPeres** [comment]
Have you considered using [admob_flutter](https://pub.dev/packages/admob_flutter) ?

**Comment by heshaShawky** [comment]
> Have you considered using [admob_flutter](https://pub.dev/packages/admob_flutter) ?

Yes, that's what I'm already using, and on any change inside the builder the ads will be reloaded ( The Plugin depends on a web view )

**Comment by RollyPeres** [comment]
First of all, you should use the approach described [here](https://flutter.dev/docs/cookbook/lists/mixed-list) to handle different types on your list instead of using separators.
Secondly, I don't find this to be an issue related to bloc, since you'll get it with any approach to rendering the listview.
If you want to use bloc to solve this issue then you could create an individual bloc for each item which is not an ad, but you might be better of opening an issue on their repo, since this is a side effect of how they implemented their library.

**Comment by heshaShawky** [comment]
> If you want to use bloc to solve this issue then you could create an individual bloc for each item which is not an ad,

Yes, this is what I need to do for now, how I could implement this?

**Comment by RollyPeres** [comment]
You literally wrap each list item in a bloc.
```
ListView.builder(
          itemBuilder: (context, index) => BlocProvider<ItemBloc>(
            create: (_) => ItemBloc(),
            child: ListItem(),
          ),
        ),
```

**Comment by shamnex** [comment]
> You literally wrap each list item in a bloc.
> 
> ```
> ListView.builder(
>           itemBuilder: (context, index) => BlocProvider<ItemBloc>(
>             create: (_) => ItemBloc(),
>             child: ListItem(),
>           ),
>         ),
> ```

Hi @RollyPeres,

I've tried this way of doing it and while it worked really well but I had one issue,  especially with the `ListView.builder` and I would like so hear your opinion on this:

`ListView.Builder` destroys it's child widgets when those widgets are scrolled off the screen and in this use-case closing each `ItemBloc` that is off the screen. This seems like a good thing until you have to make asynchronous calls within the `ItemBloc` that might take a while and if the user scrolls the widget off-screen during the call, the state is lost. How would you solve or approach this? Or would you move all asynchronous calls to the Parent `ListBloc()`?

**Comment by RollyPeres** [comment]
Hi @shamnex 👋

I find using a dedicated bloc for each list item to be a workaround actually, so I don't encourage doing so. Normally you would manage the entire list using a single bloc.

Your question is very subjective and there's no right answer to it; it basically all boils down to your exact requirements.

If reducing the number of async requests is what you care about, then you can definitely make use of `addAutomaticKeepAlives` to prevent your list items from being destroyed.
If that's too drastic for you then you can increase your `cacheExtent` to prevent items being quickly destroyed upon leaving the visible viewport.

**Comment by shamnex** [comment]
@RollyPeres Thanks a lot for the feedback! And you are right, there's exactly no right answer to this. I think `cacheExtent` would be the best solution for my use-case.

Thanks again.

**Comment by felangel** [comment]
Closing this for now since it appears the original question has been answered 👍
