### ISSUE TITLE
Offer a way to execute an action on "initial state"/ when a widget has been loaded

### ISSUE THREAD

**Issue by jorgecoca** [felangel/bloc#16]
**Is your feature request related to a problem? Please describe.**
As a user of `bloc`, I'd like to have a way to identify a `WidgetHasBeenLoaded` UiEvent. This way, if I need to respond in my bloc to an action immediately after a widget has been drawn on the screen, I can do it without relying on the bloc constructor, which might be too late.
By also following this approach, we would respect the single input/single output, allowing us to still track the events and responses.

**Describe the solution you'd like**
We might have to alternatives:

```dart
  @override
  Stream<SalutationUiState> mapEventToState(
      SalutationUiState state, event) async* {
    if (event is WidgetHasBeenLoaded) {
      // do your job here
    }
  }
```
where `WidgetHasBeenLoaded` is a UiEvent provided by Bloc.

Or we could add an additional method, optional, to the bloc API that is just: `Future<UiState> onInitialEvent()` (or similar).

**Describe alternatives you've considered**
At this moment, the only way to achieve this is using the bloc's constructor. However, that might be too soon: if you initialize your bloc in an upper node of your tree, but it is only consumed in a widget on lower leafs, we might get the result of the action before even the widget was rendered.

**Comment by felangel** [comment]
@jorgecoca im not sure I fully understand the problem we are trying to solve.

Couldn’t you notify the bloc by dispatching a WidgetLoaded event from the widget’s constructor?

I’m also worried about this being a flutter specific request. The library should ideally stay decoupled from flutter.

**Comment by felangel** [comment]
@jorgecoca closing for now. I’d be happy to reopen if you have more feedback/suggestions.
