### ISSUE TITLE
Number of bloc/cubits per screen

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#1604]
**Is your feature request related to a problem? Please describe.**
How many blocs/cubits I need to create if I get data from **n** i.e rest api in one screen

**Comment by RollyPeres** [comment]
Hi @II11II 👋

It certainly depends on how you plan on showing that data and the different states involved, but most of the time you would end up needing a single bloc/cubit and sending those n requests with a `Future.wait`.

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

When thinking about how many blocs/cubits I would avoid thinking about the data layer and think about the feature/use-case. Generally, you should have one bloc/cubit per feature regardless of the number of http requests, etc...

Hope that helps 👍
