### ISSUE TITLE
Project structure for bloc and/or cubit from FELANGEL)

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#1605]
**Additional context**
**Good Example Project structure for bloc and/or cubit**

**Comment by RollyPeres** [comment]
Hi @II11II 👋

While waiting for @felangel 's answer you can check out a couple of [project structures](https://bloclibrary.dev/#/faqs?id=project-structure) in the official docs.

I also know for a fact that he recommends a per feature project structure and so do I. At the end of the day it's really up to the developer/team to go with what feels better and easier to work with.

I hope that is of help, but if you need further clarification I'm sure @felangel will gladly help you out. 👍

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

As @RollyPeres mentioned, I recommend a feature-based project structure which separate modules (packages) for the data and repository layers.

You can check out the revamped [firebase login example](https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login) as a reference 👍 

Closing for now but feel free to add additional comments/questions and I'm happy to continue the conversation!
