### ISSUE TITLE
ArchSampleKeys question

### ISSUE THREAD

**Issue by YanaKrivitskaya** [felangel/bloc#1610]
Hi there!

Maybe a stupid question but it is not obvious to me where ArchSampleKeys in Flutter todo app comes from... 
Can you please point me to the right direction?

**Comment by felangel** [comment]
Hi @YanaKrivitskaya 👋 
Thanks for opening an issue!

They are coming from https://github.com/brianegan/flutter_architecture_samples/blob/master/todos_app_core/lib/src/keys.dart.

Hope that helps 👍
