### ISSUE TITLE
How to test Bloc-to-Bloc communication

### ISSUE THREAD

**Issue by Dexter-C** [felangel/bloc#1612]
Hi @felangel 
I have same issue, but I don't understand your solution.
say there are two bloc, A_Bloc and B_Bloc, B_Bloc is depend on A_Bloc

`

    class B_Bloc extends Bloc<B_Event, B_State> {
     final A_Bloc a_bloc;
      StreamSubscription a_BlocSubscription;

      B_Bloc({@required this.a_bloc}) : assert(a_bloc != null) {
        a_BlocSubscription = a_bloc.listen((state) {
          if (state is Some_A_State) {
            this.add(Some_B_Event());
          }
        });
      }
    }

`

now I want to test this bloc logic, 
`

    blocTest(
      'should fire event in response to a_bloc state change',
      build: () {
        when(a_Bloc.state)
            .thenReturn(Some_A_State());
        return b_Bloc;
      },
      act: (B_Bloc bloc) async {
        a_Bloc..add(Some_A_Event());   // fire A_Event, trigger A_State change, 
        // bloc.a_bloc.add(Some_A_Event()); // this won't work neither 
      },
      expect: <B_State>[
        Some_B_State(),
      ],
    );

`

the idea is: add A_Event triggers A_State change, B_Bloc should notice A_State changed, then add B_Event, however when I run test, the actual output is a list of empty state.

I don't know how to test this bloc.listen logic, any suggestion?

_Originally posted by @Dexter-C in https://github.com/felangel/bloc/issues/335#issuecomment-673211531_

**Comment by felangel** [comment]
HI @Dexter-C 👋 
Thanks for opening an issue!

You can use `MockBloc` from `bloc_test` to create a mock instance of the base bloc and then use `whenListen` to stub the `Stream` of states from the base bloc like so:

```dart
import 'package:bloc/bloc.dart';
import 'package:bloc_test/bloc_test.dart';
import 'package:test/test.dart';

abstract class CoreEvent {}

abstract class CoreState {}

class CoreStateA extends CoreState {}

class CoreStateB extends CoreState {}

abstract class CoreBloc extends Bloc<CoreEvent, CoreState> {
  CoreBloc(CoreState state) : super(state);
}

abstract class OtherEvent {}

class OtherEventA extends OtherEvent {}

class OtherEventB extends OtherEvent {}

abstract class OtherState {}

class OtherStateA extends OtherState {}

class OtherStateB extends OtherState {}

class OtherBloc extends Bloc<OtherEvent, OtherState> {
  OtherBloc(CoreBloc coreBloc) : super(OtherStateA()) {
    coreBloc.listen((coreState) {
      if (coreState is CoreStateA) {
        add(OtherEventA());
      } else if (coreState is CoreStateB) {
        add(OtherEventB());
      }
    });
  }

  @override
  Stream<OtherState> mapEventToState(OtherEvent event) async* {
    if (event is OtherEventA) {
      yield OtherStateA();
    } else if (event is OtherEventB) {
      yield OtherStateB();
    }
  }
}

class MockCoreBloc extends MockBloc<CoreState> implements CoreBloc {}

void main() {
  group('OtherBloc', () {
    CoreBloc coreBloc;

    setUp(() {
      coreBloc = MockCoreBloc();
    });

    blocTest<OtherBloc, OtherState>(
      'emits [OtherStateB] when coreBloc emits CoreStateB',
      build: () {
        whenListen(coreBloc, Stream.value(CoreStateB()));
        return OtherBloc(coreBloc);
      },
      expect: [isA<OtherStateB>()],
    );
  });
}
```

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by karabanovbs** [comment]
@felangel, hello!
 But what can I do, when I use stream API in `OtherBloc `.
 
For example: 
```
  OtherBloc(CoreBloc coreBloc) : super(OtherStateA()) {
    _subscription = coreBloc.where(**do something**).listen((coreState) {
      if (coreState is CoreStateA) {
        add(OtherEventA());
      } else if (coreState is CoreStateB) {
        add(OtherEventB());
      }
    });
  }
```
 In this case `where` function returns `null`.

I should mock all stream API?
