### ISSUE TITLE
BlocDelegate

### ISSUE THREAD

**Issue by ninoid** [felangel/bloc#1618]
Not sure why I cant access to BlocDelegate and BlocSupervisor with bloc 6.0.1?

**Comment by felangel** [comment]
Hi @ninoid 👋 
Thanks for opening an issue!

`BlocDelegate` has been renamed to `BlocObserver` and `BlocSupervisor` was removed. Check out the [migration guide](https://bloclibrary.dev/#/migration?id=%e2%9d%97blocdelegate-renamed-to-blocobserver) for more details 👍

**Comment by ninoid** [comment]
Thanks a lot for the update. 👍
