### ISSUE TITLE
Unnecessary performance loss

### ISSUE THREAD

**Issue by rs5173** [felangel/bloc#1623]
There are three Widgets under the same WdigetTree, namely WidgetA, WidgetB, and WidgetC. The states they respond to are StateA, StateB, and StateC, because they listen to the same Stream (depending on the same BLoC). When StateA responds, WidgetA, Both WidgetB and WidgetC will be rebuilt at the same time, but in fact WidgetB and WidgetC do not need to be updated. If these three Widgets are very complex, it will cause unnecessary performance loss. Is there any way to prevent this from happening?

Thanks!

**Comment by felangel** [comment]
Hi @rs5173 👋 
Thanks for opening an issue!

It sounds like your single bloc has too many responsibilities and you should probably split up the bloc into three smaller, more focused blocs (or cubits). That way you can have each widget only react to changes on the stream it cares about.

Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions or details and I'm happy to continue the conversation 👍
