### ISSUE TITLE
[ Chinese Docs ] Update Introduction part

### ISSUE THREAD

**Issue by jakecastelli** [felangel/bloc#1628]
Hi guys,

Since there are a lot changes happened since bloc v4, I will be tying to keep the Simplified-Chinese docs updated.

I will start from the introduction part again, and gradually updating the bloc docs.

Here is my plan:

- Introduction:
  - [x] Getting Started
  - [x] Why Bloc?

  - Core Concept
    - [x] package:bloc
    - [x] package:flutter_bloc
  - [x] Architecture
  - [x] Testing
  - [x] Naming Conventions
  - [x] FAQs Migration
  - [ ] Migration

**Comment by felangel** [comment]
Closing this for now since #1630 was merged. We can address the remaining sections separately 👍
