### ISSUE TITLE
Is it possible to trigger render without BlocBuilder?

### ISSUE THREAD

**Issue by giovanigm** [felangel/bloc#1633]
Hello,

I'd like to avoid having to use BlocBuilder all the time, but `context.bloc<MyCubit>()` does not trigger render. I've tried using `Provider.of<MyCubit>(context, listen: true)` but it does not work either.

Is there a way to trigger render without using BlocBuilder? Or someway to use provider package methods `context.watch()` and `context.select()` with this library?

Best regards.

**Comment by felangel** [comment]
Hi @giovanigm 👋 
Thanks for opening an issue!

Currently, `BlocBuilder` is the preferred way to render widgets in response to state changes. Check out https://github.com/felangel/bloc/issues/1521 regarding adding `selector` support and provide additional context regarding why you feel `BlocBuilder` is not adequate if possible? Thanks! 👍

**Comment by giovanigm** [comment]
Hi @felangel, I just think provider's way to render through context extension methods are simpler than using a widget specifically for that, that's all. Thanks for the answer any way!
