### ISSUE TITLE
[VScode] Problem with generating Bloc folder with Freezed package

### ISSUE THREAD

**Issue by nguyenduckhai** [felangel/bloc#1635]
I have no intension of using freezed in Bloc but the extension kept generate freezed bloc folder. My question is how can I change it back to generate default folder?

**Comment by felangel** [comment]
Hi @nguyenduckhai 👋
Thanks for opening an issue!

Currently it defaults based on the dependencies in your pubspec but I will add the ability to override that behavior 👍
