### ISSUE TITLE
How to test not equal to some expected state

### ISSUE THREAD

**Issue by suyash-binary** [felangel/bloc#1636]
```
blocTest(
      'my test',
      build: () async {
        return testBloc;
      },
      act: (bloc) => bloc.add(EventA),
      expect: [StateA],
    );
```
Let's say in a test, instead of checking that EventA produces StateA, I want test that on EventA, StateB is never produced. How can I test this scenario?

**Comment by felangel** [comment]
Hi @suyash-binary 👋
Thanks for opening an issue!

The expect in blocTest is strict so the test will only pass if the bloc emits exactly what is in expect (in the exact order). If you expect nothing to be emitted just leave expect empty and then if the bloc does emit StateA/StateB the test will fail.

Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍
