### ISSUE TITLE
MultiBlocProvider.values

### ISSUE THREAD

**Issue by zenkog** [felangel/bloc#1638]
**Is your feature request related to a problem? Please describe.**
When providing an existing Bloc to a `MaterialPageRoute` (with `Navigator.push`), I use `BlocProvider.value` because it does not recreate the bloc. But when I want to provide more than one bloc then I need to do nested `BlocProvider.value` like this:
```
Navigator.push(context, MaterialPageRoute(
    builder: (_context) => BlocProvider.value(
        value: BlocProvider.of<ABloc>(context),
        child: BlocProvider.value(
            value: BlocProvider.of<BBloc>(context),
            child: Page2(),
         ),
))));
```
**Describe the solution you'd like**
Hope to have something like `MultiBlocProvider` that solves the nested `BlocProvider`. This time it is to solve nested `BlocProvider.value`. Something like this:
```
Navigator.push(context, MaterialPageRoute(
    builder: (_context) => MultiBlocProvider.values([
        BlocProvider.of<ABloc>(context),
        BlocProvider.of<BBloc>(context),
    ],
        child: Page2(),         
)));
```

So all the values in a List<Bloc<T>>.

**Describe alternatives you've considered**
Using nested `BlocProvider.value`. It seems that there is no other way around it when dealing with `Navigator.push`

**Comment by felangel** [comment]
Hi @zenkog 👋 
Thanks for opening an issue!

You can currently achieve this like:

```dart
Navigator.of(context).push(
  MaterialPageRoute(
    builder: (_) => MultiBlocProvider(
      providers: [
        BlocProvider.value(value: context.bloc<BlocA>(),
        BlocProvider.value(value: context.bloc<BlocB>(),
      ],
      child: Page2(),
    );
  ),
);
```

Hope that helps 👍

**Comment by mahamedh** [comment]
hi @felangel ,

class HotelProvider extends StatefulWidget {

  @override
  State<HotelProvider> createState() => _HotelProviderState();
}

class _HotelProviderState extends State<HotelProvider> {
  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: <BlocProvider>[
        BlocProvider<HotelBloc>(
          create: (context) => HotelBloc(context),
        ),
        BlocProvider.value(value:  BlocProvider.of<SearchBloc>(context))

      ],
      child: HotelSearchReasult(),

    );
  }
}


The following assertion was thrown building HotelProvider(dirty, state: _HotelProviderState#b1116):
        BlocProvider.of() called with a context that does not contain a SearchBloc.

        No ancestor could be found starting from the context that was passed to BlocProvider.of<SearchBloc>().

        This can happen if the context you used comes from a widget above the BlocProvider.

        The context used was: HotelProvider(dirty, state: _HotelProviderState#b1116)
        
The relevant error-causing widget was:

**Comment by narcodico** [comment]
Hi @mahamedh 👋

If you already have a `BlocProvider<SearchBloc>` above your `HotelProvider` widget then you don't need an additional `BlocProvider.value`, you can simply fetch the existing bloc with `context.read<SearchBloc>()` if you need to add an event to it or use `BlocBuilder<SearchBloc, SearchEvent0>` to build your UI.
