### ISSUE TITLE
The member 'emit' can only be used within 'package:bloc/src/bloc.dart' or a test

### ISSUE THREAD

**Issue by ybin0823** [felangel/bloc#1647]
**Describe the bug**
If I use the `emit` function while using `bloc`, a warning occurs.

**Expected behavior**
In my opinion, `bloc` inherits `cubit`, `emit` should be used.
Am I using it incorrectly? I wonder if you don't want to use emit in bloc.

**Screenshots**
![image](https://user-images.githubusercontent.com/7553607/90711385-8e387000-e2db-11ea-866e-1f76e6979054.png)
![image](https://user-images.githubusercontent.com/7553607/90711408-9abcc880-e2db-11ea-8259-ce1f216d2dcf.png)

**Comment by felangel** [comment]
Hi @ybin0823 👋 
Thanks for opening an issue!

This is working as expected. `emit` should only ever be used within a `Cubit`. Are you sure you are extending `Cubit` instead of `Bloc`? If you are extending `Bloc`, you must override `mapEventToState` to `yield` new states.

Hope that helps 👍
