### ISSUE TITLE
[Discussion] Cubit should be Bloc

### ISSUE THREAD

**Issue by ollydixon** [felangel/bloc#1650]
Before we had this

```
 return BlocBuilder<SomeBloc, SomeState>(
      bloc: someBloc,
```

Now we have 
```
 return BlocBuilder<SomeBloc, SomeState>(
      cubit: someBloc,
```

Now not only do we need to change 31 applications and hundreds of lines of code for this change but it doesn't make any sense. (Find and replace it risky and conflicts)

Cubit
An ancient measure of length, approximately equal to the length of a forearm.

So using cubit wording anywhere is extremely confusing.

There's no length in Bloc, it's more about processing data; more like a queue hehe.

'Block' is more akin to a processing block which contains the ability to process these actions (via a switch mainly). Using one terminology is clearer and helps not to confuse the learners.

Maybe I'm completely wrong but

If you're anything like me, any many other developers the whole 'block' is in one place, for example:

```

part 'logs_bloc.g.dart';

final logsBloc = LogsBloc();

@JsonSerializable()
@immutable
class LogsState {
  // The uid and the logged workout.
  final Map<String, DrillV1> loggedWorkouts;

  /// A list of UIDs of the offline workouts or exercise logs. Stored for later sync.
  final List<String> offlineLogs;

  LogsState({
    this.loggedWorkouts = const {},
    this.offlineLogs = const [],
  });

  LogsState copy({
    Map<String, DrillV1> loggedWorkouts,
    List<String> offlineLogs,
  }) {
    return LogsState(
      loggedWorkouts: loggedWorkouts ?? this.loggedWorkouts,
      offlineLogs: offlineLogs ?? this.offlineLogs,
    );
  }
}

class LogsBloc extends HydratedBloc<dynamic, LogsState> {
  LogsBloc() : super(LogsState());

  @override
  Stream<LogsState> mapEventToState(dynamic event) async* {
    if (event is UpdateDrillLogs) {
      final Map<String, DrillV1> loggedWorkouts = {};
      loggedWorkouts.addAll(state.loggedWorkouts);
      event.workouts.forEach((element) {
        loggedWorkouts[element.uid] = element;
      });
      yield state.copy(loggedWorkouts: loggedWorkouts);
    }
    if (event is UpdateDrillLog) {
      final Map<String, DrillV1> loggedWorkouts = {};
      loggedWorkouts.addAll(state.loggedWorkouts);
      loggedWorkouts[event.workout.uid] == event.workout;
      yield state.copy(loggedWorkouts: loggedWorkouts);
    }
    if (event is SetOfflineLogs) {
      final List<String> officeLogs = [];
      officeLogs.addAll(event.offlineLogs);
      officeLogs.addAll(state.offlineLogs);
      yield state.copy(offlineLogs: officeLogs.toSet().toList());
    }
  }

  @override
  LogsState fromJson(Map<String, dynamic> json) => _$LogsStateFromJson(json);

  @override
  Map<String, dynamic> toJson(LogsState state) => _$LogsStateToJson(state);
}

class UpdateDrillLogs {
  final List<DrillV1> workouts;
  UpdateDrillLogs(this.workouts);
}

class UpdateDrillLog {
  final DrillV1 workout;
  UpdateDrillLog(this.workout);
}

class SetOfflineLogs {
  final List<String> offlineLogs;
  SetOfflineLogs(this.offlineLogs);
}
```

Then we reference this like so:

```
return BlocBuilder<LogsBloc, LogsState>(
            bloc: logsBloc, // Doesn't make sense to call this a cubit, very annoying change.
            builder: (context, logsState) {
              return body(context, logsState);
            },
```
          );

**Comment by RollyPeres** [comment]
Hi @ollydixon 👋

I'm sorry to hear you're finding this rename so disruptive; I can ensure you it was thoroughly considered before being implemented. 

The parameter was renamed to `cubit` since `Cubit` is the base class of `Bloc` now. A `BlocBuilder` can be used to build both from a `Cubit` or  a `Bloc`, hence the renaming.

I think a find and replace `bloc:` for `cubit:` should solve your issue. Please let us know if we can help you further. 👍

**Comment by ollydixon** [comment]
@RollyPeres thanks for the reply. The library is called Bloc, no? Also lots of beginners are going to be totally confused by this. I don't even know what the cubit thing is; and neither does anyone else I speak to about this lib, what is it?

**Comment by ollydixon** [comment]
@RollyPeres can you see my point here?

**Comment by RollyPeres** [comment]
You'd be surprised how many people prefer cubit over bloc 😊. The cubit was implemented as a result of a popular demand to have a simpler way of using bloc, one that doesn't involve events. Since state changes are common between the two, it only makes sense to implement that in an abstraction which is `Cubit`.

I'm hoping you'd give it a chance and have a look at [differences](https://bloclibrary.dev/#/coreconcepts?id=cubit-vs-bloc) between the 2 concepts for a better understanding of this change. I'm sure you'd find good usages for cubit in your apps.

> `Bloc: >> extends Bloc`, it should never reference a child that no one knows about.

`Cubit` is actually the parent class not the child 😊

**Comment by ollydixon** [comment]
@RollyPeres then make a new lib called ```Cubit``` 😎🔥 don't focus us to change 100s of lines of code (we had to update cause of incompatibility across libraries)

**Comment by RollyPeres** [comment]
The change was discussed and approved by most of our members. Please check https://github.com/felangel/bloc/issues/1427 for more details.

We are aware of the inconveniences caused by this change but at the same time we think this is for the greater good.

**Comment by ollydixon** [comment]
@RollyPeres I don't see a discussion there 😂
