### ISSUE TITLE
Android studio bloc extensions for version 0.11.0

### ISSUE THREAD

**Issue by Nothing-Works** [felangel/bloc#166]
apparently, the Android studio bloc extension still generates the `currentState` as the first argument for `mapEventToState`, it not a big problem, but it will be nice if it can be removed.

Cheers

**Comment by felangel** [comment]
@Nothing-Works thanks for bringing this up! The change is in master and we just need to publish it. @jorgecoca when can you publish the latest intellij plugin update?

**Comment by Nothing-Works** [comment]
@felangel  thank you very much for your always quick response, it's like a live chat. lol

**Comment by jorgecoca** [comment]
Yeah, I'll test it tomorrow and publish it ;)

**Comment by jorgecoca** [comment]
Tested, it works! I'll publish it in a few minutes

![bloc](https://user-images.githubusercontent.com/3237451/54998213-903db880-4f9b-11e9-9196-f0c3e3f2b9e1.gif)

**Comment by jorgecoca** [comment]
I just submitted 1.1. It is pending approval from JetBrains. Once approved, you should see a notification in the IDE to update the plugin
