### ISSUE TITLE
What are extensions (from the documentation)

### ISSUE THREAD

**Issue by ajain-bst** [felangel/bloc#1662]
```
// with extensions
context.bloc<BlocA>();

// without extensions
BlocProvider.of<BlocA>(context)
```

Can't find a reference to these **extensions** anywhere. What are they?

**Comment by felangel** [comment]
Hi @ajain-bst 👋 
Thanks for opening an issue!

You can learn more about Dart extensions at [https://dart.dev/guides/language/extension-methods](https://dart.dev/guides/language/extension-methods) 👍
