### ISSUE TITLE
List not updated when removing item

### ISSUE THREAD

**Issue by bobykurniawan11** [felangel/bloc#1665]
As an example i have two items in my list, i want to remove the second item

Here is what i do

```
if (event is MinQty && currentState is ResultState) {
      var contain = currentState.cartitems
          .firstWhere((element) => element.item_code == event.item_code, orElse: () => null);
      if (contain != null) {
        if (contain.qty > 0) {
          contain.qty = contain.qty - 1;
          contain.grand_total =
              contain.qty * int.parse(double.parse(contain.item_price).toStringAsFixed(0));
          List<ShoppingCart> shoppingCart = [];
          shoppingCart.add(contain);
          currentState.cartitems.removeWhere((element) => element.item_code == event.item_code);
          final new_data = currentState.cartitems + shoppingCart;
          new_data.sort((a, b) => a.item_name.toString().compareTo(b.item_name.toString()));
          yield ResultState(
            cartitems: new_data,
          );
        } else {
          currentState.cartitems.removeWhere((element) => element.item_code == event.item_code);
          var new_data_list = currentState.cartitems;
          if (new_data_list.length > 0) {
            new_data_list.sort((a, b) => a.item_name.toString().compareTo(b.item_name.toString()));
            yield ResultState(
              cartitems: new_data_list,
            );
          } else {
            yield DefaultState();
          }
        }
      } else {
        yield ResultState(
          cartitems: currentState.cartitems,
        );
      }
    }
```
Explain 

- The First item has 1 quantity
- The Second item has 1 quantity

when i run the `MinQty event` at my second item, the quantity become zero . Then i run the event again, the item still there. When i click it again, it is causing me an error `RangeError (index): Invalid value: Only valid value is 0: 1` , i think the error cause is because the item should not showing in the list. 

I need to run `MinQty event`  at my first item, then my second item is gone.

**Comment by RollyPeres** [comment]
Hi @bobykurniawan11 👋

Make sure you're working with a fresh list and not altering the existing state.
So start from `final cartItems = List.from(currentState.cartitems)` and do whatever computations/operations you might need.

**Comment by bobykurniawan11** [comment]
@RollyPeres thank you. But why i should not do that ?

**Comment by RollyPeres** [comment]
Because value equality won't properly work and new state won't be emitted as a result of that.

**Comment by felangel** [comment]
Thanks @RollyPeres for taking the time to answer! 🙏 
@bobykurniawan11 closing this for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍
