### ISSUE TITLE
Minor improvements to Github Search flutter example

### ISSUE THREAD

**Issue by bharat-biradar** [felangel/bloc#1667]
Hi felix,
I was going through Github search example  [(link)](examples/github_search/flutter_github_search/lib/main.dart).I noticed that minor changes to code can be such as adding generic type to BlocProvider and some linting.If you think those changes are required I would like to work on them.

**Comment by felangel** [comment]
Hi @bharat-biradar 👋 
Thanks for opening an issue!

I'm still in the process of rewriting the tutorials but if they are quick fixes and you don't mind opening a pull request then definitely go for it! 👍

**Comment by bharat-biradar** [comment]
#1671
