### ISSUE TITLE
Edit the order of actions in context menu, vscode

### ISSUE THREAD

**Issue by dagba** [felangel/bloc#1670]
Can u please add an ability to sort actions in the context menu, its a little bit inconvenient all the time to scroll to "Wrap with widget" option, ty :).
![image](https://user-images.githubusercontent.com/16746885/91308974-a0864280-e7e2-11ea-9093-1b1690c273b6.png)

**Comment by felangel** [comment]
Hi @dagba 👋
Thanks for opening an issue!

I tried searching for a way to control the order but haven’t had any luck. If you or anyone else knows how to achieve this I’m more than happy to make that change 👍

**Comment by dagba** [comment]
Thank you for fastly reply! From an hour of researching, I found only sorting of menu groups, idk if its gonna work
![image](https://user-images.githubusercontent.com/16746885/91314256-f3fb8f00-e7e8-11ea-8b88-7a38691ea276.png)

**Comment by felangel** [comment]
Closing this for now since it doesn't appear to be customizable. Feel free to comment with any links to relevant docs if you know of a way and I'm happy to reopen this 👍
