### ISSUE TITLE
bloc and hooks examples

### ISSUE THREAD

**Issue by lsaudon** [felangel/bloc#168]
**Describe the solution you'd like**
I would like to have an example to integrate **flutter_hooks** and **flutter_bloc** into flutter_todos or other.

**Comment by felangel** [comment]
Hi 👋 

What’s preventing you from using flutter_bloc with flutter_hooks? Is there any issues you’re running into?

**Comment by lsaudon** [comment]
I didn't have any problems.
I'm blocked by my abilities.
It was more of an example.

**Comment by felangel** [comment]
I’ll try to put something together over the next few days 👍

**Comment by cyrsis** [comment]
Great, Just found out my problem with Bloc can solve by Hook~ Let me give it a try

**Comment by cyrsis** [comment]
I did a study on hook, intended to solve my animation controller but end up move on with flare.

but I guess we are trying to solve same problem

let's take a look the map

`
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import './bloc_action_widget/GoToNewYorkButton.dart';
import '../MapBlocExport.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapWidget extends StatefulWidget {
  MapWidget({Key key}) : super(key: key);

  @override
  _MapWidgetState createState() => new _MapWidgetState();
}

class _MapWidgetState extends State<MapWidget> {
  final Set<Marker> _markers = Set();
  final double _zoom = 15;
  CameraPosition _initialPosition =
      CameraPosition(target: LatLng(22.3527422, 114.1270739));
  MapType _defaultMapType = MapType.normal;
  GoogleMapController _controller;

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
        body: new Stack(
      children: <Widget>[
        new BlocBuilder(
            bloc: BlocProvider.of<MapBloc>(context),
            builder: (context, state) {
              if (state is MapInitState) {
                return GoogleMap(
                  markers: _markers,
                  mapType: _defaultMapType,
                  myLocationEnabled: true,
                  onMapCreated: _onMapCreated,
                  initialCameraPosition: _initialPosition,
                );
              }

              if (state is GoToNewYorkState) {
                double lat = 40.7128;
                double long = -74.0060;
                _controller.animateCamera(
                    CameraUpdate.newLatLngZoom(LatLng(lat, long), _zoom));
                _markers.clear();
                _markers.add(
                  Marker(
                      markerId: MarkerId('newyork'),
                      position: LatLng(lat, long),
                      infoWindow: InfoWindow(
                          title: 'New York', snippet: 'Welcome to New York')),
                );
                return GoogleMap(
                  markers: _markers,
                  mapType: _defaultMapType,
                  myLocationEnabled: true,
                  onMapCreated: _onMapCreated,
                  initialCameraPosition: _initialPosition,
                );
              }

              if (state is ChangeMapTypeState) {
                assert(state.mapType != null);
                return GoogleMap(
                  markers: _markers,
                  mapType: state.mapType,
                  myLocationEnabled: true,
                  onMapCreated: _onMapCreated,
                  initialCameraPosition: _initialPosition,
                );
              }
              return Container(
                width: 0.0,
                height: 0.0,
              );
            }),
      ],
    ));
  }

  void _onMapCreated(GoogleMapController controller) {
    _controller = controller;
  }
}
`

**Comment by felangel** [comment]
@lsaudon sorry for the really long delay but I finally spent a bit of time and created a simple example using `flutter_hooks` with `flutter_bloc` which you can check out [here](https://gist.github.com/felangel/d9322837c07721b97ae2f7be541cabb2).

I basically created a `useBloc` hook which handles creating and disposing the bloc for you so you don't need to create a `StatefulWidget` and initialize/dispose the bloc every time.

Hope that helps! 👍

**Comment by rrousselGit** [comment]
_randomly passes here_
that `useBloc` is unnecessarily big.

`useBloc` could be:

```dart
T useBloc<T extends Bloc>(
    T Function() blocFactory,
    [List<Object> keys = const <dynamic>[]],
) {
  final bloc = useMemoized(blocFactory, keys);
  useEffect(() => bloc.dispose, [bloc]);
}
```


And you can make one for `BlocBuilder` too:

```dart
T useBlocListener<T>(Bloc<T, Object> bloc) {
  final state = useMemoized(() => bloc.state.skip(1), [bloc.state]);
  return useStream(state, initialData: bloc.currentState);
}
```

**Comment by lsaudon** [comment]
Do you have full exemple @rrousselGit ?

**Comment by Chojecki** [comment]
Would be awsome to see full example with usage @rrousselGit

**Comment by cgestes** [comment]
currently using the following sample in place of BlocProvider:

```dart
/*
 * use instead of BlocProvider<YoloBloc, YoloState>
 * state = useBlocState<YoloBloc, YoloState>();
 */
S useBlocState<B extends Bloc<dynamic, S>, S>() {
  final context = useContext();
  final bloc = BlocProvider.of<B>(context);

  final stream = useMemoized(() => bloc.skip(1), [bloc.state]);
  return useStream(stream, initialData: bloc.state).data;
}
```
