### ISSUE TITLE
[Inquiry] BlocListener in AppBar  with Shoppingcart Badges number not listening to state change

### ISSUE THREAD

**Issue by yk-theapps** [felangel/bloc#1683]
Hi @felangel , 

I have tried many ways to either use cubit or bloc to trigger state like NewItemAdded so Buildlistener in AppBar when received state change from bloc or cubit it should show badges numbers ( example add item into cart, so App bar in the shopping cart will show badges number of how many items inside) but seem, it didn't work as usual in AppBar. do you have any advice?

**Comment by yk-theapps** [comment]
* the last try was with BlocBuilder

**Comment by felangel** [comment]
Hi @yk-theapps 👋 
Thanks for opening an issue!

Can you please share a link to a sample app which illustrates the issue? I'm not sure I understand the question because you mention BlocListener but have a snippet using BlocBuilder. Is your `bloc` properly yielding/emitting states? I would recommend checking out the [FAQs](https://bloclibrary.dev/#/faqs?id=state-not-updating) as well.

Let me know if that helps and if not please share a link to a sample app 👍

**Comment by yk-theapps** [comment]
sample with blocListener 

![image](https://user-images.githubusercontent.com/18683120/91729766-a2337a00-ebd7-11ea-80dd-96deeb7cbd98.png)



class ShoppingCartBloc extends Bloc<ShoppingCartEvent, ShoppingCartState> {
  CatalogRepository _catalogRepository;
  StoreRepository _storeRepository;
  ShoppingCartBloc({@required CatalogRepository catalogRepository}) :assert(catalogRepository != null), _catalogRepository = catalogRepository
    , super(ShoppingCartInitial());

  @override
  Stream<ShoppingCartState> mapEventToState(
    ShoppingCartEvent event,
  ) async* {
    //TODO:load shopping cart
     
    if(event is LoadShoppingCart)
    {
      yield ItemAdded(2);
      // yield* _mapAddItemToCartToState(event);
    }
    if (event is AddItemToCart) {
      yield* _mapAddItemToCartToState(event);
    }
    if (event is RemoveItemFromCart) {
      
    }
  }

  // TODO: implement mapEventToState

  Stream<ShoppingCartState> _mapAddItemToCartToState(
      AddItemToCart event) async* {
     int total = 0;
     try{
       total = await _catalogRepository.addItemToShoppingCart(
        "XDrhHyEaWGj9FmoW2hf4", event.userId, event.product);
        yield ItemAdded(total);
     }catch(ex)
     {
        print(ex);
     }
    
  }
}

part of 'shopping_cart_bloc.dart';
abstract class ShoppingCartEvent extends Equatable {
  const ShoppingCartEvent();
}
class LoadShoppingCart extends ShoppingCartEvent{

  @override
  List<Object> get props => [];
}

class AddItemToCart extends ShoppingCartEvent {
  
  final String userId;
  final ShoppingCartProduct product;
  AddItemToCart(this.userId, this.product);
  
  @override
  List<Object> get props => [];

}



class RemoveItemFromCart extends ShoppingCartEvent {
  @override
  List<Object> get props => [];

}


part of 'shopping_cart_bloc.dart';

abstract class ShoppingCartState extends Equatable {
  const ShoppingCartState();
}

class ShoppingCartInitial extends ShoppingCartState {
  @override
  List<Object> get props => [];
}


class ItemAdded extends ShoppingCartState {
  final int totalItems;
  ItemAdded(this.totalItems);


  @override
  List<Object> get props => [totalItems];

  @override
  String toString() => 'ShoppingCartState =>ItemAdded { totalItems: $totalItems }';
}

class ItemRemoved extends ShoppingCartState {
  @override
  List<Object> get props => [];
}

**Comment by felangel** [comment]
@yk-theapps can you please provide a link to a complete sample app on github or a gist? It's hard to help without seeing the complete source code and in the most recent snippet I don't see use of an `appBar` at all.

**Comment by yk-theapps** [comment]
okay, but I need time to split the project. as it quite big couldn't directly share.  I will try to create a sample project for that. thanks

**Comment by yk-theapps** [comment]
hi @felangel  
Thanks for your time. I think I figure out the issue already.  It was due to that, there are two bloc providers in 2 parts. 
One at Navigator by route name and another provider at destinated route. I didn't notice there are set 2 providers there.  when I moving or simulate code for you to review. I saw that.
