### ISSUE TITLE
Support for separate multiple blocs of same type

### ISSUE THREAD

**Issue by munkhp** [felangel/bloc#1686]
Hello,

 I was trying to implement a pagination for firestore. According to this video, https://youtu.be/poqTHxtDXwU, my best bet seems to have separate listeners for each and every 10 loaded documents so that they are still real time. I couldn't figure out how I could add more separate stream listeners on-demand dynamically using flutter bloc. I would like to know if it is possible with flutter bloc. Thank you :)

**Comment by felangel** [comment]
Hi @munkhp 👋 
Thanks for opening an issue!

Can you please provide a sample app which illustrates the current setup and what you're trying to achieve? It would be much easier for me to help if you could provide sample code, thanks! 🙏

**Comment by munkhp** [comment]
Hello @felangel,
 
 Thank you for your reply! I was thinking of different ways to implement "pagination" for firestore using flutter bloc with greatest efficiency to reduce billing costs while not losing the "real-time capability" of firestore but it seems it's an overkill to have multiple  BlocBuilders similar to having multiple StreamBuilders. I actually managed to solve my problem by adding the implementation in todos_repository, so I can have a single BlocBuilder. Not sure if that is the best "Bloc way" to handle things but it works for me :P
