### ISSUE TITLE
Authentication user check error!!

### ISSUE THREAD

**Issue by Puspharaj** [felangel/bloc#1690]
As per the flutter_bloc version.

 flutter_bloc: ^6.0.1
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1

> 
> E/flutter (14777):
> E/flutter (14777): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: type 'User' is not a subtype of type 'User' where
> E/flutter (14777):   User is from package:firebase_auth/firebase_auth.dart
> E/flutter (14777):   User is from package:sample/packages/authentication_repository/lib/src/models/user.dart
> E/flutter (14777):

The above issue starts with deprecated method at the end of the authentication_repository.dart

```
> 
> import 'package:firebase_auth/firebase_auth.dart';
> import 'package:google_sign_in/google_sign_in.dart';
> import 'package:meta/meta.dart';
> 
> import 'models/models.dart';
```

The User from firebase and model get clashed easily.

Would you please provide alternative way to check authentication check?...the below one is deprecated and warns and do not compile anymore.

```
> extension on auth.FirebaseUser {
  User get toUser {
    return User(id: uid, email: email, name: displayName, photo: photoUrl);
  }
}
```

Would you please check?. thanks

**Comment by RollyPeres** [comment]
Hi @Puspharaj 👋

`FirebaseUser` was renamed to `User`. Please follow the [migration guide](https://firebase.flutter.dev/docs/migration/) and make sure you're namespacing your packages to differentiate between firebase `User` and your own `User` class.

Hope that helps 👍

**Comment by Puspharaj** [comment]
```

> 
> extension on auth.User {
>   User get toUser {
>     return User(id: uid, email: email, name: displayName, photo: photoURL);
>   }
> }

```
```

> 
>  Stream<User> get user {
>     return _firebaseAuth.authStateChanges().map((firebaseUser) {
>       return firebaseUser == null ? User.empty : firebaseUser.toUser;
>     });
>   }

```

Those above changes will solve the errors.
