### ISSUE TITLE
Builder is triggered even though buildWhen returns false.

### ISSUE THREAD

**Issue by Pakkapao** [felangel/bloc#1696]
**Describe the bug**
I'm not sure if this relates to #1682 which was fixed in 6.0.4.

This piece of code works as expected for `flutter_bloc: 6.0.2`. The widget should only be rebuilt when state is **SubjectBookLoadSuccess**.
![image](https://user-images.githubusercontent.com/11070293/92238141-c4ccd800-eee2-11ea-87cf-32744ca33bb4.png)

However, after upgrading to `flutter_bloc: 6.0.4`. The builder function was triggered even though the buildWhen return false.
![image](https://user-images.githubusercontent.com/11070293/92238075-a961cd00-eee2-11ea-8286-790a2ba83db8.png)

**Comment by felangel** [comment]
Hi @Pakkapao 👋 
Thanks for opening an issue!

I'll investigate this further but it would be super helpful if you could provide a simple app that reproduces the issue 👍

**Comment by Pakkapao** [comment]
Hi @felangel , https://github.com/Pakkapao/bloc_flutter

**Comment by felangel** [comment]
@Pakkapao this has been fixed as part of #1699 and included in v6.0.5 🎉

**Comment by docmobile17** [comment]
> @Pakkapao this has been fixed as part of #1699 and included in v6.0.5 🎉


@felangel ,  Does this fix also apply to Cubit ?

**Comment by felangel** [comment]
> > @Pakkapao this has been fixed as part of #1699 and included in v6.0.5 🎉
> 
> @felangel , Does this fix also apply to Cubit Listener?

Did you mean BlocListener? If so yes 👍

**Comment by docmobile17** [comment]
> > > @Pakkapao this has been fixed as part of #1699 and included in v6.0.5 🎉
> > 
> > 
> > @felangel , Does this fix also apply to Cubit Listener?
> 
> Did you mean BlocListener? If so yes 👍

i meant CubitListener,

I just thought this case also happened in CUBITLISTENER, sorry in advance if my guess is wrong,

**Comment by felangel** [comment]
CubitListener doesn’t exist. BlocListener is compatible with cubits 👍

**Comment by docmobile17** [comment]
> CubitListener doesn’t exist. BlocListener is compatible with cubits 👍

Ok @felangel , Thank you.
