### ISSUE TITLE
Widget testing with flutter bloc

### ISSUE THREAD

**Issue by MattisBrizard** [felangel/bloc#170]
Hi @felangel, 

I've got another question about widgets testing with the bloc. I don't have any idea on how to do that. If you can add an example on how to test the weather widget in the flutter weather example app, it would help me.

Thanks.

**Comment by felangel** [comment]
@MattisBrizard great question! While there aren't any widget tests for the Weather App, the Todos App is fully tests (unit tests, widget tests, and integration tests). You can check it out [here](https://github.com/brianegan/flutter_architecture_samples/tree/master/bloc_library). Let me know if that helps!

**Comment by felangel** [comment]
Closing for now but feel free to comment with any questions and I'm happy to reopen this. 👍
