### ISSUE TITLE
is there a way to use a single bloc in more than one instance?

### ISSUE THREAD

**Issue by amanuel15** [felangel/bloc#1705]
I have a bloc that receives data from firestore and provides it and what i am wondering is if i can use the same bloc but for different requests and get notified separately so the other widget dont get rebuilt. What I have in mind is more than one horizontally paginated List Views in the same page and build each of them separately as if they were provided with different blocs.

**Comment by mikededo** [comment]
You could use `buildWhen` method which allows you to choose if you want to build it's child or not.  
Check the [api](https://bloclibrary.dev/#/flutterbloccoreconcepts?id=blocbuilder), it explains the `buildWhen` method, when you are using `BlocBuilder`. It is the same in the `BlocConsumer`.

**Comment by amanuel15** [comment]
I guess that is the only way to achieve what i want, I hoped there was some other way.

**Comment by mikededo** [comment]
Do you wrap all lists as a child of the `BlocBuilder` or do you have a `BlocBuilder` for each list (which is how I would do it)?

**Comment by amanuel15** [comment]
I'm planning to have BlocBuilder for each, which i guess restricts me to make my state the type with the const factory and copywith the fields in the bloc to avoid mapping each state in every builder.

**Comment by mikededo** [comment]
I don't undestand what do you mean. Could you provide an example?

**Comment by amanuel15** [comment]
```
@freezed
abstract class ProductWathcerState with _$ProductWathcerState {
  const factory ProductWathcerState.initial() = Initial;
  const factory ProductWathcerState.loadInProgress() = LoadInProgress;
const factory ProductWathcerState.success(List<Result> results) = Success;
}
```
this is the traditional way of doing the **state** class. But if you do this you have to **map** each (or **maybeMap** and account for **orElse**) of this state which in my case i may not want to rebuild based on.

Instead you make the state:
```
@freezed
abstract class HomeWatcherBlocState with _$HomeWatcherBlocState {
  const factory HomeWatcherBlocState({
    @required bool loading,
    @required List<Result> results,
     ....
  }) = _HomeWatcherBlocState;

  factory HomeWatcherBlocState.initial(
    loading: false,
    results: [],
  ) => HomeWatcherBlocState();
}
```
so now you don't have to map each state, you just access any state by its fields like **state.results**

**Comment by mikededo** [comment]
Hmmm, I'm not used to using the freezed package. I will search about it and if I come to a solution I wi tell you! 🙏

**Comment by amanuel15** [comment]
Thanks man!

**Comment by felangel** [comment]
Hi @amanuel15 👋 
Thanks for opening an issue!

I'm not sure I understand the problem you're having.

> so now you don't have to map each state, you just access any state by its fields like state.results

It's totally up to you how you choose to represent the state of your feature so if it's easier to have a single base class with a bunch of properties as opposed to multiple subclasses then there's nothing wrong with going with the single class approach.

**Comment by amanuel15** [comment]
> It's totally up to you how you choose to represent the state of your feature so if it's easier to have a single base class with a bunch of properties as opposed to multiple subclasses then there's nothing wrong with going with the single class approach.

You are right i just didn't like the single class implementation.

Excuse me if its not the place to ask my question as it is not an issue that pertains to your package. 
"Basically what i want to do is create blocs, _which are derived from an already predefined bloc with the same states and events just different in the event parameters they accept_, based on some external event(maybe a user adds a widget by clicking some button) and the now added widget can use the **events** and the **builder** of this newly generated bloc."
So if there is a way to do this i would appreciate some direction. Thanks for this great package @felangel !

**Comment by mikededo** [comment]
If you could provide a simple example of how would it look, it would help us understand 😄.

**Comment by felangel** [comment]
@amanuel15 you should be able to dynamically create blocs in response to button taps and you can make them derived from existing blocs by defining some some sort of bloc factory. As @mikededo mentioned, it's hard for us to help without more context so if you can share an example of what you're trying to achieve and what you're tried it would help us give better suggestions/feedback 👍

**Comment by amanuel15** [comment]
> @amanuel15 you should be able to dynamically create blocs in response to button taps and you can make them derived from existing blocs by defining some some sort of bloc factory. As @mikededo mentioned, it's hard for us to help without more context so if you can share an example of what you're trying to achieve and what you're tried it would help us give better suggestions/feedback 👍

This gives me a good idea of what to do.
this is my state
```
@freezed
abstract class CatagoryWatcherState with _$CatagoryWatcherState {
  const factory CatagoryWatcherState.initial() = Initial;
  const factory CatagoryWatcherState.inProgress() = InProgress;
  const factory CatagoryWatcherState.loadSucess(
      KtList<CatagoryEntity> catagories) = LoadSucess;
}
```
this is my event
```
@freezed
abstract class CatagoryWatcherEvent with _$CatagoryWatcherEvent {
  const factory CatagoryWatcherEvent.watchCatagories(String condition1, String operator, String condition2) =
      _WatchCatagories;
}
```
I will have a vast firestore database of items with many fields they can be queried on. So a user can subscribe to a new category and when he does the app will create a new bloc for it pass the conditions and the operator, this parameters will serve as a base for querying from the firestore in the repo(` _firestore.collection('items').where(condition1, operator, condition2).get()` ) .

In the ui the states are mapped and different widgets are shown
```
state.map(
          initial: (_) => Container(),
          loadInProgress: (_) => const Center(
            child: CircularProgressIndicator(),
          ),
          loadSuccess: (state) {
            // some ui
          },
);
```
So if you can show me some sample code that can give me some idea on how to create a bloc dynamically using a factory, it will be a great help!

**Comment by felangel** [comment]
@amanuel15 you can dynamically create blocs by wrapping the dynamically created `Item` widgets each in their own `BlocProvider` like:

```dart
// in `ListView.builder` or `Column` for example
items.map((item) => BlocProvider(create: ..., child: Item(...))
```

Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
