### ISSUE TITLE
FirebaseAuth Migrate to Version "^0.18.0+1" in the Firebase Login Example. 

### ISSUE THREAD

**Issue by ethansbenjamin** [felangel/bloc#1706]
**Is your feature request related to a problem? Please describe.**
Dealing with login errors in FlutterFire auth for the old version is troublesome. Particularly when attempting to link credentials. There is only documentation for the latest version of FlutterFire. The version that is used in the latest FirebaseLoginBloc example does not have the class FirebaseAuthError, which returns an email in the error. This frustration can be seen [here](https://github.com/FirebaseExtended/flutterfire/issues/1318).  I've been trying to migrate the package myself, however all firebase packages depend on FirebaseCore. Since the firebase login is written with the Authentication Repository being a separate package, I was having trouble initializing a firebase core instance there.

**Describe the solution you'd like**
Migrate the firebase login bloc example to the latest version of firebase auth. This would require having to create an instance of a FirebaseApp as seen [here](https://firebase.flutter.dev/docs/overview).

**Describe alternatives you've considered**
I considered scrapping together linking credentials as done [here](https://github.com/FirebaseExtended/flutterfire/issues/1318), however, that is only a short term solution. There is not enough documentation to maintain the codebase. Any help would be appreciated.

**Comment by corymalcolmtaylor** [comment]
I found some code somewhere online for the get user method in authentication_repository.dart and it seems to work for me, in short replace the calls to onAuthStateChanged  to authStateChanges() -- note the **()**, the getter did not need them.
  
  /// Stream of [AppUser] which will emit the current user when
  /// the authentication state changes.
  ///
  /// Emits [AppUser.empty] if the user is not authenticated.
  Stream<AppUser> get user {
    return _firebaseAuth.authStateChanges().map((firebaseUser) {
      return firebaseUser == null ? AppUser.empty : firebaseUser.toAppUser;
    });

and in the tests :
 
   when(firebaseAuth.authStateChanges()).thenAnswer(
          (_) => Stream.value(null),
        )

**Comment by perryrh0dan** [comment]
Is there any update on this issue ? :)

**Comment by felangel** [comment]
@perryrh0dan will try to get to it this weekend right. Wrapping up the [weather revamp](https://github.com/felangel/bloc/pull/1762) and will get to this right after 👍
