### ISSUE TITLE
Error by cubit not getting caught

### ISSUE THREAD

**Issue by vaibhavdangayachvd** [felangel/bloc#1716]
I have code like this
The saveProfilePressed act throws a NotAuthenticatedError ( Extends error )

`  blocTest<ProfileCubit, ProfileState>(

      'when not authenticated',

      build: () {

        when(authFacade.getCurrentUserId())
            .thenAnswer((realInvocation) async => none());
        return ProfileCubit(profileService, authFacade);
      },

      act: (profileCubit) {
        profileCubit.nameChanged('Harshita');
        profileCubit.ageChanged('12');
        profileCubit.genderChanged(Gender.female);
        profileCubit.saveProfilePressed(); // this method throws error
      },

      skip: 3,
      expect: [
        ProfileState.initial().copyWith(
          name: 'Harshita',
          age: '12',
          gender: Gender.female,
          isSubmitting: true,
          failureOrSuccessOption: none(),
        ),
      ],

      errors: [
        isA<NotAuthenticatedError>(),
      ],

      verify: (profileCubit) {
        verify(authFacade.getCurrentUserId());
        verifyNoMoreInteractions(authFacade);
        verifyNoMoreInteractions(profileService);
      },
);`

I was expecting the test to pass but it shows something like this : -

00:01 +6 -1: Test save profile when not authenticated [E]
  Instance of 'NotAuthenticatedError'
  package:gulluck/application/profile/profile_cubit.dart 77:26  ProfileCubit._makeUserFromCurrentState.<f
n>
  package:dartz/src/option.dart 146:59                          None.fold
  package:dartz/src/option.dart 12:28                           Option.getOrElse
  package:gulluck/application/profile/profile_cubit.dart 77:10  ProfileCubit._makeUserFromCurrentState
  ===== asynchronous gap ===========================
  dart:async                                                    _asyncErrorWrapperHelper
  test\application\profile\profile_cubit_test.dart 171:24       main.<fn>.<fn>
  package:bloc_test/src/bloc_test.dart 155:20                   runBlocTest.<fn>
  dart:async                                                    runZoned
  package:bloc_test/src/bloc_test.dart 149:9                    runBlocTest
  package:bloc_test/src/bloc_test.dart 122:11                   blocTest.<fn>

  Expected: [<<Instance of 'NotAuthenticatedError'>>]
    Actual: []
     Which: shorter than expected at location [0]

  package:test_api                             expect
  package:bloc_test/src/bloc_test.dart 177:23  runBlocTest

**Comment by felangel** [comment]
Hi @vaibhavdangayachvd 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which reproduces the issue? It's hard to tell why this is happening without having access to the cubit implementation.

**Comment by vaibhavdangayachvd** [comment]
> Hi @vaibhavdangayachvd 👋
> Thanks for opening an issue!
> 
> Can you please provide a link to a sample app which reproduces the issue? It's hard to tell why this is happening without having access to the cubit implementation.

There you go
https://pastebin.com/Kb8EYnAa

**Comment by felangel** [comment]
@vaibhavdangayachvd can you please push the code to a github repo which I can clone and run locally? Thanks 🙏

**Comment by vaibhavdangayachvd** [comment]
> @vaibhavdangayachvd can you please push the code to a github repo which I can clone and run locally? Thanks 🙏

https://github.com/gullucktheapp/CubitErrorReport

**Comment by felangel** [comment]
@vaibhavdangayachvd I took a look and it's because you are throwing an `Error` rather than an `Exception`.

```
* Error objects thrown in the case of a program failure.
 *
 * An `Error` object represents a program failure that the programmer
 * should have avoided.
 *
 * Examples include calling a function with invalid arguments,
 * or even with the wrong number of arguments,
 * or calling it at a time when it is not allowed.
 *
 * These are not errors that a caller should expect or catch -
 * if they occur, the program is erroneous,
 * and terminating the program may be the safest response.
```

An `Error` means that the program should terminate and are not meant to be caught and handled. In this case, you should likely be throwing an `Exception` instead.

Hope that helps 👍

**Comment by vaibhavdangayachvd** [comment]
> @vaibhavdangayachvd I took a look and it's because you are throwing an `Error` rather than an `Exception`.
> 
> ```
> * Error objects thrown in the case of a program failure.
>  *
>  * An `Error` object represents a program failure that the programmer
>  * should have avoided.
>  *
>  * Examples include calling a function with invalid arguments,
>  * or even with the wrong number of arguments,
>  * or calling it at a time when it is not allowed.
>  *
>  * These are not errors that a caller should expect or catch -
>  * if they occur, the program is erroneous,
>  * and terminating the program may be the safest response.
> ```
> 
> An `Error` means that the program should terminate and errors are not meant to be caught and handled. In this case, you should likely be throwing an `Exception` instead.
> 
> Hope that helps 👍

In the code I am not catching it but in the test how can I be sure if the error is thrown or not ?
