### ISSUE TITLE
[Question] What's the purpose of the RepositoryProvider?

### ISSUE THREAD

**Issue by JoseGeorges8** [felangel/bloc#1719]
Hi!

I had a quick question. I wasn't sure what use case does a RepositoryProvider cover, could I not create a separate instance of a repository if another bloc needs it? 

Thanks!

**Comment by RollyPeres** [comment]
Hi @JoseGeorges8 👋

Please read more on this topic [here](https://bloclibrary.dev/#/flutterbloccoreconcepts?id=repositoryprovider).


> could I not create a separate instance of a repository if another bloc needs it?

You could but but there's no point in doing so. It's an optimization to re-use an existing instance.
