### ISSUE TITLE
In `flutter_login` example, how to open `HomePage` from `LoginPage` when logging in successfully

### ISSUE THREAD

**Issue by anticafe** [felangel/bloc#172]
I look at your `flutter_login` example:
https://github.com/felangel/bloc/blob/master/examples/flutter_login/lib/login/login_bloc.dart#L34

```
@override
  Stream<LoginState> mapEventToState(LoginEvent event) async* {
    if (event is LoginButtonPressed) {
      yield LoginLoading();

      try {
        final token = await userRepository.authenticate(
          username: event.username,
          password: event.password,
        );

        authenticationBloc.dispatch(LoggedIn(token: token));
        yield LoginInitial();
```

In my case, there is a SplashPage with a LogIn button, touch on it will open LoginPage (with a form to perform log in). Back from LoginPage will be SplashPage. After logging in successfully, the HomePage will be opened. Press BACK on HomePage will be SplashPage (just an example to demonstrate how navigation works).

With such scenario, I want to use `loginBloc` to handle `LoggedIn` state in LoginPage instead transfer that to `authenticationBloc`. New code should be like this:
```
@override
  Stream<LoginState> mapEventToState(LoginEvent event) async* {
    if (event is LoginButtonPressed) {
      yield LoginLoading();

      try {
        final token = await userRepository.authenticate(
          username: event.username,
          password: event.password,
        );
        yield LoginSuccess(token: token);
```

However I notice in LoginPage, there is just method to build the widget but no place to handle navigation to HomePage.
```
@override
  Widget build(BuildContext context) {
    return BlocBuilder<LoginEvent, LoginState>(
      bloc: _loginBloc,
      builder: (BuildContext context, LoginState state) {
        print('Login: state=$state');
        if (state is LoginFailure) {
          // In this case show a Toast or Snackbar error
        } else if (state is LoginSuccess) {
          // how to navigate to next screen???
        }

        return Scaffold(...);
```

Could you recommend me an official solution to handle navigation with Bloc library. Thanks.

**Comment by felangel** [comment]
Hey @anticafe 👋 

Great question! You can handle navigation by adding a PostFrameCallback and using the Flutter Navigator within your build method.

```dart
import 'package:flutter/scheduler.dart';

...

} else if (state is LoginSuccess) {
    SchedulerBinding.instance.addPostFrameCallback((_) {
        Navigator.of(context).push(...);
    });
}
```

Hope that helps! 👍

**Comment by carotkut94** [comment]
lets say that 
`BlocBuilder<LoginBloc, LoginStates>(
          bloc: loginBloc,
          builder: (context, state){
            if(state is LoginSuccessFullState){
              Fluttertoast.showToast(msg: state.loginJson.message);
            }else if(state is LoginFailedStateState){
              Fluttertoast.showToast(msg: state.message);
            }
return SomeWidget();
`
now if i navigate to some other page, after getting LoginFailedStateState , lets say ForgotPasswordPage and whenever i come back, or go forth, flutter toast shows up every time.

**Comment by felangel** [comment]
@carotkut94 you should use BlocListener for side effects. BlocBuilder should only return widgets in response to states.
