### ISSUE TITLE
Second yield not received by bloc builder

### ISSUE THREAD

**Issue by LaurentMalmendier** [felangel/bloc#1725]
Hi,

I tried to make your login example work in my current project.
Almost everything works fine !
I have a problem when firing the LoginSubmitted event.

My blocBuilder is notified when the first yield is fired:

yield state.copyWith(status: FormzStatus.submissionInProgress);

But never notified when the second yield is fired:

yield state.copyWith(status: FormzStatus.submissionSuccess);

In debug mode, my breakpoint is reached so the submissionSuccess is normally fired.

I'm not able to provide a sample to test, since the code is client payed.

Any idea why only 1 yield is received when firing the LoginSubmitted event?

context.bloc<LoginBloc>().add(const LoginSubmitted());

Thanks for any advice ;)

**Comment by felangel** [comment]
Hi @LaurentMalmendier 👋
Thanks for opening an issue!

Can you please provide a link to a complete sample app which illustrates the issue? I’m guessing you’re navigating to another screen on submissionSuccess which could result in the widget being unmounted. Thanks! 🙏

**Comment by LaurentMalmendier** [comment]
Hi @felangel 

Thank you for your quick reply, really appreciate ;)

Here is a [sample App](https://github.com/LaurentMalmendier/test_signin_bloc).

The BlocBuilder in sign_in_screen receive the initial state (none).
When a click the login button, the bloc builder receive the first yield "submissionInProgress". But not the second yield fired 3 secondes later (submissionSuccess).

It is very likely that i didn't understand the core concept of bloc ^_^

**Comment by RollyPeres** [comment]
Hi @LaurentMalmendier 👋

I fixed your issue in this [PR](https://github.com/LaurentMalmendier/test_signin_bloc/pull/1).
You didn't pass your status to equatable's `props` thus your states were considered equal.

**Comment by LaurentMalmendier** [comment]
Thank you so much @RollyPeres 🙏

This issue can be closed !
