### ISSUE TITLE
How do I prevent the subsequent events if the same event is in progress?

### ISSUE THREAD

**Issue by jezsung** [felangel/bloc#1730]
There's a chance that the multiple same events can occur while processing the event. The use case I encountered is when implementing an infinite lazy loading list with the bloc, load events can occur multiple times before the items are fully loaded. I wanted to prevent subsequent events if the event is in process. I thought I could achieve it by overriding the transformEvents methods but I couldn't because there's no way to get the current processed event. Any ideas?

**Comment by felangel** [comment]
Hi @jezsung 👋 
Thanks for opening an issue!

You should be able to apply `distinct` in the `transformEvents` override like in https://github.com/felangel/bloc/blob/587eddf2da6a39641b34fa5ffbb980557ec6756d/examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart#L23.

Let me know if that helps 👍

**Comment by jezsung** [comment]
> Hi @jezsung 👋
> Thanks for opening an issue!
> 
> You should be able to apply `distinct` in the `transformEvents` override like in
> 
> https://github.com/felangel/bloc/blob/587eddf2da6a39641b34fa5ffbb980557ec6756d/examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart#L23
> 
> .
> Let me know if that helps 👍

Thanks for replying. `distinct` isn't what I want. `distinct` prevents the same event even after the new state has been updated. I want to allow the subsequent event if the new state is updated.

**Comment by felangel** [comment]
@jezsung by default events are processed in the order in which they are received so this shouldn't be a problem. The bloc will only process the next event once the previous has been fully processed in `mapEventToState`.
