### ISSUE TITLE
Best Practice for Bloc Initialization

### ISSUE THREAD

**Issue by DrRuhe** [felangel/bloc#1731]
Hi, 
what is the best practice for initializing a bloc? I could only figure out that to initialize a "the bloc is initializing please wait" state, as well as a "finished the init, now show the wanted values" event are needed. 

I feel like needing an extra event & state only for initialization is not the way to go.

I was also not able to locate relevant information in the documentation. Although I appreciate that many examples are provided, a detailed description on how the components should be used and what each method is for would be very nice, since the examples (at least in my perspective) have a lot of bloat attached to them (which is necessary for examples but just buries the wanted information under boilerplate).

Thanks for your help in providing and maintaining this package.

**Comment by RollyPeres** [comment]
Hi @DrRuhe 👋

If you don't like the event based approach bloc takes you can always use cubit instead.
Bloc is not opinionated, so it's up to you to decide how you're gonna model the states and the events.

> the examples (at least in my perspective) have a lot of bloat attached to them (which is necessary for examples but just buries the wanted information under boilerplate).

Most people would disagree with you, since most people want real world examples of feature implementation.
I would suggest you start with a counter app or something simple and work your way up to more advanced tutorials/examples.

**Comment by DrRuhe** [comment]
Tanks for taking the time to respond!

I might have phrased this a bit badly, and edited out possibly relevant information, for that, I apologize. Examples are very welcome and have every right to be there. It is also great, that there are multiple Examples covering various use cases. 

The use case I am trying to achieve would be the following:

I initialize the Bloc with a given parameter. 
The initial State of the Bloc should contain information derived from the parameter. Since I would like to avoid having the aforementioned "the bloc is not yet initialized, please wait" state, I would want to call the super Constructor with the computed value. 

The problem arises when trying to compute this value for the initial state before calling the super constructor. Is there another way except using initializer lists, which are sadly quite limited, to compute the value that should get used in the initial state?

I saw (don't remember where) something about a getter called initialState in a bloc class, which would solve my problem since the constructor could properly initialize everything in the constructor function body and the initial state could use all the instance variables of the bloc. Was/is there something like that?

**Comment by RollyPeres** [comment]
`initialState` was deprecated in favor of calling the super constructor with the initial state.

You can do:

```
 YourBloc({
    @required this.parameter,
  })  : 
        super((){
          compute initial state based on parameter...
          return yourComputedState;
        }());
```

**Comment by DrRuhe** [comment]
> `initialState` was deprecated in favor of calling the super constructor with the initial state.

Can you elaborate on why this decision was made? Or link an issue where this is discussed, I would love to learn more!

Never occurred to me that one can evaluate an anonymous function by just appending parenthesis. Thanks.

**Comment by RollyPeres** [comment]
You're welcome. Have a look at https://github.com/felangel/bloc/issues/1304 for details.

**Comment by DrRuhe** [comment]
Sadly this did not fix my problem, since the only way to prevent a lot of duplicate code would be to have a constructed instance on which to call functions. I have made adjustments to the code here: https://github.com/DrRuhe/bloc/commit/23a6affbf1128d55fa84d93f02d73c832e37e93c

The change I would propose is an optional function constructor parameter for both cubit and bloc.
The function would get the instance as a parameter and would return the state that will be used as the initial state. 

This would go inline with the proposed future change when nnbd goes online, that the initialState parameter should be named. Using this approach people can access instance methods of the bloc to calculate the initial state.

**Comment by RollyPeres** [comment]
Can you share a real world example where you can't use the current bloc's implementation to properly initialize your bloc ?

**Comment by DrRuhe** [comment]
I have uploaded an example https://github.com/DrRuhe/bloc 
An overview of everything necessary: https://github.com/felangel/bloc/compare/master...DrRuhe:master

With the proposed change initializing would be relatively straightforward (The signature situation is not ideal but the best I could come up so far). However, when trying to achieve this using the old version I would resort to a static method or duplicate the entire logic.

**Comment by RollyPeres** [comment]
I think you're misusing bloc, since you're keeping additional state inside your bloc; it should only be kept on the state class/classes.
The example you provided has no real world applicability. I'd like to see an example that derives from a realistic feature.
If your state depends on some external data you can always compute that outside the bloc or within some other bloc and pass it through the constructor to attach it to the initial state. Further state should not be kept and modified from the incoming data.

**Comment by DrRuhe** [comment]
So to clarify, (in the intended use case) Blocs should not have any internal state? This would imply, that one could construct a bloc instance using only one state/a state can fully identify a bloc. 

My understanding was that a bloc contains the state and sends the UI the "state if the UI", since the UI should only take the Information it needs. 

From that understanding, I defined the State Objects to only carry the information relevant for the UI and the UI has only the Information it needs. Therefore a very clean separation between the Logic/State(inside the bloc) and the UI State (the State Objects that the bloc produces) would be given.

Can you clarify?

**Comment by RollyPeres** [comment]
bloc is also a `Stream<State>`, you send your state to the UI through it.
I encourage you to read through [bloc documentation](https://bloclibrary.dev/#/gettingstarted).
