### ISSUE TITLE
Example how to integrate Firebase with Cubit

### ISSUE THREAD

**Issue by reidlai** [felangel/bloc#1732]
Hi There,

I found many example to integrate firebase with Bloc.  But after cubit, is it possible to integrate firebase with cubit instead of bloc?  Thanks fo your advice.

**Comment by RollyPeres** [comment]
Hi @reidlai 👋

It is possible, you would basically swap bloc events for cubit method calls.
You can read more about this in [cubit vs bloc](https://bloclibrary.dev/#/coreconcepts?id=cubit-vs-bloc).

**Comment by felangel** [comment]
Hi @reidlai 👋 
Thanks for opening an issue!

As @RollyPeres mentioned you can definitely swap out bloc with cubit by replacing events with methods 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄
