### ISSUE TITLE
Passing bloc through multiple page

### ISSUE THREAD

**Issue by linxkaa** [felangel/bloc#1744]
Please help me out, 

I want to ask about passing the bloc, i have this main page called 
"ProductAddWidget()" here are several children related to this main page: 
- ProductCategory() -> (it has 3 children page)
- AddEtalasePostDatabase() -> (it has 2 children page)

Before, i passed the `SelectedCategoriesBloc` and  `EtalaseBloc` that used in `ProductCategory() `& `ProductAddWidget()` using MultiBlocProvider in main.dart. the problem is, the state is managed even i already close the `ProductAddWidget()` page. (because i want to manage the state in multiple page but only when im still opening the ProductAddWidget page) so im using `MultiBlocProvider` on my file route like this:
<img width="610" alt="Screen Shot 2020-09-18 at 15 27 07" src="https://user-images.githubusercontent.com/57997512/93575104-6a904480-f9c3-11ea-813a-4e278eb5621e.png">

when i called BlocProvider.of<SelectedCategoriesBloc> on product category, it gives me error: 
` BlocProvider.of() called with a context that does not contain a Bloc of type SelectedCategoriesBloc.`

but when i passed the bloc from `ProductAddWidget()` like this:
<img width="547" alt="Screen Shot 2020-09-18 at 15 38 30" src="https://user-images.githubusercontent.com/57997512/93576366-02426280-f9c5-11ea-9e8a-75d0bccb4896.png">

and in ProductCategory() i used screen args that passed the bloc from `ProductAddWidget()` like this:
<img width="597" alt="Screen Shot 2020-09-18 at 15 39 16" src="https://user-images.githubusercontent.com/57997512/93576456-1d14d700-f9c5-11ea-8b1b-503cb636e743.png">

it works just fine, but i want to know the best approach to used this kind of bloc when i have more than 10 children page and i only want to manage the state in 1 main page only not the entire app. 

I already used multiple approach like BlocProvider.value() etc. but its still the same.

**Comment by RollyPeres** [comment]
Hi @linxkaa 👋

Well you're proving a bloc called `SelectedCategoriesBloc` but trying to lookup a bloc of type `SelectedCategoryBloc`. Please notice that one uses plural and the other singular. Could that be your issue ? 😊

**Comment by linxkaa** [comment]
oh my bad, i mean `SelectedCategoriesBloc`. i write wrong on this issues but in my code its both `SelectedCategoriesBloc`

**Comment by RollyPeres** [comment]
I think it would be easier to get help if you'd share a link to a repo containing a minimal reproduction of your issue. 👍

**Comment by linxkaa** [comment]
i want to, but its my office related project and i could not share it publicly.. 😔 i just want to know how we can pass a bloc to multiple page without declaring and repeat passing the bloc from parent page to every children page.

**Comment by RollyPeres** [comment]
You can instantiate it in your router file and pass it with `BlocProvider.value` to each page that needs it.

**Comment by linxkaa** [comment]
here's are the code from my route in `ProductCategory()` --> the children page:
<img width="545" alt="Screen Shot 2020-09-18 at 17 17 41" src="https://user-images.githubusercontent.com/57997512/93586694-dd54ec00-f9d2-11ea-9630-2f1951bbbe6c.png">

here's are the code from my route in `ProductAddWidget()` --> the parent page:
<img width="547" alt="Screen Shot 2020-09-18 at 17 17 52" src="https://user-images.githubusercontent.com/57997512/93586713-e47bfa00-f9d2-11ea-9e2c-a7645c1308e3.png">


it not giving me any error instead it always giving me new state when i navigate to each page (the categories Bloc in `ProductAddWidget()` and `ProductCategory()` is different bloc), although i already declared that they both use the same categories bloc 

please help.

**Comment by RollyPeres** [comment]
As I already mentioned, you need to pass your bloc with `BlocProvider.value` to ALL pages that needs it. So don't use it with `create`.
```
final categoriesBloc = SelectedCategoriesBloc();

case ... BlocProvider.value
case ... BlocProvider.value

void dispose() {
  categoriesBloc.close();
}
```

**Comment by linxkaa** [comment]
Hello, thankyou for responding 🙏

but, the result is still the same after i used your code, it didnt save the previous state from the children page and giving me a new value instead,

![image](https://user-images.githubusercontent.com/57997512/93729555-3dc07500-fbef-11ea-9558-7151b4c6faf5.png)

here's the result:

<img width="549" alt="Screen Shot 2020-09-21 at 09 46 14" src="https://user-images.githubusercontent.com/57997512/93729564-4b75fa80-fbef-11ea-8831-2f523be1b1e6.png">

the value that i sent to bloc was 'CD Players', but when i'm navigator pop, the data become null again.

**Comment by RollyPeres** [comment]
This is just a partial snippet of your full implementation, so I can't advise you further unless you're taking the time to share a minimal reproduction repository of the issue you're having. Thanks 👍

**Comment by linxkaa** [comment]
thankyou i already solve it, its because i used static in my router files, and declare the SelectedCategoriesRoutes below the RouteSettings.
