### ISSUE TITLE
How do I replace BlocSupervisor().delegate when upgrading to 6.0.5?

### ISSUE THREAD

**Issue by MilesAdamson** [felangel/bloc#1748]
Hi. I was previously on a very old version of flutter bloc, 3.0.1. I am trying to upgrade to 6.0.5, and have fixed everything except for this line:

```
BlocSupervisor.delegate = BlocTransitionListener(userLoggingInfo: sentryLogging);
```

Both `BlocSupervisor` and `BlocSupervisor()` are now undefined.

I can't find the new method of listening to all my bloc transitions. Please help, thank you

**Comment by felangel** [comment]
Hi @MilesAdamson 👋 
Thanks for opening an issue!

Please refer to the [migration guide](https://bloclibrary.dev/#/migration?id=%e2%9d%97blocdelegate-renamed-to-blocobserver). Let me know if you still have questions 👍

**Comment by MilesAdamson** [comment]
Quick response and quick fix, already working. thank you!

`  Bloc.observer = BlocTransitionListener(userLoggingInfo: sentryLogging);`

`class BlocTransitionListener extends BlocObserver {`

**Comment by ajaygautam** [comment]
> Quick response and quick fix, already working. thank you!
> 
> ` Bloc.observer = BlocTransitionListener(userLoggingInfo: sentryLogging);`
> 
> `class BlocTransitionListener extends BlocObserver {`

Thanks for this quick fix!
The migration guide should make this clear.
I got stuck try to set an observer on MyAppBloc (instead of the parent Bloc class!) :(

**Comment by felangel** [comment]
@ajaygautam this should be covered in the [migration guide](https://bloclibrary.dev/#/migration?id=%e2%9d%97blocdelegate-renamed-to-blocobserver). Let me know if it was unclear/confusing and if there's anything you'd like to add or adjust 👍

**Comment by ajaygautam** [comment]
@felangel thanks for the response.
My apologies. I didn't read correctly. All set now. Thanks
