### ISSUE TITLE
How to cancel a processing event in Flutter bloc?

### ISSUE THREAD

**Issue by lzhuor** [felangel/bloc#1750]
I have already implemented `switchMap`. However, I am curious about how can I cancel a processing **Event A** (`OneTimeWebAppLauncherStarted` below) once **Event B** (`OneTimeWebAppLauncherCancelled`) is dispatched. Basically, I am still seeing `await callApi()` is executed although the cancel event is dispatched before the execution of `await callApi()`. 

Code snippet of my bloc:

```dart
  @override
  Stream<ApiResponse<String>> mapEventToState(OneTimeWebAppLauncherEvent event) async* {
      if (event is OneTimeWebAppLauncherCancelled) {
        yield ApiResponse.notAsked();
      }

      if (event is OneTimeWebAppLauncherStarted) {
        yield ApiResponse.loading();
        data = await callApi();
        yield ApiResponse<String>.completed(data: data);
      }
  }


  @override
  Stream<Transition<Event, ApiResponse>>
      transformEvents(
          Stream<OneTimeWebAppLauncherEvent> events,
          TransitionFunction<OneTimeWebAppLauncherEvent, ApiResponse>
              transitionFn) {
    return events.switchMap(transitionFn);
  }
```

**Comment by RollyPeres** [comment]
Hi @lzhuor 👋

If what you want is to cancel the API request then I'd suggest you use `dio` http client and make use of its [`CancelToken`](https://pub.dev/documentation/dio/latest/dio/CancelToken-class.html).

Alternatively, you could make use of `async` package with `CancelableOperation` or `CancelableCompleter`.

**Comment by felangel** [comment]
@lzhuor closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by lzhuor** [comment]
Thanks @felangel @RollyPeres !
