### ISSUE TITLE
Changing Bloc to Cubit form

### ISSUE THREAD

**Issue by ezra126** [felangel/bloc#1751]
how can  I change bloc to cubit form?  I got an error of type  Stream AuthenticationState can not be assigned to AuthenticationState

```
Class AuthenticationBloc extends Bloc<AuthenticationEvent, AuthenticationState> {
  final UserRepository _userRepository;

  AuthenticationBloc({@required UserRepository userRepository}) : assert(userRepository != null), _userRepository = userRepository, super(null);

  AuthenticationState get initialState => Uninitialized();
@override
Stream<AuthenticationState> mapEventToState(
  AuthenticationEvent event,
) async* {
  if (event is AppStarted) {
    yield* _mapAppStartedToState();
  } else if (event is LoggedIn) {
    yield* _mapLoggedInToState();
  } else if (event is LoggedOut) {
    yield* _mapLoggedOutToState();
  }
}

Stream<AuthenticationState> _mapAppStartedToState() async* {
  try {
    final isSignedIn = await _userRepository.isSignedIn();
    if (isSignedIn) {
      final name = await _userRepository.getUser();
      yield Authenticated(name);
    } else {
      yield Unauthenticated();
    }
  } catch (_) {
    yield Unauthenticated();
  }
}

Stream<AuthenticationState> _mapLoggedInToState() async* {
  yield Authenticated(await _userRepository.getUser());
}

Stream<AuthenticationState> _mapLoggedOutToState() async* {
  yield Unauthenticated();
  _userRepository.signOut();
}
```

**Comment by felangel** [comment]
Hi @ezra126 👋 
Thanks for opening an issue!

Can you please try changing the return type of `mapEventToState` to be `Stream<AuthenticationState>`?

```dart
@override
Stream<AuthenticationState> mapEventToState(AuthenticationEvent event) async* {...}
```

Let me know if that helps 👍

**Comment by ezra126** [comment]
Hi @felangel  The error is caused by change the above Bloc code into cubit.  emit function only works when passing the state to the parameter right but i need to add other functionality like repository so i create other functions to manage the repository which called by event triggered in cubit function .how can i implement in cubit ? here is the code again thanks in advance

class AuthenticationCubit extends Cubit<AuthenticationState> {
  final UserRepository _userRepository;

  AuthenticationCubit({@required UserRepository userRepository}) : assert(userRepository != null), _userRepository = userRepository, super(Uninitialized());

  void appStarted() async {
     _mapAppStartedToState();
  }
  void loggedIn() => emit(_mapLoggedInToState());
  void loggedOut() => emit( _mapLoggedOutToState());


 /* @override
  Stream<AuthenticationState> mapEventToState(AuthenticationEvent event) async* {
    if (event is AppStarted) {
      yield* _mapAppStartedToState();
    } else if (event is LoggedIn) {
      yield Authenticated('dd');
    } else if (event is LoggedOut) {
      yield* _mapLoggedOutToState();
    }
  }
*/

  Stream<AuthenticationState> _mapAppStartedToState() async* {
     try {
       final isSignedIn = await _userRepository.isSignedIn();
       if (isSignedIn) {
         final name = await _userRepository.getUser();
         emit(Authenticated(name));

       } else {
         emit(Unauthenticated());
       }
     } catch (_) {
       emit(Unauthenticated());
     }
  }

   _mapLoggedInToState() async* {
  //  print('hello');
     yield Authenticated('hf');

  }

   _mapLoggedOutToState() async* {
    yield Unauthenticated();
    _userRepository.signOut();
  }
}``

**Comment by ezra126** [comment]
ahh I asked a silly question I could use like this 

```
void appStarted()  async {
   // emit(Authenticated(''));
  //  _mapAppStartedToState();
    try {
      final isSignedIn = await _userRepository.isSignedIn();
      if (isSignedIn) {
        final name = await _userRepository.getUser();
        emit(Authenticated(name));

      } else {
        emit(Authenticated(''));
      }
    } catch (_) {
      emit(Unauthenticated());
    }
  }

```
