### ISSUE TITLE
[flutter_bloc] Proposal: add child parameter to BlocBuilder constructor

### ISSUE THREAD

**Issue by iapicca** [felangel/bloc#1752]
Adding a child parameter to BlocBuilder could improve efficiency and reduce boilerplate,
especially in cases where the bloc affect a widget but not its child, as for the example below.

In the current situation you have either:

1. Pointless rebuild

```dart
@override
 Widget build(BuildContext context) => BlocBuilder<OpacityCubit, double>(
    builder: (BuildContext context, double state) => Opacity(
    opacity: state,
    child: SomeWidget(), // <= rebuilds pointlessly
  ),
);
```

2. boilerplate and limitations 

```dart
 final Widget _child = SomeWidget();  // <= could be a problem in stateless widget with const constructor

 @override
 Widget build(BuildContext context) => BlocBuilder<OpacityCubit, double>(
   builder: (BuildContext context, double state) => Opacity(
    opacity: state,
    child: _child,
  ),
);
```

```dart
 @override
 Widget build(BuildContext context) {
   final Widget _child = SomeWidget();  // not fond of declaring stuff in the build function if I can avoid it
   return BlocBuilder<OpacityCubit, double>(
     builder: (BuildContext context, double state) => Opacity(
       opacity: state,
       child: _child,
    ),
  );
}
```

I propose something like the example below (an [approach](https://youtu.be/6KiPEqzJIKQ) similar to some implicit animation)

```dart
Widget build(BuildContext context) => BlocBuilder<OpacityCubit, double>(
  child: SomeWidget(),
  builder: (BuildContext context, double state) => Opacity(
    opacity: state,
    child: child,
  ),
);
```

**Comment by iapicca** [comment]
@felangel sorry I didn't see this [issue](https://github.com/felangel/bloc/issues/1596) I noticed only from the [PR](https://github.com/felangel/bloc/pull/1597) you linked
I won't take it personal if this issue get closed as duplicate

**Comment by felangel** [comment]
@iapicca the main problem I have with this feature request is justifying the breaking, verbose API will be worthwhile when in most cases this is an extra optimization. In my opinion, having a child and builder is confusing and adds noise to the API. Also, I think it's worthwhile pointing out that `StreamBuilder` does not currently offer support for this when the same argument can be made for including it -- it'd be interesting to raise this issue on Flutter in regards to `StreamBuilder` to see if there's a reason why support for `child` hasn't been added to `StreamBuilder`. Thoughts?

**Comment by iapicca** [comment]
@felangel 
I think you are making a valid point,
even though I'm convinced that this would be a positive change
and fairly safe to implement being essentially syntactic sugar
it would "break parity" with `StreamBuilder` which is less than desirable.

I'm considering making a PR for a `StreamBuilder` child parameter in flutter,
but I'll gather some feedback first. (yours is welcome as well)

I'm closing this issue for now

**Comment by felangel** [comment]
@iapicca sounds great, can you provide a link to the issue on Flutter?
