### ISSUE TITLE
flutter_firestore_todos is incompatible with the latest version of cloud_firestore 0.14.0+2 and firebase_auth

### ISSUE THREAD

**Issue by ssingh12** [felangel/bloc#1754]
**Describe the bug**
The 'todo_entity.dart' shows errors in fromSnapshot() method, and the 'firebase_user_repository,dart' has errors in isAuthenticated() method

**To Reproduce**
Update the cloud_firestore and firebase_auth packages to the latest version in pubspec.yaml

**Expected behavior**
No compile error, the 'flutter_firebase_todos' example works as expected.

I hope there is a plan to upgrade the examples to the latest versions of firebase and firestore packages.
Thanks.

**Comment by felangel** [comment]
Hi @ssingh12 👋 
Thanks for opening an issue!

This is a duplicate of #1706 👍
