### ISSUE TITLE
BlocListener emits multiple same states  causing navigated screen to build multiple times .

### ISSUE THREAD

**Issue by davidAg9** [felangel/bloc#1763]
**Describe the bug**
I have a screen that calls a view event  on a blog from my <blogPost>bloc which updates a field value if firebase and then emits a  viewsuccess state .I then use the bloclistener to list for the success state for which it should navigate to blog's detailed page and then passing the id of the blogdetailed  through a contractor to to call a new<blocPost> bloc of which emits a get blog using the id passed but when I am moving back  it seem to have built multiple version of the detailed screen about 3 times . and upon  **Debug** it seem to be coming from the listener which emits the view success state multiple times .
**Question**
why is this happening ?
Is it because if didn't scope the two different instances well ,if so how would I scope it cos I have used every means I could find online.

**All Codes**

**event handling viewEvent**
`if (event is ViewPost) {
      try {
        await _blogRepo.getAndUpdateViews(id: event.postId);
        yield ViewSuccess();
      } catch (e) {
        yield ViewFailed(err: e);
      }
}`

**code that update the firebase**
`Future<int> getAndUpdateViews({@required String id}) async {
    await _collection.document(id).updateData({VIEWS: FieldValue.increment(1)});
    return 0;`

**BlocListener and BlocBuilder**
<img width="508" alt="Screenshot 2020-09-23 at 10 02 00 AM" src="https://user-images.githubusercontent.com/56321266/93998349-edc6e700-fd83-11ea-9aba-43cf90959d7c.png">

<img width="471" alt="Screenshot 2020-09-23 at 10 02 29 AM" src="https://user-images.githubusercontent.com/56321266/93998336-e99ac980-fd83-11ea-8210-9f415c98d174.png">

**methods to handle navigation**
`void nextScreen(index, id) {
    var info = {'index': index, 'blogPost': id};
    detailedBlog = info;
  }`

  `void goToDetailed(context) {
    Navigator.of(context).pushNamed('/blogDetailed', arguments: detailedBlog);
  }`

**Comment by felangel** [comment]
Hi @davidAg9 👋 
Thanks for opening an issue!

Are you able to provide a link to a sample app which I can clone and run locally to reproduce the issue? Thanks! 👍

**Comment by davidAg9** [comment]
Fortunately you are a contributor since its a private repository

**Comment by davidAg9** [comment]
I think I was over using bloc although and since I wasn't popping any route in the above issue it kept the bloc listening for other states

**Comment by davidAg9** [comment]
To any one with the same issue ,you can consider the issue to be you bloc is still alive when routing to a new screen which indicates break some of it task into other blocs ,other properly popPush or pop and replace to close the bloc
