### ISSUE TITLE
Add support for Flutter Desktop: MacOS, Linux, Windows

### ISSUE THREAD

**Issue by karora** [felangel/bloc#1765]
With Flutter Desktop now available it's great to be able to target MacOS, Linux and Windows as well as Android, iOS and Web with a single build.  It would be nice to be able to use Bloc for these developments.

**Comment by JoseGeorges8** [comment]
I've used flutter bloc in a MacOS project and it works fine

**Comment by felangel** [comment]
Hi @karora 👋
Thanks for opening an issue!

There shouldn’t be any reason you can’t use bloc on all platforms. Is there a problem you’re encountering? If so, can you please provide a sample app to reproduce the issue? Thanks! 👍

**Comment by karora** [comment]
Sorry for the noise.  I guess I was fooled by the "Platforms Supported" as shown on https://pub.dev/packages/flutter_bloc but perhaps that's not updated yet to show support for Desktop platforms.
