### ISSUE TITLE
Error states Enum or generated by Freezed - bloc sending states issue

### ISSUE THREAD

**Issue by zs-dima** [felangel/bloc#1769]
We have simple bloc with 2 states Connected and ErrorState - and we do not need extra states (ConnectionStart or etc)

In case of unable to `api.connect();` we sending `ErrorState` used to warn users by toast message.
(widget subscribed to the bloc and showing toast message + we have 'Connect again' button)

In case of no connection and user continually press 'Connect again' button - it will by just first alert displayed - all next 'Connect again' button presses will display no alerts

States example:
```dart
enum ConnectState { connected, errorState }
```
or
```dart
@freezed
abstract class ConnectState with _$ConnectState {
  const factory ConnectState.connected() = Connected;
  const factory ConnectState.errorState(String error) = ErrorState;
}
```

Bloc part example:
```dart
  @override
  Stream<ConnectState> mapEventToState(ConnectEvent event) =>
    event.when(
      connect: () async* {
       try {
          api.connect();
          yield Connected();
       } on ConnectionError catch {
          yield ErrorState('Unable to connect');
       }
    }
```

You could easily find issue in the bloc source code:
_bindEventsToStates method

return state == transition.nextState || _stateController.isClosed;

So as you could see issue appear because of '==' comparison and it is no way to override it to fix this issue.
Could I kindly ask you to fix this issue or add possibility to override it?

It is some other scenarios when this issue appear I just provide certain one I always have.
And override States '==' method (generate random hash or etc) or create unneeded states is not good solution.

Thanks in advance

**Comment by RollyPeres** [comment]
Hi @zs-dima 👋

The issue you're facing is not really an issue and is certainly not bloc related. You should open an issue on `freezed` repo to allow for equality override on freezed classes, but I can tell you right now that Remi won't agree with that.

What you should do is:

```
yield Connecting();
api.connect();
yield Connected();
```

or have a `DateTime` field on your `ErrorState` to ensure subsequent yield of it will result in different states.

**Comment by zs-dima** [comment]
I do not need `Connecting` state for my case

**Comment by zs-dima** [comment]
More over states order not guaranteed - so it will not help to solve bloc issue

**Comment by RollyPeres** [comment]
I gave you a realistic solution to your "issue".
I highly encourage you to read more about immutability and it's benefits as well as the bloc pattern to get a better overall understanding of the what you're dealing with.

If you want to blame something for your equality not working as you expect that is `freezed` not `bloc`.
To demonstrate that, you can use simple classes instead of your freezed union and you'll notice that things are working as you expect.
If you want to be able to override an equality behavior that should be done on your freezed class not inside bloc implementation.

**Comment by zs-dima** [comment]
@RollyPeres you even had not read my comment about states order

**Comment by RollyPeres** [comment]
> More over states order is not guaranteed - so even this ugly boilerplate will not help to solve bloc issue

States order is guaranteed, they are emitted in the order of your yields.
With your case you'd always get: `Connecting` followed by `Connected` or `Connecting` followed by `ErrorState`.

**Comment by zs-dima** [comment]
@RollyPeres thanks you trying to help but 

1. I don't like crutches and ugly boilerplate

2. Even this crutches and ugly boilerplate is not really solution

So I hope Felix fix bloc issue finally

**Comment by zs-dima** [comment]
> States order is guaranteed, they are emitted in the order of your yields.

no as `transformEvents` usually overridden

**Comment by zs-dima** [comment]
However you could make bloc `transformEvents` private to remove possibility to override it and you example will work :) but `transformEvents` is not private.

**Comment by RollyPeres** [comment]
`transformEvents` has nothing to do with our discussion here, we're talking about processing of a single event and the states resulting from that processing.

**Comment by zs-dima** [comment]
User could press 'Connect again' button continually and you could not force him to do not do it 
and `transformEvents` means states order is NOT guaranteed

**Comment by zs-dima** [comment]
any way - any beautiful solution are welcome
or bloc issue fix at least

**Comment by zs-dima** [comment]
I could modify your example to make it mostly works, but it is really ugly:
```dart
try {
   api.connect();
   yield CrutchesToFixBlocIssueState();
   yield Connected();
} on ConnectionError catch {
   yield CrutchesToFixBlocIssueState();
   yield ErrorState('Unable to connect');
}
```

**Comment by felangel** [comment]
@zs-dima the following should work without:

```dart
abstract class ConnectState {}
class Connected extends ConnectState {}
class ErrorState extends ConnectState {
  ErrorState(this.error);
  final String error;
}

abstract class ConnectEvent {}
class ConnectStarted extends ConnectEvent {}

class ConnectBloc extends Bloc<ConnectEvent, ConnectState> {
  ConnectBloc() : super(null);

  @override
  Stream<ConnectState> mapEventToState(ConnectEvent event) async* {
    if (event is ConnectStarted) {
      try {
        await api.connect();
        yield Connected();
    } on ConnectionError {
      yield ErrorState('unable to connect');
    }
  }
}
```

Hope that helps 👍 

Closing for now but feel free to comment if you're still having trouble with the above implementation and I'm happy to help 😄

**Comment by zs-dima** [comment]
> 
> Hope that helps 👍 

@felangel it is NOT heplp at all as I have to use freezed classes for complex states

and Enum for simple

**Comment by felangel** [comment]
Why do you have to use `freezed` and `enums` exclusively?

**Comment by zs-dima** [comment]
I know you want to make immutable classes popular, and I respect immutable classes usages in right places.

But block is not really good tool to advertise immutable classes.

However you free to make with your library whatever you want, even lead developers to exceptions as above and make them problems.

**Comment by felangel** [comment]
@zs-dima you didn't answer my question. As I mentioned before, if you prefer mutable state then there are other solutions out there 👍

**Comment by zs-dima** [comment]
@felangel 
I want to use complex states with Freezed - in other case it will be a lot of bollerplate.

And for simple states I will prefer Enums for the same reason.

So any solution to answer this bloc bug are welcome, but your code is not related to my question.

**Comment by felangel** [comment]
@zs-dima you can't use enums because you want the same enum value to trigger a rebuild. Why would you why the UI to rebuild when the state has not changed?

**Comment by zs-dima** [comment]
I do not rebuild UI, I am sending toast alerts with this bloc.
More over bloc could be used without UI at all.
I mention it in the initial question.

**Comment by felangel** [comment]
@zs-dima BlocListener is only triggered on state changes. If the enum value hasn't changed then by definition, no state change has occurred.

**Comment by zs-dima** [comment]
I don't use flutter_bloc, I am using bloc + StreamBuilder

**Comment by zs-dima** [comment]
@felangel 
I don't use flutter_bloc, I am using subscribing on bloc stream directly to send toast alerts, I don't sure if BlocListener have to be changed as it could lead to unnedded UI rebuilds

**Comment by felangel** [comment]
@zs-dima state changes only occur when the state changes. In your case emitting ` ConnectState.connected` twice should not trigger a state change because nothing has changed.

**Comment by zs-dima** [comment]
bloc.whereState<ErrorState>().forEach(); for example

**Comment by zs-dima** [comment]
> @zs-dima state changes only occur when the state changes. In your case emitting ` ConnectState.connected` twice should not trigger a state change because nothing has changed.

I could easily filter out or district `ConnectState.connected` state as I like in the same way

**Comment by zs-dima** [comment]
More over it is one more point to remove check on bloc side - in case on filter I could receive duplicated states even with current bloc

**Comment by felangel** [comment]
I have already explained why I am against removing the check. Without that check, state will no longer need to be immutable which will cause more harm than good. We have given you several suggestions at this point for how to resolve your issue.

**Comment by zs-dima** [comment]
Let's summarize:
1. current bloc check doesn't work so I have to use district:
`bloc.whereState<Connected>(). distinct()`
2. in the block injected issue to advertise immutable classes, but lead new developers to issues and bollerplate:
`bloc.whereState<ErrorState>().forEach(...);`
3. Bloc library created exclusively for Flutter UI and don't care other scenarios (server side or etc)

**Comment by felangel** [comment]
@zs-dima I strongly disagree with your statements and it seems you are misunderstanding the point of immutable state and the role it plays in bloc.

1. You can use distinct but you need to make sure you're overriding `==` correctly
2. Immutability is there to save you from issues not cause more issues. If immutability was not enforced, the library would no longer be predictable as states could change at any point in time from anywhere.
3. That's incorrect (that's the reason for having separate packages like bloc, angular_bloc, flutter_bloc, etc...)

I think the problem you're facing is with [how equality works in Dart](https://dart.dev/guides/language/effective-dart/design#equality) and I would highly recommend reading more about it and looking at the [freezed implementation](https://github.com/rrousselGit/freezed/blob/2f1638f5e2a12f48800d05de1b095a9e875792c3/packages/freezed/lib/src/templates/concrete_template.dart#L338) for how equality is overridden.

**Comment by zs-dima** [comment]
@felangel looks you answer without reading my message.
current bloc state equally check even doesn't works, and lead to younger mistakes and bollerplate.
And you couldn't provide any beautiful solution to fix them.
Let's I will create new issue for bloc equally check, it is all I could help you.

You could be right if bloc restricted to the one state class only, but as bloc could send different states classes it is wrong. Hope you will understand it one day.

**Comment by felangel** [comment]
@zs-dima [I provided a solution](https://github.com/felangel/bloc/issues/1769#issuecomment-698388170) and you disregarded it. @RollyPeres provided a different suggestion and you disregarded it as well.

The only thing bloc enforces is that states are different (since a state change requires a change). It's up to you as the developer to override that behavior as needed (you're in full control of `operator==` and `hashCode`).

A bloc should not emit duplicate states by default because it doesn't make sense -- a state change requires something to have changed where a change is defined as the equality comparison between the previous state and the newly emitted state.

**Comment by zs-dima** [comment]
Hope final solution you provided for the !!!Freezed and !!!Enum states will help youngers:
​`​`​`dart
try {
   api.​connect​();
   ​yield​ ​CrutchesToFixBlocIssueState​();
   ​yield​ ​Connected​();
} ​on​ ​ConnectionError​ ​catch​ {
   ​yield​ ​CrutchesToFixBlocIssueState​();
   ​yield​ ​ErrorState​(​'Unable to connect'​);
}
​​`​`​`
however I don't like it and will use different way, please let me know when you understand what I told this topic about, in other case you just wasted my time.

**Comment by felangel** [comment]
That is the solution you came up with, not the one we recommended.

If you want to use classes:

```dart
abstract class ConnectState {}
class Connected extends ConnectState {}
class ErrorState extends ConnectState {
  ErrorState(this.error);
  final String error;
}

abstract class ConnectEvent {}
class ConnectStarted extends ConnectEvent {}

class ConnectBloc extends Bloc<ConnectEvent, ConnectState> {
  ConnectBloc() : super(null);

  @override
  Stream<ConnectState> mapEventToState(ConnectEvent event) async* {
    if (event is ConnectStarted) {
      try {
        await api.connect();
        yield Connected();
      } on ConnectionError {
        yield ErrorState('unable to connect');
      }
    }
  }
}
```

If you want to use enums:

```dart
try {
  yield ConnectionState.connecting;
   await api.​connect​();
   ​yield​ ​ConnectionState.connected​;
} ​on​ ​ConnectionError​ ​catch​ {
  yield ConnectionState.error;
}
```

If you want to use freezed:

```dart
try {
  yield ConnectionInProgress();
   await api.​connect​();
   ​yield​ ConnectionSuccess();
} ​on​ ​ConnectionError​ ​catch​ {
  yield ConnectionFailure('unable to connect');
}
```

Closing this issue since I don't appreciate your tone. If you don't like any of the above solutions you can always fork the library and make whatever changes you'd like.
