### ISSUE TITLE
[SUGGESTION/QUESTION] A Bloc example using Form validations

### ISSUE THREAD

**Issue by programadorthi** [felangel/bloc#177]
Please, update the Login example to show how to implement form validations using bloc.

**scenarios**:

1. Map a state when the username is empty. Show a specific message using I18N;
2. Map a state when the username does not match a regex expression. Show a specific message using I18N;
3. Map a state when the password is empty. Show a specific message using I18N;
4. Map a state when the password does not match a regex expression. Show a specific message using I18N;

The above scenario can be simple but what we do when have more fields such as a register form with the city, state, country, email, etc.

I did only open this issue because I didn't find in your examples something using bloc and validations.

**Comment by felangel** [comment]
Hey @programadorthi 👋 

I’ll try to put together an example over the next few days of form validation using bloc.
Thanks 👍

**Comment by Nothing-Works** [comment]
@felangel   please do so, looking forward to reading more examples.

**Comment by felangel** [comment]
@programadorthi @Nothing-Works check out [examples/flutter_form_validation](https://github.com/felangel/bloc/tree/master/examples/flutter_form_validation) for how to use bloc for form validation. Let me know if you have any other question 👍

**Comment by anticafe** [comment]
Hi @felangel Could you please update README to include your 2 new examples `flutter_form_validation` and `flutter_firebase_authentication`. BTW, thanks for your hard work 👍

**Comment by felangel** [comment]
Yup will do in the next few hours 👍 
No problem!

**Comment by felangel** [comment]
Just updated the README 👍
