### ISSUE TITLE
Using animation when BlocBuilder state changes

### ISSUE THREAD

**Issue by samramez** [felangel/bloc#1771]
**Is your feature request related to a problem? Please describe.**
Not really. I just can't figure out a clean way to solve my problem.

**Describe the solution you'd like**
As a states changes inside `BlocBuildder`, I wish to be able to change the state using animations such as "fade animation". Normally without using `flutter_bloc`, `AnimatedSwitcher` is used for this purpose but I wasn't able to find a clean way to achieve it.

**Describe alternatives you've considered**
I tried calling `setState()` each time the state is changed but that's not a clean way to do it.

**Additional context**
Let me know if I can provide further context.

**Comment by felangel** [comment]
Hi @samramez 👋 
Thanks for opening an issue!

I would highly recommend using `BlocListener` to manage animations. You can interact with an `AnimationController` in the `BlocListener's` `listener` callback to manage the animation.

Let me know if that helps! If you still have questions, it'd be great if you could put together a simple sample app which illustrates the problem you're facing 👍

**Comment by samramez** [comment]
Thanks @felangel for always being responsive.

good to know.
Do you happen to have access to an example for this which you can share here?

For example in the simple example below:

```dart
              BlocConsumer<OwnerCubit, OwnerState>(builder: (context, state) {

                    if (state is Success) {
                      return OwnerWidgets();
                    } 
                    
                    else if (state is Loading) {
                      return CircularProgressIndicator();
                    } 

                   else {
                      // initial state. We will return empty view.
                      return Container();
                    }
                  },
                   listener: (context, state) {      
                      
                   }
                 )
``` 

Are you suggesting that I wrap my `OwnerWidget()` with `AnimatedSwitcher` inside the `listener` ?

```dart
listener: (context, state) {      
       if (state is Success) {
            return AnimatedSwitcher(
                   child: OwnerWidget(),
            )            
        }
 }           
```

**Comment by RollyPeres** [comment]
Hi @samramez 👋

In case of an implicitly animated widget like `AnimatedSwitcher` you can make use of the builder instead.

```
BlocBuilder<OwnerCubit, OwnerState>(
      builder: (context, state) {
        return AnimatedSwitcher(
          child: state is Success
              ? OwnerWidget()
              : const CircularProgressIndicator(),
        );
      },
    )
```

**Comment by samramez** [comment]
thanks @RollyPeres and @felangel

**Comment by dxGuan** [comment]
> Hi @samramez 👋
> 
> In case of an implicitly animated widget like `AnimatedSwitcher` you can make use of the builder instead.
> 
> ```dart
> BlocBuilder<OwnerCubit, OwnerState>(
>       builder: (context, state) {
>         return AnimatedSwitcher(
>           child: state is Success
>               ? OwnerWidget()
>               : const CircularProgressIndicator(),
>         );
>       },
>     )
> ```

I am trying to build a layout with ```AnimatedSwitcher``` just like the snippet above.

However,  it seems not working. Do I need to call ```setState()``` explicitly or if I missing something?
