### ISSUE TITLE
[Question] 2 blocs with same state

### ISSUE THREAD

**Issue by SergejSachs** [felangel/bloc#1782]
Hello,

I have one bloc currently and he is handling two domain models "Note" and "Todo".
Both implements the interface "IWorkItem", so far so good but now my bloc gets pretty big.

I would like to split it into two blocs one for handling "Note" and one for "Todo".

My problem here is that currently my bloc holds the state of "List IWorkItem".
But if I would split into two blocs who will hold the state? 
A separate state for each bloc seems not practical because I have to show both types in one collection.

All solutions i can think of I don't like. 
* Passing two other classes and let them handle it at the bloc.
* One bloc extends another bloc, but this will result in a master and child basically.

Whats the best way to solve this problem?

**Comment by felangel** [comment]
Hi @SergejSachs 👋 
Thanks for opening an issue!

I would highly recommend creating a bloc for each feature rather than having a bloc for each type of resource. Let me know if that helps and if you're still unsure about the best approach it would be great if you could share a link to a sample app which illustrates the structure you have and what you're trying to achieve. Thanks! 🙏

**Comment by SergejSachs** [comment]
Hi :) Thanks for your fast response.

ok I think I got it while I tried to write my answer here haha.

Basically I should have two blocs for creating and updating notes and todos and one bloc for getting the overview "merged" list which holding the state.  

The create/update blocs don't need to hold the state and just report the overview bloc that one item got created right? :D

**Comment by felangel** [comment]
That would work but without additional context I’m not sure if that’s the way I’d recommend. I’d say try it and see how it feels or if you want you can provide a sample app which illustrates the functionality you want to achieve and I’m happy to give some suggestions 👍

**Comment by SergejSachs** [comment]
Thank you I think will try it that way first, I think that will solve my problem.

**Comment by SergejSachs** [comment]
thanks for your help 👍
