### ISSUE TITLE
Multi State (Stream)

### ISSUE THREAD

**Issue by geoffreylzf** [felangel/bloc#179]
Is there any way to make multi state (Stream) when I receive an event?

As Example below
https://github.com/filiph/state_experiments/blob/master/shared/lib/src/bloc/cart_bloc.dart
It receive one event (addition) , then trigger item_count and items.

Or I should implement the additional state (Stream) by myself? and dispose it somewhere

**Comment by felangel** [comment]
Hi @geoffreylzf 👋 

You can always expose new streams in the bloc just like in the example you linked to but I would question why you need to expose multiple streams in the bloc. I would recommend either consolidating the information into a single state object or creating multiple blocs. 

In the example you linked, I’d recommend having a single cart bloc with a state that includes a list of items in the cart. Hope that helps and great question 👍

**Comment by felangel** [comment]
Closing this for now but feel free to comment with additional questions/comments and I'm happy to continue to conversation 👍
