### ISSUE TITLE
Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by grappetite-ali** [felangel/bloc#1791]
**Describe the bug**
Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
I am getting this exception inside `HydratedStorage.build()` whenever i add flutter_facebook_auth package in my flutter project.

<img width="876" alt="Screen Shot 2020-10-02 at 4 20 35 PM" src="https://user-images.githubusercontent.com/16663361/94918143-6a1ba180-04cb-11eb-8a37-1eef4eec6e2a.png">

**To Reproduce**
1. Add this line at start of your flutter app. 
`HydratedBloc.storage = await HydratedStorage.build();` 
2. This `flutter_facebook_auth: ^0.3.2` in your pubspec.yaml
3. Install packages
4. Run the app you will get above exception in `HydratedStorage.build()` function.

**Expected behavior**
hydrated_bloc should work fine even with flutter_facebook_auth

**Logs **
_Analyzing newsifier...                                                  
No issues found! (ran in 7.6s)_

```
Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.4 at /Users/ali/Tools/flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ali/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
```

**Comment by felangel** [comment]
Hi @grappetite-ali 👋
Thanks for opening an issue!

It sounds like you might have forgotten to add `WidgetsFlutterBinding.ensureInitialized(); ` before initializing HydratedStorage.

Let me know if that helps 👍

**Comment by grappetite-ali** [comment]
No. `WidgetsFlutterBinding.ensureInitialized();` is already there. 
Look!
<img width="428" alt="Screen Shot 2020-10-02 at 6 17 19 PM" src="https://user-images.githubusercontent.com/16663361/94927426-ad7e0c00-04db-11eb-9ff8-611dcc8a80cb.png">

**Comment by felangel** [comment]
Can you provide a link to a repo which reproduces the issue? Thanks!

**Comment by narcodico** [comment]
Hi @grappetite-ali 👋
Do you have `path_provider` in your `pubspec.yaml` ?

**Comment by grappetite-ali** [comment]
Hey @narcodico ,
No.

**Comment by narcodico** [comment]
`getTemporaryDirectory` is from `path_provider` so try and add that package.

**Comment by grappetite-ali** [comment]
I tried. Same error.

**Comment by grappetite-ali** [comment]
I am closing this issue. This issue is related to path_provider plugin. I even tried calling  `getTemporaryDirectory` from my own code and its crashing.
