### ISSUE TITLE
[docs] What Core Concepts I'm learning new today?

### ISSUE THREAD

**Issue by Classy-Bear** [felangel/bloc#1796]
**Is your feature request related to a problem? Please describe.**

I was reading the new `Flutter Login Tutorial` (which is awesome btw) and I stopped and ask myself: What new BLoC [Core Concepts](https://bloclibrary.dev/#/flutterbloccoreconcepts) I'm learning today? I don't want the boring: "In the following tutorial, we're going to build...". 

**Describe the solution you'd like**

In the following tutorial, we're going to build... [Typical description]
What's new? <- [New Core Concepts I'm learning in this tutorial]
BlocListener : ...
BlocProvider: ...

**Describe alternatives you've considered**

Link a class when they appear for the first time. Why? People don't read the documentation, they jump in right to the tutorials, a reference to know more about the new CoreConcept will be epic.

**Additional context**

This is just a suggestion, I would like to know what Core Concept I'm learning in the tutorial because at the end of the day I have to figured out which to use and when. Another suggestion is to have interactive tutorials like Hive documentation has, it will be SO SO SO AWESOME TO HAVE IT.

Note : I haven't checked in past issues if something related were mentioned.

**Comment by mikededo** [comment]
It is a good idea, however, I believe that all tutorials use nearly all elements of `flutter_bloc`. I mean, there's barely one tutorial that only uses `BlocBuilder` so to say. Since the tutorials are nearly full projects (no matter their size), it is hard to implement such specific thing.  
Still, I believe it would be really interesting to add a small introduction or however it is called that explains what is going to be used and why in the following tutorial.  
What do you think? 😃

**Comment by felangel** [comment]
I agree with @mikededo that most tutorials will cover a wide variety of topics and I think the recipes section of the docs was more intended for these focused samples (see [SnackBar Recipe](https://bloclibrary.dev/#/recipesfluttershowsnackbar), [Bloc Access Recipe](https://bloclibrary.dev/#/recipesflutterblocaccess) for an example).

**Comment by Classy-Bear** [comment]
Replying to @mikededo 

Totally agree, what is going to be used and why is what I'm proposing.

> What's new? <- [New Core Concepts I'm learning in this tutorial]

My intention with the line above is to show the new core concepts that I haven't seen in previous tutorials assuming that I'm taking tutorials in the right order (beginner -> intermediate -> andvanced) because seen `BlocBuilder` again and again as "new core concept" is very repetitive.

This is just an idea, where I'm from some people confuses the `bloc` package with the `flutter_bloc` package, because they think [Core Concepts (package:bloc)](https://bloclibrary.dev/#/coreconcepts) is the same as [Core Concepts (package:flutter_bloc)](https://bloclibrary.dev/#/flutterbloccoreconcepts) which is not, maybe other people get confused as well with this

---

Replying to @felangel 

You're right.  If you think this is unnecessary close this issue. This problem is some kind related to https://github.com/felangel/bloc/issues/538, because in the [Flutter Counter Tutorial](https://bloclibrary.dev/#/fluttercountertutorial) says:

> Note: Only the Text widget is wrapped in a BlocBuilder because that is the only widget that needs to be rebuilt in response to state changes in the CounterCubit. Avoid unnecessarily wrapping widgets that don't need to be rebuilt when a state changes.

Unnecessary wrapping leads to `MultipleBlocBuilder`, which is bad design that solves a problem that can be avoided. This is related to this issue because some people doesn't fully understand the `flutter_bloc` concept.

This happens with any API, Design Pattern or Concept. For example OOP, is good when done correctly, SOLID principle came out as a solution of good written OOP, which kinda solves to the problem.

**Comment by mikededo** [comment]
Probably, what you are looking for, instead of more dense documentation (meaning, more information about each component), would be ways of structuring the Bloc pattern and your code. 

Maybe diagrams or widget trees that show how a proper (or efficient) structure should/could be, would do the trick.

**Comment by Classy-Bear** [comment]
First of all sorry for the late response.

No, I refer to [this](https://dart.dev/tutorials/language/streams) (in the "What's the point?" section). 

This will be a "What's new" example in BLoC:

What's new in this Tutorial?
- What's a [repository](https://bloclibrary.dev/#/architecture?id=repository) and why it's useful?
- Cubit instead of BLoC because of ... (felangel  wise explanation).
- Equatable is not being used and you will know why.
- When to use [Formz](https://pub.dev/packages/formz) and why it's best than using a [normal forms](https://api.flutter.dev/flutter/widgets/Form-class.html).

Aside of that, what you said earlier is a possible or extra solution I would like, a bad practice vs good practice on how to "proper (or efficient) structure" the widgets.

**Comment by mikededo** [comment]
Let's see what @felangel says. I will be up to contribute if necessary 😄

**Comment by felangel** [comment]
@Classy-Bear @mikededo sorry for the delayed response! I think it's a great idea to have a "What's new" section at the top of tutorials and welcome all pull requests to add this section to the existing tutorials 😄

**Comment by felangel** [comment]
This was done as part of #2131 thanks to @Classy-Bear 🎉
