### ISSUE TITLE
Basic issue with repository instantiation

### ISSUE THREAD

**Issue by ywaz** [felangel/bloc#1797]
**Describe the bug**
The app is a simple messenger, using firestore.
After setting the message event/state/bloc and also the repository that handles the message sending/fetching
I instantiated the repository in main()
however, the following error is returned:

'package:pingMe/bloc/bloc.dart': Failed assertion: line 12 pos 51: 'repository!=null': is not true.

I believe the solution is really straightforward, but I had a hard time to figure it out since I am new to this pattern.

Repository:
![image](https://user-images.githubusercontent.com/69506415/95017649-f5776d00-065a-11eb-9de9-5f33297ef93f.png)

bloc:

![image](https://user-images.githubusercontent.com/69506415/95017666-0aec9700-065b-11eb-9438-dc46d31eff10.png)

main:
![image](https://user-images.githubusercontent.com/69506415/95017676-15a72c00-065b-11eb-9f2c-14a03df172d7.png)

message event and state:

![image](https://user-images.githubusercontent.com/69506415/95017719-4f783280-065b-11eb-9349-d53fc1718094.png)

![image](https://user-images.githubusercontent.com/69506415/95017734-6b7bd400-065b-11eb-8ae5-a43f01dd9a88.png)

Many thanks in advance

Younes

**Comment by narcodico** [comment]
Hi @ywaz 👋

Looks like you're not passing the repository to your bloc in your `BlocProvider` creation.
`create: (context) => MessageBloc(repository: yourRepositoryInstance)`

**Comment by ywaz** [comment]
Hi @narcodico ,

Thank you for your reply.

I see your point, but in the main SS (that was incomplete in my first message) I am intiializing my MessageBloc in the initstate 
and only used BlocBuilder, which dosn't contain bloc property anymore as you can see here:

![image](https://user-images.githubusercontent.com/69506415/95018581-fad7b600-0660-11eb-89a4-5d49181310e7.png)

If I use BlocProvider, is the instantiation of MessageBloc in the initstate  no longer needed?

the blocprovider doesn't contain neither the bloc property as shown in the weather app example:
https://medium.com/flutter-community/weather-app-with-flutter-bloc-e24a7253340d

thank you in advance.

Younes

**Comment by narcodico** [comment]
Please share a minimal github repo with your issue, your screenshots are incomplete.

**Comment by ywaz** [comment]
yeah sure, 

just pushed it : https://github.com/ywaz/PingMe/tree/master

Thank you.

**Comment by narcodico** [comment]
I've open a [PR](https://github.com/ywaz/PingMe/pull/1) with fixes and improved coding practices.

Your initial code wasn't working because you had at some point in one of the constructors `{@required repository}` instead of ``{@required this.repository}`` and also you had no `BlocProvider<MessageBloc>` to provide an instance of `MessageBloc` to your widget tree. The quickest fix would have been to specify in your `BlocBuilder` `cubit: _msgBloc`.
