### ISSUE TITLE
Include SignUp for firebase authentication

### ISSUE THREAD

**Issue by ricktotec** [felangel/bloc#180]
**Issue.**
I've tried to add a signup bloc for new users but when I press the Signup Button, it creates the user but doesn't redirect to login or home page.

**Feature Request**
I'd like to know how to add signup bloc in order to create a new user account with email and password.

Thanks.

**Comment by felangel** [comment]
Hey @ricktotec 👋 

There's currently a [firebase_authentication example](https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_authentication) which I can add sign up functionality to 👍 

I'll try to do that over the next few days.

**Comment by ricktotec** [comment]
Thanks form your quick response. 
I've seen the firebase_authentication example. I'll try to add the sign up and let you know if I can't get it to work.

Regards.

**Comment by felangel** [comment]
Added SignUp to the [Flutter Firebase Authentication Example](https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_authentication).
