### ISSUE TITLE
A package may not list itself as a dependency. (flutter_bloc: ^0.9.0)

### ISSUE THREAD

**Issue by rrifafauzikomara** [felangel/bloc#181]
When i try to get the package i get this

`[flutter_bloc] flutter packages get
Running "flutter packages get" in flutter_bloc...               
Error on line 20, column 3 of pubspec.yaml: A package may not list itself as a dependency.

  flutter_bloc: ^0.9.0

  ^^^^^^^^^^^^
pub get failed (65)
exit code 65`

**Comment by felangel** [comment]
Hi @rrifafauzikomara 👋 

I'm guessing the name of your flutter project is also `flutter_bloc`.

```yaml
name: flutter_bloc

dependencies:
  flutter_bloc: ^0.9.0
```
Can you check if that's the case and if not could you please include the full `pubspec.yaml` file?

Thanks!

**Comment by rrifafauzikomara** [comment]
Hi @felangel 


Yes, you are right. That happens because the project name is the same as the library name. So when running the "flutter packages get" command, flutter reads the project name instead of the library name. Thank you

**Comment by AliAon** [comment]
thanks

**Comment by JeanGonzalo** [comment]
thanks a lot

**Comment by viralvaghela** [comment]
Thank you

**Comment by paurakhsharma** [comment]
Thank you :sweat_smile:

**Comment by vinayvishnu725** [comment]
@felangel felangel you are absolutely right thank you so much

**Comment by ARJUPTA** [comment]
Thank you

**Comment by reshnu** [comment]
Thanks,this is because my project name and package name is same so this error happens after that changing my project name it working fine

**Comment by and2carvalho** [comment]
Nice catch! Thanks

**Comment by keshkaush** [comment]
thanks a lot..u saved the night..!!

**Comment by akmaljoha** [comment]
thank you so muchhh bruhjhhhhhhhhhhhhhhhhhh really help!

**Comment by hayatbangash55** [comment]
Thanks

**Comment by jhon2520** [comment]
Thanks a lot. I had the same problem.

**Comment by 90-TinhMercedes** [comment]
> Hi @rrifafauzikomara 👋
> 
> I'm guessing the name of your flutter project is also `flutter_bloc`.
> 
> ```yaml
> name: flutter_bloc
> 
> dependencies:
>   flutter_bloc: ^0.9.0
> ```
> 
> Can you check if that's the case and if not could you please include the full `pubspec.yaml` file?
> 
> Thanks!

> Yes, thanks a lot. ❤

**Comment by furkanKuran** [comment]
Thank u @felangel

**Comment by LakshanKodithuwakku** [comment]
Thank you!

**Comment by ahmadbintariq4u** [comment]
Thanku Man you name my time

**Comment by ahmadbintariq4u** [comment]
> Thanku Man you save my time

**Comment by nhoaichuong2001** [comment]
That was awesome

**Comment by bisrax** [comment]
thanks

**Comment by behnambagi** [comment]
thanks goood man

**Comment by IrfanAbdulghaffar** [comment]
thanks for this buddy
