### ISSUE TITLE
how to handle auto suggest tag text field with multiple inputs with other form values before submit using bloc ?

### ISSUE THREAD

**Issue by johnyenatu** [felangel/bloc#1814]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by felangel** [comment]
Hi @johnyenatu 👋 
Thanks for opening an issue!

Can you please fill out the issue template and provide more information? Just based on the title of the issue I don't think I have enough information to help.

**Comment by felangel** [comment]
Closing for now since there isn't enough information in the issue. Feel free to add additional info and I'm happy to continue the conversation 👍

**Comment by johnyenatu** [comment]
hello felangel I am trying to get multiple  key value pairs from text field and add them to array object but I have no Idea how can I Implement this can you help ?

**Comment by johnyenatu** [comment]
import 'package:flutter/material.dart';

import 'model/lable.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: Test(),
    );
  }
}

class Test extends StatefulWidget {
  @override
  _TestState createState() => _TestState();
}

class _TestState extends State<Test> {
  final TextEditingController _controllerKey = TextEditingController();
  final TextEditingController _controllerValue = TextEditingController();

  int adddinput = 1;

  List<Lable> list = new List<Lable>();
  void manageInput(String key, String value) {
    Lable l = new Lable();
    l.key = key;
    l.value = value;
    this.list.add(l);
    int addInout2 = adddinput + 1;
    setState(() {
      adddinput = addInout2;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: [
          ListView.builder(
              shrinkWrap: true,
              itemCount: adddinput,
              itemBuilder: (context, index) {
                return Container(
                  child: Center(
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Expanded(
                          child: TextField(
                            controller: _controllerKey,
                            decoration: InputDecoration(labelText: "key"),
                          ),
                        ),
                        Expanded(
                          child: TextField(
                            controller: _controllerValue,
                            decoration: InputDecoration(labelText: "value"),
                          ),
                        ),
                        IconButton(
                            icon: Icon(Icons.add),
                            onPressed: () {
                              manageInput(
                                  _controllerKey.text, _controllerValue.text);
                            }),
                      ],
                    ),
                  ),
                );
              }),
          RaisedButton(
            child: Text('Create Data'),
            onPressed: () {
              setState(() {
                print(this.list);
              });
            },
          ),
        ],
      ),
    );
  }
}



class Subscriber{
  List<Lable> labeldata;
}

class Lable {
  String key;
  String value;
}
