### ISSUE TITLE
Blocs communication with each other

### ISSUE THREAD

**Issue by popay34** [felangel/bloc#1815]
Hello! In Todos example we have two blocs witch are communicate with each other: FilteredTodosBloc and TodosBloc. 
This is a part of code in main.dart file witch create dependencies: 
```
BlocProvider<FilteredTodosBloc>( 
create: (context) => FilteredTodosBloc( 
todosBloc: BlocProvider.of<TodosBloc>(context), 
 ), 
 ), 
```
How to create dependencies if i use get_it package? Because this method does not work: 
`BlocProvider<FilteredTodosBloc>(create: (context) => getIt<FilteredTodosBloc>()), `

**Comment by JErazo7** [comment]
The same doubt

**Comment by felangel** [comment]
Hi @popay34 👋 
Thanks for opening an issue!

That should work as long as you've registered both blocs properly like:

```dart
getIt.registerSingleton<TodosBloc>(TodosBloc());
getIt.registerSingleton<FilteredTodosBloc>(FilteredTodosBloc(getIt<TodosBloc>()));
```

Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment if you have additional questions and I'm happy to continue the conversation 👍

**Comment by edmbn** [comment]
Hello @felangel, 

Do you think it is really needed get_it? If bloc is already easy to test I don't see why so many people use it with get_it. 

Thank you for your time!

**Comment by JoseGeorges8** [comment]
@edmbn GetIt is great for injecting third party libraries that might complicate your testing. I use it for a NetworkClient singleton that I've created and Instabug package and it works great. 

I was also thinking about changing some of my repositories to be part of the GetIt instance as well, which I think will decouple things a big more.

**Comment by popay34** [comment]
Hey, Felix! Thank you for your answer!
But when i create dependencies in the usual way everything works fine:
`todosBloc: BlocProvider.of<TodosBloc>(context)`
But this solution still not work for me:
`getIt.registerSingleton<FilteredTodosBloc>(FilteredTodosBloc(getIt<TodosBloc>()));`
Does this injection provide a current contex (current state) of TodosBloc? Mayby i get an error because it provide only initial state and do not update the state when it changed?
