### ISSUE TITLE
Wrap with blockprovider is not visible in refractor

### ISSUE THREAD

**Issue by Sathish9222** [felangel/bloc#1818]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

**Additional context**

**Comment by felangel** [comment]
Hi @Sathish9222 👋
Thanks for opening an issue!

Can you please fill out the issue template and provide steps to reproduce the issue? Thanks 🙏

**Comment by Sathish9222** [comment]
Hi ,
Please find the below screen shot. Not able to find the bloc in refractor 

![image](https://user-images.githubusercontent.com/20543188/95660327-c87dfb00-0b2f-11eb-9d01-5594a2e90345.png)

**Comment by QAQyzk** [comment]
I think the problem is 'wrap with bloc' only exist in quick fix (ctrl+.) not in refactor(ctrl+shift+r)

**Comment by Sathish9222** [comment]
Ok dear .thank you got it.
