### ISSUE TITLE
VSCode Extension: cubit state template seems to have a typo

### ISSUE THREAD

**Issue by MasterHiei** [felangel/bloc#1821]
**Describe the bug**
cubit state template seems to have a typo like below:
```diff
- const factory ${pascalCaseCubitName}State.inital() = _Initial;
+ const factory ${pascalCaseCubitName}State.initial() = _Initial;
```
https://github.com/felangel/bloc/blob/master/extensions/vscode/src/templates/cubit-state.template.ts#L53

**To Reproduce**
Generate new cubit with vscode bloc extension

**Expected behavior**
Fix it if need be.

**Comment by felangel** [comment]
Hi @MasterHiei 👋 
Thanks for opening an issue!

This has been fixed in #1822 and published in v5.3.1 🎉
