### ISSUE TITLE
Architecture for repositories within blocs

### ISSUE THREAD

**Issue by engineerdeep** [felangel/bloc#1827]
Hi @felangel 👋 ,

I'm sorry if this question was already asked, I tried to search the same but it wasn't quite answered.

I've created blocs into their own separate packages along with the repository and data provider.

I noticed in your [fluttersaurus](https://github.com/felangel/fluttersaurus) project (and in many other examples) you're using `RepositoryProvider` to add a repository to a widget and then use that to inject the repository into the bloc. If the UI is only ever going to interact with the bloc, why do we need to add the repository dependency on the UI? Wouldn't it be better to add the repository as the dependency in the bloc package itself and by doing so the UI will only depend on the bloc package and doesn't need to care about what repository the bloc uses. 

I'd love to hear your thoughts for the same & thank you for your time!

**Comment by rodrigobastosv** [comment]
Hi @engineerdeep ,

Adding the repository dependency on the UI make it simples when you try to test your code, since you can always pass a mock instance of repository to your bloc. Besides that, when trying to text your widgets you can easily mock that too.

**Comment by engineerdeep** [comment]
Hi @rodrigobastosv, 

Thank you for the quick response. Wouldn't mocking the repository be possible when we test the bloc package itself with the repository added there? I don't have much experience with mockito so please pardon me if I'm wrong.

**Comment by rodrigobastosv** [comment]
Hi @engineerdeep,

If you create the repository instance inside of the bloc it will be much harder to mock this instance.

Passing the repository instance through bloc constructor greatly simplify things, because while testing you can create your mock repository instance and pass it to the bloc you are testing.

I hope i made myself clear :)

**Comment by engineerdeep** [comment]
Hi @rodrigobastosv,

Oh yes, I get it. For some reason I was assuming I wouldn't have to pass the repository if in my bloc package I pass the repository through the constructor . I would have to create the bloc in my UI and would have to pass the repository instance anyway, my bad!
Thank you so much! :)
