### ISSUE TITLE
(Login tutorial) Document how to use a User with other blocs?

### ISSUE THREAD

**Issue by hacker1024** [felangel/bloc#1843]
**Is your feature request related to a problem? Please describe.**
My app has multiple features that use authenticated API calls. The login example/tutorial has been great for getting the architecture started (thanks!), but one thing remains unclear. How can API calls made from other blocs/repositories make use of the `User` object?

- The `User` is part of the `AuthenticationState`, so other blocs could depend on the `AuthenticationBloc`, and pass the user as an argument to their repositories. This will also allow the bloc to easily make sure that the user is in fact authenticated before it tries to do anything. This approach, however, causes the business logic layer to depend on an object that's really part of the data layer, which doesn't seem right.

- Other repositories could depend on the `AuthenticationRepository`. This approach seems cleaner, but at the moment there's no way to actually check the authentication state from the repository alone; that information is only sent to a stream, of which the sole listener is the `AuthenticationBloc`. The other bloc(s) calling the repository could also depend on the `AuthenticationBloc`, and use that to check the state before using the repository - but that seems like it shouldn't be neccesary, as the repository _could_ theoretically be changed to keep track of its own state (but the example doesn't do that).

**Describe the solution you'd like**
It'd be great if this could perhaps be discussed in the tutorial, as I'm sure it's quite common for apps to need a `User` object to authenticate API calls with.

**Describe alternatives you've considered**
N/A

**Additional context**
None.

**Comment by felangel** [comment]
Hi @hacker1024 👋 
Thanks for opening an issue!

There are several things you can do:

The simplest is probably to expose an extension on `BuildContext` to perform the lookup and fetch the current user.

```dart
extension UserX on BuildContext {
  User get user => bloc<AuthenticationBloc>().state.user;
}
```

This could then be used through the widget tree to access the current user and inject it into other blocs like:

```dart
BlocProvider(
  create: (context) => SomeOtherBloc(user: context.user),
  child: SomeOtherFeature(),
);
```

Hope that helps!

Closing for now but feel free to comment with additional questions/comments and I'm happy to continue the conversation 👍

**Comment by hacker1024** [comment]
Thanks for the advice!

This doesn't quite work for me, for a couple of reasons:

1. The other blocs would have no way of knowing when the user changes; if the auth bloc assigns a new user to the `user` variable, the existing blocs would still be holding on to the old instance.

2. This is putting the responsibility on the bloc layer to supply a user to additional repositories. As the user is only used for authentication in other repositories, I feel like it shouldn't be passed through the bloc layer at all.

I've taken a slightly different approach, which I hope is okay (I'm quite new to all this architecture stuff):

- When the login event is sent to the auth bloc, it calls `login` in the auth repository.
- The auth repository has a `BroadcastStream` that broadcasts an `AuthStatus` enum. Upon logging in, the user is stored in a variable inside the repository, and a "logged in" state is broadcasted.
- The login bloc listens to the status stream, and updates its state accordingly.

This is very similar to the example so far, but with two notable differences. The status stream is a broadcast stream meaning more than one listener can attach to it, and the user is stored in the auth repository instead of a bloc.
Now, when the user is needed elsewhere:

- A bloc that uses an API that relies on a user will have its own repository that takes the auth repository as a constructor parameter (through the magic of dependency injection).
- The new repository will use the user object from the passed in authentication repository.
- The new repository will also listen to the auth repository's status stream, so it can clear caches when neccesary. If it does so, it will also notify its bloc with the use of its own separate `CacheStatus` stream.

This way, everything is kept in the data/repository layer, and the blocs only need to deal with updates from their own repositories.
