### ISSUE TITLE
BlocProvider.of() called with a context that does not contain a Cubit

### ISSUE THREAD

**Issue by truongduy997** [felangel/bloc#1845]
**Describe the bug**
BlocProvider.of() called with a context that does not contain a Cubit
 - I want to add event with BlocProvider.of<Bloc>(context), but I got this error. Help meee!!!!!

![image](https://user-images.githubusercontent.com/43513612/96638955-26d68500-134b-11eb-8412-a129ad1567b2.png)

**Comment by venkateshironman** [comment]
BlocProvider.of() will be used to get the existing bloc

// with extensions
context.bloc<BlocA>();

// without extensions
BlocProvider.of<BlocA>(context)

Below method is used to create bloc 

BlocProvider(
  create: (BuildContext context) => BlocA(),
  child: ChildA(),
);

**Comment by felangel** [comment]
Hi @truongduy997 👋 
Thanks for opening an issue!

Please make sure you are trying to access the bloc from a different `BuildContext`.

You cannot access it directly from the same context because that BuildContext does not have access to the bloc.

```dart
BlocProvider(
  create: (_) => MyBloc(),
  child: TextButton(
    onPressed: () {
      // this will not work because the BuildContext does not have access to the provided bloc
      final bloc = context.bloc<MyBloc>();
    },
  ),
)
```

```dart
BlocProvider(
  create: (_) => MyBloc(),
  child: Builder(
    builder: (context) => TextButton(
      onPressed: () {
        // this will work as expected
        final bloc = context.bloc<MyBloc>();
      },
    ),
  ),
)
```

Let me know if that helps 👍

**Comment by truongduy997** [comment]
Thank @felangel and @venkateshironman so much, i'm done =))
Because i called BlocProvider.of<BlocA>(context) outside BlocBuilder, thank you again for your help !!!!

**Comment by bretmh** [comment]
> BlocProvider.of() will be used to get the existing bloc
> 
> // with extensions
> context.bloc();
> 
> // without extensions
> BlocProvider.of(context)
> 
> Below method is used to create bloc
> 
> BlocProvider(
> create: (BuildContext context) => BlocA(),
> child: ChildA(),
> );

What do you mean by with/without extensions?

**Comment by felangel** [comment]
> > BlocProvider.of() will be used to get the existing bloc
> > // with extensions
> > context.bloc();
> > // without extensions
> > BlocProvider.of(context)
> > Below method is used to create bloc
> > BlocProvider(
> > create: (BuildContext context) => BlocA(),
> > child: ChildA(),
> > );
> 
> What do you mean by with/without extensions? That bloc provides an extension for BuildContext to lookup bloc providers?

Yup you can use the extension method on `BuildContext` to access a bloc via:

```dart
// Read
final bloc = context.read<MyBloc>();

// Watch for changes
final bloc = context.watch<MyBloc>();
```

They are just shorthand for:
```dart
// Read
final bloc = BlocProvider.of<MyBloc>(context);

// Watch for changes
final bloc = BlocProvider.of<MyBloc>(context, listen: true);
```

Hope that helps 👍
