### ISSUE TITLE
Problem with widget test of a BLoC with bool state

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#1846]
Please note that this bug (?) has been observed on version 2.0.0 of the library. Yes, my workplace is a sad place. However, maybe you know this one and can say when it was fixed and what was going on, or maybe it is reproducible on a newer version?

**Describe the bug**

Our BLoC's state is a simple `bool`. When we run the application, all works fine, it's the test that is giving us issues. We mock the BLoC like this:

```dart
class MockBoolStateBloc extends Mock implements BoolStateBloc {}

...

bloc = MockBoolStateBloc();

...

whenListen(bloc, Stream.fromIterable([true, true]));
```

In the Widget, we use a `BlocBuilder`, like this:

```dart
return BlocBuilder<BoolStateBloc, bool>(
  builder: (context, state) {
    return state ? WidgetA() : WidgetB();
  },
);
```

When the test is run, we get the following erorr:
```
The following assertion was thrown building BlocBuilder<BoolStateBloc, bool>(dirty,
state: _BlocBuilderBaseState<BoolStateBloc, bool>#86d84):
Failed assertion: boolean expression must not be null

...

When the exception was thrown, this was the stack:
#0      _BoolWidget.build.<anonymous closure> (package:blabla/bool_widget.dart:28:20)
#1      BlocBuilder.build (package:flutter_bloc/src/bloc_builder.dart:88:57)
#2      _BlocBuilderBaseState.build (package:flutter_bloc/src/bloc_builder.dart:157:48)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4663:28)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4546:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
...
```

and the line in `#2` points to the line:

```dart
  Widget build(BuildContext context) => widget.build(context, _state);
```

To make the test work, we also need this:
```dart
when(bloc.state).thenReturn(false);
```

All other BLoCs and tests that we have don't require this `bloc.state` stubbing, but all of them use custom classes as states. So we conducted an experiment and changed the BLoC so that the state is not a `bool`, but rather a wrapper type around it, and the test passes without changes (except that we need to change the `whenListen` call to return a stream of our wrapper), i.e. we can get rid of the `when(bloc.state)...` line and the test passes.

It seems that the issue is specific to `bool` states only (we tested with `int` as well and it works fine) and originates from within this library, or maybe deeper.

Is this something you guys are aware of?

**Comment by wujek-srujek** [comment]
I created a small app that should reproduce the error, but I can't, which means it only fails in our app. I will close this until we know more, which may be never. Sorry for the noise.

**Comment by felangel** [comment]
@wujek-srujek keep me posted and let me know if there's anything I can do to help 👍
