### ISSUE TITLE
When to use Login Bloc if I integrate form_validation_bloc

### ISSUE THREAD

**Issue by Rickem** [felangel/bloc#185]
**Issue**
I'm tryning to implement the login bloc with form validation. I've seen the validation exemple, now I wonder when to use the login bloc.

**Solution**
Can you specify where and how to include the login bloc?

Thanks in advance.

**Comment by felangel** [comment]
Hi @rickem 👋 

You can have a LoginForm bloc that does the form validation and keep the login bloc for managing the overall login state (error/loading/success). Let me know if that helps. 👍
