### ISSUE TITLE
Flutter - Bloc builder is not updating UI state in Alert Dialog?

### ISSUE THREAD

**Issue by jaym-inci** [felangel/bloc#1852]
I am trying to implement a Feature using Flutter BLoC Pattern in which i want to update the UI theme based on the selection of Theme Type from Alert Dialog, but when i try to implementing this functionality using Flutter BLoC pattern my UI doesn't get update in Alert Dialog

currently, i have Applied workaround Solution for changing theme by dispatching two BLoC Events 
1. to Set the Theme
2. to Get Updated Theme

```
BlocProvider.of<ThemeChangeBloc>(context).add(SetThemeChangeEvent('GreenDark'));
BlocProvider.of<ThemeChangeBloc>(context).add(GetThemeChangeEvent());
```

i have created a GIT repo and providing you the link here
[https://github.com/jaygadariya/Theme-Changer](url)

so how can i update my Alert Dialog UI using Flutter BLoC Pattern?

Thanks.

**Comment by felangel** [comment]
Hi @jaym-inci 👋 
Thanks for opening an issue!

I opened a [pull request](https://github.com/jaygadariya/Theme-Changer/pull/1) which includes changes to achieve the desired functionality. Hope that helps 👍

**Comment by abdulhaq-e** [comment]
> Hi @jaym-inci 👋
> Thanks for opening an issue!
> 
> I opened a [pull request](https://github.com/jaygadariya/Theme-Changer/pull/1) which includes changes to achieve the desired functionality. Hope that helps 👍

I was just looking around the issues while learning from this repo and I found this comment and PR. I have to say you are awesome. Thanks for all your hard work!

**Comment by felangel** [comment]
@jaym-inci closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
