### ISSUE TITLE
Doese buildWhen not fire at fist time ?

### ISSUE THREAD

**Issue by danbn-100295** [felangel/bloc#1855]
I have demo with this code 
` BlocBuilder<TyperoomBloc, TyperoomState>(
            buildWhen: (previous, current) {
              print('current state');
              print(current);
              return false;
            },`
But it is not print any thing at first time ?
Any wrong ?

**Comment by felangel** [comment]
Hi @danbn-100295 👋 
Thanks for opening an issue!

This is working as expected because the initial render is not due to a state change. `buildWhen` is only invoked on state changes 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄

**Comment by omidraha** [comment]
When I press `backbutton`, the `buildWhen` is not called, but `BlocBuilder` called for unwanted condition in the `buildWhen`.
