### ISSUE TITLE
[Feature Request] SuperHydratedBloc: A Hydrated Bloc, taking an API Url and an UpdateRuleObject

### ISSUE THREAD

**Issue by mapadj** [felangel/bloc#1857]
Hi Felix!

Imagine a SuperHydratedBloc, extending Hydrated Bloc, that will pull an api json object from URL, safes data persistant and takes an update Object, defining a cache_rule, similar to advanced_network_image:

```
AdvancedNetworkImage(
    url,
    header: header,
    useDiskCache: true,
    cacheRule: CacheRule(maxAge: const Duration(days: 7)),
```

Imagine, we add a second URL to the Cach_rule, which will be able to pull the version/hash of the data url, so we can update persistant data from the web, only, if there is new data.

This could reduce complexity of projects, while it improves speed (displays old data, before pulling new, if availabe), and reduces traffic.

A Class of SuperHydrated Bloc could look like this:

```
@injectable()
 class WebObjectsCubit extends SuperHydratedCubit<KtList<WebObject>> {

WebObjectsCubit (): super(KtList<WebObject>.empty(), url: 'someUrl', cache_rule: CacheRule( time: null, hash: 'url_to_hash'));

@override
  KtList<WebObject> fromJson(Map<String, dynamic> json) =>  WebObjectsDto.fromJson(json).toDomain();

 @override
  Map<String, dynamic> toJson(KtList<WebObject> state) =>
      WebObjectsDto.fromDomain(state).toJson();
}
```

Love your work.

Marcel from Hamburg

**Comment by felangel** [comment]
Hi @mapadj 👋 
Thanks for opening an issue and for the positive feedback!

This could be an interesting concept as an external package but my initial reaction is not to incorporate it into the existing package because it results in tightly coupling raw API data to the UI when usually I recommend maintaining a clear separation between the two (using repositories). Despite that, it could be interesting as a standalone package -- is that something you'd be interested in maintaining? If so, I'd be happy to help review any pull requests and answer any questions you might have 👍 

Thoughts?

**Comment by mapadj** [comment]
Hey!

of course a stand alone package would be just fine. no need to clutter the bloc library. 
When i finished my current project, i will need to look into package design and maintaining, for i have never done such.

i actually use your library in separete layers of my project, to keep stuff testable. i struggled to get my head arround a clear structure of what i am trying to achieve and ended up using the hydrated_bloc library for private, persistant data and cubits for api calls in the infrastructure level, having dtos, contracts, and value objects in domain and business logic in application layer. have a look:

![current_structure](https://user-images.githubusercontent.com/8014186/97155617-ec6b4e80-1775-11eb-91b9-9678473e637f.png)

from this point i thought, i i could do the same with the api endpoints, as i did with application data using hydrated bloc, that would be awesome and speed up dev/testing a lot.

Is your approach completely different? Or am i missing some better strategy that makes this approach obsolete?

Have a nice week.

**Comment by felangel** [comment]
Thanks for sharing! I usually recommend having the cubits/blocs communicate with one or more repositories and each repository depends on one or more api clients/data providers. You can check out [fluttersaurus](https://github.com/felangel/fluttersaurus) for an example of the project and feature structure.

**Comment by mapadj** [comment]
Cool. I will have a look at it. If I still find a package usefill, i might get back to you at a later point. Have a nice day.
