### ISSUE TITLE
Bug flutter_infinite_list example

### ISSUE THREAD

**Issue by longth97** [felangel/bloc#1858]
I try to load the list for the first time with 5 elements and get the bottom loading like this
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-24 at 21 27 11](https://user-images.githubusercontent.com/48413548/97084221-cd6aa080-163f-11eb-8ad2-2decddfbf015.png)

**Comment by cemanganas** [comment]
i added this code, !state.hasReachedMax to 

return ListView.builder(
            itemBuilder: (BuildContext context, int index) {
              return index >= state.posts.length && !state.hasReachedMax // i added this 
                  ? BottomLoader()
                  : PostWidget(post: state.posts[index]);
            },
            itemCount: state.hasReachedMax
                ? state.posts.length
                : state.posts.length + 1,
            controller: _scrollController,
          );
 and everything works fine, however maybe @felangel has a better way to solve this.

**Comment by cemanganas** [comment]
i added this code, !state.hasReachedMax to 

return ListView.builder(
            itemBuilder: (BuildContext context, int index) {
              return index >= state.posts.length && !state.hasReachedMax // i added this 
                  ? BottomLoader()
                  : PostWidget(post: state.posts[index]);
            },
            itemCount: state.hasReachedMax
                ? state.posts.length
                : state.posts.length + 1,
            controller: _scrollController,
          );
 and everything works fine, however i am sure @felangel has a better way to solve this.

**Comment by cemanganas** [comment]
i added this code, !state.hasReachedMax to 

return ListView.builder(
            itemBuilder: (BuildContext context, int index) {
              return index >= state.posts.length && !state.hasReachedMax // i added this 
                  ? BottomLoader()
                  : PostWidget(post: state.posts[index]);
            },
            itemCount: state.hasReachedMax
                ? state.posts.length
                : state.posts.length + 1,
            controller: _scrollController,
          );
 and everything works fine, and so sure @felangel has a better way to solve this.

**Comment by jmayobres** [comment]
Same for me.TY
