### ISSUE TITLE
Question regarding bloc

### ISSUE THREAD

**Issue by eliudio** [felangel/bloc#1860]
Hi Felix. Great work man. Thanks for contributing!

I've been using bloc in several projects but I think I'm possibly only scratching its surface. I always use the same pattern which is what you've documented in several places, e.g. https://medium.com/flutter-community/flutter-todos-tutorial-with-flutter-bloc-d9dd833f9df3

Today I like to use a nested bloc. Let me explain.

I have XBloc, 
- which extends Bloc<XEvent, XState> 
- which is used within XWidget
- which extends Widget

Inside XWidget (widget 1) I have some nesting of widgets which all require / could require XState (state 1) info,  I can do so using BlocProvider.of<BlocBloc>(context).state. This is all within my knowledge and standard use of bloc.

Now comes the question: inside XWidget I want the ability to create another XWidget (widget 2). This other XWidget has another XBloc with its own XState (state 2). If inside this nested XWidget I retrieve BlocProvider.of<BlocBloc>(context).state, then can I be guarenteed this will be state 2, not state 1?

thanks,

Eliud

**Comment by felangel** [comment]
Hi @eliudio 👋
Thanks for opening an issue and for the positive feedback!

Regarding your question, yes BlocProvider.of will always return the nearest bloc so in the nested case you will always get the second bloc instance 👍

Hope that helps!

**Comment by eliudio** [comment]
Thanks
