### ISSUE TITLE
Cubit - consider using StackTrace to log the calling method ?

### ISSUE THREAD

**Issue by benoitjadinon** [felangel/bloc#1861]
The lack of logging info about the 'event' (the method) that called `emit` is documented as a downside of Cubit when compared to Bloc,
but have you considered using `StackTrace.current` (or at least have an optional argument) inside of Cubit.emit ?

```dart
  void emit(State state, [String methodName]) {
    (...)
    final transition = Transition(
        currentState: state,
        event: methodName ?? StackTrace.current.toString().split('\n')[1],
        nextState: nextState,
      )
```
that currently prints `(...)event: #1      CounterCubit.increment (file:///Users/ben/Workspaces/Flutter/bloc/packages/bloc/example/main.dart:100:23)(...)` 
but could be further parsed to look like `CounterCubit.increment():100:23`

this would have to be benchmarked, but it would deprecate the Change class, and there would be one less downside to Cubit ;-)

**Comment by felangel** [comment]
Hi @benoitjadinon 👋
Thanks for opening an issue!

I did originally look into this but it performs very poorly and does not work in release builds afaik so I don’t think it’s a valid solution. Thanks for the suggestion though and let me know what you think 👍

**Comment by benoitjadinon** [comment]
right, I just remembered it only works in debug mode too, sorry.
what about the optional argument ? wouldn't cost much, and if people don't add it, it just doesn't log it ?

**Comment by narcodico** [comment]
Hi @benoitjadinon 👋

I personally feel that people should be using cubits when they don't care about the source of change, but only about the end result, which is the state. If you care about who triggered those states then bloc should be used instead.

**Comment by felangel** [comment]
I agree with @narcodico. Introducing an optional argument for the method name will introduce a lot of additional complexity -- will the `Change` class also need an optional `event`? Then what will be the difference between `Transition` and `Change`? Should we combine them at that point? I think it introduces more problems than it solves, unfortunately 😞
