### ISSUE TITLE
Pls help to implement this feature

### ISSUE THREAD

**Issue by samsheldin** [felangel/bloc#1866]
[cart details.txt](https://github.com/felangel/bloc/files/5445978/cart.details.txt)

hi guys this  is a json of a shopping cart app
in each object of the list there is a discount start and discount end

so i know know how to make the price change based on the timing for individual products,,,

but logic looks a bit confusing when i am totalling the price and displaying it in ui,,,

for eg    10 + 5(discounted price) + 10   + 5(discounted price)  + 5(discounted price) 

total price  35 

now suppose after  5 min user is still on the screen  discount on one of the products end 

it looks like this 

    10 + 10  + 10   + 5(discounted price)  + 5(discounted price) 

total price 40..

So dislpaying the discount individally is alright,,, but as you can see how can i do the total price based on differnt discount start time and discount end time  for each unique product

**Comment by felangel** [comment]
Hi @samsheldin 👋 
Thanks for opening an issue!

Closing this because it's not related to the bloc library but feel free to repost on stackoverflow or in the offtopic channel of the discord server 👍

**Comment by samsheldin** [comment]
Hi this the ui I am using  which is in bloc @felangel 

[cart.txt](https://github.com/felangel/bloc/files/5449348/cart.txt)
