### ISSUE TITLE
How to implement dyanmic price changes in bloc

### ISSUE THREAD

**Issue by samsheldin** [felangel/bloc#1868]
[cart.txt](https://github.com/felangel/bloc/files/5457419/cart.txt)
hi guys this is a json of a shopping cart app
in each object of the list there is a discount start and discount end

so i know know how to make the price change based on the timing for individual products,,,

but logic looks a bit confusing when i am totalling the price and displaying it in ui,,,

for eg 10 + 5(discounted price) + 10 + 5(discounted price) + 5(discounted price)

total price 35

now suppose after 5 min user is still on the screen discount on one of the products end

it looks like this

10 + 10  + 10   + 5(discounted price)  + 5(discounted price) 

total price 40..

So dislpaying the discount individally is alright,,, but as you can see how can i do the total price based on differnt discount start time and discount end time for each unique product

this is the ui which i am implementing this
[cart details.txt](https://github.com/felangel/bloc/files/5457423/cart.details.txt)

**Comment by felangel** [comment]
Hi @samsheldin 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which illustrates the issue? Text files aren't very helpful and it'd be much easier to help if you create a public github repository with a sample app that can be run and illustrates the issue.

**Comment by samsheldin** [comment]
Sure wiill do so

**Comment by samsheldin** [comment]
@felangel   Hi sir check this out,,, i have added a json for you to easily manipulate discount of each item                                                              ...https://github.com/samsheldin/checkout

**Comment by felangel** [comment]
Hey @samsheldin sorry for the delayed response! You should be able to use a [Timer.periodic](https://api.dart.dev/stable/2.10.5/dart-async/Timer/Timer.periodic.html) within the bloc and whenever the desired time passes (for example 5 mins) you can add a new event to the bloc internally (like `DiscountUpdated`) which recalculates the prices and yields an updated state. Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation. Also, if you haven't already consider [joining the bloc discord server](https://discord.gg/Hc5KD3g) to get more real-time help from myself and other members of the community 👍
