### ISSUE TITLE
Bloc not init when call BlocProvider ?

### ISSUE THREAD

**Issue by danbn-100295** [felangel/bloc#1871]
Hey everyone
I try implement Bloc but i got unexpect bug,Please help me !
Here is how i implement 
<img width="457" alt="Screen Shot 2020-10-30 at 16 52 45" src="https://user-images.githubusercontent.com/61224981/97691214-a6452080-1ad0-11eb-8182-e110cbac942f.png">
Here is my main.dart
<img width="476" alt="Screen Shot 2020-10-30 at 16 53 27" src="https://user-images.githubusercontent.com/61224981/97691236-ae04c500-1ad0-11eb-98e4-a8c7d626a5d4.png">
Here is my bloc.dart
I try print in constructor of bloc but it not work

**Comment by felangel** [comment]
Hi @danbn-100295 👋
Thanks for opening an issue!

BlocProviders are lazy by default and only call create when the bloc is accessed. If you want them to be created immediately you can set lazy: false.

```dart
BlocProvider(
  lazy: false,
  create: ...
)
```

Hope that helps 👍
