### ISSUE TITLE
Using two BLoCs in same page and passing first BLoC's state in second BLoC

### ISSUE THREAD

**Issue by CherukuriSiva** [felangel/bloc#1872]
I have been learning about Bloc Pattern in Flutter for a few days.

I have a page where I need to generate OTP and validate it.

There are two APIs(generateOtp, validateOtp) two implement this functionality.

In the generateOtp API response, I need to save one key i.e uniqueIdentifier.

Then I need to pass the above uniqueIdentifier and Otp value(User entered) to the validateOtp API.

I have created two separate BLoCs... generateOtpBloc, validateOtpBloc.

Using MultiBLoC Provider I am using these two BLoCs.

                            Navigator.of(context).push(
                              MaterialPageRoute<LandingPage>(
                                builder: (_) => MultiBlocProvider(
                                  providers: [
                                    BlocProvider<GenerateOtpBloc>(
                                      create: (context) => GenerateOtpBloc(GenerateOtpInitial())
                                    ),
                                    BlocProvider<ValidateOtpBloc>(
                                      create: (context) => ValidateOtpBloc(ValidateOtpInitial())
                                    )
                                  ],
                                  child: OtpPage(),
                                ),
                              ),
                            );
I am able to invoke APIs and get the API responses in my UI page.
But how to save the uniqueIdentifier value which I get in the generateOtp and how to pass this uniqueIdentifier in the second API?

I thought of using setState() to set the state of uniqueIdentifier. But I'm receiving an error.

          child: BlocBuilder<GenerateOtpBloc, GenerateOtpState>(
            builder: (context, state) {
              if (state is GenerateOtpLoading) {
                print("**********GenerateOtpLoading*************");

                return buildLoading();
              } else if (state is GenerateOtpLoaded) {
                print("**********GenerateOtpLoaded*************");

                ***//But Im getting error here.***
                ***setState(() {
                  uniqueIdentifier: state.uniqueIdentifier
                });***

                return buildGenerateOtpWidget(context, state.generateOtpRes);
              } else {
                print("**********Else*************");
                print(state);
              }
            },
          ),
        ),
Both generateOtp and validateOtp requests and responses are completely different... that is why I used two different BLoCs.

Please suggest to me the best way to handle this?

**Comment by felangel** [comment]
Hi @CherukuriSiva 👋 
Thanks for opening an issue!

If you want to have bloc-to-bloc communication you can use a BlocListener to notify the blocs of updates:

```dart
BlocListener<GenerateOtpBloc, GenerateOtpState>(
  listener: (context, state) {
    if (state is GenerateOtpLoaded) {
      context.bloc<ValidateOtpBloc>().add(OtpGenerated(state.uniqueIdentifier));
    }
  },
  child: ...
);
```

Then you have use a BlocBuilder in response to the `ValidateOtpBloc` to update the UI accordingly 👍 

Hope that helps! Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄
