### ISSUE TITLE
Cubit Multiple Emits - miss understood

### ISSUE THREAD

**Issue by LloydRBS** [felangel/bloc#1873]
Good Day

My Question: Can you keep built UI that was built by a state when another state is called

Please correct me if I'm using the cubit pattern wrong. I have a unique example I'm trying to solve. I have the cubit set up and its working as per documentation.

I have a screen where I have a horizontal list that is returned through cubit. Then based on the horizontal list returned if you click one of the items the cubit fetches a second list to display vertically underneath the horizontal list.

```
var _responseCategories = await _repository.postGetRootCategories();
      emit(ShowCategories(state, _responseCategories));
      var _responseCategoryItems = await _repository.postGetCategoryItems(_responseCategories[0].id);
      emit(ShowCategoriesItems(state, _responseCategoryItems));
```
The ui has a bloc builder and processes the two states but when the one state is changed the UI for the first built state is then not there I understand why this happens but is there a way to stop it until I emit the state again. The UI decodes the states in a builder as follows:

```
return Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                if (state is ShowCategories) buildCategories(context, state),
                state is ShowCategoriesItems
                    ? Expanded(child: buildMenuItems(context, state))
                    : SizedBox.shrink(), //getMenuList(_activeSelection)),
             
              ],
            );
```
If im using this wrong thats understandable I just want to know if there is a better solution to this to solve the problem as the category items are different per category and i don't need to fetch the categories every time the state changes.

The app is essentially a menu. The horizontal section is the categories of the menu 'I only need to load them once or when I emit the state again' and the vertical section is the items 'I need to load them when the user selects a category'. The items are different per category but the categories never change unless set by the server or a scenario where i invoke an emit again.

Thanks

**Comment by felangel** [comment]
Hi @LloydRBS 👋 
Thanks for opening an issue!

If you want to have common information present across multiple states I would recommend refactoring your state to be a single concrete class rather than an abstract base class with multiple concrete subclasses.

You can take a look at [fluttersaurus](https://github.com/felangel/fluttersaurus/blob/master/lib/synonyms/cubit/synonyms_state.dart) for an example. Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
