### ISSUE TITLE
Using streams in mapEventToState (again)

### ISSUE THREAD

**Issue by antonovttm** [felangel/bloc#1877]
Hi. I'm having an issue with yielding states in a stream subscription. I think I have the same issue as this one #112 but unfortunately the PR with the suggested solution is no longer available.

What I'm trying to do is yield directly from a stream subscription with listen() without adding an extra event and yielding an extra final state. I have a few different final states and I wanted to avoid having 2 events and 2 states for each.

I have something very similar to Felix's example using [geolocator ](https://gist.github.com/felangel/68e2fd89d56de8866935e3f058d6e81b)but, instead of this:

```dart
@override
  Stream<LocationState> mapEventToState(
    LocationEvent event,
  ) async* {
    if (event is LocationStarted) {
      yield LocationLoadInProgress();
      _locationSubscription?.cancel();
      _locationSubscription = _geolocator.getPositionStream().listen(
            (Position position) => add(
              LocationChanged(position: position),
            ),
          );
    } else if (event is LocationChanged) {
      yield LocationLoadSuccess(position: event.position);
    }
  }
```

I wanted to do this:

```dart
  @override
  Stream<LocationState> mapEventToState(
    LocationEvent event,
  ) async* {
    if (event is LocationStarted) {
      yield LocationLoadInProgress();
      _locationSubscription?.cancel();
      _locationSubscription =
          _geolocator.getPositionStream().listen((Position position) {
        print(position);
        return LocationLoadSuccess(position: position);
      });
    }
  }
```

I can print the position object, but I cannot find a wait to return or yield the state from the subscription. I can make it work with "await for", but cancelling those subscriptions is a pita. 

Is there a way of achieving this?

**Comment by felangel** [comment]
Hi @antonovttm 👋 
Thanks for opening an issue!

I would highly recommend going with the initial approach of adding an event in response to new data from the stream because it will allow the bloc to react asynchronously and without blocking subsequent events. You can make the `LocationChanged` event private so that it can only be used within the bloc itself.

Alternatively, you can use a `Cubit` for this to achieve the desired effect

```dart
class LocationCubit extends Cubit<LocationState> {
  LocationCubit(this._geolocator) : super(LocationLoadInitial());
  
  final Geolocator _geolocator;
  StreamSubscription _locationSubscription;

  void locationStarted() {
    _locationSubscription?.cancel();
    _locationSubscription = _geolocator.getPositionStream().listen((Position position) {
      emit(LocationLoadSuccess(position: position);
    });
  }
}
```

Let me know if that helps 👍

**Comment by antonovttm** [comment]
Hi @felangel 

Thanks for the help. Really appreciate your work on building flutter bloc and helping out the community.

Making LocationChanged private is a great idea. I will do that and work with the extra event.

I used cubits on my forms but when I did that I was still very green on applying the bloc pattern, so I still have to go back to that code. I went with blocs here because I'm using a mixture of streams and real time data. Would you agree that blocs are the favourable option when working with data streams?

**Comment by felangel** [comment]
No problem! You can check out the [documentation](https://bloclibrary.dev/#/coreconcepts?id=cubit-vs-bloc) for more information about bloc vs cubit 👍
