### ISSUE TITLE
Called by a context that does not contain a Cubit of type ...

### ISSUE THREAD

**Issue by CodeCakePie** [felangel/bloc#1883]
Hello,

maybe someone could help me with my problem...

I have a Bloc (CreateRecipeBloc) which should be accessable within a certain scope (inside the CreateRecipeForm).

```dart
return Scaffold(
      appBar: AppBar(
        title: Text('Neues Rezept'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(12),
        child: BlocProvider<CreateRecipeBloc>(
          create: (context) {
            return CreateRecipeBloc();
          },
          child: CreateRecipeForm(),
        ),
      ),
    );
```
Inside of the CreateRecipeForm I create another Widget (_ChooseEquipment) which contains a button that routes to another Widget, because it's a kinda complicated select:

```dart
class _ChooseEquipment extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CardButton(
      text: 'Benötigtest Equipment auswählen',
      icon: Icon(Icons.kitchen),
      onTap: () => Navigator.of(context).push(
        EquipmentSelection.route(),
      ),
    );
  }
```
As you can see I'm use the same strategie (static route method in the widget) that is used in the [Login Tutorial](https://bloclibrary.dev/#/flutterlogintutorial).

Inside of EquipmentSelection widget i cannot access the CreateRecipeBloc anymore and i don't understand why...
The widget is a child of the BlocProvider, not a direct one but that shouln't be a problem. I am able to access the AuthenticationBloc which i provided globally in the app.

```dart
class EquipmentSelection extends StatefulWidget {
  static Route route() {
    return PageRouteBuilder(
      pageBuilder: (c, a1, a2) => EquipmentSelection(),
      transitionsBuilder: (c, anim, a2, child) => ScaleTransition(
        alignment: Alignment(-0, 0),
        scale: Tween(begin: 0.0, end: 1.0).animate(
            CurvedAnimation(parent: anim, curve: Curves.fastOutSlowIn)),
        child: child,
      ),
      transitionDuration: Duration(milliseconds: 200),
    );
  }

  @override
  _EquipmentSelectionState createState() => _EquipmentSelectionState();
}

class _EquipmentSelectionState extends State<EquipmentSelection> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Benötigtes Equipment'),
        actions: [IconButton(icon: Icon(Icons.search), onPressed: null)],
      ),
      body: BlocBuilder<CreateRecipeBloc, CreateRecipeState>(
        builder: (context, state) {
          return GridView.count(
            crossAxisCount: 2,
            padding: const EdgeInsets.all(20),
            children: List.generate(
              100,
              (index) {
                return CheckmarkSelectable(
                  child: Container(
                    child: Text('Item '),
                  ),
                );
              },
            ),
          );
        },
      ),
    );
  }
}

```

I hope I was able to express my problem understandable 😄  It would be great if someone could explain why it's not working.

Thank you!

**Comment by felangel** [comment]
Hi @CodeCakePie 👋 
Thanks for opening an issue!

When routing to a new page you will need to use `BlocProvider.value` to provide the existing bloc to the new route. You can check out the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=anonymous-route-access) for more information/examples.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
