### ISSUE TITLE
Show Snackbar after clicked on Favourite button (question)

### ISSUE THREAD

**Issue by pavankumarkatakam** [felangel/bloc#189]
Hi, this is just a question of how to use this library for flutter for a provided scenario. I have already developed a screen with List of Products with states `ProductsLoaded`, `ProductsLoading` events  `LoadProducts`, but now i want to give a favourite IconButton if it is clicked an http req will be sent and server will response with an auto generated message now i need to show that message in the same page of list of products as a snackbar. Now im trying to keep another event `FavouriteProduct` and dispatch from pressed of `IconButton` and how to get the message from response because the list is already loading via `ProductsLoaded`. 
I have seen many issues and didn't find the situation where two states are emitted at the same time (for a single dispatched event.)

**Comment by felangel** [comment]
Hi @pavankumarkatakam 👋 

In this case, I would recommend creating a separate bloc for managing favorites. That way the favorites feature is independent of the loading of products. Hope that helps 👍

**Comment by pavankumarkatakam** [comment]
Even though favorites part in second block still I need to show them in main product s list with done heart icon .

**Comment by pavankumarkatakam** [comment]
May be second block is used when I need to show all his favorite product s at a time. But still I need to give button for making favorite in main products page as indicated I need to show toast as well when clicked

**Comment by pavankumarkatakam** [comment]
I have seen the login example but in that case form is returned in any state. But in my case I need to show snackbar and products list at a time

**Comment by pavankumarkatakam** [comment]
I think i need to add some message in the the ProductsLoaded state i think so that i can show products as well as snackbar like below

```
class ProductsLoaded extends CoursesState {
  final List<Product> products;
  final String message;

  CoursesLoaded([this.products = const [], this.message=""]) : super([products, message]);

  @override
  String toString() => 'ProductsLoaded { products: $products }';
}
```

Doing this I can achieve my requirement but the code is not organized i think, can any one tell me the better way.

**Comment by felangel** [comment]
@pavankumarkatakam I think that approach is actually fine for your use-case. Why do you feel the code is not organized?

**Comment by iammart** [comment]
Hi @felangel are you to expand on this a little more please?

I think what @pavankumarkatakam is trying to do is similar to myself, only I seem to be going around in circles. I have a list of products which loads the details. On this details page the user can like the product.

However when returning to the list, it needs to know what product was liked without having to refresh the data. I guess it's definitely a situation of communication between blocs - currently I have three

- ProductsBloc
- ProductBloc
- FavouriteBloc

Thanks in advance for any direction you give :thumbsup:

**Comment by felangel** [comment]
@iammart are you able to share a link to your implementation? It would be much easier for me to help if I can run your app locally and see what you're having trouble with. Thanks! 👍

**Comment by pavankumarkatakam** [comment]
Im not using bloc package, i feel there are more constraints to follow to use this package, Im using general bloc pattern with own Behavior and Pusblish subjects from RxDart
