### ISSUE TITLE
BlocProvider from context

### ISSUE THREAD

**Issue by mikededo** [felangel/bloc#1896]
The method `bloc` from `BlocProvider` has been deprecated and we should use `watch` or `read` instead. However, this changes have not been made in the documentation.

Is it because you will add the new functions in the `7.0.0` version? If not, should the documentation be updated? 🤔

**Comment by felangel** [comment]
Hi @mikededo 👋
Thanks for opening an issue!

Can you please let me know what documentation hasn’t been updated? I tried to update all references and examples accordingly.

**Comment by mikededo** [comment]
Sure.

![Documentation image](https://user-images.githubusercontent.com/48334745/98452425-8c9a7d80-214f-11eb-9ea3-907101ff87a0.png)

I have not been much active with Flutter lately and when looking over an old project I found that `context.bloc` is deprecated. So I came to the docs and found this. Maybe I'm not looking in the right place.

**Comment by felangel** [comment]
I think maybe you are looking at a cached version. Can you try refreshing the page/clearing the cache?

**Comment by mikededo** [comment]
That solved it 😅
