### ISSUE TITLE
Allow user to force emit a new state

### ISSUE THREAD

**Issue by jinyus** [felangel/bloc#1899]
**Is your feature request related to a problem? Please describe.**
A new state will not be emitted if the previous_state == new_state. While this is usually the desired behavior. This doesn't work when I am using the super_enum package (https://pub.dev/packages/super_enum) to represent my different states. Adding this option doesn't do too much harm and it gives the user mode control of the behavior of the cubit.

**Describe the solution you'd like**
Allow force emitting a state through an optional parameter in the emit method.

**Comment by felangel** [comment]
Hi @jinyus 👋
Thanks so much for opening an issue!

Can you please provide a link to a sample app which illustrates the issue you’re facing? Thanks 🙏

**Comment by jinyus** [comment]
I am making the example code and I want to know when emit has fired...does the onChange in BlocObserver indicates when a state has been emitted?

**Comment by felangel** [comment]
Yup onChange is called when a new state is emitted 👍

**Comment by jinyus** [comment]
here is the example code: https://github.com/jinyus/cubit_super_enum_sample

**Comment by felangel** [comment]
Hi @jinyus this is because you are mutating the state rather than emitting a new instance. 

I modified

```dart
var currentMessages = s.messages;
```

to

```dart
final currentMessages = List.of(s.messages);
```

and that resulted in:

```sh
$ dart lib/main.dart
lib/main.dart: Warning: Interpreting this as package URI, 'package:cubit_superenum_sample/main.dart'.
onChange -- cubit: LoggerCubit, change: Change { currentState: Initial(), nextState: Loaded(messages: [hello 1]) }
onChange -- cubit: LoggerCubit, change: Change { currentState: Loaded(messages: [hello 1]), nextState: Loaded(messages: [hello 1, hello 2]) }
onChange -- cubit: LoggerCubit, change: Change { currentState: Loaded(messages: [hello 1, hello 2]), nextState: Loaded(messages: [hello 1, hello 2, hello 3]) }
onChange -- cubit: LoggerCubit, change: Change { currentState: Loaded(messages: [hello 1, hello 2, hello 3]), nextState: Loaded(messages: [hello 1, hello 2, hello 3, hello 4]) }
```

Hope that helps 👍

**Comment by jinyus** [comment]
Thanks @felangel , works as expected now.

**Comment by jinyus** [comment]
Hello,
I would like to reopen this issue. 

There is a memory usage issue when dealing with a list of large objects. It would be nice to be able to modify the list instead of allocating a new list when adding items.

**Comment by felangel** [comment]
> Hello, I would like to reopen this issue.
> 
> There is a memory usage issue when dealing with a list of large objects. It would be nice to be able to modify the list instead of allocating a new list when adding items.

Can you provide a reproduction sample that illustrates the issue you’re facing? You can always override == to determine when a new state should be emitted. The only thing bloc checks is that the current state != the emitted state.

**Comment by jinyus** [comment]
We have a specific usecase where the issue came up, though it was solved with overriding ==, I think adding the ability to skip the equality check would be useful.

**Comment by felangel** [comment]
> We have a specific usecase where the issue came up, though it was solved with overriding ==, I think adding the ability to skip the equality check would be useful.

I really prefer to leave it as is because the same state being emitted multiple times should not trigger a state change. It’s up to you as a developer to define the state and you can implement it however you’d like (you can even create a mixin which returns always returns false for ==) and mix it into whatever states have that requirement.
