### ISSUE TITLE
Transform Example

### ISSUE THREAD

**Issue by rsnider19** [felangel/bloc#19]
Can you please provide an example of overriding `transform`? Specifically debouncing a certain event (e.g. Search), but not other events in the bloc? Thanks!

**Comment by felangel** [comment]
Hi @rsnider19 if we use the `CounterBloc` as an example you can do something like:

```dart
@override
  Stream<CounterEvent> transform(Stream<CounterEvent> events) {
    final observableStream = events as Observable<CounterEvent>;
    final nonDebounceStream = events.where((event) {
      return (event is! Search);
    }) as Observable<CounterEvent>;
    final debounceStream = (observableStream).where((event) {
      return (event is Search);
    }).debounce(Duration(milliseconds: 300));

    return nonDebounceStream.mergeWith([debounceStream]);
  }
```

Essentially, in the transform override you have access to the raw `Stream<Event>` and you can do whatever manipulation/transformation and return the new `Stream<Event>` which will be used to `mapEventToState`. 

Let me know if that makes sense or if you have other questions.

**Comment by felangel** [comment]
Closing this for now but feel free to comment with any additional questions and I'll reopen it 👍

**Comment by rsnider19** [comment]
Worked perfect! Thanks!
