### ISSUE TITLE
What is the correct way to test

### ISSUE THREAD

**Issue by basketball-ico** [felangel/bloc#190]
Hello,
For example I have `BlocA`  `BlocB` `BlocC` `BlocD`

```dart
final blocD = BlocD();
final blocC = BlocC();
final blocB = BlocB(blocC, blocD);
final blocA = BlocA(blocB);
```
The `BlocA` dispatch `Events` to `BlocB`
The `BlocB` dispatch `Events` to `BlocC` and `BlocD`

I make Unit test for all Blocs mocking all bloc dependencies, and work fine for each bloc.

How can I make integration test for example to ensure that `BlocA` work?

Because for example when `BlocA` dispatch event to `BlocB` and after `BlocB` emits events to `BlocC` or `BlocD` I want to ensure that in this moment all `Blocs` have the expected state.

But I don't know how to do that,

Thanks

**Comment by felangel** [comment]
Hey @basketball-ico 👋 

I think that if you've unit tested each bloc fully then you can just do the end-to-end testing using widget and integration tests. You should be able to interact with the UI in widget/integration tests in order to trigger dispatches of events and then expect that the ui has updated based on the bloc state.

Hope that helps 👍

**Comment by basketball-ico** [comment]
Thank :D

But now I have more doubts before make integration tests

I see you login test an in this [line](https://github.com/felangel/bloc/blob/66d07fa382cc5de9af48061b1df50240eac8c245/examples/flutter_login/test/login/login_bloc_test.dart#L52)

you use `verify` for ensure that this bloc dispatch a event to the other bloc. 

1) So in my example, I need to make the same?
>The BlocB dispatch Events to BlocC and BlocD

Currently I am omitting this step, and assuming that the dispatch occur, but I think is better `verify` like you :D,  I am rookie in testing :(


But in my case for example `BlocB. dispatch(SomeEvent())`  and when this event is call I dispatch `EventInC` to `BlocC`, but in the `BlocB` I no change the state.
So I can't use
```dart 
expectLater(
        loginBloc.state,
        emitsInOrder(expectedResponse),
      ).then((_) {
        verify(authenticationBloc.dispatch(LoggedIn(token: 'token'))).called(1);
      });
```
2) How can I `verify` that I dispatch this `event` when the state not change.?

3) So If a `BlocA` have a dependency of other `BlocB`, If I fully test `BlocB`, and I test `BlocA` and in the case that `BlocA` call `BlocB` I use `verify`, I can be confident that this `Blocs` are fully tested ? or I need to do other step?

Again, sorry I am rookie in testing. 🙁

Thanks 🤗🤗🤗

**Comment by felangel** [comment]
@basketball-ico 

1. You can use mockito to mock BlocC like:

```dart
class MockBlocC extends Mock implements BlocC {}
```

Then you can inject the `MockBlocC` into `BlocC` like:

```dart
blocC = MockBlocC();
blocB = BlocB(blocC);
```

and then you can verify that `EventC` was dispatched to `BlocC`.

3. I think so especially if you also write widget tests and integration tests to test the functionality end to end.

**Comment by basketball-ico** [comment]
Thanks :D,

But, when I use verify and **not update the state** I get this error
```
Exception has occurred.
TestFailure (No matching calls (actually, no calls at all).
```
For example in your LoginBloc I add
```dart
class LoginWithDefaultToken extends LoginEvent {}
```
and in the `mapEventToState`
```dart
...
  if (event is LoginWithDefaultToken) {
    authenticationBloc.dispatch(LoggedIn(token: 'defaultToken'));
  }
...
```
and in the test file
```dart
...
  group('LoginWithDefaultToken', () {
    test('Emit default token', () {
      verify(authenticationBloc.dispatch(LoggedIn(token: 'token'))).called(1);
      loginBloc.dispatch(LoginWithDefaultToken());
     // or call verify after dispatch also throw an exception
     // verify(authenticationBloc.dispatch(LoggedIn(token: 'token'))).called(1);
    });
  });
...
```
I have the same `Exception`  :(

How do you `verify` this? 

Thanks

**Comment by felangel** [comment]
@basketball-ico you need to wait before verifying because the dispatch is async.

```dart
group('LoginWithDefaultToken', () {
    test('Emit default token', () {
      expectLater(authenticationBloc.state, emitsInOrder(expectedResponse))
      .then((_) {
        verify(authenticationBloc.dispatch(LoggedIn(token: 'token'))).called(1);
      });      
      loginBloc.dispatch(LoginWithDefaultToken());
    });
  });
```

**Comment by basketball-ico** [comment]
@felangel hello and thanks again 🤗
What is the `expectedResponse`?
because `authenticationBloc` is a Mock `authenticationBloc = MockAuthenticationBloc();`

**Comment by felangel** [comment]
@basketball-ico Now I'm confused haha 😛 
If `authenticationBloc` is a mock then why are you testing it?

**Comment by basketball-ico** [comment]
@felangel Thanks
it work if `expectedResponse = [LoginInitial()]` but why not work if `expectedResponse = []`
because This dispatch not change the state?

like you dispose test
```dart
  test('dispose does not emit new states', () {
    expectLater(
      loginBloc.state,
      emitsInOrder([]),
    );
    loginBloc.dispose();
  });
```

**Comment by felangel** [comment]
@basketball-ico where did you see that dispose test? It’s correct to have it emit LoginInitial because that is the initialState before any events have been dispatched.

**Comment by basketball-ico** [comment]
I see [here](https://github.com/felangel/bloc/blob/e4ee3ed677ec5a52b7247e269ac96711174a970c/examples/flutter_login/test/login/login_bloc_test.dart#L31)

**Comment by basketball-ico** [comment]
Thanks again,

For example in your [Form Bloc](https://github.com/felangel/bloc/blob/e4ee3ed677ec5a52b7247e269ac96711174a970c/examples/flutter_form_validation/lib/bloc/my_form_bloc.dart#L37) In `FormSubmitted` I replace with this
mapEventToState
```dart
if (event is FormSubmitted) {
      if (currentState.isFormValid){
           loginBloc.dispatch(LoginButtonPressed(
               username: currentState.email,
               password: currentState.password,
           ));
      }
    }
```
the next test work, but I want to know why I need to expect the last state again for use verify?
so the last state is emitted again?
```dart
import 'package:flutter_test/flutter_test.dart';
import 'package:flutter_form_validation/bloc/bloc.dart';
import 'package:mockito/mockito.dart';

class MockLoginBloc extends Mock implements LoginBloc {}

void main() {
  MyFormBloc myFormBloc;
  MockLoginBloc loginBloc;

  setUp(() {
    loginBloc = MockLoginBloc();
    myFormBloc = MyFormBloc(loginBloc);
  });

  test('FormSubmitted', () async {
    final email = 'example@domain.com';
    final password = 'Aa12345678';
    final expectedResponse = [
      MyFormState.initial(),
      MyFormState(
          email: email,
          isEmailValid: true,
          password: '',
          isPasswordValid: false,
          formSubmittedSuccessfully: false),
      MyFormState(
          email: email,
          isEmailValid: true,
          password: password,
          isPasswordValid: true,
          formSubmittedSuccessfully: false),
    ];

    myFormBloc.dispatch(EmailChanged(email: email));
    myFormBloc.dispatch(PasswordChanged(password: password));
    await expectLater(myFormBloc.state, emitsInOrder(expectedResponse));

    myFormBloc.dispatch(FormSubmitted());

    // Why the last state is emitted?

    await expectLater(
        myFormBloc.state,
        emitsInOrder([
          MyFormState(
              email: email,
              isEmailValid: true,
              password: password,
              isPasswordValid: true,
              formSubmittedSuccessfully: false),
        ]));

    verify(loginBloc.dispatch(LoginButtonPressed(
               username: email,
               password: password,
           ))).called(1);
  });
}

```

**Comment by felangel** [comment]
@basketball-ico thanks for catching this! I've updated the tests to assert that the initial state is emitted even on a dispose. 👍

**Comment by felangel** [comment]
@basketball-ico regarding your second question, the last state isn't emitted twice so you don't have to do that. It's just there so that you can make sure the last state change has occurred before verifying that dispatch was called. Hope that makes sense!

**Comment by basketball-ico** [comment]
@felangel  thanks again,
Sorry, I want to catch the concept. 🤗

So when I use 
```dart
expectLater(
        bloc.state,
        emitsInOrder(expectedResponse));
```
1) `bloc.state` emits the current state first?
this is a bloc behavior or a stream behavior?

2) The test that i show you in my before comment is correct? you said "the last state isn't emitted twice so you don't have to do that.", so I am confusing. but remember that I want to dispatch a event after the form is valid.

Thanks for your time.

**Comment by felangel** [comment]
@basketball-ico 

1. The `initialState` will always be the first state that is emitted.
2. You can have as many expectLaters as you want. That doesn't mean that the events are being emitted multiple times. Hope that helps 👍
