### ISSUE TITLE
Can you add support for intelij idea 2019.1

### ISSUE THREAD

**Issue by MichelMelhem** [felangel/bloc#191]

**Comment by felangel** [comment]
Hey @michelmelhem 👋 

Does the current IntelliJ plugin not work? I’m not super familiar with IntelliJ plugins but my understanding was the plugin would be universal. Thanks!

**Comment by MichelMelhem** [comment]
As you can see an this screenshot:
![image](https://user-images.githubusercontent.com/25546627/55476723-a12f9f00-5617-11e9-919e-79346a031ce1.png)

The last version of you plugin, the 1.1 is compactible just with intelij idea  2018.2.7 but since then a new version of intelij idea was relased the 2019.1.
So you need to recompile you app and specify that your plugin is compactible with intelij idea 2019.1

**Comment by felangel** [comment]
Ah got it! We’ll try to have it updated ASAP. Thanks for bringing this up 👍

**Comment by MichelMelhem** [comment]
Ok nice

**Comment by jorgecoca** [comment]
I just submitted a new release, and now it is pending of approval by JetBrains:

<img width="890" alt="Screen Shot 2019-04-05 at 9 21 07 AM" src="https://user-images.githubusercontent.com/3237451/55634490-3cde1e00-5784-11e9-8dd7-becd9cb9c1e5.png">

**Comment by jorgecoca** [comment]
New version has been released and approved here: https://plugins.jetbrains.com/plugin/12129-bloc-code-generator

Closing this issue. Thank you everyone!
