### ISSUE TITLE
Missing tests for the Timer example

### ISSUE THREAD

**Issue by albertodev01** [felangel/bloc#1910]
I see that there is no `test` folder in the [examples/flutter_timer](https://github.com/felangel/bloc/tree/master/examples/flutter_timer) example.

I was looking for it because I wanted to see how to test a series of states emitted in sequence by a periodic stream. Can it be added please? 😁

**Comment by felangel** [comment]
Hi @albertodev01 👋 
Thanks for opening an issue!

As I revamp each example, I am ensuring that they are fully tested and I'll prioritize the timer example next 👍
