### ISSUE TITLE
Using Named Routes and passing an existing bloc to the new page

### ISSUE THREAD

**Issue by olivierbrand** [felangel/bloc#1911]
I am using onGenerateRoute in my main where I pass Blocs when I need to create them and use also The MultiBlocProvider for my MaterialApp to share a couple of blocs.
I have a route where I pass a RecommendationsRequestBloc:
` case BookRecommendationRequestPage.routeName:
      return PageTransition(
        //duration: Duration(seconds: 0),
        child: MultiBlocProvider(
          providers: [
            BlocProvider(create: (context) => RecommendationsRequestBloc()),
            BlocProvider(create: (context) => BookSearchBloc()),
            BlocProvider(create: (context) => RecommendationsBloc())
          ],
          child: RecommendationRequestPage(),
        ),
        type: PageTransitionType.rightToLeft,
        settings: settings,
      );`

The RecommendationRequestPage then offers the ability to navigate to a search page where I need to get access to the same instance of RecommendationsRequestBloc created above.

` case RecommendationRequestSearchPage.routeName:
      return PageTransition(
        //duration: Duration(seconds: 0),
        type: PageTransitionType.rightToLeft,
        child: MultiBlocProvider(
          providers: [
            BlocProvider(create: (context) => BookSearchBloc())
          ],
          child: RecommendationRequestSearchPage(),
        ),
        settings: settings,
      );`

So far the only way I found to pass the RecommendationsRequestBloc to the search screen is to pass it as an argument in the navigation code:

`Navigator.pushNamed(
                      context, RecommendationRequestSearchPage.routeName,
                      arguments:
                          BlocProvider.of<RecommendationsRequestBloc>(context))`

I then retrieve it in the Search screen and all works well BUT I would like to listen to some state changes and for this I have to use the listen method on the bloc instance in the didChangeDependencies:

`_recommendationsRequestBloc.listen((state) {`

BUT would be cleaner to use:

`BlocListener<RecommendationsRequestBloc, RecommendationsRequestState>` 

What is the best way to achieve a cleaner way?

**Comment by alfredobs97** [comment]
Hi! If you want to use the BlocListener, they access to the context to get the bloc, you must inject before in the widget tree to the last screen could find in the context.

**Comment by olivierbrand** [comment]
How do you do this? I guess I cannot use the onGenerateRoute but need to push to a route in my first screen?

**Comment by felangel** [comment]
Hi @olivierbrand 👋 
Thanks for opening an issue!

Have you taken a look at the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=named-route-access)? It covers how to handle providing/accessing blocs from named routes. Let me know if that helps 👍

**Comment by olivierbrand** [comment]
Let me look at it and will get back to you with questions if any. Thanks

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍

**Comment by olivierbrand** [comment]
@felangel I have looked at the recipes, especially at the AppRouter which matches what I want to do.

In your recipe, you are creating CounterBloc which acts as the global access method in a way.

In my case I have 2 routes:

- BookRecommendationRequestPage.routeName: which needs to create a recommendationsRequestBloc instance every time it is called (the bloc is stateful and keeps an array in memory)
- searchBlocRoute which needs to use the same instance of recommendationsRequestBloc that was created by the parent route (recommendationsRequestRoute)

Once the recommendationsRequestRoute is discarded (the screen that was open by that route), the recommendationsRequestBloc should be discarded

Question can I do this:

`
RecommendationsRequestBloc _recommendationsRequestBloc; 
....

case BookRecommendationRequestPage.routeName:
    if(_recommendationsRequestBloc != null) {
          _recommendationsRequestBloc.close();
   }
   _recommendationsRequestBloc = RecommendationsRequestBloc();

   ... pass it to the screen with BlocProvider.value(
  

case RecommendationRequestSearchPage.routeName:
  ... pass the previously create bloc using  BlocProvider.value(

`

Questions:
1- I assume that a bloc can keep a state
2- Is the above correct?
3- Would it be possible to make all of this transparent by having flutter_bloc handling cascading blocs upon navigation
