### ISSUE TITLE
Best practice on showing loading indicator in bloc listener

### ISSUE THREAD

**Issue by Babwenbiber** [felangel/bloc#1919]
I couldn't find an example for that in the repo.
But I have several use cases, where I don't have a bloc builder, but only a bloc listener.
When I interact and e.g. press a button I trigger the LoadingState and want to show a loading dialog ON TOP of my current view.
I currently use the code above and always need to keep track of a isLoading variable in my view.
Are there better practices for this? (could only find this #1149 which doesn't provide code for the indicator)

```
body: BlocListener<MyBloc, MyState>(
  listener: (BuildContext context, MyState state) {
    if (state is MyStateLoading) {
      if (!loading) {
        LoadingDialog.show(context);
        loading = true;
      }
    } else {
      if (loading) {
        LoadingDialog.hide(context);
        loading = false;
      }
      //do some other listening actions
    }
  },
  child:...
```

this is my dialog. Note, that if I call hide when it is currently not shown, I pop my current view.
```
class LoadingDialog extends StatelessWidget {
  static void show(BuildContext context, {Key key}) => showDialog<void>(
        context: context,
        useRootNavigator: false,
        barrierDismissible: false,
        builder: (_) => LoadingDialog(key: key),
      ).then((_) => FocusScope.of(context).requestFocus(FocusNode()));

  static void hide(BuildContext context) => Navigator.pop(context);

  LoadingDialog({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async => false,
      child: Center(
        child: Card(
          child: Container(
            color: Colors.transparent,
            width: 80,
            height: 80,
            padding: EdgeInsets.all(12.0),
            child: CircularProgressIndicator(),
          ),
        ),
      ),
    );
  }
}
```

**Comment by alfredobs97** [comment]
Hi! Why do you need a local variable to keep the state of something is loading? "loading" variable is redundant, when you use the bloclistener and listen to loadingState, you only have to show dialog or whatever you want and nothing else, the state of loading represent itself.

`body: BlocListener<MyBloc, MyState>(
  listener: (BuildContext context, MyState state) {
    if (state is MyStateLoading) {
        LoadingDialog.show(context);
    }
      //do some other listening actions
  },`

**Comment by Babwenbiber** [comment]
@alfredobs97  
Lets say I have some states state1, state2, state3 and stateloading.
when I now have stateloading, then I can say LoadingDialog.show().
However, when I have state1,2,3 I have to close the dialog with LoadingDialog.hide().
If I don't close it, it will stay on top of my view.
So if I just say if state loading =>  show else hide, I have the problem explained in my post, which is that if the LoadingDialog is not active, it will pop the current view.

**Comment by alfredobs97** [comment]
Okay, I understand I think, in this case I would close the LoadingDialog in the other states, for example:  

```
listener: (BuildContext context, MyState state) {
    if (state is MyStateLoading) {
        LoadingDialog.show(context);
    }
   else {
       LoadingDialog.close();
   }
      //do some other listening actions
  },`
```

But, I recommend you to refactor this decision to avoid if/else or if you see fine, okay!

**Comment by Babwenbiber** [comment]
I still have the problem, that I need to keep track of a local variable.
With your recommendation I would close my current view if I switch from state 1 to state 2 because the LoadingDialog does pop the view and I have no LoadingDialog open yet.

**Comment by aaassseee** [comment]
@Babwenbiber Hi, I was facing the same problem before. Here is the solution I think is the best way to implement loading dialog. 

1. First, use Overlay instead of pushing dialog route. As far as I know BlocListener will keep listening after Navigator.of(context).push. So if you try to dismiss the dialog by using Navigator.of(context).pop while BlocListener start another LoadingDialog.show(context), that will dismiss the loading dialog wrongly. Moreover, if you are having complex navigation flow, managing the navigator is pain as hell as i had experienced.

2. Second, using show dialog for presenting loading dialog will lead to problems which was mentioned. Because Navigator.of(context).push is not affecting the layout immediately, so if you are calling hide dialog too fast will cause to pop current page rather than hiding the dialog.

Enough talking here is the acceptable way I think:
``` dart
class LoadingOverlay {
  OverlayEntry _overlay;

  LoadingOverlay();

  void show(BuildContext context) {
    if (_overlay == null) {
      _overlay = OverlayEntry(
        // replace with your own layout
        builder: (context) => ColoredBox(
          color: Color(0x80000000),
          child: Center(
            child: CircularProgressIndicator(
              valueColor: AlwaysStoppedAnimation(Colors.white),
            ),
          ),
        ),
      );
      Overlay.of(context).insert(_overlay);
    }
  }

  void hide() {
    if (_overlay != null) {
      _overlay.remove();
      _overlay = null;
    }
  }
}

class StatelessWidget extends StatelessWidget {
  final LoadingOverlay _loadingOverlay = LoadingOverlay();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: BlocListener<MyBloc, MyState>(
        listener: (context, state) {
          if (state is ServiceLoading) {
            _loadingOverlay.show(context);
          } else {
            _loadingOverlay.hide();
          }
        },
        child: Container(),
      ),
    );
  }
}
```

Hope it answers your question

**Comment by Babwenbiber** [comment]
Thanks a lot. The answer is a lot better than the navigation way.
The ideal way would have a static loading_overlay, but then you could not keep track of your state.
I am closing this issue, unless someone has a better way of doing it :)

**Comment by f-hoedl** [comment]
Hey everyone, 

hope this is still the best practice and so I have used it within an Hook Widget.
There I had the problem, since the state of the widget changes and it rebuild, the LoadingOverlay was always a new instance and I can not close it, since I call close on a new, not shown, LoadingOverlay.
My fix was to make the LoadingOverlay to an singleton so I always get the same instance and I can close it. 
Is this a good way, or is there a better way.

**Comment by aaassseee** [comment]
Hi, @f-hoedl. I am not too familiar with flutter_hooks package. However I think your issue is, putting the loading overlay with in the widget instead of page. If your loading overlay reconstruct after state changes, thats means you are using bloc in the wrong way. Because in normal loading overlay should not construct within build function and the page widget shouldn't rebuild after state changes.

I had used singleton instance before however faces with lots of problem. For example, pop until is hard to trigger the right number of hide loading overlay call. If loading overlay is inside the page widget, hide the right number of overlay with dispose will help on those situation.

I am still using this solution with production app. But I made some changes to make it more convenient to use.

Hope it answers your problem. If you still have any problem, please some example code. If you want the latest overlay code drop down a comment to let me know.

**Comment by sed1ka** [comment]
> @Babwenbiber Hi, I was facing the same problem before. Here is the solution I think is the best way to implement loading dialog.
> 
> 1. First, use Overlay instead of pushing dialog route. As far as I know BlocListener will keep listening after Navigator.of(context).push. So if you try to dismiss the dialog by using Navigator.of(context).pop while BlocListener start another LoadingDialog.show(context), that will dismiss the loading dialog wrongly. Moreover, if you are having complex navigation flow, managing the navigator is pain as hell as i had experienced.
> 2. Second, using show dialog for presenting loading dialog will lead to problems which was mentioned. Because Navigator.of(context).push is not affecting the layout immediately, so if you are calling hide dialog too fast will cause to pop current page rather than hiding the dialog.
> 
> Enough talking here is the acceptable way I think:
> 
> ```dart
> class LoadingOverlay {
>   OverlayEntry _overlay;
> 
>   LoadingOverlay();
> 
>   void show(BuildContext context) {
>     if (_overlay == null) {
>       _overlay = OverlayEntry(
>         // replace with your own layout
>         builder: (context) => ColoredBox(
>           color: Color(0x80000000),
>           child: Center(
>             child: CircularProgressIndicator(
>               valueColor: AlwaysStoppedAnimation(Colors.white),
>             ),
>           ),
>         ),
>       );
>       Overlay.of(context).insert(_overlay);
>     }
>   }
> 
>   void hide() {
>     if (_overlay != null) {
>       _overlay.remove();
>       _overlay = null;
>     }
>   }
> }
> 
> class StatelessSample extends StatelessWidget {
>   final LoadingOverlay _loadingOverlay = LoadingOverlay();
> 
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       body: BlocListener<MyBloc, MyState>(
>         listener: (context, state) {
>           if (state is MyStateLoadInProgress) {
>             _loadingOverlay.show(context);
>           } else {
>             _loadingOverlay.hide();
>           }
>         },
>         child: Container(),
>       ),
>     );
>   }
> }
> ```
> 
> Hope it answers your question

Nice another solution with OverlayEntry. But I have another issue, if I show the Loading Overlay inside the page that contains BottomNavigationBar the Overlay does not overlay the entire screen and the BottomNavigationBar is not overlayed by OverlayEntry.

**Comment by gustavo-bordin** [comment]
I came across the same issue and i realized that using dialog for loading states is painful, so i've implemented a wrapper widget that shows a loading indicator over the screen using Stack, this is way cleaner now

**Comment by Tilakraj-B** [comment]
> I came across the same issue and i realized that using dialog for loading states is painful, so i've implemented a wrapper widget that shows a loading indicator over the screen using Stack, this is way cleaner now

can you provide the code you implemented

**Comment by Tilakraj-B** [comment]
> I came across the same issue and i realized that using dialog for loading states is painful, so i've implemented a wrapper widget that shows a loading indicator over the screen using Stack, this is way cleaner now

Can you provide the source code you used

**Comment by gustavo-bordin** [comment]
@Tilakraj-B 
```

import 'package:flutter/material.dart';
import 'package:loading_animation_widget/loading_animation_widget.dart';

class LoadingLayer extends StatelessWidget {
  const LoadingLayer({super.key, required this.child, required this.isLoading});

  final bool isLoading;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        child,
        if (isLoading)
          Material(
            color: Colors.black.withOpacity(0.5),
            child: Center(
              child: LoadingAnimationWidget.fourRotatingDots(
                color: Colors.white,
                size: 100,
              ),
            ),
          )
      ],
    );
  }
}

```

Then i use it like this:


```
 return LoadingLayer(
          isLoading: state is AuthLoading,
          child: Scaffold(
            bottomNavigationBar: const BottomProgress(pages: 3, currentPage: 1),
            body: SafeArea(
            
            ......
```
