### ISSUE TITLE
Using rxdart

### ISSUE THREAD

**Issue by kostyanchikoff** [felangel/bloc#1921]
Tell me how I can use rxDart with your library, basically I need a transformation of streams, in my use cases (clean architecture), for example, I have a get request from the server, I want to pull 1 request to get the result and execute 2 (flatMap) and return Stream with useCase to bloc, tell me how to do it as nicely and correctly as possible

**Comment by felangel** [comment]
Hi @kostyanchikoff 👋 
Thanks for opening an issue!

Your question is very vague -- can you please provide a link to a sample app which illustrates what you're trying to achieve and illustrates the challenges you've faced? There are many examples and tutorials which you can look at including the [weather app](https://github.com/felangel/bloc/tree/master/examples/flutter_weather) which integrate with 3rd party APIs.

I would highly recommend using the examples as a reference and providing a sample app which reproduces the issue you're having if you feel the examples aren't enough. Thanks! 🙏

**Comment by kostyanchikoff** [comment]
Thank you very much for answering this, that's enough!)
