### ISSUE TITLE
Error to Use "context.read" inside a "build" method

### ISSUE THREAD

**Issue by JErazo7** [felangel/bloc#1922]
I try use a context.read inside a build method without success. The issue is this is unsafe to do so according to Provider.

**Screenshots**
**This is the error in console:**
![image](https://user-images.githubusercontent.com/19997065/98971596-61ad8200-24df-11eb-9352-661785291ecd.png)

**Fragment of my code where I want to access the state of my bloc.**
![image](https://user-images.githubusercontent.com/19997065/98971835-afc28580-24df-11eb-838e-bcae5f9bf868.png)

**Expected behavior**
I only want to get the state of my bloc without  have to listen it. In this case, i want to know if my user is premium or not. 
The alternative is using "context.select", it works, but it stays listening, and that is not the behavor i expect.

**Comment by felangel** [comment]
Hi @JErazo7 👋 
Thanks for opening an issue!

I would recommend using `context.select` in this case:

```dart
final isFree = context.select((PremiumBloc bloc) => bloc.state.subscription == Subscription.none));
```

If you really want to access the bloc without listening for changes (which is not recommended) you can use `BlocProvider.of<PremiumBloc>(context)`.

Hope that helps and closing for now 👍
