### ISSUE TITLE
[6.1+] BlocProvider.of question

### ISSUE THREAD

**Issue by llfbandit** [felangel/bloc#1923]
Looking for v6.1.1 migration, I'm meeting those few cases:
- Just need current bloc or its dependent blocs to push events where `context.read` can't be called.
- A state independent value retrieved via regular function call (I use Bloc to get a clear view of what is event firing and what it's not).

As far I can see, `read` method is the very same as `BlocProvider.of` without preliminary checks.

So, does `BlocProvider.of` intend to stay long or do I need to plan further migration effort?
If so, do you have any suggestion to provide?

Thanks

**Comment by felangel** [comment]
Hi @llfbandit 👋 
Thanks for opening an issue!

> Just need current bloc or its dependent blocs to push events where context.read can't be called.

If you absolutely don't want to use `context.read` you can always use `BlocProvider.of` although in most cases you should prefer to either use `BlocBuilder`, `context.watch`, or `context.select` directly in `build` methods.

> A state independent value retrieved via regular function call (I use Bloc to get a clear view of what is event firing and what it's not).

I would highly recommend not maintaining internal state in your bloc -- all state should be part of the bloc state itself.

> So, does BlocProvider.of intend to stay long or do I need to plan further migration effort?

There is no plan to remove `BlocProvider.of` 👍 

Hope that helps! Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄
