### ISSUE TITLE
Null-Safety

### ISSUE THREAD

**Issue by enyo** [felangel/bloc#1932]
I've seen that there is a `null-safety` branch, but it doesn't seem to be maintained.

It would be great if you could state your intent on when you'll be migrating to null-safety.

Maybe it makes sense to pin this issue.

**Comment by felangel** [comment]
Hi @enyo 👋
Thanks for opening an issue!

The null-safety branch is open to test null safety and report feedback to the Dart team. 

As far as I know, the dart team does not recommend publishing third party packages with null safety support since it is still under development. My intention is to update and publish these changes when nnbd lands in stable.

Hope that helps 👍

**Comment by enyo** [comment]
Thanks for the swift response. Ok that makes sense. I've seen plenty of libraries releasing versions like `7.0.0-nullsafety.1`. Is that also no recommended?

And: is the `null-safety` branch usable? I think that, for example, the `flutter_bloc` package isn't ported yet?

**Comment by felangel** [comment]
As far as I know it isn’t recommend to publish packages as nnbd isn’t considered production ready at this stage.

> Flutter experimentation with technical preview 2: This is today. Because we’ve successfully migrated the core Flutter framework to null safety, you’re able to try null safety to learn the new language feature and experiment with a small Flutter sample. If you’re a package author, you may also be able to do a trial migration, if you have a small dependency set that’s already been migrated by us. You need to pass an experiment flag, shouldn’t use it in production, and shouldn’t publish any migrated packages.

https://link.medium.com/1iT0ZIREpbb

I plan to migrate flutter_bloc in the near future but the initial push was for pure dart packages.

**Comment by Yegorisa** [comment]
@felangel hey since Null Safety is in beta, it is time to update Bloc library to support null safety. Are there any timelines on this? Thanks!

**Comment by felangel** [comment]
@Yegorisa yes I plan to publish a null-safety version within the next day or two 👍

**Comment by JohnGalt1717** [comment]
Hi there, it looks like hydrated and replay have not been updated to support the null safety of the base packages?

**Comment by felangel** [comment]
Hi @JohnGalt1717 yup, this is high on my priority list and should be done sometime this week 👍

**Comment by JohnGalt1717** [comment]
@felangel whoohoo!  Now for freezed.. ;)
