### ISSUE TITLE
BlocListener keeps missing states after switching tabs

### ISSUE THREAD

**Issue by mhnowak** [felangel/bloc#1934]
**Describe the bug**
BlocListener listens to states emitted only within the span of his living.

**To Reproduce**
1. Run the app below or create something similar below. 
2. "Loaded cubit data" is visible on the screen after 2 seconds.
3. Switch to the 2nd tab and go back to the first one.
4. "Initial widget data" is visible.

```dart
void main() {
  runApp(TabBarDemoApp());
}

class TabBarDemoApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const TabBarDemo(),
    );
  }
}

class ExampleCubit extends Cubit<String> {
  ExampleCubit() : super("Initial cubit data");

  load() async {
    emit("Loading cubit data");
    await Future.delayed(const Duration(seconds: 2));
    emit("Loaded cubit data");
  }
}

class TabBarDemo extends StatelessWidget {
  const TabBarDemo({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => ExampleCubit()..load(),
      child: DefaultTabController(
        length: 2,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              CarPage(),
              Icon(Icons.directions_transit),
            ],
          ),
        ),
      ),
    );
  }
}

class CarPage extends StatefulWidget {
  @override
  _CarPageState createState() => _CarPageState();
}

class _CarPageState extends State<CarPage> {
  final _controller = TextEditingController(text: "Initial widget data");

  @override
  Widget build(BuildContext context) {
    return BlocListener<ExampleCubit, String>(
      listener: (context, state) {
        _controller.text = state;
      },
      child: Center(
        child: Padding(
          padding: const EdgeInsets.all(32),
          child: TextFormField(
            controller: _controller,
          ),
        ),
      ),
    );
  }
}

```

**Expected behavior**
BlocListener should run the listener function again with latest state.  

**Screenshots**
https://share.getcloudapp.com/kpuw0Rrp

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.
```
Analyzing bloc_listener_test...                                         
No issues found! (ran in 4.1s)
```

Paste the output of running `flutter doctor -v` here.
```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.6 19G2021, locale en-GB)
    • Flutter version 1.22.3 at /Users/michal/Develop/flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/michal/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 0CA6CEFD-5A9D-4E8C-A5AD-81F11E4130AB • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

• No issues found!
```

**Additional context**
I'm not sure if this is a bug or intended behaviour. Please let me know if I made any mistakes or misunderstood the purpose of using BlocListener. 

I think the use case is pretty clear in this example, but I'll explain it anyway:
I have a TabBarView with Cubit that I provided above it. I want to update TextEditingController's value based on the latest state in the Cubit.

**Comment by narcodico** [comment]
Hi @mhnowak 👋

The behavior is normal since your `CarPage` gets disposed each time to switch to the other tab, so your `BlocListener` will also be disposed. In order for your setup to work you'd have to ensure the `CarPage` is not disposed when switching. You could achieve that using `AutomaticKeepAliveClientMixin`.

**Comment by mhnowak** [comment]
> Hi @mhnowak 👋
> 
> The behavior is normal since your `CarPage` gets disposed each time you switch to the other tab, so your `BlocListener` will also be disposed. In order for your setup to work you'd have to ensure the `CarPage` is not disposed when switching. You could achieve that using `AutomaticKeepAliveClientMixin`.

I'm aware of that, but I thought that `BlocListener` would listen for all of the events from `Cubit`, more like `BlocBuilder` does.. That's kinda a shame, but I guess I'm gonna need to work around that.

**Comment by narcodico** [comment]
Sorry for the late reply @mhnowak . This has nothing to do with how `BlocListener` works but rather with how tabs work. If you want to work around this internal behavior of tabs then you either keep alive your tab pages or you move your `BlocListener` above tabs where it would remain mounted in the tree even when switching between tab pages.
