### ISSUE TITLE
bug in update state in BlocConsumer

### ISSUE THREAD

**Issue by mbfakourii** [felangel/bloc#1937]
hi

I use BottomNavigationBar and IndexedStack.

When I use BlocConsumer, when I am in another stack, when a new situation occurs in the widget that I am not, the widget is not updated.

For example, we have two widgets, "A" and "B". I am in widget B and an Internet request comes for widget "A", but widget "A" is not updated.

Main Screen
```
body: IndexedStack(
        index: _selectedPage,
        children: _pages,
      ),
```

wiget A
```
 BlocConsumer<ProviderBloc, ProviderState>(
                            listener: (context, state) {
                              if (state is ProfileLoadSuccess) {...
```

widget B
```
another code ... 

In this widget screen fetch req for widget A but not update wiget A !
```

**Comment by felangel** [comment]
Hi @mbfakourii 👋 
Thanks for opening an issue!

`BlocBuilder`, `BlocListener`, and `BlocConsumer` only react to state changes if they are mounted in the widget tree. It sounds like you need to lift the `BlocConsumer` higher up in your widget tree if you want it to stay mounted even when switching pages.


Closing for now but feel free to comment with additional info/reproduction sample and I'm happy to continue the conversation 👍
