### ISSUE TITLE
Cannot call yield from callback in Bloc

### ISSUE THREAD

**Issue by anticafe** [felangel/bloc#194]
**Describe the bug**
In `DownloadBloc`, I have a `httpRepository` to handle download file, and of course with callback of how many percentage. For example:
```
} else if (event is EventDownloadStart) {
  String fileSavePath = await httpRepository.downloadFile(
  ..
  progressCallback: ((int count, int total) {
    double percent = count * 100 / total;
    yield StateDownloadProgress(progress: percent);
   }),
  ...
  );
```
However I notice cannot invoke `yield` here because of compiler error: `The built-in identifier 'yield' can't be used as a type.`

**Expected behavior**
I would like to know how can I send back percentage data to main UI.

**Additional context**
It seems there is similar issue (#171 - Function callbacks in Bloc). According to your suggestion in that issue, should I create additional `DownloadProgressLoc` to dispatch progress?

**Comment by felangel** [comment]
Hi @anticafe I think you need to mark your callback function as async* in order to be able to yield. Let me know if that helps 👍

**Comment by felangel** [comment]
Closing this for now but feel free to comment with any other questions/comments and I can reopen this/continue the conversation. 👍

**Comment by anticafe** [comment]
Unfortunately if I mark callback function as `async*` then no log as well as yield at all.
Otherwise if I remove `async*` then there is log but no yield.

My code is:
```
Stream<StateViewFile> mapEventToState(
...
} else if (event is EventDownloadStart) {
  String fileSavePath = await httpRepository.downloadFile(
  ..
  progressCallback: onProgressCallback,
  ...
  );
...
onProgressCallback(int count, int total) async* {
    double percent = count * 100 / total;
    print('fileRepository.downloadFile $progress% ($percent%)');
    yield StateDownloadProgress(progress: progress);
  }
```

**Comment by felangel** [comment]
Can you please put together a simple sample app that has the same problem? It’d be much easier for me to help if you can share a sample that I can run locally. Thanks!

**Comment by anticafe** [comment]
Here you are: https://drive.google.com/open?id=1uaZuKrHTD9KE7EzmYR8BBh7Yi0OV801x

**Comment by felangel** [comment]
@anticafe thanks! You can see the working version [here](https://drive.google.com/file/d/1DYVbw2XRbQvEmfOhkxNraCnMlLSdUZwn/view?usp=sharing). 👍

**Comment by anticafe** [comment]
@felangel It looks go good. Now it's possible to dispatch download progress although requires more code than just Bloc. Thank you so much for spending time to help me resolve this hard problem. 🥇

**Comment by felangel** [comment]
@anticafe no problem! Glad I was able to help 😄

**Comment by fvisticot** [comment]
I have the same issue (using DIO and progress callback).
The link with the answer is broken :(

I try to reinject Event in bloc when progress is updated.

BUT the UserAvatarPictureUploadProgressEvent are only fired in the bloc when the updateUserPicture await function is completed


```
@override
  Stream<UserAvatarUpdatePictureState> mapEventToState(
      UserAvatarUpdatePictureEvent event) async* {
    if (event is UserAvatarPictureUploadProgressEvent) {
      yield UserAvatarPictureUploadProgress(
          send: event.send, total: event.total);
    }
    if (event is UserAvatarUpdatePicture) {
      try {
        final updateResponse = await Api().updateUserPicture(
            bytes: event.imageBytes,
            file: event.file,
            progress: (send, total) async {
              add(UserAvatarPictureUploadProgressEvent(
                  send: send, total: total));
            });
```

**Comment by fvisticot** [comment]
> @felangel It looks so good. Now it's possible to dispatch download progress although requires more code than just Bloc. Thank you so much for spending time to help me resolve this hard problem.

Can you please post the answer ? (link is broken)

**Comment by PDDStudio** [comment]
I'm having the same problem. @felangel could you provide a solution that is available to the public? The drive link is broken.

**Comment by felangel** [comment]
Sure, I'll create a recipe for it 👍 (will try to get to it later today/tomorrow)

**Comment by stay-safe** [comment]
I'm waiting for it.

**Comment by felangel** [comment]
@stay-safe sorry been swamped but will try to get to it tomorrow!

**Comment by stay-safe** [comment]
Thank you. I bow before the magnificence of your code.

**Comment by stay-safe** [comment]
Still waiting

**Comment by felangel** [comment]
Sorry for the delay! You can check out the [gist](https://gist.github.com/felangel/68088378617e6d4b5fee06f070cafef4). I'll add it to the website recipes with written explanations shortly 👍
