### ISSUE TITLE
I can not set initial value for TextField in Bloc 

### ISSUE THREAD

**Issue by playerthong** [felangel/bloc#1941]
I'm facing one problem.  I find "how to set initial value textfield" in Bloc document. However I can not see any article about it. could you mind give me one example

**Comment by felangel** [comment]
Hi @playerthong 👋 
Thanks for opening an issue!

You can achieve this by using the `initialValue` parameter on `TextFormField`

```dart
return BlocBuilder<MyBloc, MyState>(
  builder: (context, state) {
    return TextFormField(
      initialValue: state.someValue,
      ...
    );
  },
);
```

Hope that helps 👍

**Comment by GsProjects** [comment]
Hi @felangel 

Is there away to have initialValue change in response to changes in state caused by other widgets?

**Comment by saeedesmaeili** [comment]
Is there any way without TextEditingController?

**Comment by aezakmi8** [comment]
For some reason InitialValue didnt work

a made this Widget

https://stackoverflow.com/a/77918286/9842271
