### ISSUE TITLE
IDE gets really slow when writing code in Bloc

### ISSUE THREAD

**Issue by jezsung** [felangel/bloc#1945]
Well, I don't think this issue is related to the Bloc package but I just wanted to know if there's someone experiencing the same problem.

Android Studio gets really slow when writing and editing Bloc file. This also happens on VS code so I think the issue was in Dart or Flutter plugins. Looks like the code analyzer has some bug when analyzing Stream.

Does anyone have the same issue? And where should I report a Dart & Flutter plugin issue?

Also, I did almost everything to optimize my IDE. I disabled all the unused plugins and background processes. I'm using Macbook Pro 2020 with 16GB RAM.

**Comment by felangel** [comment]
Hi @jezsung 👋 
Thanks for opening an issue!

Might be related to https://github.com/Dart-Code/Dart-Code/issues/2906 or https://github.com/flutter/flutter-intellij/issues/4849? I would recommend either adding information to those issues or if you feel it's unrelated, opening a new issue and providing as much information as possible 👍 

Hope that helps!
