### ISSUE TITLE
Cubit in BlocListener not working in initState

### ISSUE THREAD

**Issue by ukieTux** [felangel/bloc#1948]
I have issue when try to execute method in Cubit in **initState** it's not working in bloc listener

![image](https://user-images.githubusercontent.com/1531684/99792953-e002c780-2b62-11eb-8d62-0aa90266c8b9.png)

![image](https://user-images.githubusercontent.com/1531684/99792918-cbbeca80-2b62-11eb-9196-3f18efbb4a82.png)

Resource.Loading() state it's not triggered, and only when i'm using BLocListener it's not working
**I was try using BLocBuilder, it's work
I was try replace Cubit with Bloc , it's work
i was try add Delay before call getListEmployees, it's work**

**Comment by felangel** [comment]
Hi @ukieTux 👋 
Thanks for opening an issue!

BlocListener only receives updates after it is mounted in the widget tree. In this case, the `ListEmployeesBloc` is emitting a state before `BlocListener` is mounted. I would recommend lifting `BlocListener` higher in the widget tree.

Hope that helps 👍

**Comment by ukieTux** [comment]
Hi @felangel 👋
Thanks for reply.

But why when i'm trying to replace **Cubit<State>** with **Bloc<Event,State>** , BlocListener can get Resources.loading state ?

### Can get Loading state in BlocListener  ✅

![image](https://user-images.githubusercontent.com/1531684/99862302-23e1e500-2bd4-11eb-8121-842671c374d7.png)

### Can't get Loading state in BlocListener ❌
![image](https://user-images.githubusercontent.com/1531684/99862338-4411a400-2bd4-11eb-8059-92c8dbdaf68a.png)

**Comment by felangel** [comment]
@ukieTux it's because you're getting lucky since the bloc takes a little longer to emit the new state due to the event loop.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
