### ISSUE TITLE
Is there any downsides when providing all Blocs above MaterialApp? 

### ISSUE THREAD

**Issue by QAQyzk** [felangel/bloc#1950]
As the app grows bigger I found myself need to access other bloc's state and data in another bloc more often, and usually their in different route. So I wonder is there any reason to not place all blocs above the MaterialApp widget?

**Comment by Elias8** [comment]
It is fine. You can put it anywhere in the widget tree you want. I do that when I use `bloc` for dynamic theming or localization, which both are needed in the `MaterialApp` widget to rebuild it with different them or localization when changed.

**Comment by QAQyzk** [comment]
Thanks! Those information is really helpful! I will keep blocs as scoped as possible. :+1:
