### ISSUE TITLE
Immutability 

### ISSUE THREAD

**Issue by sm2017** [felangel/bloc#1958]
Must state object be Immutable ? to `emit` ne state or in `mapEventToState` must we clone state object to change its values , like with `copyWith`

**Comment by felangel** [comment]
Hi @sm2017 👋 
Thanks for opening an issue!

Yes, state should be immutable. If you emit `S1` and `S2` where `S1 == S2` then `S2` will not trigger a state change.
Hope that helps 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄
