### ISSUE TITLE
Question: emit in bloc

### ISSUE THREAD

**Issue by sm2017** [felangel/bloc#1959]
I see `**[emit] should never be used outside of tests.**` in bloc , Can you explain why?

**Comment by QAQyzk** [comment]
Use of emit() outside of the Cubit will directly changes the state of the cubit. 
![image](https://user-images.githubusercontent.com/31653933/100092194-94e00180-2e4d-11eb-8f00-e49e86ca81f5.png)
As the diagram shows the state of a cubit should only change based events and its internal logic.
[Bloc Core Concepts](https://bloclibrary.dev/#/coreconcepts)
