### ISSUE TITLE
How can I save the state?

### ISSUE THREAD

**Issue by kostyanchikoff** [felangel/bloc#1963]
Hello! Tell me how can I save the screen state? I have,
very complex UI that was loaded with TestState but I need to show the BottomSheetDialog and still keep the state of my screen. If I call another state, then my UI changes and there will be a void from the back of my bottomSheetDialog
`
class TestCorePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) => BlocConsumer<CoreBlocExample, CoreState>(
 listener : (context, state){
    if(state is OpenDialogState){
       showBottomSheetDialog();
     }
},  
 builder: (context, state){
          if(state is StateUI){
            return UI
          }
      }
}
`
How to get a new state and at the same time keep the same! Thanks a lot in advance!

**Comment by felangel** [comment]
Hi @kostyanchikoff 👋 
Thanks for opening an issue!

Please take a look at the [FAQs](https://bloclibrary.dev/#/faqs?id=handling-errors). You can model your state as a single concrete class rather than an abstract base class with multiple concrete subclasses. You can also take a look at [fluttersaurus](https://github.com/felangel/fluttersaurus) as an example.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by kostyanchikoff** [comment]
The bottom line is that I want to avoid boilerplate code

**Comment by felangel** [comment]
@kostyanchikoff I'm not sure what boilerplate you're referring to. The solution I suggested would likely reduce the number of lines of code.

**Comment by kostyanchikoff** [comment]
I'm going to have a basic blocBuilder with a listener in which I will have an error state and at the same time so that they do not affect other functionality, under the error I think of showing a snackBar or dialog, about the solution you are talking about, you need to create a model of a new state for each bloc

**Comment by kostyanchikoff** [comment]
as I see an ideal solution, this is to create a basic block, create an abstract state with an error, add a function to the BaseBloc, when an error is received, take the current state and send an error, but this solution does not work since BlocBuilder only works once.

`class BaseState<T>{
     T error;
}

 class BaseBloc exstend Bloc{
   
   launchRequest(req){
     try{
       req()
     }cath(ex){
            if(ex is Ext){
               if(state is BaseState){
                   yield  state..error = ex.toString()
                }
           }
      }
   }
}
`

**Comment by felangel** [comment]
> but this solution does not work since BlocBuilder only works once.

What do you mean BlocBuilder only works once? BlocBuilder will rebuild whenever the state of the bloc changes.
