### ISSUE TITLE
context.read<T>().methodHere() inside BlocBuilder

### ISSUE THREAD

**Issue by ForceGT** [felangel/bloc#1967]

**Comment by ForceGT** [comment]
Sorry actually I just opened the issue and it got submitted automatically, Idk how but 

The issue is as follows

Suppose I have a blocbuilder and I need to access a certain method from my repository using the read method 
What would be the correct method to do so?

read() doesn't work in a builder block

**Comment by narcodico** [comment]
Hi @ForceGT 👋

You can always edit your issue from the top right context menu and move your description there.

As for your question the answer is you should never make calls to your  repository in the UI layer. Your repository should be injected into your bloc and you'd trigger the call to your desired method by adding an event to your bloc which will result in that particular call.

Hope that helps ✌

**Comment by ForceGT** [comment]
> Hi @ForceGT 👋
> 
> You can always edit your issue from the top right context menu and move your description there.
> 
> As for your question the answer is you should never make calls to your  repository in the UI layer. Your repository should be injected into your bloc and you'd trigger the call to your desired method by adding an event to your bloc which will result in that particular call.
> 
> Hope that helps ✌ 

Thanks for that
How does it work for a cubit when there is no event?
And in general when there are no events as such

**Comment by narcodico** [comment]
You call methods on the cubit instead of adding events to a bloc. But you do that from a callback, e.g.: the `onTap` on a button or directly on the cubit inside `create` method when you provide it; basically where you normally could either already have access to the cubit(`create`) or you could use `context.read` to grab it(some callbacks).

You basically never want to add events directly inside `build` since that can get called multiple times and could result in a bunch of unwanted calls being made.

**Comment by ForceGT** [comment]
> You call methods on the cubit instead of adding events to a bloc. But you do that from a callback, e.g.: the `onTap` on a button or directly on the cubit inside `create` method when you provide it; basically where you normally could either already have access to the cubit(`create`) or you could use `context.read` to grab it(some callbacks).
> 
> You basically never want to add events directly inside `build` since that can get called multiple times and could result in a bunch of unwanted calls being made.

Thanks buddy!
That was really helpful
I was also used to calling read in a build method usually the widget build method and resulted it in being multiple times 

But now I'll change my approach
I'm new to writing decoupled code so the approach confuses me a little bit

What's the use case for watch though?

**Comment by narcodico** [comment]
It's used to rebuild a widget.
You can read more about these concepts [here](https://bloclibrary.dev/#/migration?id=%e2%9d%97contextbloc-and-contextrepository-are-deprecated-in-favor-of-contextread-and-contextwatch).
