### ISSUE TITLE
flutter_timer: how to make duration dynamic?

### ISSUE THREAD

**Issue by marcoheine** [felangel/bloc#1968]
Hi,

i want to make the duration variable dynamic. 
The user should determine the seconds. But I just can't do it.
Can someone help me and give an example?

**Comment by narcodico** [comment]
Hi @marcoheine 👋

```
class Ticker {
  const Ticker({this.duration});

  final Duration duration;

  Stream<int> tick({int ticks}) {
    return Stream.periodic(duration ?? const Duration(seconds: 1), (x) => ticks - x - 1)
        .take(ticks);
  }
}
```

```
BlocProvider(
        create: (context) => TimerBloc(ticker: Ticker(duration: const Duration(milliseconds: 500))),
        child: Timer(),
      ),
```

Is that what you're after ?

**Comment by marcoheine** [comment]
Hi @narcodico,

thank you for the answer!
But this is not what i'm after.

I want to have the 60 dynamical:

`class TimerBloc extends Bloc<TimerEvent, TimerState> {
  final Ticker _ticker;
  static const int _duration = 60;

  StreamSubscription<int> _tickerSubscription;

  TimerBloc({@required Ticker ticker})
      : assert(ticker != null),
        _ticker = ticker,
        super(TimerInitial(_duration));

  @override
  void onTransition(Transition<TimerEvent, TimerState> transition) {
    print(transition);
    super.onTransition(transition);
  }`

**Comment by narcodico** [comment]
I see.

```
TimerBloc({@required Ticker ticker, Duration duration})
      : assert(ticker != null),
        _ticker = ticker,
        super(TimerInitial(duration ?? _duration));
```

Then you can provide your bloc with a different value for the duration.

**Comment by marcoheine** [comment]
@narcodico thank you so much! :-)
