### ISSUE TITLE
How to Provide Bloc to other screens

### ISSUE THREAD

**Issue by pazhut** [felangel/bloc#1969]
Hi

in my widget init code i have the following:
@override
  void initState() {
    _authErrorHandler = AuthErrorHandler();
    _authBloc = AuthBloc();
    super.initState();
  }

i would like to make it such that the bloc (_authBloc) is available for all screens in the path that comes after the current screen (including the current screen), my goal is to be able to get reference to the bloc using BlocProvide.of ... 

i couldn't figure out a way, can you pleas help?

**Comment by narcodico** [comment]
Hi @pazhut 👋

You can use a `BlocProvider` to provide your auth bloc on top of the `MaterialApp`, that way your bloc will be globally available to any route/screen. Read more about it [here](https://bloclibrary.dev/#/flutterbloccoreconcepts?id=blocprovider).

**Comment by pazhut** [comment]
Hi

I am aware of the possibility to add bloc as global,  but i doesn't want to
use it, i would like to have the bloc available only to part of the
navigation path, not the whole app, can I do that?

**Comment by pazhut** [comment]
Hi 

do you have any information to my last comment? in general i thought that i can use BlocProvider.value to inject the block on the navigation tree whenever needed?

**Comment by felangel** [comment]
@pazhut check out the [Bloc Access Recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=recipes-bloc-access) 👍

**Comment by pazhut** [comment]
Hi

i am not sure i managed to find an answer to my question in the recipe,
what i am looking for is:
- screenA (which is not the first screen in the app) create bloc => blocA =
BlocA();
- screenA push screenB, screenB do not need access to thee bloc
- screenB push screenC - which need access to the bloc (lets say add event
so this will be reflected when we pop all the way to screenA)
- when screenA is being popped the bloc will be closed as we do not need it
any longer

Can you please point me to which part of your recipe covers this use case?
 Thanks much

**Comment by felangel** [comment]
@pazhut how are you pushing routes? Are you using `Navigator.push` or `Navigator.pushNamed`?

**Comment by pazhut** [comment]
i am using Navigator.pushNamed

**Comment by felangel** [comment]
Did you read through the [Named Route Access](https://bloclibrary.dev/#/recipesflutterblocaccess?id=named-route-access) section?

**Comment by pazhut** [comment]
That example allocates the bloc globally - so not achieving my goal of the
bloc being released after ScreenA popped.

maybe what i should use is: Generated Route Access? and make sure i pass
the correct bloc to the correct screen?

**Comment by felangel** [comment]
@pazhut you can use a nested Navigator so it doesn't have to be a global bloc. Yeah you also use generated route access as well 👍

**Comment by narcodico** [comment]
You can achieve your desired setup by simply using `BlocProvider.value` and passing the bloc to route A and route C only, or a nested navigator.

**Comment by pazhut** [comment]
You can achieve your desired setup by simply using BlocProvider.value and
passing the bloc to route A and route C only - can you provide me with an
example on how to do that?

**Comment by felangel** [comment]
@pazhut refer to https://bloclibrary.dev/#/recipesflutterblocaccess?id=homepage

**Comment by narcodico** [comment]
```
class AppRouter {
  final _counterBloc = CounterBloc();

  Route onGenerateRoute(RouteSettings settings) {
    switch (settings.name) {
      case 'routeA':
        return MaterialPageRoute(
          builder: (_) => BlocProvider.value(
            value: _counterBloc,
            child: PageA(),
          ),
        );
      case '/routeC':
        return MaterialPageRoute(
          builder: (_) => BlocProvider.value(
            value: _counterBloc,
            child: PageC(),
          ),
        );
      default:
        return null;
    }
  }

  void dispose() {
    _counterBloc.close();
  }
}
```

**Comment by pazhut** [comment]
OK thanks got it, only that it uses push and not pushNamed :)

**Comment by pazhut** [comment]
thanks much for your support guys
