### ISSUE TITLE
BlocBuilder not getting called after an update, ListView still displays old data

### ISSUE THREAD

**Issue by kajannDev** [felangel/bloc#197]
I'm using flutter_bloc for state management and landed on this issue. When updating a field and Dispatching UpdateTodo, the BlocBuilder is not refreshing the page. It is working fine when Adding or Deleting. I'm not sure what I'm doing wrong here.

Even if I go to a different screen and returning to this screen it still displays the old data even though the file was updated.

I spent more than 2 hours trying to debug this to no avail. I tried initializing the updatedTodos = [] then adding each todo one by one, to see if that does something, but that didn't work either.

Any help here would be appreciated.

TodosBloc.dart:
```
Stream<TodosState> _mapUpdateTodoToState(
    TodosLoaded currentState,
    UpdateTodo event,
  ) async* {     
        if (currentState is TodosLoaded) {
        final index = currentState.Todos
            .indexWhere((todo) => event.todo.id == todo.id);
        final List<TodoModel> updatedTodos =
            List.from(currentState.todos)
              ..removeAt(index)
              ..insert(index, event.todo);

        yield TodosLoaded(updatedTodos);
        _saveTodos(updatedTodos);
      }
  }
```
todos_screen.dart:
```
...
Widget build(BuildContext context) {
    return BlocBuilder(
      bloc: _todosBloc,
      builder: (BuildContext context, TodosState state) {
        List<TodoModel> todos = const [];
        String _strings = "";
        if (state is TodosLoaded) {
          todos = state.todos;
        }
        return Expanded(
          child: ListView.builder(
            itemCount: todos.length,
            itemBuilder: (BuildContext ctnx, int index) {
              return Dismissible(
                key: Key(todo.toString()),
                child: DetailCard(
                  todo: todos[index],
                ),
              );
            },
          ),
        );
...
```
I'm expecting when the BlocBuilder to be called and refreshed the ListView.

**Comment by felangel** [comment]
Hi @kajannDev 👋 

Can you share the `TodosLoaded` state implementation please? Thanks! 👍

**Comment by kajannDev** [comment]
```
class TodosLoaded extends TodosState {
  final List<TodoModel> todos;

  TodosLoaded([this.todos = const []]) : super([todos]);

  @override
  String toString() => 'TodosLoaded { tpdos $todos }';
}
```

**Comment by felangel** [comment]
@kajannDev thanks! can you also include the `TodoModel` implementation?

**Comment by kajannDev** [comment]
```
@immutable
class TodoModel extends Equatable {
  final String id;
  final String todoType;
  final DateTime dueBy;
  final int quantity;
  final bool completed;

  TodoModel({
    String id,
    this.todoType,
    this.dueBy,
    this.quantity,
    this.completed,
  })  : this.id = id ?? Uuid().generateV4(),
        assert(todoType != null),
        assert(dueBy != null),
        assert(quantity != null),
        assert(completed != null);

  TodoModel copyWith({
    String id,
    String todoType,
    int quantity,
    DateTime dueBy,
    bool completed,
  }) {
    return TodoModel(
      id: id ?? this.id,
      todoType: todoType ?? this.todoType,
      dueBy: dueBy ?? this.dueBy,
      quantity: quantity ?? this.quantity,
      completed: completed ?? this.completed,
    );
  }

  @override
  String toString() {
    return 'Todo { id: $id, todoType: $todoType, dueBy: $dueBy, quantity: $quantity, completed: $completed }';
  }

  TodoEntity toEntity() {
    return TodoEntity(id, todoType, dueBy, quantity, completed);
  }

  static TodoModel fromEntity(TodoEntity entity) {
    return TodoModel(
      id: entity.id ?? Uuid().generateV4(),
      todoType: entity.todoType,
      dueBy: entity.dueBy,
      quantity: entity.quantity,
      completed: entity.completed,
    );
  }
}
```

**Comment by felangel** [comment]
Thanks! I think the problem is you are extending `Equatable` but you aren't passing the props to the super class in this case. If you update your constructor to be:

```dart
TodoModel({
    String id,
    this.todoType,
    this.dueBy,
    this.quantity,
    this.completed,
  })  : this.id = id ?? Uuid().generateV4(),
        assert(todoType != null),
        assert(dueBy != null),
        assert(quantity != null),
        assert(completed != null),
        super([id, todoType, dueBy, quantity, completed]);
```
I think that will solve your problem. Let me know if that helps! 👍

**Comment by kajannDev** [comment]
That was it. Wow totally missed that. Thank you so much. 
Really appreciate your quick response to this.

**Comment by felangel** [comment]
@kajannDev no problem! Glad I was able to help 😄

**Comment by ariefsn** [comment]
Hi @felangel 
according to this issue,
how about if i'm not using equatable?? but blocBuilder still not refreshed. :(
i have to go to other page, and go back to old page again to get blocBuilder called again.

**Comment by craiglabenz** [comment]
@ariefsn Is your widget with the ListView a StatefulWidget or a StatelessWidget? What might be happening is your BlocBuilder is actually working, but if it controls a StatefulWidget and you're not calling `setState()` anywhere, the update fails to propagate from `bloc` to core `Flutter`.

**Comment by ariefsn** [comment]
> @ariefsn Is your widget with the ListView a StatefulWidget or a StatelessWidget? What might be happening is your BlocBuilder is actually working, but if it controls a StatefulWidget and you're not calling `setState()` anywhere, the update fails to propagate from `bloc` to core `Flutter`.

Hi @craiglabenz,,
I have textfield and dropdown button.
onchanged textfield the blocBuilder not rebuild, it will be rebuild when onSubmit textfield.
and same condition, blocBuilder not rebuild when onChange dropdown button.

**Comment by felangel** [comment]
Hi @ariefsn 👋 
Can you please share a sample app that demonstrates the issue you’re having? Thanks!

**Comment by ariefsn** [comment]
ShowoffState.dart
``` Dart
class InitialShowoffState {`
  FlatButtonState flatButtonState;`

  InitialShowoffState({`
    this.flatButtonState,`
  })

  init() => InitialShowoffState(
    flatButtonState: flatButtonState,
  );
}

class FlatButtonState {
  FlatButtonState({
    this.width = 200.0,
    this.label = "Flat Button",
    this.onPressed,
    this.color,
    this.splashColor,
    this.disabledColor,
    this.textColor,
    this.highlightColor,
    this.padding,
    this.borderTopLeft = 0,
    this.borderTopRight = 0,
    this.borderBottomLeft = 0,
    this.borderBottomRight = 0,
  });

  double width, borderTopLeft, borderTopRight, borderBottomLeft, borderBottomRight;
  String label;
  void Function() onPressed;
  Color color, splashColor, disabledColor, textColor, highlightColor;
  EdgeInsetsGeometry padding;
}
```

Showoff_bloc.dart
``` Dart
class ShowoffBloc extends Bloc<Actions, InitialShowoffState> {
  @override
  InitialShowoffState get initialState => InitialShowoffState().init();

  StreamController _flatButtonSC = StreamController<FlatButtonState>.broadcast();
  StreamSink<FlatButtonState> get inFlatButton => _flatButtonSC.sink;
  Stream<FlatButtonState> get outFlatButton => _flatButtonSC.stream;

  ShowoffBloc() {
    _flatButtonSC.stream.listen((v) {
      currentState.flatButtonState = v;
    });
  }

  @override
  void dispose() {
    super.dispose();
    _flatButtonSC.close();
  }

  @override
  Stream<InitialShowoffState> mapEventToState( Actions event, ) async* {
  }
}
```

Component MyDropdown.dart
```Dart
class MyDropdown extends StatelessWidget {
  MyDropdown({
    @required this.items,
    @required this.onChanged,
    this.hint,
    this.isDense = true,
    @required this.value,
    this.width = 150.0,
    this.colorBox = false,
    this.iconBox = false,
    this.disabled = false
  });

  final List<Map<String, dynamic>> items;
  final void Function(dynamic value) onChanged;
  final Widget hint;
  final bool isDense, colorBox, iconBox, disabled;
  final Map<String, dynamic> value;
  final double width;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 205,
      child: DropdownButton(
        key: key,
        isExpanded: true,
        items: items.map((Map<String, dynamic> value) {
          return DropdownMenuItem(
            key: UniqueKey(),
            child: Row(
              children: <Widget>[
                colorBox ? Container(
                  color: value["value"],
                  height: 20.0,
                  width: 20.0,
                ) : iconBox ? Icon(value["value"]) : Container(),
                Padding(padding: EdgeInsets.all(10.0),),
                Text(value["label"])
              ],
            ),
            value: value,
          );
        }).toList(),
        onChanged: disabled ? null : onChanged,
        hint: hint,
        isDense: isDense,
        value: value,
      ),
    );
  }
}
```

Here my views page
``` Dart
  @override
  Widget build(BuildContext context) {
    final _bloc = InheritedBloc.of(context).bloc;

    return BlocBuilder(
      bloc: _bloc,
      builder: (BuildContext context, InitialShowoffState state) {
        _width.text = state.flatButtonState.width.toString();
        _color = state.flatButtonState.color;
        _colorSelected = colorList.where((e) => e["value"] == _color).toList()[0];
        _textColor = state.flatButtonState.textColor;
        _textColorSelected = colorList.where((e) => e["value"] == _textColor).toList()[0];

        print("rebuild!!!");

        return Column(
           children: <Widget>[
             Expanded(
               flex: 1,
                 child: ListView(
                   shrinkWrap: true,
                   physics: BouncingScrollPhysics(),
                   children: <Widget>[
                     ListTile(
                       dense: true,
                       title: Text("Width"),
                       trailing: Container(
                         child: TextField(
                           controller: _width,
                           onChanged: (v) {
                             state.flatButtonState.width = double.parse(v);
                             _bloc.inFlatButton.add(state.flatButtonState);
                           },
                           textAlign: TextAlign.end,
                           keyboardType: TextInputType.number,
                         ),
                         width: 205,
                       ),
                     ),
                     ListTile(
                       dense: true,
                       title: Text("Color"),
                       trailing: MyDropdown(
                         items: colorList,
                         onChanged: (value) {
                           state.flatButtonState.color = value["value"];
                           _bloc.inFlatButton.add(state.flatButtonState);
                           _bloc.dispatch(Actions.getFlatButtonState);
                         },
                         value: _colorSelected,
                         hint: Text("Choose Color"),
                         colorBox: true,
                       ),
                     ),
               ]
             ),
           ]
        )
      }
    );
  }
```

@felangel on first ListTile with TextField it can be rebuild when onSubmit, not onChange. Same condition with second ListTile with DropdownButton, it can't rebuild with onChange event. Thanks before 😕

**Comment by craiglabenz** [comment]
@ariefsn Are you able to provide any code?

**Comment by felangel** [comment]
@ariefsn thanks for sharing those code samples. I'm a bit confused by your use of the bloc library. It seems you are extending bloc but are still maintaining your own `StreamController` and aren't using `mapEventToState`?

Would it be possible for you to share a link to the full source code so that I can see the complete code and run it locally? Thanks! 👍

**Comment by kovzone** [comment]
I'm facing same problem. I tried to call currentState but the view is not reloaded. Could you help me?

`
abstract class AuthState extends Equatable {
  const AuthState();
  @override
  List<Object> get props => [];
}

class AuthInitial extends AuthState {}

class Intro extends AuthState {}

class Authenticated extends AuthState {}

class Unauthenticated extends AuthState {
  final User user;
  final User errUser;
  final String message;

  const Unauthenticated({
    this.user,
    this.errUser,
    this.message,
  });

  Unauthenticated copyWith({
    User user,
    User errUser,
    String message,
  }) {
    return Unauthenticated(
      user: user ?? this.user,
      errUser: errUser ?? this.errUser,
      message: message ?? this.message,
    );
  }

  @override
  List<Object> get props => [user, errUser, message];
}
`

**Comment by jaykadamss** [comment]
hiii felangel data in loaded state is not refreshed after insert update data to sqflite i use blocbuilder with blocprovider can you help me to solve this

**Comment by jaykadamss** [comment]
Container(
          width: MediaQuery.of(context).size.width,
          padding: const EdgeInsets.only(top: 2.0, left: 2.0, right: 2.0),
    child:BlocBuilder<BlocEvents,BlocStates>(
            bloc: widget.todoBloc,
            builder: (BuildContext context, BlocStates todoStates) {
              if(todoStates is LoadingState){
                return _loadingdata();
              }
              else if(todoStates is LoadedState){
                print('therer is ${todoStates.todoList}');
                return _getListForTodo(todoStates.todoList);
              }
              return _loadingdata();
            },
          ),
        ),

this is blocbuilder which i called

**Comment by jaykadamss** [comment]
class TodoBloc extends Bloc<BlocEvents, BlocStates> {
  final dbHelper = DatabaseHelper();

  final StreamController<List<Todo>> todoController =
      StreamController<List<Todo>>.broadcast();

  Stream<List<Todo>> get todos => todoController.stream;

  var states;
  TodoBloc() {
    getTodo();
  }

  getTodo({String query, String des, BlocStates states}) async{
    if (des != null && des.toString().isNotEmpty) {
      todoController.sink.add(await dbHelper.getTodoSortList(
          startDate: query != null ? query : null, des: des, states: states));
    } else {
      todoController.sink.add(await dbHelper.getTodoMapList(query: query, states:states));
    }
  }

  getCategoryList({String query}) async {
    if (query != null && query.toString().isNotEmpty) {
      todoController.sink.add(await dbHelper.getDataByCategory(title: query));
    } else {
      todoController.sink.add(await dbHelper.getDataByCategory());
    }
  }

  void dispose() {
    todoController.close();
  }

  @override
  // TODO: implement initialState
  BlocStates get initialState => LoadedState();

  @override
  Stream<BlocStates> mapEventToState(BlocEvents event) async* {
    if (event is TodoLoading) {
      yield* _mapTodosLoadedToState();
    } else if (event is TodoAdded) {
      yield* _mapTodoAddedToState(event);
    } else if (event is TodoUpdated) {
      yield* _mapTodoUpdatedToState(event);
    } else if (event is TodoDeleted) {
      yield* _mapTodoDeletedToState(event);
    }
  }

  Stream<BlocStates> _mapTodosLoadedToState() async* {
    yield LoadedState();
    if(currentState is LoadedState){
       getTodo(states: currentState);
    }
  }

  Stream<BlocStates> _mapTodoAddedToState(TodoAdded event) async* {
    await dbHelper.insertData(event.todo);

    if(currentState is LoadedState){
      List<Todo> updatedTodos = List.from((currentState as LoadedState).todoList)..add(event.todo);
      var getList=getTodo(states: currentState);
      yield LoadedState(getList);
    }
  }

  Stream<BlocStates> _mapTodoUpdatedToState(TodoUpdated event) async* {
    await dbHelper.updateData(event.todo);
    if(currentState is LoadedState){
      final List<Todo> updatedTodos =
      (currentState as LoadedState).todoList.map((todo) {
        return todo.id == event.todo.id ? event.todo : todo;
      }).toList();
      var getList=getTodo(states: currentState);
      yield LoadedState(getList);
    }
  }

  Stream<BlocStates> _mapTodoDeletedToState(TodoDeleted event) async* {
    await dbHelper.deleteData(event.listTodo);
    if(currentState is LoadedState){
      final List<Todo> updatedTodos = (currentState as LoadedState)
          .todoList
          .toList();
      var getList=getTodo(states: currentState);
      yield LoadedState(getList);
    }
  }
}
 this is bloc class in which insert update delete operation done in loadedstate

**Comment by jaykadamss** [comment]
& this is class DatabaseHelper{
  static Database _database;
  String tableName = 'todoTable';
  String dbName = 'todoDb';
  String colId = 'id';
  String colDate = 'date';
  String colTime = 'time';
  String colCategory = 'category';
  String colTitle = 'title';
  String colDescription = 'description';

  static final DatabaseHelper _dbHelper = DatabaseHelper();

  Future<Database> get database async {
    if (_database == null) {
      _database = await initDb();
    }
    return _database;
  }

  Future<Database> initDb() async {
    Directory directory = await getApplicationDocumentsDirectory();
    String path = join(directory.path, dbName);
    return await openDatabase(path, version: 1, onCreate: _onCreate);
  }

  Future _onCreate(Database db, int version) async {
    await db.execute('''
        CREATE TABLE $tableName (
            $colId INTEGER PRIMARY KEY,
            $colTitle TEXT,
            $colDescription TEXT,
            $colDate TEXT,
            $colCategory TEXT,
            $colTime TEXT )
        ''');
  }

  Future<int> insertData(Todo todo) async {
    Database db = await _dbHelper.database;
    var insert = await db.insert(tableName, todo.toDatabaseJson());
    return insert;
  }

  Future<int> updateData(Todo todo) async {
    Database db = await _dbHelper.database;
    var update = await db.update(
        tableName, todo.toDatabaseJson(), where: '$colId = ?',
        whereArgs: [todo.id]);
    return update;
  }

  deleteData(List id) async {
    Database db = await _dbHelper.database;
    var stringList = id.join(",");
    Batch batch = db.batch();
    var delete = batch.rawDelete(
        'DELETE FROM $tableName WHERE $colId IN ($stringList)');
    var results = await batch.commit();
    return results;
  }

  deleteAllTodos() async {
    Database db = await _dbHelper.database;
    var deleteAll = await db.delete(tableName);
    return deleteAll;
  }

  getTodoMapList({int id, String query, BlocStates states}) async {
    Database db = await _dbHelper.database;
    List<Map<String, dynamic>> queries;
    if (query != null) {
      if (query.isNotEmpty)
        if (query == Constants.textTitleController.text.toString()) {
          queries = await db.query(tableName,
              where: '$colTitle LIKE ?',
              whereArgs: ["%$query%"]);
        }
        else if (query == Constants.textDescriptionController.text.toString()) {
          queries = await db.query(tableName,
              where: '$colDescription LIKE ?',
              whereArgs: ["%$query%"]);
        }
        else if (query == Constants.textTimeController.text.toString()) {
          queries = await db.query(tableName,
              where: '$colTime LIKE ?',
              whereArgs: ["%$query%"]);
        }
        else {
          queries = await db.query(tableName,
              where: '$colDate LIKE ?',
              whereArgs: ["%$query%"]);
        }
    } else {
      queries = await db.query(tableName);
    }

    List<Todo> dataList = queries.isNotEmpty
        ? queries.map((c) => Todo.fromDatabaseJson(c)).toList()
        : [];
    if (states != null) {
      (states as LoadedState).todoList = dataList;
      List<Todo> updatedList = (states as LoadedState).todoList;
      print('get after list  is $updatedList');
//      LoadedState(updatedList);
//      notifyListeners();
      return updatedList;
    }
    return dataList;
  }


  getDataByCategory({String title}) async {
    Database db = await _dbHelper.database;
    List<Todo> datasList = [];
    Batch batch = db.batch();
    var query = batch.query(
        tableName, where: '$colCategory=?', whereArgs: ['$title']);
    var results = await batch.commit();
    if (results != null) {
      for (int i = 0; i < results.length; i++) {
        List resultData = results[i];
        datasList = resultData.isNotEmpty
            ? resultData.map((c) => Todo.fromDatabaseJson(c)).toList()
            : [];
      }
      return datasList;
    }
    else {
      Batch batch = db.batch();
      var query = batch.query(tableName);
      var results = await batch.commit();
      print('sort is $results');
      if (results != null) {
        for (int i = 0; i < results.length; i++) {
          List resultData = results[i];
          datasList = resultData.isNotEmpty
              ? resultData.map((c) => Todo.fromDatabaseJson(c)).toList()
              : [];
        }
      }
      return datasList;
    }
  }

  getTodoSortList({String startDate, String des, BlocStates states}) async {
    Database db = await _dbHelper.database;
    List<Todo> datasList = [];
    List<Todo> updatedTodos = [];
    if (startDate != null) {
      Batch batch = db.batch();
      var query = batch.query(tableName, where: '$colDate=?',
          whereArgs: ['$startDate'],
          orderBy: '$colTime $des');
      var results = await batch.commit();
      print('date is $results');
      if (results != null) {
        for (int i = 0; i < results.length; i++) {
          List resultData = results[i];
          datasList = resultData.isNotEmpty
              ? resultData.map((c) => Todo.fromDatabaseJson(c)).toList()
              : [];
          if (states != null) {
            (states as LoadedState).todoList = datasList;
            updatedTodos = (states as LoadedState).todoList;
            print('second is $updatedTodos');

          }
          return updatedTodos;
        }
      }
    }
    else {
      Batch batch = db.batch();
      var query = batch.rawQuery(
          'SELECT * FROM $tableName ORDER BY $colTime $des');
      var results = await batch.commit();
      if (results != null) {
        for (int i = 0; i < results.length; i++) {
          List resultData = results[i];
          datasList = resultData.isNotEmpty
              ? resultData.map((c) => Todo.fromDatabaseJson(c)).toList()
              : [];
          if (states != null) {
            (states as LoadedState).todoList = datasList;
            updatedTodos = (states as LoadedState).todoList;
            print('third is $updatedTodos');
//            LoadedState(updatedTodos);
//            notifyListeners();
            return updatedTodos;
          }
        }
      }
      return datasList;
    }
  }
} database class of sqflite

**Comment by nurbek-b** [comment]
is in Equatable changed smith? 'Cause I can not put parameters on.
Issue is same, BlockBuilder not getting called after update, and displays still old data.
super() of Todo `Too many positional arguments: 0 expected, but 1 found`

My model.
```
@JsonSerializable(createToJson: true)
@HiveType(typeId: 0)
class HealthDataModel extends Equatable {
  const HealthDataModel({
    required this.id,
    required this.date,
    this.temperature,
    this.weight,
    this.dayType = DayType.idle,
    this.ovulation = Ovulation.idle,
    this.dayData = DayData.idle,
    this.sexStatus = SexStatus.idle,
    this.note,
    this.mood,
    this.symptom = const [],
    this.cycleId,
  });

  @HiveField(0)
  final String id;

  @HiveField(1)
  final DateTime date;

  @HiveField(2)
  final double? temperature;

  @HiveField(3)
  final double? weight;

  @HiveField(4)
  final String? note;

  @HiveField(5)
  final DayType? dayType;

  @HiveField(6)
  final Ovulation? ovulation;

  @HiveField(7)
  final DayData? dayData;

  @HiveField(8)
  final Mood? mood;

  @HiveField(9)
  final List<Symptom>? symptom;

  @HiveField(10)
  final SexStatus? sexStatus;

  @HiveField(11)
  final String? cycleId;

  bool get isEmpty =>
      (temperature == null || temperature == 0) &&
      (weight == null || weight == 0) &&
      (note?.isEmpty ?? true) &&
      (dayType == null || dayType == DayType.idle) &&
      (ovulation == null || ovulation == Ovulation.idle) &&
      (dayData == null || dayData == DayData.idle) &&
      mood == null &&
      (symptom?.isEmpty ?? true) &&
      (sexStatus == null || sexStatus == SexStatus.idle) &&
      cycleId == '0';

  bool get hasData => !((temperature == null || temperature == 0) &&
      (weight == null || weight == 0) &&
      (note?.isEmpty ?? true) &&
      mood == null && cycleId != '0' &&
      (symptom?.isEmpty ?? true) &&
      (sexStatus == null || sexStatus == SexStatus.idle));

  HealthDataModel copyWith({
    double? temperature,
    double? weight,
    DayType? dayType,
    Ovulation? ovulation,
    DayData? dayData,
    SexStatus? sexStatus,
    String? note,
    Mood? mood,
    List<Symptom>? symptom,
    String? cycleId,
  }) {
    return HealthDataModel(
      id: id,
      date: date,
      temperature: temperature ?? this.temperature,
      weight: weight ?? this.weight,
      dayType: dayType ?? this.dayType,
      ovulation: ovulation ?? this.ovulation,
      dayData: dayData ?? this.dayData,
      sexStatus: sexStatus ?? this.sexStatus,
      note: note ?? this.note,
      mood: mood ?? this.mood,
      symptom: symptom ?? this.symptom,
      cycleId: cycleId ?? this.cycleId,
    );
  }

  @override
  String toString() => 'id: $id,'
      ' date:$date,'
      ' temperature:$temperature,'
      ' weight:$weight,'
      ' dayType:$dayType,'
      ' ovulation:$ovulation,'
      ' dayData:$dayData,'
      ' mood:$mood,'
      ' symptom:${symptom?.join(', ')},'
      ' sexStatus:$sexStatus,'
      ' note:$note';

  static String convertId(DateTime date) => date.convertToId;

  factory HealthDataModel.fromJson(Map<String, dynamic> json) =>
      _$HealthDataModelFromJson(json);

  Map<String, dynamic> toJson() => _$HealthDataModelToJson(this);

  @override
  bool operator ==(Object other) {
    return other is HealthDataModel && hashCode == other.hashCode;
  }

  @override
  int get hashCode => id.hashCode;

  @override
  List<Object?> get props => [
        id,
        date,
        temperature,
        weight,
        note,
        dayType,
        ovulation,
        dayData,
        mood,
        symptom,
        sexStatus,
        cycleId,
      ];
}

```
My state.
```
class LogPeriodState extends LogPeriodCalendarState {
  static const _tag = 'LogPeriodState';

  final Set<CycleModel> cycleModels;
  final Set<HealthDataModel> healthData;
  final Set<HealthDataModel>? removedData;

  const LogPeriodState(
      {required this.cycleModels, required this.healthData, this.removedData});

  @override
  List<dynamic> get props => [cycleModels, healthData, removedData];
}
```
