### ISSUE TITLE
dispose callback for RepositoryProvider

### ISSUE THREAD

**Issue by comerc** [felangel/bloc#1970]
please add line 40 and change line 45 :)

![Снимок экрана от 2020-11-27 15-19-13](https://user-images.githubusercontent.com/1025241/100448965-2c4e8a00-30c4-11eb-97ae-29f325c07d7e.png)

**Comment by felangel** [comment]
Hi @comerc 👋 
Thanks for opening an issue!

Can you please explain the use-case? Repositories should ideally not have a lifecycle and should not maintain internal state. All lifecycle-related code and state should be maintained in blocs/cubits.

**Comment by comerc** [comment]
![Снимок экрана от 2020-11-28 21-15-38](https://user-images.githubusercontent.com/1025241/100523121-f8a45a80-31be-11eb-960d-012e33344be7.png)

It is wrong code :) [source](https://github.com/felangel/bloc/blob/master/examples/flutter_login/lib/authentication/bloc/authentication_bloc.dart#L45)

But I found workaround now

![Снимок экрана от 2020-11-28 21-20-42](https://user-images.githubusercontent.com/1025241/100523216-d3641c00-31bf-11eb-8acf-44ebf0648e8e.png)

[source](https://github.com/comerc/pet_finder/blob/master/lib/cubits/home.dart#L24)

![Снимок экрана от 2020-11-28 21-21-53](https://user-images.githubusercontent.com/1025241/100523223-d9f29380-31bf-11eb-87f9-5af3e92931a3.png)

[source](https://github.com/comerc/pet_finder/blob/master/lib/repositories/database.dart#L24)

Also I know about `.broadcast()` now :) [useful article](https://medium.com/flutter-community/flutter-stream-basics-for-beginners-eda23e44e32f)

**Comment by RomainFranceschini** [comment]
Hi @felangel,
Thanks for your amazing work! 

I also thought it would be ok for a repository to have a lifecycle.. until I stumbled upon this issue (and #952, #965). 

My use-case would be two blocs that depend on the same cached data. Currently I have a `CacheProvider` (using `hive` as a backend) which is used in my repositories along with other API providers. So `hive` itself has a lifecycle. Beside that, I also use a stream inside repositories for being able to notify changes across blocs that subscribes to the repository.

I'm still considering using a stateful widget for managing the repository lifecycle but maybe I should re-structure my code to to use a third bloc for subscriptions and making the cache provider a repository. What is the best practice? (apologies for pinging on a closed issue).

**Comment by vinayluzrao** [comment]
@felangel 
A common scenario where a `RepositoryProvider.dispose()` would be useful is calling `package:http/http.dart`'s `Client.close()`

**Comment by vinayluzrao** [comment]
Just realized this #2085 is a duplicate of this, and it has been assigned as todo.
