### ISSUE TITLE
Different HydratedBloc on a same Bloc

### ISSUE THREAD

**Issue by Bligoubloups** [felangel/bloc#1974]
Hello !

I've a question:
I have a single HydratedBloc that I use on 3 different pages. So I provide it 3 times.
The problem I have is that when I restart the app, the 3 pages get their state from the same HydratedBloc, so the 3 pages have the same state.
How can I use a same Bloc on different pages with a different Hydration ?

Thanks a lot for your help.

**Comment by felangel** [comment]
Hi @Bligoubloups 👋
Thanks for opening an issue!

You can override the id getter on your HydratedBloc to differentiate between different caches for the same bloc type.

Hope that helps 👍

**Comment by Bligoubloups** [comment]
Thank you very much ! It helps :D
