### ISSUE TITLE
[Question] Best way to handle error and display messages

### ISSUE THREAD

**Issue by fernando-s97** [felangel/bloc#1977]
Currently in my app, on every screen that I want to be able to display a snackbar, I add a parameter that is a String representing the message to be shown.

In the bloc listener, I check if this property is not null, and show a snackbar if so.

In order for the message to show only once, I have to set the property to null on the next state emission. The best way I've found to do that is to always set this property to null in the first line of the mapEventToState.

The problem I see with this approach is that this forces me to use BLoC instead of Cubit, I have to remember to add that first line of code and I don't think it's very performative to always yield this property to null, since in most of the time it will be null.

Are there any recommended practices to handle that?

**Comment by felangel** [comment]
Hi @fernando-s97 👋 
Thanks for opening an issue!

Are you able to provide a link to a sample app which illustrates the issue you're facing? Thanks 👍

**Comment by JoseGeorges8** [comment]
I'm not OP, but I was browsing the issue history to find a recommendation for this as I also have a String error property for each cubit state I create.

Most of the cubits, if not all of them, in my app have this basic implementation, which I use to show a **loading state for when awaiting** and an **error message for when something goes wrong**

**Cubit state**
```
class CubitState extends Equatable {

  final bool loading;
  final String error;
  final Data data;

  CubitState(
      {this.data,
      this.loading = false,
      this.error});

  CubitState copyWith(
          {Data data,
          bool loading = false,
          String error}) =>
      PaySlipState(
          data: data ?? this.data
          loading: loading,
          error: error);

  @override
  List<Object> get props =>
      [data, loading, error];
}

```

**Cubit**

```


class MyCubit extends Cubit<MyCubitState> {
  final MyRepository _myRepository;

  MyCubit(this._myRepository) : super(MyCubitState());

  fetchSomeData() async {
    // loading...
    emit(state.copyWith(loading: true));

    try {
      final data = await _myRepository.fetchSomeData();
     emit(state.copyWith(data: data);
    } catch (e) {
      // notify something went wrong
      addError(e);
    }
  }


  @override
  void onError(Object error, StackTrace stackTrace) {
   // I override the onError so I can handle any error the same for the cubit in here.
   // I added this example for simplicity 
    emit(state.copyWith(error: error));
    super.onError(error, stackTrace);
  }

}

```

**UI**

```
...
BlocListener<MyCubit, MyCubitState>(
          listenWhen: (prev, curr) => prev.error != curr.error,
          listener: (context, state) {
            if(state.error != null){
              SnackBars.showErrorSnackBar(context, error: state.error);
            }
          },
...

```

Although this handles everything properly, I find it repetitive once you get to a certain number of cubit/blocs throughout your app, not to mention every method/event within the cubit/bloc needs to yield loading and have a try/catch to handle the situation.

Is there an approach/practices that you can think of where this can be reduced?

Thanks!

**Comment by felangel** [comment]
If you really want to show a SnackBar for each error you can use the new ScaffoldMessenger and wire it up to an onError callback from your custom BlocObserver but I would highly recommend having feature specific error handling for the best user experience.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by fernando-s97** [comment]
@felangel Sorry for the late reply. 

Below is how I'm doing now. I'm not sure how your answer would help me. Sorry if I've missed something.

**State**

```dart
@freezed
abstract class MyState with _$MyState {
  const factory MyState({
    @required int count,
    // Every state I wanna show an error, I need a property like this
    String error,
  }) = _MyState;

  factory MyState.initial() => const MyState(count: 0);
}
```

**Bloc**

```dart
class MyBloc extends Bloc<MyEvent, MyState> {
  final MyRepository _repo;
  
  MyBloc(final this._repo) : super(MyState.initial());

  @override
  Stream<MyState> mapEventToState(MyEvent event) async* {
    // This is necessary in order to the error don't show on every state change, 
    // but I dont think it's performatic.
    yield state.copyWith(error: null);

    final String result = await _repo.asyncProcessing();

    if (result == condition1) {
      yield state.copyWith(count: state.count + 1);
    } else if (result == condition2) {
      yield state.copyWith(count: state.count - 1);
    } else {
      yield state.copyWith(error: 'some error');
    }
  }
}
```

**UI**

```dart
@override
Widget build(BuildContext context) {
  return BlocListener<MyBloc, MyState>(
    listener: (_, __) {},
    listenWhen: (previous, current) {
      if (previous.error == null && current.error != null) {
        Scaffold.of(context).showSnackbar(Snackbar(current.error));
      }
      ...
    },
    child: ...,
  );
}
```
