### ISSUE TITLE
Stream Variation

### ISSUE THREAD

**Issue by diazsasak** [felangel/bloc#198]
**Describe the bug**
How to implement different stream variation? like publish subject, behaviour subject and replay subject. in my case, the library look like behave like replay subject?

**To Reproduce**
1. trigger event on page A, state changed
2. open page B, the blocbuilder seem got all the previous event

**Expected behavior**
the previous event at page A is already passed, i don't want it trigger UI change to at page B. the snackbar is showed because of that.

**Comment by felangel** [comment]
Hi @diazsasak 👋 

Thanks for opening an issue! Can you please provide a sample application which illustrates the problem you are having? Thanks! 👍

**Comment by diazsasak** [comment]
Thank you for your attention @felangel 

I use your example "flutter_login" as a sample application with some modification to illustrates my problem.

main.dart: i directly go to login page
`child: MaterialApp(
        home: LoginPage(userRepository: _userRepository),
        // home: BlocBuilder<AuthenticationEvent, AuthenticationState>(
        //   bloc: _authenticationBloc,
        //   builder: (BuildContext context, AuthenticationState state) {
        //     if (state is AuthenticationUninitialized) {
        //       return SplashPage();
        //     }
        //     if (state is AuthenticationAuthenticated) {
        //       return HomePage();
        //     }
        //     if (state is AuthenticationUnauthenticated) {
        //       return LoginPage(userRepository: _userRepository);
        //     }
        //     if (state is AuthenticationLoading) {
        //       return LoadingIndicator();
        //     }
        //   },
        // ),
      ),`

login_bloc.dart: i make login failure
`if (event is LoginButtonPressed) {
      yield LoginLoading();

      // try {
      //   final token = await userRepository.authenticate(
      //     username: event.username,
      //     password: event.password,
      //   );

      //   authenticationBloc.dispatch(LoggedIn(token: token));
      //   yield LoginInitial();
      // } catch (error) {
      yield LoginFailure(error: "error happen");
      // }
    }`

login_form.dart: i create button to go another page
` RaisedButton(
                onPressed:
                    state is! LoginLoading ? _onLoginButtonPressed : null,
                child: Text('Login'),
              ),
              RaisedButton(
                onPressed: () => Navigator.push(context,
                    MaterialPageRoute(builder: (context) => HomePage())),
                child: Text('Home'),`

when error snackbar showed, then i go to another page. when i go back (pop) to login page, the snackbar is showed again. that is my problem, how to make snackbar not showed again?

**Comment by felangel** [comment]
Hey @diazsasak 

Are you able to share a link to the full app so I can run it locally and help debug the issue? It's going to be much harder to help by glancing at code snippets. Thanks! 👍

**Comment by felangel** [comment]
@diazsasak closing for now but feel free to comment with the link to a fully functioning sample app that demonstrates the problem you're having and I'm happy to take a look 👍
