### ISSUE TITLE
BLoC for session events

### ISSUE THREAD

**Issue by enyo** [felangel/bloc#1980]
In the documentation it says:

> Blocs should never directly emit new states. Instead every state change must be output in response to an incoming event within mapEventToState.

I was under the impression, that BLoC should be used everywhere business logic should be abstracted from the UI. How would you suggest to handle session state specific information?

As an example: I have a nav bar, and want to write "Logged in as USERNAME | Logout" or "Sign In!" depending on user state. This state needs to change in response to the session state, so I would have provided the `SessionService` to a `SessionBloc` and used that to control the state by listening to changes on the `SessionService` and emitting new states in my BLoC.

Since that is discouraged, is there another way you would approach this?

**Comment by felangel** [comment]
Hi @enyo 👋 
Thanks for opening an issue!

> Blocs should never directly emit new states.

The above statement refers to the fact that you shouldn't do something like:

```dart
RaisedButton(
  onPressed: () => myBloc.emit(newState),
);
```

You can still have the `SessionBloc` listen to state changes in the `SessionService` and add events internally 👍 
Hope that helps!

**Comment by enyo** [comment]
Great. That's how I understood it. I think that the docs on the website are misleading

> Blocs should never directly emit new states. Instead every state change must be output in response to an incoming event within mapEventToState.

I think that it should be something like:

"New states should only be emitted by blocs themselves. Either as a reaction to an incoming event within `mapEventToState` or because an underlying state changed (e.g.: the user authenticated)."

**Comment by enyo** [comment]
The `emit` function itself also has a `@visibleForTesting` annotation, and the docblock:

> **[emit] should never be used outside of tests.**
> Updates the state of the bloc to the provided [state].
> A bloc's state should only be updated by `yielding` a new `state`
> from `mapEventToState` in response to an event.

I think, it would make sense to change this to `@protected` and change the docblock to say that usually, it should only be used by `mapEventToState` or when responding to other state change events.

**Comment by felangel** [comment]
closing this based on our conversation in #1982 👍
