### ISSUE TITLE
getBloc() & getRepository()

### ISSUE THREAD

**Issue by comerc** [felangel/bloc#1981]
I want to suggest idiomatic useful functions :)

```dart
T getBloc<T extends Cubit<Object>>(BuildContext context) =>
    BlocProvider.of<T>(context);

T getRepository<T>(BuildContext context) => RepositoryProvider.of<T>(context);
```

usage:
```dart
getBloc<LoginCubit>(context).logInWithCredentials();

// ...

SignUpCubit(getRepository<AuthenticationRepository>(context));
```

**Comment by narcodico** [comment]
Hi @comerc 👋

Thanks for the suggestions! There are already existing extension methods on `BuildContext` for this.
You can use `context.read<LoginCubit>()` or `context.read<AuthenticationRepository>()`.

Hope that helps! ✌

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions/comments and I'm happy to continue the conversation 👍
