### ISSUE TITLE
Why my second approach is not working

### ISSUE THREAD

**Issue by bobykurniawan11** [felangel/bloc#1986]
Well there is no error message. The problem is when i call the `event` on the `child`, the state is stuck on `FinancialProgress` . But when i run the event from the `parent` it is showing data that i request from my event.

Here is the `parentWidget` (working scenario)

```
 return BlocProvider(
      create: (context) {
        return FinancialBloc(financialRepository: financialRepository)
          ..add(FinancialRequested(store_id: store_id, date: "2020-11-01"));
      },
      child: ReportFinancialScreen(
        store_id: store_id,
      ),
    );
```

with my script above it is working. But when i move the `event caller` to the `child` the state is stuck on `FinancialProgress` . 
```
  return BlocProvider(
      create: (context) {
        return FinancialBloc(financialRepository: financialRepository);
      },
      child: ReportFinancialScreen(
        store_id: store_id,
      ),
    );
```

then here is `ReportFinancialScreen`

  ```
FinancialRepository financialRepository;

  FinancialBloc financialBloc;
  FinancialApi financialApi;
  bool _showSearch = false;
  final _formKey = GlobalKey<FormState>();

  @override
  void initState() {
    financialApi = FinancialApi();
    financialRepository = FinancialRepository(financialApi: financialApi);
    financialBloc = FinancialBloc(financialRepository: financialRepository);
    financialBloc
      ..add(FinancialRequested(store_id: widget.store_id, date: "2020-11-01"));

    super.initState();
  }
...
```

BlocObserver

I/flutter (31594): FinancialRequested
I/flutter (31594): Transition { currentState: FinancialInitial, event: FinancialRequested, nextState: FinancialProgress }
I/flutter (31594): Transition { currentState: FinancialProgress, event: FinancialRequested, nextState: FinancialLoadSuccess }

**Comment by narcodico** [comment]
Hi @bobykurniawan11 👋

That is because you're providing an instance of your bloc like so:
```
create: (context) {
        return FinancialBloc(financialRepository: financialRepository);
      },
```

but then you also create a second instance where you add the event:
```
financialBloc = FinancialBloc(financialRepository: financialRepository);
  financialBloc
    ..add(FinancialRequested(store_id: widget.store_id, date: "2020-11-01"));
```

So your `BlocBuilder` will use the bloc which is provided but that one is not the instance on which you add the event, so it's stuck at your initial state.

Hope that help! ✌

**Comment by bobykurniawan11** [comment]
hi @narcodico ,

Thanks for your answer, it is my first time using that "repository thing", so i thought i need to re-create the instance. It is working fine now, thanks to you
