### ISSUE TITLE
Why you use BlocConsumer?

### ISSUE THREAD

**Issue by thinhhoangnguyen** [felangel/bloc#1988]
I noticed that you use BlocConsumer and in the listener you check if the client scrolls to call _solutionBloc.add (SolutionFetched ());, but in the _onScroll () method you also do things like so. Is this redundant or not?

**Comment by felangel** [comment]
Hi @thinhhoangnguyen 👋 
Thanks for opening an issue!

I'm not sure what you're referring to. Can you please include a link to the code that you're referring to? Thanks 🙏

**Comment by thinhhoangnguyen** [comment]
in post_list.dart, you used  "return BlocConsumer<PostBloc, PostState>(
      listener: (context, state) {
        if (!state.hasReachedMax && _isBottom) {
          _postBloc.add(PostFetched());
        }
      },". And i wonder what do you use listener for? while you were using: "void _onScroll() {
    if (_isBottom) _postBloc.add(PostFetched());
  }" in post_list.dart

**Comment by felangel** [comment]
@thinhhoangnguyen good catch! You're totally right and it's unnecessary 👍 
I removed it as part of https://github.com/felangel/bloc/commit/01f01c2f8ecca2e3170fbaa8a80d90c7c8edd182 😄
