### ISSUE TITLE
'BlocProvider' can't be returned from method 'build'

### ISSUE THREAD

**Issue by Hesham9733** [felangel/bloc#1990]
error: A value of type 'BlocProvider<CounterCubit>' can't be returned from method 'build' because it has a return type of 'Widget'. (return_of_invalid_type at [new_app] lib\src\counter_screen.dart:8)

Using bloc: ^6.1.0 , flutter_bloc: ^6.1.1

![Screenshot 2020-12-04 154929](https://user-images.githubusercontent.com/69996433/101171391-5960e680-3648-11eb-85eb-fbeda33bf857.jpg)
![Screenshot 2020-12-04 154856](https://user-images.githubusercontent.com/69996433/101171395-5a921380-3648-11eb-86c6-2bf7743d009b.jpg)

**Comment by felangel** [comment]
Hi @Hesham9733 👋 
Thanks for opening an issue!

Are you able to share a link to a reproduction sample on GitHub? Thanks 🙏

**Comment by Hesham9733** [comment]
> Hi @Hesham9733 👋 
> Thanks for opening an issue!
> 
> Are you able to share a link to a reproduction sample on GitHub? Thanks 🙏 

I used the counter example in bloc documentations and took the code as it is copy paste and the error still exist so i don't know is that an issue in the VScode and Android Studio on my laptop or else

**Comment by felangel** [comment]
@Hesham9733 can you share the link to the exact code you used?

**Comment by Hesham9733** [comment]
> @Hesham9733 can you share the link to the exact code you used?

https://github.com/felangel/bloc/tree/master/examples/flutter_counter

**Comment by Alecckie** [comment]
**I have been experiencing the exact same issue.**
I too copy pasted (After trying out many different tutorials and getting the same error) the counter code from [Here](https://bloclibrary.dev/#/fluttercountertutorial) and still getting the same error.

You will notice that its not only for this particular code but for any code where we are using **BlocProvider**

I have posted the same question on [StackOverflow here](https://stackoverflow.com/questions/65186310/the-argument-type-blocprovider-cant-be-assigned-to-the-parameter-type-widget/65186820#65186820) no one seems to understand why this is the case.

Here is [The link to my actual codes that produce the error](https://github.com/Alecckie/cubitnogiveup)

![Screenshot 2020-12-08 095849](https://user-images.githubusercontent.com/10174852/101450739-0e8ee980-393c-11eb-8578-78f47c2481ac.jpg)

**Comment by Hesham9733** [comment]
> **I have been experiencing the exact same issue.**
> I too copy pasted (After trying out many different tutorials and getting the same error) the counter code from [Here](https://bloclibrary.dev/#/fluttercountertutorial) and still getting the same error.
> 
> You will notice that its not only for this particular code but for any code where we are using **BlocProvider**
> 
> I have posted the same question on [StackOverflow here](https://stackoverflow.com/questions/65186310/the-argument-type-blocprovider-cant-be-assigned-to-the-parameter-type-widget/65186820#65186820) no one seems to understand why this is the case.
> 
> Here is [The link to my actual codes that produce the error](https://github.com/Alecckie/cubitnogiveup)
> 
> ![Screenshot 2020-12-08 095849](https://user-images.githubusercontent.com/10174852/101450739-0e8ee980-393c-11eb-8578-78f47c2481ac.jpg)

yes it's same issue i got , thought I'm the only one in the world that have this issue as there is no one answered me yet.

**Comment by felangel** [comment]
Can you share the pubspec.yaml?

**Comment by Hesham9733** [comment]
bloc: ^6.1.0 
  flutter_bloc: ^6.1.1

**Comment by felangel** [comment]
@Hesham9733 can you please share the full `pubspec.yaml`?

**Comment by Hesham9733** [comment]
> @Hesham9733 can you please share the full `pubspec.yaml`?

https://github.com/felangel/bloc/blob/master/examples/flutter_counter/pubspec.yaml

**Comment by felangel** [comment]
@Hesham9733 can you try `flutter pub cache repair`? Sounds like you might have accidentally modified code within external packages.

**Comment by Hesham9733** [comment]
> flutter pub cache repair

Thanks so much , That solved the issue ^_^

**Comment by Rajkarnikar-unish** [comment]
Hi is there anyone who's having this same issue?? mine didnt work after trying the solution from @felangel
