### ISSUE TITLE
[Question] How to send an event to a BLoC when navigating to a named route?

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#1995]
Version 6.1.0 deprecated `context.bloc` and introduced `read`, `watch` and `select` instead. I have a question how I can properly send an initial event when I navigate to a named route. So far my strategy was this:
1. My `MaterialApp` used the `routes` property, which is nothing more than a `Map` of `String` (name) -> `WidgetBuilder` (a function building a `Widget`). The routes map looked like this:
```dart
{
  AuthCheckScreen.routeName: (context) {
    context.bloc<AuthBloc>().add(AuthCheckRequested());
    return AuthCheckScreen();
  },
  ...
```
As you can see, when the screen is built, I first send an event to the main BLoC used in it so that it can initialize the screen. I was using the now-deprecated `context.bloc` call. This worked nice and I had no issues with it.

Now I finally got down to removing all the deprecated calls, and this is the only one that is proving harder than expected. When I use `read` I get an error saying

```
Tried to use `context.read<AuthBloc>` inside either a `build` method or the `update` callback of a flutter: provider.
```

I didn't realize that the route-building function is considered to be the same as any other `Widget.build` or `State.build`, so my previous code may have been wrong. However, how should I do it properly? I see 2 obvious options:
1. Use `context.watch` or `BlocProvider.of(context)`, but I'm not sure I like either: I don't want the route to be rebuilt when the state changes, the widget it 'hosts' will be rebuilt if needed, but it doesn't matter for the route.
2. `BlocProvider.of` seems to be kind-of deprecated (is it really?) and it actually does exactly the same thing as `read`/`watch` (which actually delegate to it with `listen` being `false` and `true`, respectively), barring a couple of assertions.

On a more general note, what is the canonical way of doing what I want to do - send an event right before a named route is navigated to?

**Comment by felangel** [comment]
Hi @wujek-srujek 👋 
Thanks for opening an issue!

In this case you can use `BlocProvider.of<AuthBloc>(context).add(AuthCheckRequested());`. `BlocProvider.of` is not deprecated and it should be used in cases like this one where you want to override the `read` exception. I also think it's worthwhile to raise this as an issue in `package:provider` because the read extension errors are produced by provider and maybe there's an opportunity to improve them in this case since the route builder isn't directly in the `build` method.

Let me know if that helps 👍

**Comment by wujek-srujek** [comment]
Thanks, will do.

Where would YOU put such one-off event sending?

**Comment by felangel** [comment]
@wujek-srujek sorry for the delayed response! In this case I think it's cleaner for the `AuthCheckScreen ` to add the event in `initState`.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
