### ISSUE TITLE
Pagination with bloc Using Firebase Cloud Firestore

### ISSUE THREAD

**Issue by eliudio** [felangel/bloc#1997]
Hi,

ones again, thank you very much for - in my opinion - the top flutter project available. I use your implementation of bloc in all my apps. So, I'm very pleased with your work.

I have a question regarding paginating with bloc.

Currently when I have a list of data from e.g. firestore (my main storage), I follow the pattern which is illustrated in your example https://github.com/felangel/bloc/tree/master/examples/flutter_firestore_todos. This works perfectly fine. However, today I want to implement a feed, like an instagram feed. This could become a huge feed and hence some sort of paginating / load-more type of loading of the feed is required. For this I was looking at another example:  https://github.com/felangel/bloc/tree/master/examples/flutter_firestore_todos However, that doesn't necessarily seem to do what I was hoping it would do. Well, perhaps it does, but I have 2 questions

1) Memory
I'm a bit concerned with respect to memory usage.  If I look at the post state, ie https://github.com/felangel/bloc/blob/master/examples/flutter_infinite_list/lib/posts/bloc/post_state.dart, then I can see that eventually the entire list will be in memory. Is that going to blow up memory? Is there no way out of this, e.g. only have items in memory that are displayed?

2) Listen
I quite like my original implementation as it listens to the data and automatically populates the list when items are inserted, e.g. in another app, through a web version of the app. I quite like that and the infinite_list implementation doesn't do this. Is there a way to have a firestore listener which limits the data and hence we could implement a combination of the examples todos+infitite_list?

If you have pointers, snippets of code or perhaps even a bloc implementation, that would be massively appreciated.

Many thanks,

Eliud

**Comment by felangel** [comment]
Hi @eliudio 👋 
Thanks for opening an issue and for the positive feedback! I really appreciate it 🙏 

1. Memory

Yes, with the current approach eventually memory will be a concern but I believe you can use [queryCursors](https://firebase.google.com/docs/firestore/query-data/query-cursors) to paginate the data in firestore so that the bloc is only maintaining the current page in memory.

2. Listen

I don't think there's a FirestoreListener widget so I think you will need to query and expose a stream of data from the repository and consume that via the bloc (via an internal listener within the bloc/cubit).

Let me know if that helps 👍

**Comment by eliudio** [comment]
Hi @felangel 

thanks for your feedback. Wrt memory: I think I understand, but my preference still goes to using a realtime listener of course.

Wrt to your comments on listen, I'm not sure if I follow, but that's possibly because of my lack of understanding, or possibly because my initial question wasn't entirely clear... To avoid the latter, let me share the below:

I have 

  final PostRepository _postRepository;
  StreamSubscription _postsListSubscription;

Where PostRepository is:

typedef PostModelTrigger(List<PostModel> list);

abstract class PostRepository {
  Future<PostModel> add(PostModel value);
  Future<void> delete(PostModel value);
  Future<PostModel> get(String id);
  Future<PostModel> update(PostModel value);
  Stream<List<PostModel>> values(String currentMember);
  Stream<List<PostModel>> valuesWithDetails(String currentMember);
  Future<List<PostModel>> valuesList(String currentMember);
  Future<List<PostModel>> valuesListWithDetails(String currentMember);
  StreamSubscription<List<PostModel>> listen(String currentMember, PostModelTrigger trigger, { String orderBy, bool descending });
  StreamSubscription<List<PostModel>> listenWithDetails(String currentMember, PostModelTrigger trigger);
  void flush();

  Future<void> deleteAll();
}


I have various implementations of this interface, like a fireftore implementation, as well as js-firestore allowing my app to work in web and android, as well as a cached version, allowing to limit database access when not needed. Anyway, that's not the topic of this conversation.

The firestore implementation of listen is:

  StreamSubscription<List<PostModel>> listen(String currentMember, PostModelTrigger trigger, { String orderBy, bool descending }) {
    Stream<List<PostModel>> stream;
    if (orderBy == null) {
       stream = PostCollection.where('readAccess', arrayContainsAny: [currentMember, 'PUBLIC']).snapshots().map((data) {
        Iterable<PostModel> posts  = data.documents.map((doc) {
          PostModel value = _populateDoc(doc);
          return value;
        }).toList();
        return posts;
      });
    } else {
      stream = PostCollection.orderBy(orderBy, descending: descending).where('readAccess', arrayContainsAny: [currentMember, 'PUBLIC']).snapshots().map((data) {
        Iterable<PostModel> posts  = data.documents.map((doc) {
          PostModel value = _populateDoc(doc);
          return value;
        }).toList();
        return posts;
      });
  
    }
    return stream.listen((listOfPostModels) {
      trigger(listOfPostModels);
    });
  }


I use this interface inside my bloc.

  Stream<PostListState> _mapLoadPostListToState({ String orderBy, bool descending }) async* {
    _postsListSubscription?.cancel();
    _postsListSubscription = _postRepository.listen(_currentMember(),  (list) => add(PostListUpdated(value: list)), orderBy: orderBy, descending: descending);
  }

That listens realtime to my data. Unfortunatly, it listens to ALL data, including the 4 billion posts a person has in the db. I would like to resolve this problem.

**Comment by ofury** [comment]
hi @eliudio 
Initially you can limit the number of documents retrieved using limit() and save the last DocumentSnapshot.
As a user scrolls, retrieve documents using startAfterDocument() passing the last document snap and add new data to state. 
Also you can check snapshot.size to determine if db has more data to fetch.
Hope this helps :)

**Comment by eliudio** [comment]
Thanks
