### ISSUE TITLE
Minor Readme issue 

### ISSUE THREAD

**Issue by SilverBirchh** [felangel/bloc#2]
Just want to say this is a great package and has been really helpful in helping me implement the bloc pattern.

I think I noticed a really small mistake in the Readme.
Where it says `yield LoginState.error(error.toString());` (unsure of the actual line number) I think it should be `yield LoginState.failure(error.toString());`. 

If that's the case, happy to raise a PR if you want me to?

**Comment by felangel** [comment]
Thanks so much for the feedback! You’re right about the documentation error and it’d be great if you can open a PR.
