### ISSUE TITLE
BlocListener is fired multiple times with same state

### ISSUE THREAD

**Issue by madhuflutter** [felangel/bloc#2006]
**Describe the bug**
BlocListener is fired multiple times with same state
**To Reproduce**
1. Attached sample project in github https://github.com/madhuflutter/bloc_listener_poc
2. Click (tap) search text field on home page, navigates to search screen and displays suggestions
3. Select (tap) a suggestion, navigates to search_results screen and displays searched products
4. Click (tap) search text field on search_results screen, navigates to search screen and displays suggestions
5. Select (tap) a suggestion, navigates to search_results screen and displays searched products
6. Repeat step 4 and 5
**Expected behavior**
BlocListener should have fired only once with SearchResultsState in search screen and navigate to search_results only once

**Screenshots**

**Logs **
No errors but info
flutter analyze
Analyzing snapsale_poc...

   info - 'bloc' is deprecated and shouldn't be used. Use context.read or context.watch instead. Will be removed in v7.0.0 - bloc_listener_poc\lib\screens\app_bar.dart:24:19 - deprecated_member_use
   info - 'bloc' is deprecated and shouldn't be used. Use context.read or context.watch instead. Will be removed in v7.0.0 - bloc_listener_poc\lib\screens\app_bar.dart:30:17 - deprecated_member_use
   info - 'bloc' is deprecated and shouldn't be used. Use context.read or context.watch instead. Will be removed in v7.0.0 - bloc_listener_poc\lib\screens\app_bar.dart:38:19 - deprecated_member_use
   info - 'bloc' is deprecated and shouldn't be used. Use context.read or context.watch instead. Will be removed in v7.0.0 - bloc_listener_poc\lib\screens\app_bar.dart:43:16 - deprecated_member_use
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: HomeView._editingController -
          bloc_listener_poc\lib\screens\home_view.dart:4:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: SearchResultsView._editingController -
          bloc_listener_poc\lib\screens\search_results_view.dart:5:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its instance fields aren't final: SearchView._editingController -
          bloc_listener_poc\lib\screens\search_view.dart:7:7 - must_be_immutable
   info - 'bloc' is deprecated and shouldn't be used. Use context.read or context.watch instead. Will be removed in v7.0.0 - bloc_listener_poc\lib\screens\search_view.dart:39:23 - deprecated_member_use
   info - 'bloc' is deprecated and shouldn't be used. Use context.read or context.watch instead. Will be removed in v7.0.0 - bloc_listener_poc\lib\screens\search_view.dart:67:27 - deprecated_member_use

9 issues found. (ran in 1.7s)
Paste the output of running `flutter doctor -v` here.

**Additional context**
I placed print statements at few places to understand the execution pattern, here is output in debug console

Launching lib\main.dart on sdk gphone x86 in debug mode...
 lib\main.dart
√ Built build\app\outputs\flutter-apk\app-debug.apk.
I/Choreographer(23140): Skipped 73 frames!  The application may be doing too much work on its main thread.
Connecting to VM Service at ws://127.0.0.1:57642/NgewS80Uo2A=/ws
I/flutter (23140): inside router with /
I/flutter (23140): SearchBloc StartSearchBlocEvent
I/flutter (23140): SearchBloc SearchTapEvent
I/flutter (23140): inside router with /search
W/IInputConnectionWrapper(23140): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(23140): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(23140): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(23140): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(23140): endBatchEdit on inactive InputConnection
I/flutter (23140): Transition { currentState: SearchNoState, event: StartSearchBlocEvent, nextState: SearchNoState }
I/flutter (23140): Change { currentState: SearchNoState, nextState: SearchNoState }
I/flutter (23140): Transition { currentState: SearchNoState, event: SearchTapEvent, nextState: SearchSuggestionsState }
I/flutter (23140): Change { currentState: SearchNoState, nextState: SearchSuggestionsState }
I/flutter (23140): search view builder function
I/flutter (23140): search suggestions build function
I/flutter (23140): search view. state is SearchSuggestionsState
I/flutter (23140): SearchBloc SearchProductsEvent
I/flutter (23140): Transition { currentState: SearchSuggestionsState, event: SearchProductsEvent, nextState: SearchInProgressState }
I/flutter (23140): Change { currentState: SearchSuggestionsState, nextState: SearchInProgressState }
I/flutter (23140): Transition { currentState: SearchInProgressState, event: SearchProductsEvent, nextState: SearchResultsState }
I/flutter (23140): Change { currentState: SearchInProgressState, nextState: SearchResultsState }
I/flutter (23140): search view listener. state is SearchResultsState
I/flutter (23140): search view. state is else
I/flutter (23140): SearchBloc StartSearchBlocEvent
I/flutter (23140): inside router with /search_results
I/flutter (23140): Transition { currentState: SearchResultsState, event: StartSearchBlocEvent, nextState: SearchNoState }
I/flutter (23140): Change { currentState: SearchResultsState, nextState: SearchNoState }
I/flutter (23140): search results view builder function
I/flutter (23140): search results view - search products list builder function
I/flutter (23140): search view. state is else
I/flutter (23140): SearchBloc SearchTapEvent
I/flutter (23140): inside router with /search
I/flutter (23140): Transition { currentState: SearchNoState, event: SearchTapEvent, nextState: SearchSuggestionsState }
I/flutter (23140): Change { currentState: SearchNoState, nextState: SearchSuggestionsState }
W/IInputConnectionWrapper(23140): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(23140): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(23140): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(23140): endBatchEdit on inactive InputConnection
I/flutter (23140): search view builder function
I/flutter (23140): search suggestions build function
I/flutter (23140): search view. state is SearchSuggestionsState
I/flutter (23140): search view. state is SearchSuggestionsState
W/IInputConnectionWrapper(23140): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(23140): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(23140): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(23140): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(23140): endBatchEdit on inactive InputConnection
I/flutter (23140): SearchBloc SearchProductsEvent
I/flutter (23140): Transition { currentState: SearchSuggestionsState, event: SearchProductsEvent, nextState: SearchInProgressState }
I/flutter (23140): Change { currentState: SearchSuggestionsState, nextState: SearchInProgressState }
I/flutter (23140): Transition { currentState: SearchInProgressState, event: SearchProductsEvent, nextState: SearchResultsState }
I/flutter (23140): Change { currentState: SearchInProgressState, nextState: SearchResultsState }
I/flutter (23140): search view listener. state is SearchResultsState
I/flutter (23140): search view listener. state is SearchResultsState
I/flutter (23140): search view. state is else
I/flutter (23140): search view. state is else
I/flutter (23140): SearchBloc StartSearchBlocEvent
I/flutter (23140): inside router with /search_results
I/flutter (23140): SearchBloc StartSearchBlocEvent
I/flutter (23140): inside router with /search_results
I/flutter (23140): Transition { currentState: SearchResultsState, event: StartSearchBlocEvent, nextState: SearchNoState }
I/flutter (23140): Change { currentState: SearchResultsState, nextState: SearchNoState }
I/flutter (23140): search results view builder function
I/flutter (23140): search results view - search products list builder function
I/flutter (23140): search results view builder function
I/flutter (23140): search results view - search products list builder function
I/flutter (23140): search view. state is else
I/flutter (23140): search view. state is else
I/flutter (23140): SearchBloc SearchTapEvent
I/flutter (23140): inside router with /search
I/flutter (23140): Transition { currentState: SearchNoState, event: SearchTapEvent, nextState: SearchSuggestionsState }
I/flutter (23140): Change { currentState: SearchNoState, nextState: SearchSuggestionsState }
W/IInputConnectionWrapper(23140): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(23140): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(23140): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(23140): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(23140): endBatchEdit on inactive InputConnection
I/flutter (23140): search view builder function
I/flutter (23140): search suggestions build function
I/flutter (23140): search view. state is SearchSuggestionsState
I/flutter (23140): search view. state is SearchSuggestionsState
I/flutter (23140): search view. state is SearchSuggestionsState
W/IInputConnectionWrapper(23140): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(23140): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(23140): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(23140): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(23140): endBatchEdit on inactive InputConnection
I/flutter (23140): SearchBloc SearchProductsEvent
I/flutter (23140): Transition { currentState: SearchSuggestionsState, event: SearchProductsEvent, nextState: SearchInProgressState }
I/flutter (23140): Change { currentState: SearchSuggestionsState, nextState: SearchInProgressState }
I/flutter (23140): Transition { currentState: SearchInProgressState, event: SearchProductsEvent, nextState: SearchResultsState }
I/flutter (23140): Change { currentState: SearchInProgressState, nextState: SearchResultsState }
I/flutter (23140): search view listener. state is SearchResultsState
I/chatty  (23140): uid=10152(com.example.bloc_listener_poc) 1.ui identical 1 line
I/flutter (23140): search view listener. state is SearchResultsState
I/flutter (23140): search view. state is else
I/chatty  (23140): uid=10152(com.example.bloc_listener_poc) 1.ui identical 1 line
I/flutter (23140): search view. state is else
I/flutter (23140): SearchBloc StartSearchBlocEvent
I/flutter (23140): inside router with /search_results
I/flutter (23140): SearchBloc StartSearchBlocEvent
I/flutter (23140): inside router with /search_results
I/flutter (23140): SearchBloc StartSearchBlocEvent
I/flutter (23140): inside router with /search_results
I/flutter (23140): Transition { currentState: SearchResultsState, event: StartSearchBlocEvent, nextState: SearchNoState }
I/flutter (23140): Change { currentState: SearchResultsState, nextState: SearchNoState }
I/flutter (23140): search results view builder function
I/flutter (23140): search results view - search products list builder function
I/flutter (23140): search results view builder function
I/flutter (23140): search results view - search products list builder function
I/flutter (23140): search results view builder function
I/flutter (23140): search results view - search products list builder function
I/flutter (23140): search view. state is else
I/chatty  (23140): uid=10152(com.example.bloc_listener_poc) 1.ui identical 1 line
I/flutter (23140): search view. state is else

**Comment by wuweijian1997** [comment]
input 123 search then input 123 search again.Their state and event change
```
I/flutter (25135): SearchEvent: SearchTypeEvent, SearchState: SearchSuggestionsState
I/flutter (25135): SearchEvent: SearchTypeEvent, SearchState: SearchSuggestionsState
I/flutter (25135): SearchEvent: SearchTypeEvent, SearchState: SearchSuggestionsState
I/flutter (25135): SearchEvent: SearchProductsEvent, SearchState: SearchSuggestionsState
I/flutter (25135): SearchEvent: StartSearchBlocEvent, SearchState: SearchResultsState
I/flutter (25135): SearchEvent: SearchTapEvent, SearchState: SearchNoState

I/flutter (25135): SearchEvent: SearchTypeEvent, SearchState: SearchSuggestionsState
I/flutter (25135): SearchEvent: SearchTypeEvent, SearchState: SearchSuggestionsState
I/flutter (25135): SearchEvent: SearchProductsEvent, SearchState: SearchSuggestionsState
I/flutter (25135): SearchEvent: StartSearchBlocEvent, SearchState: SearchResultsState
I/flutter (25135): SearchEvent: StartSearchBlocEvent, SearchState: SearchNoState

```

State is always changing

**Comment by madhuflutter** [comment]
Thank you for quick reply.

Yes, the state is always changing. 

Here the issue is navigation routing written inside the BlocListener in SearchView is executed multiple times for the same state SearchResultsState. And interesting thing is it happens from 2nd iteration not in first iteration.

I followed below steps:
1. tap on search on Homescreen, navigates to searchview, displays search suggestions

I/flutter ( 5570): SearchBloc StartSearchBlocEvent
I/flutter ( 5570): SearchBloc SearchTapEvent
I/flutter ( 5570): inside router with /search
W/IInputConnectionWrapper( 5570): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 5570): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 5570): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 5570): endBatchEdit on inactive InputConnection
I/flutter ( 5570): Transition { currentState: SearchNoState, event: StartSearchBlocEvent, nextState: SearchNoState }
I/flutter ( 5570): Change { currentState: SearchNoState, nextState: SearchNoState }
I/flutter ( 5570): Transition { currentState: SearchNoState, event: SearchTapEvent, nextState: SearchSuggestionsState }
I/flutter ( 5570): Change { currentState: SearchNoState, nextState: SearchSuggestionsState }
I/flutter ( 5570): search view builder function
I/flutter ( 5570): search suggestions build function
I/flutter ( 5570): search view. state is SearchSuggestionsState

2. select suggestion1 or 2, searches products and navigates to searchresults view

I/flutter ( 5570): SearchBloc SearchProductsEvent
I/flutter ( 5570): Transition { currentState: SearchSuggestionsState, event: SearchProductsEvent, nextState: SearchInProgressState }
I/flutter ( 5570): Change { currentState: SearchSuggestionsState, nextState: SearchInProgressState }
I/flutter ( 5570): Transition { currentState: SearchInProgressState, event: SearchProductsEvent, nextState: SearchResultsState }
I/flutter ( 5570): Change { currentState: SearchInProgressState, nextState: SearchResultsState }
I/flutter ( 5570): search view listener. state is SearchResultsState
I/flutter ( 5570): search view. state is else
I/flutter ( 5570): SearchBloc StartSearchBlocEvent
I/flutter ( 5570): inside router with /search_results
I/flutter ( 5570): Transition { currentState: SearchResultsState, event: StartSearchBlocEvent, nextState: SearchNoState }
I/flutter ( 5570): Change { currentState: SearchResultsState, nextState: SearchNoState }
I/flutter ( 5570): search results view builder function
I/flutter ( 5570): search results view - search products list builder function
I/flutter ( 5570): search view. state is else

_search view listener. state is SearchResultsState_ is print statement written inside bloc listener and with in if condition. Here search view listener. state is SearchResultsState is printed once and navigation to search results happend once. It is expected and no issues for first iteration.

Lets start second iteration

3. tap on search in search results view
I/flutter ( 5570): SearchBloc SearchTapEvent
I/flutter ( 5570): inside router with /search
I/flutter ( 5570): Transition { currentState: SearchNoState, event: SearchTapEvent, nextState: SearchSuggestionsState }
I/flutter ( 5570): Change { currentState: SearchNoState, nextState: SearchSuggestionsState }
W/IInputConnectionWrapper( 5570): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 5570): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 5570): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 5570): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 5570): endBatchEdit on inactive InputConnection
I/flutter ( 5570): search view builder function
I/flutter ( 5570): search suggestions build function
I/flutter ( 5570): search view. state is SearchSuggestionsState
W/IInputConnectionWrapper( 5570): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 5570): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 5570): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 5570): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper( 5570): endBatchEdit on inactive InputConnection

4. select a suggestion (1 or 2), navigates to search results view. 

I/flutter ( 5570): SearchBloc SearchProductsEvent
I/flutter ( 5570): Transition { currentState: SearchSuggestionsState, event: SearchProductsEvent, nextState: SearchInProgressState }
I/flutter ( 5570): Change { currentState: SearchSuggestionsState, nextState: SearchInProgressState }
I/flutter ( 5570): Transition { currentState: SearchInProgressState, event: SearchProductsEvent, nextState: SearchResultsState }
I/flutter ( 5570): Change { currentState: SearchInProgressState, nextState: SearchResultsState }
I/flutter ( 5570): search view listener. state is SearchResultsState
I/flutter ( 5570): search view. state is else
I/flutter ( 5570): SearchBloc StartSearchBlocEvent
I/flutter ( 5570): inside router with /search_results
I/flutter ( 5570): SearchBloc StartSearchBlocEvent
I/flutter ( 5570): inside router with /search_results
I/flutter ( 5570): Transition { currentState: SearchResultsState, event: StartSearchBlocEvent, nextState: SearchNoState }
I/flutter ( 5570): Change { currentState: SearchResultsState, nextState: SearchNoState }
I/flutter ( 5570): search results view builder function
I/flutter ( 5570): search results view - search products list builder function
I/flutter ( 5570): search results view builder function
I/flutter ( 5570): search results view - search products list builder function
I/flutter ( 5570): search view. state is else

In 2nd iteration also, search view listener. state is SearchResultsState is printed once but the routing (written inside bloclistener) to search results happened 2 times (inside router with /search_results is printed twice).

Likewise, repeat step 3 and 4, and execution of navigation step (written inside bloclistener) gets executed multiple times.

**Comment by madhuflutter** [comment]
Any update please?

**Comment by wuweijian1997** [comment]
![image](https://user-images.githubusercontent.com/29529286/103601082-db904380-4f43-11eb-8ba5-179a0ef42640.png)
![image](https://user-images.githubusercontent.com/29529286/103601111-eb0f8c80-4f43-11eb-8931-a6e41784f0ae.png)

Each time you click `TextField`, an additional `SearchView` page will be created in the routing stack.
![image](https://user-images.githubusercontent.com/29529286/103601264-3b86ea00-4f44-11eb-8659-a939f97300d5.png)

The reason why you call it many times is because you have created multiple `SearchView`.

```
3.tap on search in search results view
```
You will create one more `SearchPage` each time in step 3.

**Comment by wuweijian1997** [comment]
It's not about the library, it's about your own business logic.I hope it helps you.

**Comment by madhuflutter** [comment]
> It's not about the library, it's about your own business logic.I hope it helps you.

I am new to Flutter. I tried to understand what is wrong with my logic. Can you please help me correcting it.

**Comment by rahuloexe** [comment]
@felangel  Please suggest how to overcome this , if we are pushing same screen again and using bloclistener on that page. so that it will not called multiple time.
