### ISSUE TITLE
Hello, I want to know what is the role of Cubit's _emitted?

### ISSUE THREAD

**Issue by wuweijian1997** [felangel/bloc#2007]
```
abstract class Cubit<State> extends Stream<State> {
  ///What problem does it solve?
  bool _emitted = false;

  void emit(State state) {
    ...
    if (state == _state && _emitted) return;
    ...
    _emitted = true;
  }
}
```

**Comment by felangel** [comment]
Hi @wuweijian1997 👋 
Thanks for opening an issue!

This change was made to allow blocs and cubits to emit their initial state which would enable things like rehydrating the state upon initialization and notifying all listeners.

You can see https://github.com/felangel/bloc/commit/da9e2699d8c4023d5282075126e82f84228fd024 for more details 👍
