### ISSUE TITLE
[QUESTION] Dealing with multiple futures.

### ISSUE THREAD

**Issue by werexzenok** [felangel/bloc#2013]
I'm creating an app in which the user will be able to load multiple images and see them as thumbnails.
I'm using a future function called ".getBytes();" and a FutureBuilder to load them in a Image.memory() widget after they are completely loaded.
I'm using a bloc builder and one bloc to build and manage the state of the entire screen. The problem I already identified is that every time the bloc changes it's state, the FutureBuilder will fire and reload the image.
This problem would be easy to solve by saving the result of the future in the state of the bloc. But I think it's not ideal for performance to load multiple images in RAM. So I came up with 3 ways I could solve that, but I can't decide which one would be the most adequate solution:

1-Find a way to stop the bloc from re-building the images after they loaded for the first time. That would be ideal because I would let the optimization problem to Flutter deal with, but I can't find a _BloChy_ a way to do that. I already tried creating a nested bloc builder just for the FutureBuilder and changing the "buildWhen" parameter. But I had no success.

2-Load the images inside the BloC, manually resize and save them inside the state of the bloc.

3-Use AsyncMemoizer dart class. But I think it would also load the whole image in the memory causing performance issues.

Thank you guy for the support.
I struggled a lot with bloc and I couldn't find any other place more helpful than here.

**Comment by felangel** [comment]
Hi @werexzenok 👋 
Thanks for opening an issue!

I would recommend loading the images within the bloc and managing them as part of the bloc state. You should probably still do any resizing in the UI layer (since it's presentation logic) but none of that should be async or require a FutureBuilder ideally. Let me know if that helps 👍

**Comment by werexzenok** [comment]
Thank you for your reply!
I managed to do the trick by using a widget provided by the thid-party library I'm using.
You helped me a lot by keeping me away from futures. Thanks!

For curiosity sake, what do you define as "presentation logic"?
I'm doing everything inside the bloc. Part of my app contains a gallery copy-cat and even the _selection logic_ I'm doing inside the bloc. Am I doing it wrong? Should I do these things in cubits, instead?

**Comment by felangel** [comment]
@werexzenok glad you were able to figure it out!

In my opinion, presentation logic is any logic that is strictly related to how data is presented. A good rule of thumb to ensure presentation logic stays in the UI is to make sure you don't have any flutter imports in your blocs and cubits. Blocs and cubits should be pure dart and decoupled from the UI layer.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
