### ISSUE TITLE
Same events added but doesn't get dispatched

### ISSUE THREAD

**Issue by MohammedAlimoor** [felangel/bloc#2015]
hello there 

I have a problem when I try to add the same event  
the event does not dispatch if the previous  event not finish

**Comment by II11II** [comment]
Hi @MohammedAlimoor,
The queue logic is default for this case, but you can override method which answer to this functionalities.
If I understood your problem correctly, please look these methods **asyncExpand** or/and **transformEvents**.
I hope this will help you.

**Comment by felangel** [comment]
Hi @MohammedAlimoor 👋 
Thanks for opening an issue!

This is the default behavior of bloc but you can override the behavior by overriding `transformEvents` as @II11II mentioned.

Closing for now but feel free to provide a reproduction example if you're still having trouble and I'm happy to continue the conversation 👍
