### ISSUE TITLE
Infinite list example, hasReachedMax has incorrect logic

### ISSUE THREAD

**Issue by djensen47** [felangel/bloc#2016]
https://github.com/felangel/bloc/blob/46a4699f24ff64f2c5cae2d30fb78b07a37c3ae4/examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart#L80

should be 

```dart
bool _hasReachedMax(int postsCount) => postsCount < _postLimit ? false : true;
```

**Comment by djensen47** [comment]
If you want, I can submit a quick PR for this.

**Comment by felangel** [comment]
Thanks for pointing this out! Should be fixed now 🎉
