### ISSUE TITLE
[Question] Where could I check the doc for flutter_bloc 3.2.0.

### ISSUE THREAD

**Issue by sephrouse** [felangel/bloc#2017]
**Is your feature request related to a problem? Please describe.**
Both flutter_bloc 3.2.0 and bloc 3.0.0 are used in a repo. This repo has not been maintained for a long period. Just found that the current version of flutter bloc is 6.x. Also the online doc is for 6.x version too.

As is stands now, I have to utilize flutter_bloc 3.2.0 to add a new feature for the repo. However, cannot find the flutter bloc doc for version 3.2.0 online, which impacts the progress of the implementation of the new feature.

**Describe the solution you'd like**
Could you please provide where could I find and read the doc for flutter_bloc 3.2.0?

**Describe alternatives you've considered**
As there is no migration guide for 3.2.0 to 6.x in online doc, how to migrate the flutter_bloc from 3.2.0 to 6.0.0?

**Additional context**
None.

**Comment by felangel** [comment]
Hi @sephrouse 👋 
Thanks for opening an issue!

You can checkout the v3.2.0 tag and run the docs locally:

1. `git clone git@github.com:felangel/bloc.git`
2. `git checkout flutter_bloc-v3.2.0`
3. `cd docs &&  python3 -m http.server 8080`

Regarding the migration I would highly recommend looking at the [CHANGELOG](https://github.com/felangel/bloc/blob/master/packages/flutter_bloc/CHANGELOG.md) and join the [discord server](https://discord.gg/Hc5KD3g). That way you can ask migration questions and get answers much faster.

Hope that helps 👍
