### ISSUE TITLE
添加事件后,不能收到事件

### ISSUE THREAD

**Issue by hu70258tao** [felangel/bloc#2018]
在Bloc里有如下代码:
Stream xx;
xx.listen({
   (data)=>add(SomeEvent(data))
});
我发现在执行add(SomeEvent(data))时,没有立马收到该事件,当我停止listen的时候,才匹配到大量的Event
![image](https://user-images.githubusercontent.com/20218008/102196767-4cbb7880-3efb-11eb-801f-2b7ceb32c635.png)
![image](https://user-images.githubusercontent.com/20218008/102196893-6e1c6480-3efb-11eb-9a4e-73e0ea2db430.png)
![image](https://user-images.githubusercontent.com/20218008/102197266-de2aea80-3efb-11eb-8600-9aa27925a5aa.png)

**Comment by hu70258tao** [comment]
就像这样
![image](https://user-images.githubusercontent.com/20218008/102197942-c0aa5080-3efc-11eb-985e-b69aa92334eb.png)
只有listen结束后,才能在mapEventToState方法里收到event

**Comment by felangel** [comment]
Hi @hu70258tao 👋 
Thanks for opening an issue!

Can you please edit your issue to be in english? I am having a hard time understanding the problem.

**Comment by zombiu** [comment]
Translate it into English, little brother

**Comment by cervonwong** [comment]
_My translation:_

There is code like this in my Bloc:
```
Stream xx;
xx.listen({
(data) => add(SomeEvent(data))
});
```
I found that when calling `add(SomeEvent(data))`, [the Bloc] does not receive the events immediately. When i stopped `listen`, then a huge amount of events are received.
[image]
[image]
[image]

Here's an example:
[image]
Only after `listen` completes, then the `mapEventToState` method receives the events.

**Comment by wuweijian1997** [comment]
mapEventToState 应该是 async* + yield吧,你的是,async* + yield*,是不是这个问题?除非你贴个最小可运行demo,不然这样很难找问题的.

**Comment by hu70258tao** [comment]
我找到原因了,我在处理某次add时间,有while-delay操作,发生了阻塞.

**Comment by hu70258tao** [comment]
十分感谢你们的反馈

**Comment by hu70258tao** [comment]
我在处理每个事件的时候,又产生了一个新事件,在处理新事件的时候,进行了循环延时的操作,导致新事件后的添加的事件,都被阻塞了.我之所以这么操作是因为偷懒,在页面想显示一个倒计时,后来改用AnimationController来控制,就正常了.
