### ISSUE TITLE
Show dialog using BlocListner 

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2021]
Hi @felangel ,
Please if it is possible could you show how to show dialog in bloclistener in 2nd page when from 1st page navigated to 2nd page?

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

If you just want to show a dialog immediately after navigating you don't need a bloc to do that. Can you please provide a link to a sample app which illustrates the issue you're facing? Thanks 🙏

**Comment by II11II** [comment]
class Page1 extend StatelessWidget{
@override
  Widget build(BuildContext context)=>RaisedButton(
 onPressed:()=>Navigator.push(context,
                                    MaterialPageRoute(
                                        builder: (context) =>  BlocProvider<FeatureIn2PageCubit>(
                      create: (BuildContext context) =>
                          FeatureIn2PageCubit()..showDialogByEmitingLoadingState(),
                      child: TournamentsPage())) )
 )
}

class Page2 extend StatelessWidget{
@override
  Widget build(BuildContext context)=>BlocListener<FeatureIn2PageState,FeatureIn2PageCubit>(child:Container(),
  listener:(context,state){
  if(state is Loading){
showDialog();
        }
  }
  )
}

//showDialogByEmitingLoadingState() this method in Cubit, and it is future method or not future method

**Comment by II11II** [comment]
https://user-images.githubusercontent.com/45257709/102886593-33747800-4477-11eb-8301-4cce30165681.mp4

I gonna implement loading popup feature when opened new page as in video

**Comment by II11II** [comment]
Finally, i got it.
It is not possible to implement this feature in cubit without awaiting it before emit.
However it is possible in Bloc
