### ISSUE TITLE
Widget tree not rebuild inside ModalBottomSheet

### ISSUE THREAD

**Issue by McCrafterIV** [felangel/bloc#2026]
Hello :)

Opening the modal and building it works fine. Adding events to the bloc also work fine but the changes are not triggering the build function and therefor can't be seen. When I close the modal and reopen it, the changes I made before appear without any error.
For context, the modal is used to select or deselect a list of tags that will be appended to a forum post object. The forum post form is controlled by the `PostFromBloc`. To get the full information of the tags, the `TagActorBloc` is used.
I sadly can't provide a sample project at this point, and can only provide the widget tree that is responsible for the opening of the `ModalBottomSheet` and the `ModalBottomSheet` itself.

```dart
 // get PostBloc from context to later provide it to the modal
    final postBloc = BlocProvider.of<PostBloc>(context);

    return BlocConsumer<PostBloc, PostState>(
      listener: (c, s) {},
      buildWhen: (p, c) => p.post.tags != c.post.tags && c.post.tags != null,
      builder: (postFormBlocContext, postFormBlocState) {
        final List<Widget> tagList = <Widget>[];

        // Null safety checks and loading indicators
        // ....

       for (final UniqueId tagId in postFormBlocState.post.tags) {
            tagList.add(
              BlocProvider(
                create: (context) => getIt<TagActorBloc>()
                  ..add(TagActorEvent.getTagFromGroupById(
                      tagId, postFormBlocState.post.group)),
                child: BlocConsumer<TagActorBloc, TagActorState>(
                  listener: (c, s) {},
                  builder: (tc, ts) => ts.maybeMap(
                    getFromGroupByIdSuccess: (cts) => CustomChipWidget(
                      data: cts.tag.name,
                      color: cts.tag.color,
                      xIcon: false,
                    ),
                    orElse: () => CustomChipLoadingWidget(),
                  ),
                ),
              ),
            );
          }

        return Column(
          children: [
            Wrap(
              alignment: WrapAlignment.start,
              spacing: 8,
              runSpacing: 4,
              children: tagList,
            ),
            SmallButtonWidget(
              onPressed: () => _openModal(postFormBlocContext, postBloc),
              label: translate('postScreen.createPostScreen.addTagButton'),
            ),
          ],
        );
      },
    );
```

The called `_openModal` function:
```dart
   void _openModal(BuildContext context, PostBloc postBloc) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      enableDrag: true,
      isDismissible: true,
      backgroundColor: Colors.transparent,
      builder: (BuildContext context) => BlocProvider<PostBloc>.value(
        value: postBloc,
        child: BlocBuilder<PostBloc, PostState>(
          builder: (postFormBlocModalContext, postFormBlocModalState) {
            print("Rebuild");
            return BlocProvider<TagActorBloc>(
              create: (c) => getIt<TagActorBloc>()
                ..add(TagActorEvent.getAllTagsFromGroup(
                    postFormBlocModalState.post.group)),
              child: BlocBuilder<TagActorBloc, TagActorState>(
                builder: (getAllTagsContext, getAllTagsState) =>
                    getAllTagsState.maybeMap(
                  orElse: () => const CircularProgressIndicator(),
                  getAllTagsFromGroupSuccess: (allTagsState) {
                    // in case of an initial data failure, we show that
                    // we're still fetching the correct data :)
                    if (postFormBlocModalState.post.tags == null) {
                      return const CircularProgressIndicator();
                    }

                    final List<Widget> checkboxTileList = <Widget>[];
                    for (int i = 0; i < allTagsState.tags.length; i++) {
                      final Tag tag = allTagsState.tags[i];
                      checkboxTileList.add(
                        BlocBuilder<PostBloc, PostState>(
                          buildWhen: (p, c) => p.post.tags != c.post.tags,
                          builder: (context, state) => CheckboxListTile(
                            title: Text(
                              tag.name,
                              style: const TextStyle(
                                color: CustomColors.PrimaryText,
                              ),
                            ),
                            value: postFormBlocModalState.post.tags
                                .contains(tag.id),
                            onChanged: (bool value) {
                              final newTagList =
                                  postFormBlocModalState.post.tags;
                              if (value) {
                                newTagList.add(tag.id);
                              } else {
                                newTagList.remove(tag.id);
                              }
                              postBloc.add(PostEvent.tagsUpdated(newTagList));
                            },
                          ),
                        ),
                      );
                    }

                    return CustomBottomSheetWidget(
                      key: UniqueKey(),
                      maxChildSize: 1.0,
                      children: checkboxTileList,
                    );
                  },
                ),
              ),
            );
          },
        ),
      ),
    );
  }
```

For more information: the `CustomBottomSheetWidget` just returns a `DraggableScrollableSheet` with some styling properties and a `Column` with also a `ListView` of the widgets provided using the `children` list.

Thanks for the help!

**Comment by felangel** [comment]
Hi @McCrafterIV 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app on github which reproduces the issue? It would be much easier for me to help and provide suggestions if I can clone and reproduce the issue locally. Thanks 🙏

**Comment by McCrafterIV** [comment]
Thanks for the quick response! I created a test project and my simple example there works. It's probably a fault on my side, maybe because of my bloc implementation. I'll reach out again if I've fixed the issue, can provide a project that reproduces it or have other questions.

**Comment by felangel** [comment]
@McCrafterIV awesome, thanks!
Closing for now but feel to comment with any additional questions comments and I'm happy to continue the conversation 👍

**Comment by McCrafterIV** [comment]
Still haven't figured out how to solve my issue. I think the problem lies in the fact that the widget tree is not rebuild when a new event is processed by the bloc. So I guess the issue lies in the bloc implementation, which is afaik the same as in my other blocs which work perfectly fine. Below you find my bloc implementation with the event- and state classes. I hope you can help me and figure out the issue. Because the other fields like the title can be edited without any problems, the problem should be found in the part that is used for the tags. Because my post would get really long, you can find the code at this gist:
https://gist.github.com/McCrafterIV/10eef4a30cfe0b2824e0a987283c5e34

Thank you for your help.

**Comment by McCrafterIV** [comment]
Due to the complexity of the project, I really can't post more source code because it's probably even then not reproducible. Maybe we could talk or chat about my application (Discord, Telegram etc.) so I can show you @felangel how the project works and can give you login credentials so you can run the app on your machine/device?

**Comment by felangel** [comment]
@McCrafterIV yeah definitely! DM me on [discord](https://discord.gg/Hc5KD3g) 👍

**Comment by McCrafterIV** [comment]
Great thanks!
