### ISSUE TITLE
[Discussion] Question about internal implementation of Bloc

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#2030]
Historically, the `Bloc` implementation has used 2 separate `Subject`s (a long time ago) or `StreamController` (more modern times), one for events, and one for states (e.g. https://github.com/felangel/bloc/blob/bloc-v4.0.0/packages/bloc/lib/src/bloc.dart#L40-L41 in `v4.0.0`). A `Bloc` instance, when created, would subscribe to the event stream and maybe (depending on `operator ==`) add a new state to state sink.

I have been playing around learning things, and noticed that it is possible to implement all (?) of the `Bloc` functionality using just one `StreamController` (sample code at the end). I'm obviously missing something, my code is just a toy sample, that's why I would like to ask what the advantage of using 2 separate controllers is, what is my implementation missing out on that previous* library versions had and what is only possible with 2 controllers?

(*Previous because nowadays the state controller is within `Cubit`, and the event controller within `Bloc`, so I guess there is no way to implement it using only one.)

Code (I implemented my own `BlocBuilder` as well using `StreamBuilder` internally and all of this works just fine even for a complex use case of mine, hence the question about the 2 controllers):

```dart
abstract class Bloc<E, S> extends Stream<S> implements Sink<E> {
  final StreamController<E> _streamController = StreamController<E>.broadcast();

  Stream<S> _states;
  S _state;

  Bloc(this._state) {
    final statesStream = transformEvents(
      _streamController.stream.doOnData(onEvent),
      mapEventToState,
    );
    _states = transformStates(statesStream).distinct().doOnData((newState) {
      onTransition(_state, newState);
      _state = newState;
    });
  }

  @override
  void add(E event) {
    _streamController.add(event);
  }

  S get state => _state;

  @override
  StreamSubscription<S> listen(
    void Function(S) onData, {
    Function onError,
    void Function() onDone,
    bool cancelOnError,
  }) {
    return _states.listen(
      onData,
      onError: onError,
      onDone: onDone,
      cancelOnError: cancelOnError,
    );
  }

  Stream<S> transformEvents(
    Stream<E> events,
    Stream<S> Function(E) convert,
  ) {
    // By default, events are processed sequentially to completion.
    return events.asyncExpand(convert);
  }

  Stream<S> transformStates(Stream<S> statesStream) {
    // By default, states are not transformed.
    return statesStream;
  }

  void onEvent(E event) {}

  void onTransition(S state, S newState) {}

  Future<void> close() {
    return _streamController.close();
  }

  Stream<S> mapEventToState(E event);
}
```

**Comment by wujek-srujek** [comment]
I understand now - separate controllers for events and states are a way of making the BLoC 'hot' - so that it processes the events and changes its state even if there are no subscribes to the states stream. In my solution with just one controller, as long as there are no subscribers, the BLoC will do nothing at all.

Funny, I always though of 'broadcast' controllers as 'hot' but apparently this doesn't apply - the events are not buffered, but not processed either, and it is all documented (facepalm). I have a lot to learn.

**Comment by felangel** [comment]
@wujek-srujek sorry for the delayed response (I've been slow to respond due to the holidays). I'm glad you were able to resolve the issue yourself. Closing for now but feel free to comment with any additional questions you might have 👍
