### ISSUE TITLE
add event triggers only once and won't trigger again for the same bloc in the same widget

### ISSUE THREAD

**Issue by mabdelatief** [felangel/bloc#2031]
i call bloc.add(event) in initState once, and after that anytime i add the event again in the same widget it never gets called, in the debug mode the mapStateToEvent function doesn't even get called. i have this problem in 2 parts of my app, one part with the RefreshIndicator onRefresh function, and the other part whenever i push a detail widget of the post to get and show the comments, it accepts only 1 post, when i try to press on another post after that, nothing happens ! it never gets called ! 
i'm not even getting any errors ! 
here is what i tried so far : 

- i tried not using equatable at all, Not working.
- i tried not to close the bloc in the dispose, Not working.
- i tried making separate state classes, Not working.

**forum_bloc.dart**

` class ForumBloc extends Bloc<ForumEvent, ForumState> {

  ForumBloc(this._forumRepository,this.navigator) : super(ForumState.defaultState());

  final ForumRepository _forumRepository;
  final AppNavigator navigator;

  @override
  Stream<ForumState> mapEventToState(
      ForumEvent event,
      ) async* {
    if (event is GetPostsEvent)  yield* _getPosts(event);
    if (event is GetCommentsEvent) yield* _getComments(event);
    if (event is RefreshPostsEvent)  yield* _refreshPosts(event);
    if (event is RefreshCommentsEvent) yield* _refreshComments(event);
    if (event is NewPostRequest) yield* _newPost(event);
    if (event is NewCommentRequest) yield* _newComment(event);
  }

  Stream<ForumState> _getPosts(GetPostsEvent event) async* {
    print("get posts event called");
    yield state.copyWith(status: BlocStatus.pending);
    try {
      // show progress hud
      final postsResponse = await _forumRepository.getPosts(event.trainerID);

      postsResponse.posts.sort((a, b) => b.datetimeCreated.compareTo(a.datetimeCreated));
      print(postsResponse.posts[0].question);
      yield state.copyWith(posts: postsResponse.posts, status: BlocStatus.success, total: postsResponse.posts.length);

    } on DioError catch (error) {
      // report error
      yield state.copyWith(status: BlocStatus.error, appError: error.toAppError());

    }

  }
  Stream<ForumState> _refreshPosts(RefreshPostsEvent event) async* {

    yield state.copyWith(status: BlocStatus.pending);
    try {
      // show progress hud
      final postsResponse = await _forumRepository.getPosts(event.trainerID);
      print(postsResponse.posts.length);
      postsResponse.posts.sort((a, b) => b.datetimeCreated.compareTo(a.datetimeCreated));
      yield state.copyWith(posts: postsResponse.posts, status: BlocStatus.success, total: postsResponse.posts.length);

    } on DioError catch (error) {
      // report error
      // yield state.copyWith(status: BlocStatus.error, appError: error.toAppError());

    }
  }

  Stream<ForumState> _getComments(GetCommentsEvent event) async* {

    try {
      // show progress hud
      final commentsResponse = await _forumRepository.getComments(event.postID,event.trainerID);

      commentsResponse.post.commentList.sort((a, b) => b.datetimeCreated.compareTo(a.datetimeCreated));
      List<BlogPost> newList = state.posts;
      newList.firstWhere((element) => element.id == event.postID).commentList =commentsResponse.post.commentList;
      yield state.copyWith(posts: newList, status: BlocStatus.success, total: newList.length);
      navigator.push(PostSingle.route(commentsResponse.post));
    } on DioError catch (error) {
      // report error
      yield state.copyWith(status: BlocStatus.error, appError: error.toAppError());

    }
  }} `

**forum_event.dart**

`abstract class ForumEvent extends Equatable  {
    const ForumEvent([List props = const []]) : super();
   }

   class GetPostsEvent extends ForumEvent {
    final String trainerID;
    GetPostsEvent(this.trainerID);
    
    @override
    List<Object> get props => [trainerID];
   }

   class RefreshPostsEvent extends ForumEvent {
    final String trainerID;
    RefreshPostsEvent(this.trainerID);
    
    @override
    List<Object> get props => [trainerID];
   }

   class GetCommentsEvent extends ForumEvent {
    final String postID;
    final String trainerID;
    GetCommentsEvent(this.postID,this.trainerID);

    @override
    List<Object> get props => [postID, trainerID];
   }

   class RefreshCommentsEvent extends ForumEvent {
    final String postID;
    final String trainerID;
    RefreshCommentsEvent(this.postID,this.trainerID);

    @override
    List<Object> get props => [postID, trainerID];
   }

   class SendPostEvent extends ForumEvent {
    final NewPostRequest postRequest;
    SendPostEvent(this.postRequest);

    @override
    List<Object> get props => [postRequest];
   }

   class SendCommentEvent extends ForumEvent {
    final NewCommentRequest commentRequest;
    SendCommentEvent(this.commentRequest);

    @override
    List<Object> get props => [commentRequest];
   }`

**forum_state.dart**

`class ForumState extends Equatable {
  ForumState({
    this.total,
    this.posts,
    this.status,
    this.appError
  });
  final int total;
  final List<BlogPost> posts;
  final BlocStatus status;
  final AppError appError;
  factory ForumState.defaultState() => ForumState(
    total: 0,
    posts: [],
status: BlocStatus.idle,
appError: null
  );
  ForumState copyWith({
    int total,
    List<BlogPost> posts,
    AppError appError,
    BlocStatus status,  }) {  return ForumState(
      total: total ?? this.total,
      posts: posts ?? this.posts,
      status: status,
    );}
  @override
  List<Object> get props => [posts,total,status,appError];

  @override
  bool get stringify => true;
}`

**forum_screen.dart**

`class ForumMain extends StatefulWidget {
  @override
  _ForumMainState createState() => _ForumMainState();
}

class _ForumMainState extends State<ForumMain> {
  TextEditingController nameController = TextEditingController();
  MyTheme myTheme = MyTheme();
  ForumBloc _forumBloc;
  PlanBloc _planBloc;
  Completer<void> _refreshCompleter;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
   myTheme.initLoadingHUD();
    _forumBloc = BlocProvider.of<ForumBloc>(context);
    _planBloc = BlocProvider.of<PlanBloc>(context);
    _forumBloc.add(GetPostsEvent(_planBloc.state.chosenOrder.trainer.id));
    _refreshCompleter = Completer<void>();
  }
  @override
  void dispose() {
_forumBloc.close();
_planBloc.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    ScreenUtil.init(context, width: 375, height: 812, allowFontScaling: true);

    return BlocConsumer<ForumBloc,ForumState>(
        listener: (context, state) {
          print(state.status.toString());
          if (state.status == BlocStatus.success) {
            _refreshCompleter?.complete();
              _refreshCompleter = Completer<void>();

          }
            myTheme.errorBlocListener(context, state.appError);

        },
        cubit: _forumBloc,
        builder: (context, state) {
          return Scaffold(
              backgroundColor: Colors.white,
              appBar: ForumAppBar(
                height: 80.h,
                forum: true,
              ),
              body: state.status == BlocStatus.success ? Stack(
                children: [
                  RefreshIndicator(
                    onRefresh: () {

                        return _refreshCompleter.future;

                    },
                    child: ListView(
                        children: state.posts.map((e) {
                          return GestureDetector(
                            onTap: () {
                              print("post pressed");
                              _forumBloc.add(GetCommentsEvent(e.id, _planBloc.state.chosenOrder.trainer.id, e));
                            },
                            child: PostWidg(
                              post: e,
                              mini: true,
                              reply: false,
                              comment: null,
                            ),
                          );
                        }).toList()),
                  ),
                  myTheme.loadingHUD
                ],
              ) : PostShimmer(comment: false)
          );
        }); }
}`

**forum_model.dart**

`class BlogPost extends Equatable {
  BlogPost(
      {this.id,
        this.initiatingUser,
        this.topic,
        this.question,
        this.datetimeCreated,
        this.commentList,
        this.responseCount});
  final int responseCount;
  final String id;
  final InitiatingUser initiatingUser;
  final String topic;
  final String question;
  final DateTime datetimeCreated;
  final List<Comment> commentList;

  factory BlogPost.fromJson(Map<String, dynamic> json) => BlogPost(
    id: json["id"] == null ? null : json["id"],
    initiatingUser: json["initiating_user"] == null
        ? null
        : InitiatingUser.fromJson(json["initiating_user"]),
    topic: json["topic"] == null ? null : json["topic"],
    question: json["question"] == null ? null : json["question"],
    datetimeCreated: json["datetime_created"] == null
        ? null
        : DateTime.parse(json["datetime_created"]),
    commentList: json["response_list"] == null
        ? null
        : List<Comment>.from(
        json["response_list"].map((x) => Comment.fromJson(x))),
    responseCount:
    json["response_count"] == null ? null : json["response_count"],
  );

  @override
  // TODO: implement props
  List<Object> get props => [id,initiatingUser,topic,question,datetimeCreated,commentList,responseCount];
  @override
  bool get stringify => true;
}

class InitiatingUser extends Equatable {
  InitiatingUser({
    this.id,
    this.firstName,
    this.lastName,
    this.imageUrl,
  });

  final String id;
  final String firstName;
  final String lastName;
  final dynamic imageUrl;

  factory InitiatingUser.fromJson(Map<String, dynamic> json) => InitiatingUser(
    id: json["id"] == null ? null : json["id"],
    firstName: json["first_name"] == null ? null : json["first_name"],
    lastName: json["last_name"] == null ? null : json["last_name"],
    imageUrl: json["image_url"],
  );

  @override
  // TODO: implement props
  List<Object> get props => [id,firstName,lastName,imageUrl];

}

class Comment extends Equatable {
  Comment({
    this.id,
    this.user,
    this.text,
    this.datetimeCreated,
  });

  final int id;
  final InitiatingUser user;
  final String text;
  final DateTime datetimeCreated;

  factory Comment.fromJson(Map<String, dynamic> json) => Comment(
    id: json["id"] == null ? null : json["id"],
    user:
    json["user"] == null ? null : InitiatingUser.fromJson(json["user"]),
    text: json["text"] == null ? null : json["text"],
    datetimeCreated: json["datetime_created"] == null
        ? null
        : DateTime.parse(json["datetime_created"]),
  );

  @override
  // TODO: implement props
  List<Object> get props => [id,user,text,datetimeCreated];
}

**Comment by felangel** [comment]
Hi @mabdelatief 👋 
Thanks for opening an issue!

Can you please provide a link to a github repository which reproduces the issue? It would be much easier for me to help if there is a complete reproduction sample as opposed to a bunch of inline code snippets. Thanks 🙏

**Comment by mabdelatief** [comment]
Hey @felangel , i can share the whole project with you, will be easier and better, can you please send me your gitlab ?

**Comment by mabdelatief** [comment]
Hey @felangel , i solved the problem, i had a Bloc.close() in the dispose of a widget that was never initiated but i tried removing it and now everything works as expected, thanks so much
