### ISSUE TITLE
Feature: Devtools

### ISSUE THREAD

**Issue by jascodes** [felangel/bloc#2032]
Hi @felangel 

First of all great work!! and much appreciate you maintaining package like you do.

One of my humble suggestion would be to maybe support devtool for this package. Below is an to do so using devtools originally made for redux. This can be better vertically integrated in the project itself.

https://pub.dev/packages/flutter_bloc_devtools

Stay Safe
Jas

**Comment by felangel** [comment]
Hi @jascodes 👋 
Thanks for opening an issue and for the positive feedback!

> This can be better vertically integrated in the project itself.

Can you please clarify what you are proposing? I'm not sure I understand the desired outcome of this issue. Thanks! 🙏

**Comment by felangel** [comment]
Closing for now since I'm unsure of what the desired outcome for this issue is. Feel free to comment with additional information and I'm happy to reopen this and continue the conversation 👍
