### ISSUE TITLE
Automatic disposal of added subscriptions on dispose

### ISSUE THREAD

**Issue by cedvdb** [felangel/bloc#2034]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a way to add subscriptions to the cubit  so the subscription cancels on close. I'm open to make a PR if needed.

At the moment you have to dispose yourself:
```
class AuthCubit extends Cubit<AuthState> {
  StreamSubscription<AuthUser> _authUserSubscription;
  AuthAPI _authAPI;

  AuthCubit({AuthAPI authAPI})
      : _authAPI = authAPI,
        super(AuthState.unknown()) {
    _authUserSubscription = authAPI.user$.listen(
      (user) => _onAuthStatusChanged(user),
    );
  }

  _onAuthStatusChanged(AuthUser authUser) {
    if (authUser.authenticated) {
      emit(AuthState.authenticated(userId: authUser.id));
    } else {
      emit(AuthState.unauthenticated());
    }
  }

  signIn(AuthProvider provider) {
    _authAPI.signIn(provider);
  }

  signOut() {
    _authAPI.signOut();
  }

  @override
  Future<void> close() {
    _authUserSubscription?.cancel();
    return super.close();
  }
}

```

**Describe the solution you'd like**
```
  AuthCubit({AuthAPI authAPI})
      : _authAPI = authAPI,
        super(AuthState.unknown()) {
    final authUserSubscription = authAPI.user$.listen(
      (user) => _onAuthStatusChanged(user),
    );
    addSubscription([authUserSubscription]);
  }
```

**Comment by felangel** [comment]
Hi @cedvdb 👋 
Thanks for opening an issue!

I don't think this is necessarily something that should be part of the bloc package. In my opinion, this feature request pertains to any dart code which involves StreamSubscriptions. If you feel the current handling of subscriptions is sub-optimal you could create a new package which defines a `Disposable` mixin like:

```dart
mixin Disposable on Object {
  void dispose() {
    // cancel all internal subscriptions
  }

  void addSubscription(StreamSubscription subscription) {
    // add subscription to internal data structure
  }
}
```

Then you can use this with your blocs:

```dart
class AuthCubit extends Cubit<AuthState> with Disposable {
    AuthCubit({AuthAPI authAPI})
      : _authAPI = authAPI,
        super(AuthState.unknown()) {
    final authUserSubscription = authAPI.user$.listen(
      (user) => _onAuthStatusChanged(user),
    );
    addSubscription([authUserSubscription]);
  }

  Future<void> close() {
    dispose();
    return super.close();
  }
}
```

This solution would address the issue and would also be more broadly applicable to other contexts outside of bloc.
Let me know what you think 👍

**Comment by cedvdb** [comment]
You are right, great idea

**Comment by cedvdb** [comment]
@felangel for info a much simpler solution, since the cubit is a stream is to use rxdart takeUntil

takeUntil(this)

this will close the subscription when the cubit is destroyed

**Comment by cedvdb** [comment]
After using my own Extended cubits for a while I feel like this should be integrated somehow. At least a getter to replace this:

```dart
.takeUntil(Stream.fromFuture(this.stream.drain()))
```

into this

```dart
.takeUntil(destroy$)
```

Yes, mixin or subclass work. However it just seems like such a common use case I feel like it should be added.
