### ISSUE TITLE
Docs: Update Tutorials and Examples to Support Null Safety

### ISSUE THREAD

**Issue by chanreylee** [felangel/bloc#2037]
Now the version is 6.1.0+, but so far bloc docs may not update together, such as flutter_weather tutorials is using with version 5.0.0 of flutter_bloc. There are some differences between tutorials and example codes. Therefore, Could you update the tutorials?  And I think many people would like to see that.
Thank you so much!

**Comment by felangel** [comment]
Hi @chanreylee 👋 
Thanks for opening an issue and sorry for the delayed response!

I'm currently working on migrating the bloc ecosystem to null-safety and plan to go back and update all of the examples and tutorials as soon as that's wrapped up 👍

**Comment by Abhishek01039** [comment]
we have migrated many examples to null safety.
you can refer to the null safety branch for that.
and some of our examples depends on some package which is still not migrated to null safety.
so I and @felangel are thinking about it.

**Comment by ali-thowfeek** [comment]
Hi, @felangel We would love it if you could update the Flutter tutorials to null safety. We really appreciate the time and work you put in ❤️ Thank you. I wish I could help.

**Comment by felangel** [comment]
This should be done now. If there are tutorials that haven't been migrated please create a new issue, thanks! 👍
