### ISSUE TITLE
Creating dependencies for 2 blocs using "GetIt" package

### ISSUE THREAD

**Issue by popay34** [felangel/bloc#2039]
Hello! I create dependencies using "GetIt" with "Injectable" package. Here's my code.
bloc.dart
```
class MyBloc extends Bloc {
  final OtherBloc otherBloc;
  StreamSubscription otherBlocSubscription;

  MyBloc(this.otherBloc) {
    otherBlocSubscription = otherBloc.listen((state) {
        // React to state changes here.
        // Add events here to trigger changes in MyBloc.
    });
  }

  @override
  Future<void> close() {
    otherBlocSubscription.cancel();
    return super.close();
  }
}
```
main.dart
```
runApp(
      BlocProvider<MyBloc>(
        create: (context) => getIt<MyBloc>()
      ),
      child: MaterialApp()   
    )
  )

```
injectionconfig.dart
```
gh.factory<OtherBloc >(() => OtherBloc ());
gh.factory<MyBloc >(() => MyBloc (get<OtherBloc >()));
```
I guess this code won't work correctly. Because this injection does not provide a current contex (current state) of OtherBloc to MyBloc?  If it true, then creating dependencies manually will become very difficult. How to create dependencies using "GetIt" with "Injectable" package it this case?

**Comment by 2shrestha22** [comment]
You can make other bloc singleton and same bloc instance is passed to my bloc.

**Comment by felangel** [comment]
Hi @popay34 👋 
Thanks for opening an issue and sorry for the delayed response!

> I guess this code won't work correctly.
I'm not sure what you mean. Unless I'm missing something I believe the above code should work fine. Can you please provide a link to a github repo which reproduces the issue you're facing and I'm happy to open a pull request with any suggestions, thanks! 🙏
