### ISSUE TITLE
Question: based on both the routing and firebase login examples

### ISSUE THREAD

**Issue by MdeBruin93** [felangel/bloc#2041]
Hi @felangel ,

I'm using your Firebase Login example for my own Firebase login flow in my app. However I'm kinda running into an issue of which I'm not sure how to solve.
On the home screen I have a tabbar which loads the body of the page, but also an appbar.
The appbar has 2 buttons that lead to two other pages. However both of those pages have the same appbar which can result in a huge stack of those pages before the user returns to the home page.
I've tried to use the popUntil method of the Navigator which runs fine in the emulator, but not so fine on a physical device since that one is much faster and you can actually see the page getting popped and then replaced.

I hope I made my question/issue a bit clear.
Do you have any suggestions that might help me?

Hope to hear from you.

**Comment by felangel** [comment]
Hi @MdeBruin93 👋 
Thanks for opening an issue and sorry for the delayed response.

Can you please provide a link to a reproduction sample and I'm happy to take a closer look and open a pull request with any suggestions/feedback. Thanks 🙏

**Comment by MdeBruin93** [comment]
Hi @felangel ,

Thanks for your reply. I will upload a sample to GitHub asap. The current project is on Azure DevOps.

**Comment by MdeBruin93** [comment]
Hi @felangel ,

Here is the link to a reproduction sample. This time I've quickly used your login flow without Firebase and added the needed setup with tabscreen and some test screens.
[https://github.com/MdeBruin93/repo-sample](https://github.com/MdeBruin93/repo-sample)

Thank in advance for your help and suggestions.

**Comment by felangel** [comment]
Hi @MdeBruin93 👋 
Sorry for the delay! I took a closer look and believe you should be able to achieve the behavior you want by using `pushNamedAndRemoveUntil` like:

```dart
createHeaderIcon(
  Icons.notifications,
  () {
    Navigator.of(context).pushNamedAndRemoveUntil(
        AppBarScreenB.RouteName, (route) => route.isFirst);
  },
),
createHeaderIcon(
  Icons.account_circle,
  () {
    Navigator.of(context).pushNamedAndRemoveUntil(
        AppBarScreenA.RouteName, (route) => route.isFirst);
  },
),
```

Hope that helps! Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
