### ISSUE TITLE
multiple hit in onTap handler

### ISSUE THREAD

**Issue by peterdownunder** [felangel/bloc#2042]
I am new to the whole dart/flutter/bloc combo so suspect that this is a design issue.
Am just querying this and if required will create some simplified example of my problem.

I have a main page (android at this point) that displays a list of tiles showing the state of external devices (IOT modules)
Each one has indication of the current state of the IOT device that notifies asynchronously via MQTT. The tile has an icon that changes based on the state, mostly just an on/off indication.

If the tile is tapped an onTap event initiates another bloc that loads an edit screen to edit the definition of the IOT device associated with this device.

If I tap the tile and am editing the device, and a MQTT notification comes through for that device, the the onTap handler get called again, as the state of the bloc has changed, causing a  reset the current edit screen. 

I feel the problem may be related to how the edit screen is effectively a child of the status screen, and a different form of navigation where the child replaces the status screen may fix it (actually just thought of that while writing this)

The app is more complex and would like some guidance before I go down another rabbit hole and rework the current code.

**Comment by felangel** [comment]
Hi @peterdownunder 👋 
Thanks for opening an issue and sorry for the delayed response!

Are you able to provide a link to a sample app which illustrates the issue you're facing? It would be much easier for me to help if I'm able to reproduce the issue locally, thanks! 🙏

**Comment by peterdownunder** [comment]
No problem about the delay, it is Christmas after all.

I gather that this is unexpected. I have since tried modifying the counter example that you have in your demo, but cannot reproduce it. I will close this issue and post a comment later if when find out what is causing this.

Quite likely due to some misunderstanding on my part and could be more related to flutter rather than specifically to bloc.
