### ISSUE TITLE
simple bloc observer omitting parameters

### ISSUE THREAD

**Issue by teneon** [felangel/bloc#2046]
**Describe the bug**
I am writing an app, based on firebase_login example from the docs. I have added phone cubit (phone_state.dart ,phone_cubit.dart). 

This is how the phone_state.dart looks like

```
part of 'phone_cubit.dart';

enum IsoCodeStatus { unknown, finished }
enum PhoneVerificationStatus { phoneVerify, codeVerify }
enum SomethingVerificationStatus { thisVerify, thatVerify }

class PhoneState extends Equatable {
  const PhoneState({
    this.phoneNumber = const PhoneNumber.pure(),
    this.phoneApproval = const PhoneApproval.pure(),
    this.isoCode = const IsoCode.pure(),
    this.isoCodeStatus = IsoCodeStatus.unknown,
    this.phoneVerificationStatus = PhoneVerificationStatus.phoneVerify,
    this.somethingVerificationStatus = SomethingVerificationStatus.thisVerify,
    this.status = FormzStatus.pure,
  });

  final PhoneNumber phoneNumber;
  final PhoneApproval phoneApproval;
  final IsoCode isoCode;
  final IsoCodeStatus isoCodeStatus;
  final PhoneVerificationStatus phoneVerificationStatus;
  final SomethingVerificationStatus somethingVerificationStatus;
  final FormzStatus status;

  @override
  List<Object> get props => [
        phoneNumber,
        phoneApproval,
        isoCode,
        isoCodeStatus,
        phoneVerificationStatus,
        somethingVerificationStatus,
        status
      ];

  PhoneState copyWith({
    PhoneNumber phoneNumber,
    PhoneApproval phoneApproval,
    IsoCode isoCode,
    IsoCodeStatus isoCodeStatus,
    PhoneVerificationStatus phoneVerificationStatus,
    SomethingVerificationStatus somethingVerificationStatus,
    FormzStatus status,
  }) {
    return PhoneState(
      phoneNumber: phoneNumber ?? this.phoneNumber,
      phoneApproval: phoneApproval ?? this.phoneApproval,
      isoCode: isoCode ?? this.isoCode,
      isoCodeStatus: isoCodeStatus ?? this.isoCodeStatus,
      phoneVerificationStatus:
          phoneVerificationStatus ?? this.phoneVerificationStatus,
      somethingVerificationStatus:
          somethingVerificationStatus ?? this.somethingVerificationStatus,
      status: status ?? this.status,
    );
  }
}
```

simple_bloc_observer.dart is implemented as in the docs. Since i have added three additional parameters (already included in the example code above), 
```
final IsoCodeStatus isoCodeStatus;
final PhoneVerificationStatus phoneVerificationStatus;
final SomethingVerificationStatus somethingVerificationStatus;
```
the onChange method inside simple_bloc_observer.dart
```
  @override
  void onChange(Cubit cubit, Change change) {
    print(change);
    super.onChange(cubit, change);
  }
```
is somehow omitting, truncating, shortening the output of currentState and nextState. Pay attention to the three dots (...)
right after IsoCode(US, false), below. Basically, three dots (...) are displayed instead of two additional parameters (isoCodeStatus, somethingVerificationStatus) in the state.

`I/flutter (19880): Change { currentState: PhoneState(PhoneNumber(, true), PhoneApproval(false, true), IsoCode(HR, true), ..., SomethingVerificationStatus.thisVerify, FormzStatus.pure), nextState: PhoneState(PhoneNumber(, true), PhoneApproval(false, true), IsoCode(US, false), ..., SomethingVerificationStatus.thisVerify, FormzStatus.pure) }`

Is there a solution for this? I would like to see (print) the whole currentState and nextState into the debug console of Visual Studio Code. How can i do this please :D ?

Thank you!

**Comment by mikededo** [comment]
The three dots are due to very long strings 😄

**Comment by felangel** [comment]
Hi @teneon 👋 
Thanks for opening an issue and sorry for the delayed response!

As @mikededo mentioned, this behavior has nothing to do with bloc and is simply a result of how flutter prints long strings. See https://github.com/flutter/flutter/issues/22665 for more information 👍
