### ISSUE TITLE
blocTest type inference fails when 'seed' is used and state is a type hierarchy

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#2052]
**Describe the bug**

Given this code:

```dart
import 'package:bloc/bloc.dart';
import 'package:bloc_test/bloc_test.dart';
import 'package:equatable/equatable.dart';

// event

class IntEvent {
  final int value;

  IntEvent(this.value);
}

// state

abstract class IntState extends Equatable {
  int get value;

  @override
  List<Object> get props => [value];
}

class IntInitial extends IntState {
  @override
  int get value => 0;
}

class IntSuccess extends IntState {
  @override
  final int value;

  IntSuccess(this.value);
}

// bloc

class IntBloc extends Bloc<IntEvent, IntState> {
  IntBloc() : super(IntInitial());

  @override
  Stream<IntState> mapEventToState(IntEvent event) {
    return Stream.value(IntSuccess(state.value + event.value));
  }
}

// tests

void main() {
  blocTest(
    'test without seed',
    build: () {
      return IntBloc();
    },
    act: (bloc) {
      bloc.add(IntEvent(17));
    },
    expect: [IntSuccess(17)],
  );

  blocTest(//<IntBloc, IntState>(
    'test with seed',
    build: () {
      return IntBloc();
    },
    seed: IntSuccess(3),
    act: (bloc) {
      bloc.add(IntEvent(17));
    },
    expect: [IntSuccess(20)],
  );
}
```
type inference fails for test 'test with seed' with the error 'Couldn't infer type parameter C'. Similar tests work for much simpler cases, like if the state is a plain `int`. To make inference work I can do this:

```dart
blocTest(//<IntBloc, IntState>(
'test with seed',
    build: () {
      return IntBloc();
    },
    seed: IntSuccess(3) as IntState, // <==== here
    act: (bloc) {
      bloc.add(IntEvent(17));
    },
    expect: [IntSuccess(20)],
  );
```
but this in turn generates the warning 'Unnecessary cast'.

I played around a bit and it turns out that:
1. If state is a type hierarchy, like in the example above, and
2. The 'seed' parameter is used
type inference fails.

Type inference with 'seed' works for the simplest of use cases only, e.g. if the state is an `int`, or if there is no state hierarchy, e.g. if there were a single type `IntState` which wraps around an `int`; as soon as another state subtype is introduced `blocTest` requires explicit typing.

Would there be a way to improve this? Or am I missing something in my test? Or is it a Dart inference limitation and there is nothing that can be done?

**Comment by felangel** [comment]
Hi @wujek-srujek 👋 
Thanks for opening an issue!

Unfortunately, I believe this is a limitation of Dart's type inference.

When you specify a seed of type `IntSuccess(3)`, Dart infers the generic to be `IntSuccess` rather than `IntState` which results in it being unable to reconcile the cubit/bloc type since it expects `IntBloc` to extend `Bloc<IntEvent, IntSuccess>` rather than `Bloc<IntEvent, IntState>`.

```dart
abstract class Bloc<E, S> {}

abstract class MyState {}

class StateA extends MyState {}

abstract class MyEvent {}

class EventA extends MyEvent {}

class MyBloc extends Bloc<MyEvent, MyState> {}

void main() {
  foo(
    build: () => MyBloc(),
    seed: StateA(),
  );
}

void foo<B extends Bloc<Object, S>, S>({
  B Function() build,
  S seed,
}) {}
```

We could address this issue by refactoring the above to:

```dart
void foo<B extends Bloc<Object, S>, T extends S, S>({
  B Function() build,
  T seed,
}) {}
```

but this will fail in other cases (namely where state-specific APIs aren't used so state can't be inferred) and will result in an even more verbose explicit type declaration (`foo<MyBloc, StateA, MyState>`).

**Comment by wujek-srujek** [comment]
Ok, thanks for confirming it.
