### ISSUE TITLE
Are there any example using bloc with flutter_downloader  ?

### ISSUE THREAD

**Issue by bobykurniawan11** [felangel/bloc#2053]

**Comment by felangel** [comment]
Hi @bobykurniawan11 👋 
Thanks for opening an issue!

I personally am not aware of an example but is there anything in particular that you'd like to see? If you have a sample app which uses `flutter_downloader` and are having trouble integrating with bloc, I'm more than happy to take a look and provide suggestions/feedback. Let me know what you think, thanks! 🙏

**Comment by thisisamank** [comment]
Hi, @felangel
I would like to make an example app which uses `flutter_downloader` with the bloc, can you assign this to me and please let me know what all features will it have?

**Comment by alexaung** [comment]
Any update?

**Comment by felangel** [comment]
Closing this for now since it's a really old issue and I'm happy to answer specific questions if folks have them.

**Comment by sathya4code** [comment]
Hi

Is there any example available using bloc with flutter_downloader?

**Comment by balajiks-dev** [comment]
How to implement the flutter_downloader using bloc? 

I have an issue with calling event or state in the port listener.
