### ISSUE TITLE
Merging Stream and future with BLOC state management

### ISSUE THREAD

**Issue by yanisG** [felangel/bloc#2054]
hello ,
**I'm trying to get a **stream of List <Product>** in a cart, inside that Cart there is IDs of products so for each ID i want to get a particular product and display its informations.**

My soltion was : 

**//collections of the CART and All Products**
```
 final productCartCollection = FirebaseFirestore.instance
      .collection("Users")
      .doc(FirebaseAuth.instance.currentUser.uid)
      .collection("Cart");  
final allProductCollection =
      FirebaseFirestore.instance.collection("Products");

```
**//here i'm getting stream of List of Future Product** 
```
 
 @override
  Stream<List<Future<Product>>> getProducts() {
    return productCartCollection.snapshots().map((snapshot) {
      return snapshot.docs.map((doc) => getProduct(doc.id)).toList();
    });
  }


  @override
  Future<Product> getProduct(String productID) {
    return allProductCollection.doc(productID).get().then((value) {
      return Product.fromEntity(ProductEntity.fromSnapshot(value));
    });
  }
```
**//in the Bloc part :** 
```
  Stream<CartState> _mapCartStartedToState() async* {
    try {
      _productsSubscription?.cancel();
      _productsSubscription = _productsRepository.getProducts().listen(
            (product) => Future.wait(product).then((value)=>add(CartProductUpdate(value))),
          );
    } catch (Exception) {
      yield CartError(Exception.toString());
    }
  }
```
**the issue is i'm not getting all the Products i'm getting only one ! is there a better solution to implement ??
i'm beginning with BLoc so please i need your help .**
thanks .

**Comment by felangel** [comment]
Hi @yanisG 👋 
Thanks for opening an issue!

Are you able to provide a link to a sample app which illustrates the issue you're facing? It would be much easier for me to help if I could run/debug the example locally and open a pull request with suggestions. Thanks 🙏

**Comment by yanisG** [comment]
Hello @felangel ,
thank you for your response , actually i found the solution of my issue and it was **not a Bloc Issue.**
So to conclude it's **seems okay to use Stream and Future together in Bloc** ..
because i'm using  for a "Stream of IDs Products" a Future to get the Informations of  one Paricular product and i thought that the Future will affect the stream to do hes work properly and so i might  get a wrong state .

**if there is a better implementation of the idea please refer me to it ,**
 **Thank you very much for your hard work !**
