### ISSUE TITLE
UI update

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2060]
Is it recommended to use blocbuilder (instead of converting widget to Statefull and use setState) for simple ui update based on user interactions only?

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

If there is no business logic involved there is no need to use a bloc and BlocBuilder. Feel free to use a StatefulWidget and setState 👍

**Comment by II11II** [comment]
HI @felangel )
Thank for fast reply)
This question was appeared based on your example of using bloc in counter app

**Comment by felangel** [comment]
No problem! I would argue that incrementing the counter is business logic which is why the bloc was introduced.
