### ISSUE TITLE
 BlocProvider.of() called with a context that does not contain a Bloc/Cubit of type [TestCubit].

### ISSUE THREAD

**Issue by Jaekyun-Song** [felangel/bloc#2064]
Hello,

I've been enjoying using the Flutter bloc. However, I ran into the problem as described in the title. The following code is to reproduce this problem.

-------------------- test_cubit.dart --------------------
```dart
import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';

class TestState extends Equatable {
  @override
  List<Object> get props => [];
}

class TestCubit extends Cubit<TestState> {
  TestCubit() : super(null);
}
```
------------------- main.dart -------------------------
```dart
import 'package:cubit/test_cubit.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
void main() {
  runApp(MyApp());
}
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);
  @override
  _MyHomePageState createState() => _MyHomePageState();
}
class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: BlocProvider(
          create: (context) => TestCubit(),
          child: RaisedButton(
            onPressed: () {
              BlocProvider.of<TestCubit>(context); // The error occurs here
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by felangel** [comment]
Hi @Jaekyun-Song 👋 
Thanks for opening an issue!

The problem you're facing is due to the fact that you're using a `BuildContext` that does not contain the `TestCubit`. You need to either decompose your widget into two widgets (which I recommend for testability reasons) or use a `Builder` widget to get a child `context`.

## Decomposition (Recommended)

```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => TestCubit(),
      child: MyHomeView(),
    );
  }
}

class MyHomeView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(onPressed: () => BlocProvider.of<TestCubit>()...)
      ),
    );
  }
}
```

## Builder Approach

```dart
class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: BlocProvider(
          create: (_) => TestCubit(),
          child: Builder(
            builder: (context) {
              return RaisedButton(onPressed: () => BlocProvider.of<TestCubit>(context)...);
            }
          ),
        ),
      ),
    );
  }
}
```

I also highly recommend checking out [this video](https://youtu.be/iNgwFMm3opE) for a more in-depth explanation.

Hope that helps 👍

**Comment by Jaekyun-Song** [comment]
I think I have expanded my knowledge of Flutter as well as Flutter Bloc. Thank you @felangel! Your minutes saved my hours because I've already spent hours.

**Comment by WindRmen05** [comment]
"This can happen if the context you used comes from a widget above the BlocProvider."
this is the error I'm getting when I used BlocProvider.of<exampleBloc>(context); inside a class : -
class exampleClass(context) {
     BlocProvider.of<exampleBloc>(context);
}

do you know why this happens.

**Comment by Abdurahmon727** [comment]
Thanks, problem solved😁

**Comment by hhoang-be** [comment]
If I understand correctly a bloc is not readable in the context of its grand children. 

I am wondering weather there is anyway a bloc is accessible to children widgets down from it in the tree?
