### ISSUE TITLE
Question: Why do events implement equatable

### ISSUE THREAD

**Issue by markbeij** [felangel/bloc#2070]
All the BLoC examples @ https://bloclibrary.dev/ extend Equatable. Why is that?
I can't come up with a reason for that. States should extend Equatable, I get that. When states are not effectively the BlocBuilder should not redraw. Multiple Events however should always be handled. Whether they're the same or not.

**Comment by felangel** [comment]
Hi @markbeij 👋 
Thanks for opening an issue!

The main reason is for consistency but in reality unless you're overriding `transformEvents` and performing operations which rely on event equality then it's not necessary 👍 

Hope that helps!

**Comment by markbeij** [comment]
It does, thanks!
