### ISSUE TITLE
Customizable Folder Structure

### ISSUE THREAD

**Issue by mrgnhnt96** [felangel/bloc#2071]
**Is your feature request related to a problem? Please describe.**
Depending on how you structure your app, the folder's & file's names could vary. Following DDD, I group all of my BLoCs within a folder and they are labeled after their feature. For example: 

```
application
│ ├── blocs
│ │ ├── featureA
│ │ │ ├── bloc
│ │ │ ├── state
│ │ │ └── event
```

Because of how I have structured my app this way, I find myself having to rename the folders and files whenever I generate a new BLoC folder.

**Describe the solution you'd like**
Currently when the folder and files are generated they're set up like: 

```
bloc
│ ├── featureA_bloc
│ ├── featureA_state
│ └── featureA_event
```

This is redundant and could be made more DRY, for example:

```
featureA_bloc
│ ├── bloc
│ ├── state
│ └── event
```

or even:

```
featureA
│ ├── bloc
│ ├── state
│ └── event
```

A way that we can introduce a solution would be to create a setting that you can adjust to set up the folder and file names.

**Comment by felangel** [comment]
We generally recommend having a bloc per feature and following the directory structure outlined in the official bloc examples. If you prefer to have your own custom structure, I highly recommend extending the [bloc brick](https://brickhub.dev/bricks/bloc/0.2.0) and customizing it to fit your team's needs.
