### ISSUE TITLE
AppLifecycleState 

### ISSUE THREAD

**Issue by yanisG** [felangel/bloc#2072]
hello sir , 
i want to know if it is good practice to close bloc on AppLifecycleState.paused because the bloc is using some streams so in case the app is in the background , is it good practice to close all bloc instance ? and if yes how to proceed 

**i tried some thing like that in the didChangeAppLifecycleState method and it's not working** 

```
 @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
  final  CartBloc _cartBloc = context.read<CartBloc>();
   final  ProductInfoBloc _productInfoBloc = context.read<ProductInfoBloc>();

    if (state == AppLifecycleState.resumed) {
      _cartBloc.add(CartStarted());
      _productInfoBloc.add(ProductsStarted());
    } else  if (state == AppLifecycleState.paused){
      _cartBloc.close();
      _productInfoBloc.close();
    
    }
  }
```

thank you !

**Comment by felangel** [comment]
Hi @yanisG 👋 
Thanks for opening an issue!

I don't recommend trying to do this manually as it is an unnecessary optimization. `BlocProvider` automatically handles closing blocs automatically when the widget is unmounted from the widget tree.

Hope that helps 👍
