### ISSUE TITLE
Should have isDisposed() method

### ISSUE THREAD

**Issue by nambv** [felangel/bloc#208]
**Is your feature request related to a problem? Please describe.**
- Sometime we need to check the bloc is disposed or not before call `dispose()` or `dispatch()` method

**Describe the solution you'd like**
- It will be good if we have `isDisposed()` method
```
if (!_bloc.isDisposed()) {
   _bloc.dispatch(SomeEvent());
}

if (!_bloc.isDisposed()) {
   _bloc.dispose();
}
```

**Describe alternatives you've considered**
- Something like that in `bloc.dart`:

```
bool isDisposed() {
    return _eventSubject.isClosed && _stateSubject.isClosed? true: false;
  }
```

**Comment by felangel** [comment]
Hi @nambv 👋 

Thanks for the feature request!

Would it be possible to provide some specific examples of when you’d need to know if a bloc was disposed? So far we haven’t had a use case for this but would love to hear about how you’re using bloc and why this is necessary feature. 👍

Thanks!

**Comment by felangel** [comment]
Closing this for now since we don’t have a specific use-case.

When you get a chance let me know what the use case is and we can continue the discussion 👍
