### ISSUE TITLE
how to get FutureList from firestore?

### ISSUE THREAD

**Issue by yeahse** [felangel/bloc#2084]
@override
  Stream<List (Model) > todos() {
    return FirebaseFirestore.instance
        .collection('todos')
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) {
        return Model.fromEntity(TodoEntity.fromSnapshot(doc));
      }).toList();
    });
  }

this works perfectly. but if I change 
 Stream<List(Model)> todos() ->  Future<List(Model) todos()

then it shows error. how to get Future<List<Todo>> in your project?

**Comment by felangel** [comment]
Hi @yeahse 👋 
Thanks for opening an issue!

You should be able to do something like:

```dart
Future<List<Model>> todos() async {
  final querySnapshot = await FirebaseFirestore.instance
    .collection('todos')
    .get();

  return querySnapshot.docs.map((doc) {
    return Model.fromEntity(TodoEntity.fromSnapshot(doc));
  }).toList();
}
```

Hope that helps 👍
