### ISSUE TITLE
replay_bloc should allow a filter function to ignore some states

### ISSUE THREAD

**Issue by JohnGalt1717** [felangel/bloc#2086]
**Is your feature request related to a problem? Please describe.**
In the state queue of most pages there is typically Loading, Loaded, error etc.  Unfortunately, right now the ones that don't matter to reply are stored and it doesn't appear to be any way to intercept and filter those out before they get dumped in to the change tracker.

**Describe the solution you'd like**
I'd like a method that can be overridden that is simply defined as bool shouldReplay(state) => true;

This would allow us to filter out stuff.

**Describe alternatives you've considered**
Simply overriding emit doesn't work because the change stack is private and even if it did it would be less than ideal

**Comment by evandrmb** [comment]
I don't know if this should be another issue, but I think would be nice to have a `undoTo` that works like `Navigator.popUntil`. That way we would go back directly to the specified State.
