### ISSUE TITLE
Bloc State updating only once.

### ISSUE THREAD

**Issue by BashisthaSudeep** [felangel/bloc#2089]
I am having a problem where the text field shows the value from the bloc builder using the text controller. 

The text field is read-only and I've assigned an onTap property on it to navigate to a different screen where the user selects the specific item from the ListView. 

It works for the first field when I select the value, but if I try to change the value of the selected field or try to select other fields their value isn't updated on the text field. 

The detailed explanation is below: 
https://stackoverflow.com/questions/65757277/blocbuilder-not-updating-after-change

**Comment by felangel** [comment]
Hi @BashisthaSudeep 👋 
Thanks for opening an issue!

I'm guessing this is happening because your `Quote` class does not extend `Equatable`. Please refer to the [FAQs](https://bloclibrary.dev/#/faqs?id=state-not-updating) for more information 👍
