### ISSUE TITLE
Is correct insert FirebaseMessaging in application_bloc?

### ISSUE THREAD

**Issue by romaluca** [felangel/bloc#209]
Hi, i'm trying to develop an app with bloc pattern.
I'm using plugins like firebase_messaging, sentry, etc.
My question is.. Where i have to put the variable with the instance of them?
In the application_bloc like a  variable  or in the ApplicationState?

Thanks

**Comment by felangel** [comment]
Hi @romaluca 👋 
Thanks for opening an issue!

Regarding your question, I would recommend treating the plugin instance as a raw dat provider and creating a repository around it like UserRepository etc. Then you can inject the repository Into the bloc as a dependency. You can check out the [firebase authentication example](https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_authentication) for a reference. Hope that helps! 👍
