### ISSUE TITLE
Offline Copy of Bloc Docs? 

### ISSUE THREAD

**Issue by mstfkhazaal** [felangel/bloc#2091]
Does anyone here have an offline copy of Bloc documentation?

**Comment by felangel** [comment]
Hi @mstfkhazaal 👋 
Thanks for opening an issue!

You can clone this repository and then run an http server in the `docs` directory like:

```sh
python3 -m http.server 8080
```

Then you can go to `localhost:8080` and you should be able to browse the docs offline 👍 
See the [CONTRIBUTING GUIDE](https://github.com/felangel/bloc/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more details.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
