### ISSUE TITLE
Cubit isn't emitting a state without waiting on a future.delayed()

### ISSUE THREAD

**Issue by Mx-Tech** [felangel/bloc#2094]
**Describe the bug**
I tried to use a cubit and wanted to emit a loading state before fetching data via network. But the loading state was never set and therefore, the loading widget wasn't displayed. I had to put an `await Future.delayed(Duration(microseconds: 1));` before the loading state to trigger it correctly.

**To Reproduce**
I posted an answer at stackoverflow.com with the code snippet that solved my problem for a similar problem.
https://stackoverflow.com/questions/65757277/blocbuilder-not-updating-after-change/65770103#65770103

**Expected behavior**
Emitting states won't need a future.delayed before.

**Additional context**
I don't know if it's really a bug or if I missed something implementing the cubit.

**Comment by felangel** [comment]
Hi @Mx-Tech 👋 
Thanks for opening an issue!

This is working as expected. The problem you're facing is the state of the cubit is changing faster than the UI can rebuild. The same thing will happen if you use `setState` and update the state back to back. See https://github.com/felangel/bloc/issues/173#issuecomment-478279105

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by Mx-Tech** [comment]
Hello @felangel,
many thanks for your comment and help. I totally agree if I emit the states too fast, they can't be rebuild. But in my case, between the SearchLoading-state and the SearchLoaded-state, I'm making a network request (ok, it's quite fast :grin: ) and also execute an 
`await Future.delayed(Duration(seconds: 2))`. But the SearchLoaded-state is never emitted. I debugged my code and the state in the BlocConsumer was never reached. But, once I set an `await Future.delayed(Duration(microseconds: 1))` before emitting the SearchLoading-state it worked.
Here's my code example:
```
class SearchCubit extends Cubit<SearchState> {
  final ClubRepository _clubRepository = ClubRepository();
  final log = getLogger("SearchCubit");

  SearchCubit() : super(SearchInitial());

  Future<void> getClubs() async {
    try {
      // removing the next line will never emit the SearchLoading()-state and no spinner is shown
      await Future.delayed(Duration(microseconds: 1));
      emit(SearchLoading());
      final List<Club> clubs = await _clubRepository.fetch();
      await Future.delayed(Duration(seconds: 2));
      emit(SearchLoaded(clubs));
    } catch (err, stacktrace) {
      emit(SearchError("Retrieving data from API failed!"));
    }
  }
}
```
Ok, maybe it might be a problem that I'm calling the `getClubs()` function from the BlocConsumer's initial state, to automatically retrieve my network data.
```
child: BlocConsumer<SearchCubit, SearchState>(
            listener: (context, state) {
              // here navigation etc.
            },
            builder: (context, state) {
              log.d(state.toString());
              if (state is SearchInitial) {
                final searchCubit = BlocProvider.of<SearchCubit>(context);
                searchCubit.getClubs();
              } else if (state is SearchLoading) {
                return LoadingWidget();
              } else if (state is SearchLoaded) {
                return SearchWidget(clubs: state.clubs);
              } else if (state is SearchError) {
                // todo: Display error card
                return Container(
                  child: Text("Error"),
                );
              }
              return Container();
            },
          ),
```
If it is a problem, is there a better way to fetch the network data without user interaction?

P.s. The issue occurred with an Android emulator and also on a real device.

Thanks for your great work!!!!
