### ISSUE TITLE
`MyBloc` doesn't extend `Cubit<Object>` when using BlocProvider

### ISSUE THREAD

**Issue by vishna** [felangel/bloc#2096]
**Describe the bug**
This is due to recent change in the bloc package - https://pub.dev/packages/bloc/versions/7.0.0-nullsafety.1/changelog and lack of respective flutter_bloc version published yet: https://pub.dev/packages/flutter_bloc/versions/7.0.0-nullsafety.0/changelog

**To Reproduce**

1. Use `BlocProvider` or `BlocConsumer` with a class extending from `Bloc`

**Comment by felangel** [comment]
Hi @vishna 👋 
Thanks for opening an issue and sorry for the inconvenience!

I just published [bloc v7.0.0-nullsafety.1](https://pub.dev/packages/bloc/versions/7.0.0-nullsafety.1) 🎉 

Closing for now but let me know if you're still having trouble 👍

**Comment by vishna** [comment]
thanks @felangel, that has fixed it. Now having a different issue, it would seem the context extension is not recognized:

```
context.bloc<MyBloc>()
```

**Comment by vishna** [comment]
nevermind, API changed more in between, should use `watch` instead
