### ISSUE TITLE
Navigate Page using Hydrated bloc

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2111]
How to navigate to the route that is obtained from HydratedBox?

I tried to use BlocListener to navigate to the last route which is saved in database using HydratedBloc. And i found from the docs that 1st state is not listened in BlocListener

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

You can re-emit the first state for this exact use-case.

```dart
class MyBloc extends HydratedBloc<MyEvent, MyState> {
  MyBloc() {
    add(_Initialized());
  }
  
  @override
  Stream<MyState> mapEventToState(MyEvent event) async* {
    if (event is _Initialized) {
      yield state; // initial state can be re-emitted
    }
  }
}
```

Hope that helps! Closing for now but if you're still having trouble please create a reproduction sample and share the link and I'm happy to take a closer look 👍

**Comment by II11II** [comment]
Hi @felangel,
Thank you for help😊
Is it ok if i implemented  equitable to my state ?
And i read from bloc docs that listener and builder not updates if instances are the same,  is it true with hydrated bloc?

**Comment by felangel** [comment]
No problem, and yes that's totally fine. Even if you extend Equatable you should still be able to re-emit the first state with hydrated_bloc 👍
