### ISSUE TITLE
Best practice for showing alter dialog globally?

### ISSUE THREAD

**Issue by dxGuan** [felangel/bloc#2114]
We are facing a problem or let's say a confusion when using flutter_bloc to build a production-grade app.

### Scenario

We use ```MultiBlocProvider``` to wrap ```MaterialApp``` as its child that we want to achieve global access within the pages in app for specific ```bloc(s)```. 

One of these ```bloc(s)``` is an ```AuthBloc``` which provides authentication states management.

We want to use ```AuthBloc``` to emit ```unauthenticated``` state no matter where the user is in the app and shows a alter dialog that informs user the unauthenticated state.

### Question

May be using ```BlocListener``` in every page will possibly achieves this, but sounds like too cumbersome.

What is the good or best practice to implement this feature?

Is there any suggestions that can accomplish this feature (or related feature) globally or in a manageable way?

**Comment by felangel** [comment]
Hi @dxGuan 👋 
Thanks for opening an issue!

You can add a `GlobalKey` to your `MaterialApp` like so:

```dart
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final _navigatorKey = GlobalKey<NavigatorState>();

  void showAuthErrorDialog() {
    final dialog = AlertDialog(
      content: Text('Authentication Error!'),
    );
    final context = _navigatorKey.currentState.overlay.context;
    showDialog(context: context, builder: (_) => dialog);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: _navigatorKey,
      home: BlocProvider(
        create: (_) => AuthBloc(),
        child: MyAppView(onAuthError: showAuthErrorDialog),
      ),
    );
  }
}

class MyAppView extends StatelessWidget {
  const MyAppView({Key key, @required this.onAuthError}): super(key: key);

  final VoidCallback onAuthError;

  @override
  Widget build(BuildContext context) {
    return BlocListener<AuthBloc, AuthState>(
      listenWhen: (_, current) => current is AuthenticationError,
      listener: (context, state) => onAuthError(),
      child: ...
    );
  }
}
```

Hope that helps 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄
