### ISSUE TITLE
Best practice to show error state without changing the UI

### ISSUE THREAD

**Issue by AdrianDev0** [felangel/bloc#2115]
Hi @felangel ,

In your [Infinite list tutorial](https://bloclibrary.dev/#/flutterinfinitelisttutorial) you have a state called [PostFailure](https://bloclibrary.dev/#/flutterinfinitelisttutorial?id=post-states). If this state is yielded, you change the UI to a simple text. 
What I would like to do now is to show the error as a snackbar and keep the UI in its previous state (Showing the already loaded part of the list or the Loading Spinner).

I would therefore in the mapEventToState method yield something like:

```dart
...
var temp = currentState;
yield PostFailure();
yield temp;
...
```

and in the UI use a BlocConsumer. 
The listener-part would listen to the PostFailure-State to show the snack bar. 
And the Builder will only build the latest state (due to [this](https://github.com/felangel/bloc/issues/173#issuecomment-477148562) ) (which is then PostInitial oder PostSuccess) and therefore show the UI with the previous content.

Would you say, that this approach is fine? Or do you see any problem with it or would you change something?

**Comment by felangel** [comment]
Hi @AdrianDev0 👋 
Thanks for opening an issue!

If you want to support "partial states" (error and data can exist at the same time) then I would recommend refactoring the state to look something like:

```dart
enum PostStatus { initial, loading, success, failure }

class PostState {
  const PostState({
    this.status = PostStatus.initial,
    this.posts = const <Post>[],
  });

  final PostStatus status;
  final List<Post> posts;

  PostState copyWith({PostStatus status, List<Post> posts}) {
    return PostState(status: status ?? this.status, posts: posts ?? this.posts);
  }
}
```

Then in your UI you can handle errors and still show the previous list of posts.

If you want a more concrete example of how this looks you can take a look at https://github.com/felangel/fluttersaurus/blob/master/lib/search/bloc/search_state.dart.

Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by talksik** [comment]
Thank you for the helpful example @felangel !! Is there a way to do that search_state example that you linked with @freezed unions or with simple `sealed class` and a bunch of extends?

I am confused by dart type system and having trouble finding a way to have common properties for all states.
