### ISSUE TITLE
Make Bloc aware of object from  state update from, so object event  goes back to that same object

### ISSUE THREAD

**Issue by bsanderson1981** [felangel/bloc#2116]
New to Dart/Flutter and mobile dev.  Building my  first app.  

I have done several demo counter apps on the web to learn Bloc.    While these basic apps are a good start. I maybe have jump ahead of my programming skill set on the app i am building 

I built a shopping cart for my bagel store.  it pulls in bagel name, flavor  and price  json data  from my server.   The app brings everything up nicely. Bloc is working to increment the Plain Bagel quantity counter:  (  -   0   + ).   I understand Bloc only is for managing state.  But with a list view of bagels dynamically generated seem I am missing the something, maybe beyond bloc here?   

issue out of the box my code updates all the counters in the listview. for all flavors when I update one.  yes I understand why this happens currently.  see attach pix. 

If BLoc was aware of the widget object sending the event by reference to widgets  listview[index]  the widget code  for the event updates that widget.

I am search stackoverflow post for answer to this nothing back yet..   maybe I need to building dynamic Bloc's for each item in the listview.?

Thanks for Bloc and your  time ...

![incremented9-25-04](https://user-images.githubusercontent.com/5122840/106214409-972f4680-6183-11eb-95bb-6123c7b5443d.png)

**Comment by felangel** [comment]
Hi @bsanderson1981 👋 
Thanks for opening an issue!

You should either wrap each ListItem in it's own `BlocProvider` and provide a unique instance of your bloc to each one or you should have a single top level bloc which manages the count of all flavors.

The simpler refactor would probably be the former:

```dart
ListView.builder(
  itemBuilder: (context, index) => BlocProvider(create: (_) => BagelCounterBloc(), child: BagelTile(flavors[index])),
  ...
```

But I would argue it's probably a better idea to have a single bloc which manages the state of this screen so you can have it manage a `List<Bagel> bagels` like:

```dart
class Bagel {
  const Bagel(this.flavor, {this.count = 0});
  final Flavor flavor;
  final int count;
}

class BagelListState {
  const BagelListState({
    this.bagels = const <Bagel>[],
  });

  final List<Bagel> bagels;
}
```

Then you can have `increment` and `decrement` events which also require a flavor:

```dart
class BagelIncremented extends BagelListEvent {
  const BagelIncremented(this.flavor);
  final Flavor flavor;
}

class BagelDecremented extends BagelListEvent {
  const BagelIncremented(this.flavor);
  final Flavor flavor;
}
```

In the bloc you can then react to each event and update the appropriate bagel count based in the incoming event's flavor.

Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by bsanderson1981** [comment]
Felix,    thank you for suggestions and feedback.

  i re-watch your
Brisbane Mobile App Developers  video:   https://www.youtube.com/watch?v=nc55gOsL8lc briasa   which gave me an idea to check  my  placed of my  blockprovider.

i had placed the blockprovider at top of my  ui widget tree.  this seem to have affect of updating all the context of item counts  in my Listview pf bagel items.  I moved the blockprovider wrap only on the listview counter widget that shows count and  inc/dec .  this made it act correctly to only update that list item.   so i guess i had it coded correctly. just overlook the placement of the state blockprovider change.    I have more to work out in my app.  [ still learning so much ]  but really appreciate your reply...

If  you are ever in Palm Springs, CA. .  I owe you some bagels...
bill sanderson
townie bagels,   palm springs ca.
