### ISSUE TITLE
BLoC wait for another BLoC state change

### ISSUE THREAD

**Issue by cosinus84** [felangel/bloc#212]
How can I change the state of a bloc in mapEventToState of another Bloc

 I have this situation
```
@override
  Stream<AppState> mapEventToState(
    AppEvent event,
  ) async* {
    if (event is AppStarted) {
      await _appStore.load();
      authBloc.dispatch(AuthDemoEvent());
      yield AppInitialized();
    }

  }
```
I need somehow to change the authBloc state, and then yield AppInitialized(). authBloc.dispatch(AuthDemoEvent()) is async operation and AppState is AppInitialized before authBloc state is changed.

I found that I can call `await authBloc.mapEventToState(AuthDemoEvent()).first` in mapEventToState. This works but I think is not almost right. 

Is there any other solution? I maybe missing something.

**Comment by felangel** [comment]
Hey @cosinus84 👋 

Great question! This isn't simple to do because `dispatch` is asynchronous and is not `awaitable` (because you can yield multiple states for a single event).

Can you provide a sample app and describe what feature/functionality you're trying to implement and I can try to give suggestions on how I would go about implementing it without having to do stuff like `await authBloc.mapEventToState(AuthDemoEvent()).first`? Thanks! 👍

**Comment by cosinus84** [comment]
In the first place thank for your quick answer and patience.
I have AppBloc witch is load in main.dart

```
void initState() {
    super.initState();
    _authBloc = AuthBloc();
    _appBloc = AppBloc(authBloc: _authBloc);
    _appBloc.dispatch(AppStarted());
  }

  @override
  Widget build(BuildContext context) {
    return BlocProviderTree(
        blocProviders: [
          BlocProvider<AppBloc>(bloc: _appBloc),
          BlocProvider<AuthBloc>(bloc: _authBloc),
        ],
        child: MaterialApp(
          home: BlocBuilder<AppEvent, AppState>(
              bloc: _appBloc,
              builder: (BuildContext context, AppState state) {
                if (state is AppInitialized) {
                 //uses authBloc state to go to LoginScreen or HomeScreen
                  return Index();
                }
                if (state is AppUninitialized) {
                  return SplashScreen();
                }
              }),
          title: 'iAgent',
        ));
  }
```
In AppBloc:
```
class AppBloc extends Bloc<AppEvent, AppState> {
  final AppStore _appStore = getIt<AppStore>();
  AuthBloc authBloc;
  @override
  AppState get initialState => AppUninitialized();

  AppBloc({this.authBloc});

  @override
  Stream<AppState> mapEventToState(
    AppEvent event,
  ) async* {
    if (event is AppStarted) {
      await _appStore.load(); //loads the token from shared pref, etc
     //when the store is loaded, update the authBloc state depending on if there is a token or not
      authBloc.dispatch(AuthAppInitialized()); 
      yield AppInitialized();
    }

  }
}
```
In AuthBloc:
```
class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final UserRepository userRepository = UserRepository();
  AuthBloc();

  @override
  AuthState get initialState => AuthUnauthenticated();     


  @override
  Stream<AuthState> mapEventToState(AuthEvent event) async* {
   if(event is AuthAppInitialized){
      await Future.delayed(Duration(seconds: 10)); //maybe other operations
      if(userRepository.hasToken()){
        yield AuthAuthenticated();
      }else{
        yield AuthUnauthenticated();
      }
    }
  }
}
```
**In another the application I did before**  I set authBloc as a property in AppBloc
```
  @override
  Stream<AppState> mapEventToState(
    AppEvent event,
  ) async* {
    if (event is AppStarted) {
      await _appStore.load(); //loads the token from shared pref, etc
      authBloc = AuthBloc() //the store is loaded
      yield AppInitialized();
    }
  }
}
```
and in AuthBloc

```
class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final UserRepository userRepository = UserRepository();
  AuthBloc();

  @override
  AuthState get initialState =>
      userRepository.hasToken() ? AuthAuthenticated() : AuthUnauthenticated();
```

With this new one application I wanted to pull AuthBloc from AppBloc. So when the AppBloc is ini initialized state the authBloc should also update the state as auth or notauth.

**Comment by felangel** [comment]
Hey @cosinus84 thanks for the extra details.

Based on what you said, I would recommend making the AuthBloc have a dependency on the AppBloc and then in the constructor of the AuthBloc you can subscribe to the AppBloc state like:

```dart
class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final AppBloc appBloc;
  StreamSubscription appBlocSubscription;
  
  AuthBloc(this.appBloc) {
    appBlocSubscription = appBloc.state.listen((appState) {
      if (appState is AppInitialized) {
        // Check if logged in or not and dispatch Authenticated or Unauthenticated
      }
    });
  }

  @override
  dispose() {
    appBlocSubscription.cancel();
    super.dispose();
  }
```

Check out [bloc to bloc communication](https://felangel.github.io/bloc/#/architecture?id=bloc-to-bloc-communication) in the docs.

Alternatively you can use `BlocListener` to dispatch an event to your AuthBloc whenever the AppBloc state changes like:

```dart
BlocListener(
  bloc: appBloc,
  listener: (context, state) {
    if (state is AppInitialized) {
      // notify auth bloc
      authBloc.dispatch(...)
    }
  },
  child: BlocBuilder(
    bloc: authBloc,
    builder: (context, state) {
      // render widget based on authBloc state
    },
  }
)
```

Hope that helps 👍

**Comment by cosinus84** [comment]
Thanks, in the end I will adapt to one of this solutions. 
I think what I am trying to say is that the only way to add a state is using dispatch(event.sink), no way of adding a state directly to the bloc(only when instantiate you have an initial state).
Adding directly to the stateSubject bypassing the mapEventToState (for example: I will do all the work in AppBloc and in the and just adding(sync) a new state to AuthBloc and then dispatch AppInitialized).
I don't know if is a good ideea, just saying :)

**Comment by felangel** [comment]
I think that’s totally fine! It’s intentional that there is only one way to change a bloc’s state. 

Bloc attempts to make state changes predictable by regulating when a state change can occur and enforcing a single way to change state throughout an entire application.

If you’re worried about things becoming too cluttered then I would ask the question, what does AppInitialized actually mean? I think you might find that you don’t need the AppBloc. Hope that helps!

**Comment by cosinus84** [comment]
Yes you might be right regarding AppBloc, but I am thinking to have an main AppBloc that may do something in the future.I am ok with the solution found because, as I said in previous comment, if I add more blocs that need to do work when app starts I can make some rx magic to combine, etc....
 I also hope that this discussion might helps others that are trying everyday take over the world :)
Thank you for yor time and I hope this becomes the package the official google package for BLoC.
