### ISSUE TITLE
When to use Equatable?

### ISSUE THREAD

**Issue by hitrop** [felangel/bloc#2122]
I just started with bloc and kind of confused when to use equatable? Is equatable required when my state class is immutable? Or is it only needed when my state class is not immutable?

**Comment by felangel** [comment]
Hi @hitrop 👋 
Thanks for opening an issue!

You can check out the [FAQs](https://bloclibrary.dev/#/faqs?id=when-to-use-equatable) for a detailed answer to your question 👍
