### ISSUE TITLE
No relation between documentation tutorial and this repository

### ISSUE THREAD

**Issue by zurcacielos** [felangel/bloc#2123]
The documentation tutorial at
- https://bloclibrary.dev/#/flutterweathertutorial

points to this repository, where it's expected to have folders like:
lib/
-- bloc
-- models
-- repositories

Which makes learning confusing.

**Comment by felangel** [comment]
Hi @zurcacielos 👋 
Thanks for opening an issue and sorry for the confusion. The [flutter_weather example](https://github.com/felangel/bloc/tree/master/examples/flutter_weather) was revamped and the tutorial is currently out-dated but I will try to update it sometime this week 👍

**Comment by felangel** [comment]
Closing this as I'm going to track this work as part of #2276 👍
