### ISSUE TITLE
Updating flutter_bloc to 6.1.0 

### ISSUE THREAD

**Issue by VladislavYakonyuk** [felangel/bloc#2126]
Hi, updated flutter_bloc and now BlocSupervisor does not work 
![image](https://user-images.githubusercontent.com/58368922/106637180-9431bd00-65ac-11eb-9818-93f963d3918d.png)
![image](https://user-images.githubusercontent.com/58368922/106637229-a01d7f00-65ac-11eb-9d30-53e02c7b67a0.png)

Version:
```yaml
flutter_bloc: ^6.1.0
```

**Comment by fchiumeo** [comment]
[Migration note](https://bloclibrary.dev/#/migration?id=%e2%9d%97blocsupervisor-has-been-removed)

**Comment by VladislavYakonyuk** [comment]
Thanks!
