### ISSUE TITLE
How to use hero animation between two separated bloc ?

### ISSUE THREAD

**Issue by omidraha** [felangel/bloc#2128]
Hi,

How to use `Hero` animation between two separated `bloc` ?
I have two page with separated bloc.
And when I use `hero` animation between them, I got this error:

```dart
 CubitProvider.of() called with a context that does not contain a Cubit
``` 
I can't use one share bloc between them, because each of these pages has its own bloc (Every feature has own bloc).

Thanks.

**Comment by felangel** [comment]
Hi @omidraha 👋 
Thanks for opening an issue!

Can you please provide a link to a reproduction sample which illustrates the issue you're facing? I'm happy to take a look and open a pull request with suggestions, thanks! 🙏

**Comment by omidraha** [comment]
Sorry it was related to hot reload,
And fixed after new run.

**Comment by omidraha** [comment]
The main issue is when we would like to have hero animation between two widgets,
While data of second widget needs to load from an API, so we have one extra loading widget between them.
And hero is not working on forward, and only works backward (when you press back button).
Here is a sample code to show this problem:

https://github.com/omidraha/sample_auth
