### ISSUE TITLE
The method 'switchMap' isn't defined for the type 'Stream'.

### ISSUE THREAD

**Issue by RomanSoviak** [felangel/bloc#2129]
I have 
```
 flutter_bloc: ^6.1.1
  rxdart: ^0.25.0
```

```
 @override
  Stream<Transition<HomeEvent, HomeState>> transformEvents(
    Stream<HomeEvent> events,
    TransitionFunction<HomeEvent, HomeState> transitionFn,
  ) =>
      events.switchMap(transitionFn);
```
What should I use now for canceling events? Or how can rewrite my old code?

**Comment by felangel** [comment]
Hi @RomanSoviak 👋 
Thanks for opening an issue!

You can take a look at https://github.com/felangel/bloc/blob/daf09b994cbcc4b7105572d954c069e4795abbd0/examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart#L23 for an example 👍 

Hope that helps 😄
