### ISSUE TITLE
[bloc_test] How to test a bloc that adds event to itself

### ISSUE THREAD

**Issue by canvural** [felangel/bloc#2134]
Hello,

I have the following bloc (just a pseudo code for simplicity)
```dart
@override
  Stream<FooState> mapEventToState(
    FooEvent event,
  ) async* {
    if (event is Foobar) {
    	// Handling logic
		...
		// At some point a new event is added
		add(NewEvent();
		...
    }
	...
}
```

Usually, if a bloc uses another bloc, I can mock the other bloc and run assertions on it. But in this case, it uses itself. How can I test this scenario?

**Comment by jeroen-meijer** [comment]
Personally, I wouldn't add events as a result of another event.
I'd rather move the logic that `Foobar` and `NewEvent` share into a separate function and just make sure the state changes are correct.

In the end, I don't think any part outside the bloc should care _how_ it's doing its logic, as long as the states it produces are valid. 👍🏻 

Hope that made sense 😄

**Comment by felangel** [comment]
Hi @canvural 👋 
Thanks for opening an issue!

At the end of the day the bloc takes events as input and emits states so your test should just verify that when event x is added, state y is emitted. Whether the bloc adds more events internally or not is just an implementation detail and does not impact the behavior.

As @jeroen-meijer mentioned, in general, it's not recommend to add more events internally. Rather than adding `NewEvent` you should just execute the logic you'd like and `yield` a new state.

Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by PuffPastry** [comment]
Just as an fyi, when I listen to a stream from another bloc in a handler, that async gap means I cannot yield states and therefore the logic is dispatched to other events, where the bloc context allows me to emit States again. Something like this:

```
   on<_Init>((event, emit) async {
      positionSubscription ??=
          positioningCubit.stream.listen(_positionListener);
   });

... 

_positionListener(positioningState) {
    if (positioningState.lastKnownLocation != state.lastKnownLocation) {
      add(Event.updateLocation(
        lastKnownLocation: positioningState.lastKnownLocation,
      ));
}
```

**Comment by makri-aymen** [comment]
@felangel, but there are some cases where we have a bunch of events that will treat data, but in some cases it will call EventReconfigureBloc which load the initial data again, sop it's not ideal to add all cases of EventReconfigureBloc event that I have already well tested to each event that I'm testing!
