### ISSUE TITLE
How to trigger event from my drawer (filter function)

### ISSUE THREAD

**Issue by farmcow** [felangel/bloc#2138]
hi, i'm having issue triggering the yield state when i try to pass data from my drawer to the browse page, the data is successfully passed to the event but when i try to yield the data, it does not update or replace the existing state results . I'm not sure which part went wrong, can you guide me on how to solve this issue please ? thank you in advance !

this is the browse bloc file (browse_bloc.dart)

    if (event is BrowseUpdated) {
      print(event.query);
      yield BrowseSuccess(query: event.query);
      } catch (error) {
        yield BrowseFailure(error: error.toString());
      }

this is the drawer page (filterbar.dart)

    return FlatButton(
        color: Colors.transparent,
        onPressed: () {
          browseBloc.add(BrowseUpdated('updated text'));
        },
        child: Text(
          'Search',
          style: TextStyle(
            fontFamily: 'Syne',
            fontSize: 12.0,
          ),
        ),
        shape: RoundedRectangleBorder(
            side: BorderSide(color: Colors.grey),
            borderRadius: BorderRadius.all(Radius.circular(5))));

**Comment by SEGVeenstra** [comment]
What does your `BrowseUpdated` class look like?
Did you override the props with the query?

**Comment by farmcow** [comment]
> What does your `BrowseUpdated` class look like?
> Did you override the props with the query?

hi @SEGVeenstra here is my BrowseUpdated class
browse_event.dart

class BrowseUpdated extends BrowseEvent {
  final String query;

  const BrowseUpdated(this.query);

  @override
  List<Object> get props => [query];

  @override
  String toString() {
    return 'BrowseUpdated { query: $query }';
  }
}

I managed to get the data from print(event.query); the problem is yield BrowseSuccess, when i pass the data to BrowseSuccess it doesn't seems to work at my browse page

browse_page.dart

Widget build(BuildContext context) {
    return BlocListener<BrowseBloc, BrowseState>(
      listener: (context, state) {

        if (state is BrowseLoading) {
          showDialog(
              context: context,
              builder: (BuildContext context) {
                return LoadingIndicator();
              });
        }

        if (state is BrowseSuccess) {
          print(state.query);
          Navigator.pop(context);
        }

        if (state is BrowseFailure) {
          showDialog(
              context: context,
              child: new AlertDialog(
                backgroundColor: Colors.red,
                content: Text('${state.error}'),
              ));
        }
      },
      child: BlocBuilder<BrowseBloc, BrowseState>(
        builder: (context, state) {
          
          if (state is BrowseSuccess) {
            print(state.query);
            context.watch<BrowseBloc>().isFetching = false;
          }

          return Container(
            margin: EdgeInsets.only(top: 80.0),
            child: Column(children: <Widget>[
              _searchField(),
              _titleSection(),
              _filterSection(widget.scaffoldKey),
              _productSection(),
            ]),
          );
        },
      ),
    );
  }

**Comment by SEGVeenstra** [comment]
@farmcow Ok, and what does the code look like that is yielding the BrowseSuccess?
And could you also show the BrowseSuccess state implementation?

**Comment by farmcow** [comment]
the state in my browse_page.dart doesn't seems to trigger anything after yielding the BrowseSuccess

class BrowseSuccess extends BrowseState {
  final String query;

  const BrowseSuccess({
    @required this.query,
  });

  List<Object> get props => [query];

  @override
  String toString() => ' BrowseSuccess { products: $query }';
}

**Comment by SEGVeenstra** [comment]
I'm not sure if this has anything to do with it, but I don't think you suppose to use the `context.watch` in your `BlocBuilder`.
I think you can use a regular builder:
https://bloclibrary.dev/#/migration?id=%e2%9d%97contextbloc-and-contextrepository-are-deprecated-in-favor-of-contextread-and-contextwatch

**Comment by felangel** [comment]
Hi @farmcow 👋 
Thanks for opening an issue!

Are you still experiencing an issue? If so can you please provide a link to a reproduction sample and I'm happy to take a look 👍

**Comment by felangel** [comment]
Closing for now but if you're still having trouble please provide a reproduction sample and I'm happy to take a look 👍
