### ISSUE TITLE
_hasReachedMax is not working

### ISSUE THREAD

**Issue by smakarov** [felangel/bloc#2141]
this line 
`bool _hasReachedMax(int postsCount) => postsCount < _postLimit ? false : true;`
has no sense and not working, because we reaching max at the start.
This is working solution
```
bool _hasReachedMax(int postsCount) =>
      state.status == PostStatus.success && state.hasReachedMax;
```

**Comment by felangel** [comment]
Hi @smakarov 👋 
Thanks for opening an issue!

Can you please provide instructions to reproduce the issue?

`_hasReachedMax` is only used internally on lines 47 and 56 in the bloc where the status is being set to `PostStatus.success`.

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional information and I'm happy to continue the conversation 👍
