### ISSUE TITLE
Using BlocBuilder to return AppBar

### ISSUE THREAD

**Issue by ariefwijaya** [felangel/bloc#2144]
**Describe the bug**
I'm trying to add BlocBuilder logic in the **appBar** of scaffold. But I got an error 

> The argument type 'BlocBuilder<dynamic, int>' can't be assigned to the parameter type 'PreferredSizeWidget'.

**To Reproduce**
add BlocBuilder in the appBar Scaffold

```Dart
 Scaffold(
                  key: globalScaffoldKey,
                  appBar:  BlocBuilder<CounterBloc, CounterState>(
                          builder: (context, state) {
                              if(state is StatusFirst)
                              {
                                   return AppBar(title: Text('First'));
                               }
                               
                                if(state is StatusFirst)
                              {
                                   return AppBar(title: Text('First'));
                               }
                                   
                          },
                      )
 )
```

You will see the error directly in the Code Editor (I am using VisualCode)

**Expected behavior**
Can use BlocBuilder in appBar attribute to return AppBar Widget

**Flutter Doctor **
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.1 20D74 darwin-x64, locale en-ID)
    • Flutter version 1.22.6 at /Users/ittcel/Documents/development/flutter
    • Framework revision 9b2d32b605 (3 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ittcel/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by jurej1** [comment]
@ariefwijaya I have an Idea. You can wrap the BlocBuilder in the `PreferredSize()` Widget and then give it a size, and as its child have a BlocBuilder. Or you can do completely separate Widget like this.

```
class MyAppBar extends StatelessWidget with PreferredSizeWidget {
  @override
  Widget build(BuildContext context) {
    //BlocBuilder ....
    return Container();
  }

  @override
  Size get preferredSize => Size.fromHeight(kToolbarHeight);
}
```

**Comment by jurej1** [comment]
Or also in your case you can just do like this.

```
return Scaffold(
      appBar: AppBar(
        title: BlocBuilder<CounterBloc, CounterState>(
          builder: (context, state) {
            if (state is StatusFirst) {
              return Text('First');
            }

            if (state is StatusFirst) {
              return Text('First');
            }
          },
        ),
      ),
    );
```

**Comment by ariefwijaya** [comment]
> @ariefwijaya I have an Idea. You can wrap the BlocBuilder in the `PreferredSize()` Widget and then give it a size, and as its child have a BlocBuilder. Or you can do completely separate Widget like this.
> 
> ```
> class MyAppBar extends StatelessWidget with PreferredSizeWidget {
>   @override
>   Widget build(BuildContext context) {
>     //BlocBuilder ....
>     return Container();
>   }
> 
>   @override
>   Size get preferredSize => Size.fromHeight(kToolbarHeight);
> }
> ```

Thank you, I solved it using this idea.

**Comment by paulinavita** [comment]
> Or also in your case you can just do like this.
> 
> ```
> return Scaffold(
>       appBar: AppBar(
>         title: BlocBuilder<CounterBloc, CounterState>(
>           builder: (context, state) {
>             if (state is StatusFirst) {
>               return Text('First');
>             }
> 
>             if (state is StatusFirst) {
>               return Text('First');
>             }
>           },
>         ),
>       ),
>     );
> ```

Wonder why I got this when implementing the code? Hmm

```
Cannot hit test a render box with no size.
I/flutter ( 4988): The hitTest() method was called on this RenderBox: RenderSemanticsAnnotations#c2803 relayoutBoundary=up12:
```

**Comment by Binozo** [comment]
> @ariefwijaya I have an Idea. You can wrap the BlocBuilder in the `PreferredSize()` Widget and then give it a size, and as its child have a BlocBuilder. Or you can do completely separate Widget like this.
> 
> ```
> class MyAppBar extends StatelessWidget with PreferredSizeWidget {
>   @override
>   Widget build(BuildContext context) {
>     //BlocBuilder ....
>     return Container();
>   }
> 
>   @override
>   Size get preferredSize => Size.fromHeight(kToolbarHeight);
> }
> ```

The keyword `with` doesn't seem to work anymore in Flutter version `3.16.8`.

You need to switch it out with `implements`:

```dart
class MyAppBar extends StatelessWidget implements PreferredSizeWidget {
  const MyAppBar({super.key});

  @override
  Widget build(BuildContext context) {
    //BlocBuilder ....
    return Container();
  }

  @override
  Size get preferredSize => Size.fromHeight(kToolbarHeight);
}

```
