### ISSUE TITLE
Is it necessary to use BlocProvider.of when using DI?

### ISSUE THREAD

**Issue by SaeedMasoumi** [felangel/bloc#215]
I provide lazy singletons for all of my bloc instances using [get_it](https://pub.dartlang.org/packages/get_it), So I simply inject them into my widgets.

I want to know that It's necessary to use `BlocProvider.of` or It's ok to use any DI libraries?

**Comment by felangel** [comment]
Hi @SaeedMasoumi 👋 
Thanks for opening an issue!

Great question! `BlocProvider` is there if you need it but there's nothing stopping you from using any other DI libraries 👍

**Comment by Feelthewind** [comment]
Would you make another sample app with kiwi later?
