### ISSUE TITLE
BlocBuilder inside Stateful widget has unexpected behaviour when navigating to a new screen when the state has TickerProviderStateMixin

### ISSUE THREAD

**Issue by mmazurovsky** [felangel/bloc#2155]
**Describe the bug**
When I use "with TickerProviderStateMixin" in my stateful widget's state, the BlocBuilder (BlocConsumer with builder) performs unexpected build when navigating to a new screen via Navigator.push method. 

There is a screen (stateful widget which has a mixin TickerProviderStateMixin) with a list of entities which are loaded from the backend. The loading events and  states are managed using Bloc ^6.1.1. There are loading state and loaded state. When entities are loaded the user should be able to tap on the entity object and proceed to the detailed screen of the entity. This navigation is done by using flutter's navigator push method (I don't use bloc for navigation). The problem is when I tap on the entity to proceed to the detailed page, the BlocBuilder gets triggered and It returns the widget from the "else" clause which goes after all "if state is LoadingState", "if state is LoadedState" so the Loaded state gets lost. So when I go back from the detailed screen (navigator.pop), the screen with the list of entities is empty. Deleting TickerProviderStateMixin form the state resolves the issue and results in expected behaviour.

Code fragment:
```class _ColorsListPageState extends State<ColorsListPage>
// if "with TickerProviderStateMixin" uncommented, navigator push unexpectedly triggers BlocBuilder to return purple Container
    with
        TickerProviderStateMixin {
  List<int> colorsList;

  @override
  void initState() {
    BlocProvider.of<ColorsBloc>(context)..add(InitialLoadColors());
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          widget.title,
        ),
        backgroundColor: widget.color,
      ),
      body: BlocConsumer<ColorsBloc, ColorsState>(
        listener: (context, state) {
          if (state is ColorsLoadingState) {
            print('loading ' + DateTime.now().toString());
          } else if (state is ColorsLoadedState) {
            print('loaded ' + DateTime.now().toString());
          } else {
            print('some unknown state');
          }
        },
        builder: (context, state) {
          if (state is ColorsLoadingState) {
            return _buildLoading();
          } else if (state is ColorsLoadedState) {
            if (colorsList != state.loadedColors) {
              colorsList = state.loadedColors;
              return _buildList();
            }
          }
          // Purple Container which is unexpectedly returned on navigator push
          return Container(
            color: Colors.purple,
            child: Center(
              child: Text('Lost ColorsLoadedState'),
            ),
          );
        },
      ),
    );
  }
```

Repo with the full code: https://github.com/mmazurovsky/flutter_bloc_navigation_trouble

Gif to visualize the issue: https://gifyu.com/image/V0rT

**Expected behavior**
Gif to visualize the expected behaviour: https://gifyu.com/image/VCPp

**Logs **
Paste the output of running `flutter doctor -v` here.
![image](https://user-images.githubusercontent.com/64072949/107948143-7dc03400-6fa4-11eb-97ab-0080f5189e7f.png)

It might be not a Bloc bug but it is still worth mentioning. My googling didn't get the results and I found out the problem is with TickerProviderStateMixin by randomly commenting code lines.

**Comment by jurej1** [comment]
You do not handle the NavigateDetailColor event in the ColorsBloc.
So when this event is triggered it goes thru the mapEventToState in colors Bloc.
There is currently no method that would cover this event, so new event is added but no state is yield.
This is probably why you are facing this error.

In color_list_page.dart in line 79 (onTap method) just do Navigator.of(context).push(MaterialPageRoute(builder: (_) => ColorDetailPage(color: color, title: title, index: materialIndex)));

**Comment by mmazurovsky** [comment]
@jurej1 Thank you for the reply!
> You do not handle the NavigateDetailColor event in the ColorsBloc.
Yes, I have NavigateDetailColor event in ColorsBloc, but I don't really add it to the event's stream in the code. The line that adds it is commented. I've just created a new commit where I deleted any NavigateDetailColor mentions in the code so as not to mislead people.

The problem is not connected with the NavigateDetailColor event.

**Comment by felangel** [comment]
Hi @mmazurovsky 👋 
Thanks for opening an issue and sorry for the delay!

I took a look and opened a [pull request to fix the issue](https://github.com/mmazurovsky/flutter_bloc_navigation_trouble/pull/1).

Hope that helps and closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by mmazurovsky** [comment]
Thank you very much, @felangel !
My mistake, I can see now that nested if condition inside bloc builder caused the trouble
