### ISSUE TITLE
QUESTION ABOUT BLOC'S EVENTS

### ISSUE THREAD

**Issue by jurej1** [felangel/bloc#2159]
EXAMPLE!!!

Lets say we have a bloc with this **states**

```
class ProductsLoading {}

class ProductsLoadingSuccess {
    final List<Product> products;
 }

class ProductsLoadFailure {}
```

And then we have the **events**

```
class AppStarted {}

class ProductAdded { final Product product; }

class ProductUpdated { final Product product;}

class ProductDeleted { final Product product}
```

And then lets say we have a bloc listener that we want to listen to this bloc so when the card gets added we can display a SnackBar. How is that possible? Can we get the blocs event that was added?

**Comment by felangel** [comment]
Hi @jurej1 👋 
Thanks for opening an issue!

The UI should only react to state changes so in this case if you need to differentiate based on an action, I would recommend adjusting your state.

```dart
class ProductAddSuccess {...}
class ProductUpdateSuccess {...}
class ProductDeleteSuccess {...}
```

Then you can use a BlocListener to show a SnackBar based on the state type. Hope that helps 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄
