### ISSUE TITLE
InfiniteListView with follow button: one bloc per all list or one bloc per item?

### ISSUE THREAD

**Issue by romaluca** [felangel/bloc#216]
Hi, i have a infinite list view.
Every items has a follow button.
Is better put a bloc in every item with follow Event or manage the Event in the bloc list?
Thanks

**Comment by felangel** [comment]
Hi @romaluca 👋 
Thanks for opening an issue!

I’d recommend starting with a bloc for the entire list and seeing if that fits your needs.
You can check out the [infinite list example](https://felangel.github.io/bloc/#/flutterinfinitelisttutorial) for an example of you haven’t already 👍

Hope that helps!
