### ISSUE TITLE
[Question] dispose for generated route bloc/cubit access

### ISSUE THREAD

**Issue by fionues** [felangel/bloc#2162]
I am trying to provide a bloc/cubit to several screens according to the [documentation for generated route access](https://bloclibrary.dev/#/recipesflutterblocaccess?id=app-router), since I need to share a state across three different screens.

According to the documentation the dispose of the bloc that is shared should be called in the _AppState. Does this mean the dispose is only called when the top most App state is disposed? So it would live longer than the screens that use the bloc?

So is the difference to provide the bloc by (Multi)Provider on the top most app level ([Global access](https://bloclibrary.dev/#/recipesflutterblocaccess?id=global-access)) that you are in control where to access it but it lives in the same state?

**Comment by felangel** [comment]
Hi @fionues 👋 
Thanks for opening an issue!

Yup, that's correct. In both cases the bloc is only disposed when the App is unmounted but in the case of global access it can be accessed from anywhere in the widget tree whereas with the generated route access you can scope it to one or more routes.

Hope that helps 👍

**Comment by fionues** [comment]
@felangel yes, thank you!
