### ISSUE TITLE
Best practices locate bloc in or over screen

### ISSUE THREAD

**Issue by aBuder** [felangel/bloc#2163]
Hi, I love bloc library and this way to abstract UI from business logic. I used it in some projects, but in different ways. So I would like maybe make an open discussion or to get a best practice for **Blocs** and **Screens**.

In the most cases we have one **bloc** for one **screen**. The bloc fetch some data and to some other stuff and bring out the different states to UI. So the UI maybe have some different states like **loading**, **loaded** and **error**.

So what is best practice to locate the bloc of the screen. 

I faced 2 ways, first where the bloc is over the screen and second where bloc is in screen widget itself.

![Ohne Titel](https://user-images.githubusercontent.com/1265139/108257747-85780800-715f-11eb-8a26-a69a6ee6b975.png)

## 1. Locate Bloc over the screen
Here I have to pass the bloc over screen in navigation. It looks ugly but works and the bloc is over the screen.
```dart
    await Navigator.of(context).push(
      MaterialPageRoute(
        builder: (context) {
          return BlocProvider(
            lazy: true,
            create: (context) => CourseListBloc(
              courseRepository: courseRepository,
            )..add(LoadCourseListEvent()),
            child: CourseListScreen(),
          );
        },
      ),
    );
```
## 2. Bloc is in Screen
In this example the bloc is screen widget itself, but I have to create a separate content widget, because **BlocBuilder** is not 
accessible  via ** BlocProvider.of<AppointmentTemplateDetailCubit>(context)**

```dart
class AppointmentTemplateDetailScreen extends StatelessWidget {
  final AppointmentTemplate appointmentTemplate;

  AppointmentTemplateDetailScreen({
    @required this.appointmentTemplate,
  }) : assert(appointmentTemplate != null);
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Zeitpunkt wählen'),
      ),
      body: BlocProvider(
        create: (context) => AppointmentTemplateDetailCubit(
          appointmentRepository:
              RepositoryProvider.of<AppointmentRepository>(context),
          appointmentTemplate: appointmentTemplate,
        )..load(),
        child: AppointmentTemplateDetailContent(),
      ),
    );
  }
}
```

So my question to @felangel is there some best practices locating the bloc in or over screen. How do you handle this?

**Comment by Abhishek01039** [comment]
it depends on your use case.
if you want to persist `appbar`(or any other widget which you want Persist for all state) then 2nd approach would be good otherwise 1st.

**Comment by felangel** [comment]
Hi @aBuder 👋 
Thanks for opening an issue!

In general, I highly recommend maintaining a clear separation between the widget which is providing the bloc and the widget which is consuming the bloc. This allows you to easily test how the UI interacts with and consumes the bloc by injecting a mock instance.

With that being said, I prefer to create a top-level feature widget which is the entrypoint for the feature and the responsibility of the entrypoint is to provide the relevant bloc to the view.

```dart
class AppointmentTemplateDetailsScreen extends StatelessWidget {
  const AppointmentTemplateDetailScreen({
    @required this.appointmentTemplate,
  }) : assert(appointmentTemplate != null);

  final AppointmentTemplate appointmentTemplate;

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => AppointmentTemplateDetailCubit(
          appointmentRepository: context.read<AppointmentRepository>(),
          appointmentTemplate: appointmentTemplate,
      )..load(),
      child: AppointmentTemplateDetailView(),
  }
}

class AppointmentTemplateDetailView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocBuilder< AppointmentTemplateDetailCubit, AppointmentTemplateDetailState>(
      builder: (context, state) {...}
    );
  }
}
```

This allows the `AppointmentTemplateDetailView` to be decoupled from the `AppointmentTemplateDetailScreen` making it easy to test and providing a clear separation of responsibilities. In addition, other features don't need to know about the dependencies and internal implementation details of `AppointmentTemplateDetailScreen`, they can just route to the relevant feature without knowing what bloc/cubit it needs.

Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation! Also, if you haven't already feel free to join the [bloc discord](https://discord.gg/bloc) as I feel it's a great place to have these types of discussions in real time with other members of the community 👍
