### ISSUE TITLE
flutter listview inside singleChildScrollview

### ISSUE THREAD

**Issue by cgowthamanmca** [felangel/bloc#2164]
how to add pagination for listview(reverse ListView) when it is placed inside singleChildScrollview? my problem is, not able to find the exact threshold. How to solve this?

SingleChildScrollView(
          controller: _scrollController,
          child: Column(
            children: [
              _buildAcceptRejectButton(),
              ListView.builder(
                  shrinkWrap: true,
                  reverse: true,
                  physics: NeverScrollableScrollPhysics(),
                  itemCount: _bloc.totalRecords != 0 && !_bloc.isLastPage
                      ? _bloc.comments.length + 1
                      : _bloc.comments.length,
                  itemBuilder: (context, int index) {
                    return index >= _bloc.comments.length
                        ? Container(
                            child: Center(
                              child: CircularProgressIndicator(),
                            ),
                          )
                        : TeleMedicineCommentWidget(
                            _bloc.comments[index],
                            isSameUser,
                            onTapEdit: _onTapEdit,
                            index: index,
                          );
                  })
            ],
          ),
        )

**Comment by Abhishek01039** [comment]
wrap your `ListView.builder` widget to `Expanded`.

**Comment by felangel** [comment]
Hi @cgowthamanmca 👋 
Thanks for opening an issue!

Please refrain from opening issues that don't directly pertain to the bloc library. If you have general questions about Flutter you can ask in the #off-topic channel of the [bloc discord](https://discord.gg/bloc), [post on StackOverflow](https://stackoverflow.com/), etc.

Thanks! 🙏
