### ISSUE TITLE
Trigger state change from repository

### ISSUE THREAD

**Issue by Fiyiin** [felangel/bloc#2169]
I'm trying to trigger a state change from the repository, what's the right way of doing this.

```
class OtpRepository {
  await _auth.verifyPhoneNumber(
        phoneNumber: phoneNumber,
        verificationCompleted: (PhoneAuthCredential credential) {
        // When function runs, do
          emit(OtpState.success(credential))
        },
        verificationFailed: (FirebaseAuthException e) {
          if (e.code == 'invalid-phone-number') {
            
          }
        },
        codeSent: (String verificationId, int resendToken) {
       
        },
        codeAutoRetrievalTimeout: (String verificationId) {},
      );
 }
      ```

**Comment by Gene-Dana** [comment]
In the Firebase Login tutorial, the BLoC itself is listening to the User in the repo. 

![image](https://user-images.githubusercontent.com/45580241/108860478-39442200-75bc-11eb-83b3-b2802a91211f.png)

![image](https://user-images.githubusercontent.com/45580241/108860578-54af2d00-75bc-11eb-95c3-e56aa1a867b8.png)

I believe the only way to trigger the state change is in the BLoC itself

See how the logout state change is triggered here?
![image](https://user-images.githubusercontent.com/45580241/108860756-80caae00-75bc-11eb-831c-445293737ab5.png)

![image](https://user-images.githubusercontent.com/45580241/108860784-89bb7f80-75bc-11eb-975a-a8d91ea1e32a.png)

**Comment by felangel** [comment]
@Fiyiin I would recommend either exposing a `Stream` of updates from the repository or having callbacks so that the bloc can get notified of changes to the auth state and add internal events.

**Comment by Gene-Dana** [comment]
It's confusing at first ! 

'exposing a Stream of updates from the repository' looks like this. 

![image](https://user-images.githubusercontent.com/45580241/109366497-901e5580-7861-11eb-94e1-0d9b43dbec1e.png)

That's because the Bloc is really what should be emitting the state changes. The repo itself is intended to be that abstraction.
