### ISSUE TITLE
Can you please explain how BlocBuilder works?

### ISSUE THREAD

**Issue by Turbozanik** [felangel/bloc#2170]
I was trying to understand how BlocBuilder works from the sources, but didn't succeed. I am really interested in BlocBuilder.

We were creating a custom bloc implementation for our company, and stuck with the StreamBuilder.
By default it caches the latest item it has. And there is no clean way(passing null to stream sink was a workaround) to clear that, so we were having duplicate dialogs after screen rotation for example.

And BlocBuilder is working just fine, no duplicates, same time it seems like it's based on a stream, so how does it work? 
Any help is appreciated.

**Comment by Gene-Dana** [comment]
Hi there ! This is a really helpful document to me

https://pub.dev/packages/flutter_bloc

![image](https://user-images.githubusercontent.com/45580241/108760711-fb8fbc80-751b-11eb-8153-6cd72d3c3ae2.png)

**Comment by Turbozanik** [comment]
Yep, I read it, but it's still unclear, how it works, it has a Cubit under the hood, but mapEventToState is a sync* and is a stream, so we are pushing our states to a stream. And the only way I can imagine it working, is that Cubit should hold that stream, and pass data to the builder. But I can't find that BlocBuilder's Cubit logic anywhere, so it's steel a black box for me.

Or maybe I misunderstood the whole concept.

**Comment by felangel** [comment]
Hi @Turbozanik 👋 
Thanks for opening an issue!

`BlocBuilder` subscribes to the bloc/cubit (which is a `Stream`) and invokes the `builder` with the latest `state` whenever the state changes. Hope that helps 👍

**Comment by Turbozanik** [comment]
Ok, one last question, does it subscribe to bloc/cubit using StreamBuilder, or by calling listen?

**Comment by felangel** [comment]
> Ok, one last question, does it subscribe to bloc/cubit using StreamBuilder, or by calling listen?

By calling listen 👍

**Comment by Turbozanik** [comment]
Thanks! Now it makes sense to me.

**Comment by Turbozanik** [comment]
One more last question =), can you please show me how do you create a widget on base of this stream.listen?

**Comment by felangel** [comment]
Check out the BlocListener code for an example: https://github.com/felangel/bloc/blob/94d5ed24af2afb4773a758517577394dc61307b0/packages/flutter_bloc/lib/src/bloc_listener.dart#L178

**Comment by Turbozanik** [comment]
Thanks! Now it feels like I am starting to understand.

**Comment by Gene-Dana** [comment]
@felangel, is this a scenario where a BlocListener would be appropriate? 

`
class SignUpForm extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocListener<SignUpCubit, SignUpState>(
      listener: (context, state) {
        if (state.status.isSubmissionFailure) {
          Scaffold.of(context)
            ..hideCurrentSnackBar()
            ..showSnackBar(
              const SnackBar(content: Text('Sign Up Failure')),
            );
        }
      },
`

https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/lib/sign_up/view/sign_up_form.dart

**Comment by Turbozanik** [comment]
Maybe I am wrong, but personally I don't see any reason to use BlocListener over BlocBuilder except if you are doing some optimization and want to reduce widget depth.
BlocListener  is included in BlocBuilder, so I would just use BlocBuilder.

But I am also interested in this =).

**Comment by felangel** [comment]
@Turbozanik BlocBuilder is responsible for returning a widget when the state changes. If you're performing side-effects like showing a snackbar you should not be using `BlocBuilder`. `BlocListener` should be used for cases where you aren't building a widget in response to a state change.

**Comment by felangel** [comment]
@Turbozanik feel free to [join the bloc discord](https://discord.gg/bloc) if you have more questions like this as it'd probably be faster and easier to get responses in real-time from the community.

**Comment by Turbozanik** [comment]
Will do, thanks again!
