### ISSUE TITLE
TabBar Example

### ISSUE THREAD

**Issue by gutisalex** [felangel/bloc#2174]
I just open a new ticket on this because I dont know if comments on closed issues getting your attention?!

I might have a case where it would be convenient to have a cubit/bloc but I am not sure if its really needed for that.. 

So let's say I have a TabBar and some views. Inside of a view somewhere in the depth of the widget tree I have a button and want to change the currentIndex of the tabBar and jump to the second view for example. 

Or what if I want to change tab styles according to the currentIndex:

```dart
borderRadius: BorderRadius.only(
                topLeft: Radius.circular(_tabController.index == 0 ? 9 : 0),
                topRight: Radius.circular(_tabController.index == 3 ? 9 : 0),
              ),
```

Does it make sense to have a cubit for that? I could probably use a GlobalKey for that, too?! 

What do you think?

**Comment by felangel** [comment]
Hi @gutisalex 👋 
Thanks for opening an issue!

Generally, I recommend having a bloc/cubit to handle any business logic pertaining to a specific feature. In this case, the current index is more of a presentational state which is okay to be handled by a `StatefulWidget`. You can definitely create a bloc/cubit to manage this state if you want to be able to modify that state from a different part of the widget tree and/or if you want to be able to track the state changes over time 👍 

Hope that helps!

Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 😄
