### ISSUE TITLE
Question: how to pass dynamic bloc to new screen

### ISSUE THREAD

**Issue by Martibis** [felangel/bloc#2175]
I have the following scenario. I have a feed of posts which has its own globally accessible bloc, but each post has its own bloc as well. From a post a user can navigate to a new screen through a generated route. I want to access the bloc of a post in the the comments screen. How would I achieve this?

Whatever I seem to try, I seem to get to the route fine, but than I end up with the following error after hot reloading:

 ```
The following assertion was thrown building Builder(dirty):
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.

The relevant error-causing widget was
CupertinoTabView
lib\main.dart:99
When the exception was thrown, this was the stack
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
package:flutter/…/widgets/framework.dart:3906
#1      Element._debugCheckStateIsActiveForAncestorLookup
package:flutter/…/widgets/framework.dart:3920
#2      Element.getElementForInheritedWidgetOfExactType
package:flutter/…/widgets/framework.dart:3986
#3      Provider._inheritedElementOf
package:provider/src/provider.dart:304
#4      Provider.of
```

The structure looks something like this:

```
BlocProvider (FeedBloc)
    CupertinoTabScaffold
        CupertinoTabView (navigatorKey: tabNavKeys[0], onGenerateRoute: widget.appRouter.onGenerateRouteFromFeed)
            TabBar
            TaBarview
                BlocBuilder (FeedBloc)
                    Listview builder 
                        item: BlocProvider (PostBloc)
                                     BlocBuilder (PostBloc)
                                         PostWidget
```
From the PostWidget above I navigate to a new screen from where I want to access the PostBloc. I currently navigate to the new screen like so:

```
Navigator.of(context).push(MaterialPageRoute(
                    builder: (_) => MultiBlocProvider(
                            providers: [
                              BlocProvider.value(
                                  value:
                                      BlocProvider.of<FeedPostBloc>(context)),
                            ],
                            child: PostComments<T>(
                              post: p,
                            ))));
```

I am fairly certain the issue lies with me passing the BlocProvider wrongly as when I remove the MultiBlocProvider and instead use builder: (_) => PostComments<T>(post: p) the problem is not there.

**Comment by Martibis** [comment]
I currently solved this by passing the context through routesettings.arguments (but I'm not sure this is the right way to do it).

**Comment by Martibis** [comment]
Update: 
Actually this doesn't seem to work as I get the following error on hot reload:
```
The following assertion was thrown building Builder(dirty):
Looking up a deactivated widget's ancestor is unsafe.

At this point the state of the widget's element tree is no longer stable.

To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
```

**Comment by felangel** [comment]
Hi @Martibis 👋 
Thanks for opening an issue!

I would highly recommend taking a look at the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=anonymous-route-access) if you haven't already. Are you able to share a link to a complete reproduction sample? Thanks! 🙏

**Comment by Martibis** [comment]
I've already looked at the bloc access recipes (was following the examples there). At the moment I can not, but I'll see if I can put something together that can reproduce it in the upcoming days and I'll share that here afterwards.

**Comment by Martibis** [comment]
I don't have time to make a minimal example at the moment, might reopen later if I run into the scenario again.
