### ISSUE TITLE
Question: How to add events with parameters from a StatelessWidget?

### ISSUE THREAD

**Issue by daemonchow** [felangel/bloc#2180]
Greetings

I have a StatelessWidget that takes an id as parameter, and right now i call the Bloc (really a cubit) to fetch the data related to the id in the Build method, this does not seem a good practice.

How can i do it better? I don't have a context before build to get the Bloc

The StatelessWidget:
![image](https://user-images.githubusercontent.com/5224867/109561015-5d6f9980-7abb-11eb-9896-26b0ae9a7634.png)

This widget is created for many ids in a ListView, and the BlocProvider is inside that page with the ListView. 

ItemsBloc:
![image](https://user-images.githubusercontent.com/5224867/109561484-fc949100-7abb-11eb-977b-51364923db89.png)

**Comment by felangel** [comment]
Hi @daemonchow 👋 
Thanks for opening an issue!

I would recommend adding the `fetchItem` event to the bloc when it is instantiated via `BlocProvider` and not as part of your `build` method (build can be called many times by the framework and should not contain any side-effects).

```dart
BlocProvider(
  create: (_) => ItemsBloc()..fetchItem(itemId),
  child: ...
)
```

But you can also use a `StatefulWidget` and add the event in `initState` if you really want. Let me know if that helps 👍

**Comment by daemonchow** [comment]
Thanks for the answer @felangel 

The reason I can't add when the bloc is created is that I use this same bloc instance for all the elements in my list and creating a bloc for each seems worse. ¿Isn't it?

I'm going to convert it to `StatefulWidget`, do it on the `initState `and give it a try.

Great work with the library, I just finished a Flutter course with the vanilla bloc approach and refactoring it with this was a breeze, much concise code. 

Something I could not find in the examples was a tutorial of the simple use case of having a list fetched from the internet, on tap of a element goes to detail fetching more information from the net again.

**Comment by felangel** [comment]
Sounds good and thanks for the positive feedback! You can check out [fluttersaurus](https://github.com/felangel/fluttersaurus) for an example of a master/detail experience using a real API.

Closing for now but feel free to comment with any additional questions and I’m happy to continue the conversation 🙂
