### ISSUE TITLE
BlocListener listens after the route has been popped

### ISSUE THREAD

**Issue by aliyazdi75** [felangel/bloc#2182]
Hi Felix,
This is the reproduction code https://gist.github.com/aliyazdi75/a273a2e2306126acfc5b3a6a495b40ba and there is a `BlocListener` on the Dialog page. After the Dialog page has been poped, `BlocListener` still listens on state changes. Is that an expected behavior?
Actual output:
```
I/flutter ( 5401): hi Felix :)
I/flutter ( 5401): Also me Should not print!
```
Expected output:
```
I/flutter ( 5401): hi Felix :)
```

**Comment by felangel** [comment]
Hi @aliyazdi75 👋 
Thanks for opening an issue!

This is working as expected because in this case the state is changing just before the `DialogPage` is disposed. Check out [this modified sample](https://gist.github.com/aliyazdi75/a273a2e2306126acfc5b3a6a495b40ba#gistcomment-3652389) which prints when the `DialogPage` is actually disposed and you can see the state is received before the widget is disposed. Hope that helps! 👍

**Comment by aliyazdi75** [comment]
Thank you. So what should I do to prevent that situation? This means getting value from the dialog and assigning the variable, and the dialog page has not been disposed yet!
It seems so strange. DO you think is that a flutter issue, or is it the expected behavior?

**Comment by felangel** [comment]
@aliyazdi75 I don't think this is a flutter issue. Can you provide more context around what you're trying to achieve? Thanks! 🙏

**Comment by aliyazdi75** [comment]
I have a state which needs to be listened when the Dialog page has not been disposed.
And this code
```
            final ringingResponse = await showDialog<String>(
              context: context,
              builder: (_) => DialogPage(
                BlocProvider.of<DialogBloc>(context),
              ),
            );
```
means that the dialog should be completely popped and returns the value, after this code, I trigger this event by this `BlocProvider.of<DialogBloc>(context).add(Accept());` and this changes to a new state and dialog page makes problem by listening to this new state.
I could fix this problem by splitting that state but I believe the dialog page should be disposed before I trigger new event.

**Comment by felangel** [comment]
@aliyazdi75 You can use [this approach](https://gist.github.com/aliyazdi75/a273a2e2306126acfc5b3a6a495b40ba#gistcomment-3679443). You should be able to update the state when the dialog is popped and ignore state subsequent state changes. Closing for now but feel free to post additional questions/comments and I'm happy to continue the conversation 👍
