### ISSUE TITLE
whenListen() called with generated mockito mock throws "Bad state: when called on a real object."

### ISSUE THREAD

**Issue by NikoBoerger** [felangel/bloc#2197]
**Describe the bug**
Mockito introduced the @GenerateMocks() annotation with nullsafety.
However, It seems like the whenListen() method doesn't work with those generated mocks. The whenListen() method doesn't detect the mock as a mock, since the super class is different (even though with the same name "Mock"). It then throws "Bad state: when called on a real object.".

Is that expected behavior, or a bug?

Thanks!

==============================
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (30 hours ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

mockito: ^5.0.0-nullsafety.7
bloc_test: ^8.0.0-nullsafety.1

**Comment by felangel** [comment]
Hi @NikoBoerger 👋 
Thanks for opening an issue!

This is expected behavior because bloc_test is using mocktail for mocking the bloc due to limitations of mockito and codegen.

I’m working to try to reconcile the differences and even potentially merge mocktail into mockito but for now this is expected behavior.

Sorry for any inconvenience!

**Comment by NikoBoerger** [comment]
Hi @felangel,

Thanks for clarifying mate! It's fine, don't bother :) It was very convenient to use but then I know now that I have to migrate the code to the normal "when" there.

Cheers! ✌️

**Comment by kluverua** [comment]
Is there any option to test bloc method arguments?

Before null safety i use this code:
`mockito.verify(_bloc.add(argThat(isA<FetchApprovals>()))).called(1);`

Now it's does not work and I trying to rewrite it like this:

`mocktail.verify(() => _bloc.add(argThat(isA<FetchApprovals>()))).called(1);`

but got exception:

```
The following ArgumentError was thrown running a test:
Invalid argument(s): The "argThat" argument matcher is used outside of method stubbing (via `when`)
or verification (via `verify` or `untilCalled`). This is invalid, and results in bad behavior during
the next stubbing or verification.
```

Can anyone give me some advice?

**Comment by felangel** [comment]
@kluverua after null-safety `bloc_test` using `mocktail` instead of `mockito`. The following should work:

```dart
mocktail.verify(() => _bloc.add(any(that: isA<FetchApprovals>()))).called(1);
```

Hope that helps 👍

**Comment by kluverua** [comment]
here is answer:
```
final List<dynamic> captured = mocktail.verify(() => _bloc.add(mocktail.captureAny())).captured;
expect(captured.last is FetchApprovals, isTrue);

```
And DO NOT override method `add` in your bloc mock!
