### ISSUE TITLE
Question about passing models using PushReplacement

### ISSUE THREAD

**Issue by ebelevics** [felangel/bloc#2199]
Currently, I have 3 screens, which are ordered in a specific order:

> LoginScreen
>   -RegisterScreen
>     -RegisterCompleteScreen

The idea is from LoginScreen I can navigate to RegisterScreen. There I provide an email address and after verifying I go further to RegisterCompleteScreen. In RegisterCompleteScreen I fill the rest of the information to complete registration. **Important note: I navigate to RegisterCompleteScreen with PushReplacement method.**

What I want to achieve with Cubit is - I want to create a local cubit for registration use only (no global use). From RegisterScreen I pass created cubit to RegisterCompleteScreen to finish the registration process. After registration is done, I dispose an object.

This is how my routing looks so far in code:
```
static Route<dynamic> generateRoute(
      BuildContext context, RouteSettings settings) {
    // final args = settings.arguments;
    var page = () {
      switch (settings.name) {
        //AUTH ROUTES
        case LoginScreen.routeName:
          return LoginScreen();
        case RegisterScreen.routeName:
          return BlocProvider(
            create: (_) => RegisterCubit(),
            child: RegisterScreen(),
          );
        case RegisterCompleteScreen.routeName:
          return BlocProvider.value(
            value: settings.arguments as RegisterCubit,
            child: RegisterCompleteScreen(),
          );
        default:
          return ErrorScreen();
      }
    };
    FocusManager.instance.primaryFocus?.unfocus();
    return MaterialPageRoute(builder: (_) => page());`

```
On RegisterScreen everything works fine. But while in RegisterCompleteScreen I still can use cubit with `context.read<RegisterCubit>();` and access its methods, I can't anymore listen to events that are emitted from cubit by using `BlocListener<RegisterCubit, RegisterState>.`, BlocListener just doesn't react to them anymore.

When using in RegisterScreen to navigate .push method to RegisterCompleteScreen, it does do a trick, but it's not desired behavior. Also, it's kind of weird that I can still use the cubit instance in RegisterCompleteScreen despite BlocListener not responding to events. Why this is the case? Is it Cubit or it is Provider related? Or the only fix is to put all providers in MaterialApp level? What to do if I want to recreate and dispose specific cubit in a smaller scale (similar to RegisterCubit case)?

**Comment by Gene-Dana** [comment]
I think this may be a situation where the new page is losing the context where the RegisterCubit resides.

> - I want to create a local cubit for registration use only (no global use)

The instant I read this, I thought it may be a perfect candidate for Flow Builder https://pub.dev/packages/flow_builder

> Currently, I have 3 screens, which are ordered in a specific order:
> 
> LoginScreen
> -RegisterScreen
> -RegisterCompleteScreen
> 

FlowBuilder literally walks through flows exactly like this. And, in the authentication example, you will see, Felix creates a local cubit for this scenario.

Give this a look and let me know if it can help solve your issue. 

And, if you would like to ask on the Discord, there is a Flow Builder channel !
https://discord.com/invite/Hc5KD3g
