### ISSUE TITLE
Need Full control to developer on context.select() Simpler Build When Method

### ISSUE THREAD

**Issue by RR-Reddy** [felangel/bloc#2210]
This is a great library

I used it in one of my game and now i am trying to migrate to null safety version ( deprecated apis removed)

**Note :**  I have read   #1521 

I am having below scenario to use context.select() only when some game event updated

```dart
   class GameState {
      GameUpdateType gameUpdateType;    // enum  game events 
      String arg1,arg2,argN.            // some may variables
   }
  ```

```dart
   enum GameUpdateType {
      START,
      RUNNING,
      KILL_MOVE,
      NORMAL_MOVE,
      ANIM_START,
      ANIM_END,
      COMPLTED
   }
  ```

Use cases
1) When GameUpdateType is KILL_MOVE i have to do some re-render/ action in only one specific widget
2) There are so may use Use cases like first use case
3) We can only compare one variable at a time in existing context.select(). i want to compare on multiple 
     variables 

**My expecatation context.select() api is like below**

   ```dart
  Widget build(BuildContext context) {
     var blocOrCubic = context.select((blocOrCubic,previousState,currentState){

                                            // developer responsibility to return boolean  
                                           // here we have full controll on  blocOrCubic, previousState,currentState objects
                                           // boolean desides this widget to  re-render or not

                                           return true;

                                         }); // end of select method
  
   var data=  collected from blocOrCubic object ( it has current state )

     return someWidget(data);
   }
   ```
**Underlying Signature**

```dart
extension BlocSelectContext on BuildContext {
      R blocSelect<R, T>(bool selector(R,T,T)) {}
     
      // R Bloc or Cubic
      // T State 


}
```

**Intended Use case**
I am storing some of **game flow variables** in to cubic object and  game updates in state object 
so in widget tree what i need is cubic, previous state, current state objects

**NOTE :** 

**Previously i am using BlocBuilder with buildWhen**
Whenever game state updated i will check required condition in buildWhen and Next in builder i use context.bloc() to get  cubic object reference. so that i can get access to **game flow variables** inside cubic object 

Now context.bloc() is deprecated so i am unable to get access to cubic object inside build method

**Comment by felangel** [comment]
Hi @RR-Reddy 👋 
Thanks for opening an issue!

Just to clarify, are you asking for an update to `context.select` just out of convenience? There should be nothing preventing you from using `BlocBuilder` with `buildWhen` in the null-safety prereleases.

For some context, `context.select` is implemented in `package:provider` and `BlocProvider` uses `Provider` internally. As a result, if we want these changes to `context.select` they either need to be made in `package:provider` or `package:flutter_bloc` needs to implement this separately.

Thanks! 🙏

**Comment by RR-Reddy** [comment]
Thanks  @felangel for great documentation 

I have successfully migrated code to null safety,  after reading full migration documentation [https://bloclibrary.dev/#](https://bloclibrary.dev/#/migration)

I understood how bloc library respecting provider package features and API's, and no confusion to developers
