### ISSUE TITLE
Can't pub get examples.

### ISSUE THREAD

**Issue by Malyasse** [felangel/bloc#2216]
**Describe the bug**

when I 'pub get' on the project examples, I have the following error: 

_With flutter_complex_list :_ 

Because equatable >=2.0.0-nullsafety.3 depends on meta ^1.3.0 and every version of flutter from sdk depends on meta 1.3.0-nullsafety.6, equatable >=2.0.0-nullsafety.3 is incompatible with flutter from sdk.
So, because flutter_complex_list depends on both flutter any from sdk and equatable ^2.0.0, version solving failed.
Running "flutter pub get" in flutter_complex_list...
pub get failed (1; So, because flutter_complex_list depends on both flutter any from sdk and equatable ^2.0.0, version solving failed.)

_With flutter_counter :_ 
Because mocktail >=0.0.2-dev.0 depends on test_api ^0.2.19 and every version of flutter_test from sdk depends on test_api 0.2.19-nullsafety.6, mocktail >=0.0.2-dev.0 is incompatible with flutter_test from sdk.
So, because flutter_counter depends on both flutter_test any from sdk and mocktail ^0.0.2-dev.5, version solving failed.
Running "flutter pub get" in flutter_counter...
pub get failed (1; So, because flutter_counter depends on both flutter_test any from sdk and mocktail ^0.0.2-dev.5, version solving failed.)
**To Reproduce**

1. Dowload the git
2. Open an example
3. flutter pub get

**Comment by felangel** [comment]
Hi @Malyasse 👋 
Thanks for opening an issue!

The examples have been upgraded to flutter 2.0 and it looks like you’re using an older version. Can you try upgrading and let me know if you’re still running into the same issue?

```sh
flutter channel stable
flutter upgrade
```

Thanks!

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions/comments and I'm happy to continue the conversation 👍
