### ISSUE TITLE
StorageNotFound (Storage was accessed before it was initialized...

### ISSUE THREAD

**Issue by graphicbeacon** [felangel/bloc#2217]
**Description**
Hello, I'm getting the below error when starting the app:

```
StorageNotFound (Storage was accessed before it was initialized.
Please ensure that storage has been initialized.

For example:

HydratedBloc.storage = await HydratedStorage.build();)
```

**To reproduce**
In my main.dart file I am initialising HydratedBloc.storage:

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Bloc.observer = AppBlocObserver();
  FlutterError.onError = (details) {
    log(details.exceptionAsString(), stackTrace: details.stack);
  };

  HydratedBloc.storage = await HydratedStorage.build(
    storageDirectory: await getApplicationDocumentsDirectory(),
  );

  runZonedGuarded(
    () => runApp(const App()),
    (error, stackTrace) => log(error.toString(), stackTrace: stackTrace),
  );
}
```
and my initialised App:
```dart
class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
        create: (_) => AuthenticationBloc(),
        child: AppRouter(),
      );
  }
}
```

and I have my hydrated bloc instance:

```dart
class AuthenticationBloc
    extends HydratedBloc<AuthenticationEvent, AuthenticationState> {
..
}
```
**Additional context**
It seems that whenever I start the app, an attempt is made to retrieve the value of `storage` in `HydratedBloc` which fails. Although we define the storage field before `runApp()` it's not getting picked up. Am I doing something wrong? Your help would be much appreciated.

**Comment by graphicbeacon** [comment]
@felangel This is happening with version **^7.0.0-nullsafety.3**. Can't share the codebase since it's private. I can share the below observations to hopefully help. If you still want a reproducible example then I'll put one together.

So far I'm seeing that HydratedBloc invokes `hydrate()` in its constructor which has this line:

```dart
void hydrate() {
    final storage = HydratedBloc.storage;
    //...
  }
```
That line is invoking the storage getter here:

```dart
abstract class HydratedBloc<Event, State> extends Bloc<Event, State>
    with HydratedMixin {
  /// {@macro hydrated_bloc}
  HydratedBloc(State state) : super(state) {
    hydrate();
  }

  /// Setter for instance of [Storage] which will be used to
  /// manage persisting/restoring the [Bloc] state.
  static Storage? _storage;

  static set storage(Storage? storage) => _storage = storage;

  /// Instance of [Storage] which will be used to
  /// manage persisting/restoring the [Bloc] state.
  static Storage get storage {
    if (_storage == null) throw const StorageNotFound();
    return _storage!;
  }
}
```
which is throwing that StorageNotFound exception. It seems that doing the bit below in main.dart isn't recognised:

```dart
HydratedBloc.storage = await HydratedStorage.build(
    storageDirectory: await getApplicationDocumentsDirectory(),
  );
```

**Comment by felangel** [comment]
Yeah it would be great if you could provide a reproduction sample because this error means there's either an issue with the initialization or the storage is being used before it's initialized as you pointed out. Thanks! 🙏

**Comment by graphicbeacon** [comment]
@felangel Apologies, I figured it out. I have a project generated with very_good_cli and didn't realise I was running main_production.dart rather than main_development.dart. _Silly me, I need rest!_
