### ISSUE TITLE
Will bloc use Riverpod instead of Provider?

### ISSUE THREAD

**Issue by DDDrop** [felangel/bloc#2218]
**Is your feature request related to a problem? Please describe.**
For example Riverpod put provider globally, so MultiBlocProvider is not more needed.
Will bloc use Riverpod in next big update?

**Comment by furkanvatandas** [comment]
There is an open issue here https://github.com/felangel/bloc/issues/2100

**Comment by felangel** [comment]
Hi @DDDrop 👋
Thanks for opening an issue!

As @furkanvatandas mentioned there is already an issue open to discuss this 👍
