### ISSUE TITLE
fromJson and toJson in state [Hydrated bloc]

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2224]
I have auth hydrated bloc and there are 3 states.
```
part of 'auth_bloc.dart';

// @freezed
// class AuthState with _$AuthState {
//   const factory AuthState.initial() = _Initial;
//   const factory AuthState.authenticated(
//       {required String path, required String token}) = _Authenticated;
//   const factory AuthState.unauthenticated() = _UnAuthenticated;
// }

abstract class AuthState extends Equatable {}

class Authenticated extends AuthState {
  final String token;
  final String path;

  Authenticated({required this.token, required this.path});

  @override
  List<Object?> get props => [token, path];

 
}

class Initial extends AuthState {
  @override
  List<Object?> get props => [];
}

class UnAuthenticated extends AuthState {
  final String path;

  UnAuthenticated(this.path);
  @override
  List<Object?> get props => [path];

 
}
```
I want to implement fromJson and toJson Methods in order to save state in the hydrated bloc.
Could you show please the best way  to implement fromJson and toJson in hydrated bloc ?

**Comment by samulefevre** [comment]
Hello, this video should help you :
https://www.youtube.com/watch?v=L5QinDY7nKE (Maintaining Flutter Application State with Hydrated Bloc)

**Comment by II11II** [comment]
> Hello, this video should help you :
> https://www.youtube.com/watch?v=L5QinDY7nKE (Maintaining Flutter Application State with Hydrated Bloc)

Hi @samulefevre, I ve watched this video and it is informative and awesome ))
But this kind of example is not shown when the state of the bloc consists of two or more classes and linked with inheritance

**Comment by wujek-srujek** [comment]
How about this: each state has its own `fromJson` and `toJson` methods and apart from the data, they additionally save a field called e.g. `_subtype`; then the bloc, when it gets the JSON, gets the field and depending on its value it call `fromJson` on the correct subclass. There are many variations of this solution, e.g. you can create a factory in `AuthState` etc. Hope this helps.

**Comment by II11II** [comment]
Yeap, I am doing as you said. I would like to know are there better solutions.
If yes, I will be here.
For now, I close the issue.
