### ISSUE TITLE
HydratedBloc test - MissingPluginException

### ISSUE THREAD

**Issue by jamesnicholls04** [felangel/bloc#2227]
Hi!

I have been unable to write a blocTest for a HydratedCubit, though I have been able to test other cubits.

<img width="431" alt="Screenshot 2021-03-12 at 12 27 46" src="https://user-images.githubusercontent.com/68249898/110940235-78999f00-832e-11eb-99b7-90ae2d3c8a32.png">

<img width="862" alt="Screenshot 2021-03-12 at 12 28 07" src="https://user-images.githubusercontent.com/68249898/110940249-7f281680-832e-11eb-8104-a6857724f49b.png">

I would expect that the test run successfully! (I hope - I'm new to making tests)

<img width="844" alt="Screenshot 2021-03-12 at 12 31 00" src="https://user-images.githubusercontent.com/68249898/110940460-d8904580-832e-11eb-9e96-e0e3c51ea956.png">

Thank you for your time, I'd very much appreciate any ideas! 😊

**Comment by samulefevre** [comment]
Hello got same kind of problem :

`HydratedBloc.storage = await HydratedStorage.build(
    storageDirectory: await getApplicationDocumentsDirectory(),
  );`

[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)

Happens for me when i use flutter run --release

I tried flutter clean or change minSdkVersion 20 to 23 but don't work.

**Comment by felangel** [comment]
Hi @jamesnicholls04 @samulefevre 👋 
Thanks for opening an issue!

In previous versions, HydratedStorage would rely on `path_provider` internally to determine the default storage directory so you'll need to mock the storage instead of using the real storage. You can take a look at the [weather example tests](https://github.com/felangel/bloc/blob/6c2aadddf60f3656292c4a1039bc5cdbd95828c7/examples/flutter_weather/test/weather/view/weather_page_test.dart#L23) to get started.

Hope that helps! 👍

**Comment by samulefevre** [comment]
Hi, i have tried with only Directory directory = await getApplicationDocumentsDirectory(); (in main.dart) It works in debug mode but when i want to build for release it shows error. So it is a problem with package path_provider. But if you have any ideas how to solve it ? If not, i should open an issue on path_provider github.

**Comment by felangel** [comment]
> Hi, i have tried with only Directory directory = await getApplicationDocumentsDirectory(); (in main.dart) It works in debug mode but when i want to build for release it shows error. So it is a problem with package path_provider. But if you have any ideas how to solve it ? If not, i should open an issue on path_provider github.

Are you referring to tests or regular code?

**Comment by samulefevre** [comment]
regular code

**Comment by felangel** [comment]
> regular code

Are you running on mobile (iOS/Android), web, or desktop?

**Comment by samulefevre** [comment]
on mobile android, flutter 2.0.2(stable)

**Comment by felangel** [comment]
Can you share the complete error and stacktrace?

**Comment by samulefevre** [comment]
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (10623): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter (10623): <asynchronous suspension>
E/flutter (10623): #1      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:139)

**Comment by felangel** [comment]
@samulefevre I would recommend opening an issue on `path_provider` with a reproduction sample and clear reproduction steps. If you haven't already, I would recommend cleaning and re-running:

```sh
flutter clean
flutter packages get
flutter run --release
```

Hope that helps 👍

**Comment by samulefevre** [comment]
Thank you for your help and time. I already done this, so i will open an issue.

**Comment by samulefevre** [comment]
found my problem, it is package image_picker 0.7.2+1 who cause the error.
