### ISSUE TITLE
Using cubit class from another widget not working

### ISSUE THREAD

**Issue by edu81** [felangel/bloc#2229]
In my main.dart I am calling my HomeRoute providing my cubit like this:

**main.dart**

```
@override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: BlocProvider<GenericCubit>(
        create: (context) => GenericCubit(),
        child: HomeRoute(),
      ),
    );
  }
```

in **home_route.dart** I have, inside the BlocConsumer:

```
if (state is UnknownErrorState){
      return BlocProvider.value(
              value: BlocProvider.of<GenericCubit>(context),
              child: DefaultErrorWidget(state.errorMessage),
       );
}
```

in **default_error_widget.dart**, the cubit is not working in this button pressed:

```
ElevatedButton(
         child: Text("Reload"),
         style: ElevatedButton.styleFrom(
                      primary: Colors.red,
                      onPrimary: Colors.black
           ),
           onPressed: () {
                    print("OnReload");
                    context.read<GenericCubit>().tryReload();
                  },
                ),

```
Error tells: 

`Error: The method 'read' isn't defined for the class 'BuildContext'.`

How to make this work properly? or how to pass the Cubit class between widgets?

**Comment by felangel** [comment]
Hi @edu81 👋
Thanks for opening an issue!

I believe you just forgot to import flutter_bloc.

`import ‘package:flutter_bloc/flutter_bloc.dart’;`

hope that helps 👍

**Comment by edu81** [comment]
Hi @felangel 

You were totally right...so stupid mistake, sorry for the disturbance.

Would it be a good feedback to add this suggestion to the error message? something like:

```
Error: The method 'read' isn't defined for the class 'BuildContext'.
Maybe you forgot to import ‘package:flutter_bloc/flutter_bloc.dart’; 
```

Anyway, thanks for the good and fast help!

**Comment by felangel** [comment]
No worries! Unfortunately, the error message is part of the flutter/dart vscode extension and isn’t specific to bloc.
