### ISSUE TITLE
Listen to only part of state

### ISSUE THREAD

**Issue by najibghadri** [felangel/bloc#2230]
Dear maintainers, question: am I right that if I want to listen (in flutter e.g.) to only changes of part of the state I need to define `listenWhen` with a partial state check?

And is this an antipattern?

**Comment by felangel** [comment]
Hi @najibghadri 👋 
Thanks for opening an issue!

Yes, you can use `listenWhen` if you only want your `BlocListener` to be notified whenever some part of the state changes 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation! Alternatively, if you haven't already, I highly recommend joining the [bloc discord](https://discord.gg/bloc) to chat with the community and get these types of questions answered more promptly 😄
