### ISSUE TITLE
MockBloc testing Error since moving to Null Safety

### ISSUE THREAD

**Issue by shaun-pendrigh** [felangel/bloc#2233]
Since moving my project to Null Safety I am getting the following error:

Bad state: A test tried to use `any` or `captureAny` on a parameter of type `XXXXXEvent`, but
registerFallbackValue was not previously called to register a fallback value for `XXXXXEvent`

As these packages are still pre-release I wanted to confirm if it was a known issue. Using flutter_bloc: ^7.0.0-nullsafety.5 and bloc_test: ^8.0.0-nullsafety.5. I tried https://github.com/felangel/bloc/tree/master/packages/bloc_test/example and received the same error.

**Comment by felangel** [comment]
Hi @shaun-pendrigh 👋 
Thanks for opening an issue!

The problem is the prerelease of `bloc_test` is using `package:mocktail` instead of mockito so you'll need to use `any()` or `captureAny()` from [mocktail](https://pub.dev/packages/mocktail).

Let me know if that helps and sorry for the inconvenience! 👍

**Comment by felangel** [comment]
@shaun-pendrigh were you able to resolve the issue or are you still having trouble? Thanks!

**Comment by shaun-pendrigh** [comment]
@felangel, thanks you can close the issue, or should I?

**Comment by Justice4Joffrey** [comment]
Hi @felangel, I'm having this same issue here. I'm not quite sure what your solution is suggesting I should do (the bloc_test library is the only caller of those functions in my code, and it's imported from mocktail).

Could you kindly explain in a bit more detail?

**Comment by felangel** [comment]
Hi @Justice4Joffrey can you please describe exactly what issue you’re facing with some sample code? Thanks!

**Comment by Valentin-Seehausen** [comment]
I get these error, too:

```
    Bad state: A test tried to use `any` or `captureAny` on a parameter of type `TransactionState`, but
    registerFallbackValue was not previously called to register a fallback value for `TransactionState`
    
    To fix, do:
    
    ```
    void main() {
      setUpAll(() {
        registerFallbackValue<TransactionState>(TransactionState());
      });
    }
    ```
    
    If you cannot easily create an instance of TransactionState, consider defining a `Fake`:
    
    ```
    class TransactionStateFake extends Fake implements TransactionState {}
    
    void main() {
      setUpAll(() {
        registerFallbackValue<TransactionState>(TransactionStateFake());
      });
    }
    ```
```

With this code:

    testWidgets(
        'Call ReceiverBloc with term when term entered and waited for 500 ms',
        (WidgetTester tester) async {
      when(() => receiverBloc.state).thenAnswer((_) => ReceiverState());
      await tester.pumpWidget(
        MultiBlocProvider(
          providers: [
            BlocProvider<TransactionBloc>.value(
              value: transactionBloc,
            ),
            BlocProvider<ReceiverBloc>.value(value: receiverBloc)
          ],
          child: PlatformApp(
            home: PlatformScaffold(
              body: TransactionReceiver(),
            ),
          ),
        ),
      );
      await tester.enterText(
          find.byKey(Key('TransactionReceiver_searchField')), 'accountAddress');
      await tester.pumpAndSettle();
      await tester.pump(new Duration(milliseconds: 600));
      await tester.pumpAndSettle();
      return verify(() =>
              receiverBloc.add(ReceiverTermEntered(term: 'accountAddress')))
          .called(1);
    });
Blocks are usual Mocks with mocktail.

**Comment by nicol-ograve** [comment]
@Valentin-Seehausen I just had the same problem, which I solved by applying the proposed solution:

`
    void main() {
      setUpAll(() {
        registerFallbackValue<TransactionState>(TransactionState());
      });
    }
`
