### ISSUE TITLE
how to use MultiRepositoryProvider

### ISSUE THREAD

**Issue by brianmori** [felangel/bloc#2238]
Salut, hello,

I have a question concerning the MultiRepositoryProvider.

I followed the tutorials:

- https://bloclibrary.dev/#/flutterfirebaselogintutorial
- https://bloclibrary.dev/#/flutterfirestoretodostutorial

and I wish to change to MultiRepositoryProvider to have Firebase Auth and Firestore available everywhere

I changed the 

```

class App extends StatelessWidget {
  final AuthenticationRepository authenticationRepository;

  const App({
    Key? key,
    required this.authenticationRepository,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {

@override
  Widget build(BuildContext context) {
    return RepositoryProvider.value(
      value: authenticationRepository,
      child: BlocProvider(
        create: (_) => AuthenticationBloc(
          authenticationRepository: authenticationRepository,
        ),
        child: AppView(),
      ),
    );
  }
```

into

```
    return MultiRepositoryProvider(
      providers: [
        RepositoryProvider.value(
            value: authenticationRepository,
            child: BlocProvider(
              create: (_) => AuthenticationBloc(
                authenticationRepository: authenticationRepository,
              ),
            ))
      ],
      child: AppView(),
    );
```

and it says it could not find the correct provider for <AuthenticationBloc> above this BlocListener<AuthenticationBlock,AuthenticationState> widget, would you have any suggestions how the MultiRepositoryProvider should be used?

**Comment by dawidd6** [comment]
Use the `child` property of `MultiRepositoryProvider`.

**Comment by brianmori** [comment]
> Use the `child` property of `MultiRepositoryProvider`.

Hi @dawidd6,

the `child` is the one of the `MultiRepositoryProvider` or I have not understood 

Here is the full snippet in case

```
  @override
  Widget build(BuildContext context) {
    return MultiRepositoryProvider(
      providers: [
        RepositoryProvider.value(
          value: authenticationRepository,
          child: BlocProvider(
              create: (_) => AuthenticationBloc(
                    authenticationRepository: authenticationRepository,
                  )),
        )
      ],
      child: AppView(),
    );
  }
}
```

**Comment by dawidd6** [comment]
Right. I misread the code.

**Comment by felangel** [comment]
Hi @brianmori 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which reproduces the issue? I think we need to see more code in order to identify the problem. Thanks! 🙏

**Comment by brianmori** [comment]
> Hi @brianmori 👋
> Thanks for opening an issue!
> 
> Can you please provide a link to a sample app which reproduces the issue? I think we need to see more code in order to identify the problem. Thanks! 🙏

Merci beaucoup 

I uploaded the project in this repo https://github.com/brianmori/flutterfirebase

It is the code of https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login which I am using to experiment with Flutter Bloc :)

I am trying to figure out the reason behind to not return only the AuthenticationProvider, but also the BlocProvider -> AuthenticationBloc

Was it for the `AppView` to have everything ready to dispatch the user to the correct page ?

**Comment by felangel** [comment]
> Was it for the AppView to have everything ready to dispatch the user to the correct page ?

Yes, that's correct and it's also good practice to decouple the widget that is providing the bloc from the widget that is consuming the bloc for increased testability 👍 

Closing for now but feel free to comment with any additional questions or if you haven't already join us on [discord](https://discord.gg/bloc) 👍

**Comment by parsa10** [comment]
hello , i have @brianmori problem , when i use `MultiRepositoryProvider` i get this error : 
**it could not find the correct provider for above this BlocListener<AuthenticationBlock,AuthenticationState> widget**
this is the code snippet : 
```
return MultiRepositoryProvider(
      providers: [
        RepositoryProvider.value(
          value: authenticationRepository,
          child: BlocProvider(
            create: (context) => AuthenticationBloc(
                authenticationRepository: authenticationRepository,
                storageRepository: storageRepository),
          ),
        ),
        RepositoryProvider.value(
          value: storageRepository,
          child: BlocProvider(
            create: (context) => LoginBloc(
                authenticationRepository: authenticationRepository,
                storageRepository: storageRepository),
          ),
        )
      ],
      child: const AppView(),
    );
```
but when i changed it to : 
`return MultiRepositoryProvider(
      providers: [
        RepositoryProvider.value(
          value: authenticationRepository,
        ),
        RepositoryProvider.value(
          value: storageRepository,
        ),
      ],
      child: BlocProvider(
        create: (context) => AuthenticationBloc(
            authenticationRepository: authenticationRepository,
            storageRepository: storageRepository),
        child: const AppView(),
      ),
    );`
it worked with no error. 
I cant understand whats going on here ? why the second snippet is working ? can someone help me ? 
here is the link to my code:
https://github.com/parsa10/isp_support
