### ISSUE TITLE
Listener using previous widget's attribute.

### ISSUE THREAD

**Issue by ChristianConstantNel** [felangel/bloc#2239]
Hi!

Firstly I want to thank everyone involved with this package. I've been using it for our production app and it's absolutely fantastic! I cannot express enough gratitude for the extensive documentation and tutorials. Hands down one of the best packages I've used.

I'm struggling with a bug regarding the listener of BlocConsumer. When the listener is called, I check an attribute of the widget before going forward. The problem is that the listener uses a previous widget's attribute and the current one. Resulting in strange behaviour. 

Below is the build function with the BlocConsumer. 

```

  @override
  Widget build(BuildContext context) {
    return BlocConsumer(
      listener: (context, FavouritesState state) {
        successFailureSnack(context, state.blocStatus);
        print(widget.type); //! Called twice for school and team
        if (state.showPopUp && widget.type == 'School') {
          //! Called even when widget.type is team
          //! Seems to be using old widget for school.
          print('Widget.type: ${widget.type}');
        }
        if (state.showPopUp && widget.type == 'Team') {
          print('Widget.type: ${widget.type}');
        }

        if (state.noUser) _showSignInFlush(context);
      },
      cubit: _favouritesCubit,
      builder: (BuildContext context, FavouritesState state) {
        return _getCorrectWidget(state);
      },
    );
  }
```
**Expected behavior**
The current widget's attribute being used not the previous one.

[✓] Flutter (Channel stable, 2.0.0, on macOS 11.1 20C69 darwin-arm, locale
    en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (3 available)

• No issues found!

Any advice would be much appreciated.

**Comment by felangel** [comment]
Hi @ChristianConstantNel 👋
Thanks for opening an issue and for the positive feedback! I really appreciate it 🙏

Regarding the issue, are you able to create a small sample app which illustrates the issue? Also, which version of bloc are you currently using? Thanks!

**Comment by ChristianConstantNel** [comment]
Hi @felangel,

Thank you for the quick response!
I'm on flutter_bloc 6.1.0.

I'll jump on that small sample app right now and sent it as soon as it's done.

**Comment by ChristianConstantNel** [comment]
Hi @felangel,

Here is a sample app that reproduces the bug. 
I've added the steps in the Read Me.

https://github.com/ChristianConstantNel/BlocConsumer-Bug.git

Please let me know if you need anything else.
Thank you for taking a look at this!

**Comment by felangel** [comment]
Hi @ChristianConstantNel 👋 
I took a closer look and this seems to be working as expected. The reason you see two logs is because you have two BlocListeners. There is one on the first screen and a second one is added when you push the `TeamPage`. When you push a route to the navigation stack the previous route is still mounted so the `BlocListener` from the first page is still listening.

Hope that helps! 👍

**Comment by ChristianConstantNel** [comment]
Hi @felangel,

Ahh okay that makes a lot of sense! Is there anyway of removing the first listener when pushing a new route?

Thanks for the clarification!

**Comment by felangel** [comment]
@ChristianConstantNel no problem! You can use `pushReplacement` to unmount the previous widgets when you push the new route 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄

**Comment by ChristianConstantNel** [comment]
@felangel Thank you so much! 

It really means a lot that you take time to reply to even the most basic of questions.

You're a rockstar! 
Have a good day/night!
