### ISSUE TITLE
Performance on listView

### ISSUE THREAD

**Issue by locpt** [felangel/bloc#224]
Hi @felangel,

You just contributed a great project to our flutter community. I really loved it.
In your flutter_inifite_list, I saw that:
 - Each time we get the new data and addAll to the list, the flutter ListView try to rebuild the entire list (from the beginning item). 

So I wonder:
1/ Does it affect the performance of the list view if our PostWidget had much more complicated UI(maybe, it included the pictures or video)?
2/ So if I wanted to update an item in the list, ListView was also rebuilt entire list?
3/ Do we have a solution for that in flutter(in android native we got method notifyItemRangeInserted to solved that)?

**Comment by felangel** [comment]
Hi @locpt 👋 
Thanks for opening an issue and great question!

The `ListView.builder` constructor will only create items as they are scrolled onto the screen ([source](https://flutter.dev/docs/cookbook/lists/long-lists)).

As a result, as long as our build is a pure function (meaning we don't have any side effects like making network requests or reading from a DB) it should be totally fine. I haven't seen any performance issues personally but if you are then let me know and I'm more than happy to help. 👍

**Comment by locpt** [comment]
Thank you so much @felangel
