### ISSUE TITLE
How to close bloc instance

### ISSUE THREAD

**Issue by LabN36** [felangel/bloc#2240]
Hi everyone,

I've created a bloc instance(`connectionBloc`) in the main method.
now I'm getting warning(`Close instances of dart.core.Sink.`) to close this bloc instance which is obvious.

here is my code

```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  final connectionBloc = ConnectionBloc(ConnectionState('none'));

  Connectivity().onConnectivityChanged.listen((event) {
    print('[Connectivity Listen] $event');
    connectionBloc.add(ConnectionEvent(event));
  });

  runApp(InternetWidget(connectionBloc));

}
```

```
class InternetWidget extends StatelessWidget {
  final ConnectionBloc connectionBloc;
  InternetWidget(this.connectionBloc);
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => connectionBloc,
      child: MaterialApp(
     ....//other code

```

now my question is 
1. where should i close this bloc ? if i define a method in main method then when and how should i call it.
2. is there any better way i can do the same thing.

I'm beginner in the bloc so please help me.

Thanks for the great package.

**Comment by felangel** [comment]
Hi @LabN36 👋 
Thanks for opening an issue!

Generally it is the responsibility of the object that created the bloc to also close the bloc. I don't recommend creating a bloc globally like that and instead it would be better to create the bloc within the `InternetWidget` and instead inject the Connectivity instance:

```dart
void main() => runApp(InternetWidget(Connectivity());
``` 

```dart
class InternetWidget extends StatelessWidget {
  const InternetWidget({Key key, this.connectivity}) : super(key: key);
  final Connectivity connectivity;

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (_) => ConnectionBloc(connectivity),
      child: ...
    );
  }
}
```

Then you can subscribe to the `onConnectivityChanged` stream within the `ConnectionBloc` and add the `ConnectionEvent` internally.

```dart
class ConnectionBloc extends Bloc<ConnectionEvent, ConnectionState> {
  ConnectionBloc(Connectivity connectivity) : super(ConnectionState(...)) {
    _subscription = connectivity.onConnectivityChanged.listen((event) => add(ConnectionEvent(event));
  }

  StreamSubscription _subscription;

  @override
  Future<void> close() {
    _subscription.cancel();
    return super.close();
  }
}
```

Hope that helps 👍

**Comment by LabN36** [comment]
Thanku so much for the great answer. your approach is brilliant. Really appreciate your quick response and your valuable time.
