### ISSUE TITLE
Tried to call Provider.of<dynamic>

### ISSUE THREAD

**Issue by edu81** [felangel/bloc#2254]
This is more a question than a bug.

In one of my Stateful widgets, on the initState function I am trying to call a function from the cubit:

```
@override
  void initState() {
    context.read<SalesCubit>().getAllCurrentSales();
    super.initState();
  }
```

which works fine.

However, further down in the same class, inside other function i am doing:

```
sendData() {
    context.read()<SalesCubit>().addNewSale(
      saleDate,
      price,
      description ?? "---");
  }
```

And this is not working with the following output:

```
The following assertion was thrown while handling a gesture:
Tried to call Provider.of<dynamic>. This is likely a mistake and is therefore
unsupported.

If you want to expose a variable that can be anything, consider changing
`dynamic` to `Object` instead.
'package:provider/src/provider.dart':
Failed assertion: line 304 pos 7: 'T != dynamic'
```

Could anyone help?

**Comment by dawidd6** [comment]
Check your syntax. The second line is wrong.

**Comment by felangel** [comment]
Hi @edu81 👋 
Thanks for opening an issue!

As @dawidd6 mentioned, you just need to update the syntax:

```dart
context.read<SalesCubit>().addNewSale(
```

Also, make sure to call `super.initState` first when overriding `initState`.

Hope that helps 👍

**Comment by edu81** [comment]
omg.....ok this is the clear indication that it has been too much coding time for today....thanks to both of you. Please feel free to close/delete this question/issue.

Thanks!
