### ISSUE TITLE
Navigation with BloC = BlocListener fired multiple-times, and more issues

### ISSUE THREAD

**Issue by Lix-ai** [felangel/bloc#2255]
Hi :),
I'm trying to use navigation with in order to avoid memory leakage, etc.
Learning a lot, and still not find a correct solution:

I'm facing 2 issues:
 1. BlocListener is fired/executed/called x2 multiple times after every navigation (fired 2 and then 4 and than 8, and so on...).
 2. Not sure how I can use 'Navigator.pop(context)'.

And I still:

-  Not sure how to use navigation with 'pushNamed' (I'm using 'Route onGenerateRoute'):
   * "Navigator.of(context).pushNamed(/AnyPage)"
   OR
   * Navigator.pushNamed(context, '/AnyPage');
==> I use below with 'Route onGenerateRoute':
      case '/AnyPage':
        return MaterialPageRoute(
          builder: (_) => AnyPage(),
        );

- Not sure how to use the navigation, with 'BlocListener' and the 'child' of the will be 'BlocBuilder'?
- (regarding last step, if yes) Not sure If to set the BlocBuilder at a new class or?
- Not If to set cubit at 'BlocListener' and/or 'BlocBuilder' ==> and if yes, what to set exactly?
- Not at the 'BlocListener' and/or 'BlocBuilder' set the: "listener/builder: (BuildContext context, AnyPageState state)" Or like this "listener/builder: (context, state)" respectively.
- Not sure what is going after a navigation, because I saw that after each navigation I see that the last page is not dispose/disappeared from the tree (I used 'Flutter Inspector' at AndroidStudio).

**_### AND in general not sure how to use navigation correctly with Bloc._**

Thanks in advance =]!!!

**Comment by Lix-ai** [comment]
And also,
Where the BlocListener for navigation shall be located? if for example i have BlocListener for checking internet connection, it shall be above this or not?

**Comment by Gene-Dana** [comment]
Hi there ! Anytime anyone talks Bloc and Navigation, I become a shill for FlowBuilder.

https://github.com/felangel/flow_builder

Basically, you can implement flows in all types of ways to navigate as needed.

> * BlocListener is fired/executed/called x2 multiple times after every navigation (fired 2 and then 4 and than 8, and so on...).

So instead of BlocListener, you can make a switch on a piece of state managed by a cubit

```dart
return FlowBuilder<NavigationState>(
          state: context.select((NavigationCubit cubit) => cubit.state),
          onGeneratePages: (NavigationState state, List<Page> pages) {
            switch (state) {
              case NavigationState.home:
                return [Home.page()];
              case NavigationState.learn:
                return [Learn.page()];
              case NavigationState.page2:
                return [Page2.page()];
              default:
                return [Home.page()];
            }
          },
        );
```


> 2\. Not sure how I can use 'Navigator.pop(context)'.

In FlowBuilder, you can 'complete' the flow to basically pop out

```dart
appBar: AppBar(
        title: const Text('Login'),
        leading: BackButton(
          onPressed: () {
            context.flow<AuthenticationState>().complete();
          },
        ),
      ),

```

And, it uses the Pages API too

```dart
class LoginPage extends StatelessWidget {
  static Page page() => MaterialPage<void>(child: LoginPage());

```


Check it out. I think it's what you are looking for. Feel free to ask more questions here or on the Discord !

https://discord.com/invite/Hc5KD3g

**Comment by Lix-ai** [comment]
Thanks for the details and information =]!!!
Regarding the "multiple-fired" issue, I just change it to "pushReplacementNamed".
