### ISSUE TITLE
Should emit throw an Exception if BlocBase is closed?

### ISSUE THREAD

**Issue by nmfisher** [felangel/bloc#2261]
**Is your feature request related to a problem? Please describe.**
I've just been trying to figure out why `emit` wasn't actually updating the state of my (singleton) BlocBase. I only just realized that close was being inadvertently called during debug, and emit() returns silently without updating the Bloc state if the BlocBase has been closed.

**Describe the solution you'd like**
Throw an Exception if emit() is called after close() is called on a BlocBase.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by felangel** [comment]
Hi @nmfisher 👋 
Thanks for opening an issue!

This is intentional because there may be cases where this is unavoidable. See https://github.com/felangel/bloc/issues/1236 and https://github.com/felangel/bloc/issues/120 for more information.

Hope that helps! 👍

**Comment by nmfisher** [comment]
Obviously you're BDFL for this project but I can't say I agree with that design decision :)

This is all IMO of course, but I believe a function should do exactly what it says it will do, and if it can't, an exception should be raised (or at least, that failure should somehow be communicated to the consumer). In this case, emit() should emit a new state. If it can't do that, it should throw an exception or return an error code. Silently failing doesn't seem like a good option.

I understand that you want to avoid "false flag" exceptions when a Future completes after the Cubit is closed, but this itself would contravene the rule above. If emit() does not actually emit a state because it was invoked by a Future that completed after the Cubit was closed, it should be the Future/consumer side's job to deal with that. 

Can I suggest one of two compromises:
- emit() should return a bool, rather than void, to indicate whether a state was actually emitted
- emit() should accept an optional bool argument to specify whether an exception should be thrown if nothing was emitted (or perhaps a constructor argument)
- BlocBase should expose the isClosed property of the StreamController so we can at least check whether (my least preferred option, because I don't want to wrap every emit call inside if(!bloc.isClosed) { .. }

Thanks again for your library and look forward to hearing your thoughts.

**Comment by felangel** [comment]
@nmfisher thanks for your feedback, I really appreciate it! Can you please provide a concrete use case so that I can have more context regarding your particular usage? Thanks!

**Comment by nmfisher** [comment]
Originally it was because I was doing:

BlocProvider<SomeBloc>(builder:(ctx, state) => doStuff()))

where SomeBloc was a singleton. During hot reload, close() was being called on SomeBloc, hence the emit never worked. 

I can avoid the issue now that I know how it all works, but it would have been easier to track down the weird behaviour if emit wasn't silently failing.

**Comment by felangel** [comment]
This is addressed by #2913 and will be included in bloc v8.0.0-dev.5
