### ISSUE TITLE
Please suggest a best practice for state update with copyWith() function for nullable values

### ISSUE THREAD

**Issue by jezsung** [felangel/bloc#2266]
It's very common to have `copyWith()` for bloc state to easily update the certain value without loosing the other pervious values. But it's impossible to use it when you want to update the value to `null` because the `copyWith()` will ignore it and return the state with previous values. What's the suggested solutions in this case?

**Comment by omidraha** [comment]
Here is the [answer](https://github.com/felangel/bloc/issues/1770#issuecomment-716223037).

**Comment by underfilho** [comment]
Is this really the best practice? I didn't like so much the idea to need to use functions. An approach that I like is for this specific variable that can be nullable, set one specific method for that.
One ```copyWith()``` for generics and one ```withName(String name)``` for non-nullable variables.
