### ISSUE TITLE
[Question] Why is it always downloading tons of update each time flutter channel change?

### ISSUE THREAD

**Issue by scheung38** [felangel/bloc#2267]
thanks you

**Comment by felangel** [comment]
Hi @scheung38 👋 
Thanks for opening an issue!

When you switch channels flutter has to checkout the new branch and pull/apply all changes. It is not cached so it executes/downloads the changes each time. There are tools like [fvm](https://github.com/leoafarias/fvm) that aim to simplify switching between flutter versions.

Hope that helps 👍
