### ISSUE TITLE
Bloc Plugin wont install in Intellij Ultimate 2019.1

### ISSUE THREAD

**Issue by cyrsis** [felangel/bloc#227]
**Describe the bug**
Can not find plugin from the official Market

![image](https://user-images.githubusercontent.com/731087/56253703-1a3af600-60f0-11e9-80a1-3047d91e8e01.png)

Try manual install from Disk

![image](https://user-images.githubusercontent.com/731087/56253794-80277d80-60f0-11e9-901d-e0437839a86e.png)

Wish I can fix it and PR, but end up doesn't work too well

**Comment by felangel** [comment]
@cyrsis thanks for reporting this! We’ll investigate and hopefully have a fix for this soon 👍

**Comment by felangel** [comment]
@jorgecoca according to IntelliJ, the plugin should be compatible with IntelliJ Ultimate 2019.1. Any ideas what might be causing this?

**Comment by cyrsis** [comment]
@felangel Works in Android Studio, Great plugin

**Comment by felangel** [comment]
@cyrsis this should be addressed by #228

**Comment by felangel** [comment]
Just pushed the update (v1.3) so it should be available in the next few days 👍 
Closing this for now but feel free to open another issue if the problem persists in v1.3
