### ISSUE TITLE
[Question] The flutter_firebase_login and flutter_firestore_todos use different structures

### ISSUE THREAD

**Issue by bgervan** [felangel/bloc#2270]
Hi, 

I have just started with flutter and bloc. I have tried the firebase todos app and the firebase login app and tried to merge it without luck.

The firebase login: 

- It has proper login and sign up pages
- It uses SomePage.route()

The firebase todos:

- It uses MultiblocProviders and route navigation
- The proper login page is a big miss, if it has it, could be usable as a template

Also the folder structure is different.
Which one is better, and how to merge the two app? 

Other errors:
The dependencies are incorrect in the example, newer flutter bloc is required for example.
The google sign in miss a big step, which cause crash in iOS, the tutorial could be extended by this, the firestore official doc doesn't mention: 

```
<key>CFBundleURLTypes</key>
<array> 
  <dict> 
    <key>CFBundleTypeRole</key> 
    <string>Editor</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <! - TODO Replace this value: -->
      <! - Copied from GoogleServices-Info.plist key REVERSE_CLIENT_ID -->
      <string>com.googleusercontent.apps.461305999095-eben8ar105amv32f7uiekdn1vbpi1hld</string> 
    </array>
  </dict>
</array>
```

Thank you for the suggestions.

**Comment by felangel** [comment]
Hi @bgervan 👋 
Thanks for opening an issue!

This is will be addressed as part of #2276 👍
