### ISSUE TITLE
[Question] When to dart migrate --apply-changes?

### ISSUE THREAD

**Issue by miriam-z** [felangel/bloc#2271]
**Describe the bug**
When is appropriate to dart migrate --apply-changes for firebase_login example etc? 

Wait until all packages indicate version opting in to null safety?

![Screenshot 2021-03-26 at 20 46 20](https://user-images.githubusercontent.com/19760229/112690811-53e81000-8e74-11eb-833f-9a92c451d794.png)

**To Reproduce**
dart pub outdated --mode=null-safety

**Expected behavior**
all packages to null safety

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

 [✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.0.3 at $HOME/flutter
    • Framework revision 4d7946a68d (8 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at $HOME/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = $HOME/Library/Android/sdk
    • ANDROID_SDK_ROOT = $HOME/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.8538.45

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] VS Code (version 1.29.1)
    • VS Code at$HOME/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • 51E80FB1-C689-4F5E-8331-69F4FD43AEEB • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 11.2.3 20D91 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 89.0.4389.90

**Comment by felangel** [comment]
Hi @miriam-z 👋 
Thanks for opening an issue!

I believe most examples should be ready to migrate to null safety and I will do my best to migrate the remaining examples over as soon as I can. The reason it has taken longer is because I am rewriting/refactoring each example in the process in order to make them as "production-ready" as possible (which includes unit and widget tests).

Closing this but I'm going to use #2123 to track the progress of the example null safety migration and refactors 👍
