### ISSUE TITLE
Issue in BlocObserver after updating the new version 7.0.0

### ISSUE THREAD

**Issue by GaneshSingaravelu** [felangel/bloc#2273]
Hi,

I have updated the bloc, flutter_bloc in the flutter app. After that, I got the error on the "onCreate, onChange, onError, onClose" methods in MyBlocobserver class using BlocObserver.

**_Error Message:_**
"message": "'MyBlocObserver.onCreate' ('void Function(Cubit<dynamic>)') isn't a valid override of 'BlocObserver.onCreate' ('void Function(BlocBase<dynamic>)').",

**_Packages:_**
  bloc: ^7.0.0  
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  equatable: ^2.0.0
  simple_animations: ^3.0.2
  connectivity_plus: ^1.0.0
  path_provider: ^2.0.1

**_Flutter Version_**

Flutter 2.0.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4d7946a68d (8 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2

![image](https://user-images.githubusercontent.com/26732057/112719123-230fe580-8f1d-11eb-9c2a-ea6707bedfcf.png)

Thanks,

**Comment by devj3ns** [comment]
Have a look at https://bloclibrary.dev/#/migration.

`Bloc` and `Cubit` extend `BlocBase` now. 

So you have to change `Cubit` to `BlocBase`.

**Comment by GaneshSingaravelu** [comment]
Hi @devj3ns ,

Thanks for your kind update.  I have updated the Blocbase as per the documentation which you shared.

But now I have got another issue i.e (This requires non-nullable language feature to be enabled)

I have updated the minimum SDK version 2.12.0. After that, I have to do a lot of changes in my app like (remove null values & Changes in Blocstate)

is there any workaround for this scenario?

**_pubspec.yaml_**

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  hydrated_bloc: ^7.0.0
  equatable: ^2.0.0
  simple_animations: ^3.0.2
  connectivity_plus: ^1.0.0
  path_provider: ^2.0.1


![image](https://user-images.githubusercontent.com/26732057/112722633-b7d00e80-8f30-11eb-9ab2-a4c4965dc227.png)

Thanks

**Comment by devj3ns** [comment]
I would recommend that you migrate your codebase to null safety. It's a bit of work, but it makes your codebase more secure. 

If you need help, have a look at this page: https://dart.dev/null-safety/migration-guide

**Comment by felangel** [comment]
Hi @GaneshSingaravelu  👋 
Thanks for opening an issue and thanks @devj3ns for taking the time to answer!

While I would also recommend upgrading to null safety, you can still use the latest version without null safety:

```dart
@override
void onEvent(Bloc bloc, Object event) {...}
```

Hope that helps 👍 

Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 😄

**Comment by jay23794** [comment]
@override
  void onEvent(Bloc bloc, Object? event) {  //Pass parameter like this Object? event. its giving an error when Object event
    super.onEvent(bloc, event); 
    print(event);
  }

**Comment by narcodico** [comment]
What error are you getting @jay23794 ? feel free to share a sample with your issue.

**Comment by hunglvv** [comment]
Hi, I have updated flutter_bloc to 8.1.1. then I got the same error as @GaneshSingaravelu's on the "onEvent" method
![image](https://user-images.githubusercontent.com/74697891/192256504-070b46d8-64ff-44a8-8b0f-288b1bf2f387.png)

**Comment by felangel** [comment]
@hunglvv it should be:
```dart
@override
void onEvent(Bloc bloc, Object? event) {…}
```
