### ISSUE TITLE
Add "addStream" method in Bloc

### ISSUE THREAD

**Issue by webnickell** [felangel/bloc#2275]
When we want to interact between our blocs, we pass one bloc to other in constructor args and listen it. Like it next example.
```dart
class MyBloc extends Bloc {
  final OtherBloc otherBloc;
  StreamSubscription otherBlocSubscription;

  MyBloc(this.otherBloc) {
    otherBlocSubscription = otherBloc.listen((state) {
        // React to state changes here.
        // Add events here to trigger changes in MyBloc.
    });
  }

  @override
  Future<void> close() {
    otherBlocSubscription.cancel();
    return super.close();
  }
} 
```

But I think that it's not very flexible solution, because:
1. Our blocs need to know about states of each other.
2. We need to manually cancel subscriptions.

I suggest to add "addStream" method to bloc with such signature:
```dart
Future<void> addStream(Stream<TEvent> stream)
```
We could use it like this:
```dart
BlocProvider<AuthBloc>(
 create: (ctx) => AuthBloc(),
),
BlocProvider<ProfileBloc>(
 create: (ctx) => ProfileBloc()..addStream(
   ctx.read<AuthBloc>()
        .stream
        .whereType<AuthStateLogin>()
        .map((state) => ProfileEventLoad()),
 ),
)
```
In this case we could use all power of rxdart and simple using. Also each of blocs don't need to depend on each other.

**Comment by PlugFox** [comment]
@felangel this is bad feature with `addStream` from `dart:async` out of box.
if u `blocA.eventController.addStream(blocB.map(state2event));`
When `blocB.stateController` not closed - you can't `blocA.eventController.add(someEvent)`.
and can't `blocA.eventController.addStream(blocC.map(state2event));`.

**Comment by felangel** [comment]
Closing for now because as @PlugFox mentioned this has the potential to introduce way more problems that it will solve. If the community feels that this solution is really necessary then we can revisit implementing a custom `addStream` API but I would prefer to avoid this unless there are many compelling use-cases.
