### ISSUE TITLE
[docs] refactor examples to be production-quality

### ISSUE THREAD

**Issue by felangel** [felangel/bloc#2276]
**Is your feature request related to a problem? Please describe.**
As a developer, I expect to be able to look at any example app in the examples directory and have the code be production quality. This includes:

- [x]  Counter
    - [x]  null-safety
    - [x]  Web
    - [x]  Desktop
    - [x]  layered architecture
    - [x]  unit
    - [x]  widget
    - [x] up-to-date documentation
- [x]  Timer
    - [x]  null-safety
    - [x]  Web
    - [x]  Desktop
    - [x]  layered architecture
    - [x]  unit
    - [x]  widget
    - [x] up-to-date documentation
- [x]  Infinite List
    - [x]  null-safety
    - [x]  layered architecture
    - [x]  unit
    - [x]  widget
    - [x]  Web
    - [x]  Desktop
    - [x] up-to-date documentation
- [x]  Login
    - [x]  null-safety
    - [x]  Web
    - [x]  Desktop
    - [x]  layered architecture
    - [x]  unit
    - [x]  widget
    - [x] up-to-date documentation
- [x]  Firebase Login
    - [x]  null-safety
    - [x]  web
    - [x]  Desktop
    - [x]  layered architecture
    - [x]  unit
    - [x]  widget
    - [x] up-to-date documentation
- [x]  Weather
    - [x]  null-safety
    - [x]  Web
    - [x]  Desktop
    - [x]  layered architecture
    - [x]  unit
    - [x]  widget
    - [x] up-to-date documentation
- [x]  Firebase todos
    - [x]  null-safety
    - [x]  Web
    - [x]  Desktop
    - [x]  layered architecture
    - [x]  unit
    - [x]  widget
    - [x] up-to-date documentation
- [x]  Todos
    - [x]  null-safety
    - [x]  web
    - [x]  Desktop
    - [x]  layered architecture
    - [x]  unit
    - [x]  widget
    - [x] up-to-date documentation
- [x]  Fluttersaurus
    - [x]  null-safety
    - [x]  Web
    - [x]  Desktop
    - [x]  layered architecture
    - [x]  unit
    - [x]  widget
    - [x] up-to-date documentation

**Comment by Gene-Dana** [comment]
Sunday Funday

**Comment by Gene-Dana** [comment]
Would diagrams like these help? 

![image](https://user-images.githubusercontent.com/45580241/113937337-026e4800-97c7-11eb-93af-473733d3969e.png)

![image](https://user-images.githubusercontent.com/45580241/113937367-0e5a0a00-97c7-11eb-8a21-d84d52f4782c.png)

**Comment by Gene-Dana** [comment]
@felangel Is the Flutter Infinite Post example a good candidate for Cubit? What do you think about one example that has both a cubit and bloc implementation?

**Comment by nimi0112** [comment]
@felangel  how about giving reference to the https://github.com/flutter/photobooth. In my opinion this is an excellent resource

**Comment by felangel** [comment]
> @felangel how about giving reference to the https://github.com/flutter/photobooth. In my opinion this is an excellent resource

Yeah definitely a good call! I'll add the reference to it in the READMEs 👍

**Comment by nimi0112** [comment]
> > @felangel how about giving reference to the https://github.com/flutter/photobooth. In my opinion this is an excellent resource
> 
> Yeah definitely a good call! I'll add the reference to it in the READMEs 👍

PhotoBooth is a game changer for me. Can't tell how much I take reference from that project regarding writing test cases and arranging my project files.
