### ISSUE TITLE
Repository Provider does not seem to support abstract base classes.

### ISSUE THREAD

**Issue by TommyLCox** [felangel/bloc#2279]
In the documentation, it states that RepositoryProvider uses "dependency injection" to support singleton instances of the application's repositories. However, it seems to require specific concrete implementations of my repository classes and cannot handle abstract base classes.

The solution I would like would be where you could store in the dependency injection a specific repository implementation under its base class so that it is easy to swap out repositories with mock repositories or other implementations without the bloc having to know which specific implementation was used.

Currently, as an alternative to RepositoryProvider, I simply inject the specific repository implementation I need into my bloc's constructor. But, I thought I would try to use RepositoryProvider instead to see if it would streamline my code.

Here is an example with an entity called "Profile".

 I would like to provide it like this where ProfileRepository is the base type and a specific child class is provided:
` RepositoryProvider<ProfileRepository>(
        create: (context) => FirebaseProfileRepository(),
      );`

Then, the ProfileBloc would use it like this:
`Repository.of<ProfileRepository>(context);`

So, I am basically injecting the Firebase implementation of my ProfileRepository into my ProfileBloc. The ProfileBloc just requests a ProfileRepository (abstract base class) and in this case, it would return the Firebase implementation. The bloc doesn't have to know which specific implementation of the profile repository that ti is using.

What happens now is that I get an error when using Repository.of<ProfileRepository>(context) that "abstract classes cannot be instantiated". This tells me that it is not really able to do dependency injection because it seems to require  a specific implementation type.

Am I doing something wrong with RepositoryProvider? Is there a way to make it work? Or, should I just continue passing the specific instance through the Bloc constructor  when I use the MultiBlocProvider? The latter is working fine for me, but one of my developers asked me about using RepositoryProvider instead of doing injection through the Bloc constructors, so I thought I would look into it.  - Thank you.

**Comment by felangel** [comment]
Hi @TommyLCox 👋 
Thanks for opening an issue!

Can you please provide a reproduction sample? The use-case you're describing should be supported, thanks! 👍

**Comment by TommyLCox** [comment]
@felangel  Yes, I will be happy put together some code examples for consideration.

**Comment by felangel** [comment]
@TommyLCox have you had a chance to put together a small reproduction sample? Thanks!

**Comment by felangel** [comment]
@TommyLCox going to close this for now but feel free to comment with a reproduction sample and I'm happy to reopen and continue the conversation 👍
