### ISSUE TITLE
BlocBuilder intermittently not receiving states from bloc

### ISSUE THREAD

**Issue by PaulVipond** [felangel/bloc#2282]
**Describe the bug**
Intermittently, states are yielded by my bloc, but not received by the BlocBuilder that is supposed to respond to them.

**To Reproduce**
This is quite involved and could be down to timing, so I'm not sure I can put together a minimum reproducible example, but here's the gist of it. The number on the left hand side represents the current Unix time stamp in milliseconds.

In my bloc:

1) 1617189409542 Create message in database in Moor and expect a corresponding stream notification at some point
2) 1617189409630 Yield a state which notifies the UI to expect user input
3) 1617189409634 Receive the Moor stream notification and yield a state which notifies the UI to update the chat typing indicators

There is a 4ms gap between 2) and 3) and the state yielded in 2) is not received by the BlocBuilder that is listening for it. This happens intermittently - sometimes it is received, sometimes not. In this case it wasn't.

I'm not sure how Bloc is architected internally, but are all states 'guaranteed' to be received? I.e. there's a queue and they're all dispatched, or is it possible for states to be replaced and therefore some kind of delay logic is necessary?

Because I receive stream notifications to the bloc from database processing outside of mapEventToState(), for both yields I'm raising 'back-end' events using bloc.add(..) and then these are received in mapEventToState and yielded into UI states.

**Expected behavior**
All bloc states should be received and processed by BlocBuilder.

**Code samples**

_Bloc Class_

Handling stream notification from Moor:

  ```
...
groupChangeSubscription = groupChangeStream.listen(handleTypingIndicatorsChange);
...

void handleTypingIndicatorsChange(ContentGroup group) {
    if (this.activeTypists != group.activeTypists) {
      List<String> users = group.activeTypists.split(',');
      if (users[0].isEmpty) {
        users = [];
      }
      this.add(InboundTypingIndicatorsEvent(users));
      this.activeTypists = group.activeTypists;
    }
  }

```
Raising an input notification event:

`this.add(AwaitInputEvent(botEvent.inputState));`

Yielding both events as states:

```
Stream<ChatState> mapEventToState(ChatEvent event) async* {
...
    if (event is AwaitInputEvent) {
      yield AwaitInputState(event.inputState);
    }
    if (event is InboundTypingIndicatorsEvent) {
      yield TypingIndicatorsChangeState(event.users, AppState.i.lastGroupMessageId);
    }
}

```

_UI_

Note, I get no output from print('chat footer mainFooterBody(): $state') in the code below when the state is not received.

```
@override
  Widget build(BuildContext context) {
    chatBloc = BlocProvider.of<ChatBloc>(context);
    typingIndicatorTracker.chatBloc = chatBloc;

    return BlocBuilder<ChatBloc, ChatState>(builder: mainFooterBody);
  }

  Widget mainFooterBody(BuildContext context, ChatState state) {
    print('chat footer mainFooterBody(): $state');
    if (state is AwaitInputState && state.inputState != currentInputState) {
      adjustInputToState(state.inputState);
      currentInputState = state.inputState;
      //print('chat footer mainFooterBody(): new input state: $currentInputState');
    }
    if (state is MessageSentState) {
      resetInputState();
    }

```

**Screenshots**
N/A

**Logs **
Run `flutter analyze` and attach any output of that command below. Nothing major:

   info - Dead code - lib\models\data\app_db.dart:230:5 - dead_code
   info - The declaration '_userDao' isn't referenced - lib\providers\user_data_provider.dart:16:19 - unused_element
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its
          instance fields aren't final: BaseChatItem.isFromAppUser - lib\ui\widgets\core\chat\base_chat_item.dart:7:16 -
          must_be_immutable
   info - Dead code - lib\ui\widgets\core\chat\base_chat_item.dart:131:7 - dead_code
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its
          instance fields aren't final: ContentChoiceMessage.chatBloc, BaseChatItem.isFromAppUser -
          lib\ui\widgets\core\chat\chat_items\content_choice_message.dart:10:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its
          instance fields aren't final: FormMessage.webViewController, FormMessage.options, FormMessage.isFromAppUser,
          BaseChatItem.isFromAppUser - lib\ui\widgets\core\chat\chat_items\form_message.dart:11:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its
          instance fields aren't final: TextMessage.isFromAppUser, TextMessage.containsLinkMetadata,
          BaseChatItem.isFromAppUser - lib\ui\widgets\core\chat\chat_items\text_message.dart:15:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its
          instance fields aren't final: TypingIndicator.isActive -
          lib\ui\widgets\core\chat\chat_items\typing_indicator.dart:8:7 - must_be_immutable
   info - This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its
          instance fields aren't final: PagedAnimatedList.controller, PagedAnimatedList.scrollDuration -
          lib\ui\widgets\helpers\paged_animated_list.dart:23:7 - must_be_immutable
   info - The declaration '_MaxVelocityPhysics' isn't referenced - lib\ui\widgets\helpers\paged_animated_list.dart:453:7
          - unused_element
   info - 'RaisedButton' is deprecated and shouldn't be used. Use ElevatedButton instead. See the migration guide in
          flutter.dev/go/material-button-migration-guide). This feature was deprecated after v1.25.0-8.1.pre. -
          lib\ui\widgets\helpers\slide_button_menu.dart:43:28 - deprecated_member_use

Paste the output of running `flutter doctor -v` here.

[✓] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.18363.1316], locale en-GB)
    • Flutter version 2.0.3 at C:\SDK\flutter\flutter_windows_v1.2.1-stable\flutter
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Paul\AppData\Local\Android\sdk
    • Platform android-30, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.54.3)
    • VS Code at C:\Users\Paul\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[✓] Connected device (3 available)
    • M2007J20CG (mobile) • d9c2c646 • android-arm64  • Android 10 (API 29)
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)          • edge     • web-javascript • Microsoft Edge 89.0.774.63

• No issues found!

**Additional context**
N/A

**Comment by felangel** [comment]
Hi @PaulVipond 👋 
Thanks for opening an issue!

This is expected behavior because BlocBuilder can only rebuild as fast as the Flutter Framework allows (60fps) which means if your bloc is emitting subsequent states faster than flutter can re-render then BlocBuilder will "miss" states.

I would highly recommend refactoring your bloc state to accumulate the data/notifications using a `copyWith` method rather than emitting completely independent states. Alternatively, you can use `BlocListener` which is guaranteed to be notified for each state change. Let me know if that helps 👍

**Comment by PaulVipond** [comment]
Thanks for this @felangel - my creeping sense of paranoia that there was something fundamentally wrong with what I've done has now been eased :-)

I'm still relatively new to flutter, so would appreciate it if you could elaborate on the accumulation / copyWith approach. For instance, if I don't know when the events are coming in, do I accumulate them and then emit them in short bursts?

**Comment by haashem** [comment]
@felangel Thanks for pointing this, would you add this hint in documentation? I had same issue, and I thought its a bug!

**Comment by narcodico** [comment]
Hi @PaulVipond 👋

Here's a quick `rxdart` approach to buffering quick incoming events which end up triggering an aggregate event. This way you won't yield a bunch of bloc states which get skipped.

```
abstract class BufferEvent extends Equatable {
  const BufferEvent();

  @override
  List<Object?> get props => [];
}

class BufferQuickEvent extends BufferEvent {
  const BufferQuickEvent(this.value);

  final int value;

  @override
  List<Object> get props => [value];
}

class BufferSumEvent extends BufferEvent {
  const BufferSumEvent(this.sum);

  final int sum;

  @override
  List<Object> get props => [sum];
}

```

```
class BufferState extends Equatable {
  const BufferState(this.value);

  final int value;

  @override
  List<Object> get props => [value];
}

```

```
class BufferBloc extends Bloc<BufferEvent, BufferState> {
  BufferBloc() : super(const BufferState(0)) {
    _sub = Stream.periodic(
      const Duration(milliseconds: 100),
      (value) => BufferQuickEvent(value),
    ).listen(add);
  }

  late StreamSubscription _sub;

  @override
  Future<void> close() async {
    await _sub.cancel();
    return super.close();
  }

  @override
  Stream<BufferState> mapEventToState(
    BufferEvent event,
  ) async* {
    if (event is BufferSumEvent) {
      yield BufferState(event.sum);
    }
  }

  @override
  Stream<Transition<BufferEvent, BufferState>> transformEvents(
      Stream<BufferEvent> events, transitionFn) {
    final bufferedEvents = events
        .whereType<BufferQuickEvent>()
        .bufferTime(const Duration(seconds: 1))
        .flatMap((bufferEvents) async* {
      final sum = bufferEvents.fold<int>(
        0,
        (previousValue, element) => previousValue + element.value,
      );
      yield BufferSumEvent(sum);
    }).asyncExpand(transitionFn);

    final forwardedEvents =
        events.whereType<BufferSumEvent>().asyncExpand(transitionFn);

    return forwardedEvents.mergeWith([bufferedEvents]);
  }
}
```

**Comment by PaulVipond** [comment]
Thanks for posting this @narcodico - I appreciate the effort. So I can see the BufferQuickEvents are summed over a second and then yielded as an aggregate. In my case, as it's a chat app, I have various asynchronous events (typing indicators, incoming messages, presence indicators) that may happen in the background, mixed with UI sourced typing indicators and messages. I can't really aggregate anything, so is it best to do something similar with the transformEvents() method, but emit a superstate which is an array of substates? Theoretically any network sourced state could be right next to any UI sourced state. Or would there be a way to force a rhythm to event -> state conversion, so store events and emit them as states every 50ms if there is one?

**Comment by narcodico** [comment]
One option is to aggregate each type of event separately and yield a separate aggregated event by type.
Other option is to have a more complex event class which holds aggregated data for multiple sources.


> Or would there be a way to force a rhythm to event -> state conversion, so store events and emit them as states every 50ms if there is one?

You could use `.interval()` from `rxdart` to space out state emissions in `transformTransitions`, but I find caching events and aggregating them to be cleaner while also allowing you to control the duration between state emissions.

**Comment by PaulVipond** [comment]
Thanks @narcodico. One other question I had - how do the transform...() functions get called? E.g. are they called for every item that is added to the stream, or are they grouped? Lets say I use the interval() function and the following sequence of events happens:
1. Time 00:00:00 + 220ms - event received
2. Time 00:00:00 + 250ms - event received - transformEvents() called with 2 items - each gets 30ms added
3. Time 00:00:00 + 254ms - event received - transformEvents() called with 1 item - gets 30 ms added
Events 2 and 3 are re-emitted at 280ms and 284ms, so the effect of spacing the events with a minimum gap of 30ms is not achieved.

**Comment by narcodico** [comment]
If you're buffering events you don't need `interval` added.

**Comment by PaulVipond** [comment]
I meant if I was using interval() instead of buffering

**Comment by narcodico** [comment]
`interval` will hold each event for the specified duration before being released thus handled. This works well but if you're receiving a bunch of events and you care about the real-time aspect of your incoming data then this won't cut it. Same goes if you'd space out the transitions using the same approach. This is up to you to decide based on the volume of events.

When dealing with large number of events buffering them gets the job done.

Something else I'd recommend is to ensure you're processing distinct events only if this is something you can get away with.

**Comment by PaulVipond** [comment]
Ace. Appreciate your patience :-)

**Comment by hateshkumar** [comment]
@PaulVipond  did you find any work around for that?
