### ISSUE TITLE
The listen of BlocConsumer does not work when yielding the same State multiple times, even though I set listenWhen(return true)

### ISSUE THREAD

**Issue by 1541157892** [felangel/bloc#2288]
Hello, when I use "BlocConsumer", if the user continues to submit a verification error behavior, I will continue to "yield" the same "State" in the "Bloc". Is this behavior correct? Well, if it is correct, when I set "listenWhen" (return true), "listen" is not executed multiple times

**Comment by felangel** [comment]
Hi @1541157892 👋 
Thanks for opening an issue!

This is expected behavior because regardless of `listenWhen`, blocs will not re-emit the same state. Hope that helps 👍

**Comment by 1541157892** [comment]
alright, thank you very much
