### ISSUE TITLE
About using navigator in the [app.dart] file.

### ISSUE THREAD

**Issue by thinhhoangnguyen** [felangel/bloc#2289]
class AppView extends StatefulWidget {
  @override
  _AppViewState createState() => _AppViewState();
}

class _AppViewState extends State<AppView> {
  final _navigatorKey = GlobalKey<NavigatorState>();

  NavigatorState get _navigator => _navigatorKey.currentState;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: theme,
      navigatorKey: _navigatorKey,
      builder: (context, child) {
        return BlocListener<AuthenticationBloc, AuthenticationState>(
          listener: (context, state) {
            switch (state.status) {
              case AuthenticationStatus.authenticated:
                _navigator.pushAndRemoveUntil<void>(
                  HomePage.route(),
                  (route) => false,
                );
                break;
              case AuthenticationStatus.unauthenticated:
                _navigator.pushAndRemoveUntil<void>(
                  LoginPage.route(),
                  (route) => false,
                );
                break;
              default:
                break;
            }
          },
          child: child,
        );
      },
      onGenerateRoute: (_) => SplashPage.route(),
    );
  }
}

Recently I use this navigation structure for my projects. I find using onGenerateRoute as a Splash Ccreen gives me some discomfort. For example, when this structure navigates to the HomePage screen, in the time it is about to convert, the splash screen will appear, but it will show up for a very short time. Therefore, when users look at the splash screen, they do not perceive exactly what it is, which makes the user feel uncomfortable in terms of UX.

**Comment by Gene-Dana** [comment]
Hi there ! I appreciate you sharing this issue, I think I know what you are talking about. The user is already authenticated in this case, and the when you refresh, the splash screen is only there for a moment ! 

I have the same issue with what I'm working on right now ! 

I can imagine two possible solutions here, and it would help to have a more senior dev weigh in on this !

1) Hydrated Bloc to manage the cached state? In my case, I believe authentication is persisted by Firebase Auth and perhaps it is in that process there is a momentary unauth case, which causes the flicker.

2) Simple and stupid solution, put a delay on the splash screen? Make it hold for a second?

**Comment by thinhhoangnguyen** [comment]
> Hi there ! I appreciate you sharing this issue, I think I know what you are talking about. The user is already authenticated in this case, and the when you refresh, the splash screen is only there for a moment !
> 
> I have the same issue with what I'm working on right now !
> 
> I can imagine two possible solutions here, and it would help to have a more senior dev weigh in on this !
> 
> 1. Hydrated Bloc to manage the cached state? In my case, I believe authentication is persisted by Firebase Auth and perhaps it is in that process there is a momentary unauth case, which causes the flicker.
> 2. Simple and stupid solution, put a delay on the splash screen? Make it hold for a second?

Do you mean to use HydratedBloc instead of Bloc?

**Comment by Gene-Dana** [comment]
I believe Hydrated bloc works in conjunction with Bloc. @felangel, would that be correct?

**Comment by thinhhoangnguyen** [comment]
I need an effective solution

**Comment by thinhhoangnguyen** [comment]
> Hi there ! I appreciate you sharing this issue, I think I know what you are talking about. The user is already authenticated in this case, and the when you refresh, the splash screen is only there for a moment !
> 
> I have the same issue with what I'm working on right now !
> 
> I can imagine two possible solutions here, and it would help to have a more senior dev weigh in on this !
> 
> 1. Hydrated Bloc to manage the cached state? In my case, I believe authentication is persisted by Firebase Auth and **perhaps it is in that process there is a momentary unauth case, which causes the flicker.**
> 2. Simple and stupid solution, put a delay on the splash screen? Make it hold for a second?

**Comment by felangel** [comment]
Hi @thinhhoangnguyen 👋 
Thanks for opening an issue!

This tutorial is currently out-dated and I'm going to rework it to use Navigator 2.0 with [flow_builder](https://pub.dev/packages/flow_builder) to handle the navigation stack based on the authentication state. This will allow you to remove the flutter splash screen and only rely on the native splash screen which should be present for a reasonable amount of time 👍 

The work for the refactor will be done as part of #2276

**Comment by narcodico** [comment]
@Gene-Dana when properly using firebase auth you won't have issues and you surely won't need hydrated bloc to cache anything. 
You should only rely on the native splash screen; no in-app splash screen is needed since the native one will be present until flutter draws it's first frame and that will give you plenty of time to check for the auth status and know exactly where to navigate the user.

**Comment by Gene-Dana** [comment]
@narcodico Hi ! I think this is what OP is talking about ! 

![2021-04-07 16 28 28](https://user-images.githubusercontent.com/45580241/113930038-c636e980-97be-11eb-901d-cf989b3c843f.gif)


At first, using Firebase auth, even though it has persistence, the initial state is unauthenticated 
![image](https://user-images.githubusercontent.com/45580241/113930192-f8484b80-97be-11eb-9580-233b93bfe0ce.png)

**Comment by narcodico** [comment]
@Gene-Dana before calling `runApp` you can check the auth status from firebase auth and set the `initialRoute` on the `MaterialApp`.

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions or join the [bloc discord](https://discord.gg/bloc) 👍
