### ISSUE TITLE
Mock a cubit method response

### ISSUE THREAD

**Issue by RickZzDev** [felangel/bloc#2290]
Hello guys, i'm trying to mock a response of a method in a cubit.
I tried this:
    whenListen(loginCubit.auth(), Stream<LoginState>.value(LoginLoading()));
So when i call loginCubit.auth() i would like to emit this LoginLoading state, but a receive and compilation error
Can anyone help me?

**Comment by Elias8** [comment]
Hey @RickZzDev 👋

The `whenListen` method expects a `cubit` subclass and stream of the cubit's state.

To fix your code, you need to change it something like this `whenListen(loginCubit, Stream.value(LoginLoading()));`.

Hope that helps.

**Comment by RickZzDev** [comment]
Thxxx
