### ISSUE TITLE
CubitListener of auth cubit inside Project_list_page gives build on null error

### ISSUE THREAD

**Issue by Himanshu081** [felangel/bloc#2294]
![image](https://user-images.githubusercontent.com/49179641/113508146-fd618c80-956b-11eb-901c-4fbe44be0c85.png)

I am facing this error whenever i am trying to use Auth cubit inside my Project list Page even when i have injected the auth cubit correctly inside this page and also returning the container when state condition is false.

code where i am using the cubit ::
![image](https://user-images.githubusercontent.com/49179641/113508206-4f0a1700-956c-11eb-9cfd-501bde56548d.png)

 code of parent widget where i am injecting the cubit:::
![image](https://user-images.githubusercontent.com/49179641/113508238-7b259800-956c-11eb-9392-64bdfee61134.png)

please help me

**Comment by devj3ns** [comment]
You have to pass the container to the `child` attribute of the `BlocListener` instead of returning it in the `listener` function.   

A `BlocListener` is for doing things like showing a snackbar. If you want to display a widget based on the current state use a `BlcBuilder`.

**Comment by Himanshu081** [comment]
Thanks man.
