### ISSUE TITLE
Website broken on mobile

### ISSUE THREAD

**Issue by chimon2000** [felangel/bloc#2299]
**Describe the bug**
The documentation website navigation appears to be broken on mobile devices. It opens with a transparent background and it doesn't appear to let me select any menu items.

**To Reproduce**
1. Go to Bloc website on mobile device.
2. Click on menu button
3. See behavior

**Expected behavior**
Should be able to navigate to sections of site using menu. Should be able to view menu without transparency.

**Screenshots**
![Screenshot_20210405-154212](https://user-images.githubusercontent.com/6907797/113619068-8210e100-9626-11eb-8218-9bfc552d41b1.jpg)

**Logs **
n/a

**Additional context**
n/a

**Comment by dawidd6** [comment]
It works fine if you just scroll down a bit though.

**Comment by felangel** [comment]
Hi @chimon2000 👋 
Thanks for opening an issue!

@dawidd6 yeah I think it's just an issue with the coverpage. I'll try to get a fix for this asap 👍
