### ISSUE TITLE
Inject a repository instance to a Generated Route bloc instance

### ISSUE THREAD

**Issue by joseucarvajal** [felangel/bloc#2301]
According to this Bloc documentation ([https://bloclibrary.dev/#/recipesflutterblocaccess?id=generated-route-access](https://bloclibrary.dev/#/recipesflutterblocaccess?id=generated-route-access)), we can create a Bloc instance for sharing it among different routes. The problem I'm currently facing is, how could I inject a repository dependency into this bloc instance (The _counterBloc one)?

I have read the documentation but I haven't found a solution to do that. The repository I want to inject into this bloc is a repository that I created with the "MultiRepositoryProvider" functionality.

Thanks in advance,

**Comment by Gene-Dana** [comment]
HI @joseucarvajal ! Do you mean something like this:

```dart
@override
  Widget build(BuildContext context) {
    return RepositoryProvider.value(
      value: authenticationRepository,
      child: BlocProvider(
        create: (_) => AuthenticationBloc(
          authenticationRepository: authenticationRepository,
        ),
        child: AppView(),
      ),
    );
  }
}
```

https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/lib/app.dart

**Comment by narcodico** [comment]
Hi @joseucarvajal 👋

If your repository instance is not directly available(usually because it is further up the tree) you can always make use of the context to retrieve it:

```
 BlocProvider<CounterBloc>(
        create: (context) => CounterBloc(
          userRepository: context.read<UserRepository>(),
        ),
```

**Comment by joseucarvajal** [comment]
Hey guys thanks for answering, actually is more complicated than that. 

I'm currently using "Generated Access Routing", like so (in main.dart):

`return MaterialApp(
      debugShowCheckedModeBanner: false,
      navigatorKey: _navigatorKey,
      onGenerateRoute: _appRouter.onGenerateRoute,`

Now, in my AppRouter class I have a bloc instance (in my AppRouter class):
`class AppRouter {
  MandatoryQuestionnaireBloc _mandatoryQuestionnaireBloc;`

What I need to do is to share this bloc among different screens, so I'm creating the Bloc instance (_mandatoryQuestionnaireBloc) manually and using BlocProvider for each route:
`MaterialPageRoute(
          builder: (_) => BlocProvider.value(
            value: _mandatoryQuestionnaireBloc,`

Since I have created this bloc instance manually within my AppRouter class as recommended in the [official Bloc documentation](https://bloclibrary.dev/#/recipesflutterblocaccess?id=generated-route-access), I don't have access to any context instance to get my repository previously created using dependence injection through MultiRepository provider: 

` return MultiRepositoryProvider(
      providers: [
        RepositoryProvider(
          create: (context) {
            return FirebaseUserDataRepository();
          },
        ),`

The question is, how can I pass the FirebaseUserDataRepository to my AppRouter class in order to inject this instance into my bloc instance?, and again, I don't have access to any context instance in my AppRouter class.

Thanks again,

**Comment by narcodico** [comment]
With your setup you can simply inject your repo instance in your `AppRouter` then pass it to your bloc.

**Comment by joseucarvajal** [comment]
> With your setup you can simply inject your repo instance in your `AppRouter` then pass it to your bloc.

Awesome,  @narcodico, thanks. Any place in main.dart recommended to do that?, I'm currently doing that in the last BlocProvider injection, because that Bloc would also need another bloc as dependency:

```
BlocProvider<UserDataBloc>
            create: (context) {
              var userDataBloc = UserDataBloc(
                firebaseAuthenticationRepository:
                    context.read<FirebaseAuthenticationRepository>(),
                pdhiRepository: context.read<PDHIRepository>(),
                createAccountBloc: context.read<SignUpCredentialsBloc>(),
                userFeedbackBloc: context.read<DialogMessageBloc>(),
              );

              ****_appRouter.injectDependencies(****
                signUpService: context.read<SignUpService>(),
                dialogMessageBloc: context.read<DialogMessageBloc>(),
                authenticationBloc: context.read<AuthenticationBloc>(),
                userDataBloc: userDataBloc,
              );

```

This is the only place I've found to do that, but that's not pretty clear,

**Comment by narcodico** [comment]
I'm not sure about your setup but working from a basic example you'd have something like this:

```
void main() => runApp(App());

class App extends StatefulWidget {
  final CounterRepository counterRepository = CounterRepository();

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  late AppRouter _router;

  @override
  void initState() {
    _router = AppRouter(widget.counterRepository);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      onGenerateRoute: _router.onGenerateRoute,
    );
  }

  @override
  void dispose() {
    _router.dispose();
    super.dispose();
  }
}

class AppRouter {
  AppRouter(CounterRepository counterRepository)
      : _counterBloc = CounterBloc(counterRepository);

  final CounterBloc _counterBloc;

  Route onGenerateRoute(RouteSettings settings) {
    switch (settings.name) {
      case '/':
        return MaterialPageRoute(
          builder: (_) => BlocProvider.value(
            value: _counterBloc,
            child: HomePage(),
          ),
        );
      case '/counter':
        return MaterialPageRoute(
          builder: (_) => BlocProvider.value(
            value: _counterBloc,
            child: CounterPage(),
          ),
        );
      default:
        return UnknownPage();
    }
  }

  void dispose() {
    _counterBloc.close();
  }
}
```

**Comment by joseucarvajal** [comment]
> I'm not sure about your setup but working from a basic example you'd have something like this:
> 
> ```
> void main() => runApp(App());
> 
> class App extends StatefulWidget {
>   final CounterRepository counterRepository = CounterRepository();
> 
>   @override
>   _AppState createState() => _AppState();
> }
> 
> class _AppState extends State<App> {
>   late AppRouter _router;
> 
>   @override
>   void initState() {
>     super.initState();
>     _router = AppRouter(widget.counterRepository);
>   }
> 
>   @override
>   Widget build(BuildContext context) {
>     return MaterialApp(
>       title: 'Flutter Demo',
>       onGenerateRoute: _router.onGenerateRoute,
>     );
>   }
> 
>   @override
>   void dispose() {
>     _router.dispose();
>     super.dispose();
>   }
> }
> 
> class AppRouter {
>   AppRouter(CounterRepository counterRepository)
>       : _counterBloc = CounterBloc(counterRepository);
> 
>   final CounterBloc _counterBloc;
> 
>   Route onGenerateRoute(RouteSettings settings) {
>     switch (settings.name) {
>       case '/':
>         return MaterialPageRoute(
>           builder: (_) => BlocProvider.value(
>             value: _counterBloc,
>             child: HomePage(),
>           ),
>         );
>       case '/counter':
>         return MaterialPageRoute(
>           builder: (_) => BlocProvider.value(
>             value: _counterBloc,
>             child: CounterPage(),
>           ),
>         );
>       default:
>         return UnknownPage();
>     }
>   }
> 
>   void dispose() {
>     _counterBloc.close();
>   }
> }
> ```

Almost there @narcodico , but I'm utilizing the 'RepositoryProvider' to flesh out my entire chain of dependencies

```
RepositoryProvider(
          create: (context) {
            return TestResultsRepository(
              firebaseUserDataRepository:
                  context.read<FirebaseUserDataRepository>(),
              pdhiRepository: context.read<PDHIRepository>(),
              firebaseRemoteConfigRepository: _firebaseRemoteConfigRepository,
            );
          },
        ),
```

How to get this repository from context and send it to the AppRouter class?

**Comment by narcodico** [comment]
```
@override
  void initState() {
    super.initState();
    _router = AppRouter(context.read<CounterRepository>());
  }
```

**Comment by joseucarvajal** [comment]
> @override
>   void initState() {
>     super.initState();
>     _router = AppRouter(context.read<CounterRepository>());
>   }

Interesting, I'm getting a "_ProviderNotFoundException (Error: Could not find the correct Provider<PDHIRepository>_" error. But I also think the solution should something like that. This is the code:

```
@override
  void initState() {
    super.initState();
    initDependencies();
  }

  initDependencies() async {
    await _initializeFlutterFire();
    try {
      var myDependency = context.read<PDHIRepository>();
    } catch (e) {
      print(e);
    }
  }
```

**Comment by narcodico** [comment]
I think it would be easier if you'd share a minimal reproduction sample so that I can suggest you the right approach.

**Comment by joseucarvajal** [comment]
> I think it would be easier if you'd share a minimal reproduction sample so that I can suggest you the right approach.

Thanks @narcodico,

For sure, here is the minimalistic sample. Just a single bloc with a single repository dependency, not working with a Generated Route.

Minimalistic sample URL: [https://github.com/joseucarvajal/bloc_basic_injection](https://github.com/joseucarvajal/bloc_basic_injection)

My real scenario involves a deep chain of dependencies, that's why I need to use a "_MultiRepositoryProvider_"

Thanks,

**Comment by narcodico** [comment]
I've created a [PR](https://github.com/joseucarvajal/bloc_basic_injection/pull/1) with a fix. Hope that helps! ✌

**Comment by joseucarvajal** [comment]
Thanks so much, @narcodico, you rock man.

I was refactoring my code, your proposal is much more clearer. Because of my deep chain of dependencies, I ended up creating a lot of dependencies, including blocs in the main.dart file, something like:

In (**main.dart**):

```
@override
  void initState() {
    super.initState();
    _initDependencies();
  }

Future _initDependencies() async {
    await _initializeFlutterFire();

    /*Repositories*/
    _firebaseUserDataRepository = FirebaseUserDataRepository();
    _firebaseAuthenticationRepository = FirebaseAuthenticationRepository();
    _pdhiRepository = PDHIRepository(
      firebaseRemoteConfigRepository: _firebaseRemoteConfigRepository,
    );
    _signUpService = SignUpService(
      firebaseUserDataRepository: _firebaseUserDataRepository,
      pdhiRepository: _pdhiRepository,
    );

    /*Blocs*/
    _dialogMessageBloc = DialogMessageBloc();
    _authenticationBloc = AuthenticationBloc(
      authenticationRepository: _firebaseAuthenticationRepository,
    );
    _signUpCredentialsBloc = SignUpCredentialsBloc(
      firebaseAuthenticationRepository: _firebaseAuthenticationRepository,
      userFeedbackBloc: _dialogMessageBloc,
    );
    _userDataBloc = UserDataBloc(
      createAccountBloc: _signUpCredentialsBloc,
      userFeedbackBloc: _dialogMessageBloc,
      firebaseAuthenticationRepository: _firebaseAuthenticationRepository,
      pdhiRepository: _pdhiRepository,
    );

    /*Router*/
    _appRouter = AppRouter(
      signUpService: _signUpService,
      dialogMessageBloc: _dialogMessageBloc,
      authenticationBloc: _authenticationBloc,
      userDataBloc: _userDataBloc,
    );
  }

```

Because I'm creating some blocs manually I'm reusing them in the MultiBlocProvider (**main.dart**):

```
child: MultiBlocProvider(
providers: [
          BlocProvider.value(value: _dialogMessageBloc),
          //BlocProvider.value(value: _authenticationBloc),
          BlocProvider<AuthenticationBloc>(create: (context) {
            _authenticationBloc = AuthenticationBloc(
              authenticationRepository:
                  context.read<FirebaseAuthenticationRepository>(),
            );
            return _authenticationBloc;
          }),
          BlocProvider.value(value: _signUpCredentialsBloc),
          BlocProvider.value(value: _userDataBloc),
```

And I'm also closing them in the dispose method (**main.dart**):

```
@override
  void dispose() {
    _userDataBloc.close();
    _signUpCredentialsBloc.close();
    _dialogMessageBloc.close();
    _authenticationBloc.close();

    _appRouter.dispose();
    super.dispose();
  }
```
