### ISSUE TITLE
[QUESTION] [DOC] Interceptor bloc 

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2307]
Hi @felangel 🖐,

How to create an Interceptor bloc which handle if the request's status code is 401  then it will try re-auth user, if it cannot due to refresh token is invalid (because of the user device token was removed by another phone), then it will throw to login page?

It would be nice if you show an example and it could be added to documentation 🙂

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

I highly recommend using [fresh](https://github.com/felangel/fresh) to manage your authentication tokens. You can use [fresh_dio](https://pub.dev/packages/fresh_dio/versions/0.3.0-nullsafety.0) as an interceptor 👍 

Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 😄

**Comment by II11II** [comment]
Hi @felangel 👋
Thanks for the fast response,
I used http library instead of dio for remote HTTP requests.
Is fresh_dio applicable in my situation?

**Comment by II11II** [comment]
I found interesting package [http_interceptor](https://pub.dev/packages/http_interceptor) which is build on http library It can be used if you already have built your repository using HTTP library

**Comment by felangel** [comment]
@II11II fresh_dio only works with `dio` unfortunately but you can feel free to make your own implementation using `http_interceptor`. I personally recommend dio if you need interceptors but it's totally up to you 👍
