### ISSUE TITLE
Build error: angular_github_search [win]

### ISSUE THREAD

**Issue by eliaspn** [felangel/bloc#231]
Hello there 👋, thanks for the package and all detailed examples. The example git  github_search  helps a lot to conceptualize the cross platform architecture with BloC 👍

I'm having an issue while compiling the angular_github_search . It seems that some files are missing in /build/generated. Could be a permission issue ?

I've tried the following:
- running the command in Windows Power Shell
- deleting the github_search_result_item
 
Also notice how it looks after path, using both forward and back slashes. 

**To Reproduce**
clone the repo and cd into examples\github_search\angular_github_search
1. pub get
2. webdev serve
here it throws the following:
```
[SEVERE] build_modules:module_library on lib/src/github_search_form/github_search_body/github_search_results/github_search_result_item/github_search_result_item_component.dart:

FileSystemException: Cannot create file, path = 'c:\users\els\downloads\bloc-master\examples\github_search\angular_github_search\.dart_tool/build/generated/angular_github_search/lib/src/github_search_form/github_search_body/github_search_results/github_search_result_item/github_search_result_item_component.module.library' (OS Error: The system cannot find the path specified.
, errno = 3)
[SEVERE] build_modules:dartdevc on lib/$lib$: 

AssetNotFoundException: angular_github_search|.dart_tool/build/generated/angular_github_search/lib/src/github_search_form/github_search_body/github_search_results/github_search_result_item/github_search_result_item_component.module.library
[SEVERE] build_modules:dartdevc on web/main.dart:

NoSuchMethodError: The getter 'modules' was called on null.
Receiver: null
Tried calling: modules
[SEVERE] build_web_compilers:entrypoint on web/main.dart:

AssetNotFoundException: angular_github_search|web/main.dartdevc.module
[SEVERE] build_modules:dartdevc on lib/$lib$:

AssetNotFoundException: angular_github_search|.dart_tool/build/generated/angular_github_search/lib/src/github_search_form/github_search_body/github_search_results/github_search_result_item/github_search_result_item_component.module.library
```

**Expected behavior**
A web server running the project

**Logs **
for `flutter analyze`

> Analyzing angular_github_search...
> No issues found! (ran in 52.0s)

`flutter doctor -v` 
> all check are right here 

**Additional context**
Windows 10 Entrerprise LTSC version 1809 (OS build 17763.437)
Dart plugin version 182.5215
 Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

**Comment by felangel** [comment]
Hi @eliaspn 👋 
Thanks for opening an issue and for the positive feedback!

I’ll take a look later today and see if I’m able to reproduce it 👍

**Comment by eliaspn** [comment]
Thanks for responsiveness, since i didn't manage to build Dart in Fedora, in the meantime i'll give it a shot in Ubuntu 19.04

**Comment by felangel** [comment]
No problem! You might want to also try setting up your own angular dart project as described in the [tutorial](https://felangel.github.io/bloc/#/flutterangulargithubsearch?id=angulardart-github-search) and copying over the dart files over. If that works then I’ve missed committing certain files to git.

**Comment by eliaspn** [comment]
Tested in Fedora and it's working !
Probably the compiler resolves the path wrong on windows. 
Proper investigation needs to be made, i think the issue it's somewhere upstream.
