### ISSUE TITLE
[Question] Accessing BLoC in a different route without having to pass it as argument

### ISSUE THREAD

**Issue by diogosequeira94** [felangel/bloc#2311]
I have seen some threads about this situation and although they have been closed I can seem to find the best practice.

Do we have a cleaner solution to make bloc available across screens in named navigation without having to pass the same instance through arguments?

Look at my example below:

Routes:
```
class MyDummyExampleRoutes {
  static MaterialPageRoute onGenerateRoute(RouteSettings settings) {
    final routeName = settings.name;
    final arguments = settings.arguments;
    switch (routeName) {
      case examplePageRoute:
        return MaterialPageRoute(
            builder: (_) => ExamplePageRoute(arguments: arguments));
     default:
        return MaterialPageRoute(builder: (_) => ExamplePageRoute(arguments: arguments));
    }
  }
}
```

Inner Route Class:

```
class ExamplePageRoute extends StatelessWidget {
  final ExamplePageArguments arguments;
  ExamplePageRoute({Key key, this.arguments}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ExamplePage(arguments: arguments);
  }
}
```

Arguments: 

```
class ExamplePageArguments {
  final MyBloc myBloc;
  final String someString;

  ExamplePageArguments({
    this.myBloc,
    this.someString
  });
}

```

In this way I can access the same instance of BLoC I injected in my parent widget in the widget tree. But if I simply try to do a 

`final bloc = BlocProvider.of<MyBloc>(context); `

in screen the screen I navigated to, it will say BLoC is not available in the widget tree.

@felangel can you give your insights? Thanks

**Comment by rodrigobastosv** [comment]
You have two solutions to this @diogosequeira94  problem. The first is to make the Bloc in question accessible throughout the app. Placing a BlocProvider above the MaterialApp, for example. 

The other option you have is to provide the Bloc in question for the screen you are navigating through a BlocProvider.value. Something like the above code:

```
Navigator.push(
   MaterialPageRoute(
       builder: (_) => BlocProvider.value(
           value: BlocProvider.of<MyBloc>(context),
           child: NextScreen(),
       ),
   )
)
```

You can even put this kind of kind on your `onGenerateRoute` to make the code cleaner and more organized.

If I haven't been clear enough, please let me know.

**Comment by narcodico** [comment]
Hi @diogosequeira94 👋

In addition to previous answer, you might also wanna have a look at using a router class as per [documentation](https://bloclibrary.dev/#/recipesflutterblocaccess?id=app-3).

**Comment by diogosequeira94** [comment]
Hi Rodrigo thanks for the fast reply.

I've used that approach and it works in small sized apps, in the case there are different route classes for every feature.

In my case, navigation should look something like this:

```
  void navigateToAnotherPage(BuildContext context) {
    Navigator.of(context).push(
      MyDummyExampleRoutes.onGenerateRoute(
        RouteSettings(
          name: examplePageRoute,
          arguments: ExamplePageArguments(
            myBloc:
                BlocProvider.of<MyBloc>(context),
            someString: someString,
          ),
        ),
      ),
    );
  }
```

in this should I wrap the entire MyDummyExampleRoutes.onGenerateRoute as you suggested?

**Comment by rodrigobastosv** [comment]
Hey @diogosequeira94,

I think this is exactly what @narcodico  is suggesting that you do. Put all your routing logic inside a Router class and call method that handle all routes creation to MaterialApp, it's the parameter called onGenerateRoute of MaterialApp. 

This would considerably decrease the complexity of your code.

**Comment by diogosequeira94** [comment]
Thanks guys, haven't seen the reply before answering. I was looking for a way to keep all that bloc injection logic inside the Router class and I believe that suggestion will help me.

Cheers !
