### ISSUE TITLE
BlocProvider in ListView's item doesn't update

### ISSUE THREAD

**Issue by yerkejs** [felangel/bloc#2313]
Every list view's item's parent is a BlocProvider. Issue here is that when I add new item to the list view blocProvider does not move, it does not change its index. For instance, first elements bloc becomes automatically becomes bloc of the new added item.

That is the list view item's code:

AutoScrollTag(
        key: ValueKey(index),
        controller: chatBloc.scrollController,
        index: index,
        child: isTimeDeletionEnabled ?
          BlocProvider(
            create: (_) => timerCubit,
            child: BlocConsumer<TimerCubit, TimerState> (
              listener: (context, timerState) {
                if (timerState.timeLeft == null 
                  || timerState.timeLeft == 0
                ) {
                  chatBloc.add(MessageDelete(ids: [currentMessage.id]));
                  context.read<main_chat_cubit.ChatGlobalCubit>().updateLastMessage(
                    widget.chatEntity.chatId, 
                    state.messages.getItemAt(currentIndex + 1)
                  );
                }
              },
              builder: (context, timerState) {
                return this._buildCellOfMessage(
                  params: messageCellParams(
                    timeLeft: timerState.timeLeft
                  ),
                  chatBloc: chatBloc
                );
              }, 
            )
          ) : currentMessage.chatActions == null ? 
            this._buildCellOfMessage(params: messageCellParams(), chatBloc: chatBloc) :
              ChatActionView(
                chatAction: buildChatAction(currentMessage)
              )

No idea why it does not move to next cell

**Comment by narcodico** [comment]
Hi @yerkejs 👋

Please provide a repository with a minimal reproduction of the issue you're encountering. Thanks!

**Comment by yerkejs** [comment]
okey, thanks @narcodico, now I will create from scratch. But can u answer to one question. Does BlocProvider inside the ListView every time rebuild when new item added ?

**Comment by narcodico** [comment]
With your setup you have one `BlocProvider` per list item which is not common.
Usually you handle a list using a single one.
Do you have any reasons why you feel that you need one per item ?
