### ISSUE TITLE
I can't see Code Actions in the refactor menu with the VSCode extension

### ISSUE THREAD

**Issue by alcarlos1** [felangel/bloc#2314]
I'm new to BLoC, my VSCode ils not working well with the extension.

My refactor Menu : 

![image](https://user-images.githubusercontent.com/71258223/114202666-b1da2480-9957-11eb-86dc-5bf07562e1c3.png)

Expected refactor menu :

![](https://raw.githubusercontent.com/felangel/bloc/master/extensions/vscode/assets/wrap-with-usage.gif)

If someone know  this issue i'll be grateful.
Thanks in advance ! 😊

**Comment by felangel** [comment]
Hi @alcarlos1 👋 
Thanks for opening an issue!

Just to clarify is it only in certain cases that you cannot see the menu or is it all the time? Thanks! 🙏

**Comment by alcarlos1** [comment]
It's all the time, i can't see the bloc part of the menu when my extension is enabled. I've tried to download it again but nothing can repair that :/
Thanks for this help, it will be great if someone can solve this problerm ! 😊

**Comment by ajackson2907** [comment]
I am also experiencing no code actions in the context menu, I can see Bloc: New Bloc and Cubit: New Cubit when right-clicking on a folder name and the code snippets are available in the editor but no sign of the code actions at any time.

bloc Extension for VSCode is 5.6.0
VSCode version is 1.55.2

**Comment by felangel** [comment]
@ajackson2907 thanks for the video and detailed explanation! We'll be sure to include the actions in the refactor menu in the upcoming release 👍

**Comment by felangel** [comment]
This is included in #2474 and will be available in v5.6.1 👍
