### ISSUE TITLE
[Question] Bloc State is yielded but UI is not updating

### ISSUE THREAD

**Issue by shivam-01** [felangel/bloc#2315]
I'm having an issue using bloc. The bloc state is yielded but it seems to be no effect on UI. I have reproduced the issue using an example app. The issue is removing an item from the list page does not change it's color back to deselected state. Actually what happens is When you select an item on home page the cart button appears and on no items selected state it disappears. So when you select an item on homepage the cart button appears. When you click on the button you're navigated to another page i.e. ListPage where you can see the list of all selected items and a remove button corresponding to every item. When you remove an item it gets removed from ListPage but still it's color is Red i.e. selected on HomePage. I have to click again to change the color although it was deselected i.e. (item.active = false) on removing it from the ListPage. Just the color stays the same, it's not getting updated. The code files are given below:

item_bloc.dart

    import 'dart:async';
    
    import 'package:bloc/bloc.dart';
    import 'package:demo/bloc/cart/cart_bloc.dart';
    import 'package:demo/item_model.dart';
    import 'package:demo/repository.dart';
    import 'package:equatable/equatable.dart';
    import 'package:flutter/foundation.dart';
    
    part 'items_event.dart';
    part 'items_state.dart';
    
    class ItemsBloc extends Bloc<ItemsEvent, ItemsState> {
      final ItemRepository itemRepository;
      final CartBloc cartBloc;
    
      ItemsBloc({
        @required this.itemRepository,
        @required this.cartBloc,
      }) : super(ItemsLoading());
    
      @override
      Stream<ItemsState> mapEventToState(
        ItemsEvent event,
      ) async* {
        if (event is GetItems) {
          yield* _mapGetItemsToState(event);
        } else if (event is UpdateItem) {
          yield* _mapUpdateItemToState(event);
        }
      }
    
      Stream<ItemsState> _mapGetItemsToState(GetItems event) async* {
        yield ItemsLoading();
        try {
          final _items = await itemRepository.loadItems();
          yield ItemsLoaded(items: _items);
          print('Yielded');
        } catch (_) {
          yield ItemsFailure();
        }
      }
    
      Stream<ItemsState> _mapUpdateItemToState(UpdateItem event) async* {
        try {
          _updateRepositoryItems(event.item);
          if (event.item.active) {
            cartBloc.add(ShowItems());
          } else {
            cartBloc.add(RemoveItem(itemId: event.item.id));
          }
          yield* _mapGetItemsToState(GetItems());
        } catch (_) {
          yield ItemsFailure();
        }
      }
    
      Item _updateRepositoryItems(Item item) => itemRepository.setItem = item;
    }

item_state.dart

```
part of 'items_bloc.dart';

abstract class ItemsState extends Equatable {
  const ItemsState();

  @override
  List<Object> get props => [];
}

class ItemsInitial extends ItemsState {}

class ItemsLoading extends ItemsState {}

class ItemsLoaded extends ItemsState {
  final List<Item> items;

  ItemsLoaded({@required this.items});

  @override
  List<Object> get props => [items];
}

class ItemsFailure extends ItemsState {}
```

cart_bloc.dart

    import 'dart:async';
    
    import 'package:bloc/bloc.dart';
    import 'package:demo/item_data_model.dart';
    import 'package:demo/repository.dart';
    import 'package:equatable/equatable.dart';
    import 'package:flutter/foundation.dart';
    
    part 'cart_event.dart';
    part 'cart_state.dart';
    
    class CartBloc extends Bloc<CartEvent, CartState> {
      final ItemRepository itemRepository;
    
      CartBloc({@required this.itemRepository}) : super(CartLoading());
    
      @override
      Stream<CartState> mapEventToState(
        CartEvent event,
      ) async* {
        if (event is ShowItems) {
          yield* _mapShowItemsToState(event);
        } else if (event is RemoveItem) {
          yield* _mapRemoveItemToState(event);
        }
      }
    
      Stream<CartState> _mapShowItemsToState(ShowItems event) async* {
        try {
          final _selectedItems = await itemRepository.getSelectedItems;
    
          if (_selectedItems.isNotEmpty) {
            final data = ItemData(items: _selectedItems);
    
            yield CartLoaded(itemData: data);
          } else {
            yield CartLoading();
          }
        } catch (_) {
          yield CartFailure();
        }
      }
    
      Stream<CartState> _mapRemoveItemToState(RemoveItem event) async* {
        try {
          final _selectedSounds = await itemRepository.getSelectedItems;
    
          if (_selectedSounds.isEmpty) {
            yield CartLoading();
          } else {
            yield* _mapShowItemsToState(ShowItems());
          }
        } catch (_) {
          yield CartFailure();
        }
      }
    }

homepage.dart

    import 'package:demo/bloc/cart/cart_bloc.dart';
    import 'package:demo/bloc/items/items_bloc.dart';
    import 'package:demo/item_tile.dart';
    import 'package:demo/list_page.dart';
    import 'package:flutter/material.dart';
    import 'package:flutter_bloc/flutter_bloc.dart';
    
    class HomePage extends StatefulWidget {
      @override
      _HomePageState createState() => _HomePageState();
    }
    
    class _HomePageState extends State<HomePage> {
      @override
      Widget build(BuildContext context) {
        return SafeArea(
          child: Scaffold(
            appBar: AppBar(
              title: Text("Home Page"),
              centerTitle: true,
            ),
            body: Column(
              children: [
                Expanded(
                  child: Padding(
                    padding: const EdgeInsets.all(8.0),
                    child: BlocBuilder<ItemsBloc, ItemsState>(
                      // ignore: missing_return
                      builder: (context, state) {
                        if (state is ItemsLoading) {
                          return Center(
                            child: CircularProgressIndicator(),
                          );
                        } else if (state is ItemsLoaded) {
                          print('Items Loaded');
                          return GridView.count(
                            crossAxisCount: 3,
                            crossAxisSpacing: 20.0,
                            mainAxisSpacing: 20.0,
                            childAspectRatio: 0.6,
                            children: [
                              for (var item in state.items) ItemTile(item: item),
                            ],
                          );
                        } else if (state is ItemsFailure) {
                          return Center(
                            child: Text(
                              'Unexpected Failure, Cannot Load Items',
                              style: Theme.of(context).textTheme.headline6,
                            ),
                          );
                        }
                      },
                    ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: CartButton(),
                ),
              ],
            ),
          ),
        );
      }
    }
    
    class CartButton extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return BlocBuilder<CartBloc, CartState>(
          // ignore: missing_return
          builder: (context, state) {
            if (state is CartLoading) {
              return SizedBox.shrink();
            } else if (state is CartLoaded) {
              print('Cart Loaded');
              return TextButton(
                onPressed: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) {
                      return ListPage(
                        items: state.itemData.items,
                      );
                    }),
                  );
                },
                child: Text('Go To Cart'),
              );
            } else if (state is CartFailure) {
              return Center(
                child: Text(
                  'Unexpected Failure, Cannot Load Cart',
                  style: Theme.of(context).textTheme.headline6,
                ),
              );
            }
          },
        );
      }
    }

item_tile.dart

    import 'package:demo/bloc/items/items_bloc.dart';
    import 'package:demo/get_it.dart';
    import 'package:demo/item_model.dart';
    import 'package:flutter/material.dart';
    
    class ItemTile extends StatefulWidget {
      final Item item;
    
      const ItemTile({Key key, this.item}) : super(key: key);
      @override
      _ItemTileState createState() => _ItemTileState();
    }
    
    class _ItemTileState extends State<ItemTile> {
      bool active;
    
      @override
      void initState() {
        super.initState();
        active = widget.item.active;
      }
    
      void _onItemTap() {
        setState(() {
          active = !active;
        });
    
        getIt<ItemsBloc>()
            .add(UpdateItem(item: widget.item.copyWith(active: active)));
      }
    
      @override
      Widget build(BuildContext context) {
        return ListTile(
          title: Text(widget.item.title),
          tileColor: active ? Colors.redAccent : Colors.blueAccent,
          onTap: () {
            _onItemTap();
          },
        );
      }
    }

item_page.dart

    import 'package:demo/bloc/items/items_bloc.dart';
    import 'package:demo/get_it.dart';
    import 'package:flutter/material.dart';
    
    import 'item_model.dart';
    
    class ListPage extends StatefulWidget {
      final List<Item> items;
    
      const ListPage({Key key, this.items}) : super(key: key);
      @override
      _PlayerScreenState createState() => _PlayerScreenState();
    }
    
    class _PlayerScreenState extends State<ListPage> {
      @override
      Widget build(BuildContext context) {
        return SafeArea(
          child: Scaffold(
            appBar: AppBar(
              title: Text(
                'Cart List Page',
                style: Theme.of(context).textTheme.headline6,
              ),
              centerTitle: true,
            ),
            body: Padding(
              padding: const EdgeInsets.all(12.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Expanded(
                    child: ListView.separated(
                      itemCount: widget.items.length,
                      separatorBuilder: (BuildContext context, int index) =>
                          Divider(),
                      itemBuilder: (BuildContext context, int index) {
                        return ListTile(
                          trailing: IconButton(
                            icon: Icon(
                              Icons.close_rounded,
                              color: Colors.black,
                            ),
                            onPressed: () {
                              getIt<ItemsBloc>().add(UpdateItem(
                                item: widget.items.elementAt(index).copyWith(
                                    active: !widget.items.elementAt(index).active),
                              ));
    
                              setState(() {
                                widget.items.removeAt(index);
                              });
                              if (widget.items.isEmpty) {
                                Navigator.pop(context);
                              }
                            },
                          ),
                          title: Text(
                            widget.items.elementAt(index).title,
                          ),
                        );
                      },
                    ),
                  ),
                ],
              ),
            ),
          ),
        );
      }
    }

get_it.dart

    import 'package:demo/bloc/cart/cart_bloc.dart';
    import 'package:demo/bloc/items/items_bloc.dart';
    import 'package:demo/repository.dart';
    import 'package:get_it/get_it.dart';
    
    final getIt = GetIt.instance;
    
    Future<void> init() async {
      // Bloc
    
      getIt.registerLazySingleton<CartBloc>(() => CartBloc(itemRepository: getIt()));
    
      getIt.registerFactory(() => ItemsBloc(
            itemRepository: getIt(),
            cartBloc: getIt(),
          ));
    
      // Repository
      getIt.registerSingleton<ItemRepository>(ItemRepository());
    }

main.dart

    import 'package:demo/bloc/cart/cart_bloc.dart';
    import 'package:demo/bloc/items/items_bloc.dart';
    import 'package:demo/get_it.dart';
    import 'package:flutter_bloc/flutter_bloc.dart';
    
    import 'get_it.dart' as di;
    import 'package:flutter/material.dart';
    
    import 'home_page.dart';
    
    void main() {
      WidgetsFlutterBinding.ensureInitialized();
      di.init();
      runApp(MyApp());
    }
    
    class MyApp extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MultiBlocProvider(
          providers: [
            BlocProvider(
              create: (context) => getIt<ItemsBloc>()..add(GetItems()),
            ),
            BlocProvider(
              create: (context) => getIt<CartBloc>(),
            ),
          ],
          child: MaterialApp(
            title: 'Flutter Demo',
            debugShowCheckedModeBanner: false,
            theme: ThemeData(
              primarySwatch: Colors.blue,
            ),
            home: HomePage(),
          ),
        );
      }
    }

Down Here are the images of the issue:
![Screenshot_20210409-012105](https://user-images.githubusercontent.com/68195813/114208044-ab10d900-997a-11eb-91a9-a0b9d045786b.png)
![Screenshot_20210409-012110](https://user-images.githubusercontent.com/68195813/114208049-ac420600-997a-11eb-8304-fce2d746de36.png)

When the app starts it shows in the console as (I/flutter ( 4923): Items Loaded) and when you select an item it shows (I/flutter ( 4923): Cart Loaded). But it does not show ItemsLoaded when an item is removed from the ListPage. 

The line after yield ItemsLoaded in _mapGetItemsToState as print('Yielded') in the Items_bloc file. It is printing that line on removing the item. So the state is yielded but somehow I think bloc is treating the new state with updated items as the previous one and that's why the BlocBuilder function is not called again. First I thought I should create a new State i.e. ItemsUpdated, but it would also create the same problem as the list of updated items would be treated as same. I got no idea how to fix this issue. Help needed please.

**Comment by narcodico** [comment]
Hi @shivam-01 👋

Please share a repository showcasing your issue; it would be a lot easier for you to get help if we could run a sample. Thanks!

**Comment by shivam-01** [comment]
https://github.com/shivam-01/Example-app  -  I have added the example app repository, you can check it. And thanks for replying.

**Comment by narcodico** [comment]
Refactored the important bits in this [PR](https://github.com/shivam-01/Example-app/pull/1).

Important things to remember:
- don't register blocs in getit with `registerFactory` since you'll always get a new instance of your bloc when fetching;
- don't fetch your blocs, repos, etc from get it except when passing them to `create` of `BlocProvider`, `RepositoryProvider`; use `context` to fetch the existing instance from the tree;
- don't keep state in your repositories(I assumed you did that for testing purposes and left it like that);
- a `BlocBuilder` cannot rebuild widgets across routes(if you're gonna pass a list of items coming from a `BlocBuilder` in route A to a new route B, that list will remain unchanged in route B even if it's updated in route A).

Hope that helps!

**Comment by alexgrusu** [comment]
@narcodico , in regards to your second statement, how would you suggest to proceed in this case?
In my example I use very often
```
getIt<InAppPurchasesBloc>()
        .add(const InAppPurchasesEvent.getPurchaserInfo());
```

Also, I encounter a similar issue with the following example. The BlocListener does not react to state changes.
```
class MusicTab extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    getIt<InAppPurchasesBloc>()
        .add(const InAppPurchasesEvent.getPurchaserInfo());
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        BlocProvider(
          create: (context) => getIt<CheckAvailabilityBloc>(),
          child: MusicCardsGrid(getMusicCards()),
        ),
      ],
    );
  }
}
```

```
class MusicCardsGrid extends StatelessWidget {
  final List<MusicCardContent> musicCards;

  const MusicCardsGrid(
    this.musicCards,
  );

  @override
  Widget build(BuildContext context) {
      return BlocListener<CheckAvailabilityBloc, CheckAvailabilityState>(
      listener: (context, state) {
        print('state changed: ${state.toString()}');

        state.availabilityFailure.map(
          none: (_) {},
          inMaintenance: (_) {},
          networkUnavailable: (_) {
            showAlertDialog(
              context,
              musicAlertTitle,
              musicAlertMessage,
            );
          },
          ready: (_) {
            context.router.push(
              MusicPlayerPageRoute(
                card: musicCards.elementAt(state.index!),
              ),
            );
          },
        );
      },
      child: Consumer<InAppPurchasesData>(
        builder: (context, data, child) {
          return AnotherWidget();
        },
      ),
    );
  }
}
```

**Comment by narcodico** [comment]
> in regards to your second statement, how would you suggest to proceed in this case?

You use the `context` to fetch an existing provided instance, e.g.:
```
context.read<InAppPurchasesBloc>()
        .add(const InAppPurchasesEvent.getPurchaserInfo());
```

You should never add events directly inside `build` methods since they will be randomly added each time your widget rebuilds.
One small step for 
```diff
class MusicTab extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
-   getIt<InAppPurchasesBloc>()
-        .add(const InAppPurchasesEvent.getPurchaserInfo());
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        BlocProvider(
          create: (context) => getIt<CheckAvailabilityBloc>(),
          child: MusicCardsGrid(getMusicCards()),
        ),
      ],
    );
  }
```
As for your listener issue, probably you're registering `CheckAvailabilityBloc` as a factory instead of lazy singleton or singleton in get it, thus you're dealing with 2 instances of your bloc, one received when creating your `BlocProvider` and one received when adding the event. So the one which receives the event is not the same with the one which is retrieved from the tree by the `BlocListener`, thus it doesn't react to your state changes.

Doing:
```
context.read<CheckAvailabilityBloc>()
                      .add(CheckAvailabilityEvent.checkAvailability(index));
```
 should fix your issue. Also, register your blocs as `lazySingleton`.

**Comment by shivam-01** [comment]
Thank you so much @narcodico 
The project worked and issue is gone now. And thanks for the above mentioned points. Just one more doubt. Could you explain your third point -  (don't keep state in your repositories.) I'm unable to understand what it means.

**Comment by alexgrusu** [comment]
@narcodico , greetings, thank you, you're right.

I use to mark the Blocs with @injectable that by default registers as a factory.
```dart
<del>@ingectable
class CheckAvailabilityBloc
    extends Bloc<CheckAvailabilityEvent, CheckAvailabilityState> {
  final ICheckAvailabilityRepository _checkAvailabilityRepository;

  CheckAvailabilityBloc(this._checkAvailabilityRepository)
      : super(CheckAvailabilityState.initial());
```
I registered my bloc like so and seems to be ok
```dart
@module
abstract class FlutterBlocsInjectableModule {
  @lazySingleton
  CheckAvailabilityBloc get checkAvailabilityBloc =>
      CheckAvailabilityBloc(GetIt.instance());
}
```
I used to call 
```dart
getIt<InAppPurchasesBloc>()
       .add(const InAppPurchasesEvent.getPurchaserInfo());
```
because I would like to trigger this event every time when the tab is changed. As far as I can see the onTap member of the BottomNavigationBar requires a function with an integer param. Therefore, I can't pass the context inhere so that to trigger the before build.

**Comment by narcodico** [comment]
@shivam-01 repositories are meant to be an interface between data providers and blocs; they're not meant to store state data or state because data comes from your data providers and state is meant to be stored in blocs' states.

@alexgrusu you're inside `build` method so of course you can access the `context`. Simply do:

```
onTap: (index) {
          context.read<InAppPurchasesBloc>().add(
                const InAppPurchasesEvent.getPurchaserInfo(),
              );
        },
```

**Comment by alexgrusu** [comment]
Obviously, thank you. I parsed a reference to the function that must be called and avoided this approach.
Kind regards.

**Comment by shivam-01** [comment]
@narcodico as you said repositories are meant to be an interface between data providers and blocs. I got it, but in my main app (it's basically a music app), I'm just loading data stored in assets folder from a json file in assets which contains all the details about data. So in that case repository class loads the data using `rootBundle.loadString` method and I save them in two class variables `categories` and `sounds`. Then the bloc retrieves data from those two variables and then updates them if there's some updates in UI part. It's similar to the example app you fixed just with a variety of data. So in my case repositories are holding data and state so is that a wrong approach?? As you told data comes from your data providers, So in my case I can't call `rootBundle.loadString` every time when bloc requests to fetch data. What would you suggest in this case?? If I shouldn't store data and state in repositories and can't call the data provider every time then where to store the data while the app is running in memory?

**Comment by narcodico** [comment]
@shivam-01  I would advice you to have a single source of truth for your data, which in your case is your json file; storing data in memory can lead to losing it, so I wouldn't advice you to store it anywhere after you read it. You should read from and save changes to the json file or even better, some database.
Don't get me wrong, you could definitely cache it locally but that would need a more complex approach which would make sure you changes will always get saved, so a strong persistence is needed anyway.
I guess is up to your requirements to choose the right approach for you.

**Comment by alexgrusu** [comment]
@narcodico I would like to ask you one more question.

Is it possible to access the context in didChangeAppLifecycleState?

```dart
void didChangeAppLifecycleState(AppLifecycleState state)
```

Thank you in advance!

**Comment by narcodico** [comment]
@alexgrusu you are mixin in `WidgetsBindingObserver` on a state class so `context` is available even in the overrides like `didChangeAppLifecycleState` since they are part of the state class.

For future off topic questions I'd kindly ask you to join our [discord](https://discord.gg/bloc) where we have a channel specific for this, as we try to keep the issues bloc related. Thanks!
