### ISSUE TITLE
[Question] Bloc state for different types

### ISSUE THREAD

**Issue by NikitaEfim** [felangel/bloc#2316]
Hello! I need your advice, in my app I have a screen for addresses. There is a request  to create an address (`AddressState.success(Address address)`) and also to get all addresses (`AddressState.success(AddressesResponse addressesResponse)` ???).

And here I have a question: how to use one AddressBloc for this? Should I create one more Success State for AddressesResponse or add it as second parameter to success? What is the best way to do it?

```
enum AddressStatus { unknown, processing, success, failure, cancel }

class AddressState {
  const AddressState({this.status = AddressStatus.unknown, this.address});

  const AddressState.unknown() : this();

  const AddressState.processing() : this(status: AddressStatus.processing);

  const AddressState.success(Address address) : this(status: AddressStatus.success, address: address);
  // Another success State for AddressesResponse ???
  
  const AddressState.failure() : this(status: AddressStatus.failure);

  final AddressStatus status;
  final Address address;
  // final AddressesResponse addressesResponse;
}
```

**Comment by NikitaEfim** [comment]
Is something like this OK?

```
const AddressState.success(Address address)
      : this(status: AddressStatus.success, address: address);

const AddressState.successAddresses(AddressesResponse addressesResponse)
      : this(status: AddressStatus.success, addressesResponse: addressesResponse);
```

**Comment by narcodico** [comment]
Hi @NikitaEfim 👋

Those seem like 2 different features(one is displaying a list of addresses and the other one is creating a new address), so I'd suggest using 2 separate blocs.

**Comment by NikitaEfim** [comment]
> Hi @NikitaEfim 👋
> 
> Those seem like 2 different features(one is displaying a list of addresses and the other one is creating a new address), so I'd suggest using 2 separate blocs.

Ok, thanks

Can I have one more question? If I have an app in which there are many pages and requests, then what is better - to create all the blocs in main.dart class at once, or still create them as needed?

**Comment by narcodico** [comment]
I'd advise you to think in terms of features rather than pages and requests. You should create a bloc per feature and provide it as lower as possible in the widget tree while also having it available to all the widgets needing it.

**Comment by NikitaEfim** [comment]
Thanks!
