### ISSUE TITLE
Tabbar and Bloc

### ISSUE THREAD

**Issue by mehrdad78** [felangel/bloc#2319]
Hi there!
I have a Tabbar with 3 tabs in my app.
there is some Textfields in each tab.
i define some Texteditingcontroller in cubit class to use in each tab.
my question is where i should call dispose method for them?

**Comment by narcodico** [comment]
Hi @mehrdad78 👋

`TextEditingController`s are UI related and shouldn't be used in cubits/blocs.
You should initiate and dispose of them in a state class of a `StatefulWidget`.

Alternatively you can make use of the `onChanged` callback of `TextField`s to call cubit methods or add bloc events.
Have a look at this complete [example ](https://github.com/felangel/bloc/tree/master/examples/flutter_form_validation) for a more advanced use case including validation too.

Hope that helps!

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions or [join the bloc discord](https://discord.gg/bloc) 👍
