### ISSUE TITLE
[Feature Request] Listening changing field of state

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2321]
To update state nowadays in bloc **emit()** function or yield in **mapEventToState** are used.
But sometimes, it does not cost to change the whole state by creating a new object of state and emit it (f.e. if we have a state in which fields are nested objects and we need only change one field of nested object state).

My solution:
Create a listener in the bloc which lives until the bloc dispose of.

```
Stream<State> stateListener();

//or 

void stateListener();
``` 
where we can there depending on the **state** changes update UI.

Why it is useful?

We do not need to create new events to change one field and call ```context.read<Bloc>().add(BlocEventChangedText(text))``` or ```context.read<Cubit>.changeText(text)```.  Some features request many f.e text field where we pass value to our state which making boilperate code.

**Comment by PlugFox** [comment]
listenWhen & buildWhen

**Comment by II11II** [comment]
Buildwhen and listenwhen are not applicable in my scenario.

**Comment by PlugFox** [comment]
> Buildwhen and listenwhen are not applicable in my scenario.

`bloc.whereType<T>().where((s) => ...).listen((s) => ...);`

**Comment by II11II** [comment]
> To update state nowadays in bloc **emit()** function or yield in **mapEventToState** are used.
> But sometimes, it does not cost to change the whole state by creating a new object of state and emit it (f.e. if we have a state in which fields are nested objects and we need only change one field of nested object state).
> 
> My solution:
> Create a listener in the bloc which lives until the bloc dispose of.
> 
> ```
> Stream<State> stateListener();
> 
> //or 
> 
> void stateListener();
> ``` 
> where we can there depending on the **state** changes update UI.
> 
> Why it is useful?
> 
> We do not need to create new events to change one field and call ```context.read<Bloc>().add(BlocEventChangedText(text))``` or ```context.read<Cubit>.changeText(text)```.  Some features request many f.e text field where we pass value to our state which making boilperate code.
> 
> 

    @PlugFox thanks this what i want)
