### ISSUE TITLE
Having trouble with dispatching LoadData event when [ socket event is dispatched from the node js server ]

### ISSUE THREAD

**Issue by JoeMartin2001** [felangel/bloc#2322]
Hi beautiful people! 

I have a node js server which is using socket io. I have got two apps. One for waiter and one for kitchen. I want to refresh orders page of the kitchen app when *new_order* event is emitted from the server. My socket code is the following:

```
        socketService.socket.on(
          'createOrder',
              (data) async* {
            yield OrderLoadedState(loadedOrders: _loadedOrderList);
          },
        );
```

I have been trying to resolve it for a couple of days now and have thought about doing it in a number of ways:
1. I have solved it by putting the above inside the build method of my widget:
```
  @override
  Widget build(BuildContext context) {
    
    socketService.socket.on(
      'createOrder',
          (data) {
            OrderBloc(orderRepo: _orderRepo).add(OrderLoadEvent())
          }
    );
    
    return BlocProvider<OrderBloc>(
      create: (context) => OrderBloc(orderRepo: _orderRepo)..add(OrderLoadEvent()),
      child: Scaffold(
        body: BlocBuilder<OrderBloc, OrderState>(
          builder: (BuildContext context, state) {
            if (state is OrderLoadingState) {
              return Text('Loading');
            }.........
```
It is working fine. But later I found out that this approach might slow down my app, since heavy process is not allowed inside builder method. 

2. I thought about moving the socket code into Bloc itself. But I could not know how to dispatch Bloc event from inside itself. 
3.  I have tried analyzing other flutter bloc widgets, too. After I was adviced to read the documentation, I have known about purpose of all those widgets. But I think none of them suit my needs. Cuz their purpose is different. 

Now the question is where should I place my code(socket code) to call LoadEvent after emitting new event from my server?

**Comment by dawidd6** [comment]
I would advise putting 

```dart
socketService.socket.on(
      'createOrder',
      (data) => add(OrderLoadEvent()),
);
```
in bloc constructor.

**Comment by JoeMartin2001** [comment]
OrderBloc({@required this.orderRepo})
      : assert(orderRepo != null),
        super(OrderLoadingState());

in here?

**Comment by JoeMartin2001** [comment]
So, I am supposed to be using this logic inside bloc class, which I though was the correct way of doing :) But where should I put it? This is my bloc class:
```
class OrderBloc extends Bloc<OrderEvent, OrderState> {
  final SocketService socketService = injector.get<SocketService>();

  final OrderRepo orderRepo;

  OrderBloc({
    @required this.orderRepo,
  })
      : assert(orderRepo != null),
        super(OrderLoadingState());

  @override
  Stream<OrderState> mapEventToState(
    OrderEvent event,
  ) async* {
    if (event is OrderLoadEvent) {
      yield OrderLoadingState();
      try {
        final List<Order> _loadedOrderList = await orderRepo.getAllOrders();
        yield OrderLoadedState(loadedOrders: _loadedOrderList);
      } catch (e) {
        print(e);
        yield OrderErrorState();
      }
    }
  }
}
```

**Comment by dawidd6** [comment]
> in here?

Yes. In constructor's body.

**Comment by JoeMartin2001** [comment]
I have put my code inside contructor of the bloc. But constructor runs only once. Socket should listen to events continuously

**Comment by dawidd6** [comment]
And it will because you register those callbacks to selected events. I think that's the correct approach here as I guess you use socket.io client.

**Comment by JoeMartin2001** [comment]
Sure

**Comment by JoeMartin2001** [comment]
It is that difficult to use socket with bloc?

**Comment by JoeMartin2001** [comment]
I have no idea what I can do

**Comment by felangel** [comment]
Hi @JoeMartin2001 👋 
Thanks for opening an issue!

Ideally, blocs should not be directly interacting with low level networking clients. I would recommend creating a data provider which abstracts the websocket client functionality and then you can use the data provider in one or more repositories and expose a `Stream` which one or more feature blocs can subscribe and react to. From the bloc's perspective it is just listening to a stream of data and the fact that it's coming from a web socket should not really matter. You can refer to [this example](https://github.com/felangel/bloc/blob/2ded25a760aa299c804752500a141eef7692cd7b/examples/flutter_bloc_with_stream/lib/bloc/ticker_bloc.dart#L24) for a reference.

Hope that helps! 👍 

Closing for now but feel free to comment with additional questions or join the [bloc discord](https://discord.gg/bloc).

**Comment by JoeMartin2001** [comment]
Thaks :)
