### ISSUE TITLE
How can we persist  list in hydrated bloc

### ISSUE THREAD

**Issue by maheshbhattaraai** [felangel/bloc#2324]
I want to store list of data in hydrated bloc how can i implement this. I have list of model from API, these data should be persistent for next time. How can i achieve this type of persistent with hydrated_bloc.

**Comment by JoeMartin2001** [comment]
https://www.youtube.com/watch?v=L5QinDY7nKE&list=PLptHs0ZDJKt_T-oNj_6Q98v-tBnVf-S_o&index=12

i advice to watch this tutorial or read about hydrated bloc from the documentation

**Comment by JoeMartin2001** [comment]
https://github.com/felangel/bloc/blob/master/packages/hydrated_bloc/README.md

**Comment by narcodico** [comment]
Hi @maheshbhattaraai 👋

Your model needs to implement `fromJson` and `toJson` methods that you can use in the same methods of your hydrated bloc to define how your state is persisted and restored. 

Hope that helps!

**Comment by felangel** [comment]
Hi @maheshbhattaraai 👋 
Thanks for opening an issue!

Closing this for now but if you have additional questions feel free to join the [bloc discord](https://discord.gg/bloc) 😄

**Comment by maheshbhattaraai** [comment]
This is fromJson file in which homeLoadedState is List<T>

      HomeState fromJson(Map<String, dynamic> json) {
        try {
          final homeLoadedState = json['value']
          return HomeLoadedState(homeLoadedState);
        } catch (_) {
          return null;
       }
     }

This is my toJson function of bloc.

  
 
     Map<String, dynamic> toJson(HomeState state) {
       if (state is HomeLoadedState) {
            final post = state;
            return {'value': post};
       } else if (state is HomeInitial) {
          return {};
       } else {
          return null;
       }
    }

which is causing issue in console is

**Unhandled Exception: Unhandled error Unhandled error Converting object to an encodable object failed: Instance of 'HomeLoadedState' occurred in Instance of 'HomeBloc'**

I am trying to implement if network connection is not available need to load previously loaded data.
Thank You.

**Comment by felangel** [comment]
Hi @maheshbhattaraai you need to make sure you are actually storing valid json objects. In this case `post` is not valid json. I would recommend using something like [json_serializable](https://pub.dev/packages/json_serializable) to handle automatically converting your state to/from json.

**Comment by maheshbhattaraai** [comment]
Hi @felangel  thank you for your reply. But mentiond `post` is `List<T>`, i have to convert this list to json?

**Comment by felangel** [comment]
@maheshbhattaraai no problem! You'll need to adjust the generic like:

```dart
abstract class Mappable {
  Map<String, dynamic> toJson();
  factory Mappable.fromJson(Map<String, dynamic> json);
}

class MyState<T implements Mappable> {
  final List<T> posts;
  ...
}
```

Hope that helps 👍

**Comment by 1Krishna16** [comment]
Where you actually able to persist the list using hydrated bloc ? can i have a example code please

**Comment by 1Krishna16** [comment]
> I want to store list of data in hydrated bloc how can i implement this. I have list of model from API, these data should be persistent for next time. How can i achieve this type of persistent with hydrated_bloc.

Where you able to achieve this?

**Comment by JavascriptMick** [comment]
Here you go.. this kind of works...
```
import 'package:hydrated_bloc/hydrated_bloc.dart';

class TodosCubit extends HydratedCubit<List<Todo>> {
  TodosCubit() : super([]);

  //...methods

  //HydratedCubit overloads
  @override
  List<Todo>? fromJson(Map<String, dynamic> json) {
    final todos = json['todos'] as List<dynamic>;
    final list = todos.map((e) => Todo.fromJson(e)).toList();
    return list;
  }

  @override
  Map<String, dynamic>? toJson(List<Todo> state) {
    return {'todos': state.map((e) => e.toJson()).toList()};
  }
}
```

and this is the Todo Class (note that fromJson and toJson use Map<String,dynamic>
```
class Todo {
  final int userId;
  final int id;
  final String title;
  final bool completed;

  Todo({
    required this.userId,
    required this.id,
    required this.title,
    required this.completed,
  });

  factory Todo.fromJson(Map<String, dynamic> json) {
    return Todo(
      userId: json['userId'],
      id: json['id'],
      title: json['title'],
      completed: json['completed'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'userId': userId,
      'id': id,
      'title': title,
      'completed': completed,
    };
  }
}
```
