### ISSUE TITLE
Managing only one state for bloc

### ISSUE THREAD

**Issue by quantosapplications** [felangel/bloc#236]
Is considered a good approach to manage only one kind of state in a single bloc?

In your example a list bloc will have three states:
Uninitialized, loaded and error like your infinite list example.

What about using instead only one state, say eg. “ListState” with some variables that tell me about the internal state of the bloc?

Eg 

Class ListState {  
bool isLoading;
bool isOnError;
List<Post> posts;

.....

 }

I know that the transition will be fired so it’s working from a technical point of view. 
I was just wondering if it’s correct from the library point of view because i think this way it’s more similar to a redux approach which i’m using in different projects.

Thank you

**Comment by felangel** [comment]
Hey @quantosapplications 👋 
Thanks for opening an issue!

Regarding your question, the bloc library is not opinionated about how to manage events/states so it's totally up to you. With that being said, I would recommend the following:

Ask the question: "is it possible for x, y, and z to happen at the same time?"
In the above example, if it's not possible to be loading, have an error, and have posts at the same time then I would recommend separating them into separate states. 

```dart
abstract class MyState {}

class Loading extends MyState {}

class Error extends MyState {}

class Loaded extends MyState {
  final posts;
  Loaded(this.posts);
}
```

If it is possible, then I would recommend keeping them as part of the same state.
```dart
class MyState {
  bool isLoading;
  bool isError;
  List posts;
}
```

Hope that helps! 👍

**Comment by quantosapplications** [comment]
Thanks @felangel I'm gaining some experience in using bloc.
I'm confused about state transition and I would like to ask you taking the flutter_infinite_list example:
if I receive an error during a fetch post event I then go to an error state.
When I'm in an error state I lost all posts fetched before that state and if I put a button to try fetch posts again I start from zero. 
That's why  I asked you to maintain only one state with both posts and an error flag.

Which is the right way for you to manage this kind of situation?

Thank you,
Fabrizio

**Comment by felangel** [comment]
@quantosapplications no problem! It depends on how the feature is supposed to function. In your case, it makes sense to add the error property to the same state because you can have an error and still retain the posts. The second snippet I shared above is what I would use for this use-case. 

Hope that helps 👍
