### ISSUE TITLE
[QUESTION] Why is Immutable state chosen for bloc?

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2374]
Why is state of bloc should immutable but not mutable?
 If there are huge states and only one field of huge state should be changed, the huge state must be recreated, so it speeds down from my point of view

P.s. I know how bloc do a comparison of state

**Comment by narcodico** [comment]
Hi @II11II 👋

Bloc uses value equality to compare states in order optimize state emissions, thus the number of rebuids, thus performance. 
Equality and hashcode of an object is determined when the object is instantiated. 
Later on mutations have no impact in determining the value equality so precisely that is why new instances are required.

**Comment by II11II** [comment]
Does it mean that the bloc library prevents fake updating UI?

**Comment by II11II** [comment]
Recreating new instance will not slow app?

**Comment by narcodico** [comment]
> Does it mean that the bloc library prevents unnecessary updating UI?

Yes.



> Recreating new instance will not slow app?

The amount of time it takes to create a new object is insignificant in terms of performance, so no.

**Comment by II11II** [comment]
@narcodico  Thank you
