### ISSUE TITLE
Accessing Blocs at various Pages inside app

### ISSUE THREAD

**Issue by Himanshu081** [felangel/bloc#2377]
I am new to bloc, can some help me,

Firstly i am initializing all the required blocs at Starting Phase of my app and passing them to ProjectListPage(HomePage of my App).
![image](https://user-images.githubusercontent.com/49179641/114477075-34ddd200-9c19-11eb-868a-016e4ed27807.png)

now I want to access the UserProjectPostCubit inside AddScreen Page which has to be accessed via a UserProjectScreen.

I am already passing UserProjectCubit inside UserProjectScreen using CubitProvider.value:::
![image](https://user-images.githubusercontent.com/49179641/114477487-e1b84f00-9c19-11eb-9862-ef838a0f7a57.png)

So now i am confused how to pass  UserProjectPostCubit  to Add Screen ..can anyone help me?  The AddScreen has to acccesed via UserProjectScreen.

UserProjectScreen Code Snippet ,by clicking add project Buttton i go to AddScreen where i need to access the  UserProjectPostCubit::
![image](https://user-images.githubusercontent.com/49179641/114478226-65bf0680-9c1b-11eb-8eb3-00bb53d030ed.png)

**Comment by felangel** [comment]
Hi @Himanshu081 👋 
Thanks for opening an issue!

I highly recommend checking out [the bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=anonymous-route-access). You will need to make sure the bloc/cubit is provided to your route via `BlocProvider.value` and then you should be able to access it via `context.read<UserProjectCubit>()`.

Hope that helps 👍
