### ISSUE TITLE
Recommended approach when having a complex workflow

### ISSUE THREAD

**Issue by gbaccetta** [felangel/bloc#2379]
Hello There,

I must really thank you for this amazing library. I'm starting a personal project that aim to build a quite complex app from scratch all based on bloc.
Since I'm starting more complex bloc I found out I have two ways of yielding states that seems to me almost equivalent.
Let's say I have a bloc that manage a user group.
If I add a leaveGroup event I have two possible way of implementing the workflow:
- directly yielding the success or failure
- adding a leaveGroupSucceeded or failureEvent: 
The only advantage of the second solution seems to be the fact that I can also trigger the event elsewhere in my project.

``` Dart
Stream<GroupState> _mapLeaveGroupToState(LeaveGroup event) async* {
    yield Loading();
    final leave = await _groupRepository.leaveGroup(
      group: event.groupId,
      user: event.userId,
    );
    if (leave.isLeft()) {
        yield Failure();
      },
     if (leave.isRight()) {
        yield GroupLeft();
      },

  }
```

``` Dart
Stream<GroupState> _mapLeaveGroupToState(LeaveGroup event) async* {
    yield Loading();
    final leave = await _groupRepository.leaveGroup(
      group: event.groupId,
      user: event.userId,
    );
    leave.fold(
      (failure) => add(FailureEvent(failure));
      },
      (_) => add(LeaveGroupSucceeded()) ,
    );
  }
```

maybe it is not the best functional example, but I was only aiming to illustrate my doubt.

Again thank you for the wonderful job done with this package.

**Comment by narcodico** [comment]
Hi @gbaccetta 👋

If you also need to add the event from outside the bloc or simply you can improve the bloc implementation by reusing the event, then definitely the second approach is the way to go; basically creating an event make things more reusable and keeps your code DRY.

If your logic is more like a one time thing, then you can improve upon first approach with:
 ```
 Stream<GroupState> _mapLeaveGroupToState(LeaveGroup event) async* {
    yield Loading();
    final leave = await _groupRepository.leaveGroup(
      group: event.groupId,
      user: event.userId,
    );
    yield leave.fold(
      (failure) => Failure(),
      (_) => GroupLeft(),
    );
  }
 ```
 
 Hope that helps!

**Comment by gbaccetta** [comment]
@narcodico thank you very much. So my feeling was right about them. I had the doubt one of the implementation had some flow I could not see.

Thanks for the little optimization! I'm still not used to generator function and yield and I wrote it down without too much thinking :-)
