### ISSUE TITLE
Best practices: should I put "inner state" in bloc private fields or in state?

### ISSUE THREAD

**Issue by terekhovyes** [felangel/bloc#2393]
Let's analyze the situation:
- I need to pass Id into bloc to get some `Data`
- Bloc actually have to request `A`, `B` and `C` values to construct `Data` for me
- Any of `A`, `B`, `C` requests may finish with error
- Bloc must support retry, restarting only failed requests
- Let's use some abstract `Loading<X>` structure to indicate Idle/Load/Success/Failure state of `X`

Which approach do you think is better?

### 1. State contains what I need, bloc puts what it need in private fields and construct state for me based on these private fields
```
State {
    Id id
    Loading<Data> data
}

// Events
IdChanged(Id id)
ALoaded(Loading<A> a)
BLoaded(Loading<B> b)
CLoaded(Loading<C> c)
Retry

Bloc {
    Loading<A> _a
    Loading<B> _b
    Loading<C> _c

    mapEventToState(Event event) {
        // start async A, B, C loading on IdChanged
        // update _a/_b/_c fields on ...Loaded
        // restart A/B/C loading on Retry
        // return new state based on current state and _a, _b, _c fields
    }
}
```

### 2. State contains all data bloc need, bloc just provides this data without hiding any implementation details, I have to construct my Data myself using state
```
State {
    Id id
    Loading<A> a
    Loading<B> b
    Loading<C> c
    
    // Maybe calculated property here?
    Data data() { // build Data based on a, b and c }
}

// Events (the same)
IdChanged(Id id)
ALoaded(Loading<A> a)
BLoaded(Loading<B> b)
CLoaded(Loading<C> c)
Retry

Bloc {
    Stream<State> mapEventToState(Event event) {
        // start async A, B, C loading on IdChanged and return new state with a, b, c in Load state
        // restart A/B/C loading on Retry and return new state with a/b/c in Load state
        // update a/b/c in current state on ...Loaded and return this new state
    }
}
```

**Comment by narcodico** [comment]
Hi @terekhovyes 👋

The only situation where storing fields directly in bloc is ok is when they're **final** and they're pretty much used to initialize the initial state.
In your case you should store everything in your state.

**Comment by terekhovyes** [comment]
@narcodico, hi and thank you, it makes sense! 

You answered my direct question: I should put intermediate `A`, `B` and `C` values inside state. But I don't know then, which way is better to get `Data` out of bloc:
1. Calculate `Data` out of bloc - feels wrong, because bloc supposed to do it
2. Put `Data` inside state too - feels wrong, because `Data` calculated with `A`, `B` and `C` which already presented in state, so data become implicitly duplicated, and state become error prone
3. Create "calculated" property in state - feels right for me, because none of data duplicated. But I never did it before and need advice, is it ok or not

**Comment by narcodico** [comment]
If you need the separate incoming data individually then I'd store it on state and have a computed property like you said.
If you only care about the computed value then I'd compute it inside bloc once the requests are completed and store it on state already computed.

**Comment by terekhovyes** [comment]
@narcodico got it, thank you! In my example I implicitly need that separate incoming data in case some of them are finished with error - putting them in state will help to cache successfully loaded data and retry only failed requests.
