### ISSUE TITLE
Wrong `bloc_test` version in migration guide

### ISSUE THREAD

**Issue by zepfietje** [felangel/bloc#2397]
**Describe the bug**
It's not 100% clear to me, but I think the [`v7.0.0` migration guide](https://bloclibrary.dev/#/migration?id=packagebloc_test) shows the wrong version numbers for `bloc_test` (should be `v8.0.0`, right?).

**Comment by felangel** [comment]
Hi @zepfietje 👋 
Thanks for opening an issue!

This should be addressed in #2404 👍
