### ISSUE TITLE
Exposing isClosed property on BlocBase 

### ISSUE THREAD

**Issue by ycherniavskyi** [felangel/bloc#2398]
**Is your feature request related to a problem? Please describe.**

Possible to check that `Bloc` or `Cubit` is closed could be used in some type of long-running handlers to finish their work when their results are redundant.

_Use case example:_
Some event processing executes several external HTTP calls which could be executed for several seconds each. Let's assume that for some reason a user left this page and `Bloc` or `Cubit` is closed. But handler continues to execute external HTTP calls when its results are not necessary anymore.

**Describe the solution you'd like**
Exposing `isClosed` property on `BlocBase`. Implementation is rather trivial:
```dart
bool get isClosed => _stateController.isClosed;
```

**Describe alternatives you've considered**
Currently, this issue could be resolved by implementing `close` method of `BlocBase` and set some instance flag or state flag.

**Comment by Gene-Dana** [comment]
Hi there ! I wonder, would exposing this encourage anti-patterns?

**Comment by ycherniavskyi** [comment]
@Gene-Dana hm, if you could suggest another solution to resolve described use case, it would be greate.
