### ISSUE TITLE
how to emit states by listening to a stream of data

### ISSUE THREAD

**Issue by Simouche** [felangel/bloc#2401]
I have a flutter app, which fetches a list of products from the server (product are related to the user, so the list doesn't change that much) so I'm saving the product lists locally. I'm using moor as a local database inside the application. when the user opens the products list page:

1. I get the latest product creation date.
2. Request data created after that date from the server async.
3. I open a stream from the database to load the local data.
4. When the the server response arrives with new data, I save it to the database, then the database stream will provide that data.

what I tried:

1. yield the stream of data after mapping it, and wrapping its items inside the state:
    The problems I faced here are: - the code right under the stream yield, never gets executed (idk why). - it only work once, 
    means if I exit that page and reopen it (trigger the load product even again), nothing would happen (no state change, no 
    event triggered).

1. listen to the stream of data, and use the emit() method to emit new states.

   this approach worked properly, I achieved what I wanted, but the docs say that the emit() method, should be used for test 
    purposes only, and that states from bloc should be yield only.

the code can be found in [SO question](https://stackoverflow.com/questions/67147549/flutter-bloc-emit-states-by-listening-to-a-stream-of-data).
    I'd appreciate any other solution that satisfies my needs, and that doesn't break any rules set by the docs.

**Comment by felangel** [comment]
Hi @Simouche 👋 
Thanks for opening an issue!

If you're extending `Cubit` then you can use `emit` directly within the `onData` callback; however, if you're extending `Bloc` then you should add an event within the `onData` callback and then handle emitting a new state when that event is added from within `mapEventToState`. You can see an example of this [here](https://github.com/felangel/bloc/blob/2ded25a760aa299c804752500a141eef7692cd7b/examples/flutter_bloc_with_stream/lib/bloc/ticker_bloc.dart#L24).

Hope that helps 👍
