### ISSUE TITLE
caching multiple instances of a bloc with hydratedBloc

### ISSUE THREAD

**Issue by real-john-doe** [felangel/bloc#2402]
I am designing a ticketing system for customer support and want to cache the reply drafts to different tickets. is there a way to achieve this with HydratedBloc ?

**Comment by felangel** [comment]
Hi @real-john-doe 👋 
Thanks for opening an issue!

You should be able to achieve this by overriding the `id` on your `HydratedBloc` instance. This will allow multiple instances of the same HydratedBloc to maintain distinct cached states.

```dart
class MyHydratedBloc extends HydratedBloc<MyEvent, MyState> {
  ...
  @override
  String get id => ticketId;
}
```

Hope that helps 👍

**Comment by real-john-doe** [comment]
Thanks man.Worked perfectly.
