### ISSUE TITLE
[hydrated_bloc] HydratedBloc not working after clear

### ISSUE THREAD

**Issue by andrea689** [felangel/bloc#2407]
**Describe the bug**
Hi, your `HydratedBloc.storage.clear()` calls `box.deleteFromDisk()` that close the box: https://pub.dev/documentation/hive/latest/hive/BoxBase/deleteFromDisk.html

So HydratedBloc no longer works.

I tried `box.clear()` that fix this problem: https://pub.dev/documentation/hive/latest/hive/BoxBase/clear.html

**Comment by hasankarli** [comment]
Hi, I think I have a same issue.

- If user sign out, I called `HydratedBloc.storage.clear()` (My expectation is that all data in cubits connected with hydaretedmixin will be deleted )

- But it didn't work like that. Fetch previous data instead of pulling in new data

**Comment by suha-glal** [comment]
I have the same issue.

**Comment by felangel** [comment]
This should be addressed as part of #2502 and will be available in v7.0.1.

**Comment by miguelangelflores1993** [comment]
@felangel This problem still occurs even in the example project of the official library
