### ISSUE TITLE
What is paste-the-reversed-client-id-from-googleservice-info.plist-here

### ISSUE THREAD

**Issue by huephase** [felangel/bloc#241]
Hello,

What is meaning of below line:
paste-the-reversed-client-id-from-googleservice-info.plist-here

There is no extension with ".plist-here".  There are several files using (info.plist) - which should be updated and how?

Many thanks.

**Comment by felangel** [comment]
Hi @huephase 👋 
Thanks for opening an issue!

You need to copy the `reversed-client-id` that can be found in the `GoogleService-info.plist` into the `info.plist`. Hope that helps 👍

**Comment by huephase** [comment]
Thank you for clarification.

To confirm, the `reversed-client-id` is to be pasted in `info.plist` > under "**Bundle identifier**" key correct?

![image](https://user-images.githubusercontent.com/16631415/56811007-cb583380-6848-11e9-878b-4705e3a704c9.png)

Many thanks.

**Comment by felangel** [comment]
@huephase no it should look something like this:

<img width="490" alt="Screen Shot 2019-04-27 at 12 40 14 PM" src="https://user-images.githubusercontent.com/8855632/56853178-abc51780-68e9-11e9-9880-2354e8d6a71d.png">
