### ISSUE TITLE
Have a question I was hoping you could help me with.

### ISSUE THREAD

**Issue by SApolinario** [felangel/bloc#2414]
I'm working on implementing an authentication flow.  I'm basing the flow on your Firebase Login example.  In that example you store the user object in the AppState after the user has been authenticated.  I understand all that. Thing is at various points throughout the application different aspects of the user may get updated (e.g. user profile picture).

I was wondering what you would recommend in regards to updating the user in the AppState and letting other parts of the application know it's been updated.  I was thinking about having a stream in my UserRepository class that the AppBloc would listen to and then make use of a userUpdatedEvent.  So calling UserRepo.UpdateProfileImage() would then update the stream and notify the AppBloc which would then notify the rest of the application.

Do you have any other suggestions in how I may better do this?  I appreciate any help you can offer. I love your work!

Sam

**Comment by narcodico** [comment]
Hi @SApolinario 👋

When working with firebase you'd probably want to switch the firebase auth stream to a user's document stream, where you'd store advanced user info like the profile picture url. Updates to this document would result in updates to the user on the AppState. You're right to expose this stream through a repository.
You can definitely use `BlocBuilder`s with the `AppBloc` to build different UI parts.
As for other parts I tend to believe you'd need to get the user info once you need it, e.g. for some request, so pushing changes are not needed.
But if you do need it you can always inject your app bloc into other blocs or simply pass user info through events added to other blocs. It all boils down to your requirements.

Hope that helps you!
