### ISSUE TITLE
switchMap doesn't work when merging nonDebounceStream with debounceStream.

### ISSUE THREAD

**Issue by Tkko** [felangel/bloc#2417]
I'm building search page which have 4 states  `Initial` `Loading` `Empty` `Loaded` and 2 Events `SearchEventTyping` `SearchEventInitial`
I want to debounce `SearchEventTyping` but not `SearchEventInitial` I've done that then that I merged those streams and added `switchMap`
but now `SearchEventTyping` event not being cancelled after `SearchEventInitial` is added.
so if I type 'e' and then delete `Bloc` emits `Initial` and than `Loaded` state. 

```
  @override
  Stream<Transition<SearchEvent, SearchState>> transformEvents(
      Stream<SearchEvent> events, transitionFn) {
    final nonDebounceStream = events
        .where((event) => event is SearchEventInitial)
        .asyncExpand(transitionFn);

    final debounceStream = events
        .where((event) => event is SearchEventTyping)
        .debounceTime(Duration(milliseconds: 250))
        .switchMap(transitionFn);

    return debounceStream.mergeWith([nonDebounceStream]);
  }
```

**Comment by narcodico** [comment]
Hi @Tkko 👋

What's the point of having the search initial event and how are you using it ?

**Comment by Tkko** [comment]
> Hi @Tkko 👋
> 
> What's the point of having the search initial event and how are you using it ?

Before user types anything there are recent searched keywords on page let's call it `InitialPage`. so when user deletes keyword I want to show `InitialPage` instantly.
Yeah I can add empty string into Event but separate Event is more readable.

**Comment by narcodico** [comment]
The thing with your approach is that even when you're deleting the last search char, the debounce will be applied.
You should also send the length of the search keyword and based off of that you could skip debouncing when length is 0.

**Comment by Tkko** [comment]
> The thing with your approach is that even when you're deleting the last search char, the debounce will be applied.
> You could make use of the length of the search keyword and based off of that you could skip debouncing when length is 0.
I don't get what's difference between checking  `length` and `class instance`?

**Comment by narcodico** [comment]
You're adding an event only in `onChanged` and you're making sure that when there's no text you're not debouncing that last char deletion.

**Comment by Tkko** [comment]
> You're adding an event only in `onChanged` and you're making sure that when there's no text you're not debouncing that last char deletion.
Could you provide  me sample code?
