### ISSUE TITLE
Possible to get state variables without using BlocBuilder

### ISSUE THREAD

**Issue by esfomeado** [felangel/bloc#242]
I have the following piece of code:

```
class VehicleLoaded extends VehicleState {
  final Vehicle vehicle;

  VehicleLoaded({this.vehicle}) : super([vehicle]);
}
```

Is possible to get the variable **vehicle** without the need for a _BlocBuilder_?

Thanks

**Comment by felangel** [comment]
Hi @esfomeado 👋 
Thanks for opening an issue!

You can access the stream of bloc states via the `state` property like:

```dart
bloc.state.listen((state) {
  // Do stuff with state
});
```

Alternatively, if you just want to know the current state of the bloc you can use the `currentState` property.

```dart
final state = bloc.currentState;
```

Hope that helps! 👍
