### ISSUE TITLE
Best practice for changing from listener state to builder state

### ISSUE THREAD

**Issue by ninoid** [felangel/bloc#2432]
I am working with bloc for one year and acheived some bloc skills, but also a lot of benefits using bloc.
I am wondering what is right way when changing from listener state to builder state without rebuilding stuff.
Example: I have 2 states. BuildUIState and ShowSnackbarWithMessageState.
Page is build with BuildMyUIState but I am listening with listenWhen for ShowSnackbarWithMessageState and showing snackbar to user. After showing Snakcbar with ShowSnackbarWithMessageState, on later event I need to access to BuildMyUIState but current state is ShowSnackbarWithMessageState and can not use previous BuildMyUIState data to continue with.
I know that I can yield BuildMyUIState right after ShowSnackbarWithMessageState but that is overhead and page is rebild without real reason. My question is how I can get access to latest BuildMyUIState when block current state is ShowSnackbarWithMessageState. What is best practice for this kind scenario?
I hope that my quiestion is well formed and clear :)

**Comment by narcodico** [comment]
Hi @ninoid 👋

It looks like you'd need a single state class incorporating both your data and snackbar info.

**Comment by ninoid** [comment]
@narcodico Thanks for support. I was already thinking to implement that for all future blocks :).
Single state approach: state can have one or more listen flags. Eg. showErrorMessage=true flag. When listening I am checking for that flags and shows messages. 
However I will rebuild UI (buildWhen) only if listen flags are not set. Important is when emiting new states to rebuild UI we need to reset all listener flags since if they stay set UI will not rebuild.
I belive this is best way to acomplish single state scenario used for listnening and rebuilding.

**Comment by narcodico** [comment]
I don't think your flags should dictate when the UI should rebuild, but rather your data, e.g.:
`buildWhen: (previous, current) => previous.list != current.list`

**Comment by ninoid** [comment]
@narcodico Yes, correctly. But in case in single state approach when I want to show snackbar then I need also to check state.showSnackbar == false on buildWhen check. Otherwise it will rebuid UI without real reason.
Understand if buildWhen: (previous, current) => previous.list != current.list
But we need to exclude listenWhen scenario in buildWhen check.

**Comment by narcodico** [comment]
You should show snackbars from a `BlocListener` which has nothing to do with conditional building from your data.
I'd advise to read more about `BlocBuilder` and `buildWhen` [here](https://bloclibrary.dev/#/flutterbloccoreconcepts?id=blocbuilder) to understand why my suggestion actually works.
