### ISSUE TITLE
how to structure blocs/repositories sharing functionality to normalize state and keep it DRY?

### ISSUE THREAD

**Issue by RobertHeim** [felangel/bloc#2436]
I use bloc since some months and I still struggle to come up with a good understanding of state modeling with bloc.

Can you please help me design a bloc / repository structure for the following aspects of a social network (profile, friends, news-feed, comments, etc)? 

For example, a REST API provides a "/profile/{userId}" endpoint and the response contains
* complete profile data (depending on visibility preferences and friendship status)
* friendship-status (e.g. `INITIAL`, `PENDING`, `FRIEND`)

And an endpoint "/friends" with response:
* multiple entries each having friend-id, friendship-status, stripped profile data (only displayname and avatar).

The UI provides two screns:
1. View user profile (showing the profile data and the friendship status with according actions (add friend, confirm friend, remove friend, etc))
2. View a list of my friends and friend requests

The screens use the respective API endpoints.

The recommended approach is "bloc per feature". So I have a `profile_repository` with a `profile_bloc` and a `friends_repository` with a `friends_bloc` where each feature fetches (and caches) it's data. This feels odd, because the repositories duplicate state (e.g. the friendship information) and the state architecture isn't DRY. I wonder how I can keep it DRY?

I thought of extracting a "synthetic" `friendship_repository` holding only the friendship-information per user and providing manipulation methods (e.g. confirm a request). **It would not be connected to the API but gets its data pushed in by the other repositories when they query the API** (that feels strange). The other repositories then would not provide the friendship information to the blocs but the blocs would need to use the `friendship_repository` for getting friendship information / methods.

In this scenario the data providers know each other which feels strange, but might be ok-ish in terms of dependency management, because we could always split state into their smallest repository-slices to keep it DRY.

I know that bloc is not redux and violates "single source of truth", but I wonder about what design philosophy I should keep when working with bloc?

Without that "synthetic repository" I would need to let them listen to each other and understand quite a lot of the internal state structure. That gets pretty dirty and complex when dealing with the complexity of a real life app and much more features that also contain friendship information. Can you please elaborate a bit on how you would approach this scenario in terms of modeling state, blocs, and repositories?

**Comment by felangel** [comment]
Hi @RobertHeim 👋 
Thanks for opening an issue!

I would highly recommend creating a single api client in this case:

```dart
class ApiClient {
  Future<ProfileResponse> getProfile(String id) {...}

  Future<FriendsResponse> getFriends() {...}
}
```

Then I would recommend having a `UserRepository` which depends on the `ApiClient` and exposes an abstraction for interacting with the API `getUser`, `getFriends`, etc.

Regarding the bloc layer, I would recommend a single bloc per feature so in this case it might be good to have a `UserProfileBloc`, `FriendsBloc` which each have a dependency on the `UserRepository`. The `UserRepository` can handle exposing a `Stream` of models so that each of the blocs react to changes in realtime without needing to depend on each other.

In my opinion, it's best to have a single data provider per data source, a single repository per domain, and a single bloc per feature. I would also recommend having blocs only depend on one or more repositories and repositories depend on one or more data providers and to avoid inter-bloc, inter-repository, or inter-data provider dependencies.

Hope that helps! Feel free to comment with additional questions or join the [bloc discord](https://discord.gg/bloc) to continue the conversation 👍

**Comment by RobertHeim** [comment]
Thanks for digging into the scenario, @felangel.

I think it is less about the API client layer, but more about the repository layer. From my perspective, the root cause of the described slicing-problem is that APIs typically do not provide state in a normalized fashion. But we learned that state management should be done normalized to be much more predictable.

Let's check if I got your proposed solution right: It uses a single repository for two different features, that have some state they share. By merging the repositories into one, it becomes an "internal problem" of the repository how it internally manages the friendship information, if it is normalized or not etc.

A bloc is only created for a specific view and just gets the newest data from the repository, so they are fine and just depend on a proper interface of the repositories.

Maybe my only problem with this is that the repository internals are too complex now as it handles way to much state slices. So I would want to split it up into sub-implementations - which is basically what I meant by "synthetic repository". 1. profile specific state, 2. friend specific state, but of course they need to interact with each other. If I do not split them up the single repository would still need to deal with the problem of managing in which internal part it keeps the friendship information and where to keep the other stuff (basically it is in charge of normalizing).

An alternative might be to have a layer between the API client and the repositories that are in charge of normalizing state of API responses and put it in the responsible repositories.

What are your thoughts around splitting up repositories that become too big/complex?

**Comment by robsonsilv4** [comment]
Great explanations @felangel. I think it's good to put like similar in architecture section.

How do you use http client? The api or data provider depends directly on http package or you create some abstraction layer?

**Comment by felangel** [comment]
> Great explanations @felangel. I think it's good to put like similar in architecture section.
> 
> How do you use http client? The api or data provider depends directly on http package or you create some abstraction layer?

Thanks! Yeah I’m planning to rewrite the architecture section very soon 👍

I generally just have the data provider depend on http directly.

**Comment by RobertHeim** [comment]
I think the original issue is addressed. We ended up with the repositories providing (data-change-)event streams that the blocs can react to. So the blocs stay slim and just address a specific feature.

I am still unsure what to do about too complex repositories and proper patterns to split them up, but I think that this is domain specific (besides some general software engineering best practices).
