### ISSUE TITLE
[Question] Sorting event queue/stream by a value of the event with transformEvents

### ISSUE THREAD

**Issue by Giuspepe** [felangel/bloc#2441]
Is there an easy way to sort the event queue/stream of a bloc by a value of the event class? E.g. I have a class MyEvent with a int property and the event queue/stream looks like this:

[MyEvent(5), MyEvent(3), MyEvent(7), AnotherEvent(), MyEvent(2), MyEvent(1)]

I want to transform the event queue/stream so that the event with the lowest int property is executed first -> [MyEvent(3), MyEvent(5), MyEvent(7), AnotherEvent(), MyEvent(1), MyEvent(2)]

It should be possible by overriding transformEvents somehow and maybe using an extension of rxdart, but I wasn't able to get it right and would be glad if somebody could help me out. Thanks in advance!

**Comment by narcodico** [comment]
Hi @Giuspepe 👋

I believe you want something around the lines of:

```
 @override
  Stream<Transition<SortEvent, SortState>> transformEvents(
    Stream<SortEvent> events,
    transitionFn,
  ) {
    return events
        .bufferTest((event) => event is BreakEvent)
        .flatMap<SortEvent>((bufferedEvents) async* {
      final sortedEvents = bufferedEvents.whereType<ValueEvent>().toList()
        ..sort((x, y) => x.value.compareTo(y.value));
      yield* Stream<SortEvent>.fromIterable([
        ...sortedEvents,
        ...bufferedEvents.whereType<BreakEvent>(),
      ]);
    }).asyncExpand(transitionFn);
  }
```

**Comment by Giuspepe** [comment]
Hi @narcodico, thank you a lot for your quick help!

**Comment by federicodesia** [comment]
Hi! I have a similar problem.
I'd be glad if @narcodico or someone could help me.

I have the following events:
```
abstract class MyEvent {}

class MyEventA extends MyEvent {}
class MyEventB extends MyEvent {}
class MyEventC extends MyEvent {}
```

And I'm grouping them as mentioned in #3143 to apply an EventTransformer to all events. I am looking for the user to be able to add any type of `MyEvent` in any order, and have them execute in a specific order sequentially after a 5 second debounce time.


Suppose the user enters the following events before the debounce time:
|    1     |    2     |    3     |    4     |    5     |    6     |
|----------|----------|----------|----------|----------|----------|
| MyEventC | MyEventC | MyEventA | MyEventC | MyEventA | MyEventB |

So I want to execute the events in order, taking the last of each type, as follows:
|    5     |    6     |    4     |
|----------|----------|----------|
| MyEventA | MyEventB | MyEventC |


Thanks for everything!
