### ISSUE TITLE
BlocBuilder not getting called after an update, pageview still displays old data

### ISSUE THREAD

**Issue by prakash6491** [felangel/bloc#2444]
In my application am using pull to refresh .after complete pull to refresh I called bloc method. Event, State, API everything working fine. but old data only showing new data not update.

**Comment by felangel** [comment]
Hi @prakash6491 👋 
Thanks for opening an issue!

Can you please share a minimal reproduction sample that illustrates the problem you're facing? I would also recommend taking a look at the [pull-to-refresh implementation](https://github.com/felangel/bloc/blob/f1f0b9fbdd604e42cf0fc8fdafac6197b8e7fea7/examples/flutter_weather/lib/weather/widgets/weather_populated.dart#L25) as part of the [weather example](https://github.com/felangel/bloc/tree/master/examples/flutter_weather).

Hope that helps 👍

**Comment by felangel** [comment]
Closing for now since there is not a reproduction sample
