### ISSUE TITLE
Unexpected behaviour when using Provider + Cubit with constructor

### ISSUE THREAD

**Issue by Danau5tin** [felangel/bloc#2446]
**Describe the bug**
Hey there!

If I use Provider<Foo> in my flutter app, that holds a List<Bar>.. then I do the following with a cubit:

```
final List<Bar> myBigListOfBar = Provider.of<Foo>(context).getList();
BlocProvider<SomeCubit, SomeState>(    
    create: (_) => SomeCubit(myBigListOfBar)..initList()
    child: AWidgetWithListViewThatNeedsCubit())
```

Then inside my `AWidgetWithListViewThatNeedsCubit()` I use the `Provider.of<Foo>(context).addItem(Bar())` to add an item to the list and notify listeners. Well at this point even though the listeners of the provider are notified... and the `myBigListOfBar `is correctlu updated with the new addition included ... the `BlocProvider/SomeCubit()` is not reinstated with the newly updated List<Bar> in it's constructor.

What is the best way to do this? I have thought of a few ways around this but I want to try and be less hacky and more correct.

**To Reproduce**
As above

**Expected behavior**
I wanted the newly updated action list that has comes from the provider to be available in SomeCubit as it is passed into the constructor. However it appears that the BlocProvider does not re-instantiate itself when the widget rebuilds..

**Logs **
```
Analyzing goals_app...

   info - The exception variable 'e' isn't used, so the 'catch' clause can be removed - lib\app\goals\goals_provider.dart:39:28 - unused_catch_clause
   info - Unused import: 'package:goals_app/app/common/models/attainable.dart' - lib\app\goals\widgets\completed_by_goal_date_picker.dart:2:8 - unused_import
   info - Unused import: 'package:provider/provider.dart' - lib\app\goals\widgets\completed_by_goal_date_picker.dart:5:8 - unused_import
   info - Unused import: 'package:goals_app/app/common/widgets/centered_progress_bar.dart' - lib\app\home\home_screen.dart:9:8 - unused_import
   info - Unused import: 'package:goals_app/app/common/widgets/something_went_wrong.dart' - lib\app\home\home_screen.dart:12:8 - unused_import
   info - Unused import: 'package:goals_app/network/api_paths.dart' - lib\app\login_register\auth_screen.dart:7:8 - unused_import

6 issues found. (ran in 10.9s)
```

Flutter Doctor:

```
C:\Users\dan96\Documents\Devo_Work\DEVO_POS\devo_pos\devo_pos>flutter doctor -v
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [Version 10.0.19042.928], locale en-US)
    • Flutter version 2.0.3 at C:\Users\dan96\Documents\flutter_dev\flutter
    • Framework revision 4d7946a68d (7 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\dan96\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31025.194
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.3.2
    • Flutter plugin version 55.1.5
    • Dart plugin version 211.7233

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\dan96\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19042.928]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 90.0.818.51

• No issues found!

```

**Comment by iandis** [comment]
> Then inside my AWidgetWithListViewThatNeedsCubit() I use the Provider.of<Foo>(context).addItem(Bar()) to add an item to the list and notify listeners. Well at this point even though the listeners of the provider are notified... and the myBigListOfBar is correctlu updated with the new addition included ... the BlocProvider/SomeCubit() is not reinstated with the newly updated List in it's constructor.

You should use **BlocProvider.of<SomeCubit>(context).addItem(Bar())** because you're providing **BlocProvider<SomeCubit, SomeState>** to your **AWidgetWithListViewThatNeedsCubit**. Your SomeCubit only accepts value from Foo, and not updating it. So it's SomeCubit 's job to update the value, not Foo.

**Comment by felangel** [comment]
Hi @Danau5tin 👋 
Thanks for opening an issue and sorry for the delayed response. This is working as expected because `BlocProvider` extends `Provider` and the `create` API in `Provider` does not get invoked on each rebuild. Instead, you can think of `create` more like `initState` in that it will only get called when the `BlocProvider` is initially mounted in the widget tree.

As @iandis mentioned, in this case you can add an event to the bloc when the list changes to notify the bloc. Hope that helps 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄
