### ISSUE TITLE
Update docs to match the newest version

### ISSUE THREAD

**Issue by MounirMesselmeni** [felangel/bloc#2448]
Currently [documentation](https://bloclibrary.dev/#/flutterbloccoreconcepts?id=blocbuilder) is still referring to version 6.x as far as I've seen.

Example:

```dart
BlocBuilder<BlocA, BlocAState>(
  cubit: blocA, // provide the local cubit instance
  builder: (context, state) {
    // return widget here based on BlocA's state
  }
)
```

which will not work as `cubit` was removed and should be `bloc`.
I thought about opening a PR for this case but then found out that no update was done to the documentation since version 6.

**Comment by Gene-Dana** [comment]
Thanks for the heads up! We are in the process of updating all the examples first and then the documentation.

**Comment by felangel** [comment]
Hi @MounirMesselmeni 👋 
Thanks for opening an issue!

As @Gene-Dana mentioned we're still in the process of updating all of the docs 👍 
I just updated the flutter_bloc core concepts that you linked to as part of https://github.com/felangel/bloc/commit/f1f0b9fbdd604e42cf0fc8fdafac6197b8e7fea7 but let us know if you find other areas that are outdated. Thanks! 🙏

**Comment by MounirMesselmeni** [comment]
@felangel Thank you!
