### ISSUE TITLE
Using Refresh Indicator

### ISSUE THREAD

**Issue by abinvp** [felangel/bloc#245]
Hi @felangel,

This isn't a bug but I would like to get a suggestion from you on the right way to use refresh indicator. I have my bloc hooked up with the repository. Upon an event, this will call the API and output various states based on the response. The `onRefresh` method of `RefreshIndicator` widget is expecting a `Future` so I can't use the `dispatch` there. Please let me know your suggestion.

Thank you!

**Comment by felangel** [comment]
Hey @abinvp 👋 
Thanks for opening an issue and great question!

You can check out https://felangel.github.io/bloc/#/flutterweathertutorial?id=pull-to-refresh for an example but I need to update the example to manage the completer using BlocListener instead of BlocBuilder.

Hope that helps 👍

**Comment by abinvp** [comment]
My bad. I didn't see that. Thanks much @felangel

**Comment by geegog** [comment]
Hi @felangel 

I am having some issue with my page RefreshIndicator (I am using bloc), as the indicator keeps rolling. It actually work well sometimes. For example, like after I scroll down and new contents are loaded.

I am thinking that the BlocListener is not called every time my Refresh event is triggered.

Here is the link to the page with the list view and RefreshIndicator: https://github.com/geegog/todo_flutter/blob/master/lib/task/pages/all_todo.dart

Here is the link to the bloc: https://github.com/geegog/todo_flutter/blob/master/lib/task/bloc/alltodo/todo_bloc.dart

Please, can you point me in the right direction?

Thank you.

**Comment by RakaAlrian** [comment]
how to stop/hide the loading when the data already loaded?
