### ISSUE TITLE
BlocBuilder force update flag feature request

### ISSUE THREAD

**Issue by RuiChen0101** [felangel/bloc#2457]
In my project, I use bloc to manage state of input field and form, which take changed value and its key as event and preform some compute then yield the state. The problem is, the yield state is always the same and have props type like Map or custom mutable date entity, which brake Equitable and cause UI not update.

Thus, I want to request a feature to add a flag that can bypass the ```oldBloc``` ```currentBloc``` equal check
```
BlocBuilder<SomeBloc,SomeBlocState>(
  bloc: someBloc,
  forceUpdate: true, //add flag
  builder: (BuildContext context, SomeBlocStatestate) {
    //always update
    if()...
  },
),
```

or take ```buildWhen``` result into consider in  ```oldBloc``` ```currentBloc```  equal check so developer can select which state can update without check

Thank you.

**Comment by felangel** [comment]
Hi @RuiChen0101 👋 
Thanks for opening an issue!

Can you provide a bit more context? You can force your bloc to always emit duplicate states by not making the state extend `Equatable`. The bloc does not want to re-emit the same state because logically there is no state change if the state is the same but you as a developer are in full control over how to determine whether or not two states are equal. Let me know if that helps 👍

**Comment by RuiChen0101** [comment]
Thanks for your reply!

I am sorry for miss to mansion that I need ```Equatable``` for unit-test. It took a lots of extra time to compare state in ```expectLater``` without ```Equatable```.
    
 The following is a small example in my project. As you can see, ```AccountSettingFieldChange``` did change the state of form but ```Equatable``` cannot compare ```Map<String, dynamic>```, which let bloc think these two states are the same. I currently  solve this problem by using ```Map.of()``` to force copy the map, and this solution force me to use ```Map``` instead custom mutable date entity like ```UserEntity``` in the example to transfer data in the state.
   
Bloc
```dart
import 'package:bloc/bloc.dart';
import 'package:meta/meta.dart';
import 'package:equatable/equatable.dart';

import 'package:fdtigermaster_app/utility/injector.dart';
import 'package:fdtigermaster_app/entity/user_entity.dart';
import 'package:fdtigermaster_app/backend/auth/login_user.dart';

part 'account_setting_event.dart';
part 'account_setting_state.dart';

class AccountSettingBloc
    extends Bloc<AccountSettingEvent, AccountSettingState> {
  bool _isDirty = false;
  Map<String, dynamic> _data = {};
  AccountSettingBloc() : super(AccountSettingLoading());

  @visibleForTesting
  AccountSettingBloc.test(
      {bool isDirty = false, required Map<String, dynamic> data})
      : this._isDirty = isDirty,
        this._data = data,
        super(AccountSettingLoading());
  @visibleForTesting
  bool get isDirty => this._isDirty;

  @override
  Stream<AccountSettingState> mapEventToState(
      AccountSettingEvent event) async* {
    if (event is AccountSettingInit) {
      yield* this._onInitial();
    } else if (event is AccountSettingFieldChange) {
      yield* this._onFieldChange(event.key, event.value);
    } else if (event is AccountSettingSave) {
      yield* this._onSave();
    }
  }

  Stream<AccountSettingState> _onInitial() async* {
    this._data =
        (await Injector.instance.get<LoginUser>()!.getFullData()).toJson();
    yield AccountSettingFormDisplay(this._data);
  }

  Stream<AccountSettingState> _onFieldChange(String key, dynamic value) async* {
    if (key == 'invoiceTitle' || key == 'businessId') {
      this._isDirty = true;
      this._data['client'][key] = value;
    } else {
      this._isDirty = true;
      this._data[key] = value;
    }
    yield AccountSettingFormDisplay(this._data);
  }

  Stream<AccountSettingState> _onSave() async* {
    if (!this._isDirty) {
      yield AccountSettingFormDisplay(this._data);
      return;
    }
    yield AccountSettingLoading();
    await Injector.instance
        .get<LoginUser>()!
        .update(UserEntity.fromJson(this._data));
    yield AccountSettingFormDisplay(this._data);
  }
}
```

State
```dart
part of 'account_setting_bloc.dart';

@immutable
abstract class AccountSettingState extends Equatable {
  @override
  List<Object> get props => [];
}

class AccountSettingLoading extends AccountSettingState {}

class AccountSettingFormDisplay extends AccountSettingState {
  final Map<String, dynamic> accountData;
  AccountSettingFormDisplay(Map<String, dynamic> accountData)
      : this.accountData = Map<String, dynamic>.of(accountData);

  @override
  List<Object> get props => [accountData];
}
```

Event
```dart
part of 'account_setting_bloc.dart';

@immutable
abstract class AccountSettingEvent extends Equatable {
  @override
  List<Object> get props => [];
}

class AccountSettingInit extends AccountSettingEvent {}

class AccountSettingFieldChange extends AccountSettingEvent {
  final String key;
  final dynamic value;
  AccountSettingFieldChange(this.key, this.value);

  @override
  List<Object> get props => [key, value];
}

class AccountSettingSave extends AccountSettingEvent {}
```

It will be great to add force update feature in bloc which can allow developers use map or custom entity in their state and preserve functionality of ```Equitable```.

Thanks!

**Comment by felangel** [comment]
@RuiChen0101 I would prefer not to do this because logically if the state hasn't changed, then there shouldn't be a need to force the UI to rebuild. You can always add a unique id or timestamp to your state which allows you to still use `Equatable` while being able to cause updates even if the "data" you're holding via the state hasn't changed. You can refer to the [weather example](https://github.com/felangel/bloc/tree/master/examples/flutter_weather) for an example of how this could look. Closing for now but feel free to comment with additional questions or [join the bloc discord](https://discord.gg/bloc) and I'm happy to continue the discussion 👍
