### ISSUE TITLE
How to process events concurrently?

### ISSUE THREAD

**Issue by II11II** [felangel/bloc#2458]
How to process each event concurrently?

**Comment by Gene-Dana** [comment]
HI there ! From what I understand, Bloc processes events in the order they were received. I saw someone with a similar question here on stack, perhaps this may help you https://stackoverflow.com/questions/62624161/flutter-bloc-events-not-happening-in-correct-order

**Comment by felangel** [comment]
Hi @II11II 👋 
Thanks for opening an issue!

As @Gene-Dana mentioned, by default blocs process all events in the order in which they are received. You can change that behavior by overriding `transformEvents`. You can take a look at the [GitHub Search Example](https://github.com/felangel/bloc/blob/c68ce35d7bb1a38b0309bee48ef04b40abf17862/examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart#L21) for reference. Hope that helps 👍

**Comment by II11II** [comment]
Hi 👋, 
Thank you for response, 
I ve found solution
