### ISSUE TITLE
How to manipulate bloc state in Widget Testing?

### ISSUE THREAD

**Issue by SilkeNL** [felangel/bloc#2464]
I am trying to widget test my app and I use bloc on almost every page. I can't seem to understand how to manipulate bloc. I use Mockito to make a Mock of my bloc but I don't understand how to use it.
Is there an example on how to do this? I have tried `when(myBloc.state).thenReturn(LoadingState());` but this doesn't seem to work. I also tried with whenListen.

Can you give an example on how to use the Mock?

This is my page:

    `class ContactScreenMakeBlocProviders extends StatelessWidget {
      @override
      Widget build(BuildContext context) {
        return MultiBlocProvider(providers: [
          BlocProvider<WelcomeBloc>(
            create: (context) => WelcomeBloc()
              ..add(WelcomeLoadRequestEvent(id: '609a88d324a01928242d1ca9')),
          ),
          BlocProvider<ContactBloc>(
            create: (context) => ContactBloc()..add(ContactLoadRequestEvent()),
          ),
        ], child: ContactScreen());
      }
    }`

with the contactScreen:

` Widget build(BuildContext context) {
    return BlocBuilder<ContactBloc, ContactState>(
      builder: (context, state) {
        return BlocBuilder<WelcomeBloc, WelcomeState>(
            builder: (context, _state) {
              if (_state is WelcomeLoadSuccessState) {
                if (state is ContactLoadSuccessState) {
                  return Text('ContactLoad Success);
                }
                if (state is ContactSavedState) {
                  return Text('Contact Save State');
                }
                if (state is ContactSaveFailedState) {
                 return Text('Save Failed');
                }
                if (state is ContactLoadInProgressState) {
                  return Text('Loading in progress');
                }

                return const Text('Error 1');
              }
              return const Text('Error 2');
            });
      },
    );
  }`

The bloc I want to use:

    `class ContactBloc extends Bloc<ContactEvent, ContactState> {
      final ContactService _contactService = localServices<ContactService>();

      ContactBloc() : super(ContactLoadInProgressState());

      Stream<ContactState> mapEventToState(ContactEvent event) async* {
        if (event is ContactLoadRequestEvent) {
          yield* _mapContactLoadRequestEventToState();
        }
        if (event is ContactSaveEvent) {
          yield* _mapContactSavingEventToState(event);
        }
      }

      Stream<ContactState> _mapContactLoadRequestEventToState() async* {
        yield ContactLoadSuccessState();
      }

      Stream<ContactState> _mapContactSavingEventToState(
          ContactSaveEvent event) async* {
        try {
          yield ContactLoadInProgressState();
          final ContactPageReturnClass done = await //returns succeed = true and message = '';

          if (done.succeeded == true) {
            yield ContactSavedState();
          } else {
            yield ContactSaveFailedState(message: done.message);
          }
        } catch (e) {
          print(e);
          yield ContactLoadFailedState();
        }
      }
    }`

My Mock:
    `class MockContactBloc extends Mock implements ContactBloc {}`

**Comment by felangel** [comment]
Hi @SilkeNL 👋 
Thanks for opening an issue!

I highly recommend taking a look at the [weather example tests](https://github.com/felangel/bloc/tree/master/examples/flutter_weather/test) or the [firebase login example tests](https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login/test). The two examples are fully tested and should help address your questions. If you're still having trouble after taking a look at the examples please [join the bloc discord](https://discord.gg/bloc) 👍
