### ISSUE TITLE
Alternative BlocProvider implementation

### ISSUE THREAD

**Issue by andcan** [felangel/bloc#247]
**Is your feature request related to a problem? Please describe.**
`BlocProvider` is implemented as an `InheritedWidget` this doesn't allow correct disposal of blocs.

**Describe the solution you'd like**
An alternative would be the hybrid stateful-inherited as implemented [here](https://gist.githubusercontent.com/boeledi/cb9b933b2e2664ae1ee5cc78b0da273a/raw/221dcc91b1e42913e3f7902acb8b3da779dc4a6f/bloc_provider_new.dart).
This implementation allows correct disposal of blocs while keeping inherited widget performance.

**Comment by felangel** [comment]
Hi @andcan 👋
Thanks for opening this feature request!

Have you checked out https://github.com/felangel/bloc/issues/233?

I think this is a duplicate.
