### ISSUE TITLE
docs[flutter_infinite_list] : invalid code

### ISSUE THREAD

**Issue by RealYoungk** [felangel/bloc#2470]
**Describe the bug**
There is a typo in the official document example code.

**To Reproduce**3
1. Go to 'https://bloclibrary.dev/#/flutterinfinitelisttutorial'
2. Scroll down to 'Post Bloc'
3. See typo

change
PostBloc({required this.httpClient}) : super(const PostInitial());
to
PostBloc({required this.httpClient}) : super(const PostState());

**Comment by Gene-Dana** [comment]
Thanks for opening an issue about this ! Just made the request to update it.
