### ISSUE TITLE
What is the difference usage Between BlocProvider and RepositoryProvider ?

### ISSUE THREAD

**Issue by drogbut** [felangel/bloc#2477]

**Comment by robsonsilv4** [comment]
BlocProvider is used to provide Bloc and Cubit (Stream and State) and RepositoryProvider is used to provide another classes (repositories, data providers and etc), like normal Provider.

**Comment by felangel** [comment]
Hi @drogbut 👋 
Thanks for opening an issue!

As @robsonsilv4 mentioned, `BlocProvider` is used to provide a single instance of a bloc or cubit to the widget tree. It handles automatically closing the bloc/cubit when the subtree is unmounted so you don't have to. Similarly, `RepositoryProvider` is used to provide a single instance of a repository to the widget tree. I highly recommend reading through the [architecture documentation](https://bloclibrary.dev/#/architecture) if you haven't already and you can take a look at [BlocProvider](https://github.com/felangel/bloc/blob/924b47e071406a2c5dcc65f9cf6eeb83b808c3de/examples/flutter_weather/lib/app.dart#L19) and [RepositoryProvider](https://github.com/felangel/bloc/blob/924b47e071406a2c5dcc65f9cf6eeb83b808c3de/examples/flutter_weather/lib/app.dart#L17) in action in various examples such as the [weather example](https://github.com/felangel/bloc/tree/master/examples/flutter_weather). Hope that helps!

Closing for now but feel free to comment with any additional questions or [join us on discord](https://discord.gg/bloc) 👍

**Comment by drogbut** [comment]
The definition is clear but in the implementation with Firebase I have trouble understanding. Indeed the RepositoryProvider could be passed to the bloc in its constructor. To me this seems to be the right approach. 

My question is whether the best approach is to pass the Repository into the constructor of the bloc or to wrap the bloc in the Repository?

**Comment by drogbut** [comment]
> 
> 
> BlocProvider is used to provide Bloc and Cubit (Stream and State) and RepositoryProvider is used to provide another classes (repositories, data providers and etc), like normal Provider.

My question is whether the best approach is to pass the Repository into the bloc-constructor or to wrap the block in the Repository?

**Comment by Pingear** [comment]
> > BlocProvider is used to provide Bloc and Cubit (Stream and State) and RepositoryProvider is used to provide another classes (repositories, data providers and etc), like normal Provider.
> 
> My question is whether the best approach is to pass the Repository into the bloc-constructor or to wrap the block in the Repository?

@drogbut @felangel 
Hi)
I have the same misunderstanding, which approach is better? Did you find the answer?

**Comment by felangel** [comment]
> > > BlocProvider is used to provide Bloc and Cubit (Stream and State) and RepositoryProvider is used to provide another classes (repositories, data providers and etc), like normal Provider.
> > 
> > 
> > My question is whether the best approach is to pass the Repository into the bloc-constructor or to wrap the block in the Repository?
> 
> @drogbut @felangel Hi) I have the same misunderstanding, which approach is better? Did you find the answer?

I recommend providing your repositories to the widget tree using `RepositoryProvider` and then injecting the provided instance into the bloc:

```dart
BlocProvider(
  create: (context) => MyBloc(context.read<MyRepository>()),
  child: MyChild(),
)
```

Hope that helps 👍

**Comment by Pingear** [comment]
> > > > BlocProvider is used to provide Bloc and Cubit (Stream and State) and RepositoryProvider is used to provide another classes (repositories, data providers and etc), like normal Provider.
> > > 
> > > 
> > > My question is whether the best approach is to pass the Repository into the bloc-constructor or to wrap the block in the Repository?
> > 
> > 
> > @drogbut @felangel Hi) I have the same misunderstanding, which approach is better? Did you find the answer?
> 
> I recommend providing your repositories to the widget tree using `RepositoryProvider` and then injecting the provided instance into the bloc:
> 
> ```dart
> BlocProvider(
>   create: (context) => MyBloc(context.read<MyRepository>()),
>   child: MyChild(),
> )
> ```
> 
> Hope that helps 👍

Thanks for the answer)
I'm ecstatic about your library, awesome features and documentation, thanks)

**Comment by talksik** [comment]
This is helpful.

I am curious what one should do for more complicated apps where the only other layer is not just data layer, but more like a service which handles a lot of things. 

As of now, I simply inject them via RepositoryProvider but it feels weird because it's technically not a "repository". 

Wondering whether a future version would consider renaming repository to something less opinionated?

**Comment by talksik** [comment]
I will attempt to give some examples (although technically many of these should be server-side):

- a weather service that not only pulls weather data but does transformations, looks at local geography and hits another api for getting specific user data and caches to local storage/shared preferences
- a service that takes in a stream of audio data and outputs transcriptions and translations
- a service that searches users by query and also combines it with information from another API which returns presence information of users

You can see how the concept of "repository" is for rather simple CRUD apps. At the risk of sounding naive, it _just feels wrong_ to categorize these as repository.

**Comment by talksik** [comment]
I guess it's fine to just call these services and inject with RepositoryProvider

**Comment by felangel** [comment]
> I will attempt to give some examples (although technically many of these should be server-side):
> 
> * a weather service that not only pulls weather data but does transformations, looks at local geography and hits another api for getting specific user data and caches to local storage/shared preferences
> * a service that takes in a stream of audio data and outputs transcriptions and translations
> * a service that searches users by query and also combines it with information from another API which returns presence information of users
> 
> In my opinion, the concept of "repository" works for rather simple CRUD apps. At the risk of sounding naive, it _just feels wrong_ to categorize these examples as repository; perhaps because I'm used to grpc/protobuf concept of services.

Those all generally fit the definition of repository in the context of the [bloc architecture](https://bloclibrary.dev/architecture/#repository). Terms like Repository and Service are quite overloaded in general and mean different things to different teams/contexts which is why I highly recommend defining them upfront so there’s no confusion.
