### ISSUE TITLE
Cubit example doesn't work(

### ISSUE THREAD

**Issue by KrillioSokolov** [felangel/bloc#2487]
Hi, 👋. Thank you for the great library!

I try to use Cubit instead of Bloc, but I can't use it even from library example. 

Maybe you have some secret sauce, don't you?) 

<img width="926" alt="Screenshot 2021-05-28 at 10 37 06" src="https://user-images.githubusercontent.com/23337273/119948016-12bdca80-bfa1-11eb-919b-2f673d55107c.png">

**Comment by KrillioSokolov** [comment]
flutter_bloc: 7.0.0-nullsafety.3

> Hi KrillioSokolov, which versions of bloc/flutter_bloc are you using?
> 
> If you need, this is the updated counter example:
> https://github.com/felangel/bloc/tree/master/examples/flutter_counter

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional information if you're still having trouble using `^7.0.0` 👍

**Comment by KrillioSokolov** [comment]
It is work with 7.0.1.
