### ISSUE TITLE
back button previous screen event not triigger

### ISSUE THREAD

**Issue by devsekar-1992** [felangel/bloc#2489]
https://github.com/devsekar-1992/emp_app

i am developing code review management system. In that app, Navigate list view to detail view and detail view to add/edit task page. need to refresh the previous screen by clicking back button. but, it's not working

**Comment by robsonsilv4** [comment]
You could try to use _then_ on navigation and add an event, like RefreshEvent.

```dart
Navigator.push(context,
    MaterialPageRoute(
        builder: (context) => TaskDetailView(taskId: data.taskId),
    ),
).then((_) => ...YourEvent);
```

Tip: create a static route on pages to simplify navigation.

**Comment by devsekar-1992** [comment]
@robsonsilv4  can i call same blocprovider.of<TaskList>(context).add(TaskList()) once again in then promises ?

**Comment by devsekar-1992** [comment]
> You could try to use _then_ on navigation and add an event, like RefreshEvent.
> 
> ```dart
> Navigator.push(context,
>     MaterialPageRoute(
>         builder: (context) => TaskDetailView(taskId: data.taskId),
>     ),
> ).then((_) => ...YourEvent);
> ```
> 
> Tip: create a static route on pages to simplify navigation.

not working

**Comment by Gene-Dana** [comment]
Hi there ! Have you looked into Flowbuilder? It's really cool and it solves this problem.

Here's a brief how-to:

First, you start a flow:

```
onTap: () async {
                  await Navigator.of(context).push(OnboardingFlow.route());
                ...
```

The flow build's itself depending on a piece of state
```
  @override
  Widget build(BuildContext context) {
    return FlowBuilder(
      state: OnboardingState.initial,
      observers: [HeroController()],
      onGeneratePages: onGenerateOnboardingPages,
    );
  }

List<Page> onGenerateOnboardingPages(OnboardingState state, List<Page> pages) {
  switch (state) {
    case OnboardingState.usageComplete:
      return [
        OnboardingWelcome.page(),
        OnboardingUsage.page(),
        OnboardingComplete.page(),
      ];
    case OnboardingState.welcomeComplete:
      return [
        OnboardingWelcome.page(),
        OnboardingUsage.page(),
      ];
    case OnboardingState.initial:
    default:
      return [OnboardingWelcome.page()];
  }
}
```

At any moment, you can press the back button and it works. Also, whenever you'd like, you can complete the flow:

```
FloatingActionButton(
            heroTag: 5,
            onPressed: () => context
                .flow<OnboardingState>()
                .complete((_) => OnboardingState.onboardingComplete),
            child: const Icon(Icons.check),
          ),
```

Check it out: Felix made this to work specifically with Bloc and Nav 2.0

https://github.com/felangel/flow_builder

**Comment by devsekar-1992** [comment]
Ok i will try

**Comment by devsekar-1992** [comment]
@Gene-Dana  i used event based approach and pass the previous screen bloc information via multiblocprovider. is this right way of approach that method? Flow Builder , i am new to flutter and dart. so , i am not ready to deviate from flutter , bloc . 

Review the source 
https://github.com/devsekar-1992/emp_app

**Comment by devsekar-1992** [comment]
@Gene-Dana @felangel  please help on this

**Comment by devsekar-1992** [comment]
Hi @felangel 


I am waiting for reply

**Comment by Gene-Dana** [comment]
Hey there @devsekar-1992, flowbuilder itself was created by @felangel and it works seamlessly in the bloc pattern. 

So first off, you use an app router and bloc builder in order to handle authentication. The firebase login tutorial actually uses flowbuilder for this. This is the approach I would suggest ! 

https://github.com/felangel/bloc/blob/78680b8d3047678e7787c5c9e01b946c1fe0a79d/examples/flutter_firebase_login/lib/app/view/app.dart#L35-L43

As for what's happening with the state information being passed between each screen, it's hard for me to tell where exactly the code for this is.

May you share with me exactly where you use the state to drive this flow?

**Comment by devsekar-1992** [comment]
@Gene-Dana  Actually, I fixed back button trigger option based on multi provider when navigating from one screen to another screen. But, i will learn flow builder once i understand bloc state management. i am facing issue with drop down widget rebuild the form and previous state information maintaining data in that form fields



Example code for dropdown widget issue

`https://github.com/devsekar-1992/emp_app/blob/main/lib/Tasks/view/task_edit.dart`

![image](https://user-images.githubusercontent.com/38203027/121496216-e15cea00-c9f7-11eb-95e5-3d60bba43737.png)

Dropdown reusable widgets dart file

`https://github.com/devsekar-1992/emp_app/blob/main/lib/Tasks/widgets/task_edit_dropdown.dart`

**Comment by devsekar-1992** [comment]
Thanks for all help . i fixed
