### ISSUE TITLE
How to use token in api header using bloc

### ISSUE THREAD

**Issue by georgek1991** [felangel/bloc#2505]
Hi @felangel 

I am little confused on how to pass access token in my http header. I have a authenticationBloc which retrieve the access token from keychain using authenticationRepository, something like this:

```
class AuthenticationBloc
    extends Bloc<AuthenticationEvent, AuthenticationState> {
....
final token = await authenticationRepository.getToken();
...
}

class AuthenticationRepository {
Future<String?> getToken() async {
    return await storage.get(key: _accesstokenKey);
  }
}
```

I have a class for making http request, something like this

```
class Service {
Future<dynamic> get(String url, Map<String, dynamic> parameters) async {
    var responseJson;
    try {
      final uri = Uri.parse(url);
      final response = await http.get(
        uri,
        headers: {
          "Content-Type": "application/json",
          "Authorization":
              "Bearer <token goes here>",
        },
      );
      responseJson = _response(response);
    } on SocketException {
      throw FetchDataException('No Internet connection');
    }
    return responseJson;
  }
}
```

My question is how do I get the value of bearer token in the Service class? 

Do I use authenticationRepository in service class? OR
Do I create a helper method in the service class and access the storage? OR
Do i retrieve the accessToken in every bloc and pass it down to the get method?

Please suggest.

**Comment by uris77** [comment]
I recently had to do something like this. I opted for using `Repositories`. I have a `ConfigRepository` that holds state related to configuration, like access keys. This repository is created when the app starts up, and is made available via  the `MultiRepositoryProvider`.

**Comment by georgek1991** [comment]
@uris77 will it be like `configRepository.getAccessToken()` inside the Service class? Can you please elaborate with some sample code?

**Comment by iandis** [comment]
@georgek1991  Is it something like this or?
```dart
class Service {
Future<dynamic> get(String url, Map<String, dynamic> parameters, String  authToken) async {
    var responseJson;
    try {
      final uri = Uri.parse(url);
      final response = await http.get(
        uri,
        headers: {
          "Content-Type": "application/json",
          "Authorization":
              'Bearer $authToken', /* <- place your token here from authToken */
        },
      );
      responseJson = _response(response);
    } on SocketException {
      throw FetchDataException('No Internet connection');
    }
    return responseJson;
  }
}
```

**Comment by georgek1991** [comment]
> @georgek1991 Is it something like this or?
> 
> ```dart
> class Service {
> Future<dynamic> get(String url, Map<String, dynamic> parameters, String  authToken) async {
>     var responseJson;
>     try {
>       final uri = Uri.parse(url);
>       final response = await http.get(
>         uri,
>         headers: {
>           "Content-Type": "application/json",
>           "Authorization":
>               'Bearer $authToken', /* <- place your token here from authToken */
>         },
>       );
>       responseJson = _response(response);
>     } on SocketException {
>       throw FetchDataException('No Internet connection');
>     }
>     return responseJson;
>   }
> }
> ```

@iandis so should I pass auth token as function parameter?

**Comment by iandis** [comment]
@georgek1991 I guess you should try it.

**Comment by georgek1991** [comment]
> @georgek1991 I guess you should try it.

Doing so wouldn't I need to import authentication repository in every repository that makes a api call? Authentication repository is where i am retrieving the access token.

**Comment by iandis** [comment]
@georgek1991 I guess you should, so the auth repo will depend on the **Service** class. But for me that would not be a good practice though. I usually just create one repository for REST API needs. Be it retrieving data, login, sign up, etc. Because I don't want to create more than 1 HttpClient.

**Comment by georgek1991** [comment]
> @georgek1991 I guess you should, so the auth repo will depend on the **Service** class. But for me that would not be a good practice though. I usually just create one repository for REST API needs. Be it retrieving data, login, sign up, etc. Because I don't want to create more than 1 HttpClient.

@iandis  Can you please show some code example?

**Comment by felangel** [comment]
Hi @georgek1991 👋 
Thanks for opening an issue and sorry for the delay! Regarding token management, I highly recommend using something like [fresh_dio](https://pub.dev/packages/fresh_dio). This allows the token management to stay within the networking layer since it technically has nothing to do feature state and bloc.

Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍

**Comment by tong-k-k** [comment]
Hi @felangel , I am facing the same problem.

I follow bloc tutorial and think that after login process, the token may be stored inside a authentication repository.

But for the rest of apis call, how do the api clients get the token? thinking if I inject the authentication repository to all api clients is quite messy.

And I have read your fresh_dio example. You have made a jsonplaceholder_client to handle all http requests and also storing the token directly inside the client. Seems you mix all api clients and authentication repository together to a single jsonplaceholder_client. I am wondering if my app has many api call, then the single client will become very large, and the single client will have many responsibilities including handling token storage and different api calls.

So I am thinking is there a better way, to separate different api calls to clients and keep the authentication repository for storing the token. But no need to always inject the token from the authentication repository to different api clients.

Looking forward to your suggestion!

Thanks!
