### ISSUE TITLE
Persist same state with different user's data in hydrated bloc

### ISSUE THREAD

**Issue by walid-ashik** [felangel/bloc#2507]
I'm actually learning bloc and stuck in a problem. In my app, I have a chat page. On that page, I'm pulling chat data for different users. Implemented Hydrated Bloc to persist state. Persisting is working. But the problem is after persisting user A data then I go back and go to user B chat page and in user B chat page, it also shows previous user A's data. Here is the code of `SingleChatMessagesCubit.dart`

```
class SingleChatMessagesCubit extends Cubit<SingleChatMessagesState> with HydratedMixin {
  ApiServices apiServices;

  SingleChatMessagesCubit({@required this.apiServices})
      : super(SingleChatMessagesLoading());

  Future<void> fetchSingleChatMessages(String messageListId, int page) async {

    RpChatMessages chatMessages =
        await apiServices.fetchChatMessages(messageListId, page);
    if (chatMessages == null) {
      emit(SingleChatMessagesEmpty());
    }

    if (chatMessages.message != null &&
        chatMessages.message == "Unknown error occurred!") {
      emit(SingleChatMessagesFailed());
    }

    if (chatMessages.messages.docs.isEmpty && page == 1) {
      emit(SingleChatMessagesEmpty());
    }
    if (chatMessages.messages.docs.isEmpty && page != 1) {
      // emit(SingleChatMessagesFetchedAll());
    } else {
      emit(SingleChatMessagesLoaded(chatMessages: chatMessages));
    }
  }

  @override
  SingleChatMessagesState fromJson(Map<String, dynamic> json) {
    try{
      final chatMessages = RpChatMessages.fromJson(json);
      return chatMessages.messages.page == 1 ? SingleChatMessagesLoaded(chatMessages: chatMessages) : null;
    } catch(_){
      return null;
    }
  }

  @override
  Map<String, dynamic> toJson(SingleChatMessagesState state) {
    if(state is SingleChatMessagesLoaded){
      return state.chatMessages.messages.page == 1 ? state.chatMessages.toJson() : null;
    }else {
      return null;
    }
  }
}

```

Here is the problem video recording. user A also sees the persisted user B data.

![bloc state duplicates](https://user-images.githubusercontent.com/33910898/120408692-57ff4500-c371-11eb-988c-acbc252eefa7.gif)

How can I persist state for all users and show each user only their data?

**Comment by felangel** [comment]
Hi @walid-ashik 👋 
Thanks for opening an issue!

You can maintain individual caches based on a cache id by overriding the `id`getter on your `HydratedBloc` like:

```dart
@override
String get id => userId;
```

Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions or [join the bloc discord](https://discord.gg/bloc) to continue the conversation 👍
