### ISSUE TITLE
Need to retain the values in different pages

### ISSUE THREAD

**Issue by GaneshSingaravelu** [felangel/bloc#2516]
Hi,

I have two pages (A, B). I have three fields on Page A and Page B respectively.

I have redirected the Page B Once values enter on page A.

When I hit the back button (App Bar Back Button) to go to page A and modifies some values in the field and again redirect to page B.

Now I have to retain the values on page B whatever I entered on the page before. However, it removes entire values and loads the page as new.

How can I fix it using bloc?

**Page B State Class:-**
```

class PageBState {
  // Page 02
  final String firstname;
  bool get isValidFirstname => firstname.length > 5;

  final String lastname;
  bool get isValidLastname => lastname.length > 5;

  final String mobileNumber;
  bool get isValidMobileNumber =>
      (mobileNumber.length > 9 && mobileNumber.length < 11);

  final FormSubmissionState formStatus;

  CompleteProfileState(
      {this.firstname = '',
      this.lastname = '',
      this.mobileNumber = '',
      this.formStatus = const InitialFormStatus()});

  CompleteProfileState copyWith(
      {String firstname,
      String lastname,
      String mobileNumber,
      FormSubmissionState formStatus}) {
    return CompleteProfileState(
      firstname: firstname ?? this.firstname,
      lastname: lastname ?? this.lastname,
      mobileNumber: mobileNumber ?? this.mobileNumber,
      formStatus: formStatus ?? this.formStatus,
    );
  }
}
```

Thanks,
Ganesh

**Comment by DoubleTrio** [comment]
Hi there!

I think your code problem is that the PageB bloc state is being disposed whenever your user navigates back to PageA. 

A solution to this might be having your BlocProvider of the PageB state be above PageA and PageB so that the state retains even when the user navigates back to PageA!

**Comment by GaneshSingaravelu** [comment]
Hi DoubleTrio,

I am new to flutter and bloc pattern.

Could you please provide me with a sample? It helps me a lot more.

Thanks

**Comment by DoubleTrio** [comment]
Sure, can you provide the sample code if the solution doesn't help you?

Takes a look at this example [here](https://github.com/felangel/bloc/blob/master/examples/flutter_shopping_cart/lib/main.dart).

Here, MultiBlocProviders provides both the CatalogBloc and CartBloc to the cart and catalog page,

So when the cart page is pushed like so: 
```dart
() => Navigator.of(context).pushNamed('/cart')
```
And then you tap the back button to go back to the catalog page, the cart's state is still retained.

Link to the full [example](https://github.com/felangel/bloc/blob/master/examples/flutter_shopping_cart)

**Comment by felangel** [comment]
Thanks so much for helping out @DoubleTrio 🙏 
Closing for now since it appears there is no further action required.

@GaneshSingaravelu feel free to comment with additional questions or [join the bloc discord](https://discord.gg/bloc) to continue the conversation 👍
