### ISSUE TITLE
Two Issues upgrading from 6.0.1 to 7.0.1

### ISSUE THREAD

**Issue by DJSL1NKY** [felangel/bloc#2528]
I upgraded my Project from flutter_bloc 6.0.1 to 7.0.1.

Now i got at difference positions these Issues:

`final authBloc = context.bloc<AuthBloc>();`

here is the Issue `bloc`.

```
Expanded(
            child: BlocBuilder<AuthBloc, AuthBlocState>(
              cubit: authBloc,
              builder: (context, state) {
                if (state is! UserAuthenticated) {
                  return Center(child: CircularProgressIndicator());
                }
```
here is the issue `cubit`.

I saw also, that something changed for the context.bloc but i can't figure out what to take to remain the same functionality.
After reading the ChangeLog, i saw that `cubit` got renamed to `bloc`, to remain the same functionality, is this the same?

Your help would be Nice.

**Comment by felangel** [comment]
Hi @DJSL1NKY 👋 
Thanks for opening an issue!

You just need to rename the `cubit` parameter to `bloc` in `BlocBuilder`

```dart
BlocBuilder<AuthBloc, AuthBlocState>(
  bloc: authBloc,
  builder: (context, state) {...}
),
```

You can refer to the [migration guide](https://bloclibrary.dev/#/migration?id=packageflutter_bloc) for more information 👍

**Comment by felangel** [comment]
In your case you can remove `bloc: authBloc` since it is provided to the current `BuildContext`.

```dart
BlocBuilder<AuthBloc, AuthBlocState>(
  builder: (context, state) { ... },
)
```

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
