### ISSUE TITLE
Flutter Bloc Test: Null check operator used on a null value

### ISSUE THREAD

**Issue by rdcoder33** [felangel/bloc#2530]
I am using 
flutter_bloc: ^7.0.1
flutter_test:
    sdk: flutter
bloc_test: ^8.0.2
mockito: ^5.0.10

(All latest version).

So, the following test is not working. I tried different ways but to implement tests but always end up with this error. And I have no idea what's causing this, 
earlier I also got errors such as bloc are null or bloc is not initialized. Now I am unable to reproduce those errors but this error persists.

```
import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/mockito.dart';
import 'package:orotask/logic/bloc/map_bloc/map_bloc.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:orotask/logic/repository/addr_map_repository.dart';

class MockAddrRepository extends Mock implements MapAddrRepository {}

void main()async {

  late MapAddrRepository mapAddrRepository ;
  late MapBloc mapBloc;
  await Firebase.initializeApp();

  setUp(() {
     
    mapAddrRepository = MapAddrRepository();
    mapBloc = MapBloc();
  });

  tearDown(() {
    mapBloc.close();
  });

  blocTest<MapBloc, MapState>('Map Bloc Initial State Tests',
      build: () => mapBloc,
      expect: () => MapNotLoaded());
}
```

Error after flutter test

```
package:flutter/src/services/platform_channel.dart 142:86                                       MethodChannel.binaryMessenger
  package:flutter/src/services/platform_channel.dart 148:36                                       MethodChannel._invokeMethod
  package:flutter/src/services/platform_channel.dart 331:12                                       MethodChannel.invokeMethod
  package:flutter/src/services/platform_channel.dart 344:41                                       MethodChannel.invokeListMethod
  package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart 30:37  MethodChannelFirebase._initializeCore
  package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart 77:13  MethodChannelFirebase.initializeApp
  package:firebase_core/src/firebase.dart 41:47                                                   Firebase.initializeApp
  test\src\bloc\visit_bloc\visit_bloc_test.dart 9:18                                              main


```

**Comment by felangel** [comment]
Hi @rdcoder33 👋 
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample so that I can run the test locally? Thanks 🙏

**Comment by rdcoder33** [comment]
Hi @felangel 👋,
Thanks for the prompt reply, a big fan of your work ❤️‍🔥.

Following is a minimal re-production sample for this error. 
**Turns out this comes only when using [`cloud_firestore`](https://pub.dev/packages/cloud_firestore/install) in Blocs.**

https://github.com/rdcoder33/flutter_bloc_firestore

Try to run the flutter test in the above repository and you will get the error: `Null check operator used on a null value.`

Thanks & Best Wishes

**Comment by felangel** [comment]
> Hi @felangel 👋,
> Thanks for the prompt reply, a big fan of your work ❤️‍🔥.
> 
> Following is a minimal re-production sample for this error.
> **Turns out this comes only when using [`cloud_firestore`](https://pub.dev/packages/cloud_firestore/install) in Blocs.**
> 
> https://github.com/rdcoder33/flutter_bloc_firestore
> 
> Try to run the flutter test in the above repository and you will get the error: `Null check operator used on a null value.`
> 
> Thanks & Best Wishes

No problem! I took a look and opened a [pull request](https://github.com/rdcoder33/flutter_bloc_firestore/pull/1) with my suggestions. I highly recommend using [mocktail](https://pub.dev/packages/mocktail) when working with null safety 👍 

Hope that helps 😄

**Comment by rdcoder33** [comment]
Yeah, that was a silly mistake on my side.
Appreciate the help, Keep the good work up!
