### ISSUE TITLE
State listen for multiple Streams best practice with Equatable

### ISSUE THREAD

**Issue by nathan1658** [felangel/bloc#2534]
Hello, just started to learn Bloc and I found its very fun and clean pattern for development.

Recently I started a project with firebase firestore, and I tried to hook up the stream to the state.
I've read the ticker example on how to listen a steam, and yield a new loaded State instance, with the use of Equatable to notify bloc builder to rebuild UI.

For my case, I have a Loaded State with four lists, each represents a collection on firebase. I also added a "Version" variable to trigger the update for the bloc builder.

The implementation works but it feels like Im violating some best practices, how can I improve it? Thanks!
 
```
class LoadedState extends State {
  late List<Object> a;
  late List<Object> n;
  late List<Object> c;
  late List<Object> d;
  int version = 0;

  @override
  List<Object?> get props => [version];
```

In my Bloc:
```class MyBloc extends Bloc<Event, State> {
  MyRepo raceRepo = MyRepo();

  StreamSubscription? _aSubscription;
  StreamSubscription? _bSubscription;
  StreamSubscription? _cSubscription;
  StreamSubscription? _dSubscription;
```

In my mapEventToState
``` @override
  Stream<State> mapEventToState(
    Event event,
  ) async* {
    if (event is LoadingEvent) {

      print("loading...");
      yield LoadingState();

      _bSubscription?.cancel();
      _aSubscription?.cancel();
      _cSubscription?.cancel();
      _dSubscription?.cancel();

  
      _bSubscription = raceRepo.fetchA("1234").listen((event) {
        add(aUpdatedEvent(event));
      });
      _aSubscription = raceRepo.fetchB("1234").listen((event) {
        add(bUpdatedEvent(event));
      });
      _cSubscription = raceRepo.fetchC().listen((event) {
        add(cUpdatedEvent(event));
      });
      _dSubscription = raceRepo.fetchD().listen((event) {
        add(dUpdatedEvent(event));
      });
```

For every event, I will yield a new LoadedState with corrosponding new value, and update the "version" variable

```  
if (event is aUpdatedEvent) {
      if (state is LoadedState) {
        var oldState = state as LoadedState;
        final newState = LoadedState.copyWith(oldState..a = event.updated);
        newState.version += 1;
        yield newState;
      }
    }

    if (event is bUpdatedEvent) {
      if (state is LoadedState) {
        var oldState = state as LoadedState;
        final newState = LoadedState.copyWith(oldState..n = event.updated);
        newState.version += 1;
        yield newState;
      }
    }

    if (event is cUpdatedEvent) {
      if (state is LoadedState) {
        var oldState = state as LoadedState;
        final newState = LoadedState.copyWith(oldState..c = event.updated);
        newState.version += 1;
        yield newState;
      }
    }
    if (event is dUpdatedEvent) {
      if (state is LoadedState) {
        var oldState = state as LoadedState;
        final newState = LoadedState.copyWith(oldState..d = event.updated);
        newState.version += 1;
        yield newState;
      }
    }
```

**Comment by felangel** [comment]
Hi @nathan1658 👋 
Thanks for opening an issue!

I would highly recommend providing a stricter type to your state:

```dart
class LoadedState extends State {
  late List<DataA> a;
  late List<DataN> n;
  late List<DataC> c;
  late List<DataD> d;
  int version = 0;

  @override
  List<Object?> get props => [a, n, c, d, version];
}
```

Then in those respective classes you can extend `Equatable` like:

```dart
class DataA extends Equatable {
  ...

  @override
  List<Object> get props => [...];
}
```

If you use `Object` then `Equatable` cannot properly determine whether instances are equal. Hope that helps 👍

**Comment by nathan1658** [comment]
> Hi @nathan1658 👋
> Thanks for opening an issue!
> 
> I would highly recommend providing a stricter type to your state:
> 
> ```dart
> class LoadedState extends State {
>   late List<DataA> a;
>   late List<DataN> n;
>   late List<DataC> c;
>   late List<DataD> d;
>   int version = 0;
> 
>   @override
>   List<Object?> get props => [a, n, c, d, version];
> }
> ```
> 
> Then in those respective classes you can extend `Equatable` like:
> 
> ```dart
> class DataA extends Equatable {
>   ...
> 
>   @override
>   List<Object> get props => [...];
> }
> ```
> 
> If you use `Object` then `Equatable` cannot properly determine whether instances are equal. Hope that helps 👍

Hi thanks for the quick response! However I'm a bit worried the current pattern, having four streams, with four corresponding event, yield a new instance of LoadedState, this seem a bit complicated.. Is it a bad practice or is there a better way for such scenario? Thanks again on your help!

**Comment by felangel** [comment]
> > Hi @nathan1658 👋
> > Thanks for opening an issue!
> > I would highly recommend providing a stricter type to your state:
> > ```dart
> > class LoadedState extends State {
> >   late List<DataA> a;
> >   late List<DataN> n;
> >   late List<DataC> c;
> >   late List<DataD> d;
> >   int version = 0;
> > 
> >   @override
> >   List<Object?> get props => [a, n, c, d, version];
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then in those respective classes you can extend `Equatable` like:
> > ```dart
> > class DataA extends Equatable {
> >   ...
> > 
> >   @override
> >   List<Object> get props => [...];
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If you use `Object` then `Equatable` cannot properly determine whether instances are equal. Hope that helps 👍
> 
> Hi thanks for the quick response! However I'm a bit worried the current pattern, having four streams, with four corresponding event, yield a new instance of LoadedState, this seem a bit complicated.. Is it a bad practice or is there a better way for such scenario? Thanks again on your help!

No problem! It's hard to say without more context -- in general I would recommend making sure the repo exposes an API that abstracts the underlying implementation details. In addition, you can use `combineLatest` to consolidate the four streams into a single one. Again, I don't think I have enough information to provide a concrete suggestion but I would definitely advise against having multiple parallel streams like that unless you're positive that it's what you want.

**Comment by felangel** [comment]
Closing for now but feel free to add additional comments/questions and I'm happy to continue the conversation 👍
