### ISSUE TITLE
seed in blocTest causing test to fail

### ISSUE THREAD

**Issue by georgek1991** [felangel/bloc#2538]
Hi @felangel,

Here is my code,

_test.dart
```
blocTest<ListBloc, ListState>(
      'emits [success] on api failure but the data list is not empty',
      build: () {
        when(() => mockListRepository.getList(any(), any()))
            .thenThrow(Exception('oops'));
        return ListBloc(ListRepository: mockListRepository);
      },

     **_// If I give this, ie. empty array then the test fails because I am expecting [ListSuccess] but it return [ListFailure]_**
      // seed: () =>
      // ListSuccess(List: [], isEndOfList: false, pageNumber: 1),

     **_// If I give this, ie. pass an non-empty array then the test fails because I am expecting [ListSuccess] but it return [ ]_**
      seed: () => ListSuccess(
          List: [mockData],
          isEndOfList: false,
          pageNumber: 2),

      wait: const Duration(seconds: 1),
      act: (bloc) => bloc.add(ListRequested()),
      expect: () => [
        ListSuccess(List: [mockData], isEndOfList: false, pageNumber: 2)
      ],
      verify: (_) {
        verify(() => mockListRepository.getList(2, 30)).called(1);
      },
    );
```

_bloc.dart
```
...
try{
...
...
}on Exception catch (_) {
 if (state.List.length > 0) {
   yield ListSuccess(
     List: state.List,
     isEndOfList: false,
     pageNumber: state.pageNumber,
   );
   return;
 }
 yield ListFailure(ListErrorStatus.server);
}
...
```

As you can see I am trying to yield Success state in Exception. 

While specifying the seed if I give non-empty array to my success state's list, then it return an empty in `expect`. If I give an empty array then it returns [Failure] as expected.

My question is why is the Success state not returned?

I debugged the code and the execution of code is as expected. State also has the correct values, `yield Success` code is also executed but somehow it is not received in `expect`.

**Comment by felangel** [comment]
Hi @georgek1991 👋
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? Thanks!

**Comment by georgek1991** [comment]
Sure @felangel

**Comment by georgek1991** [comment]
Hi @felangel,

Please check this sample app https://github.com/georgek1991/sample_app

**Comment by georgek1991** [comment]
Hi @felangel , did you get time to check the sample app.

**Comment by felangel** [comment]
Hi @georgek1991 👋 
Thanks for opening an issue!

I took a look and this is working as expected because you are re-emitted the same state. By default bloc will not re-emit the same state since no state change has occurred. If you really want to force a re-emit you can avoid extending `Equatable` but I generally don't recommend it.

Hope that helps 👍

**Comment by georgek1991** [comment]
Hi @felangel,

Can you suggest any solution for this keeping equatable?

**Comment by felangel** [comment]
> Hi @felangel,
> 
> Can you suggest any solution for this keeping equatable?

If you really want to keep Equatable and re-emit the state you need to make the state different. You can add a `lastUpdated` DateTime or a `uuid` or however you want to differentiate them but why do you want to force the bloc to re-emit the same state? It'll trigger a rebuild of your BlocBuilders and notify BlocListeners even when nothing has changed.

**Comment by georgek1991** [comment]
understood @felangel. 

Thanks for your help.
