### ISSUE TITLE
vscode extension removed existing bloc folder

### ISSUE THREAD

**Issue by MoonChel** [felangel/bloc#254]
https://github.com/felangel/bloc/blob/master/extensions/vscode/src/extension.ts#L111

> The rimraf executable is a faster alternative to the rm -rf shell command.

I've accidentally removed files from 3 hours of work, after creating new bloc with vscode extension. Don't know why, but I thought it will merge files, and because of it I didn't commit changes :(

May be it's possible to show some confirm notification if folder already exists? But merge way of creating new bloc will be even better. Thanks

**Comment by felangel** [comment]
Hi @MoonChel 👋 
Thanks for opening an issue and I'm really sorry about that!

I think having a confirmation dialog makes a lot of sense. I'll try to have that added over the next few days. Thanks 👍

**Comment by felangel** [comment]
@MoonChel this change is now available in v0.6.1 of the vscode bloc extension 🎉
