### ISSUE TITLE
[ReplayBloc proposal] check the next redo state.

### ISSUE THREAD

**Issue by Chralu** [felangel/bloc#2543]
Hi everyone,

After playing with `ReplayCubit`/`ReplayBloc` (which is super handy), I encounter a slight limitation. 

# Context 

I use a `ReplayCubit` to manage a multi screens form.
When the user validates a form screen, it calls a `Cubit's` method. 
That method emits an updated state, and the screen updates to display the next questions.

Now, to handle the `back` action, I use `ReplayCubit::undo()` method. 

It works pretty well, but with a limitation.

# Use case

1. on the first screen, the user picks answer `A`
2. on the second screen, he/she picks answer `3`
3. on the third screen, he/she picks answer `m`
4. user uses `back` action TWICE
   => state is `undo` TWICE, and user goes back to first screen

Until there, everything is fine.

Here is the limitation I encounter :
- If user picks answer `A` again, I would like to use `ReplayCubit::redo()`
- If user picks another answer, I would like to push a new `State`

To achieve that, I need to know if my new `State` is equal to the one on top of `_changeStack._redos`.

# Solution proposal

`ReplayCubitMixin` could expose a getter :
```
State get nextRedo;
```

That getter would return the `State` on top of the `_redos` stack.

What do you think about it ?

I'll try an implementation ASAP.

Thanks a lot for your work !
Cheers,

**Comment by felangel** [comment]
Hi @Chralu 👋 
Thanks for opening an issue!

Can you please elaborate a bit on why you'd want to "redo" instead of letting the user go through the selection normally? I think it's a bit of a custom requirement and I'd prefer to better understand the use-case before trying to make changes to the library. Thanks!

**Comment by Chralu** [comment]
Sure :)

If user has filled `X` form screens, and then wants to go back to review/update some values.
If I let him go through the normal selection, he/she will have to re-fill all the fields by hand.

A `ReplayCubitMixin.nextRedo` would allow to determine if user did the same choice as before.
In that case, we could use `ReplayCubitMixin.redo()`  instead of emitting a new state.

That way, user would keep his/hers previous selections as long as he/she has the same choices.

**Comment by felangel** [comment]
@Chralu you should be able to cache the replies by using the `HydratedMixin` in conjunction with `ReplayCubit` 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
