### ISSUE TITLE
Cubit Testing: Could not find correct Provider<T> above this BlocListener<T Cubit, T state> Widget.

### ISSUE THREAD

**Issue by ochmist** [felangel/bloc#2548]
**Describe the bug**
I am trying to write tests for widgets that rely on BlocListener and BlocBuilder.

**My test**
```
import 'package:bloc_test/bloc_test.dart';
import 'package:chala/blocs/auth_cubit/authentication_cubit.dart';
import 'package:chala/blocs/login_cubit/login_cubit.dart';
import 'package:chala/screens/auth/login.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';

class MockLoginCubit extends MockCubit<LoginState> implements LoginCubit {}

class MockAuthenticationCubit extends MockCubit<AuthenticationState>
    implements AuthenticationCubit {}

class FakeLoginState extends Fake implements LoginState {}

class FakeAuthenticationState extends Fake implements AuthenticationState {}

void main() {
  setUpAll(() {
    registerFallbackValue<LoginState>(FakeLoginState());
    registerFallbackValue<AuthenticationState>(FakeAuthenticationState());
  });

  _loginPage();
}

void _loginPage() {
  group('Login Page', () {
    testWidgets('Login page renders', (WidgetTester tester) async {
      final page = MultiBlocProvider(
        providers: [
          BlocProvider(
            lazy: false,
            create: (context) => MockLoginCubit(),
          ),
          BlocProvider(
            lazy: false,
            create: (context) => MockAuthenticationCubit(),
          ),
        ],
        child: MaterialApp(
          home: Builder(
            builder: (context) {
              return LoginPage();
            },
          ),
        ),
      );

      await tester.pumpWidget(page);

      expect(find.byWidget(page), findsOneWidget);

      final titleFinder = find.text('Welcome Back');

      expect(titleFinder, findsOneWidget);
    });
  });
}
```

**Error**

```
The following ProviderNotFoundException was thrown building _NestedHook:
Error: Could not find the correct Provider<AuthenticationCubit> above this
BlocListener<AuthenticationCubit, AuthenticationState> Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your `main.dart` and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that BlocListener<AuthenticationCubit, AuthenticationState> is under your
MultiProvider/Provider<AuthenticationCubit>.
  This usually happens when you are creating a provider and trying to read it immediately.
```

I was under the impression that the builder will generate a new context for LoginPage to use. Could someone point out what I am missing, please? Thanks in advance.

**Comment by felangel** [comment]
Hi @ochmist 👋 
Thanks for opening an issue!

I'm guessing the issue is because the types of the blocs your are providing are mock so the lookup is failing. You should be able to specify the type like so:

```dart
final page = MultiBlocProvider(
        providers: [
          BlocProvider<LoginCubit>(
            lazy: false,
            create: (context) => MockLoginCubit(),
          ),
          BlocProvider<AuthenticationCubit>(
            lazy: false,
            create: (context) => MockAuthenticationCubit(),
          ),
        ],
        child: MaterialApp(
          home: LoginPage(),
        ),
      );
```

Let me know if that helps 👍

**Comment by ochmist** [comment]
This worked. Thank you very much!!

**Comment by ochmist** [comment]
One other question, AuthenticationState has a class member called status which seems to be null when a bloclistener depends on it. How can I initialize it? Thank you in advance. 

```
The following JSNoSuchMethodError was thrown running a test:
NoSuchMethodError: invalid member on null: 'status'
```

**Comment by ismafils** [comment]
Hello @felangel I am having the same issue, I tried to follow you solution bu still get the same message error.
here is my code.

could you please help me fix this.

class FDRPlansScreen extends StatefulWidget {
  @override
  _FDRPlansScreenState createState() => _FDRPlansScreenState();
}

class _FDRPlansScreenState extends State<FDRPlansScreen> {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
      context.read<FDRCubit>().getListOfPlans();
    });
  }

  @override
  Widget build(BuildContext context) {
    final _size = MediaQuery.of(context).size;
    final _theme = Theme.of(context);
    return Scaffold(
        body: BlocConsumer<FDRCubit, FDRState>(
      listener: (context, state) {
        if(state is FDRErrorState){
          if(state.errorMessage==Constant.invalidToken){
            state.errorMessage.showSnackBar(context);
            Navigator.pushAndRemoveUntil(context, MaterialPageRoute(builder: (context)=>Login()), (route) => false);
          }
        }
      },
      builder: (context, state) {
        if (state is FDRLoadingState) {
          return LoadingScreen();
        } else if (state is FDRErrorState) {
          return Container(
            child: Center(
              child: Text(state.errorMessage),
            ),
          );
        } else if (state is FDRPlansSuccesstate) {
          return successScreen(state.model);
        } else {
          return Center(
            child: Text("Something went wrong!!"),
          );
        }
      },
    ));
  }

  Widget successScreen(dynamic model) {
    final _size = MediaQuery.of(context).size;
    final _theme = Theme.of(context);
    return SingleChildScrollView(
        child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        ListView.builder(
            shrinkWrap: true,
            physics: ScrollPhysics(),
            itemCount: model["fdr"].length,
            itemBuilder: (BuildContext ctx, index) {
              dynamic plan = model["fdr"][index];
              return Container(
                  margin: EdgeInsets.only(top: 10),
                  child: Column(
                    children: [
                      const SizedBox(height: 4.0),
                      Row(
                        children: [
                          Expanded(
                            flex: 2,
                            child: CircleAvatar(
                                radius: 20.0,
                                backgroundColor: _theme.cardColor,
                                child: Icon(Icons.diamond_rounded)),
                          ),
                          Expanded(
                            flex: 6,
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                              children: [
                                Text(
                                  "${plan["name"]}",
                                  maxLines: 2,
                                  overflow: TextOverflow.ellipsis,
                                  style: _theme.textTheme.bodyText2!.copyWith(
                                    fontWeight: FontWeight.w500,
                                    fontSize: 15.0,
                                    letterSpacing: 0.75,
                                  ),
                                ),
                                Text(
                                  "max - ${double.parse(plan["maximum_amount"].toString()).toStringAsFixed(2)}",
                                  style: _theme.textTheme.bodyText2!.copyWith(
                                    letterSpacing: 0.75,
                                    fontSize: 14.0,
                                    color: Colors.grey,
                                  ),
                                ),
                                Text(
                                  "min - ${double.parse(plan["minimum_amount"].toString()).toStringAsFixed(2)}",
                                  style: _theme.textTheme.bodyText2!.copyWith(
                                    letterSpacing: 0.75,
                                    fontSize: 14.0,
                                    color: Colors.grey,
                                  ),
                                ),
                              ],
                            ),
                          ),
                          Expanded(
                            flex: 3,
                            child: Padding(
                              padding: const EdgeInsets.only(right: 20.0),
                              child: InkWell(
                                onTap: () {
                                  Navigator.push(
                                      context,
                                      MaterialPageRoute(
                                          builder: (context) => FDRAmountScreen(
                                                planId: plan["id"].toString(),
                                                max: plan["maximum_amount"]
                                                    .toString(),
                                                min: plan["minimum_amount"]
                                                    .toString(),
                                                plan_name:
                                                    plan["name"].toString(),
                                                plan: plan,
                                              ))).then((value) {
                                    if (value != null && value[0] != null) {
                                      context.read<FDRCubit>().getListOfPlans();
                                    }
                                  });
                                },
                                child: Container(
                                  width: 70,
                                  height: 30,
                                  alignment: Alignment.center,
                                  decoration: BoxDecoration(
                                      color: Colors.blueAccent,
                                      borderRadius:
                                          BorderRadius.all(Radius.circular(4))),
                                  child: Text(
                                    "Buy",
                                    style: TextStyle(color: Colors.white),
                                  ),
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                      const SizedBox(height: 3.0),
                      Padding(
                        padding: EdgeInsets.only(
                          left: _size.width * 0.16,
                          right: _size.width * 0.02,
                        ),
                        child: Divider(
                          thickness: 1.75,
                          color: Colors.grey.withOpacity(0.2),
                        ),
                      ),
                    ],
                  ));
            })
      ],
    ));
  }

  String formatDate(String date) {
    DateTime dt = DateTime.parse(date);
    return DateFormat("d MMM yyyy").format(dt);
  }
}
