### ISSUE TITLE
copyWith state is not updating my ui

### ISSUE THREAD

**Issue by Add00w** [felangel/bloc#2549]
I have read some issues like mine where the solution was `List<type>.from(list);` but it causes an issue for me, I have screen with topics when user chooses a topic I want to change the selected field value to true or false and update the screen with checked icon but since I removed the item from its position it shows it different position if you can see my repo is private but I gave you access plz if you have time check and when you run the app see the welcome screen after intro screens and try to choose a topic then you will see it appears another place thanks @felangel   [here](https://github.com/Add00w/share_book.git)

**Comment by felangel** [comment]
Hi @Add00w 👋 
Thanks for opening an issue!

I took a look and it looks like there are parts of the state which aren't `Equatable`. For example, https://github.com/Add00w/share_book/blob/10b6443df45c6def44ee19c9f05512cfc3ef0d23/lib/models/topics.dart#L1. In order for `Equatable` to work properly all properties of an `Equatable` class must also be `Equatable`. Let me know if that helps 👍

**Comment by Add00w** [comment]
> Hi @Add00w 👋
> Thanks for opening an issue!
> 
> I took a look and it looks like there are parts of the state which aren't `Equatable`. For example, https://github.com/Add00w/share_book/blob/10b6443df45c6def44ee19c9f05512cfc3ef0d23/lib/models/topics.dart#L1. In order for `Equatable` to work properly all properties of an `Equatable` class must also be `Equatable`. Let me know if that helps 👍

thanks for your time.
I changed my model as follows:

```
class Topic extends Equatable {
  final String id;
  final String title;
  final image;
  bool selected;

  Topic({
    required this.title,
    required this.image,
    this.selected = false,
    required this.id,
  });

  @override
  List<Object?> get props => [id, title, image, selected];
}
```


 

And in my cubit
```
     void selectTopic(String? topicId) async {
        log('Topic Id $topicId');
        final list1 = <Topic>[];
        for (var item in _topics) {
          if (item.id == topicId) {
            item.selected = !item.selected;
          }
          list1.add(item);
        }
        emit((state as TopicsLoaded).copyWith(topics: list1));}
```

but the ui is not updated

**Comment by huynguyennovem** [comment]
Same problem here. How's it going?

**Comment by jonathankao97** [comment]
Pulled the code and was able to get it working locally. Would recommend making Topic immutable 
`class Topic {
  final String id;
  final String title;
  final image;
  final bool selected;

  Topic({
    required this.title,
    required this.image,
    this.selected = false,
    required this.id,
  });
}
`
and refactoring your selectTopic method to look like this
`
  void selectTopic(String? topicId) async {
    final list = List<Topic>.from(_topics);
    final index = list.indexWhere((element) => element.id == topicId);
    final updatedTopic = list[index];
    final newTopic = Topic(
        id: updatedTopic.id,
        title: updatedTopic.title,
        image: updatedTopic.image,
        selected: !updatedTopic.selected);
    list[index] = newTopic;
    emit((state as TopicsLoaded).copyWith(topics: list));
  }
`

**Comment by felangel** [comment]
@Add00w closing for now but feel free to comment with additional questions if @jonathankao97's answer was unclear and I'm happy to continue the conversation 👍
