### ISSUE TITLE
Sync events from different Blocs

### ISSUE THREAD

**Issue by YanaKrivitskaya** [felangel/bloc#2552]
Hi there! 

I have a question regarding how to synchronize events from different blocs during page load.

Let's say I have a NotesPage. On the page load I have to call to APIs - GetNotes, GetTags. These methods are called from different blocs. The issue is that they call API independently from each other, so if I have access token expired, both methods will call refresh token method at the same time which leads to two tokens generated. 

Is there a way to call events from different blocs in order? 

Code samples:

Part of the router:

`case notesRoute:
        return MaterialPageRoute(
          builder: (_) => BlocProvider<NoteBloc>(
            create: (context) =>
                NoteBloc(),
            child: NotesPage(),
          ),
        );`

Part of notes page:

`class NotesPage extends StatelessWidget{
  NotesPage();

  @override
  Widget build(BuildContext context) {
    
    return MultiBlocProvider(
      providers: [
        BlocProvider.value(
          value: context.read<NoteBloc>()..add(GetAllNotes()),
        ),
        BlocProvider<TagFilterBloc>(
          create: (context) => TagFilterBloc()..add(GetTags()),
        ),
      ],
      child: Scaffold(
        appBar: AppBar(
          leading: IconButton(
            icon: FaIcon(FontAwesomeIcons.chevronLeft, color: ColorsPalette.lynxWhite),
            onPressed: () => Navigator.of(context).pop(),
          ),
          title: Text('Notes', style: GoogleFonts.quicksand(textStyle: TextStyle(color: Colors.white, fontSize: 25.0))),
          backgroundColor: ColorsPalette.greenGrass,
          actions: [
            IconButton(
              icon: FaIcon(FontAwesomeIcons.search, color: ColorsPalette.lynxWhite),
              onPressed: (){
                context.read<NoteBloc>().add(SearchBarToggle());
              },
            ),
            TagsFilterButton(),
            NoteFilterButton()
          ],
        ),
        body:  NotesView(),
        floatingActionButton: FloatingActionButton(
          onPressed: (){
            Navigator.pushNamed(context, noteDetailsRoute, arguments: 0).then((value) 
              => context.read<NoteBloc>().add(GetAllNotes()));
          },
          tooltip: 'Add New Note',
          backgroundColor: ColorsPalette.nycTaxi,
          child: Icon(Icons.add, color: ColorsPalette.white),
        ),
      ),
    );
  }
}`

**Comment by YanaKrivitskaya** [comment]
This has been solved

**Comment by felangel** [comment]
> This has been solved

Glad you solved it!
