### ISSUE TITLE
How to update only one item in listview

### ISSUE THREAD

**Issue by lazy-geek** [felangel/bloc#2553]
If i have a todosbloc for displaying todos in a list view , when i update the content of one todo , i only want that to do to update and not the entire listview

If i emit a state from todosbloc then the whole list view will be updated , what are best practices/ solution to doing something like this?

**Comment by Elias8** [comment]
Hello @lakerszhy 👋,

You can use [ListView.builder](https://flutter.dev/docs/cookbook/lists/long-lists) for such cases so that only visible items are updated as they scrolled onto the screen.

Hope that helps.

**Comment by lazy-geek** [comment]
@Elias8 I think you are misunderstanding what i said,
I want to update only one item in the list but if i have created a bloc that builds the list whenever it changes , the whole list will be updated when i update only one item

**Comment by felangel** [comment]
Hi @lazy-geek 👋 
Thanks for opening an issue!

As @Elias8 mentioned, if you use a `ListView.builder` you don't need to worry about prematurely optimizing because only the visible items will be rebuilt. Are you running into performance issues or can you provide additional context? Thanks! 👍

**Comment by lazy-geek** [comment]
Thank for the reply i will try to do as you said and see the performance , for now i am closing this issue
