### ISSUE TITLE
Add the previous state as property in the bloc listener 

### ISSUE THREAD

**Issue by devmuaz** [felangel/bloc#2573]
Hi, I've used bloc for a very long time and published 2 of my apps in production mode.
Recently, in the latest project I'm currently working on.. I had a little issue which is:
when I use `BlocListener`, I use it for executing some action as obvious.. but it happened that I want the listener to have another property to its function which is `previous`.. the reason why is that is because in some cases I want to check the previous state that was emitted by the bloc so I can perform some actions in there.

Currently, I can't do that since I can't get the previously emitted state (only the current).. and you may ask and wonder why would I need the previous state if I have a listener already? Well, the answer is when a state is emitted in screen (view) and the listener is in another screen (view) and I navigate to the other screen (view) the listener obviously can do the actions because the state is already emitted before I navigated to the current screen (view) that contains the listener.

I don't know if this is clear enough to explain what happens.. but I hope it does 😅!!

I'll be waiting your response at any time.

Thank in advance by the way ❤️, big fan of the bloc library and all the efforts you guys make!

**Comment by GZGavinZhao** [comment]
There is actually a way to do so.

Set a variable within your cubit/bloc called `last`. Whether to initialize it depends on your specific usage. Here I will just initialize it. The important part is to override the `onChange` function to set `last` to the `currentState` right before the new state gets emitted. Remember, the `onChange` function is executed right before the new state is emitted.

When you need to use it, just call `myCubit.last`.

```dart
class CounterCubit extends Cubit<int> {
  CounterCubit() : super(0);

  int last = 0;

  void increment() => emit(state + 1);

  @override
  void onChange(Change<int> change) {
    super.onChange(change);
    last = change.currentState;
  }
}

void main(List<String> arguments) {
  final cubit = CounterCubit();
  for (var i = 0; i < 5; i++) {
    cubit.increment();
    print('${cubit.state} ${cubit.last}');
  }
}
```
The output should be:
```
1 0
2 1
3 2
4 3
5 4
```

I'm actually surprised that a variable inside the cubit is preserved... I wouldn't have learned this without your question. Hope this helps! :)

**Comment by devmuaz** [comment]
Great wrok around buddy ❤️, it could absolutely work fine.. but just in case, this feature could be really helpful and useful to directly use it in a bloc builder, consumer, or listener.

Thanks You 😄!

**Comment by felangel** [comment]
Hi @devmuaz 👋 
Thanks for opening an issue!

I highly recommend including everything you need as part of your state class. If you really need access to the previous state then you can define a `previousValue` property on the state class.

```dart
class MyState {
  const MyState({required this.currentValue, this.previousValue});
  final int currentValue;
  final int? previousValue;
}
```

Then in your bloc you can update the state accordingly:

```dart
void increment() {
  emit(MyState(previousValue: state.currentValue, currentValue: state.currentValue + 1));
}
```

Now you can access both the current and previous state from your UI:

```dart
final state = context.watch<CounterCubit>().state;
final currentValue = state.currentValue;
final previousValue = state.previousValue;

return Text(...);
```

Hope that helps and closing for now 👍

**Comment by mercz85** [comment]
I am just a begginer, practicing with bloc, but you maybe this is useful to you:
last = change.nextState;

Result:
Hello  World!
state: 0  last: 1
state: 1  last: 2
state: 2  last: 3
state: 3  last: 2
state: 2  last: 1

`import 'dart:async';
import 'package:bloc/bloc.dart';

abstract class CounterEvent {}

class CounterIncrementPressed extends CounterEvent {}

class CounterDecrementPressed extends CounterEvent {}

class CounterBloc extends Bloc<CounterEvent, int> {
  CounterBloc() : super(0) {
    //Example with Anonymous and NotAnomymous
    on<CounterIncrementPressed>((event, emit) => emit(state + 1));
    on<CounterDecrementPressed>(_onCounterDecrementPressed);
  }

  int last = 0;

  void _onCounterDecrementPressed(event, emit) {
    emit(state - 1);
  }

  @override
  void onChange(Change<int> change) {
    super.onChange(change);
    //state = change.currentState;
    last = change.nextState; //USE THIS ONE
    print('state: $state  last: $last');
  }
}

void main() {
  print('Hello  World!');

  final bloc = CounterBloc();

  bloc.add(CounterIncrementPressed());

  bloc.add(CounterIncrementPressed());

  bloc.add(CounterIncrementPressed());

  bloc.add(CounterDecrementPressed());

  bloc.add(CounterDecrementPressed());

  bloc.close();
}`

**Comment by jnorkus** [comment]
I have now come across this issue multiple times. I think it makes sense to add previousState to the listener, the same way it is present in `listenWhen`. There are many use cases where you want to compare the states or act on previous values. Having it in the listener would just be so much more convenient.

**Comment by mateusfccp** [comment]
Now, it is very unfortunate that this issue was closed and the "solution" is to duplicate the state within the state. We are dealing with transitional states, and the previous state may be not useful to anything besides this kind of check.

`listenWhen` already had the previous value, and passing it to `listen` is extremely easy. I reckon it is a breaking change, but we can wait for it. `flutter_bloc` used to release major versions every few months (there even one instance that they are 20 days apart).

Please, reconsider this, so we don't have to overcomplicate our code.

**Comment by victor-tinoco** [comment]
> I highly recommend including everything you need as part of your state class. If you really need access to the previous state then you can define a previousValue property on the state class.

We're not talking about the current state itself, but the transition between two states. I'd agree with your answer if we were talking about `BlocBuilder` since everything used to render the current state should be within the state class. Now, talking about listeners, we might want to do some reaction between the transition of two specific states, we shouldn't need to carry over the previous state just for this purpose. We already have something similar with `listenWhen` as aforementioned by Mateus, but it is totally redundant and might be included directly over the listener instead of this complexity layer.

**Comment by maRci002** [comment]
Currently, when I need to listen for changes in two different parts of the state (like `status` and `pendingAction.status`), I often have to use **two separate `BlocListener`s** to avoid unintended behavior.

If the previous state were available in `listener` (just like it is in `listenWhen`), I could compare states directly and simplify my logic.

**Comment by felangel** [comment]
> Currently, when I need to listen for changes in two different parts of the state (like `status` and `pendingAction.status`), I often have to use **two separate `BlocListener`s** to avoid unintended behavior.
> 
> If the previous state were available in `listener` (just like it is in `listenWhen`), I could compare states directly and simplify my logic.

Can you give an example? Thanks!

**Comment by maRci002** [comment]
> Can you give an example? Thanks!

@felangel I put together a small example 👆 — what do you think?

**Comment by CBeening** [comment]
Not sure if anything related to this request happened so far, but I also have the same use case as @maRci002,
comparing the previous and the current state to show a dialog or snackbar etc.

Right now I use the listenWhen callback for this, but obviously it is not the intended use.

Sometimes I do something like emitting two states directly after each other, the first state having a flag set while the second does not, then I can pick up this change in the listener and act accordingly.  
This seems to work pretty good but it does feel like its not the recommended way to do this.

**Comment by maRci002** [comment]
I think adding `previousState` to the listener is about the same ergonomic improvement we got with `context.select`.

Just as we can now avoid nesting two `BlocBuilders` by using two `context.select` calls in one `build` method, we should be able to handle multiple state-change logics in one `listener` without nesting `BlocListeners`.

**Current UI (Flat):**

```dart
final itemA = context.select((MyBloc b) => b.state.itemA);
final itemB = context.select((MyBloc b) => b.state.itemB);

```

**Requested Logic (Flat):**
If we had `previousState`, we could avoid 'Wrapper Hell' for side effects too:

```dart
listener: (context, prev, curr) {
  if (prev.itemA != curr.itemA) // handle A
  if (prev.itemB != curr.itemB) // handle B
}

```

Currently, to do this cleanly, we are forced to nest two `BlocListeners`, which is exactly what `context.select` helped us avoid in the build tree.
