### ISSUE TITLE
Can't use multiple BlocBuilders using a single Bloc.

### ISSUE THREAD

**Issue by AbderraoufKhodja** [felangel/bloc#2576]
**Describe the bug**
I am building a flutter app where I provide a given FooBloc in the main.dart class and I use two BlocBuilders on the same FooBloc on two different screens respectively. These two screens are extended with a AutomaticKeepAliveClientMixin. My problem is that one screen shows the data stream correctly and the second shows that the same stream is empty.

- It seems like I can't use multiple BlocBuilders using a single Bloc. The only work around that a found is to create a new Bloc for each screen.
- No error is being thrown, just empty data on second opened screen.

**Expected behavior**
Expect both screen to show the same data.

Output of running `flutter doctor -v`.
[√] Flutter (Channel stable, 2.2.2, on Microsoft      
    Windows [Version 10.0.19042.985], locale en-US)   
    • Flutter version 2.2.2 at
      C:\Users\ZJNU\AppData\Local\Android\flutterr\flu      tter
    • Framework revision d79295af24 (2 weeks ago),    
      2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3       

[√] Android toolchain - develop for Android devices   
    (Android SDK version 29.0.2)
    • Android SDK at
      C:\Users\ZJNU\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android      Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 
      1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files
      (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program
      Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 
      1.8.0_242-release-1644-b01)

[√] VS Code (version 1.57.1)
    • VS Code at
      C:\Users\ZJNU\AppData\Local\Programs\Microsoft  
      VS Code
    • Flutter extension version 3.23.0

[√] Connected device (3 available)
    • Android SDK built for x86 (mobile) •
      emulator-5554 • android-x86    • Android 7.0    
      (API 24) (emulator)
    • Chrome (web)                       • chrome     
      • web-javascript • Google Chrome 90.0.4430.212  
    • Edge (web)                         • edge       
      • web-javascript • Microsoft Edge 91.0.864.48   

• No issues found!

**Comment by Elias8** [comment]
Hello @AbderraoufKhodja 👋

Create the bloc on the top level of the app widget(MaterialWidget) to make it accessible for both screens. And use `BlocProvider(create: (context) => YourBloc())` to create the bloc, and you can access it from anywhere in the widget tree.

If that doesn't fix your problem, it would be great to help if you could share a repo to your code.

Hope that helps.

**Comment by felangel** [comment]
Thanks @Elias8 for your answer! @AbderraoufKhodja closing for now but if you're still having trouble it would be great if you could provide a minimal reproduction sample, thanks! 👍
