### ISSUE TITLE
QUESTION: Multiple Blocs with OpenContainer

### ISSUE THREAD

**Issue by gbaccetta** [felangel/bloc#2584]
Hi there, 
I have this situation: I'm using a OpenContainer Widget.
I have a BlocBuilder on top of it that render a item header in the closedBuilder, and a DetailPage in the openBuilder.
Since the openBuilder push a new route to the navigator, this doesn't get rebuilt automatically as the closedBuilder.
Normally I could just reuse a BlocBuilder in the openBuilder page, but in my case I wanted to use this widget with multiple Blocs from, such as a ListBloc and a specific ItemBloc, that do not necessarely exist in the widget tree at the same time.

Am I missing something or do I have to dublicate the widget one for each BlocBuilder I want to use ?

This is my OpenContainer, the BlocBuilders that use it, provide an updated event:

```Dart
class EventListWidget extends StatelessWidget {
  final Event event;

  const EventListWidget({required this.event});

  @override
  Widget build(BuildContext context) {
    return OpenContainer(

      closedBuilder: (BuildContext context, void Function() openCreateEvent) {
        return EventTileWidget(
          event: event,
        );
      },
      
      openBuilder:
          (BuildContext context, void Function({Object? returnValue}) action) {
        return EventDetailsScreen(event: event,);
      },
    );
  }
}
```

**Comment by felangel** [comment]
Hi @gbaccetta 👋 
Thanks for opening an issue!

Can you please share a link to a minimal reproduction sample that illustrates the problem you're facing? I'm happy to take a closer look 👍

**Comment by gbaccetta** [comment]
Thank you @felangel for your reply and great work. I will be able to set a up a small sample only next week, sorry about that. 

The problem anyway come from the fact that OpenContainer push a new route when  the openBuilder is called and since it's a new route, the widget tree doesn't get rebuilt, obviously. Also any Bloc instantiated where the OpenContainer cannot be accessed from the openBuilder widget as it lies within a new route. The closedBuilder obviously give access to them. 

Anyway I will post a sample code as soon as I can

**Comment by gbaccetta** [comment]
Hi prefer to close the question, I do not want to make you lose your time and no matter how I look at it, I thingk the only solution is to have a separate detailsScreen each reinstantiating in the BlocProvider a new instance of the bloc they need. I did something along these lines:

```dart
class EventListWidget extends StatelessWidget {
  final Event event;
  final bool fromList;

  const EventListWidget({required this.event, this.fromList = false});

  @override
  Widget build(BuildContext context) {
    return OpenContainer(

      closedBuilder: (BuildContext context, void Function() openCreateEvent) {
        return EventTileWidget(
          event: event,
        );
      },
      
      openBuilder:
          (BuildContext context, void Function({Object? returnValue}) action) {
        return fromList ? EventListDetailScreen(event:event) : EventDetailsScreen(event: event,);
      },
    );
  }
}
```
Two different screen in the open container, one for each of my need.
The drawback is some code duplication and a somewhat less readable OpenContainer.

Anyway, as always I cannot thank you enough for your work on the bloc library @felangel
