### ISSUE TITLE
How to do Bloc to Bloc communication along with Flutter UI change?

### ISSUE THREAD

**Issue by jithusjacob** [felangel/bloc#2586]
Hi,
I just started Flutter and using Bloc and Flutter Bloc in my project. I have a scenario where 2 Blocs need to communicate. I saw the documentation has below example

class MyBloc extends Bloc {
  final OtherBloc otherBloc;
  StreamSubscription otherBlocSubscription;

  MyBloc(this.otherBloc) {
    otherBlocSubscription = otherBloc.listen((state) {
        // React to state changes here.
        // Add events here to trigger changes in MyBloc.
    });
  }

  @override
  Future<void> close() {
    otherBlocSubscription.cancel();
    return super.close();
  }
}

I did the same .But I have a doubt. As per my understanding we need to use the same bloc instance through out for state changes and so we use Bloc provider and pass the instance throughout the wigets. But I am writing the Stream subscription at the back end. How can I trigger  a event to change state in MyBloc in the backend so that UI also changes respectively.

As of now what I am doing is that ,since I know the event change in OtherBloc whose state output I need.I trigger the event change for MyBloc just after that.This all happens in the UI.

``` 
context.read<OtherBloc>().add(AddSubmit());
var abc =transform (state from Other Bloc) to Event for MyBloc
        context.read<MyBloc>().add(MyBlocEvent(abc));

```

I believe this is not the correct way.Could you let me know if there is any other way to achieve this

**Comment by danielroek** [comment]
Do u use `equatable` in your states?

**Comment by jithusjacob** [comment]
Yes my states extend Equatable.

**Comment by JigneshPatel23** [comment]
Happy to try if you can create and share sample project.

**Comment by jithusjacob** [comment]
Created a sample project -https://github.com/jithusjacob/BloctoBloc.git
Two Blocs- Main bloc and Add bloc
once I add a list in the add page ,the main page gets updated. The add bloc is for add page and main bloc is for main page.

In project I am doing  in the UI itself I am calling Main Bloc after Add bloc to pass the values.

```
onPressed: () {
context.read<AddBloc>().add(AddSubmit());
context.read<MainBloc>().add(
MainAddItem(
 Item(
desc: state.desc.text,
    ), 
           ),
); 

}
```
Instead I want to do this using Bloc subscription in the bloc. But how to trigger the event MainAddItem in the backend and not in the UI.As per my understanding we need to use the same bloc instance through out for state changes and so we use Bloc provider and pass the instance throughout the wigets. But I am writing the Stream subscription at the back end. How can I trigger a event to change state in MainBloc in the backend so that UI also changes respectively.

**Comment by JigneshPatel23** [comment]
Thanks @jithusjacob for sharing this as an example

Maybe I got your point which you are trying to achieve.. 
To confirm my understanding, you don't want to do these things on 2 bloc while adding new item..
```
context.read<AddBloc>().add(AddSubmit());

context.read<MainBloc>().add(
                  MainAddItem(
                    Item(
                      desc: state.desc.text,
                    ),
                  ),
                );
```
Instead you want `MainBloc` to listen `AddBloc` state changes and if any new items added successfully then`MainBloc` should update their state accordingly.. 

I think this [example](https://bloclibrary.dev/#/fluttertodostutorial) help you for the same in general and specifically for [bloc to bloc communication is here](https://bloclibrary.dev/#/fluttertodostutorial?id=bloc-1)

Hope this helps..

**Comment by jithusjacob** [comment]
Hi Jignesh,
Thanks for looking into this. I went through the example and yes this is what I was looking for. The example is not updated for
null safety  also listen' is deprecated.I made the changes accordingly in the sample program.

**I did the below changes and its working as expected. But I am still getting a warning `[dart cancel_subscriptions] [I] Cancel instances of dart.async.
        : super(  StreamSubscription.` But I already did this. Not sure any error in the code.**

```
class MainBloc extends Bloc<MainEvent, MainState> {
    final AddBloc addBloc;
>>  StreamSubscription? addSubscription;
    MainBloc({required this.addBloc})
        : super(
            MainState(
              items: <Item>[],
            ), // MainState
          ) {    addSubscription = addBloc.stream.listen((state) {        
         if (state.fstatus == true) {
          add(MainAddItem(Item(desc: state.desc.text)));
        }
      });
    }

 @override
    Future<void> close() {
      addSubscription!.cancel();
      return super.close();
    }
```
and in main.dart
```
MultiBlocProvider(
      providers: [
        BlocProvider<AddBloc>(
          create: (context) => AddBloc(),
        ), // BlocProvider
        BlocProvider<MainBloc>(
          create: (context) => MainBloc(
            addBloc: BlocProvider.of<AddBloc>(context),
          ), // MainBloc
        ), // BlocProvider
      ],
```

**Comment by JigneshPatel23** [comment]
HI @jakecastelli,

Good to know these examples helps you get goings..

If your concern now is only **warning**.. then just changing below line helps me..

From 
```
      addSubscription!.cancel();
```
To
```
     addSubscription?.cancel();
```

**Comment by jithusjacob** [comment]
Yes its resolved now. Thanks for  your help

**Comment by omidraha** [comment]
Is this normal to use `onData` inside of `mapEventToState` ?
Because I would like to access to  `event` of current block alongside with `state` of other bloc.

```dart
  final OtherBloc otherBloc;
  late StreamSubscription otherBlocSubscription;

  CurrentBloc({
    required this.otherBloc,
  }) : super(null) {
    otherBlocSubscription = otherBloc.stream.listen((state) {
     /// nothing here
      print('state: $state');
    });
  }

```


```dart

  @override
  Stream<AgeState> mapEventToState(AgeEvent event) async* {

    otherBlocSubscription.onData((data) {
     /// Here we have event of current bloc and also state of other bloc  
      OtherBlocState otherState = data as OtherBlocState;
      print('otherState: $otherState');
    });

}
```

**Comment by ThangVuNguyenViet** [comment]
Hi @felangel , can you share what's the best practice when it comes to sharing data between blocs?

Should it be the bloc-to-bloc communication as you described in the todo tutorial, maybe a year ago, or we go with the shared repository?

**Comment by gabrimatic** [comment]
> ddSubscription = addBloc.stream.listen((state) {        
>          if (state.fstatus == true) {
>           add(MainAddItem(Item(desc: state.desc.text)));
>         }

I did this, and I got this error:

> Error: Could not find the correct Provider<RemoteCubit> above this Widget


To fix the issue, I did this:
```
BlocProvider(
      create: (context) => AddBloc(),
      child: BlocProvider(
        create: (context) => MainBloc(
          addBloc: context.read<AddBloc>(),
        ),
        child: Scaffold(
        ...
```

**Comment by danielroek** [comment]
Try wrapping the second BlocProvider in a Builder widget
