### ISSUE TITLE
Give (Multi)BlocProvider a builder parameter

### ISSUE THREAD

**Issue by danielroek** [felangel/bloc#2587]
**Describe the issue**

When not defining a bloc in the `BlocBuilder` parameters the following exception is thrown. This got me thinking, when using `BlocProvider` we need to wrap the child in a `Builder` to be able to access the bloc in it's immediate children. 

This feature will help users by not needing to warp the child in a `Builder` but to just use a `builder` parameter in the `BlocProvider` 

**The message when the exception is thrown:**

The following ProviderNotFoundException was thrown building _BodyBuilder:
Error: Could not find the correct Provider<CounterCubit> above this BlocBuilder<CounterCubit, int> Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your `main.dart` and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that BlocBuilder<CounterCubit, int> is under your MultiProvider/Provider<CounterCubit>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>()),
    ),
  }
  ```

  consider using `builder` like so:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context) {
        // No longer throws
        return Text(context.watch<Example>()),
      }
    ),
  }
  ```

**Expected behavior**
instead of this:
```
            BlocProvider(
              create: (context) => _counterCubit,
              child: Builder(
                builder: (ctx) => BlocBuilder<CounterCubit, int>(
                  bloc: BlocProvider.of<CounterCubit>(ctx),
                  builder: (context, state) {
                    return Text(
                      '$state',
                      style: Theme.of(context).textTheme.headline4,
                    );
                  },
                ),
```
Do this:
```
            BlocProvider(
              create: (context) => _counterCubit,
              builder: (ctx) => BlocBuilder<CounterCubit, int>(
                bloc: BlocProvider.of<CounterCubit>(ctx),
                builder: (context, state) {
                  return Text(
                    '$state',
                    style: Theme
                        .of(context)
                        .textTheme
                        .headline4,
                  );
                },
              ),
            ),

```

**Comment by felangel** [comment]
Hi @danielroek 👋
Thanks for opening an issue!

I would highly advise against this pattern because it tightly couples the widget providing the bloc and the widget consuming the bloc making it extremely difficult to widget test your features. See https://github.com/felangel/bloc/issues/1321#issuecomment-646994310.

Let me know what you think 👍

**Comment by danielroek** [comment]
Alright, my idea was that the provider part is giving the error to use the builder param, but there's no support for it in the bloc framework. It might be confusing for new developers using bloc.
