### ISSUE TITLE
Initial state not exposed by stream

### ISSUE THREAD

**Issue by tynn** [felangel/bloc#2591]
**Describe the bug**
The initial state provided to the constructor is not available with the exposed stream.

**To Reproduce**

Listen to the stream within a BLOC constructor.

    SomeBloc(this.repo) : super(SomeState.init()) {
      _subscription = stream.listen((state) => add(SomeEvent(state)));
    }

**Expected behavior**
The initial state should be emitted.

**Additional context**

This implementation could be used to update a state dependend on state changes itself.

As a workaround I used `stream.startWith(state)` and everything worked fine.

**Comment by felangel** [comment]
Hi @tynn 👋 
Thanks for opening an issue!

Only state changes are emitted and the initial state is not considered a state change. As you mentioned you can use `startWith` or you can query the initial state via the `state` getter if you need to include the initial state.

Hope that helps 👍

**Comment by tynn** [comment]
Hej @felangel I was not fully sure about it at all.

Since the `stream` is _The current state stream_ and the initial `state` is be returned by _The current state_, I assumed that the current state would be emitted by the `stream` as well. But I think the whole stream is not buffered.

The workaround works perfectly fine :+1: and seems to be fully appropriate. Thanks for your insight and help!
