### ISSUE TITLE
[Docs] Add a full example app using hydrated bloc

### ISSUE THREAD

**Issue by Cyberavater** [felangel/bloc#2594]
Hi, I'm relatively new to this package and flutter altogether. So, It'd be nice if you could add an example app using hydrated bloc as you've done with the bloc here, https://bloclibrary.dev/#/fluttertimertutorial

Thank you very much for your wonderful work in this field! <3

**Comment by felangel** [comment]
Hi @Cyberavater 👋
Thanks for opening an issue!

The [Weather Tutorial](https://bloclibrary.dev/#/flutterweathertutorial) illustrates how to use the hydrated_bloc package. Let me know if that helps 👍

**Comment by Cyberavater** [comment]
Yes, this was exactly what I was looking for! (maybe, I should've looked further :P) I think adding this link here https://pub.dev/packages/hydrated_bloc would be helpful for newcomers like me. Anyways, thanks for your guide and support, really appreciate ya! 🥰

**Comment by felangel** [comment]
> Yes, this was exactly what I was looking for! (maybe, I should've looked further :P) I think adding this link here https://pub.dev/packages/hydrated_bloc would be helpful for newcomers like me. Anyways, thanks for your guide and support, really appreciate ya! 🥰

Thanks! Yeah good call, I’ll update the README 👍
