### ISSUE TITLE
I have a map<string,dynamic> data. I try change value it and create new map from it but bloc not re-render

### ISSUE THREAD

**Issue by gamestap99** [felangel/bloc#2601]
Map<int, List<Map<String, dynamic>>> imagesDoc;
    // yield state.copyWith(
    //   deletingStatus: DeletingStatus.loading,
    // );

    if (state.imagesDoc != null) {
      imagesDoc = Map.from(state.imagesDoc!);
    } else {
      imagesDoc = new Map();
    }
    // Map<int, bool> conditionDoc = Map.from(state.conditionDoc);

    imagesDoc[event.code]!.removeAt(event.index);

    yield state.copyWith(
      // deletingStatus: DeletingStatus.success,
      imagesDoc: imagesDoc,
    );

**Comment by felangel** [comment]
Hi @gamestap99 👋 
Thanks for opening an issue!

You should avoid mutating and maintaining a single reference. In this case the reference to `imagesDoc` is the same so even though the value is change, the value is identical which results in no state changes. Instead I recommend creating a new instance each time. If you're still having trouble can you please provide a minimal reproduction sample that illustrates the issue you're facing? Thanks! 🙏

**Comment by felangel** [comment]
Closing for now but feel free to provide a reproduction sample and I'm happy to take a closer look 👍

**Comment by gamestap99** [comment]
> Closing for now but feel free to provide a reproduction sample and I'm happy to take a closer look 👍

Thank for reading. Well I added a status and changed it with map, so UI can re-render. this is one way but i still feel it is not good.

**Comment by gamestap99** [comment]
> Closing for now but feel free to provide a reproduction sample and I'm happy to take a closer look 👍

this is function use map.

 Widget buildGridView(int code) {
    return BlocBuilder<AccountVerifyEditBloc, AccountVerifyEditState>(builder: (context, state) {
      return GridView.count(
        scrollDirection: Axis.vertical,
        shrinkWrap: true,
        crossAxisCount: 3,
        crossAxisSpacing: 5.0,
        mainAxisSpacing: 5.0,
        physics: NeverScrollableScrollPhysics(),
        padding: EdgeInsets.only(
          left: Responsive().setWidth(1.39),
          right: Responsive().setWidth(1.39),
          top: Responsive().setHeight(0.625),
          bottom: Responsive().setHeight(0.625),
        ),
        children: List.generate(
          state.imagesDoc[code]!.length,
          (index) {
            return Stack(
              alignment: const Alignment(1.4, -1.4),
              children: <Widget>[
                Container(
                  decoration: BoxDecoration(
                    color: MyColor.whiteOpacity20,
                    border: Border.all(
                      color: MyColor.light,
                    ),
                  ),
                  height: 100,
                  width: 100,
                ),
                Container(
                  width: 100,
                  height: 100,
                  color: Colors.white,
                  child: state.imagesDoc[code]![index]["image"] is String
                      ? Image.network(
                          state.imagesDoc[code]![index]["image"],
                          fit: BoxFit.fill,
                          loadingBuilder: (BuildContext context, Widget child, ImageChunkEvent? loadingProgress) {
                            if (loadingProgress == null) return child;
                            return Center(
                              child: CircularProgressIndicator(
                                value: loadingProgress.expectedTotalBytes != null ? loadingProgress.cumulativeBytesLoaded / loadingProgress.expectedTotalBytes! : null,
                              ),
                            );
                          },
                          errorBuilder: (BuildContext context, Object error, StackTrace? stackTrace) {
                            return Image.asset(Img.noImage);
                          },
                        )
                      : Image(
                          image: AssetEntityImageProvider(
                            state.imagesDoc[code]![index]["image"],
                            isOriginal: false,
                          ),
                          fit: BoxFit.cover,
                          height: 100,
                          width: 100,
                        ),
                ),
                state.imagesDoc[code]![index]["image"] is String
                    ? Center(
                        child: Container(
                          child: state.imagesDoc[code]![index]["status"].toString() == "1"
                              ? Icon(
                                  Icons.check_circle_outline,
                                  color: MyColor.main,
                                )
                              : IconButton(
                                  icon: Icon(
                                    Icons.error_outlined,
                                    color: Colors.red,
                                  ),
                                  onPressed: () {
                                    loadAsset(code, index);
                                  },
                                ),
                        ),
                      )
                    : Center(
                        child: Text(""),
                      ),
                Visibility(
                  visible: state.imagesDoc[code]![index]["isChange"] && state.imagesDoc[code]![index]["is_up"],
                  child: Container(
                    color: MyColor.white.withOpacity(0.6),
                    child: Center(
                      child: !state.imagesDoc[code]![index]["isUploadError"]
                          ? Icon(
                              Icons.cloud_upload_sharp,
                              color: Colors.red,
                            )
                          : Icon(
                              Icons.check,
                              color: Colors.green,
                            ),
                    ),
                  ),
                ),
                Visibility(
                  visible: widget.type == "add"
                      ? true
                      : state.imagesDoc[code]![index]["status"].toString() == "1"
                      ? false
                      : true,
                  child: Align(
                      alignment: const Alignment(1.5, -1.5),
                      child: IconButton(
                          padding: EdgeInsets.fromLTRB(8, 0, 0, 8),
                          onPressed: () {
                            _buildDialogDelete(code, index, _accountVerifyEditBloc);
                          },
                          icon: Icon(
                            Icons.delete,
                            color: Colors.red,
                          ))),
                ),
              ],
            );
          },
        ),
      );
    });
  }

**Comment by gamestap99** [comment]
> Closing for now but feel free to provide a reproduction sample and I'm happy to take a closer look 👍

The issue is closed but i hope you reply it. Sorry, i reply to late
