### ISSUE TITLE
Meaningless lazy initialization

### ISSUE THREAD

**Issue by PlugFox** [felangel/bloc#2607]
https://github.com/felangel/bloc/blob/78996f92595d3b63c544d325ab12e70e392aeeaf/packages/bloc/lib/src/bloc.dart#L56-L59

Try to change to:
```dart
  StreamController<Event>? __eventController;
  StreamController<Event> get _eventController {
    return __eventController ??= () {
     print('Hello world!');
     return StreamController<Event>.broadcast();
    } ();
  }
```

Create simple instanse of bloc (without emit any event) and see at console.

This is because you sub on controller with constructor:
https://github.com/felangel/bloc/blob/78996f92595d3b63c544d325ab12e70e392aeeaf/packages/bloc/lib/src/bloc.dart#L224

Need to replace with simple init:
```dart
final StreamController<Event> _eventController =
      StreamController<Event>.broadcast();
```

**Comment by felangel** [comment]
Good call, made the change to simplify this in #2608
