### ISSUE TITLE
[VS Code Extension] Add quickfix option to convert a BlocProvider to a MultiBlocProvider

### ISSUE THREAD

**Issue by frameset** [felangel/bloc#2610]
**Is your feature request related to a problem? Please describe.**
Sometimes I'd like to refactor my code to add an extra bloc injection where there was only a single one. It's a minor hassle to refactor my BlocProvider to be a MultiBlocProvider.

**Describe the solution you'd like**
It would be cool if the already excellent quickfix/lightbulb menu could detect when I'm in a BlocProvider and offer an automated way to convert it to a MultiBlocProvider.

**Describe alternatives you've considered**
I've considered continuing to do it manually 😁

**Comment by mzdm** [comment]
neat idea, I would like this also for IntelliJ. I can add it for IntelliJ part, I suppose there will be a new menu item like `Convert to MultiBlocProvider` (if the caret is at the `BlocProvider`) along with other `Wrap with` menu items.

**Comment by felangel** [comment]
This is now available to intelliJ in v2.4.0 thanks to @mzdm 🎉 
I'll add this to the VSCode extension in the next few days 👍

**Comment by felangel** [comment]
This is also now available to [vscode in v5.8.0](https://marketplace.visualstudio.com/items?itemName=FelixAngelov.bloc) 🎉
