### ISSUE TITLE
widget WillPopScope problem with event 

### ISSUE THREAD

**Issue by fedeakd** [felangel/bloc#2612]
Hello I have a problem when I return to the previous page giving the button back of android, it does not allow using the event that was used last

WillPopScope(
          onWillPop: () async {
            bool _status = false;

            try {
              _status = await RouteNavegator.backBottomBarRouterNavegator();
            } catch (e) {}

            return _status;
          },
          child: DefaultTabController(
            length: 4,
            child: Scaffold(
                key: _scaffoldKey,
                appBar: PreferredSize(
                    preferredSize: Size.fromHeight(100.0), child: HomeAppBar()),
                body: HomeBodyNavegationScreen()),
          ),

**Comment by felangel** [comment]
Hi @fedeakd 👋 
Thanks for opening an issue!

This issue doesn't appear to be related to the bloc library so closing for now. Feel free to ask the [Flutter Community](https://flutter.dev/community) for help with flutter specific questions.

If you feel this is a bloc-specific issue can you please provide a minimal reproduction sample and I'm happy to take a closer look, thanks! 🙏
