### ISSUE TITLE
Implementing Riverpod package

### ISSUE THREAD

**Issue by ekremkmz** [felangel/bloc#2614]
In the future, is there a plan for implementing the Riverpod package to the bloc? Maybe inside a different package named flutter_bloc_r. Accessing the bloc without context sounds amazing!

**Comment by felangel** [comment]
Hi @ekremkmz 👋 
Thanks for opening an issue!

I believe this is a duplicate of #2100 and there is currently a package called [riverbloc](https://pub.dev/packages/riverbloc) which sounds like what you're looking for. Hope that helps 👍
