### ISSUE TITLE
Cubit Future initialState

### ISSUE THREAD

**Issue by tmxdyf** [felangel/bloc#2618]
Hope to add the following features, thank you!
```dart
class CounterCubit extends Cubit<int> {
  CounterCubit(Future<int> initialState) : super(initialState);
}
```

**Comment by felangel** [comment]
Hi @tmxdyf 👋
Thanks for opening an issue!

A bloc and cubit must always have a state as a result the initial state cannot be asynchronous. You either inject the state (await it outside the cubit) or have a loading initial state while you do the async operation.

Hope that helps 👍
