### ISSUE TITLE
How to update first page’s state when back from second page via back button

### ISSUE THREAD

**Issue by kharitonovAL** [felangel/bloc#2625]
Hi!

I’m facing with lack of knowledge in next case.

I have two pages: one with messages list, and second with detail info of selected message.

when I go from messages list page to detail info page, I change `wasSeen` property of specific message object and update this object. 

But when I came back from detail info page via back button on the `appBar`, the messages list is not updated, and message object is still marked as unread. 

So the question is how to update state when return to messages list page?

The messages list page contains the next code:
```dart

class MessagesPage extends StatefulWidget {
  @override
  _MessagesController createState() => _MessagesController();
}

class _MessagesController extends State<MessagesPage> {
  String houseId = '';

  @override
  void initState() {
    houseId = StorageService.getString(keyTopic);
    FlutterAppBadger.removeBadge();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: _buildBody(context),
    );
  }

  Widget _buildBody(BuildContext context) {
    return BlocBuilder<MessageCubit, MessageState>(builder: (context, state) {
      if (state is MessageLoading) {
        return LinearProgressIndicator();

      } else if (state is MessageLoadFailure) {
        return Center(
          child: Text('Ошибка: ${state.error}'),
        );
        
      } else if (state is MessageLoadedSuccessfully) {
        if (state.messageList.isEmpty) return Center(child: Text('Сообщений пока не поступало...'));

        return ListView.builder(
          itemCount: state.messageList.length,
          itemBuilder: (context, index) => _buildListItem(
            context: context,
            message: state.messageList[index],
          ),
        );
      }

      return Center(child: Text('Сообщений пока не поступало...'));
    });
  }

  Widget _buildListItem({required BuildContext context, required ParseMessage message}) {
    return ListTile(
        leading: CircleAvatar(
          backgroundColor: Colors.transparent,
          child: message.wasSeen! ? Icon(Icons.mail_outline) : Icon(Icons.mail),
        ),
        title: Text(
          message.title!,
          maxLines: 2,
          style: TextStyle(fontWeight: message.wasSeen! ? FontWeight.normal : FontWeight.bold),
        ),
        subtitle: Text(message.body!, maxLines: 2),
        onTap: () {
          if (!message.wasSeen!) {
            message.wasSeen = true;
            message.update();
          }

          _navigateToDetailRequestPage(context: context, message: message);
        });
  }

  void _navigateToDetailRequestPage({required BuildContext context, required ParseMessage message}) {
    Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => MessageDetailPage(message: message),
      ),
    ).then((value) => setState(() {/* update widget */}));
  }
}
```

thanks a lot!

**Comment by liPatrick** [comment]
Hi @kharitonovAL, I would suggest keeping the read state in your MessageCubit (I am assuming you have a Message class for your message, you can add the read state there). When you successfully navigate to the detail page, you can change the read state by adding an MessageReadEvent(themessage) to your bloc stream. Finally, in blocbuilder simply check your message read state and build your widget accordingly. 

Also a couple of notes: 
- You may want to consider using a bloc for your messages instead of a cubit as it seems you have to handle multiple events, which would be outside of the scope of a cubit(which is meant for simple state management, usually containing one event and one state)
- You also have to make sure to provide your bloc at the top of the widget tree of both your messagelist screen as well as your message detail screen.

**Comment by kharitonovAL** [comment]
Hi @liPatrick !
Thanks a lot for your answer!

I will try to do things in the way you recommend, and also I have few more questions accordingly to your answer:

1. You mentioned stream. But actually I have no streams in my Cubits. For example, this is my MessageCubit:
```dart

class MessageCubit extends Cubit<MessageState> {
  final MessagesRepository messagesRepository;
  final OwnerRepository ownerRepository;
  final UserRepository userRepository;
  final String houseId;

  MessageCubit({
    required this.ownerRepository,
    required this.userRepository,
    required this.messagesRepository,
    required this.houseId,
  }) : super(MessageInitial()) {
    composeParseMessageList(houseId: houseId);
  }

  Future<void> composeParseMessageList({required String houseId}) async {
    List<ParseMessage> resultList = [];
    List<ParseMessage> messagesForHouseList = [];
    List<ParseMessage> messagesForOwnerList = [];

    ParseUser? user = await userRepository.currentUser();

    if (user != null) {
      emit(MessageLoading());
      Owner owner = await ownerRepository.ownerByEmail(email: user.emailAddress!);
      messagesForHouseList = await messagesRepository.messageListForHouse(houseId: houseId);
      messagesForOwnerList = await messagesRepository.messageListForOwner(ownerId: owner.objectId!);

    } else {
      emit(MessageLoadFailure(error: 'no user'));
    }

    if (messagesForHouseList.isEmpty && messagesForOwnerList.isEmpty) emit(MessageLoadedSuccessfully([]));

    resultList = messagesForHouseList;
    resultList.addAll(messagesForOwnerList);
    resultList.sort((a, b) => ((b.date!).compareTo(a.date!)));

    emit(MessageLoadedSuccessfully(resultList));
  }

  Future<bool> updateMessageWasSeenDate({required ParseMessage message}) async {
    bool updated = await messagesRepository.updateMessageWasSeenDate(message: message);
    if (updated) {
      emit(MessageWasSeenDateUpdatedSuccessfully());
      return updated;
    } else {
      emit(MessageWasSeenDateUpdateFailure(error: 'Дата просмотра сообщения не обновлена'));
      return updated;
    }
  }
}

```

And this is my MessageState:
```dart

abstract class MessageState extends Equatable {
  const MessageState();

  @override
  List<Object> get props => [];
}

class MessageInitial extends MessageState {
  @override
  String toString() => 'MessageInitial';
}

class MessageLoading extends MessageState {
  @override
  String toString() => 'MessageLoading';
}

class MessageLoadedSuccessfully extends MessageState {
  final List<ParseMessage> messageList;

  MessageLoadedSuccessfully(this.messageList);

  @override
  String toString() => 'MessageLoadedSuccessfully';

  @override
  List<Object> get props => [messageList];
}

class MessageLoadFailure extends MessageState {
  final String error;

  MessageLoadFailure({required this.error});

  @override
  String toString() => 'MessageLoadFailure { error: $error }';
}

class MessageWasSeenDateUpdatedSuccessfully extends MessageState {
  @override
  String toString() => 'MessageWasSeenDateUpdatedSuccessfully';
}

class MessageWasSeenDateUpdateFailure extends MessageState {
  final String error;

  MessageWasSeenDateUpdateFailure({required this.error});

  @override
  String toString() => 'MessageWasSeenDateUpdateFailure { error: $error }';
}

```

I thought that there are no streams in Cubits. Am I wrong?

2. You said I may want to prefer using Bloc instead of Cubit, because I have multiple events outside the scope of Cubit. So the Cubit can't handle such cases? Or Bloc just do it better?

3. You said:
>> You also have to make sure to provide your bloc at the top of the widget tree of both your messagelist screen as well as your message detail screen.

My MessagesPage called in my `tabBar` widget looks as following:
```dart

Widget build(BuildContext context) {
    return DefaultTabController(
      length: 4, // todo return 5 when will add payments and counters
      child: Scaffold(
        appBar: AppBar(
          bottom: TabBar(isScrollable: true, tabs: [
            messageTab,
            requestTab,
            counterTab,
            profileTab // todo: return later `paymentTab` when will add payments
          ]),
          title: Text('УК Квартал'),
        ),
        body: TabBarView(
          children: [
            BlocProvider(
              create: (context) => MessageCubit(
                ownerRepository: _ownerRepository,
                userRepository: _userRepository,
                messagesRepository: _messagesRepository,
                houseId: savedTopic,
              ),
              child: MessagesPage(),
            ),
            RequestsPage(),
            CountersPage(),
//              Center(child: Text('оплатить')), // TODO: return later `paymentTab` when will add payments
            ProfilePage()
          ],
        ),
      ),
    );
  }

```

Is it what you mean by providing my bloc at the top of the widget tree of message screen and message detail screen?

Again, thank you a lot!

**Comment by liPatrick** [comment]
Yup, so when I said streams I was referring to using a bloc. I would highly recommend replacing your cubit with a bloc to handle the various events and states. Let me know how that goes.

**Comment by felangel** [comment]
Hi @kharitonovAL 👋 
Thanks for opening an issue! Are you able to provide a link to a minimal reproduction sample? I'm happy to open a pull request with a fix 👍

**Comment by kharitonovAL** [comment]
> Yup, so when I said streams I was referring to using a bloc. I would highly recommend replacing your cubit with a bloc to handle the various events and states. Let me know how that goes. 

@liPatrick thanks a lot! Will try to replace! Will post feedback later!

**Comment by felangel** [comment]
> > Yup, so when I said streams I was referring to using a bloc. I would highly recommend replacing your cubit with a bloc to handle the various events and states. Let me know how that goes.
> 
> @liPatrick thanks a lot! Will try to replace! Will post feedback later!

@kharitonovAL bloc and cubit both use streams internally and you should be able to accomplish this using both so I don't think you should try to refactor cubit to bloc. Can you share a link to a reproduction sample and I'm happy to take a look?

**Comment by kharitonovAL** [comment]
> Hi @kharitonovAL 👋 
> 
> Thanks for opening an issue! Are you able to provide a link to a minimal reproduction sample? I'm happy to open a pull request with a fix 👍 

Hi @felangel !
Unfortunately I can't share the original project code because of NDA.
Also I'm not sure that providing code sample will help here, but only in case where you will replace Cubits with Blocs instead of me (ha-ha, it was joke 🙂).
I started with Cubits, but it seems that it should be bloc.

**Comment by kharitonovAL** [comment]
> > > Yup, so when I said streams I was referring to using a bloc. I would highly recommend replacing your cubit with a bloc to handle the various events and states. Let me know how that goes.
> 
> > 
> 
> > @liPatrick thanks a lot! Will try to replace! Will post feedback later!
> 
> 
> 
> @kharitonovAL bloc and cubit both use streams internally and you should be able to accomplish this using both so I don't think you should try to refactor cubit to bloc. Can you share a link to a reproduction sample and I'm happy to take a look?

 @felangel  
Can you please explain when it should be cubit and when it should be bloc?
Thanks a lot!

**Comment by felangel** [comment]
> > > > Yup, so when I said streams I was referring to using a bloc. I would highly recommend replacing your cubit with a bloc to handle the various events and states. Let me know how that goes.
> > 
> > 
> > > 
> > 
> > 
> > > @liPatrick thanks a lot! Will try to replace! Will post feedback later!
> > 
> > 
> > @kharitonovAL bloc and cubit both use streams internally and you should be able to accomplish this using both so I don't think you should try to refactor cubit to bloc. Can you share a link to a reproduction sample and I'm happy to take a look?
> 
> @felangel
> I'm just seeking for best practices in my case.
> Can you please explain when it should be cubit and when it should be bloc?
> Thanks a lot!

Check out https://bloclibrary.dev/#/coreconcepts?id=cubit-vs-bloc

**Comment by liPatrick** [comment]
I think it is fine to use either bloc or cubit in this case. To solve your issue with the read receipt, you should add a bool read attribute to your ParseMessage class. Also, I noticed your composePraseMessageList is of type void even though you emit a type MessageState.

**Comment by kharitonovAL** [comment]
> you should add a bool read attribute to your ParseMessage class.

What do you mean? I already have `bool` read attribute in class:
```

class ParseMessage extends ParseObject implements ParseCloneable {
  static const String _keyTableName = 'Message';

  ParseMessage() : super(_keyTableName);
  ParseMessage.clone() : this();

  @override
  ParseMessage clone(Map<String, dynamic> map) => ParseMessage.clone()..fromJson(map);

  static const String keyObjectId = 'objectId';
  static const String keyTitle = 'title';
  static const String keyBody = 'body';
  static const String keyDate = 'date';
  static const String keyWasSeen = 'wasSeen';
  static const String keyOwnerId = 'ownerId';
  static const String keyHouseId = 'houseId';
  static const String keyWasSeenDate = 'wasSeenDate';

  String? get objectId => get<String>(keyObjectId);

  String? get title => get<String>(keyTitle);
  set title(String? title) => set<String>(keyTitle, title ?? 'defaultValue');

  String? get body => get<String>(keyBody);
  set body(String? body) => set<String>(keyBody, body ?? 'defaultValue');

  DateTime? get date => get<DateTime>(keyDate);
  set date(DateTime? date) => set<DateTime>(keyDate, date ?? DateTime.now().toLocal());

  DateTime? get wasSeenDate => get<DateTime>(keyWasSeenDate);
  set wasSeenDate(DateTime? wasSeenDate) => set<DateTime>(keyWasSeenDate, wasSeenDate ?? DateTime.now().toLocal());

  bool? get wasSeen => get<bool>(keyWasSeen);
  set wasSeen(bool? wasSeen) => set<bool>(keyWasSeen, wasSeen ?? false);

  String? get ownerId => get<String>(keyOwnerId);
  set ownerId(String? ownerId) => set<String>(keyOwnerId, ownerId ?? 'defaultValue');

  String? get houseId => get<String>(keyHouseId);
  set houseId(String? houseId) => set<String>(keyHouseId, houseId ?? 'defaultValue');
}

```
Or did you mean something else?

>> Also, I noticed your composePraseMessageList is of type void even though you emit a type MessageState.

What is wrong here?
I thought that in this case, instead of using `return` keyword, I just passed `reaultList` as argument in `emit` keyword. And so as there `emit` used and nothing to return, I set it to `void`. Did I misunderstand something?

Thanks!

**Comment by kharitonovAL** [comment]
> > > > > Yup, so when I said streams I was referring to using a bloc. I would highly recommend replacing your cubit with a bloc to handle the various events and states. Let me know how that goes.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > @liPatrick thanks a lot! Will try to replace! Will post feedback later!
> 
> > > 
> 
> > > 
> 
> > > @kharitonovAL bloc and cubit both use streams internally and you should be able to accomplish this using both so I don't think you should try to refactor cubit to bloc. Can you share a link to a reproduction sample and I'm happy to take a look?
> 
> > 
> 
> > @felangel
> 
> > I'm just seeking for best practices in my case.
> 
> > Can you please explain when it should be cubit and when it should be bloc?
> 
> > Thanks a lot!
> 
> 
> 
> Check out https://bloclibrary.dev/#/coreconcepts?id=cubit-vs-bloc

Thanks!

**Comment by kharitonovAL** [comment]
Hi @felangel , @liPatrick !

I think I found the way to solve my problem.

First, as @liPatrick said, I added new state `MessageWasRead`:
```dart

class MessageWasRead extends MessageState {
  final List<ParseMessage> messageList;

  MessageWasRead(this.messageList);

  @override
  String toString() => 'MessageWasRead';

  @override
  List<Object> get props => [messageList];
}

```

Then, in `MessageCubit` I added a new method:
```dart

Future<void> updateMessage({required ParseMessage message}) async {
    await messagesRepository.updateMessageWasSeenDate(message: message);

    emit(MessageLoading());
    List<ParseMessage>? list = await _loadMessages();

    if (list != null) {
      emit(MessageWasRead(list));
    } else {
      emit(MessageWasReadFailure(error: 'Дата просмотра сообщения не обновлена'));
    }
  }

```

Finally, in the first page (where the whole message list is shown) I added new `if-else` with `MesssageWasRead` state, and on message tap the following will be called:
```dart
...

onTap: () {
          context.read<MessageCubit>().updateMessage(message: message);
          _navigateToDetailRequestPage(context: context, message: message);
        });
...
```

So now there is no logic in second page (the detail message page).

Thank you, guys, you help me to find solution!
