### ISSUE TITLE
BlocListener not listening to the last state change

### ISSUE THREAD

**Issue by hman-coder** [felangel/bloc#2641]
**Describe the bug**
It is mentioned in the documentation (and other issues opened) that `BlocListener` only listens to state changes, not the initial state. I have nested two `BlocConsumer`s (which is essentially a `BlocListener` nested within a `BlocBuilder` as documentation say). The parent `BlocConsumer` builds the child `BlocConsumer` only when the `initialState` of the bloc changes - that is, after the relevant `Bloc` 's `initialState` has **changed** . When the child `BlocConsumer` is built, the listener is not triggered, even though a state change has already taken place. Subsequent changes are listened to normally.

**To Reproduce**
```
class TestApp extends StatelessWidget {
  const TestApp({Key? key}) : super(key: key);

 @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: BlocProvider<TestBloc>(
        create: (_) => TestBloc(),
        child: Scaffold(
          body: BlocConsumer<TestBloc, State>(
            listener: (context, state) => print("** level1: $state"),
            builder: (context, state) => state == State.initial
                ? Center(child: CircularProgressIndicator())
                : BlocConsumer<TestBloc, State>(
                    listener: (context, state) => print("** level2: $state"),
                    builder: (context, state) => Center(
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Text("$state"),
                          SizedBox(
                            height: 50,
                          ),
                          ElevatedButton(
                            child: Text(
                              "add retrieve event",
                            ),
                            onPressed: () =>
                                context.read<TestBloc>().add(Event.retrieve),
                          )
                        ],
                      ),
                    ),
                  ),
          ),
        ),
      ),
    );
  }
}

class TestBloc extends Bloc<Event, State> {
  TestBloc() : super(State.initial) {
    add(Event.reload);
  }

  get _delay => Future.delayed(Duration(seconds: 1));

  @override
  Stream<State> mapEventToState(Event event) async* {
    if (event == Event.reload) {
      await _delay;
      yield State.initialized;
    } else if (event == Event.retrieve) {
      yield State.loading;
      await _delay;
      yield State.data_retrieved;
    }
  }
}

enum State { initial, initialized, loading, data_retrieved}

enum Event { reload, retrieve }
```

**Expected behavior**
Since the expected behavior of a `BlocListener` is to listen to state changes [as mentioned here](https://github.com/felangel/bloc/issues/404#issuecomment-511093263) the listener should be fired in response to the last state change (not the initalState).

**Additional context**
Lifting the listener up the widget tree doesn't help. The example written above is for simplicity's sake. In the real example the `BlocListener` manipulates its widget's state (changes size).

**Comment by elianmortega** [comment]
Hello @hman-coder,

Just as mentioned in the docs the listener is going to be called on every state change other than the initial. The issue is with your implementation.

` builder: (context, state) => state == State.initial `

with this line you are toggling the construction of the nested `BlocConsumer` so:

on `State.initial` your widget tree is this one:

`BlocConsumer1` -> `LoadingProgressIndicator`

then state changes to `State.initalized` and the widget tree rebuilds to:

`BlocConsumer1` -> `BlocConsumer2`

Soo when the `BlocConsumer2` is built the state was already `State.initialized` so as no state changed (from the BlocConsumer2 scope ) the listener callback is not called.


Hope you get the idea with the above explanation. Let me know if you still don't see it 👍

**Comment by hman-coder** [comment]
@elianmortega Thank you for the response.
I do see what you're saying, but the documentation say that the listener doesn't trigger on the `Bloc`'s initial state, but rather on every state change thereon. Well, isn't the change from `State.initial` to `State.initialized` considered a **state change**? Subsequently, wouldn't it make more sense if the `listener` is triggered according to the last state change (if any) in the bloc once the `BlocListener`/`BlocConsumer` is built?

**Comment by elianmortega** [comment]
Hey @hman-coder 

Yes the change from `State.initial` to `State.initialized` is a valid state change, but as the new widget is build after that state change the listener is not triggered.

And no it wouldn't have more sense because in that scenario your `BlocListener`/`BlocConsumer` will be reacting to a state that occurred before they were even built, and no much senes on reacting to something that happened before they were created. In that scenario it will be better to rethink the logic of how you are placing the widgets on the screen.

**Comment by Gene-Dana** [comment]
Hey guys 👋🏼 The way I've solved this is by calling a function/event in the bloc constructor body, right next to where you ideally put the stream.` If (state is initial) then go fetch data`

**Comment by hman-coder** [comment]
> Hey @hman-coder
> 
> Yes the change from `State.initial` to `State.initialized` is a valid state change, but as the new widget is build after that state change the listener is not triggered.
> 
> And no it wouldn't have more sense because in that scenario your `BlocListener`/`BlocConsumer` will be reacting to a state that occurred before they were even built, and no much senes on reacting to something that happened before they were created. In that scenario it will be better to rethink the logic of how you are placing the widgets on the screen.

Thank you for your patience and for elaborating. It does make sense now. I have fixed the problem by transforming the lowermost widget to a `StatefulWidget` and triggering the listener once in `initState`


> Hey guys 👋🏼 The way I've solved this is by calling a function/event in the bloc constructor body, right next to where you ideally put the stream.` If (state is initial) then go fetch data`

This doesn't solve the problem I stated. If you check my code you can see I already have a call in the constructor body.

**Comment by felangel** [comment]
@hman-coder just catching up on issues -- is there anything else I can help with or do you feel your issue has been resolved?

**Comment by hman-coder** [comment]
@felangel the issue has been resolved. However, I do suggest adding something like `onFirstBuild` optional parameter so that we don't have to go through the extra process of building a `StatefulWidget` to do something in `onInit` -- it feels like a hack. I have seen multiple issues opened with complaints/requests similar (but not identical) to mine.

However, I think this can be discussed in a feature request.

**Comment by TinhHuynh** [comment]
Hi @felangel 
May I know if you have any plan to support the `onFirstBuild` parameter? This is very useful for cases where: multiple screens using the same Cubit.

> @felangel the issue has been resolved. However, I do suggest adding something like `onFirstBuild` optional parameter so that we don't have to go through the extra process of building a `StatefulWidget` to do something in `onInit` -- it feels like a hack. I have seen multiple issues opened with complaints/requests similar (but not identical) to mine.
> 
> However, I think this can be discussed in a feature request. Thank you.
