### ISSUE TITLE
Help needed with code for using BLoC to get the state of the device's internet connection

### ISSUE THREAD

**Issue by flutternoob** [felangel/bloc#2649]
I am trying to use the BLoC library with the connectivity_plus plugin in Flutter. I have followed this [post](https://stackoverflow.com/questions/67104382/how-could-i-check-connectivity-using-cubit/67107250#67107250) and this [post](https://stackoverflow.com/questions/49648022/check-whether-there-is-an-internet-connection-available-on-flutter-app/68436867#68436867) to set up an Internet Cubit for the project. The code works fine when the app is started with the internet connection turned on.

However, with the internet connection turned off, if I kill the app and re-launch it or do a hot restart, the ```CircularProgressIndicator()``` is shown instead of ```Text("Internet Disconnected")```.

Turning the internet back on correctly shows ```Text("Internet Connected")``` widget. After this, If I turn off the internet connection again, this time around it correctly shows the ```Text("Internet Disconnected")``` widget.

Also, ```emitInternetDisconnected``` is not caught as an exception in the try catch block to update the app's state.

The problem with the ```CircularProgressIndicator()``` being always displayed with the internet disconnected occurs only when the app is re-launched or hot restarted. I cannot figure out the bug in my code. What should I do to fix my code? Thanks

This is the code in the ```internet_cubit.dart``` file

```
import 'dart:async';
import 'dart:io';

import 'package:bloc/bloc.dart';
import 'package:connectivity_plus/connectivity_plus.dart';

import 'internet_enum.dart';

part 'internet_state.dart';

class InternetCubit extends Cubit<InternetState> {
  final Connectivity? connectivity;
  StreamSubscription? connectivityStreamSubscription;

  InternetCubit({required this.connectivity}) : super(InternetLoading()) {
    monitorInternetConnection();
  }

  void monitorInternetConnection() async {
    connectivityStreamSubscription =
        connectivity!.onConnectivityChanged.listen((connectivityResult) async {
      try {
        final result = await InternetAddress.lookup("example.com");
        if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
          if (connectivityResult == ConnectivityResult.wifi) {
            emitInternetConnected(ConnectionType.WiFi);
          } else if (connectivityResult == ConnectivityResult.mobile) {
            emitInternetConnected(ConnectionType.Mobile);
          } else if (connectivityResult == ConnectivityResult.none) {
            emitInternetDisconnected();
          }
        }
      } on SocketException catch (_) {
        emitInternetDisconnected();
      }
    });
  }

  void emitInternetConnected(ConnectionType _connectionType) =>
      emit(InternetConnected(connectionType: _connectionType));

  void emitInternetDisconnected() => emit(InternetDisconnected());

  @override
  Future<void> close() async {
    connectivityStreamSubscription!.cancel();
    return super.close();
  }
}
```

This is the code in the ```internet_state.dart``` file

```
part of 'internet_cubit.dart';

abstract class InternetState {}

class InternetLoading extends InternetState {}

class InternetConnected extends InternetState {
  final ConnectionType? connectionType;

  InternetConnected({required this.connectionType});
}

class InternetDisconnected extends InternetState {}
```

This is the code in my ```main.dart``` file

```
import 'package:flutter/material.dart';

import 'package:flutter_bloc/flutter_bloc.dart';

import 'package:connectivity_plus/connectivity_plus.dart';

import 'internet_cubit.dart';

void main() {
  runApp(
    BlocProvider<InternetCubit>(
      create: (_) => InternetCubit(connectivity: Connectivity()),
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter BLoC Demo',
      home: SafeArea(
        child: Scaffold(
          appBar: AppBar(
            title: Text("Flutter BLoC Demo"),
            centerTitle: true,
            backgroundColor: Colors.blue[900],
          ),
          body: Center(
            child: Builder(
              builder: (context) {
                return MaterialButton(
                    onPressed: () {
                      Navigator.push(context, MaterialPageRoute(builder: (context) => ScreenOne()));
                    },
                    color: Colors.black,
                    textColor: Colors.white,
                    child: Text("Screen 1"));
              },
            ),
          ),
        ),
      ),
    );
  }
}

class ScreenOne extends StatelessWidget {
  const ScreenOne({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          title: Text("Flutter BLoC Demo"),
          centerTitle: true,
          backgroundColor: Colors.blue[900],
        ),
        body: Center(
          child: BlocBuilder<InternetCubit, InternetState>(
            builder: (_, state) {
              if (state is InternetDisconnected) {
                return Text("Internet disconnected");
              } else if (state is InternetConnected) {
                return Text("Internet connected");
              }
              return CircularProgressIndicator();
            },
          ),
        ),
      ),
    );
  }
}
```

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 What we can tell from the CircleProgressIndicator is that your InternetCubit is neither in the connected or disconnected state and I suspect it has something to do with the stream in the bloc constructor body - that is where I would start to debug.

What I notice is that the default state is `super(InternetLoading())` then in `void monitorInternetConnection() async {` you do not have an else statement in the case that this `if (result.isNotEmpty && result[0].rawAddress.isNotEmpty)` is not true.

Do you have a bloc observer set up? Something like [this? ](https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/lib/app/bloc_observer.dart)

This will help you debug events and what's firing.

It's a tedious process to track these problems down, no matter how much experience you have ! Let me know if you get stuck even more !

**Comment by flutternoob** [comment]
Hi @Gene-Dana Thank you for your response. I made some changes to changes to the ```try catch``` block. Instead of 

`else if (connectivityResult == ConnectivityResult.none){
            emitInternetDisconnected();
}`

I did:

```else {emitInternetDisconnected();}```

I also added the above ```else``` clause for ```if (result.isNotEmpty && result[0].rawAddress.isNotEmpty)```. However, the problem persists.

I do not know how to set up a BlocObserver for my use case.

**Comment by Gene-Dana** [comment]
Just like every example, you can attach the observer right in the main.dart ! 

```dart
void main() {
  Bloc.observer = AppBlocObserver();
...
```

Note: You can add this file directly to your project and import it, or just copy-paste the class itself to the main.dart 

```dart
import 'dart:developer';

import 'package:bloc/bloc.dart';

class AppBlocObserver extends BlocObserver {
  @override
  void onChange(BlocBase bloc, Change change) {
    super.onChange(bloc, change);
    log('onChange: ${bloc.runtimeType},\nCurrent state: ${change.currentState}\nNext state: ${change.nextState}');
  }

  @override
  void onError(BlocBase bloc, Object error, StackTrace stackTrace) {
    log('onError(${bloc.runtimeType}, $error, $stackTrace)');
    super.onError(bloc, error, stackTrace);
  }
}
```

**Comment by flutternoob** [comment]
@Gene-Dana Based on your guidance, I made the following changes to the ```AppBlocObserver``` class:

```
class AppBlocObserver extends BlocObserver {
  @override
  void onChange(BlocBase bloc, Change change) {
    super.onChange(bloc, change);
    log('onChange: ${bloc.runtimeType}, ${bloc.state} \nCurrent state: ${change.currentState}\nNext state: ${change.nextState}');
  }

  @override
  void onError(BlocBase bloc, Object error, StackTrace stackTrace) {
    log('onError(${bloc.runtimeType}, ${bloc.state}, $error, $stackTrace)');
    super.onError(bloc, error, stackTrace);
  }

  @override
  void onEvent(Bloc bloc, Object? event) {
    log('onEvent(${bloc.state}, ${bloc.runtimeType}, $event)');
    super.onEvent(bloc, event);
  }

  @override
  void onTransition(Bloc bloc, Transition transition) {
    log('onTransition(${bloc.state}, ${bloc.runtimeType}, ${transition.currentState}, ${transition.nextState})');
    super.onTransition(bloc, transition);
  }

  @override
  void onCreate(BlocBase bloc) {
    log('onCreate(${bloc.state}, ${bloc.runtimeType})');
    super.onCreate(bloc);
  }

  @override
  void onClose(BlocBase bloc) {
    log('onTransition(${bloc.state}, ${bloc.runtimeType})');
    super.onClose(bloc);
  }
}
```

There are no error logs triggered in the console. 

```onCreate()``` triggers the following log when the app is hot re-started or killed and then re-launched with the internet off

```
[log] onCreate(Instance of 'InternetLoading', InternetCubit)
```

In the app hot-restart/re-launch with the internet off, ```onChange()``` triggers the following log when the internet is switched back on:

```
[log] onChange: InternetCubit, Instance of 'InternetLoading' 
Current state: Instance of 'InternetLoading'
Next state: Instance of 'InternetConnected'
```

And when the internet is switched off from on, ```onChange()``` triggers the following log:

```
[log] onChange: InternetCubit, Instance of 'InternetConnected' 
Current state: Instance of 'InternetConnected'
Next state: Instance of 'InternetDisconnected'
```

**Comment by flutternoob** [comment]
@Gene-Dana I suspected the problem to lie with my Internet connection at the network layer, so I tried a different approach. I will post my solution here so that it can be useful to someone with a similar problem.

First, I modified the ```internet_cubit.dart``` and ```internet_state.dart``` files like so:

```
import 'dart:async';

import 'package:bloc/bloc.dart';
import 'package:connectivity_plus/connectivity_plus.dart';

import 'internet_enum.dart';

part 'internet_state.dart';

class InternetCubit extends Cubit<InternetConnectionTypeState> {
  final Connectivity? connectivity;
  // ignore: cancel_subscriptions
  StreamSubscription? internetConnectionTypeStreamSubscription;

  InternetCubit({required this.connectivity}) : super(InternetConnectionTypeLoading()) {
    monitorConnectionType();
  }

  void monitorConnectionType() async {
    internetConnectionTypeStreamSubscription =
        connectivity!.onConnectivityChanged.listen((connectivityResult) async {
      if (connectivityResult == ConnectivityResult.wifi) {
        emitConnectionType(ConnectionType.WiFi);
      } else if (connectivityResult == ConnectivityResult.mobile) {
        emitConnectionType(ConnectionType.Mobile);
      }
    });
  }

  void emitConnectionType(ConnectionType _connectionType) =>
      emit(InternetConnectionType(connectionType: _connectionType));

  @override
  Future<void> close() async {
    internetConnectionTypeStreamSubscription!.cancel();
    return super.close();
  }
}
```

```
part of 'internet_cubit.dart';

abstract class InternetConnectionTypeState {}

class InternetConnectionTypeLoading extends InternetConnectionTypeState {}

class InternetConnectionType extends InternetConnectionTypeState {
  final ConnectionType? connectionType;

  InternetConnectionType({required this.connectionType});
}
```

This is the ```internet_enum.dart``` file:

```
enum ConnectionType {
  WiFi, Mobile
}
```

Next, I imported the ```internet_connection_checker``` [package](https://pub.dev/packages/internet_connection_checker). I created a new ```cubit``` ```class``` called ```ConnectionCheckerCubit```. Following the above code as a guide and the documentation for the ```internet_connection_checker``` package, here is the code for the ```connection_cubit.dart``` and the ```connection_state.dart``` file.

```
import 'dart:async';

import 'package:bloc/bloc.dart';
import 'package:internet_connection_checker/internet_connection_checker.dart';

part 'connection_state.dart';

class ConnectionCheckerCubit extends Cubit<ConnectionCheckerState> {
  final InternetConnectionChecker? internetConnectionChecker;

  ConnectionCheckerCubit({required this.internetConnectionChecker}) : super(InternetConnectionLoading()) {
    monitorInternetConnection();
  }

  // ignore: cancel_subscriptions
  StreamSubscription? internetConnectionStreamSubscription;

  void monitorInternetConnection() async {
    internetConnectionStreamSubscription = InternetConnectionChecker().onStatusChange.listen((status) {
      switch (status) {
        case InternetConnectionStatus.connected:
          emitInternetConnectionConnected(InternetConnectionStatus.connected);
          break;
        case InternetConnectionStatus.disconnected:
          emitInternetConnectionDisconnected();
          break;
      }
    });
  }

  void emitInternetConnectionConnected(InternetConnectionStatus _internetConnectionStatus) =>
      emit(InternetConnectionConnected(internetConnectionStatus: _internetConnectionStatus));

  void emitInternetConnectionDisconnected() => emit(InternetConnectionDisconnected());

  @override
  Future<void> close() async {
    internetConnectionStreamSubscription!.cancel();
    return super.close();
  }
}
```

```
part of 'connection_cubit.dart';

abstract class ConnectionCheckerState {}

class InternetConnectionLoading extends ConnectionCheckerState {}

class InternetConnectionConnected extends ConnectionCheckerState {
  final InternetConnectionStatus? internetConnectionStatus;

  InternetConnectionConnected({required this.internetConnectionStatus});
}

class InternetConnectionDisconnected extends ConnectionCheckerState {}
```

In the ```main.dart``` file, I used a ```MultiBlocProvider``` in the ```main()``` function as a wrapper for ```runApp```. In the ```ScreenOne``` widget, I used two nested ```BlocBuilder``` widgets. One is used to check the status of the internet connection. If the device is connected to the internet, then another ```BlocBuilder``` is used to return the type of Internet Connection, which can be a WiFi connection or a Mobile connection. Also, I have added a ```AppBlocObserver``` class for debugging purposes. Here is the code for the ```main.dart``` file:

```
void main() {

  Bloc.observer = AppBlocObserver();
  runApp(
    MultiBlocProvider(
      providers: [
        BlocProvider<ConnectionCheckerCubit>(
          create: (_) => ConnectionCheckerCubit(internetConnectionChecker: InternetConnectionChecker()),
        ),
        BlocProvider<InternetCubit>(
          create: (_) => InternetCubit(connectivity: Connectivity()),
        ),
      ],
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter BLoC Demo',
      home: SafeArea(
        child: Scaffold(
          appBar: AppBar(
            title: Text("Flutter BLoC Demo"),
            centerTitle: true,
            backgroundColor: Colors.blue[900],
          ),
          body: Center(
            child: Builder(
              builder: (context) {
                return MaterialButton(
                    onPressed: () {
                      Navigator.push(context, MaterialPageRoute(builder: (context) => ScreenOne()));
                    },
                    color: Colors.black,
                    textColor: Colors.white,
                    child: Text("Screen 1"));
              },
            ),
          ),
        ),
      ),
    );
  }
}

class ScreenOne extends StatelessWidget {
  const ScreenOne({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          title: Text("Flutter BLoC Demo"),
          centerTitle: true,
          backgroundColor: Colors.blue[900],
        ),
        body: Center(
          child: BlocBuilder<ConnectionCheckerCubit, ConnectionCheckerState>(
            builder: (_, state) {
              if (state is InternetConnectionDisconnected) {
                return Text("Internet disconnected");
              } else if (state is InternetConnectionConnected) {
                return BlocBuilder<InternetCubit, InternetConnectionTypeState>(
                    builder: (_, state) {
                      if (state is InternetConnectionType && state.connectionType == ConnectionType.WiFi) {
                        return Text("WiFi");
                      } else {
                        return Text("Mobile");
                      }
                    }
                );
              }
              return CircularProgressIndicator();
            },
          ),
        ),
      ),
    );
  }
}

class AppBlocObserver extends BlocObserver {
  @override
  void onChange(BlocBase bloc, Change change) {
    super.onChange(bloc, change);
    log('onChange: ${bloc.runtimeType}, ${bloc.state} \nCurrent state: ${change.currentState}\nNext state: ${change.nextState}');
  }

  @override
  void onError(BlocBase bloc, Object error, StackTrace stackTrace) {
    log('onError(${bloc.runtimeType}, ${bloc.state}, $error, $stackTrace)');
    super.onError(bloc, error, stackTrace);
  }

  @override
  void onEvent(Bloc bloc, Object? event) {
    log('onEvent(${bloc.state}, ${bloc.runtimeType}, $event)');
    super.onEvent(bloc, event);
  }

  @override
  void onTransition(Bloc bloc, Transition transition) {
    log('onTransition(${bloc.state}, ${bloc.runtimeType}, ${transition.currentState}, ${transition.nextState})');
    super.onTransition(bloc, transition);
  }

  @override
  void onCreate(BlocBase bloc) {
    log('onCreate(${bloc.state}, ${bloc.runtimeType})');
    super.onCreate(bloc);
  }

  @override
  void onClose(BlocBase bloc) {
    log('onTransition(${bloc.state}, ${bloc.runtimeType})');
    super.onClose(bloc);
  }
}
```

If there is a better way than using nested ```BlocBuilder``` widgets, do let me know. I couldn't figure out how to use a ```BlocConsumer``` that uses a listener to listen to ```ConnectionCheckerCubit``` and then uses the ```BlocConsumer```'s ```builder``` property to return a widget based on the type of internet connection. I couldn't figure out how to call each of the cubit's ```close``` function either. I was also wondering - will it be possible to have a ```MultiBlocBuilder``` widget as part of the ```flutter_bloc``` library? It would also be great if an example existed for users to determine the status of in an internet connection using the ```bloc``` and ```flutter_bloc``` libraries. Thanks

**Comment by Gene-Dana** [comment]
Ever since 6.0.0, you can essentially make a blocbuilder with this code. 

```dart

final connectionState = context.watch<ConnectionCheckerCubit>().state.internetConnectionStatus

```

any time this state is updated, any UI that is attached to it will rebuild also ! You can use this as your 'MultiBlocBuilder' by just making more in one file!

**Comment by flutternoob** [comment]
Thank you very much. I revised the ```ScreenOne``` widget like so:

```
class ScreenOne extends StatelessWidget {
  const ScreenOne({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
        appBar: AppBar(
          title: Text("Flutter BLoC Demo"),
          centerTitle: true,
          backgroundColor: Colors.blue[900],
        ),
        body: Center(
          child: BlocBuilder<InternetCubit, InternetConnectionTypeState>(
            builder: (_, state) {
              final connectionState = context.watch<ConnectionCheckerCubit>().state;
              if (connectionState is InternetConnectionDisconnected)
                return Text("Internet Disconnected");
              else if (connectionState is InternetConnectionConnected){
                if (state is InternetConnectionType && state.connectionType == ConnectionType.WiFi)
                  return Text("WiFi");
                else
                  return Text("Mobile");
              }
              return CircularProgressIndicator();
            },
          ),
        ),
      ),
    );
  }
}
```

After converting ```ScreenOne``` to a ```Stateful``` widget, how do I call each of the cubit's close functions in the widget's ```dispose()``` function?

**Comment by felangel** [comment]
> Thank you very much. I revised the `ScreenOne` widget like so:
> 
> ```
> class ScreenOne extends StatelessWidget {
>   const ScreenOne({Key? key}) : super(key: key);
> 
>   @override
>   Widget build(BuildContext context) {
>     return SafeArea(
>       child: Scaffold(
>         appBar: AppBar(
>           title: Text("Flutter BLoC Demo"),
>           centerTitle: true,
>           backgroundColor: Colors.blue[900],
>         ),
>         body: Center(
>           child: Builder(
>             builder: (context) {
>               final connectionState = context.watch<ConnectionCheckerCubit>().state;
>               final internetTypeState = context.watch<InternetCubit>().state;
>               if (connectionState is InternetConnectionDisconnected)
>                 return Text("Internet Disconnected");
>               else if (connectionState is InternetConnectionConnected){
>                 if (internetTypeState is InternetConnectionType && internetTypeState.connectionType == ConnectionType.WiFi)
>                   return Text("WiFi");
>                 else
>                   return Text("Mobile");
>               }
>               return CircularProgressIndicator();
>             }
>           )
>         ),
>       ),
>     );
>   }
> }
> ```
> 
> After converting `ScreenOne` to a `Stateful` widget, how do I call each of the cubit's close methods in the widget's `dispose()` function?

If you used `BlocProvider` to create the cubit you do not need to explicitly close the cubits (it is automatically handled by BlocProvider). If you manually create the cubit instances then you can override the `dispose` method in your `State` class and call `close` on each cubit explicitly. It is generally better to use `BlocProvider` and avoid manually managing the cubits yourself.

Hope that helps!

Closing for now but feel free to comment with additional questions or if you haven't already join the [bloc discord server](https://discord.gg/bloc) to chat with other members of the community 👍
