### ISSUE TITLE
BlocBuilder with BuildWhen

### ISSUE THREAD

**Issue by bloodtearvn** [felangel/bloc#2652]
Hi,
I have a screen with Scaffold widget. In this widget i have
appBar: AppBar(
         title: BlocBuilder,
         actions[BlocBuilder]
),
body: BlocBuilder()
bottomSheet:BlocBuilder(
buildwhen(prev,curr):
var rnd = new Random();
return rnd.nextInt(100).isOdd(); <- this line if false does appbar (titile, actions), body will build (or not)?
)
May be buildwhen affect all blocbuilder?

**Comment by felangel** [comment]
Hi @bloodtearvn 👋 
Thanks for opening an issue! `buildWhen` is an optimization and does not guarantee that builder will not be called. If you want to strictly select a part of a bloc state to be available to the `builder` you can use the `BlocSelector` widget introduced in `flutter_bloc` v7.1.0. Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
