### ISSUE TITLE
[HELP] Bloc lifecycle

### ISSUE THREAD

**Issue by LVBiomas** [felangel/bloc#2653]
**Describe the bug**
Most probably this is not a bug, but ignorance in some basic flutter/bloc behavior.

**To Reproduce**
I've the following stateless widget encapsulating a report in my app:
```
class Report extends StatelessWidget {
  final String _id;

  Report(this._id);

  @override
  Widget build(BuildContext context) {
    return BlocProvider<ReportBloc>(
        create: (_) => ReportBloc(_sessionCode)..add(ReportLoadEvent(_id)),
        child: BlocBuilder<ReportBloc, ReportState>(
          builder: _buildReport,
        ));
  }
```
When state changes higher in the context, the Report widget, as exprected, is created again and again with different ids.
Then the build function is called...

**Expected behavior**
I would expect the function i pass to create to be called every time Report is instantiated (and add(ReportLoadEvent) with it), while it only gets called once.
I suspect context already contains an instance of it, can you helo me understand if this is the expected behavior and maybe point me to some documentation to explain me what's happening in detail, I fear I'm missing something in the way bloc handles the life of its blocs in the context...

**Comment by felangel** [comment]
Hi @LVBiomas 👋 
Thanks for opening an issue!

This is working as expected because `BlocProvider` uses `Provider` internally and the `create` method of provider is very similar to `initState` of a `State` class which means that unless the `BlocProvider` widget is unmounted and remounted, `create` will only be called once (even if the parent widget rebuilds). Let me know if that helps and sorry for any inconvenience!

**Comment by cedvdb** [comment]
This is very interesting to me.

This line:

`create: (_) => ReportBloc(_sessionCode)..add(ReportLoadEvent(_id))`


In my blocs I sometimes have some initialization happening that change the state of the bloc asynchronously:

```dart
  RecorderBloc()  :  super(const NoPermissions()) {
    _checkPermissions();
  }

  Future<void> _checkPermissions() async {
    final hasPerm = await _recorderSrv.askPermission();
    if (hasPerm) emit(const NotRecording());
  }
```

The problems with this is that it is hard to test. When do you test that the state has changed after the permissions have been checked ? Do you put a delay ? Do you put a synchrounous future in your mock ? do you put a field `initialized` future added as a property in the bloc that would tell my test that the permissions have been asked ?

However changing the _checkPermission to be public and checking them when creating seem to be a solution that would resolve my test problem.

```dart
create: (ctx) => RecorderBloc()..askPermissions()
```

However that looks very weird in the sens that I've not seen that anywhere else than in this issue. Is this something you would recommend ?

I went a bit on a tangeant here but I didn't want to create a separate issue for a question...

**Comment by LVBiomas** [comment]
Thanks for the explanation, I still havo to study :-)

**Comment by LVBiomas** [comment]
> This is very interesting to me.
> This line:
> `create: (_) => ReportBloc(_sessionCode)..add(ReportLoadEvent(_id))`

I've seen it used in one of my first introductory video to flutter and bloc (I come from C# and WinForms with a small experience with React).
https://www.youtube.com/watch?v=a9H8PilJ6hY&list=PL5h37q2DJtAP36eI9j9yKxbZBASUMb9eZ&index=14

Looks like you could add an event like CheckPermissionEvent to your bloc... here's some come (it's not complete and doesn't compile, I wrote just to explain what I mean):
```
BlocProvider<SomeBlocConstructor>(
        create: (_) => SomeBlocConstructor()..add(CheckPermissionEvent()),
        child: BlocBuilder<SomeBlocConstructor, SomeBlocState>(
          builder: [...],
        ));
```

```
SomeBlocConstructor() : super(DataStateLoading()) {
  @override
  Stream<SomeBlocState> mapEventToState(
      SomeBlocEvent event) async* {
    if (event is CheckPermissionEvent) {
        // Call your checkperm and yield states accordingly
    }
   //  other events
  }
}
```

**Comment by cedvdb** [comment]
I opened another issue with my comment instead. Yes the line I'm more interested about is this one:

` SomeBlocConstructor()..add(CheckPermissionEvent()`, I was wondering if adding an event upon creation was considered bad practice

**Comment by felangel** [comment]
Hi @cedvdb 👋 

I do recommend that approach (adding an event upon initialization) because it makes your bloc a lot more flexible. The bloc doesn't make any assumptions about how/when events are added. This makes it easier to reuse and test the bloc as well.

Hope that helps 👍 

Closing for now since it looks like the original question was addressed. If you have additional comments/questions I'm happy to reopen and continue the conversation, thanks! 🙏

**Comment by cedvdb** [comment]
@felangel well I continued the discussion there (which I closed because it's not really an issue but more of a design question)

https://github.com/felangel/bloc/issues/2654
