### ISSUE TITLE
[Help] testing initialization bloc_test

### ISSUE THREAD

**Issue by cedvdb** [felangel/bloc#2654]
In response of [this issue](https://github.com/felangel/bloc/issues/2653)

In my blocs I sometimes have some initialization happening that changes the state of the bloc asynchronously:

```dart
  RecorderBloc()  :  super(const NoPermissions()) {
    _checkPermissions();
  }

  Future<void> _checkPermissions() async {
    final hasPerm = await _recorderSrv.askPermission();
    if (hasPerm) emit(const NotRecording());
  }
```

The problems with this is that it is hard to test. When do you test that the state has changed after the permissions have been checked ? Do you put a delay ? Do you put a synchrounous future in your mock ? do you put a field `initialized` future added as a property in the bloc that would tell my test that the permissions have been asked ?

None of those seem to be good solutions. However changing the _checkPermission to be public and checking them when creating (like OP) seem to be a solution that would resolve my test problem.

```dart
create: (ctx) => RecorderBloc()..checkPermissions()
```

However that looks very weird in the sens that I've not seen that anywhere else than in this issue. Is this something you would recommend ?

Another example would be 

```dart
SomeBlocConstructor() : super(DataStateLoading()) {
  _dataRepository.data$.takeUntil(destroy$)
    .listen((data) => emit(DataState.loaded(data)));
}
```

Here I guess the _dataRepository mock decides of the state then

I'm thinking an init life cycle method that's guaranteed to be called by the bloc builder could resolve this, maybe ?

**Comment by irvine5k** [comment]
What's the point that you don't like in `SomeBloc()..something()`? IMHO, I prefer it over a constructor that does more than construct, it can confuse new developers, but I am also open to new approaches.

**Comment by cedvdb** [comment]
I was thinking about an initBloc similar to initState.

**Comment by irvine5k** [comment]
I think we should have a good practice guide about this scenario because we’re going to register all event handlers in constructor #2526, so, a constructor can have 3 responsibilities: object creation, event handlers registration, and a possible initialization logic.

**Comment by mkappworks** [comment]
I also have a problem with bloc testing at initialisation.

Code:

```
class BlocA extends Bloc<BlocAEvent, BlocAState> {

  BlocA(DI di) : super(BlocAInitial()) {
    on<BlocAEventStarted>((event, emit) {
      _someFunc(di);
      emit(BlocAInProgress);
    });

   on<BlocAEventPaused>((event, emit) {
      emit(BlocAPause);
    });
}
```

I want to test 

```
  blocTest<BlocA, BlocAState>(
    'When bloc is in initial setting, emits initial state',
    build: () => BlocA(Di()),
    expect: () => [BlocAInitial()],
  );
```

but I am getting the following error message

```
Expected: [BlocAInitial:BlocAInitial(0.0, false)]
  Actual: []
   Which: at location [0] is [] which shorter than expected
package:test_api                             expect
testBloc.<fn>
===== asynchronous gap ===========================
dart:async                                   _asyncThenWrapperHelper
package:bloc_test/src/bloc_test.dart         testBloc.<fn>
dart:async                                   runZonedGuarded
testBloc
blocTest.<fn>
blocTest.<fn>

✖ When bloc is in initial setting, emits initial state
Exited (1)
```

Why is this the case?
