### ISSUE TITLE
How to Re Use Custom Text Field widget using bloc?

### ISSUE THREAD

**Issue by jithusjacob** [felangel/bloc#2655]
So as part of a form I have 4 Text fields. Form Validation works fine using bloc if I have defined individual text fields on the screen.

Example As below
```
class _AmountInput extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocBuilder<AddBloc, AddState>(
        buildWhen: (previous, current) =>
            previous.amount.text != current.amount.text,
        builder: (context, state) {
          return Padding(
            padding: const EdgeInsets.all(8.0),
            child: TextField(
              decoration: InputDecoration(
                enabledBorder: OutlineInputBorder(
                  borderSide: BorderSide(
                    color: Colors.blueGrey,
                  ),
                  borderRadius: BorderRadius.circular(10.0),
                ),
                hintText: "Amount",
                errorText: state.amount.status
                    ? null
                    : 'Can not be empty and must be numeric',
              ),
              onChanged: (amount) {
                context.read<AddBloc>().add(AddAmountChange(amount));
              },
              keyboardType: TextInputType.number,
            ),
          );
        });
  }
}

```
But I want to create a custom Text field once and use that for each of the 4 inputs.  So that if I want to change the look of the text field I can do it at one place instead of 4 times. Is there any way I can do this using bloc?

**Comment by narcodico** [comment]
Hi @jithusjacob 👋

This is not related to bloc.
If you wanna control the look of your textfields from a single place you can adjust the theme on the `MaterialApp` and specify `inputDecorationTheme`.

Hope that answers your question!

**Comment by jithusjacob** [comment]
I can do that but then I also need to handle the error text using bloc(form validation). So wanted to know if there is way to do both.

**Comment by narcodico** [comment]
You can create a custom widget containing a text field and only expose the props you care about like `errorText`.
