### ISSUE TITLE
Showing Wrong State Changing Tabs

### ISSUE THREAD

**Issue by gfiury** [felangel/bloc#2656]
**Describe the bug**
I have a Tab Controller with 3 tabs. The First tab fetch's info from the server and shows a list of items. The user selects one of those items and the UI should go to the next Tab. The Second tab should show different items base on the selected.

I'm having trouble with the 2nd Tab. The 2nd Tab does not seem to refresh the current state of the bloc. Instead of showing the items, shows the spinner like it is still loading.

Logs:

I/flutter (14158): --TAB TWO STATE--
I/flutter (14158): Instance of 'ItemsOneLoaded'
I/ViewRootImpl@21021e3[MainActivity](14158): ViewPostIme pointer 0
I/ViewRootImpl@21021e3[MainActivity](14158): ViewPostIme pointer 1
I/flutter (14158): --TAB TWO STATE--
I/flutter (14158): Instance of 'ItemsTwoLoaded'

The Items of the Tab are already loaded but it shows the spinner.

**To Reproduce**
1) Loading items on the first Tab (Auto)
2) Select an item from Tab 
2.1) The Selection of the item triggers the change of state
2.2) That generates Items for the second tab
2.3) yield Items ready
3) The Second Tab is shown but in an incorrect state
3.1) Looking at the logs the state on the page is correct but the UI shows the loading

**Expected behavior**
The Second Tab should show the Items loaded.

**Example**
Made a small example of the problem [tab bloc example](https://we.tl/t-7n5xWWVFW5)

**Comment by elianmortega** [comment]
Hello @gfiury just checked your example, the **issue is the bad practice of building widgets with functions**, and the misused of `BlocConsumer`, The issue can be solved by changing the functions to class widgets and using `BlocBuilder` for the tabs. But, I'll strongly recommend checking out the [bloc library documentation](https://bloclibrary.dev/#/) so that you know the best practices of using the library. 

Update the tab_page.dart like this to solve:

```dart
import 'package:example_tab/tab_page_bloc.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class ExampleTabPage extends StatefulWidget {
  static Widget withBloc() {
    return BlocProvider<TabPageBloc>(
      create: (c) => TabPageBloc(),
      child: ExampleTabPage(),
    );
  }

  @override
  ExampleTabPageState createState() => ExampleTabPageState();
}

class ExampleTabPageState extends State<ExampleTabPage>
    with SingleTickerProviderStateMixin {
  List<Tab> _listTabs = <Tab>[
    Tab(text: 'ONE'),
    Tab(text: 'TWO'),
    Tab(text: 'THREE'),
  ];

  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(vsync: this, length: _listTabs.length);
  }

  @override
  void didChangeDependencies() {
    final TabPageBloc bappBloc = BlocProvider.of<TabPageBloc>(context);
    bappBloc.add(GetItemsTabOne());

    super.didChangeDependencies();
  }

  void _onStateChange(BuildContext context, TabPageState state) {
    if (state is ItemsTwoLoading) {
      _tabController.animateTo(1);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          bottom: TabBar(
            indicatorColor: Colors.white,
            controller: _tabController,
            tabs: _listTabs,
          ),
          title: Text("Example Tab Bloc")),
      body: BlocListener<TabPageBloc, TabPageState>(
        listener: _onStateChange,
        child: TabBarView(
          physics: NeverScrollableScrollPhysics(),
          controller: _tabController,
          children: [
            const TabOneView(),
            const TabTwoView(),
            Text("Third"),
          ],
        ),
      ),
    );
  }
}

class TabOneView extends StatelessWidget {
  const TabOneView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<TabPageBloc, TabPageState>(
      builder: (context, state) {
        if (state is ItemsOneLoaded) {
          return ListView.separated(
            shrinkWrap: true,
            itemCount: state.itemsOne.length,
            separatorBuilder: (context, index) => Divider(),
            itemBuilder: (context, index) {
              return ListTile(
                onTap: () => BlocProvider.of<TabPageBloc>(context)
                    .add(GetItemsTabTwo(itemOne: state.itemsOne[index])),
                title: Text(state.itemsOne[index].description),
              );
            },
          );
        }
        return Center(child: CircularProgressIndicator());
      },
    );
  }
}

class TabTwoView extends StatelessWidget {
  const TabTwoView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<TabPageBloc, TabPageState>(
      builder: (context, state) {
        if (state is ItemsTwoLoaded) {
          return ListView.separated(
            shrinkWrap: true,
            itemCount: state.itemsTwo.length,
            separatorBuilder: (context, index) => Divider(),
            itemBuilder: (context, index) {
              return ListTile(
                onTap: () => {},
                title: Text(state.itemsTwo[index].name),
              );
            },
          );
        }
        return Center(child: CircularProgressIndicator());
      },
    );
  }
}

```

This solves the issue, but I could spot some bad practices, so I encourage you to check out de docs 👍

**Comment by gfiury** [comment]
@elianmortega thanks for pointing it out, I'm going to take a look at the page and the examples of bloc.

Couple of questions,

1. Looking at the changes you made, you not only changed the functions for classes but you also added BlocBuilder for each class. Reading this example [Form validation](https://github.com/felangel/bloc/blob/master/examples/flutter_form_validation/lib/main.dart), it does something similar but for each input. 
What happens for example with a register form where I have for example 8 or 9 fields/inputs to fill?
**Do you need to do a StatelessWidget for each field?**

2. Trying to understand this, can you send me a link to the doc, where I can read more about "how the BlocBuilder works"?. 
Just by looking at the example it seems that the BlocBuilder "builds" the UI where ever you say so depending on the state.

**Comment by elianmortega** [comment]
Hey @gfiury  pleasure to help.

1. My first answer is yes, you will have to create one per every field. But it will also depend on your implementation.

2. Directly in the flutter_bloc package [BlocBuilder](https://pub.dev/packages/flutter_bloc#blocbuilder)

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation and if you haven't already feel free to join the [bloc discord server](https://discord.gg/bloc) 😄
