### ISSUE TITLE
Updating state inside for loop

### ISSUE THREAD

**Issue by benjamindean** [felangel/bloc#2658]
First of all, thanks for this awesome library!

I have a question regarding state updates and re-rendering inside for loop. I have a list of data that I need to process inside a loop before adding it to the cubit and render a PageView while the data is still coming in. 

The problem is that the widgets are rendered only two times and not, let's say, 100 for each entry. One with initial state and one with the final result. In both BlocBuilder and StreamBuilder. How can I make it react to the state changes immediately? I suspect it has something to do with the way Dart handles loops, but I'm not sure.

Thanks in advance!

**Comment by felangel** [comment]
Hi @benjamindean 👋 
Thanks for opening an issue!

Flutter renders at 60fps. If you emit/yield state changes more frequently then Flutter won't have time to rebuild with each state change. This is not specific to using bloc -- if you create a `StatefulWidget` and call `setState` back to back with different states, you will observe the same behavior.

Hope the helps 👍

**Comment by benjamindean** [comment]
@felangel Thank you for your response! Actually, I found a solution to that! There are two things I had to do to make it work:

1. Add `await Future.delayed(Duration.zero)` after the state change call.
2. Make the list of data immutable with `List.unmodifiable`.

I'm just keeping the rebuilding part as small as possible to avoid huge performance drops.
