### ISSUE TITLE
route or direct navigation

### ISSUE THREAD

**Issue by ki4rett4** [felangel/bloc#2659]
I'm confused whether I should implement a Route navigation or Direct navigation in my app.
What are use-cases for each of them? 
Is direct navigation suitable for complex hierachies involving bottomNavBar with multiple children for each tab or should route navigation or a mix of both be used?
Are there any disadvatages in using direct navigation?

Any help will be appreciated. Thanks

**Comment by liPatrick** [comment]
Please refer to this: https://bloclibrary.dev/#/recipesflutternavigation

**Comment by felangel** [comment]
Hi @ki4rett4 👋 
Thanks for opening an issue!

As @liPatrick mentioned you can refer to the navigation recipe to understand how to navigate in response to state changes in a bloc. For more information about the different navigation strategies I recommend checking out [the following article](https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade).

Hope that helps!
