### ISSUE TITLE
Navigation 2.0 / Router examples of implementation (and/or support)

### ISSUE THREAD

**Issue by sp00ne** [felangel/bloc#2660]
**Is your feature request related to a problem? Please describe.**
The frustration/difficulty right now lies with how to combine BloC pattern (which is the official supported way by Google) together with Navigation 2.0/Router. The issue right now more or less lies in the fact that RouterDelegate is "not a stateful widget" so we don't really have access to context in order to access any bloc but in the actual build functionality, making pop/setNewRoute etc. methods hard to handle.

Further this is the official way to do navigation, and should be covered by the documentation here. Navigation is a core functionality in any app that contains more than one screen.

**Describe the solution you'd like**
I would like a clear and concise example here in the project of how Navigation, simple and more complex using a couple of screens + bottom navigation + splash (for init).

**Describe alternatives you've considered**
I have read numerous articles and find it increasingly difficult to wrap my head around. I created a `NavigationBloc` to handle stuff and pass methods, but feel lost.

**Comment by felangel** [comment]
Closing as this is a duplicate of #2178 👍
