### ISSUE TITLE
HydratedBloc the last state does not return

### ISSUE THREAD

**Issue by flutteresbolivia** [felangel/bloc#2665]
BenefitsState my code
```
@immutable
abstract class BenefitsState extends Equatable {}

class BenefitsLoading extends BenefitsState {
  @override
  List<Object> get props => [];
}

class BenefitsLoad extends BenefitsState {
  final List<BenefitModel> benefits;
  BenefitsLoad({this.benefits});
  static BenefitsLoad get initialState => BenefitsLoad(
        benefits: [],
      );
  BenefitsLoad copyWith({
    List<BenefitModel> benefits,
  }) {
    return BenefitsLoad(
      benefits: benefits ?? this.benefits,
    );
  }

  @override
  List<Object> get props => [benefits];

  factory BenefitsLoad.fromMap(Map<String, dynamic> map) => BenefitsLoad(
        benefits: map['benefits'] == null ? null : List<BenefitModel>.from(map['benefits']?.map((x) => BenefitModel.fromJson(x))),
      );

  Map<String, dynamic> toMap() {
    return {
      'benefits': benefits == null ? null : List<dynamic>.from(benefits.map((x) => x.toJson())),
    };
  }
}

```

My bloc 

```
class BenefitsBloc extends HydratedBloc<BenefitsEvent, BenefitsState> {
  GetBenefitsAllUsecase getBenefitsAllUsecase;
  BenefitsBloc({
    @required GetBenefitsAllUsecase getBenefitsAllUsecase,
  })  : this.getBenefitsAllUsecase = getBenefitsAllUsecase,
        super(BenefitsLoad.initialState ?? BenefitsLoad());
  @override
  Stream<BenefitsState> mapEventToState(
    BenefitsEvent event,
  ) async* {
    if (event is GetBenefist) {
      try {
        print(state);
        yield BenefitsLoading();
        var response = await getBenefitsAllUsecase();
        var data = ApiResponse.completed(response);
        yield BenefitsLoad(benefits: data.data);
      } catch (e) {
        yield state;
      }
    }
  }

  @override
  BenefitsState fromJson(Map<String, dynamic> json) {
    print('fromJson');
    try {
      final weather = BenefitsLoad.fromMap(json);
      return BenefitsLoad(benefits: weather.benefits);
    } catch (_) {
      return null;
    }
  }

  @override
  Map<String, dynamic> toJson(BenefitsState state) {
    print("toJson");
    if (state is BenefitsLoad) {
      return state.toMap();
    } else {
      return null;
    }

  }
}

```

What's my problem:

My application is mostly without internet.
So when it loads the first time the BenefitsLoad state is cached with an array of data.
but when it does not detect that there is no internet, then it jumps to the try catch, and I want to return the previous state, but unfortunately it returns the BenefistLoading

Am I doing something wrong?

> JSON Conversion
> Serializing to JSON is very easy with our previous setup. We just have to make sure the state being serialized is BenefitsLoad, as the other ones cannot be serialized. Otherwise, we will return null.
> 
> Returning null will leave the stored state as it is. This means that when the user exits the app before a new weather could be loaded, he will be presented with the previous weather upon launching the app.

**Comment by flutteresbolivia** [comment]
@felangel help pls

**Comment by felangel** [comment]
Hi @flutteresbolivia 👋 
Thanks for opening an issue!

In `mapEventToState` you should handle the case explicitly by returning the cached state rather than an error state:

```dart
   if (event is GetBenefits) {
      try {
        if (state is! BenefitsLoad) yield BenefitsLoading();
        var response = await getBenefitsAllUsecase();
        var data = ApiResponse.completed(response);
        yield BenefitsLoad(benefits: data.data);
      } catch (_) {
        yield state;
      }
    }
```
Hope that helps 👍

**Comment by flutteresbolivia** [comment]
> ```dart
> if (event is GetBenefits) {
>       try {
>         if (state is! BenefitsLoad) yield BenefitsLoading();
>         var response = await getBenefitsAllUsecase();
>         var data = ApiResponse.completed(response);
>         yield BenefitsLoad(benefits: data.data);
>       } catch (_) {
>         yield state;
>       }
>     }
> ```

Thank you very much, but the problem is that now it does not show me the Loading.

**Comment by flutteresbolivia** [comment]
> > ```dart
> > if (event is GetBenefits) {
> >       try {
> >         if (state is! BenefitsLoad) yield BenefitsLoading();
> >         var response = await getBenefitsAllUsecase();
> >         var data = ApiResponse.completed(response);
> >         yield BenefitsLoad(benefits: data.data);
> >       } catch (_) {
> >         yield state;
> >       }
> >     }
> > ```
> 
> Thank you very much, but the problem is that now it does not show me the Loading.

I want the Loading to always be shown, or do I do that when refresh is done?

**Comment by felangel** [comment]
> not

If you want to show a loading indicator while also showing the cached data then you should probably restructure your bloc state to be a single state rather than an abstract base class with multiple subclasses. You can check out [the weather state])(https://github.com/felangel/bloc/blob/master/examples/flutter_weather/lib/weather/cubit/weather_state.dart) for an example 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation or, if you haven't already, join the [bloc discord server](https://discord.gg/bloc) to chat with me and other members of the community 😄
