### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by RazaShabbir-vrc** [felangel/bloc#2676]
Is there a way in BloC to not stack up events when triggering from an outer source that can be firebase? I am trying to listen to firebase events in boolean and if there is a change some data should be sent from API for certain calculation. I have implemented BloC for that feature with data providers however, the firebase is listening to it multiple times is there a way to lodge the last event only and I can add only last event and not sink in all the sequence? I suppose this could be a problem with my coding but if there is a feature to actually do this in bloc that would be great. Using something like BlocProvider.of<CartBloc>(context).add(SomeEvent(data));

**Comment by felangel** [comment]
Hi @RazaShabbir-vrc 👋 
Thanks for opening an issue!

You can customize this behavior by overriding `transformEvents` and using something like `switchMap` to always only handle the latest event https://github.com/felangel/bloc/blob/2dd0e3b70be68d206420cee11516fb266823e7ef/examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart#L23

Hope that helps 👍

**Comment by RazaShabbir-vrc** [comment]
Oh, that makes sense. Thank you so much for the prompt response.
