### ISSUE TITLE
fix: Cubit emits state twice when called.

### ISSUE THREAD

**Issue by danieladamsGDM** [felangel/bloc#2681]
**Description**
When calling my cubit, the loaded state gets emitted twice although I only call it once. I didn't notice this until I started trying to unit test the cubit with bloc test. I'm pulling in jsons with a lot of data in the actual app so I haven't noticed this behavior until implementing unit testing.

Cubit:
```
class WebServiceCubit extends Cubit<WebServiceState> {
  WebServiceCubit({required this.storyRepository})
      : super(WebServiceInitial()) {
    getStories();
  }
final StoryRepository storyRepository;
  Future<void> getStories() async {
    try {
      emit(WebServiceLoading());
      final List<Story> stories = await storyRepository.getStories();

      /// 1.2 seconds to load data and avoid errors
      await Future.delayed(const Duration(milliseconds: 800), () {
        emit(WebServiceLoaded(stories: stories));
      });
 } catch (e) {
      emit(WebServiceError());
    }
  }
```

Unit test:
```
void main() {
  group('WebServiceCubit', () {
   
    WebServiceCubit cubit =
        WebServiceCubit(storyRepository: StoryRepository());

    setUp(() {
      EquatableConfig.stringify = true;
      
       cubit = WebServiceCubit(storyRepository: StoryRepository());
    });
    tearDown(() {
  
      cubit.close();
    });

//passes
    test('initial state of WebServiceCubit', () {
      expect(cubit.state, WebServiceLoading());
    });

// fails unless I use skip: 1
    blocTest(
      'can get stories from web',
      build: () => cubit,
      act: (cubit) async => cubit.getStories(),
      expect: () => [
        cubit.state,
      ],
    );   
  });
}
```

Any ideas why this would cause the cubit to emit loaded twice??

Output:

<img width="1206" alt="Screen Shot 2021-08-19 at 1 16 39 PM" src="https://user-images.githubusercontent.com/87324313/130114138-63ef4d63-e9fd-4aa8-b625-ae6e36079474.png">

**Comment by Gene-Dana** [comment]
HI there ! On creation of the cubit, are you making any calls?

**Comment by felangel** [comment]
Hi @danieladamsGDM 👋 
Thanks for opening an issue!

This is working as expected because the initial state of the bloc/cubit can be re-emitted once in order to support re-hydrating a bloc's state (see https://github.com/felangel/bloc/pull/1441 for more info). In general, I don't recommend putting initialization code in the bloc's constructor and instead using events because it makes it a lot easier to test and keeps the bloc flexible and reusable. Let me know if that helps 👍

**Comment by danieladamsGDM** [comment]
Ok. So the getStories() function being called in the initial state is the issue?

I'll try to figure out how to use my cubit correctly without calling it in the constructor and see what happens.

Thank you @felangel

**Comment by danieladamsGDM** [comment]
Ok. I got it all worked out. Still kinda new to bloc and bloc test and this helped me a lot. 

I removed the getStories() call from the constructor and just call it at the end of BlocProvider with ..getStories()

Thank you so much @felangel !

**Comment by jseeegithub** [comment]
> 

Even though I have no method calls on cubit class's constructor, the cubit is emitting two identical states. Can you help me find why?

Cubit class:

`class AlertCubit extends Cubit<AlertState> {
  AlertCubit() : super(AlertInitial());

  void alert(InfoAlertData alertInfo) {
    emit(AlertInitial());
    emit(NewAlert(alertInfo));
  }

  void snack(String message) {
    emit(AlertInitial());
    emit(NewSnack(message));
  }
}
`

Where I call this function from another cubit:

`  
class CustomersCubit extends Cubit<CustomersState> {
  CustomersCubit(
      {required this.alertCubit,
      required this.collectionCubit,
      required this.authCubit})
      : super(CustomersInitial());

  final AlertCubit alertCubit;
  final CollectionCubit collectionCubit;
  final AuthCubit authCubit;

...

void markMissing(int loanId) async {
    if (collectionCubit.active) {
      bool marked = await CustomerService().updateMissingTemp(loanId, true);

      if (marked) {
        await getRunningAccounts();
      }
    } else {
      log('be collecting');
      alertCubit.alert(InfoAlerts.startCollect);
    }
  }

...
}
`

I passed cubit as a parameter in main:

`
...

return MultiBlocProvider(
      providers: [
        BlocProvider(
          create: (_) => AlertCubit(),
        ),
        BlocProvider(
          create: (_) => CollectionCubit(),
        ),
        BlocProvider(
          create: (BuildContext authContext) => AuthCubit(
            alertCubit: BlocProvider.of<AlertCubit>(authContext),
            collectionCubit: BlocProvider.of<CollectionCubit>(authContext),
          )..checkAuthState(),
        ),
        BlocProvider(
          create: (BuildContext cusContext) => CustomersCubit(
            alertCubit: BlocProvider.of<AlertCubit>(cusContext),
            collectionCubit: BlocProvider.of<CollectionCubit>(cusContext),
            authCubit: BlocProvider.of<AuthCubit>(cusContext),
          ),
        ),

...

`

**Comment by jseeegithub** [comment]
> Ok. I got it all worked out. Still kinda new to bloc and bloc test and this helped me a lot.
> I removed the getStories() call from the constructor and just call it at the end of BlocProvider with ..getStories()
> 
> Thank you so much @felangel ! 

Even though I have no method calls on cubit class's constructor, the cubit is emitting two identical states. Can you help me find why?

Cubit class:

```
class AlertCubit extends Cubit<AlertState> {
  AlertCubit() : super(AlertInitial());

  void alert(InfoAlertData alertInfo) {
    emit(AlertInitial());
    emit(NewAlert(alertInfo));
  }

  void snack(String message) {
    emit(AlertInitial());
    emit(NewSnack(message));
  }
}
```

Where I call this function from another cubit:

```
class CustomersCubit extends Cubit<CustomersState> {
  CustomersCubit(
      {required this.alertCubit,
      required this.collectionCubit,
      required this.authCubit})
      : super(CustomersInitial());

  final AlertCubit alertCubit;
  final CollectionCubit collectionCubit;
  final AuthCubit authCubit;

///removed irrelevant code

void markMissing(int loanId) async {
    if (collectionCubit.active) {
      bool marked = await CustomerService().updateMissingTemp(loanId, true);

      if (marked) {
        await getRunningAccounts();
      }
    } else {
      log('be collecting');
      alertCubit.alert(InfoAlerts.startCollect);
    }
  }

///removed irrelevant code
}
```

I passed cubit as a parameter in main:

```
///removed irrelevant code

return MultiBlocProvider(
      providers: [
        BlocProvider(
          create: (_) => AlertCubit(),
        ),
        BlocProvider(
          create: (_) => CollectionCubit(),
        ),
        BlocProvider(
          create: (BuildContext authContext) => AuthCubit(
            alertCubit: BlocProvider.of<AlertCubit>(authContext),
            collectionCubit: BlocProvider.of<CollectionCubit>(authContext),
          )..checkAuthState(),
        ),
        BlocProvider(
          create: (BuildContext cusContext) => CustomersCubit(
            alertCubit: BlocProvider.of<AlertCubit>(cusContext),
            collectionCubit: BlocProvider.of<CollectionCubit>(cusContext),
            authCubit: BlocProvider.of<AuthCubit>(cusContext),
          ),
        ),
///removed irrelevant code

```

**Comment by jseeegithub** [comment]
Never mind. It was my mistake; I added the same listener twice in UI code. Sorry to bother.
