### ISSUE TITLE
state changes "lost" if state sequence too fast

### ISSUE THREAD

**Issue by w461** [felangel/bloc#2689]
**Description**
If I have a screen controlled by 2 blocs and send 2 state changes for the parent bloc right after one another, the child widget will not be updated. This scenario becomes relevant if PageA/BlocA control a gateway that provides data to different screens rendered with PageB/BlocB, PageC/BlocC etc. and which also control which screen shall be shown. 

Not sure if this is caused by Bloc or Dart

**Steps To Reproduce**

If I have 2 widgets, PageA and PageB, PageB rendering the content for the otherwise empty PageA, 
- and if PageA and PageB, both are controlled by blocs BlocA, BlocB (not sure whether this happens also if PageB has no bloc)
- and if I yield a PageAInProgress state followed by a PageAShowPageB state (PageB previously already shown), 
- and if PageAInProgress renders a spinner instead of PageB
- and if the 2nd call of PageB is executed with different arguments than the first call (thus somehow changing the content of PageB)

PageB does not change to reflect the changes made with the 2nd call of PageB (actually the arguments are sent to BlocB not to PageB) - unless - I implement a pause in between both states as shown in the comment below

`      yield PageAInProgress();`
`//      await Future.delayed(Duration(seconds: 1));`
`      ++cnt;`
`      yield PageAShowPageB(cnt);`

**Expected Behavior**
I would expect that PageB is re-rendered even if there are only microseconds in between states PageAInProgress and PageAShowPageB.

**Screenshots**

**Additional Context**

**Comment by felangel** [comment]
Hi @w461 👋 
Thanks for opening an issue!

I believe this is a duplicate of #2260. Let me know if that helps 👍

**Comment by w461** [comment]
sorry, I forgot to look here but did so only at stackoverflow. 

Yes, it looks very much alike. This means for my typical pattern (yield InProgress > do something > yield Result), it was successful until now, only because do something  took longer than 20ms. 

Thanks for your quick response! 👍
