### ISSUE TITLE
docs: Question related to complex forms

### ISSUE THREAD

**Issue by SApolinario** [felangel/bloc#2691]
**Description**

Clearly describe what documentation you are looking to add or improve.

Hi I have a form/screen representing the adding/updating of a Calendar Event.  The only input I have is the name text field.  The other data is display only with the option to tap and edit in separate screens (e.g. guests, notes, calendar, etc). I have a domain object "Event" that contains various properties and nested objects, lists, etc.

For this type of form do you still feel flutter_bloc would be beneficial to use?  if so would you replicate all the Event properties in the state object or try and re-use the existing domain model as part of the state?  Is it best to keep the state separate from the domain model and map the data on submission?  Any tips or pointers you could give would be welcome.

Thanks

Samuel

**Comment by marcossevilla** [comment]
Hi @SApolinario, I think you should take a look at [formz](https://pub.dev/packages/formz) to have a custom form input with your desired validation on your event object, or just handling it as a property of an immutable state for the form, just like [this](https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/lib/login/cubit/login_state.dart) example.

Most of the time, you'll likely have a form with multiple screens, so splitting those screens into smaller blocs/cubits that update the state of a parent bloc should work well for you. Here's an [example](https://github.com/NoScopeDevs/bloc_samples/tree/feat/bloc_flow_form/examples/form_flow/lib/signup) with bloc + flow_builder + formz that I'm putting together (sorry, it's still in a dev branch) and can be helpful for what you need, especially the signup feature.

Let me know if that helps. 👍

**Comment by Gene-Dana** [comment]
@SApolinario For the sake of testing, maintenance, and all-around faster development speed, I would still highly suggest you collect form data and send it through the domain layer.

Although this example is far from perfect, it shows how I collect form data, convert it into a model, and then push it through a bloc -> repo -> firestore backend

https://github.com/Team-Crushing-It/wine_game_admin/blob/a84527fdb8f3ee65922cfcfd223d1e318a10e583/lib/home/_features/details/view/details_view.dart#L62-L124

**Comment by felangel** [comment]
@SApolinario closing for now since @marcossevilla and @Gene-Dana have provided several examples of potential ways to implement complex forms with the bloc library. Feel free to comment if you have any follow-up questions or join the [bloc discord](https://discord.gg/bloc) to chat with more community members, thanks!
