### ISSUE TITLE
feat: BlocProvider Disposal Hook

### ISSUE THREAD

**Issue by nabond251** [felangel/bloc#2692]
**Description**

I would like to be able to specify what happens when a `BlocProvider` both creates and disposes its bloc.

**Desired Solution**

Add an optional callback parameter `disposing` to the main `BlocProvider` constructor.  When `buildWithChild` constructs an `InheritedProvider` in the automatic disposal use case, for the `InheritedProvider`'s `dispose` argument, call `disposing` before calling `bloc.close()`.

**Alternatives Considered**

* Overriding `close` in the provided bloc.  This ends up splitting lifecycle management concerns between the `create` callback in `BlocProvider`, and this new overloaded `close` method in the bloc itself.  If `create` has implementation details that are not the concern of the bloc, the corresponding `close` method may also have similar implementation details with which the bloc should similarly not be concerned.
* Making the `disposing` callback an overridable method of the `BlocProvider` rather than a callback property.  Of course this carries the undesirable consequence of extending a `BlocProvider` to specify bloc disposal.  This essentially requires one extension per instance, which seems a nonsensical violation of the reused abstraction principle.

Both these approaches fail primarily for one reason:  they fail to maintain the symmetry of the proposed design between `create` and `disposing`.  By maintaining this symmetry, lifecycle implementation details are both abstracted to the same location in creating the `BlocProvider` instance; and that created instance is one of many still-reusable `BlocProvider`s.

**Additional Context**

This symmetry is already present in the underlying `InheritedProvider`; it makes sense to continue presenting it in the `BlocProvider`, since the latter is itself an provider for inherited (albeit potentially automatically disposed) blocs.  Calling the `disposing` callback from the `dispose` argument of `InheritedProvider` and subsequently calling the current `bloc.close()` ensures this additional responsibility of automatically closing the bloc is maintained.  The `disposing` callback is optional, so this is not a breaking change.  In the case of a `BlocProvider.value` instance, there is nothing to dispose so the implementation remains unchanged.

```
  @override
  Widget buildWithChild(BuildContext context, Widget? child) {
    final value = _value;
    return value != null
        ? InheritedProvider<T>.value(
            value: value,
            startListening: _startListening,
            lazy: lazy,
            child: child,
          )
        : InheritedProvider<T>(
            create: _create,
            dispose: (_, bloc)
            {
              // proposed change
              _disposing?.call();
              bloc.close();
            },
            startListening: _startListening,
            child: child,
            lazy: lazy,
          );
  }
```

My specific use case is for when, within `create`, I want to perform some subscriptions to related blocs immediately after making a new instance of the provided bloc.  I would then use `disposing` to unsubscribe.  This is more or less a straightforward application of the ["third-party connect"](https://blog.ploeh.dk/2013/09/08/di-and-events-third-party-connect/) technique discussed by software architect Mark Seemann.

**Comment by Gene-Dana** [comment]
HI there 👋🏼 ! Thanks for your patience

If streaming to blocs and disposing onClose is the functionality you'd like to see, then this is something that the pattern already implements at the Bloc level.

If you want to perform subscriptions to related blocs immediately, you can add the stream in the bloc constructor body

```dart
class AppBloc extends Bloc<AppEvent, AppState> {
  AppBloc({required AuthenticationRepository authenticationRepository})
      : _authenticationRepository = authenticationRepository,
        super(
          authenticationRepository.currentUser.isNotEmpty
              ? AppState.authenticated(authenticationRepository.currentUser)
              : const AppState.unauthenticated(),
        ) {
//see here 👇🏼
    _userSubscription = _authenticationRepository.user.listen(_onUserChanged);
  }
```

https://github.com/felangel/bloc/blob/388e329335159f8e027a65e0a6778d2f7632c730/examples/flutter_firebase_login/lib/app/bloc/app_bloc.dart#L12-L21

Also, blocs have an onClose method, which you can use to unsubscribe also.

```dart
  @override
  Future<void> close() {
    _userSubscription.cancel();
    return super.close();
  }
```

**Comment by felangel** [comment]
Hi @nabond251 👋 
Thanks for opening an issue!

> If create has implementation details that are not the concern of the bloc, the corresponding close method may also have similar implementation details with which the bloc should similarly not be concerned.

Can you provide a concrete example of what you're trying to achieve? In general, `BlocProvider` is solely intended to be used in order to provide a new instance of a bloc to the widget tree. Create should only be creating a new bloc instance and should have no other logic or functionality.

> This symmetry is already present in the underlying InheritedProvider;

That is because the underlying provider is generic and can't handle the `dispose` for you. Since `BlocProvider` is a specific implementation of `InheritedProvider` which integrates with bloc instances it can properly handling `disposing` the bloc instance automatically for you.

> My specific use case is for when, within create, I want to perform some subscriptions to related blocs immediately after making a new instance of the provided bloc.

You generally shouldn't be creating/managing subscriptions as part of the `create` method. As I mentioned, the responsibility of the `create` method is just to construct a new instance of the bloc which you want to provide. If you want to subscribe to that bloc or interact with it that logic should not be done as part of the `create` method. Instead, I would recommend following the existing pattern of using widgets like `BlocBuilder` (if you want to subscribe and rebuild UI in response to state changes) or `BlocListener` (if you want to subscribe and perform side-effects in response to state changes). In either case, the subscription generally shouldn't be part of `create` and `BlocBuilder` and `BlocListener` handle disposing their subscription when they are unmounted from the widget tree.

Let me know if that helps 👍

**Comment by nabond251** [comment]
@Gene-Dana @felangel thank you for getting back to me on this. Might be a day or two before I can respond in full, but I'll try to have a something of a minimum viable concrete situation for you to consider/correct fairly soon.

**Comment by nabond251** [comment]
Something like this:

```
          child: BlocProvider(
            create: (context) {
              var app = AppCombinedCubit();
              _taskListSub =
                  app.stream.listen(context.read<TaskListBloc>().add);
              _aboutSub = app.stream.listen(context.read<AboutBloc>().add);
              _entitiesCombinedSub =
                  app.stream.listen(context.read<EntitiesCombinedCubit>().add);
              app.add(InitRequested());
              return app;
            },
            disposing: () {
              _taskListSub.cancel();
              _aboutSub.cancel();
              _entitiesCombinedSub.cancel();
            },
            child: Home(),
            lazy: false,
          ),
```

The motivation is to not have hard dependencies on the listening blocs within the created app bloc.  All the "piping" is done at a top-level main widget.  So the app bloc is nothing more than the following:

```
import 'package:bloc/bloc.dart';

import 'event.dart';

/// App combined BLoC.
class AppCombinedCubit extends Cubit<Event> {
  /// Initializes a new instance of the [AppCombinedCubit] class.
  AppCombinedCubit() : super(Event());

  /// Notifies the Bloc of a new [event].
  void add(Event event) {
    emit(event);
  }
}
```

Could be a very bad, no good misuse of all the things.  Might consider alternate approaches, but this is the idea.

**Comment by nabond251** [comment]
@Gene-Dana @felangel also [here](https://github.com/nabond251/bloc/commit/e85a43b37c4ec079e6e5f5b35487b6a739b1a751) is a commit with the proposed changes.  Haven't updated the docs yet or added tests, so more for reference than pull request.

**Comment by felangel** [comment]
@nabond251 thanks for providing a code sample. I rewrote the snippet you provided using `BlocListener` and keeping `BlocProvider` as is:

```dart
  BlocProvider(
      lazy: false,
      create: (context) => AppCombinedCubit()..add(InitRequested()),
      child: BlocListener<AppCombinedCubit, AppCombinedState>(
        listener: (context, state) {
          context.read<TaskListBloc>().add(state);
          context.read<AboutBloc>().add(state);
          context.read<EntitiesCombinedCubit>().add(state);
        },
        child: Home(),
      ),
    );
```

With the above approach there is no need to maintain and dispose multiple subscriptions as part of `create` and it keeps `create` focused on just one thing: creating the bloc that will be provided. By using `BlocListener` you don't need to maintain and dispose subscriptions manually and still keeps the blocs loosely coupled.

Hope that helps 👍

**Comment by nabond251** [comment]
@felangel hey, that looks like a winner. Thanks for taking the time to help a noob 🤓

**Comment by felangel** [comment]
> @felangel hey, that looks like a winner. Thanks for taking the time to help a noob 🤓

Of course! Glad I was able to help 😄 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation.
