### ISSUE TITLE
docs: link is broken

### ISSUE THREAD

**Issue by vasilich6107** [felangel/bloc#2693]
**Description**
https://pub.dev/packages/hydrated_bloc

```
HydratedStorage is built on top of hive for a platform-agnostic, performant storage layer. 
See the complete [example] for more details.
```

Link on `example` is broken

**Comment by felangel** [comment]
Hi @vasilich6107 👋 
Thanks for opening an issue!

This has been fixed and will be included in the upcoming release. In the meantime, the correct link is https://github.com/felangel/bloc/blob/master/packages/hydrated_bloc/example. Sorry for the inconvenience!
