### ISSUE TITLE
docs: Complex state examples

### ISSUE THREAD

**Issue by SApolinario** [felangel/bloc#2694]
**Description**

Clearly describe what documentation you are looking to add or improve.

Is there a good example somewhere illustrating the use of a complex state object with nested objects, lists, etc?  Can a state object be as complex as needed?  Thanks.

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 This is one example that you may benefit studying!

https://github.com/Team-Crushing-It/wine_game_admin/blob/a84527fdb8f3ee65922cfcfd223d1e318a10e583/packages/questions_repository/lib/src/models/question.dart#L8-L13

It's hosted here live:
https://firestore-bloc-crud-demo.netlify.app/#/

Feel free to add or remove or edit anything to see how it all works

**Comment by SApolinario** [comment]
Hi @Gene-Dana, thanks for the link.  I will definitely have a look.

**Comment by Gene-Dana** [comment]
Okay ! for now, I plan to close this issue and feel free to comment here or the discord with any questions!
