### ISSUE TITLE
feat: onInit function for BlocProvider

### ISSUE THREAD

**Issue by mtwichel** [felangel/bloc#2701]
**Description**

When using `BlocProvider`, often we want to add an event (or call a function on a `cubit`) immediately after creating the `bloc`. For example, you could imagine loading a page with an online ordering menu immediately when opening a particular page. We don't want to do that work in the constructor as it's asynchronous, so we create an event for it. Currently, the best solution we know of (and use) is to cascade the add call in the create method, like so:
```dart
@override
Widget build(BuildContext context) {
    return BlocProvider(
        create: (context) => MenuBloc()..add(InitialMenuRequested()),
        child: // ...
    );
}
```
This works okay but is not super readable and a bit messy imho.

**Desired Solution**

It would be cool to have an optional named parameter to run some login immediately after the bloc is created. It would look something like this:
```dart
@override
Widget build(BuildContext context) {
    return BlocProvider(
        create: (context) => MenuBloc(),
        initialize: (bloc) => bloc.add(InitialMenuRequested()),
        child: // ...
    );
}
```

As for naming that parameter, I've had a few ideas:
- `onInit`
- `initialize`
- `onCreate`
- `onInitialize`
- `afterCreate`

But I'm not sold on any of them 😆

**Alternatives Considered**

The alternatives I see is using cascading methods like I described above or kicking off the async job in the constructor. To me, my proposed solution is much cleaner than both of those ideas while still being flexible for different use cases.

**Additional Context**

The only other point is that this could be done without any breaking changes, which is cool. It would just be a new option moving forward but entirely optional.

Also, for consistency's sake, maybe we should consider adding the same function for `RepositoryProvider`?

Thanks! I'm excited to hear everyone's thoughts!

**Comment by felangel** [comment]
Hey @mtwichel 👋 
Thanks so much for opening an issue!

I'm going to think a bit more about this and want to give other members of the community a chance to weigh in.

@rrousselGit have you had similar feature requests on `provider`? What are your thoughts on having an `onCreate` callback which allows developers to interact with the provided object immediately following creation?

**Comment by rrousselGit** [comment]
I'd advise against it. That's something I voluntarily avoided with Riverpod.

When we look into it, the only benefit is a minor organisation. If the `..add()` isn't satisfying, there are a few alternatives:

```dart
Provider(
  create: (ctx) {
    final value = Value();
    value.doSomething();
    return value;
  },
)
```

or:

```dart
Provider(create: (ctx) => Value())

class Value {
  Value() {
    doSomething();
  }
}
```


____

The reason I dislike the idea is, it's a significant decrease in flexibility.


In a similar yet slightly different example, with Riverpod I voluntarily changed:

```dart
Provider(
  create: (ctx) => Value(),
  dispose: (ctx, value) => value.dispose()
)
```

into:

```dart
Provider((ref) {
  final value = Value();
  ref.onDispose(value.dispose);
  return value;
});
```

(which I will likely bring to provider in a backward compatible way after I'm done with the v1 of Riverpod)

The difference is, it allows all life-cycles to access the "create" local variables.

For example, you would be unable to do:

```dart
Provider(
  create: (ctx) {
    final a = ...
     return Bloc();
  },
  onInit: (bloc) {
    print(a) // where is `a` coming from?
  }
  dispose: () {
    a.dispose(); // same issue
  }
)
```

Whereas by using a single callback for all life-cycles, we can do whatever we want:

```dart
Provider((ref) {
  final a = ...

  // onInit
  print(a)

  // dispose
  ref.onDispose(() => a.dispose());

  return Bloc();
});
```

**Comment by jorgecoca** [comment]
I share a similar point of view with @rrousselGit

If a component/class/object does not require a lifecycle by default, then I'd prefer not adding lifecycle-like APIs. And, in this case, the benefit would be purely "visual/aesthetic".

**Comment by mtwichel** [comment]
Thanks @rrousselGit and @jorgecoca for your thoughts! :pray: I totally understand your arguments and honestly I'm persuaded that this wouldn't be a good idea for `flutter_bloc`.

To Jorge's comment: 
> If a component/class/object does not require a lifecycle by default, then I'd prefer not adding lifecycle-like APIs. And, in this case, the benefit would be purely "visual/aesthetic".

I think it would be nice to have some lifecycle like features for Flutter widgets imo since I find myself re-writing the same lifecycle like code in my projects. However, I think it's clear maybe those ideas are better served in a package for specifically that use and not in the main `flutter_bloc` package itself.

to Remi's comment:
> ... it allows all life-cycles to access the "create" local variables.

That's an interesting case I hadn't considered, and I definitely differ to your expertise in something like that. I haven't ever _personally_ use `bloc` like that, so it seems like the change I proposed would be good for me, but maybe not to the wider community.

On those notes, I agree it may not be the best idea, but maybe I should look at developing separate widgets that support things the way I'd personally want. @felangel unless you disagree or think there's more discussion to have, I'm 100% okay if we close this issue :)

**Comment by felangel** [comment]
@mtwichel sorry for the delayed reply. Yeah for now I'd prefer if we close this in favor of creating a separate package for this functionality and we can revisit it in the future if needed 👍
