### ISSUE TITLE
[Question] [Hydrated_Bloc] what code generator, or data serialization recommended for a class has list

### ISSUE THREAD

**Issue by gusdoe** [felangel/bloc#2704]
Hi Felix,

I am using Hydrated_Bloc with a class that has Lists of Classes in it. I am using 'Built_value' and 'Freezed' for code generation and data serialization. I wonder if you can recommend better ways to serialize a complex class than these tools.

Thank you

**Comment by Elias8** [comment]
Hi @gusdoe 👋,

I recommend [json_serializable](https://pub.dev/packages/json_serializable) as it is very handy with [freezed](https://pub.dev/packages/freezed), or just on its own.

**Note:** This is just a personal preference.

Hope that helps!

**Comment by felangel** [comment]
Hi @gusdoe 👋 
Thanks for opening an issue!

I personally also recommend [json_serializable](https://pub.dev/packages/json_serializable) 👍 

Hope that helps and closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄

**Comment by gusdoe** [comment]
Thank you, Elias and Felix!

I am wondering if freezer and  json_serializable are still the pick in the cases of ky_dart and FIC (fast immutable class).
