### ISSUE TITLE
How to convert DateTime.Now() into a bloc stream

### ISSUE THREAD

**Issue by mfizz1** [felangel/bloc#2707]
I realize this might be trivial but I am trying to get my head around bloc.

I know I can use `StreamBuilder` to achieve my purpose but I want to utilize bloc to increase my understanding

Currently I have the following function that gets called as part of `StreamBuilder` which every second updates the UI with the current time. I specifically mean bloc and not a cubit.

```
Stream<DateTime> currentTime() async* {
  yield* Stream.periodic(Duration(seconds: 1), (_) => DateTime.now());
}
```

```
StreamBuilder(
   builder: (context, snapshot) => Text(snapshot.data.toString()),
   stream: currentTime(),
    );
```

**Comment by narcodico** [comment]
Hi @mfizz1 👋

You can simply subscribe to the stream inside your bloc.

```
Stream<DateTime> currentTime() =>
    Stream.periodic(const Duration(seconds: 1), (_) => DateTime.now());

class TheBloc extends Bloc<TheEvent, TheState> {
  TheBloc() : super(TheState(dateTime: DateTime.now())) {
    _currentTimeSubscription = currentTime().listen(_onCurrentTimeTicked);
  }

  late final StreamSubscription _currentTimeSubscription;

  void _onCurrentTimeTicked(DateTime dateTime) =>
      add(CurrentTimeTicked(dateTime));

  @override
  Future<void> close() {
    _currentTimeSubscription.cancel();
    return super.close();
  }

  @override
  Stream<TheState> mapEventToState(
    TheEvent event,
  ) async* {
    if (event is CurrentTimeTicked) {
      yield TheState(dateTime: event.dateTime);
    }
  }
}

abstract class TheEvent {}

class CurrentTimeTicked extends TheEvent {
  CurrentTimeTicked(this.dateTime);

  final DateTime dateTime;
}

class TheState {
  TheState({required this.dateTime});

  final DateTime dateTime;
}
```

If can now build the appropriate UI based on your bloc's state.

Hope that helps! ✌

**Comment by mfizz1** [comment]
@narcodico Thank you very much. I have no doubt that this will work.

I am struggling however, to get my head round the concepts behind the following perhaps you could elaborate please:

```
  TheBloc() : super(TheState(dateTime: DateTime.now())) {
    _currentTimeSubscription = currentTime().listen(_onCurrentTimeTicked);
  }

  late final StreamSubscription _currentTimeSubscription;
```

And whilst I understand it is good practice to cancel subscription I never intend to not use it.. Should I still have it in there?

**Comment by narcodico** [comment]
In order to start receiving your dates you need to `listen` to your stream. Listening will return a `StreamSubscription` which must be canceled(to avoid data leaks) by the same object which created the subscription, which in your case is the bloc. The returned `StreamSubscription` is mostly intended to be used to `pause`, `resume` or `cancel` the incoming data.

This is completely unrelated to bloc so I advise you read more about streams [here](https://dart.dev/tutorials/language/streams).

**Comment by mfizz1** [comment]
Sorry I should have made my query clearer, I understand the listening element. I want to know why it is being called as super constructor as opposed to just a normal constructor of the class.

**Comment by narcodico** [comment]
`super` calls the `Bloc` constructor in order to set the initial state of your bloc. By `Bloc` I mean the base class which you're extending from.

**Comment by mfizz1** [comment]
Thank you. That explains it!
