### ISSUE TITLE
The class 'Future' was not exported from 'dart:core' until version 2.1

### ISSUE THREAD

**Issue by ammaratef45** [felangel/bloc#271]
Examples are using Future and SDK constraints include dart version less than `2.1`

We should either update SDK constraints or import async.

**Comment by felangel** [comment]
Hi @ammaratef45 👋 
Thanks for opening an issue!

Can you please be a bit more specific about which examples? Thanks!

**Comment by ammaratef45** [comment]
@felangel I confirm the issue in the login example, didn't check anymore examples
I can fix it by updating the sdk constraints if you would assign me

**Comment by felangel** [comment]
I would prefer we fix it while leaving the constraints just for the time being. In the near future I’ll go through all of them and bump the SDK constraints.

**Comment by felangel** [comment]
@ammaratef45 I just fixed this on master. Thanks for bringing this up! 💯
