### ISSUE TITLE
Hi team how to use two cross call blocks together please help me!

### ISSUE THREAD

**Issue by dev-khanh** [felangel/bloc#2724]
**Description**

I  have two blocs `PlayGameBloc` or `PhotonRealtimeBloc` in `MultiBlocProvider`. I want to put  `PhotonRealtimeBloc.of(context)` in `PlayGameBloc` how can I help please thanks, team!

<img width="411" alt="Screenshot 2021-09-08 at 12 48 28 PM" src="https://user-images.githubusercontent.com/13836791/132453502-c44064e7-2213-46b0-afcb-d10f53d3720c.png">

**Comment by nbourdin** [comment]
Hello,
You could make something like that : 

```
class Wrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => PlayGameBloc(...), 
      child: YourWidget()
    );
  }
}

class YourWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => PhotonRealtimeBloc(
        playBlocGame: PlayGameBloc.of(context),
        ...
      ), child: AnotherWidget());
  }
}
```

But i think the solution depends on your context, but there is a more elegant solution, maybe with the `BlocProvider.value(...)`

**Comment by dev-khanh** [comment]
Do you have an example of BlocProvider.value(...), thanks @nbourdin?

**Comment by nbourdin** [comment]
Something like that, but i think you can only use StatefullWidget 

```
class YourWidget extends StatefulWidget {
  @override
  State<YourWidget> createState() => _YourWidgetState();
}

class _YourWidgetState extends State<YourWidget> {

  late PlayGameBloc playGameBloc;

  @override
  void initState() {
    playGameBloc = PlayGameBloc(...);
    super.initState();
  }

  @override
  void dispose() {
    playGameBloc.close();
    super.dispose();
  }


  @override
  Widget build(BuildContext context) {
    return BlocProvider.value(
      value: playGameBloc,
      child: BlocProvider(
      create: (context) => PhotonRealtimeBloc(
        playBlocGame: playBlocGame,
        ...
      ), child: AnotherWidget())
    );
  }
}
```

**Comment by dev-khanh** [comment]
Hi, Bro @nbourdin I found another solution, or help me see it.


import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
// Providers
class AppProviders extends StatelessWidget {
  final Widget child;
  AppProviders({required this.child});
  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<PlayGameBloc>(
          create: (context) => PlayGameBloc(
            photonRealtimeBloc: PhotonRealtimeBloc.getInstance(),
          ),
        ),
        BlocProvider<PhotonRealtimeBloc>(
          create: (context) => PhotonRealtimeBloc(
            playGameBloc: PlayGameBloc.of(context),
          ),
        ),
      ],
      child: child,
    );
  }
}
// PLAY GAME
class PlayGameBloc extends Bloc<PlayGameEvent, PlayGameState> {
  final PhotonRealtimeBloc photonRealtimeBloc;
  PlayGameBloc({required this.photonRealtimeBloc}) : super(PlayGameState.initState());
  @override
  Stream<PlayGameState> mapEventToState(PlayGameEvent event) async* {}
  static PlayGameBloc of(BuildContext context) => BlocProvider.of<PlayGameBloc>(context);
}
abstract class PlayGameEvent extends Equatable{}
class PlayGameState extends Equatable{
  PlayGameState();
  PlayGameState.initState() : this();
  @override
  List<Object?> get props => [];
}

// PHOTON
class PhotonRealtimeBloc extends Bloc<PhotonRealtimeEvent, PhotonRealtimeState> {
  static PhotonRealtimeBloc? instance;
  final PlayGameBloc playGameBloc;
  PhotonRealtimeBloc({required this.playGameBloc}) : super(PhotonRealtimeState.initState()){
    instance = this;
  }
  static PhotonRealtimeBloc of(BuildContext context) => BlocProvider.of<PhotonRealtimeBloc>(context);
  static PhotonRealtimeBloc getInstance() => instance!;
  @override
  Stream<PhotonRealtimeState> mapEventToState(PhotonRealtimeEvent event) async* {}
}
abstract class PhotonRealtimeEvent extends Equatable{}
class PhotonRealtimeState extends Equatable{
  PhotonRealtimeState();
  PhotonRealtimeState.initState() : this();
  @override
  List<Object?> get props => [];
}

**Comment by nathanielxd** [comment]
Hello Khanh, it's generally not a good idea to use another bloc in a bloc, especially if you're aiming for consistent code. If PhotonRealtimeBloc depends on PlayGameBloc, see my answer below:

```
class AppProviders extends StatelessWidget {

  final playGameBloc = PlayGameBloc();

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider.value(playGameBloc),
        BlocProvider(
          create: (_) => PhotonRealtimeBloc(
            playGameBloc: playGameBloc
          ),
        ),
      ],
      child: child
    )
  }
}
```

**Comment by dev-khanh** [comment]
Thanks for the explanation @nathanielxd! it works great!
