### ISSUE TITLE
page rebuilding again and again after using pageroute with bloc library

### ISSUE THREAD

**Issue by mojtabaparvar** [felangel/bloc#273]
hi.
I have used your solution for page route
WidgetsBinding.instance.addPostFrameCallback((_){
 Navigator.of(context).pushNamed(‘/newRoute’);
});

but the next page is being rebuilt again and again. this is my code:
Stream<LoginOneState> mapEventToState(LoginOneEvent event) async* {

if (event is LoginOneButtonPressed) {

yield LoginOneLoading();

try {

await userRepo.authOne(event.phone);

} catch (e) {

yield LoginOneFailure(error: e.toString());

}

yield LoginOneCompleted();

}

}

and the ui part:
BlocBuilder<LoginOneEvent, LoginOneState>(

bloc: _loginOneBloc,

builder: (BuildContext context, LoginOneState state) {

if (state is LoginOneFailure) {

_onWidgetDidBuild(() {

Scaffold.of(context).showSnackBar(

SnackBar(

content: Text(‘${state.error}’),

backgroundColor: Colors.red,

),

);

});

}

if (state is LoginOneCompleted) {

WidgetsBinding.instance.addPostFrameCallback((_) {

Navigator.of(context)

.push(MaterialPageRoute(builder: (BuildContext context) {

return LoginTwoPage();

}));

});

}

**Comment by felangel** [comment]
Hi @mojtabaparvar 👋 
Thanks for opening an issue!

I would not recommend doing navigation in BlocBuilder. Check out the [navigation recipe](https://felangel.github.io/bloc/#/recipesflutternavigation) for detailed information on how to do navigation with flutter_bloc. 

Hope that helps 👍
