### ISSUE TITLE
question: How do I use a time stream in bloc to trigger time based events 

### ISSUE THREAD

**Issue by mfizz1** [felangel/bloc#2730]
Following on from my previous question of creating a time stream (Thank you @narcodico). I want to extend this further. I am trying to create a flutter app that is time based. A sort of dashboard with minimal to no user interaction. Which means most of the things are done automatically based on time based events. One such event are meetings. When a particular meeting time is reached I want to open a new screen showing the new meeting title and description for 5 minutes before returning to its previous screen again.

I think I understand some of how to do it but not all of it. I gather I would have to use `BlocListener` to do a Navigation but I am struggling to see where to add this so bloc navigates to and back. I would like to use the same "Timer" stream that is continuously running to update the time to compare against the meeting times. I gather then I would have to start a new timer of 5 minutes using `.take(5)` and then cancel / dispose of the timer and call the navigation back to the main screen.

Update: On second thought this is turning out to be more difficult than I thought. Currently have 2 blocs, CalendarBloc and TimeBloc. The time bloc is constantly updating the time. I need to somehow interact with the 2 states, incorrectly (probably) I was trying to do this in the UI code and should be doing it in the bloc layer.

**Comment by narcodico** [comment]
Hi @mfizz1 👋

You should probably not have a separate timer bloc but instead subscribe to that timer stream wherever you think it's needed, inside multiple feature blocs if needed.
To solve your given task, you could create multiple `Timer`s. As for closing the meeting just add a delayed event. A basic approach would be:
```
Timer(meetingTime.difference(DateTime.now()), () {
  // add event to start meeting
  Future.delayed(const Duration(minutes: 5), () {
    // add event to close meeting
  ));
});
```

But this would probably be an amateur solution. You'd probably be better off using scheduled cloud functions(if you're using firebase that is) and update some kind of meeting status on a meeting document. But this is out of the scope of bloc 😉

**Comment by felangel** [comment]
@mfizz1 closing for now but feel free to comment with any additional questions and we're happy to continue the conversation 👍

**Comment by mfizz1** [comment]
Thank you both! I think I am stuck on 2 problems at the moment. A suggested I have converted to a stream and displaying time using a StreamBuilder. However, within the same function I get the time from a network api, then generate the periodic stream adding 1 second to time fetched. Of course this means it is an async function.

I wanted to use this stream and subscribe to it in 2 different widgets, first to display  (where the stream is first called) and another to show a time difference between now and next event. Now I thought I was using the single instance of stream and subscribing to it, turns out I think I am creating 2 instances of a stream which then run in the background. Whilst not a problem I don't like it.. This is where I hope bloc / cubit can help in subscribing to the same stream.

The second problem is, that I am using bloc which returns data from repository and updates the state which is displayed on screen. I want to utilize the same data in another widget without having to fetch it again. I am not sure if that state data is available to access or not but stopping short of storing it in shared_preferences or get_storage is there another method i can use?
