### ISSUE TITLE
Events gets Dispatched with old state

### ISSUE THREAD

**Issue by PascalGehring** [felangel/bloc#2735]
**Description**
I would like to dispatch two events on the initialization of my widget: one event where the state gets retrieved from the cache [GetCachedTimetableEvent] and then one event where the fresh State gets requested remotely [GetFreshTimetable]. Both take in the oldTimetable(state before adding event).

**Expected Behavior**
 The Idea would be that GetCachedTimetable yields the CachedTimetable which gets Displayed and then GetFreshTimetable event should be added with the cachedTimetable gotten previously.

**Actual Behaviour**
What happens is that the GetFreshTimetable event gets added with the old state (initial) and not the new one gotten previously.

Any Answers Highly Appreciated!

**UI Code**
` 
        class TimetablePageMobile extends StatelessWidget {
        final BuildContext buildContextWholeScreen;
        final TabController tabController;
        final ScrollController scrollController;
  
    TimetablePageMobile(
        {Key? key,
        required this.tabController,
        required this.scrollController,
        required this.buildContextWholeScreen})
        : super(key: key);

    @override
    Widget build(BuildContext context) {
      final List<String> tabNames = [
        LocaleKeys.monday.tr(),
        LocaleKeys.tuesday.tr(),
        LocaleKeys.wednesday.tr(),
        LocaleKeys.thursday.tr(),
        LocaleKeys.friday.tr(),
      ];

    TimeManager timeManager = sl<TimeManager>();

    final String appBarText =
        '${LocaleKeys.week.tr()} ${timeManager.getWeekNumber()}';

    return BlocListener<TimetableBloc, TimetableState>(
      listener: (context, state) {
        if (state is TimetableRefreshed) {
          showSnackBar(
              context: context, message: state.message, isError: false);
        } else if (state is TimetableRefreshError) {
          showSnackBar(
              context: context, message: state.errorCode, isError: true);
        }
      },
      child:
          BlocBuilder<TimetableBloc, TimetableState>(builder: (context, state) {
        late Timetable timetable;
        if (state is TimetableInitial) {
          timetable = state.emptyTimetable;
        } else if (state is TimetableRefreshing) {
          timetable = state.oldTimetable;
        } else if (state is TimetableCached) {
          timetable = state.timetable;
        } else if (state is TimetableRefreshed) {
          timetable = state.timetable;
        } else if (state is TimetableRefreshError) {
          timetable = state.oldTimetable;
        } else if (state is TimetableCacheError) {
          timetable = state.oldTimetable;
        }

        Future<void>? onRefresh() {
          BlocProvider.of<TimetableBloc>(context)
              .add(GetFreshTimetable(oldTimetable: timetable));
        }

        return StatefulWrapper(
          onInit: () async {
             BlocProvider.of<TimetableBloc>(context)
               .add(GetCachedTimetable(oldTimetable: timetable));
       

          },
          child: MobilePage(
            tabs: [
              DayTabMobile(
                  onRefresh: () async {
                    onRefresh();
                  },
                  day: timetable.weeks[0].days[0],
                  buildContextWholeScreen: buildContextWholeScreen),
              DayTabMobile(
                  onRefresh: () async {
                    onRefresh();
                  },
                  day: timetable.weeks[0].days[1],
                  buildContextWholeScreen: buildContextWholeScreen),
              DayTabMobile(
                  onRefresh: () async {
                    onRefresh();
                  },
                  day: timetable.weeks[0].days[2],
                  buildContextWholeScreen: buildContextWholeScreen),
              DayTabMobile(
                  onRefresh: () async {
                    onRefresh();
                  },
                  day: timetable.weeks[0].days[3],
                  buildContextWholeScreen: buildContextWholeScreen),
              DayTabMobile(
                  onRefresh: () async {
                    onRefresh();
                  },
                  day: timetable.weeks[0].days[4],
                  buildContextWholeScreen: buildContextWholeScreen),
            ],
            tabNames: tabNames,
            tabController: tabController,
            scrollController: scrollController,
            appBarText: appBarText,
          ),
        );
      }),
    );
  }
}

`

**Timetable Bloc**
`
          class TimetableBloc extends Bloc<TimetableEvent, TimetableState> {
            final GetTimetable getTimetable;
            final GoogleAnalyticsService googleAnalyticsService;
          
            TimetableBloc(
                {required this.getTimetable, required this.googleAnalyticsService})
                : super(TimetableInitial());
          
            @override
            Stream<TimetableState> mapEventToState(
              TimetableEvent event,
            ) async* {
              if (event is GetFreshTimetable) {
                yield* _mapGetFreshTimetableToState(event);
              }
              if (event is GetCachedTimetable) {
                yield* _mapGetCachedtimetableToState(event);
              }
            }
          
            int _mapFailureToErroCode(Failure failure) {
              googleAnalyticsService.log(failure);
              switch (failure.runtimeType) {
                case ServerFailure:
                  return SERVER_FAILURE;
                case OfflineFailure:
                  return OFFLINE_FAILURE;
                case AuthFailure:
                  return AUTH_FAILURE;
                default:
                  googleAnalyticsService.log('UnexpectedFailure');
                  return UNEXPECTED_FAILURE;
              }
            }
          
          
          
          
          Stream<TimetableState> _mapGetFreshTimetableToState(
                GetFreshTimetable event) async* {
              googleAnalyticsService.log(event);
              // TODO: Modify tests with expect: TimetableRefreshing(oldTimetable: oldTimetable)
              yield TimetableRefreshing(oldTimetable: event.oldTimetable);
              final Either<Failure, Week> failureOrTimetable = await (getTimetable(true));
              yield* failureOrTimetable.fold((failure) async* {
                yield TimetableRefreshError(
                    errorCode: _mapFailureToErroCode(failure),
                    oldTimetable: event.oldTimetable);
              }, (week) async* {
                googleAnalyticsService.log('GetFreshTimetableSucess');
                yield TimetableRefreshed(
                    timetable: Timetable([week]), message: REFRESH_SUCESS_MESSAGE);
              });
            }
          
          
           Stream<TimetableState> _mapGetCachedtimetableToState(
                GetCachedTimetable event) async* {
              googleAnalyticsService.log(event);
              final Either<Failure, Week> failureOrTimetable =
                  await (getTimetable(false));
          
              yield* failureOrTimetable.fold((failure) async* {
                googleAnalyticsService.log(failure);
                yield TimetableCacheError(oldTimetable: event.oldTimetable);
              }, (week) async* {
                yield TimetableCached(timetable: Timetable([week]));
              });
            }

`

**Comment by marcossevilla** [comment]
hi @PascalGehring! you should be able to chain 2 events like [this](https://github.com/NoScopeDevs/bloc_samples/blob/96e4051131635a5d8511a554f176d789635ccaad/examples/preference_navigation/lib/preferences/bloc/preferences_bloc.dart#L43) if you want another one to happen right after the other every time. 

Or just chaining them as your bloc is created, like [this](https://github.com/NoScopeDevs/bloc_samples/blob/96e4051131635a5d8511a554f176d789635ccaad/examples/preference_navigation/lib/app/app.dart#L29). If you do this one, probably you want to add a `transformEvents` to process your events sequentially, as they might overlap each other.

Let me know if that helps. 👍

**Comment by PascalGehring** [comment]
Hi @marcossevilla! Thank you for your response. I tried both solutions. When I'am Adding the state with the creation of the bloc it stays longer because the getFresh Event is added later. But as soon as the getFresh Event is added, somehow the event gets still added with the initial state...

**Comment by PascalGehring** [comment]
> I haven't really studied your code, but a problem I recently had is that 2 states yielded right after one another (state A -> state B -> state A) get ignored. There should be a time lag of about 50ms between both yield statements, otherwise the UI has not updated with state B and is still in state A (as such ignoring a new state A).

Thanks @w461 for your answer. I tried it with `await Future.delayd(Duration(seconds:10))` between the two events and it still doesn't work. The state is rebuild with the cachedData but the event isn't dispatched with the current state...

**Comment by Gene-Dana** [comment]
Hi there 👋🏼

Can you share with us a reproducible example? Or a repo?

**Comment by PascalGehring** [comment]
It's a private projects but I could add you guys to the repository temporarily.

**Comment by PascalGehring** [comment]
I sent you guys an invitation.

**Comment by PascalGehring** [comment]
I'll create a reproducible repo

**Comment by PascalGehring** [comment]
Here's the Link to the repo: https://github.com/PascalGehring/bloc_bug.git
Thank you for your effort!

**Comment by PascalGehring** [comment]
@Gene-Dana, @marcossevilla, @felangel: Does the repo need clarification?
Thank you for your answers.

**Comment by elianmortega** [comment]
Hello @Gene-Dana, I did check your example with @marcossevilla, 

To understand what is happening and why in your example your "event gets dispatched with old state", you need to understand that streams are asynchronous objects. What you are doing in your code is adding 2 events one after another without taking into account that the methods being triggered by the `GetCachedTimetable` are `async` so its possible that the 2nd event is added without the state being already changed. 

If you want to ensure that the state is fully initialized before adding `GetFreshTimetable` I'll recommend making a singe event that do all the work like `TimetableInitialized()` with this you could `await` for the locally fetched Timetable and only when the local query of the timetable is done you could continue to do the work for the external fetching of your timetable.

Hope you find this helpful.

I did spot some bad practices regarding naming and dart in general, I'll highly recommend checking the [bloclibrary.dev](https://bloclibrary.dev/#/coreconcepts) core concepts so you have a better understanding of what is going on. And also the use of a linter like [Very Good Analysis](https://pub.dev/packages/very_good_analysis) this will help a lot giving you hints of how to write better code.

**Comment by PascalGehring** [comment]
@elianmortega Thank you so much for your detailed explanation. I added a new Event and it worked perfectly. Thank you also for your honest feedback on my code: I'll checkout the bloclibrary.dev core concepts and install the Very Good Analysis to improve my code.

@felangel your package is one of the best maintained flutter packages out there.
