### ISSUE TITLE
docs: how to update user data provided by AuthState.authenticated

### ISSUE THREAD

**Issue by w461** [felangel/bloc#2737]
I am wondering how to update the user data if you store the user in an authentication bloc state. Imagine someone wanting to edit a typo in his/her name or changing a preference.

Basically I am using the Firestore authentication tutorial which I quite like with `state.authenticated(user)`
```dart
 @override
  Stream<AuthState> mapEventToState(
    AuthEvent event,
  ) async* {
    yield* event.map(
      authCheckRequested: (e) async* {
        final userOption = await _authFacade.getSignedInUser();
        yield userOption.fold(
              () => const AuthState.unauthenticated(),
              (user) => AuthState.authenticated(user),
        );
      },
      signedOut: (e) async* {
        await _authFacade.signOut();
        yield const AuthState.unauthenticated();
      },
    );
  }
```
If the user is authenticated and updates any of his/her data, I would like to call the `authBloc` again with event `AuthCheckRequested`. However, since the state has not changed, it would not update the `user` (not yield the same state again). So I could yield an intermittent state. But this does not feel right to have any other state than authenticated in between. And worse, I would have to pause code execution for 50 to 100ms, because otherwise BLoC will ignore the sequence of state A -> intermittent state -> state A.

Any ideas how to approach this?

(copy of my (unanswered) question on stackoverflow)

PS: In the app I am getting all info on the user from the authState user

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 Help me understand this a little bit more. 

The user itself is actually a stream from the repo already. Meaning, if anything changes with the user, the repo will see that

https://github.com/felangel/bloc/blob/388e329335159f8e027a65e0a6778d2f7632c730/examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart#L50-L60

Inside the App bloc, this is where we subscribe to that stream and react to it
https://github.com/felangel/bloc/blob/388e329335159f8e027a65e0a6778d2f7632c730/examples/flutter_firebase_login/lib/app/bloc/app_bloc.dart#L12-L26

This is how you would call an event based on at change in User data with this pattern

**Comment by w461** [comment]
Apologies, I am noticing that my implementation (adapted from Reso Coder's DDD tutorial) differs more from yours than I thought from remembering your tutorial. I still had this `AuthState.authenticated(user)` in mind. I am triggering authchecks by singular events, not with a stream. My app's focus is on offline use and hence I never really thought about streaming a firebase user. 2nd reason for this is that I am storing most user data only locally for privacy reasons (more to give a better feeling than a better level of privacy...). 

Anyhow, do you have an advice for me how to best solve this 😅

**Comment by Gene-Dana** [comment]
My advice: follow the Flutter Firebase Login tutorial exactly !

**Comment by Gene-Dana** [comment]
It has a cache built into, meant specfically for this type of situation

**Comment by w461** [comment]
I was already convinced, but then, if I understand this correctly, updating the user data would need an online connection, right.

Besides, fyi, the cache package used in the tutorial is not Dart 2 compatible and it appears not to be maintained any longer

**Comment by Gene-Dana** [comment]
I'm pretty sure it is Dart 2 compatible! And, it's a package that's included in the example itself - it's not a pub.dev package

**Comment by Gene-Dana** [comment]
At the end of the day.. you are speaking to an example that's not we do not maintain ! It's tough for us to help in that scenario.

The approach from the examples is one where the AppBloc holds the user state, and that's streamed from the Authentication Repository so that anytime the user information changes, the AppBloc receives the information. 

The whole point of subscribing to streams like this is to avoid the problems that arise when you try to manually fetch. If you manually fetch and then push to a specific bloc, then the repositories themselves have a dependency on that bloc, something which is the opposite of Bloc's declarative nature.

Even if the application offline, the state of the user can still be streamed from an authentication repo to the app bloc

**Comment by w461** [comment]
Your efforts for maintaining bloc are highly appreciated and I am well aware that you are no help hotline. I was mistaken, because I thought my issue was of general nature and related more closely to your tutorial than it actually is.

I got your point and I see the advantage of the user stream. I guess your cache method won't work "out-of-the-box" for my use case, but I have an idea how to mix the online stream with some kind of an offline stream.

Thanks
