### ISSUE TITLE
question: [flutter_firebase_login] How to determine if signed in user is a new user?

### ISSUE THREAD

**Issue by VictorUvarov** [felangel/bloc#2738]
**Description**

How would you change the current  `flutter_firebase_login` example to show a specific page for new users that sign in via password, phone, or OAuth?

**Some context**
When you sign in or sign up with firebase, you are able to see if the user is a **new** user via the `UserCredential` object return from all the auth methods (e.g. `createUserWithEmailAndPassword`, `signInWithEmailAndPassword`, `signInWithCredential`).

**Alternatives Considered**

I've considered using something like `shared_preferences` or a local database, but those solutions don't work if the user deletes the app and reinstalls it or installs the app on a different device.

**Current Solution**

I've had to remove the global auth changes listener for determining what page to show and let the login page determine what page to show instead. Whatever screen logs the users out will pop all the screens and show the signed out screen.

**Comment by Gene-Dana** [comment]
Hi there 👋 Have you taken a look at the authentication repository? In there, you have all the alternative sign-in methods already implemented and tested!

**Comment by VictorUvarov** [comment]
How would I determine what String to pass in?

**Comment by Gene-Dana** [comment]
I would use an onClick to setState of a String held in a stateful widget, and then perhaps trigger the navigation based on that.

**Comment by Puspharaj** [comment]
I would say as long as the user data not saved somewhere, Then every user would be treated as new user. If I save the user data in local or remote it would be nice to treat them every time even if the uninstalled my app and returning to my app(stored in firebase ).
