### ISSUE TITLE
feat: Reuse Cubit Multiple Times

### ISSUE THREAD

**Issue by pitanni** [felangel/bloc#2739]
Hi, I can't understand if this is already feasible or if it is a future request. 
It would be great to have the ability to reuse the same cubit multiple times (even with dynamic objects). 
Let me explain: it would be great to have the possibility of passing the same BlocProvider with different names several times in the MultiBlocProvider. This avoids replicating code. 
For example, the cubit for the management of Top Products is the same for Top Stores, the difference is only in the object passed which can be dynamic. 
Sorry for my English. I hope I was clear.

**Comment by Gene-Dana** [comment]
Hi there ! Yes, it's already possible to create multiple instances of the same cubit, each one of them being unique in and of themselves. @felangel is there an example of this nearby?

**Comment by felangel** [comment]
Hi @pitanni 👋 
Thanks for opening an issue!

You can provide multiple instances of they are managing different types of state for example:

```dart
MultiBlocProvider(
  providers: [
    BlocProvider<MyBloc<StateA>>(create: (_) => MyBloc<StateA>()),
    BlocProvider<MyBloc<StateB>>(create: (_) => MyBloc<StateB>()),
    BlocProvider<MyBloc<StateC>>(create: (_) => MyBloc<StateC>()),
  ],
  child: ...
);
```

Then later you can access whichever you want via `context.read`:

```dart
final a = context.read<MyBloc<StateA>>();
final b = context.read<MyBloc<StateB>>();
final c = context.read<MyBloc<StateC>>();
```

Hope that helps 👍

**Comment by pitanni** [comment]
Yeahhhh! Thanks @felangel. It works!
