### ISSUE TITLE
chore: 

### ISSUE THREAD

**Issue by programming6131** [felangel/bloc#2742]
when using BlocConsumer the listener is a required parameter , what if i dont need to use it in my code ? do i have to just call the listener function and leave an empty todo or can it be made optional ?

**Comment by felangel** [comment]
Hi @programming6131 👋 
Thanks for opening an issue!

`BlocConsumer` is meant for when you want to both rebuild and react to state changes. If you only need to rebuild in response to state changes you should use `BlocBuilder` and if you only want to react to state changes you should use `BlocListener`. Hope that helps 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation.
