### ISSUE TITLE
question: Using bloc/cubit to subscribe to Stream.periodic()

### ISSUE THREAD

**Issue by mfizz1** [felangel/bloc#2743]
Appreciate all the help that is being provided here. However I am stuck on an element. Using the help provided here, I have created a cubit that fetches time from a server and then increments 1 second to simulate the current time based on location. The below code works well with `StreamBuilder` because of passing the stream as a state change which I then use in `stream`. 

```
Stream<DateTime> currentTimeIs() async* {
  DateTime local = await fetchLocationTime();
  yield* Stream.periodic(
    Duration(seconds: 1),
    (x) => local
        .add(
          const Duration(seconds: 1),
        )
        .add(
          Duration(seconds: x),
        ),
  );
}

class TimerCubit extends Cubit<TimerState> {
  TimerCubit() : super(TimerInitial(DateTime.now()));

  void startTimer() => currentTimeIs().listen(
        (event) => emit(
          TimerTicked(event),
        ),
      );
}

```
For the sake of improving the performance, I want to streamline as much as possible. My question is how can I use `Stream.periodic` (which has the ability to broadcast stream) and use it directly in child widgets utilizing bloc/cubit instead of emitting a state. I have tried triggering an event and subscribing to it and then subscribing in another widget, but this creates 2 streams as opposed to subscribing to the same stream. I know this is something very trivial finding it difficult to wrap my head round it.

**Comment by felangel** [comment]
Hi @mfizz1 👋 
Thanks for opening an issue!

If I understood correctly, you should be able to do something like:

```dart
class TimerCubit extends Cubit<TimerState> {
  TimerCubit() : super(TimerInitial(DateTime.now()));

  @override
  Stream<TimerState> get stream {
    return Stream<int>.periodic(const Duration(seconds: 1), (_) => _)
      .asyncMap<TimerState>((x) async {
        final local = await fetchLocationTime();
        return TimerState(local.add(Duration(seconds: x)));
      });
}
```

I'm not sure I fully understood what you're trying to achieve though and in general I don't recommend doing this because you are overriding the built in state stream and not really taking advantage of using Cubit. If that's all you need to do then it's probably simpler/more fitting to just stick to using a `StreamBuilder` like:

```dart
return StreamBuilder(
  initialData: TimerState(DateTime.now()),
  stream: Stream<int>.periodic(const Duration(seconds: 1), (_) => _)
    .asyncMap<TimerState>((x) async {
      final local = await fetchLocationTime();
      return TimerState(local.add(Duration(seconds: x)));
    }),
  builder: (context, snapshot) {
    // ...
  },
);```

Let me know if that helps 👍

**Comment by mfizz1** [comment]
Hi @felangel tha k your for responding.

Apogies for not making my question clear. I simply want to use stream.periodic and create a single stream (instance / singleton) that is accessible by many child widgets. Similar to how one would use stream controller and inherited widgets.

I am currently using stream builder to create the widget. Your alternative solution creates the stream in the steambuilder and updates the state of the TimerState, which other widgets could listen to? Do you believe this is the most efficient way. I mean that as a complete novice in this situation, I'm looking for advice.

I thought that there would be some native way to use stream.periodic since it has Broadcast and asbroadcaststream methods.

**Comment by narcodico** [comment]
You can use a `StreamProvider` on top of your `MaterialApp` then you can get your state anywhere in the app. It's part of the `provider` package.

**Comment by mfizz1** [comment]
@narcodico and @felangel thank you both. I think I will stick to the solution provided by yourself earlier as I don't want 2 state management solutions in my app.. Perhaps for the next one I will look at provider I think bloc / cubit it easier to digest.

**Comment by narcodico** [comment]
`provider` is not a state management solution, pragmatically speaking that is 😉
It's just a dependency injection tool, which is actually used by the bloc library under the hood.
