### ISSUE TITLE
 question: emit several states one by one

### ISSUE THREAD

**Issue by octokim** [felangel/bloc#2744]
I need to emit several states one by one, but builder takes only last state (while listener takes them all)

```
class SomeCubit extends Cubit<SomeState> {
  ExperimentalCubit() : super(SomeState());

  void exec() {
    emit(StateA());
    emit(StateB());
    emit(StateC());
  }
}

class SomeView extends StatefulWidget {
  const SomeView({Key? key}) : super(key: key);

  @override
  _SomeViewState createState() => _SomeViewState();
}

class _SomeViewState extends State<SomeView> {
  @override
  Widget build(BuildContext context) {
    return BlocConsumer<ExperimentalCubit, ExpS>(
      listener: (context, state) {
        print('listen -> ${state.runtimeType}');
      },
      builder: (context, state) {
        print('build -> ${state.runtimeType}');
        return Center(child: CupertinoButton(child: Text('wow'), onPressed: () => BlocProvider.of<ExperimentalCubit>(context).exec()));
      },
    );
  }
}
```
I got next output
```
build -> SomeState
listen -> StateA
listen -> StateB
listen -> StateC
build -> StateC
```

is it a common behavior?

**Comment by felangel** [comment]
Hi @octokim 👋 
Thanks for opening an issue!

This is working as expected. The problem you're facing is the state of the cubit is changing faster than the UI can rebuild. The same thing will happen if you use `setState` and update the state back to back. See #173 (comment)

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by octokim** [comment]
@felangel thanks for your answer!
But now I'm wondering how to handle this behavior. Have you some workarounds? Or maybe I misuse Bloc lib and it's wrong to emit more than one state at once?

**Comment by octokim** [comment]
Any suggests?

**Comment by marcqtan** [comment]
same question. any suggestion for this problem?

**Comment by felangel** [comment]
@octokim @marcqtan if you need to emit states in succession which all contain relevant data to the UI then I recommend restructuring your state to aggregate the info rather than having pieces of data scattered throughout multiple states:

```dart
class MyState {
  final String someValue;
  final String someOtherValue;

  MyState copyWith(...) {...}
}
```

This would allow you to emit in succession without risk of losing any state:

```dart
emit(state.copyWith(someValue: 'someValue'));

// Later...

emit(state.copyWith('someOtherValue: 'someOtherValue'));
```

This way you're constantly aggregating relevant data so that the UI has everything it needs at all times to render correctly. Let me know if that helps 👍

**Comment by marcqtan** [comment]
> @octokim @marcqtan if you need to emit states in succession which all contain relevant data to the UI then I recommend restructuring your state to aggregate the info rather than having pieces of data scattered throughout multiple states:
> 
> ```dart
> class MyState {
>   final String someValue;
>   final String someOtherValue;
> 
>   MyState copyWith(...) {...}
> }
> ```
> 
> This would allow you to emit in succession without risk of losing any state:
> 
> ```dart
> emit(state.copyWith(someValue: 'someValue'));
> 
> // Later...
> 
> emit(state.copyWith(someOtherValue: 'someOtherValue'));
> ```
> 
> This way you're constantly aggregating relevant data so that the UI has everything it needs at all times to render correctly. Let me know if that helps 👍

@felangel 

Hello Thanks for this. I've tried your suggestion but seems like i cannot access properties of the states?: 

**Mystate:**

<img width="513" alt="Screen Shot 2021-11-11 at 10 58 17 AM" src="https://user-images.githubusercontent.com/66229352/141229554-9a5503a2-c806-49db-b5d3-661e635ceaa2.png">

**MyCubit:**
<img width="558" alt="Screen Shot 2021-11-11 at 10 57 56 AM" src="https://user-images.githubusercontent.com/66229352/141229427-80099e11-2929-4b06-ac6d-c0b4794cc24c.png">

As you can see, in my cubit, i cannot access the "color" or "lastpage" field of MyStateLoaded. Any ideas why ?

Thanks!

**Comment by octokim** [comment]
@marcqtan because state is a getter, it returns value that is not final. You can do something like this:
```
final s = state;
if (s is MyStateLoaded) {
  s.color;
}
```
As far as I understand, @felangel is talking about defining full state in a base state class. But, if so, there are no reasons to have more than one state for each bloc/cubit and handling of this state becames very difficult.
