### ISSUE TITLE
update/refresh bloc data?

### ISSUE THREAD

**Issue by hesamchobanlou** [felangel/bloc#2745]
Good day,

I have been following the Infinite List example from the official documentation.

For my use-case, the data is retrieved from the API and shown as a list of item. However, I am wondering what the best approach is to update the list of items (let's assume a db insert happened from another user) periodically or through a pull-down-refresh.

What's the best practice to reset the data stored in a bloc and retrieve this data again?

Thanks.

**Comment by felangel** [comment]
Hi @hesamchobanlou 👋 
Thanks for opening an issue!

If you want to update the data you can add an `UpdateRequested` event to the bloc when an update is requested (either in response to a pull-to-refresh request or a periodic timer):

```dart
onRefresh: () {
  context.read<MyBloc>().add(UpdateRequested());
}
```

Then in the bloc you can perform the update and return the latest data:

```dart
if (event is UpdatedRequested) {
  try {
    final posts = await _fetchPosts(...);
    yield state.copyWith(posts: posts);
  } catch (_) {
    // handle errors
  }
}
```

Hope that helps 👍

**Comment by hesamchobanlou** [comment]
Thank you @felangel, that worked out perfectly.
