### ISSUE TITLE
build: [angular_bloc] angular 7.0.0 (null safety)

### ISSUE THREAD

**Issue by afpatmin** [felangel/bloc#2750]
**Description**

Update version restrictions and migrate to null safety to support newly released angular 7.0.0. 

Fixes the following build error:
`Because angular_bloc >=6.0.0 depends on angular ^6.0.1 and [PROJECT] depends on angular ^7.0.0, angular_bloc >=6.0.0 is forbidden.`

**Comment by felangel** [comment]
Hi @afpatmin 👋 
Thanks for opening an issue!

Apologies, I must've missed the v7.0.0 angular release 😅 
Just published [angular_bloc v7.0.0](https://pub.dev/packages/angular_bloc/versions/7.0.0) which supports angular v7.0.0 🎉
