### ISSUE TITLE
feat: please provide option to send first state to listen

### ISSUE THREAD

**Issue by steeling** [felangel/bloc#2752]
This has been talked about countless times. The workarounds leave require too much boilerplate. Why not add an optional param to allow calling listen on the bloc's initial state?

**Comment by felangel** [comment]
Hi @steeling 👋 
Thanks for opening an issue!

If you really want that behavior you can easily achieve it by overriding the `stream` with `rxdart` like:

```dart
@override
Stream<State> get stream => super.stream.startWith(state);
```

Hope that helps 👍

**Comment by steeling** [comment]
nice, thanks for the tip!
