### ISSUE TITLE
refactor: improve bloc with stream example

### ISSUE THREAD

**Issue by plibr** [felangel/bloc#2768]
Am I able to show 'Press the floating button to start' text after Ticker class tick 10 times?

[here](https://github.com/felangel/Bloc/blob/master/examples/flutter_bloc_with_stream/lib/main.dart)

I suppose that I might change this part: 

```dart
body: BlocBuilder<TickerBloc, TickerState>(
    builder: (context, state) {
        if (state is TickerTickSuccess) {
            return Center(
                child: Text('Tick #${state.count}'),
            );
        }
        return const Center(
            child: Text('Press the floating button to start'),
        );
    },
),```

How can I change it?

**Comment by felangel** [comment]
Hi @plibr 👋 
Thanks for opening an issue!

I opened #2774 which updates the example app to include a complete state when the ticker is done.

Hope that helps 👍

**Comment by plibr** [comment]
is there a way to do this without bloc_concurrency? 
I was confusing until this, and now confused 200% :)

**Comment by felangel** [comment]
> is there a way to do this without bloc_concurrency?
> I was confusing until this, and now confused 200% :)

What specifically are you confused about? The reason for bloc_concurrency in this case is to cancel the previous ticker subscription if the user taps the button while the ticker is in progress.
