### ISSUE TITLE
[Design Question] Multiple isolated operations ?

### ISSUE THREAD

**Issue by matanshukry** [felangel/bloc#277]
Consider a scrolling list of items, where on each item a "remove button" exist. It is possible for the user to click the button on multiple times, before previous ones finished, so multiple network calls, each one removing a different item, may be done in parallel.

(1) How would one design a state for such a thing?

Considering the tree, you would want a widget for the item in the scrolling list, which also includes a BlocBuilder, where you could check the state and show a (a) the button, (b) a progress indicator.

(2) How would one design the list versus the single item state?
My initial thought is creating 2 blocs - one for the list, and one for the single item. When removing an item, the single item bloc will do the operation (SingleItemRemoving(), SingleItemRemoved), and on success it will also dispatch a RemoveItemFromList() event to the list bloc. What do you think?

**Comment by felangel** [comment]
Hi @matanshukry 👋 
Thanks for opening an issue and great question!

I think you're proposed solution should work just fine. I'll go through the exercise over the next few days and will share my solution as well. 👍

Thanks again! 😄

**Comment by matanshukry** [comment]
Well my proposed solution is actually only for (2). For (1), I didn't really say anything.
I did come up with something so far though: I have a single state, that has a list of items with states, and when I need to update any one of them, I create a new state with the same type, and the same list, but different value inside.

It works, but it means the entire tree is being rebuilt, even though only 1 item changes (although I think flutter may do cache to the widgets as well, but not sure about it)

**Comment by felangel** [comment]
@matanshukry sorry for the delay! I've put together an example of what I think you're trying to accomplish under [examples/flutter_complex_list](https://github.com/felangel/bloc/tree/master/examples/flutter_complex_list).

Hope that helps! 👍

**Comment by matanshukry** [comment]
@felangel Yeah the general form is what I mentioned as my current idea. Seems to be spot on!
I have a few questions though regarding your specific implementation:

1. why copy every item (the not deleteing ones I mean) ?
https://github.com/felangel/bloc/blob/master/examples/flutter_complex_list/lib/bloc/list_bloc.dart#L33

2. after deleteItem(), you listen and wait for it to finish, dispatch another event, and then handle it. Why not just do await and yield() w/e new data you want?

**Comment by felangel** [comment]
@matanshukry awesome!

1. Oops that's my mistake (I was too tired when writing the example 😆). We don't need to use copyWith for the non-deleted items. (I'll update the example).
2. If we `await` then we will block the bloc event loop and it will prevent us from being able to execute multiple deletions in parallel.

Hope that helps and great questions 👍
