### ISSUE TITLE
docs: BLoC Exception Handling - Firebase Login Tutorial 

### ISSUE THREAD

**Issue by jasonjackson** [felangel/bloc#2775]
Hello, I am unable to find any clear best practice examples of how exception handling is best implemented.  I'm new to flutter, and was looking to learn by implementing better handing in the Firebase Login example.  Currently, if a new user signs up and any of the supported firebase exceptions are thrown for invalid-email, user-disabled, user-not-found, wrong-password, email-already-in-use, these are captured as a general Exception and "Sign Up Failure" is displayed in the SnackBar.  I would like to have this SnackBar instead display a more informative message that maps to the specific exception.  I suspect this is a common challenge for other beginners, and would like to contribute back a PR or help with documentation once I understand it myself. 

This is my current thinking:

In [authentication_repository.dart](https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart):

I'm importing firebase_auth_platform_interface to get access to FirebaseAuthException

`import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart';`

Then I am using FirebaseAuthException to parse error codes and messages in the signUp future

```
  Future<void> signUp({required String email, required String password}) async {
    try {
      await _firebaseAuth.createUserWithEmailAndPassword(
        email: email,
        password: password,
      );
    } on FirebaseAuthException catch (e) {
      if (e.code == 'email-already-in-use') {
        print('DEBUG: ${e.message}');
      }
    }
  }
```

What I am not clear on, is how to make a String based on `e.message` available in [sign_up_form.dart](https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/lib/sign_up/view/sign_up_form.dart)?

```
  Widget build(BuildContext context) {
    return BlocListener<SignUpCubit, SignUpState>(
      listener: (context, state) {
        if (state.status.isSubmissionSuccess) {
          Navigator.of(context).pop();
        } else if (state.status.isSubmissionFailure) {
          ScaffoldMessenger.of(context)
            ..hideCurrentSnackBar()
            ..showSnackBar(
              const SnackBar(content: Text('Sign Up Failure')),
            );
        }
      },
```

I'm assuming this should all go through the bloc?  Would I add an "error" props to sign_up_state.dart?  Or emit from inside the exception catch if statement?  Or is this when you want to use addError / onError (which I don't really understand from the documentation) and if so then how is the best way to present that in the SnackBar? 

Any help on best approach would be awesome.  Thanks!

**Comment by nathanielxd** [comment]
You could create your own exception for authentication.

```
class AuthenticationException implements Exception {
  
  final String message;
  AuthenticationException(this.message);

  /// Create an authentication message from a firebase authentication exception code.
  factory AuthenticationException.fromCode(String code) {
    switch(code) {
      case 'invalid-email': return AuthenticationException('Email is not valid or badly formatted.');
      case 'user-disabled': return AuthenticationException('This user has been disabled. Please contact support for help.');
      default: return AuthenticationException('An unknown exception occurred!');
    }
  }
}
```
In your API provider catch a FirebaseException and throw an AuthenticationException:

```
  Future<void> signUp({required String email, required String password}) async {
    try {
      await _firebaseAuth.createUserWithEmailAndPassword(
        email: email,
        password: password,
      );
    } on FirebaseAuthException catch (e) {
      throw AuthenticationException.fromCode(e.code);
    }
  }
```

in your BLOC or Cubit, when authenticating, catch the AuthenticationException and emit a state that contains the error message. So your state should look like this:

```
class SignUpState extends Equatable {
  // Your other fields here.
  final String? errorMessage;
}
```

And your signup method in the cubit:

```
void signup() {
  try {
    // Stuff here
  }
  on AuthenticationException catch(e) {
    emit(state.copyWith(errorMessage: e.message));
  }
}
```

Hope it helps.

**Comment by jasonjackson** [comment]
Hi nathanielxd

I really appreciate it.  Not only does it help to get it working, but it also helps to connect a few dots on bloc / cubit.  Thank you!

I'll get exception handing added to other sign-up / login use cases and send it over as a PR if felangel would like to merge it.  At minimum i'll get it up on github and link it here for others. 

Thanks again!
