### ISSUE TITLE
how change Flutter Files template for v7.2.0-8.0.0

### ISSUE THREAD

**Issue by Gorniv** [felangel/bloc#2776]
i'm developer https://marketplace.visualstudio.com/items?itemName=gornivv.vscode-flutter-files (176,248) and i don't understand easy way for migrate:
bloc:
```dart
@override
  Stream<YouAwesomeState> mapEventToState(
    YouAwesomeEvent event,
  ) async* {
    try {
      yield* event.applyAsync(currentState: state, bloc: this);
    } catch (_, stackTrace) {
      developer.log('$_', name: 'YouAwesomeBloc', error: _, stackTrace: stackTrace);
      yield state;
    }
  }
```
event:
```dart
class LoadYouAwesomeEvent extends YouAwesomeEvent {
   
  @override
  Stream<YouAwesomeState> applyAsync(
      {YouAwesomeState? currentState, YouAwesomeBloc? bloc}) async* {
    try {
      yield UnYouAwesomeState();
      await Future.delayed(const Duration(seconds: 1));
      yield InYouAwesomeState('Hello world');
    } catch (_, stackTrace) {
      developer.log('$_', name: 'LoadYouAwesomeEvent', error: _, stackTrace: stackTrace);
      yield ErrorYouAwesomeState( _.toString());
    }
  }
}

```

**Comment by felangel** [comment]
Hi @Gorniv 👋 
Thanks for opening an issue!

I don't really recommend this pattern where your events contain the logic to map themselves to states but the v7.2.0 equivalent would be:

```dart
class YourAwesomeBloc extends Bloc<YourAwesomeEvent, YourAwesomeState> {
  YourAwesomeBloc() : super(UnYourAwesomeState()) {
    on<YourAwesomeEvent>((event, emit) {
      emit.forEach<YourAwesomeState>(
          event.applyAsync(currentState: state, bloc: this),
          onData: (state) => state);
    });
  }
}
```

Hope that helps 👍

**Comment by Gorniv** [comment]
Why logic is responsibility bloc?
if bloc do 'event is ...{logic}' - event do logic.
Bloc responsibility how event apply.

**Comment by felangel** [comment]
> Why logic is responsibility bloc?
> if bloc do 'event is ...{logic}' - event do logic.
> Bloc responsibility how event apply.

Bloc is your business logic component. Its responsibility is reacting to incoming events and emitting states. Events and States should ideally just be data classes. When the UI adds an event to the bloc that event shouldn’t know/contain logic about how it will be transformed into a state — this approach means the event is tightly coupled to the state and exposes a public API which anyone can call from anywhere.

If you still prefer this approach that’s fine but I personally don’t recommend it.

Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍
