### ISSUE TITLE
Prevent Code Duplication 

### ISSUE THREAD

**Issue by PouryaNoufallah96** [felangel/bloc#2780]
Hi!
I have some code duplicates in one of my projects. For example, in the two pages that just the list of items are loaded with infinite loading and some filters, all the state and cubit items are similar, only the model of their list item is different. I wanted to see if there is a solution like generics

i uploaded these 2 cubits here:
https://ufile.io/f/39kk4

**Comment by felangel** [comment]
Hi @PouryaNoufallah96 👋 
Thanks for opening an issue!

Can you please provide a link to a GitHub repo or Gist instead? Thanks 👍

**Comment by PouryaNoufallah96** [comment]
Sure . Do you have a microsoft account so i can invite you ? My project is on azure

**Comment by felangel** [comment]
> Sure . Do you have a microsoft account so i can invite you ? My project is on azure

Can you create a minimal reproduction sample (as simple as possible to illustrate the problem) and just make a gist?

**Comment by PouryaNoufallah96** [comment]
the project is so big:(
i just send some states and cubits below. i hope you can get what i mean .

this is one of my states:
part of 'customer_remain_invoices_data_cubit.dart';

@immutable
class VisitorCustomerRemainInvoicesDataState extends Equatable {
  final ListDataStatusModel dataStatus;
  final BaseSort baseSort;
  final FromToDateFilter filter;
  final String search;
  final List<VisitorCustomerRemainInvoicesDataModel> items;
  final bool hasReachedMax;

  const VisitorCustomerRemainInvoicesDataState({
    this.dataStatus = const ListDataStatusModel(),
    this.baseSort = const BaseSort(),
    this.filter = const FromToDateFilter(),
    this.search = "",
    this.items = const <VisitorCustomerRemainInvoicesDataModel>[],
    this.hasReachedMax = false,
  });

  VisitorCustomerRemainInvoicesDataState copyWith({
    ListDataStatusModel? dataStatus,
    BaseSort? baseSort,
    FromToDateFilter? filter,
    String? search,
    List<VisitorCustomerRemainInvoicesDataModel>? items,
    bool? hasReachedMax,
  }) {
    return VisitorCustomerRemainInvoicesDataState(
      dataStatus: dataStatus ?? this.dataStatus,
      baseSort: baseSort ?? this.baseSort,
      filter: filter ?? this.filter,
      search: search ?? this.search,
      items: items ?? this.items,
      hasReachedMax: hasReachedMax ?? this.hasReachedMax,
    );
  }

  @override
  bool operator ==(Object o) {
    if (identical(this, o)) return true;

    return o is VisitorCustomerRemainInvoicesDataState &&
        o.dataStatus == dataStatus &&
        o.baseSort == baseSort &&
        o.filter == filter &&
        o.search == search &&
        o.items == items &&
        o.hasReachedMax == hasReachedMax;
  }

  @override
  int get hashCode =>
      dataStatus.hashCode +
      search.hashCode +
      baseSort.hashCode +
      filter.hashCode +
      items.hashCode +
      hasReachedMax.hashCode;

  @override
  String toString() =>
      'VisitorCustomerRemainInvoicesDataState { dataStatus:$dataStatus, search: $search, baseSort: $baseSort, filter: $filter, items: ${items.length}, hasReachedMax: $hasReachedMax }';

  @override
  List<Object> get props => [
        dataStatus,
        search,
        baseSort,
        filter,
        items,
        hasReachedMax,
      ];
}

------------------------------------------------

and this is another state:

part of 'customer_cubit.dart';

@immutable
class VisitorCustomerState extends Equatable {
  final ListDataStatusModel dataStatus;
  final BaseSort baseSort;
  final VisitorCustomerFilterModel filter;
  final String search;
  final List<VisitorCustomer> items;
  final bool hasReachedMax;

  const VisitorCustomerState({
    this.dataStatus = const ListDataStatusModel(),
    this.baseSort = const BaseSort(),
    this.filter = const VisitorCustomerFilterModel(),
    this.search = "",
    this.items = const <VisitorCustomer>[],
    this.hasReachedMax = false,
  });

  VisitorCustomerState copyWith({
    ListDataStatusModel? dataStatus,
    BaseSort? baseSort,
    VisitorCustomerFilterModel? filter,
    String? search,
    List<VisitorCustomer>? items,
    bool? hasReachedMax,
  }) {
    return VisitorCustomerState(
      dataStatus: dataStatus ?? this.dataStatus,
      baseSort: baseSort ?? this.baseSort,
      filter: filter ?? this.filter,
      search: search ?? this.search,
      items: items ?? this.items,
      hasReachedMax: hasReachedMax ?? this.hasReachedMax,
    );
  }

  @override
  bool operator ==(Object o) {
    if (identical(this, o)) return true;

    return o is VisitorCustomerState &&
        o.dataStatus == dataStatus &&
        o.baseSort == baseSort &&
        o.filter == filter &&
        o.search == search &&
        o.items == items &&
        o.hasReachedMax == hasReachedMax;
  }

  @override
  int get hashCode =>
      dataStatus.hashCode +
      search.hashCode +
      baseSort.hashCode +
      filter.hashCode +
      items.hashCode +
      hasReachedMax.hashCode;

  @override
  String toString() =>
      'VisitorCustomerState { dataStatus:$dataStatus, search: $search, baseSort: $baseSort, filter: $filter, items: ${items.length}, hasReachedMax: $hasReachedMax }';

  @override
  List<Object> get props => [
        dataStatus,
        search,
        baseSort,
        filter,
        items,
        hasReachedMax,
      ];
}



----------------------------
every thing is the same only the items data types are different

**Comment by PouryaNoufallah96** [comment]
and this is one of my cubits:
import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:udplus_app/models/list_data_status.dart';
import 'package:udplus_app/repository/repository.dart';
import 'package:meta/meta.dart';
import 'package:udplus_app/shared/filters/from_to_date/from_to_date_filter_model.dart';
import 'package:udplus_app/shared/sort/ordering_sort_model.dart';
import 'package:udplus_app/translations/locale_keys.g.dart';
import 'customer_remain_invoices_data_model.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:udplus_app/utils/extensions/date_extensions.dart';
part 'customer_remain_invoices_data_state.dart';

class VisitorCustomerRemainInvoicesDataCubit
    extends Cubit<VisitorCustomerRemainInvoicesDataState> {
  final UdPlusRepository _repository;
  VisitorCustomerRemainInvoicesDataCubit(this._repository)
      : super(VisitorCustomerRemainInvoicesDataState());
  BaseSort getCurrentSort() => state.baseSort;
  FromToDateFilter getCurrentFilter() =>
      state.filter == const FromToDateFilter()
          ? FromToDateFilter(
              fromDate: DateTime.now().getDaysAddedFromString(-365),
              toDate: DateTime.now().dateToString)
          : state.filter;
  String getCurrentSearch() => state.search;
  void setSorts(BaseSort sort) {
    emit(state.copyWith(baseSort: sort));
  }

  void setFilters(FromToDateFilter filter) {
    emit(state.copyWith(filter: filter));
  }

  void setSearch(String search) {
    emit(state.copyWith(search: search));
  }

  void emitError({required String error}) {
    emit(state.copyWith(
      dataStatus:
          ListDataStatusModel(status: ListDataStatus.failure, message: error),
    ));
  }

  Future<void> getItems(int customerId, bool forceRefresh) async {
    var currentSort = getCurrentSort();
    var currentModel = getCurrentFilter();
    var currentSearch = getCurrentSearch();
    if (forceRefresh)
      emit(state.copyWith(
          items: [],
          hasReachedMax: false,
          dataStatus: ListDataStatusModel(status: ListDataStatus.initial)));
    if (state.hasReachedMax) return;
    try {
      await _firstLoad(
          customerId, state, currentSearch, currentModel, currentSort);
      await _loadMore(customerId, state);
    } catch (_) {
      emitError(error: LocaleKeys.getCustomerRemainInvoicesErrorMessage.tr());
    }
  }

  Future _firstLoad(
    int customerId,
    VisitorCustomerRemainInvoicesDataState state,
    String currentSearch,
    FromToDateFilter currentFilter,
    BaseSort currentSort,
  ) async {
    if (state.dataStatus.status == ListDataStatus.initial) {
      final result = await _repository.getVisitorCustomerRemainInvoices(
          customerId,
          search: currentSearch,
          skip: 0,
          sort: currentSort,
          filter: currentFilter);
      if (result != null &&
          result is List<VisitorCustomerRemainInvoicesDataModel>) {
        emit(state.copyWith(
            dataStatus: ListDataStatusModel(status: ListDataStatus.success),
            search: currentSearch,
            baseSort: currentSort,
            filter: currentFilter,
            items: result,
            hasReachedMax: false));
      } else
        emitError(
            error: result?.toString() ??
                LocaleKeys.getCustomerRemainInvoicesErrorMessage.tr());
    }
  }

  Future _loadMore(
    int customerId,
    VisitorCustomerRemainInvoicesDataState state,
  ) async {
    if (state.dataStatus.status != ListDataStatus.success) return;
    var currentCustomers = state.items;
    var skip = currentCustomers.length;
    final result = await _repository.getVisitorCustomerRemainInvoices(
        customerId,
        search: state.search,
        skip: skip,
        sort: state.baseSort,
        filter: state.filter);
    if (result != null &&
        result is List<VisitorCustomerRemainInvoicesDataModel>) {
      {
        if (result.isEmpty)
          emit(state.copyWith(hasReachedMax: true));
        else
          emit(state.copyWith(
              dataStatus: ListDataStatusModel(status: ListDataStatus.success),
              baseSort: state.baseSort,
              filter: state.filter,
              items: List.of(state.items)..addAll(result),
              hasReachedMax: false));
      }
    } else
      emitError(
          error: result?.toString() ??
              LocaleKeys.getCustomerRemainInvoicesErrorMessage.tr());
  }
}


------------------------------------------

and this is another one: 

import 'dart:async';
import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';
import 'package:udplus_app/models/list_data_status.dart';
import 'package:udplus_app/repository/repository.dart';
import 'package:udplus_app/shared/sort/ordering_sort_model.dart';
import 'package:udplus_app/translations/locale_keys.g.dart';
import 'package:udplus_app/utils/geo_location.dart';
import 'index.dart';
import 'package:easy_localization/easy_localization.dart';
part 'customer_state.dart';

class VisitorCustomerCubit extends Cubit<VisitorCustomerState> {
  final UdPlusRepository _repository;
  VisitorCustomerCubit(this._repository) : super(VisitorCustomerState());

  BaseSort getCurrentSort() => state.baseSort;
  VisitorCustomerFilterModel getCurrentFilter() => state.filter;
  String getCurrentSearch() => state.search;
  Future<VisitorCustomerFilterModel> initPosition(
      VisitorCustomerFilterModel currentFilter) async {
    var position = await GLocation().determinePosition();
    return position == null
        ? currentFilter
        : currentFilter.copyWith(x: position.latitude, y: position.longitude);
  }

  void setSorts(BaseSort? sort) {
    emit(state.copyWith(baseSort: sort));
  }

  void setFilters(VisitorCustomerFilterModel filter) {
    emit(state.copyWith(filter: filter));
  }

  void setSearch(String search) {
    emit(state.copyWith(search: search));
  }

  void emitError({required String error}) {
    emit(state.copyWith(
      dataStatus:
          ListDataStatusModel(status: ListDataStatus.failure, message: error),
    ));
  }

  Future<void> getItems(bool forceRefresh) async {
    var currentSort = getCurrentSort();
    var currentModel = getCurrentFilter();
    var currentSearch = getCurrentSearch();
    if (forceRefresh)
      emit(state.copyWith(
          items: [],
          hasReachedMax: false,
          dataStatus: ListDataStatusModel(status: ListDataStatus.initial)));
    if (state.hasReachedMax) return;
    try {
      await _firstLoad(state, currentSearch, currentModel, currentSort);
      await _loadMore(state);
    } catch (_) {
      emitError(error: LocaleKeys.getCustomersErrorMessage.tr());
    }
  }

  Future _firstLoad(
    VisitorCustomerState state,
    String currentSearch,
    VisitorCustomerFilterModel currentFilter,
    BaseSort currentSort,
  ) async {
    if (state.dataStatus.status == ListDataStatus.initial) {
      currentFilter = await initPosition(currentFilter);
      final result = await _repository.getVisitorCustomers(
          search: currentSearch,
          skip: 0,
          sort: currentSort,
          filter: currentFilter);
      if (result != null && result is List<VisitorCustomer>) {
        emit(state.copyWith(
            dataStatus: ListDataStatusModel(status: ListDataStatus.success),
            search: currentSearch,
            baseSort: currentSort,
            filter: currentFilter,
            items: result,
            hasReachedMax: false));
      } else
        emitError(
            error:
                result?.toString() ?? LocaleKeys.getCustomersErrorMessage.tr());
    }
  }

  Future _loadMore(
    VisitorCustomerState state,
  ) async {
    if (state.dataStatus.status != ListDataStatus.success) return;
    var currentCustomers = state.items;
    var skip = currentCustomers.length;
    final result = await _repository.getVisitorCustomers(
        search: state.search,
        skip: skip,
        sort: state.baseSort,
        filter: state.filter);
    if (result != null && result is List<VisitorCustomer>) {
      {
        if (result.isEmpty)
          emit(state.copyWith(hasReachedMax: true));
        else
          emit(state.copyWith(
              dataStatus: ListDataStatusModel(status: ListDataStatus.success),
              baseSort: state.baseSort,
              filter: state.filter,
              items: List.of(state.items)..addAll(result),
              hasReachedMax: false));
      }
    } else
      emitError(
          error:
              result?.toString() ?? LocaleKeys.getCustomersErrorMessage.tr());
  }
}

------------------------------------

and same here every thing are just the same but some data types and ect are different. 
i think this is wrong and i dont know what to do. 
i was thinking about creating a generic cubit for my infinite lists like these 2 but i dont know how to do it.
i wish you could help me<3 many thanks

**Comment by PouryaNoufallah96** [comment]
i added my project here: 
https://github.com/PouryaNoufallah96/udplus_test/tree/master/udplus_app

please look at these directories (cubit and state)
udplus_test/udplus_app/lib/visitor/customer/
udplus_test/udplus_app/lib/visitor/customer/remain_invoices_data/

**Comment by PouryaNoufallah96** [comment]
> > Sure . Do you have a microsoft account so i can invite you ? My project is on azure
> 
> Can you create a minimal reproduction sample (as simple as possible to illustrate the problem) and just make a gist?

any solution?:(

**Comment by felangel** [comment]
Hi @PouryaNoufallah96 👋 
If you want to share code you can just create a common base class for states where it makes sense (or use a mixin):

```dart
class DataState extends Equatable {
  final ListDataStatusModel dataStatus;
  final BaseSort baseSort;
  final bool hasReachedMax;

  ...
}
```

Then you can have the two cubit states extend the base state:

```dart
class VisitorCustomerRemainInvoicesDataState extends DataState {
 ...
}
```

```dart
class VisitorCustomerState extends DataState {
 ...
}
```

This isn't really specific to bloc -- in general if you feel it makes sense to create some sort of abstraction/generalization because you're repeating yourself you can use inheritance or mixins to reduce duplication. Hope that helps 👍
