### ISSUE TITLE
How to spilit logic code for v7.2.0-8.0.0

### ISSUE THREAD

**Issue by gamestap99** [felangel/bloc#2782]
When using v7.2.0 I usually do this for split logic code for small. I have a question is How can I do it in v8.0.0. This is code v7.2.0:
` Stream<SubjectState> mapEventToState(SubjectEvent event) async* {
    final currentState = state;
    final currentEvent = event;

    if (currentEvent is SubjectEventDoGetList && !_hasReachedMax(currentState)) {
      yield* _eventGetData(currentEvent, currentState);
    }

  }`

`Stream<SubjectState> _eventGetData(SubjectEventDoGetList event, SubjectState state) async* {
	//any logic
  }`

**Comment by alvinvin00** [comment]
what's the inside of method _hasReachedMax?

this is my attempt to refactor your code :
```dart
class ListBloc extends Bloc<ListEvent, ListState> {
  ListBloc() : super(ListInitial()) {
    on<ListFetched>(_onListFetched);
  }

  FutureOr<void> _onListFetched(event, emit) {
    if (_hasReachedMax) {
      //Since you don't want to execute a handler when a list has reached maximum
      //We return so no further code is executed
      return null;
    }
    //Handle the event
  }
}
```

**Comment by gamestap99** [comment]
> what's the inside of method _hasReachedMax?
> 
> this is my attempt to refactor your code :
> 
> ```dart
> class ListBloc extends Bloc<ListEvent, ListState> {
>   ListBloc() : super(ListInitial()) {
>     on<ListFetched>(_onListFetched);
>   }
> 
>   FutureOr<void> _onListFetched(event, emit) {
>     if (_hasReachedMax) {
>       //Since you don't want to execute a handler when a list has reached maximum
>       //We return so no further code is executed
>       return null;
>     }
>     //Handle the event
>   }
> }
> ```

Thank for reply. _hasReachedMax is the method to check list are can be fetch continue.

**Comment by alvinvin00** [comment]
> > what's the inside of method _hasReachedMax?
> > this is my attempt to refactor your code :
> > ```dart
> > class ListBloc extends Bloc<ListEvent, ListState> {
> >   ListBloc() : super(ListInitial()) {
> >     on<ListFetched>(_onListFetched);
> >   }
> > 
> >   FutureOr<void> _onListFetched(event, emit) {
> >     if (_hasReachedMax) {
> >       //Since you don't want to execute a handler when a list has reached maximum
> >       //We return so no further code is executed
> >       return null;
> >     }
> >     //Handle the event
> >   }
> > }
> > ```
> 
> Thank for reply. _hasReachedMax is the method to check list are can be fetch continue.

I would make a extension method on your State and use the getter instead of functions so it will be more expressive and your brain will thank you :)

```dart
extension ListStateX on ListState{
    bool get hasReachedMax => list.length == maxLength;
}
```

```dart
FutureOr<void> _onListFetched(event, emit){
   if(state.hasReachedMax){
       return null;
   }
}
```

**Comment by gamestap99** [comment]
> > > what's the inside of method _hasReachedMax?
> > > this is my attempt to refactor your code :
> > > ```dart
> > > class ListBloc extends Bloc<ListEvent, ListState> {
> > >   ListBloc() : super(ListInitial()) {
> > >     on<ListFetched>(_onListFetched);
> > >   }
> > > 
> > >   FutureOr<void> _onListFetched(event, emit) {
> > >     if (_hasReachedMax) {
> > >       //Since you don't want to execute a handler when a list has reached maximum
> > >       //We return so no further code is executed
> > >       return null;
> > >     }
> > >     //Handle the event
> > >   }
> > > }
> > > ```
> > 
> > 
> > Thank for reply. _hasReachedMax is the method to check list are can be fetch continue.
> 
> I would make a extension method on your State and use the getter instead of functions so it will be more expressive and your brain will thank you :)
> 
> ```dart
> extension ListStateX on ListState{
>     bool get hasReachedMax => list.length == maxLength;
> }
> ```
> 
> ```dart
> FutureOr<void> _onListFetched(event, emit){
>    if(state.hasReachedMax){
>        return null;
>    }
> }
> ```

Last question. Can you help me?. This is example logic code:
```dart
Stream<SubjectState> _eventGetData(SubjectGetList event, SubjectState state) async* {
	yield SubjectLoading();
final result = await callApi();
yield SubjectLoaded(//somedata);
  }
```
So I change it to V8.0.0 

```dart
FutureOr<void> _onListFetched(event, emit){
   if(state.hasReachedMax){
       return null;
   }
   
   emit(SubjectLoading());
   
   final result = await callApi();
   
   emit(SubjectLoaded(result));
}
```

```dart
class SubjectBloc extends Bloc<SubjectEvent, SubjectBloc > {
  SubjectBloc () : super(SubjectIdle()) {
    on<SubjectFetch>(_onListFetched);
  }
//....
}
```
After, i have a proplem is: Class 'SubjectFetch' has no instance method 'call'.

**Comment by alvinvin00** [comment]
did you create SubjectFetch as an abstract class?

**Comment by gamestap99** [comment]
> did you create SubjectFetch as an abstract class?

yep

**Comment by alvinvin00** [comment]
that's the problem, your Event class must extend the Base Event class

```dart
abstract class SubjectEvent extends Equatable {}

class SubjectFetch extends SubjectEvent {}
```

**Comment by alvinvin00** [comment]
it depends on use case, you can go subclassing or lump it all in one concrete state class, usually people gone to the latter because they want to display old data when there's an error

**Comment by gamestap99** [comment]
> it depends on use case, you can go subclassing or lump it all in one concrete state class, usually people gone to the latter because they want to display old data when there's an error

Thank for helping!. I CHANGE MY CODE LIKE HE FROM EXAMPLE INFINITE LIST

**Comment by alvinvin00** [comment]
What's with the capital letters?

**Comment by gamestap99** [comment]
> What's with the capital letters?



> What's with the capital letters?

sorry i replied late. After, Reading some his example projects I removed my state is asbtractClass and edited to a class. Finish, I achieved  what I want from the article, and thanks to your help and I understand many things. Thank you!

**Comment by alvinvin00** [comment]
No problem. @felangel, can you close this issue?
