### ISSUE TITLE
Migration to 7.2 docs: How to retain sequential event processing for all events of a Bloc

### ISSUE THREAD

**Issue by rorystephenson** [felangel/bloc#2790]
**Description**

I'm looking to migrate to the new `on<Event>((event, emit) { /* ... /* }` event processing and I'm a bit confused on how I should set it up so that one event is processed at a time before moving on to the next event (regardless of the event type).

E.g. if I have a counter bloc with an add and subtract event triggered by buttons where each event waits three seconds before adding or subtracting and I hit *add*, *add*, *subtract*. I'd expect to see:

- 3 second delay and then 1 emitted
- 3 second delay and then 2 emitted
- 3 second delay and then 1 emitted

Instead I seem to get:

- 3 second delay and then 1 emitted
- very shortly after (the delay before I hit the subtract button) 0 emitted
- 3 seconds after: 1 emitted.

I've tried setting both of the `on()` transformers to `sequential()` (from `bloc_concurrency`) and even sharing the same instance of `sequential()` (as you can see below) and I can't seem to get the desired behaviour where each event is fully processed before moving on to the next one regardless of the type.

Here is my current attempt:

```dart
import 'package:bloc_concurrency/bloc_concurrency.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class TestBloc extends Bloc<TestBlocEvent, TestBlocState> {
  TestBloc() : super(TestBlocState(0)) {
    final sequentialTransformer = sequential<TestBlocEvent>();
    on<TestBlocAddEvent>(
      (event, emit) async {
        await Future.delayed(Duration(seconds: 3));
        emit(TestBlocState(state.count + 1));
      },
      transformer: sequentialTransformer,
    );

    on<TestBlocSubtractEvent>(
      (event, emit) async {
        await Future.delayed(Duration(seconds: 3));
        emit(TestBlocState(state.count - 1));
      },
      transformer: sequentialTransformer,
    );
  }
}

abstract class TestBlocEvent {}

class TestBlocAddEvent extends TestBlocEvent {}

class TestBlocSubtractEvent extends TestBlocEvent {}

class TestBlocState {
  final int count;

  TestBlocState(this.count);
}
```

Am I missing something obvious?

**Comment by felangel** [comment]
Hi @rorystephenson 👋
Thanks for opening an issue!

The easiest way to apply a sequential event transformer to all blocs is to override the default transformer:

```dart
import 'package:bloc/bloc.dart';
import 'package:bloc_concurrency/bloc_concurrency.dart';

void main() {
  Bloc.transformer = sequential();
  ...
}
```

Hope that helps 👍

**Comment by rorystephenson** [comment]
Hi @felangel thanks for the very fast reply (and, since I forgot to mention it in my original message, the fantastic packages).

I've given it a try and, as you mentioned, by only registering a single event handler and using a `sequential()` transformer I can achieve the same behaviour as `mapEventToState` in previous versions. It may be worth adding a section to the migration docs for those that just want to keep the existing bloc behaviour but want to use the new event handler approach to clarify that they should only register a single event handler.

I'll leave this open in case you want to make documentation changes but my question is resolved :).

**Comment by riverscuomo** [comment]
Hi @felangel , I'm trying to figure out migration while retaining sequential events. I put `Bloc.transformer = sequential();` in my main() but I can't figure out the second part you mentioned "if you want it to apply to all events you need to register a single event handler rather than multiple". 

I have about 30 events in a block that can be added singly, doubly, or triply and in different orders. Do you mean I should wrap them all in one meta event handler? Or that I need to create a new event for every combination of events? Or is it something else?

This is the example I'm confused about:
`on<TestBlocEvent>((event, emit) {…});`

flutter_bloc: 7.0.1  was working for me and now I'm trying 7.3.2. Thank you.

**Comment by riverscuomo** [comment]
@felangel  I think I'm almost there. I do have a new error, though, that maybe you could help me with. 

All is well if I handle the event in the containing event handler:

```dart
on<PlayerScreenEvent>(
(event, emit) async {
if (event is PlayerLoadUser) {
  final user = await _userRepository.getUserWithId(
    userId: _authBloc.state.user!.uid);
  emit(state.copyWith(status: PlayerScreenStatus.loaded, user: user));
}
```

But if I separate the event handling into a function like this:
```dart
on<PlayerScreenEvent>(
  (event, emit) async {
  if (event is PlayerLoadUser) {
  _loadUser(event, emit);
}

void _loadUser(PlayerLoadUser event, Emitter<PlayerScreenState> emit) async {
    final user = await _userRepository.getUserWithId(
      userId: _authBloc.state.user!.uid);
    emit(state.copyWith(status: PlayerScreenStatus.loaded, user: user));
}
```

I get this error on the final line where I call emit:
`
  emit was called after an event handler completed normally.
  This is usually due to an unawaited future in an event handler.
  Please make sure to await all asynchronous operations with event handlers
  and use emit.isDone after asynchronous operations before calling emit() to
  ensure the event handler has not completed.
`

**Comment by felangel** [comment]
> @felangel I think I'm almost there. I do have a new error, though, that maybe you could help me with.
> 
> All is well if I handle the event in the containing event handler:
> 
> ```dart
> on<PlayerScreenEvent>(
> (event, emit) async {
> if (event is PlayerLoadUser) {
>   final user = await _userRepository.getUserWithId(
>     userId: _authBloc.state.user!.uid);
>   emit(state.copyWith(status: PlayerScreenStatus.loaded, user: user));
> }
> ```
> 
> But if I separate the event handling into a function like this:
> 
> ```dart
> on<PlayerScreenEvent>(
>   (event, emit) async {
>   if (event is PlayerLoadUser) {
>   _loadUser(event, emit);
> }
> 
> void _loadUser(PlayerLoadUser event, Emitter<PlayerScreenState> emit) async {
>     final user = await _userRepository.getUserWithId(
>       userId: _authBloc.state.user!.uid);
>     emit(state.copyWith(status: PlayerScreenStatus.loaded, user: user));
> }
> ```
> 
> I get this error on the final line where I call emit: `emit was called after an event handler completed normally. This is usually due to an unawaited future in an event handler. Please make sure to await all asynchronous operations with event handlers and use emit.isDone after asynchronous operations before calling emit() to ensure the event handler has not completed.`

Hey 👋 

That's because you need to change the return type of `_loadUser` to `Future<void>` and await the Future in the event handler:

```dart
on<PlayerScreenEvent>(
  (event, emit) async {
  if (event is PlayerLoadUser) {
  await _loadUser(event, emit);
}

Future<void> _loadUser(PlayerLoadUser event, Emitter<PlayerScreenState> emit) async {
    final user = await _userRepository.getUserWithId(
      userId: _authBloc.state.user!.uid);
    emit(state.copyWith(status: PlayerScreenStatus.loaded, user: user));
}
```

Let me know if that helps 👍

**Comment by riverscuomo** [comment]
@felangel that did the trick. Thank you.

**Comment by definitelyme** [comment]
> Hi @felangel , Wouldn't it be good having a way to override the default transformer for a **single** Bloc? Instead of every Bloc in the project...

Yes this would come in handy
