### ISSUE TITLE
question: Sharing variables acquired from state between Builder and Listener in consumer

### ISSUE THREAD

**Issue by mfizz1** [felangel/bloc#2791]
Hi, from the docs I read that it is better to use listener to to page navigation etc everything that is not UI related. I have a stream stream emitted in a state that I am using to do some checks / calculation after which something is built and based upon the result may or may not do navigation.

I am having to do calculations twice, once in listener and again in builder which may not be good for performance, I am not sure.. but isn't there a way to share the variables that I create between the two? or should I just switch to a blocuilder and do everything in there?

**Comment by narcodico** [comment]
Hi @mfizz1 👋

It sounds like you're doing some business logic in there which I would advise against.
Just move that logic inside bloc or maybe as an extension method on your state class and keep the builder/listener checks to 
 minimal. e.g.: `if state.user.isNew`, `if state is DataLoaded`.

**Comment by nathanielxd** [comment]
Could you provide an example? You should only do logic inside a bloc or cubit. If you might need navigation based on calculations, then set up a variable inside your bloc state `bool needsNavigation` and emit it true or false with your other data.

**Comment by mfizz1** [comment]
You're absolutely right.. Sometimes when you working on it for too long you get tunnel vision and forget the basics of, logic goes in the bloc.

So with this instance, I use the data returned from the bloc as bloc.data to build a widget. Should I use this to navigate to a different page or utilize listener instead?

**Comment by narcodico** [comment]
Your logic result should be outputted through your state not directly kept on the bloc.
`BlocListener` should be used to initiate navigation.

**Comment by nathanielxd** [comment]
I agree with Rolly. If you are using both BlocListener and BlocBuilder, you could simply use BlocConsumer. Although, if you are using AnimatedSwitcher you could imitate navigation through just a bloc builder. I have written some examples:

```
// With BlocConsumer
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: BlocConsumer<MyBloc, MyState>(
        listener: (context, state) {
          if(state.needsNavigation) {
            // Do Navigation
          }
        },
        builder: (context, state) {
          // Build your widgets here.
        }
      )
    );
  }
```

```
// With BlocBuilder - Different type of navigation
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: BlocBuilder<MyBloc, MyState>(
        builder: (context, state) {
          return AnimatedSwitcher(
            duration: Duration(milliseconds: 300),
            child: [
              Page1(),
              Page2(),
              Page3()
            ][state.navigationIndex],
          );
        }
      )
    );
  }
```

**Comment by mfizz1** [comment]
I was using a blocconsumer.. But now I have the bloc emit a state that I now use. The animatedswitcher is a brilliant idea. Have you got a blog or anything with some more examples I could go through?

**Comment by nathanielxd** [comment]
Haha no but I might make one. Cheers.
