### ISSUE TITLE
use a bloc in another bloc without StreamSubscription

### ISSUE THREAD

**Issue by PouryaNoufallah96** [felangel/bloc#2805]
hello,
I was wondering that is it ok to pass a bloc to another one and then in one of BlocA events i add an event from BlocB:

class BlocA extends Bloc<BlocAEvent, BlocAState> {
  final BLocB _blocB;
  BlocA(this._blocB){
  on< LoadEvent >(_onLoad);
}
  void _onLoad(
      LoadEvent event, Emitter<BlocAState> emit) async {
    .
    .
    .
    _blocB.add(SomeEvent())
  }
}

does it decrease my performance or something?

**Comment by narcodico** [comment]
Hi @PouryaNoufallah96 👋

You can do that but a better solution would be to keep your blocs decoupled by using a `BlocListener` with your `BlocA` and based on the incoming state choose when to add the event to your `BlocB`.

**Comment by PouryaNoufallah96** [comment]
thanks for you response 
yes but my BlocB is on another route and when i'm trying to use this code in bloclistener (context.read<BlocA>().add(event)) i got an error :Could not find the correct Provider<BlocA> above this BlocListener
what i'm doing right know is that when i navigate to first page again i pass the state of BlocB to navigator.pop(state) and after that i add the blocA event. but i don't know it's ok or not:
 var data = await context.showBottomModal(
      () => MyActionSheet() );
    if (data != null) {
      context.read<BlocA>.add(event(data));
}

**Comment by narcodico** [comment]
That's a good solution for your current requirements.

**Comment by PouryaNoufallah96** [comment]
ok thank you for you quick response again <3
