### ISSUE TITLE
question: Stringing states in new API

### ISSUE THREAD

**Issue by mfizz1** [felangel/bloc#2806]
I have managed to change the to the new on<event> api. However I was wondering how to string states together..

For example in the mapeventtostate method you could do something like: 

```
async* {
     if (event is FetchTimetable) {
     yield GettingTime();
       yield* _fetchEventTime();
       yield TimesLoaded()
    }
```
The only way I can emulate this right now is to emit states in the void function. Perhaps that is the way but I feel you lose some code clarity there where you could see the chain of states for a particular event without having to worry about the actual logic of what its doing?

**Comment by brianrobles204** [comment]
The `emit` object passed into the `on<Event>()` handler actually has extra methods for emitting streams. In your example, you can do

```dart
on<FetchTimetable>((event, emit) async {
  emit(GettingTime());
  await emit.forEach(_fetchEventTime(), onData: (state) => state);
  emit(TimesLoaded());
});
```

Just be sure to await the forEach call

**Comment by mfizz1** [comment]
Brilliant..! Thank you
