### ISSUE TITLE
fix: transformEvents does not get called

### ISSUE THREAD

**Issue by serendipity1004** [felangel/bloc#2813]
```dart
  @override
  Stream<Transition<CompanyEvent, CompanyState>> transformEvents(
      Stream<CompanyEvent> events,
      TransitionFunction<CompanyEvent, CompanyState> transitionFn) {
   print('TRANSFORM'); <----- this does not print
    if (events is CompanyRequested &&
        (events as CompanyRequested).type == 'ga') {
      return super.transformEvents(
        events.debounceTime(
          Duration(
            milliseconds: 200,
          ),
        ),
        transitionFn,
      );
    }

    return super.transformEvents(events, transitionFn);
  }
```

I am pretty sure transformEvents had been working correctly until a few weeks ago but suddenly I cannot get it to be called.

it does not print 'TRNASFORM' nor does it correctly debounce the stream.

Is it a bug? Anyone else experiencing same issue?

I am using ^7.2.0 in my pubspec so I think 7.3.0 version as of now.

**Comment by felangel** [comment]
Hi @serendipity1004 👋
Thanks for opening an issue!

Can you please share a minimal reproduction sample? Thanks!

**Comment by serendipity1004** [comment]
I think it was some kind of a bug in 7.1.0. I migrated to 7.2.0 and changed to on<E> mechanism and it's working fine now.
