### ISSUE TITLE
feat: [HydratedBloc] Add possibility to skip storing some states

### ISSUE THREAD

**Issue by erickzanardo** [felangel/bloc#2820]
**Description**

It would be quite useful if we could somehow inform HydratedBloc if a state should be serialised or not.

An example of use for this is: Imagine a bloc that loads some info from an endpoint. If for some reason the API returns an error, we may not want to save the resulting error state.

**Desired Solution**

One idea that I had to implement this, would be to simply add a method like this `bool shouldStore(prevState, currentState)` on the bloc, with a default implementation returning always true so we don't get a breaking change. And then users would be able to override this and implement their logic.

**Alternatives Considered**

I couldn't think on any ways of doing this without the proposed method.

I would love to work on this if this is something that makes sense for the package.

**Comment by marcossevilla** [comment]
hi @erickzanardo! I like your proposal, it's very similar to what is done with `replay_bloc` with the `[shouldReplay](https://github.com/felangel/bloc/blob/b05d312acdb4ca04693e638cce751ed4e62e1cd7/packages/replay_bloc/lib/src/replay_bloc.dart#L145)` method.

If that API looks like what you wanted to do, we can have a `shouldHydrate`/`shouldPersist` method to return a bool if we want to persist the state that's sent. Also, pinging @felangel to know his opinion about this addition. 👍

**Comment by erickzanardo** [comment]
> hi @erickzanardo! I like your proposal, it's very similar to what is done with `replay_bloc` with the [`shouldReplay`](https://github.com/felangel/bloc/blob/b05d312acdb4ca04693e638cce751ed4e62e1cd7/packages/replay_bloc/lib/src/replay_bloc.dart#L145) method.
> 
> If that API looks like what you wanted to do, we can have a `shouldHydrate`/`shouldPersist` method to return a bool if we want to persist the state that's sent. Also, pinging @felangel to know his opinion about this addition. 👍

The `shouldReplay` method seems pretty much like what I though for the HydratedBloc, a `shouldHydrate`/`shouldPersist` would be exactly what I need :D

**Comment by felangel** [comment]
Hi @erickzanardo 👋 
Thanks for opening an issue!

You should already be able to achieve this with the current API. `toJson` can return `null` which means that the provided state will not be cached. Similarly, `fromJson` can return `null` which means that the bloc will not restore from cache and will instead use the default initial state.

Let me know if that helps 👍

**Comment by erickzanardo** [comment]
Awesome, yeah that would indeed work! Seems that I missed this in the docs 😅

Thanks for pointing me the right direction.

We can close this.
