### ISSUE TITLE
fix: The listenner function in Bloc Consumer take a short time to get a new state

### ISSUE THREAD

**Issue by nhoangthinh** [felangel/bloc#2822]
**Description**
The listenner function of BlocConsummer take a short time to got a new state although I just emit a state of enum type? Why this happens?

**flutter_bloc_version**
flutter_bloc: ^7.0.0

**Steps To Reproduce**

1. 'dashboard_v2_cubit.dart': the logic func to emit new state called getDataAt()
2. 'dashboard_v2_state.dart': to see state of dashboard_v2_cubit
3.  'dashboard_date_picker.dart' where I use BlocConsummer
4.  When the getDataAt() function invoked. I debugged at line 104 in 'dashboard_v2_cubit.dart'. The state emit immediately, but at line 17 in 'dashboard_v2_cubit' where I debugged at the same time take a short time (about 200ms) to get the new state. I think the reason maybe belong to BlocConsummer. Please take your time to respond this issue. Tks.

**Expected Behavior**
The listenner will get state immediately when i emit the enum state.

**Screenshots**
![image](https://user-images.githubusercontent.com/87893232/135757413-7089b1cb-4849-4f6e-b910-e67c78033f8d.png)
![image](https://user-images.githubusercontent.com/35698467/135757481-6a6b233a-1ebc-4e10-b922-3331ff24cca4.png)
![image](https://user-images.githubusercontent.com/35698467/135757497-a855372f-68c9-4070-8e57-005584b9c1ed.png)
Full code here: https://github.com/nhoangthinh/dasboard

**Video**

https://user-images.githubusercontent.com/35698467/135758352-e80d2e92-2507-40ee-a39d-4a4cf4aae2ab.mp4

**Comment by TMAnhoangthinh** [comment]
> hi @nhoangthinh! Just to make sure I understand, you do:
> 
> ```dart
> emit(state.copyWith(queryProgress: QueryProgress.inProgress));
> ```
> 
> And that does emit the state well. But takes a lot of time when emitting this?
> 
> ```dart
> emit(state.copyWith(query: query, queryProgress: QueryProgress.done));
> ```
> 
> In that case, I see you await multiple futures in that call and that can be the problem because the bloc waits for those to complete and then emits the `QueryProgress.done` state.
> 
> Also, I see you have a lot of cubits as dependencies of your `DashboardV2Cubit`, to avoid that I suggest using the repository pattern with [`RepositoryProvider`](https://bloclibrary.dev/#/architecture?id=repository). If you're using them as dependencies because you need to know the state changes between them, it's better if you listen to their streams as explained in the [docs](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication).

At line 104 where i called emit(state.copyWith(query: query, queryProgress: QueryProgress.done)).It's always occurs before multiple function call on  my cubits.

**Comment by marcossevilla** [comment]
> > hi @nhoangthinh! Just to make sure I understand, you do:
> > ```dart
> > emit(state.copyWith(queryProgress: QueryProgress.inProgress));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And that does emit the state well. But takes a lot of time when emitting this?
> > ```dart
> > emit(state.copyWith(query: query, queryProgress: QueryProgress.done));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In that case, I see you await multiple futures in that call and that can be the problem because the bloc waits for those to complete and then emits the `QueryProgress.done` state.
> > Also, I see you have a lot of cubits as dependencies of your `DashboardV2Cubit`, to avoid that I suggest using the repository pattern with [`RepositoryProvider`](https://bloclibrary.dev/#/architecture?id=repository). If you're using them as dependencies because you need to know the state changes between them, it's better if you listen to their streams as explained in the [docs](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication).
> 
> At line 104 where i called emit(state.copyWith(query: query, queryProgress: QueryProgress.done)).It's always occurs before multiple function call on my cubits.

Yes, that's because you await multiple cubit methods at a time. If you call any API you're awaiting that async response and that's probably going to take a while because there are multiple methods. You also have:
```dart
await Future.delayed(Duration(milliseconds: 210));
```
Before your state is emitted, so it takes a bit longer. As I said before, I suggest you decouple a bit your domain and business logic, but more importantly, if you await multiple async methods it's always going to take a lot of time to get your new state emitted.

**Comment by TMAnhoangthinh** [comment]
> > > hi @nhoangthinh! Just to make sure I understand, you do:
> > > ```dart
> > > emit(state.copyWith(queryProgress: QueryProgress.inProgress));
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And that does emit the state well. But takes a lot of time when emitting this?
> > > ```dart
> > > emit(state.copyWith(query: query, queryProgress: QueryProgress.done));
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > In that case, I see you await multiple futures in that call and that can be the problem because the bloc waits for those to complete and then emits the `QueryProgress.done` state.
> > > Also, I see you have a lot of cubits as dependencies of your `DashboardV2Cubit`, to avoid that I suggest using the repository pattern with [`RepositoryProvider`](https://bloclibrary.dev/#/architecture?id=repository). If you're using them as dependencies because you need to know the state changes between them, it's better if you listen to their streams as explained in the [docs](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication).
> > 
> > 
> > At line 104 where i called emit(state.copyWith(query: query, queryProgress: QueryProgress.done)).It's always occurs before multiple function call on my cubits.
> 
> Yes, that's because you await multiple cubit methods at a time. If you call any API you're awaiting that async response and that's probably going to take a while because there are multiple methods. You also have:
> 
> ```dart
> await Future.delayed(Duration(milliseconds: 210));
> ```
> 
> Before your state is emitted, so it takes a bit longer. As I said before, I suggest you decouple a bit your domain and business logic, but more importantly, if you await multiple async methods it's always going to take a lot of time to get your new state emitted.

And that does emit the state well. But takes a lot of time when emitting this?

No. I means it takes a lot of time to emit(state.copyWith(query: query, queryProgress: QueryProgress.inProgress));.Please check the video. Tks.

**Comment by TMAnhoangthinh** [comment]
> @TMAnhoangthinh it seems like you're calling the `getDataAt` method multiple times, it might be for every cubit you have as a dependency. But you're running it on debug, if you disable the breakpoints still takes a lot of time to emit the `QueryProgress.inProgress`?

No, in this case when i emit state QueryProgress.inProgress. The listenner function on BlocConsumer should be get the state == QueryProgress.inProgress immediately. But such as above video, it takes about 200ms to get new state == QueryProgress.inProgress

**Comment by nhoangthinh** [comment]
Ok,let me try

**Comment by felangel** [comment]
@nhoangthinh were you able to figure out the issue?
