### ISSUE TITLE
problem with unawaited

### ISSUE THREAD

**Issue by PouryaNoufallah96** [felangel/bloc#2824]
hello, 
i migrate to 7.3.0 and when i try to use this code below i get an error. i tried to use it like you complex list sample:

  
  
  class VisitorProductBloc
    extends Bloc<VisitorProductEvent, VisitorProductState> {
  VisitorProductBloc()
      : super(const VisitorProductState()) {
    on<VisitorProductFavoriteChangedEvent>(_onFavoriteChanged);
  }
  
  
  
  void _onFavoriteChanged(VisitorProductFavoriteChangedEvent event,
      Emitter<VisitorProductState> emit) async {
    final favoriteInProgress = state.items.map((item) {
      return item.id == event.id ? item.copyWith(isLoading: true) : item;
    }).toList();
    emit(state.copyWith(items: favoriteInProgress));

    unawaited(Future.delated(Duration(seconds:3)).then((_) {
      final favoriteDone = state.items.map((item) {
        return item.id == event.id
            ? item.copyWith(isLoading: false, favorite: event.favorite)
            : item;
      }).toList();
      emit(state.copyWith(items: favoriteDone));
    }));
  }
}

Error:
emit was called after an event handler completed normally.
This is usually due to an unawaited future in an event handler.
Please make sure to await all asynchronous operations with event handlers
and use emit.isDone after asynchronous operations before calling emit() to
ensure the event handler has not completed.

  **BAD**
  on<Event>((event, emit) {
    future.whenComplete(() => emit(...));
  });

  **GOOD**
  on<Event>((event, emit) async {
    await future.whenComplete(() => emit(...));
  });
)

**Comment by felangel** [comment]
Hi @PouryaNoufallah96 👋
Thanks for opening an issue!

As the error mentions, you are calling emit after the event handler has completed. You should remove the unawaited and await the future instead as shown in the suggestions in the error.

**Comment by PouryaNoufallah96** [comment]
thanks . yea i did that and it's ok now but should i only use unawaited for situation like this in cubit ?

**Comment by felangel** [comment]
> thanks . yea i did that and it's ok now but should i only use unawaited for situation like this in cubit ?

Yeah in bloc you can only emit in response to an event so you should always await futures in your event handler. In cubit you can emit from anywhere so it’s not an issue to use unawaited.

Closing for now but feel free to comment if you have any follow up questions and I’m happy to continue the conversation 👍

**Comment by davidAg9** [comment]
I have this problem with firebase phone auth who's future completes immediately even tho its closure might be still running
 any ideas on how I should deal with it
