### ISSUE TITLE
What is the best approach ?  Pass the Repository into the bloc-constructor or wrap the block in the Repository?perf: 

### ISSUE THREAD

**Issue by drogbut** [felangel/bloc#2827]
**Description**

Clearly describe what code needs to be changed and what the performance impact is going to be.

**Comment by felangel** [comment]
Hi @drogbut 👋 
Thanks for opening an issue!

I recommend providing the repository to the widget tree using `RepositoryProvider` and then when creating a bloc that requires a repository you can access the repository via `context.read` and inject the repository into the bloc via constructor like:

```dart
@override
Widget build(BuildContext context) {
  return RepositoryProvider(
    create: (context) => MyRepository(),
    child: MyWidget(),
  );
}
```

Then in `MyWidget` or in any children of `MyWidget` you can inject the repository instance into a bloc like:

```dart
@override
Widget build(BuildContext context) {
  return BlocProvider(
    create: (context) => MyBloc(repository: context.read<MyRepository>()),
    child: MyOtherWidget(),
  );
}
```

Closing for now but feel free to comment with any follow up questions and I'm happy to continue the conversation 👍
