### ISSUE TITLE
Change ThemeData on the fly

### ISSUE THREAD

**Issue by Reidond** [felangel/bloc#283]
Is it possible to change ThemeData of MaterialApp on the fly with bloc? If it is, how?

**Comment by felangel** [comment]
Hi @Reidond 👋 
Thanks for opening an issue! It's most certainly possible and you can check out an example of it [here](https://github.com/felangel/bloc/tree/master/packages/flutter_bloc/example).

Hope that helps! 👍

**Comment by Reidond** [comment]
Thank you! I am soo blind 😃

**Comment by felangel** [comment]
No problem!
