### ISSUE TITLE
fix: counter tutorial pubspec file relative paths

### ISSUE THREAD

**Issue by guysbryant** [felangel/bloc#2833]
**Description**

I'm learning BLoC from the documentation at https://bloclibrary.dev/
I just started the tutorials section and for both the Counter and Timer tutorials I'm having an issue with the pubspec file. I deleted the contents of my pubspec.yaml and pasted the contents from the one in the tutorial. Visual Studio Code is complaining that the relative paths in the the pubspec don't exist. My terminal is complaining that bloc_test doesn't exist. I ran flutter clean and then flutter packages get again just in case but its the same problem.

**Steps To Reproduce**

1. Go to https://bloclibrary.dev/#/fluttercountertutorial
2. Follow tutorial exactly as written

**Expected Behavior**

I expected the contents of the pubspec file to work.

**Screenshots**

Here is a screen shot of the pubspec with its complaints and terminal with its complaints:
<img width="1792" alt="Screen Shot 2021-10-06 at 09 49 35" src="https://user-images.githubusercontent.com/15893869/136215856-1f26b16f-8de1-41a6-8895-baa62cf3bec3.png">

Here is a screenshot of the complaints in the problems tab of Visual Studio Code terminal:
<img width="1792" alt="Screen Shot 2021-10-06 at 09 51 49" src="https://user-images.githubusercontent.com/15893869/136216177-5d6c0c5f-109a-4bcf-8037-e1839dfb90af.png">

**Additional Context**

Flutter and Dart versions incase those are relevant:
❯ flutter --version
Flutter 2.6.0-12.0.pre.222 • channel master • https://github.com/flutter/flutter.git
Framework • revision ed60103645 (4 hours ago) • 2021-10-06 06:53:04 -0400
Engine • revision f967ebb685
Tools • Dart 2.15.0 (build 2.15.0-178.0.dev)
❯ dart --version
Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "macos_x64"

**Comment by felangel** [comment]
Hi @guysbryant 👋 
Thanks for opening an issue!

I will try to address this shortly but in the meantime you should just adjust your pubspec to remove the dependency overrides and use the published versions of each of the packages from pub.dev:

```yaml
dependencies:
  bloc: ^7.2.0
  flutter_bloc: ^7.3.0

dev_dependencies:
  bloc_test: ^8.0.0
```

Hope that helps and sorry for the inconvenience!

**Comment by felangel** [comment]
> Thanks I deleted my pubspec file, copied the contents of a fresh project pubspec and then ran the following two commands in my terminal: `flutter pub add flutter_bloc` `flutter pub add bloc_test` That fixed almost everything. I had to add the following import to test/widget_test.dart: `import 'package:flutter_counter/app.dart'` and then change line 5 from MyApp to CounterApp. Now everything is working.
> 
> Should the tutorial be updated to include those changes to widget_test?

Awesome! The tutorial is pulling from the real, working code at https://github.com/felangel/bloc/tree/master/examples/flutter_counter. It should be correct with the exception of the `pubspec.yaml`.
