### ISSUE TITLE
[bloc_test] feat: Add tags and other parameters from package:test to blocTest

### ISSUE THREAD

**Issue by Giuspepe** [felangel/bloc#2839]
**Description**

Our app has different flavors which cause it to behave a bit differently. Some tests should be only run for some flavors. To achieve this, we pass tags to the call of the `test` function from `package:test`. Then we can use these tags to only run specific tests (e.g. `flutter run test --tags flavor1||flavor2`. See this documentation for more detail: https://pub.dev/packages/test#tagging-tests

However, `blocTest` does not accept the `tags` parameter.

**Desired Solution**

`blocTest` should accept the `tags` parameter as well as all the other parameters of the `test` function from `package:test` and pass them on to the `test` function.

I have opened a pull request to solve this issue: https://github.com/felangel/bloc/pull/2840

**Comment by felangel** [comment]
@Giuspepe thanks for the context and clarification! I updated #2840 to include just the tags and will publish the change as part of bloc_test v8.3.0 shortly 🎉 

Thanks for the contribution! 🚀
