### ISSUE TITLE
BLOC not updating state immediately

### ISSUE THREAD

**Issue by mnnlthmpsn** [felangel/bloc#2851]
**Description**
BLOC doesn't update state immediately

**Steps To Reproduce**

Check out this repo. I was able to reproduce the error

**Expected Behavior**
I expected updated state in my Detail Page Screen. Rather, the initial State still remained
However, the state was updated later in my console when no routing was done

**Screenshot
![Screenshot (73)](https://user-images.githubusercontent.com/28049358/136666951-9374fa8e-2b42-4281-bf32-22d1c6e17ddb.png)

**Comment by alestiago** [comment]
👋 Hi @mnnlthmpsn.

I would like to make sure I've understood your issue correctly. I've created some simplified reproduction sample using the new Bloc API. I'm using `flutter_bloc: ^7.3.0`. Does this match your scenario?

**main.dart**
```dart
import 'package:bloc_issue_2851/test/test_bloc.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => TestBloc(),
      child: MaterialApp(
        title: 'Bloc Issue 2851',
        home: TestPage(),
      ),
    );
  }
}

class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final bloc = BlocProvider.of<TestBloc>(context);

    return Scaffold(
      body: Center(
        child: ElevatedButton(
          child: Text('Toggle State'),
          onPressed: () {
            print('Initialize update');
            bloc.add(ToggleStateEvent());
            print('Initialization done');
          },
        ),
      ),
    );
  }
}

```

**test_bloc.dart**
```dart
import 'package:bloc/bloc.dart';
import 'package:meta/meta.dart';

part 'test_event.dart';
part 'test_state.dart';

class TestBloc extends Bloc<TestEvent, TestState> {
  TestBloc() : super(TestStateA()) {
    on<ToggleStateEvent>((event, emit) {
      print('Updating category');

      if (state is TestStateA) {
        emit(TestStateB());
      } else if (state is TestStateB) {
        emit(TestStateA());
      }
    });
  }
}
```

**test_event.dart**
```dart
part of 'test_bloc.dart';

@immutable
abstract class TestEvent {}

class ToggleStateEvent extends TestEvent {}
```

**test_state.dart**
```dart
part of 'test_bloc.dart';

@immutable
abstract class TestState {}

class TestState extends TestState {}
```

I'm not sure about what you are trying to achieve with the `BlocBuilder`. 

However, I'm assuming you wish to perform some navigation you might want to use a `BlocListener`  . The [documentation](https://bloclibrary.dev/#/flutterbloccoreconcepts?id=bloclistener) suggests to use this widget for "functionality that needs to occur once per state change such as navigation, showing a SnackBar, showing a Dialog, etc...". 

Let me know if this helps :)

**Comment by mnnlthmpsn** [comment]
Awesome. Exactly what i was looking for
Thanks a million
