### ISSUE TITLE
[Question] Authentication flow with pushReplacement in flow

### ISSUE THREAD

**Issue by fvisticot** [felangel/bloc#286]
My app is using a bloc for authentication.
1. Login
2. Screen with List
3. ===> PushReplacement to clear the navigation stack
4. Detail Screen
5. Logout page with Logout button

When I click on logout:
- Authentication bloc -> logout

Unfortunately, the bloc in charge of displaying the login page is no more in the stack (due to PushReplacement)
What would be your advice / architecture to fix this issue ?

**Comment by felangel** [comment]
Hi @fvisticot 👋 
Thanks for opening an issue!

Have you taken a look at the basic [login example](https://felangel.github.io/bloc/#/flutterlogintutorial)?

I would recommend avoiding PushReplacement for most cases.

Let me know if that helps 👍

**Comment by fvisticot** [comment]
I do not know how to avoid using PushReplacement.
If I only use Push with fullscreenDialog=true I get a cross to close the screen. Is it possible to disable the cross on pushed screens ?

**Comment by felangel** [comment]
You can just push without fullscreenDialog and then it will be a normal navigation.

**Comment by fvisticot** [comment]
If I do that, I will have a back arrow to get back :)
I try to change the workflow to send an event in the bloc and display a new screen from root tree (like your Login sample)

**Comment by felangel** [comment]
Yeah it depends on what you want the user experience to be. You can check out the [navigation recipe](https://felangel.github.io/bloc/#/recipesflutternavigation) for more details. 

Hope that helps 👍
