### ISSUE TITLE
How to pass data to another screen with bloc -Flutter

### ISSUE THREAD

**Issue by Oliwiana** [felangel/bloc#2873]
How to transfer data from one screen to another using bloc and save , I would like to create a user profile where I have two screens, two steps to creating a profile. I created two blocs for each class, in one I have an avatar, city and name, in the other only description. I used an amplify and when I save the first screen and when I go to the second one, delete the data from the first screen. How do I save everything? without delete? after save second screen.

**First screen:**

     class ProfileBloc extends Bloc<ProfileEvent, ProfileState> {
     final DataRepository dataRepo;
     final StorageRepository storageRepo;
     final _picker = ImagePicker();

    ProfileBloc(
      {User? user,
      required bool isCurrentUser,
      required this.storageRepo,
      required this.dataRepo})
      : super(ProfileState(user: user, isCurrentUser: isCurrentUser)) {
    // storageRepo
    //     .getUrlForFile(user!.avatarKey)
    //     .then((url) => add(ProvideImagePath(avatarPath: url)));

    ImageUrlCache.instance
        .getUrl(user!.avatarKey)
        .then((url) => add(ProvideImagePath(avatarPath: url)));
    }

    @override
    Stream<ProfileState> mapEventToState(ProfileEvent event) async* {
    if (event is ChangeAvatarRequest) {
      yield state.copyWith(isImageSourceActionSheetVisible: true);
    } else if (event is OpenImagePicker) {
      yield state.copyWith(isImageSourceActionSheetVisible: false);
      try {
        final selectedImage =
            await _picker.pickImage(source: event.imageSource);
        if (selectedImage == null) return;
        final imageKey = await storageRepo.uploadFile(File(selectedImage.path));
        final user = state.user!.copyWith(avatarKey: imageKey);

        String? imageUrl;
        await Future.wait<void>([
          dataRepo.updateUser(user),
          storageRepo.getUrlForFile(imageKey).then((value) => imageUrl = value)
        ]);

        yield state.copyWith(avatarPath: imageUrl);
      } catch (e) {
        throw e;
      }
    } else if (event is ProvideImagePath) {
      if (event.avatarPath != null)
        yield state.copyWith(avatarPath: event.avatarPath);
    } else if (event is ProfileCityChanged) {
      yield state.copyWith(userCity: event.city);
    } else if (event is ProfileNameChanged) {
      yield state.copyWith(userName1: event.name);
    } else if (event is SaveProfileChanges) {
      // handle save changes
      yield state.copyWith(formStatus: FormSubmitting());
      final updatedUser2 =
          state.user!.copyWith(city: state.userCity, name: state.userName1);
      try {
        await dataRepo.updateUser(updatedUser2);
        print(updatedUser2);
        yield state.copyWith(formStatus: SubmissionSuccess());
      } on Exception catch (e) {
        yield state.copyWith(formStatus: SubmissionFailed(e));
      } catch (e) {
        print(e);
      }
    }
    }
    }

**Second screen:**

    class Profile2Bloc extends Bloc<Profile2Event, Profile2State> {
     final DataRepository dataRepo;
    // User? user;
    //   String ?get userCity => user!.city;
    //   String? get userName1 => user!.name;

    Profile2Bloc(
        {User? user, required bool isCurrentUser, required this.dataRepo})
         : super(Profile2State(user: user, isCurrentUser: isCurrentUser));

     @override
     Stream<Profile2State> mapEventToState(Profile2Event event) async* {
      if (event is ProfileDescriptionChanged) {
        yield state.copyWith(userDescription: event.description);
       } else if (event is SaveProfile2Changes) {
        yield state.copyWith(formStatus: FormSubmitting());
      final updatedUser =
      state.user!.copyWith(description: state.userDescription);
      try {
        await dataRepo.updateUser(updatedUser);
        print(updatedUser);
        // print(userDescribe);
        yield state.copyWith(formStatus: SubmissionSuccess());
      } on Exception catch (e) {
        yield state.copyWith(formStatus: SubmissionFailed(e));
      } catch (e) {
        print(e);
      }
    }
    }
    }

**Data Repo:**

     Future<User> updateUser(User updatedUser) async {
       try {
         await Amplify.DataStore.save(updatedUser);
         return updatedUser;
        } catch (e) {
           throw e;
          }
          }

**Comment by marcossevilla** [comment]
hi @Oliwiana! I suggest you have only one `ProfileBloc` in your case. That way, you'll be able to fill in the user data from a page on which you can have a form and a separate bloc to handle the form submission logic, like `LoginBloc` for example, and then you consume `ProfileBloc` in any page you want.

I have an example of filling a sign-up form and showing a profile page with the data of that form [here](https://github.com/NoScopeDevs/bloc_samples/blob/main/examples/form_flow). It's done with [flow_builder](https://pub.dev/packages/flow_builder) and [formz](https://pub.dev/packages/formz) but the logic is similar to what you want to achieve.

Hope that helps. 👍
