### ISSUE TITLE
Need example bloc communicate antoher blocs

### ISSUE THREAD

**Issue by 1AlexFix1** [felangel/bloc#288]
Hi, thanks again for the great library. I would like to discuss and see examples of communication between the blocks.
For example, if two blocks are on the same level, it is logical to create a parent block for their communication, but here’s how a block can communicate with its parent. There are the following examples on the Internet.

```
class BlocA {

BlocB blocB;

BlocA () {
blocB = BlocB (this);
}

}
```
and if dispose does not reset the links, there will be a leak since the two classes have a link to each other;
There is a second option that I think about, this is either a streamConroller transmission, or transfer stream and sink to communicate and listen to the parent. What do you think, could you not make examples and add to the documentation it would be just great!

**Comment by felangel** [comment]
Hi @1AlexFix1 👋 
Thanks for opening an issue. 

Have you taken a look at [bloc to bloc communication](https://felangel.github.io/bloc/#/architecture?id=bloc-to-bloc-communication) in the docs?

If that isn’t what you are looking for can you please provide a more specific example of the use-case you have so that I have some more context? Thanks!

**Comment by 1AlexFix1** [comment]
> Hi @1AlexFix1 👋
> Thanks for opening an issue.
> 
> Have you taken a look at [bloc to bloc communication](https://felangel.github.io/bloc/#/architecture?id=bloc-to-bloc-communication) in the docs?
> 
> If that isn’t what you are looking for can you please provide a more specific example of the use-case you have so that I have some more context? Thanks!

Wow, I looked bad (thanks, I see the implementation yes, and it turns out that the child dispatch events to the parent

**Comment by felangel** [comment]
Haha no worries! Closing for now but if you have additional questions let me know 🙂
