### ISSUE TITLE
Why many AuthenticationState subclasses are used?

### ISSUE THREAD

**Issue by francobellu** [felangel/bloc#289]
@felangel 

I see to that in order to differentiate among different type of AuthenticationState you subclass.
I wonder way you don't simply us an enumeration that could be a property of AuthenticationState ( see below what I'm currently using).
This why when yielding states in the bloc or when handling states in the ui, you can use a switch statement.
So, is there's an important reason to subclass instead of using an enumeration.  

```
enum AuthState  {
  UNKNOWN,
  WAITING_RESPONSE,
  NOT_LOGGED_IN,
  LOGGED_IN,
  FAILED,
}

class AuthenticationState extends BlocState {
  AuthState state = AuthState.NOT_LOGGED_IN;
  final String email;
  final String displayName;

  AuthenticationState({
    @required this.state,
    this.email,
    this.displayName,
  });
```

```
@immutable
abstract class AuthenticationState extends Equatable {
  AuthenticationState([List props = const []]) : super(props);
}

class Uninitialized extends AuthenticationState {
  @override
  String toString() => 'Uninitialized';
}

class Authenticated extends AuthenticationState {
  final String displayName;

  Authenticated(this.displayName) : super([displayName]);

  @override
  String toString() => 'Authenticated { displayName: $displayName }';
}

class Unauthenticated extends AuthenticationState {
  @override
  String toString() => 'Unauthenticated';
}
```

**Comment by felangel** [comment]
Hi @francobellu 👋 
Thanks for opening an issue. 

There’s nothing wrong with using enums for cases where you don’t need additional properties but in general it’s a bit more “future-proof” to use classes because if your code evolves and requires additional properties to be passed, you will not need to refactor.

Hope that helps and great question 👍

**Comment by francobellu** [comment]
@felangel  many thanks !!
