### ISSUE TITLE
"freeze" BlocBuilder during page transitions using buildWhen?

### ISSUE THREAD

**Issue by Lootwig** [felangel/bloc#2891]
When changing a BlocBuilder's returned Widget _while_ there is a page transition taking place, the Widget is of course updated during the animation.

However, since operations like e.g. Navigator.pop() do not return a future (which would allow me to wait with the state update until _after_ that transition is done), it seems like returning "false" from buildWhen might be the next best option - however, as the documentation somewhat suggests ("...provides no security about the state passed..."), I'm not sure if this is a recommended way of achieving the described behavior. Any best practices for this?

**Comment by Lootwig** [comment]
This code works with dartpad. The timer has the same effect as a bloc state update: Not only is the position switched, but also the text of the "old" widget that should just remain the same.
In the example, it's a crossfade, but the same behavior happens with a Navigator.push().

And yes, the `Text` widgets could just be created outside of the stateful widget, but that is not the point as it only applies to this simplified example - because **while** the "old" widget is still visible, I actually need it to be updated along with the sate.


```dart
import 'dart:async';

import 'package:flutter/material.dart';

const Color darkBlue = Color.fromARGB(255, 18, 32, 47);

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: darkBlue,
      ),
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: MyWidget(),
      ),
    );
  }
}

class MyWidget extends StatefulWidget {
  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  bool _toggle = true;

  @override
  initState() {
    super.initState();
    Timer.periodic(
        const Duration(seconds: 3), (_) => setState(() => _toggle = !_toggle));
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedCrossFade(
        duration: const Duration(seconds: 2),
        crossFadeState:
            _toggle ? CrossFadeState.showFirst : CrossFadeState.showSecond,
        firstChild: Padding(
          padding: const EdgeInsets.only(right: 100.0),
          child: Text(
            'toggle is $_toggle',
            style: Theme.of(context).textTheme.headline4,
          ),
        ),
        secondChild: Padding(
          padding: const EdgeInsets.only(left: 100.0),
          child: Text(
            'toggle is $_toggle',
            style: Theme.of(context).textTheme.headline4,
          ),
        ));
  }
}

```

**Comment by Gene-Dana** [comment]
Okay, I really appreciate you putting together the example ! This seems like a pretty interesting problem, although the more I look at it, the more I think that perhaps this isn't really even a bloc problem.

Further, I'm still slightly confused what you'd like to achieve ! Do you want to value to change **before** you initiate the transition?
