### ISSUE TITLE
feat: Match bloc generation from plugin to suggested approach with named constructors

### ISSUE THREAD

**Issue by Gene-Dana** [felangel/bloc#2892]
**Description**
When I generate a bloc from the extension, I normally have to refactor all the code in order to use named constructors in the suggested approach

**Desired Solution**

I'd like the plugin to generate the suggested approach ! 

**Alternatives Considered**

Just ignoring the problem

**Comment by felangel** [comment]
Hi @Gene-Dana 👋 
Thanks for opening an issue!

Can you please be a bit more specific? It would be super helpful if you could provide a snippet of the currently generated code and the code you wish was generated, thanks!

**Comment by nathanielxd** [comment]
Hello! Are you referring to the generated states by the extensions? You could always write your own snippets, it should automate your work flow.

**Comment by Gene-Dana** [comment]
@nathanielxd Hey ! that's kinda cool !
