### ISSUE TITLE
feat: Missing skipLast or skipAfter parameter

### ISSUE THREAD

**Issue by MlecznyU** [felangel/bloc#2893]
**Description**

The skip parameter is available in the package, but I am missing the skipLast or skipAfter parameter.
I often face the problem that after performing a certain operation on a bloc, the bloc emits a state. E.g. every time I fetch new data bloc emits state loading. I would like to test if this always happens. Now, I am not able to write such a test, because most of the time states like loaded or error are emitted afterward. 

**Desired Solution**

Add parameter skipLast or skipAfter. 

skipLast -> ignore last 2 states

skipAfter -> ignore after emiting e.g. 1 state

**Comment by marcossevilla** [comment]
hi @MlecznyU! I'm not sure I understand well your request, have you tried expecting all the states the operation should emit?

If you want to check a loading state you can expect it with the other states on the expect parameter of bloc test. Similar to [this test](https://github.com/felangel/bloc/blob/a9b8a340d2440c84737bd03405bc69866321d4ee/examples/flutter_shopping_cart/test/catalog/bloc/catalog_bloc_test.dart#L37).

Let me know if that helps. 👍
