### ISSUE TITLE
Me again ˆ_ˆ

### ISSUE THREAD

**Issue by 1AlexFix1** [felangel/bloc#290]
```
import 'package:bloc/bloc.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class TestClass extends StatefulWidget {
  @override
  _TestClassState createState() => _TestClassState();
}

class _TestClassState extends State<TestClass> {
  final _bloc = TestBloc();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: BlocProvider(
        bloc: _bloc,
        child: Container(
          child: BlocBuilder<BlocEvent, BlocState>(
            bloc: _bloc,
            builder: (_, state) {
              return Container(
                color: state.a ? Colors.white : Colors.black,
                child: Container(
                  child: BlocBuilder<BlocEvent, BlocState>(
                    bloc: _bloc,
                    builder: (_, state) {
                      return Text(state.b.toString());
                    },
                  ),
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}

class TestBloc extends Bloc<BlocEvent, BlocState> {
  @override
  BlocState get initialState => BlocState();

  @override
  Stream<BlocState> mapEventToState(BlocEvent event) {
    // TODO: implement mapEventToState
    return null;
  }
}

class BlocEvent {}

class BlocState {
  bool a = true;
  var b = 1;
}

```

This is an individual example, question or function request as follows. BlocBuilder does not allow you to somehow listen to a stream with filters. Since in this example, if there are two variables that can change at different times, and when the parameter a changes, the parameter b is called, this is solved using StreamBuilder and streaming data filters. The point is to be able to filter state data and not cause unnecessary assemblies.
P.S.  I'm a little crazy about optimization

**Comment by felangel** [comment]
Hi @1AlexFix1 👋 
Thanks for opening an issue.

Regarding your question, it sounds very similar to #174. Can you confirm whether or not you are asking for the same feature? Thanks!

**Comment by 1AlexFix1** [comment]
Yes, this is what you need, thanks again!

**Comment by felangel** [comment]
Thanks, so do you like the solution proposed in the extensions package?

**Comment by 1AlexFix1** [comment]
> Thanks, so do you like the solution proposed in the extensions package?

I prefer StremBuilder =)

**Comment by happapa** [comment]
Would a more concrete visualization of this example be a simple counter app, like the default flutter project? A class called CounterBloc would have the current counter value (int) and information whether the value is divisible with 1000000 (bool) as its state. The int value will change very often and the bool very rarely. Both things are tightly connected, so it wouldn't make sense to me to try to divide the bloc into smaller components. The UI has one text widget that shows the counter value and updates often. Another widget changes the background color based on the bool state and updates very rarely. Both widgets are listening to the CounterBloc which results in many unneccessary rebuilds for the background color with the current flutter_bloc implementation. Is this the problem in a nutshell?
