### ISSUE TITLE
Should state always be immutable?

### ISSUE THREAD

**Issue by VivekKannaV** [felangel/bloc#292]
I have seen in some of the blogs or tutorial, they created a state with the _immutable_ annotation.
For reference:
[flutter_bloc_with_stream](https://github.com/felangel/bloc/blob/master/examples/flutter_bloc_with_stream/lib/bloc/ticker_state.dart)

Should it always be an immutable one?

If it is yes. If immutable exists at infinite scroll list page means, the object creation might demands & it leads garbage collection to be done at a short span of time regularly which may affect app performance and memory usage.

Please express your views on that @felangel

**Comment by felangel** [comment]
Hi @VivekKannaV 👋 
Thanks for opening an issue!

Regarding your question, yes states should always be immutable. Can you please provide an example to illustrate your concerns? Thanks!

**Comment by VivekKannaV** [comment]
Hi @felangel 
Please look at the following example
[Flutter Infinite List](https://github.com/felangel/bloc/tree/master/examples/flutter_infinite_list)

In this project, take a look at [profile_state](https://github.com/felangel/bloc/blob/master/examples/flutter_infinite_list/lib/bloc/post_state.dart)

In that [profile_state](https://github.com/felangel/bloc/blob/master/examples/flutter_infinite_list/lib/bloc/post_state.dart), 
_PostLoaded_ State has a _list_ & list will add more items whenever the user scrolls.
In that situation, if I keep state as an immutable one means, I need to create a new object `new PostLoaded(posts: list)` every time, which may affect my app performance as I said earlier.

In spite of this, why shouldn't I create the state as a mutable one & whenever user scrolls, I can update the _list_ alone rather than creating a new object like below.
`state.list.add(items)`.

Thanks.

**Comment by felangel** [comment]
Immutable state is a requirement of the bloc library for several reasons:

- It allows the library to detect state changes efficiently
- Makes handling data safer (no side-effects or mutations)
- Makes state management predictable because we're using static snapshots of our state instead of state which can change at any point in time leading to strange/unpredictable behavior.

Hope that helps 👍

**Comment by BitBlueDevStudio** [comment]
> Immutable state is a requirement of the bloc library for several reasons:
> 
> * It allows the library to detect state changes efficiently
> * It makes handling data safer (no side-effects or mutations)
> * It makes state management predictable because we're using static snapshots of our state instead of state which can change at any point in time leading to strange/unpredictable behavior.
> 
> Hope that helps 👍

Can you please provide example of problems for every point?Side effects examples, mutations problems, unpredictable behavior, etc

**Comment by siva636** [comment]
Immutable state is a requirement for for bloc library for several reasons. But [using mutable state instead of immutable state can sometimes be more efficient](https://riverpod.dev/docs/providers/change_notifier_provider). Please choose a suitable solution for your individual use case.

**Comment by alexkmbk** [comment]
> * It allows the library to detect state changes efficiently

Hello! But why do we need to detect state changes if we call "emit" method and we surely know what has been changed? All subscribers will notice the changes after we call emit.
