### ISSUE TITLE
how can i run samples?

### ISSUE THREAD

**Issue by MahdiPishguy** [felangel/bloc#293]
after clone repository and opening folder with vs code or android studio i cant run samples and trace code to learn

**Comment by felangel** [comment]
Hi @MahdiPishguy 👋 
Thanks for opening an issue!

Can you be more specific about how you are running the samples and what error you are seeing? Thanks 🙏

**Comment by MahdiPishguy** [comment]
@felangel i clone your git from this link as ```https://github.com/felangel/bloc.git``` from Android Studio, after finish that i get download Dart SDK message on top of android studio screen 

on Run/Debug Configuration and Dart endpoit this location which file from samples folder i should be set? i set ```E:\Projects\Flutter\bloc_samples\examples\flutter_login\lib\main.dart``` and i expect to tun project, but nothing change,

i'm sorry for my english

**Comment by felangel** [comment]
You probably need to open the specific example project in android studio instead of the top level project. Otherwise I would recommend just opening a terminal, changing directories into the specific example you want to run, and then running flutter run. Hope that helps 👍

**Comment by MahdiPishguy** [comment]
@felangel  thanks

**Comment by MahdiPishguy** [comment]
@felangel can i ask some other question about Bloc implementation as issue?  

thanks in advance
