### ISSUE TITLE
feat: Distinguish between States and Side Effects

### ISSUE THREAD

**Issue by ptrbrynt** [felangel/bloc#2933]
**Description**

A common pattern when using Bloc and Cubit is to use a `State` to represent what is actually a side-effect. For example, you may have a simple cubit which loads some data and has `Initial`, `Loading`, `Error` and `Success` states. You want to display a Snackbar on Error states but not re-build the widget.

Currently you would need to emit the Error state, immediately followed by, say, the Initial state. There would be an unnecessary re-build by the `BlocBuilder` widget and the developer would have to add a placeholder to handle displaying a widget on Error states when it's not needed.

I think there is a better way to handle the above scenario using Bloc, while improving developers' ability to write concise and understandable code.

**Desired Solution**

I believe that the Bloc library could allow Blocs and Cubits to emit side-effects. These could be given a type distinct from states and would allow developers to separate widget rebuilds from single-event effects.

This would be supported by updating `BlocListener` to listen to side-effects, not state changes.

**Comment by felangel** [comment]
Hi @ptrbrynt 👋 
Thanks for opening an issue!

In the scenario you described, I would generally recommend restructuring your state to consist of a single concrete implementation rather than multiple subclasses:

```dart
enum MyStatus { initial, loading, success, failure }

class MyState {
  const MyState({this.status = MyStatus.initial, this.value, this.error});

  final MyStatus status;
  final SomeValue? value;
  final Object? error;

 MyState copyWith(...) {...}
}
```

Then in your UI, you can use `BlocSelector` to select the value and only rebuild when the value changes:

```dart
BlocSelector<MyBloc, MyState>(
  selector: (state) => state.value,
  builder: (context, value) {
    // Render UI in response to value.
  },
);
```

> Currently you would need to emit the Error state, immediately followed by, say, the Initial state. There would be an unnecessary re-build by the BlocBuilder widget and the developer would have to add a placeholder to handle displaying a widget on Error states when it's not needed.

You shouldn't need to emit back-to-back states like this if you adjust the way the state is represented to better fit your current use case. With the above approach you can use `copyWith` to emit a copy of the current state and set the error value if an error occurs:

```dart
try {
  emit(state.copyWith(status: MyStatus.loading));
  final value = await _getValueAsync(...);
  emit(state.copyWith(status: MyStatus.success, value: value));
} catch (error, stackTrace) {
  emit(state.copyWith(status: MyStatus.failure, error: error));
}
```

Let me know if that helps and thanks again for opening an issue! 👍

**Comment by felangel** [comment]
Closing for now since there are no actionable next steps but feel free to comment with additional comments/feedback and I'm happy to continue the conversation 👍

**Comment by alvindrakes** [comment]
@felangel  Hi Felix, your example definitely helps a lot. 

Just a quick question, if I want multiple buttons in the UI for the same screen to have their own loading states, is it recommended to have different loading status in the state class? 

Something like this:
```

enum MyStatus { initial, loading, success, failure }

class MyState {
  const MyState({this.buttonOneStatus= MyStatus.initial, this.buttonTwoStatus= MyStatus.initial, this.value, this.error});

  final MyStatus buttonOneStatus;  <---- added this
  final MyStatus buttonTwoStatus;   <----
  final SomeValue? value;
  final Object? error;

  MyState copyWith(...) {...}
}`
```



Currently in my redux implementation, I have an action (similar to bloc events) that is defined like this:

```
class LogOut {
  LogOut({
    required this.completer,
  });

  final Completer<void> completer;

  static const requestId = 'LogOut';

  @override
  String toString() {
    return 'LogOut';
  }
}

class SetLogOutLoading implements SetLoadingInterface {
  @override
  String get loadingRequestId => LogOut.requestId;

  @override
  String toString() {
    return 'SetLogOutLoading';
  }
}

class CompleteLogOutSuccess implements StopLoadingInterface {
  @override
  String get loadingRequestId => LogOut.requestId;

  @override
  String toString() {
    return 'CompleteLogOutSuccess';
  }
}

class CompleteLogOutFail implements StopLoadingInterface {
  CompleteLogOutFail({
    required this.error,
  });

  final dynamic error;

  @override
  String get loadingRequestId => LogOut.requestId;

  @override
  String toString() {
    return 'CompleteLogOutFail error=$error';
  }
}
```

But in the epics, I am able to check if the dispatched action type and set a global loading state to be **loading** like this:
```
typedef Epic = Stream<dynamic> Function(
  Stream<dynamic> actions,
  EpicStore<AppState> store,
);

Epic createLogOutEpic(AppEpicDependencies dependencies) {
  return (
    actions,
    store,
  ) {
  
    return actions
        .whereType<LogOut>()
        .switchMap((action) {
      return Rx.concat([
        // set loading
        Stream.value(SetLogOutLoading()),
        // initiate query
        makeQuery(
            action: action, state: store.state, dependencies: dependencies),
      ]);
    });
  };
}
```

Are there any ways to implement the same side effect architecture in bloc? 
Thank you =)
