### ISSUE TITLE
docs: Infinite List, The method 'throttle' isn't defined for the type 'Stream'.

### ISSUE THREAD

**Issue by ChauCM** [felangel/bloc#2934]
Trying to follow the example, got this error:

![image](https://user-images.githubusercontent.com/86839861/141088960-281547e6-06f0-49b3-9f89-36fab8b34c34.png)

pubspec.yaml:
bloc_concurrency: ^0.1.0
flutter_bloc: ^7.3.1

**Comment by felangel** [comment]
Hi @ChauCM 👋 
Thanks for opening an issue!

In the infinite list example, `throttle` comes from `package:stream_transform/stream_transform.dart';` so you just need to add the `stream_transform` package to your `pubspec.yaml` and import it:

```yaml
dependencies:
  stream_transform: ^2.0.0
```

```dart
import 'package:bloc/bloc.dart';
import 'package:bloc_concurrency/bloc_concurrency.dart';
import 'package:stream_transform/stream_transform.dart';

part 'post_event.dart';
part 'post_state.dart';

const _postLimit = 20;
const throttleDuration = Duration(milliseconds: 100);

EventTransformer<E> throttleDroppable<E>(Duration duration) {
  return (events, mapper) {
    return droppable<E>().call(events.throttle(duration), mapper);
  };
}
```

You can check out the complete source code for the bloc at https://github.com/felangel/bloc/blob/master/examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart.

Let me know if that helps and sorry for any confusion!
