### ISSUE TITLE
style: bloc naming convention

### ISSUE THREAD

**Issue by datdefboi** [felangel/bloc#2935]
Hi, Felix!

I try to understand what is a current naming convention I have to use. 
The [corresponding page](https://bloclibrary.dev/#/blocnamingconventions?id=state-conventions) says I have to create different classes for each state:
`State should be one of the following: Initial | Success | Failure | InProgress and initial states should follow the convention: BlocSubject + Initial.`
But some examples created by you contain only the one state with [`Status field`](https://github.com/felangel/fluttersaurus/blob/e436e1f147acde5104fd511b944b460f5dfd9e89/lib/search/bloc/search_state.dart#L20). 
Does this mean that the agreements have changed?

**Comment by felangel** [comment]
Hi @datdefboi 👋 
Thanks for opening an issue!

I'm going to update the naming conventions shortly but yes the current naming conventions apply in cases where it makes sense to have multiple distinct state subclasses. There are cases where it makes more sense to have a single concrete state class with a status enum as illustrated by some of the examples 👍
