### ISSUE TITLE
fix: 通过context获取到的Bloc不能触发事件

### ISSUE THREAD

**Issue by hu70258tao** [felangel/bloc#2936]
描述：
  第一步：使用MultiBlocProvider创建了Bloc
```
return MultiBlocProvider(
                          providers: [
                            BlocProvider<ControlBloc>(
                                create: (context) => ControlBloc(
                                      routerBloc: BlocProvider.of<RouterBloc>(context),
                                      groupType: pageParam.groupType,
                                      deviceId: pageParam.deviceId,
                                      deviceCode: pageParam.deviceCode,
                                      twoWaterPump: pageParam.twoWaterPump,
                                      useZhaQian: pageParam.useZhaQian,
                                      useYanCao: pageParam.useYanCao,
                                      heightMax: pageParam.maxXingCheng,
                                      beforeMax: pageParam.maxBeforeWaterlevel,
                                      slotMax: pageParam.maxWeirTroughWaterlevel,
                                      flowMax: pageParam.maxFlow,
                                      plcCount: pageParam.plcCount,
                                    )..add(EventInited())),
                            BlocProvider<LiantiaoBloc>(create: (context)=>LiantiaoBloc(deviceId: pageParam.deviceId))
                          ],
                          child: ControlView(),
class ControlView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    ControlBloc bloc = BlocProvider.of<ControlBloc>(context);
    return SingleChildScrollView(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          ControlTypeView(),
          GateControlTypeView(useZhaQian: bloc.useZhaQian, useYanCao: bloc.useYanCao),
          ValveControlTypeView(),
          WhichPumpView(),
          WhichPlcView(),
          ControlTimeView(),
          ControlParamView(),
          ControlOperCodeView(),
          Container(
            margin: EdgeInsets.only(top: 20),
            child: SubmitButton(),
          ),
        ],
      ),
    );
  }
}
class SubmitButton extends StatelessWidget {
  ///test bloc
  LiantiaoBloc _bloc = LiantiaoBloc(deviceId: '');
  @override
  Widget build(BuildContext context) {
    return BlocConsumer<ControlBloc, ControlState>(
      buildWhen: (p, c) => p.pageStatus != c.pageStatus || p.formStatus != c.formStatus,
      builder: (context, state) {
        if (state.pageStatus == PageStatus.Load) return CircularProgressIndicator();
        VoidCallback? onPressed = () {
          FocusScope.of(context).requestFocus(FocusNode());
          int? opercode = AuthRepo.user.operCode;
          if (opercode == null) {
            Utils.checkOperCode(context);
          } else {
            BlocProvider.of<ControlBloc>(context).add(EventSubmit());
          }
        };
        String message = "制定控制计划";
        if (!state.formStatus.success) {
          onPressed = null;
          message = state.formStatus.message;
        }
        ElevatedButton button = ElevatedButton(
          style: ButtonStyle(
            backgroundColor: MaterialStateProperty.resolveWith((states) => Colors.blue),
            shape: MaterialStateProperty.resolveWith((states) => RoundedRectangleBorder(borderRadius: new BorderRadius.circular(45.0))),
          ),
          child: Text(message, style: TextStyle(fontSize: 14.0, color: Color.fromARGB(255, 255, 255, 255))),
          onPressed: onPressed,
        );
        return SizedBox(height: 45.0, width: 270.0, child: button);
      },
      listenWhen: (p, c) => p.liantiaotanchuang != c.liantiaotanchuang,
      listener: (context, state) {
        LiantiaoBloc _bloc = context.read<LiantiaoBloc>();
        // _bloc.add(LiantiaoEventStart());
        showCupertinoDialog(
          context: context,
          builder: (context2) {
            return WillPopScope(
              child: CupertinoAlertDialog(
                title: Text("闸门联调数据"),
                content: Container(
                  height: 120.h,
                  color: Colors.white,
                  child: Text("占位"),
                  // PhotoView.customChild(
                  //   child: BlocProvider(
                  //     create:(context)=>liantiaoBloc,
                  //     child: LiantiaoView(),
                  //   ),
                  // ),
                ),
                actions: [TextButton(onPressed: ()async{
                  _bloc.add(LiantiaoEventStop());
                  await Future.delayed(Duration.zero);
                  Navigator.of(context2).pop();
                }, child: Text("关闭"))],
              ),
              onWillPop: () async => false,
            );
          },
        );
      },
    );
  }
}
```
如果使用context.read<LiantiaoBloc>();的方式获取到_bloc,Dialog关闭后，再次弹出Dialog时就不能再触发Bloc的事件了.假如使用SubmitButton类里的属性_bloc,每次弹窗关窗，都能触发事件。

**Comment by hu70258tao** [comment]
bloc代码
···
class LiantiaoData {
  final String kaidu;
  final String shuiwei;
  final String liuliang;
  const LiantiaoData({required this.kaidu, required this.shuiwei, required this.liuliang});
}

class LiantiaoState {
  final bool hasValue;
  final LiantiaoData left;
  final LiantiaoData right;
  final LiantiaoData jiezhizha;
  const LiantiaoState({required this.left, required this.right, required this.jiezhizha, this.hasValue = true});
}

const LiantiaoState initState = const LiantiaoState(
  hasValue: false,
  left: LiantiaoData(kaidu: "", shuiwei: "", liuliang: ""),
  right: LiantiaoData(kaidu: "", shuiwei: "", liuliang: ""),
  jiezhizha: LiantiaoData(kaidu: "", shuiwei: "", liuliang: ""),
);

abstract class LiantiaoEvent {}

class LiantiaoEventStart extends LiantiaoEvent {}
class LiantiaoEventLoad extends LiantiaoEvent {}
class LiantiaoEventStop extends LiantiaoEvent {}

class LiantiaoBloc extends Bloc<LiantiaoEvent, LiantiaoState> {
  final String deviceId;
  StreamSubscription<int>? _timer;
  LiantiaoBloc({required this.deviceId}) : super(initState) {
    on<LiantiaoEventStart>(_liantiaoEventStart);
    on<LiantiaoEventLoad>(_liantiaoEventLoad);
    on<LiantiaoEventStop>(_liantiaoEventStop);
  }
  void _liantiaoEventStart(event, emit) {
    print("开始调用数据");
    _timer = Utils.tick(step: 3).listen((event) => add(LiantiaoEventLoad()));
  }
  void _liantiaoEventLoad(event, emit) {
    LiantiaoState state = LiantiaoState(
      hasValue: false,
      left: LiantiaoData(kaidu: "${Random.secure().nextInt(100)}mm", shuiwei: "${Random.secure().nextInt(100)}mm", liuliang: "${Random.secure().nextInt(100)}m³/s"),
      right: LiantiaoData(kaidu: "${Random.secure().nextInt(100)}mm", shuiwei: "${Random.secure().nextInt(100)}mm", liuliang: "${Random.secure().nextInt(100)}m³/smm"),
      jiezhizha: LiantiaoData(kaidu: "${Random.secure().nextInt(100)}mm", shuiwei: "${Random.secure().nextInt(100)}mm", liuliang: "${Random.secure().nextInt(100)}m³/smm"),
    );
    emit(state);
  }
  void _liantiaoEventStop(event, emit) {
    print("结束调用数据");
    _timer?.cancel();
    _timer = null;
  }
}
···

**Comment by hu70258tao** [comment]
主要在这段代码里。继续使用BlocProvider来提供liantiaoBloc
```
/ PhotoView.customChild(
                  //   child: BlocProvider(
                  //     create:(context)=>liantiaoBloc,
                  //     child: LiantiaoView(),
                  //   ),
                  //),
```

**Comment by Gene-Dana** [comment]
Instead of this

```dart
  BlocProvider.of<ControlBloc>(context).add(EventSubmit());
```

I believe you should do this

```dart
 context.read<ControlBloc>().add(EventSubmit());
```

**Comment by felangel** [comment]
Hi @hu70258tao 👋 
Thanks for opening an issue!

BlocProvider will automatically close the bloc when it is unmounted so in this case when you do

```dart
BlocProvider(
  create:(context)=> liantiaoBloc,
  child: LiantiaoView(),
)
```

Then the liantiaoBloc instance will be closed when LiantiaoView is unmounted. Instead, you should use BlocProvider.value to re-provide an existing bloc to a new context. BlocProvider.value will not automatically close the bloc.

```dart
BlocProvider.value(
  value: liantiaoBloc,
  child: LiantiaoView(),
)
```

Hope that helps! 👍

**Comment by hu70258tao** [comment]
> Hi @hu70258tao 👋 Thanks for opening an issue!
> 
> BlocProvider will automatically close the bloc when it is unmounted so in this case when you do
> 
> ```dart
> BlocProvider(
>   create: (context) => liantiaoBloc,
>   child: LiantiaoView(),
> )
> ```
> 
> Then the liantiaoBloc instance will be closed when LiantiaoView is unmounted. Instead, you should use BlocProvider.value to re-provide an existing bloc to a new context. BlocProvider.value will not automatically close the bloc.
> 
> ```dart
> BlocProvider.value(
>   value: liantiaoBloc,
>   child: LiantiaoView(),
> )
> ```
> 
> Hope that helps! 👍

my english is bad，tanks very much,it works

**Comment by hu70258tao** [comment]
应该使用BlocProvider.value来提供一个已存在的bloc，使用BlocProvider((context)=>bloc)来提供一个已存在的bloc,会导致该bloc被此处的BlocProvider关闭。
