### ISSUE TITLE
[Question] How to implement/migrate StreamSubscription in Bloc >=7.2.0? 

### ISSUE THREAD

**Issue by AscentionOne** [felangel/bloc#2937]
Hi @felangel, when I was migrating the code to v7.2.0 and looking at the Bloc documentation [Example](https://bloclibrary.dev/#/fluttertodostutorial?id=bloc-2). I have a question is how to properly migrate the code with `StreamSubscription` that listens to another bloc? Like in the example code of `Todos App`. The `StatsBloc` is lisenting to `TodosBloc`.

As the [article](https://verygood.ventures/blog/how-to-use-bloc-with-streams-and-concurrency?utm_source=linkedin&utm_medium=social&utm_campaign=bloc_concurrency_examples) article mentioned, in the "Blocs and Streams" section, the new Bloc (v7.2.0) is to prevent direct bloc-to-bloc coupling. I look through the  "Video Streaming Example" section and still cannot grasp the idea of how to properly migrate bloc with  `StreamSubscription` to another bloc in it. 

My thought was to use `BlocListener` that listens to another bloc in the widget tree and fire the event ( `context.read<FoodBloc>().add(FoodEvent.getFood())` ) related to the different states of the bloc that we are listening to. Is this the right way? Thank you! 😁

**Comment by ash0080** [comment]
1. moving the data to the domain layer and "listening in" from blocs above ...
2. putting bloc listeners higher in the widget tree and adding events to other blocs when another bloc's state changes...

Sorry, I don't quite understand the first solution, can you provide an example?
For the second one, it's better to understand, but wouldn't this put part of the business logic into the widget? I'm confused.

riverpod, which has good support for provider's composition, 
But whether it's bloc-to-bloc communication, or either of the above, I feel it's a detour 
In react, there is a common concept, computed property, is there a simple way to implement it in bloc?

**Comment by marcossevilla** [comment]
@AscentionOne you can check the login example on the v8 branch [here](https://github.com/felangel/bloc/blob/a08e2380936171021dcf85def952081907c825b9/examples/flutter_login/lib/authentication/bloc/authentication_bloc.dart#L21).

**Comment by AscentionOne** [comment]
@marcossevilla Cool, thanks for the sharing. I will take a look. 😁
