### ISSUE TITLE
docs(flutter_counter): translate to zh-cn

### ISSUE THREAD

**Issue by hyj1204** [felangel/bloc#2951]
**Description**

I found there is no Chinese translation of the tutorial part. 

I am wondering if anyone is already working on it? 

Please let me know how is the current status of the Chinese translation and I am willing to help.

**Comment by felangel** [comment]
Hi @hyj1204 👋 
Thanks for opening an issue!

Which tutorial are you referring to? No one is actively working on any Chinese translations as far as I know so if you are willing/able to contribute that would be amazing!

You should be able to follow the [contributing instructions](https://github.com/felangel/bloc/blob/master/CONTRIBUTING.md#contributing-to-documentation) to get started.

Feel free to comment with any questions and I’m happy to help. Thanks again! 💙🙏

**Comment by hyj1204** [comment]
Hi @felangel, 

Since I am new to contributing to open source, I would love to start from the first tutorial in Flutter **Counter**, then make a PR for it.  After it, I move to the next **Timer**  until finish all the tutorials are in the Flutter category. What do you think about it? 

Looking for your feedback. Thanks.

- Tutorials
  - Flutter
    - [X] Counter -> Yijing 
    - [ ] Timer
    - [ ] Infinite List
    - [ ] Login
    - [ ] Weather
    - [ ] Todos
    - [ ] Firebase Login
    - [ ] Firestore Todos

**Comment by felangel** [comment]
@hyj1204 that sounds great to me! We can make this issue specifically for the counter and when you're done if you'd like to work on another we can create a new issue 👍

**Comment by jeroen-meijer** [comment]
Thanks a lot for the effort @hyj1204!

Just a small heads-up; both the regular Flutter Todos example and the Firebase version are currently being remade, so I would recommend to wait with translating documentation for the time being while we finish up the code and new documentation. The PR in question can be found here: #2859

We'll keep this thread up to date, and tell you when the example is updated. Thanks again! 👋🏻

**Comment by hyj1204** [comment]
@jeroen-meijer  
Thanks for letting me know. I just finished the first Counter example and gonna wait until the new version released.

**Comment by felangel** [comment]
Closing this since #2972 has been merged and deployed 🎉
