### ISSUE TITLE
feat: Flutter Web Support for HydratedBloc linked into localStorage.  

### ISSUE THREAD

**Issue by hamzablx195** [felangel/bloc#2952]
#flutter_web #hydrated_bloc 
Extending a Mobile product into a Web product using Flutter Web. Ideally I'd like my HydratedBloc storage to be directly linked with my localStorage module. There should be an override for the the following command for the web scenario. 

`HydratedBloc.storage = await HydratedStorage.build(
      storageDirectory: await getTemporaryDirectory(),
    );`

If there is a solution, can you please guide me to it. Much Appreciated. 

Best Regards.

**Comment by felangel** [comment]
Hi @hamzablx195 👋 
Thanks for opening an issue!

This is currently supported:
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  HydratedBloc.storage = await HydratedStorage.build(
    storageDirectory: kIsWeb
        ? HydratedStorage.webStorageDirectory
        : await getTemporaryDirectory(),
  );
  runApp(App());
}
```

Closing for now but feel free to comment with any follow-up questions and I’m happy to continue the conversation 👍

**Comment by hamzablx195** [comment]
Yep, found this after some manual searching :p 

Thank you so much for your timely response! Much Appreciated! 🙌

**Comment by Omar-Khaium** [comment]
@felangel 

Getting this error:
**`"error: The setter 'storage' isn't defined for the type 'HydratedBloc'. (undefined_setter at [tmoto_admin_panel] lib\main.dart:20)"`** for Flutter web.
Currently using version **`8.0.0`** of hydrated_bloc.

![image](https://user-images.githubusercontent.com/40541185/144704930-9411f508-6b06-4295-b897-230e1c37bfb0.png)

**Comment by felangel** [comment]
> @felangel
> 
> Getting this error: **`"error: The setter 'storage' isn't defined for the type 'HydratedBloc'. (undefined_setter at [tmoto_admin_panel] lib\main.dart:20)"`** for Flutter web. Currently using version **`8.0.0`** of hydrated_bloc.
> 
> ![image](https://user-images.githubusercontent.com/40541185/144704930-9411f508-6b06-4295-b897-230e1c37bfb0.png)

You need to use the new HydratedBlocOverrides API to specify a storage instance. You can check out the [hydrated_bloc example](https://github.com/felangel/bloc/blob/master/packages/hydrated_bloc/example/lib/main.dart#L10) for reference and read more about the change in the [migration guide](https://bloclibrary.dev/#/migration?id=%e2%9d%97%e2%9c%a8-introduce-new-hydratedblocoverrides-api)

**Comment by sramac2** [comment]
I just wanted to ask, If there is a way to implement hydrated bloc for the web as well which is awesome, can you update the package to say it supports the web as well, or still, it needs work to update it?
