### ISSUE TITLE
Incoming events are blocked while listening a WebSocket stream

### ISSUE THREAD

**Issue by LeonidArefev** [felangel/bloc#2953]
**Description**
I'm working with Websockets now. I need to get events while websocket connection is not closed. But if i use `.map()` it will block all incoming evets for Bloc

```dart
   @override
  Stream<SpeakerListState> mapEventToState(SpeakerListEvent event) async* {
    if (event is SpeakerListInitialize) {
      /// INITIALIZE
      yield* _subscribeToWebSocket(teamId);
    }
***
Stream<SpeakerListState> _subscribeToWebSocket(String teamId) async* {
    _repository.webSocketConnect();
    var retStream = _repository.webSocketStream()
        .where((event) => event.speakers.items.length > 0)
        .map((event) => event.speakers)
        .map((event) => _simplyGenerateNewUsersState(event));
    _repository.webSocketSetCurrentTeam(teamId);
    yield* retStream;
  }

```
`retStream` - will be active until websocket connection is alive.
This stream will block all incoming events for Bloc until websocket connection will be closed. So i can not click on any buttons to send request to server.

Or using `.listen()` with `this.add(InternalUpdateEvent)`  it's the only valid solution?
```dart
_repository.webSocketStream().listen((data)->{
  add(UpdateScreenEvent(usersList))
})
```

**Comment by felangel** [comment]
Hi @LeonidArefev 👋 
Thanks for opening an issue and sorry for the delayed response!

If you're using `bloc >= 7.2.0` then you can refactor your code to:

```dart
class SpeakerListBloc extends Bloc<SpeakerListEvent, SpeakerListState> {
  SpeakerListBloc() : super(SpeakerListInitial()) {
    on<SpeakerListInitialize>(_onSpeakerListInitialize);
  }

  Future<void> _onSpeakerListInitialize(
    SpeakerListInitialize event,
    Emitter<SpeakerListState> emit,
  ) async {
    _repository.webSocketConnect();
    final stream = _repository.webSocketStream()
        .where((event) => event.speakers.items.length > 0)
        .map((event) => event.speakers)
        .map((event) => _simplyGenerateNewUsersState(event));
    _repository.webSocketSetCurrentTeam(teamId);
    return emit.forEach(stream, onData: (state) => state);
  }
}
```

Hope that helps 👍

**Comment by LeonidArefev** [comment]
Hi @felangel 
Thanks for explanation. I'm little bit outdated about latest features in BLoC v8.+
Problem now solved. 
But here is only request.
```dart
// defined exact returned type SpeakerListLoadSuccess as subtype of SpeakerListState
SpeakerListState _simplyGenerateNewUsersState(UsersList users) {
    return SpeakerListLoadSuccess(...);
  }

Future<void> _subscribeToWebSocket(
      String teamId, Emitter<SpeakerListState> emit) {
    _repository.webSocketConnect();
    final Stream<***SpeakerListState***> usersStream = _repository <---- event with exact variable type
        .webSocketStream()
        .where((event) => event.speakers.items.length > 0)
        .map((event) => _simplyGenerateNewUsersState(event.speakers));
    _repository.webSocketSetCurrentTeam(teamId);
    return emit.forEach(usersStream,
        onData: (state) => state as ***SpeakerListState***);<---- state must have type conversion
  }
```
Variable `usersStream` have type `Stream<SpeakerListState>` but i need to use ` as SpeakerListState` 
Curently i upgrate `flutter_bloc` to version 7.3.3. May be this is not a problem in version 8.+. I can't do this for whole project quickly.

But problem is closed.
Thanks for support!

**Comment by felangel** [comment]
> ```dart
> class SpeakerListBloc extends Bloc<SpeakerListEvent, SpeakerListState> {
>   SpeakerListBloc() : super(SpeakerListInitial()) {
>     on<SpeakerListInitialize>(_onSpeakerListInitialize);
>   }
> 
>   Future<void> _onSpeakerListInitialize(
>     SpeakerListInitialize event,
>     Emitter<SpeakerListState> emit,
>   ) async {
>     _repository.webSocketConnect();
>     final stream = _repository.webSocketStream()
>         .where((event) => event.speakers.items.length > 0)
>         .map((event) => event.speakers)
>         .map((event) => _simplyGenerateNewUsersState(event));
>     _repository.webSocketSetCurrentTeam(teamId);
>     return emit.forEach(stream, onData: (state) => state);
>   }
> }
> ```

Glad it's working now! Regarding the casting you should be able to specify the type instead like:

```dart
class SpeakerListBloc extends Bloc<SpeakerListEvent, SpeakerListState> {
  SpeakerListBloc() : super(SpeakerListInitial()) {
    on<SpeakerListInitialize>(_onSpeakerListInitialize);
  }

  Future<void> _onSpeakerListInitialize(
    SpeakerListInitialize event,
    Emitter<SpeakerListState> emit,
  ) async {
    _repository.webSocketConnect();
    final stream = _repository.webSocketStream()
        .where((event) => event.speakers.items.length > 0)
        .map((event) => event.speakers)
        .map((event) => _simplyGenerateNewUsersState(event));
    _repository.webSocketSetCurrentTeam(teamId);
    return emit.forEach<SpeakerListState>(stream, onData: (state) => state);
  }
}
```
