### ISSUE TITLE
Control PageView With Bloc State-Management in Flutter

### ISSUE THREAD

**Issue by tawasoli369** [felangel/bloc#2956]
**Hi, in this project I wanted to control a PageView, three buttons and dots at the bottom of the page by State-Management (Bloc) but I could not control it. If anyone can help me, thank you.**

**UI**
In this part, I designed the program UI, which includes a PageView widget, three buttons: one for the next PageView page / one to jump to the last page of the PageView page and the other button to go to another page.

``// version 2.0 Page intro
import 'package:dayan/bloc/intro_bloc/intro_bloc.dart';
import 'package:dayan/events/intro_event/intro_event.dart';
import 'package:dayan/states/intro_state/intro_state.dart';
import 'package:flutter/material.dart';
import 'package:dayan/helper/strings.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:lottie/lottie.dart';

class Intro extends StatelessWidget {
  const Intro({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: BlocProvider<IntroBloc>(
        create: (context) => IntroBloc(InitialState()),
        child: const IntroPage(),
      ),
    );
  }
}

class IntroPage extends StatefulWidget {
  const IntroPage({Key? key}) : super(key: key);

  @override
  _IntroPageState createState() => _IntroPageState();
}

class _IntroPageState extends State<IntroPage> {
  late PageController _pageController;
  int currentIndex = 0;
  bool _buttionSkipVisibility = true;
  bool _buttionNextVisibility = true;
  bool _buttionDoneVisibility = false;

  @override
  void initState() {
    _pageController = PageController(initialPage: 0);
    super.initState();
  }

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: <Widget>[
          Center(
            child: PageView(
              onPageChanged: (int page) {
                _buttionDoneVisibility = false;
                _buttionSkipVisibility = true;
                _buttionNextVisibility = true;
                setState(() {
                  context.read<IntroBloc>().add(ClickedNextButtonEvent());
                  currentIndex = page;
                });
                if (page == 5 - 1) {
                  context.read<IntroBloc>().add(ClickedSkipButtonEvent());
                  _buttionSkipVisibility = false;
                  _buttionNextVisibility = false;
                  _buttionDoneVisibility = true;
                }
              },
              controller: _pageController,
              children: <Widget>[
                introSlide(
                  jsonAnimation: Strings.slide_1_json_animation,
                  title: Strings.slide_1_title,
                  description: Strings.slide_1_desc,
                ),
                introSlide(
                  jsonAnimation: Strings.slide_2_json_animation,
                  title: Strings.slide_2_title,
                  description: Strings.slide_2_desc,
                ),
                introSlide(
                  jsonAnimation: Strings.slide_3_json_animation,
                  title: Strings.slide_3_title,
                  description: Strings.slide_3_desc,
                ),
                introSlide(
                  jsonAnimation: Strings.slide_4_json_animation,
                  title: Strings.slide_4_title,
                  description: Strings.slide_4_desc,
                ),
                introSlide(
                  jsonAnimation: Strings.slide_5_json_animation,
                  title: Strings.slide_5_title,
                  description: Strings.slide_5_desc,
                ),
              ],
            ),
          ),
          Align(
            alignment: Alignment.bottomCenter,
            child: Container(
              margin: const EdgeInsets.only(
                bottom: 25,
              ),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: _buildIndicator(),
              ),
            ),
          ),
          BlocBuilder<IntroBloc, IntroState>(builder: (context, state) {
            // UI for InitialState
            if (state is InitialState) {
              return Visibility(
                visible: InitialState().visibilityButtionDone,
                child: Padding(
                  padding: const EdgeInsets.only(
                    left: 20,
                    bottom: 5,
                  ),
                  child: Align(
                    alignment: Alignment.bottomLeft,
                    child: TextButton(
                      onPressed: () {
                        setState(() {
                          _pageController.jumpToPage(5 - 1);
                        });
                      },
                      child: Text(
                        Strings.skip,
                        style: const TextStyle(
                          color: Color(0XFF7D818A),
                          fontFamily: 'ShabnamBold',
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ),
                  ),
                ),
              );
            }
            // UI for GoNextPageState
            if (state is GoNextPageState) {
              return Visibility(
                visible: GoNextPageState().visibilityButtionDone,
                child: Padding(
                  padding: const EdgeInsets.only(
                    left: 20,
                    bottom: 5,
                  ),
                  child: Align(
                    alignment: Alignment.bottomLeft,
                    child: TextButton(
                      onPressed: () {
                        setState(() {
                          _pageController.jumpToPage(5 - 1);
                        });
                      },
                      child: Text(
                        Strings.skip,
                        style: const TextStyle(
                          color: Color(0XFF7D818A),
                          fontFamily: 'ShabnamBold',
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ),
                  ),
                ),
              );
            }
            // UI for GoEndPageState
            if (state is GoEndPageState) {
              return Visibility(
                visible: GoEndPageState().visibilityButtionDone,
                child: Padding(
                  padding: const EdgeInsets.only(
                    left: 20,
                    bottom: 5,
                  ),
                  child: Align(
                    alignment: Alignment.bottomLeft,
                    child: TextButton(
                      onPressed: () {
                        setState(() {
                          _pageController.jumpToPage(5 - 1);
                        });
                      },
                      child: Text(
                        Strings.skip,
                        style: const TextStyle(
                          color: Color(0XFF7D818A),
                          fontFamily: 'ShabnamBold',
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ),
                  ),
                ),
              );
            }
            // UI for GoLoginPageState
            if (state is GoLoginPageState) {
              return Visibility(
                visible: GoLoginPageState().visibilityButtionDone,
                child: Padding(
                  padding: const EdgeInsets.only(
                    left: 20,
                    bottom: 5,
                  ),
                  child: Align(
                    alignment: Alignment.bottomLeft,
                    child: TextButton(
                      onPressed: () {
                        setState(() {
                          _pageController.jumpToPage(5 - 1);
                        });
                      },
                      child: Text(
                        Strings.skip,
                        style: const TextStyle(
                          color: Color(0XFF7D818A),
                          fontFamily: 'ShabnamBold',
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ),
                  ),
                ),
              );
            }
            // UI for InitialState
            else {
              return Visibility(
                visible: InitialState().visibilityButtionDone,
                child: Padding(
                  padding: const EdgeInsets.only(
                    left: 20,
                    bottom: 5,
                  ),
                  child: Align(
                    alignment: Alignment.bottomLeft,
                    child: TextButton(
                      onPressed: () {
                        setState(() {
                          _pageController.jumpToPage(5 - 1);
                        });
                      },
                      child: Text(
                        Strings.skip,
                        style: const TextStyle(
                          color: Color(0XFF7D818A),
                          fontFamily: 'ShabnamBold',
                        ),
                        textAlign: TextAlign.center,
                      ),
                    ),
                  ),
                ),
              );
            }
          }),
          // دکمه بعدی
          BlocBuilder<IntroBloc, IntroState>(
            builder: (context, state) {
              // UI for InitialState
              if (state is InitialState) {
                return Visibility(
                  visible: InitialState().visibilityButtionNext,
                  child: Padding(
                    padding: const EdgeInsets.only(
                      right: 20,
                      bottom: 5,
                    ),
                    child: Align(
                      alignment: Alignment.bottomRight,
                      child: TextButton(
                        onPressed: () {
                          context
                              .read<IntroBloc>()
                              .add(ClickedNextButtonEvent());
                          _pageController.nextPage(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeIn);
                        },
                        child: Text(
                          Strings.next,
                          style: const TextStyle(
                            color: Color(0XFF7D818A),
                            fontFamily: 'ShabnamBold',
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                );
              }
              // UI for GoNextPageState
              if (state is GoNextPageState) {
                return Visibility(
                  visible: GoNextPageState().visibilityButtionNext,
                  child: Padding(
                    padding: const EdgeInsets.only(
                      right: 20,
                      bottom: 5,
                    ),
                    child: Align(
                      alignment: Alignment.bottomRight,
                      child: TextButton(
                        onPressed: () {
                          _pageController.nextPage(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeIn);
                        },
                        child: Text(
                          Strings.next,
                          style: const TextStyle(
                            color: Color(0XFF7D818A),
                            fontFamily: 'ShabnamBold',
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                );
              }
              // UI for GoEndPageState
              if (state is GoEndPageState) {
                return Visibility(
                  visible: GoEndPageState().visibilityButtionNext,
                  child: Padding(
                    padding: const EdgeInsets.only(
                      right: 20,
                      bottom: 5,
                    ),
                    child: Align(
                      alignment: Alignment.bottomRight,
                      child: TextButton(
                        onPressed: () {
                          _pageController.nextPage(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeIn);
                        },
                        child: Text(
                          Strings.next,
                          style: const TextStyle(
                            color: Color(0XFF7D818A),
                            fontFamily: 'ShabnamBold',
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                );
              }
              // UI for GoLoginPageState
              if (state is GoLoginPageState) {
                return Visibility(
                  visible: GoLoginPageState().visibilityButtionNext,
                  child: Padding(
                    padding: const EdgeInsets.only(
                      right: 20,
                      bottom: 5,
                    ),
                    child: Align(
                      alignment: Alignment.bottomRight,
                      child: TextButton(
                        onPressed: () {
                          _pageController.nextPage(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeIn);
                        },
                        child: Text(
                          Strings.next,
                          style: const TextStyle(
                            color: Color(0XFF7D818A),
                            fontFamily: 'ShabnamBold',
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                );
              }
              // UI for InitialState
              else {
                return Visibility(
                  visible: InitialState().visibilityButtionNext,
                  child: Padding(
                    padding: const EdgeInsets.only(
                      right: 20,
                      bottom: 5,
                    ),
                    child: Align(
                      alignment: Alignment.bottomRight,
                      child: TextButton(
                        onPressed: () {
                          _pageController.nextPage(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeIn);
                        },
                        child: Text(
                          Strings.next,
                          style: const TextStyle(
                            color: Color(0XFF7D818A),
                            fontFamily: 'ShabnamBold',
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                );
              }
            },
          ),=
          BlocBuilder<IntroBloc, IntroState>(
            builder: (context, state) {
              // UI for InitialState
              if (state is InitialState) {
                return Visibility(
                  visible: InitialState().visibilityButtionDone,
                  child: Padding(
                    padding: const EdgeInsets.only(
                      right: 20,
                      bottom: 5,
                    ),
                    child: Align(
                      alignment: Alignment.bottomRight,
                      child: TextButton(
                        onPressed: () {
                          _pageController.nextPage(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeIn);
                        },
                        child: Text(
                          Strings.done,
                          style: const TextStyle(
                            color: Color(0XFF7D818A),
                            fontFamily: 'ShabnamBold',
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                );
              }
              // UI for GoNextPageState
              if (state is GoNextPageState) {
                return Visibility(
                  visible: GoNextPageState().visibilityButtionDone,
                  child: Padding(
                    padding: const EdgeInsets.only(
                      right: 20,
                      bottom: 5,
                    ),
                    child: Align(
                      alignment: Alignment.bottomRight,
                      child: TextButton(
                        onPressed: () {
                          _pageController.nextPage(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeIn);
                        },
                        child: Text(
                          Strings.done,
                          style: const TextStyle(
                            color: Color(0XFF7D818A),
                            fontFamily: 'ShabnamBold',
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                );
              }
              // UI for GoEndPageState
              if (state is GoEndPageState) {
                return Visibility(
                  visible: GoEndPageState().visibilityButtionDone,
                  child: Padding(
                    padding: const EdgeInsets.only(
                      right: 20,
                      bottom: 5,
                    ),
                    child: Align(
                      alignment: Alignment.bottomRight,
                      child: TextButton(
                        onPressed: () {
                          _pageController.nextPage(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeIn);
                        },
                        child: Text(
                          Strings.done,
                          style: const TextStyle(
                            color: Color(0XFF7D818A),
                            fontFamily: 'ShabnamBold',
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                );
              }
              // UI for GoLoginPageState
              if (state is GoLoginPageState) {
                return Visibility(
                  visible: GoLoginPageState().visibilityButtionDone,
                  child: Padding(
                    padding: const EdgeInsets.only(
                      right: 20,
                      bottom: 5,
                    ),
                    child: Align(
                      alignment: Alignment.bottomRight,
                      child: TextButton(
                        onPressed: () {
                          _pageController.nextPage(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeIn);
                        },
                        child: Text(
                          Strings.done,
                          style: const TextStyle(
                            color: Color(0XFF7D818A),
                            fontFamily: 'ShabnamBold',
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                );
              }
              // UI for InitialState
              else {
                return Visibility(
                  visible: InitialState().visibilityButtionDone,
                  child: Padding(
                    padding: const EdgeInsets.only(
                      right: 20,
                      bottom: 5,
                    ),
                    child: Align(
                      alignment: Alignment.bottomRight,
                      child: TextButton(
                        onPressed: () {
                          _pageController.nextPage(
                              duration: const Duration(milliseconds: 300),
                              curve: Curves.easeIn);
                        },
                        child: Text(
                          Strings.done,
                          style: const TextStyle(
                            color: Color(0XFF7D818A),
                            fontFamily: 'ShabnamBold',
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ),
                    ),
                  ),
                );
              }
            },
          ),
        ],
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
  Widget introSlide({
    required String jsonAnimation,
    title,
    description,
  }) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        SizedBox(
          width: 250.0,
          height: 250.0,
          child: Lottie.asset(
            jsonAnimation,
            repeat: true,
          ),
        ),
        const SizedBox(
          height: 20,
        ),
        Text(
          title,
          style: const TextStyle(
            fontSize: 22,
            color: Color(0XFF0B0D0C),
            fontFamily: 'ShabnamBold',
          ),
          textAlign: TextAlign.center,
        ),
        const SizedBox(
          height: 10,
        ),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 40),
          child: Text(
            description,
            style: const TextStyle(
              fontSize: 16,
              color: Color(0XFF7D818A),
              fontFamily: 'ShabnamLight',
            ),
            textAlign: TextAlign.center,
          ),
        ),
      ],
    );
  }

  Widget _indicator(bool isActive) {
    return AnimatedContainer(
      duration: const Duration(milliseconds: 300),
      height: 10,
      width: isActive ? 40 : 10,
      margin: const EdgeInsets.only(right: 5),
      decoration: isActive
          ? BoxDecoration(
              color: const Color(0XFF1597E5),
              borderRadius: BorderRadius.circular(5),
            )
          : BoxDecoration(
              color: const Color(0XFF7D818A),
              borderRadius: BorderRadius.circular(5),
            ),
    );
  }

  List<Widget> _buildIndicator() {
    List<Widget> indicators = [];
    for (int i = 0; i < 5; i++) {
      if (currentIndex == i) {
        indicators.add(_indicator(true));
      } else {
        indicators.add(_indicator(false));
      }
    }
    return indicators;
  }
}
``
**Bloc**
``import 'package:dayan/events/intro_event/intro_event.dart';
import 'package:dayan/repositories/shared_prefs_repository/shared_prefs_repository.dart';
import 'package:dayan/states/intro_state/intro_state.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class IntroBloc extends Bloc<IntroEvent, IntroState> {
  final SharedPrefsRepository _sharedPrefsRepository = SharedPrefsRepository();
  IntroBloc(IntroState initialState) : super(initialState);

  @override
  Stream<IntroState> mapEventToState(IntroEvent event) async* {
    var isFirstTimeLaunch = await _sharedPrefsRepository.isFirstTimeLaunch();
    if (isFirstTimeLaunch == false) {
      yield GoLoginPageState();
    }
    if (event is ClickedNextButtonEvent) {
      yield GoNextPageState();
    }
    if (event is ClickedSkipButtonEvent) {
      _sharedPrefsRepository.setFirstTimeLaunch(false);
      yield GoLoginPageState();
    }
    if (event is ClickedDoneButtonEvent) {
      _sharedPrefsRepository.setFirstTimeLaunch(false);
      yield GoLoginPageState();
    }
  }
}
``

**State Bloc**
``import 'package:equatable/equatable.dart';

abstract class IntroState extends Equatable {}

class InitialState extends IntroState {
  final visibilityButtionSkip = true;
  final visibilityButtionNext = true;
  final visibilityButtionDone = false;
  @override
  // TODO: implement props
  List<Object?> get props => throw UnimplementedError();
}

class GoNextPageState extends IntroState {
  final visibilityButtionSkip = true;
  final visibilityButtionNext = true;
  final visibilityButtionDone = false;
  @override
  // TODO: implement props
  List<Object?> get props => throw UnimplementedError();
}

class GoEndPageState extends IntroState {
  final visibilityButtionSkip = false;
  final visibilityButtionNext = false;
  final visibilityButtionDone = true;
  @override
  // TODO: implement props
  List<Object?> get props => throw UnimplementedError();
}

class GoLoginPageState extends IntroState {
  final visibilityButtionSkip = false;
  final visibilityButtionNext = false;
  final visibilityButtionDone = true;
  @override
  // TODO: implement props
  List<Object?> get props => throw UnimplementedError();
}
``

**Event Bloc**
``import 'package:equatable/equatable.dart';

abstract class IntroEvent extends Equatable {}

class ClickedSkipButtonEvent extends IntroEvent {
  @override
  // TODO: implement props
  List<Object?> get props => throw UnimplementedError();
}

class ClickedDoneButtonEvent extends IntroEvent {
  @override
  // TODO: implement props
  List<Object?> get props => throw UnimplementedError();
}

class ClickedNextButtonEvent extends IntroEvent {
  @override
  // TODO: implement props
  List<Object?> get props => throw UnimplementedError();
}
``

**Comment by Devlonoah** [comment]
@tawasoli369 wrapping your call to bloc doesn't have to be in setState,
and you didn't specify the bloc type you are making reference to.

--❌---
```
setState(() {
context.read().add(ClickedNextButtonEvent());
currentIndex = page;
});
```

--✅--
`context.read<IntroBloc>().add(ClickedNextButtonEvent());`

you can even construct your Events to pass  your current index/page index to the bloc:
`context.read<IntroBloc>().add(ClickedNextButtonEvent(_currentIndex));`

I would suggest that you go through the official Bloc **[Website](https://bloclibrary.dev/#/)**  for more knowledge.
Kind regards.

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
