### ISSUE TITLE
AuthenticationUninitialized on first of IF statement not working

### ISSUE THREAD

**Issue by MahdiPishguy** [felangel/bloc#296]
hi @felangel thanks in advance to answer to my questions about implementing `bloC` pattenr

im `main.dart` we have this code:

```
builder: (BuildContext context, AuthenticationState state) {
  if (state is AuthenticationUninitialized) {
    return SplashPage();
  }
  if (state is AuthenticationAuthenticated) {
    return HomePage();
  }
  if (state is AuthenticationUnauthenticated) {
    return LoginPage(userRepository: _userRepository);
  }
  if (state is AuthenticationLoading) {
    return LoadingIndicator();
  }
},
```

when i run sample code part to of `if` statement run always, we dont have any database or `sharedpreferences` in that yet and my question is know why first part `if` statement not working although in `AuthenticationBloc` i use `SharedPreferences` and that return `false`, yield `AuthenticationUninitialized`, first `if` statement not working.

result in console:

```
Restarted application in 6,488ms.
I/flutter (18825): App Started
I/flutter (18825): appFreshInstallation : false
I/flutter (18825): Transition { currentState: Instance of 'AuthenticationUninitialized', event: App Started, nextState: AuthenticationUnAuthenticated }
```

`mapEventToState` in `AuthenticationBloc` class

```
  @override
  Stream<AuthenticationStates> mapEventToState(
      AuthenticationEvent event) async* {
    if (event is AppStarted) {

      final appFreshInstallation = await SFP.freshInstallationApplication();
      print("appFreshInstallation : "+appFreshInstallation.toString());

      if (appFreshInstallation) {
        yield AuthenticationUninitialized();
      } else {
        final bool userRegistered = await userRepository.isRegistered();
        if (userRegistered) {
          yield AuthenticationAuthenticated();
        } else {
          yield AuthenticationUnauthenticated();
        }
      }
    }

    ...
  }
```

`SFP` class as `SharedPreferences` helper

```
class SFP {
  static Future<bool> freshInstallationApplication() async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    return prefs.getBool('app_fresh_installed') ?? false;
  }
}
```

in fact after running `AuthenticationUninitialized` in `main.dart` other event as `AuthenticationUnauthenticated` yield automatically

**Comment by felangel** [comment]
Hi @MahdiPishguy 👋 
Thanks for opening an issue!

Can you please give a bit more detail about what the issue you're having is?
What do you expect to happen and what is happening? I'm not sure I understand.
Thanks! 👍

**Comment by MahdiPishguy** [comment]
ok. suresimply i want to show splash_screen page on fresh installation application by checking `app_fresh_installed` from `Shared preferences`if that return false then app in new installed on phone and i should show splash screen pageby my implementation and deploy your code i try to achive thatunfortunately on yield AuthenticationUninitialized to show splash screen, after that AuthenticationUnauthenticated automaticaly yield and login from show in screenhow can resolve this problem to show splash screen?thanks in advance

**Comment by felangel** [comment]
@MahdiPishguy isn't it because your appFreshInstallation boolean is false?
`I/flutter (18825): appFreshInstallation : false`

Shouldn't the implementation look like:

```dart
class SFP {
  static Future<bool> freshInstallationApplication() async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    return prefs.getBool('app_fresh_installed') ?? true; // default to true
  }
}
```

If it's your first time installing the app, shared preferences won't have anything so it will return null and before your default value was false.

Then you need to write to sharedPreferences to avoid having it always be true.
