### ISSUE TITLE
emit was called after an event handler completed normally.

### ISSUE THREAD

**Issue by savadmv** [felangel/bloc#2961]
### Code in Bloc class

```dart
 OtpOrPasswordBloc({
    required this.validator,
    required this.sendOtp,
  }) : super(Init()) {
    on<PickOtp>(_onPickOtp);
    on<PickPassword>(_onPicPassword);
  }
FutureOr<void> _onPickOtp(
      PickOtp event, Emitter<OtpOrPasswordState> emit) async {
    final phoneNumberValidate =
        validator.validatePhoneNumber(event.phoneNumber);

    phoneNumberValidate.fold(
        (failure) => emit(Error(message: INVALID_PHONE_NUMBER_FAILURE_MESSAGE)),
        (validData) async {
      emit(Loading());
      await Future.delayed(const Duration(seconds: 2));
      emit(OtpLogin(phoneNumber: '+9xx701xxxx80'));
    });
  }
```
### This is the log

> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:bloc/src/bloc.dart': Failed assertion: line 137 pos 7: '!_isCompleted': 
> E/flutter (28825): 
> E/flutter (28825): 
> E/flutter (28825): emit was called after an event handler completed normally.
> E/flutter (28825): This is usually due to an unawaited future in an event handler.
> E/flutter (28825): Please make sure to await all asynchronous operations with event handlers
> E/flutter (28825): and use emit.isDone after asynchronous operations before calling emit() to
> E/flutter (28825): ensure the event handler has not completed.
> E/flutter (28825): 
> E/flutter (28825):   **BAD**
> E/flutter (28825):   on<Event>((event, emit) {
> E/flutter (28825):     future.whenComplete(() => emit(...));
> E/flutter (28825):   });
> E/flutter (28825): 
> E/flutter (28825):   **GOOD**
> E/flutter (28825):   on<Event>((event, emit) async {
> E/flutter (28825):     await future.whenComplete(() => emit(...));
> E/flutter (28825):   });

**Comment by jeroen-meijer** [comment]
Thanks for submitting an issue!

I might be wrong here, so @felangel, feel free to correct me where applicable.

Because of the new API, bloc needs to know when an event handler performs async operations, and when these have completed. However, because the `phoneNumberValidate.fold` call is not `await`ed, the event handler completes _before_ the `emit(OtpLogin(...))` call happens.

You can try to fix this by making the `phoneNumberValidate.fold` async and `await`ing it.

```dart
// ...
await phoneNumberValidate.fold(
// ...
```

Let me know if this resolves the issue. Good luck! 👍🏻

**Comment by savadmv** [comment]
Can't do 
```dart 
await phoneNumberValidate.fold(
```
because that's not an async method 

```dart 
 final phoneNumberValidate =
        validator.validatePhoneNumber(event.phoneNumber);
```

Here is how the validator looks like 

```dart 
import 'package:dartz/dartz.dart';
import 'package:com_example_xxx/core/error/failure.dart';
 class InputValidator {
  Either<Failure, String> validatePhoneNumber(String str) {
    try {
      if (str.isEmpty) throw const FormatException();
      return Right(str);
    } on FormatException {
      return Left(InvalidPhoneNumberFailure());
    }
  }
}
```

**Comment by felangel** [comment]
@savadmv I believe you need to adjust the callbacks in fold to be async:

```dart
await phoneNumberValidate.fold(
        (failure) async => emit(Error(message: INVALID_PHONE_NUMBER_FAILURE_MESSAGE)),
        (validData) async {
      emit(Loading());
      await Future.delayed(const Duration(seconds: 2));
      emit(OtpLogin(phoneNumber: '+9xx701xxxx80'));
    });
```

Hope that helps 👍

**Comment by savadmv** [comment]
That does the trick. Thank you so much

**Comment by rohan20** [comment]
@savadmv Thanks for submitting this issue. I encountered the same issue.

I believe @jeroen-meijer's suggestion was spot on here. 

In your case, contrary to @felangel's reply, using `(failure) async ...` vs `(failure) ...` wouldn't make a difference because there's no `async` operation in the failure case. You're only emitting a simple synchronous state. (I see that you already had the `async` keyword for the success case `(validData) async { ... }`)

The actual solution is in fact the `await phoneNumberValidate.fold(...)` part regardless of `phoneNumberValidate.fold(...)` itself being `async` or not because the bloc finishes processing the event after `phoneNumberValidate.fold(...)` is called regardless of it `await`ing something in the success callback inside the `fold(...)` statement.

> Because of the new API, bloc needs to know when an event handler performs async operations, and when these have completed. However, because the phoneNumberValidate.fold call is not awaited, the event handler completes before the emit(OtpLogin(...)) call happens.

Spot on! Thanks @jeroen-meijer 🎉

**Comment by br-allstreet** [comment]
I am seeing the same issue, and can't seem to resolve it when following the advice in this thread. The issue comes up with using [Firebase's phone verification](https://firebase.flutter.dev/docs/auth/phone/#native-verifyphonenumber), which requires defining callbacks that I would like to emit() from.

```
  /// Sends the SMS code to the user's phone.
  Future<void> _onSendCodeToPhone(
    SignUpCodeSendCodeToPhoneEvent event,
    Emitter<SignUpCodeState> emit,
  ) async {
    final phoneNumber = Constants.disablePhoneNumberFormatting
        ? FlutterLibphonenumber().formatNumberSync(event.phoneNumber)
        : FlutterLibphonenumber().formatNumberSync('+1 ${event.phoneNumber}');

    await FirebaseAuth.instance.verifyPhoneNumber(
      phoneNumber: phoneNumber,
      verificationCompleted: (PhoneAuthCredential credential) async {
        await _authenticationRepository.signIn(credential);
      },
      verificationFailed: (FirebaseAuthException e) async {
        LogService().log.d('VERIFICATION FAILED: $e');
        emit(
          state.copyWith(
            formStatus: SubmissionFailed(exception: e),
          ),
        );
      },
      codeSent: (String verificationId, int? forceResend) async {
        emit(state.copyWith(verificationId: verificationId));
      },
      codeAutoRetrievalTimeout: (String verificationId) async {
        emit(state.copyWith(verificationId: verificationId));
      },
    );
  }
```

When the `codeSent` callback gets hit, it throws the error:

```
E/flutter (24885): emit was called after an event handler completed normally.
E/flutter (24885): This is usually due to an unawaited future in an event handler.
E/flutter (24885): Please make sure to await all asynchronous operations with event handlers
E/flutter (24885): and use emit.isDone after asynchronous operations before calling emit() to
E/flutter (24885): ensure the event handler has not completed.
E/flutter (24885): 
E/flutter (24885):   **BAD**
E/flutter (24885):   on<Event>((event, emit) {
E/flutter (24885):     future.whenComplete(() => emit(...));
E/flutter (24885):   });
E/flutter (24885): 
E/flutter (24885):   **GOOD**
E/flutter (24885):   on<Event>((event, emit) async {
E/flutter (24885):     await future.whenComplete(() => emit(...));
E/flutter (24885):   });
```

Any guidance would be much appreciated!

**Comment by felangel** [comment]
> I am seeing the same issue, and can't seem to resolve it when following the advice in this thread. The issue comes up with using [Firebase's phone verification](https://firebase.flutter.dev/docs/auth/phone/#native-verifyphonenumber), which requires defining callbacks that I would like to emit() from.
> 
> ```
>   /// Sends the SMS code to the user's phone.
>   Future<void> _onSendCodeToPhone(
>     SignUpCodeSendCodeToPhoneEvent event,
>     Emitter<SignUpCodeState> emit,
>   ) async {
>     await FirebaseAuth.instance.verifyPhoneNumber(
>       phoneNumber: event.phoneNumber,
>       verificationCompleted: (PhoneAuthCredential credential) async {
>         await _authenticationRepository.signIn(credential);
>       },
>       verificationFailed: (FirebaseAuthException e) async {
>         emit(
>           state.copyWith(
>             formStatus: SubmissionFailed(exception: e),
>           ),
>         );
>       },
>       codeSent: (String verificationId, int? forceResend) async {
>         emit(state.copyWith(verificationId: verificationId));
>       },
>       codeAutoRetrievalTimeout: (String verificationId) async {
>         emit(state.copyWith(verificationId: verificationId));
>       },
>     );
>   }
> ```
> 
> When the `codeSent` callback gets hit, it throws the error:
> 
> ```
> E/flutter (24885): emit was called after an event handler completed normally.
> E/flutter (24885): This is usually due to an unawaited future in an event handler.
> E/flutter (24885): Please make sure to await all asynchronous operations with event handlers
> E/flutter (24885): and use emit.isDone after asynchronous operations before calling emit() to
> E/flutter (24885): ensure the event handler has not completed.
> E/flutter (24885): 
> E/flutter (24885):   **BAD**
> E/flutter (24885):   on<Event>((event, emit) {
> E/flutter (24885):     future.whenComplete(() => emit(...));
> E/flutter (24885):   });
> E/flutter (24885): 
> E/flutter (24885):   **GOOD**
> E/flutter (24885):   on<Event>((event, emit) async {
> E/flutter (24885):     await future.whenComplete(() => emit(...));
> E/flutter (24885):   });
> ```
> 
> Any guidance would be much appreciated!

Are you able to share a link to a minimal reproduction sample?

**Comment by br-allstreet** [comment]
Like a full bloc, or a full app?

Not sure how easy it will be to get all the firebase setup you need here from a full app.

Looks like someone else is facing the same issue with the same library:
https://github.com/felangel/bloc/issues/2784#issuecomment-1000334746

**Comment by felangel** [comment]
> Like a full bloc, or a full app?
> 
> Not sure how easy it will be to get all the firebase setup you need here from a full app.
> 
> Looks like someone else is facing the same issue with the same library: [#2784 (comment)](https://github.com/felangel/bloc/issues/2784#issuecomment-1000334746)

Ideally a simple app with the least amount of code needed to reproduce the issue.

**Comment by br-allstreet** [comment]
Will need some time on that. In the meantime, I can avoid the issue by defining and an `InternalEvent` type that carries the data I need to emit in those callbacks and defining a handler for the `InternalEvent` which does the emitting.

In the firebase callbacks, I can successfully `add()` the events in the same spot where I cannot `emit()` states.

**Comment by savadmv** [comment]
Here _**verifyPhoneNumber**_ wont be waiting for its callback functions (i.e  **verificationCompleted**, **verificationFailed**)

Use   `Completer<OtpModel> c = Completer<SignUpCodeState>();`

in you case 

 ```
/// Sends the SMS code to the user's phone.


  Future<void> _onSendCodeToPhone(
    SignUpCodeSendCodeToPhoneEvent event,
    Emitter<SignUpCodeState> emit,
  ) async {
Completer<SignUpCodeState> c = Completer<SignUpCodeState>();
    await FirebaseAuth.instance.verifyPhoneNumber(
      phoneNumber: event.phoneNumber,
      verificationCompleted: (PhoneAuthCredential credential) async {
      ///TODO assign this to some state and use state listner to do this task 
        ///await _authenticationRepository.signIn(credential);
      },
      verificationFailed: (FirebaseAuthException e) async {
        c.complete(
          state.copyWith(
            formStatus: SubmissionFailed(exception: e),
          ),
        );
      },
      codeSent: (String verificationId, int? forceResend) async {
        c.complete(state.copyWith(verificationId: verificationId));
      },
      codeAutoRetrievalTimeout: (String verificationId) async {
        c.complete(state.copyWith(verificationId: verificationId));
      },
    );
var stateToRetern= c.future;
emit(state)
  }
```


Hope this helps

**Comment by ubaidillahSriyudi** [comment]
> 

i have the same issue, i tried that code but it seems still not work.
emit(state) was called immediately before the codeSent or verificationFailed completed

**Comment by ElieBamunoba** [comment]
hello, 
im having the same issue 

class PrescriptionBloc extends Bloc<PrescriptionEvent, PrescriptionState> {
  final PrescriptionRepository prescriptionRepository;
  late StreamSubscription _subscription;

  PrescriptionBloc({required PrescriptionRepository repository})
      : prescriptionRepository = repository,
        super(PrescriptionInitial()) {
    on<CheckPrescription>(_onPrescription);
  }

  void _onPrescription(
      CheckPrescription event, Emitter<PrescriptionState> emit) async {
    emit(PrescriptionLoading());

    _subscription =
        Stream.periodic(const Duration(seconds: 5)).listen((_) async {
      try {
        Map<String, dynamic> response = await prescriptionRepository
            .getPrescriptionStatus(prescriptionId: event.prescriptionId);
        if (int.parse(await response['status']) == 200) {
          _subscription.cancel();
          emit(PrescriptionSuccess(
              message: response['message'],
              prescriptionResponseList: response['prescriptionResponse']
                  as List<PrescriptionResponse>));
        }
      } catch (error) {
        _subscription.cancel();
        emit(const PrescriptionFailed(message: 'Kindly Refresh'));
      }
    });
  }

  @override
  Future<void> close() {
    _subscription.cancel();
    return super.close();
  }
}

**Comment by BAXMAY** [comment]
I do get the same error. Mine was
```dart
 SomeBloc() : super(Init()) {
    on<EventA>(_onA);
    on<EventB>(_onB);
  }
FutureOr<void> _onA(
      EventA event, Emitter<SomeState> emit) async {

    emit(Loading());

    anotherFunc(emit);
  }

void anotherFunc(Emitter<SomeState> emit) {

   final res = callApi();

   res.fold(
        (failure) => emit(SomeError()),
        (success) => emit(Loaded())
    });
}
```

And I solve this by putting the content of `anotherFunc` to `_onA`.

```dart
 SomeBloc() : super(Init()) {
    on<EventA>(_onA);
    on<EventB>(_onB);
  }
FutureOr<void> _onA(
      EventA event, Emitter<SomeState> emit) async {

    emit(Loading());

   final res = callApi();

   res.fold(
        (failure) => emit(SomeError()),
        (success) => emit(Loaded())
    });
}
```

Now it work. Don't know why it behave like this.

**Comment by sok-leaphea** [comment]
Hi pls also help me I also got that problem and I don't know how to solve it. Please help me
```
on<PhoneAuthEvent>((event,emit) async{
      emit(AuthLoadingState());
      try{
        await _firebaseAuth.verifyPhoneNumber(
            phoneNumber: event.phoneNumber,
            timeout: const Duration(seconds: 60),
            verificationCompleted: (PhoneAuthCredential credential) {

            },
            verificationFailed: (FirebaseAuthException e) {
              emit(AuthErrorState(e.message.toString()));
            },
            codeSent: (String verificationId, int? resendToken) {
              verificationID = verificationId;
              emit(AuthCodeSentState());
            },
            codeAutoRetrievalTimeout: (String verificationId) {
              verificationID = verificationId;
            },
        );
      } catch (e){
        emit(AuthErrorState(e.toString()));
      }
    });
````
Here the error message:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:bloc/src/emitter.dart': Failed assertion: line 114 pos 7: '!_isCompleted': 
E/flutter (25177): 
E/flutter (25177): emit was called after an event handler completed normally.
E/flutter (25177): This is usually due to an unawaited future in an event handler.
E/flutter (25177): Please make sure to await all asynchronous operations with event handlers
E/flutter (25177): and use emit.isDone after asynchronous operations before calling emit() to
E/flutter (25177): ensure the event handler has not completed.
E/flutter (25177): 
E/flutter (25177):   **BAD**
E/flutter (25177):   on<Event>((event, emit) {
E/flutter (25177):     future.whenComplete(() => emit(...));
E/flutter (25177):   });
E/flutter (25177): 
E/flutter (25177):   **GOOD**
E/flutter (25177):   on<Event>((event, emit) async {
E/flutter (25177):     await future.whenComplete(() => emit(...));
E/flutter (25177):   });
E/flutter (25177): 
E/flutter (25177): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (25177): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (25177): #2      _Emitter.call (package:bloc/src/emitter.dart:114:7)
E/flutter (25177): #3      new AuthBloc.<anonymous closure>.<anonymous closure> (package:masterstudy_app/presentation/bloc/auth/auth_bloc.dart:56:19)
E/flutter (25177): #4      MethodChannelFirebaseAuth.verifyPhoneNumber.<anonymous closure> (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:626:19)
E/flutter (25177): #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (25177): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (25177): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (25177): #8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter (25177): #9      _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
E/flutter (25177): #10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter (25177): #11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (25177): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (25177): #13     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
E/flutter (25177): #14     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
E/flutter (25177): #15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
E/flutter (25177): #16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (25177): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (25177): 
```

**Comment by dhruvanbhalara** [comment]
> Hi pls also help me I also got that problem and I don't know how to solve it. Please help me
> 
> ```
> on<PhoneAuthEvent>((event,emit) async{
>       emit(AuthLoadingState());
>       try{
>         await _firebaseAuth.verifyPhoneNumber(
>             phoneNumber: event.phoneNumber,
>             timeout: const Duration(seconds: 60),
>             verificationCompleted: (PhoneAuthCredential credential) {
> 
>             },
>             verificationFailed: (FirebaseAuthException e) {
>               emit(AuthErrorState(e.message.toString()));
>             },
>             codeSent: (String verificationId, int? resendToken) {
>               verificationID = verificationId;
>               emit(AuthCodeSentState());
>             },
>             codeAutoRetrievalTimeout: (String verificationId) {
>               verificationID = verificationId;
>             },
>         );
>       } catch (e){
>         emit(AuthErrorState(e.toString()));
>       }
>     });
> ```
> 
> Here the error message:
> 
> ```
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:bloc/src/emitter.dart': Failed assertion: line 114 pos 7: '!_isCompleted': 
> E/flutter (25177): 
> E/flutter (25177): emit was called after an event handler completed normally.
> E/flutter (25177): This is usually due to an unawaited future in an event handler.
> E/flutter (25177): Please make sure to await all asynchronous operations with event handlers
> E/flutter (25177): and use emit.isDone after asynchronous operations before calling emit() to
> E/flutter (25177): ensure the event handler has not completed.
> E/flutter (25177): 
> E/flutter (25177):   **BAD**
> E/flutter (25177):   on<Event>((event, emit) {
> E/flutter (25177):     future.whenComplete(() => emit(...));
> E/flutter (25177):   });
> E/flutter (25177): 
> E/flutter (25177):   **GOOD**
> E/flutter (25177):   on<Event>((event, emit) async {
> E/flutter (25177):     await future.whenComplete(() => emit(...));
> E/flutter (25177):   });
> E/flutter (25177): 
> E/flutter (25177): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
> E/flutter (25177): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
> E/flutter (25177): #2      _Emitter.call (package:bloc/src/emitter.dart:114:7)
> E/flutter (25177): #3      new AuthBloc.<anonymous closure>.<anonymous closure> (package:masterstudy_app/presentation/bloc/auth/auth_bloc.dart:56:19)
> E/flutter (25177): #4      MethodChannelFirebaseAuth.verifyPhoneNumber.<anonymous closure> (package:firebase_auth_platform_interface/src/method_channel/method_channel_firebase_auth.dart:626:19)
> E/flutter (25177): #5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
> E/flutter (25177): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
> E/flutter (25177): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
> E/flutter (25177): #8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
> E/flutter (25177): #9      _HandleErrorStream._handleData (dart:async/stream_pipe.dart:253:10)
> E/flutter (25177): #10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
> E/flutter (25177): #11     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
> E/flutter (25177): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
> E/flutter (25177): #13     _DelayedData.perform (dart:async/stream_impl.dart:515:14)
> E/flutter (25177): #14     _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
> E/flutter (25177): #15     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
> E/flutter (25177): #16     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
> E/flutter (25177): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
> E/flutter (25177): 
> ```

Hi @sok-leaphea,
try this solution it worked for me: https://github.com/felangel/bloc/issues/2961#issuecomment-1025144654
