### ISSUE TITLE
Android Studio bloc generator extension does not focus on the extension dialog

### ISSUE THREAD

**Issue by schatekar** [felangel/bloc#298]
The bloc generator extension for Android Studio does not focus on the text field of the extension dialog

**To Reproduce**
1. Click on Bloc Genrator -> New Bloc which brings up the New Bloc dialog
2. Start typing the name of the bloc
3. Nothing happens because the text box for the name of the bloc is not in focus

**Comment by felangel** [comment]
Fixed in #302 and will be in v1.4 in the next few days 👍
