### ISSUE TITLE
question: StateError

### ISSUE THREAD

**Issue by DenisBogatirov** [felangel/bloc#2980]
**Description**
In 8.0.0 if bloc is closed both `emit` and `add` throws `StateError`. In Merge Request is mentioned [2261](https://github.com/felangel/bloc/issues/2261) which refers to [1236](https://github.com/felangel/bloc/issues/1236) and [2912](https://github.com/felangel/bloc/pull/2912). I'm on the side of last two, because most happening case is `Future` resolved after bloc is closed.

For example is started inside bloc, user goes away from the screen before `Future` is resolved and bloc is closed now. When `Future` is resolved it calls emit which results in `StateError`.

So my questions how to properly handle this case, because `Future`s cannot be canceled?
Just adding if `(isClosed)` before each of my emit in every bloc seem's like a lot of code, and overriding `emit` is not an options since it's an argument of event handler

**Steps To Reproduce**

1. Go to Page with Bloc on it
2. Trigger event with Future in it
3. Leave the Page before Future is resolved
4. See StateError

**Additional Context**
I've started using BLoC instead of Provider because Provider was getting error about it being updated after dispose.

**Comment by felangel** [comment]
Hi @DenisBogatirov 👋 
Thanks for opening an issue!

Can you please provide a minimal reproduction sample that illustrates the scenario you are describing? Thanks!

**Comment by DenisBogatirov** [comment]
Hi, @felangel here is example code:

App starts with home screen, user navigates to other screen and navigates back with app bar icon before! future is resolved.

home_screen.dart
```
class HomeScreen extends StatefulWidget {
  static const String _routeName = '/';

  static Route<HomeScreen> getRoute() {
    return MaterialPageRoute(
      settings: const RouteSettings(name: _routeName),
      builder: (context) => const HomeScreen(),
    );
  }

  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      body: SafeArea(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            ElevatedButton(
              onPressed: () {
                Navigator.of(context).push(OtherScreen.getRoute());
              },
              child: const Text('Go to other'),
            ),
          ],
        ),
      ),
    );
  }
}
```

other_screen.dart
```
class OtherScreen extends StatelessWidget {
  static const String _routeName = '/other';

  static Route<OtherScreen> getRoute() {
    return MaterialPageRoute(
      settings: const RouteSettings(name: _routeName),
      builder: (context) =>
          BlocProvider(
            create: (_) =>
            OtherCubit()..mockFuture(),
            child: const OtherScreen(),
          ),
    );
  }

  const OtherScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<OtherCubit, OtherState>(
      builder: (context, state) {
        final isLoading = state is OtherLoading;

        Widget child = const Text('OTHER');

        if (isLoading) {
          child = const CircularProgressIndicator();
        }

        return Scaffold(
          appBar: AppBar(
            title: const Text('Other'),
          ),
          body: SafeArea(
            child: Center(
              child: child,
            ),
          ),
        );
      },
    );
  }
}
```

other_cubit.dart
```
@immutable
abstract class OtherState {}

class OtherIdle extends OtherState {}
class OtherLoading extends OtherState {}

class OtherCubit extends Cubit<OtherState> {
  OtherCubit() : super(OtherIdle());

  Future<void> mockFuture() async {
    emit(OtherLoading());

    await Future.delayed(const Duration(seconds: 10));

    emit(OtherIdle());
  }
}
```

**Comment by DenisBogatirov** [comment]
@felangel Any news or ideas?

**Comment by felangel** [comment]
@DenisBogatirov I opened a feature request https://github.com/felangel/bloc/issues/3069. Would love your feedback/thoughts, thanks! 🙏

**Comment by felangel** [comment]
Closing this as it's being tracked by #3069
