### ISSUE TITLE
feat: Add @visibleForTesting

### ISSUE THREAD

**Issue by pr0gramista** [felangel/bloc#2981]
**Description**
I don't use `blocTest` much so I often emit state as the first step in my tests. Previously that wasn't an issue but since bloc 8.0.0 has new annotations that limit the scope the analyzer is not happy.

It is not like `blocTest` is doing anything better in that regard. It's just that the ignore line for analyzer is in single place: https://github.com/felangel/bloc/blob/774d1c1733acd9a01b544b6f79813518361c0169/packages/bloc_test/lib/src/bloc_test.dart#L197

**Desired Solution**
Add `@visibleForTesting` for emit and probably onEvent etc. methods. This will make the analyzer happy again.

However, one place that this change won't work is in `Bloc` instances, because Bloc class overrides `emit` as `@internal` and from my tests, it seems that `@visibleForTesting` doesn't work for internal methods.

**Alternatives Considered**
I could just add `// ignore_for_file: invalid_use_of_protected_member` to each file.

**Additional Context**
I wanted to make the PR, but I am not sure this is the right solution, though I think it is important to give people an indication of such a problem so they don't just disable analysis entirely 😄

**Comment by felangel** [comment]
Hi @pr0gramista 👋 
Thanks for opening an issue!

Is there any particular reason why you prefer not to use bloc_test? Thanks!

**Comment by eimantas1998** [comment]
Is it correct behaviour to use act: bloc.emit(), while using bloc tests? If not what would be a correct way to do this?
Example:
```

blocTest<CounterBloc, int>(
  'emits [2] when increment is added',
  build: () => CounterBloc()..emit(1),
  act: (bloc) => bloc.add(CounterEvent.increment),
  expect: const <int>[2],
);

```
Since after upgrading to bloc 8.0.0 emit shows (The member 'emit' can only be used within its package.) lint warning.

**Comment by narcodico** [comment]
Hi @eimantas1998 👋

Proper way to seed a specific state is by using the `seed` property:

```
blocTest<CounterBloc, int>(
  'emits [2] when increment is added',
  build: () => CounterBloc(),
  seed: () => 2,
  act: (bloc) => bloc.add(CounterEvent.increment),
  expect: const <int>[2],
);
```

**Comment by pr0gramista** [comment]
> Hi @pr0gramista 👋 Thanks for opening an issue!
> 
> Is there any particular reason why you prefer not to use bloc_test? Thanks!

Hey, I think the main reason is the added complexity of the tests. I want my tests to be dead simple and while blocTest gives a nice skeleton for the tests I wouldn't call it easy to understand, especially for newcomers who just started to learn about async/Streams.

Expect clause is a good example.

Often I want to check a single property of the state. While it is possible to do that with `having` or 'predicate' I like the simplicity of just using multiple expect clauses.

Compare
```
.having(
  (w) => w.weather,
  'weather',
  isA<Weather>()
      .having((w) => w.lastUpdated, 'lastUpdated', isNotNull)
      .having((w) => w.condition, 'condition', weatherCondition)
      .having(
        (w) => w.temperature,
        'temperature',
        Temperature(value: weatherTemperature.toFahrenheit()),
      )
      .having((w) => w.location, 'location', weatherLocation),
),
```
to something like
```
expect(bloc.state.weather.lastUpdated, isNotNull);
expect(bloc.state.weather.condition, weatherCondition);
expect(bloc.state.weather.temperature, Temperature(value: weatherTemperature.toFahrenheit()));
expect(bloc.state.weather.location, weatherLocation);
```
while the 1st structure probably gives better test output I like how the 2nd option is just easier to make.

Another thing is that expect clause checks only the observed state, which is mostly a good thing, but in my imperfect app, I sometimes had to check another thing as well. I know I could use predicate matchers, but that's again - complexity.

I like how the other comment in this thread somewhat shows what I mean 😄

Anyway, I don't have much against using bloc_test. Thanks! 💙

**Comment by felangel** [comment]
@pr0gramista I reverted the change to annotate `emit` as `internal` and kept it as `visibleForTesting`. Can you please verify that the changes in #2982 will address the issues you're facing?
