### ISSUE TITLE
Append new bloc to the existing barrel file when generating bloc code using Android Studio extension, 

### ISSUE THREAD

**Issue by schatekar** [felangel/bloc#299]
The Android Studio Bloc Generator extension tries to create a new `bloc.dart` file for every new bloc you try to add. It would be good if the exports for the new blocs can be added to the existing `block.dart` file. 

This will also make it easy to import a single file no matter which bloc you are interested in.

**Comment by mainawycliffe** [comment]
So, ideally the extension should prompt you for an export file (block.dart) path or have some default config of some sorts?

**Comment by felangel** [comment]
@mainawycliffe I think the extension should just add the new bloc to the existing bloc.dart file so long as the new bloc name doesn’t conflict with the existing bloc names

**Comment by felangel** [comment]
Published in v1.5 🎉
