### ISSUE TITLE
Unhandled Exception: Bad state occured after upgrade to v8.0.0

### ISSUE THREAD

**Issue by alexaung** [felangel/bloc#2993]
**Description**
Unhandled Exception: Bad state: add(GetMonksEvent) was called without a registered event handler.
E/flutter (10526): Make sure to register a handler via on<GetMonksEvent>((event, emit) {...})

Upgrade from v7.3.3 to 8.0.0

**Steps To Reproduce**
`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Preferences.init();
  await setupServiceLocator();
  await FlutterDownloader.initialize(debug: true);
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent, // transparent status bar
  ));
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(
          create: (context) => ThemeBloc(),
        ),
        BlocProvider(
          create: (context) =>
              MonkBloc(monkRespository: MonkRespository(MonkApiProvider())),
        ),
        BlocProvider(
          create: (context) =>
              AlbumBloc(albumRespository: AlbumRespository(AlbumApiProvider())),
        ),
        BlocProvider(
          create: (context) =>
              SongBloc(songRespository: SongRespository(SongApiProvider())),
        ),
        BlocProvider(
          create: (context) =>
              EbookBloc(eBookRespository: EbookRespository(EbookApiProvider())),
        ),
        BlocProvider(
          create: (context) => ChantingBloc(
              chantingRespository: ChantingRespository(ChantingApiProvider())),
        ),
        BlocProvider(
          create: (context) => AppointmentBloc(
              appointmentRespository:
                  AppointmentRespository(AppointmentApiProvider())),
        ),
        BlocProvider(
          create: (context) => AboutBloc(
              aboutRespository:
                  AboutRespository(AboutApiProvider())),
        ),
        BlocProvider(
          create: (context) => PlayerBloc(),
        ),
        BlocProvider(
          create: (context) =>
              FavouriteBloc(favouriteRepository: FavouriteRepository()),
        ),
        
        BlocProvider(
          create: (context) => FavouriteSongListBloc(
              favouriteSongRespository: FavouriteSongRepository()),
        ),
        BlocProvider(
          create: (context) => FavouriteSongBloc(
              favouriteSongRepository: FavouriteSongRepository()),
        ),
        BlocProvider(
          create: (context) => DownloadedEbookBloc(
              ebookRepository: DownloadedEbookRepository()),
        ),
      ],
      child: BlocBuilder<ThemeBloc, ThemeState>(
        builder: (BuildContext context, ThemeState themeState) {
          initializeDateFormatting('my_MM');
          return MaterialApp(
            debugShowCheckedModeBanner: false,
            title: 'Thitsarparami',
            theme: themeState.themeData,
            // home: const HomeScreen(),
            initialRoute: '/',
            routes: routes,
          );
        },
      ),
    );
  }
}`
`class MonkBloc extends Bloc<MonkEvent, MonkState> {
  final MonkRespository monkRespository;
  late List<Monk> monks;

  MonkBloc({required this.monkRespository}) : super(MonkInitial());

  @override
  Stream<MonkState> mapEventToState(MonkEvent event) async* {
    yield MonkLoading();
    if (event is GetMonksEvent) {
      try {
        final List<Monk> monks = await monkRespository.fetchMonks();
        yield MonkLoaded(monks: monks);
      } catch (e) {
        yield MonkError(error: (e.toString()));
      }
    }
    if (event is MonkSearchEvent) {
      try {
        final List<Monk> monks = await monkRespository.searchMonks(event.query);
        yield MonkLoaded(monks: monks);
      } catch (e) {
        yield MonkError(error: (e.toString()));
      }
    }
  }
}`

`_loadMonks() async {
    BlocProvider.of<MonkBloc>(context).add(const GetMonksEvent());
  }

  @override
  void initState() {
    super.initState();
    _loadMonks();
  }`

**Expected Behavior**
Event does not trigger. It was showing list of monks but now got error after upgrade to version 8

**Comment by alexaung** [comment]
After I read the documentation, then I know that  I need to migrate mapEventToState to on<Event>. After that I don't get an error but state is not trigger. Here is my code. Is there anything I miss out?

    `class MonkBloc extends Bloc<MonkEvent, MonkState> {
          final MonkRespository monkRespository;
          late List<Monk> monks;

         MonkBloc({required this.monkRespository}) : super(MonkInitial()) {
             on<GetMonksEvent>((event, emit) => _getMonks(emit));
             on<MonkSearchEvent>((event, emit) => _searchMonks(event.query, emit));
        }

        Stream<MonkState> _getMonks(Emitter<MonkState> emit) async* {
             yield MonkLoading();
            try {
                  final List<Monk> monks = await monkRespository.fetchMonks();
                  yield MonkLoaded(monks: monks);
            } catch (e) {
            yield MonkError(error: (e.toString()));
        }
       }

       Stream<MonkState> _searchMonks(String query, Emitter<MonkState> emit) async* {
           yield MonkLoading();
           try {
                final List<Monk> monks = await monkRespository.searchMonks(query);
                yield MonkLoaded(monks: monks);
           } catch (e) {
                yield MonkError(error: (e.toString()));
          }
      }
      }`

     `class MonkScreen extends StatefulWidget {
          static const routeName = '/monk';
          final String? title;
          final MonkScreenMode? screenMode;
         const MonkScreen({Key? key, this.title, this.screenMode}) : super(key: key);

         @override
         State<MonkScreen> createState() => _MonkScreenState();
     }

      class _MonkScreenState extends State<MonkScreen> {
      
           _loadMonks() async {
                 BlocProvider.of<MonkBloc>(context).add(const GetMonksEvent());
          }

           @override
            void initState() {
              super.initState();
             _loadMonks();
             }

            @override
            Widget build(BuildContext context) {
                    return BaseWidget(
                           child: Scaffold(
                                     backgroundColor: Theme.of(context).backgroundColor,
                                      
                          body: BlocBuilder<MonkBloc, MonkState>(
                          builder: (BuildContext context, MonkState monkState) {
                           if (monkState is MonkError) {
                                return const SomethingWentWrongScreen();
                           } else if (monkState is MonkLoaded) {
                                 return listViewBuilder(
                                    context, monkState.monks, widget.screenMode!);
                             }
                           return const Center(
                              child: CircularProgressIndicator(),
                           );
                           },
                         ),
                         ),
                   );
              }
                }`

**Comment by ngtrongha** [comment]
`abstract class CounterEvent {}
class Increment extends CounterEvent {}
class Decrement extends CounterEvent {}

class CounterBloc extends Bloc<CounterEvent, int> {
  CounterBloc() : super(0) {
    on<Increment>(_onIncrement);
    on<Decrement>(_onDecrement);
  }

  void _onIncrement(Increment event, Emitter<int> emit) {
    emit(state + 1);
  }

  void _onDecrement(Decrement event, Emitter<int> emit) {
    emit(state - 1);
  }
}
`
[link](https://github.com/felangel/bloc/issues/2526)

**Comment by alexaung** [comment]
@ngtrongha I think I did same thing and follow the link that you share. My question is that what I am missing?

**Comment by ngtrongha** [comment]
> @ngtrongha I think I did same thing and follow the link that you share. My question is that what I am missing?

Steam => void
Yield => emit(state)

See code change bro. I tried it and it works fine

**Comment by alexaung** [comment]
@ngtrongha here is working code. Thanks for reply.

class MonkBloc extends Bloc<MonkEvent, MonkState> {
  final MonkRespository monkRespository;
  late List<Monk> monks;

  MonkBloc({required this.monkRespository}) : super(MonkInitial()) {
    on<GetMonksEvent>((event, emit) async {
      await _getMonks(emit);
    });
    on<MonkSearchEvent>((event, emit) async {
      await _searchMonks(event.query, emit);
    });
  }

  Future<void> _getMonks(Emitter<MonkState> emit) async {
    emit(MonkLoading());
    try {
      final List<Monk> monks = await monkRespository.fetchMonks();
      emit(MonkLoaded(monks: monks));
    } catch (e) {
      emit (MonkError(error: (e.toString())));
    }
  }

  Future<void> _searchMonks(String query, Emitter<MonkState> emit) async {
    emit(MonkLoading());
    try {
      final List<Monk> monks = await monkRespository.searchMonks(query);
      emit(MonkLoaded(monks: monks));
    } catch (e) {
      emit(MonkError(error: (e.toString())));
    }
  }
}
