### ISSUE TITLE
refactor: аdding interfaces

### ISSUE THREAD

**Issue by PlugFox** [felangel/bloc#2994]
Why does the entire **architectural** library still lack a interfaces?
Whats about `Dependency inversion principle` and `interface segregation principle`?

Why `BlocBuilder` depends on `BlocBase` and not on `IStateObservable` something like this:
```dart
/// {@template i_state_observable}
/// An interface to observe states stream.
/// Current [state] available as property.
/// State subject to implement the Observer (Dependents) pattern
/// {@endtemplate}
abstract class IStateObservable<T extends Object?> {
  /// The current [state].
  T get state;

  /// The state stream.
  StateStream<T> get stream;
}
```
`BlocBuilder`, `BlocListener`, `BlocProvider`, `BlocConsumer` really needs `addError`, `emit`, `onChange`, `onError` and others methods and callbacks?

Also you need something like this:
```dart
/// {@template i_bloc_subject}
/// Interface to observe states stream.
/// Current [state] available as property.
/// [Bloc] Subject to implement the Publisher/Subscriber pattern
/// {@endtemplate}
abstract class IBlocSubject<State extends Object?>
    implements IStateObservable<State> {
  /// Updates the [state] to the provided [state].
  /// [setState] does nothing if the instance has been closed.
  @protected
  @mustCallSuper
  void setState(State state);

  /// Called whenever a [change] occurs with the given [change].
  /// A [change] occurs when a new `state` is emitted.
  /// [onChange] is called before the `state` of the `bloc` is updated.
  /// [onChange] is a great spot to add logging/analytics for a specific `bloc`.
  ///
  /// **Note: `super.onChange` should always be called first.**
  /// ```dart
  /// @override
  /// void onChange(Change change) {
  ///   // Always call super.onChange with the current change
  ///   super.onChange(change);
  ///
  ///   // Custom onChange logic goes here
  /// }
  /// ```
  ///
  /// See also:
  ///
  /// * [IBlocObserver] for observing [Bloc] behavior globally.
  @protected
  @mustCallSuper
  @visibleForOverriding
  void onChange(Change<State> change);
}

/// {@template i_bloc_sink}
/// A [Bloc] Sink interface that accepts events both synchronously
/// and asynchronously.
///
/// The [IBlocSink] methods can't be used while the [addStream] is called.
/// As soon as the [addStream]'s [Future] completes with a value, the
/// [EventSink] methods can be used again.
///
/// If [addStream] is called after any of the [EventSink] methods, it'll
/// be delayed until the underlying system has consumed the data added by the
/// [EventSink] methods.
///
/// When [EventSink] methods are used, the [done] [Future] can be used to
/// catch any errors.
///
/// When [close] is called, it will return the [done] [Future].
/// {@endtemplate}
abstract class IBlocSink<Event extends Object?> implements StreamSink<Event> {
  /// Reports an [error] which triggers [onError] with an optional [StackTrace].
  /// If [close] has already been called, any subsequent calls to [addError]
  /// will be ignored and will not result in any subsequent state changes.
  @override
  @protected
  @mustCallSuper
  void addError(Object error, [StackTrace? stackTrace]);

  /// Notifies the [Bloc] of a new [event]
  /// If [close] has already been called, any subsequent calls to [add] will
  /// be ignored and will not result in any subsequent state changes.
  @override
  void add(Event event);

  /// Called whenever an [event] is [add]ed to the [Bloc].
  /// A great spot to add logging/analytics at the individual [Bloc] level.
  ///
  /// **Note: `super.onEvent` should always be called first.**
  /// ```dart
  /// @override
  /// void onEvent(Event event) {
  ///   // Always call super.onEvent with the current event
  ///   super.onEvent(event);
  ///
  ///   // Custom onEvent logic goes here
  /// }
  /// ```
  ///
  /// See also:
  ///
  /// * [IBlocObserver.onEvent] for observing events globally.
  ///
  @protected
  @mustCallSuper
  @visibleForOverriding
  void onEvent(Event event);

  /// Called whenever an [error] occurs and notifies [IBlocObserver.onError].
  ///
  /// In debug mode, [onError] throws a [BlocUnhandledErrorException] for
  /// improved visibility.
  ///
  /// In release mode, [onError] does not throw and will instead only report
  /// the error to [IBlocObserver.onError].
  ///
  /// **Note: `super.onError` should always be called last.**
  /// ```dart
  /// @override
  /// void onError(Object error, StackTrace stackTrace) {
  ///   // Custom onError logic goes here
  ///
  ///   // Always call super.onError with the current error and stackTrace
  ///   super.onError(error, stackTrace);
  /// }
  /// ```
  @protected
  @mustCallSuper
  @visibleForOverriding
  void onError(Object error, StackTrace stackTrace);

  /// Closes the `event` and `state` `Streams`.
  /// This method should be called when a [Bloc] is no longer needed.
  /// Once [close] is called, `events` that are [add]ed will not be
  /// processed.
  /// In addition, if [close] is called while `events` are still being
  /// processed, the [Bloc] will finish processing the pending `events`.
  @override
  @mustCallSuper
  @visibleForOverriding
  Future<void> close();

  /// Pass all [eventStream] events to the [Bloc]
  /// If [close] has already been called, any subsequent calls to [addStream]
  /// will be ignored and will not result in any subsequent state changes.
  @override
  Future<void> addStream(Stream<Event> eventStream);

  /// Return a future which is completed when the [IBlocSink] is finished.
  ///
  /// If the `IBlocSink` fails with an error,
  /// perhaps in response to adding events using [add], [addStream], [addError]
  /// or [close], the [done] future will complete with that error.
  ///
  /// Otherwise, the returned future will complete when either:
  ///
  /// * all events have been processed and the sink has been closed, or
  /// * the sink has otherwise been stopped from handling more events
  ///   (for example by canceling a stream subscription).
  @override
  Future<void> get done;
}

/// {@template i_bloc}
/// An interface to implement the Publisher/Subscriber pattern for [Bloc].
/// Takes a `Stream` of `Events` as input
/// and transforms them into a `Stream` of `States` as output.
/// {@endtemplate}
abstract class IBloc<Event extends Object?, State extends Object?>
    implements IBlocSink<Event>, IBlocSubject<State> {
  /// Transforms the [events] stream along with a [transitionFn] function into
  /// a `Stream<Transition>`.
  /// Events that should be processed by [mapEventToState] need to be passed to
  /// [transitionFn].
  /// By default `asyncExpand` is used to ensure all [events] are processed in
  /// the order in which they are received.
  /// You can override [transformEvents] for advanced usage in order to
  /// manipulate the frequency and specificity with which [mapEventToState] is
  /// called as well as which [events] are processed.
  ///
  /// For example, if you only want [mapEventToState] to be called on the most
  /// recent [Event] you can use `switchMap` instead of `asyncExpand`.
  ///
  /// ```dart
  /// @override
  /// Stream<Transition<Event, State>> transformEvents(events, transitionFn) {
  ///   return events.switchMap(transitionFn);
  /// }
  /// ```
  ///
  /// Alternatively, if you only want [mapEventToState] to be called for
  /// distinct [events]:
  ///
  /// ```dart
  /// @override
  /// Stream<Transition<Event, State>> transformEvents(events, transitionFn) {
  ///   return super.transformEvents(
  ///     events.distinct(),
  ///     transitionFn,
  ///   );
  /// }
  /// ```
  @visibleForOverriding
  Stream<Transition<Event, State>> transformEvents(
    Stream<Event> events,
    TransitionFunction<Event, State> transitionFn,
  );

  /// Must be implemented when a class extends [Bloc].
  /// [mapEventToState] is called whenever an [event] is [add]ed
  /// and is responsible for converting that [event] into a new [state].
  /// [mapEventToState] can `yield` zero, one, or multiple states for an event.
  @protected
  @visibleForOverriding
  Stream<State> mapEventToState(Event event);

  /// Called whenever a [transition] occurs with the given [transition].
  /// A [transition] occurs when a new `event` is [add]ed and [mapEventToState]
  /// executed.
  /// [onTransition] is called before a [Bloc]'s [state] has been updated.
  /// A great spot to add logging/analytics at the individual [Bloc] level.
  ///
  /// **Note: `super.onTransition` should always be called first.**
  /// ```dart
  /// @override
  /// void onTransition(Transition<Event, State> transition) {
  ///   // Always call super.onTransition with the current transition
  ///   super.onTransition(transition);
  ///
  ///   // Custom onTransition logic goes here
  /// }
  /// ```
  ///
  /// See also:
  ///
  /// * [IBlocObserver.onTransition] for observing transitions globally.
  ///
  @protected
  @mustCallSuper
  @visibleForOverriding
  void onTransition(Transition<Event, State> transition);

  /// Transforms the `Stream<Transition>` into a new `Stream<Transition>`.
  /// By default [transformTransitions] returns
  /// the incoming `Stream<Transition>`.
  /// You can override [transformTransitions] for advanced usage in order to
  /// manipulate the frequency and specificity at which `transitions`
  /// (state changes) occur.
  ///
  /// For example, if you want to debounce outgoing state changes:
  ///
  /// ```dart
  /// @override
  /// Stream<Transition<Event, State>> transformTransitions(
  ///   Stream<Transition<Event, State>> transitions,
  /// ) {
  ///   return transitions.debounceTime(Duration(seconds: 1));
  /// }
  /// ```
  @protected
  @visibleForOverriding
  Stream<Transition<Event, State>> transformTransitions(
    Stream<Transition<Event, State>> transitions,
  );
}
```

and much more, like `ISink`, `IDisposal`, `ITransition`, `IChange`, `IEventConsumer`, `IStateEmiter`.

**Comment by felangel** [comment]
Hi @PlugFox 👋 
Thanks for opening an issue!

Can you provide more context? I don’t understand what you’re trying to achieve. In Dart all classes are interfaces so I’m not sure what the benefit would be of defining a bunch of additional C style interfaces. See https://dart.dev/guides/language/language-tour#implicit-interfaces.

**Comment by purplenoodlesoop** [comment]
I would hop in with this issue because I very much agree with most of the points that @PlugFox stated in his original message. 

> I don’t understand what you’re trying to achieve. In Dart all classes are interfaces so I’m not sure what the benefit would be of defining a bunch of additional C style interfaces. See https://dart.dev/guides/language/language-tour#implicit-interfaces.

@PlugFox can correct me if I distort their message by accident, but I think that we are mostly talking about two techniques and principles from the SOLID acronym, letters I and D. Currently, those principles are not followed, there are no use-case-specific interfaces and a lot of code depends on concrete implementations, and not abstractions. 

Because of that, it is not possible to provide your own implementations of only needed parts that need to be reimplemented for any reason, and the code is unnecessarily coupled.

Moreover, because the *Interface segregation principle* is not followed, even the internal parts of the library have too much control of the obtained entities. 

For example, the BlocBuilder expects the `BlocBase`. The `BlocBuilder` has one main purpose and two sub-purposes

* Display a widget based on Bloc's state.
    * Apply conditions on displaying using a predicate.
    * Locate a Bloc of a given type if it was not passed in a `bloc` argument of the constructor.
    
It needs exactly two capabilities of the Bloc to fulfill its purposes – a Stream of states and a getter of the last state, when in reality it obtains an instance of the BlocBase that has an implicit interface that allows a BlocBuilder to:

1) Add error to the Bloc using the `addError` method.
2) Close the Bloc using the `close` method.
3) Emit an arbitrary State from the bloc using the `emit` method.
4) Invoke a reaction that happens on a state transition using the `onChange` method.

When in reality it needed only two getters – a getter of stream of states and a getter of the last state. That is objectively a non-ideal design, and the case of the BlocBuilder is not the only part that suffers because there is no *interface segregation*.

> Also, I prefer not to start using terminology like Observable and Subject because those are ReactiveX concepts that are independent of bloc.

I totally agree that the terminology that is not already used may be redundant, and the naming can be changed to more appropriate variants, but the points are still valid – the library lacks small, idependant interfaces.


Another very important "pro" point is that this refactoring would not introduce any breaking changes! It is totally possible to add the interfaces, thus following the *Dependency inversion* and *Interfaces segregation* principles, obtaining all the benefits that they offer and not break any existing code. 

Thank you very much for the work that you've done and continue to do for the whole Dart/Flutter community, we love the BLoC dearly and want it to advance and become even better :)

**Comment by narcodico** [comment]
I agree that a high level concept like `BlocBuilder` should not have access to low level implementations.

**Comment by felangel** [comment]
Hi @purplenoodlesoop thanks for the positive feedback and for providing additional context! 

> For example, the BlocBuilder expects the `BlocBase`. The `BlocBuilder` has one main purpose and two sub-purposes
> 
>* Display a widget based on Bloc's state.
>    * Apply conditions on displaying using a predicate.
>    * Locate a Bloc of a given type if it was not passed in a `bloc` argument of the constructor.

I agree with this except there is one small detail missing:

`BlocBuilder` needs the ability to lookup the bloc (or some "subject") via `BuildContext`. is a bloc is not explicitly specified. This means that `BlocBuilder` must reference the same type `T` as that which is provided to `BlocProvider` -- currently that is `BlocBase`.

My confusion is regarding this detail ☝️ 

In your ideal mind, how would `BlocProvider` provide an instance of a `Bloc`? What type would it use and how would `BlocBuilder`, `BlocListener`, etc. perform the lookup? What type would they use?

I'll mess around with this a bit more to see if there's anything we can do better but I don't see how this would work because the type being provided by `BlocProvider` needs to be the same as the type used to perform the lookup via `context`.

**Comment by PlugFox** [comment]
> In your opinion, how would BlocProvider provide an instance of a Bloc? What type would it use and how would BlocBuilder, BlocListener, etc. perform the lookup? What type would they use?

You can just rename BlocBase to IStateObservable (with state and stream getters), that's all.
Everything will continue to work as usual.

**Comment by felangel** [comment]
> > In your opinion, how would BlocProvider provide an instance of a Bloc? What type would it use and how would BlocBuilder, BlocListener, etc. perform the lookup? What type would they use?
> 
> You can just rename `BlocBase` to `IStateObservable` (with state and stream getters), that's all. Everything will continue to work as usual.

Sorry if I misunderstood but how would renaming the class address the concerns you mentioned above?

**Comment by felangel** [comment]
> > In your opinion, how would BlocProvider provide an instance of a Bloc? What type would it use and how would BlocBuilder, BlocListener, etc. perform the lookup? What type would they use?
> 
> You can just rename `BlocBase` to `IStateObservable` (with state and stream getters), that's all. Everything will continue to work as usual.

Then you would no longer be able to do `BlocProvider.of<T>(context).add(...)` for example.

**Comment by PlugFox** [comment]
> Then you would no longer be able to do `BlocProvider.of<T>(context).add(...)` for example.

BlocProvider depends on BlocBase now.
BlocBase has not `add` method.

How it works now?)
Elementary. You pass right type into generic.

**Comment by felangel** [comment]
> > Then you would no longer be able to do `BlocProvider.of<T>(context).add(...)` for example.
> 
> BlocProvider depends on BlocBase now. BlocBase has not `add` method.
> 
> How it works now?) Elementary. You pass right type into generic.

What I mean is currently the signatures look like:

```dart
BlocProvider<B extends BlocBase<S>, S>
BlocBuilder<B extends BlocBase<S>, S>
```

To clarify, you're suggesting to change to:

```dart
BlocProvider<B extends BlocBase<S>, S>
BlocBuilder<B extends IStateObserver<S>, S>
```

Is that correct?

If so, that's a breaking change and the internal implementation of `BlocBuilder` would still have to know about `BlocBase` to perform the lookup via `BuildContext`.

**Comment by PlugFox** [comment]
```
BlocProvider<B extends IStateObserver>
BlocBuilder<B extends IStateObserver<S>, S>
```

I think BlocProvider must be with IStateObserver too.
This is not breaking change.

If you want, i can create pull request with interfaces without changing tests.

**Comment by felangel** [comment]
> ```
> BlocProvider<B extends IStateObserver>
> BlocBuilder<B extends IStateObserver<S>, S>
> ```
> 
> I think BlocProvider must be with IStateObserver too. This is not breaking change.

If `BlocProvider` would change as well then how would the lookup work?

> If you want, i can create pull request with interfaces without changing tests.

Sure, that'd be great, thanks!

**Comment by PlugFox** [comment]
> If BlocProvider would change as well then how would the lookup work?

No worry, just wait maybe few weeks)
As soon as I finish with my presentation at the meetup, I will do this refactoring)

**Comment by felangel** [comment]
> > If BlocProvider would change as well then how would the lookup work?
> 
> No worry, just wait, maybe, few weeks) As soon as I finish with my presentation at the meetup, I will do this refactoring)

Sounds good, I'll play around with it in the meantime as well 👍 
Good luck with the meetup presentation! 💯

**Comment by felangel** [comment]
@PlugFox @purplenoodlesoop I opened https://github.com/felangel/bloc/pull/3012 which introduces a `StateObservable` and `StateDisposable` interface and updated the widgets in `package:flutter_bloc` to reference the interfaces rather than `BlocBase`. Let me know what you think.

**Comment by PlugFox** [comment]
Yeah, thats very good beginning)

**Comment by narcodico** [comment]
Spot on, although I'm not completely sold on the `Observable` naming. It's a ReactiveX concept which implies that it has observers subscribing to it. Although one might make a point that it follows the dart controller approach of having a `stream` to which you can listen and attach observers to, I still feel it's a bit off.

To me this class looks more like a `Subject`, a `BehaviorSubject` to be more precise, because you have a stream of values but you're also able to tap at any given point into the current value through the `state` getter. Basically a partial `BehaviorController` 🙄.

**Comment by felangel** [comment]
> Spot on, although I'm not completely sold on the `Observable` naming. It's a ReactiveX concept which implies that it has observers subscribing to it. Although one might make a point that it follows the dart controller approach of having a `stream` to which you can listen and attach observers to, I still feel it's a bit off.
> 
> To me this class looks more like a `Subject`, a `BehaviorSubject` to be more precise, because you have a stream of values but you're also able to tap at any given point into the current value through the `state` getter. Basically a partial `BehaviorController` 🙄.

Yeah naming is the hardest part haha. I went with Observable because as @PlugFox mentioned, it’s a generic term for a class which can be observed when implementing the observer pattern. The issue with Subjects is you can also modify the state of a subject whereas this interface should represent a read only object. An alternative to Observable could be StateStream? Wdyt?

**Comment by purplenoodlesoop** [comment]
I love it! That definitely solves most of the problem! 

One thing though, I think that something like `IBlocSink` is missing, that way almost all of the methods will be expressed through interfaces.

Regardless of the naming, I think something in the spirit of `IBlocBehavior`will fit well. Citing the paper that basically created the whole concept of reactivity, [Functional Reactive Animations](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.701.930&rep=rep1&type=pdf), the definition of "Behaviors" is following: 

> *Behaviors* are time-varying, reactive values.

That's exactly what the interface represents.

**Comment by felangel** [comment]
> I love it! That definitely solves most of the problem!
> 
> One thing though, I think that something like `IBlocSink` is missing, that way almost all of the methods will be expressed through interfaces.
> 
> Regardless of the naming, I think something in the spirit of `IBlocBehavior`will fit well. Citing the paper that basically created the whole concept of reactivity, [Functional Reactive Animations](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.701.930&rep=rep1&type=pdf), the definition of "Behaviors" is following:
> 
> > _Behaviors_ are time-varying, reactive values.
> 
> That's exactly what the interface represents.

Thanks for sharing! I’m fine with renaming Observable to BlocBehavior. My only complaint about that naming is it’s not as intuitive for the average developer. @narcodico do you prefer BlocBehavior?

Regarding the BlocSink interface why do you feel it’s necessary at this stage? It will introduce complexity because both Bloc and Cubit have addError but only Bloc has add and generally with EventSink both are grouped together along with close.

**Comment by narcodico** [comment]
@felangel `BehaviorBloc` maybe. but bloc is not an implementation of rx so you're safe either way.

Indeed `EventSink` plays well with bloc but not cubit.
You could potentially define your own set of abstractions, somewhat similar to what dart has:

```
abstract class CubitSink { 
  void addError(Object error, [StackTrace? stackTrace]);

  Future<void> close();
}

abstract class BlocSink<T> implements CubitSink {
  void add(T event);
}
```
And with the current implementation you'd have:
```

abstract class BlocBase<State> implements CubitSink {
  @override
  void addError(Object error, [StackTrace? stackTrace]) {
    // TODO: implement addError
  }

  @override
  Future<void> close() {
    // TODO: implement close
    throw UnimplementedError();
  }
}

abstract class Bloc<Event, State> extends BlocBase<State>
    implements BlocSink<Event> {
  @override
  void add(Event event) {
    // TODO: implement add
  }

  @override
  Future<void> close() {
    // TODO: implement close
    throw UnimplementedError();
  }
}
```

`CubitSink` could be named `BlocBaseSink`, at least in the current implementation, although the `BlocBase` is nothing but the cubit implementation basically.

**Comment by felangel** [comment]
Just updated #3012 again replacing `Observable` with `Streamable` and `StateStreamable` in an attempt to align more with existing Dart and Flutter naming conventions (`Listenable`/`ValueListenable`). I also took a stab at adjusting the sink interfaces. Would love to hear your thoughts, thanks!

**Comment by PlugFox** [comment]
@felangel 
Personally, naming is not important to me.
Made a small review

https://github.com/felangel/bloc/pull/3012
