### ISSUE TITLE
chore: Sync bloc_test versions with the bloc and flutter_bloc?

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#2996]
Would it make sense syncing major versions of the libs? I keep making the same mistake over and over: add bloc ^8.0.0, flutter_bloc ^8.0.0, and bloc_test ^8.0.0 just to get a pub error, due to incompatibilities in transitive deps. Then I look around and it turns out I need bloc_test ^9.0.0.

As far as I can see, except for the non-1.x.x versions (reply_bloc, bloc_concurrency), all the others are 8.x.x except for bloc_test. I'm not sure whether these, once they reach final status, should be made version 1 or synced with the main libraries as well.

**Comment by felangel** [comment]
Hi @wujek-srujek 👋 
Thanks for opening an issue and sorry for the inconvenience!

We can try to keep the versions synced but I worry it'll result in unnecessary revving of versions. For example, if there is a breaking change in just bloc_test we would need to treat all packages as having a breaking change even if that isn't the case. I was hoping instead to just maintain and version the packages independently and we happened to get lucky so far haha. Let me know what you think, and apologies again for any confusion/inconvenience!

**Comment by felangel** [comment]
Closing for now but if you feel strongly about syncing the versions please let me know and I’m happy to continue the conversation 👍

**Comment by wujek-srujek** [comment]
Sorry, I got distracted and forgot all about this issue. You do have a point, it's just pretty strange for the test lib to have a different version, is all (I would be curious to know how and when it got out of sync). I don't feel strong about it and it seems I'm by myself on it anyway, closing is fine.
