### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: HiveError: This should not happen. Please open an issue on GitHub.

### ISSUE THREAD

**Issue by Lednak007** [felangel/bloc#3010]

**Comment by felangel** [comment]
Hi @Lednak007 👋 
Thanks for opening an issue!

Can you please provide a minimal reproduction sample? There's not enough information here for me to help, thanks!

**Comment by Gene-Dana** [comment]
Hi there ! Closing this for now because there has been no response !
