### ISSUE TITLE
style: remove redundant function parameter syntax

### ISSUE THREAD

**Issue by purplenoodlesoop** [felangel/bloc#3016]
Hello!

[The package `replay_bloc` seems to use redundant and outdated function parameter syntax which can be removed.](https://github.com/felangel/bloc/blob/master/packages/replay_bloc/lib/src/change_stack.dart#L55)

I will be more than happy to submit a PR :)

**Comment by felangel** [comment]
Hi @purplenoodlesoop 👋 
Thanks for opening an issue!

Good catch! A PR would be awesome, thanks! 🙏
