### ISSUE TITLE
Migration to v8.0.0 issue

### ISSUE THREAD

**Issue by fdetun** [felangel/bloc#3019]
The following StateError was thrown building Builder:
Bad state: add(FeedPageEvent) was called without a registered event handler.
Make sure to register a handler via on<FeedPageEvent>((event, emit) {...})

my app is working as well but after upgrading the flutter_bloc version to 8.0.0 i got always this error:
----------------------------------------------------------------------------------------------------------------------------------------------------------------
The following StateError was thrown building Builder:
Bad state: add(FeedPageEvent) was called without a registered event handler.
Make sure to register a handler via on<FeedPageEvent>((event, emit) {...})
----------------------------------------------------------------------------------------------------------------------------------------------------------------
with flutter_bloc 7.3.3 it was working fine

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 8.0.0 introduced breaking changes ! You can visit the [migration guide here](https://bloclibrary.dev/#/migration) and although I'm closing this issue, feel free to continue to leave comments on this issue or to reach us more directly [on Discord](https://discord.gg/bmqDWRxk)

**Comment by felangel** [comment]
@fdetun as @Gene-Dana mentioned, you should refer to the [migration guide](https://bloclibrary.dev/#/migration) but based on the error I'm guessing you don't have a registered event handler for the `FeedPageEvent`:

```dart
class FeedPageBloc extends Bloc<FeedPageEvent, FeedPageState> {
  FeedPageBloc() : super(FeedPageInitial()) {
    on<FeedPageEvent>((event, emit) {...});
  }
}
```

**Comment by fdetun** [comment]
This the navigation bloc :) . And i said it was working fine with flutter bloc 7.3.3 just i uptader it to v 8 i got this error. Now i m working with 7.3.3 i don't have any problem.

This the navigation bloc

class NavigationBloc extends Bloc<NavigationEvent, NavigationState> {

  NavigationBloc() : super(FeedPageState());


  @override
  Stream<NavigationState> mapEventToState(
      NavigationEvent event,
      ) async* {

    if (event is FeedPageEvent) {
      yield FeedPageState();
    }

    if (event is GroupePageEvent) {
      yield GroupePageState();
    }

    if (event is NewGroupePageEvent) {
      yield NewGroupePageState();
    }
      if (event is GroupCreationPageEvent) {
      yield GroupCreationPageState();
    }



  }

  @override
  NavigationState get initialState => FeedPageState();

}

**Comment by danzapple** [comment]
@fdetun problem is same

**Comment by Blackheart8788** [comment]
I got the same issue when updated to ver. 8, so I downgraded to ver. 7.3.3 because the app release was an urgent matter. Now I'll start migrating and let you know how things went.
