### ISSUE TITLE
[Question] Difference between emit.onEach and emit.forEach

### ISSUE THREAD

**Issue by AscentionOne** [felangel/bloc#3038]
Hi @felangel, I have a question about when to use `emit.onEach()` and `emit.forEach()`. Based on the comment in the code below I can not quite distinguish the difference(to me it looks the same😂). However, I checked the parameter of both functions. 
It looks like `onEach` will have a `onData` callback that returns void
 ``` Dart 
 required void Function(T data) onData,
 ``` 
 `forEach` will have a `onData` callback that returns a state 
 ```Dart
 required State Function(T data) onData,
  ```

onEach:
```
Subscribes to the provided [stream] and invokes the [onData] callback when the [stream] emits new data.
[onEach] completes when the event handler is cancelled or when the provided [stream] has ended.
```

forEach:
```
Subscribes to the provided [stream] and invokes the [onData] callbackn when the [stream] emits new data and the result of [onData] is emitted.
 [forEach] completes when the event handler is cancelled or when the provided [stream] has ended.
```

Thanks again for the great package😁.

**Comment by felangel** [comment]
Hi @AscentionOne 👋 
Thanks for opening an issue!

The difference is `onData` in `forEach` must return a state which will be emitted whereas `onData` in `onEach` is `void` so you should use `forEach` when you directly want to map data from the stream into states that will be emitted by the bloc and `onEach` for all other scenarios.

Hope that makes sense and I'll improve the docs to make it more obvious when to use one vs the other 👍

**Comment by AscentionOne** [comment]
Hi, @felangel thank you for the clarification. 👍

**Comment by lngyeen** [comment]
Hi @felangel
As I understand it, when designing these two functions, you encouraged communication between Blocks directly through Stream, is that correct? ( i'm new to the BloC ;))

I've read a few threads about this issue and it still doesn't seem to have an end in sight.
https://github.com/slovnicki/reactive_repositories
https://medium.com/@saitejaerumandla/bloc-to-bloc-communication-in-flutter-3e6d2fba6fbf
https://medium.com/flutter-community/blocs-with-reactive-repository-5fd440d3b1dc
https://github.com/felangel/bloc/issues/3816

**Comment by nikkijuk** [comment]
> Hi @felangel As I understand it, when designing these two functions, you encouraged communication between Blocks directly through Stream, is that correct? ( i'm new to the BloC ;))

Could document here be helpful? https://bloclibrary.dev/architecture/#bloc-to-bloc-communication
