### ISSUE TITLE
Feat: neovim support

### ISSUE THREAD

**Issue by RomjanHossain** [felangel/bloc#3039]

**Comment by felangel** [comment]
Hi @RomjanHossain 👋 
Thanks for opening an issue!

Can you please provide a bit more context regarding what you'd expect in terms of neovim support? Thanks! 🙏

**Comment by eliasreis54** [comment]
I don't know what exactly @RomjanHossain expect with neovim support.

But, may be this [plugin](https://github.com/eliasreis54/vim-bloc-plugin) can help with generation files.

**Comment by erickzanardo** [comment]
> I don't know what exactly @RomjanHossain expect with neovim support.
> 
> But, may be this [plugin](https://github.com/eliasreis54/vim-bloc-plugin) can help with files generation.

This plugin works pretty good, AFAIK this is the only plugin available for vim/nvim out there. I wonder if it could be mentioned on the Tools/Extensions section of https://bloclibrary.dev/ so more people can be aware of it

**Comment by felangel** [comment]
@eliasreis54 thanks so much for taking the time to create the plugin 🙏 💙 
What are your thoughts on migrating the plugin into the [bloc repo under extensions](https://github.com/felangel/bloc/tree/master/extensions)? If you prefer to maintain it under your own personal repo that's totally fine as well and we can add a link to the docs in either case, thanks!

**Comment by eliasreis54** [comment]
I'm so happy to contribute with the community. 
All right, i can move the files to bloc extensions... I just need to check how to do the install process. 
I'll do that and a soon as possible i open the PR moving the files.

**Comment by erickzanardo** [comment]
@eliasreis54 this should just be a matter of asking the users to specify the `dir` argument: https://github.com/junegunn/vim-plug#plug-options

Something like: 

```
Plug `felangel/bloc', { 'dir': 'extensions/vim'}
```

**Comment by eliasreis54** [comment]
Sounds good! Thanks Erick!
