### ISSUE TITLE
Improve BlocDelegate Initialization

### ISSUE THREAD

**Issue by felangel** [felangel/bloc#304]
**Is your feature request related to a problem? Please describe.**
Setting a custom `BlocDelegate` is a bit confusing in its current state.
We need to do:

```dart
BlocSupervisor().delegate = MyBlocDelegate()
```

This makes it seem like we are creating a new instance of the `BlocSupervisor` when instead we are retrieving a reference to the singleton instance.

**Describe the solution you'd like**
It would be a bit more intuitive to initialize the delegate like:

```dart
BlocSupervisor.delegate = MyBlocDelegate();
```

**Comment by felangel** [comment]
Merged in #305 and will be included in bloc v0.14.0

**Comment by AlejandroC90** [comment]
I'm having trouble creating my own BlocDelegate, when overriding onTransition I get an error, did the annotation change? Thanks

**Comment by felangel** [comment]
@AlejandroC90 can you please share your BlocDelegate code as well as the error you’re getting? Thanks!

**Comment by AlejandroC90** [comment]
Sorry for late response, but I was just getting and error with the old BlocDelegate.
`class SimpleBlocDelegate extends BlocDelegate {`
 ` @override`
 ` void onTransition(Transition transition) {`
   ` print(transition.toString());`
 ` }`
`}`

Didnt know that I had to update it to:

`class SimpleBlocDelegate extends BlocDelegate {`
 ` @override`
 ` void onTransition(Bloc bloc, Transition transition) {`
    `super.onTransition(bloc, transition);`
    `print(transition);`
 ` }`
`}`

Thanks for the response
