### ISSUE TITLE
fix:  State doesn't update even when a member has changed

### ISSUE THREAD

**Issue by Hari-07** [felangel/bloc#3048]
**Description**
One of the state members, when given a new value, still fails to be recognized as a new state

**Steps To Reproduce**
I have a state with one of its members as a List of Lists
```dart
const factory GridState({
  required List<List<GridCellData>> gridCellData,
}) = _GridState;
```
In order to update one of the elements in this 2d list, as mentioned in docs, I created a new instance of the list rather than modifying the original one, and then updated the state with the new instance
```dart
cellActivated: (e) async {
    final gridCellData = state.gridCellData[e.rowIndex][e.colIndex];
    final updatedGridCellData = gridCellData.copyWith(
      currentValue: gridCellData.currentValue + 1,
    );

    final List<List<GridCellData>> updatedGrid = List.from(state.gridCellData);
    updatedGrid[e.rowIndex][e.colIndex] = updatedGridCellData;

    print('Updated state');
    print(updatedGrid == state.gridCellData);  //Gives False
    print(state.copyWith(gridCellData: updatedGrid) == state); //Gives True
    emit(state.copyWith(gridCellData: updatedGrid));
},
```
Even though the value is different as proven by the first comparison which evaluates to false, the state doesn't seem to be a new one, and thus the builder doesn't rebuild

**Expected Behavior**
Expected a new state to be created

**Comment by narcodico** [comment]
Hi @Hari-07 👋

That happens because you're mutating the inner list instead of creating a new one. Something like this should do it:

```
final grid = state.gridCellData;
    final cellData = grid[rowIndex][columnIndex];
    final newCellData =
        cellData.copyWith(currentValue: cellData.currentValue + 1);
    final newGridData = List<GridCellData>.from(grid[rowIndex])
      ..[columnIndex] = newCellData;
    final newGrid = List<List<GridCellData>>.from(grid)
      ..[rowIndex] = newGridData;
    emit(state.copyWith(gridCellData: newGrid));
```

**Comment by Hari-07** [comment]
Alright got 

> Hi @Hari-07 👋
> 
> That happens because you're mutating the inner list instead of creating a new one. Something like this should do it:
> 
> ```
> final grid = state.gridCellData;
>     final cellData = grid[rowIndex][columnIndex];
>     final newCellData =
>         cellData.copyWith(currentValue: cellData.currentValue + 1);
>     final newGridData = List<GridCellData>.from(grid[rowIndex])
>       ..[columnIndex] = newCellData;
>     final newGrid = List<List<GridCellData>>.from(grid)
>       ..[rowIndex] = newGridData;
>     emit(state.copyWith(gridCellData: newGrid));
> ```

Thanks, that worked. Could you let me know why then does the element itself does not evaluate as equal although the state which contains it does?

**Comment by Hari-07** [comment]
As a followup, in the new version are multiple emits not allowed from the same event, previously before 8, I have had projects where at the beginning of the event I would yield a state setting a loading indicator or so, and at the end update the state with the data fetched and the state updated twice and UI responded too, currently it seems the emit() is only happening at the end, and the data does get updated but rebuild does not occur. For example 

```dart
cellActivated: (e) async {
  emit(
    state.copyWith(
      gridReady: false,
    ),
  );

//updating the grid
emit(
    state.copyWith(
      gridCellData: newGrid,
      gridReady: true,
    ),
  );
}
```

Now I have a print statement that executes everytime the builder is invoked, and in that I am printing out the value of gridReady, however it never prints out as false which means the 2 emits seem to have cascaded in some way

**Comment by narcodico** [comment]
> Could you let me know why then does the element itself does not evaluate as equal although the state which contains it does?

The first print evaluates the `gridCellData` while the second one the whole `state`. I don't have access to all your code to better understand what's going on but I assume your state is mutated by other concurrent event possibly. Keep in mind `state` is ever changing.



> in the new version are multiple emits not allowed from the same event, previously before 8, I have had projects where at the beginning of the event I would yield a state setting a loading indicator or so, and at the end update the state with the data fetched and the state updated twice and UI responded too, currently it seems the emit() is only happening at the end, and the data does get updated but rebuild does not occur

You can emit as many states as you want from an event. Your states are not all rendered most likely because flutter doesn't get the chance to do that as multiple state changes occur during same frame.
