### ISSUE TITLE
fix: Cannot find stack trace for exception in BloC constructor

### ISSUE THREAD

**Issue by jmewes** [felangel/bloc#3052]
**Description**

If there is an exception in the BloC constructor, then the message and stack trace of that exception cannot be found in the message and stack trace printed to the console.

**Steps To Reproduce**

See https://github.com/felangel/bloc/pull/3051 => https://github.com/felangel/bloc/runs/4446243502

**Screenshot**

![Selection_507](https://user-images.githubusercontent.com/5235584/145060444-0e3d4562-17bb-47bc-8de1-11ba4bf5a7c3.png)

**Expected Behavior**

The message and stack trace of the exception in the BloC constructor should be printed to the console.

**Additional Context**

As a workaround, one can run the test or app in debug mode. Then the debugger automatically sets a breakpoint right after the throwing of the exception.

Here is the start of what is printed to the console:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following StateError was thrown building InheritedProvider<CounterCubitWithBrokenConstructor>:
Bad state: Tried to read a provider that threw during the creation of its value.
The exception occurred during the creation of type CounterCubitWithBrokenConstructor.

The relevant error-causing widget was:
  InheritedProvider<CounterCubitWithBrokenConstructor>
  InheritedProvider:file:///home/janux/src/misc/bloc/packages/flutter_bloc/lib/src/bloc_provider.dart:130:11

When the exception was thrown, this was the stack:
#0      _CreateInheritedProviderState.value (package:provider/src/inherited_provider.dart:701:7)
#1      _CreateInheritedProviderState.debugFillProperties (package:provider/src/inherited_provider.dart:793:44)
```

Here is a the full console output from the test `propagates stack trace of BloC constructor exception` in https://github.com/felangel/bloc/pull/3051:

[console-output.txt](https://github.com/felangel/bloc/files/7669556/console-output.txt)

**Comment by felangel** [comment]
Hi @jmewes 👋 
Thanks for opening an issue!

Are you able to reproduce with just `Provider`? This looks like it should ideally be addressed within `provider` wdyt?
Thanks!

**Comment by jmewes** [comment]
Hi @felangel ,

Thank you for your quick response!

Yes, I could reproduce the issue in the `provider` package:

https://github.com/rrousselGit/provider/issues/705

If this issue gets fixed at any time with the next `provider` version applied by `flutter_bloc`, this is fine for me. So, I am closing this issue. Feel free to reopen if you want to keep it as a reminder for a required version bump.
