### ISSUE TITLE
docs: getting a error when listening to a state in many areas of my code : error: Bad state: on<T> was called multiple times. There should only be a single event handler per event type

### ISSUE THREAD

**Issue by ride4sun** [felangel/bloc#3061]
**Description**

Clearly describe what documentation you are looking to add or improve.

I get and exception when I listen to a bloc state in multiple errors of my code.

```
error: Bad state: on<CommunicationInitEvent> was called multiple times. There should only be a single event handler per event type.
```

and that is correct and intended and I need that functionality. I migrated from an older version of bloc to 7.X

This is the bloc I listen to an 5 areas of my code

```
comInit.on(
      (onData, emit) {
        if (onData.isNull) return;

... more here...

   ```

I have the feeling there is an easy way around that...

**Comment by chonghorizons** [comment]
Recommend to tag/triage as migration specific issue.

We'll probably ask for a minimum reproducible snippet of code. If you can, modify the counter example  https://dartpad.dev/?id=90da115645caf06ffe10dc8ab170f347 to generate the same error.

By any chance: are you emitting the event to the bloc within a widget build process? Or is it via some UI event like a button? 

You might also see the builder infinite loop issue mentioned in https://github.com/felangel/bloc/issues/3008#issuecomment-989285403

**Comment by ride4sun** [comment]
```
comInit.on(
      (onData, emit) {
        if (onData.isNull) return;

... more here...
```

I did  
```
comInit.stream.listen(
      (onData {...
... more here...

**Comment by felangel** [comment]
@ride4sun can you provide a link to a minimal reproduction sample? I'm not sure what `comInit` is referring to in the above snippet. Thanks!

**Comment by felangel** [comment]
Closing for now but feel free to provide a link to a minimal reproduction sample (DartPad or GitHub repo) and I'm happy to take a closer look, thanks!
