### ISSUE TITLE
docs: Create one bloc throughout the app?

### ISSUE THREAD

**Issue by itaishalom** [felangel/bloc#3063]
**Description**

Hi, is there a way to create one bloc instance for the entire app?
I can use the provider to provide the same bloc through the widget tree but my issue is that I have firebase notifications that allows me to open the app from the notification and navigate to a widget but then I don't have the father's context in order to provide the bloc.
How can I achieve that? Something like a static bloc?

**Comment by ShakyaCsun** [comment]
If you wrap your MaterialApp with BlocProvider, it is available throughout your apps context. See https://bloclibrary.dev/#/recipesflutterblocaccess?id=global-access

**Comment by felangel** [comment]
Hi @itaishalom 👋 
Thanks for opening an issue!

As @ShakyaCsun mentioned, you can provide a bloc above `MaterialApp` to make it globally accessible. Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by itaishalom** [comment]
Thanks.
