### ISSUE TITLE
refactor: further apply the DIP and ISP principles

### ISSUE THREAD

**Issue by purplenoodlesoop** [felangel/bloc#3065]
Hello!

Thank you so much for the recent "core interfaces" update! It is really a lifesaver! 

I've identified three places where it can be extended to further apply the same principles.

1. Extract "hooks" to separate interfaces. The `onChange` and `onError` can be extracted in one interface, `BlocBaseHooks`, and the `onEvent` and `onTransition` can be extracted to the second, `BlocHooks`, that will implement the first.

2. The `isClosed` getter can be moved to the `Closable` interface.

3. `BlocObserver` can depend on interfaces using the following schema with explicit covariance.

|  Method  |  New type  |
|---|---|
|  `onCreate`  |  `StateStreamableSource`  |
|  `onEvent`  |  `BlocEventSink`  |
|  `onChange`  |  `StateStreamable`  |
|  `onTransition`  |  `BlocEventSink`  |
|  `onError`  |  `ErrorSink`  |
|  `onClose`  |   `Closable`  |

I'm almost done with the PR and looking forward to seeing what you think :)

**Comment by purplenoodlesoop** [comment]
@felangel thanks for the review! My laptop broke down, I will apply the feedback in the next few days 😅

**Comment by felangel** [comment]
> @felangel thanks for the review! My laptop broke down, I will apply the feedback in the next few days 😅

Sounds good! I'll re-review again tomorrow but I feel fine with the changes to `Closable` and `BlocObserver`. The only change I am unsure about is the `Hooks`/`Lifecycle` change. Would you be okay if I updated your PR to revert the hooks change so we can merge it? We can then continue to discuss the hooks/lifecycle 👍

**Comment by purplenoodlesoop** [comment]
> Would you be okay if I updated your PR to revert the hooks change so we can merge it?

Of course, sounds good!

**Comment by purplenoodlesoop** [comment]
Oh wait. I think the `BlocObserver` update can lead to unexpected runtime behavior. 

Could you also revert those changes? Only Closable update it is :)
