### ISSUE TITLE
refactor: Shouldn't onChange, onError and addError be protected ?

### ISSUE THREAD

**Issue by cedvdb** [felangel/bloc#3068]
This is bothering me a bit, shouldn't onChange, onError and addError be protected ?  it looks odd as a public api.

**Comment by felangel** [comment]
Hi @cedvdb 👋 
Thanks for opening an issue!

Good catch, I agree they should be protected 👍 

I opened #3071 to make `onChange` and `addError` protected (`onError` is already `protected`).
