### ISSUE TITLE
question: Hot Reload doesn't work with the new `on<...>` API?

### ISSUE THREAD

**Issue by rohan20** [felangel/bloc#3074]
**Description**
When using the `mapEventToState(...)` API, any changes to this method in the bloc were picked up by hot-reload. On migrating to the new `on<...>` API, that's not the case.

**Steps To Reproduce**

1. Create any bloc and process an event (let's say as follows):
```dart
class LoginBloc extends Bloc<LoginEvent, LoginState> {
  LoginBloc() : super(LoginState.initial()) {
    on<SubmitCredentialsTappedEvent>(
      (event, emit) async {
            doA();
            doB();            
        },
    );
}
```
2. Hot **Restart** the app and trigger `SubmitCredentialsTappedEvent` from the UI
3. Back in the bloc, change the logic to:
```dart
    on<SubmitCredentialsTappedEvent>(
      (event, emit) async {
            doA();
            doB();
            doC(); // new
        },
    );
```

4. Hot **Reload** (note: not Hot Restart) the app and trigger `SubmitCredentialsTappedEvent` again from the UI

**Actual Behavior**
`doC();` is never called.

**Expected Behavior**
Would be nice if `doC();` gets picked up on hot-reload. Currently, it doesn't. I believe this is because on hot-reloading the app, the bloc isn't created again, so the changes never get picked up within the bloc. This was not the case with the `mapEventToState(...)` API.

I am new to the `on<...>` API so I may be implementing the bloc incorrectly on my end. Looking for suggestions around how to get hot-reload to work again. Thank you!

**Comment by narcodico** [comment]
Hi @rohan20 👋

That happens because `BlocProvider` caches the instance of the bloc thus it doesn't get recreated upon hot reload.
This combined with the way you're registering your event handler makes it such that it needs a recreating in order for it to be up to date.
The easy solution and the recommended way of registering event handlers is to extract your event handler; now you're only registering the reference to your handler thus allowing you to alter it's body.

```
class LoginBloc extends Bloc<LoginEvent, LoginState> {
  LoginBloc() : super(LoginInitial()) {
    on<SubmitCredentialsTappedEvent>(_onSubmitCredentialsTappedEvent);
  }

  Future<void> _onSubmitCredentialsTappedEvent(
    SubmitCredentialsTappedEvent event,
    Emitter<LoginState> emit,
  ) async {
    doA();
    doB();
  }
}
```

**Comment by rohan20** [comment]
@narcodico That makes so much sense. Hot reload works now 🎉 

Thank you so much! ⭐
