### ISSUE TITLE
perf: Future<void> close()  

### ISSUE THREAD

**Issue by hatemragab** [felangel/bloc#3075]
why close method is type Future
```
 int ? isOpenPage;
  @override
  Future<void> close() async {
    isOpenPage = null;
    super.close();
  }

 initConstractor(value){
  isOpenPage = value;
}
````
in my case, I want to 
```
Navigator.pop()
```
then push the same page
but with different parameters 

close method invoked after push so the isOpenPage  will have the null value 
because close method invoked after push 

if fix this by 
await 500 millisecond
then push 
by this way i make sure the close method has been invoked

**Comment by narcodico** [comment]
Hi @hatemragab 👋

> why close method is type Future
That's because internally cubit/bloc need to await closing the state/event stream controllers.

As for your issue, it seems you're keeping additional state directly on the bloc instance which is not recommended.
All state should be kept on the state class.

**Comment by hatemragab** [comment]
Ok
