### ISSUE TITLE
feat: (network) Please add example usage inside initState()

### ISSUE THREAD

**Issue by erlangparasu** [felangel/bloc#3081]
**Description**

Currently the example BlocProvider called inside build method

**Desired Solution**

https://docs.flutter.dev/cookbook/networking/fetch-data#why-is-fetchalbum-called-in-initstate

> 
> Why is fetchAlbum() called in initState()?
> 
> Although it’s convenient, it’s not recommended to put an API call in a build() method.
> 
> Flutter calls the build() method every time it needs to change anything in the view, and this happens surprisingly often. Leaving the fetch call in your build() method floods the API with unnecessary calls and slows down your app. 
>

**Comment by felangel** [comment]
Hi @erlangparasu 👋
Thanks for opening an issue!

Can you please provide a bit more context? What example are you referring to?

Thanks!

**Comment by erlangparasu** [comment]
Thank you for responding :)

The official documentation recommends not calling network requests inside the build function because flutter can call the `build` function over and over again.

When we call the `BlocProvider` in the `build` method, will the saved state/cubit be recreated many times too?
for example `return new BookCubit()`

**Comment by felangel** [comment]
> Thank you for responding :)
> 
> The official documentation recommends not calling network requests inside the build function because flutter can call the `build` function over and over again.
> 
> When we call the `BlocProvider` in the `build` method, will the saved state/cubit be recreated many times too? for example `return new BookCubit()`

BlocProvider’s create method is only called once when the BlocProvider is mounted and the bloc is closed when the BlocProvider is unmounted. This is not the same as directly creating instances within a build method. 

Hope that helps!

**Comment by erlangparasu** [comment]
Thank you for providing an explanation. Sorry because I misperceived the behavior of the BlocProvider in the build method. Thank you so much :)

**Comment by felangel** [comment]
> Thank you for providing an explanation. Sorry because I misperceived the behavior of the BlocProvider in the build method. Thank you so much :)

No problem! Glad I was able to help 🙂
