### ISSUE TITLE
build(extension/vscode): configure bloc generation

### ISSUE THREAD

**Issue by JigneshPatel23** [felangel/bloc#3082]
**Configure Bloc Generation**

I have a project which has **freezed** and **equatable** both has a dependency and I would like to **use equatable for new code** but I can't able to find a way to configure this to generate new bloc code using equatable. 

https://github.com/felangel/bloc/blob/77ebe56884129495bf0c445db2892376eb3933d9/extensions/vscode/src/utils/get-bloc-type.ts#L32

@felangel any suggestions to get those working or any temp. solution?

**Comment by ShakyaCsun** [comment]
@JigneshPatel23 you can set default bloc and cubit template in VSCode settings. Just search for bloc in settings UI.
![image](https://user-images.githubusercontent.com/38353746/146935189-4039666f-5a6b-4d92-bd03-7ed1eb90c363.png)

**Comment by felangel** [comment]
Hi @JigneshPatel23 👋
Thanks for opening an issue!

See @ShakyaCsun’s answer and feel free to comment if you’re still having trouble.

Closing for now 👍

**Comment by JigneshPatel23** [comment]
Thanks much @ShakyaCsun & @felangel it will help a lot..  🎉
