### ISSUE TITLE
docs: Dynamic list of BlocListenerSingleChildWidget?

### ISSUE THREAD

**Issue by itaishalom** [felangel/bloc#3083]
**Description**

I try to find a way to make MultiBlocListener dynamic with listener array which is build on runtime.
for exmaple:
```
List<BlocListenerSingleChildWidget> list = [];

if(..)

list.add(SomeBlocListener1);

if(..)

list.add(SomeBlocListener2);

  return MultiBlocListener(
        listeners:
          list
```

But I can't import BlocListenerSingleChildWidget.
What should I do?

**Comment by narcodico** [comment]
Hi @itaishalom 👋

You can do this:
```
final listeners = <BlocListener<BlocBase<Object>, Object>>[];
...
listener.add(SomeBlocListener(...));
...
return MultiBlocListener(listeners: listeners); 
```

**Comment by itaishalom** [comment]
Thanks for reply!
I'm getting:
The argument type 'BlocListener<BlocBase<dynamic>, dynamic>' can't be assigned to the parameter type 'BlocListener<BlocBase<Object>, Object>'.

**Comment by itaishalom** [comment]
Changing to to dynamic, dynamic solved it!

**Comment by narcodico** [comment]
Make sure you explicitly set the types when you create the listeners `BlocListener<SomeBloc, SomeState>`.

**Comment by felangel** [comment]
Thanks @narcodico for the prompt response!

Closing for now but feel free to comment if you have any follow-up questions and we can continue the conversation 👍
