### ISSUE TITLE
[proposal] [BREAKING] feat(bloc): make `BlocObserver` dependent on interfaces

### ISSUE THREAD

**Issue by purplenoodlesoop** [felangel/bloc#3085]
Hi @felangel!

**Description**

With the new update bringing interface, it is now possible to make `BlocObserver` dependent on abstractions, following the *Dependency Inversion Principle*. 

This will certainly be a breaking change, but it will enable developers to fully leverage the power of a centralized observing entity with a custom implementation of new interfaces.

**Desired Solution**

`BlocObserver` will depend on interfaces using the following schema.

|  Method  |  New type  |
|---|---|
|  `onCreate`  |  `StateStreamableSource`  |
|  `onEvent`  |  `BlocEventSink`  |
|  `onChange`  |  `StateStreamable`  |
|  `onTransition`  |  `BlocEventSink`  |
|  `onError`  |  `ErrorSink`  |
|  `onClose`  |   `Closable`  |

**Alternatives Considered**

There is a single alternative option besides not making the change altogether, but it can lead to unexpected runtime behavior. Every argument type could be declared with explicit covariance, which would make this change non-breaking, but add restrictions on not modifying the types when extending the `BlocObserver`.

**Additional Context**

Feel free to close the issue and reject the proposal, I do not feel strongly about it and the fact of a breaking change could certainly outweigh the benefits :)

**Comment by felangel** [comment]
Hi @purplenoodlesoop 👋 
Thanks for opening an issue!

I've thought about this as well but I personally prefer to leave the API as is because:
- as you mentioned it's a breaking change
- when observing blocs/cubits from the perspective of supporting dev tools I'd want to have the base interface to support things like time-travel debugging.

Let me know what you think and thanks again for opening the issue! 🙏

**Comment by purplenoodlesoop** [comment]
@felangel I agree that the cons outweigh the pros, and the point with the dev tools is certainly a big one. Thank you for the response and official closure of the change.
