### ISSUE TITLE
[proposal] feat(bloc): clarify State convention.

### ISSUE THREAD

**Issue by SuhwanCha** [felangel/bloc#3088]
**Description**

Hello,
I just started to migrate my project to BloC from provider, but I'm quite confused on State.

Some examples use State with Status parameters, **(1)**
 and examples use abstract State class. **(2)**
I tried to both way but there are pros and cons.

In case of **(1)**, I have difficulties when there is a lot of status.
For examples, there are a lots of Status, I have to emit like
```dart
return emit(
            state.copyWith(
              status: 
              (state.status == Status.status1 || state.status == Status.status2) ?
                status.success1,
                status.success2,
            ),
 );
```
So, I have to dealing with a lots of cases every emit.

In case of **(2)**, It is more clear but I have to implement a lots of overide methods, and it will take long.

I'm bad at BloC, so maybe it's because of my misunderstanding, but I'd like to suggest unify both ways or clarify documents.

**Desired Solution**

Unify both methods, takes only advantage from each method.

**Alternatives Considered**

Please clarify document for each methods, because I'm very confused because I'm newbie here.

Thank you!

**Comment by Gene-Dana** [comment]
Hi there 👋🏼  Here is a recent discussion that you may benefit from ! 

https://github.com/felangel/bloc/issues/2884

**Comment by SuhwanCha** [comment]
Hello, @Gene-Dana 
Thank you for your answer!

I found it's depend on my needs, and I like it because It's high genetic polymorphism!

But, in simple or most universal cases, I think implementing everything is quite cumbersome.
So, how about make some **abstract state class** like Equatable for most universal cases?

That class has Equatable's feature, and make much easier to implement State and make state more clearly.
I think that would be awesome and makes BLoC to be easier to use 👏

 Have a good year end! 😀

cc/ @felangel

**Comment by chonghorizons** [comment]
I think that there isn't a convention with state. Depending on the complexity, different things are needed.

But the docs could link to #2884, with some text like:

> TIP: When creating your class to hold your Bloc's state, these three patterns might help you. (Link to #2884)

**Comment by chonghorizons** [comment]
> I think that there isn't a convention with state. Depending on the complexity, different things are needed.
> 
> But the docs could link to #2884, with some text like:
> 
> > TIP: When creating your class to hold your Bloc's state, these three patterns might help you. (Link to #2884)

@SuhwanCha , if you want to be bold and helpful, find the markdown file in the docs and make a pull request. You should be able to find the exact md file by searching for the phrase using the GitHub search bar.


I can't guarantee the PR will be accepted, but I think adding these kinds of tips is under consideration.

**Comment by SuhwanCha** [comment]
@chonghorizons, Ok, thank you for your comment.
Because I’m new to bloc, so I'll consider more and make PR :)

**Comment by felangel** [comment]
This should be covered in the [naming conventions](https://bloclibrary.dev/#/blocnamingconventions?id=state-conventions) section of the documentation.

Closing for now but feel free to open a PR to enhance the documentation if you feel something is missing 👍
