### ISSUE TITLE
style(bloc): misc style changes

### ISSUE THREAD

**Issue by purplenoodlesoop** [felangel/bloc#3089]
Hi! 

I've spotted two potential style change candidates that will align nicely with the overall package code style.

1) [Can be potentially implemented through expression body function (`=>`)](https://github.com/felangel/bloc/blob/master/packages/bloc/lib/src/change.dart#L30)
2) [Can be potentially implemented through `late` keyword instead of manual cached assignment](https://github.com/felangel/bloc/blob/master/packages/bloc/lib/src/bloc_base.dart#L62)

**Comment by narcodico** [comment]
1. I believe the body syntax is preferred because expression body will result in a line longer than 80 chars and having it on two lines doesn't look that great in this case.
2. Good catch

**Comment by felangel** [comment]
Yup I agree with @narcodico, thanks @purplenoodlesoop!

**Comment by purplenoodlesoop** [comment]
> I believe the body syntax is preferred because expression body will result in a line longer than 80 chars and having it on two lines doesn't look that great in this case.

Indeed, thanks!
