### ISSUE TITLE
MultiBlocProvider with dio interceptor

### ISSUE THREAD

**Issue by tayfunuyar** [felangel/bloc#3095]
Hi,
I'm using  dio for api call. 
In the project base I have a authbloc for logout and login. 
How to trigger login listener here without context or is it possible?   
![image](https://user-images.githubusercontent.com/27923376/147455918-cddfd81f-012f-41d7-a00e-5a5df94e7df4.png)

**Comment by narcodico** [comment]
Hi @tayfunuyar 👋

You should check out [fresh_dio](https://pub.dev/packages/fresh_dio) and the example from the repo.

**Comment by tayfunuyar** [comment]
@narcodico  thank you  for quick response. I saw this package. But I'm looking  diffrerent solution redirect to login without any package with trigger bloc event.

**Comment by narcodico** [comment]
You would usually emit states and react to those states in a `BlocListener` where you could potentially add events to other blocs.
It's hard to give you guidance without seeing your overall setup, so if you still encounter issues I'd kindly ask you to share a repo we could run locally.
