### ISSUE TITLE
fix: Unhandled Exception: 'package:bloc/src/bloc.dart': Failed assertion: line 232 pos 7: '!_isCompleted': 

### ISSUE THREAD

**Issue by gilangsatria09** [felangel/bloc#3098]
**Description**
I tried called emit inside dartz fold after i called await function

 var token = await fetchToken(NoParams());
    token.fold((l) async => emit(ErrorState('error')), (r) async {
      //Error Unhandled Exception if this line added
      var res = await getBanner(GetBannerParams(token: r));

      emit(GetHomeDataSuccess(listBanner: []));

    });

**Expected Behavior**
I expected that emit(GetHomeDataSuccess) is called successful

**Screenshots**
![image](https://user-images.githubusercontent.com/52986068/147628506-ca9a10f8-8393-4e3d-9459-f2ac8f4f876c.png)
![image](https://user-images.githubusercontent.com/52986068/147628538-edc5e09c-1095-40f3-9f8e-03be73124c58.png)

**Comment by felangel** [comment]
Hi @gilangsatria09 👋
Thanks for opening an issue!

You need to await the call to token.fold to prevent the event handler from completing before emit is called.

Let me know if that helps! 👍

**Comment by gilangsatria09** [comment]
Thank you so much for reply my issues this fast!!

so, what i should do is add await to the token.fold like this:
var token = await fetchToken(NoParams());
await token.fold((l) async => emit(ErrorState('error')), (r) async {

am i right?

**Comment by felangel** [comment]
> Thank you so much for reply my issues this fast!!
> 
> so, what i should do is add await to the token.fold like this: var token = await fetchToken(NoParams()); await token.fold((l) async => emit(ErrorState('error')), (r) async {
> 
> am i right?

Yup, no problem! 👍 
Let me know if that resolves the issue.

**Comment by gilangsatria09** [comment]
omg!!! thank you soooooo much, it really worked. thank you for helping me despite my bad english

**Comment by felangel** [comment]
> omg!!! thank you soooooo much, it really worked. thank you for helping me despite my bad english

No problem! 😄
