### ISSUE TITLE
ges_block_invoke

### ISSUE THREAD

**Issue by jiharal** [felangel/bloc#310]
![image](https://user-images.githubusercontent.com/21150538/57983718-e143c780-7a87-11e9-9007-bda559156bd3.png)

**Comment by felangel** [comment]
Hi @jiharal 👋 
Thanks for opening an issue. 

Can you please provide more details or better yet, share a link to a sample app which has the problem? Thanks!

**Comment by felangel** [comment]
Closing this for now as there is not enough information provided but feel free to comment with additional details or a sample app and I'm happy to continue the conversation 👍
