### ISSUE TITLE
build: Version solving failed

### ISSUE THREAD

**Issue by milanobrenovic** [felangel/bloc#3105]
**Description**
I currently use `flutter_bloc: ^7.3.1` and i'm trying to upgrade to the current latest version `flutter_bloc: ^8.0.1` but im getting a version solving failed error

```
Because <app> depends on chat from path which depends on flutter_bloc ^7.3.1, flutter_bloc ^7.3.1 is required.
So, because <app> depends on flutter_bloc ^8.0.1, version solving failed.
pub get failed (1; So, because <app> depends on flutter_bloc ^8.0.1, version solving failed.)
```

**Comment by felangel** [comment]
Hi @milanobrenovic 👋
Thanks for opening an issue!

It looks like you have a dependency on a package called chat which depends on flutter_bloc: ^7.3.1. You need to first make sure your dependencies are upgraded before updating your app.

Let me know if that helps! 👍

**Comment by milanobrenovic** [comment]
> Hi @milanobrenovic 👋 Thanks for opening an issue!
> 
> It looks like you have a dependency on a package called chat which depends on flutter_bloc: ^7.3.1. You need to first make sure your dependencies are upgraded before updating your app.
> 
> Let me know if that helps! 👍

Yes, my bad. Forgot to update in the chat package first. Thank you
