### ISSUE TITLE
fix: removeFieldBlocs is not working in Flutter

### ISSUE THREAD

**Issue by nilesh2211** [felangel/bloc#3106]
**Description**
In Flutter, when i am trying to call removeFieldBlocs function is not removing filed but its adding field i am not sure it is bug or is something missing in my code 

I have checked here : https://giancarlocode.github.io/form_bloc/#/ got to Conditional Field Example this is also not working

**Steps To Reproduce**

class ConditionalFieldsFormBloc extends FormBloc<String, String> {
  final doYouLikeFormBloc = SelectFieldBloc(
    validators: [FieldBlocValidators.required],
    items: ['No', 'Yes'],
  );

  final whyNotYouLikeFormBloc = TextFieldBloc(
    validators: [FieldBlocValidators.required],
  );

  final showSecretField = BooleanFieldBloc();

  final secretField = TextFieldBloc(
    validators: [FieldBlocValidators.required],
  );

  ConditionalFieldsFormBloc() {
    addFieldBlocs(
      fieldBlocs: [
        doYouLikeFormBloc,
      ],
    );

    showSecretField.onValueChanges(
      onData: (previous, current) async* {
        if (current.value) {
          addFieldBlocs(fieldBlocs: [secretField]);
        } else {
          removeFieldBlocs(fieldBlocs: [secretField]);
        }
      },
    );

    doYouLikeFormBloc.onValueChanges(
      onData: (previous, current) async* {
        removeFieldBlocs(
          fieldBlocs: [
            whyNotYouLikeFormBloc,
            showSecretField,
            secretField,
          ],
        );

        if (current.value == 'No') {
          addFieldBlocs(fieldBlocs: [
            whyNotYouLikeFormBloc,
          ]);
        } else if (current.value == 'Yes') {
          addFieldBlocs(fieldBlocs: [
            showSecretField,
            if (showSecretField.value) secretField,
          ]);
        }
      },
    );
  }

  @override
  Future<void> close() {
    whyNotYouLikeFormBloc.close();
    showSecretField.close();
    secretField.close();

    return super.close();
  }
}

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 This is not a package that we support. [Here](https://github.com/GiancarloCode/form_bloc/issues) is the correct place for you to file this issue and receive support !

**Comment by nilesh2211** [comment]
Thanks for the quick response @Gene-Dana
