### ISSUE TITLE
docs: Firebase Login - A superfluous call; or maybe it's a stream-thing?

### ISSUE THREAD

**Issue by KDCinfo** [felangel/bloc#3108]
Hi there, 

I was wondering what the purpose of the line below is in the `main.dart` of the [Firebase Login app example](https://bloclibrary.dev/#/flutterfirebaselogintutorial?id=maindart)? Apologies if it's obvious. I'm only confused because the `user` getter shows it should return a `Stream<User> get user`, but maybe it's doing something Dart-wise that I don't know about (I'm still quite new). 

`await authenticationRepository.user.first;`

It's not being assigned or passed anywhere. Does it kick off the Stream?

**Comment by narcodico** [comment]
Hi @KDCinfo 👋
It's indeed kicking off the stream, ensuring there's a current user when setting up the initial state of our app.

https://github.com/felangel/bloc/blob/033c95260e8f638a32a1733cfd2575e2480e2cd3/examples/flutter_firebase_login/lib/app/bloc/app_bloc.dart#L16

https://github.com/felangel/bloc/blob/033c95260e8f638a32a1733cfd2575e2480e2cd3/examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart#L186

https://github.com/felangel/bloc/blob/033c95260e8f638a32a1733cfd2575e2480e2cd3/examples/flutter_firebase_login/packages/authentication_repository/lib/src/authentication_repository.dart#L194

**Comment by KDCinfo** [comment]
Awesome. Thank you very much!!
