### ISSUE TITLE
Question: What best practice using bloc.

### ISSUE THREAD

**Issue by heshaShawky** [felangel/bloc#3111]
I am refactoring a flutter project that every single page/screen uses many streams components in one bloc!

So, for example, all the streams on the home page are with the home bloc.

Which causes many problems

1. performance as all those streams will load at once ( all of the streams are SQLite queries )
2. not easy to maintain or debug.

So I'm thinking of creating a bloc/cubit for each page component that has its state ( loading, error ..etc ), but that will lead to a lot of boilerplate for a single screen!.

I don't know what the best practice is here using bloc! specially folder structure after this do we move those blocs to screen folder like lib/screens/home/blocs/some_bloc or let it as it's now like lib/blocs/some_bloc

there's no code here to implement I guess as the question is about the best practice to my use case!

**Comment by chonghorizons** [comment]
Check out item number 4 in https://github.com/felangel/bloc/pull/2859#issuecomment-1004018783. In short: one bloc per screen/feature, and put them as low as possible.

Boilerplate is good if it modularizes your code and lets you test each one individually. 

You might also want to use a repo to centralize your SQLite queries. See some opinions here: https://github.com/chonghorizons/flutter_bloc_opinionated_practices/wiki/Opinionated-%22Recommended%22-Practices-for-flutter_bloc

This might also be useful: https://github.com/felangel/bloc/issues/3055

**Comment by heshaShawky** [comment]
> and put them as low as possible

Thanks for replying, 
Do you mean by that few blocs as possible?

And another question, all my app are based on SQL streams that come from the `moor` package and feel hard to maintain due to the blocs as I have to trigger events over and over so the bloc gets updating.

Also and because I'm using many streams in one bloc ( 13 streams for example in only the home page ) if one gets updating all the UI rebuild which is wasting performance!

So my question is do I need to maintain reading the streams with StreamBuilders instead of blocs? or what is the best practice here as well?

**Comment by chonghorizons** [comment]
> > and put them as low as possible
> 
> Thanks for replying, 
> Do you mean by that few blocs as possible?

Low in the widget tree. (Search the issues for widget tree).

> 
> And another question, all my app are based on SQL streams that come from the `moor` package and feel hard to maintain due to the blocs as I have to trigger events over and over so the bloc gets updating.

Look at the writeup about fetch vs stream patterns in the opinionated practice link.

> 
> Also and because I'm using many streams in one bloc ( 13 streams for example in only the home page ) if one gets updating all the UI rebuild which is wasting performance!

Read the docs about rebuilding. You might be architecture your blocs weirdly.

> 
> So my question is do I need to maintain reading the streams with StreamBuilders instead of blocs? or what is the best practice here as well?

Look through the examples. None of them use StreamBuilders.
> 

@heshaShawky
