### ISSUE TITLE
Question: what is the benefit of creating a feature as package

### ISSUE THREAD

**Issue by sekny** [felangel/bloc#3113]
Like in Bloc's document(Login tutorial), it separates authentication as a package instead of creating it in lib folder. can you give a reason or split to make it easily readable?

Thank.

**Comment by alvinvin00** [comment]
so you can reuse the same logic on other apps

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 !

First things first.. the repo itself serves many features, not just one. For example, the `sign up` feature also uses the `auth repo`, and the repo's serve as a domain which exposes the data layer to a particular set of features.

Another point of this is to indicate that this is business product, meaning that it's code that meant be shared across an entire company, as opposed to packages that are made public on pub.dev. 

At first, I felt the same way.. and then, as I came to understand it's purpose and put it into practice, I began to see the merit in this approach.

At the end of the day, it's really about SOLID principles, in particular the 'Single-Responsibility Principle,' and the repo itself truly has separate responsibilities from the feature-layer where bloc's are tightly coupled to the UI.

**Comment by felangel** [comment]
Hi @sekny 👋 
Thanks for opening an issue!

Just want to add on to what others have mentioned -- in my opinion, splitting repositories and data clients into packages have several benefits:

- Creating a package forces you to provide explicit dependencies which makes it easier to maintain a decoupled, reusable library
- Creating a package allows you to reuse that functionality in multiple flutter applications
- Creating a package allows you to improve your CI (you can more efficiently run tests on only things that have changed as opposed to running all tests all the time)
- Creating a package allows you to version the functionality independently of the core application which is especially useful when working on a larger team where the functionality is shared across many codebases/projects (you can even publish the functionality on pub.dev, your own internal pub server, or a separate git repo)

I also highly recommend using [very_good_cli](https://pub.dev/packages/very_good_cli) to create new packages:

```sh
# create a new dart package called my_dart_package
very_good create packages/my_dart_package -t dart_pkg --desc "A new Dart Package"

# create a new flutter package called my_flutter_package
very_good create packages/my_flutter_package -t flutter_pkg --desc "A new Flutter Package"
```

Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with any additional questions and I’m happy to continue the conversation 👍

**Comment by sekny** [comment]
Thank @felangel, @Gene-Dana, and @alvinvin00  for your reply, I got that point.

**Comment by Tokenyet** [comment]
Thanks for the great structure! @felangel , just wanna ask how did you test locally. I just saw [1.20.2-dev](https://github.com/dart-lang/test/blob/master/pkgs/test/CHANGELOG.md#1202-dev) released, and my project have 20+ packages. 

The workaround for me is the test tab from vscode, then I could choose the test. For the case, I wish I could use `flutter test --exclude-tags someTag` or `dart test --exclude-tags someTag` to run all tests included sub-packages.

Any advice would be appreciated!
