### ISSUE TITLE
I am only able to clone some examples, but not all of them.

### ISSUE THREAD

**Issue by lipingx** [felangel/bloc#3114]
Hi, 
I am learning the bloc through the examples, and find that read/navigating the code on github isn't so pleasant. 
So I want to clone the code to my Android Studio, so I can read/study the example code more easily. 
But when I use "git clone git@github.com:lipingx/bloc.git" to clone the code, I can only see several examples, but not the one I want, for example, I am trying to study the flutter_firebase_login, but I couldn't clone it to my computer.
Is this intended or am I missing some steps? Thanks.

**Comment by felangel** [comment]
Hi @lipingx 👋 
Thanks for opening an issue!

When you clone the repo you should get access to all examples. It's hard to say without additional information what the problem you're facing is. A good alternative way would be to use the GitHub UI and just download the repo as a .zip file.

Let me know if that helps 👍

**Comment by lipingx** [comment]
"download the repo as a .zip file" works, thanks a lot. :)
