### ISSUE TITLE
Livestream Topics: What would you like to see implemented by Felix?

### ISSUE THREAD

**Issue by Gene-Dana** [felangel/bloc#3121]
**Description**

It is clear that the community has ongoing questions about specific subjects, and in order to demystify these topics, we have organized a  30 minute livestream of the Bloc team building in public a mini-project of the communities choice.

**Desired Comments**

We need your help generating a a list of mini-projects that the community would like to see implemented. Topics could be: 

- Repository scoping and generation
- How to model correctly
- Adding a new feature to an existing example

**Comment by farhanahmadzade** [comment]
Finished or not started yet?

**Comment by ShashankSMayya** [comment]
The right way to declare and use blocs in route generators and passing instance of this BLOC to multiple pages.

Thanks

More explained doubt:
Let's say I have a BLOC A of same single instance used in 3rd page and also on the 10th page in the app. So, How I was doing this was initializing this BLOC in init state of route generator class and then provide it to the routes that point to 3rd and 10th screen. And have a dispose function that is called in main.dart.  Is this the only right way to do this in route generator or could there be a way when route will only be initialized if it's called the first time by say 3rd page ... in the above example. So that I don't need to initialize all the blocs before their actual use.

**Comment by petrnymsa** [comment]
What about handling more complex forms with "autosuggestions / autocomplete " feature set?

**Comment by hhacker1999** [comment]
In my apps I use a separate bloc for each screen, but some blocs are required to be app level so that the entire app can access it. I want to know how to architect the app in such a way that the screen level blocs communicate with app level blocs without making code spaghetti.

**Comment by salkhan-ops** [comment]
I am interested in knowing more about implementing complex data repositories. For instance, google-map/tracking with/or autocomplete search (cache some data before the search [offline-online], first search in existing-cache and then in firebase or API, if not may rely on cache only). 

QuickNote: Thank you for the great work done by @felangel and the team on [bloc library](https://bloclibrary.dev/). I have learned about the best practices of coding such as using getters, extensions, barrels, models, and error handling from your examples.

**Comment by dbilgin** [comment]
I have always used cubits so far and I never felt that anything is missing, what is a real life scenario for preferring blocs over cubits?

**Comment by CoderUni** [comment]
I'm interested in how to configure bloc for logging and error reporting in firebase crashlytics or in sentry. I'm very interested on how its being configured and used in big projects that have 1M+ users. I would also like to thank you for your hard work Felix. You've made flutter better for everyone in the community :)

**Comment by mnkeis** [comment]
If possible, it would be great to add some flow_builder routing on the run, including back and forth navigation please.

**Comment by mnkeis** [comment]
I also would like to know what could be the best approach to add a confirm dialog for, let's say for example, a logout action.
I mean, how would you add a confirm logout dialog to the firebase login tutorial.

I'm currently simply showing the dialog on the onPressed function itself but I don't know if this is OK from an architecture and good practices point of view.

**Comment by paolovalerdi** [comment]
It would be great to see some cubit/bloc implementation of side effects and one time events like showing snack bars for example.

**Comment by adam-sroka** [comment]
Hi,

For us at [Gibsonify](https://github.com/DigitalNutritionalAssessment/gibsonify), we would be really grateful for going over the [BLoC architecture](https://bloclibrary.dev/#/architecture) in a less abstract way, with _more examples_ of some BLoC/Repository design diagrams for different types of apps, especially with mutliple BLoCs.

I think this would encompass @hhacker1999's request of how to lay out multiple BLoCs across different screens and their communication, plus also how to architecture a the data layer (repository & API) to communicate with these multiple BLoCs (maybe that's what is also covered by "Repository scoping and generation" in @Gene-Dana's comment).

Thanks so much for all the work on BLoC and the support 💙!

<br>
<br>

_More detail:_

Even though the [architecture](https://bloclibrary.dev/#/architecture) tutorial gives an abstract overview of BLoC architecture and the app tutorials (especially the new [flutter todos example](https://github.com/felangel/bloc/pull/2859) give examples of simple implementations, there are not many resources on architecting a more complex app with multiple BLoCs and a repository and how they should communicate. This would not require going over the code, just examples of architecture diagrams of BLoCs and a Repository (+API) and how they communicate, ideally for a variety of different apps.

For example, we have a [simple app](https://github.com/DigitalNutritionalAssessment/gibsonify) with multiple screens and BLoCs that handle different forms of data and need to pass the data between themselves and also save it to a repository that saves them to local storage, and we're already feeling a little lost about how to architect it 🤷‍♂️.

**Comment by SaltySpaghetti** [comment]
Hi everyone. In my app a have a Cubit that listens whenever your phone is connected to internet or not. In the UI I have a `BlocListener` that shows a Dialog when the state is `Disconnected`. Is there a way to perform `,pop()` (close the dialog) when the state is `Connected`?

**Comment by fabianMendez** [comment]
I have a simple question: should the `started` event be added in the constructor (automatically) or should it be added after creating the bloc (using the cascade operator)?

**Comment by felangel** [comment]
> I have a simple question: should the `started` event be added in the constructor (automatically) or should it be added after creating the bloc (using the cascade operator)?

I recommend adding it after the bloc is created via the cascade operator because it is more predictable, flexible, and easier to test.

**Comment by jinyus** [comment]
> I have always used cubits so far and I never felt that anything is missing, what is a real life scenario for preferring blocs over cubits?

When you need to debouce the events. eg: When you have a search bar that sends the request after the user stops typing.

**Comment by rohan20** [comment]
Using sub-classes for states vs using `copyWith`.

When using sub-classes, it is difficult to build UIs that require loading states as overlays over the rest of the UI because this means that 2 states require all state fields from the UI.

For example:

```dart
yield OrdersPlacementInProgressState(order: order);
yield LoadingState(order: order);
yield OrdersPlacedState(order: order);
```

Here we just have one field `order` that needs to be repeated in all states but in case `OrdersPlacementInProgressState` has many such fields like `order, deliveryDate, deliveryTime, deliveryNotes`, then they'd all have to be repeated for `LoadingState` and `OrdersPlacedState` as we want these 2 states to still show the information from the first state.

For this, we used a single state class using `copyWith` approach:

```dart
class OrderPlacedState {
  final Order order;
  final bool isLoading;
  final bool isError;

  OrderPlacedState({@required this.order, this.isLoading = false, this.isError = false});

  OrderPlacedState copyWith({Order order, bool isLoading, bool isError}) {
    return OrderPlacedState(
      order: order ?? this.order,
      isLoading: isLoading ?? this.isLoading,
      isError: isError ?? this.isError,
    );
  }
}
```

When using `copyWith`, we realised that showing one-off things via `BlocListener` such as snackbars becomes a bit hacky since we use it like this:

```dart
  OrderPlacedState copyWith({Order order, bool isLoading, bool isError}) {
    return OrderPlacedState(
        ...
      showOrderPlacementFailedMessage: showOrderPlacementFailedMessage ?? false,
    );
  }
```

Is this the right way to go about it? Any alternatives?

Thank you! ⭐

**Comment by ebelevics** [comment]
Is it possible to send EventA which extends abstract class Event. And listen on two or more different Blocs: BlocA<Event, StateA> and BlocB<Event, StateB> with on<EventA>((event, emit)? I saw this concept in Unity with `public static event Action<T>` and it seems pretty flexible way to share events with blocs?

**Comment by fernan542** [comment]
When and where is the proper time to use a Repository layer versus just directly accessing the Data Provider layer?

**Comment by Skhendle** [comment]
Hi @Gene-Dana and @felangel,

I have been learning and using a lot of the Bloc library. I also want to try out contributing to open source within my stack(Flutter). 

I was wondering if I can work on improving this [https://github.com/Skhendle/north-wind-api-flutter-ui](project) which use's the bloc library. 

I believe I can update and refactor it to meet the requirements
[x] Repository scoping and generation
[x] How to model correctly
[x] Adding a new feature to an existing example

Is it a good idea to try out?

**Comment by felangel** [comment]
Closing this for now since I don't have the time to spend on organized live streams at currently. I'll revisit this thread in the future once I'm a bit more free.
