### ISSUE TITLE
Question:BLOC suitability for common global assets (dynamic in nature)

### ISSUE THREAD

**Issue by yashhema** [felangel/bloc#3128]
Consider a case , I have multiple firebase projects, and I need to maintain auth state of all , and the project list is dynamic is nature (the same UI can be then reused for different project)
or consider a case of chatrooms , where chatrooms can be created anytime by backend and a bloc needs to be maintained for state

So is it a good practice to have a singleton with a Map of project id and corresponding bloc state , any time someone wants to look at the state they can just look in the map,
similarly for the chat room.

Please do suggest.

**Comment by felangel** [comment]
Hi @yashhema 👋 
Thanks for opening an issue!

I don't think there's enough information to provide a solid recommendation. One example you can refer to is https://verygood.ventures/blog/very-good-location-sharing-chat-app.

Closing for now but feel free to comment with any outstanding questions and I'm happy to continue the conversation 👍
