### ISSUE TITLE
feat(flutter_bloc): buildWhen/selectWhen in BlocSelector

### ISSUE THREAD

**Issue by bornold** [felangel/bloc#3130]
First of all thank you so much for all the fantastic work you guys does!

**Description**
I am missing a similar check to BlocBuilder's [`buildWhen`](https://github.com/felangel/bloc/blob/4e1cfbb8ffafaa239c6c94e88844f985b5704a63/packages/flutter_bloc/lib/src/bloc_builder.dart#L80) in [BlocSelector](https://github.com/felangel/bloc/blob/master/packages/flutter_bloc/lib/src/bloc_selector.dart)

**Desired Solution**
Adding a `selectWhen` to blocSelector,
like so: https://github.com/bornold/bloc/commit/c91d9eb7b2ff0b94f11bcbd63f2d4ac9d2d4907d

**Alternatives Considered**
Could also make the selector return nullable type that won't call build when null is return.
(Don't like this)

I would love to open a PR if this is something that is wanted

**Comment by narcodico** [comment]
Hi @bornold 👋

The `selector` is already filtering the state and prevents unnecessary rebuilds.

So basically
```
class Status extends StatelessWidget {
  const Status({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocSelector<AppBloc, AppState, AppStatus>(
      selector: (state) => state.status,
      builder: (context, status) {
        return Text('$status');
      },
    );
  }
}
```
is equivalent to 
```
class Status extends StatelessWidget {
  const Status({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<AppBloc, AppState>(
      buildWhen: (previous, current) => previous.status != current.status,
      builder: (context, state) {
        return Text('${state.status}');
      },
    );
  }
}
```

Could you give a realistic example when you'd also need a `selectWhen` and how would you make use of it ?

**Comment by bornold** [comment]
Thanks for the quick response.
Maybe it is a really niche problem and not really needed for any one else...
But the issue I am having is not that build is called unnecessary, it's when the state equals is really slow and/or selector is a has to do work that could be prevented by a guard.

Specifically `DateTime` compare and equals is really slow

In this example a cubit outputs a random date, and we don't want to do anything in the selector if the random date is outside the range of the List of dates which is calculated the max value before


```dart
class RandomDateCubit extends Cubit<DateTime> {
  RandomDateCubit() : super(DateTime(0)) {
    Stream.periodic(const Duration(seconds: 1), (i) => i).listen(
      (i) => emit(DateTime(0, 0, Random().nextInt(100))),
    );
  }
}

class LostOfDates extends Equatable {
  final List<DateTime> dates;
  final DateTime maxDate;
  LostOfDates(this.dates)
      : maxDate = dates.reduce((d1, d2) => d1.isBefore(d2) ? d2 : d1);
  @override
  List<Object?> get props => dates;
}

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: BlocProvider(
        create: (context) => RandomDateCubit(),
        child: Scaffold(
          body: GridView.count(
            crossAxisCount: 10,
            children: [
              for (var i = 0; i < 1000; i++)
                CounterView(
                  LostOfDates(
                    [
                      for (var i = 0; i < 1000; i++)
                        DateTime(0, 0, Random().nextInt(100) + 50),
                    ],
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}

class CounterView extends StatelessWidget {
  final LostOfDates dates;
  const CounterView(this.dates, {Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return BlocSelector<RandomDateCubit, DateTime, List<DateTime>>(
      // selectWhen: (_, r) => r <= dates.max,
      selector: (random) {
        // Here, both the state equals and the selector is really slow
        // and we don't wan't to do unnecessary
        return dates.dates.where((value) => value.isAfter(random)).toList();
      },
      builder: (context, state) {
        return Text('${state.length}');
      },
    );
  }
}

```

Im sorry I could not think of a better example, but this is kinda close to what my own case.
Then again it could be that it's just the architecture that is really

**Comment by bornold** [comment]
After some deliberating, I now believe I am just using the BlocSelector incorrectly.

Thanks for taking the time for the proposal though

**Comment by narcodico** [comment]
You should just move computational/data aggregation stuff inside your bloc instead of doing it in the UI.
