### ISSUE TITLE
fix:  diff_match_patch ^0.4.1 is forbidden

### ISSUE THREAD

**Issue by mehade369** [felangel/bloc#3135]
**Description**
Can't run `flutter_todos` example app. 
It's a fresh clone of the [flutter_todos](https://github.com/felangel/bloc/tree/master/examples/flutter_todos) example app. 

**Error**: 
```
[flutter_todos] flutter pub get
Running "flutter pub get" in flutter_todos...                   
Because no versions of diff_match_patch match 0.4.1 and no versions of diff_match_patch match >0.4.1 <0.5.0, diff_match_patch ^0.4.1 is forbidden.
So, because flutter_todos depends on bloc_test ^9.0.1 which depends on diff_match_patch ^0.4.1, version solving failed.
pub get failed (1; So, because flutter_todos depends on bloc_test ^9.0.1 which depends on diff_match_patch ^0.4.1, version solving failed.)
exit code 1
```

**Comment by mehade369** [comment]
`flutter doctor` results 

```
mehade@manjaro ~/D/flutter_todos> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on Manjaro Linux 5.10.89-1-MANJARO, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] VS Code
[✓] Connected device (2 available)

• No issues found!
```

**Comment by felangel** [comment]
Hi @mehade369 👋 
Thanks for opening an issue!

I'm not sure why you're seeing that error because `diff_match_patch: 0.4.1` is available on pub.dev https://pub.dev/packages/diff_match_patch. Are you pointing to a different pub.dev server by any chance?

**Comment by mehade369** [comment]
> Hi @mehade369 👋 
> Thanks for opening an issue!
> 
> I'm not sure why you're seeing that error because `diff_match_patch: 0.4.1` is available on pub.dev https://pub.dev/packages/diff_match_patch. Are you pointing to a different pub.dev server by any chance?

No, I don't think so.
And, everything else is working fine.

**Comment by felangel** [comment]
> > Hi @mehade369 👋
> > Thanks for opening an issue!
> > I'm not sure why you're seeing that error because `diff_match_patch: 0.4.1` is available on pub.dev https://pub.dev/packages/diff_match_patch. Are you pointing to a different pub.dev server by any chance?
> 
> No, I don't think so. And, everything else is working fine.

Are you able to install `diff_match_patch` in a different project? For example if you create a new project and add it to the `pubspec.yaml`

```yaml
dependencies:
  diff_match_patch: ^0.4.1
```

Do you get the same error?

**Comment by mehade369** [comment]
Yes, I get the same error. 
Here I found a possible solution!! 

```
dependency_overrides: 
  diff_match_patch: ^0.4.0
```

**Comment by felangel** [comment]
> Yes, I get the same error. Here I found a possible solution!!
> 
> ```
> dependency_overrides: 
>   diff_match_patch: ^0.4.0
> ```

That seems like a bug in `pub.dev` since it should be able to resolve diff_match_patch v0.4.1. I highly recommend [opening an issue on pub.dev](https://github.com/dart-lang/pub-dev/issues/new?body=URL%3A+https%3A%2F%2Fpub.dev%2F%0A%0A%3CDescribe+your+issue+or+suggestion+here%3E&title=%3CSummarize+your+issues+here%3E&labels=Area%3A+site+feedback).

**Comment by mehade369** [comment]
ok, thanks.
