### ISSUE TITLE
question: Using BlocBuilder will cause me to lose part of the state.

### ISSUE THREAD

**Issue by HSCOO** [felangel/bloc#3138]
**Version**
`Flutter 2.5.3`
`Dart 2.14.4`
`flutter_bloc: ^8.0.1`
`equatable: ^2.0.3`

**My usage**
I used to only use `BlocBuilder` at first and I found a problem that I would miss part of the state.

The code I use in the widget is like this:

```dart
class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<TestBloc, TestInitial>(
      buildWhen: (previous, current) =>
          previous.testA != current.testA || previous.testB != current.testB,
      builder: (context, state) {
        debugPrint("========builder testA=${state.testA} testB=${state.testB}");
        if (state.testA == "1") {
          // do something
        } else if (state.testA == "2") {
          // do something
        }
        return const Center(
          child: Text("hello world!"),
        );
      },
    );
  }
}
```
The code I use in bloc.dart is like this:
```dart
class TestBloc extends Bloc<TestEvent, TestInitial> {
  TestBloc() : super(const TestInitial()) {
    on<TestInitialEvent>(_onTestInitial);
  }

  Future<void> _onTestInitial(
    TestInitialEvent event,
    Emitter<TestInitial> emit,
  ) async {
    emit(state.copyWith(testA: "1"));
    // some future function
    await aFunc();
    emit(state.copyWith(testA: "2"));
  }
}
```
If `aFunc` executes fast enough, below 5ms, I will not get `state.testA=1` in`BlocBuilder`.

**Problem reproduces**

It seems that `BlocBuilder` does not fit my usage scenario, I guess `BlocBuilder` is optimized to avoid multiple refreshes. I used the `BlocListener` and `BlocConsumer` again to verify my guess.

The code I use in bloc.dart is like this:
```dart
class TestBloc extends Bloc<TestEvent, TestInitial> {
  TestBloc() : super(const TestInitial()) {
    on<TestInitialEvent>(_onTestInitial);
  }

  Future<void> _onTestInitial(
    TestInitialEvent event,
    Emitter<TestInitial> emit,
  ) async {
    emit(state.copyWith(testA: "1"));
    await Future.delayed(const Duration(milliseconds: 16));
    emit(state.copyWith(testA: "2"));
    await Future.delayed(const Duration(milliseconds: 16));
    emit(state.copyWith(testB: "1"));
    emit(state.copyWith(testB: "2"));
  }
}
```

The code I use in the widget is like this:

```dart
class TestPage extends StatelessWidget {
  const TestPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocConsumer<TestBloc, TestInitial>(
      listenWhen: (previous, current) =>
          previous.testA != current.testA || previous.testB != current.testB,
      listener: (context, state) {
        debugPrint(
            ">>>>>>>>listener testA=${state.testA} testB=${state.testB}");
      },
      buildWhen: (previous, current) =>
          previous.testA != current.testA || previous.testB != current.testB,
      builder: (context, state) {
        debugPrint("========builder testA=${state.testA} testB=${state.testB}");

        return Scaffold(
          body: Center(
            child: CupertinoButton(
                color: Colors.amber,
                child: const Text("test bloc"),
                onPressed: () {
                  context.read<TestBloc>().add(TestInitialEvent());
                }),
          ),
        );
      },
    );
  }
}
```
On click of the button, I get the log output:

```shell
2022-01-13 17:04:59.896116+0800 Runner[82967:2754801] flutter: >>>>>>>>listener testA=1 testB=
2022-01-13 17:04:59.901139+0800 Runner[82967:2754801] flutter: ========builder testA=1 testB=
2022-01-13 17:04:59.906262+0800 Runner[82967:2754801] flutter: >>>>>>>>listener testA=2 testB=
2022-01-13 17:04:59.914028+0800 Runner[82967:2754801] flutter: ========builder testA=2 testB=
2022-01-13 17:04:59.922181+0800 Runner[82967:2754801] flutter: >>>>>>>>listener testA=2 testB=1
2022-01-13 17:04:59.922388+0800 Runner[82967:2754801] flutter: >>>>>>>>listener testA=2 testB=2
2022-01-13 17:04:59.932524+0800 Runner[82967:2754801] flutter: ========builder testA=2 testB=2
```
If I shorten the interval, the builder only has the last state.
```dart
await Future.delayed(const Duration(microseconds: 100));
```
```shell
2022-01-13 17:02:47.833538+0800 Runner[82967:2754801] flutter: >>>>>>>>listener testA=1 testB=
2022-01-13 17:02:47.834390+0800 Runner[82967:2754801] flutter: >>>>>>>>listener testA=2 testB=
2022-01-13 17:02:47.839853+0800 Runner[82967:2754801] flutter: >>>>>>>>listener testA=2 testB=1
2022-01-13 17:02:47.840080+0800 Runner[82967:2754801] flutter: >>>>>>>>listener testA=2 testB=2
2022-01-13 17:02:47.842686+0800 Runner[82967:2754801] flutter: ========builder testA=2 testB=2
```

**My question**
1. Using `BlocBuilder` will cause me to lose part of the `state`. Although I can listen to all the `states` using `BlocListener`, I cannot use it to change the `widget`.
2. An event triggers a series of interfaces. Is it necessary for me to store the results of each interface in `state`? At present, only the data that the `widget` cares about is saved in the `state`.

**Comment by felangel** [comment]
Hi @HSCOO 👋 
Thanks for opening an issue!

> Using BlocBuilder will cause me to lose part of the state. Although I can listen to all the states using BlocListener, I cannot use it to change the widget.

This is because your bloc is emitted states faster than flutter can rebuild. You should probably refactor your bloc state to aggregate the data if it's critical that you render each state.

> An event triggers a series of interfaces. Is it necessary for me to store the results of each interface in state? At present, only the data that the widget cares about is saved in the state.

With your current approach you'll need to aggregate the data although I highly recommend splitting this into two blocs if the properties for 'testA' are independent of 'testB'.

`buildWhen` is just there for optimization but it does not guarantee that the `builder` will not be called. You shouldn't rely on it for logic like this and instead it'd be much simpler to split this into two blocs (one that manages the state for A and another than manages the state for B).

Hope that helps! 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍

**Comment by erlangparasu** [comment]
@HSCOO

Try using `WidgetBinding` in widget State. Eg:

```dart
@override
void initState() {
  super.initState();
  WidgetsBinding.instance.addPostFrameCallback((duration) async {
    await context.read<MyCustomCubit>().onInit();
  });
}
```
