### ISSUE TITLE
docs: dedicated page for explaining read, select and watch methods

### ISSUE THREAD

**Issue by JanDrabik** [felangel/bloc#3141]
### Problem:
The only place to find good explanation on what `context.read`, `context.select` and `context.watch` methods are for is migration page that covers [migration to version 6.1.0](https://bloclibrary.dev/#/migration?id=v610). This might be problematic for newcomers that are trying to better understand how to use these methods, especially these ones without experience of working with Provider package, which from these methods are named from. Aside to that, typing 'read', 'select' or 'watch' in search bar does not provide good search results; without knowledge where to look for answers (migration page mentioned above) it's basically impossible to find explanation.

### Solution:
Create dedicated page that will cover what for these methods are, what is their origin and maybe some use cases.

**Comment by alestiago** [comment]
Thanks @JanDrabik ! 

This is a great suggestion. I will try to write something up and make a PR for it. Hopefully, it resolves confusion over the extension methods.

**Comment by alestiago** [comment]
@JanDrabik I've started the PR. This is still under development. Feel free to suggest feedback or pointers that can improve the documentation.
