### ISSUE TITLE
question: bloc-to-bloc communication - initial state

### ISSUE THREAD

**Issue by FisherWL** [felangel/bloc#3142]
**Description**
bloc1: AdsBloc - controlling admob;
bloc2: PurchaseBloc - controlling in-app-purchase;

AdsBloc is reacting to PurchaseState change(s),
but not reacting to initial PurchaseState.

**Steps To Reproduce**
with the following code, no matter if the user is paid or unpaid,
the AdsState is sticking to AdsLoadInitial when the app launches.

```dart
class AdsBloc extends Bloc {
  final PurchaseBloc purchaseBloc;
  late final StreamSubscription purchaseBlocSubscription;

  AdsBloc(this.purchaseBloc) : super(AdsLoadInitial) {
    purchaseBlocSubscription = purchaseBloc.stream.listen((purchaseState) {
      if (purchaseState.status.isPaid) {
        add(AdsCancelled);
      }
          if (purchaseState.status.isNotPaid) {
        add(AdsLoaded);
      }
    });
    ...
    ...

  }

  @override
  Future<void> close() {
    purchaseBlocSubscription.cancel();
    return super.close();
  }
}
```

**Expected Behavior**
How to make AdsBloc grab the purchase info at the very beginning, even if PurchaseBloc is provided before AdsBloc in the tree?

**Comment by felangel** [comment]
Hi @FisherWL 👋 
Thanks for opening an issue!

Upon subscribing to a bloc you'll only get notified of subsequent state changes. If you also want to include the current state you can do something like:

```dart
_onPurchase(purchaseBloc.state);
purchaseBlocSubscription = purchaseBloc.stream.listen(_onPurchase);

...

void _onPurchase(purchaseState) {
  if (purchaseState.status.isPaid) {
    add(AdsCancelled);
  }
  if (purchaseState.status.isNotPaid) {
    add(AdsLoaded);
  }
}
```

Alternatively you can use `startWith` from `package:rxdart` like:

```dart
purchaseBlocSubscription = purchaseBloc.stream.startWith(purchaseBloc.state).listen(_onPurchase);
```

Hope that helps 👍

**Comment by FisherWL** [comment]
Thx @felangel 
this is very helpful!
