### ISSUE TITLE
feat: Ability to apply a transformer to all events

### ISSUE THREAD

**Issue by Amir-P** [felangel/bloc#3143]
**Description**

Recently I started using bloc v8 and bloc_concurrency and I noticed that in this new version there is no way (or at least I couldn't find any way) to apply a transformer to all incoming events. Right now we can do something like this:

```dart
MyBloc(this.useCase) : super(const MyBlocState()) {
  on<Event1>(_event1);
  on<Event2>(_event2, transformer: debounced());
}
```

But what if we wanted to apply restartable transformer to all events?

**Desired Solution**

Ability to define global transformers.

**Comment by felangel** [comment]
Hi @Amir-P 👋 
Thanks for opening an issue!

If you want to apply a transformer to multiple events you must group the events together. In this case, if you want all events to be `restartable` then you could do:

```dart
MyBloc(this.useCase) : super(const MyBlocState()) {
  on<Event>(_onEvent, transformer: restartable());
}

FutureOr<void> _onEvent(Event event, Emitter<State> emit) {
  if (event is Event1) return _onEvent1(event, emit);
  if (event is Event2) return _onEvent2(event, emit);
}
```

You can read more about this [here](https://verygood.ventures/blog/how-to-use-bloc-with-streams-and-concurrency).

Hope that helps 👍

**Comment by Amir-P** [comment]
Thanks for your response @felangel .

That's something I thought about but doesn't we lose the ability to apply transformers on specific events? For example I want to be able to apply debounce on a specific type of events and apply restartable on all events. How this is achievable?

**Comment by felangel** [comment]
> Thanks for your response @felangel .
> 
> That's something I thought about but doesn't we lose the ability to apply transformers on specific events? For example I want to be able to apply debounce on a specific type of events and apply restartable on all events. How this is achievable?

No problem! You can write a transformer that handles applying the correct transformer depending on the event type. See https://github.com/felangel/bloc/blob/10542d868fb0d615e1f7afba9d6a5af39a221bca/packages/bloc/test/blocs/counter/merge_bloc.dart#L6 for an example.

**Comment by Amir-P** [comment]
Thanks @felangel ! It really helped.
