### ISSUE TITLE
Bad state: Cannot add new events after calling close 

### ISSUE THREAD

**Issue by mohmmad47** [felangel/bloc#3147]
**Description**
so there are three features which are executed, basically like tab so when we ran app for first time it works normally but when i go on third and again on first or second tab it starts crashing there blocs i dont know why but when i haven't create third bloc they(second and third tab bloc) works fine and in error it is telling 'Bad state: Cannot add new events after calling close' i have searched but i didn't found any solution i have attached some screenshots 

**Screenshots**
errors
![Screenshot (2)](https://user-images.githubusercontent.com/87911619/149871703-d4022eb5-b0ea-4269-ba22-eb017d1cbe68.png)
this is 1 tab 
![code1](https://user-images.githubusercontent.com/87911619/149872345-f95327a2-8a55-410e-bfd6-1f6617b53edf.png)
this is 2 tabs 1 part
![angle](https://user-images.githubusercontent.com/87911619/149872504-cfe1c920-5094-4356-bc84-8a7da51c2ab0.png)
this is second tab
![qibla](https://user-images.githubusercontent.com/87911619/149872530-081541fe-b954-4eef-811f-02a6b3846755.png)
this is location cubit it gives location to both 1 and 2 bloc 
![location](https://user-images.githubusercontent.com/87911619/149872622-de576f63-18c6-4ea7-9f6f-b14aa8e9aaa2.png)
this is and small address widget 
![locdetail](https://user-images.githubusercontent.com/87911619/149872562-7eea4e42-4b18-4db6-ac23-c458f29024a2.png)
and final third widget 
![sujra](https://user-images.githubusercontent.com/87911619/149872658-f0277018-2226-4d72-bd8c-ce2fbd678f1a.png)

and this is get it
```
// bloc/cubit
  sl.registerLazySingleton<NamazTimeCubit>(() => NamazTimeCubit(sl()));

  sl.registerLazySingleton<SujraSharifCubit>(() => SujraSharifCubit(sl()));

  sl.registerLazySingleton<LocationdetailCubit>(() => LocationdetailCubit());

  sl.registerLazySingleton<QiblaBloc>(() => QiblaBloc());

  sl.registerLazySingleton<AngleBloc>(() => AngleBloc(sl()));

  sl.registerLazySingleton<LocationCubit>(() => LocationCubit(sl(), sl()));

  // usecase
  sl.registerLazySingleton<GetSujraSharifList>(() => GetSujraSharifList(sl()));

  sl.registerLazySingleton<GetNamazTimeList>(() => GetNamazTimeList(sl()));

  sl.registerLazySingleton<GetLocation>(
      () => GetLocation(locationRepository: sl()));

  // repository
  sl.registerLazySingleton<SujraRepository>(() => SujraRepositoryImpl(sl()));

  sl.registerLazySingleton<NamazTimeRepository>(
      () => NamazTimeRepositoryImpl(sl()));

  sl.registerLazySingleton<LocationRepository>(
      () => LocationRepositoryImpl(sl()));

  // external

  sl.registerFactory<SujraDataSource>(() => SujraDataSourceImpl());

  sl.registerFactory<NamazRemoteDataSource>(() => NamazRemoteDataSourceImpl());

  sl.registerFactory<LocationDataSource>(() => LocationDataSourceImpl());
```

**Comment by felangel** [comment]
Hi @mohmmad47 👋 
Thanks for opening an issue!

This is because you are using a singleton for the blocs and cubits and if you provide them with BlocProvider they will automatically be closed when BlocProvider is unmounted. I recommend not mixing BlocProvider with get_it but the immediate fix would be to change the bloc/cubit registrations to be factories instead of lazy singletons.

Hope that helps 👍

**Comment by mohmmad47** [comment]
hii Felix sorry for being unprofessional i have just realized that pasting screenshot was not really good idea and really thank you for your advise it works and also thank you for creating such amazing package for state management ❤️
