### ISSUE TITLE
feat: HydrateCubit/Bloc should listen to change in saved data

### ISSUE THREAD

**Issue by ChauCM** [felangel/bloc#3150]
**Description**
I actually try to use HydrateCubit as my local database. Everything work fine except I need it to work inside handler in FirebaseMessaging.onBackgroundMessage(handler). The [docs](https://firebase.flutter.dev/docs/messaging/usage) requires handler is a top-level function(if not, result in Null check operator used on a null value on Android device) that mean I cannot pass anything to it. 

I really hope I can do something just like
```
Future<void> handler(RemoteMessage message) async {
  if (message.data['type'] == 'newUsers') {
    final storage = await HydratedStorage.build(
        storageDirectory: await getApplicationSupportDirectory());
    HydratedBlocOverrides.runZoned(() {
      LocalDataCubit localDataCubit = LocalDataCubit();
      localDataCubit.newUser(message.data['newUser']);
    }, storage: storage);
  }
}
```
and also my main 
```
void main() async {
  final storage = await HydratedStorage.build(
      storageDirectory: await getApplicationSupportDirectory());
  HydratedBlocOverrides.runZoned(
      () => runApp(
            MultiBlocProvider(
              providers: [
                BlocProvider<LocalDataCubit>(
                  create: (BuildContext context) => LocalDataCubit(),
                ),
              ],
              child: const MyApp(),
            ),
          ),
      storage: storage);
}

```

**Desired Solution**

With the same storage path(runzone?) localDataCubit1 and localDataCubit2 should emit the same state at the same time wherever one of the two call a function,
LocalDataCubit localDataCubit1 = LocalDataCubit();
LocalDataCubit localDataCubit2 = LocalDataCubit();

**Comment by federicodesia** [comment]
Duplicated of #2633

**Comment by felangel** [comment]
Closing in favor of #2633
