### ISSUE TITLE
feat: Add a way to allocate multiple listeners in a single BlocListener/BlocConsumer widget

### ISSUE THREAD

**Issue by dzsonni** [felangel/bloc#3155]
**Description**

Offer a way to assign multiple independent listeners with their own listenWhen conditions to a single BlocListener/BlocConsumer.

**Desired Solution**

Creating a new widget like MultiblocListener, that would take a list of BlocListenerConditons and BlocListeners combined. But instead of creating a nested widget it would iterate over the list and when conditions are fulfilled it would call them. 
**Alternatives Considered**

It is already possible to build this with using a list of functions for listenwhen and a list of functions for execution. But it adds considerable amount of boilerplate for something that could be solved easily in the widget.

**Additional Context**

My main consideration is having  a better way to structure listeners, by separating them for the different conditions they are executed upon. The alternative is a multiple nested widgets or multibloclistener which is basically just nested widgets simplified. I am not aware if there are any limitations that make it necessary for the listeners to be nested widgets.
Main advantage over MultiBlocListeners is that you no longer need to specify the type for bloc and state, as they are inherited from their respective parents BlocListener and BlocConsumer

**Comment by felangel** [comment]
Hi @dzsonni 👋
Thanks for opening an issue!

Can you please share a code snippet to illustrate your desired solution? I’m not sure I fully understand the request.

Thanks!

**Comment by dzsonni** [comment]
Not necessarily my desired solution but the desired way for it to work. 
Suppose we have something like:
`class ConditionalListener<T> {
  final bool Function(T previousState, T nextState) condition;
  final void Function(T state) listener;

  ConditionalListener(this.condition, this.listener);
}`

I imagine using it like this:
Setup part:
` List<ConditionalListener<ShortOfferFeedbackState>> listeners = [
    ConditionalListener((previousState, nextState) => true, (state) => log(state.toString())),
    ConditionalListener((previousState, nextState) => true, (state) => log(state.toString())),
    ConditionalListener((previousState, nextState) => true, (state) => log(state.toString())),
  ];
  List<int> trueIndices = [];`

And usage in a consumer:
`BlocConsumer<ShortOfferFeedbackBloc, ShortOfferFeedbackState>(
      listenWhen: (previous, current) {
        trueIndices.clear();
        for (int index = 0; index < listeners.length; index++) {
          if (listeners[index].condition(previous, current)) {
            trueIndices.add(index);
          }
        }
        return trueIndices.isNotEmpty;
      },
      listener: (context, state) {
        for (int index in trueIndices) {
          listeners[index].listener(state);
        }
      },
      builder: (context, state) => Container(),
    );`

Basically what I would like is to have multiple listeners with each their respective conditions. I can't do this in one listener without these external elements because in the listener I have no access to know why the listener is invoked. Some concrete usecases for these would be: a filterable list, that has search, some user editable filtering criteria, sorting and deleting. Now if we add pagination to this I already have a lot of nested listener, one listener waiting for new pages to add to pagingcontroller, another listener waiting to remove an element from the list in case of delete (Ideally we don't want to refresh the list when deleting), a listener to refresh the list when the filters change.

I might be over complicating things, I just thought it would be nice to have a way to conditionally invoke listeners without adding multiple nested widgets into the tree when they apply to the same bloc/state type

**Comment by felangel** [comment]
Hi @dzsonni 👋 
You should be able to use a MultiBlocListener to achieve this:

```dart
MultiBlocListener(
  listeners: [
    BlocListener<ShortOfferFeedbackBloc, ShortOfferFeedbackState>(
      listenWhen: (previous, current) {...},
      listener: (context, state) {...},
    ),
    BlocListener<ShortOfferFeedbackBloc, ShortOfferFeedbackState>(
      listenWhen: (previous, current) {...},
      listener: (context, state) {...},
    ),
    BlocListener<ShortOfferFeedbackBloc, ShortOfferFeedbackState>(
      listenWhen: (previous, current) {...},
      listener: (context, state) {...},
    ),
  ],
  child: BlocBuilder<ShortOfferFeedbackBloc, ShortOfferFeedbackState>(
    builder: (context, state) {...},
  ),
)
```

Let me know if that helps 👍

**Comment by dzsonni** [comment]
My initial reason for requesting for this feature is to remove the bloat that is MultiBlocListener. Not only does it deepen the tree for a screen it also has no support for providing blocs on the spot, requiring the use of BlocProviders. Also it adds a lot of bloat as the type of bloc and the type of state could be inferred. I will just try to use listenWhen to invoke the listeners on the spot as a side effect for the conditional evaluation so I can get rid of the index array. and leaving listener itself empty as a hack.

**Comment by felangel** [comment]
> Not only does it deepen the tree for a screen

`MultiBlocListener` adds a single level of indentation to the tree regardless of the number of listeners.

> it also has no support for providing blocs on the spot, requiring the use of BlocProviders.

This is intentional because if the widget provided and consumed the bloc then you've tightly coupled the two and cannot easily test with a mock instance.

> Also it adds a lot of bloat as the type of bloc and the type of state could be inferred

You can easily create your own widget as you mentioned and customize the behavior/public API as you see fit.
