### ISSUE TITLE
feat: Freezed support for IntelliJ plugin

### ISSUE THREAD

**Issue by Ben-Baert** [felangel/bloc#3160]
**Description**

IntelliJ plugin doesn't support generating BLoCs with freezed, while this is supported in the VS Code plugin.

**Desired Solution**

Add an option to the create dialog (underneath "Use equatable"?) to be able to use freezed.

**Alternatives Considered**

None

**Additional Context**

None.

**Comment by mitas** [comment]
bump 🍻

**Comment by derekedelaney** [comment]
+1

**Comment by ChiPhanTlm** [comment]
+2

**Comment by piwai44** [comment]
+3

**Comment by EArminjon** [comment]
Seems to be available today.
