### ISSUE TITLE
A couple of problems with the TODOs tutorial.

### ISSUE THREAD

**Issue by komapeb** [felangel/bloc#317]
Just a couple of small problems on https://felangel.github.io/bloc/#/fluttertodostutorial, that newcomers might find hard to tackle.

1. ~~Missing implementation of `ExtraAction` `enum` (I suppose it should go in the `models` dir under the filename `extra_actions.dart` and then be exported via `models.dart`~~ Edit: actually the implementation is already present in the repository, it's just that it isn't mentioned anywhere in the actual tutorial page.

2. The files `flutter_todos_keys.dart` and `localization.dart` are both in the repository of the tutorial but are not mentioned anywhere on the actual page.

Apart from that, I just want to say BIG thanks and great job. I highly appreciate the time and effort put into this piece.

**Comment by felangel** [comment]
Hi @komapeb 👋 
Thanks so much for opening an issue and for the positive feedback!

I've tried to address your feedback in https://github.com/felangel/bloc/commit/17ba340b2232fe47dd6a069596ad1016dafcbeb6.

You should be able to refresh the tutorial documentation and see the new sections for keys and localization as well as the `ExtraAction` enum definition.

Thanks again 💯

**Comment by komapeb** [comment]
@felangel quick to react! Maybe a bit too quick - missing a closing bracket for `class FlutterTodosKeys` in the code block for the keys... but I'm sure that's intentional, as one should always practice debugging such simple issues 😄

**Comment by felangel** [comment]
@komapeb that was my bad 😅 

Thanks for catching that...should be all good now 👍
