### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by br-allstreet** [felangel/bloc#3177]
Is it possible to access a repository from the build context of a widget without that widget being built based on a bloc? Essentially, is there a way to call the equivalent of `context.read<MyRepository>()` without the BlocBuilder?

**Comment by ultimate-tester** [comment]
Hi there! Yes it's perfectly possible but you cannot use the extension method. Try this:

RepositoryProvider.of<T>(context)

**Comment by felangel** [comment]
Hi @br-allstreet 👋 
Thanks for opening an issue!

You can access a repository that was provided higher in the widget tree either via `RepositoryProvider.of<T>(context)` or `context.read<T>()` -- both syntaxes are functionally equivalent.

Let me know if that helps 👍
