### ISSUE TITLE
Conceptual confirmation of generalized notification bloc

### ISSUE THREAD

**Issue by nhwilly** [felangel/bloc#318]
Would it be a reasonable idea to have a `notificationBloc` in my `scaffold` with a `blocListener` to handle `snackBar` notifications of errors, failures, etc.

It could be passed into the other all the other `blocs` as a dependency.  When they had problems the user need to know about, they could just dispatch the error/message.

Almost like a global notification widget? Perhaps for lost internet connections.

Then, for that `blocListener` I could have the `child` be another `blocListener` that might process different notifications from a specific notification type - perhaps for failed logins.

I understand that the `blocListener` doesn't steal the state change, so I'd have to be careful to process the same message twice.

Can I nest them like that?

**Comment by felangel** [comment]
Hi @nhwilly 👋 
Thanks for opening an issue!

Regarding your question, I think having a `NotificationBloc` to handle showing `SnackBars` makes sense. I'm not sure what you mean by having nested `BlocListeners`. Can you please provide a simple code snippet to illustrate what you're describing? Thanks! 👍

**Comment by felangel** [comment]
Closing this for now but feel free to let me know if you have additional questions or can provide a simple code snippet to provide more context around the nested `BlocListener` point. Thanks! 👍
