### ISSUE TITLE
Question to refresh other state

### ISSUE THREAD

**Issue by alexaung** [felangel/bloc#3180]
I am stuck with one issue with bloc. 

I have a screens, Artist list -> Albums-> Songs. If user click the player popup. On the player there is favourite button.

I have another set of screens Favourite Folder -> Songs. 

I have Two blocs, favourite_folder_bloc and favourite_song_bloc.

The issue is that if user click the favourite button, bottom sheet will popup and there is list of existing favourite folder and user can create the new folder and add the song into folder.

If user create new folder, I call the create_favourite_folder function and then create the favourite folder and create the favourite song. I can refresh the favourite_folder list but I can't refresh the song_list by favourite because it is two different state.

May I know any approach to achieve this?

**Comment by ultimate-tester** [comment]
As a beginner with bloc I'm stuck with the same question. Although the OP is very specific, the question basically boils down to how to update a state from within another screen where the bloc is not applicable.

Should the bloc just be provided to that screen as well and should a method be created inside the blog to signal an update? If yes, how can you prevent a full re-render but only do that for the small relevant part of the view?

**Comment by alexaung** [comment]
Yes, it make sense. Just want to know how experience will deal with it. Anyway, we will change the design and will follow the bloc.
