### ISSUE TITLE
fix(docs): desktop sidebar toggle overlaps menu

### ISSUE THREAD

**Issue by alestiago** [felangel/bloc#3192]
**Description**
The sidebar toggle (hamburger menu) has too much width on desktop devices and overlaps with the actual menu. This causes the user to accidentally collapse the menu when wishing to navigate to a new section.

**Steps To Reproduce**

1. Go to the [bloclibrary.dev](https://bloclibrary.dev/).
2. Click on the last visible menu item next to the sidebar toggle "icon".

<details>
<summary>GIF showing issue</summary>

<img src="https://user-images.githubusercontent.com/44524995/151958933-75108122-2627-43d4-b405-72434f50584e.gif" height="500px" />

</details>

**Expected Behavior**
I would expect the sidebar toggle to action only when the "icon" is clicked.

<details>
<summary>GIF showing expected behaviour</summary>

<img src="https://user-images.githubusercontent.com/44524995/151961320-61d4cba7-bd43-4a21-8737-2e034d17012d.gif" height="500px" />

</details>

**Additional Context**
Although having the width larger than the actual icon might benefit mobile users with big fingers, I think it hinders desktop users since the mouse pointer is very precise in comparison to a finger tap.

The "sidebar toggle" seems to be implemented by [docsify](https://docsify.js.org/). When visiting their website they include a gradient to avoid this behaviour.

<details>
<summary>docsify screenshot</summary>
<img width="310" alt="Screenshot 2022-02-01 at 11 50 42" src="https://user-images.githubusercontent.com/44524995/151963720-cd91ced4-3e82-48a3-bb62-1f90ada67da9.png">
</details>

**Comment by Shamsudeen12** [comment]
Can I work on this?
@felangel

**Comment by felangel** [comment]
> Can I work on this? @felangel

Yup, I'll assign you. Thanks!
