### ISSUE TITLE
feat: use-case for ListView<>child updates

### ISSUE THREAD

**Issue by ultimate-tester** [felangel/bloc#3193]
As a beginner to both Flutter and BloC I find it hard to sometimes implement my use cases correctly with it. It's very easy with BloC to have the feeling you're abusing the system instead of using it properly.

I think that a very common use-case would be to have a ListView with cards with simple information which on clicked will Navigate to another page with more details on this clicked item. Both in the ListView cards and inside the single item page, there's a button to Favorite this item. Now, how do I make sure that this Favorite click is received on both the single page but also on the ListView so that when I press the back button, I land back on the ListView page and can see that the item is indeed favorited?

I am thinking of a few things, but would like to get some feedback on what would be most appropriate, trying to keep it as simple as possible hence the usage of Cubits as well:

1. Create a separate FavoritesCubit which has the methods:
- `loadFavorites()`
- `addFavorite(Item item)`
- `removeFavorite(Item item)`
- `isFavorited(Item item)`

These methods will call the relevant repository. Another Cubit called ListCubit for simplicity will use the `isFavorited` method from the FavoritesCubit to set a "isFavorited" field inside the model and trigger a render of the ListView widget. The downside I see is that the whole ListView is rendered again.

2. Instead of using the BloC/Cubit to manipulate favorite items, directly use the relevant repository in the view instead to mark an item as favorite (i.e. `await itemRepository.addFavorite(Item item)`). From a BloC listen to events coming from the Repository using StreamSubscription. The BloC is then used to render the ListView items, and to provide details on single items. If I have multiple listviews that all have their own BloC but the same item models, that means I should also have StreamSubscription in every BloC. Seems a bit messy to me if all BloCs regarding the lists are listening to the stream of the repository. Doesn't sound very easily scalable.

3. Create a base class for the Cubit with common methods regarding favorite management. For every ListView page with common item models, create a Cubit inheriting this base class. Inject the Cubit of the ListView when creating the view for the detail page. On toggling the favorite button, the model field "isFavorite" will be updated and the Cubit of the ListView to indicate a favorite will be called. The downside to this is that it only supports updating 1 ListView. What if I have multiple ListView that are showing an identical item in the list.

I can probably think about a few more ways to go, but would like to hear some feedback before I go crazy on theorizing :)

**Comment by felangel** [comment]
Hi @ultimate-tester 👋 
Thanks for opening an issue!

I highly recommend having a bloc manage the state of the list view and a separate bloc to manage the state of the details view. Each bloc can subscribe to a stream of posts from a common PostRepository and can toggle the favorite status of an individual post through the PostRepository. This will ensure that favoriting a post on either page will propagate throughout the whole app and it will also help you to maintain smaller, decoupled, and focused blocs. You can see an example of this architecture in the [flutter todos example](https://github.com/felangel/bloc/tree/master/examples/flutter_todos).

Let me know if that helps 👍

**Comment by ultimate-tester** [comment]
HI felangel, thanks a lot for commenting that really helps. I have a few follow-up questions if that's alright:

* Am I right in understanding that whenever a Todo is saved, the full list of Todo's is sent over the stream again? Wouldn't it be more optimal to just sent the one changed Todo over the stream for updating and e.g. the listener BLoC has to find whether the Todo is part of its state and then update it and emit an event to rebuild the widgets? I'm just trying to see if I understood it.
* I see that right now the repository implementation caries the stream and uses it. If I'm building an app with several implementations of the same repository (e.g. local storage, API, etc.), this means I have quite some duplicate code across repositories for the stream. Would you say there's another location that this would fit better or would you say create another base class that all repositories use to use the stream? Again just trying to understand it :)

Thanks a lot again for replying! I am noticing that especially with BLoC I'm really looking for best ways to do something as it offers so many possibilities!

**Comment by felangel** [comment]
Closing for now but feel free to comment with any additional questions and I’m happy to continue the conversation 👍
