### ISSUE TITLE
fix: Cubit Async Problem

### ISSUE THREAD

**Issue by mtouati** [felangel/bloc#3194]
Hi 
I try to use a simple counter with cubit and a delayed function. The tracking of the variable (index) is OK but on the text widget with same variable the value is skipped or ignored.
 
Thanks

![Screenshot_1643797264](https://user-images.githubusercontent.com/27012472/152135915-de2000ea-7d14-4551-bc6d-e558bfaf4f0c.png)
[https://github.com/mtouati/jad](url)

**Comment by Gene-Dana** [comment]
How come you use 'context1'

First thing I'd suggest is to use the same context - it seems like you provided the processCubit in a separate context than the builder you are BLoC building from

**Comment by mtouati** [comment]
Thank you **Gene-Dana** for your suggestion. But it doesn't resolve this problem! It still, after a while,  bypass or ignore some value in the index although the value is correct with a _**print**_ command.

**Comment by Gene-Dana** [comment]
Okay let me take a deeper look at this

**Comment by mtouati** [comment]
Hi [Gene-Dana](https://github.com/Gene-Dana)
Firstly, Thank you a lot! That's a great help for me. 
Perhaps, it's a **weakness** of Cubit when you have to use Asynchronous computation as I read on **[cubit vs bloc](https://bloclibrary.dev/#/coreconcepts?id=cubit-vs-bloc)**.

Thank you Sir.
