### ISSUE TITLE
feat: ability to remove event handlers

### ISSUE THREAD

**Issue by josiahsrc** [felangel/bloc#3195]
**Description**

I often need a way to test if events are properly added as a result of listening to a stream. For example:

```dart
class MyBloc extends Bloc<MyEvent, MyState>
  MyBloc() {
    on<SubscribeToStream>((event, emit) {
      someStream.listen((value) {
        add(AnotherEvent());
      }
    });
    
    on<AnotherEvent>((event, emit) {
      // Does some really nasty business logic
    });
  }
```

In this example, I'd want to write a test to make sure that the `SubscribeToStream` adds `AnotherEvent` events when the stream changes. This, however, doesn't seem to be possible unless I also test the business logic in the `AnotherEvent` handler.

**Desired Solution**

Ideally, when writing the test, it would be possible to remove an event handler as part of the build phase.

```dart
int anotherEventCount = 0;

blocTest<MyBloc, MyState>(
  'ensures that events are added to the stream',
  build: () => MyBloc()
    ..removeHandler<AnotherEvent>() // Desired solution
    ..on<AnotherEvent>((event, _) => anotherEventCount++,
  setUp: () {
    // Mock the someStream to emit fake events
  },
  act: (bloc) => bloc.add(SubscribeToStream()),
  expect: {
    expect(anotherEventCount, equals(2)); // Make sure this many events were added
  },
);
...
```

**Alternatives Considered**

- It might be possible to use the `errors` callback on the `blocTest`, but I haven't tested this.
- A cleaner solution might be to allow for a way to listen for and "consume" any events of some type. E.g.

```dart
blocTest<MyBloc, MyState>(
  'ensures that events are added to the stream',
  addsEvents: [isA<EventA>(), isA<EventA>()],
)
```

Or something to that effect.

**Comment by marcossevilla** [comment]
hey @josiahsrc! I would advice to take a look at the flutter_timer example, [here](https://github.com/felangel/bloc/blob/9f1c9c7f8cfc103a2689dd98143e95b8501dc03e/examples/flutter_timer/lib/timer/bloc/timer_bloc.dart#L36) you have a way to subscribe your bloc to a `StreamSubscription` and structure your events in a better way.

Take a look and let me know if that helps. 👍

**Comment by josiahsrc** [comment]
Hi @marcossevilla , thanks for the quick response. The timer example presents a similar issue, the issue being that it's difficult to test if a bloc correctly adds events based on a stream's changes.

In the timer example, events are added and handled, but there is no way to test the "Is this event added when the stream changes" logic in isolation. E.g.

```dart
void _onStarted(TimerStarted event, Emitter<TimerState> emit) {
  emit(TimerRunInProgress(event.duration));
  _tickerSubscription?.cancel();
  _tickerSubscription = _ticker
      .tick(ticks: event.duration)
      // This event is added when the stream changes. The goal is to write a unit test to make sure these events
      // are added when the stream emits a new duration.
      .listen((duration) => add(TimerTicked(duration: duration)));
}

// This will be invoked each time the timer ticks. Ideally, we wouldn't want to test this logic when we're only
// trying to test that an event is added when the ticker stream changes.
void _onTicked(TimerTicked event, Emitter<TimerState> emit) {
    emit(
      event.duration > 0
          ? TimerRunInProgress(event.duration)
          : TimerRunComplete(),
    );
```

With the current system, we would have to convolute the test with stubbing out the `_onTicked` method's logic. 

```dart
blocTest(
  'ensures that events are added when the ticker changes',
  create: () => TimerBloc(),
  act: (bloc) => bloc..add(TimerStarted()),
  setUp: () { ... },
  expect: () {
    // Need a way to make sure those TimerTicked events were added
    // expect(that_TimerTicked_events_were_added, equals(true))

    // With the current system, we have to account for timer state changes (Even though this isn't what we're testing)
    return [TimerRunInProgress(...), TimerRunInProgress(...), TimerRunInProgress(...)];
  }
)
```

**Comment by marcossevilla** [comment]
@josiahsrc oh I get what you mean, you should be able to mock the duration and set it to emit {count} values and then use blocTest's verify method to see if add was called {count} times with the right event.

Have you tried that already?

**Comment by felangel** [comment]
I'd also add that usually these events are "internal" and you generally should make the private and avoid exposing them if they are only going to be added from within the bloc. In those cases, you shouldn't need to verify that the internal event was added because that's an implementation detail -- instead you should aim to write tests that verify the end behavior of the bloc (the correct states were emitted). Hope that helps 👍

**Comment by josiahsrc** [comment]
Thanks @marcossevilla , I'll look into that. @felangel I hadn't considered that perspective before, but that makes thinking about these tests a bit easier. I think I'll go for that approach. Thanks all!

Closing this issue since its addition would break some paradigms in the bloc pattern.
