### ISSUE TITLE
Best practice to use Inheritance or Composition for Bloc (Cubit) reusability

### ISSUE THREAD

**Issue by Arthur-Zaripov** [felangel/bloc#3199]
**Description**
Hello everyone! First of all i apologize for opening a new topic. But after scrolling a lot of closed issues...
#2780
#1806
#1631...
... i still did not understand how to inherit Cubit (Bloc) from another one.

In practice, you often need to add new functionality to the Cubit (Bloc). How to properly extend the functionality of the existing cubit (bloc)?

For example we have DataTable without filtering functionality. We already have a DataTableCubit for managing state. And we need to add some filtering functionality. DataTableCubit class is closed for modification. What is the right thing to do in this case? 

So i create a DataTableWithFiltersCubit extends DataTableCubit. Here is an example. 
![DataTable](https://user-images.githubusercontent.com/60180239/152526294-14eb8270-d682-4251-bf08-4232c2cecdb8.jpg)

```
// A table without filtering. Do not extend Equatable for simplify reading code.
class DataTableState {
  final List<String> columns;
  final List<List<String>> rows; //one row has many cells

  const DataTableState(this.columns, this.rows);
}

class DataTableCubit extends Cubit<DataTableState> {
  DataTableCubit() : super(const DataTableState([], []));
  
  selectRow() => emit(someNewState); 
  addRow() => emit(someNewState); 
  deleteRow() => emit(someNewState); 
}

// A table with filtering
class DataTableWithFiltersState extends DataTableState {
  final Predicate filter1;
  final Predicate filter2;
  DataTableWithFiltersState(this.filter1, this.filter2) : super([], []);
}

class DataTableWithFiltersCubit extends DataTableCubit {
  filterTable() => emit(someNewState); //emit new state
}

```

Now, if we add "copyWith" methods to the States, we get an error. Invalid override. 'DataTableWithFiltersState.copyWith' isn't a valid override of 'DataTableState.copyWith'. Please help me to answer these 2 questions:

1. Is it right in this case to extend the functionality using inheritance?
2. If inheritance is possible, then how to fix this "copyWith" method error?

**Comment by Tokenyet** [comment]
If I need to use filter feature, I will do this...
```
cubit.search(filter: YourFilterClas(keyword: 'abc', date: DateTime.now()));
bloc.add(EmployeeSearchFetched(keyword: 'abc', date: DateTime.now()));
```

So in my situation.
> Is it right in this case to extend the functionality using inheritance?
> If inheritance is possible, then how to fix this "copyWith" method error?

Both question is a simply no.
