### ISSUE TITLE
Unit test bloc dispose

### ISSUE THREAD

**Issue by MattisBrizard** [felangel/bloc#321]
Hi Felix ✋ ,

I've got a question about unit testing a bloc and especially the dispose method : 
In fact, as described [here](https://github.com/felangel/bloc/blob/master/examples/flutter_login/test/login/login_bloc_test.dart#L31) the writed test is : 
```
test('dispose does not emit new states', () {
    expectLater(
      loginBloc.state,
      emitsInOrder([LoginInitial()]),
    );
    loginBloc.dispose();
  });
```
This test isn't really testing the fact that `dispose doesn't emit new states` because the bloc won't emit new state in normal behavior, am I wrong ?

Also the expectLater() method let the test pass directly after matching the matcher condition and doesn't wait for other states.
This can be checked by writing this "test" :
```
test('wrong use of emitsInOrder()', () {
    expectLater(
      loginBloc.state,
      emitsInOrder([]),
    );
    loginBloc.dispose();
  });
```
This test will pass despite the fact that the InitialState of the bloc will always be in the bloc's stateStream.

Do you have any idea of how to properly test the dispose method ?
Maybe like this : 
```
test('dispose does not emit new states', () {
    expectLater(
      typingUsersBloc.state,
      emitsInOrder([LoginInitial(), emitsDone]),
    );
    typingUsersBloc.dispose();
  });
```
Thank you

**Comment by felangel** [comment]
Hi @MattisBrizard 👋 
Thanks for opening an issue!

Yeah you're totally right! It's much better to use `emitsDone` to ensure that the stream has been closed in the `dispose` tests. I've updated the tests in `example/flutter_login` in https://github.com/felangel/bloc/commit/16a0c079e5f9f8a3670aa48c65e875e9c53c3982 accordingly.

Thanks for bringing this up 💯
