### ISSUE TITLE
[Question] How to model Repositories for children resources?

### ISSUE THREAD

**Issue by pmartelletti** [felangel/bloc#3216]
Hi @felangel and team!

First of all, I just wanted to thank you for the great effort you guys have done (and continue doing) in maintaining this project. It's amazing!

Secondly, I wanted to ask a question which I'm not sure has a right or wrong answer - or even if Github is the correct place to ask for it (if it's not, please feel free to direct me to the correct one).

So, I've been reading the updated version of the Todo's tutorial that implements Streams instead of Futures.

https://bloclibrary.dev/#/fluttertodostutorial

I think that approach really makes BloC's very clean (as you don't need bloc-to-bloc communication) plus it allows for real-time data to come in automatically where needed. However, my question comes when dealing with real data:

1. Let's say that instead of the local storage API you have a network API:
- Would you still call _init() on the constructor?
- How would you add real-time data, eg, new Todos coming from the network (via WebSockets, for example), and not just created/modified in the app itself? Where in the repository would you listen to that WebSocket stream, and how would you merge both sources together? 
- Would you also keep a list of the "retrieved" todos in memory, like in the LocalStorage one? As if not, how would you know what to return when a todo was modified?

2. The second main question is about children repositories. Let's say todos can have comments, and that you can do a bunch of stuff in them (edit the properties, but also upvote/downvote). Would you keep all that logic in the TodoRepository, or would you create a TodoCommentRepository? 
- If the latter, imagine that in the OverviewTodoBloc you have a count of upvotes/downvotes (essentially the number of comments that were upvoted). In order to keep that up to date, the TodoCommentsRepository would need to somehow communicate to the TodoRepository that the Todo has changed, so it updates its todo list and sends a new Stream of Data that the OverviewTodoBloc can consume.

Hope all this makes sense. If you have any questions or anything it's not clear, let me know and I'll try to amend it / make it clearer.

Thanks in advance!

**Comment by marcossevilla** [comment]
hey @pmartelletti!

1.1. I think it would depend on the API, if it's Firebase Firestore I don't think that would be necessary as you can just listen to the snapshots of a specific collection and maybe add a query to that. Those are implementation details that are always gonna depend on the API.

1.2. In that case, the repository is supposed to apply business rules (merge sources from 2 different APIs), but I don't think I get what you mean with 2 sources with different operations, can you explain more about that?

1.3. Based on what we have, we can add a remote API for getting todos from a server, and then use a local API to persist those todos if the connection fails or some exception is thrown. If the remote API fails, we can pick up what we have on the local one.

2.1. It comes down to the structure of the data you have, if you're calling another API, I think you might need to create a CommentsApi or something similar, but if it's for the todos domain, I think it should be on the TodosRepository so maybe you can update properties from todos, if necessary.

2.2. Same as I said, makes more sense to have both APIs in the same repository if they're affecting the same domain IMO.

Let me know if that helps. 👍

**Comment by pmartelletti** [comment]
Hi @marcossevilla - yes, it helps. Thanks a lot for taking your time to reply! Just some comments:

1.1/2: Yes, I was talking about using something else other than firebase. I think you pretty much summarise it by saying it's the Repository's job to merge the data from the different sources. However, what if it's a paginated list you request from an HTTP source, and then you also listen to a WebSocket that sends updates of new data available (eg, new Todo)? Is the repository responsible of knowing in what order to add that new Todo arrived via WS, then?

1.3 I guess it depends if having potentially not up-to-date date is relevant to the end-user or not, right?

2.2 Yes, I agree with having the logic in the Todo repository - as essentially a comment cannot live on itself. Just was wondering what other people's comments were on this.

Based on 2.2. Imagine you're previewing a specific todo (you're in a TodoDetailsPage). In my head, you'd have a BloC that handles the state of that and communicates with the ToDo repository to update the todo. How would the TodoDetailsBloc will communicate with the TodoOverviewBloc to let it know a Todo was changed? Or will you let the TodoRepository do that and avoid BloC-to-BloC communication?

Thanks a lot for your help!

**Comment by marcossevilla** [comment]
1.1/2. I suggest you check the infinite list example, specifically [this](https://github.com/felangel/bloc/blob/master/examples/flutter_infinite_list/lib/posts/bloc/post_bloc.dart) file so you can see how pagination would be implemented. Take into consideration that it's an old example, so you'll find the API layer directly on the bloc layer, so that logic can be restructured and you can create a PostsRepository and PostsApi. Still, the concepts are the same.

1.3. Yeah I think it depends on the business rules, how a stakeholder might want the app to function when the connection fails.

2.2. 🚀. Again, it depends on the repository, if you want to avoid bloc-to-bloc communication, it's a good call to make a reactive repository that can sync data and be a dependency of each bloc so you can simplify your relation/dependency graph.

Happy to help! I'm closing this issue for now as I see your doubts are pretty much solved, but feel free to keep commenting and opening another question if it's not related to this topic/example.

**Comment by pmartelletti** [comment]
thanks again @marcossevilla ! This was really helpfull. Just one last question re 2.2.

If I don't want to make my repository reactive, therefore I'd need to use bloc-to-bloc communication. How would you inject TodoDetailsBloc in TodosOverviewBloc to subscribe to the event changes, if TodoDetailsBloc does not exist when creating TodosOverViewBloc (assuming you only create the TodosDetailsBloc when you navigate to the TodoDetailsPage).

The way I found around it was to add a new Event on TodosOverviewBloc that would accept the TodosDetailsBloc stream, so whenever I get that event I start listening to changes until the TodosOverviewBloc is destroyed.

But I really don't like that approach.

Any thoughts?

Again, thank you very much for your help! I really appreciate it 😄

**Comment by pmartelletti** [comment]
@marcossevilla yeah, that's what I've ended up doing - it's just that the end result is having the TodoOverviewBloc at the top of the widget tree when it's only required at the TodoOverviewPage - so I thought there was maybe another way of doing it. 

Now I know it's either reactive repositories or just moving the bloc up.

Thanks a lot for your answers - they've been of great help!
