### ISSUE TITLE
[question]: null check when using whenListen

### ISSUE THREAD

**Issue by l-borkowski** [felangel/bloc#3218]
**Description**
I'm trying to test bloc listener that navigates to different page when state changes

```
class MockLoginCubit extends MockCubit<LoginState> implements LoginCubit {}

void main() {
  late AuthRepository authRepository;
  late LoginCubit loginCubit;

  Widget testableWidget() => BlocProvider.value(
        value: loginCubit,
        child: const LoginView(),
      );

  setUp(
    () {
      loginCubit = MockLoginCubit();
    },
  );

testWidgets('navigate to next page when isLogged is true', (tester) async {
      whenListen(
        loginCubit,
        Stream.fromIterable([
          LoginState.initial(),
          LoginState.initial().copyWith(isLogged: true),
        ]),
      );
      when(() => loginCubit.state).thenReturn(LoginState.initial());
      await tester.pumpApp(testableWidget());
      await tester.pumpAndSettle();
      expect(find.byType(AppNav), findsOneWidget);
    });
}
```

**Expected Behavior**
Testable widget is pumped up, then after tester pump page changes and expect checks it

**Screenshots**
![image](https://user-images.githubusercontent.com/79083099/153210637-c5c59f6b-5d95-4038-9e37-5c2243efee02.png)

**Additional Context**
From my conclusions there's problem with pumping app cause after removing whenListen app is pumping fine with initial state, I believe there's some problem with empty state cause after deleting `/when(() => loginCubit.state).thenReturn(LoginState.initial());` I get 
![image](https://user-images.githubusercontent.com/79083099/153211256-d46a529e-25fc-4747-a90f-0562d2bd17b6.png)

**Comment by marcossevilla** [comment]
hey @l-borkowski 👋 

can you try changing your `whenListen` to:

```dart
whenListen(
  loginCubit,
  Stream.fromIterable([
    LoginState.initial().copyWith(isLogged: true),
  ]),
  initialState: LoginState.initial(),
);
```
and remove `when(() => loginCubit.state).thenReturn(LoginState.initial());`?

**Comment by l-borkowski** [comment]
Hey
unfortunately, nothing changed at all, I've moved testable widget here to make it more readable

![image](https://user-images.githubusercontent.com/79083099/153461932-cd212656-f551-46ff-bf67-1acd6b5e22be.png)

I think I can also share some code from LoginView, I don't think it will helpfull but maybe cause it's basic listener but I guess it won't hurt 😅
```
class LoginView extends StatelessWidget {
  const LoginView({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final l10n = context.l10n;
    final cubit = context.read<LoginCubit>();
    return BlocListener<LoginCubit, LoginState>(
      listener: (context, state) {
        if (state.isLogged) {
          Navigator.of(context)
              .pushReplacement(AppNav.route(state.authResponse!));
        }
      },
```

**Comment by l-borkowski** [comment]
Ahh, after changing to 
```dart
await tester.pumpApp(
        BlocProvider.value(
          value: loginCubit,
          child: const LoginPage(),
        ),
      );
```
the exception seems to be gone, but unfortunately in this case state always stays the same, cause after adding a couple of debug prints `state.isLogged` is always false, like `whenListen` never emitted a new state

**Comment by marcossevilla** [comment]
just tried with the code you shared in a new project and the test passes (bottom image), is the test passing for you? maybe you're omitting another part of the code, some dependency on those widgets? I'm thinking maybe there's another dependency that you're not mocking?

![Screen Shot 2022-02-10 at 1 51 03 PM](https://user-images.githubusercontent.com/31174242/153485629-ade5902c-0ae2-475e-aea6-0198cbd24ae1.png)

**Comment by marcossevilla** [comment]
@l-borkowski were you able to make the test pass?

**Comment by l-borkowski** [comment]
Hey, sorry for the late response, unfortunately, I haven't been able to make this test pass, in the code that I've shared with you everything works fine, even after I expand it to be much more similar to my case. I'll definitely spend some more time to check why this is happening just for my curiosity but I can't do it right now so I believe you can close this issue if there will be an option in the future to reopen it with a solution that I found I'll definitely share it here but right now it has to wait for my weekends free time 😅

**Comment by marcossevilla** [comment]
@l-borkowski sorry to hear that! hope you find a solution soon and feel free to open another issue if you get stuck in another part of the process. there's also the [bloc discord server](https://discord.gg/h4s5jEXtTx) if you want to continue the conversation there, closing for now. 👍
