### ISSUE TITLE
docs(hydrated_bloc): Pub.dev does not include Web as supported platform

### ISSUE THREAD

**Issue by elianortega** [felangel/bloc#3219]
**Description**

The pub.dev website for [hydrated_bloc](https://pub.dev/packages/hydrated_bloc) does not include `Web` as a supported platform 

![Screen Shot 2022-02-09 at 12 36 22](https://user-images.githubusercontent.com/54898038/153267495-69aededc-904a-4acb-a98f-6a9e1d8ed6c1.png)

**Comment by MisaGu** [comment]
Does anybody keep track of it? Does "does not include Web" means it is actually supported on the Web or does it just implies the feature is missing?

**Comment by felangel** [comment]
> Does anybody keep track of it? Does "does not include Web" means it is actually supported on the Web or does it implies the feature is missing?

HydratedBloc does support web — this is just a false positive on pub.dev

**Comment by Zazo032** [comment]
From pub.dev's [score page](https://pub.dev/packages/hydrated_bloc/score):

<details>
<summary>Package not compatible with platform Web</summary>

Because:

- `package:hydrated_bloc/hydrated_bloc.dart` that imports:
- `package:hydrated_bloc/src/hydrated_storage.dart` that imports:
- `dart:io`
</details>

**Comment by shroot91** [comment]
> From pub.dev's [score page](https://pub.dev/packages/hydrated_bloc/score):
> 
> Package not compatible with platform Web
> Because:
> 
> * `package:hydrated_bloc/hydrated_bloc.dart` that imports:
> * `package:hydrated_bloc/src/hydrated_storage.dart` that imports:
> * `dart:io`

Some Update? 
In debug mode, works fine... On release mode, doesn't.

**Comment by felangel** [comment]
This has been resolved 🎉
