### ISSUE TITLE
After logout, redirected to login page. but Login again not being redirected to home page. State is updated properly

### ISSUE THREAD

**Issue by rajesh-kc** [felangel/bloc#322]
**Describe the bug**
I have followed your tutorials for login bloc & infinity list and combined both of the code bases. Now, when user logins, home screen is opened, after logout, login screen appears. Now when i try to login again, the loading indicator appears and disappears immediately. It is not redirected to Home screen. State transitions are working properly.

**To Reproduce**
1. Able to login
2. Able to logout
3. Able to login again as per transition states in console, but screen not redirected to home page

**Expected behavior**
Able to login and logout as many times as possible

**Screenshots**
My Logout function in drawer app:

> `new ListTile(
            leading: new Icon(Icons.exit_to_app),
            title: new Text('Sign Out'),
            onTap: () {
              authenticationBloc.dispatch(LoggedOut());
              Navigator.pop(context);
              Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context) => Login()));
            }
          ),`

**Logs **
I/flutter ( 9122): AppStarted
I/flutter ( 9122): Transition { currentState: AuthenticationUninitialized, event: AppStarted, nextState: AuthenticationUnauthenticated }
I/flutter ( 9122): LoginButtonPressed { username: , password:  }
I/flutter ( 9122): Transition { currentState: LoginInitial, event: LoginButtonPressed { username: , password:  }, nextState: LoginLoading }
I/flutter ( 9122): LoggedIn { token: token }
I/flutter ( 9122): Transition { currentState: LoginLoading, event: LoginButtonPressed { username: , password:  }, nextState: LoginInitial }
I/flutter ( 9122): Transition { currentState: AuthenticationUnauthenticated, event: LoggedIn { token: token }, nextState: AuthenticationLoading }
I/flutter ( 9122): Transition { currentState: AuthenticationLoading, event: LoggedIn { token: token }, nextState: AuthenticationAuthenticated }
I/flutter ( 9122): LoggedOut
I/flutter ( 9122): Transition { currentState: AuthenticationAuthenticated, event: LoggedOut, nextState: AuthenticationLoading }
I/flutter ( 9122): Transition { currentState: AuthenticationLoading, event: LoggedOut, nextState: AuthenticationUnauthenticated }
I/flutter ( 9122): LoginButtonPressed { username: , password:  }
I/flutter ( 9122): Transition { currentState: LoginInitial, event: LoginButtonPressed { username: , password:  }, nextState: LoginLoading }
I/flutter ( 9122): LoggedIn { token: token }
I/flutter ( 9122): Transition { currentState: LoginLoading, event: LoginButtonPressed { username: , password:  }, nextState: LoginInitial }
I/flutter ( 9122): Transition { currentState: AuthenticationUnauthenticated, event: LoggedIn { token: token }, nextState: AuthenticationLoading }
I/flutter ( 9122): Transition { currentState: AuthenticationLoading, event: LoggedIn { token: token }, nextState: AuthenticationAuthenticated }

Paste the output of running `flutter doctor -v` here.
flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_IN)
    • Flutter version 1.5.4-hotfix.2 at /home/raja/development/flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/raja/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/raja/Android/Sdk
    • Java binary at: /snap/android-studio/75/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/73/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.4)
    • Android Studio at /snap/android-studio/75/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.34.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Additional context**
Trying to debug since 1 day, please help.

**Comment by felangel** [comment]
Hi @rajesh-kc 👋 
Thanks for opening an issue!

Are you able to share a link to your app on GitHub? It would be much easier for me to help debug. Thanks!

**Comment by rajesh-kc** [comment]
Understood the root cause of the problem in flutter_login example:

1. In main.dart file, userRepository is passed as named parameter for LoginPage
2. In the demo application, there are only 2 screens - login page and home page. What if there are 25+ screens and logout button needs to be added to every screen, then how to access the userRepository across all 25+ pages, which needs to be passed to LoginPage when redirecting to login page after logout
3. If we try to create new userRepository instance on every page, then not able to login for the second time as mentioned in title of the above issue
4. When tried to create navigation routes for MaterialApp, not been able to pass userRepository as named parameter. got this error:

//Only static members can be accessed in initializers.

final routes = <String, WidgetBuilder>{
    '/login': (context) => LoginPage(userRepository: _userRepository),
  };


How to resolve this issue?

**Comment by felangel** [comment]
@rajesh-kc glad to hear you figured out the root cause. I would recommend having a single instance of your UserRepository which you provide to the rest of the application either by making your own RepositoryProvider ([example](https://gist.github.com/felangel/7a5312535ea6fcc6d66cd5ea3e293c6f)) or you can use the [provider](https://pub.dartlang.org/packages/provider) package to make the repository available.

That way you can access the UserRepository via BuildContext like:

```dart
RepositoryProvider.of<UserRepository>(context)
```

or 

```dart
Provider.of<UserRepository>(context)
```

Hope that helps 👍

**Comment by rajesh-kc** [comment]
Hi,

I tried implementing both the above mentioned Provider methods, but failed to login for second time, because any Inherited widget context should be added either in the build widget or didChangeDependencies method instead of initState method.  Tried adding

Provider.of<UserRepository>(context)

in build widget, but didn't work out as expected. Got the below error:

The following assertion was thrown building BlocBuilder<AuthenticationEvent,
I/flutter (10680): AuthenticationState>(state: _BlocBuilderBaseState<AuthenticationEvent, AuthenticationState>#02309):
I/flutter (10680): inheritFromWidgetOfExactType(UserRepositoryProvider) or inheritFromElement() was called before
I/flutter (10680): _LoginState.initState() completed.
I/flutter (10680): When an inherited widget changes, for example if the value of Theme.of() changes, its dependent
I/flutter (10680): widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor
I/flutter (10680): or an initState() method, then the rebuilt dependent widget will not reflect the changes in the
I/flutter (10680): inherited widget.
I/flutter (10680): Typically references to inherited widgets should occur in widget build() methods. Alternatively,
I/flutter (10680): initialization based on inherited widgets can be placed in the didChangeDependencies method, which
I/flutter (10680): is called after initState and whenever the dependencies change thereafter.

When added in didChangeDependencies method, didn't also worked.

Finally resolved the issue by moving the userRepository instance creation from main.dart file to LoginPage.

This bug costed me 3 days of my development time. Thanks for the support

**Comment by felangel** [comment]
@rajesh-kc are you able to share a link to the source code? I can try to take a look and see if there are any improvements you can make and sorry for the trouble you had to go through.

**Comment by wfybiz** [comment]
I am very new to flutter so how to use single instance of UserRepository as mentioned by rajesh kc a link of demo would be very helpful.

**Comment by felangel** [comment]
@wfybiz you can just use RepositoryProvider and create your repository instance at the root of your app like:

```dart
return RepositoryProvider(
  builder: (context) => MyRepository(),
  child: MaterialApp(...),
)
``` 

Then from anywhere in your application you can access your `MyRepository` instance via `RepositoryProvider.of<MyRepository>(context)`.

Hope that helps 👍

**Comment by 2000calories** [comment]
I am facing the same issue. How you make it work? Appreciate a lot if you could explain briefly.

**Comment by JackieLee1** [comment]
Use this script :
await _auth.signOut().then((value) => Navigator.pushReplacement(
        context, MaterialPageRoute(builder: (context) => MyApp())));

**Comment by alihesari** [comment]
> Use this script : await _auth.signOut().then((value) => Navigator.pushReplacement( context, MaterialPageRoute(builder: (context) => MyApp())));

Thank you this works for me.
