### ISSUE TITLE
Flutter Bloc is not updating the state/ not working

### ISSUE THREAD

**Issue by jackDev90** [felangel/bloc#3223]
Hi,

Am currently developing a mobile application with flutter and am using the bloc package (https://pub.dev/packages/bloc) for managing and setting up the bloc. But when the state change it is not updating the widgets or views.

login_state.dart

```
part of 'login_bloc.dart';

abstract class LoginState extends Equatable {
  const LoginState();

  @override
  List<Object> get props => [];
}

class LoginInitial extends LoginState {} //the ui is getting stuck here

class LoginLoading extends LoginState {}

class LoginFailure extends LoginState {
  final String error;

  const LoginFailure({required this.error});

  @override
  List<Object> get props => [error];

  @override
  String toString() => 'LoginFailure { error: $error }';
}
```

login_event.dart

```
part of 'login_bloc.dart';

abstract class LoginEvent extends Equatable {
  // const LoginEvent();
}

class LoginButtonPressed extends LoginEvent {
  final String email;
  final String password;

  LoginButtonPressed({
    required this.email,
    required this.password,
  });

  @override
  List<Object> get props => [email, password];

  @override
  String toString() =>
      'LoginButtonPressed { email: $email, password: $password }';
}

```
```
login_bloc.dart

import 'dart:async';

import 'package:intercity_travellers/bloc/auth_bloc/auth.dart';
import 'package:intercity_travellers/repositories/repositories.dart';
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';
import 'package:bloc/bloc.dart';
part 'login_event.dart';
part 'login_state.dart';

class LoginBloc extends Bloc<LoginEvent, LoginState> {
  final UserRepository userRepository;
  final AuthenticationBloc authenticationBloc;

  LoginBloc({
    required this.userRepository,
    required this.authenticationBloc,
  })  : assert(userRepository != null),
        assert(authenticationBloc != null),
        super(LoginInitial()) {
    on<LoginButtonPressed>(_loginButtonPressed);
  }

  void _loginButtonPressed(
    LoginButtonPressed event,
    Emitter<LoginState> emit,
  ) async {
    final state = this.state;
    print(state);
    if (state is LoginButtonPressed) {
      emit(LoginLoading());

      try {
        final token = await userRepository.login(
          event.email,
          event.password,
        );
        authenticationBloc.add(LoggedIn(token: token));
        emit(LoginInitial());
      } catch (error) {
        emit(LoginFailure(error: error.toString()));
      }
    }
  }
}
```

**Comment by marcossevilla** [comment]
hey @jackDev90 👋  can you share a minimal reproducible sample of your code? it's hard to tell what's the issue you're having without any description/context.

**Comment by Gene-Dana** [comment]
I found this in my email

Hi,

Am currently developing a mobile application with flutter and am using the bloc package (https://pub.dev/packages/bloc) for managing and setting up the bloc. But when the state change it is not updating the widgets or views.

login_state.dart

part of 'login_bloc.dart';

abstract class LoginState extends Equatable {
  const LoginState();

  @override
  List<Object> get props => [];
}

class LoginInitial extends LoginState {} //the ui is getting stuck here

class LoginLoading extends LoginState {}

class LoginFailure extends LoginState {
  final String error;

  const LoginFailure({required this.error});

  @override
  List<Object> get props => [error];

  @override
  String toString() => 'LoginFailure { error: $error }';
}

login_event.dart

part of 'login_bloc.dart';

abstract class LoginEvent extends Equatable {
  // const LoginEvent();
}

class LoginButtonPressed extends LoginEvent {
  final String email;
  final String password;

  LoginButtonPressed({
    required this.email,
    required this.password,
  });

  @override
  List<Object> get props => [email, password];

  @override
  String toString() =>
      'LoginButtonPressed { email: $email, password: $password }';
}

login_bloc.dart

import 'dart:async';

import 'package:intercity_travellers/bloc/auth_bloc/auth.dart';
import 'package:intercity_travellers/repositories/repositories.dart';
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';
import 'package:bloc/bloc.dart';
part 'login_event.dart';
part 'login_state.dart';

class LoginBloc extends Bloc<LoginEvent, LoginState> {
  final UserRepository userRepository;
  final AuthenticationBloc authenticationBloc;

  LoginBloc({
    required this.userRepository,
    required this.authenticationBloc,
  })  : assert(userRepository != null),
        assert(authenticationBloc != null),
        super(LoginInitial()) {
    on<LoginButtonPressed>(_loginButtonPressed);
  }

  void _loginButtonPressed(
    LoginButtonPressed event,
    Emitter<LoginState> emit,
  ) async {
    final state = this.state;
    print(state);
    if (state is LoginButtonPressed) {
      emit(LoginLoading());

      try {
        final token = await userRepository.login(
          event.email,
          event.password,
        );
        authenticationBloc.add(LoggedIn(token: token));
        emit(LoginInitial());
      } catch (error) {
        emit(LoginFailure(error: error.toString()));
      }
    }
  }
}

**Comment by Gene-Dana** [comment]
Also @jackDev90, may you share with us the view itself?

**Comment by jackDev90** [comment]
hi thank you for getting back to me, i was using bloc version 7.3.0 for
authentication and managing state in app and everything was working fine
until i  upgraded to version 8.0.1

**Comment by jackDev90** [comment]
this used to work in version 7.3.0 but when i upgraded to version 8.0.1 nothing is firing i have tried printing the state in the console but nothing is been printed
```
import 'dart:async';

import 'package:intercity_travellers/bloc/auth_bloc/auth.dart';
import 'package:intercity_travellers/repositories/repositories.dart';
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';
import 'package:bloc/bloc.dart';
part 'login_event.dart';
part 'login_state.dart';

class LoginBloc extends Bloc<LoginEvent, LoginState> {
  final UserRepository userRepository;
  final AuthenticationBloc authenticationBloc;

  LoginBloc({
    required this.userRepository,
    required this.authenticationBloc,
  })  : assert(userRepository != null),
        assert(authenticationBloc != null),
        super(LoginInitial()) {
    on<LoginButtonPressed>(_loginButtonPressed);
  }

  void _loginButtonPressed(
    LoginButtonPressed event,
    Emitter<LoginState> emit,
  ) async {
    final state = this.state;
    print(state); // am printing the state but nothing is been printed in the console
    if (state is LoginButtonPressed) { // and this is not firing
      emit(LoginLoading());

      try {
        final token = await userRepository.login(
          event.email,
          event.password,
        );
        authenticationBloc.add(LoggedIn(token: token));
        emit(LoginInitial());
      } catch (error) {
        emit(LoginFailure(error: error.toString()));
      }
    }
  }
}
```import 'dart:async';

import 'package:intercity_travellers/bloc/auth_bloc/auth.dart';
import 'package:intercity_travellers/repositories/repositories.dart';
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';
import 'package:bloc/bloc.dart';
part 'login_event.dart';
part 'login_state.dart';

class LoginBloc extends Bloc<LoginEvent, LoginState> {
  final UserRepository userRepository;
  final AuthenticationBloc authenticationBloc;

  LoginBloc({
    required this.userRepository,
    required this.authenticationBloc,
  })  : assert(userRepository != null),
        assert(authenticationBloc != null),
        super(LoginInitial()) {
    on<LoginButtonPressed>(_loginButtonPressed);
  }

  void _loginButtonPressed(
    LoginButtonPressed event,
    Emitter<LoginState> emit,
  ) async {
    final state = this.state;
    print(state); // am printing the state but nothing is been printed in the console
    if (state is LoginButtonPressed) { // and this is not firing
      emit(LoginLoading());

      try {
        final token = await userRepository.login(
          event.email,
          event.password,
        );
        authenticationBloc.add(LoggedIn(token: token));
        emit(LoginInitial());
      } catch (error) {
        emit(LoginFailure(error: error.toString()));
      }
    }
  }
}

**Comment by jackDev90** [comment]
this is the repo for the project [https://github.com/jackDev90/flutterauthbloc](https://github.com/jackDev90/flutterauthbloc)

**Comment by jackDev90** [comment]
@felangel @marcossevilla @Gene-Dana any progress with my current situation?

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 I was able to check it out and I really liked the intro screen.

There are some alarming things I saw here, like this ⚠️

<img width="416" alt="image" src="https://user-images.githubusercontent.com/45580241/154410197-0110b1fb-46fd-4b7e-95d1-c5da24fbd167.png">

In order to add events to a bloc, you need to provide it higher in the widget tree just like it's done here in the `firebase_login` example 

https://github.com/felangel/bloc/blob/a48f2e75e40744d8a3ab21d7c6872955f9c5a8df/examples/flutter_firebase_login/lib/login/view/login_page.dart#L12-L24

And... this is not the only problem you have ! 

![2022-02-17 00 06 06](https://user-images.githubusercontent.com/45580241/154410808-bbb51bf7-d548-4f67-9d4e-01777d48e6d4.gif)

I'd highly suggest you refactor exactly like the `firebase_login` example, meaning copy paste 🥷🏼 the folders (aka features) completely. Or better yet - use `firebase_login` as a base for refactoring.

If you have any more questions, feel free to ask and we can do our best to help 🙏🏼

**Comment by jackDev90** [comment]
@Gene-Dana hi thank you, now looking at how my authentication logic is laid out on my app does it mean i have to refactor every bit of code, as in sending of request to and from the server? am basically new at flutter bloc

**Comment by Gene-Dana** [comment]
@jackDev90 My advice is to do more than refactor - it's to rebuild a new project based on the Firebase Login example.

Although everything is really already build and tested and working - all you'd need to do is refactor the existing views to your snazzy design - so it's a lot less work than you may think..

Mostly, it's so that you can see the proper way we implement all the authentication features and use that as a template moving forward

**Comment by jackDev90** [comment]
@Gene-Dana alright thank you, though this is not what i was hoping for but i will try to make it work

**Comment by Gene-Dana** [comment]
Closing this for now. Feel free to continue commenting here, or to chat with us directly in the discord https://discord.gg/VJm86k9F
