### ISSUE TITLE
How to properly use `buildWhen`?

### ISSUE THREAD

**Issue by AcarFurkan** [felangel/bloc#3229]
firstly it is a question, it isnt a bug. 
l am using blocbuilder and l am trying to use buildwhen but when l return false build rebuild again. l am  just learning flutter l hope l dont bother. 

![image](https://user-images.githubusercontent.com/65075121/154042302-a41c903a-6546-4837-a94b-d34eecf3dc26.png)

**Comment by federicodesia** [comment]
Hi! I think that on each render it is initializing the `temp` variable with the value `-2` again.
Consider using `previousState.count != state.count` inside `buildWhen`. If you need to keep the temp variable for another reason, consider using `StatefulWidget`. [Equatable](https://pub.dev/packages/equatable) package may also interest you.
Sorry if this doesn't help you, I'm new too.

**Comment by AcarFurkan** [comment]
actually l tried this also but nothing changed. return false doesnt work.what am i missing
![image](https://user-images.githubusercontent.com/65075121/154161216-92eefeec-ea0f-40d5-b26d-592c13b648fa.png)

**Comment by federicodesia** [comment]
Do you have another `BlocBuilder` on top of that one? Similar to #1413

**Comment by AcarFurkan** [comment]
no l am not using second blocBuilder.
code link: https://github.com/AcarFurkan/Coin-App/blob/master/lib/features/coin/bitexen/view/bitexen_page.dart
![image](https://user-images.githubusercontent.com/65075121/154249584-9808905e-c915-423b-8c78-ec4ab984f280.png)

**Comment by Gene-Dana** [comment]
@AcarFurkan Do you have a repo that you can share?

**Comment by AcarFurkan** [comment]
@Gene-Dana   https://github.com/AcarFurkan/Coin-App/blob/master/lib/features/coin/bitexen/view/bitexen_page.dart

**Comment by Gene-Dana** [comment]
Here is an example of how to properly use `buildWhen`

https://www.loom.com/share/6e008d018f24478fb26f0b31c0fa41b7

**Comment by Gene-Dana** [comment]
Here is what the same example looks like if I just returned false
https://www.loom.com/share/a4137ba5dea24fb8904db7f83e585269

**Comment by AcarFurkan** [comment]
yes l tried this also but it doesnt work for my real project. l return
false and it build again again. l showed this lots of people  nobody
couldnt any mistake about my code. l am not saying bloc dont work just I'm
stuck l couldnt find where is the mistake. but l am sure return false
doesnt work for me.

**Comment by Gene-Dana** [comment]
See this
https://stackoverflow.com/questions/52249578/how-to-deal-with-unwanted-widget-build

**Comment by AcarFurkan** [comment]
@Gene-Dana  with this thought, shouldn't blockbuildir be triggered more than once?
but blocbuilder only runs once in the whole project.
![image](https://user-images.githubusercontent.com/65075121/154653327-bfd5652b-ab23-4d6d-850a-6057ffb9d499.png)
this is all log. so l searched all terminal blocbuilder just works onces.
![image](https://user-images.githubusercontent.com/65075121/154653688-ba307e73-de5a-4896-b7a4-b0a694263cbd.png)

**Comment by Gene-Dana** [comment]
May you add a BlocObserver and run the exact same options?

https://github.com/felangel/bloc/blob/35f0e39ab68ec014d353cdd7c6a3addf31381132/examples/flutter_todos/lib/bootstrap.dart#L18-L24

**Comment by AcarFurkan** [comment]
The build of the project runs once in all logs.
![image](https://user-images.githubusercontent.com/65075121/154654600-271ff58b-ce88-4374-b2ee-4bdafa5a2985.png)

![image](https://user-images.githubusercontent.com/65075121/154654688-6a979207-188c-4705-a9be-b36fd7e3d824.png)

**Comment by AcarFurkan** [comment]
l added blocobserver but there are too much log. which one should i share

**Comment by AcarFurkan** [comment]
![image](https://user-images.githubusercontent.com/65075121/154655344-cade43b0-bed6-44fd-be6b-35cf037abe25.png)

**Comment by Gene-Dana** [comment]
```dart

import 'dart:developer';

import 'package:bloc/bloc.dart';

class AppBlocObserver extends BlocObserver {
  @override
  void onChange(BlocBase bloc, Change change) {
    super.onChange(bloc, change);
    // ignore: lines_longer_than_80_chars
    log('onChange: ${bloc.runtimeType},\nCurrent state: ${change.currentState}\nNext state: ${change.nextState}');
  }

  @override
  void onError(BlocBase bloc, Object error, StackTrace stackTrace) {
    log('onError(${bloc.runtimeType}, $error, $stackTrace)');
    super.onError(bloc, error, stackTrace);
  }

  @override
  void onCreate(BlocBase bloc) {
    log('onCreate(${bloc.state}, ${bloc.runtimeType})');
    super.onCreate(bloc);
  }

  @override
  void onClose(BlocBase bloc) {
    log('onClose(${bloc.state}, ${bloc.runtimeType})');
    super.onClose(bloc);
  }
}
```dart

**Comment by Gene-Dana** [comment]
Also, put the print in the builder

**Comment by AcarFurkan** [comment]
all log
![image](https://user-images.githubusercontent.com/65075121/154655953-6b7b316d-4409-485c-b62a-4363810a36b1.png)
only relevant page
![image](https://user-images.githubusercontent.com/65075121/154656214-fe8984b5-5dcb-4b93-a307-4fa486611f2d.png)

**Comment by Gene-Dana** [comment]
@AcarFurkan, you have quite a few problems!

<img width="89" alt="image" src="https://user-images.githubusercontent.com/45580241/154656879-a2205a9b-83e4-469a-91e0-0fdcf70ca1d1.png">

This is a tough knot to unravel. Let's move this to the discord and see if we can solve it together.

https://discord.gg/FGzNZYP4
Message me! Gene#7475

**Comment by felangel** [comment]
See https://github.com/felangel/bloc/issues/3234#issuecomment-1044728275 (as Gene mentioned). `buildWhen` is just an optimization but does not guarantee rebuilds won't happen. Sounds like you'd benefit from using `BlocSelector` instead of `BlocBuilder` + `buildWhen`.

Closing for now but feel free to comment with any additional questions 👍

**Comment by janarthanan1711** [comment]
Im getting black screen when im try to tap event related function more than twice continuesly in bloc....I dont know why its getting like this its based on event calling or some other issues.
Is buildWhen resolve this issues or some other solutions help me to sort out this
