### ISSUE TITLE
fix: Unhandled Exception: Binding does not extend BindingBase

### ISSUE THREAD

**Issue by Gene-Dana** [felangel/bloc#3230]
**Description**

`[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: Binding does not extend BindingBase
An instance of ServicesBinding was created but the BindingBase constructor was not called.
This could happen because the binding was implemented using "implements" rather than "extends" or "with". Concrete binding classes must extend or mix in BindingBase.` 

when running the weather example (and I think every other example except todos) on the master branch

**Steps To Reproduce**

1. Switch to channel Stable `flutter channel stable`
2. Upgrade `flutter upgrade`
2. Run `flutter_weather` from the examples -> ✅
3. Switch to channel Master `flutter channel master`
4. Upgrade `flutter upgrade`
4. Run `flutter_weather` from the examples -> ❌

**Expected Behavior**
The example runs like normal

**Screenshots**

<img width="883" alt="image" src="https://user-images.githubusercontent.com/45580241/154405740-6c7ad1f5-3b7e-4c95-a295-5c400d9433e4.png">

**Additional Context**
I'm running this on an the Apple M1 Pro

**Comment by morlay** [comment]
`flutter  channel beta` have same issue.

**Comment by holdenhinkle** [comment]
I'm new to Dart/Flutter and just ran into this when going through the Weather App tutorial.

I just submitted this issue - https://github.com/felangel/bloc/issues/3306

**Comment by felangel** [comment]
WIP PR to address this is #3240

**Comment by dovahkrid** [comment]
It seems to get back after updating flutter 3. I don't even use hydrated_bloc

**Comment by felangel** [comment]
> It seems to get back after updating flutter 3. I don't even use hydrated_bloc

Can you provide a reproduction sample? FlutterServicesBinding is deprecated and should not be used because it’s no longer viable.

**Comment by dovahkrid** [comment]
> > It seems to get back after updating flutter 3. I don't even use hydrated_bloc
> 
> Can you provide a reproduction sample? FlutterServicesBinding is deprecated and should not be used because it’s no longer viable.

So should I back to WidgetsFlutterBinding ?

**Comment by felangel** [comment]
> > > It seems to get back after updating flutter 3. I don't even use hydrated_bloc
> > 
> > 
> > Can you provide a reproduction sample? FlutterServicesBinding is deprecated and should not be used because it’s no longer viable.
> 
> So should I back to WidgetsFlutterBinding ?

yup check out the [weather example](https://github.com/felangel/bloc/blob/master/examples/flutter_weather/lib/main.dart) for the most up-to-date recommendation 👍
