### ISSUE TITLE
fix: TextFormField not clearing when state is updated.

### ISSUE THREAD

**Issue by ShahzadUmarBaig** [felangel/bloc#3231]
**Description**
I have been trying to achieve a small behavior through BLoC but so far I have not been able to do that, I just want to empty the textformfield when I press a button. It is easier to do that with controller and stateful widget but apparently I am failing to do so through BLoC.

**Steps To Reproduce**
1. Create a simple state with a string value. initially set is to empty string.
2. Create a Textformfield on UI part and assign initialValue to state.value.
3. Then create an event to clear the value of state.
4. Textformfield won't remove the text

**Expected Behavior**
It should clean the textfield once the state is cleared since it is assigned a bloc property on initial value.

**Comment by Gene-Dana** [comment]
The solution is to add a key to the `TextFormField` like this:

```dart
TextFormField(
   key: UniqueKey(),
   initialValue: state.text,
   onChanged: (value) => context.read<TextfieldBloc>().add(OnValueChanged(value)),
   decoration: Constants.textFieldDecoration,
),
```

This is a good explanation of `why`
https://medium.com/flutter/keys-what-are-they-good-for-13cb51742e7d

Closing this for now, let me know if you have any more questions

**Comment by Gene-Dana** [comment]
> I don't recommend that. The proper way imo is to maintain a `TextEditingController` and call `clear` when you want to clear the input.

Definitely an opinion I respect ! Would the button then make the `clear` call on the `TextEditingController`, which would in turn (due to onChanged) update the bloc?

**Comment by ShahzadUmarBaig** [comment]
According to the concept of maintaining the UI in UI classes, I believe having TextEditingController is the best approach mentioned by you. 

So thumbs up for your answer! and Thank you both for the quick responses.

**Comment by eriquezinedine** [comment]
hello where are you declaring the text controller?

because I have the same doubt and I am leaving it in a stateless widget and when I try to write, it does not show me the text.
