### ISSUE TITLE
fix: Bloc mapEventToState is not called though event was fired

### ISSUE THREAD

**Issue by abhi-kyros** [felangel/bloc#3235]
**Description**
mapEventToState is called only for 2,3 times then it is not called. I am making signalr chatting application in flutter. And when internet is off it should fire disconnect event and when internet is available it should fires connect event.

**Steps To Reproduce**

Just internet on and off( I am getting internet toast for 2 times and disconnect only ones)then event is triggered but it has not reached the mapstatetoevent
Here is a[ stackoverflow link](https://stackoverflow.com/questions/71173691/flutter-mapeventtostate-is-not-called-though-event-was-fired).

**Expected Behavior**
Atleast it should reach mapstatetoevent when add() is called. I had tried removing equatable from state and event.

**Comment by felangel** [comment]
Hi @abhi-kyros 👋
Thanks for opening an issue!

Can you please share a link to a minimal reproduction sample (DartPad or GitHub repository link)? Thanks!

**Comment by Gene-Dana** [comment]
From linked stackoverflow

mapEventToState is called only for 2,3 times then it is not called. I am making signalr chatting application in flutter. And when internet is off it should fire disconnect event and when internet is available it fires connect event.

For example:
```dart

abstract class SocketEvent extends Equatable {
  const SocketEvent();

  @override
  List<Object> get props => [];
}

class SocketConnectRequested extends SocketEvent {
  const SocketConnectRequested();
  @override
  List<Object> get props => [];
}

class SocketDisconnectRequested extends SocketEvent {
  const SocketDisconnectRequested();
  @override
  List<Object> get props => [];
}
}
```
and for internet sense code:
```dart

_subscription =
        Connectivity().onConnectivityChanged.listen((connectivityResult) async{
          print(state.status);
          if (connectivityResult == ConnectivityResult.wifi) {
            add(SocketConnectRequested());
          } else if (connectivityResult == ConnectivityResult.mobile) {
            add(SocketConnectRequested());
          } else if (connectivityResult == ConnectivityResult.none) {
            add(SocketDisconnectRequested());
          }
        });
```
For mapEventToState code snippet:

```dart
 @override
  Stream<SocketState> mapEventToState(SocketEvent event) async* {
 if (event is SocketConnectRequested) {
      yield* _mapSocketConnectRequestedToState();
    } else if (event is SocketDisconnectRequested) {
      yield* _mapSocketDisconnectRequestedToState(state);
    }
}
```
It calls only 2 times then it unable to trigger mapEventToState though it calls SocketEvent.

Thankful for any kind of help.

**Comment by abhi-kyros** [comment]
No, the connectivity plugin works perfectly. It's just this event SocketConnectRequested is called and not catching to mapEventToState. And yes I will provide the given suggestion soon.

**Comment by felangel** [comment]
> No, the connectivity plugin works perfectly. It's just this event SocketConnectRequested is called and not catching to mapEventToState. And yes I will provide the given suggestion soon.

That likely means the bloc has been closed.

**Comment by abhi-kyros** [comment]
Hello Please look into this git to reproduce issue:
**https://github.com/abhi-kyros/bloc_reproduce_issue.git**

Even I am getting same issue here also.

Steps:
1)Run App: You will get Snackbar saying internet connected.
2) Off the connection: again You will get Snackbar saying internet disconnected.
Repeat for 2,3 times.

I had tried **blocobserve** also but I am getting logs like this other than that I am not getting anything.(This log is from my project)

Observer: Transition { currentState: SplashState(SplashStatus.initial, null), event: CheckPermission(), nextState: SplashState(SplashStatus.initial, null) }
Observer: Transition { currentState: SplashState(SplashStatus.initial, null), event: CheckingAuthenticStatus(), nextState: SplashState(SplashStatus.navigate_to_home, DataResponse {}
Observer: Transition { currentState: SocketState(SocketStatus.initial, null), event: Instance of 'SocketConnectRequested', nextState: SocketState(SocketStatus.initial, null) }
Observer: Transition { currentState: Instance of 'ConnectionInitial', event: Instance of 'ConnectionChanged', nextState: Instance of 'ConnectionWifii' }
Observer: Transition { currentState: SocketState(SocketStatus.initial, null), event: Instance of 'SocketConnectRequested', nextState: SocketState(SocketStatus.loading, null) }
Observer: Transition { currentState: SocketState(SocketStatus.loading, null), event: Instance of 'SocketConnectRequested', nextState: SocketState(SocketStatus.connect, 1) }
Observer: Transition { currentState: HomeState(HomeStatus.initial, [], null, null), event: GetChatListRequested(), nextState: HomeState(HomeStatus.success, [], null, null) }
Observer: Transition { currentState: HomeState(HomeStatus.success, [], null, null), event: ChatListReceived([ChatList {})

Error :Unhandled Exception: Connection closed while receiving data

Observer: Transition { currentState: SocketState(SocketStatus.connect, 1), event: Instance of 'SocketNoInternetConnectionRequested', nextState: SocketState(SocketStatus.disconnect, 1) }
Observer: Transition { currentState: Instance of 'ConnectionWifii', event: Instance of 'ConnectionChanged', nextState: Instance of 'ConnectionFailure' }

Observer: Transition { currentState: SocketState(SocketStatus.disconnect, 1), event: Instance of 'SocketConnectRequested', nextState: SocketState(SocketStatus.initial, null) }
Observer: Transition { currentState: Instance of 'ConnectionFailure', event: Instance of 'ConnectionChanged', nextState: Instance of 'ConnectionWifii' }
Observer: Transition { currentState: SocketState(SocketStatus.initial, null), event: Instance of 'SocketConnectRequested', nextState: SocketState(SocketStatus.loading, null) }
Observer: Transition { currentState: SocketState(SocketStatus.loading, null), event: Instance of 'SocketConnectRequested', nextState: SocketState(SocketStatus.connect, 1) }
Observer: Transition { currentState: Instance of 'ConnectionWifii', event: Instance of 'ConnectionChanged', nextState: Instance of 'ConnectionFailure' }

After disconnected 3rd time next state is not called in Socket though (connection state called saying connection failure).

**Comment by abhi-kyros** [comment]
If you have a socket demo and run this git file you will have more Idea I guess.

**Comment by felangel** [comment]
Hi @abhi-kyros 👋 

Is this still an issue? Are you able to reproduce on the latest stable version? Thanks!

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional info and I’m happy to continue the conversation 👍
