### ISSUE TITLE
question: Merge transformers

### ISSUE THREAD

**Issue by subzero911** [felangel/bloc#3238]
**Description**

How can I apply multiple transformers to the same incoming event stream? Say, I want to apply sequential(), but I also want to apply debounce.

**Comment by subzero911** [comment]
I've received an answer from some Korean YT channel https://www.youtube.com/watch?v=RIqfOm0hp6Q

EventTransformer<E> debounceSequential<E>(Duration duration) {
  return (events, mapper) {
    return sequential<E>().call(events.debounce(duration), mapper);
  };
}

Should be in the manual, I believe!

**Comment by felangel** [comment]
Hi @subzero911 👋 
Thanks for opening an issue and glad you found a solution. A variation of this is included as part of the [GitHub Search Example](https://github.com/felangel/bloc/blob/35f0e39ab68ec014d353cdd7c6a3addf31381132/examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart#L8) and you can see another example in the [VGVentures Bloc Concurrency Demos Repo](https://github.com/VGVentures/bloc_concurrency_demos/blob/85fd3948b4e77b537f82a59a8e1d4e5fdf417262/lib/registration/bloc/registration_bloc_new.dart#L98).

I'll update the core concepts shortly 👍
