### ISSUE TITLE
Dependency Overrides doesn't exist

### ISSUE THREAD

**Issue by gehhrald** [felangel/bloc#324]
Tried adding the dependency_overrides to my pubspec.yaml as stated in the document but I keep getting the error below:

`flutter packages get
Because <<app-name>> depends on dependency_overrides any which doesn't exist (could not find package dependency_overrides at https://pub.dartlang.org), version solving failed.`

Anyone has any idea on how to solve this?

**Comment by felangel** [comment]
Hi @gehhrald 👋 
Thanks for opening an issue!

Can you please describe what commands you're running and clear steps to reproduce the problem you're having? Thanks! 👍

**Comment by gehhrald** [comment]
Hi @felangel 

Thank you for your quick reply. I was looking at the this [tutorial](https://felangel.github.io/bloc/#/fluttertodostutorial) and when I try adding the dependency_override section in my pubsepc.yaml, I am thrown with this issue. 

The only command ran is `flutter packages get`

**Comment by felangel** [comment]
No problem! Can you share a link to your repo? I'm not able to reproduce this locally. Can you try cloning and running the finished [todos app](https://github.com/felangel/bloc/tree/master/examples/flutter_todos)

**Comment by gehhrald** [comment]
I somehow managed to get it to work on my repo currently and I'm unsure why. But thank you for your help :)
