### ISSUE TITLE
How to verify if `MockSharedPreferences` is actually writing to the (mocked) storage?

### ISSUE THREAD

**Issue by KDCinfo** [felangel/bloc#3241]
**Description**
In using the Flutter Bloc's Todos example app, I'm having troubles verifying that the MockSharedPreferences is actually writing to the (mocked) storage. In the test provided in the code, it appears to only verify that the stream was updated, not that the mock storage was written to.

**Steps To Reproduce**

To test, I set the [saveTodo function](https://github.com/felangel/bloc/blob/35f0e39ab68ec014d353cdd7c6a3addf31381132/examples/flutter_todos/packages/local_storage_todos_api/lib/src/local_storage_todos_api.dart#L51) to be `async`,

    Future<void> saveTodo(Todo todo) async {

And I replaced [the return](https://github.com/felangel/bloc/blob/35f0e39ab68ec014d353cdd7c6a3addf31381132/examples/flutter_todos/packages/local_storage_todos_api/lib/src/local_storage_todos_api.dart#L61) with:

    final setVal = await _setValue(kTodosCollectionKey, json.encode(todos));
    final getVal = _getValue(kTodosCollectionKey);
    // ignore: avoid_print
    print(getVal);

    return setVal;

**Expected Behavior**
If you pause the debugger on the `return`, you'll find the `getVal` doesn't have the new 4th item.

**Additional Context**
Was just curious on how to test the 'save' (or 'update') portion of the Mock Shared Preferences.

I could perhaps not be looking at or interpreting something correctly. Or maybe the Mock Shared Preferences isn't geared for actual storage, and the streamed value in the API singleton instance is sufficient for testing?

Thanks for any insights.

[Todos: Shared Prefs API](https://github.com/felangel/bloc/blob/master/examples/flutter_todos/packages/local_storage_todos_api/lib/src/local_storage_todos_api.dart)

[Todos: Test File](https://github.com/felangel/bloc/blob/master/examples/flutter_todos/packages/local_storage_todos_api/test/local_storage_todos_api_test.dart)

**Comment by robsonsilv4** [comment]
Hi @KDCinfo, you could use _setMockInitialValues_, from SharedPreferences [testing](https://pub.dev/packages/shared_preferences) section.

The testing would be like this:
```dart
 SharedPreferences.setMockInitialValues(<String, Object>{});
 
 final prefs = await SharedPreferences.getInstance();
 final subject = YouSubject(prefs: prefs);
```

**Comment by KDCinfo** [comment]
Good thought. I tried that. You can only use the `setMockInitialValues()` from within the test, so I entwined it with the save, checking the debug on every pass, but it never updated the mock shared prefs instance. 

Perhaps there's another approach to this...

```
        SharedPreferences.setMockInitialValues(
          <String, Object>{'__todos_collection_key__': newTodo},
        );
        await Future<void>.delayed(Duration(seconds: 2));

        expect(subject.saveTodo(newTodo), completes);
        await Future<void>.delayed(Duration(seconds: 2));

        SharedPreferences.setMockInitialValues(
          <String, Object>{'__todos_collection_key__': newTodo},
        );
        await Future<void>.delayed(Duration(seconds: 2));

        await subject.saveTodo(newTodo);
        await Future<void>.delayed(Duration(seconds: 2));

        expect(subject.saveTodo(newTodo), completes);
        await Future<void>.delayed(Duration(seconds: 2));
```

**Comment by KDCinfo** [comment]
After watching through [Testing Flutter Apps - Making Sure Your Code Works](https://www.youtube.com/watch?v=bj-oMYyLZEY&ab_channel=Flutter) provided by The Boring Flutter Development Show, Ep. 21, I'm closing this ticket as I realize now there is no need to ensure the storage is written to. That would be looking to test the storage library itself, which is beyond the scope of this type of test.

Learn as you go... I'm seeing much more of the forest now. Many, many thanks to the Flutter team for all their 'boring shows'. I'm sure they're [missing Filip too](https://www.youtube.com/watch?v=4KXePjjdoF0&ab_channel=FilipHr%C3%A1%C4%8Dek).
