### ISSUE TITLE
[Question] Emit seems not to be sent in real time to my app 

### ISSUE THREAD

**Issue by DebroyeAntoine** [felangel/bloc#3249]
**Description**
Hi everyone, I'm very new to flutter and I'm trying to create an app which updates the background color.
I have some isolates which send by socket a value to my cubit every 5 minutes, and then the cubit will emit the new state. In the debugger I see all is ok before the emit. But the impress I have, is my color is refreshed at the next 5 minutes so not useful.
I think I missed something in my code but I didn't find what.

Thanks for your future help 🙏

**Code to reproduce**

**statefull home widget**
```dart
Widget build(BuildContext context) {
    return BlocBuilder<TestCubit, TestState>(
        builder: (context, state) {
      return Scaffold(
        backgroundColor: state.status,
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Text(state.path),
              TextField(
                controller: _controller,
                maxLines: null,
                keyboardType: TextInputType.url,
                onChanged: (url) =>
                    context.read<TestCubit>().urlChanged(url),
              ),

              const SizedBox(
                height: 50,
              ),
              CupertinoSwitch(
                  value: _sw_value,
                  onChanged: (value){
                    setState(() {
                      _sw_value = value;
                    });
                    if (value == true){
                      BlocProvider.of<TestCubit>(context).validate();
                    }
                    else {
                      BlocProvider.of<TestCubit>(context).cancel();
                    }
                  }
              ),
            ],
          ),
        ),
      );
    });
  }
}
```
and this is my cubit file
```dart
const fetchBackground = "fetchBackground";

void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    switch (task) {
      case fetchBackground:
        var sock = await Socket.connect("127.0.0.1", 8124,
            timeout: Duration(seconds: 5));
        sock.write("loading");
        String result = "OK"
        if (result == "OK") {
          sock.write("good");
        } else {
          sock.write("warning");
        }
        sock.close();
      break;
    }
    return Future.value(true);
  });
}

final BatteryRepository repo = BatteryRepository(api: ServerAPI(http.Client()));

class TestCubit extends Cubit<TestState> {
  var serverSocket;
  TestCubit() : super(TestState("", Colors.grey));

  urlChanged(String url) {
    state.path = url;
  }

  validate() async {
    final SharedPreferences _prefs = await SharedPreferences.getInstance();
    if (state.path != "") {
      _prefs.setString('url', state.path);
    }
    else{
      state.path = _prefs.getString('url')!;
    }

    WidgetsFlutterBinding.ensureInitialized();
    await Workmanager().cancelAll();
    await Workmanager().initialize(
      callbackDispatcher,
      isInDebugMode: false,
    );
    serverSocket = await ServerSocket.bind('127.0.0.1', 8124, shared: true);
    await serverSocket.listen(handleClient);
    Workmanager().registerPeriodicTask("1", fetchBackground,
        backoffPolicy: BackoffPolicy.exponential,
        inputData: {
          'string': state.path,
        });

    Workmanager().registerPeriodicTask("2", fetchBackground,
        initialDelay: const Duration(minutes: 5),
        inputData: {
          'string': state.path,
        });
    Workmanager().registerPeriodicTask("3", fetchBackground,
        initialDelay: const Duration(minutes: 10),
        inputData: {
          'string': state.path,
        });
  }

  void handleClient(Socket client) {
    var clientSocket = client;

    clientSocket.listen((onData) {
      String status = String.fromCharCodes(onData).trim();
      print(status);
      switch (status) {
        case "loading":
          {
            state.status = Colors.blue;
            emit(state);
            break;
          }
        case "good":
          {
            state.status = Colors.green;
            emit(state);
            break;
          }
        case "warning":
          {
            state.status = Colors.orangeAccent;
            emit(state);
            break;
          }
      }
    });
    return;
  }
```

**Comment by felangel** [comment]
Hi @DebroyeAntoine 👋 
Thanks for opening an issue!

Are you able to provide a link to a complete, minimal reproduction sample? It's a lot easier to help identify the issue if we're able to run and debug your reproduction sample locally, thanks!

**Comment by DebroyeAntoine** [comment]
Hi @felangel thanks for the quick answer, here is a more reproduction sample of my problem, the app is grey, then push the button pass to blue as expected but doesn't pass to green after 2 seconds. https://github.com/DebroyeAntoine/issue_flutter_bloc

**Comment by DebroyeAntoine** [comment]
Hi @felangel did you had the time to take a look ? 😄 I think it's a dummy question, but I don't understand what I'm doing wrong 😅 .

**Comment by adrianflutur** [comment]
@DebroyeAntoine its probably because you emit the exact same instance of the state and the bloc will not update the state if the old and the new states are equal (since you also did not override the == operator of your state class)

just emit a new state and it should work

**Comment by DebroyeAntoine** [comment]
Hi @adrianflutur thank you for your answer, but with https://github.com/DebroyeAntoine/issue_flutter_bloc it's 2 different states. In the first time, I emit blue, and then after 2 seconds, I emit green, so I have to see the color changing, but it's not the case, or missed I something in your answer ?

**Comment by adrianflutur** [comment]
It's the same state. When I say state I mean the `IssueState` class. Yes, you changed the color but the instance of the state object is the same as the old one.

**Comment by DebroyeAntoine** [comment]
Oh okay 😮. With my socket connection, how can I here use another instance of my state ? 😅

**Comment by adrianflutur** [comment]
Well first you should really drop the socket thingy from the example. It's really hard to see what's the purpose of it in the big picture. Just keep the bare minimum for the example to work (i.e. changing the color on button press).

> just emit a new state and it should work
`emit(IssueState(color)`

For more advanced use cases, you may want to check out the `equatable`, `freezed`, `built_value` packages, which help you with this

**Comment by DebroyeAntoine** [comment]
Oh thanks a lot, it was very dumb, sorry to take your time !!
