### ISSUE TITLE
Bloc, state, and push navigation

### ISSUE THREAD

**Issue by paulinventome** [felangel/bloc#325]
I don't know if this is a bug or a lack of knowledge.

I have a page which displays a list of categories. This are pulled from an api and i have a BlocBuilder doing the checking of state and building this list. This works. The page is being called with a parent category and i dispatch the fetch event in the initState.

If you click on a category we display a list of sub categories. So i push the next page onto the stack (navigator.push) pass the new parent category and the new page slides in and refreshes.

There's an AppBar which provides the back button and pops the previous page on.

However popping any page takes me back to the previous page but the display is the category listing which we popped from. 

So it seems that navigator push/pop is not storing the state of the existing render. But i see no additional calls being made to the api when the page is popped. 

I can kind of see why. The Bloc is a singleton and navigator push is *not* storing the rendered widget tree. But at the same time i would have thought that navigator push would store enough state to be able to re-render the page being popped correctly.

So am i just approaching this wrong and in fact i shouldn't be pushing the sub category page on the stack? Instead i should be staying on the same page and updating the listing with the new parent code. But ideally I wanted the back button navigation to work as it makes UI sense...

Does this make sense?

I am still finding my way around blocs!

thanks
Paul

**Comment by felangel** [comment]
Hi @paulinventome 👋 
Thanks for opening an issue!

If I understood correctly, it seems like it's just a misunderstanding of how the navigator works. You are correct when you say the navigator push does not store the rendered widget tree so the state when you pop is not necessarily going to be the state before you pushed. Are you able to share a link to your code (or a sample app that illustrates the issue you're having). It would be much easier to give advice if  I could take a look at your implementation. Thanks! 👍

**Comment by paulinventome** [comment]
Hi @felangel, thank you so much for replying!

It could be a misunderstanding on my part. But my thinking is: if the navigator pushes a page to the stack then it would push it with all the parameters (in my case just one parameter) that was used calling it. So if the page is popped off the stack then that saved parameter is used to build the page the way it was. Prior to trying bloc i'd a test app up just using normal widgets and state and those pages pushed and popped correctly.

Because bloc is a global singleton what is happening is that there's no recreation of state or events for the bloc when the page is popped.

I'm adding some simple code to show, it's missing some of the rendering functions but has the core of the structure. If it's not enough let me know. So basically the page takes a category and the page gets called within itself to display a new category. When the back button is hit then the previous page shows the same state as the page you're on. So the popped page looses that start parameter.

To my mind it could be

1. I've totally misunderstood how navigator should work and i should not be structuring like this. Instead i should be just dispatching a new event on this page but then i don't know how to handle the back button i want

2. There is something odd going on and this should in theory work. Either i've not done something correctly, or maybe (just maybe) there's a bug in the bloc approach for this!

Kindest
Paul

```
class CategoriesPage extends StatefulWidget {

  final String startCode;
  CategoriesPage({@required this.startCode, @required Key key}) : super(key:key);

  @override
  _CategoriesPageState createState() => _CategoriesPageState(this.startCode);
}




class _CategoriesPageState extends State<CategoriesPage> {

String currentCode;
CategoryBloc catsBloc;

_CategoriesPageState(this.currentCode);


  
 @override
  void initState() {
    this.catsBloc = BlocProvider.of<CategoryBloc>(context);
    this.catsBloc.dispatch(FetchCategories(classcode: currentCode));
    print("initState: Dispatch: " + currentCode);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
 return Scaffold(
      appBar: CommonUI.TbAppBar(context),
      endDrawer: CommonUI.TbDrawer(context),
      body: Container(
        child: 
        BlocBuilder(
          bloc: catsBloc,
          builder: (context, CategoryState state) {
            print("BlocBuilder: State: " + state.toString());
            if (state is CategoryLoading) {
              return CircularProgressIndicator();
            }
            if (state is CategoriesLoaded) {
              if(state.categorylist == null || state.categorylist.length==0) {
                return Text("No Layouts");
              }
              print("BlocBuilder: renderListView: parentCode" + state.categorylist[0].code);
              return renderListView(context,state);
            }
            if (state is CategoryError) {
              return Text('Failure');
            }
            return Text("Unknown State");
          }
        )
      ),
    );
  }



  Widget renderListView(BuildContext context,CategoriesLoaded state) {
    return ListView.builder(
      key: new UniqueKey(),
      itemCount: state.categorylist.length,
      itemBuilder: 
      (context, position) {
        //print("In renderListView for state.parentcode" + state.categorylist[0].parentCode);
        return Container(
          child: ListTile(
                    contentPadding: EdgeInsets.all(5.0),
                    leading: _itemThumbnail(state.categorylist[position]),
                    title: _itemTitle(state.categorylist[position]),
                    subtitle: _itemSubtitle(state.categorylist[position]),
                    //trailing: _itemTrail(this.categories[index]),
                    onTap: () {
                       if(state.categorylist[position].numberClasses==0) {
                          Navigator.push(context, MaterialPageRoute(builder: (context) => ProductsPage(state.categorylist[position].code)));
                        } else {
                          Navigator.push(context, MaterialPageRoute(
                              settings: RouteSettings(arguments: state.categorylist[position].code),
                              builder: (context) => CategoriesPage(startCode: state.categorylist[position].code, key: UniqueKey(),)
                              ));
  
                          //this.catsBloc.dispatch(FetchCategories(classcode:state.categorylist[position].code));
                        }
                    }

                  )
        );
      }

    );
  }  
```

**Comment by felangel** [comment]
@paulinventome if you're modifying the state of the `CategoryBloc` in the pushed page and you're using a `BlocBuilder` in the initial page, then when you pop, the initial page will have updated because it is still subscribed to the same bloc. If you want to have them be decoupled, you might want to have two different blocs: one to manage the initial screen state and one to manage the push screen state. It's hard for me to give more concrete advice without more information so if that didn't help then it would be great if you could share a sample app which exhibits the issue and then I can give better advice/suggestions. Closing for now but feel free to comment if I wasn't helpful and I'm more than happy to continue the discussion. 👍

**Comment by paulinventome** [comment]
This does make sense and i understand why.

So yes, the CategoryBloc is global across the initial page and all the sub category pages. What i wasn't quite understanding is that when a page is popped back and that page has a parameter it was called with (the parent category). Then shouldn't that page get initialised again and the bloc be called again with the change in requested data?

So:

CategoryPage("rootcat') -> push -> CategoryPage("subcatA") -> push -> CategoryPage("subcatB") -> pop

When the last page is popped i would expect the block to get a message so it can prepare the list for subcatA because in the initState for CategoryPage the bloc is sent an event to fetch the categories.

So when a page is popped it seems that initState is not called again and actually what i need to do is to call the catBloc.dispatch() somewhere else, somewhere where a pop ensures that it is called?

Is there a best practise for where to dispatch an event to a bloc when a page is created? Maybe initState is not correct?

Thanks
Paul

**Comment by felangel** [comment]
@paulinventome `initState` is called only once when the page is created. When pages are pushed and popped, it doesn't have an impact on the underlying pages so `initState` will not be called again. I think you need to refactor your bloc setup because it seems you're trying to use a single bloc instance to manage the stages of three different pages instead of a bloc to manage each.

Hope that helps 👍 

If you join the [gitter chat](https://gitter.im/bloc_package/Lobby) we can continue to discuss this there as well as potentially setup a live coding session to work through this issue.
