### ISSUE TITLE
docs: Login Bloc tutorial to be updated with Navigator 2.0

### ISSUE THREAD

**Issue by rahulrmishra** [felangel/bloc#3251]
Hi, I was wondering when could we get the login tutorial updated with Navigator 2?

**Comment by felangel** [comment]
Hi @rahulrmishra 👋 
Thanks for opening an issue!

The [firebase login example](https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login) is using navigator 2.0 via [package:flow_builder](https://pub.dev/packages/flow_builder). If you have specific questions about how to use Navigator 2.0 APIs feel free to ask in the [Discord](https://discord.gg/bloc) 👍
