### ISSUE TITLE
feat: hydrated_bloc storageToken override

### ISSUE THREAD

**Issue by liviuls** [felangel/bloc#3255]
**Description**

First of all hi, amazing job to everyone that developed this package!

I have a use case where hydrated_bloc has a bit of an issue. I obfuscate the dart code every time I create a new production build for the stores. Because the storageToken uses runtimeType, which changes with every new build because of the obfuscation, the state data gets lost, and by lost I mean that the bloc will look in the wrong place in storage for the persisted state. 

**Desired Solution**

To be obfuscation compliant, we should be able to override the storageToken.

Thanks!

**Comment by b055man** [comment]
This is fantastic finding! We've been struggling with unreliable upgrades of the app for quite some time and were not sure what causes the data loss. 
Now, this issue seems to explain the problems we observed.
@felangel any ETA for addressing this? @liviuls do you know if there is any workaround for this issue possible?

**Comment by liviuls** [comment]
@b055man for now we've forked the package and made storageToken overridable and used custom values for the storageToken that don't include the runtimeType

**Comment by b055man** [comment]
@liviuls thanks! would you mind sharing that fork perhaps?

**Comment by felangel** [comment]
I’m planning to address this sometime today 👍

**Comment by liviuls** [comment]
@b055man I can't share it because it's an internal fork, but the main idea is that we used a prefix in combination with the id. It's very important to override this id in order to have different storage locations for different bloc types. But maybe you can just wait for an update from @felangel.

![image](https://user-images.githubusercontent.com/13398323/156777803-45993530-ab10-4b07-964a-4a00cfc34d41.png)

**Comment by felangel** [comment]
> @b055man I can't share it because it's an internal fork, but the main idea is that we used a prefix in combination with the id. It's very important to override this id in order to have different storage locations for different bloc types. But maybe you can just wait for an update from @felangel.
> 
> ![image](https://user-images.githubusercontent.com/13398323/156777803-45993530-ab10-4b07-964a-4a00cfc34d41.png)

The problem with that approach is if you don’t override id, you’ll have storage conflicts.

**Comment by felangel** [comment]
I opened #3261 to address this. @b055man @liviuls can you test the changes on the branch locally and let me know if you have any issues? The changes should be backward compatible so you shouldn't lose any data.

**Comment by domindx** [comment]
@felangel it seems that obfuscation is not the only problem here.
We will meet the same issue when bloc name has changed between app versions. 
Maybe that is something which may be worth mentioning in package documentation?

And second thing:
Does anyone have a good idea how to migrate the state saved with obuscated app version?
I was thinking about 'manually' looking into hive box, the keys seems to be ordered by the time they were stored. Looking through most recent ones may do the job.
What do you think?

**Comment by felangel** [comment]
@b055man @liviuls @domindx I opened https://github.com/felangel/bloc/pull/3262 to attempt to address this. It exposes a `storagePrefix` which can be overridden like:

```dart
class CounterBloc extends HydratedBloc<CounterEvent, int> {
  CounterBloc() : super(0) {
    on<CounterIncrementPressed>((event, emit) => emit(state + 1));
    on<CounterDecrementPressed>((event, emit) => emit(state - 1));
  }

  @override
  String get storagePrefix => 'CounterBloc';

  @override
  int fromJson(Map<String, dynamic> json) => json['value'] as int;

  @override
  Map<String, int> toJson(int state) => {'value': state};
}
```

This should address obfuscation issues as well as bloc renaming issues. Please try the changes in the branch and let me know what you think, thanks! 🙏

**Comment by domindx** [comment]
@felangel Thanks for providing solution so fast. 
It looks nice, but I would rather make `storagePrefix` abstract so it would need to be explicitly defined.

I know that we will loose some backward compatibility.
From the other hand it will make everyone aware how the storage works, and that there is possiblity to unintetionally loose the data.

There is a chance that many users may be already affected by that issue but they dont know it yet.

**Comment by felangel** [comment]
> @felangel Thanks for providing solution so fast. It looks nice, but I would rather make `storagePrefix` abstract so it would need to be explicitly defined.
> 
> I know that we will loose some backward compatibility. From the other hand it will make everyone aware how the storage works, and that there is possiblity to unintetionally loose the data.
> 
> There is a chance that many users may be already affected by that issue but they dont know it yet.

I’d prefer to leave it optional because HydratedBloc is not a replacement for a database. It’s just a mechanism to cache feature state and in most cases it shouldn’t be a big deal if cached data is lost (especially between debug/release builds). With the current approach you can opt into providing your own storage prefix but for cases where it’s not critical, you aren’t forced to specify one and the change is backward compatible.

**Comment by domindx** [comment]
> > @felangel Thanks for providing solution so fast. It looks nice, but I would rather make `storagePrefix` abstract so it would need to be explicitly defined.
> > I know that we will loose some backward compatibility. From the other hand it will make everyone aware how the storage works, and that there is possiblity to unintetionally loose the data.
> > There is a chance that many users may be already affected by that issue but they dont know it yet.
> 
> I’d prefer to leave it optional because HydratedBloc is not a replacement for a database. It’s just a mechanism to cache feature state and in most cases it shouldn’t be a big deal if cached data is lost (especially between debug/release builds). With the current approach you can opt into providing your own storage prefix but for cases where it’s not critical, you aren’t forced to specify one and the change is backward compatible.

Ok, got it 👍 
It would be perfect to have that information in package description too.

**Comment by liviuls** [comment]
@felangel great stuff, looks good to me!

**Comment by aggeloskoutanis** [comment]
@domindx Did you find a good migration strategy for the obfuscated storagePrefix?

**Comment by add022** [comment]
> [@domindx](https://github.com/domindx) Did you find a good migration strategy for the obfuscated storagePrefix?

@aggeloskoutanis sure,
once I know the obfuscated storage key name I've implemented custom `Storage` which attempts to read hydrated data from this key if it cannot be retreived using `storagePrefix`.

This should restore the bloc state from obfuscated storage key and further writes/reads should use `storagePrefix`.
