### ISSUE TITLE
[Question] how to update the URL when using Flutter for web with the Navigator 2.0 option

### ISSUE THREAD

**Issue by MdeBruin93** [felangel/bloc#3256]
Hello there,

I'm currently building a simple website using Flutter and looking into your "Navigation 2.0" solution. However, how does it update the URL to make sure that the website doesn't have to remember the entire state of the app?

Hope to hear from you.

**Comment by felangel** [comment]
Hi this is currently a work in progress on `package:flow_builder`. You can track the progress at https://github.com/felangel/flow_builder/tree/feat/url-routing-and-deep-linking. I'm hoping to add support for it in the next week or two.

**Comment by MdeBruin93** [comment]
Looks great, but I'm failing see how it can read the URL from the browser.
