### ISSUE TITLE
fix: Emitter for stream does not provide StreamSubscription

### ISSUE THREAD

**Issue by trigri1** [felangel/bloc#3258]
**Description**
I am trying to migrate to version 8.0.0. In my bloc, there are some streams that I want to listen to using `emitter.forEach`. But the problem is I want to get the subscription so that I can pause the stream for some time and then resume later on. There does not appear to be any obvious solution other than using `listen` that I am trying to remove for consistency. 
Is there a way to get a subscription from Emitter?

**Expected Behavior**
There could be a way to get the subscription from Emitter or have some public method(s) inside the Emitter that can pause/cancel a particular stream subscription.

**Comment by felangel** [comment]
Hi @trigri1 👋 
Thanks for opening an issue!

If you use `forEach` or `onEach` from the `Emitter` then the `StreamSubscription` will be managed for you by the bloc. If you want granular controller over the `StreamSubscription` then you should manage it yourself and use `listen`. See the [timer example](https://github.com/felangel/bloc/blob/master/examples/flutter_timer/lib/timer/bloc/timer_bloc.dart) for reference.

Hope that helps 👍

**Comment by trigri1** [comment]
hey @felangel!

Thank you for the reply. I checked this example and I am already using `listen` ut for the sake of consistency I wanted to use the Bloc way to manage the Presentation layer. 

Maybe this can be considered an improvement for some future release?

**Comment by felangel** [comment]
> hey @felangel!
> 
> Thank you for the reply. I checked this example and I am already using `listen` ut for the sake of consistency I wanted to use the Bloc way to manage the Presentation layer.
> 
> Maybe this can be considered an improvement for some future releases?

There’s nothing wrong with using listen when you need to manage the subscription yourself.

**Comment by felangel** [comment]
Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍
