### ISSUE TITLE
fix: bloc throwing widget is not a function error with latest version of flutter 2.10.3

### ISSUE THREAD

**Issue by mayor04** [felangel/bloc#3266]
**Description**
Bloc throwing widget is not a function error with latest version of flutter 2.10.3 
flutter_bloc version 8.0.1

**Steps To Reproduce**

1. Upgrade to flutter 2,10,3
2. Build application on windows, web or mobile
3. See error
```
     : Error: 'widget' isn't a function or method and can't be invoked.
../…/src/selector.dart:85
      cache = widget().builder(
Error: 'widget' isn't a function or method and can't be invoked.
../…/src/selector.dart:84
      oldWidget = widget();

```

**Expected Behavior**

**Screenshots**

**Additional Context**
My windows app was previously working before the flutter upgrade, I also tested it on 2 other projects which also produces the same issue.

**Comment by felangel** [comment]
Hi @mayor04 👋
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? Thanks!

**Comment by mayor04** [comment]
Good day, while trying to reproduce the error I downgraded and still got the same error 

So I had to delete flutter and most packages from the pub cache and it was fixed.

Sorry for any inconveniences I caused

I will proceed to closing the issue. Thanks for your time
