### ISSUE TITLE
Bloc for JavaScript?

### ISSUE THREAD

**Issue by jagdishjadeja** [felangel/bloc#327]
is bloc available for AngularJS ?

**Comment by felangel** [comment]
Hi @jagdishjadeja 👋 
Thanks for opening an issue!

There currently isn’t a JavaScript library but if it’s something you would like, I would love to hear more about why. The main reason I haven’t made one is because dart can be used for web with AngularDart (and soon Flutter). Thanks 👍

**Comment by felangel** [comment]
Closing for now since there doesn't seem to be much interest in the topic. I'm happy to reopen this in the future if people think it's worthwhile discussing 👍

**Comment by localpcguy** [comment]
We're starting an Angular (standard, not dart) project and since our mobile apps use Flutter/Dart with the BLoC pattern, we're exploring using BLoC in the Angular app as well. I like some of the patterns these plugins expose, so might at a minimum adapt our code to use those patterns. If it becomes something that could be usable by others, I'll see if I can't break it out publicly as a library or external module.

**Comment by felangel** [comment]
@localpcguy that’s awesome! Keep us updated 😄

I don’t think it would be that much effort to port the core bloc library over to js. I can try to mess with it when I have some time later this week especially if it would benefit others.

**Comment by localpcguy** [comment]
While we're definitely moving forward with the BLoC pattern, I don't know if we'll use this specific implementation. The limitation of just one stream in, one stream out doesn't match how we've been using BLoCs. I understand the thinking behind it (single responsibility), but sometimes sharing functionality in a `bloc` file while allowing multiple output streams or multiple incoming events is helpful from an organizational perspective and splitting that up to multiple `bloc` files would add complexity without a lot of gain, in our perspective. 

Just wanted to provide that update, I know this comment isn't specific to JS but didn't want you to go through a bunch of work for us and not have us take advantage of it.

**Comment by felangel** [comment]
@localpcguy thanks for the update and best of luck!

**Comment by felangel** [comment]
For anyone interested: https://github.com/felangel/bloc.js
