### ISSUE TITLE
[Question] Run tests included sub packages

### ISSUE THREAD

**Issue by Tokenyet** [felangel/bloc#3274]
Just wanna ask how did you test locally. I just saw [1.20.2-dev](https://github.com/dart-lang/test/blob/master/pkgs/test/CHANGELOG.md#1202-dev) released, and my project have 20+ packages. 

The workaround for me is the test tab from vscode, then I could choose the test. For the case, I wish I could use `flutter test --exclude-tags someTag` or `dart test --exclude-tags someTag` to run all tests included sub-packages.

Any advice would be appreciated!

**Edit:**
Just check the [1.20.2-dev](https://github.com/dart-lang/test/pull/1668/files), seems that If the version release, the ci with the structure might have a redundant run? https://github.com/felangel/bloc/blob/330d43be7300c879f1abdd5515ea71c7559470e7/.github/workflows/flutter_examples.yaml#L62-L65

`flutter test examples/flutter_todos` will run the sub packages by default.

**Comment by mrverdant13** [comment]
At the moment, the only way to achieve what you describe is by using a mono-repo or multi-package manager.

There are two alternatives, here:
- [`mono_repo`](https://pub.dev/packages/mono_repo) by Google
- [`melos`](https://pub.dev/packages/melos) by Invertase

Besides that, [`very_good_cli`](https://pub.dev/packages/very_good_cli)'s contributors are currently working on a feature focused on testing.
Check VeryGoodOpenSource/very_good_cli#279.

**Comment by Tokenyet** [comment]
Thanks for sharing the research!
