### ISSUE TITLE
[Question] What is the reason for making AuthenticationEvent extends Equatable

### ISSUE THREAD

**Issue by henryliang3027** [felangel/bloc#3277]
I'm very new to flutter bloc. Recently, I've read your Login tutorial and I am curious about why you make `AuthenticationEvent extends Equatable` in [flutter login tutorial](https://bloclibrary.dev/#/flutterlogintutorial?id=authentication_eventdart) ?

What I understand about the reason for making `AuthenticationState extends Equatable` is to make sure the same state will not trigger the bloc to process. However, when we add the AuthenticationEvent, it will always trigger the bloc to process whether we make `extends Equatable` or not. Users may trigger the same event multiple times generally, so we can make it work without extending Equatable as well.

Not sure whether my understanding is correct. Any explanation would be appreciated.

**Comment by BartWesthoff** [comment]
I think it is in general a better idea to have the event extens equatable not specific for this use case.

**Comment by felangel** [comment]
Hi @henryliang3027 👋 
Thanks for opening an issue!

Events extend Equatable for several reasons:
- ease of testing/comparisons
- to support event transformers like distinct
- consistency

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
