### ISSUE TITLE
[PROPOSAL] fallback to window.sessionStorage on Firefox private browsing

### ISSUE THREAD

**Issue by danjodanjo** [felangel/bloc#3278]
Hi everyone! I hope everyone is in a good shape.

**Current Issue and some investigation**

One of my team encountered an issue when trying to initialise `HydratedBloc.storage` in main on web platform, specifically on firefox private browsing. Upon launching the app, it causes the app to not load at all. Catching the error on initialisation creates another issue because `HydratedBloc.storage` will end up as `null` thus persisting the states is pretty much impossible. This issue is the same as opened here [https://github.com/felangel/bloc/issues/2423](https://github.com/felangel/bloc/issues/2423)

After some investigation, it appears that `hive` uses `indexedDb' as its storage and this functionality is disabled in firefox private browsing causing an error to be thrown. Here is the reference [https://github.com/hivedb/hive/issues/800](https://github.com/hivedb/hive/issues/800)

**Desired Solution**

I would like to extend the implementation of HydratedStorage in `hydrated_storage.dart`. If initialising storage using hive is not possible, I would like the storage to fallback to window.sessionStorage. 

```dart
if (storageDirectory == webStorageDirectory) {
        try {
          box = await hive.openBox<dynamic>(
            'hydrated_box',
            encryptionCipher: encryptionCipher,
          );
          // fallback to window.sessionStorage should
          // hive is accessed through firefox private browsing
        } catch (_) {
          storage = uni_html.window.sessionStorage;
        }
```

Here I used `universal_html` package since using `dart:html` of `window.sessionStorage`  will make it impossible for the package to be built to mobile / other platform.

As for the `read`, `write`, `delete`, and `clear`, i added one more implementation for sessionStorage just below the box CRUD operation. Here's for the `read` operation:

```dart
  @override
  dynamic read(String key) {
    if (_box?.isOpen ?? false) {
      return _box?.get(key);
    }

    if (_storage != null) {
      return (_storage!.containsKey(key)) ? jsonDecode(_storage![key]!) : null;
    }

    return null;
  }
```
Full implementation is in this branch at the moment [https://github.com/danjodanjo/bloc/tree/refactor/hydrated-bloc-fallback-sessionStorage-web](https://github.com/danjodanjo/bloc/tree/refactor/hydrated-bloc-fallback-sessionStorage-web)

Hopefully I can get some feedback regarding this change proposal. Thank you!

**Comment by danjodanjo** [comment]
Hmm, makes sense. Since in the end `indexedDB` is being called in `hive`, improving it on the `hive` implementation will also fix any packages that depends on it. My first mindset when improving is to not touch the low level and provide alternative on a top level implementation for short term solution.
I think I will try to extend this implementation in `hive` instead and propose it to them, though it may take a while.

Thank you for the feedback @felangel and cheers!

**Comment by felangel** [comment]
No problem! Closing this for now since there isn't any additional work to be done in bloc. Feel free to drop a link to the hive issue so others can leave a 👍
