### ISSUE TITLE
BlocBuilder condition bug - _previousState == null

### ISSUE THREAD

**Issue by CosmicPangolin** [felangel/bloc#328]
First off, thanks for including the condition  :)

I think there's a bug in _BlocBuilderBaseState.  If I initialize a BlocBuilder with a condition, previousState defaults to null even if the provided bloc has an existing state...so the listener built in _subscribe() necessarily throws a null error on the bloc's next state change (assuming you're using an operator on previousState).

I think this can be fixed by setting _previousState = widget.bloc.currentState in the initState() method...ie. same assignment as state.

**Comment by felangel** [comment]
@CosmicPangolin thanks for catching this! I’ll have it fixed later today 👍

**Comment by felangel** [comment]
Fixed in #329 and included in `v0.15.1` of `flutter_bloc`.
