### ISSUE TITLE
fix: state.runtimTypes prints minified:uZ

### ISSUE THREAD

**Issue by ronytesler** [felangel/bloc#3280]
flutter_bloc: ^8.0.1

I have this code:```

BlocListener<UserBloc, UserState>(
          listener: (context, state) {
            print(state.runtimeType);
```
And some states like this one: `class UserLoggedOutState extends UserState {}`

After I deploy the project to Firebase, the print statements print "minified:Cg" and "minified:uZ" and similar things.
In my local development environment it prints "UserLoggedOutState" normally.

**Comment by felangel** [comment]
Hi @ronytesler 👋
Thanks for opening an issue!

This is working as expected and has nothing to do with bloc. RuntimeType will be different depending on the environment the code is running in and whether it’s a debug/release build.
