### ISSUE TITLE
bloc listner not responding to state changes. 

### ISSUE THREAD

**Issue by alanbosco003** [felangel/bloc#3294]
**Problem**
Bloc listner not changeing to state changes. I use a bloc for login purpose, it is passing to the login page and when the state changes to goes to home page working perfectly, But the problem is when i try to logout. When the got out event is triggered and the logout state is set but in the authentication page the bloc listener is not rebuilding the UI. 

**Steps To Reproduce**
my auth page:- 

```
  Widget build(BuildContext context) {
    loginBloc = BlocProvider.of<LoginBloc>(context);

    loginBloc.add(CheckIfLogedInEvent());
    return Scaffold(
      body: BlocListener<LoginBloc, LoginState>(
          listener: (context, state) {
            if (state is LoginSuccesfullState) {
              Navigator.pushReplacementNamed(context, 'home');
            } else {
              Navigator.pushReplacementNamed(context, 'login');
            }
          },
          child: const CircularProgressIndicator()),
    );
  }
```
my Logut button in home page

```
     TextButton(
              onPressed: () {
                BlocProvider.of<LoginBloc>(context).add(LogOutEvent());
                // Navigator.pop(context);
              },
              child: const Text("logout"))
```

my login bloc:-

```
import 'package:bloc/bloc.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:equatable/equatable.dart';
import 'package:samplebloc/modules/login/models/loginresponce.dart';
import 'package:samplebloc/repositorys/loginapi.dart';
import 'package:samplebloc/service/connectivity.dart';

part 'login_event.dart';
part 'login_state.dart';

class LoginBloc extends Bloc<LoginEvent, LoginState> {
  final LoginService _loginService;
  final ConnectivityService _connectivityService;
  LoginBloc(this._loginService, this._connectivityService)
      : super(LogoutState()) {
    _connectivityService.connectivityStream.stream.listen((event) {
      if (event == ConnectivityResult.none) {
        add(NoInternetEvent());
      } else {
        add(LogOutEvent());
      }
    });
    on<CheckIfLogedInEvent>((event, emit) {
      emit(LogoutState());
    });
    on<FetchLoginEvent>((event, emit) async {
      emit(LoadingState());
      LoginResponce loginResponce =
          await _loginService.login(event.username, event.password);
      emit(LoginSuccesfullState());
    });
    on<LogOutEvent>((event, emit) {
      emit(LogoutState());
    });
    on<LoginpageEvent>((event, emit) {
      emit(LoginPageState());
    });
    on<NoInternetEvent>((event, emit) {
      emit(NoInternetConnectionState());
    });
  }
}

```
This is the github repo : - https://github.com/alanbosco003/bloc-login/tree/main/bloc_login

Thank you

**Comment by fodor99** [comment]
> **Problem** Bloc listner not changeing to state changes. I use a bloc for login purpose, it is passing to the login page and when the state changes to goes to home page working perfectly, But the problem is when i try to logout. When the got out event is triggered and the logout state is set but in the authentication page the bloc listener is not rebuilding the UI.
> 
> **Steps To Reproduce** my auth page:-
> 
> ```
>   Widget build(BuildContext context) {
>     loginBloc = BlocProvider.of<LoginBloc>(context);
> 
>     loginBloc.add(CheckIfLogedInEvent());
>     return Scaffold(
>       body: BlocListener<LoginBloc, LoginState>(
>           listener: (context, state) {
>             if (state is LoginSuccesfullState) {
>               Navigator.pushReplacementNamed(context, 'home');
>             } else {
>               Navigator.pushReplacementNamed(context, 'login');
>             }
>           },
>           child: const CircularProgressIndicator()),
>     );
>   }
> ```
> 
> my Logut button in home page
> 
> ```
>      TextButton(
>               onPressed: () {
>                 BlocProvider.of<LoginBloc>(context).add(LogOutEvent());
>                 // Navigator.pop(context);
>               },
>               child: const Text("logout"))
> ```
> 
> my login bloc:-
> 
> ```
> import 'package:bloc/bloc.dart';
> import 'package:connectivity_plus/connectivity_plus.dart';
> import 'package:equatable/equatable.dart';
> import 'package:samplebloc/modules/login/models/loginresponce.dart';
> import 'package:samplebloc/repositorys/loginapi.dart';
> import 'package:samplebloc/service/connectivity.dart';
> 
> part 'login_event.dart';
> part 'login_state.dart';
> 
> class LoginBloc extends Bloc<LoginEvent, LoginState> {
>   final LoginService _loginService;
>   final ConnectivityService _connectivityService;
>   LoginBloc(this._loginService, this._connectivityService)
>       : super(LogoutState()) {
>     _connectivityService.connectivityStream.stream.listen((event) {
>       if (event == ConnectivityResult.none) {
>         add(NoInternetEvent());
>       } else {
>         add(LogOutEvent());
>       }
>     });
>     on<CheckIfLogedInEvent>((event, emit) {
>       emit(LogoutState());
>     });
>     on<FetchLoginEvent>((event, emit) async {
>       emit(LoadingState());
>       LoginResponce loginResponce =
>           await _loginService.login(event.username, event.password);
>       emit(LoginSuccesfullState());
>     });
>     on<LogOutEvent>((event, emit) {
>       emit(LogoutState());
>     });
>     on<LoginpageEvent>((event, emit) {
>       emit(LoginPageState());
>     });
>     on<NoInternetEvent>((event, emit) {
>       emit(NoInternetConnectionState());
>     });
>   }
> }
> ```
> 
> This is the github repo : - https://github.com/alanbosco003/bloc-login/tree/main/bloc_login
> 
> Thank you

Hi alabosco003

if You extend Your LoginBloc with 2 override function:
@override
  void onEvent(YOUREVENT event) {
    super.onEvent(event);
  }

  @override
  void onTransition(Transition<YOUREVENT, YOURSTATE> transition) {
    super.onTransition(transition);
  }
and You set debugger points on calling super.* debugger catches the state change while the program is running?
I have something similar bug with the BlocListener like You have... and I wonder this is similar or not...

**Comment by alanbosco003** [comment]
Hi @fodor99 Thanks for responding. 
Sorry i didn't get what you said. can you please clone the project and check it yourself?

**Comment by Add00w** [comment]
> **Problem** Bloc listner not changeing to state changes. I use a bloc for login purpose, it is passing to the login page and when the state changes to goes to home page working perfectly, But the problem is when i try to logout. When the got out event is triggered and the logout state is set but in the authentication page the bloc listener is not rebuilding the UI.
> 
> **Steps To Reproduce** my auth page:-
> 
> ```
>   Widget build(BuildContext context) {
>     loginBloc = BlocProvider.of<LoginBloc>(context);
> 
>     loginBloc.add(CheckIfLogedInEvent());
>     return Scaffold(
>       body: BlocListener<LoginBloc, LoginState>(
>           listener: (context, state) {
>             if (state is LoginSuccesfullState) {
>               Navigator.pushReplacementNamed(context, 'home');
>             } else {
>               Navigator.pushReplacementNamed(context, 'login');
>             }
>           },
>           child: const CircularProgressIndicator()),
>     );
>   }
> ```
> 
> my Logut button in home page
> 
> ```
>      TextButton(
>               onPressed: () {
>                 BlocProvider.of<LoginBloc>(context).add(LogOutEvent());
>                 // Navigator.pop(context);
>               },
>               child: const Text("logout"))
> ```
> 
> my login bloc:-
> 
> ```
> import 'package:bloc/bloc.dart';
> import 'package:connectivity_plus/connectivity_plus.dart';
> import 'package:equatable/equatable.dart';
> import 'package:samplebloc/modules/login/models/loginresponce.dart';
> import 'package:samplebloc/repositorys/loginapi.dart';
> import 'package:samplebloc/service/connectivity.dart';
> 
> part 'login_event.dart';
> part 'login_state.dart';
> 
> class LoginBloc extends Bloc<LoginEvent, LoginState> {
>   final LoginService _loginService;
>   final ConnectivityService _connectivityService;
>   LoginBloc(this._loginService, this._connectivityService)
>       : super(LogoutState()) {
>     _connectivityService.connectivityStream.stream.listen((event) {
>       if (event == ConnectivityResult.none) {
>         add(NoInternetEvent());
>       } else {
>         add(LogOutEvent());
>       }
>     });
>     on<CheckIfLogedInEvent>((event, emit) {
>       emit(LogoutState());
>     });
>     on<FetchLoginEvent>((event, emit) async {
>       emit(LoadingState());
>       LoginResponce loginResponce =
>           await _loginService.login(event.username, event.password);
>       emit(LoginSuccesfullState());
>     });
>     on<LogOutEvent>((event, emit) {
>       emit(LogoutState());
>     });
>     on<LoginpageEvent>((event, emit) {
>       emit(LoginPageState());
>     });
>     on<NoInternetEvent>((event, emit) {
>       emit(NoInternetConnectionState());
>     });
>   }
> }
> ```
> 
> This is the github repo : - https://github.com/alanbosco003/bloc-login/tree/main/bloc_login
> 
> Thank you

I cloned your code and it's working fine when logout it shows signin page.

**Comment by felangel** [comment]
Closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍
