### ISSUE TITLE
Proper way of using bloc/cubit to do api calls and store user behaviour 

### ISSUE THREAD

**Issue by kmigntw** [felangel/bloc#3297]
Hi guys,

This is more like a question, rather than an actual issue. It is a use case I face a lot and I took different approach to resolve it everytime, but I have no idea which one is the best and like 'best practice'. It is some kind related to #182 

I have the following use case:
I have a page with list of data. This data is based on several different parameters.

For getting the data I have a Cubit with Initial, Loading, Loaded and Errored states.

But I also need to track the different parameters that I have to send to the server. 
For example I have filtering on 8 different filters. I do not only need to filter but to "remember" which filter was choosen last.
I have sorting of different columns, again I need to know what the user chooses.
I have dropdown button where the user can choose different type of data
I have a group buttons for choosing the different time frame, e.g. 1 day, 1 week, 1 month, 1 year and so on

Everytime the user chooses something I need to do a request to an API with the choosen parameters and to mark them as choosen in the UI.

- One of the approaches will be to emit the state with the received data, the chosen filter, time frame, type of data and so on. So basically everything I need to be in the state.
- Also I tried puting the different parameters in the abstract State class, but this also means to emit the Loaded state and pass the parameters to the super constructor. So it is more or less the same as the first approach
- Another approach is to have 2 cubits - one for the actual api request and emitting the loaded state and one for tracking the different parameters (something like LoginState from the login tutorial)

What will be better in this case? Also is there any other approach that will fit my needs better?

Thank you in advance!

**Comment by aaassseee** [comment]
@kmigntw I think the proper way is you may separate the feature with different bloc like service bloc and form bloc.
For service bloc, you should only implement the network calling and deserialising feature. With form bloc, you should handle the values with filtering, if hand made form bloc is hard and time consuming you should checkout [form_bloc](https://pub.dev/packages/flutter_form_bloc). There is also a [interactive web](https://giancarlocode.github.io/form_bloc/#/) may inspire you with the same situation
