### ISSUE TITLE
Why _BlocProviderInherited.updateShouldNotify is hardcoded to false ?

### ISSUE THREAD

**Issue by sestegra** [felangel/bloc#33]
It seems that following implementation could be used when updating bloc itself.
``` dart
class _BlocProviderInherited<T extends Bloc<dynamic, dynamic>>
  ...
  bool updateShouldNotify(_BlocProviderInherited oldWidget) => oldWidget.bloc != bloc;
}
```

**Comment by felangel** [comment]
@sestegra that was an intentional performance optimization because blocs should not change; only their states should change. Can you please describe the use case that requires these changes?

**Comment by felangel** [comment]
Closing this for now.
