### ISSUE TITLE
refactor:  Question: Does adding events from inside gesture detector's onPanUpdate method affects performance?

### ISSUE THREAD

**Issue by Haidar0096** [felangel/bloc#3303]
**Description**

I have an image wrapped inside a `GestureDetector`, and inside the `onPanUpdate` handler I am adding events to the bloc to change the saved state (i.e. change the saved position i..e. `Offset` of the image inside the bloc's state), like this: 

```
                             onPanUpdate: (details) {
                                BlocProvider.of<EditorBloc>(context).add(
                                  EditorEvent.elementDragged(...),
                                );
                              },
```

However I notice lagging animations when I drag the image fast (you can guess already that hundreds or thousands of events are being added to the bloc in this interval of seconds.

I am building the app for linux and running it on linux, but running in both debug and release mode are lagging in this thing.

Is this due to flutter being still poor on linux or is this wrong usage of bloc or is it netiher?

Thanks in advance :)

Also sorry for asking under the refactor category I couldn't find the questions category

**Comment by marcossevilla** [comment]
hi, @Haidar0096 👋 

blocs are very performant but I suggest applying some kind of debounce for this kind of interaction, you can take some inspiration from photobooth on the photobooth preview [widget](https://github.com/flutter/photobooth/blob/main/lib/photobooth/widgets/photobooth_preview.dart#L119) where an event is [transformed](https://github.com/flutter/photobooth/blob/e23be72f669b2581490202169cc1c2b157e2c165/lib/photobooth/bloc/photobooth_bloc.dart#L37) when added to the bloc. You'll have to implement it with the new EventTransformer API using [bloc_concurrency](https://pub.dev/packages/bloc_concurrency).

let me know if that helps 👍

**Comment by Haidar0096** [comment]
> 

thanks for the reply, I don't understand what you mean by debounce. But I looked at the method that handles the bloc event that you mentioned, and I am doing the same thing in my bloc exactly: send raw data (drag details) from widget into the bloc and call the service inside the bloc's handling method, [here it is ](https://github.com/maheshmnj/Image-Editor-Desktop-Flutter/blob/67ab7ad48b5a423da396e75208619bd3bc3005ff/lib/presentation/screens/edit_image_screen/bloc/editor_bloc.dart#L110) 

Is this not the right way to do it?

**Comment by marcossevilla** [comment]
the drag update should be an event added to the bloc so it can be processed. I suggest you take a look at this [blog](https://verygood.ventures/blog/how-to-use-bloc-with-streams-and-concurrency) about blocs and event transformers, which also has a code [example](https://github.com/VGVentures/bloc_concurrency_demos). I think with a decent amount of debounce duration (you can check again photobooth to see how to do the gesture update) your code will have good performance for FPS, but try to keep the state as simple as possible so the computations are quick.

**Comment by marcossevilla** [comment]
will close this issue but feel free to continue the conversation if the examples aren't clear enough!
