### ISSUE TITLE
fix: Bloc Listener Widget not checking if widget is mounted before calling listener callback.

### ISSUE THREAD

**Issue by sultanhunter** [felangel/bloc#3310]
**Description**
Bloc listener widget is not checking if the widget is mounted before calling the listener callback. As a result if the state changes between unmounted and dispose state due to some api response, it throws error since we can't use the context as the widget is unmounted.

**Steps To Reproduce**

1. Its hard to reproduce, but I encountered while building the app for my company.

**Expected Behavior**

I am able to solve it by modifying the bloc listener for checking if the widget is mounted before calling the listener callback. If it is unmounted I am unsubscribing from the state stream.

**Comment by felangel** [comment]
Hi @sultanhunter 👋 
Thanks for opening an issue!

It would be extremely helpful if you could try to put together a minimal reproduction sample. I know you said it was hard to reproduce but it's very difficult to triage/resolve an issue without a reproduction sample, thanks!

**Comment by sultanhunter** [comment]
I tried a lot to reproduce the issue but failed to do so. You can close the issue. Thanks.

**Comment by sultanhunter** [comment]
Sure.

**Comment by sultanhunter** [comment]
Sure.
