### ISSUE TITLE
Update state in different page and rebuild page - Bloc

### ISSUE THREAD

**Issue by iammiland** [felangel/bloc#3311]
Hi,
i have a question.

This is my actually condition:

**PAGE1**
|- BlocProvider Bloc1
|- BlocBuilder Bloc1, BlocState1
|-> IconButton : Navigator.of(context).push(NaterialPageRoute( builder: (context) => PAGE2())),

**PAGE2**
|- BlocProvider Bloc2
|- BlocListener Bloc2
|- BlocBuilder Bloc2
|-> IconButton that update item in PAGE2, and in PAGE1

If i want that action below IconButton in PAGE2 change the state of Bloc in PAGE1 and, in case, refresh it, how should I do ?

**Comment by felangel** [comment]
Hi @iammiland 👋 
Thanks for opening an issue!

In the case you described, you'd need to provide Bloc1 above both Page1 and Page2. Then you can access Bloc1 from Page2 via `context.read` and add an event to update the state.

Hope that helps 👍

**Comment by iammiland** [comment]
Hi @felangel 
thanks for your help 👍 

I try to use :
- MultiblocProvider with Bloc1 and Bloc2 in Page1
- MultiblocProvider with Bloc1 and Bloc2 in Page2

But when i add an event with the _context.read_ to the Bloc1 in Page2 that changes the state of Bloc1, the listener in Page1 doesn't listen the new state and i'am not able to rebuild the Page1.

I hope I have explained well.
If not, I can add portions of code 👍

**Comment by erlangparasu** [comment]
did you try BlocProvider.value ?

https://bloclibrary.dev/#/recipesflutterblocaccess?id=homepage

<img width="608" alt="image" src="https://github.com/felangel/bloc/assets/20636828/0d2b9b7d-d36e-4ebe-ba6b-70b7da16fcc0">
