### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by CodeRebirth** [felangel/bloc#3313]
I have a bloc called specialityBloc which will fetch doctors according to their speciality from firestore by delegating it to a repository.

The problem is when I want to fetch different doctors with different speciality and emit them from same state(fetchSuccessState).

I am able to fetch them separately from firestore but when It comes to rendering in the UI using different bloc builders(that listen to the same specialityBloc).It overrides the old data(which was there in the first Api call) and replaces it with the result of the subsequent api calls.

I want to keep the old the in the state and render it UI and also render the new Data below it(which was emitted from the same state).

Here is my Specialitybloc

  SpecialityBloc() : super(InitialState()){
    on<GetSpeciality>((event, emit) async {
      emit(WaitingSpeciality());
      try{
        final data = await FirebaseRepo.getDoctorsBySpeciality(event.speciality);
        data.fold((l){
          emit(GetSpecialitySuccess(doctors:l));
        }, (r){
          
        });
      }catch(e){
        print(e);
      }
    });
  }
  
}

abstract class SpecialityState extends Equatable {

}

abstract class SpecialityEvent {

}

class InitialState extends SpecialityState {
@override
  List<Object> get props => [];
}

class WaitingSpeciality extends SpecialityState {
  @override
  List<Object> get props => [];

}

class GetSpecialitySuccess extends SpecialityState {
final List<DoctorModel> doctors;
GetSpecialitySuccess({required this.doctors});
@override
  List<Object> get props => [doctors];
}

class GetSpeciality extends SpecialityEvent {

  final String speciality;
  GetSpeciality(this.speciality);

}```

This is the UI part

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:patient_app/ui/screens/home/home_bloc/popular_bloc.dart';
import 'package:patient_app/ui/screens/home/home_bloc/speciality_bloc.dart';
import 'package:patient_app/ui/widgets/gridViewLoading.dart';
import 'package:shimmer/shimmer.dart';
import 'package:patient_app/ui/screens/home/home_bloc/home_bloc.dart';
import 'package:patient_app/ui/widgets/custom_carousel.dart';
import 'package:patient_app/ui/widgets/search_bar.dart';
import 'package:patient_app/ui/widgets/square.dart';
import 'package:patient_app/ui/widgets/username.dart';

class Home extends StatefulWidget {
  const Home({ Key? key }) : super(key: key);

  @override
  State<Home> createState() => _HomeState();
}

class _HomeState extends State<Home> {

  @override
  void initState() {
    super.initState();

    context.read<HomeBloc>().add(GetUserInfo());
    context.read<PopularBloc>().add(GetPopularDoctors());
    context.read<SpecialityBloc>().add(GetSpeciality('paediatrics'));
    context.read<SpecialityBloc>().add(GetSpeciality('gynaecologist'));
  }

  @override
  Widget build(BuildContext context) {
    return   SingleChildScrollView(
          child: Padding(
            padding: const EdgeInsets.only(left:20.0,right: 20,),
            child: Column(

              children: [
                const SizedBox(height: 35,),
                BlocBuilder<HomeBloc,HomeState>(
                  
                  builder: (ctx,state){
                    if(state is Waiting){
                      return Align(
                        alignment: Alignment.centerLeft,
                        child: Shimmer.fromColors(
                          baseColor: Colors.amber,
                          highlightColor: Colors.grey[300]!,
                          child: Container(
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(10),
                              color: Colors.amber,
                            ),
                            height: 20,width: 150,),
                        ));
                    }
                    if(state is Success){
                      return UserName(name: state.data.name!);
                    }
                    else{
                      return Container();
                    }
                    
                  },
                ),
                CustomCarousel(slides: [
                  SizedBox(
                    width: double.infinity,
                    child: Image.network("https://cdn.pixabay.com/photo/2020/09/13/20/24/doctor-5569298_960_720.png",fit: BoxFit.cover,),
                  ),
                  SizedBox(
                    width: double.infinity,
                    child: Image.network("https://cdn.pixabay.com/photo/2021/11/20/03/16/doctor-6810750_960_720.png",fit: BoxFit.cover,),
                  ),
                ]),
                const SearchBar(),
                
                BlocBuilder<PopularBloc,PopularState>(builder: (ctx,state){
                  if(state is WaitingPopular){
                    return const GridViewLoading();
                  }
                  if(state is PopularDoctorsSuccess){
                   
                    return Square(doctors: state.doctors,title: "Popular Doctors",);
                  }
                  return Container();
                }),
               
                
                BlocBuilder<SpecialityBloc,SpecialityState>(builder: (ctx,state){

                  if(state is WaitingSpeciality){
                    return const GridViewLoading();
                  }
                  if(state is GetSpecialitySuccess){
                    return Square(doctors: state.doctors,title: " Paediatrics",);
                  }
                  return Container();

                }),

                BlocBuilder<SpecialityBloc,SpecialityState>(builder: (ctx,state){

                  if(state is WaitingSpeciality){
                    return const GridViewLoading();
                  }
                  if(state is GetSpecialitySuccess){
                    return Square(doctors: state.doctors,title: "Gynaecologist",);
                  }
                  return Container();

                })
                
              ],
            ),
          ),
        );
  }
}

**Comment by felangel** [comment]
Closing for now but feel free to comment with any follow-up questions and I'm happy to continue the conversation 👍
