### ISSUE TITLE
fix:  _state = widget.selector(_bloc.state());

### ISSUE THREAD

**Issue by ANGADJIT** [felangel/bloc#3317]
**Description**
Error: 'state' isn't a function or method and can't be invoked

**Steps To Reproduce**
change _bloc.state(); to _bloc.state;
in builder,listener ,selector file

**Comment by felangel** [comment]
Hi @ANGADJIT 👋 
Thanks for opening an issue!

Can you please provide more context and a minimal reproduction sample? I'm afraid there isn't enough information to help at the moment. Thanks!

**Comment by ANGADJIT** [comment]
Thanks sir for responding

Last night i started a project with bloc
While building the project i got an error 
state = widget.select or _bloc.state()

Then i checked that in following files
- **bloc_selector**
- **bloc_listener**
- **bloc_builder**

_bloc.state() is invoking as function

I changed _bloc.state() to _bloc.state
And it worked

So that's why I raised this issue

Thanks
