### ISSUE TITLE
docs(hydrated_bloc): unclear how to mock out the hydrated storage for testing

### ISSUE THREAD

**Issue by alexlomm-dormzi** [felangel/bloc#3318]
**Description**

It is unclear how exactly to mock out the hydrated bloc. I'm trying to follow this example:

https://github.com/felangel/bloc/blob/4b8e2f43be77f76684fb5b93c8581b5db1f08d6f/examples/flutter_weather/test/weather/view/weather_page_test.dart#L32-L37

But it doesn't seem to be working in my case, I'm still getting an error:

<img width="567" alt="Screen Shot 2022-04-07 at 9 41 36 PM" src="https://user-images.githubusercontent.com/91471110/162346446-56455b29-2de1-4766-a49e-af57d40ff6bd.png">

My code looks like this:

```dart
// mockHydratedStorage implementation
class MockStorage extends Mock implements Storage {}

FutureOr<T> mockHydratedStorage<T>(
  T Function() body, {
  Storage? storage,
}) {
  return HydratedBlocOverrides.runZoned<T>(
    body,
    storage: storage ?? _buildMockStorage(),
  );
}

Storage _buildMockStorage() {
  TestWidgetsFlutterBinding.ensureInitialized();
  final storage = MockStorage();
  when(() => storage.write(any(), any<dynamic>())).thenAnswer((_) async {});
  return storage;
}
```

```dart
// test fragment
await mockHydratedStorage(() async {
  await tester.pumpWidget(
    MultiBlocProvider(
      providers: [
        BlocProvider<AuthBloc>(create: (_) => authBloc),
        BlocProvider<ThemeCubit>(create: (_) => themeCubit),
      ],
      child: MaterialApp.router(
        routeInformationParser: BeamerParser(),
        routerDelegate: routerDelegate,
      ),
    ),
  );
});
```

What am I doing wrong?

**Comment by felangel** [comment]
Hi @alexlomm-dormzi 👋
Thanks for opening an issue!

I believe you just need to remove the TestWidgetsFlutterBinding.ensureInitialized(); from _buildMockStorage. If you’re still having trouble it would be awesome if you could create a minimal reproduction sample and I’ll take a closer look 👍

**Comment by alexlomm-dormzi** [comment]
Strangely enough, everything worked when I did a minimal reproduction 🤔 Must be something else going on in the codebase.
