### ISSUE TITLE
docs: zone overrides documentation could mention how to deal with nested `runZoned`

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#3319]
In the migration guide (https://bloclibrary.dev/#/migration?id=packagehydrated_bloc) and in the README (https://github.com/felangel/bloc/tree/master/packages/hydrated_bloc#setup-hydratedstorage) it is shown how to use `runZoned` to set storage etc. It has a very basic example but for example I now have (due to Crashlytics):
```dart
Future<void> main() async {
  await runZonedGuarded<Future<void>>(
    () async {
      // ...

      HydratedBlocOverrides.runZoned(
        () => runApp(...),
        storage: storage,
      );
    },
    (error, stack) => FirebaseCrashlytics.instance.recordError(error, stack),
  );
}
```
i.e. nested `runZoned` calls. The documentation could mention how to correctly structure the code (which one should be the outer call, if relevant, etc.) and reassure clueless end users like myself that all is going to be good (I don't really know if my code is correct). What do you think?

**Comment by felangel** [comment]
Hi @wujek-srujek 👋 
Thanks for opening an issue!

Yes, the snippet you have is correct (you can nest zones). There are still open discussions regarding whether zones a good fit for this use case so I'll keep this open until those discussions are resolved and we will either document this better or adjust the API.

**Comment by felangel** [comment]
The `BlocOverrides` API has been deprecated in bloc v8.1.0.
