### ISSUE TITLE
Dispach payload

### ISSUE THREAD

**Issue by JojoSalustiano** [felangel/bloc#332]
Sometimes it is useful to pass some kind of data to the Dispatch.
For example: in a case where we have different increment buttons (+10, +5, +2)
Instead of creating an event for each, a single "Increment" event is possible and passes the increment value. Something like 'dispatch (CounterEvent.increment, {' increment ': 10})'
[I come from the world of vue, and this is how it is done with vuex]

So we would pass the payloader to the mapEventToState and each subroutine handles it as desired

**Comment by felangel** [comment]
Hi @JojoSalustiano 👋 
Thanks for opening an issue!

Regarding your question, I would recommend using a class to represent your event.

```dart
abstract class CounterEvent {}

class Increment extends CounterEvent {
  final int by;

  Increment({this.by});
}
```

Then you can dispatch like so:

```dart
counterBloc.dispatch(Increment(by: 10))
```

You can handle the payload in your `mapEventToState` like so:

```dart
mapEventToState(CounterEvent event) async* {
  if (event is Increment) {
    yield currentState + event.by;
  }
  // handle other events
}
```

Enums are great for super simple cases but when you need to start passing data, I would recommend using classes. Hope that helps 👍

**Comment by JojoSalustiano** [comment]
Is it possible to make this more explicit in the documentation?

**Comment by felangel** [comment]
@JojoSalustiano sure I'll update the Core Concepts section to include this.
If you take a look at any of the tutorials, you'll see that most of them use classes for events and state.
