### ISSUE TITLE
Best Practices

### ISSUE THREAD

**Issue by PauloRutkoski** [felangel/bloc#3328]
I have a question about the best practices when creating an edit screen. 
If I need to create a CRUD of a Person entity, that would have a document, name, last name, .... And I'm using cubit as state management.
Should I have each attribute replicated in the state of the Cubit? Or there is another way to do that without replicate everything?

**Comment by Add00w** [comment]
> I have a question about the best practices when creating an edit screen. If I need to create a CRUD of a Person entity, that would have a document, name, last name, .... And I'm using cubit as state management. Should I have each attribute replicated in the state of the Cubit? Or there is another way to do that without replicate everything?

If I understand your question well you need to have the Person object in the state, not the fields.

**Comment by PauloRutkoski** [comment]
But then, everytime I want to change some attribute value, like the name, Would I have to do like this?

`context.read<Cubit>().changePerson(state.person.copyWith(name: name));`
`changePerson(Person person) => emit(state.copyWith(person: person));`

**Comment by Add00w** [comment]
> But then, everytime I want to change some attribute value, like the name, Would I have to do like this?
> 
> `context.read<Cubit>().changePerson(state.person.copyWith(name: name));` `changePerson(Person person) => emit(state.copyWith(person: person));`

You can do so.
