### ISSUE TITLE
feat: instant messagning with bloc arch

### ISSUE THREAD

**Issue by uemirhanselim** [felangel/bloc#3339]
**Description**

A messaging app or content with bloc arch.

**Desired Solution**

**Alternatives Considered**

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by marcossevilla** [comment]
hi @uemirhanselim 👋 you can find a good chat example on VGV's [chat_location](https://github.com/VGVentures/chat_location) repo, with location-sharing functionality included 👍 

let me know if that helps!

**Comment by uemirhanselim** [comment]
I will look and let you know

**Comment by marcossevilla** [comment]
@uemirhanselim will close this issue but feel free to continue the conversation and I'm happy to help!
