### ISSUE TITLE
fix: Event emission is always async

### ISSUE THREAD

**Issue by passsy** [felangel/bloc#3340]
### Description

The following test fails. That's surprising because everything is sync.

```dart
import 'package:bloc/bloc.dart';
import 'package:test/test.dart';

void main() {
  test('Execute synchronous events synchronously', () async {
    final bloc = MyBloc();
    int value = 0;
    bloc.stream.listen((event) {
      value = event;
    });
    bloc.add(Object());

    // waiting fixes the test
    // await pumpEventQueue();

    expect(value, 1);
    // Test failed 
    // Expected: <1>
    // Actual: <0>
  });
}

class MyBloc extends Bloc<Object, int> {
  MyBloc() : super(0) {
    on<Object>((event, emit) => emit(state + 1));
  }
}
```

I know the internals and know that all events are processed asynchronously. But, looking at the public API it is surprising that a pure **synchronous** bloc operates **asynchronously**. Because that's not documented.

### Expected Behavior
A sync event handler should be called sync, and emit the event sync. 

### Real-world usecases

Blocs often have initial "loading" events that are triggered right after creating the instance.

```dart
return MyBloc()..add(LoadData());
``` 

Adding the event transforms the state from "not loading" to "loading". Because of the current async nature, this causes a 1 frame flicker in the UI. The output `stream` first emits "not loading" followed by "loading", but it should only emit "loading" from the very beginning.

--- 

Haven't tinkered with the implementation yet, but it should be doable by using `SynchronousStreamController`.
But it might also break the contract of `Stream`.
But it could reduce flickering.
But it could be a breaking change, breaking real apps.
But it could make stacktraces easier to read.

There are many pros and cons. Just wanted to start a discussion 👋

**Comment by felangel** [comment]
Hey @passsy 👋 
Thanks for opening an issue!

> Blocs often have initial "loading" events that are triggered right after creating the instance.

> ```dart
> return MyBloc()..add(LoadData());
> ```
> Adding the event transforms the state from "not loading" to "loading". Because of the current async nature, this causes > a 1 frame flicker in the UI. The output stream first emits "not loading" followed by "loading", but it should only emit > "loading" from the very beginning.

If you want a bloc's state to be "loading" from the beginning, why not just set the initial state to loading?

```dart
class MyBloc extends Bloc<MyEvent, MyState> {
  MyBloc() : super(MyLoadingState()) {...}
}
```

**Comment by felangel** [comment]
Closing for now since there doesn't appear to be any actionable next steps. Let me know if you have follow-up comments/questions and I'm happy to continue the discussion 👍
