### ISSUE TITLE
fix: Failure to handle unexpected exceptions in Bloc event handlers #flutter_bloc

### ISSUE THREAD

**Issue by KCL-TelferAA** [felangel/bloc#3343]
**Description**
Bloc silently fails when an unhandled exceptions is thrown in Bloc::on handlers.

I noticed that sometimes events would not get registered with the bloc and could not understand why. I realized that the flutter_bloc plugin was silently failing without handling errors that were generated in the event handlers. In my case a null-pointer exception occurred.

**Steps To Reproduce**

1. Generate a Bloc
2. In the `on` event handler for the generated bloc add `throw Error();`
3. In a widget, print the state of the bloc somehow
4. In a widget, add a button and make the onPress action call `Bloc::add` to add an event to the bloc
5. Observe that no change has occurred in the bloc state and observe that no error is output to the console

**Expected Behavior**
The error and stack trace should be printed somewhere or flutter_bloc should inform the developer an error occurred in an event handler.

**Screenshots**

**Additional Context**

**Comment by felangel** [comment]
Hi @KCL-TelferAA 👋 
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? Thanks! 🙏
