### ISSUE TITLE
BLoC closes itself when I push new page, unable to add new events

### ISSUE THREAD

**Issue by onatcipli** [felangel/bloc#3346]
**Description**
Hi guys, I have a `MvpQuizBloc` that manages the MVP quizzes basically but the problem is **when I try to navigate to a different page it automatically closes itself**, I found it via debugging since its close I'm not able to add new events but I'm able to get the latest state 

**Steps To Reproduce**
on the UI I'm reaching out to the BLoC instance with the following code;

`    final MvpQuizBloc mvpQuizBloc = BlocProvider.of<MvpQuizBloc>(context);`

and pushing the new page with following BLoC event

`         mvpQuizBloc.add(
                              PushQuizPage(context),
                            );
`

```dart
 Stream<MvpQuizState> mapEventToState(
    MvpQuizEvent event,
  ) async* {
  //....
  if (event is PushQuizPage) {
      Navigator.push(
        event.context,
        createBottomTransitionRoute(
          page: BlocProvider<MvpQuizBloc>.value(
            value: this,
            child: FixtureQuizPage(),
          ),
        ),
      );
    }
  //....
  }

  Route createBottomTransitionRoute({
    required Widget page,
  }) {
    return PageRouteBuilder(
      transitionsBuilder: (
        BuildContext _,
        Animation first,
        Animation second,
        Widget child,
      ) {
        const begin = Offset(0.0, 1.0);
        const end = Offset.zero;
        final tween = Tween(begin: begin, end: end);
        final curve = Curves.easeInCubic;
        final curveTween = CurveTween(curve: curve);
        final slideTransition = tween.chain(curveTween);
        return SlideTransition(
          position: first.drive(slideTransition),
          child: child,
        );
      },
      pageBuilder: (
        BuildContext _,
        Animation<double> animation,
        Animation<double> secondaryAnimation,
      ) {
        return page;
      },
    );
  }
```

**Expected Behavior**
It should call the close method of BLoC, and be able to retrieve new events 

**Screenshots**
The close method of BLoC called after `FixtureQuizPage` draws its first frame  

![Screen Shot 2022-05-03 at 10 42 34](https://user-images.githubusercontent.com/26159899/166419187-cf3477aa-fab5-4f28-af1e-356302b6800c.png)

**Additional Context**
on `FixtureQuizPage` I'm able to reach out to the latest state with BlocBuilder like the following;

```dart
  @override
  Widget build(BuildContext context) {
    final mvpQuizBloc = BlocProvider.of<MvpQuizBloc>(context);
    return BlocBuilder<MvpQuizBloc, MvpQuizState>(
      builder: (_, state) {
        return Scaffold(
          backgroundColor: MainTheme.coloursDarkMode7,
          appBar: AppBar(
...
...
```

but not able to add any new events

**What did I so far?**
I thought I'm using the wrong context but in that case, I think I should be able to get the latest state too? correct me if I'm wrong 
so that I ensure that I'm giving the correct context while providing BLoC 

Versions: 

  bloc: ^7.2.1
  flutter_bloc: ^7.3.0

**Comment by felangel** [comment]
Hi @onatcipli 👋 
Thanks for opening an issue!

Are you able to provide a link to a minimal reproduction sample? My guess is you're providing the bloc via BlocProvider too low in the widget tree and when the BlocProvider is unmounted, it automatically closes the bloc instance prematurely.
