### ISSUE TITLE
[QUESTION] bloc_test: How to step into bloc when debugging

### ISSUE THREAD

**Issue by mbabuglia** [felangel/bloc#3348]
**Description**
In a unit test using the blocTest<FooBloc, FooBlocState> test case, my breakpoints inside the bloc are not hit.
I can put a breakpoint inside _act_, but there I only perform an _add_ on my bloc.
What I need is to debug the actual event handler defined for that event.

**Expected Behavior**
I can debug code inside my Bloc.

**Comment by felangel** [comment]
Hi @mbabuglia 👋 
Thanks for opening an issue!

You should be able to set breakpoints inside your bloc and debug the blocTest normally. Are you able to share a link to a minimal reproduction sample with a screen recording to illustrate the issue? Thanks!

**Comment by mbabuglia** [comment]
Hi Felix, thank you for your extremely quick response.

I tried to build a minimal sample and everything worked fine, I couldn't reproduce the issue.  

I will add mocktail and/or freezed to see if I can reproduce and let you know.

**Comment by felangel** [comment]
> Hi Felix, thank you for your extremely quick response.
> 
> I tried to build a minimal sample and everything worked fine, I couldn't reproduce the issue.
> 
> I will add mocktail and/or freezed to see if I can reproduce and let you know.

No problem, thanks!

**Comment by mbabuglia** [comment]
I discovered something very strange: a breakpoint in the middle of a method is not hit, but a breakpoint on the method signature is.

Besides that, I was [debugging with "All exceptions"](https://github.com/felangel/mocktail/issues/88) with mocktail, which sent me down the incorrect rabbit hole. 

So this has nothing to do with bloc_tests. Thank you for your time!
