### ISSUE TITLE
fix: problem with navigation using BlocListener

### ISSUE THREAD

**Issue by H0SSaM7** [felangel/bloc#3355]
With flutter new update 3.0.0 there is a problem with navigation using BlocListener when I navigate to the next screen it navigates and when I go back I need two clicks to pop the screen when navigating with anything else it works and I pop the screen with one click, this happen with flutter update, it was working before

=== code === 
`BlocListener<ReportsBloc, ReportsState>(
                    listener: (context, state) {
                      if (state is GetReportedAdScucess) {
                        if (report.adCollection ==
                            AppConstants.cityMarketCollection) {
                          navigateTo(
                              context,
                              ProductDetailsScreen(
                                item: state.item,
                              ));
                        } else {
                          navigateTo(
                              context,
                              JobDetailsScreen(
                                job: state.item,
                              ));
                        }
                      }
                    },
                    child: TextButton(
                      onPressed: () {
                        context.read<ReportsBloc>().add(
                              GetReportedAd(report.adId, report.city,
                                  report.adCollection),
                            );
                      },
                      child: Text(
                        'Watch Ad',
                        style: Theme.of(context).textTheme.bodyLarge!.copyWith(
                              color: Colors.green,
                            ),
                      ),
                    ),
                  ),`

**Comment by felangel** [comment]
Hi @H0SSaM7 👋
Thanks for opening an issue!

Can you please provide a link to a minimal reproduction sample? Thanks!

**Comment by H0SSaM7** [comment]
https://user-images.githubusercontent.com/74508773/168597659-14c09c00-0644-426f-975d-f0180dde4572.mp4

**Comment by H0SSaM7** [comment]
@felangel

**Comment by felangel** [comment]
@H0SSaM7 can you provide a link to a repository that we can run/debug locally to reproduce the issue?
