### ISSUE TITLE
docs: weather app tutorial

### ISSUE THREAD

**Issue by AbdulbasitSaid** [felangel/bloc#3369]
The weather app tutorial has an issue with the API link used in the example. It gives a 404 page not found error [metaweather. com](https://www.metaweather.com/). Please help update the tutorial.

**Comment by Tokenyet** [comment]
Few days ago, I found the api we used in this tutorial is missing, so I make one roughly with another free api (open-meteo). You might wanna take a look at It 😊

https://github.com/Tokenyet/flutter_weather_clean_architecture/blob/main/lib/features/weather/data/datasources/weather_remote_data_source.dart

Hope It help somehow!

**Comment by vogdb** [comment]
@felangel Hi! I plan to implement this tutorial with the new Weather API and make a PR after that. Please let me know what weather API works better for you. I don't see the analog of location search in the suggested [open-meteo](https://open-meteo.com), at least in its [API](https://open-meteo.com/en/docs#api_form). However it does not require an API key for usage. The free weather APIs, I could find, still require registration and API keys. May be it makes sense to use a weather API with an API key? What do you think?
