### ISSUE TITLE
question:  Difference between Bloc's default EventTransform and `concurrent<Event>()` in bloc_concurrency?

### ISSUE THREAD

**Issue by albuscrow** [felangel/bloc#3376]
When should I use `concurrent<Event>()` in bloc_concurrency?

`on<Event>(xxx)` in `Bloc` has default EventTransform which will process event concurrently. What's difference between Bloc's default EventTransform and `concurrent<Event>()` in bloc_concurrency?

**Comment by felangel** [comment]
Hi @albuscrow 👋 
Thanks for opening an issue!

`concurrent` is the default transformer so you likely won't need to use it unless you're chaining transformers. Hope that helps 👍
