### ISSUE TITLE
Bloc to Bloc Communication Suggestion

### ISSUE THREAD

**Issue by Habib23me** [felangel/bloc#338]
Hey, I would like to thank you for this awesome library am doing my second flutter project with it which is kind of  ecommerce app.

So I have to blocs WishListBloc and CartBloc that needs to communicate the scenario arrises when items are moved from the wishListBloc to the cartBloc. What I wanted to do is when wishListBloc is requested to move Items to the cartBloc it first dispatches an (AddToCart) event and then listen if that was successful and then delete it from the wishList items;

This is my wishListBloc

[WishListBloc](https://github.com/iBrave-dev/codecs-client-app/blob/32859dd934b086709d95932c65acdadf45ae81cd/lib/src/bloc/wish_list/wish_list_bloc.dart#L1-L47)
It uses a singleton pattern and uses a mixin to handle accessing list(adding, removing ...)

and this is CartBloc
[CartBloc](https://github.com/iBrave-dev/codecs-client-app/blob/32859dd934b086709d95932c65acdadf45ae81cd/lib/src/bloc/cart/cart_bloc.dart#L1-L46)
Thanks in advance!

**Comment by felangel** [comment]
Hi @Habib23me 👋 
Thanks for the feedback! We are currently working through several approaches to help with Bloc to Bloc Communication and we are taking `mixins` into consideration!

Your input is much appreciated! Thanks so much for sharing and you can expect this to be included in v0.15.0 of bloc 👍
