### ISSUE TITLE
feat: Performance Monitoring in bloc transition

### ISSUE THREAD

**Issue by ariefwijaya** [felangel/bloc#3381]
**Description**
When having complex applications, sometimes we experience performance degradation, especially execution time in BLOC. Therefore we need to monitor and analyze how long the BLOC transition time is. For example, how long does it take from "Loading" state to "Success" or Failed", and so on. 

**Desired Solution**
We need to know the execution time of each BLOC transition. How we know it? Can we get it from Bloc Observer?

**Alternatives Considered**
if the desired solution is not possible, how we inspect the bloc performance. 

**Additional Context**
-

**Comment by aaassseee** [comment]
@ariefwijaya  you can log any bloc activity by using the [bloc observer](https://pub.dev/documentation/bloc/latest/bloc/BlocObserver-class.html). With bloc observer you can use [onTransition](https://pub.dev/documentation/bloc/latest/bloc/BlocObserver/onTransition.html) to keep track on the time that process with event.

**Comment by ariefwijaya** [comment]
any example to do it?

**Comment by aaassseee** [comment]
@ariefwijaya Due to zero information, I can only modify an example which is provided by bloc. You can replace the [app_bloc_observer](https://github.com/felangel/bloc/blob/master/examples/flutter_todos/lib/app/app_bloc_observer.dart) file in [flutter_todos](https://github.com/felangel/bloc/tree/master/examples/flutter_todos) with these lines below and test it out
``` dart
import 'dart:developer';

import 'package:bloc/bloc.dart';
import 'package:flutter_todos/edit_todo/edit_todo.dart';

class AppBlocObserver extends BlocObserver {
  Map<int, int> eventHashTimeMap = {};

  @override
  void onChange(BlocBase bloc, Change change) {
    super.onChange(bloc, change);
    log('onChange(${bloc.runtimeType}, $change)');
  }

  @override
  void onError(BlocBase bloc, Object error, StackTrace stackTrace) {
    log('onError(${bloc.runtimeType}, $error, $stackTrace)');
    super.onError(bloc, error, stackTrace);
  }

  @override
  void onEvent(Bloc bloc, Object? event) {
    super.onEvent(bloc, event);

    if (bloc is EditTodoBloc) {
      final editTodoEvent = event as EditTodoEvent?;
      if (editTodoEvent == null) return;
      final key = editTodoEvent.hashCode;
      eventHashTimeMap[key] = DateTime.now().microsecond;
    }
  }

  @override
  void onTransition(Bloc bloc, Transition transition) {
    super.onTransition(bloc, transition);
    if (bloc is EditTodoBloc) {
      final editTodoEvent = transition.event as EditTodoEvent?;
      if (editTodoEvent == null) return;
      final key = editTodoEvent.hashCode;
      final eventStartTime = eventHashTimeMap[key];
      eventHashTimeMap.remove(key);
      if (eventStartTime == null) return;
      final processTime =
          Duration(milliseconds: DateTime.now().microsecond - eventStartTime);
      log('EditTodoBloc state change from ${transition.currentState} to ${transition.nextState} by ${transition.event} used $processTime');
    }
  }
}

```
