### ISSUE TITLE
docs: Example of list items with state

### ISSUE THREAD

**Issue by IlyaMax** [felangel/bloc#3386]
I'd like to have an example of how to handle list of items, when each of them can process events in parallel, because there are two ways to achieve that. 1. to provide bloc with blocprovider for each item of list which leads to impossible mocking when testing. 2. to make list of blocs inside bloc for screen with list which I used in my example and I think it should be recommended one and mentioned in docs. To understand better please see my [pr](https://github.com/felangel/bloc/pull/3385). If this approach(generally speaking put blocs in other blocs and access them via state) has any drawbacks please let me know, thanks

**Comment by felangel** [comment]
Hi @IlyaMax 👋 
Thanks for opening an issue!

I generally don't recommend including blocs as part of the state of other blocs because it tightly couples the blocs and also goes against the idea of a state as a model (since it now contains logic).

In option 1. you can still mock the blocs you just need to widget test the individual components and provide a mock bloc rather than the entire system. Hope that helps 👍

**Comment by IlyaMax** [comment]
@felangel yes, I know that I can test individual components in option 1, I mean, I can't test other part of screen in that case and that's a problem. Regarding tightly coupling I agree, I think it's better to avoid it as much as it possible, but in case if you have more than one blocs to provide to your screen like in my case it's pretty hard to choose something better between losing possibility to test entire screen and tightly coupled blocs. I'd pick the second option. I felt that something wrong can be with what you said  "idea of a state as a model". Can you explain what exactly is wrong with this idea?

**Comment by IlyaMax** [comment]
I'll give you a couple of examples. Simple screen which consists of button and listview with dependency on blocA(I need to test that when I tap a button event is added), and listview, each item of which depends on blocB. I can't mock blocB here, maybe I could resolve it by creating separate widget with that button and test it separately, but it seems more logical for me if I could not to overcomplicate my code by that. Second example is creating golden test for entire widget. It could be useful sometimes as well and if I don't mock all the deps of screen I can't do that.

**Comment by felangel** [comment]
Closing for now but feel free to comment with any additional thoughts and I'm happy to continue the conversation 👍

**Comment by IlyaMax** [comment]
I mended the first version of example and the final is here https://github.com/IlyaMax/flutter_bloc_example. For now it has only problem with tightly coupled blocs but allows to reuse bloc, events and states of `RandomIntLoader` feature + allows to test buttons just by `MyScreen` widget pumping, which would've been impossible if I'd used `BlocProvider` just inside `MyScreen`.
