### ISSUE TITLE
fix: Event with list of items fired multiple times

### ISSUE THREAD

**Issue by MoeHamdan** [felangel/bloc#3398]
**Description**
I have an event, that has a list of items as property as below.

**Steps To Reproduce**

`class PushSessionDataEvent extends PushSignalRDataEvent {
  final List<SessionEventSigned> events;
  PushSessionDataEvent(this.events);
}`
When I fire this event using the below:
`add(PushSessionDataEvent(events))`

The event will fire multiple times based on the count of the list with each time having only 1 objects in the "events" property.

**Expected Behavior**
The event should fire only once and pass the complete list.

**Screenshots**
Firing the event with a list of multiple values.
![image](https://user-images.githubusercontent.com/12870330/174243994-73f0e963-5743-4dde-9994-40167fdd8d0e.png)

All I get is a single item in the events list.
![image](https://user-images.githubusercontent.com/12870330/174244173-af72b9fe-46f6-48e9-b95b-bdb217cea93f.png)

Kindly Advise.

**Comment by narcodico** [comment]
Hi @MoeHamdan 👋

This is insufficient information for us to be able to help. I'm assuming your data source sends one event at a time, but if that's not the case then feel free to provide a reproduction sample and you'll get further help.
