### ISSUE TITLE
docs: migrate all examples to Dart 2.17 and Flutter 3.0

### ISSUE THREAD

**Issue by felangel** [felangel/bloc#3406]
**Description**

As a developer, I want to have all the bloc examples be running on the latest stable version of Flutter/Dart.

- [X] angular_counter
- [X] flutter_bloc_with_stream
- [X] flutter_complex_list
- [x] flutter_counter
- [x] flutter_dynamic_form
- [x] flutter_firebase_login
- [x] flutter_form_validation
- [x] flutter_graphql_jobs
- [x] flutter_infinite_list
- [x] flutter_login
- [x] flutter_shopping_cart
- [x] flutter_timer
- [x] flutter_todos
- [x] flutter_weather
- [x] flutter_wizard
- [x] github_search

**Comment by BeatriceMitchell** [comment]
Preferably, there will be one PR per item on the list.
