### ISSUE TITLE
feat: Add child param on BlocConsumer

### ISSUE THREAD

**Issue by jasontcs** [felangel/bloc#3411]
**Description**

Currently, BlocConsumer/ BlocBuilder/ BlocSelector rebuild the whole subtree
```dart
BlocConsumer<BlocA, BlocAState>(
  listener: (context, state) {
    //
  },
  builder: (context, state) {
    // rebuild the whole subtree
  }
)
```

**Desired Solution**

Should we add a child param to reduce the unnecessary rebuild?
```dart
BlocConsumer<BlocA, BlocAState>(
  listener: (context, state) {
    //
  },
  builder: (context, state, child) {
    // rebuild only the depended widget
    ...child
  },
  child: WidgetShouldNotRebuild(),
)
```

**Comment by felangel** [comment]
Hi @jasontcs 👋 
Thanks for opening an issue!

I believe this is a duplicate of #1596. See https://github.com/felangel/bloc/issues/1596#issuecomment-671595704 for my thoughts and feel free to provide additional context if you feel strongly about introducing this change, thanks!

**Comment by jasontcs** [comment]
@felangel Thank you so much. I am going to close this.
