### ISSUE TITLE
feat: BlocListener + BlocSelector

### ISSUE THREAD

**Issue by dedonnodev** [felangel/bloc#3417]
**Description**

If you want Listen event of a bloc, and select the event, you have to wrap a BlocSelector with a BlocListener

**Desired Solution**

A join between BlocSelector and BlocListener, so a BlocConsumer with a selector

**Comment by felangel** [comment]
Hi @dedonnodev 👋
Thanks for opening an issue!

If you want to avoid nesting you can use a BlocListener with context.select:

```dart
final state = context.select(…);
BlocListener<MyBloc, MyState>(
  listener: (context, state) {…},
  child: …
):
```

Hope that helps 👍

**Comment by dedonnodev** [comment]
Oh, cool!
I didn't know about context.select
really thank you.

**Comment by erlangparasu** [comment]
@felangel how to `BlocListener` but want to check state first like selector. If the selected properties changes, then run the `listener:` 
?

**Comment by erlangparasu** [comment]
@felangel I means `BlocListener` that internally check changes for the selected state. Without manually check prevState & currentState. Something like `selector:` but without `listenWhen`.
