### ISSUE TITLE
Top Level Error Hanling

### ISSUE THREAD

**Issue by iBrave-dev** [felangel/bloc#342]
I love using this package and I was wondering what the right way of hanling Top level errors for my mapEventToState callback would be. The following snippet although doesn't work tries to explain what I want to do

`
```
@override
  Stream<ProductState> mapEventToState(
    ProductEvent event,
  ) async* {
  try{
      if(event is AddProductToWishList)
        yield* _addProductToWishListMTS();
      else if(event is AddProductToCart)
        yield* _addProductToCartMTS(event.cartItem);
      else if(event is ChangeProductState)
        yield* _changeProductStateMTS();
 }catch(e){
     yield ErrorState():
} }
Stream _addProductToWishListMTS()async*{
    //does something that may throw an error
}
```
`

**Comment by felangel** [comment]
Hi @iBrave-dev 👋 
Thanks so much for the positive feedback and for opening an issue!

Regarding your question, you can handle errors at the bloc level by overriding `onError` like:

```dart
@override
void onError(Object error, StackTrace stacktrace) {    
  super.onError(error, stacktrace);
  // handle bloc-specific errors here
}
```

Alternatively, if you want global error handling for all blocs you can override `onError` in your own `BlocDelegate` like so:

```dart
@override
void onError(Bloc bloc, Object error, StackTrace stacktrace) {
  super.onError(bloc, error, stacktrace);
  // handle global bloc errors here
}
```

Hope that helps! Let me know if you have any additional questions 👍

**Comment by iBrave-dev** [comment]
Thank u so much for your fast reply.I dispatched a new event inside the onError which will be mapped to an ErrorState. Keep going with this very predictable and awesome library!!

**Comment by felangel** [comment]
No problem! I think I might've misunderstood your question though. You should not need to dispatch another event in `onError` because you should be able to just yield the error state in your `catch` block. Can you please provide a link to some sample code which illustrates the problem you were having with your initial approach? Thanks!

**Comment by iBrave-dev** [comment]
Checkout this demo https://github.com/iBrave-dev/demo/blob/3dc8b81a11e15e4d9c0aa4c2e9e917cb689f64d7/demo.dart#L1-L33

All I one to do is handle all error of my map to state function (async* functions) from one place and yield an errorState to the UI so that it may display an error toast

**Comment by felangel** [comment]
I think that should work if you change line 20 to
```dart
yield await AiRepository().addToWishList(productModel);
```
