### ISSUE TITLE
Question | Recommended approach to share "UI state" between multiple blocs

### ISSUE THREAD

**Issue by logic-and-math** [felangel/bloc#3420]
First, I want to say thank you for the package, I'm thoroughly enjoying working with it!

I have two blocs.
Both of these blocs depend on a repository. So for the repository I created a streaming value so both blocs can react to the changes(in order to avoid dependencies between blocs). This works great in the case where my repository communicates to some data source(web, cache, ...).
Now I have that both blocs also depend on the scroll position of a ListView. I really prefer sharing common dependencies through repositories rather than through UI. But this really feels wrong to call a repository, especially since my data is coming from UI, not from some data source.
What would be the recommended approach to sharing the state from UI layer with multiple blocs?

Thank you a lot.

**Comment by tenhobi** [comment]
Hi @logic-and-math, could you please describe your needs more or could you create a minimal reproduction sample?

But from what you are describing it seems that you are mixing two separate needs -- fetching data and some scroll related states -- into a single bloc? Maybe rethinking the bloc structure would help?
