### ISSUE TITLE
question: listener does not catch the first state transition

### ISSUE THREAD

**Issue by joaofyz** [felangel/bloc#3432]
I'm using a Cubit in my app and I'm struggling to understand one behavior. 

I have a list of products and when I open the product detail screen I want to have a "blank" screen with a loading indicator until receiving the data to populate the layout, but the loading indicator is not being triggered in the listener.

I'm using a BlocConsumer and i'm making the request in the builder when catching the ApplicationInitialState (first state), in cubit I'm emitting the ApplicationLoadingState(), but this state transition is not being caught in the listener, only when the SuccessState is emitted the listener triggers and tries to remove the loader.

I know the listener does not catch the first State emitted but I was expecting it to catch the first state transition.

Thanks for your help in advance

UI
```
class ProductDetailUI extends StatefulWidget {
  final String productId;

  const ProductDetailUI({
    required this.productId,
    Key? key,
  }) : super(key: key);

@override
  State<ProductDetailUI> createState() =>
      _ProductDetailUIState();
}

class _ProductDetailUIState extends State<ProductDetailUI>
    with WidgetsBindingObserver {
  final _ProductCubit = CubitFactory.ProductCubit;
  final _loadingIndicator =LoadingDialog();
  AppLocalizations? _l10n;

@override
void initState() {
  super.initState();
  WidgetsBinding.instance.addObserver(this);
}

@override
Widget build(BuildContext context) {
  _l10n = AppLocalizations.of(context);
  return _buildConsumer();
}

_buildConsumer() {
  return BlocConsumer<ProductCubit, ApplicationState>(
    bloc: _productCubit,
    builder: (context, state) {
      if (state is ApplicationInitialState) {
        _getProductDetail();
      }
      return Scaffold(
        appBar: _buildAppbar(state),
        body: _buildBodyState(state),
      );
    },
    listener: (previous, current) async {
      if (current is ApplicationLoadingState) {
        _loadingIndicator.show(context);
      } else {
        _loadingIndicator.close(context);
      }
    },
  );
}
```

Cubit

```
class ProductCubit extends Cubit<ApplicationState> with ErrorHandler {
  final ProductUseCase _useCase;

  ProductCubit({
    required ProductUseCase useCase,
  })  : _useCase = useCase,
        super(const ApplicationInitialState());

  void getProductDetail(String id) async {
    try {
      emit(const ApplicationLoadingState());

      final Product = await _useCase.getProductDetail(id);

      emit(CSDetailSuccessState(
        detail: ProductDetailMapper.getDetail(Product),
      ));
    } catch (exception) {
      emit(getErrorState(exception));
    }
  }
}
```

Cubit Factory
````
class CubitFactory {
  ...
  static ProductCubit get ProductCubit =>
    ProductCubit(
      useCase: ProductUseCaseImpl(
        repository: ProductRepositoryImpl(
          httpClient: _httpClient,
        ),
      ),
    );
}
```

**Comment by Gene-Dana** [comment]
Hi there ! May you share with us the code where you provide the ProductCubit?

**Comment by joaofyz** [comment]
Hello @Gene-Dana . I have updated the example, we use a CubitFactory and we get if when creating the state. I hope this can help.

**Comment by joaofyz** [comment]
Unfortunately I'm not allowed to share the repo, but I will try to mount a demo repo to reproduce the same behavior and share it here.

**Comment by felangel** [comment]
Hi @joaofyz 👋 
Thanks for opening an issue!

This is working as expected -- BlocListener listens for state changes. If the BlocListener is mounted later, then it's likely that the BlocListener has missed the initial state change.

**Comment by joaofyz** [comment]
Thanks @felangel 

I was already expecting to not receive de ApplicationInitialState in the listener, but I thought that from that state on, it will catch all state changes.

When you say "If the BlocListener is mounted later...", there's any way of ensuring the listener is mounted before these state changes occurs?

**Comment by felangel** [comment]
> Thanks @felangel
> 
> I was already expecting to not receive de ApplicationInitialState in the listener, but I thought that from that state on, it will catch all state changes.
> 
> When you say "If the BlocListener is mounted later...", there's any way of ensuring the listener is mounted before these state changes occurs?

The only way to ensure the listener is mounted before the changes occur is to move the `BlocListener` right under the `BlocProvider`.

Hope that helps, closing for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍

**Comment by joaofyz** [comment]
Thanks @felangel for your help. 

We ended up making the request in the addPostFrameCallback method, and this way we solved the problem of the listener not handling the first state transition.
