### ISSUE TITLE
HydratedBloc not firing BlocConsumer listener at first

### ISSUE THREAD

**Issue by MHKalantarian** [felangel/bloc#3434]
I have a bloc for user that keeps state of user, I managed to save state of user for being loaded and works at first but when I open the app again, listener is not fired to reroute user to another screen but state in builder is correct. 

**I want a way to fire listener with UserLoggedIn state on hydratedbloc loading**

    return BlocConsumer<UserBloc, UserState>(
      listener: (context, state) {
        log('listener ${state.toString()}');
        if (state is UserLoggedIn) {
          Navigator.popAndPushNamed(context, EmailListScreen.routeName);
        }
      },
      buildWhen: (previous, current) {
        log('buildWhen ${current.toString()}');
        return current is! UserLoggedIn;
      },
      builder: (context, state) {
        log('builder ${state.toString()}');
      }

So the output is:

    [log] builder UserLoggedIn()

Meaning the listener and buildWhen didn't trigger

Here is my user bloc:

    class UserBloc extends HydratedBloc<UserEvent, UserState> {
      UserBloc({required this.userRepository}) : super(UserInitial()) {
        on<UserStartingOver>(_startingOver);
        on<UserLogin>(_loginUser);
        on<UserRegister>(_registerUser);
        on<UserResendOTP>(_resendOTP);
      }
    
      final UserRepository userRepository;
    
      void _startingOver(UserStartingOver event, Emitter<UserState> emit) {
        emit(UserInitial());
      }
    
      void _loginUser(UserLogin event, Emitter<UserState> emit) async {
        emit(UserLoginLoading());
        try {
          final item = await userRepository.loginUser(event.user);
    
          switch (item.status) {
            case ApiResponse.successStatus:
              emit(UserLoggedIn(item.data!));
              break;
            default:
              emit(UserLoginFailure(item.message));
              break;
          }
        } catch (e) {
          print(e);
          emit(UserLoginFailure(null));
        }
      }
    
      void _registerUser(UserRegister event, Emitter<UserState> emit) async {
        emit(UserRegisterLoading());
        try {
          final item = await userRepository.registerUser(event.user);
    
          switch (item.status) {
            case ApiResponse.successStatus:
              emit(UserOTPSent());
              emit(UserRegistered());
              break;
            case ApiResponse.invalidNameStatus:
              emit(UserOTPSent());
              emit(UserRegisteredWithoutName());
              emit(UserRegistered());
              break;
            default:
              emit(UserRegisterFailure(item.message));
              break;
          }
        } catch (e) {
          print(e);
          emit(UserRegisterFailure(null));
        }
      }
    
      void _resendOTP(UserResendOTP event, Emitter<UserState> emit) async {
        emit(UserRegisterLoading());
        try {
          final item = await userRepository.registerUser(event.user);
    
          switch (item.status) {
            case ApiResponse.successStatus:
              emit(UserOTPSent());
              emit(UserRegistered());
              break;
            case ApiResponse.invalidNameStatus:
              emit(UserOTPSent());
              emit(UserRegisteredWithoutName());
              emit(UserRegistered());
              break;
            default:
              emit(UserRegisterFailure(item.message));
              break;
          }
        } catch (_) {
          emit(UserRegisterFailure(null));
        }
      }
    
      @override
      UserState? fromJson(Map<String, dynamic> json) {
        try {
          final user = User.fromJson(json);
          return UserLoggedIn(user);
        } catch (_) {
          return null;
        }
      }
    
      @override
      Map<String, dynamic>? toJson(UserState state) {
        if (state is UserLoggedIn) {
          return state.user.toJson();
        } else {
          return null;
        }
      }
    }

**Comment by felangel** [comment]
Hi @MHKalantarian 👋 
Thanks for opening an issue!

If this is still an issue can you please provide a link to a minimal reproduction sample that I can easily run to reproduce the issue locally? Thanks! 👍

**Comment by felangel** [comment]
Closing for now but if it's still an issue please provide a link to a minimal reproduction sample and I'm happy to take a closer look, thanks!
