### ISSUE TITLE
Question: call `whenListen` multiple times on the same cubit for integration test isn't working?

### ISSUE THREAD

**Issue by tijanirf** [felangel/bloc#3440]
**Description**
I need to stub a mock cubit in my integration test to handle navigation on `BlocListener`, so I use`whenListen` to return `AState` and it is working. But later on in the same test case, I need to stub that cubit to return `BState` to handle another behavior on the `BlocListener` but it is not working. 

**Steps To Reproduce**

```dart
... some unit test assertions ...

whenListen(
  _fooCubit,
  Stream.fromIterable([
    AState(),
  ]),
);

... some unit test assertions ...

whenListen(
  _fooCubit,
  Stream.fromIterable([
    BState(),
  ]),
);


```

This is the `BlocListener` on the main app (inside MaterialApp builder)
```dart
BlocListener<FooCubit, BaseState>(
  listener: (context, state) async {
    if (state is AState) {
      navigateToAScreen(); // It is working
    }

    if (state is BState) {
      navigateToBScreen(); // It is not working
    }
  }
)
```

**Expected Behavior**
`BlocListener` will trigger after I did the second stub so `navigateToBScreen()` is called.

**Additional Context**
I am mocking bloc for the integration test (black-box testing) because all the presentation layers are only interacting with blocs, I encapsulate any other dependency (data layer, etc) inside the bloc. So I think it makes sense to fully mock blocs to cover all of the negative cases, it helps simplify testing on the complex project. In the previous project, I ended up mocking the data layer on the integration test because the data layer is simple. I can't use this approach on the more complex project, I did try but the data layer mocking spends too much time.

**Comment by tijanirf** [comment]
I found a workaround for my specific case, I ended up borrowing the original `whenListen` code and giving it a modification

`when_listen.dart` from the package
```dart
final broadcastStream = stream.asBroadcastStream();

if (initialState != null) {
  when(() => bloc.state).thenReturn(initialState);
}

when(() => bloc.stream).thenAnswer(
  (_) => broadcastStream.map((state) {
    when(() => bloc.state).thenReturn(state);
    return state;
  }),
);
```

My test implementation:
```dart
final StreamController fooCubitStreamController = StreamController();
final Stream fooCubitCustomStream = fooCubitStreamController.stream.asBroadcastStream();

when(() => fooCubit.stream).thenAnswer(
  (_) => fooCubitCustomStream.map((state) {
    when(() => fooCubit.state).thenReturn(state);
      return state;
    }),
);

... some unit test assertions ...

fooCubitStreamController.add(AState);

... some unit test assertions ... 

fooCubitStreamController.add(BState);

...

fooCubitStreamController.close() // Close after the test ends

```

Is my approach anti-pattern? If it's ok maybe I could create PR for allowing `whenListen()` to receive the optional `StreamController` parameter for more granular control

**Comment by felangel** [comment]
Hi @tijanirf 👋 
Thanks for opening an issue!

`whenListen` should already be able to accept a stream from a StreamController for granular control:

```dart
final controller = StreamController<MyState>();
whenListen(myCubit, controller.stream);
```

Let me know if that helps 👍

**Comment by tijanirf** [comment]
Hi @felangel,

How could I didn't think of that, silly me! I think your solution will works, thanks for the help ✌️
