### ISSUE TITLE
feat: Use Melos

### ISSUE THREAD

**Issue by lsaudon** [felangel/bloc#3443]
**Description**

Use [Melos ](https://melos.invertase.dev/)(A tool for managing Dart projects with multiple packages.)

**Desired Solution**

Setup [Melos](https://melos.invertase.dev/)

**Comment by felangel** [comment]
Hi @lsaudon 👋
Thanks for opening an issue!

I personally prefer to keep things as simple/vanilla as possible. I haven’t really had any issues with the current setup.
