### ISSUE TITLE
refactor: support onListen method

### ISSUE THREAD

**Issue by ybin0823** [felangel/bloc#3464]
Hi felangel!. I found a issue while writing a sample comparing pure StreamController and bloc.

**Description**

Since StreamController is private there is no way to pass `onListen`.
```dart
  factory StreamController.broadcast(
      {void onListen()?, void onCancel()?, bool sync = false}) {
    return sync
        ? _SyncBroadcastStreamController<T>(onListen, onCancel)
        : _AsyncBroadcastStreamController<T>(onListen, onCancel);
  }
```

```dart
abstract class BlocBase<State>
    implements StateStreamableSource<State>, Emittable<State>, ErrorSink {
  /// {@macro bloc_base}
  BlocBase(this._state) {
    // ignore: invalid_use_of_protected_member
    _blocObserver?.onCreate(this);
  }

  final _blocObserver = BlocOverrides.current?.blocObserver;

  late final _stateController = StreamController<State>.broadcast();
```

For Example,
```dart
/// sample_bloc.dart

class SampleBloc extends Cubit<int> {
   SampleBloc: super(0) {
       emit(1);  // <- First event
   }
}


@override
  void initState() {
    super.initState();

    _bloc.stream.listen((event) {
       // Cannot receive the first emitted event
  }
```

I'd like to use 

```dart
class SampleBloc extends Cubit<int> {
   SampleBloc: super(0) {
      onListen = () {
       emit(1);  // <- First event
      }
   }
}


@override
  void initState() {
    super.initState();

    _bloc.stream.listen((event) {
     // Can receive event!!
  }
```

https://api.dart.dev/stable/2.17.6/dart-async/StreamController/StreamController.broadcast.html

> A Stream should be inert until a subscriber starts listening on it (using the onListen callback to start producing events). Streams should not leak resources (like websockets) when no user ever listens on the stream.

It would be nice if a function to emit an event when the stream's listen started was also provided.

**Comment by tenhobi** [comment]
Hi @ybin0823, you cannot receive the state `0` or `1` because the `_bloc.state.listen` function was called after that. Meaning that the listen function can only subscribe to values that come after the stream subscription is created out of it.

If you want to check current state, use `_bloc.state` or I would advise to use `listen` callback in `BlocListener` or `BlocConsumer` widgets rather than working with it in an `initState` method.

**Comment by ybin0823** [comment]
Thank u for your comment!
