### ISSUE TITLE
feat: Extend the VSCode Extension with the possibility to create a "Form" Bloc. 

### ISSUE THREAD

**Issue by julienandco** [felangel/bloc#3466]
**Description**

I often have to implement some kind of form inside of my apps (either a simple registration form that takes username, email and password, or a massive form that holds user input data for some datastructure creation, say an event app where you can create an event and each event has 20 attributes or so). I like to use the bloc package as state management around this, but this leads to me writing a lot of boilerplate code, that always is the same. 

Let me give you an example with more context:

I want the users of my app to create new Recipes, which have the following attributes:

final String name;
final int durationInMinutes;
final List<Ingredient> ingredients;
final DifficultyEnum difficulty;
final User author;

... (etc. the list could go on).

I then would always have written a RecipeCreationBloc, which would have a state RecipeCreationState with the fields:

final String? name;
final int? durationInMinutes;
final List<Ingredient>? ingredients;
final DifficultyEnum? difficulty;
final User? author;
final bool isSubmitting;

Then the RecipeCreationEvent class would look something like this (i like to use freezed, that's why i'm using factories here):

const factory RecipeCreationEvent.changeName(String newName) = ..;
const factory RecipeCreationEvent.changeDurationInMinutes(int newDurationInMinutes) = ..;

... etc. for every attribute (or just a toggle function for every bool attribute).

Then i would hook everything up in the bloc, leading to n event handler registrations (for n attributes) and every single one of these event handlers would always do the same (i am using freezed, remember?):

void onChangeName(event, emitter) => emit(state.copyWith(name: event.newName));
void onChangeDurationInMinutes(event, emitter) => emit(state.copyWith(durationInMinutes: event.newDurationInMinutes));

etc...

So: a lot of boilerplate and easy code which is just busy work and annoys me.

P.S.: yes, i do know about the formz package, but I felt it was often too overkill for my purposes (if i create a recipe with a DifficultyEnum attribute, the validation function simply is: is it of type DifficultyEnum?, so the tradeoff of not having to make it nullable, because i have the .pure(), function, but always having the validator and errorType boilerplate was not working out for me).

**Desired Solution**

I would like to extend the VSCode extension (🤡) with a new method "Bloc: new FormBloc". It would prompt you for the name (as always), the number of attributes you want (as i have not found out yet how to make a vscode extension accept a dynamic number of prompts w/o permanently asking "do you want to add more?" in between two) and then for every single attribute it will prompt for the name, the stateType (type defined in the state) and the submission type (type used for the submission). 

What do I mean by stateType and submissionType? As you saw above, the stateType for e.g. difficulty is DifficultyEnum?, but its submissionType would be DifficultyEnum, as i do want something non-null in my backend, but i do not want to give it a default value in the frontEnd, thus instantiating the CreateRecipeState with a null value.

It then would generate all the files according to the boilerplate description above and you would only have to pass the bloc some dependencies via the constructor if needed and implement the onSubmit event handler.

**Alternatives Considered**

Keep wasting my time writing everything myself 👎🏻

**Additional Context**

In fact, I already have implemented the extension of the VSCode extension (🤡), since I really need it. I would love to get in touch with you if you think other users would profit from this as well and a PR would make sense. Looking forward to hearing from you!

**Comment by felangel** [comment]
Hi @julienandco 👋 
Thanks for opening an issue!

Since your form implementation will likely be opinionated, I'd prefer not to include it in the official bloc VSCode extension. Feel free to release your own VSCode extension if you have already done the work. I highly recommend creating a brick via [mason](https://github.com/felangel/mason) and publishing it via https://brickhub.dev. Then you can use the [mason vscode extension](https://marketplace.visualstudio.com/items?itemName=FelixAngelov.mason) to generate code from your template directly in VSCode. 

Hope that helps! Closing for now but feel free to comment with any follow up questions and I'm happy to continue the conversation 👍

**Comment by julienandco** [comment]
Hi @felangel,
thanks for the quick response! I will probably stick to my existing implementation, but could you elaborate how you think mason could be used here? As I am always passing a dynamic amount of variables, I was not quite sure how to design the .yaml file that describes my brick.

Cheers!
