### ISSUE TITLE
deprecate: BlocOverrides API

### ISSUE THREAD

**Issue by felangel** [felangel/bloc#3470]
## Overview

The `BlocOverrides` API was introduced in v8.0.0 in an attempt to support scoping bloc-specific configurations such as `BlocObserver`, `EventTransformer`, and `HydratedStorage`. In pure Dart applications, the changes worked well; however, in Flutter applications the new API caused more problems than it solved.

The `BlocOverrides` API was inspired by similar APIs in Flutter/Dart:

- [HttpOverrides](https://api.flutter.dev/flutter/dart-io/HttpOverrides-class.html)
- [IOOverrides](https://api.flutter.dev/flutter/dart-io/IOOverrides-class.html)

## Problems

While it wasn't the primary reason for these changes, the `BlocOverrides` API introduced additional complexity for developers. In addition to increasing the amount of nesting and lines of code needed to achieve the same effect, the `BlocOverrides` API required developers to have a solid understanding of [Zones](https://api.dart.dev/stable/2.17.6/dart-async/Zone-class.html) in Dart. `Zones` are not a beginner-friendly concept and failure to understand how Zones work could lead to the introduction of bugs (such as uninitialized observers, transformers, storage instances).

For example, many developers would have something like:

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  BlocOverrides.runZoned(...);
}
```

The above code, while appearing harmless, can actually lead to many difficult to track bugs. Whatever zone `WidgetsFlutterBinding.ensureInitialized` is initially called from will be the zone in which gesture events are handled (e.g. `onTap`, `onPressed` callbacks) due to `GestureBinding.initInstances`. This is just one of many issues caused by using `zoneValues`.

In addition, Flutter does many things behind the scenes which involve forking/manipulating Zones (especially when running tests) which can lead to unexpected behaviors (and in many cases behaviors that are outside the developer's control -- see issues below).

Due to the use of the [runZoned](https://api.flutter.dev/flutter/dart-async/runZoned.html), the transition to the `BlocOverrides` API led to the discovery of several bugs/limitations in Flutter (specifically around Widget and Integration Tests):

- https://github.com/flutter/flutter/issues/96939
- https://github.com/flutter/flutter/issues/94123
- https://github.com/flutter/flutter/issues/93676

which affected many developers using the bloc library:

- https://github.com/felangel/bloc/issues/3394
- https://github.com/felangel/bloc/issues/3350
- https://github.com/felangel/bloc/issues/3319

## Decision

After many discussions with various members of the community (including folks from the Dart/Flutter teams), we've decided to deprecate the `BlocOverrides` API and reintroduce the previous APIs in order to provide a safe, beginner friendly API, eliminate the need to worry about the above issues. When using `Zones`, technically there's nothing stopping another package from overriding the Zone values provided or even creating a brand new Zone which does not inherit the previous zone specifications. By moving back to the previous API, we eliminate these potential pit-falls and end up with a safer, simpler API.

## Next Steps

The `BlocOverrides` and `HydratedBlocOverrides` APIs will be deprecated, the previous `Bloc.observer`, `Bloc.transformer`, and `HydratedBloc.storage` APIs will be restored, and the deprecated APIs will be removed in the next major release.

### Migration

Currently, in order to specify a custom `BlocObserver` or `EventTransformer` we use the `BlocOverrides.runZoned` API:

**Before**

```dart
void main() {
  BlocOverrides.runZoned(
    () {
      // Application code...
    },
    blocObserver: MyBlocObserver(),
    eventTransformer: myEventTransformer(),
  );
}
```

After these changes, you will be able to use the previous APIs (from v7.x.x) to specify a custom `BlocObserver`, `EventTransformer`, or `HydratedStorage` instance.

**After**

```dart
void main() {
  Bloc.observer = MyBlocObserver();
  Bloc.transformer = myEventTransformer(),
  // Application code...
}
```

**Comment by purplenoodlesoop** [comment]
Hi @felangel! 

That's a good call, `BlocOverrides` did raise a lot of questions. I maintain an ecosystem-compatible BLoC alternative that uses the old API, and I have encountered similar complaints from users of my package.

To avoid breaking changes, I've implemented a system that can use both `Zone` injection and plain static variables – maybe you could use it as a reference to do something similar.

- [Observer](https://github.com/purplenoodlesoop/stream-bloc/blob/master/lib/src/base/stream_bloc_observer.dart)
- [Injection config](https://github.com/purplenoodlesoop/stream-bloc/blob/master/lib/src/model/stream_bloc_observer_config.dart)
- [Injection location](https://github.com/purplenoodlesoop/stream-bloc/blob/master/lib/src/model/stream_bloc_observer_location.dart)

**Comment by felangel** [comment]
The `BlocOverrides` API has been deprecated in bloc v8.1.0.

**Comment by bartekpacia** [comment]
Thank you very much @felangel!
