### ISSUE TITLE
feat: eventTransformer in Cubit

### ISSUE THREAD

**Issue by welderknaf** [felangel/bloc#3475]
**Description**

Is there any way to transform events in Cubit, ex: switchMap?
Why is it working only in BLOC?

**Desired Solution**

Overrides a transformer method or add a "transformer" property, just like BLOC.

**Comment by felangel** [comment]
Hi @welderknaf 👋 
Thanks for opening an issue!

The reason there is no event transformer in Cubit is because there are no events and consequently no event stream in Cubit.

Closing for now but feel free to comment with any follow up questions and I'm happy to continue the conversation 👍
