### ISSUE TITLE
Listen vs Dispatch - Style question

### ISSUE THREAD

**Issue by nhwilly** [felangel/bloc#348]
This is a pretty simple question, but it's one that I keep running into.  

In this example, I have a `user` and a `menu`.  The contents of the menu are dependent on the user who has logged in.

In the `UserBloc` I can dispatch something to the `MenuBloc` to load the correct menus after the user is authenticated.  

Or, I could have the `MenuBloc` listen to the `UserBloc` and dispatch the correct event to itself to load the proper menu after the user is authenticated.

My gut says that the `UserBloc` shouldn't know anything about menus, but the menus clearly have to know about the `user`, so I should use the latter approach.

Does that sound right?

**Comment by felangel** [comment]
Hi @nhwilly 👋 
Thanks for opening an issue!

Regarding your question, I agree with you; the `UserBloc` should not know about the `MenuBloc`. Instead, I would recommend making the `MenuBloc` have a dependency on `UserBloc`, listen to states changes in the `UserBloc`, and dispatch events in response.

Hope that helps and great question! 👍

**Comment by d-jiang** [comment]
Hello @felangel 
What do you mean  "making the MenuBloc have a dependency on UserBloc"

I also have the same question,
I try to do it like below, but seems not working.

thanks.

```dart

  @override
  Widget build(BuildContext context) {
    return BlocListenerTree(
      blocListeners: [
        BlocListener<HomeEvent, HomeState>(
          bloc: _bloc,
          listener: (BuildContext context, HomeState state) {
            if (state is InitialHomeState) {
              _bloc.dispatch(HomeEventFetchProducts());
            }
          },
        ), 
       BlocListener<UserEvent, UserState>(
          bloc: _userBloc,
          listener: (BuildContext context, HomeState state) {
            if (state is UserStateLoggedIn) {
              aBoolValue = true;
            } else {
              aBoolValue = false;
            }
          },
        ),
      ],
      child: MediaQuery.removePadding(
        removeTop: true,
        context: context,
        child: BlocBuilder(
          bloc: _bloc,
          builder: (BuildContext context, HomeState state) {
   ...
```

**Comment by felangel** [comment]
@d-jiang you can check out the [bloc to bloc communication](https://felangel.github.io/bloc/#/architecture?id=bloc-to-bloc-communication) in the docs for an example of what I meant.

In the code snippet you provided what is the problem you’re having? I don’t really see bloc to bloc communication occurring. Thanks! 👍
