### ISSUE TITLE
[brick][bloc]: Adding equatable as option in the bloc brick

### ISSUE THREAD

**Issue by BartWesthoff** [felangel/bloc#3486]
**Description**

As far as I know the events and states of bloc do always extend equatable as seen there in the  [todo event](https://github.com/felangel/bloc/blob/master/examples/flutter_todos/lib/edit_todo/bloc/edit_todo_event.dart). However in the most recent version of the [bloc brick](https://brickhub.dev/bricks/bloc/0.1.3+2) (0.1.3+2) the package equatable is not supprted. 
**Desired Solution**

I would like to add the option in the mason CLI to add equatable to the states/events of a bloc. I think it will make implementing blocs even easier when they get a bit more complicated.

**Alternatives Considered**

No alternatives other then implenting it yes/no.

**Additional Context**
this is what a bloc currently outputs (mason make bloc --name EditTodo):

`abstract class EditTodoEvent {
  const EditTodoEvent();
}`

This is what I would like to be (as found [here](https://github.com/felangel/bloc/blob/master/examples/flutter_todos/lib/edit_todo/bloc/edit_todo_event.dart)):

`abstract class EditTodoEvent extends Equatable {
  const EditTodoEvent();

  @override
  List<Object> get props => [];
}`

**Comment by felangel** [comment]
This is supported in [v0.2.0 of the bloc brick](https://brickhub.dev/bricks/bloc/0.2.0) 🎉
