### ISSUE TITLE
fix: MetaWeather API no longer working :(

### ISSUE THREAD

**Issue by jorgecoca** [felangel/bloc#3491]
**Description**
Looks like MetaWeather is no longer in business, and their API throws a 404 (https://www.metaweather.com/api/)

This affects the weather tutorial. An alternative might be needed to complete the tutorial

**Comment by felangel** [comment]
Hey @jorgecoca 👋 

Yup, it's on my list of todos -- see https://github.com/felangel/bloc/issues/3369#issuecomment-1169967573 for an alternative

**Comment by jorgecoca** [comment]
Oh sorry! My bad! I did not notice it was a duplicate! 

Let me know how I could help ;)

**Comment by felangel** [comment]
> Oh sorry! My bad! I did not notice it was a duplicate!
> 
> Let me know how I could help ;)

No problem! PRs are welcome if you have time 👍
