### ISSUE TITLE
feat: Provide multiple instances of same bloc class for multiple instances of same widget class

### ISSUE THREAD

**Issue by programmador** [felangel/bloc#3494]
**Description**

I've recently encountered a problem of having different widgets of same class in the tree. The problem is each of these similar widgets depend on a bloc. Same bloc class, but different instances - one bloc per widget. I've found out that I'm not the only one facing the issue: https://stackoverflow.com/questions/69745940/flutter-bloc-is-there-a-way-to-provide-different-instances-of-a-bloc-in-a-scre

**Desired Solution**

```
import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

typedef _HomogenicBlocBuilder<T, U extends Bloc> = Widget Function(
    BuildContext context, Map<T, U> blocs);

class HomogenicBlocProvider<V, W extends Bloc> extends StatelessWidget {
  const HomogenicBlocProvider({Key? key, required blocs, required builder})
      : _blocs = blocs,
        _builder = builder,
        super(key: key);

  final _HomogenicBlocBuilder<V, W> _builder;
  final Map<V, W> _blocs;

  @override
  Widget build(BuildContext context) {
    return _build(context, _blocs);
  }

  Widget _build(BuildContext context, Map<V, W> blocs) {
    if (blocs.isEmpty) {
      return _builder(context, _blocs);
    }

    final W head = blocs[blocs.keys.first]!;
    var tail = Map<V, W>.from(blocs);
    tail.remove(blocs.keys.first);

    return BlocProvider<W>(
      create: (_) => head,
      child: _build(context, tail),
    );
  }
}
```

Then it could be used this way:
```
  @override
  Widget build(BuildContext context) {
    // HomogenicBlocProvider creates real BlocProvider-s inside which handles .close().
    return HomogenicBlocProvider<String, BlocA>(
      blocs: {
        'first': BlocA(StateA()),
        'second': BlocA(StateA()),
      },
      builder: (context, blocs) {
        return Row(children: [
          // Here we are using BlocProvider.value() to get rid of .close().
          // For example it's extremely useful if we want to wrap everything into
          // orientation builder and want to prevent errors after bloc.close() on each screen rotation
          // which would occur if we just use normal providers here
          BlocProvider.value(
            value: blocs['first'],
            child: WidgetA(),
          ),
          BlocProvider.value(
            value: blocs['second'],
            child: WidgetA(),
          ),
        ]);
      },
    );
  }

```

It also could be used to interlink blocs. For example we have two BlocA+WidgetA and one BlocB+WidgetB.
And we want both instances of BlocA to react to state change of single instance of BlocB:
```
  @override
  Widget build(BuildContext context) {
    return HomogenicBlocProvider<String, BlocA>(
      blocs: {
        'first': BlocA(StateA()),
        'second': BlocA(StateA()),
      },
      builder: (context, blocs) {
        // Injecting one more bloc type (BlocB) for one more dependent widget (WidgetB).
        // This time it is a regular provider as we need only one instance of WidgetB.
        return BlocProvider<BlocB>(
            create: (_) => BlocB(StateB),
            child: FortuneBlocListener<BlocB, StateB>(
              listener: (_, stateB) {
                blocs.forEach((String key, BlocA blocA) {
                  // Triggering BlocA events depending on BlocB state.
                  // Thus keeping BlocA and BlocB COMPLETELY decoupled.
                  if (stateB.containsSmth()) {
                    blocA.add(BlocAEvent('something'));
                  }
                });
              },
              child: Row(children: [
                BlocProvider.value(
                  value: blocs['first'],
                  // These widgets have BlocA builders inside. So they react to BlocA state changes
                  child: WidgetA(),
                ),
                BlocProvider.value(
                  value: blocs['second'],
                  child: WidgetA(),
                ),
                // This widget has builder of BlocB inside. It also triggers/adds BlocBEvent-s
                WidgetB(),
              ]),
            ));
      },
    );
  }

```

**Alternatives Considered**

Following the link above, You'll find other solutions: Bloc subclasses and bloc mixins. Actually neither of those solutions work if You have to provide bloc instances to different instances of same widget class. You just cannot tell Provider that You need `Provider.of<BlocSubclassOne>` or `Provider.of<BlocSubclassTwo>` because depending widgets are of the same class. To somehow achieve results You would have to subclass not only a bloc but the depending widget too. So: to have 3 instances of widget depending on the same bloc You need 8 classes: two for base bloc and base widget, 3 more for bloc subclasses and 3 more for depending widget subclasses. Moreover contrary to bloc-s, widget subclasses should have slightly different implementation details (though some DI trickery is also an option). The same should be with Mixins.

**Additional Context**

The proposed wrapper widget could be implemented in different ways having slightly different functionality.
It's name is discussional as it depends on it's provided functionality and thus depends on final implementation.
That's why I propose it via a feature request issue to discuss instead if a ready-to-merge PR.

* First of all, my implementation can provide blocs only of the same type. That's why I called `Homogenic`. But this is not obligatory: it could be implemented either without using Bloc as type parameter or by setting it `covariant` somehow. In that case it should not be called Homogenic anymore, I suppose.
* Regardless of variance it is rather an Injector itself, than a Provider though it's using regular Provider-s inside of implementation and also considers using Provider.value-s down the tree (though DI without Provider.value is also an option).
* It could be also presented as a special case of MultiBlocProvider preserving/injecting bloc keys to distinguish bloc-s of same class.

**Comment by programmador** [comment]
Here's a way of representing what's the case.

### This is not a problem:
```mermaid
graph LR
    B1[BlocA instance1]
    B2[BlocA instance2]
    W1[WidgetA returns BlocBuilder of BlocA]
    W2[WidgetA returns BlocBuilder of BlocA]

    B1 --> W1
    B2 --> W2
```

### This... IS PAIN!
```mermaid
graph LR
    B1[BlocA instance1]
    B2[BlocA instance2]
    OB[Widget returns OrientationBuilder]
    W1[WidgetA returns BlocBuilder of BlocA]
    W2[WidgetA returns BlocBuilder of BlocA]

    B1 --> OB
    B2 --> OB
    OB --> W1
    OB --> W2
```
because of same type of both blocs, provider should be created to the right of OrientationBuilder on the flow. But BlocProvider will trigger .close() on each orientation change! So creating blocs themselves to the left of OrientationBuilder will actually cause a runtime error.
### And this is a solution:
```mermaid
graph LR
    HB[Proposed builder creates BlocProvider for each bloc]
    B1[BlocA instance1]
    B2[BlocA instance2]
    OB[Widget receives bloc instances via DI and returns OrientationBuilder]
    W1[WidgetA returns BlocBuilder of BlocA]
    W2[WidgetA returns BlocBuilder of BlocA]
    PV1[BlocProvider.value -> instance1]
    PV2[BlocProvider.value -> instance2]

    HB --> B1
    HB --> B2
    B1 --> OB
    B2 --> OB
    OB --> PV1
    OB --> PV2
    PV1 --> W1
    PV2 --> W2
```

**Comment by programmador** [comment]
Doing the same manually invlolves trickering with context:
```
Widget Build(){
  return Builder
    var bloc1 = ...
    return Provider
      return Builder
        var bloc2 = ...
        return Provider
        //...etc
```
Which in real non-sketch code is unreadable even for two blocs, believe me )

**Comment by felangel** [comment]
Hi @programmador 👋
Thanks for opening an issue!

Can you please provide some more context regarding your current use case? It’d be really helpful to understand what you’re trying to achieve in the context of app functionality. Thanks!

**Comment by programmador** [comment]
Ok, let's then get into real code example.
My app page has 3 widgets and 3 blocs. One bloc per widget. Two of both widgets and blocs are of the same type:
![screenshot_2022-08-13-193341](https://user-images.githubusercontent.com/674995/184502931-d48cf34e-14d3-4e18-b907-59abd52b5102.png)
The app has also another layout variant:
![screenshot_2022-08-13-193316](https://user-images.githubusercontent.com/674995/184502967-a36306f2-2d01-41c6-a882-7fb470925528.png)
Which is switched via OrientationBuilder.

So, those widgets and blocs have their names, let's fix it not to be confused further: one Fortune (either [wheel or bar](https://pub.dev/packages/flutter_fortune_wheel)) and two Bingos.
### Requirements:
* Bingos are of the same type but they have different data (which You can actually see on screenshots)
* The data should retain while app orientation is switching (the blocs cannot be recreated)
* Both Bingo blocs depend on Fortune bloc state. In my case it's achieved via adding events into both Bingo blocs inside of Fortune bloc listener.

### Widget tree
Now let's traverse the tree from top to down to see where our bloc instances are flowing and what for

#### Page

```
class FortuneBingoPlayPage extends StatelessWidget {
  const FortuneBingoPlayPage({Key? key, entries})
      : _entries = entries,
        super(key: key);

  final List<FortuneBingoEntry> _entries;

  @override
  Widget build(BuildContext context) {
    return HomogenicBlocProvider<String, BingoBloc>(
      blocs: {
        'first':
            BingoBloc(BingoState(items: _toBingoItems(_entries), selected: [])),
        'second':
            BingoBloc(BingoState(items: _toBingoItems(_entries), selected: [])),
      },
      builder: (context, blocs) => FortuneBlocProvider(
        items: _toFortuneItems(_entries),
        child: BlocListener<FortuneBloc, FortuneState>(
          listener: (_, fortuneState) {
            blocs.forEach((String key, BingoBloc bingoBloc) {
              if (fortuneState.removed != null) {
                bingoBloc.add(BingoGameSelected(fortuneState.removed!.id));
              }
            });
          },
          child: Scaffold(
            body: FortuneBingoPlayOrientation(
              bingoBlocOne: blocs['first'],
              bingoBlocTwo: blocs['second'],
            ),
          ),
        ),
      ),
    );
  }
```

Both Page, Bingo and Fortune have their own entry types (they are decoupled). So the page also has `_toBingoItems()` and `_toFortuneEntries()` which I have omitted for clarity.
That's what happening on the Page:
* Two Bingo blocs are provided via HomogenicBlocProvider. So it handles bloc.close() for both
* One Fortune bloc is provided right here as it exists in only one instance
* Both bingo blocs are injected into FortuneBingoPlayOrientation

#### Orientation switcher
```
  @override
  Widget build(BuildContext context) {
    return OrientationBuilder(
      builder: (context, orientation) {
        return orientation == Orientation.portrait
            ? FortuneBingoPlayPortrait(
                bingoBlocTop: _bingoBlocOne,
                bingoBlocBottom: _bingoBlocTwo,
              )
            : FortuneBingoPlayLandscape(
                bingoBlocLeft: _bingoBlocOne,
                bingoBlocRight: _bingoBlocTwo,
              );
      },
    );
  }

```
Here the whole page is being rebuilt with the proper layout when either the device is rotated (mobile) or window proportions changed (web)

#### Concrete Orientation
```
          BlocProvider.value(
            value: _bingoBlocRight,
            child: const BingoGrid(),
          )
```
Here it doesn't matter which orientation it is or what are the siblings. The main idea is that we are using `BlocProvider.value()` to provide specific bloc instance (instance, not a type!). In my case there are two of them. The provided snippets provides `_bingoBlocRight`. Obviously there's a `left` sibling nearby.

#### Bingo

```
class BingoGrid extends StatelessWidget {
  const BingoGrid({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<BingoBloc, BingoState>(
      builder: (context, state) {
        return GridView(
```

So each BingoGrid is built according to state of it's instance of BingoBloc. That's it.

## Wrong way

First I tried to create blocs in Page and use regular `BlocProvider`s (not `.value` ones) in each Layout (both portrait and landscape).
It caused an error. As You can see, there's a code in `Page` which adds events to both Bingo blocs according to Fortune bloc state.
So they were failing at runtime because abovementioned regular providers were recreated on each orientation change(rebuild) thus closing provided blocs. So there was smth like "trying to write into stream after closed()" at runtime.

**Comment by programmador** [comment]
Actually that "wrong way" is also okay if we manually handle bloc.close() somewhere upper (for example in the `Page`)
Provided solution is actually just a way to still use `official` providers and do not do such things manually.

**Comment by programmador** [comment]
So the purpose is exactly the same as of MultiBlocProvider. The main difference is ability to somehow handle multiple blocs of same type.

**Comment by iandis** [comment]
I'm curious of the reason behind why you need 2 blocs of the same type for the same data type (bingo items)

**Comment by programmador** [comment]
Of course I can add any amount of spaghetti into the bloc and it's state and also in a widget built by BlocBuilder of that bloc. The goal is to keep components simple. In my case each Bingo should not care whether more game widgets are present on the page. It also does not care about their type. It's parent's job to interlink those widgets. And parent has to deal with child type similarity in my case.

**Comment by felangel** [comment]
I'd prefer not to include a widget like this in the library for several reasons:

- It should be something you can implement already as a separate package
- I highly recommend using blocs to manage feature state (you should have a bloc per feature in your app)
  - With this paradigm, you'd would not need multiple instances of the same bloc because there should not be multiple instances of the same feature in your application.

Feel free to comment with additional thoughts if you disagree but otherwise I'm going to close this for now since I don't think there are any actionable next steps.
