### ISSUE TITLE
Is it possible to merge blocs

### ISSUE THREAD

**Issue by fmatuszewski** [felangel/bloc#35]
Let's suppose I have two blocs Router and Model and I have to create gui based on the state of both of them with router I choose Widget that will be rendered and  I have to pass model to each view widget.
Is it possible to easily merge two  Bloc s Like for instance ZipStream.

**Comment by felangel** [comment]
You would probably have to create a third bloc which merged the two and then build the ui in response to the state of the new bloc. Let me know if that helps.

**Comment by felangel** [comment]
Closing this for now. Please feel free to comment with more details and I’ll gladly reopen it.
