### ISSUE TITLE
flutter_login is not building 

### ISSUE THREAD

**Issue by therajanmaurya** [felangel/bloc#350]
I an new to flutter, I read flutter documentation and trying to build the flutter_login sample but It is not building

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5724482/59559754-f419cf80-9026-11e9-9684-1915728dfb0d.png">

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5724482/59559784-03008200-9027-11e9-94a1-d934873f55ee.png">

Please help what I am doing wrong, Thanks in advance.

**Comment by felangel** [comment]
Hi @therajanmaurya 👋 
Thanks for opening an issue!

Where did you find the flutter_login code? It looks like the example you’re referencing is outdated. The updated version can be found [here](https://felangel.github.io/bloc/#/flutterlogintutorial).

Let me know if that helps! 👍

**Comment by therajanmaurya** [comment]
It's wired. I cloned the same repo 2 days ago. BTW Now It's working fine except one issue is there 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5724482/59560604-968b8000-9032-11e9-8ecc-9a35983bd3d9.png">

Like you can see we don't have `meta` in [`pubspec.yaml`](https://github.com/felangel/bloc/blob/master/examples/flutter_login/pubspec.yaml#L8)

I tried to add it but still, It is not resolving.

**Comment by felangel** [comment]
@therajanmaurya did you run `pub get` from the `user_repository`?

**Comment by therajanmaurya** [comment]
@felangel I tried and It's working. You can close it.
