### ISSUE TITLE
fix: there is not storage getter for HydratedBloc & HydratedCubit for mocking

### ISSUE THREAD

**Issue by aldiwijayaiskandar** [felangel/bloc#3517]
@felangel  hi so i've used the v.8.1.0 of hydrated_bloc, but i can't mock the storage of the HydratedBloc & HydratedCubit

![Screen Shot 2022-09-01 at 14 52 46](https://user-images.githubusercontent.com/42193940/187862213-9c75b49c-ff56-4b21-8387-687eb32b93ee.png)

![Screen Shot 2022-09-01 at 14 54 56](https://user-images.githubusercontent.com/42193940/187862284-4f55b619-f5d5-40e2-81ec-0302b418b2e4.png)

**Comment by felangel** [comment]
Hi @aldiwijayaiskandar 👋 
Thanks for opening an issue!

You need to use the latest version of hydrated_bloc which is currently 9.0.0-dev.3
https://pub.dev/packages/hydrated_bloc/versions/9.0.0-dev.3

Hope that helps 👍
