### ISSUE TITLE
fix:  flutter bloc  data is updating but ui doesn't update 

### ISSUE THREAD

**Issue by isshort** [felangel/bloc#3519]
Hi to everyone! 
  
  I have menu in the row side and items list when I click to my menu the item list should be change with the belonging menu 
  
  I have tow cubit one is for menu list to get menu list in horzintal side 
  and other is for item list in vertical side 
  item list is showing according to menu 
  in my example data is coming normally  when I change the menu data is changing but ui is not changing 
 for this one I did a todo example for good understanding  

      
         const MenuList(),
          BlocBuilder<LoadDataCubit, LoadDataState>(
            builder: (context, state) {
              if (state is LoadDataSuccess) {
                return Expanded(
                    child: ItemPagination(
                  itemsList: (page) async => state.itemList,
                ));
              }
              return const CircularProgressIndicator();
            },
          ),

 - and my menuList is 
    
         

              return GestureDetector(
              onTap: () {
                context.read<LoadDataCubit>().loadData(index + 10);
              },
              child: Padding(
                padding: const EdgeInsets.symmetric(horizontal: 6),
                child: Container(
                  height: 40,
                  width: 70,
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                      color: Theme.of(context).colorScheme.primary,
                      borderRadius: BorderRadius.circular(5)),
                  child: Text('$index page'),
                ),
              ),
            );

      - Here is the whole todo project example [https://github.com/isshort/pagination_todo](url)

**Comment by Gene-Dana** [comment]
Hi there ! Try adding a key to menuList

`key: Key('something_unique')`

or

`key: UniqueKey()`

**Comment by isshort** [comment]
Thanks Mr @Gene-Dana  for your response 
I added UniqueKey() 
The view side without pagination is working but when i am using pagination it doesn't work.
The problem in here is That
When I pressed anyone of the menu than 
the  ItemPagination StatefulWidget's  initState method  must be work

but  it doesn't work.

**Comment by marcossevilla** [comment]
hey @isshort, the link you provided points to the issues from this repo, can you update it with your todos repository link?

**Comment by bernaferrari** [comment]
initState only loads on the first time the widget is loaded. When it is reloaded, you need `didChangeDependencies`. Stateful is kind of Bloc's enemy.

**Comment by isshort** [comment]
Thanks @bernaferrari for your reply
