### ISSUE TITLE
fix: [bloc_test] test checks expected result before mocked repository calls in tested event execute and every state is emitted

### ISSUE THREAD

**Issue by woeckener** [felangel/bloc#3521]
**Description**
Hello guys. I am currently having a problem with testing a bloc event that calls several repository methods and emits new states between and after those calls.

I created a minimal reproducible example that is only configured to run that one test.
https://github.com/woeckener/flutter_bloctest

**Steps To Reproduce**
The bloc event emits the first status, calls and awaits two repository methods, emits the second status, calls and awaits a third repository method and is then supposed to emit the third and final status.
```
on<DeviceEventForTest>((event, emit) async {
    emit(DeviceState(status: 1));
    await this.deviceRepository.add();
    await this.deviceRepository.disconnect();
    emit(DeviceState(status: 2));
    await this.deviceRepository.delay();
    emit(DeviceState(status: 3));
});
```

During the build portion of the test I mock those repository calls and also print logs to the console for better visibility.
```
build: () {
  when(() => deviceRepository.add()).thenAnswer((_) {
    print('add');
    return Future(() {});
  });
  when(() => deviceRepository.disconnect()).thenAnswer((_) {
    print('disconnect');
    return Future(() {});
  });
  when(() => deviceRepository.delay()).thenAnswer((_) {
    print('delay');
    return Future(() {});
  });
  return bloc;
},
```

**Expected Behavior**
I expect all three status updates to emit during the test
```
expect: () => [
  DeviceState(status: 1),
  DeviceState(status: 2),
  DeviceState(status: 3),
],
```

but I get the following error message, that indicates that the test execution is finished before the second status is emitted.
```
add
disconnect
package:bloc_test/src/bloc_test.dart 226:11  testBloc.<fn>
===== asynchronous gap ===========================
dart:async                                   _asyncThenWrapperHelper
package:bloc_test/src/bloc_test.dart         testBloc.<fn>
dart:async                                   runZonedGuarded
package:bloc_test/src/bloc_test.dart 199:9   testBloc
package:bloc_test/src/bloc_test.dart 156:13  blocTest.<fn>
package:bloc_test/src/bloc_test.dart 155:5   blocTest.<fn>
delay

Expected: [
            DeviceState:DeviceState(1),
            DeviceState:DeviceState(2),
            DeviceState:DeviceState(3)
          ]
  Actual: [DeviceState:DeviceState(1)]
   Which: at location [1] is [DeviceState:DeviceState(1)] which shorter than expected

==== diff ========================================

[DeviceState(1)[-, DeviceState(2), DeviceState(3)-]]

==== end diff ====================================
```

**Comment by elianortega** [comment]
Hey @woeckener the issue with your test is in this part of the test:

```dart
 when(() => deviceRepository.add()).thenAnswer((_) {
    print('add');
    return Future(() {});
  });
  when(() => deviceRepository.disconnect()).thenAnswer((_) {
    print('disconnect');
    return Future(() {});
  });
  when(() => deviceRepository.delay()).thenAnswer((_) {
    print('delay');
    return Future(() {});
  });
```

there is no need to return a `Future`, the creation of it takes some milliseconds and this is why the `expect` fails. You could solve this by adding a `wait: const Duration(milliseconds:100)` but this is not the idea. 

You could simply define you `when` cases like this:

```dart
when(() => deviceRepository.add()).thenAnswer((_) async {});
when(() => deviceRepository.disconnect()).thenAnswer((_) async {});
when(() => deviceRepository.delay()).thenAnswer((_) async {});
```

For extra improvement, the `when` statements should be defined inside the `setup` callback from the `blocTest()`. 

For extra details I highly recommend checking out the [`bloc_test`](https://pub.dev/packages/bloc_test) documentation.

and some examples like the [todos_overview_bloc_test.dart](https://github.com/felangel/bloc/blob/master/examples/flutter_todos/test/todos_overview/bloc/todos_overview_bloc_test.dart).

Hope this helps 👍

**Comment by woeckener** [comment]
Hi @elianortega
thank you, that fixed my problem 👍 
In Germany we have a saying that you sometimes can't see the forest because there are so many trees 😬
