### ISSUE TITLE
The getter 'file' isn't defined for the type 'FileResponse'

### ISSUE THREAD

**Issue by habner12** [felangel/bloc#3524]
I'm trying to load images from Firebase, But I have a red line file, final imageBytes = fileResponse.file.readAsBytesSync(); Any Solution?

class ImageLoader {
  ui.Codec frames;

  String url;

  Map<String, dynamic> requestHeaders;

  LoadState state = LoadState.loading; // by default

  ImageLoader(this.url, {this.requestHeaders});

  void loadImage(VoidCallback onComplete) {
    if (this.frames != null) {
      this.state = LoadState.success;
      onComplete();
    }

    final fileStream = DefaultCacheManager().getFileStream(this.url,
        headers: this.requestHeaders as Map<String, String>);

    fileStream.listen(
          (fileResponse) {
        if (!(fileResponse is FileInfo)) return;
        if (this.frames != null) {
          return;
        }

        final imageBytes = fileResponse.file.readAsBytesSync();

        this.state = LoadState.success;

        PaintingBinding.instance.instantiateImageCodec(imageBytes).then(
                (codec) {
              this.frames = codec;
              onComplete();
            }, onError: (error) {
          this.state = LoadState.failure;
          onComplete();
        });
      },
      onError: (error) {
        this.state = LoadState.failure;
        onComplete();
      },
    );
  }
}

**Comment by felangel** [comment]
Hi @habner12 👋 
Thanks for opening an issue!

It doesn't appear that this is related to the bloc library so I'm closing this for now. Feel free to post on the [bloc discord](https://discord.gg/bloc), StackOverflow, etc.

Thanks!
