### ISSUE TITLE
BlocTest: mocks cause problems with discarded_futures lint

### ISSUE THREAD

**Issue by fabianbrandscheid** [felangel/bloc#3550]
Hi,

since the update to Dart 2.18 the new lint [discarded_futures](https://dart-lang.github.io/linter/lints/discarded_futures.html) is available.
We are facing the issue that we currently have to explicitly ignore the Lint for each BlocTest containing mocks.

For example:
```
 blocTest("Some Test",
        build: () {
// ignore: discarded_futures, <-- Lint fires
          when(() => mockSomeObjekt()).thenAnswer(
              (_) async => const Left(givenResult));

          return bloc;
        },
        act: (_) => bloc
          ..add(SomeEvent()),
        expect: () => [
             <Some expected states>
            ],
        verify: (_) {
// ignore: discarded_futures, <-- Lint fires
          verify(() => mockSomeObjekt()).called(1);
        });
```

How can we adjust the BlocTests without ignoring the Lint every time?
We have not found a solution for this yet.

Thanks in advance!

**Comment by felangel** [comment]
Hi @fabianbrandscheid 👋 
Thanks for opening an issue!

You could do:

```dart
 blocTest("Some Test",
        setUp: () async {
          when(() => mockSomeObjekt()).thenAnswer(
              (_) async => const Left(givenResult));
        },
        build: () => bloc,
        act: (_) => bloc
          ..add(SomeEvent()),
        expect: () => [
             <Some expected states>
            ],
        verify: (_) async {
          verify(() => mockSomeObjekt()).called(1);
        });
```

Hope that helps 👍

**Comment by fabianbrandscheid** [comment]
This was much easier than expected. Thanks for the quick reply!

We had tried all possible variants with the build method from BlocTest....

**Comment by andreBalh** [comment]
How would you solve that issue having just a normal test. There is also this problem @felangel
