### ISSUE TITLE
question: Can i use Hydrated Bloc with shared_preferences to benefit from android allowBackup function?

### ISSUE THREAD

**Issue by tmaihoff** [felangel/bloc#3554]
**Description**
I would like to use the shared_preferences package to persist my Hydrated Bloc (or Cubit) state so that I can benefit from the android allowBackup functionality which then would synch the state across the Google account. 

The benefit would be that the state would be persistent even after reinstalling the app (on a different device).

I haven't found a way to implement this in the documentation and would appreciate an answer.

Thanks in advance, really great package 🚀

**Comment by felangel** [comment]
Hi @tmaihoff 👋
Thanks for opening an issue!

You should be able to create a [custom storage implementation](https://github.com/felangel/bloc/tree/master/packages/hydrated_bloc#custom-hydrated-storage) that uses shared preferences.

Hope that helps 👍

**Comment by tmaihoff** [comment]
Thanks for the headsup, will try 👍

**Comment by tmaihoff** [comment]
Hi @felangel, with your latest release of `hydrated_bloc` we are able to change the `Storage` for a single bloc, thanks for that!
I wrote a [`shared_preferences_storage`](https://github.com/tmaihoff/shared_preferences_storage) implementation which I use for one of my Cubits now. 

With your experience, could you assess if it would be worth it publishing it to pub.dev? Do you think others could be interested? 
If so, maybe you could review it quickly to make sure I didn't miss something big. Looking forward to your thoughts!
