### ISSUE TITLE
fix: context.read in didChangeDependencies

### ISSUE THREAD

**Issue by AlexanderFarkas** [felangel/bloc#3560]
**Description**
Shouldn't it be `context.watch` [here](https://github.com/felangel/bloc/blob/master/packages/flutter_bloc/lib/src/bloc_listener.dart#L168)?

**Comment by felangel** [comment]
No, that's working as expected 👍 
Thanks for opening an issue though and lmk if you have any additional concerns.

**Comment by maximveksler** [comment]
It's possible that refecing these discussions in the form of code comments to ppl reading the code would be wise, as this would provide both an oppertunity to teach the community and will denoise the amounts of 

Community: "shouldn't it be X?"
@felangel: No, that's intentional.
