### ISSUE TITLE
feat: Honeycomb instead of Provider

### ISSUE THREAD

**Issue by AlexanderFarkas** [felangel/bloc#3564]
**Description**

What do you think about [honeycomb](https://github.com/AlexanderFarkas/honeycomb/tree/master/packages/honeycomb) package as a replacement for Provider? 

I've also released a BLoC wrapper - [honey_bloc](https://github.com/AlexanderFarkas/honeycomb/tree/master/packages/honey_bloc)

**Additional Context**

I'm an author of the packages, and I will be glad to receive any feedback, since I'm an active user of BLoC and huge fan of the whole bloc ecosystem.

**Comment by felangel** [comment]
Hi @AlexanderFarkas 👋 
Thanks for opening an issue!

So far I don't think the pros of transitioning away from `provider` outweigh the cons. If there comes a point where `provider` is no longer maintained then I'm happy to discuss alternatives (although I prefer to maintain the current API unless we have a very clear reason to diverge).

Closing for now but thanks for reaching out and for the support! I'll check out honeycomb when I have some time and will be sure to provide any feedback 👍
