### ISSUE TITLE
Question: How to implement bloc to bloc communication Flutter bloc

### ISSUE THREAD

**Issue by georgek1991** [felangel/bloc#3566]
In project I have a Home page(with list of movie data) with HomeBloc. On clicking the a single movie cell I navigate to movie details page which has MovieDetailsBloc. Now in the details page I can edit name or make movie as favourite etc, this needs to be reflected in Home page.

To update the Home page after a change in Movie details page, I am sending HomeBloc to Movie details page like this

`MovieDetailsPage(homeBloc: <instance of HomeBloc>)`

and in the MovieDetailsBloc I am calling the event of HomeBloc to update the Home page like this

`homeBlocInstance.add(<home event>)`

This method is working. 

My question is Is this good method like passing bloc to a page? There will be many places from where this Home page may need to be updated. For example

Make changes in settings -> Update home page
In this case should I pass the Home bloc to settings page? But what if the navigation is like this Home page -> Summary page -> settings page, should I keep passing the HomeBloc from Home page to Summary page and then settings page? This does not seem right.

Am i doing it right? or is there any better solution?

**Comment by tenhobi** [comment]
Think of blocks only as providers between your data storage or other services and your UI. When you change some data in the details page, you should call a service that stores the data, and the home page bloc can check for some updates.

**Comment by Luci3b** [comment]
_Disclaimer: I'm a new dev and I have been using this package for almost a year, any better answers or corrections are welcome._

> How to implement a bloc to bloc communication ?

You can connect two blocs through presentation or domain as you can see @felangel examples [here](https://bloclibrary.dev/#/architecture?id=connecting-blocs-through-presentation).

I prefer connecting them using the domain, you can create a `MoviesRepository` and expose a stream that your `MoviesBloc` will listen. Then you can provide the same repository to another bloc and any changes that you make in your repository will reflect in your `MoviesBloc`.

You can see more concrete examples in the [Login example repository](https://bloclibrary.dev/#/flutterlogintutorial?id=authentication-repository) in the [docs](https://bloclibrary.dev/#/) and the [Todos example API](https://bloclibrary.dev/#/fluttertodostutorial?id=localstoragetodosapi).

> My question is Is this good method like passing bloc to a page?
Am i doing it right? or is there any better solution?

If you provide your `MoviesBloc` above your Material App, then you can get it in any route using:

```dart
// with extensions
context.read<BlocA>();

// without extensions
BlocProvider.of<BlocA>(context);
```
as seeing [here](https://bloclibrary.dev/#/flutterbloccoreconcepts?id=blocprovider).

> But what if I declare my bloc provider below the material app ?

Then you have two options:

✅Recommended in the docs: Using `BlocProvider.value`.
```dart
// home_page.dart
Navigator.push(
  context,
  MaterialPageRoute(
    builder: (innerContext) => BlocProvider.value(
      value: MoviesBloc(),
      child: MovieDetailsPage(),
    ),
  ),
);
```
Then you can get the `MoviesBloc` in your `MovieDetailsPage` using: `context.read<MoviesBloc>();`.

✅Passing the bloc as an argument.
You can simply pass your bloc to your widget as an argument: `MovieDetailsPage(moviesBloc: moviesBloc)`.

**Comment by georgek1991** [comment]
> Think of blocks only as providers between your data storage or other services and your UI. When you change some data in the details page, you should call a service that stores the data, and the home page bloc can check for some updates.

Can you give some example? 

Did you mean using streamcontroller in the repository and any changes in repository should be listened in the bloc? In this case if I have multiple blocs that need the changes, I will need a broadcast stream. I will pass the same instance of repository in every bloc or make the repository singleton. Is my understanding correct?

**Comment by tenhobi** [comment]
@georgek1991 it all depends on your strategy.

But yes, you can listen to some service/repository for new changes in your data and emit new states if so. Or you can simply just request new data if you know that in your subpage the data were modified, or you can refresh any time you visit the route.

**Comment by georgek1991** [comment]
> Or you can simply just request new data if you know that in your subpage the data were modified, or you can refresh any time you visit the route.

how do I know if any data was modified in subpages and modify the home page? I mean I don't want to refresh the home page every time I visit that route.
And regarding the streamcontroller method making repository singleton is the way?

**Comment by Luci3b** [comment]
> how do I know if any data was modified in subpages and modify the home page? I mean I don't want to refresh the home page every time I visit that route.

If your call a method from your repository that add a new value to the stream, all subscribers will receive it. So you just need to pass the same instance to all of them.

> And regarding the streamcontroller method making repository singleton is the way?

You don't have to create a singleton, just create your `MoviesRepository` in your main method, pass as an argument to your app and use the [RepositoryProvider](https://github.com/felangel/bloc/issues/3566) for the dependency injection. Then you can get it in any widget if you declare above the material app.

```dart
void main() {
  final MoviesRepository moviesRepository = MoviesRepository();

  runApp(MyApp(moviesRepository: moviesRepository));
}

class MyApp extends StatelessWidget {
  const MyApp({required this.moviesRepository, super.key});

  final MoviesRepository moviesRepository;

  @override
  Widget build(BuildContext context) {
    return RepositoryProvider.value(
      value: moviesRepository,
      child: BlocProvider(
        create: (innerContext) => MoviesBloc(moviesRepository: moviesRepository),
        child: MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(primarySwatch: Colors.blue),
          home: const MyHomePage(title: 'Flutter Demo Home Page'),
        ),
      ),
    );
  }
}
```
Then you can get the repository this way:
```dart
// with extensions
context.read<MoviesRepository>();

// without extensions
RepositoryProvider.of<MoviesRepository>(context);
```

**Comment by georgek1991** [comment]
Thanks @Luci3b.

I have a follow up question. If I give RepositoryProvider at the root widget and create stream to listen and update the home page, this stream will always be listening even if it is not required. Won't it impact the app memory usage? I am following this example:
https://github.com/felangel/bloc/blob/master/examples/flutter_login/lib/authentication/bloc/authentication_bloc.dart

Once again thank you for clearing my doubts.

**Comment by felangel** [comment]
> Thanks @Luci3b.
> 
> I have a follow up question. If I give RepositoryProvider at the root widget and create stream to listen and update the home page, this stream will always be listening even if it is not required. Won't it impact the app memory usage? I am following this example: https://github.com/felangel/bloc/blob/master/examples/flutter_login/lib/authentication/bloc/authentication_bloc.dart
> 
> Once again thank you for clearing my doubts.
That is up to you. If it’s not always needed you can cancel the subscription but having a single active stream subscription should not have a significant impact on performance.
