### ISSUE TITLE
MultiBlocProvider only works if wrap'ed   in Widget

### ISSUE THREAD

**Issue by JCzz** [felangel/bloc#3569]
I am using `MultiBlocProvider` in the following, can you see why I am getting Error: `Could not find the correct Provider<GameBloc> above this App Widget`.

Reading from the same context and all: `context.read<GameBloc>();`

    class App extends StatelessWidget {
      const App({Key? key}) : super(key: key);
    
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          home: Scaffold(
              body: MultiBlocProvider(
                providers: [
                  BlocProvider<GameBloc>(
                      create: (_) => GameBloc()),
                  BlocProvider<BallBloc>(
                      create: (_) => BallBloc()..add(const StartTimer())),
                ],
                child: TextButton(
                  onPressed: () {
                    var b = context.read<GameBloc>();
                  },
                  child: const Text("onPress"),
                )
              ),
            ),
          );
      }
    }

I am unable to see why the following is working then - compared to the above this just wraps an extra layer of Widget below the context:

```
class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MultiBlocProvider(
          providers: [
            BlocProvider<GameBloc>(
                create: (_) => GameBloc()),
            BlocProvider<BallBloc>(
                create: (_) => BallBloc()..add(const StartTimer())),
          ],
          child: const GameView()
      ),
      );
  }
}

class GameView extends StatelessWidget {
  const GameView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: TextButton(
        onPressed: () {
          var b = context.read<GameBloc>();
        },
        child: const Text("onPress"),
      ),
    );
  }
}
```

**Comment by felangel** [comment]
Hi @JCzz 👋 
Thanks for opening an issue!

This is because you the context you are using doesn't have access to the bloc since it's a context that was created outside of the `MultiBlocProvider`. I highly recommend checking out https://bloclibrary.dev/#/faqs?id=blocproviderof-fails-to-find-bloc for more information 👍
