### ISSUE TITLE
Question: Bloc Flow Navigation

### ISSUE THREAD

**Issue by sirEgghead** [felangel/bloc#3576]
I'm not a big fan of opening a Github request for support/assistance , but I saw that you guys already have questions listed in here, and I have been struggling to find the answer elsewhere, so hopefully this is still in line with the way that you guys want to handle this request.  And of course, thank you guys for a great system!

My app is a Firebase app, so I borrowed your sample [Firebase Login](https://bloclibrary.dev/#/flutterfirebaselogintutorial) app to start off with.  The navigation there appears to be based on the authentication status.  This is great if there are no views/pages beyond just login and home, but I want to learn how to make it handle more.  So I made an attempt at that which is not fully successful.

I added a `NavigationDrawer`. I added a `CurrentView` to the `AppState`, which I don't like how I did that. I feel like I should be placing the view in a different Bloc, but I'm not certain. I didn't extract `CurrentView` primarily because I didn't know how to check within `onGenerateAppViewPages` for the currently set view if it was outside the `AppState`.

Currently, the app works insomuch as it will begin on the login page and navigate to the home page once authentication is successful. I was also able to generate navigation to the pages.  However, I found a flaw. If I attempt to navigate back to the home page, I receive an *unexpected null* error when I attempt to use the `User` information.  Just to be clear, the home page works perfectly when it is navigated to directly after authentication. It only breaks when attempting to use the link in the `NavigationDrawer`.

Am I messing up the `context` somewhere? Also if I can separate the authentication Bloc from the current view Bloc, I think that may be more appropriate. I simply just do not know how to request the info properly.  So far, I did not modify much from your sample app. 

 Here's what I've got, currently.

**routes.dart**
```dart
List<Page<dynamic>> onGenerateAppViewPages(
  AppState state,
  List<Page<dynamic>> pages,
) {
  // switch (state) {
  //   case AppStatus.authenticated:
  //     return [HomePage.page()];
  //   case AppStatus.unauthenticated:
  //     return [LoginPage.page()];
  // }

  if (state.status == AppStatus.authenticated) {
    switch (state.view) {
      case CurrentView.login:
        return [LoginPage.page()];
      case CurrentView.first:
        return [FirstPage.page()];
      case CurrentView.second:
        return [SecondPage.page()];
      case CurrentView.home:
        return [HomePage.page()];
      default:
        return [HomePage.page()];
    }
  } else {
    return [LoginPage.page()];
  }
}
```

**app_event.dart**
```dart
part of 'app_bloc.dart';

abstract class AppEvent extends Equatable {
  const AppEvent();

  @override
  List<Object> get props => [];
}

class AppLogoutRequested extends AppEvent {}

class AppUserChanged extends AppEvent {
  @visibleForTesting
  const AppUserChanged(this.user);

  final User user;

  @override
  List<Object> get props => [user];
}

class AppViewChanged extends AppEvent {
  // @visibleForTesting
  const AppViewChanged(this.view);

  final CurrentView view;

  @override
  List<Object> get props => [view];
}
```

**app_bloc.dart**
```dart
class AppBloc extends Bloc<AppEvent, AppState> {
  AppBloc({required AuthenticationRepository authenticationRepository})
      : _authenticationRepository = authenticationRepository,
        super(
          authenticationRepository.currentUser.isNotEmpty
              ? AppState.authenticated(authenticationRepository.currentUser)
              : const AppState.unauthenticated(),
        ) {
    on<AppUserChanged>(_onUserChanged);
    on<AppLogoutRequested>(_onLogoutRequested);
    _userSubscription = _authenticationRepository.user.listen(
      (user) => add(AppUserChanged(user)),
    );
    on<AppViewChanged>(_onViewChanged);
  }

  final AuthenticationRepository _authenticationRepository;
  late final StreamSubscription<User> _userSubscription;

  void _onUserChanged(AppUserChanged event, Emitter<AppState> emit) {
    emit(
      event.user.isNotEmpty
          ? AppState.authenticated(event.user)
          : const AppState.unauthenticated(),
    );
  }

  void _onLogoutRequested(AppLogoutRequested event, Emitter<AppState> emit) {
    unawaited(_authenticationRepository.logOut());
  }

  @override
  Future<void> close() {
    _userSubscription.cancel();
    return super.close();
  }
}

void _onViewChanged(AppViewChanged event, Emitter<AppState> emit) {
  emit(
    AppState.currentView(AppStatus.authenticated, event.view),
    // AppView.currentView(event.view),
  );
}
```

**app_state.dart**
```dart
part of 'app_bloc.dart';

enum AppStatus {
  authenticated,
  unauthenticated,
}

enum CurrentView {
  login,
  home,
  first,
  second,
}

class AppState extends Equatable {
  const AppState._({
    required this.status,
    this.user = User.empty,
    this.view = CurrentView.home,
  });

  const AppState.authenticated(User user)
      : this._(status: AppStatus.authenticated, user: user);

  const AppState.unauthenticated() : this._(status: AppStatus.unauthenticated);

  const AppState.currentView(AppStatus status, CurrentView view)
      : this._(status: status, view: view);

  final AppStatus status;
  final User user;
  final CurrentView view;

  @override
  List<Object> get props => [status, user, view];
  // List<Object> get props => [status, user];
}
```

**navigationdrawer.dart**
```dart
class NavigationDrawer extends StatelessWidget {
  const NavigationDrawer({super.key});

  @override
  Widget build(BuildContext context) {
    return Drawer(
        child: ListView(
      padding: EdgeInsets.zero,
      children: <Widget>[
        drawerHeader(),
        drawerBodyItem(
          icon: Icons.home,
          text: 'Home',
          onTap: () => context
                .read<AppBloc>()
                .add(const AppViewChanged(CurrentView.home))),
        ),
        drawerBodyItem(
          icon: Icons.list,
          text: 'First',
          onTap: () => context
                .read<AppBloc>()
                .add(const AppViewChanged(CurrentView.first))),
        ),
        drawerBodyItem(
          icon: Icons.star,
          text: 'Second',
          onTap: () => context
                .read<AppBloc>()
                .add(const AppViewChanged(CurrentView.second))),
        ),
        const Divider(),
        drawerBodyItem(
          icon: Icons.settings,
          text: 'Settings',
          onTap: () {},
        ),
        ListTile(
          title: const Text('App version BETA'),
          onTap: () {},
        ),
      ],
    ));
  }
}
```

Below is my home page, which demonstrates that something is different, probably the `context`.  The avatar and name display correctly after successful authentication, but if you navigate to the home page using the button in the `NavigationDrawer`, `User` is `null`.

**homepage.dart**
```dart
class HomePage extends StatelessWidget {

  const HomePage({super.key});
  static Page<void> page() => const MaterialPage<void>(child: HomePage());

  @override
  Widget build(BuildContext context) {
    final user = context.select((AppBloc bloc) => bloc.state.user);
    print(user.toString());
    return Scaffold(
      appBar: AppBar(
        title: const Text('Home'),
      ),
      drawer: const NavigationDrawer(),
      body: Center(
        child: Column(
          children: [
            const SizedBox(height: 8),
            Avatar(photo: user.photo),
            const SizedBox(height: 4),
            Text(user.displayName!),
          ],
        ),
      ),
    );
  }
}
```

Again, thank you for Bloc.  I'm enjoying it so far.  :)

**Comment by Luci3b** [comment]
## The problem
I think you problem is in your `app_state.dart` file.  In your private unnamed constructor you are defining the following:
```dart
const AppState._({
    required this.status,
    this.user = User.empty,
    this.view = CurrentView.home,
  });
```

And when your authentication is successful you call 
```dart
const AppState.authenticated(User user)
      : this._(status: AppStatus.authenticated, user: user);
```
Then you user is not empty.

But in your `navigationdrawer.dart` file you are adding the event `AppViewChanged`, which return the state:
```dart
const AppState.currentView(AppStatus status, CurrentView view)
      : this._(status: status, view: view);
```

Note that you are not passing the user variable to the private unnamed constructor, so by default the user value is what you defined in your constructor: `this.user = User.empty`.

## Possible fixes

✅Using the **CopyWith** method:
```dart
enum AppStatus {
  authenticated,
  unauthenticated,
  unknown
}

enum CurrentView {
  login,
  home,
  first,
  second,
}

class AppState extends Equatable {
  const AppState({
    this.status = AppStatus.unknown,
    this.user = const User.empty(),
    this.view = CurrentView.home,
  });

  final AppStatus status;
  final User user;
  final CurrentView view;
  
  AppState copyWith({
    AppStatus? status,
    User? user,
    CurrentView? view,
  }) {
    return AppState(
      status: status ?? this.status,
      user: user ?? this.user,
      view: view ?? this.view,
    );
  }
  
  @override
  List<Object> get props => [status, user, view];
}
```

Here I used the `AppStatus.unknown` when the application doesn't know yet if the user is authenticated or not, so you can show a loading screen or anything else. Using copyWith your user will be persisted when you don't pass the user.

See more about the copyWith [here](https://developer.school/tutorials/dart-flutter-what-does-copywith-do).

Here you can find @felangel examples using copyWith:

- [Infinite list](https://bloclibrary.dev/#/flutterinfinitelisttutorial?id=post-states);
- [Weather](https://bloclibrary.dev/#/flutterweathertutorial?id=weather-model-2);
- [Todos](https://bloclibrary.dev/#/fluttertodostutorial?id=todosoverviewstate).

✅Fixing the `AppState.currentView` constructor:

```dart
enum AppStatus {
  authenticated,
  unauthenticated,
}

enum CurrentView {
  login,
  home,
  first,
  second,
}

class AppState extends Equatable {
  const AppState._({
    required this.status,
    this.user = User.empty,
    this.view = CurrentView.home,
  });

  const AppState.authenticated(User user)
      : this._(status: AppStatus.authenticated, user: user);

  const AppState.unauthenticated() : this._(status: AppStatus.unauthenticated);

  // Fixed constructor: Added the user variable
  const AppState.currentView(AppStatus status, User user, CurrentView view)
      : this._(status: status, user: user, view: view);

  final AppStatus status;
  final User user;
  final CurrentView view;

  @override
  List<Object> get props => [status, user, view];
}
```

**Comment by sirEgghead** [comment]
Good afternoon.  My apologies for not seeing this yet.  Give me a few hours to look this over and I'll test and respond.

**Comment by sirEgghead** [comment]
@Luci3b your second solution seemed to work for me.  I was having issues with the first solution.  I might head back to it at a later point and see if I can sort it out.

Your explanation of my problem completely makes sense and definitely narrowed down the issue for me.  Thank you so much for all you help, especially considering I opened my first question about this issue elsewhere on the web over a month ago.

I'm going to take this information and test it with my additional pages as well.  If there are any issues related directly to this solution, I'll bring them back here, but for now I'll close up this issue.

Thank you!!

**Comment by sirEgghead** [comment]
Since I am new to bloc, I'm sure that I will have many questions.  Where would be the best place for me to ask questions regarding bloc.  I don't think it is the best idea for me to open an issue here in order to learn.

For instance, my next step is to figure out how to create another bloc that contains a Firestore stream, and I want to get information from it.  I'm going to try to figure it out myself, and by using existing information, but I'm sure there will be something.

**Comment by felangel** [comment]
@sirEgghead you can direct these types of questions to the [bloc discord](https://discord.gg/bloc) 😄

**Comment by sirEgghead** [comment]
> @sirEgghead you can direct these types of questions to the [bloc discord](https://discord.gg/bloc) 😄

Perfect, thank you!!
