### ISSUE TITLE
Question: Technical Cubit vs GetXService

### ISSUE THREAD

**Issue by minhkimlong** [felangel/bloc#3590]
**Description**

Clearly describe what code needs to be changed and what the performance impact is going to be.

## What 
Hi team flutter bloc, sorry firstly because I don't see the right issue for creating
I have a question about cubit, like we know GetXService class will keep instances in the app, and we can update a screen and another screen will update too
 - For example, the setting screen will have a feature change avatar, if we go to the profile screen it will auto-update too
 
 So with cubit how can we do this?
  - Bloc to bloc communication stream, stream subscription?
  - Creating the bloc provider in the material app?
  
Can we have another better technical cubit to update sync data with another screen in an app, when a screen update data?

**Comment by felangel** [comment]
Hi @minhkimlong 👋
Thanks for opening an issue!

I recommend creating a UserRepository which you provide to the entire application using RepositoryProvider. The UserRepository can methods like updateAvatar and expose a Stream of user updates which multiple blocs can subscribe to:

```dart
class UserRepository {
  Stream<User> get user;
  Future<void> updateAvatar(Avatar avatar);
}
```

I recommend reading through the [architecture docs](https://bloclibrary.dev/#/architecture?id=connecting-blocs-through-domain) and checking out examples like the [todos example](https://bloclibrary.dev/#/fluttertodostutorial) which illustrate how multiple blocs can subscribe to the same repository.

Hope that helps! Feel free to comment if you have any follow up questions and I recommend joining the [bloc discord](https://discord.gg/bloc) if you haven’t already for these types of discussions 👍

**Comment by minhkimlong** [comment]
Thank you @felangel
