### ISSUE TITLE
Question: Excute Multiple Event Before Launch APP

### ISSUE THREAD

**Issue by mstfkhazaal** [felangel/bloc#3591]
I have a app when i run the app i need to excute multiple event in multiple bloc then launch first Page
I use **[FlutterNativeSplash](https://pub.dev/packages/flutter_native_splash)** to remain  splash screen while your app initializes ([More Details](https://pub.dev/packages/flutter_native_splash#3-set-up-app-initialization-optional))
I use [ Injectable](https://pub.dev/packages/injectable) for inject Blocs/Cubits & another operation

**Note:**
1- locator to access to Injectable Method 
2- I cannot convert bloc to cubit because i use **emit.foreach**

**Question:**
How can I perform all bloc events and then start the application?
**Main.dart**
```
Future<void> beforeLaunch() async {
  locator<BusinessBloc>().add(const BusinessGetList()); 
  locator<ClientBloc>().add(const GetListClient());
  locator<PaymentTypeBloc>().add(const GetListPymnt());
  locator<TermsBloc>().add(const GetListTerms());
  locator<TaxBloc>().add(const GetListTax());
  locator<SignatureBloc>().add(const GetListSign());
  locator<StampBloc>().add(const GetListStamp());
  locator<ItemsBloc>().add(const GetListItem());
  locator<ItemUnitBloc>().add(const GetListItemUnit());
  locator<BillBloc>().add(const GetListBill());
  locator<BillTypeBloc>().add(const GetListBillType());
  FlutterNativeSplash.remove(); // To Remove Splash Screen
}
Future<void> bootstrap() async {
  WidgetsFlutterBinding.ensureInitialized();
  final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  await configureDependencies();// Injectable with Get_IT ( Inject Bloc&Cubit and others operation)

  /// Hydrated Bloc
  final storageBloc = await HydratedStorage.build(
    storageDirectory: await getTemporaryDirectory(),
  );
  FlutterError.onError = (details) {
    log(details.exceptionAsString(), stackTrace: details.stack);
  };
  await beforeLaunch(); // Run Method Before launch app
  await HydratedBlocOverrides.runZoned(
    () async => runApp(
    AppView()
    ),
    blocObserver: AppBlocObserver(),
    storage: storageBloc,
  ).onError(
    (error, stackTrace) => log(error.toString(), stackTrace: stackTrace),
  );
}
```

**Comment by felangel** [comment]
Hi @mstfkhazaal 👋
Thanks for opening an issue!

I generally recommend delegating this type of logic to one or more repositories which you can instantiate/provide to the app via RepositoryProvider. Ideally blocs should manage the state of a single feature and should be provided/scoped to the feature.

Hope that helps 👍

**Comment by mstfkhazaal** [comment]
In my app every bloc is featured but in home screen i need to get all bloc in same time, 
Example:

**BusinessBloc**
```
@lazySingleton
class BusinessBloc extends Bloc<BusinessEvent, BusinessState> {
  BusinessBloc({
    required BusinessRepository businessRepository,
    required BusinessSelectCubit buSelect,
  })  : _businessRepository = businessRepository,
        _buSelect = buSelect,
        super(
          const BusinessState(),
        ) {
    on<BusinessGetList>(_onBusinessGetList);
    on<BusinessSelectEdit>(_onBusinessSelectEdit);
    on<BusinessTyping>(_onBusinessTyping);
    on<BusinessResetEdit>(_onBusinessResetEdit);
    on<BusinessEdit>(_onBusinessEdit);
    on<BusinessDelete>(_onBusinessDelete);
    on<BusinessAdd>(_onBusinessAdd);
  }
  final BusinessRepository _businessRepository;
  final BusinessSelectCubit _buSelect;
  Future<void> _onBusinessGetList(
    BusinessGetList event,
    Emitter<BusinessState> emit,
  ) async {
    emit(
      state.copyWith(
        status: () => BusinessStatus.loading,
      ),
    );
    await emit.forEach<List<Business>>(
      _businessRepository.watchBusiness(),
      onData: (businessList) => state.copyWith(
        // step: () => BusinessStep.showList,
        status: () => BusinessStatus.initial,
        businessList: () => businessList,
      ),
      onError: (ex, __) => state.copyWith(
        // step: () => BusinessStep.showList,
        status: () => BusinessStatus.failure,
        message: () => ex.toString(),
      ),
    );
  }
....
}
```

**Business State**

```
enum BusinessStatus {
  initial,
  loading,
  success,
  failure,
}

class BusinessState extends Equatable {
  const BusinessState({
    this.status = BusinessStatus.initial,
    this.businessList = const [],
    this.businessInitial,
    this.businessSelectable,
    this.message,
  });
  final BusinessStatus status;
  final List<Business> businessList;
  final BusinessesCompanion? businessInitial;
  final BusinessesCompanion? businessSelectable;
  final String? message;

  BusinessState copyWith({
    /// Progress
    BusinessStatus Function()? status,

    /// List
    List<Business> Function()? businessList,

    /// Add/Edit
    BusinessesCompanion? Function()? businessInitial,
    BusinessesCompanion? Function()? businessSelectable,

    /// If Error
    String? Function()? message,
  }) {
    return BusinessState(
      status: status != null ? status() : this.status,
      // step: step != null ? step() : this.step,
      businessList: businessList != null ? businessList() : this.businessList,
      businessInitial:
          businessInitial != null ? businessInitial() : this.businessInitial,
      message: message != null ? message() : this.message,
      businessSelectable: businessSelectable != null
          ? businessSelectable()
          : this.businessSelectable,
    );
  }

  @override
  List<Object?> get props => [
        status,
        businessList,
        businessInitial,
        businessSelectable,
        message,
      ];
}

```
Event **BusinessGetList**  task is to fetch data from sqlite   
All blocs have roughly the same template(GetList, SelectEdit,Typing,Add,Edit,Delete)

**Comment by Luci3b** [comment]
My suggestion is to call repositories futures and wait for them in the `main()` function.

Here's an example:

```dart
class Repository {
  final CacheClient _cache;
  final Api _api;

  const Repository({required CacheClient cache, required Api api})
      : _cache = cache,
        _api = api;

  Future<void> cacheDataList() async {
    final dataList = await _api.getDataList();

    await _cache.setDataList();
  }
}
```
And in the _main.dart_ we just make use of `Future.wait` and the possibility of calling `runApp()` again.

```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // You can call your FlutterNativeSplash.remove() here

  // Here we display a temporary page while app is setting up.
  // It can be a Splash Page or a simple Loading Page
  runApp(const MySplashPage());

  final cache = CacheClient();
  final api = Api();
  final repository = Repository(cache: cache, api: api);

  // Here you can put all your Futures, so you can wait them
  await Future.wait([
    repository.cacheDataList(),
    // Other repository async calls
  ]);

  // Here you call your app
  runApp(const MyApp());
}
```

So when you need to use your Bloc, your cache will be already updated !

**Comment by maximveksler** [comment]
> the possibility of calling `runApp()` again.

Great tip, thank you.

**Comment by felangel** [comment]
Closing for now since there are no actionable next steps. Feel free to comment with any follow up questions and I’m happy to continue the conversation 👍

**Comment by mstfkhazaal** [comment]
> My suggestion is to call repositories futures and wait for them in the `main()` function.
> 
> Here's an example:
> 
> ```dart
> class Repository {
>   final CacheClient _cache;
>   final Api _api;
> 
>   const Repository({required CacheClient cache, required Api api})
>       : _cache = cache,
>         _api = api;
> 
>   Future<void> cacheDataList() async {
>     final dataList = await _api.getDataList();
> 
>     await _cache.setDataList();
>   }
> }
> ```
> 
> And in the _main.dart_ we just make use of `Future.wait` and the possibility of calling `runApp()` again.
> 
> ```dart
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
> 
>   // You can call your FlutterNativeSplash.remove() here
> 
>   // Here we display a temporary page while app is setting up.
>   // It can be a Splash Page or a simple Loading Page
>   runApp(const MySplashPage());
> 
>   final cache = CacheClient();
>   final api = Api();
>   final repository = Repository(cache: cache, api: api);
> 
>   // Here you can put all your Futures, so you can wait them
>   await Future.wait([
>     repository.cacheDataList(),
>     // Other repository async calls
>   ]);
> 
>   // Here you call your app
>   runApp(const MyApp());
> }
> ```
> 
> So when you need to use your Bloc, your cache will be already updated !

Thanks, but i cant use the repository becuase all my data in on the bloc and it is on contimouse streaming

**Comment by felangel** [comment]
> Thanks, but i cant use the repository becuase all my data in on the bloc and it is on contimouse streaming

I highly recommend refactoring to move the data management into repositories and keep feature state management in blocs.

**Comment by mstfkhazaal** [comment]
> I highly recommend refactoring to move the data management into repositories and keep feature state management in blocs.

Do you have an project example?
