### ISSUE TITLE
Without rebuilding the entire list, want to just rebuild a single element on list.

### ISSUE THREAD

**Issue by goku-org** [felangel/bloc#3596]
**Goal:** without rebuilding the entire list, want to just rebuild a single element on list.
---
You can see in the Code below that I simply try to update a single Student value, which rebuild entire student list.

**What I really want?** 
I want to update an existing student value **without** rebuilding entire/complete student list and also want to show _realtime **State** of activate so that, user can know what happing_ (like, loading, error msg or finish task).

![image](https://user-images.githubusercontent.com/76699210/198293216-6dae5853-fdff-49de-9e84-9faa925cdc5c.png)

_**File: students_state.dart**_
```dart
part of 'students_bloc.dart';

enum InnerState { LOADING, COMPLETE }

abstract class StudentsState {
  const StudentsState();
}

class StudentsLoading extends StudentsState {}

class StudentsError extends StudentsState {
  final String msg;

  const StudentsError(this.msg);
}

class StudentsComplete extends StudentsState {
  final List<MapEntry<InnerState, Student>> students;

  const StudentsComplete(this.students);
}
```

_**File: students_event.dart**_

```dart
part of 'students_bloc.dart';

abstract class StudentsEvent extends Equatable {
  const StudentsEvent();

  @override
  List<Object> get props => [];
}

class StudentsFetched extends StudentsEvent {
  const StudentsFetched();
}

class EditByIndex extends StudentsEvent {
  final int index;
  final String? name;
  final int? totalSubjects;
  final bool? isMinor;
  const EditByIndex._(this.index,
      {this.name, this.totalSubjects, this.isMinor});

  const EditByIndex.name(int index, String name) : this._(index, name: name);

  const EditByIndex.totalSubjects(int index, int totalSubjects)
      : this._(index, totalSubjects: totalSubjects);

  const EditByIndex.isMinor(int index, bool isMinor)
      : this._(index, isMinor: isMinor);
}
```
**File: _students_bloc.dart_**

```dart
import 'dart:async';
import 'package:bloc/bloc.dart';
import 'package:bloc_complexity/model/student.dart';
import 'package:bloc_complexity/repo/data_repo.dart';
import 'package:equatable/equatable.dart';

part 'students_event.dart';
part 'students_state.dart';

class StudentsBloc extends Bloc<StudentsEvent, StudentsState> {
  final StudentDataRepo studentDataRepo;
  StudentsBloc(this.studentDataRepo) : super(StudentsLoading()) {
    on<StudentsFetched>(_onFetched);
    on<EditByIndex>(_onEdit);
  }

  FutureOr<void> _onFetched(event, Emitter<StudentsState> emit) async {
    var list = await studentDataRepo.fetchData();
    emit(StudentsComplete(
        list.map((e) => MapEntry(InnerState.COMPLETE, e)).toList()));
  }

  FutureOr<void> _onEdit(EditByIndex event, Emitter<StudentsState> emit) async {
    List<MapEntry<InnerState, Student>> elements =
        (state as StudentsComplete).students;

    if (state is StudentsComplete) {
      // 1st - change the state of [index] item form list
      elements[event.index] =
          MapEntry(InnerState.LOADING, elements[event.index].value);

      emit(StudentsComplete(elements));

      // 2st - wait for http request
      if (event.isMinor != null) {
        await studentDataRepo.changeMinorty(event.index, event.isMinor!);
      }
      if (event.name != null) {
        await studentDataRepo.changeStudentName(event.index, event.name!);
      }
      if (event.totalSubjects != null) {
        await studentDataRepo.changeTotalSubjects(
            event.index, event.totalSubjects!);
      }

      // 3st - change the state again.
      elements[event.index] = MapEntry(
          InnerState.COMPLETE,
          elements[event.index].value.copyWith(
              name: event.name,
              totalsubjects: event.totalSubjects,
              isMinor: event.isMinor));
      emit(StudentsComplete(elements));
    }
  }
}
```

**Expected Behavior**

```dart
class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  Widget build(BuildContext context) {
    StudentsState studentsState =
        context.select((StudentsBloc bloc) => bloc.state);
    return Scaffold(
      body: studentsState is StudentsComplete
          ? ListView.builder(
              itemCount: studentsState.students.length,
              itemBuilder: (context, index) {
                return Builder(builder: (context) {
                  var student =
                      (context.select((StudentsBloc bloc) => bloc.state)
                              as StudentsComplete)
                          .students[index];
                  return ListTile(
                    trailing: Row(
                      mainAxisSize: MainAxisSize.min,
                      children: [
                        const Text('Minor: '),
                        Switch(
                            value: student.value.isMinor,
                            onChanged: (bool value) => context
                                .read<StudentsBloc>()
                                .add(EditByIndex.isMinor(index, value)))
                      ],
                    ),
                    title: student.key == InnerState.LOADING
                        ? const LinearProgressIndicator()
                        : Text(student.value.name),
                    subtitle: Text(
                        'Rollno. ${student.value.rollno}  |  Minor:${student.value.isMinor}  |  Subjects ${student.value.totalsubjects}'),
                  );
                });
              },
            )
          : const Center(child: CircularProgressIndicator()),
    );
  }
}
```

**Screenshots**
![Untitled video - Made with Clipchamp](https://user-images.githubusercontent.com/76699210/198285938-be425f86-b15b-4754-8849-2be633efa06c.gif)

**Comment by acampuzanoo** [comment]
@goku-org what I can see at first glance is that even though you are updating the values of just one student, at the end you are still emitting the whole list as state. It does update the value for a given student, but at the expense of rebuilding the whole list. 

You should find an approach where each student object manages its own state separated from the state that manages the list, or only update the state of a given ID.

See here:

`return Scaffold(
      body: studentsState is StudentsComplete
          ? ListView.builder(
              itemCount: studentsState.students.length,
              itemBuilder: (context, index) {
                return Builder(builder: (context) {`

Whenever the StudentsComplete state is emitted, you are telling the UI to rebuild the whole list again.

**Comment by goku-org** [comment]
> @goku-org what I can see at first glance is that even though you are updating the values of just one student, at the end you are still emitting the whole list as state. It does update the value for a given student, but at the expense of rebuilding the whole list.
> 
> You should find an approach where each student object manages its own state separated from the state that manages the list, or only update the state of a given ID.
> 
> See here:
> 
> `return Scaffold( body: studentsState is StudentsComplete ? ListView.builder( itemCount: studentsState.students.length, itemBuilder: (context, index) { return Builder(builder: (context) {`
> 
> Whenever the StudentsComplete state is emitted, you are telling the UI to rebuild the whole list again.

Although I appreciate that you recognise the issue, I haven't yet found a solution.  If you have anything in your head, please explain.

**Comment by Gene-Dana** [comment]
@acampuzanoo has the right idea here. Generally speaking, you can instantiate a bloc/cubit for each individual element if you want granular control of each element.

I'm a little confused by this
```dart
final List<MapEntry<InnerState, Student>> students;
```
Why not have just a simpler `List<student>`?

Also instead of updating the student by index, I'd suggest an approach more like this
```dart
  final newList = state.students!.map((student) {
      return student.id == event.student.id ?  name: event.name,
              totalsubjects: event.totalSubjects,
              isMinor: event.isMinor : student;
    }).toList();

```

**Comment by goku-org** [comment]
@acampuzanoo 
@Gene-Dana 

Look at the problem instant first and simple solution come in the mind. Why not? using again bloc under the Students.
So, every student inside the studentsbloc will have their own bloc (like **StudentsBloc(List\<StudentState>) )**

After That Stil Problem Remain: inner bloc emit but outer bloc remain the old state.
👇👁️👁️👇

_**StudentBloc**_
![image](https://user-images.githubusercontent.com/76699210/198559878-d88b5e38-9cf9-4c95-a1ae-a219fe81725a.png)

_**StudentsBloc**_
![image](https://user-images.githubusercontent.com/76699210/198559409-a35f5b6d-405c-44db-91cb-e3675baf1a9f.png)

_**HomePage**_
````dart
class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  Widget build(BuildContext context) {
    StudentsState studentsState =
        context.select((StudentsBloc bloc) => bloc.state);
    return Scaffold(
      body: studentsState is StudentsComplete
          ? ListView.builder(
              shrinkWrap: true,
              itemCount: studentsState.students.length,
              itemBuilder: (context, index) {
                return CreateStudentTile(index, studentsState.students[index]);
              })
          : const Center(child: CircularProgressIndicator()),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
// printing data in Outerbloc (StudentsBoc)
          (studentsState as StudentsComplete)
              .students
              .sublist(0, 5)
              .forEach((e) => print((e as StudentComplete).student));
        },
        child: const Icon(Icons.print),
      ),
    );
  }
}

class CreateStudentTile extends StatelessWidget {
  final int index;
  final StudentState state;
  const CreateStudentTile(
    this.index,
    this.state, {
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    print('INNER---Build Student---');
    return BlocProvider(
      create: (context) => StudentBloc(StudentDataRepo())
        ..add(StudentAdd(state as StudentComplete)),
      child: Builder(builder: (context) {
        var studentstate = (context.select((StudentBloc bloc) => bloc.state));
        return studentstate is StudentComplete
            ? ListTile(
                trailing: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Text('Minor: '),
                    Switch(
                        value: studentstate.student.isMinor,
                        onChanged: (bool value) => context
                            .read<StudentBloc>()
                            .add(EditByIndex.isMinor(index, value)))
                  ],
                ),
                title: Text(studentstate.student.name),
                subtitle: Text(
                    'Rollno. ${studentstate.student.rollno}  |  Minor:${studentstate.student.isMinor}  |  Subjects ${studentstate.student.totalsubjects}'),
              )
            : const ListTile(
                title: LinearProgressIndicator(),
                subtitle: Text('Loading..'),
              );
      }),
    );
  }
}
````
**Output**
![2022-10-28 15-45-02](https://user-images.githubusercontent.com/76699210/198564471-96423859-f9e7-48ad-b2bf-8cbeb5009a25.gif)

**Comment by Gene-Dana** [comment]
Do you have a repo you can share?

**Comment by Gene-Dana** [comment]
Also, just to be clear you have two separate blocs? A `students bloc` and a `student bloc`?  I've never seen this approach before, and even if it's not the source of your problem I'd highly suggest refactoring your blocs into features.

You can see this clearly in the firebase auth example - there is a signup, a login, a home feature - and these all come from the domain of the auth repo.

If you can share a repo, I can make better make some suggestions

**Comment by goku-org** [comment]
> Do you have a repo you can share?

https://github.com/goku-org/Bloc_complexity

**Comment by zippka224** [comment]
@goku-org Don't do single Bloc/Cubit instance per CreateStudentTile widget. One Bloc/Cubit is better and it really doesn't matter that you are updating the whole list.

**Comment by goku-org** [comment]
> @goku-org Don't do single Bloc/Cubit instance per CreateStudentTile widget. One Bloc/Cubit is better and it really doesn't matter that you are updating the whole list.

Well I know that it don't effect, but it a just task or challenge for me in which I fail. perhaps i see other developer also fail too.

**Comment by Gene-Dana** [comment]
@goku-org I choose to believe that these limitations are just limits in my own understanding. 

There are a few things that I see here that I'd suggest changes to (like `List<Student>` instead of `List<StudentState>`) but I think we need to take a step back to refactor into a features.

In doing so, I believe we'll greatly simplify your state.

If you can brief me on what you're trying to achieve, I can help you architect it.

Do you have any designs/wireframes?

**Comment by zippka224** [comment]
@Gene-Dana From what I'm understanding, he is concerned with the list rebuilding in case there was an update to only one object inside that list. 
What I'm saying is that it doesn't matter that much. It is only few items visible that are rebuilding and it would not cause any performance hits.

**Comment by Gene-Dana** [comment]
> What I'm saying is that it doesn't matter that much. It is only few items visible that are rebuilding and it would not cause any performance hits.

This I agree with, and I've come to realize that most of the time when someone has concerns like this - things that may seem obvious to us - it's because of a much deeper misunderstanding of Bloc and it's suggested approach.

After reviewing this code, it's very clear there are many misunderstandings! And I'm just helping solve the only way I know how - starting from the start.

When @felangel spent the time and did this for me, I began to truly understand it, and I think users like this just need a little more help to help them 'see the light' too
