### ISSUE TITLE
QUESTION: Testing events and states 

### ISSUE THREAD

**Issue by jandrop** [felangel/bloc#3597]
**Description**

I'm really interested in this test that is in the examples. I think all the tests related to events and states are only checking if the class is extending equatable, Am I right? But what should happen if I don't implement the event and state tests in my project, what are the benefits of testing these? 

        import 'package:authentication_repository/authentication_repository.dart';
        import 'package:flutter_login/authentication/authentication.dart';
        import 'package:flutter_test/flutter_test.dart';
        
        void main() {
          group('AuthenticationEvent', () {
            group('LoggedOut', () {
              test('supports value comparisons', () {
                expect(
                  AuthenticationLogoutRequested(),
                  AuthenticationLogoutRequested(),
                );
              });
            });
        
            group('AuthenticationStatusChanged', () {
              test('supports value comparisons', () {
                expect(
                  AuthenticationStatusChanged(AuthenticationStatus.unknown),
                  AuthenticationStatusChanged(AuthenticationStatus.unknown),
                );
              });
            });
          });
        }

**Comment by felangel** [comment]
Hi @jandrop 👋 
Thanks for opening an issue!

These tests are there to ensure that the events support value comparisons. If you remove equatable, for example, these tests will fail. Hope that helps!
