### ISSUE TITLE
docs: For state status using Enum

### ISSUE THREAD

**Issue by hew999** [felangel/bloc#3598]
Hi everyone, I am wondering it's okay to create a common enum state status for most my bloc api call class use?
Example:
`enum StateStatus { init, loading, success, failure, empty, error}` 

Since many of my API blocs using same status. Instead each bloc create their bloc state status, can I create a shared enum status for all? Is there any issues?

**Comment by felangel** [comment]
Hi @hew999 👋 
Thanks for opening an issue!

If the status is generic and makes sense to apply across multiple states then feel free 👍
