### ISSUE TITLE
What should i return when an unknown state is passed to the builder callback?

### ISSUE THREAD

**Issue by nerder** [felangel/bloc#360]
In a typical `BlocBuilder` implementation what should i return when an unknown state is passed?

```dart
BlocBuilder(
            bloc: _userBloc,
            builder: (BuildContext context, UserState state) {
              if (state is UserLoading) {
                return LoadingIndicator();
              }

              if (state is UserSuccess) {
                return LessonsPage(userBloc: _userBloc,);
              }
        })
```

The new `master` channel of `flutter` now the `flutter analyse` raise an issue if the callback have no return, what should i return in this case?

**Comment by felangel** [comment]
Hi @nerder 👋 
Thanks for opening an issue and great question!

It's totally up to you, but a couple of options are:

- use `if/else if/else instead of just `if`
- return a `Container()`
- switch on `state.runtimeType` instead of checking if `state is Type`

Hope that helps 👍

**Comment by nerder** [comment]
I don't even see how an unknown state might be passed since i'm the one defining them 🤣but at static code analysis it makes sense to complain 😄 

i like the `ErrorWidget` approach, because it mean that i forget to implement a UI for a possible state, so i want it to fail fast.

Thank you for your fast reply
