### ISSUE TITLE
BlocTest fails when bloc event handler method throws exception

### ISSUE THREAD

**Issue by chris-turner-datacom** [felangel/bloc#3618]
Hi there! Hopefully someone can help me with this. Let's say I have a bloc:

```
class MyBloc extends Bloc<MyEvent, MyState>{
   MyBloc({required super.initialState}){
      on<MyEventImpl>(_throwError);
   }

   void _throwError(MyEventImpl event, Emitter<MyState>){
      throw Error();
   }
}
```

If I write the following unit test:
```
void main(){
   group('MyBloc', (){
      late MyBloc myBloc;

      setUp((){
         myBloc = MyBloc(initialState: MyStateInitImpl());
      });

      blocTest('Throws Error when MyEventImpl called',
         build: () => myBloc,
         act: (MyBloc bloc) => bloc.add(const MyEventImpl()),
         errors: () => [isA<Error>()]);
   }
}
```
The test fails saying an Error was thrown. But that was kind of the point, I was trying to verify that an error was thrown in that particular circumstance. Interestingly, if I replace the act with:

```
act: (MyBloc bloc) => throw Error();
```
The test passes fine. Can anyone explain what is happening or if I am going wrong with this somewhere?

Thanks so much!

**Comment by AdamNSmith** [comment]
I'm also experiencing this. Any ideas?

**Comment by TheGlorySaint** [comment]
I'm also experiencing this.

@felangel Could you give us a explanation about that issue?

**Comment by felangel** [comment]
You should call `addError` instead of throwing in the bloc.

```dart
class MyBloc extends Bloc<MyEvent, MyState>{
   MyBloc({required super.initialState}){
      on<MyEventImpl>(_throwError);
   }

   void _throwError(MyEventImpl event, Emitter<MyState>){
      addError(Error());
   }
}
```

Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now since there aren’t any actionable next steps. Feel free to comment with any follow ups and I’m happy to continue the conversation 👍
