### ISSUE TITLE
build: i want to change state with out emit

### ISSUE THREAD

**Issue by ATHUL3120** [felangel/bloc#3621]
i want to change state with out emit

**Comment by felangel** [comment]
Hi @ATHUL3120 👋 
Thanks for opening an issue!

Emitting new states to notify listeners is a fundamental part of the bloc library. It's analogous to using `setState` to rebuild your widget when you mutate some state. Closing for now but feel free to provide additional context regarding why you want to change state without using `emit` and I'm happy to continue the conversation 👍
