### ISSUE TITLE
docs: Clicking bloc button in contents directs me to en-us

### ISSUE THREAD

**Issue by Coaspe** [felangel/bloc#3629]
I have completed the translation of [Core Concepts -> package:bloc] into Korean
But clicking bloc button in contents directs me to en-us.
How can I contribute my translation?

![Nov-16-2022 18-36-38](https://user-images.githubusercontent.com/76432686/202145587-118586fb-8d6c-4cca-ad0b-bc3ab3b6dff5.gif)

**Comment by felangel** [comment]
Hi @Coaspe 👋 
Thanks for opening an issue!

Can you open a pull request and I'm happy to take a look and help fix the issue, thanks!
