### ISSUE TITLE
docs: Does bloc inherit all Provider issues?

### ISSUE THREAD

**Issue by jacob-emery** [felangel/bloc#3638]
**Description**

I had a brief look at your library, and — since provider is a dependency — I am wondering if there are issues of provider that your library fixes. For example, is it possible to have multiple instances of the same provider type?

**Comment by felangel** [comment]
Hi @jacob-emery 👋 
Thanks for opening an issue!

Since BlocProvider extends Provider, it is functionally equivalent.
