### ISSUE TITLE
Login Tutorial - Is this an error?

### ISSUE THREAD

**Issue by oravecz** [felangel/bloc#3639]
I was noticing the `authentication_bloc.dart` file contains code invoked to close the bloc. In this code, is a class to `dispose()` the repository.

```dart
  @override
  Future<void> close() {
    _authenticationStatusSubscription.cancel();
    _authenticationRepository.dispose();
    return super.close();
  }
```

It seems odd to me to make such a lifecycle call on a dependent object when the Bloc is not responsible for creating the `AuthenticationRepository` in the first place.

**Comment by felangel** [comment]
Hi @oravecz 👋 
Thanks for opening an issue!

Yeah I agree we shouldn't be disposing the AuthenticationRepository here since the bloc is not responsible for instantiating the repository. Feel free to open a pull request with a fix, thanks! 🙏

**Comment by bensonarafat** [comment]
I can open a pull request with a fix..

**Comment by bensonarafat** [comment]
I've opened a pull request and fix🚀

**Comment by tenhobi** [comment]
Just a reminder that this has been merged in https://github.com/felangel/bloc/pull/3681 and therefore can be closed. 👍
