### ISSUE TITLE
The non-abstract class 'BlocBuilder' is missing implementations for these members

### ISSUE THREAD

**Issue by KHChanna** [felangel/bloc#3640]
**The non-abstract class 'BlocBuilder' is missing implementations for these members**

Hi, i get this error when i update the `pubspec.yaml` using command line `flutter pub get`. 
flutter_bloc : flutter_bloc: ^8.1.1

`Error: Expected a class member, but got '}'.
../…/src/bloc_builder.dart:90
}
^
: Error: The non-abstract class 'BlocBuilder' is missing implementations for these members:
../…/src/bloc_builder.dart:72
 - BlocBuilderBase.build
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or

 - provide a 'noSuchMethod' implementation.

class BlocBuilder<B extends StateStreamable<S>, S>
      ^^^^^^^^^^^
Context: 'BlocBuilderBase.build' is defined here.
../…/src/bloc_builder.dart:115
  Widget build(BuildContext context, S state);
         ^^^^^
3
`

Thank you.

**Comment by felangel** [comment]
Hi @KHChanna 👋
I’m guessing you accidentally modified the bloc source code in your pub cache. I recommend clearing your pub cache and reinstalling the package. Let me know if the issue persists, thanks!
