### ISSUE TITLE
Sharing blocs

### ISSUE THREAD

**Issue by jtdLab** [felangel/bloc#3641]
Hi thanks for the great library.

I got a question related to sharing code when using bloc.

Let's imagine there is an app for desktop and mobile which got a feature. On mobile the feature is very basic. On desktop the same feature is more complex with additional functionality. That said what is the correct path to go from here. Either implementing 1  platform independent `Bloc` or 2 platform dependent `Bloc`s. Should `Bloc`s be platform independent or not in general ?

**Comment by tenhobi** [comment]
Hi @jtdLab, that really depends on the specific use case of the feature. I would say that Blocs should not be tight to UI layer if possible, therefore you could use only one `Bloc` where you would not use some events or even disable mappers according to some boolean that distinguishes "simple" and "advanced" modes.

Depending on how sophisticated the bloc would be, one can even split it into two. Or one can make some common (maybe abstract or mobile) version of the bloc and the other one/s would extend that with additional features.

It really is "it depends" situation. 😅

**Comment by tenhobi** [comment]
Hey @jtdLab, do you have any additional things to this issue? Otherwise, it can be closed.
