### ISSUE TITLE
docs: Consider explicitly stating that all Bloc / Cubit public methods should return void

### ISSUE THREAD

**Issue by PawlikMichal25** [felangel/bloc#3645]
Recently, I saw in some projects developers adding to Bloc/Cubit some getters or other methods returning data to quickly check a flag or process some data, instead of having UI getting data from Bloc **_only_** through state, which I believe is the contract which we should have in Bloc.

so @felangel I wanted to ask whether you agree that:
- All _public and non-static_ methods in Bloc/Cubit should always return `void` or `Future<void>` ?
- If yes, then perhaps this explicit information should also be added to docs for clarity?

**Comment by felangel** [comment]
Hi @PawlikMichal25 👋 
Thanks for opening an issue!

Yeah I generally recommend:

- Blocs do not expose public methods
- Cubits only expose public methods that return `Future<void>` or `void` for the purposes of emitting new states.

Happy to update the docs to make this recommendation a bit more explicit 👍
