### ISSUE TITLE
BlocListener in Stateless Widget check for deactivated widget fix: 

### ISSUE THREAD

**Issue by harsh8088** [felangel/bloc#3646]
**Description**
How to check for the deactivated widget in BlocListener for StatelessWidget.

**Steps To Reproduce**

1. See error  'To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4241:9)
Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4255:6)
Element.findAncestorWidgetOfExactType (package:flutter/src/widgets/framework.dart:4312:12)
debugCheckHasScaffoldMessenger.<anonymous closure> (package:flutter/src/material/debug.dart:150:17)
debugCheckHasScaffoldMessenger (package:flutter/src/material/debug.dart:162:4)
ScaffoldMessenger.of (package:flutter/src/material/scaffold.dart:146:12)

**Expected Behavior**
<img width="686" alt="Screenshot 2022-12-02 at 12 46 09 PM" src="https://user-images.githubusercontent.com/7496696/205236883-507afaa4-ebd2-462c-960c-611759079a4e.png">

**Additional Context**
Need logic, check if the widget is mounted before showing the ScaffoldMessenger.
Code feedback and suggestions are welcomed. 🙏

**Comment by felangel** [comment]
You can check if a widget is mounted by checking the `mounted` property in your `State` class. See https://api.flutter.dev/flutter/widgets/State/mounted.html for more info.

Closing for now but feel free to comment with any additional comments/questions and I'm happy to continue the conversation 👍
