### ISSUE TITLE
Do local variable BloC's need to be disposed of explicitly?

### ISSUE THREAD

**Issue by MilesAdamson** [felangel/bloc#365]
I have looked through the examples and can't find an example where a BloC is a local variable, which goes out of scope at some point. It seems as though these bloc's do not get their dispose method called, which makes me worry I have a memory leak where they are never cleaned up until the app gets closed.

Say for example you had a stateful widget which has a BloC as a local variable. In that widgets dispose method do you need to call dispose on the bloc, or do these blocs get disposed of behind the scenes automatically?

```
class MyWidget extends StatefulWidget {
  @override
  State<MyWidget> createState() => MyWidgetState();
}

class MyWidgetState extends State<MyWidget> {
  MyBloc myBloc = MyBloc();
  
  @override
  Widget build(BuildContext context) {
    return Text(myBloc.currentState.toString());
  }
  
  @override
  void dispose() {
// Do I need to call this for every BloC which doesn't live for the app's entire life?
    myBloc.dispose(); 
    super.dispose();
  }
}

class MyBloc extends Bloc<int, int>{
  @override
  int get initialState => 1;
  
  @override
  Stream<int> mapEventToState(int event) async* {
    yield event;
  }
}

**Comment by felangel** [comment]
Hi @MilesAdamson 👋 
Thanks for opening an issue!

If you're using the  `flutter_bloc v0.17.0` (all examples always use the latest), then `BlocProvider` automatically disposes the bloc for you.

You would be able to go from:
```dart
class MyApp extends StatefulWidget {
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  MyBloc _myBloc;
  
  @override
  initState() {
    super.initState();
    _myBloc = MyBloc();
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      bloc: _myBloc,
      child: MyPage(),
    );
  }

  @override
  dispose() {
    _myBloc.dispose();
    super.dispose();
  }
}
```

to

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      builder: (BuildContext context) => MyBloc(),
      child: MyPage(),
    );
  }
}
```

In older versions of `flutter_bloc`, it's up to the developer to dispose each bloc.

Hope that helps and great question! 👍
