### ISSUE TITLE
fix: authentication_repository test failing

### ISSUE THREAD

**Issue by maximveksler** [felangel/bloc#3651]
**Description**

`examples/flutter_firebase_login/packages/authentication_repository/test/authentication_repository_test.dart` tests are failing on master.

**Steps To Reproduce**

```bash
m@m-inspiron5567:~/code/pr/bloc/examples/flutter_firebase_login/packages/authentication_repository$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

m@m-inspiron5567:~/code/pr/bloc/examples/flutter_firebase_login/packages/authentication_repository$ git log -n 1
commit be0bd8f8c729a52e5449f3107b5a80d2227814ea (HEAD -> master, origin/master, origin/HEAD, max-version-bump-auth-repo2)
Author: Felix Angelov <felangelov@gmail.com>
Date:   Mon Dec 5 21:14:50 2022 -0600

    chore(intellij): v3.4.0 (#3650)

$ flutter test
```

**Expected Behavior**

Tests should pass, clearly.

**Actual**

Tests are failing with 

```
Bad state: A test tried to use `any` or `captureAny` on a parameter of type `AuthProvider`, but
  registerFallbackValue was not previously called to register a fallback value for `AuthProvider`.
``` 

See full log here https://gist.github.com/maximveksler/89c200b4407071142806c386414fd6f3

<code>

**Additional Context**

```
m@m-inspiron5567:~/code/pr/bloc/examples/flutter_firebase_login/packages/authentication_repository$ flutter --version
Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (2 weeks ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0
m@m-inspiron5567:~/code/pr/bloc/examples/flutter_firebase_login/packages/authentication_repository$ dart --version
Dart SDK version: 2.18.5 (stable) (Tue Nov 22 15:47:29 2022 +0000) on "linux_x64"
```

**Comment by felangel** [comment]
Hi @maximveksler 👋 
Thanks for opening an issue!

Based on the error, I'm guessing you're not registering a fallback value as mentioned in the error:

```dart
class _FakeAuthProvider extends AuthProvider implements Fake {}

void main() {
  setUpAll(() {
    registerFallbackValue(_FakeAuthProvider());
  });
}
```

Let me know if that helps 👍

**Comment by maximveksler** [comment]
@felangel you're 100%, only that the problem is from `bloc/examples/flutter-firebase-login`. 

I'd suggest adding the `bug` label, and kindly review / approve PR https://github.com/felangel/bloc/pull/3654

Side notes

1. I wonder why it didn't pop in the automation unit tests?
2. While working on a fig I've discovered why seems like a bug in `pub` related to the order in why packages are added. https://github.com/dart-lang/pub/issues/3685
