### ISSUE TITLE
ci: migration codecov v1 to v3

### ISSUE THREAD

**Issue by SuhwanCha** [felangel/bloc#3652]
https://github.com/codecov/codecov-action

Codecov@v1 deprecated on February 1, 2022.

How about migrate `codecov/codecov-action@v1 ` to `codecov/codecov-action@v3`?

https://github.com/felangel/bloc/blob/be0bd8f8c729a52e5449f3107b5a80d2227814ea/.github/workflows/bloc.yaml#L45-L48

**Comment by SaumyaBhushan** [comment]
Hi @SuhwanCha Can I work on this issue?

**Comment by SuhwanCha** [comment]
Hi @SaumyaBhushan,
I think we need @felangel 's approval

**Comment by maximveksler** [comment]
> Hi @SaumyaBhushan, I think we need @felangel 's approval

Submit the pull requetst. Approval is easy once it's working.
