### ISSUE TITLE
feat: can we use same bloc for multiple screen ? The emit state changes will affect all screen ?

### ISSUE THREAD

**Issue by jotheeswari** [felangel/bloc#3653]
**Description**

**Desired Solution**

**Alternatives Considered**

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by felangel** [comment]
Hi @jotheeswari 👋
Thanks for opening an issue!

Yeah, as long as you’ve provided the bloc correctly, state changes in a bloc/cubit will affect multiple pages/screens 👍
