### ISSUE TITLE
feat(bloc_test): function support in expect

### ISSUE THREAD

**Issue by SuhwanCha** [felangel/bloc#3657]
**Description**

https://github.com/felangel/bloc/blob/76d76ac7b35baf4f29d3494e59d32bada7b7cd2e/examples/flutter_infinite_list/test/posts/bloc/post_bloc_test.dart#L129-L153

When I test bloc state, I should extends Equatable to check state equality.
But, in some cases, I'd like to compare shallow, not deep.
We can use `isA<T>()` matcher to check type of state, but I want to check some properties of state.
For example of source code below, it define `mockPosts` to test.

But sometimes, it would be better to check only number of `posts` or something,
because compare every proerties of `state` takes long time to implement test cases, and it's not necessary sometimes.

**Desired Solution**

```dart
   expect: (bloc) => const <PostState>[ 
      () => (bloc.state.state is PostStatus.success && bloc.state.posts.length == 1)
   ], 
```

**Alternatives Considered**

Non mocktail object can be used in `vertify` to verify state.

**Additional Context**

In my project, I'd like to check not every property in state, but check number of `List` in state.
Because check every property would be awesome and perfact, but it takes too much time to implement test code,
and we don't have enough time to implement test code.

So, I think checking number of `List` in state is enough to check state is changed or not.

**Comment by felangel** [comment]
Hi @SuhwanCha 👋 
Thanks for opening an issue!

You can write your own matcher to check whatever properties you want and reuse that matcher in multiple tests. For example:

```dart
Matcher postLengthIs(int length) {
  return isA<PostState>().predicate((s) {
    return s.state is PostStatus.success && s.posts.length == length;
  });
}

blocTest(
  ...
  expect: () => [postLengthIs(1)]
)
```

At the end of the day expect just expects a `Matcher` so you can use any matchers or create your own.

Closing for now but feel free to comment if you have additional questions/comments and I'm happy to continue the conversation 👍
