### ISSUE TITLE
fix: Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by Naveed-dev30** [felangel/bloc#3659]
**Description**
I am writing bloc tests inside a group. I have called setUpAll and initialized the bloc. The first testBloc runs successfully. But once the bloc test after it runs, it throws error.

Bad state: Cannot add new events after calling close
dart:async                                                        _BroadcastStreamController.add
package:bloc/src/bloc.dart 99:24                                  Bloc.add
test/app/features/splash/splash_bloc/splash_bloc_test.dart 55:27  main.<fn>.<fn>
package:bloc_test/src/bloc_test.dart 208:20

Kindly guide how to initialise the data or bloc for all bloc tests.

**Comment by felangel** [comment]
Hi @Naveed-dev30 👋
Thanks for opening an issue!

blocTest automatically closes the bloc so you will need to create a new bloc in setUp. Hope that helps!

**Comment by Naveed-dev30** [comment]
So if I am writing 10 - 20 bloc tests in a group. I need to open bloc everytime with all dependencies it requires in setUp?

**Comment by Naveed-dev30** [comment]
Also in that case it throws Already Initialised exception. I can't find a way to run all tests in a single go

**Comment by felangel** [comment]
Check out existing test examples like https://github.com/felangel/bloc/blob/master/examples/flutter_todos/test/todos_overview/bloc/todos_overview_bloc_test.dart

**Comment by Naveed-dev30** [comment]
TodosOverviewBloc buildBloc() {
      return TodosOverviewBloc(todosRepository: todosRepository);
    }
    
    Creating new bloc everytime in bloc in build method solved this. Thank you @felangel
