### ISSUE TITLE
feat: BlocProvider.maybeOf(context) or BlocProvider.of<Bloc?>(context)

### ISSUE THREAD

**Issue by pedropimont** [felangel/bloc#3661]
Hi,

I'm currently unable to find an easy way (other than using a try catch block which is a little verbose) to verify if a Bloc is exposed within a certain Widget tree.

I thought that an API like BlocProvider.maybeOf(context) would be nice since other Inherited Widgets on the Flutter SDK use this API to return null instead of trowing an error when they don't find the ancestor Widget in the Widget Tree.

Another option (that became possible since Provider 6.0.0) is BlocProvider.of<Bloc?>(context), since Provider.of<T?>(context) is valid syntax and works as expected [Provider Issue #235](https://github.com/rrousselGit/provider/issues/235#issuecomment-981159300)

**Comment by diegotori** [comment]
@pedropimont, you can already do that by calling:

```dart
context.read<SomeMaybeBloc?>()
```

Since that will make it null-safe if it's not found on your tree.
