### ISSUE TITLE
fix: Ignore emit to closed stream in release mode

### ISSUE THREAD

**Issue by m7mdra** [felangel/bloc#3668]
When called emit on closed stream it throws an exception.
I propose to throw an error in debug mode only while it should be ignored in release.
it should be something like this

```  dart
import 'package:meta/meta.dart';
 
@protected
@visibleForTesting
@override
void emit(State state) {
  try {
    if (isClosed) {
      if (kDebugMode) {
        throw StateError('Cannot emit new states after calling close');
      }
      return;
    }
    if (state == _state && _emitted) return;
    onChange(Change<State>(currentState: this.state, nextState: state));
    _state = state;
    _stateController.add(_state);
    _emitted = true;
  } catch (error, stackTrace) {
    onError(error, stackTrace);
    rethrow;
  }
}

```

i managed to fix it temporally by:

```dart

  @override
  void emit(State state) {
    if (!isClosed) super.emit(state);
  }

```

**Comment by felangel** [comment]
Hi @m7mdra 👋 
Thanks for opening an issue!

This behavior is consistent with existing behavior (e.g.`StreamController`). Unless there's a really good reason to have different behavior in debug vs release mode I prefer not to make this change. In general, calling `emit` after the bloc has been closed should always be considered an error imo.

**Comment by m7mdra** [comment]
> calling emit after the bloc has been closed should always be considered an error imo.

ok thanks for following up. 

will close this for now.
