### ISSUE TITLE
feat: ability to override a bloc/cubit/repository in the tree.

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [felangel/bloc#3671]
**Description**

It is frustrating that I have to split code to multiple parts to get around the fact that I can't just override a bloc provider.
Sometimes in testing, it makes that testing task a nightmare and the code untestable.

I think this is one missing feature that will make the life of a lot of developers including me, you and everybody easier.

**Desired Solution**

A BlocOverrides/RepositoryOverrides widget that overrides any Bloc/Repository in the tree under it. Something similar to how ProviderScope works.

**Alternatives Considered**

I tried splitting the providing code to a separate widget and the ui code in a different widget but that does not work for example when testing a bottom sheet opening from another screen since i use the widget that has bloc provider.

**Comment by felangel** [comment]
Hi @YazeedAlKhalaf 👋 
Thanks for opening an issue!

`BlocProvider` and `RepositoryProvider` rely on `package:provider`. This sounds like a feature request for `package:provider` and I highly recommend moving this issue to the provider GitHub repository. Let me know what you think, thanks!

**Comment by YazeedAlKhalaf** [comment]
why don't we migrate to riverpod in a breaking version?

**Comment by felangel** [comment]
> why don't we migrate to riverpod in a breaking version?

See https://github.com/felangel/bloc/issues/2100.

Closing for now since there are no actionable next steps on the bloc repo here.
