### ISSUE TITLE
Bloc state data retaining for all pages

### ISSUE THREAD

**Issue by rahuloexe** [felangel/bloc#3676]
@felangel  Please Help.
Hello Team,
I am new to bloc architecture.
I want to achieve this while pushing the same screen again and again in the navigation stack. Each page has a list of different data. Currently what is happening topmost screen data is showing on all previous screens while popping.
I want to achieve this with the bloc.
Please guide me here
Thanks.

**Comment by brenno3b** [comment]
Can you share a minimum reproducible example ?

**Comment by rahul-newgen** [comment]
> Can you share a minimum reproducible example ?

Hello @brenno3b 
Here is reference video from google drive.
https://drive.google.com/file/d/12-b21mTybjt0dyS6nMvHMdtDfW8OElvB/view
I managed to do this with stateful widget states.
but with bloc states , list got overridden with the latest data on previous pages also.

**Comment by felangel** [comment]
@rahuloexe can you please provide a link to a GitHub repo or DartPad that contains a minimum reproduction sample? Thanks!

**Comment by rahuloexe** [comment]
@felangel @brenno3b 
Thanks, Issue is resolved by creating a new bloc instance for the new screen pushed.
