### ISSUE TITLE
Question/Feature: Is it possible to eliminate the redundant emit(newState) within the `on<Event>(...)`

### ISSUE THREAD

**Issue by dinbtechit** [felangel/bloc#3682]
Is it possible to eliminate the redundant emit(newState) within the `on<Event>(...)`?

I am not sure how far this is feasible but taking some inspiration from [NGXS]https://www.ngxs.io/concepts/intro) to reduce some boilerplate. 

### **Pseudo Code.**

**Events:**
```dart
class LoadingEvent extends MyEvent { }
class AddDataEvent extends MyEvent { 
  const AddDataEvent({required String this.key, required String this.payload});
  final String key;
  final String payload;
}
class DeleteDataEvent extends MyEvent {
  const DeleteDataEvent({required String this.key});
  final String key;
 }
```
**State**
```dart
class MyState {
  final bool isLoading;
  final Map<String, String>  data;
  const MyState({required this.isLoading, required this.data});

  MyState patch({            // <---- This patch method is just a fancy name for copyWith.
    bool? isLoading,        
    Map<String, String>? data,  
  }) {                                            
    return MyState(
      isLoading: isLoading ?? this.isLoading,
      data: data ?? this.data,
    );
  }
}
```
 > The `patch` method is just a fancy name for `copyWith` method most IDEs can auto generate this. But once we have static MetaProgramming (dart 3) this is something that can be automatically generated.

**Desired Bloc:**
```dart
class MyBloc extends Bloc<MyEvent, MyState> {

  MyBloc(): super(const MyState()) {
      on<AddDataEvent, MyState>(event, emit) {
         state.patch(
               isLoading: true
           );
          // pretend we called a backend API.
          state.patch(
               isLoading: false,
               data: {"ID1": "some data we received from backend"}
           );             
       }

  }

}
```
**Current Bloc**

Currently, we have to call the `emit()` to set the state. The `emit(...)` call is a bit redundant. It would be nice if bloc can automatically update the state when you do a `state.patch`

```dart
class MyBloc extends Bloc<MyEvent, MyState> {

  MyBloc(): super(const MyState()) {
      on<AddDataEvent>(event, emit) {
          emit(        // <----------------
            state.patch(
               isLoading: true
             )
          );

          // pretend we called a backend API.

          emit(           // <----------------
             state.patch(
                isLoading: false,
                data: {"ID1": "some data we received from backend"}
             )
           )             
       }

  }
}
```

**Comment by Shamsudeen12** [comment]
I feel the emit keyword is also important for readability, or don't you think?

**Comment by tenhobi** [comment]
Hi @dinbtechit, 

I do not think that is possible with current Dart. For that to work, you would need to wrap state in some box, that would expose the `state.value` getter (similar to `ValueNotifier`). Then you would have to expose `state.patch`, which would need to have all the parameters, if any, as your state's constructor (what if you have more ways of updating state?). Meaning something like `state.patch(isLoading: false)` would have to be possible, but state is now not your state but some `StateWrapper`. As you can see, you would end up with something like `state.patch(state.value.copyWith(...))`, which is more less the same like `emit(state.copyWith(...))`.

Another way would be to force all the states to implement some interface that would force accepting a bloc reference and exposing `patch` method, but again, the parameters would have to differ or the state itself would have to know how to change itself and call `blocReference.emit(...)` inside of state, which is putting way to much attention inside to states.

It would be maybe doable with generating code, but I assume avoiding `emit()` in cost of generators is not worth it. So yea, maybe future metaprogramming feature would allow us to do some nice APIs like that, we will see. 🙏

**Comment by dinbtechit** [comment]
@tenhobi - Totally makes sense. I think metaprogramming is the holy grail for all of the redudant code. I can't wait for Dart 3.

As you stated `emit` makes more sense. Closing this issue.
