### ISSUE TITLE
[Design Question] Minimal main.dart file

### ISSUE THREAD

**Issue by anoop-b** [felangel/bloc#369]
1) How do I separate the ui part from main.dart file while still maintaining bloc pattern?
2) How can I keep the main.dart file as minimal as possible (ideally) ?

**Comment by felangel** [comment]
Hi @anoop-b 👋 
Thanks for opening an issue!

Your `main.dart` could simply consist of:

```dart
import 'package:flutter/material.dart';
void main() => runApp(MyApp());
```

Then you have have the UI for `MyApp` in `my_app.dart` like:

```dart
import 'package:flutter/material.dart';
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(...);
  }
}
```

and you have keep your business logic in the blocs (each in its own bloc directory).

You can refer to the various [Bloc Tutorials](https://felangel.github.io/bloc/#/fluttercountertutorial) and [Examples](https://github.com/felangel/bloc/tree/master/examples) for complete apps.

Hope that helps 👍
