### ISSUE TITLE
chore: questions about good using

### ISSUE THREAD

**Issue by bambinoua** [felangel/bloc#3690]
Hi, everyone. I need a little help to kick me in right direction. My task is simple: I have a `ListView` of buildings. When building is selected in the list on I need to show building's floors as `TreeView`. When floor is selected then I need to show image with floor plan which in its turn can be scaled and scrolled. It just so happens that I have no BLOC (as it is required) for buildings overview (bad programming) but I have a `ValueNotifier<Building>` which notifies listeners about building selectiom change.

For floors and floor plans I want to implement BLOCs so I prepare some classes (all classes are just mock):

```dart
class FloorsOverviewState {
  final Status status;
  final SubStatus substatus;
  final List<Floor> nodes;
  final Floor selectedNode;
  final List<String> expandedNodes;
  final Object? error;
}
```
```dart
class FloorsOverviewCubit extends HydrateCubit<FloorsOverviewState> {
  FloorsOverviewCubit(this.repository) : super(const FloorsOverviewState()) {
    _init();
  }

  final FloorsRepository repository;

  void _init() {
    _subscriber = repository.stream.listen((listOfFloors)) {
      emit(FloorsOverviewState(status: Status.success, nodes: listOfFloors, ...));
    }, onError: (error) {
      emit(FloorsOverviewState(status: Status.error, error: error);
    });
  }

  void refreshNodes(int buildingId) async {
    emit(FloorsOverviewState(status: Status.waiting);
    repository.getFloors(buildingId)
  }

  void updateSelection(Floor selectedNode) async {
    emit(FloorsOverviewState(substatus: SubStatus.fetching);
    await repository.getFloor(selectedNote.id)
    emit(FloorsOverviewState(substatus: SubStatus.idle);
  }
}
```

```dart
class FloorPlanState {
  final double scale;
  final double scrollOffset;
}
```
```dart
class FloorPlanCubit extends HydrateCubit<FloorPlanState> {
  FloorPlanCubit() : super(const FloorPlanState());

  void zoomIn() {
    emit(state.copyWith(scale: state.scale + 1));
  }

  void zoomOut() {
    emit(state.copyWith(scale: state.scale - 1));
  }

  void fitToSpace() {
    emit(const FloorPlanState());
  }

  void setOffset(Offset offset) {
    emit(state.copyWith(offset: offset));
  }
}
```
GUI is like:
```dart
class BuildingFloors extends StatefulWidget {
  BuildingFloors(this.building);

  final Building building;
}

class _BuildingFloorsState ... {
  late FloorsOverviewCubit bloc;

  @override
  void initState() {
    bloc = FloorsOverviewCubit(repository: context.read<FloorRepository>())
      ..refreshFloors(building.id);
  }

  @override
  void didUpdateWidget(... oldWidget) {
    if(widget.building != oldWidget.building) {
      bloc.refreshFloors(building.id);
    }
  }

  Widget build(...) {
    return BlocProvider<FloorsOverviewCubit>.value(
      value: bloc,
      buildWhen: (previous, current) => _some_build_when_logic(),
      builder: (context, state) {
        return Row(children: [
            // catching error or waiting status is here

            final selectedFloor = state.selectedNode;
            final floorPlanBloc = FloorPlanCubit();
               
            BuildingFloorsTreeView(), // inside I use `FloorsOverviewCubit` via context.read()
            if(selectedFloor.hasImage)
              BuildingFloorPlan(bloc: floorPlanBloc),`
            else 
              SomeWidget('There is not floor plan. Would you like to add it?'),
          ],
        );
      }
    );
  }
}

```
```dart
class FlooPlan extends StatelessWidget {
  // Widget contains big image with possibility of scrolling and scaling, i.e.
  // methods `zoomIn`, `zoomOut` of `FloorPlanCubit` are used.
}

```
Now I need to tie it all together. I have some problems in understanding if I am doing in right direction. I confused with refreshing of floors in `didUpdateWidget` because of building change. 

Should I pass new building in widget's constructor or do I need to subscribe to `ValueNotifier<Building>` (let's assume that it is similar to state of hypotetical `BuildingBloc`)?

Also now I re-initialize floors using method `refreshFloors` with parameter. But maybe I need to pass `building.id` to `FloorsOverviewCubit` constructor so I will have a bloc per building but then I need to re-create it on each building change. What is the good approach - create BLOC once and do not use re-creation on parent state change?

What is correct to create a bloc inside the widget it serves or create it outside and provide as parameter or via `Provider`?

Also for each floor plan I need to persist scale/scrollOffset of floor plan state in one case (when I switch to other page and return back) and reset those scale/scrollOffset when I change the floor (i.e. floor plan state should be reset). So `FloorPlanCubit` depends on `FloorsOverviewCubit` and I need to somehow to tie them.

Please any advices.

**Comment by tenhobi** [comment]
Hey, @bambinoua, did you already come to a solution?

I would not use `didUpdateWidget` for refreshing blocs tho.

**Comment by felangel** [comment]
Closing for now since there doesn't appear to be any actionable next steps. Feel free to comment with any updates/questions and I'm happy to continue the conversation 👍
