### ISSUE TITLE
How to control multiple bloc builder on different screen ( buildwhen doesn't work everytime )

### ISSUE THREAD

**Issue by kartikmalhotra** [felangel/bloc#3691]
**Description**

I have multiple BlocBuilder for the same bloc on different screens but the problem is if I add buildwhen to control which BlocBuilder should be called, on some screens build when is not getting called. 

**Desired Solution**

To have a full control over BlocBuilder buildwhen should be called every time

**Comment by bambinoua** [comment]
I presume that you have nested `BlocBuilder`s? So to force inner `BlocBuilder` to call `bulder` the outer `BlocBuilder`'s `buildWhen` should allow this. 

I use few `BlocBuilder`s on the same widget with different `buildWhen` and all works fine.

To have a full control over BlocBuilder buildwhen should be called every time
`BlocBuilder` with default `buildWhen` (returns `true`) re-builds **each time when state is changed**.

**Comment by tenhobi** [comment]
Hi @kartikmalhotra, could you provide a minimal reproduction sample?

**Comment by felangel** [comment]
Closing for now since there is no minimal reproduction sample. Feel free to provide one and I'm happy to take a closer look 👍

**Comment by erlangparasu** [comment]
@kartikmalhotra 
i guess because the widget is not mounted yet
