### ISSUE TITLE
Wrapping widgets ruin string interpolation (VS Code Extension)

### ISSUE THREAD

**Issue by jj-gh** [felangel/bloc#3696]
When using the action menu to wrap a widget with any of the Bloc widgets, some variables get removed from string interpolations within child widgets.

https://user-images.githubusercontent.com/29596233/214593914-37fd7706-f4cd-4439-bf89-04f820c0a8ad.mp4

**Comment by lordvidex** [comment]
I encountered the same issue today

**Comment by felangel** [comment]
Hi @jj-gh 👋
Thanks for opening an issue!

I’ll try to get a fix in this weekend. Sorry for the inconvenience, thanks!
