### ISSUE TITLE
Can you change bloc state's type to ValueObservable<State> ?

### ISSUE THREAD

**Issue by hnyaoqingping** [felangel/bloc#37]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

In rxdart 0.19.0, the ValueObservable type is provided. 
I recommend changing 
"Stream<State> get state => _stateSubject.stream;" 
to 
"ValueObservable<State> get state => _stateSubject.stream;". 
This way, in StreamBuilder , initialData can use your_bloc.state.value
Please refer to "https://twitter.com/filiphracek/status/1050798900968181761"

**Comment by felangel** [comment]
In an attempt to abstract all rxDart I have already exposed currentState in the latest version of bloc.

‘State get currentState = _stateSubject.value’
