### ISSUE TITLE
Discussion: Events - Using named constructors instead of subclasses 

### ISSUE THREAD

**Issue by cmarpert** [felangel/bloc#3706]
**Description**

What is your thought on the following pattern? I use named constructors of the Event class. This then internally calls the private constructor adding an event from the Trigger Enum. 

Under Bloc, I have a switch statement, calling a different method on different triggers.
The idea is, to easily find the events by writing "AktuellEvent." and then Intellisense gives me the choices.
Do you see any drawbacks using this style? 

Thanks in advance 

**Example Code**

*Event Part*

```dart
part of 'aktuell_bloc.dart';

enum AktuellTrigger {
  loadContent,
}

class AktuellEvent extends Equatable {
  final AktuellTrigger _trigger;
  const AktuellEvent._({required AktuellTrigger trigger}) : _trigger = trigger;

  factory AktuellEvent.loadContent() => AktuellEvent._(trigger: AktuellTrigger.loadContent);

  @override
  List<Object?> get props => [_trigger];
}

```

*BloC Part*

```dart
class AktuellBloc extends Bloc<AktuellEvent, AktuellState> {
  AktuellBloc() : super(AktuellState.initial()) {
    on<AktuellEvent>((event, emit) async {
      switch (event._trigger) {
        case AktuellTrigger.loadContent:
          loadContent(event: event, emit: emit);
      }
    });
  }

  Future<void> loadContent({required AktuellEvent event, required Emitter<AktuellState> emit}) async {
    emit(state.copyWith(status: AktuellStatus.loading));
    Future.delayed(Duration(seconds: 1));
    emit(state.copyWith(status: AktuellStatus.loaded));
  }
}

```

**Comment by cmarpert** [comment]
sorry for the bug label, but cannot figure out how to remove it ..

**Comment by tenhobi** [comment]
Wouldn't it be simpler in your case to use Cubit? :)

**Comment by tenhobi** [comment]
We moved to `on<>()` in Bloc for some reasons, like to make it clearer and less boilerplate with switch or if-else. Using this style, you actively ignore all the benefits.

I would rather use some `ActuallEventInitialized`, `ActuallEventError`, ... styles with prefixes than having a one-all-mighty event you use a switch on.

**Comment by cmarpert** [comment]
yeah, your right, after playing around with it, it feels like it does more harm then benefits. 
Anyway thks for your feedback. highly appreciated 👍

**Comment by felangel** [comment]
Going to close this for now but feel free to continue the discussion if you have additional comments/concerns 👍
