### ISSUE TITLE
feat: make MultiBlocProvider child property nullable as it done in BlocProvider

### ISSUE THREAD

**Issue by ycherniavskyi** [felangel/bloc#3714]
**Description**

Make [MultiBlocProvider](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/MultiBlocProvider-class.html) `child` property nullable as it done in [BlocProvider](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocProvider-class.html) [`child`](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocProvider/child.html) property. Especially that in [MultiBlocProvider](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/MultiBlocProvider-class.html) super class [MultiProvider](https://pub.dev/documentation/provider/latest/provider/MultiProvider-class.html) `child` property also nullable.

**Desired Solution**

```dart
MaterialApp.router(
  builder: (context, child) {
    return MultiBlocProvider(
      providers: [...],
      child: child,
    );
  },
);
```

**Alternatives Considered**

```dart
MaterialApp.router(
  builder: (context, child) {
    return MultiBlocProvider(
      providers: [...],
      child: child ?? const SizedBox(), // 🤷🏻‍♂️
    );
  },
);
```

**Additional Context**

During moving from [BlocProvider](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/BlocProvider-class.html) to [MultiBlocProvider](https://pub.dev/documentation/flutter_bloc/latest/flutter_bloc/MultiBlocProvider-class.html) within [MaterialApp](https://api.flutter.dev/flutter/material/MaterialApp/material/MaterialApp-class.html) [builder](https://api.flutter.dev/flutter/material/MaterialApp/builder.html) property function, I am getting the error: `error: The argument type 'Widget?' can't be assigned to the parameter type 'Widget'.`

**Comment by felangel** [comment]
Hi @ycherniavskyi 👋 
Thanks for opening an issue!

A `MultiBlocProvider` must have a child. The reason the `BlocProvider` child is nullable is because it can be used within a `MultiBlocProvider`:

```dart
MultiBlocProvider(
  provider: [
    BlocProvider(create: (_) => MyBloc()), // No child here
    ...
  ],
  child: child, // A child should always be specified here.
);
```

**Comment by ycherniavskyi** [comment]
@felangel, could you please explain in a bit more detail why `MultiBlocProvider` must have a child? Because, as I mentioned, even its superclass [MultiProvider](https://pub.dev/documentation/provider/latest/provider/MultiProvider-class.html) does not have such nullable restriction on its `child` property.

**Comment by felangel** [comment]
> @felangel, could you please explain in a bit more detail why `MultiBlocProvider` must have a child? Because, as I mentioned, its superclass [MultiProvider](https://pub.dev/documentation/provider/latest/provider/MultiProvider-class.html) does not have such nullable restriction on its `child` property.

What would you render if `child` is null?

**Comment by ycherniavskyi** [comment]
Hm, I have the same question for a flutter developer who makes `child` parameter of [`builder`](https://api.flutter.dev/flutter/material/MaterialApp/builder.html) function of [MaterialApp](https://api.flutter.dev/flutter/material/MaterialApp/material/MaterialApp-class.html) nullable 🙂.

In such situation, I am just curious what is the more correct way to handle possible null of `child` parameter 🤔:
```dart
MaterialApp.router(
  builder: (context, child) {
    return MultiBlocProvider(
      providers: [...],
      child: child ?? const FallbackWidget(),
    );
  },
);
```
or
```dart
MaterialApp.router(
  builder: (context, child) {
    if (child == null) {
      return const FallbackWidget();
    } else {
      return MultiBlocProvider(
        providers: [...],
        child: child,
      );
    }
  },
);
```

**Comment by ycherniavskyi** [comment]
It seems to be no reason to create `MultiBlocProvider` for the dummy internally created widget.

**Comment by felangel** [comment]
Yeah I agree if child is null you probably don't need the `MultiBlocProvider` which is even more reason to not allow a nullable `child` property.

**Comment by ycherniavskyi** [comment]
@felangel, thank you for the informative discussion 😉.
