### ISSUE TITLE
Try to dispatch event without Context

### ISSUE THREAD

**Issue by cyrsis** [felangel/bloc#373]
I have some init app service that do not have UI and without Context, is it possible to dispatch event without Context?

```
BlocProvider.of<SomeBloc>(context)
                      .dispatch(SomeReloadEvent());

```

**Comment by felangel** [comment]
Hi @cyrsis 👋 
Thanks for opening an issue!

BlocProvider needs a BuildContext in order to access the bloc; however, you can directly inject the bloc into your service and dispatch the event. Let me know if that helps 👍

**Comment by cyrsis** [comment]
Great , I like inject, should I have make Singleton bloc?

Since this bloc would take care some rendering on screen or I should make an other bloc

**Comment by felangel** [comment]
I would recommend having a single instance of the bloc and using BlocProvider to initially provide it. Then wherever you initialize your service you can access the bloc via BlocProvider.of(context) and inject it into the service. Hope that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
