### ISSUE TITLE
fix: MultiBlocProvider in specific level in flutter tree widget

### ISSUE THREAD

**Issue by esmaeil-ahmadipour** [felangel/bloc#3730]
I need MultiBlocProvider in specific level in flutter tree widget and try to use MultiBlocProvider as shown below.

![MultiBlocProvider](https://user-images.githubusercontent.com/46590079/217516028-c1d44331-209c-4b59-9a3f-bab5ad74903d.png)

In other words, when we use MultiBlocProvideron top of MaterialApp, there is no problem. But according to the code below, this item gets an error. 
```
void main() {
  runApp(MaterialApp(
    onGenerateRoute: (settings) {
      switch (settings.name) {
        case "/":
          return MaterialPageRoute(
              builder: (_) => MultiBlocProvider(providers: [
                    BlocProvider(
                      create: (_) => CounterBloc(),
                    )
                  ], child: const GroupA()),
              settings: settings);
        case "/ScopeA":
          return MaterialPageRoute(
              builder: (_) => const ScopeA(), settings: settings);
        default:
          return MaterialPageRoute(
              builder: (_) => const Text("ERROR"), settings: settings);
      }
    },
  ));
}

class GroupA extends StatelessWidget {
  const GroupA({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Group A:')),
      body: Center(
        child: MaterialButton(
            onPressed: () => Navigator.pushNamed(context, '/ScopeA'),
            child: const Text("Go To Scope A")),
      ),
    );
  }
}

class ScopeA extends StatelessWidget {
  const ScopeA({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Scope A:')),
      body: Center(
        child: BlocBuilder<CounterBloc, int>(
          builder: (context, count) {
            return Text(
              '$count',
              style: Theme.of(context).textTheme.displayLarge,
            );
          },
        ),
      ),
    );
  }
}

abstract class CounterEvent {}

class CounterIncrementPressed extends CounterEvent {}

class CounterDecrementPressed extends CounterEvent {}

class CounterBloc extends Bloc<CounterEvent, int> {
  CounterBloc() : super(0) {
    on<CounterIncrementPressed>((event, emit) => emit(state + 1));
    on<CounterDecrementPressed>((event, emit) => emit(state - 1));
  }
}
```
i using below version :
flutter_bloc : `8.1.2`
bloc : `8.1.1`

when running code in` Chrome`  Browser Version `109.0.5414.120 (Official Build) (64-bit)` get this error:

```
Error: Cannot hit test a render box that has never been laid out.
```
i running at chrome browser , this is `flutter doctor -v` result:
```
PS C:\example> flutter doctor -v
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.2130], locale en-US)
    • Flutter version 3.0.5 at C:\_files\flutter
    • Upstream repository git@github.com:flutter/flutter.git
    • Framework revision f1875d570e (7 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\esmaeil.ahmadipour\AppData\Local\Android\Sdk
    • Platform android-33, build-tools 33.0.0
    • ANDROID_HOME = C:\Users\esmaeil.ahmadipour\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] VS Code (version 1.74.3)
    • VS Code at C:\Users\esmaeil.ahmadipour\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19044.2130]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 109.0.5414.120
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 108.0.1462.76

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

**Comment by felangel** [comment]
Hi @esmaeil-ahmadipour 👋
Thanks for opening an issue!

Based on the error this doesn’t appear to be related to bloc. If you remove all bloc-related code does the problem go away? If you feel it’s a problem in bloc can you please provide a link to a minimal reproduction sample that someone can easily clone and run to reproduce the issue locally? Thanks!

**Comment by tenhobi** [comment]
Hey @esmaeil-ahmadipour 👋, as @felangel mentioned, this is not an issue with Bloc. 

To start with, the issue is in your diagram. The way how you wrote your `MaterialApp` routing is that you have Group A and Scope A side by side. And that's more less the point of routing, that you get separate pages. So basically, you just did this: black paths for widget tree dependencies (and what you can see), red paths for how the provider tries to find the provided resource in the ancestor tree, and green paths for your routing.

![image](https://user-images.githubusercontent.com/5287596/217916482-5d6d3273-92f4-4f44-98b2-b8df2e99f455.png)

As you can see, it cannot resolve the provided bloc because it is not its predecessor.

**Comment by esmaeil-ahmadipour** [comment]
Thanks @tenhobi , My Code may be wrong . Did I understand correctly? , when I change the path, I shouldn't expect to access the block I was in before.
What to do for this scenario :
```
I am in GroupA and I want to go to ScopeA and access the block.
And when I go back to GroupA and go to GroupB, , the block cannot be accessed.
```
how to change code to achieve this ?

if help me I will be appreciative for that.

**Comment by tenhobi** [comment]
Yes, as shown in the picture. Hmm, to do what you want, you probably have two options. 

One is to pass some data (your bloc) to the new route, aka ScopeA. https://docs.flutter.dev/cookbook/navigation/navigate-with-arguments There, you could provide that bloc to that route's subtree. But, while this will work, you might face issues if the bloc instance is destroyed if you `pushReplacement`. Yet if you can make sure that the old route will always exit below (aka, you are pushing the ScopeA route on top of the navigation stack, it would work). Or, maybe even better, as you don't have to deal with deleted references, and if you don't want to access the updated bloc after pop from scope A, you can create some data class with data needed for creating a new bloc provided in the scope A route. 

The second option is to use provide the bloc above the router / material app, and change states based on pushing/poping. 

The exact solution is dependent on your specific app needs tho.
