### ISSUE TITLE
fix: website is not working properly on windows machine

### ISSUE THREAD

**Issue by Dhruvesh08** [felangel/bloc#3737]
**Description**
https://bloclibrary.dev/#/
is not working properly on windows machine 
(I've tested to all major browsers i.e. Chrome, Edge, Firefox, Brave, Vivaldi)
on the Conter part it works fine on mac systems.

**Steps To Reproduce**

1. Go to https://bloclibrary.dev/#/ form windows machine 

**Expected Behavior**
it should work fine on any browser regardless of OS.

**Screenshots**
on Chrome
![image](https://user-images.githubusercontent.com/21958005/218433812-2ff59416-551a-4dca-9d1d-a7f4dfe7f7e2.png)
![image](https://user-images.githubusercontent.com/21958005/218433873-de5c52ad-4b94-48c7-af06-581310d4328e.png)

dev-tools:
![image](https://user-images.githubusercontent.com/21958005/218433767-7ff76ecc-2a24-4666-90ec-54c798a61c49.png)
![image](https://user-images.githubusercontent.com/21958005/218433700-ecd8393e-5aee-4092-bc7c-1a98d1fa3fee.png)

**Comment by tenhobi** [comment]
This looks more like a temporary server network issue. Could you test that @Dhruvesh08 ?

I also come to notice that GitHub tokens are somehow not functional on the web, cc @felangel  
<img width="326" alt="image" src="https://user-images.githubusercontent.com/5287596/218990912-b5aa8b07-4531-44ed-b59f-1bfedc6e4f8c.png">

**Comment by Dhruvesh08** [comment]
Sure @tenhobi,
I can confirm that this issue is not related to temporary server network issue as I'm able to access the website on mac perfectly while not on the windows machine at same time.

on windows chrome:
![image](https://user-images.githubusercontent.com/21958005/218998251-b63a1333-2eef-4100-bf50-4ebe0eac624a.png)
![image](https://user-images.githubusercontent.com/21958005/218999725-68f153d5-6632-4ee8-9cc7-843cc69f01d4.png)


on Mac chrome:
![image](https://user-images.githubusercontent.com/21958005/218998328-c9484149-4fe8-49b8-90dc-b98d99bf4833.png)
![image](https://user-images.githubusercontent.com/21958005/218999878-b8cb8696-102e-4fc7-a4c9-029b00fcca6f.png)

Thanks

**Comment by felangel** [comment]
@tenhobi @Dhruvesh08 is this still an issue? It definitely looks like a network issue to me 🤔 

<img width="1728" alt="Screenshot 2023-02-15 at 11 19 56 PM" src="https://user-images.githubusercontent.com/8855632/219275446-3855f0f1-59bd-4aa9-a725-c514ced1fe95.png">

**Comment by Dhruvesh08** [comment]
Hello @felangel 
yes, I can confirm that this is still the issue and not related to the network 

windows chrome:
on initial load
![image](https://user-images.githubusercontent.com/21958005/219279202-97cffbbf-e4fe-4d1e-8465-0b14bdbdb4c0.png)
![image](https://user-images.githubusercontent.com/21958005/219279300-bc3eedc5-ce23-4342-9a83-c8140c3b8c4b.png)

after some time when we ger this failed response 
![image](https://user-images.githubusercontent.com/21958005/219280287-bc2ab719-e870-4d7b-b5b8-4417aaa3af8f.png)

if I go to GitHub page and click on some examples link that redirect to [bloc](https://bloclibrary.dev)

for example 
https://bloclibrary.dev/#/flutterlogintutorial
https://bloclibrary.dev/#/flutterangulargithubsearch


on that page also in became unresponsive 
![image](https://user-images.githubusercontent.com/21958005/219281586-83ca1a56-e084-4321-b577-60c84065dbe5.png)
![image](https://user-images.githubusercontent.com/21958005/219281528-526d91ce-3693-4361-a633-449b2cc1b3ba.png)


at same time on mac, it works like charm.

on initial load
![image](https://user-images.githubusercontent.com/21958005/219282158-e7c4178b-a659-4c82-a42e-d29796b25bfe.png)
![image](https://user-images.githubusercontent.com/21958005/219282241-03f1a0f6-05ca-40c3-be52-d167163a5288.png)


if I go to GitHub page and click on some examples link that redirect to [bloc](https://bloclibrary.dev)

for example

https://bloclibrary.dev/#/flutterfirebaselogintutorial
https://bloclibrary.dev/#/flutterangulargithubsearch

![image](https://user-images.githubusercontent.com/21958005/219282322-5002a16f-18bc-46df-a78b-a63fbc11d6c8.png)
![image](https://user-images.githubusercontent.com/21958005/219282342-f5355b72-07e4-49d6-8569-e2964ed621bd.png)


Thanks

**Comment by tenhobi** [comment]
> @tenhobi @Dhruvesh08 is this still an issue? It definitely looks like a network issue to me 🤔

It works for me (even the badge) now, on Macbook. I can try in the evening on Windows laptop if I can see an issue @Dhruvesh08 mentions. 🤔 

Yet I cannot think of a reason why the OS would matter. And only on bloc web. :D

**Comment by felangel** [comment]
Seems to be a known issue with certain ISPs so I don't think there's anything we can really do about it. Let me know if you have suggestions otherwise I'll close for now since there aren't any actionable next steps.

https://twitter.com/ChinuKabi/status/1627540845426806795?s=20

**Comment by maximveksler** [comment]
It's possible that hosting the website behind Cloudflare or moving to a different IaaS hosting such as vercel could help. Worth a shot?

**Comment by felangel** [comment]
> It's possible that hosting the website behind Cloudflare or moving to a different IaaS hosting such as vercel could help. Worth a shot?

I can try moving to cloudflare shortly 👍
