### ISSUE TITLE
Flutter BloC repeat an event again after dio request time out

### ISSUE THREAD

**Issue by ElGenius-developer** [felangel/bloc#3739]
I have a problem on my flutter app, when try to load a data from api using dio and this api is private so need to be connected to the same network, so to check everything is fine I tried to connect using mobile data that means dio connection won't success and return timeout, when I call that inside BLoC and use BloCBuilder to build UI depending on state bloc return loadingstate then return errorstate and try to do the event again and fail then repeat this over and over, I just want to avoid this and return error state only and stop listening on that event
```
void _loadAllSpecialities(
      LoadAllSpecialities event, Emitter<DoctorsState> emit) async {
    emit(
      const DoctorsLoadingState(),
    );
    emit(const DoctorsLoadingState());
    final result = await doctorService.getAllSpeciality(event.jwtToken);
    print(result.toString());
    //has no error and data loaded
    if (result.item1 == null) {
      final speicailities = result.item2;

      emit(DoctorsSpecialitiesLoaded(specialities: speicailities));
    } else {
      //has error (error not null)
      emit(DoctorErrorState(result.item1!));
    }
  }```
.


```
```

class DoctorService {
  final List<DoctorSpeciality> specialities = [];
  final options = Options(
    responseType: ResponseType.json,
    receiveTimeout: 2000,
    sendTimeout: 2000,
  );
  final _dio = Dio();
  Future<Tuple<String?, List<DoctorSpeciality>>> getAllSpeciality(
      String jwtToken) async {
    specialities.clear();
    var tuple = Tuple<String?, List<DoctorSpeciality>>(null, []);

    try {
      final response = await _dio.get<List>(ApiVars.specialitiesEndPoint,
          options:
              options.copyWith(headers: {"Authorization": "Bearer $jwtToken"}));
      if (response.statusCode == 200) {
        //has no data
        if (response.data == null) {
          //set error 1
          tuple.setNewValues('No data loaded', []);
          //print it
          log(tuple.item1 ?? '');
          //return tuple with error and empty list
          return tuple;
        }
        //has data then map it into list of specialities
        response.data?.forEach((element) {
          //convert json to speciality and add it to specialities list
          specialities.add(DoctorSpeciality.fromJson(element));
        });
        //set error to null and list to specialites list
        tuple.setNewValues(null, specialities);
        return tuple;
      } else {
        //set error to error with the code and list to empty list
        tuple.setNewValues('error occur with code ${response.statusCode}', []);
        log(tuple.item1 ?? '');

        return tuple;
      }
    } on DioError catch (error) {
      //set error to error message and list to empty list
      tuple.setNewValues("doc service ${error.message}", []);
      log(tuple.item1 ?? '');
      return tuple;
    }
  }
}

```
```


I tried add droppable, sequential and didn't work

```
  `  on<LoadAllSpecialities>(_loadAllSpecialities,
        transformer: droppable());`
```

**Comment by ElGenius-developer** [comment]
**Bloc added event that load some data when timeout exception is thrown bloc emit error state as I expected , but instead of return error widget inside the bloc builder , bloc repeat event again and emit loading state again and this loop is taking forever, I tried transformer (restartable, droppable, sequential, concurrent ), and still the same**
`I/flutter (15882): DoctorsLoadingState(false)
D/DecorView[](15882): onWindowFocusChanged hasWindowFocus false
D/DecorView[](15882): onWindowFocusChanged hasWindowFocus true
I/flutter (15882): DoctorErrorState(doc service Connecting timed out [0ms])
[log] doc service Connecting timed out [0ms]
I/flutter (15882): DoctorsLoadingState(false)
I/flutter (15882): DoctorErrorState(doc service Connecting timed out [0ms])
[log] doc service Connecting timed out [0ms]
I/flutter (15882): DoctorsLoadingState(false)
[log] doc service Connecting timed out [0ms]
I/flutter (15882): DoctorErrorState(doc service Connecting timed out [0ms])
I/flutter (15882): DoctorsLoadingState(false)
[log] doc service Connecting timed out [0ms]
I/flutter (15882): DoctorsLoadingState(false)
[log] en
I/flutter (15882): DoctorsLoadingState(false)
I/LongScreenshotUtils(15882):  focus:true
I/LongScreenshotUtils(15882): current ratio width:1.0, height:1.0
[log] doc service Connecting timed out [0ms]
D/DecorView[](15882): onWindowFocusChanged hasWindowFocus false
[log] doc service Connecting timed out [0ms]
D/DecorView[](15882): onWindowFocusChanged hasWindowFocus true
D/DecorView[](15882): onWindowFocusChanged hasWindowFocus false
E/BLASTBufferQueue(15882): [ViewRootImpl[MainActivity]#0](f:0,a:1) Applying pending transactions on dtor  @9
`

**Comment by tenhobi** [comment]
Don't you have a bloc call somewhere in your `build` or `BlocBuilder`'s `builder` method?

**Comment by ElGenius-developer** [comment]
Thanks for response,
I solved the problem by adding Future<void> before function that called inside the handler function and await it to end as code in below
`///constructor called super and pass initial state...
  DoctorsBloc() : super(DoctorsInitialState()) {
    on<DoctorsEvent>(
      (event, emit) async {
        try {
          if (event is LoadAllSpecialities) {
            // * load all specialities of doctors from api ...
            **await** _loadAllSpecialities(event, emit);
          }
          //*******************
        } catch (error) {
          emit(DoctorErrorState(error.toString()));
        }
      },
    );
  }
  ////**********************************
  /// *-- load  all Specialities
  /// *********************************
  **Future**<void> _loadAllSpecialities(
      LoadAllSpecialities event, Emitter<DoctorsState> emit) async {
    emit(
      const DoctorsLoadingState(),
    );
    emit(const DoctorsLoadingState());
    final result = await doctorService.getAllSpeciality(event.jwtToken);
    //has no error and data loaded
    if (result.item1 == null) {
      final speicailities = result.item2;

      emit(DoctorsSpecialitiesLoaded(specialities: speicailities));
    } else {
      //has error (error not null)
      emit(DoctorErrorState(result.item1!));
    }
  }

  `

**Comment by tenhobi** [comment]
Nice. I would recommend you set up some analysis to disable wrong inferences, like in the code below. That might have caught the issue on the spot. 

```
# analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
```

And in general, use lints. If you do not want to invest in cherry-picking lints, use https://pub.dev/packages/lints, https://pub.dev/packages/flutter_lints, https://pub.dev/packages/very_good_analysis, or any other package that does it for you.

I also recently posted one article that covers the basics of static analysis and linting in Flutter apps, so you can check it out or get inspired by our set of lints. https://www.netglade.cz/en/blog/fluter-apps-linter-dart-netglade_analysis

**Comment by ElGenius-developer** [comment]
Ok, thanks
