### ISSUE TITLE
fix: DefaultTabControllers and CustomScrollViews aren't reseting their index or scrolling when passed through bloc provider

### ISSUE THREAD

**Issue by RyanQuigleyOsi** [felangel/bloc#3743]
**Description**
I was attempting to use BlocProvider pass a DefaultTabController into a cubit to update the state of a BlocBuilder and display the DefaultTabController. When testing this I found that the selected tab and any scrolling on the TabBar was preserved between DefaultTabControllers ignoring the what I had set for the initialIndex. The only way I've found to prevent this from happening is to pass a different widget in between the DefaultTabControllers and wait for at least 50ms before passing the new DefaultTabController. I also found that CustomScrollViews fail to reset there scrolling in a similar mannor.

**Steps To Reproduce**
I have a project that demonstrates this at https://github.com/RyanQuigleyOsi/BlocScrollDemo
The demo has two buttons on the bottom right, ScrollView and TabController. Each one loads the widget its named for. The views they load have alternating color shcemes to make it clear when a new widget is built.

Case 1:
1. Click TabController
2. Select a tab and scroll on the tab bar
3. Click TabController again

Case 2:
1. Click ScrollView
2. Scroll down
3. Click ScrollView again

**Expected Behavior**
In Case 1 you'd expect loading the new tab controller loaded on step 3 would re initialize on index one but it maintains the previously selected index and any scrolling

In Case 2 you'd expect the new ScrollView loaded on step 3 to jump back to the top but it also maintains its position.

If you alternate between the scroll view and tab controller they do reset their index and scrolling.

**Additional Context**
If I'm using any of these wrong I would love to know how I could correct this.

**Comment by tenhobi** [comment]
Hey, as a first thing, I would suggest try using Keys, like maybe `UniqueKey()` for your controllers. Flutter might confuse the tree and assign those new controller widgets to old elements. see https://www.youtube.com/watch?v=kn0EOS-ZiIc

**Comment by RyanQuigleyOsi** [comment]
That worked perfectly, thanks a ton!
