### ISSUE TITLE
feat: Include hydrated_bloc in flutter_bloc

### ISSUE THREAD

**Issue by markdynamo6** [felangel/bloc#3746]
Thanks for your work on this. It really is splendid.

We are using flutter_bloc in a large project and we were wondering if it might be appropriate to include hydrated_bloc? Currently we have to include it separately. Or perhaps there are plans to integrate persistence into the main bloc library?

**Comment by felangel** [comment]
Hi @markdynamo6 👋 
Thanks for opening an issue and for the positive feedback, I really appreciate it!

The separation is intentional -- `flutter_bloc` has an explicit dependency on `flutter` whereas `hydrated_bloc` does not. For example, you can choose to use `hydrated_bloc` in a pure Dart application. I highly recommend thinking of each bloc package as a module which you can add as needed. I'd prefer not to include `hydrated_bloc` as part of `flutter_bloc` because it would bloat the package and conflate the two libraries.

Hope that helps 👍

**Comment by markdynamo6** [comment]
Cheers for getting back to me so quickly. 

I take your point about bloat and the separation makes sense. 

I guess the question was kind of more around: What would be the effect of simply adding hydrated_bloc as a dependency of flutter_bloc and then adding `export 'package:hydrated_bloc/hydrated_bloc.dart';` into the flutter_bloc.dart file? Then users of flutter_bloc would be ready to rock and roll if they wanted to use either standard bloc or hydrated_bloc.

**Comment by felangel** [comment]
> Cheers for getting back to me so quickly.
> 
> I take your point about bloat and the separation makes sense.
> 
> I guess the question was kind of more around: What would be the effect of simply adding hydrated_bloc as a dependency of flutter_bloc and then adding `export 'package:hydrated_bloc/hydrated_bloc.dart';` into the flutter_bloc.dart file? Then users of flutter_bloc would be ready to rock and roll if they wanted to use either standard bloc or hydrated_bloc.

Ah I see, that would work but it would tightly couple the two packages and make it more challenging to maintain. Also if we did that then folks might also ask for other bloc packages like `sealed_flutter_bloc`, `replay_bloc`, and `broadcast_bloc` to also be re-exported from `flutter_bloc` so I'd prefer to just keep things decoupled and leave it up to developers to pull in whatever dependencies they need. In my opinion, re-exporting a library from a package is usually a good idea when the package is already tightly coupled to the library. In this case, `flutter_bloc` is not tightly coupled to `hydrated_bloc` and not all apps that use `flutter_bloc` will use `hydrated_bloc`.

Hope that makes sense! Let me know what you think 👍

**Comment by markdynamo6** [comment]
That's cool, no problem at all. 

I can see why you wouldn't want to open the flood gates by including it, and that in itself, is probably reason enough.

Again. awesome work.
