### ISSUE TITLE
[Question - not a bug]  What is the best way to handle navigations and URLs with bloc pattern

### ISSUE THREAD

**Issue by Retr0sec7** [felangel/bloc#3748]
**Not a bug**
I'm having this issues on my application, specifically on the login -> home/home -> login flows, where I'm not able to update the URLs when an authentication occurs, this is caused because there is something listening to state changes to update the authentication state:
```
class AuthCubit extends Cubit<AuthState> {
  AuthCubit() : super(const AuthState(isSignedIn: false)) {
    FirebaseAuth.instance.authStateChanges().listen((User? firebaseAuthUser) {
      if (firebaseAuthUser == null) {
        emit(copyWith(isSignedIn: false));
      } else {
        var firebaseUserMap =
            AuthUserModel().firebaseUsertoMap(firebaseAuthUser);
        AuthUserModel user = AuthUserModel.fromMap(firebaseUserMap);
        emit(copyWith(isSignedIn: true, currentUSer: user));
      }
    });
  }

}
```
When an emit occurs here, it refreshes the view and the route handler decides to either return my `HomePage()` view (assuming we have authenticated or a session active) or `Login()` view.

The issue with this is that since I'm returning a view to show instead of using the `Navigator` class the URL is not suffering changes, which imposes issues when using the app on a web platform/browser. According to docs, this type of navigation is called Direct Navigation (which is the same that the firebase login example uses). I want to know which is the preferred way to handle navigations, I'm trying to avoid having different kind of navigations in my app where in some situations are/are not convenient to use. I just want to have a single standard way to handle routes.

Docs also suggests to use Routes redirections, which I think it's way to go, but I'm hesitating to make the whole implementation before asking for suggestions to more experienced folks.

Also, Docs suggests [Navigation 2.0](https://bloclibrary.dev/#/recipesflutternavigation?id=navigation-20) which docs just show an implementation example and not what the advantages are, can someone explain me which are those?

**Comment by tenhobi** [comment]
As I posted to https://github.com/felangel/bloc/issues/3747, I tried to do Navigation 2.0 in my side project with this approach 

https://github.com/kingkareldev/client/blob/main/packages/presentation/lib/router/blocs/router/router_bloc.dart
https://github.com/kingkareldev/client/blob/main/packages/presentation/lib/router/app_router_delegate.dart#L225

However, now I would just use go_router and create some service or bloc that would be able to do some additional stuff like open login dialog on credentials expiration etc.
