### ISSUE TITLE
[question]: How to handle few states on the same feature screen?

### ISSUE THREAD

**Issue by bambinoua** [felangel/bloc#3753]
I need a little help in using BLOC pattern. Basically I understand it because of ToDo example but those example is enough simple and real tasks not. So maybe someone gives me an advise if I do staff wrong or correct.

My task is: I have a tree structure of some building zones. Each zone may contain floor plan image which is downloaded asynchronously when zone is selected and the downloaded data is shown in `Image.memory` widget. This image widget is used for view using scaling and scrolling. If the selected zone does not contains floor plan image the the image can be attached (uploaded) for such zone.

Visually it looks so:

1. Zones are loading using some repository (loading can be successful or failed):
```
-------------------------------
|          |                  |
|          |      /--\        |  <---- progress indicator
|          |      \--/        |
|          |                  |
-------------------------------
```
2. Zone contains floor plan so when it is selected the image is downloaded (downloading can be successful or failed). After image downloading user can scale and scroll it (if it is larger then space). Scale and scroll offset should be keeped:
```
-------------------------------
| zone 1    | --------------- |
|  zone 11  | | floor plan  | |
| zone 2    | |             | |
|           | --------------- |
-------------------------------
```

3. Zone does not contains floor plan so when it is selected we see the button which allows to attach (upload) (uploading can be successful or failed). After uploading the image will be visible as in option 2 and can be scaled and scrolled:
```
-------------------------------
| zone 1    |                 |
|  zone 11  | --------------- |
| zone 2    | | add image   | |
|           | --------------- |
-------------------------------
```

So I suppose I need to use 3 blocs because I see here 3 states (which can be successful or failed)

**1. TreeBloc to initialize zones tree.**
```dart
enum TreeState {initial, waiting, succcess, failure}

class TreeBloc extends Cubit<TreeState> {
  /// Refreshes tree from repository
  void refreshTree(int locationId);
}
```
When tree is initialized and selected zone has a floor map I need to download the image from backend and show it. For this case I use FloorMapDownloadBloc
```dart
BlocConsumer<TreeBloc,TreeState>(
  listener: (context, state) {
    if (state.isSuccess && state.selectedNode.hasMap) {
      // Send event to second BLOC to download the floor map image
      floorPlanBloc.refreshImage(1);
    }
  },
  builder: (context, state) {
    if (state.isError) {
      // show error
    }
    if (!state.isSuccess || !state.hasSelectedNode) {
      // show progress
    }
    
    return TreeViewWidget();
  },
),
```

**2. FloorMapBloc to download and operate with downloaded zone floor map.**

```dart
enum FloorPlanState {waiting, succcess, failure}

class FloorPlanBloc extends Cubit<FloorPlanState> {
  void refreshImage(int fileId);
}
```

```dart
BlocBuilder<FloorPlanBloc,FloorPlanState>(
  builder: (context, state) {
    if (state.isError) {
      // show error
    }
    if (!state.isSuccess || !state.hasSelectedNode) {
      // show progress
    }
    
    return FloorPlanViewWidget();
  },
),
```

**3. FloorPlanUploadBloc to handle button for image upload as floor plan.**

```dart
enum FloorPlanUploadState {waiting, succcess, failure}

class FloorPlanUploadBloc extends Cubit<FloorPlanUploadState> {
  void uploadImage(int floorMapId, bytes imageBytes);
}
```

```dart
BlocConsumer<FloorPlanUploadBloc,FloorPlanUploadState>(
  listener: (context, state) {
    if (state.isError) {
      ScaffoldMessager.of(context).warning(state.error);
    }
  },
  builder: (context, state) {
    if (state.isWaiting) {
      // show custom progress indicator
    }  
    return TextButton(
      child: Text('Upload'),
      onPressed: context.read<FloorPlanUploadBloc>().uploadFloorPlan(zoneId, imageBytes);
    );
  },
),
```

All 3 BLOCs use the same repository `ZoneRepository` because all of them are related to zone and zone property (floor plan). 

Is my vision correct? But it seems complex to me though. Or is there any other (simple?) solution?
I also thought if I can combine `FloorPlanBloc` and `FloorPlanUploadBloc` because they do almost similar action but then I stuck how can I separate `waiting` widget when image is downloading or uploading.

So I am little lost in three pines and I would appreciate any help. The main stuck reason is how to process `waiting` `success` and possible `failure` states from different bloc in the same user GUI. I thought also about complex state but then I need to distinguish which `waiting`, `success` or `failure` state is current. Because for one `waiting` I need to show one widget, for second `waiting` I need to show other widget. For `failure` in one case I need to show widget, for other case `Snackbar`.

P.S. Please help me. I spent days to figure out the idea and still have no the solution.

**Comment by Gene-Dana** [comment]
Hi there Bambinoua,

Having multiple blocs on the same page is an expected approach.
<img width="632" alt="image" src="https://user-images.githubusercontent.com/45580241/221886777-deca107b-4551-4f72-a6b7-24d05fc40f65.png">
https://epb.bibl.th-koeln.de/frontdoor/deliver/index/docId/1498/file/flutter-for-the-dev-of-large-scale-ref-app.pdf


Although skimming through your problem I'm not sure you need to absolutely have separate blocs for separate pieces of state.
 
The mantra is 'one bloc per feature.'

**Comment by Gene-Dana** [comment]
Hi there Bambinoua,

Having multiple blocs on the same page is an expected approach.
<img width="632" alt="image" src="https://user-images.githubusercontent.com/45580241/221886777-deca107b-4551-4f72-a6b7-24d05fc40f65.png">
https://epb.bibl.th-koeln.de/frontdoor/deliver/index/docId/1498/file/flutter-for-the-dev-of-large-scale-ref-app.pdf


Although skimming through your problem I'm not sure you need to absolutely have separate blocs for separate pieces of state.
 
The mantra is 'one bloc per feature.'

**Comment by bambinoua** [comment]
@Gene-Dana thank you for your answer! I am already reading.. :) With the hope on clarification in my brain.

**Comment by bambinoua** [comment]
> I'm not sure you need to absolutely have separate blocs for separate pieces of state.

So how can I separate, for example, handling of possible `waiting` and `failure` states? When tree view is just initializing or floor map is downloading (waiting) I need to show regular `CircularProgressIndicator` or some error widget in case of `failure`. When floor map is uploaded  (waiting) I need to show some `CustomProgressIndicator` or `Snackbar`.

The algorythm steps:

I have 2 REST API methods:
1. `http://host/location/1/zones` - returns list of zones where each on contains short piece of data without floor map (image) info
2. `http://host/zones/1` - returns full data witht floor map (image) info
3. `GET http://host/files/1` - returns binary data
4. `POST http://host/files` - post binary data as `multipart/form-data`.

So basically it works like this:

1. Initializing tree view (call 1st REST API method) - `TreeBloc.refreshTreeNodes()`
2. On first `success` state execute `updateSelection` with 1st or saved `selectedId`, i.e. call 2nd REST API method - `TreeBloc.fetchTreeNode(zoneId: 1)`
4. If selected zone contains floor plan (property `hasPlan`) call 3rd REST API function and display image - `FloorPlanBloc.refreshImage(fileId: 1)`
5. If selected zone does not contains floor map show widget `Add image`.
6. If user pressed the `Add image` button call 4th REST API funciton for upload. As previous call of `zones/{id}` does not have `hasPlan` boolean, refresh the tree view (re-read node from API **after** image successfully uploaded) and display image -  - `FloorPlanUploadBloc.uploadImage(fileId: 1)`, `TreeBloc.fetchTreeNode(zoneId: 1)` and `FloorPlanBloc.refreshImage(fileId: 1)`

**Comment by Gene-Dana** [comment]
> So how can I separate, for example, handling of possible `waiting` and `failure` states? When tree view is just initializing or floor map is downloading (waiting) I need to show regular `CircularProgressIndicator` or some error widget in case of `failure`. When floor map is uploaded (waiting) I need to show some `CustomProgressIndicator` or `Snackbar`.

The todos example handles this quite elegantly

Here it's throwing a snackbar when failure case
https://github.com/felangel/bloc/blob/b11fe6a1c00a5cb22fd38b2eba2ae6c0c773cec5/examples/flutter_todos/lib/todos_overview/view/todos_overview_page.dart#L40-L51

And here it's showing a Circular progress while loading and eventually it's displaying a list of `TodoListTiles`
https://github.com/felangel/bloc/blob/b11fe6a1c00a5cb22fd38b2eba2ae6c0c773cec5/examples/flutter_todos/lib/todos_overview/view/todos_overview_page.dart#L85-L108

**Comment by bambinoua** [comment]
> The todos example handles this quite elegantly

I was talking about different sets of statuses. When tree view is initializing it has its own `waiting`, `success` and `failure`. When floor map is down loading is uses its own `waiting` and `success` because downloading is going when `TreeBloc` is already in `success` state. If I will use `TreeBloc` for downloading also and I get the `failure` it will be treated as `failure` to tree view which handled differently.

So the main goal is to distinguish 3 async operations so they have diffetent 3 states. That is why I thought about 3 BLOCs. 

> I'm not sure you need to absolutely have separate blocs for separate pieces of state.

And that is why I ask you if you are not sure how to separate operations? How do you see it?

**Comment by Gene-Dana** [comment]
> So the main goal is to distinguish 3 async operations so they have diffetent 3 states. That is why I thought about 3 BLOCs.

I understand better now. From my perspective I see this all just one feature and you can keep this all together under one Bloc just by have three separate statuses.

I imagine it could look something like this:

```dart

enum TreeStatus {initial, waiting, succcess, failure}
enum FloorPlanStatus {initial, waiting, succcess, failure}
enum FloorPlanUploadStatus {initial, waiting, succcess, failure}

class DiagramOverviewState extends Equatable {
  const DiagramOverviewState({
    this.treeStatus = TreeStatus.initial,
    this.floorPlanStatus = FloorPlanStatus.initial,
    this.floorPlanUploadStatus = FloorPlanUploadStatus.initial,
   ...
  });

```

I'm not sure if I'd name a `FloorPlan` and `FloorPlanUpload` like that. I'd have to understand more to suggest a better one although this is the general idea.

**Comment by bambinoua** [comment]
> I'm not sure if I'd name a FloorPlan and FloorPlanUpload like that. I'd have to understand more to > suggest a better one although this is the general idea.

Well I try to describe the use case. First of all the project is for **web**. Below you will see the base GUI. Left side contains tree which is prepearing with a `TreeBloc`. Until tree is ready the left side shows `CircularProgressIndicator` and until initialnode is selected the right side shows `CircularProgressIndicator` also.

```
-------------------------------
| zone 1    | --------------- |
|  zone 11  | |             | |
| zone 2    | |  floor plan | |
|  zone 21  | |             | |
|           | --------------- |
-------------------------------
```

When node is selected the API (GET http://host/nodes/1) is requested for full info. Full info (JSON) contains (or does not contains) a key `map` which defines whethere node contains a `floor map`, i.e.
```json
{
  "code": "Zone 11",
  "map": {         
    "id": 11,
    "filename": "1st floor.jpg",
  }
}
```

So if `map` is present the API (GET http://host/files/11) is called. For this call I presumed to use `FloorPlanBloc` (why? explanation further) It returns the binary data (image). While it is downloading the right side shows `CircularProgressIndicator`. If image is downloaded the received `Uint8List` is stored in `FloorPlanBloc`'s state which is used for display in `Image.memory`. The `FloorPlanBloc` is used for managing image scaling and scrolling. I.e. I need to visualize scale animation and scroll by capturing mouse (so I thought `TreeBloc` is not for it and that is why I suppose to use other `FloorPlanBloc` bloc). So we already should have 2 BLOCs.

And here it is something else. If `map` key _is not present_ in JSON after getting zone details I need to show button _"Add Floor Plan"_ on the right side. When user pressed it he can select an image and upload it (attach to selected zone). During the uploading I need to visualize the process with some custom progress indicator (actually it can be `CircularProgressIndicator`, whatever). The image can be downloaded succesfully or failed. If image was successfully downloaded it should inform the tree list to be refreshed, i.e. the selected node must already contains `map` key because floor map image is attached to zone. And if selected node will contain `map` key the `FloorMapBloc` will initiate the downloading image for further work (as it was described above). 

_It is true I have here a challenge because why do I need to download image if I know what I uploaded and I can show image at once. But how can I disable downloading in this case which is executing when zone is selected and contains `map` key. But this is for later_

After reading your pdf where Felix Angelov advises to use BLOC for _every feature_ (which is a piece of screen) and in our case it is an _"Add Floor Plan"_ button) I thought I need a third BLOC `FloorPlanUploadBloc` which will be responsible for showing button _"Add Floor Plan"_ and, of course, for showing progress indicator while uploading (or `Snackbar` when failed)

So schematically in BLOC relations I thought so:

`TreeBloc`.`refreshTreeNodes` to get tree nodes. When its state is `success` do `TreeBloc`.`updateSelection(1)`. `BlocListener` of `TreeBloc` listens for `success` state and check is `TreeBlocState`.`selectedNode`.`hasMap` == `true`. If so it initiate `FloorPlanBloc`.`refreshFloorPlan(selectedNode.map.id)` and the `BlocBuilder` of `FloorPlanBloc` draws the image. If `hasMap` is `false` the `BlocBuilder` of `FloorMapUploadBloc` draws the button "Add Floor Plan".

```dart
final treeBloc = TreeBloc();
final floorMapBloc = FloorMapBloc();
final floorMapUploadBloc = FloorMapUploadBloc();
```

```dart
BlocProvider.value(
  value: treeBloc,
  BlocConsumer(
    listener: (_, state) {
      if (state.isSuccessful) {
        floorPlanBloc.refreshFloorPlan(state.selectedZone.data.map.id);
      }
    }
    builder: (_,state) {
      final selectedZone = state.selectedNode.data;
      Row(
        children: [
          TreeView(),
          Expanded(
            child: selectedZone.hasMap ?
              BlocProvider.value(
                value: floorMapBloc(),
                child: FloorMapView(), // in this widget I can manage scaling/scrolling and save state
              ) : 
              BlocProvider.value(
                value: floorMapUploadBloc,
                child: FloorMapUloadButton(), // in this widget I can call zoneBloc.updateSelection()
              ),
          ),        
        ],
      )
    },
  ),
),

```

Hope you understand more now. :)

**Comment by Gene-Dana** [comment]
Okay ! Well I hope you have your issue resolved !

**Comment by bambinoua** [comment]
Somehow yes but I don't like the approach and I feel it can be done better and more correct. 

I also have an idea to use 2 blocs. As I have a GUI structure like List/Detail, so first bloc is `TreeBloc` which will respond for tree loading/node selection and second Bloc is a `TreeDeailBloc` which will response for showing `Image` if zone has a floor plan and `Add Image` buton if zone does not have a free plan. The latter bloc will have 4 statuses `initial`, `downloading`, `uploading`, `success`. Basically the function of second bloc is showing an image so I can consider `downloading` and `uploading` statuses as combined `waiting` and share `failure` as it is not important when error is occurred.

What do you whink about this idea?

P.S. I've attached a short video with GUI.


https://user-images.githubusercontent.com/45417992/223043768-7dc1c02c-7d02-4918-87d7-6724b7fad2f0.mp4

**Comment by bazl-E** [comment]
i have a situation, in my app in notification feature 

- app shows a list of notification
- user can pull down to refresh
- user can pull up to load more (pagination)
- user can filter notification by date

when user trigger a loadMore/InitalLoad event while a refresh event is in progress i will cancel the new event using transformer so only one event will take place at a time.
when user applies a filter i will update the ui right at the moment so the event will call and filter will take place in the bloc
but the problem here is 

User refreshed/loadmore requested in  the page while it happening he also tried to apply a filter, 
in the bloc both event run at the same time but  refresh  took 10 seconds to complete but filter only took 5 seconds to complete 

so the user will see the filtered data first then suddenly the refresh event emit a new state and data is reset.

how can i handle situation like this ????


state class
```
class NotificationsState extends Equatable {
  const NotificationsState({
    this.currentPage = 0,
    this.isFiltered = false,
    this.canLoadMore = false,
    this.unreadNotificationCount,
    this.updateRefreshController = false,
    this.notificationsFetchStatus = DataFetchStatus.idle,
    this.notificationsList = const [],
    this.appliedDateFilterRange,
  });
  final int currentPage;
  final bool isFiltered;
  final bool canLoadMore;
  final bool updateRefreshController;
  final int? unreadNotificationCount;
  final DataFetchStatus notificationsFetchStatus;
  final List<NotificationModal> notificationsList;
  final DateTimeRange? appliedDateFilterRange;
  @override
  List<Object?> get props => [
        currentPage,
        isFiltered,
        canLoadMore,
        updateRefreshController,
        unreadNotificationCount,
        notificationsFetchStatus,
        notificationsList,
        appliedDateFilterRange,
      ];

  NotificationsState copyWith({
    int? currentPage,
    bool? isFiltered,
    bool? canLoadMore,
    int? unreadNotificationCount,
    DataFetchStatus? notificationsFetchStatus,
    List<NotificationModal>? notificationsList,
    DateTimeRange? appliedDateFilterRange,
    bool? updateRefreshController,
  }) {
    return NotificationsState(
      currentPage: currentPage ?? this.currentPage,
      isFiltered: isFiltered ?? this.isFiltered,
      canLoadMore: canLoadMore ?? this.canLoadMore,
      unreadNotificationCount:
          unreadNotificationCount ?? this.unreadNotificationCount,
      notificationsFetchStatus:
          notificationsFetchStatus ?? this.notificationsFetchStatus,
      notificationsList: notificationsList ?? this.notificationsList,
      appliedDateFilterRange:
          appliedDateFilterRange ?? this.appliedDateFilterRange,
      updateRefreshController: updateRefreshController ?? false,
    );
  }
}

```

events 

```
abstract class NotificationsEvent extends Equatable {
  const NotificationsEvent();

  @override
  List<Object?> get props => [];
}

abstract class NotificationLoadEvent extends NotificationsEvent {}

class NotificationsInitialLoad extends NotificationLoadEvent {}

class NotificationsLoadMore extends NotificationLoadEvent {}

class NotificationsRefresh extends NotificationLoadEvent {}

class NotificationsUpdateReadStatus extends NotificationsEvent {
  const NotificationsUpdateReadStatus(this.notificationId);
  final String notificationId;

  @override
  List<Object> get props => [notificationId];
}

class NotificationsFilter extends NotificationsEvent {
  const NotificationsFilter(this.range);

  final DateTimeRange? range;
  @override
  List<Object?> get props => [range];
}

class NotificationsCountUpdate extends NotificationsEvent {
  const NotificationsCountUpdate(this.notificationCount);

  final int? notificationCount;
}

class NotificationsAdd extends NotificationsEvent {
  const NotificationsAdd(this.notification);
  final NotificationModal notification;

  @override
  List<Object> get props => [notification];
}

```

Notification Bloc 

```
class NotificationsBloc extends Bloc<NotificationsEvent, NotificationsState> {
  NotificationsBloc()
      : super(
          const NotificationsState(),
        ) {
    on<NotificationLoadEvent>(
      (event, emit) {
        if (event is NotificationsInitialLoad) {
          return _onNotificationInitialLoad(event, emit);
        }
        if (event is NotificationsLoadMore) {
          return _onNotificationsLoadMore(event, emit);
        }
        if (event is NotificationsRefresh) {
          return _onNotificationsRefresh(event, emit);
        }
      },
      transformer: droppable(),
    );

    on<NotificationsFilter>(
      _onNotificationsFilter,
      transformer: restartable(),
    );

    on<NotificationsAdd>(
      _onNotificationsAdd,
      transformer: concurrent(),
    );

    on<NotificationsUpdateReadStatus>(
      _onNotificationsUpdateReadStatus,
      transformer: sequential(),
    );
    on<NotificationsCountUpdate>(
      _onNotificationsCountUpdate,
      transformer: concurrent(),
    );
  }
  final HomeService _notificationService = serviceLocator<HomeService>();

  Future<void> _onNotificationInitialLoad(
    NotificationsInitialLoad event,
    Emitter<NotificationsState> emit,
  ) async {
    if ((state.notificationsList.isNotEmpty && !state.isFiltered) ||
        state.notificationsFetchStatus == DataFetchStatus.waiting) return;
    emit(
      NotificationsState(
        unreadNotificationCount: state.unreadNotificationCount,
        notificationsFetchStatus: DataFetchStatus.waiting,
      ),
    );
    final nextState = await _getDataWithState(currentPage: 0);
    emit(nextState);
  }

  Future<void> _onNotificationsLoadMore(
    NotificationsLoadMore event,
    Emitter<NotificationsState> emit,
  ) async {
    if (state.notificationsFetchStatus == DataFetchStatus.waiting) return;
    emit(state.copyWith(notificationsFetchStatus: DataFetchStatus.waiting));
    final nextState = await _getDataWithState(
      currentPage: state.currentPage,
      range: state.appliedDateFilterRange,
    );
    emit(nextState);
  }

  Future<void> _onNotificationsRefresh(
    NotificationsRefresh event,
    Emitter<NotificationsState> emit,
  ) async {
    if (state.notificationsFetchStatus == DataFetchStatus.waiting) return;
    emit(state.copyWith(notificationsFetchStatus: DataFetchStatus.waiting));
    final nextState = await _getDataWithState(currentPage: 0);
    emit(nextState);
  }

  Future<void> _onNotificationsFilter(
    NotificationsFilter event,
    Emitter<NotificationsState> emit,
  ) async {
    emit(
      NotificationsState(
        unreadNotificationCount: state.unreadNotificationCount,
        notificationsFetchStatus: DataFetchStatus.waiting,
        appliedDateFilterRange: event.range,
      ),
    );
    final nextState =
        await _getDataWithState(currentPage: 0, range: event.range);
    emit(nextState);
  }

  Future<void> _onNotificationsAdd(
    NotificationsAdd event,
    Emitter<NotificationsState> emit,
  ) async {
    emit(
      state.copyWith(
        notificationsList: [event.notification, ...state.notificationsList],
        unreadNotificationCount: (state.unreadNotificationCount ?? 0) + 1,
      ),
    );
  }

  Future<void> _onNotificationsUpdateReadStatus(
    NotificationsUpdateReadStatus event,
    Emitter<NotificationsState> emit,
  ) async {
    await _notificationService.updateReadState(
      notificationID: event.notificationId,
    );

    final notificationList = state.notificationsList
        .map(
          (e) => e.copyWith(),
        )
        .toList();

    var unreadCount = state.unreadNotificationCount ?? 0;
    for (final element in notificationList) {
      if (element.id == event.notificationId) {
        element.readStatus = 1;

        if (unreadCount >= 1) {
          unreadCount--;
        }
      }
    }
    emit(
      state.copyWith(
        notificationsList: notificationList,
        unreadNotificationCount: unreadCount,
      ),
    );
  }

  Future<void> _onNotificationsCountUpdate(
    NotificationsCountUpdate event,
    Emitter<NotificationsState> emit,
  ) async {
    if (event.notificationCount == null) return;
    emit(
      state.copyWith(unreadNotificationCount: event.notificationCount),
    );
  }

  Future<NotificationsState> _getDataWithState({
    required int currentPage,
    DateTimeRange? range,
  }) async {
    final response = await _notificationService.getNotificationData(
      pageNumber: currentPage,
      range: range,
    );
    if (response == null) {
      return state.copyWith(notificationsFetchStatus: DataFetchStatus.failed);
    }
    final newListOfNotifications = response.notifications ?? [];
    return state.copyWith(
      updateRefreshController: true,
      canLoadMore: newListOfNotifications.length >= dataFetchLimit,
      notificationsFetchStatus: DataFetchStatus.success,
      isFiltered: range != null,
      appliedDateFilterRange: range,
      currentPage: newListOfNotifications.isNotEmpty
          ? currentPage + dataFetchLimit
          : currentPage,
      notificationsList: currentPage == 0
          ? newListOfNotifications
          : [...state.notificationsList, ...newListOfNotifications],
    );
  }
}

```

**Comment by bambinoua** [comment]
@bazl-E why do post it here?! Is this related to topic (I see not)?

**Comment by Gene-Dana** [comment]
@felangel any suggestions on this?
