### ISSUE TITLE
fix: Test times out after 30 seconds

### ISSUE THREAD

**Issue by karimkod** [felangel/bloc#3754]
**Description**
Running a dart unit test using blocTest hangs and times out. When I run `dart test` I have the output indicating that the expectation have failed (which is intended) but after that the terminal hangs until it times out after 30 seconds. 

**Steps To Reproduce**

1. Go to [here](https://github.com/jebud-com/jebud-app/blob/bloc_test_failing/src/core/test/blocs/budget_bloc_test.dart#L77) 
2. run `dart test`

**Expected Behavior**
Test fails and terminal prompt for user input again. 

**Screenshots**
Terminal hangs in this state for a while 
![image](https://user-images.githubusercontent.com/11241957/221978762-11b2eb3e-43d1-4b67-af2c-325dfd8dd296.png)
and then 
![image](https://user-images.githubusercontent.com/11241957/221979015-4b14ee7f-b5d1-4ec9-8dc2-2b122be830ad.png)
**Additional Context**
I had issues with the issue especially when trying to run the test from a test explorer. Instead of returning a meaningful failure message, it returns "TimeoutException after 0:00:30.000000: Test timed out after 30 seconds. See https://pub.dev/packages/test#timeouts"

**Comment by karimkod** [comment]
I've identified that the issue is due to the use of `runZonedGuarded` [here](https://github.com/felangel/bloc/blob/master/packages/bloc_test/lib/src/bloc_test.dart#L199). Explained [here](https://stackoverflow.com/questions/69411627/why-does-runzonedguarded-prevent-following-code-from-executing#:~:text=You%20don%27t%20throw%20an%20error%20inside%20the%20runZonedGuarded%2C,function%2C%20the%20error%20zone%20gets%20in%20the%20way.)
So issues thrown inside the zone are not propagated outside of it. 
I can open a PR to fix that, but is there a reason for using `runZonedGuarded` instead of a simple try-catch-finally blocks?

**Comment by tenhobi** [comment]
Not sure, but maybe also related to https://github.com/felangel/bloc/issues/3692.

**Comment by felangel** [comment]
Hi @karimkod 👋 
I took a look and it looks like your expectation is incorrect in this case:

The following test passes as expected:

```dart
  blocTest(
      'Add a budget period with bloc test - should fail',
      build: () => BudgetManagerBloc(budgetRepository),
      setUp: () {
        when(
          () => budgetRepository.saveBudgetPeriod(
            any(that: isA<BudgetPeriod>()),
          ),
        ).thenAnswer((_) => Future.value());
      },
      act: (bloc) {
        final expectedStart = DateTime.parse("2022-01-01");
        final expectedEnd = DateTime.parse("2022-01-31");

        bloc.add(AddBudgetPeriod(start: expectedStart, end: expectedEnd));
      },
      expect: () => [
        DetailedBudget(
          period: BudgetPeriod(
            start: DateTime.parse("2022-01-01"),
            end: DateTime.parse("2022-01-31"),
          ),
        )
      ],
      verify: (bloc) {
        verify(
          () => budgetRepository.saveBudgetPeriod(
            any(that: isA<BudgetPeriod>()),
          ),
        ).called(1);
        verifyNoMoreInteractions(budgetRepository);
      },
    );
```

Looks like it was just a typo in the expected `DateTime`. Closing for now but let me know if you have any follow-up questions and I'm happy to continue the conversation 👍

**Comment by karimkod** [comment]
Hey @felangel,
Thanks for taking the time to look at this.
The purpose of this example I provided was to demonstrated a failed test that's why there was a wrong address. 
And the expected behavior is to have a failure but without a timeout after it which is not the case as you can see in the following screenshot. 
![image](https://user-images.githubusercontent.com/11241957/223370717-d7b6b1a4-cf0f-4364-88d8-a83c40a65b5b.png)

**Comment by Maxim-Filimonov** [comment]
Facing similar issue:
Timeout on this code. Error gets printed in the output
```
blocTest<NavigationCubit, NavigationState>(
      'select book',
      build: () => NavigationCubit(),
      act: (cubit) => cubit.onBookSelected(
        Book(author: 'test', title: 'test'),
      ),
      expect: () => <NavigationState>[
        NavigationInitial(
          selectedBook: Book(author: 'test', title: 'test'),
        ),
      ],
    );
```

This gives me a proper error:
```
test('select book', () {
      final cubit = NavigationCubit()
        ..onBookSelected(
          Book(author: 'test', title: 'test'),
        );
      expect(
        cubit.state,
        NavigationInitial(
          selectedBook: Book(author: 'test', title: 'test'),
        ),
      );
    });
```
Error:
```
Expected: NavigationInitial:<NavigationInitial(Book(test, test, null, null, null))>
Actual: NavigationInitial:<NavigationInitial(null)>
```
