### ISSUE TITLE
docs: fluttercountertutorial wrong example

### ISSUE THREAD

**Issue by sovetski** [felangel/bloc#3755]
**Description**

Hi,

There is an error on this documentation: https://bloclibrary.dev/#/fluttercountertutorial

This code is wrong:

`export 'cubit/counter_cubit.dart';
export 'view/view.dart'`

and should be replaced by

`export 'cubit/counter_cubit.dart';
export 'view/counter_view.dart'`

Edit: I just checked this link: https://github.com/felangel/bloc/tree/master/examples/flutter_counter/lib/counter/view

And there is a "view.dart" file but there is no explanation on the documentation

**Comment by felangel** [comment]
Hi @sovetski 👋 
Thanks for opening an issue!

The `view.dart` acts as a barrel file which allows us to `import .../lib/counter/counter.dart` to import all publicly available parts of the counter feature. Closing this for now but feel free to comment with any follow up comments/questions and I"m happy to continue the conversation 👍
