### ISSUE TITLE
feat: add initialize() to all blocs, similarly as close()

### ISSUE THREAD

**Issue by O-Hannonen** [felangel/bloc#3759]
**Description**
Many bloc and cubits have some initialization steps, that shall run when the object is created. Often times people create own initialize() functions inside the bloc, and call it from the constructor, like so:
```dart
class CounterCubit extends Cubit<int> {
  CounterCubit() : super(0) {
    initialize();
  }

   void initialize() {
     /// Initialize the cubit
   }
}
```

How ever, this approach usually leads to the constructor having side effects, and that can make for example tests more complicated and harder to maintain. For testing purposes, it is much cleaner to keep  control of when the initialize() method is called. This being said, another approach to calling initialize method is when creating the bloc/cubit:

```dart
return BlocProvider<CounterCubit, int>(
  create: (_) => CounterCubit()..initialize(),
  child: SomeWidget(),
);
```

While this approach works perfectly fine, it could be made cleaner by the bloc and flutter_bloc. If `BlocBase` would have initialize() method, all of the blocs/cubits would have it as well and they could override it if necessary. This means that `BlocProvider` could have parameter `autoInitialize`, which would automatically call initialize, the same way it closes cubits/blocs automatically. This way the syntax would change to:
```dart
return BlocProvider<CounterCubit, int>(
  create: (_) => CounterCubit(),
  child: SomeWidget(),
);
```

When bootstrapping the cubits/blocs for tests, the parameter could be overriden to false. 
```dart
return BlocProvider<CounterCubit, int>(
  create: (_) => CounterCubit(),
  autoInitialize: false, // defaults to true, overriding to false
  child: SomeWidget(),
);
```

**Desired Solution**

[Here](https://github.com/O-Hannonen/bloc/commit/2a345083645775a5d8b69a3c6423183cfc1cb012) is an example implementation

**Comment by tenhobi** [comment]
Well, "yes," `close` is automatically called. But its purpose is not to be an event; it exists as a "destructor," as it is guaranteed that the method is the last to be run in bloc. Aka, this method should not alter the bloc state by any means.

Now you can argue that the `initialize` method would have the same use case. And it might, sure. But I think many beginners would use it wrong. However, I am not sure if a bloc should be responsible for initializing some heavy listeners, and maybe some dependency injection or service that would abstract would be a better fit.

But yea, I might see a use case now, but still, I don't think it is the feature I would vote for. Let's see what others think tho. :)

**Comment by Gene-Dana** [comment]
I think this problem has been adequately solved by standard initializer lists, no?

**Comment by O-Hannonen** [comment]
Surely its possible to setup `StreamSubscription`s in initializer lists, but that way they would start listening when the object is created. Having separate `initialize` method would give more control over when those listeners are set up. But anyways, maybe this use-case is not common enough to be included in the core library...

**Comment by felangel** [comment]
Hi @O-Hannonen 👋
Thanks for opening an issue!

Close exists because bloc creates StreamControllers internally which need to be closed when the bloc is no longer in use and dart. As @tenhobi mentioned it acts like a destructor for the bloc class.

I’m not sure I understand how initialize would be any different from putting code in the constructor body. In the example you shared, it would be up to the developer to manually call initialize on the bloc whenever it is instantiated.

Sure, in flutter code the provider could do that but blocs can be used outside of flutter code which would make the developer experience quite clunky imo.

For the above reasons and because this is functionality that can be achieved without modifying the core library, I’d prefer not to modify the core library. Let me know what you think and thanks again for the issue/discussion!

**Comment by O-Hannonen** [comment]
Yes, this can be achieved with the methods provided in the original comment. For flutter code, this just would have made the developer experience nicer. But I can see why this would be clunky outside flutter, and thus not being something to feature in the core library. Thanks for the discussion!
