### ISSUE TITLE
Bloc listener not triggered

### ISSUE THREAD

**Issue by tony123S** [felangel/bloc#3761]
I have a login screen. When logo is clicked, I want display a loading on top of it. The loading widget I put in `ContainerWithLoadingOverlay`.

**main.dart**

```
class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider(create: (_) => sl<OverlayLoadingCubit>()),
      ],
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        localizationsDelegates: [
          EasyLocalization.of(context)!.delegate,
        ],
        supportedLocales: EasyLocalization.of(context)!.supportedLocales,
        locale: EasyLocalization.of(context)!.locale,
        title: kAppTitle,
        theme: AppTheme.light,
        onGenerateRoute: AppRoute.onGenerateRoutes,
      ),
    );
  }
}
```
**log_in_screen.dart**

```
 return Scaffold(
        body: ContainerWithLoadingOverlay(    <--- this for loading 
      child: SingleChildScrollView(
          child: Padding(
              padding: const EdgeInsets.all(32.0),
              child: Center(
                child: Column(
                  children: [
                    const AppLogo(
                      width: 150,
                      height: 150,
                    ),
                    const SizedBox(height: 32),
                    InkWell(
                        onTap: () {
                          context.read<LogInCubit>().signIn(
                              SignInParams(
                                  email: _emailController.text,
                                  password: _passwordController.text));
                        },
                        child: Text(
                          "Welcome back.",
                          style: Theme.of(context).textTheme.headline4,
                        )),
                    const SizedBox(height: 32),
                    // _loginForm(context, isShown),
                  ],
                ),
              ))),
    ));
  }
```
**log_in_cubit.dart**
```

class LogInCubit extends Cubit<LogInState> {
  final OverlayLoadingCubit _loadingCubit;
  final SignInUseCase _useCase;

  LogInCubit(this._useCase, this._loadingCubit) : super(LogInLoading());

  Future<void> signIn(SignInParams params) async {
    _loadingCubit.startLoading();  
           ...
  }
}
```
**overlay_loading_cubit.dart**
```

class OverlayLoadingCubit extends Cubit<OverlayLoadingState> {
  OverlayLoadingCubit() : super(OverlayLoadingInitial());

   startLoading() {
    debugPrint("start loading");  <-- this line is able to print
    emit(IsLoadingState());  
    return;
  }
}
```
**container_with_loading_overlay.dart**
```

class ContainerWithLoadingOverlay extends HookWidget {
  final Widget child;

  const ContainerWithLoadingOverlay({Key? key, required this.child})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocListener<OverlayLoadingCubit, OverlayLoadingState>(
      listener: (context, state) {
        debugPrint("call from listener");  <--- this line not calling
        if (state is OverlayLoadingInitial) {
          context.loaderOverlay.hide();
        }

        if (state is IsLoadingState) {
          context.loaderOverlay.show();
        }
      },
      child: LoaderOverlay(
        useDefaultLoading: false,
        overlayWidget: const Center(child: CircularProgressIndicator()),
        child: child,
      ),
    );
  }
}
```
I expect the bloc listener in class ContainerWithLoadingOverlay will get triggered and loading dialog will show, but it not triggered..what's the issue?

Here the complete code

https://github.com/tony123S/sampleProject

**Comment by tenhobi** [comment]
Did you tried to debug it, aka add a breakpoint at the place of that debugPrint?

**Comment by tony123S** [comment]
> Did you tried to debug it, aka add a breakpoint at the place of that debugPrint?

ya,but it didnt go through the listener in `container_with_loading_overlay`

**Comment by tony123S** [comment]
it will went through  `emit(IsLoadingState());` only

**Comment by tenhobi** [comment]
Could you make a minimal reproducible example, so we can clone and test it? :)

**Comment by tenhobi** [comment]
Just a wild guess before I have more time to debug this, but couldn't it be that you used the DI wrong? Aka, creating both blocs using a factory?

```dart
sl.registerFactory(() => OverlayLoadingCubit());
sl.registerFactory(() => LogInCubit(sl()));
```

First, you provide `OverlayLoadingCubit` in here https://github.com/tony123S/sampleProject/blob/main/lib/app.dart#L15, which creates `OverlayLoadingCubit#1`, and then you create `LoginCubit` in here https://github.com/tony123S/sampleProject/blob/main/lib/app_route.dart#L13, that creates `OverlayLoadingCubit#2` and that is used to create `LogInCubit#1`.

The issue, therefore, could be that
- you listen to `OverlayLoadingCubit#1` at https://github.com/tony123S/sampleProject/blob/main/lib/presentation/screen/container_overlay.dart#L17
- you work with `LoginCubit#1` at https://github.com/tony123S/sampleProject/blob/main/lib/presentation/screen/log_in_screen.dart#L23, but that uses `OverlayLoadingCubit#2`, which you do not listen to and therefore any changes are listened/build.

**Comment by ymka** [comment]
Hi guys,
I've cloned a sample project and when I make click I can see loading.
@tony123S what result do you expect from that sample?

**Comment by tony123S** [comment]
@ymka  this has been fixed by @RBar

https://github.com/tony123S/sampleProject/pull/1
