### ISSUE TITLE
question: ListView with Blocs for each entry - Best practise for maintain the state?

### ISSUE THREAD

**Issue by DFelten** [felangel/bloc#3765]
I have a question about using blocs or cubits inside entries of a ListView. 

The problem is as follows: We are currently building a list of comments. Each comment can have replies that can be collapsed and expanded. These replies are loaded separately and kept in their own bloc. The problem is that the state of the entries is lost as soon as I scroll away. 

We have several ideas here now. One idea was to use KeepAlive. But this can probably lead to performance problems if there are many comments with a lot of replies. The alternative is to store each Bloc in a list and read from it if it already exists.

What would be the best solution for such a problem? Thank you in advance. A best practise here would help us a lot. 

To demonstrate the problem and our current solution, I've created a  [sample project](https://github.com/DFelten/list_view_bloc_example/blob/main/lib/main.dart). The example shows a simple list with the possibility to expand content. The state, whether the content should be visible, remains. 

Here you can see the relevant part:

```dart
class ListPage extends StatefulWidget {
  const ListPage({super.key});

  @override
  State<ListPage> createState() => _ListPageState();
}

class _ListPageState extends State<ListPage> {
  final Map<int, ExpansionCubit> expansionCubits = {};

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      itemCount: 150,
      itemBuilder: (_, index) => BlocProvider<ExpansionCubit>.value(
        value: _getCubitOrCreateNew(index),
        child: Entry(
          title: 'Item $index',
        ),
      ),
    );
  }

  ExpansionCubit _getCubitOrCreateNew(int item) {
    return expansionCubits.putIfAbsent(item, () => ExpansionCubit());
  }

  @override
  void dispose() {
    for (final ExpansionCubit cubit in expansionCubits.values) {
      cubit.close();
    }
    super.dispose();
  }
}
```

**Comment by Gene-Dana** [comment]
Hey there 👋🏼 I checked this out and I'm slightly confused

> The problem is that the state of the entries is lost as soon as I scroll away.

This was your initial problem correct?

> The example shows a simple list with the possibility to expand content. The state, whether the content should be visible, remains.

I'm seeing the state of each tile maintained in the example

**Comment by DFelten** [comment]
> I'm seeing the state of each tile maintained in the example

Exactly, we have found a solution here and this request is about what is the best practise for such a case. Is our solution already the most appropriate, or what is the best way to handle something like this?

**Comment by Gene-Dana** [comment]
I see. First thing I'd suggest is to organize your blocs/cubits as features which are organized by domain. 

Here is how the todos is organized:

![image](https://user-images.githubusercontent.com/45580241/227556597-31ed5581-bdeb-42f3-9d89-e9107cf6e456.png)

https://bloclibrary.dev/#/fluttertodostutorial

In this example there is a `Todos Overview` which holds a `List<Todo>`.  From here we have a few options when it comes to handling this expansion. 

Since this is a presentation layer concern, I'd lean towards using a `ListView.builder` on the `List<Todo>` to build stateful widgets that each hold the todo and a `bool Expanded`. I believe that will solve your problem.

Organizing like this is much more helpful to you because then you can really focus on the presentation layer exclusively without having to mix it with the business logic. Right now I believe you are mixing the two with an expansion and list cubit and that's counter to the suggested approach.

Let me know what you think !

**Comment by DFelten** [comment]
> I see. First thing I'd suggest is to organize your blocs/cubits as features which fall under a domain.

The provided example is of course just an example for showing the described problem. We of course use a logical folder and bloc structure in the described app.

> In this example there is a `Todos Overview` which holds a `List<Todo>`. From here we have a few options when it comes to handling this expansion.
> 
> Since this is a presentation layer concern, I'd lean towards using a `ListView.builder` on the `List<Todo>` to build stateful widgets that each hold the todo and a `bool Expanded`. I believe that will solve your problem.
> 
> Organizing like this is much more helpful to you because then you can really focus on the presentation layer exclusively without having to mix it with the business logic. Right now I believe you are mixing the two with an expansion and list cubit and that's counter to the suggested approach.

I don't think that your solution works as described. The stateful widget is disposed as soon as the list scrolls further. The initState and build method is called each time the widget appears in the list. So the collapse state is also lost. In the solution, the collapse state would have to be in the bloc responsible for the entire list and no longer in the bloc of each entry. This works for the simple example, but not if the entry bloc does more. Therefore, we currently keep it in a list of cubits.

The actual problem is of course much more complex, but it is easier to illustrate it with a simple bool. As described above, our app has a list of comments. Each comment can have replies that can be collapsed and expanded. These replies are loaded separately and kept in their own bloc. The problem is that the state of the entries is lost as soon as we scroll away. So we have to keep the bloc somehow alive.

**Comment by Gene-Dana** [comment]
> I don't think that your solution works as described. The stateful widget is disposed as soon as the list scrolls further.

I haven't tested this and I may be wrong here. The way the Todo example handles this is by adding a bool variable to the model directly when it's converted from JSON to the application domain.

Here is a little video explaining exactly where that happens
https://www.loom.com/share/1505326e935549bcaf72a2df300f78b9

**Comment by DFelten** [comment]
Thanks for the video and the work you had with it. But it is not about such basics. Of course I can use the ListBloc to affect the entries and put in a value. This value is also kept if the value is stored in the ListBloc. 

As soon as the entries of a list contain further logic (for example fetch and display data from an API) this is no longer so simple. Then another bloc is needed to take care of this. 

The described example (loading the replies of a comment) has such a logic. Here we have two possibilities as far as I can see:

- We use caching and need to keep the state (collapsed or expanded) in the ListBloc.
- We use a list of blocs, each belonging to an entry and holding the replies 

Both solutions work. The initial question was if these are good solutions or if there are better ideas.

Here are three screenshots of one of our apps to illustrate the behaviour ([iOS](https://apps.apple.com/us/app/china-gadgets-the-gadget-app/id545265214) and [Android](https://play.google.com/store/apps/details?id=de.appetites.chinagadgets&hl=en&gl=US)):

A comment without loaded answers with the possibility to fetch the answers from the API and display them nested.

<img width="200" alt="CleanShot 2023-03-24 at 19 44 47@2x" src="https://user-images.githubusercontent.com/1169185/227612951-703b26f1-39e7-4b82-aaed-a5abbebf8608.png"> 

After the answers are loaded, they are displayed.

<img width="200" alt="CleanShot 2023-03-24 at 19 45 03@2x" src="https://user-images.githubusercontent.com/1169185/227613029-e47259a6-2527-42d2-9399-1bda3ab9fff0.png">

After ten answers more can be fetched.

<img width="200" alt="CleanShot 2023-03-24 at 19 45 16@2x" src="https://user-images.githubusercontent.com/1169185/227613067-a5f2b6bf-04f7-4fda-8312-a8293cd466ee.png">

Here we have different loading states and it is very complicated to keep everything in one bloc and still display loading animations. Hence the need for more blocs.

Maybe now it is clearer why I asked this question in the beginning.

**Comment by Gene-Dana** [comment]
> Here we have different loading states and it is very complicated to keep everything in one bloc and still display loading animations. Hence the need for more blocs.

Hey there 👋🏼 Now I understand.

Here's the structure that I think would fit you best

chat repository - feed bloc - thread bloc

You can look to the Todos example:

todos repository - todos overview - edit todo

When the edit todo bloc is constructed it takes a specific todo and you can do the same thing with the chat feed. Pass into the thread bloc a chat model which then manages the call for requesting the answers, showing the load indicator etc..

**Comment by felangel** [comment]
Closing for now since it appears as though there are no actionable next steps. Feel free to comment with any follow up questions and we're happy to continue the conversation 👍
