### ISSUE TITLE
Using different boxes for different users so that it does not show data of one user to another user

### ISSUE THREAD

**Issue by faisalansari0367** [felangel/bloc#3766]
**Description**

I am saving some data which belongs to user A but when i log in as user B i can see the data of A which i don't want 

**Desired Solution**

Maybe if there's way to allow storing the data with a unique identifier such as userId or something

**Comment by tenhobi** [comment]
That is not an issue of Bloc. You have to create another instance of provider that holds Bloc for the new user when you switch. Or control one instance and reset the values.

If you wanna be able to keep the states for users while switching back and forth, that could be done using another bloc that would hold these states and be placed above all other blocs. Or maybe better to store these objects in some persistent storage, and with each user switch, you would load the data for the current user.

**Comment by felangel** [comment]
You can also set the `id` on a `HydratedBloc` to namespace the cached data.

**Comment by tenhobi** [comment]
I am closing this for now since there is no follow-up.
