### ISSUE TITLE
[question] VSCode extension generating code with 'part of'

### ISSUE THREAD

**Issue by felipecastilhos** [felangel/bloc#3768]
Hi, i'm new to flutter/dart so maybe this question should be obvious for a lot a people. 

But why the generated code from the VSCode extension use the 'part' directive? 

Reading the [dart documentations](https://dart.dev/guides/libraries/create-library-packages#organizing-a-library-package) it's recommended to avoid it.

Here is an example:

```
part of 'chat_bloc.dart';

class ChatState extends Equatable {
  const ChatState({required this.chatMessage});

  final ChatMessage chatMessage;

  @override
  List<Object> get props => [chatMessage];

  ChatState copyWith({ChatMessage? message}) {
    return ChatState(chatMessage: message ?? chatMessage);
  }
}

class ChatInitial extends ChatState {
  const ChatInitial() : super(chatMessage: initialChatMessage);

  static const ChatMessage initialChatMessage = ChatMessage('test', null);
}

```
This is also makes my UIState tightly coupled with the bloc lib. Right? 💭

**Comment by felangel** [comment]
It's totally up to you but the reason is because with parts you can import `chat_bloc.dart` and have access to the public event and state classes whereas when you don't use part you either need to import the event and state files separately or create another barrel file to export everything.

```dart
import 'chart_bloc.dart' // with parts we get access to everything (bloc, events, and states) with a single import
```

Hope that helps 👍

**Comment by felipecastilhos** [comment]
Appreciated the really fast reply. 

I was thinking that was probably the reason why.

 thanks for the explanation 😌
