### ISSUE TITLE
Multiple same page cause Bloc context issue

### ISSUE THREAD

**Issue by OwnappIos** [felangel/bloc#3776]
Hi, greeting all, I have a question why this problem happen

The scenario: 
**CartBloc**  is a global bloc used in my cart feature.

Have cart page, product page.

The navigation: 

Go to **Cart page** -> (push to item page) -> **Item page** -> (can push again to cart page)  -> **Cart page**

**Push from Cart page to Item page code below used:**

`Navigator.of(context).pushName("/item").then(_) => context.read<CartBloc>().add(UpdateCartList())`

When I pop back until my first page which is Cart page, it will throw this issues 

```
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
flutter: 
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4334:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4348:6)
#2      Element.getElementForInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4379:12)
#3      Provider._inheritedElementOf (package:provider/src/provider.dart:339:38)
#4      Provider.of (package:provider/src/provider.dart:293:30)
#5      ReadContext.read (package:provider/src/provider.dart:649:21)
```

The issue refer to when I pop and trigger the refresh from my CartBloc

**Comment by tenhobi** [comment]
Hey, assuming you are using context in async context, the widget might be already deactivated and therefore you cannot use the context reference.

As a rule of thumb, before each `context.` call in async methods (after await etc.), you sure re-check that the widget is mounted.

**Comment by felangel** [comment]
Closing for now but feel free to comment with any follow up questions and we're happy to continue the conversation 👍
