### ISSUE TITLE
Language not changing in BlocProvider

### ISSUE THREAD

**Issue by tony123S** [felangel/bloc#3779]
There are two pages in my app, one is main screen, another is change language screen. I using BLocProvider to change the language in app, however the language still remains the same, only the font size is changed. What is wrong?

My full code as below:
https://github.com/tony123S/sampleTranslation

**Comment by tenhobi** [comment]
Hello @tony123S, first of all, you should read the easy localization docs https://pub.dev/packages/easy_localization#usage, where you can find that you should use `context.setLocale(Locale('en', 'US'));` (use that in the `listener` of the `BlocConstumer`) for setting a language and `context.locale` for retrieve it (use that in the `MaterialApp`).

If you have any other translation-related issue, please open an issue in that package. 🙌

Closing this issue for now. If you have any more Bloc-related questions, feel free to ask.

**Comment by tony123S** [comment]
thanks, it works
