### ISSUE TITLE
question: Difference of BlocProvider and Provider

### ISSUE THREAD

**Issue by aprashantz** [felangel/bloc#3780]
Below is a LoginScreen and my question is about differences of below two lines
Way 1: final authBloc = Provider.of<AuthBloc>(context);
Way 2: final authBloc = BlocProvider.of<AuthBloc>(context);
If I want to initialize bloc above way, UI changes according to state only in way 1, In way 2, i have to hot reload to see changes in UI.
My question is whats the difference in these two, and how to use it the efficient/proper way

********login screen code below******
`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';
import 'package:postreal/business_logic/auth_bloc/auth_bloc.dart';
import 'package:postreal/presentation/shared_layout/home_screen.dart';
import 'package:postreal/utils/validator.dart';
import 'package:provider/provider.dart';
import '../../constants/routes.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final _loginKey = GlobalKey<FormState>();
  final TextEditingController _emailField = TextEditingController();
  final TextEditingController _passwordField = TextEditingController();

  @override
  void dispose() {
    super.dispose();
    _emailField.dispose();
    _passwordField.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final authBloc = Provider.of<AuthBloc>(context);
    final state = authBloc.state;
    if (state is LoggedInState) {
      return const HomeScreen();
    } else if (state is ErrorState) {
      Fluttertoast.showToast(msg: state.message!);
    }
    final size = MediaQuery.of(context).size;
    return Material(
        child: SafeArea(
            child: Center(
                child: Form(
      key: _loginKey,
      child: SingleChildScrollView(
          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
        const Text(
          "PostReal",
          style: TextStyle(fontSize: 40),
        ),
        SizedBox(
          height: size.height * 0.02,
        ),
        TextFormField(
          controller: _emailField,
          keyboardType: TextInputType.emailAddress,
          validator: (value) {
            return TextFieldValidator.emailValidator(value);
          },
          autovalidateMode: AutovalidateMode.onUserInteraction,
          decoration: const InputDecoration(
              hintText: "Email",
              prefixIcon: Icon(
                CupertinoIcons.mail,
              )),
        ),
        SizedBox(
          height: size.height * 0.02,
        ),
        TextFormField(
          controller: _passwordField,
          autovalidateMode: AutovalidateMode.onUserInteraction,
          validator: (value) {
            return TextFieldValidator.passwordValidator(value);
          },
          obscureText: true,
          decoration: const InputDecoration(
              hintText: "Password", prefixIcon: Icon(CupertinoIcons.padlock)),
        ),
        SizedBox(
          height: size.height * 0.02,
        ),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 8.0),
          child: SizedBox(
            width: double.infinity,
            child: ElevatedButton(
                onPressed: () async {
                  if (_loginKey.currentState!.validate()) {
                    authBloc.add(LoginClickedEvent(
                      email: _emailField.text,
                      password: _passwordField.text,
                    ));
                  }
                },
                child: (state is LoadingState)
                    ? const LinearProgressIndicator()
                    : const Text(
                        "Login",
                        style: TextStyle(
                            fontWeight: FontWeight.bold, fontSize: 18),
                      )),
          ),
        ),
        SizedBox(height: size.height * 0.04),
        const Text("New User?"),
        TextButton(
            onPressed: (state is LoadingState)
                ? null
                : () {
                    authBloc.add(InitialEvent());
                    Navigator.pushReplacementNamed(
                        context, AppRoutes.registerscreen);
                  },
            child:
                const Text("Create Account", style: TextStyle(fontSize: 16))),
      ])),
    ))));
  }
}
`

**Comment by felangel** [comment]
Hi @aprashantz 👋 
Thanks for opening an issue!

A `BlocProvider` is a special type of provider that is designed to provide blocs and will automatically handle disposing the bloc when it is no longer being used. For that reason, you should always use a `BlocProvider` when providing/accessing a bloc. Hope that helps 👍
