### ISSUE TITLE
Question: How to structure the application with blocs properly

### ISSUE THREAD

**Issue by IntCleastwood** [felangel/bloc#3782]
I am very new to flutter, but immediately tried to find a UI/Business logic separation concept an I really love the concept of bloc. 

The concept itself is very clear to me, since in theory its very easy to just let the view respond to the a state represented by the bloc. But when i do some hands on, I noticed, its a bit more tricky to find an appropriate pattern to structure a complete application with meaningful blocs and assign the responsibilities to the right parts.

There are many tutorials out there but they are kept very easy for better undestanding, which is absolutely fine.

But my biggest problem is to find the right aspects to give a dedicated bloc to. 

To be more precise heres an example: 

I create a "navigation bloc" which represents the current view where the user is on. Since its only possible to be on one state, it could be "profileView", "settingsView", "productsView" etc. ... but what if i wanna create a new product by clicking on the "add" button in the products view? Is this just another "productCreateView" state or does this belong to a separate "product_bloc" where the state is "add new product" and the ui should just respond to this state? Should it be divided by "views" or by "domains" like "products", "settings", etc. or even both?

I think it is also a bit confusing, since widgets itself are always nested, but states are not. While you can't reach a product detail view from a settings page, the state can be reached by just triggering the right event. What should happen then in the UI?

Its really hard for me to get into finding the right events and states for representing the whole applications. Is opening a dialog, which is usually just an anonymous function call worth a "loadingDialog" state? If yes, should it be a general one since there are ususally more than one dialogue to open?

My general question: Is there some advice, which "aspects" of the program a separate bloc should be dedicated to or how to structure it properly? 

Sorry, i hope this was not too confusing getting my thoughts

Best regards

**Comment by tenhobi** [comment]
Generally, I would say blocs should only do "one thing". Doing more things leads to weird bugs, lose of state data etc. So whenever you feel some bloc does two things / handles multiple features, try to split it. But I would not say there is a only one correct way of doing it. It all comes down to tradeoffs.

You can also read https://bloclibrary.dev/#/architecture and other pages to learn about architecture tips etc.

Let us know if that answers your question.

**Comment by tenhobi** [comment]
Closing since there is no response. If you have more questions, feel free to comment.
