### ISSUE TITLE
Fix: Hydrated Bloc Inpersistent

### ISSUE THREAD

**Issue by codesculpture** [felangel/bloc#3792]
Hey, am having multiple instances of a same Hydrated Cubit. So those are basically dynamically generated. And at a time lot of these instances created in our app. For example, u can assume a search feature which build the UserCubit frequently as user types. So we need to store those in Hydrated Cubit. So here the data was inaccurate randomly some times.. i override the id (say username) by unique perfectly. I looked the whole package and am guessing the asynchronous calls to hive maybe delayed.. But also at some point if i change some instance's state and after (as user types) new list of userCubit is generated and there some other userCubit's state is changed (those are not happening all time, but sometimes) am not able to understand. So @felangel   just take a look or tell is there anything i can do

**Comment by Gene-Dana** [comment]
Hey 👋🏼 may you please share with us a small reproducible example? Perhaps a repo?

**Comment by codesculpture** [comment]
Right i am confused a lot. Like everything is messed in my implementation so for now i close this and sorry for making trouble guys
