### ISSUE TITLE
Question: How to restore a widget state when BlocBuilder is used?

### ISSUE THREAD

**Issue by petodavid** [felangel/bloc#3793]
**Description**

How can I use the BlocBuilder in way that when it rebuilds the same widget it preserves its previous state. For example the widget has a TextEditingController or a Switch button state and when BlocBuilder builds a new widget it creates a brand new instance. Here is my example where I would like to implement a BottomNavigationBar using bloc, however I lose the widget state all the time when the bloc changes the status. Here is a short demo video. As you can see when I change the tab the state of the widget goes back to the initial state. I tried using `AutomaticKeepAliveClientMixin` and `GlobalKeys` to solve this. But it did not work

https://user-images.githubusercontent.com/47359450/231473174-1b2b5560-895f-4888-9b05-69aff981bc50.mov

UI:
```
class Dashboard extends StatelessWidget {
  static String name = 'dashboard';

  const Dashboard({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => sl<DashboardCubit>(),
      child: Scaffold(
        body: BlocBuilder<DashboardCubit, DashboardState>(
          builder: (context, state) {
            if (state is DashboardShoppingCart) {
              return OnBoardingPage();
            }

            return Container(color: Colors.red);
          },
        ),
        bottomNavigationBar: BlocBuilder<DashboardCubit, DashboardState>(
          builder: (context, state) {
            final dashboardCubit = context.read<DashboardCubit>();

            return BottomNavigationBar(
              currentIndex: dashboardCubit.currentIndex,
              onTap: (newIndex) => dashboardCubit.onIndexChanged(newIndex),
              showSelectedLabels: false,
              showUnselectedLabels: false,
              type: BottomNavigationBarType.fixed,
              items: dashboardCubit.dashboardItems
                  .map(
                    (item) => BottomNavigationBarItem(
                  icon: item.icon,
                  tooltip: item.tooltip,
                  label: '',
                ),
              )
                  .toList(),
            );
          },
        ),
      ),
    );
  }
}

```

Cubit:

```
class DashboardCubit extends Cubit<DashboardState> {
  int currentIndex = 0;
  DashboardCubit() : super(DashboardHome());

  List<DashboardState> get dashboardItems => [
        DashboardHome(),
        DashboardShoppingCart(),
        DashboardNotifications(),
        DashboardInvoices(),
      ];

  void onIndexChanged(int newIndex) {
    currentIndex = newIndex;
    final selectedState = dashboardItems.elementAt(newIndex);
    emit(selectedState);
  }
}

```

States:

```
abstract class DashboardState extends Equatable {
  final Icon icon;
  final String tooltip;

  const DashboardState({
    required this.icon,
    required this.tooltip,
  });
}

class DashboardHome extends DashboardState {
  DashboardHome()
      : super(
          icon: Icon(Remix.home_fill),
          tooltip: 'home'.tr(),
        );

  @override
  List<Object?> get props => [icon.toString(), tooltip];
}

class DashboardShoppingCart extends DashboardState {
  DashboardShoppingCart()
      : super(
          icon: Icon(Remix.shopping_cart_2_fill),
          tooltip: 'shoppingCart'.tr(),
        );

  @override
  List<Object?> get props => [icon.toString(), tooltip];
}

class DashboardNotifications extends DashboardState {
  DashboardNotifications()
      : super(
          icon: Icon(Remix.notification_2_fill),
          tooltip: 'notifications'.tr(),
        );

  @override
  List<Object?> get props => [icon.toString(), tooltip];
}

class DashboardInvoices extends DashboardState {
  DashboardInvoices()
      : super(
          icon: Icon(Remix.file_list_fill),
          tooltip: 'invoices'.tr(),
        );

  @override
  List<Object?> get props => [icon.toString(), tooltip];
}
```

**Comment by Gene-Dana** [comment]
I believe you are automatically closing the widget tree when you navigate to a new tab (alongside the state)

How about hydrated bloc?

**Comment by petodavid** [comment]
> I believe you are automatically closing the widget tree when you navigate to a new tab (alongside the state)
> 
> How about hydrated bloc?

As far as I know hydrated bloc is used for restoring the bloc state when the application starts. However in my case we are talking about keeping the same widget state in a `BlocBuilder` between different bloc states. Please correct me if I'm wrong

**Comment by codesculpture** [comment]
> > I believe you are automatically closing the widget tree when you navigate to a new tab (alongside the state)
> > 
> > How about hydrated bloc?
> 
> As far as I know hydrated bloc is used for restoring the bloc state when the application starts. However in my case we are talking about keeping the same widget state in a `BlocBuilder` between different bloc states. Please correct me if I'm wrong

Hydrated bloc restore whenever it invokes...so it can help u

**Comment by felangel** [comment]
@petodavid is this still an issue? If so can you please provide a link to a minimal reproduction sample?
Thanks!

**Comment by felangel** [comment]
Closing for now but feel free to provide a minimal reproduction sample if this is still an issue and I'm happy to take a closer look, thanks!
