### ISSUE TITLE
How to call method inside tabview to call api and reload content inside the current tab using bloc?

### ISSUE THREAD

**Issue by VickyPrajapati24** [felangel/bloc#3798]
I have already created this issue but it was closed due to not provided minimal code for reproduction. #3778 

I have a tab bar with tab bar view. Each tab will have different instance of same widget. I have passed tab type in parameter so widget will call api for that type only in the specific tab. All this works fine. Now i wanted to call the same api which is inside the tabview's widget with the search text. Search bar is on the top and outside of tab bar. So when user complete typing i want to call api call method which is inside the tabview's widget. How to achieve it?

Please check the attached demo project repo link... It has sample api so ignore if it doesn't pass search text in api.. I have made sample api call which have search parameter. if user write any text in search bar. it should call the fetchtodo method of of tabview's current tab.

https://github.com/VickyPrajapati24/tabviewflutter

Looking for quick response.. Thanks in advance...
Note:  I don't want to write api call in the widget where tab bar exist because i don't want to manage current state of each tab widget's in root widget.

**Comment by VickyPrajapati24** [comment]
@felangel can you please help me to resolve this...

**Comment by tenhobi** [comment]
Don't really understand what you want. You can call API even from some other Bloc.

**Comment by tenhobi** [comment]
Since there has been no reply, I am closing this issue. Feel free to reopen it if needed.
