### ISSUE TITLE
How to use flutter bloc inside library/package

### ISSUE THREAD

**Issue by giaur500** [felangel/bloc#3799]
Usually, blocs are provided at my app top level or as a parent for specific widget. What is correct way to provide/create bloc insatnce inside library/separate package? Apps using that package don't know anything about bloc/flutter bloc, all state management needs to be performed internally inside library.

My library exposes its api 2 ways:
- expose some method, that method takes  current context and displays a window, method is async and it returns Future with result after user performs some actions inside a window (windows means new page widget, pushed with navigator). 
- expose some widgets. As main app does not use bloc context management, widgets need to use callback methods to notify actions performed (if needed).

I think in first case I need to use `BlocProvider` inside `MaterialPageRoute` builder and in a second case exposed widget needs to be a `BlocProvider` or `MultiBlocProvider`. Is it correct way?

**Comment by tenhobi** [comment]
I think there is no correct way and it all depends on your specific use case and the way you or users want to interact with your package.

**Comment by felangel** [comment]
Closing for now since there aren't any actionable next steps. Feel free to [join the discord](https://discord.gg/bloc) if you'd like to discuss your particular setup in more detail, thanks!
