### ISSUE TITLE
fix: Authentication Bloc not triggering rebuild

### ISSUE THREAD

**Issue by ChinaeduO** [felangel/bloc#3815]
I have an application where the user needs to authenticate in order to have access. I am using the bloc library for state managing the state. My `AuthenticationBloc` holds a status streamed through the `authentication repository`. So if any event happens that changes the status the `Bloc` is aware of it. I took the [example code](https://bloclibrary.dev/#/flutterlogintutorial) as reference.

Now i want to use `go_router` for navigating. This is my SplashScreen Route:

```
GoRoute(
          path: KiGoRouter.splash,
          builder: (BuildContext context, GoRouterState state) {
            return BlocListener<AuthenticationBloc, AuthenticationState>(
              listener: (BuildContext context, AuthenticationState state) {
                if (state.status == AuthenticationStatus.authenticated) {
                  GoRouter.of(context).go(KiGoRouter.home);
                } else if (state.status == AuthenticationStatus.unauthenticated) {
                  GoRouter.of(context).go(KiGoRouter.login);
                }
              },
              child: Center(
                child: CircularProgressIndicator(),
              ),
            );
          }),
```

When the app starts and the user is unactuhenticated it redirects as it should and displays the login page. Now when the user enters the credentials and the `AuthenticationBloc` status changes to authenticated nothing happens. It stays on the login screen.

I even tested to write the code inside the redirect of `GoRouter` but its the same behaviour. It seems like inside of `GoRouter` the `Bloc` is not updated.

I habe used `get_it` to inject the `AuthenticationBloc` as a `singlton` and provided it before the construction of the MaterialApp.

Even when using context.push(x) to prevent the Listener from being removed from the widget tree, the behavior stays the same.

Has anyone a solution or hint on this?

**Comment by catalunha** [comment]
Perhaps my approach to this small project can help you.

```dart
Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark(useMaterial3: true),
      navigatorKey: _navigatorKey,
      builder: (context, child) {
        return BlocListener<AuthenticationBloc, AuthenticationState>(
          listenWhen: (previous, current) {
            return previous.status != current.status;
          },
          listener: (context, state) {
            if (state.status == AuthenticationStatus.authenticated) {
              _navigator.pushAndRemoveUntil<void>(
                  HomePage.route(), (route) => false);
            } else if (state.status == AuthenticationStatus.unauthenticated) {
              _navigator.pushAndRemoveUntil<void>(
                  LoginPage.route(), (route) => false);
            } else {
              return;
            }
          },
          child: child,
        );
      },
      routes: {
        '/': (_) => const SplashPage(),
...
```

**Comment by neoacevedo** [comment]
Currently the BlocListener isn't catching the states changes, no matter if is an authentication, a simple textfield change or whatever.
