### ISSUE TITLE
docs: Discussion - Bloc-to-Bloc communication recommendations

### ISSUE THREAD

**Issue by wujek-srujek** [felangel/bloc#3816]
Hi Felix (@felangel).

First off, I'm sorry if this is not the right place for discussion, it used to work fine here but I've been away for a long time so please forgive me.

After a many months hiatus, I'm back to Flutter with a vengeance, and back to my favourite state management library. I decided to see what changed and was very surprised to read the [Bloc-to-Bloc Communication](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication) section. It seems to be making statements that many people (at least in my surroundings) don't agree with, and I would like to ask you for your opinion on an approach we have been employing:

1. You essentially officially recommend against Bloc-to-Bloc communication, and I would consider the main reason controversial: 
   > Generally, sibling dependencies between two entities in the same architectural layer should be avoided at all costs

   Where does this rule come from? If you take a look at e.g. onion or port-adapters (hexagonal) architectures, nowhere do they prohibit components in the same layer ('siblings') from talking to each other. The only 'bad'/wrong dependencies are pointing 'outside' (e.g. a repository knowing a Bloc). I have a lot of backend experience and it is also day-to-day business to call a component with business logic by another component in the same layer.
1. The official recommendation basically kills Bloc composition - you recommend against it - while if you consider other libraries, like `provider` or `riverpod` (to name the most written-about ones recently, apart from Bloc), they actively promote it (with `ProxyProvider` and `Ref.watch(someOtherProvider)`, accordingly).
1. The recommended solutions are not ideal:
   1. Connecting the blocs in the widget - IMHO this puts too much logic into the widget, and will also result in nesting and more complicated code in the `build` method. For example, when the UI depends on the state of `BlocB`, which in turn is triggered by a change in `BlocA`, you need a `BlocListener<BlocA>` and a `BlocBuilder<BlocB>`, where the listener is nested within the builder. (And this is just one use case, there are others.) For these reasons our team decided to completely reject this approach.
   2. Connecting the Blocs by using the same repository - but this either puts too much logic into the repository (see below for a use case, where I try to explain this point) which should only be concerned with fetching the data, or forces logic duplication in the Blocs, or requires creation of an 'aggregated repository' (or some kind of 'service') that keeps the common logic, and both Blocs use it. But I would like to put my logic in the Bloc (literally 'business logic component').

My example use case is the following (silly and contrived): there is a `WeatherBloc` that gives me weather forecast (it changes as the day goes by, and the Bloc periodically calls the repository to get weather data) and `ActivityBloc` which suggests what I could do now. `ActivityBloc` gets favourite activities for the current user from a repository, but what it suggests takes weather forecast into account - it will not suggest taking a walk if the forecast is a downpour. As you can see, `ActivityBloc` could really use some help from `WeatherBloc`.

(BTW, I keep saying Bloc this, Bloc that, but in reality I always start off with a `Cubit`; all that I write here still applies.)

1. I don't think this belongs to just a single Bloc, the tasks are different enough and I would like to split them. Imagine also that other features (with other Blocs) that do something completely different than suggesting activities, also depend on the weather - I don't want to put all that into `WeatherBloc`, I want to split all of this.
1. I could use the same `WeatherRepository` in both Blocs, but `ActivityBloc` would pretty much redo a lot of logic that `WeatherBloc` already does - the polling in this case.
1. If I choose to implement the logic in a repository of some kind, does it really belong there? I would argue that it doesn't. If it is an 'aggregated' repository (a repository using other repositories internally), it will also violate your rule (as there would be a dependency on sibling repositories).
1. I could add some kind of a service that uses `WeatherRepository` and implements the polling, and both Blocs could use it. But this would introduce yet another layer which is not really talked about in any Flutter-related documents. It would also work only on one level of dependencies - `ActivityBloc` needs forecast information - but what if some other components need to work with activity suggestions as their input? This could get pretty complex.

Now the solution that I have been very successful with in a few projects - Bloc-to-Bloc communication using abstractions:
1. `WeatherBloc` get its weather data from a `WeatherRepository` and issues `WeatherState`s - pretty normal stuff.
1. `ActivitiyBloc` gets the list the user's favorite activities from `ActivityRepository`, AND ALSO `WeatherState` from `WeatherBloc`, intersect these two pieces of information and provide `ActivitySuggestions` based on that.
1. `ActivityBloc` doesn't use `WeatherBloc` directly, nor vice-versa. `ActivityBloc` gets a `Stream<WeatherState>` and when the stream emits a new event, it triggers emitting new activity suggestions. `Bloc` just so happens to be able to give me a `Stream`, which is really neat.
1. The wiring is done by someone else, e.g. (simplified):
   ```dart
   final weatherBloc = WeatherBloc(weatherRepository);
   final activityBloc = ActivityBloc(
     activityRepository,
     Stream.value(weatherBloc.state).concatWith([weatherBloc.stream]),
   );
   ```
(I think Bloc used to immediately give the current state on subscription way back in the past, then it changed, that's why I 'prefix' the stream with the current state. In my app I have an extension for it.)

This approach been working wonderfully for me:
1. A change in a Bloc that other Blocs depend on triggers a cascade of changes, and the UI updates itself accordingly. (A cascade because we could imagine `ActivitySuggestions` triggering a change in some other Blocs/features.)
1. I consider this to be a clean approach ('details (concrete implementations) depend on abstractions' etc.). Except for one: `ActivityBloc` knows about `WeatherState` - but is this bad? It does need the forecast data in some form, and it makes it possible without introducing extra code for the sake of abstractions, or more layers.
1. I can test it nicely - in a test I can just create a Bloc with a faked stream dependency using a `StreamController` and trigger changes and test reactions.

I have never had to wire the Blocs the other way round: continuing from my example above, I never needed `WeatherBloc` to know `ActivityBloc` to trigger a change. In my head this would be backwards (as `WeatherBloc` would need to know all of the Blocs that depend on it). I could make it work by just giving an abstract `Sink<WeatherState>` to `WeatherBloc`, and the `Sink` would be a 'multicast sink' that would in turn push the new state to other Blocs, and all that would be wired when the application is constructed. But I have never needed it this way, it does sound much more complex, and wrong.

I would be interested in your thoughts about our approach described in this essay. Is it a violation of some principles that don't occur to me?

Cheers.

**Comment by WieFel** [comment]
I would also like to describe our use case (CC @stev3nsen): we were trying to use the [Connecting Blocs through Presentation](https://bloclibrary.dev/#/architecture?id=connecting-blocs-through-presentation) approach, but encountered some problems with it.

The use case looks as follows (simplified):
On one page of our app (page 1) we have a list of entries. The same entries are displayed on a map (Google map) on a separate page (page 2).
<img alt="Untitled-2022-10-25-1855" src="https://github.com/felangel/bloc/assets/8345062/3c6eb4ef-e01a-4742-929b-68dd36bdceaf" width="75%" />

Now we implemented a filter mechanism which allows to filter the entries by categories. The filter mechanism appears in both pages. The state of the filter is held in a bloc `FilterBloc`. The list's state is held in the `ListBloc`, the map's state is held in the `MapBloc`.
<img alt="Untitled-2022-10-25-1855(1)" src="https://github.com/felangel/bloc/assets/8345062/91650959-df4e-4aec-93e4-0493c0b81116" width="75%" />

Both pages should use the same filter state. I.e. if I select "filter 1" on page 1, then also page 2 should apply "filter 1" automatically. The `FilterBloc` is already used on both pages, thus the state of the filter bar itself is already synchronised between them.
However, the single states of `ListBloc` and `MapBloc` still need to be updated, once the filters in the `FilterBloc` change.
Therefore, what we do in the two pages' `build` functions is the following:
List page:
```dart
BlocListener<FilterBloc, FilterState>(
  listener: (context, state) =>
      context.read<ListBloc>().add(ListFilterChanged(state.filter)),
  child: BlocBuilder<ListBloc, ListState>(
    builder: (context, state) {
      // build list with filtered items
    },
  ),
)
```

Map page:
```dart
BlocListener<FilterBloc, FilterState>(
  listener: (context, state) =>
      context.read<MapBloc>().add(MapFilterChanged(state.filter)),
  child: BlocBuilder<MapBloc, MapState>(
    builder: (context, state) {
      // build map with filtered marker items
    },
  ),
)
```
Which is exactly like in the example from the docs.

The problem we encounter here is that the synchronisation of the Blocs now depends on the UI.
E.g. if we are on the list page and change the filters, the map page is not active and thus the state of the `MapBloc` will not get updated accordingly and will be inconsistent. When we later switch to the map, it's items are incorrect.
The same happens the other way round: if we are currently on the map page, modify some filter and then switch to the list page, the filter state there will be different (wrong).

We ended up sticking to an approach similar to the one mentioned by @wujek-srujek, which connects the Blocs directly, without the involvement of the UI.

**Comment by Maxim-Filimonov** [comment]
Found this article which explains connection via domain on specific example:
https://medium.com/flutter-community/blocs-with-reactive-repository-5fd440d3b1dc might be helpful

**Comment by blackchineykh** [comment]
> I would also like to describe our use case (CC @Stev3nsen): we were trying to use the [Connecting Blocs through Presentation](https://bloclibrary.dev/#/architecture?id=connecting-blocs-through-presentation) approach, but encountered some problems with it.
> 
> The use case looks as follows (simplified): On one page of our app (page 1) we have a list of entries. The same entries are displayed on a map (Google map) on a separate page (page 2). <img alt="Untitled-2022-10-25-1855" width="75%" src="https://private-user-images.githubusercontent.com/8345062/271285124-3c6eb4ef-e01a-4742-929b-68dd36bdceaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDQ0MDYsIm5iZiI6MTcwMTg0NDEwNiwicGF0aCI6Ii84MzQ1MDYyLzI3MTI4NTEyNC0zYzZlYjRlZi1lMDFhLTQ3NDItOTI5Yi02OGRkMzZiZGNlYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMDYyODI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVjMjU0NjAwNTFlNmU5ZWVlYmJmNWFmMzY1MjdjOWZhZGM1YzkzMjVmZDliZTIwZWFlYjJiZjc3NzhiNGJiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u7jHqCOqgoQmST_ZmyWoN5f4iMHS6lNU1rMmle2rmd4">
> 
> Now we implemented a filter mechanism which allows to filter the entries by categories. The filter mechanism appears in both pages. The state of the filter is held in a bloc `FilterBloc`. The list's state is held in the `ListBloc`, the map's state is held in the `MapBloc`. <img alt="Untitled-2022-10-25-1855(1)" width="75%" src="https://private-user-images.githubusercontent.com/8345062/271286829-91650959-df4e-4aec-93e4-0493c0b81116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDQ0MDYsIm5iZiI6MTcwMTg0NDEwNiwicGF0aCI6Ii84MzQ1MDYyLzI3MTI4NjgyOS05MTY1MDk1OS1kZjRlLTRhZWMtOTNlNC0wNDkzYzBiODExMTYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDZUMDYyODI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE2Mjg0ZGMxY2MyNzg3NjRkYWUyOTBjOTk1OThhM2Y5NjQxODQ0YmRiMDEwYTM5MDIzNDYxY2E5OGU1NDU5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LW6trH2QmGAN7rSVi8LnRZ5VJrQmoyQ6Kp-LmlXzcYI">
> 
> Both pages should use the same filter state. I.e. if I select "filter 1" on page 1, then also page 2 should apply "filter 1" automatically. The `FilterBloc` is already used on both pages, thus the state of the filter bar itself is already synchronised between them. However, the single states of `ListBloc` and `MapBloc` still need to be updated, once the filters in the `FilterBloc` change. Therefore, what we do in the two pages' `build` functions is the following: List page:
> 
> ```dart
> BlocListener<FilterBloc, FilterState>(
>   listener: (context, state) =>
>       context.read<ListBloc>().add(ListFilterChanged(state.filter)),
>   child: BlocBuilder<ListBloc, ListState>(
>     builder: (context, state) {
>       // build list with filtered items
>     },
>   ),
> )
> ```
> 
> Map page:
> 
> ```dart
> BlocListener<FilterBloc, FilterState>(
>   listener: (context, state) =>
>       context.read<MapBloc>().add(MapFilterChanged(state.filter)),
>   child: BlocBuilder<MapBloc, MapState>(
>     builder: (context, state) {
>       // build map with filtered marker items
>     },
>   ),
> )
> ```
> 
> Which is exactly like in the example from the docs.
> 
> The problem we encounter here is that the synchronisation of the Blocs now depends on the UI. E.g. if we are on the list page and change the filters, the map page is not active and thus the state of the `MapBloc` will not get updated accordingly and will be inconsistent. When we later switch to the map, it's items are incorrect. The same happens the other way round: if we are currently on the map page, modify some filter and then switch to the list page, the filter state there will be different (wrong).
> 
> We ended up sticking to an approach similar to the one mentioned by @wujek-srujek, which connects the Blocs directly, without the involvement of the UI.

Is there a reason you couldn't use a `ItemsBloc` instead that is providing the items to the map UI and the list UI and have the bloc provided further up the widget tree to be available to both UI?

**Comment by Gene-Dana** [comment]
Hey there ! I just saw a section in the docs regarding this. Does that mean we can close this? 

https://bloclibrary.dev/architecture/#bloc-to-bloc-communication

**Comment by chrisdlangham** [comment]
Please don't close this. We would like to hear why this rule is in place. 

As you mentioned here, we have been waiting to hear your thoughts
https://github.com/felangel/bloc/issues/4002#issuecomment-2037894674

**Comment by MrEdgarsz** [comment]
I also would like to get an answer before this issue is closed.

For me, and it seems for many others, bloc communication feels like a core part of the business logic, so the UI layer shouldn’t be handling it. Especially in cases where one bloc needs to respond to another’s state changes.

Additionally, marking `emit` as internal and restricting state emissions to the `Emitter` within the `on` directive feels a bit limiting. Both decisions seem to enforce an opinionated approach that impacts modularity. Even if we wanted to go against the recommended approach, the `emit` restriction blocks us, forcing us to disable the lint rule on a case-by-case basis.

I’d really like to understand the reasoning behind these choices.

**Comment by NickTsitlakidis** [comment]
My two notes on the solutions suggested in the official documentation : 

1. Orchestration of bloc operation through the widget layer

There are certain use cases when a bloc operation might need to trigger a side effect in another bloc. There's no guarantee that this business rule will always be applied if the orchestration happens inside a widget.

2. Listening to updates from the repositories

Am I the only who thinks that if I do that, then I move the state management to the repository? 
For example, let's suppose we have a `UserRepository` with a `refresh` method. The refresh will be called by a `BlocB` and another `BlocA` would listen to the changes coming from a user stream in the repository. 

This will work but now part of the source-of-truth for the user state is moved to the repository. 
That doesn't feel valid to me at least.

**Comment by bw-flagship** [comment]
> Am I the only who thinks that if I do that, then I move the state management to the repository? For example, let's suppose we have a `UserRepository` with a `refresh` method. The refresh will be called by a `BlocB` and another `BlocA` would listen to the changes coming from a user stream in the repository.
> 
> This will work but now part of the source-of-truth for the user state is moved to the repository. That doesn't feel valid to me at least.

I think it is fine to put the source-of-truth into the repository. I use rxdart to make the UserRepository reactive, all blocs listen to the stream and update their state accordingly.

It gets more interesting when we don't talk about shared state, but about **shared business logic**. This should not live in a repository, but the architecture docs don't provide a solution.
I solve that by adding a new type of class in the domain layer (calling it Service or Manager) that contains the business logic and is referenced by several blocs.

**Comment by shaxxx** [comment]
Basically, answer is either

- you're doing it wrong since siblings in the same domain should not talk to each other
- move your bussiness logic outside of bussiness logic layer

For the first one, I could provide dozen examples, but others have proven the point. It's just wrong.
Even if we move it to another layer (ie. Repository) they would still need to talk to each other.

For the second: then what's the point od bussiness layer? How do you test it, maintain it and change it if I implement my logic 70% in bloc, 20% in repository, and 10% in the widgets?

You're promoting monolithic state.

**Comment by Gene-Dana** [comment]
Hey everyone.

Let me start by saying there is an infinite number of ways you can approach this. The reason why we're not coding in assembly, bits, or raw voltages is because we put layers of abstraction to help us better understand as we develop.

In this infinite world of options we decided on domain-driven layered architectures and in this approach the repository does not store state. 

It does not perform logic.

Its focus is to combine data sources into a functional domain that converts the objects in the data-domain into the application domain; i.e The Domain Transform

If you absolutely must store a piece of state in the repo (i.e the user model, certificates, etc) then a cache is the solution.

Look at the todos or the firebase login example

**Comment by loveoverflowdev** [comment]
> I also would like to get an answer before this issue is closed.
> 
> For me, and it seems for many others, bloc communication feels like a core part of the business logic, so the UI layer shouldn’t be handling it. Especially in cases where one bloc needs to respond to another’s state changes.
> 
> Additionally, marking `emit` as internal and restricting state emissions to the `Emitter` within the `on` directive feels a bit limiting. Both decisions seem to enforce an opinionated approach that impacts modularity. Even if we wanted to go against the recommended approach, the `emit` restriction blocks us, forcing us to disable the lint rule on a case-by-case basis.
> 
> I’d really like to understand the reasoning behind these choices.

I agree that referencing between components in the same layer is necessary in some cases, even though it should be used with care.

From my perspective, the main reason Bloc-to-Bloc communication is discouraged is due to lifecycle management. When two blocs hold references to each other, it can lead to coupling that makes disposal and memory management harder to reason about.

However, if the wiring between blocs happens in the view layer (e.g., via BlocListener, BlocBuilder, or through context access), and the view is properly disposed of, then the coupling is short-lived and typically not problematic.

So rather than banning bloc-to-bloc interaction completely, we should differentiate between temporary coupling (injected by view) and persistent references (held at construction time).

**Comment by shaxxx** [comment]
For all the people thinking about this, here's Gemini's take on this
https://share.google/aimode/qxbZXWWTRqrU2jR7W
