### ISSUE TITLE
question: can't add increase timer button to flutter_timer

### ISSUE THREAD

**Issue by sirgyula** [felangel/bloc#3819]
**Description**
I'm trying to extend the _flutter_timer_ example with a simple button, which adds 60 seconds to the timer, if it is not in _TimerRunInProgress_ state (button does nothing in that case). The UI updates on every press, the added observer shows the state change, but when I press start, it rolls back, and starts from one increment button press later (if I was pressing the button 5 times on 0:34, the UI shows 5:34, but after the start button, it starts counting down from only 1:34).

I've tried implementing custom == operator (correctly said it's not equal), also tried removing Equatable, did not help.
Also was trying to add something unique (a key) to the state, so it will not be the same, but it messed up the code completely.

What am I missing? I was thinking about I've messed up something with the ticker, and not the states, but that looks fine.

Many thanks!

Here is what I've currently added to the example:

A new button:
```dart
FloatingActionButton(
  child: const Icon(Icons.add),
  onPressed: () => state is TimerRunInProgress
      ? null
      : context.read<TimerBloc>().add(const TimerIncreaseMinute()),
),
```

A new event:
```dart
class TimerIncreaseMinute extends TimerEvent {
  const TimerIncreaseMinute();
}
```

A new handler with the binding:
```dart
TimerBloc({required Ticker ticker})
    : _ticker = ticker,
      super(const TimerInitial(_duration)) {
  on<TimerStarted>(_onStarted);
  on<TimerPaused>(_onPaused);
  on<TimerResumed>(_onResumed);
  on<TimerReset>(_onReset);
  on<TimerIncreaseMinute>(_onIncreaseMinute);
  on<_TimerTicked>(_onTicked);
}

void _onIncreaseMinute(TimerIncreaseMinute event, Emitter<TimerState> emit) {
  emit(TimerInitial(state.duration + 60));
}
```

**Comment by felangel** [comment]
Hi @sirgyula 👋 
You need to cancel the existing subscription and create a new one with an increased duration like:

```dart
void _onTimerIncreaseMinute(
    TimerIncreaseMinute event,
    Emitter<TimerState> emit,
  ) {
    _tickerSubscription?.cancel();
    _tickerSubscription = _ticker.tick(ticks: state.duration + 60).listen(
          (duration) => add(_TimerTicked(duration: duration)),
        );
  }
```

Hope that helps!
