### ISSUE TITLE
fix: event adds error using addError but erros in the testBloc is empty

### ISSUE THREAD

**Issue by moonkinology** [felangel/bloc#3825]
Hi, I have a problem asserting that errors are emitted using addError in the bloc and erros using the blocTest. 

Running the test in debug mode and overriding the onError method confirms that the error / exception gets thrown correctly but it cannot be verified in the test.
First I had this part in the catch part of a try/catch block and thought that might be the reason, then for the sake of testing I removed everything in my implementation to make it simple, but it made no difference and the test still fails.

Event: 
class SetReminder extends TodoEvent {
  final DateTime reminderDateTime;
  final Todo todo;

  const SetReminder(this.reminderDateTime, this.todo);

  @override
  List<Object> get props => [reminderDateTime, todo];
}

implementation:
  FutureOr<void> _onSetReminder(SetReminder event, Emitter<TodoState> emit) {
    addError(Exception("Failed to set reminder"), StackTrace.current);
  }

test:
      blocTest<TodoBloc, TodoState>(
        "set reminder fails",
        build: () => bloc,
        act: (bloc) => bloc.add(SetReminder(DateTime(2023, 12, 12), todo)),
        errors: () => [isA<Exception>()],
      );

result:
package:matcher                              expect
package:bloc_test/src/bloc_test.dart 248:28  testBloc

Expected: [<<Instance of 'Error'>>]
  Actual: []
   Which: at location [0] is [] which shorter than expected

Dependencies:
  flutter_bloc: ^8.1.2
dev: 
  test: ^1.22.0
  bloc_test: ^9.1.1

**Comment by AlexanderFarkas** [comment]
Hello!
Please, provide minimal reproducible example, which can be copy-pasted to reproduce the error.

**Comment by moonkinology** [comment]
Hi, thank you for your reply, here is the minimum code required to reproduce the same behavior:

**bloc:** 
```
import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:remindy/todo_bloc/todo_status.dart';

import '../models/todo.dart';

part 'todo_event.dart';

part 'todo_state.dart';

class TodoBloc extends Bloc<TodoEvent, TodoState> {
  TodoBloc() : super(const TodoState()) {
    on<SetReminder>(_onSetReminder);
  }

  FutureOr<void> _onSetReminder(SetReminder event, Emitter<TodoState> emit) {
    addError(Exception());
  }
}
```

**event:** 

```
part of 'todo_bloc.dart';

abstract class TodoEvent extends Equatable {
  @override
  List<Object> get props => [];

  const TodoEvent();
}

class SetReminder extends TodoEvent {
  final DateTime reminderDateTime;
  final Todo todo;

  const SetReminder(this.reminderDateTime, this.todo);

  @override
  List<Object> get props => [reminderDateTime, todo];
}

```
**state:** 
```
part of 'todo_bloc.dart';

class TodoState extends Equatable {
  final List<Todo> todos;
  const TodoState({
    this.todos = const [],
  });

  @override
  List<Object?> get props => [
        todos,
      ];

  @override
  bool? get stringify => true;

  TodoState copyWith({
    List<Todo>? todos,
  }) {
    return TodoState(
      todos: todos ?? this.todos,
    );
  }
}
```


**todo model:** 

```
import 'package:equatable/equatable.dart';
import 'package:flutter/cupertino.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:remindy/models/priority.dart';
import 'package:uuid/uuid.dart';

part 'todo.g.dart';

 
@immutable
@JsonSerializable()
class Todo extends Equatable {
  @override
  List<Object?> get props => [
        id,
        title,
        description,
        isCompleted,
      ];

  Todo({
    String? id,
    this.title = 'Todo',
    this.description = '',
    this.isCompleted = false,
  })  : assert(
          id == null || id.isNotEmpty,
          'id can not be null and should be empty',
        ),
        id = id ?? const Uuid().v4();

  final String id;
  final String title;
  final String description;
  final bool isCompleted;

  Todo copyWith({
    String? id,
    String? title,
    String? description,
    bool? isCompleted,
  }) {
    return Todo(
      id: id ?? this.id,
      title: title ?? this.title,
      description: description ?? this.description,
      isCompleted: isCompleted ?? this.isCompleted,
    );
  }
}

```
**test:** 
```

import 'package:bloc_test/bloc_test.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:remindy/models/todo.dart';
import 'package:remindy/todo_bloc/todo_bloc.dart';
import 'package:mocktail/mocktail.dart';


class TodoMock extends Mock implements Todo {}

void main() {
  late TodoBloc bloc;
  late Todo todo;

  setUp(() {
    bloc = TodoBloc();
    todo = Todo(
      id: "id",
      title: "title",
      description: "description",
      isCompleted: false,
    );

    registerFallbackValue(todo);
  });

  tearDown(() {});

  group("events", () {
    blocTest<TodoBloc, TodoState>(
      "set reminder fails",
      build: () => bloc,
      act: (bloc) => bloc.add(SetReminder(DateTime(2023, 12, 12), todo)),
      errors: () => [isA<Exception>()],
    );
  });
}

```

**Comment by felangel** [comment]
Hi @moonkinology 👋 
Thanks for opening an issue!

This is because `build` should be creating a new bloc instance instead of returning a reference to an existing bloc. If you change your test to the following it works as expected:

```diff
blocTest<TodoBloc, TodoState>(
  "set reminder fails",
-  build: () => bloc,
+ build: TodoBloc.new, 
  act: (bloc) => bloc.add(SetReminder(DateTime(2023, 12, 12), todo)),
  errors: () => [isA<Exception>()],
);
```

Hope that helps 👍

**Comment by moonkinology** [comment]
Thank you @felangel. It solved the problem. I was relying on the `setup` method for the recreation of a new instance before each test, since it worked for all other tests, but somehow it does not work here.

**Comment by felangel** [comment]
> Thank you @felangel. It solved the problem. I was relying on the `setup` method for the recreation of a new instance before each test, since it worked for all other tests, but somehow it does not work here.

blocTest has its own setup and requires that build actually creates a new bloc instance. Sorry for the inconvenience! You can still do something like:

```dart
void main() {
  TodoBloc buildBloc() => TodoBloc();

  blocTest<TodoBloc, TodoState>(
    build: buildBloc,
    …
  );
}
```
