### ISSUE TITLE
fix: Can not prevent disposing BloC widget during navigation between widgets

### ISSUE THREAD

**Issue by mamaly12** [felangel/bloc#3845]
Hi there,

I need help working with the bloc. Here's the scenario:

1. I have two components with stateless widgets (widget_A with screen_A and Bloc_A and widget_B with screen_B and  bloc_B ).

2. As a user, I see the widget_A first. After I click on an element in the screen_A, I'm redirected to the screen_B via navigation.push(), leading to the disposal of my Bloc_A.

3. In screen_B, If I click a back button, the "Navigator.of(context).pop()" is called, and I will be redirected to widget_A.

So, the question is: how can I prevent Bloc_A from disposing that I can reuse it after the pop method is called and I'm returned to the screen_A

Best,
Mohammad

**Comment by felangel** [comment]
Hi @mamaly12 👋 
Thanks for opening an issue!

That most likely means you're providing the bloc too low in the widget tree. If you want the bloc to persist across navigations you can either provide it globally (over MaterialApp etc.) or provide the bloc above a nested navigator:

```dart
BlocProvider(
  create: (context) => MyBloc(),
  child: Navigator(...),
)
```

Hope that helps 👍

**Comment by mamaly12** [comment]
Thank you @felangel for your help! I followed your guidance and moved the Bloc provider to a higher level, and everything worked perfectly.
