### ISSUE TITLE
fix: blocTest hangs on unhandled exceptions from flutter 3.10

### ISSUE THREAD

**Issue by slaci** [felangel/bloc#3848]
**Description**
When an exception is thrown in a bloc event then `blocTest` hangs forever (or until the defined timeout). This only happens from flutter 3.10 (dart 3). On 3.7.12 the test fails immediately, which is the expected behavior.

**Steps To Reproduce**

`lib/example_bloc.dart`:

```dart
import 'package:flutter_bloc/flutter_bloc.dart';

class ExampleEvent {
  const ExampleEvent();
}

class ExampleBloc extends Bloc<ExampleEvent, int> {
  ExampleBloc() : super(0) {
    on<ExampleEvent>((event, emit) => throw Exception('intentional error'));
  }
}
```

`test/bloc_test.dart`:

```dart
import 'package:bloc_test/bloc_test.dart';
import 'package:mypackage/example_bloc.dart';

void main() {
  blocTest(
    'unhandled exception',
    build: () => ExampleBloc(),
    expect: () => [0],
    act: (bloc) => bloc.add(const ExampleEvent()),
  );
}
```

**Expected Behavior**
The test fails immediately.

**Additional Context**

I think the problem is that the internal `testBloc` function wraps everything in `runZonedGuarded`. The [docs](https://dart.dev/articles/archive/zones) say errors are not propagated from a zone, which seems to be the case. So when the `test.TestFailure` is thrown from the zone's error handler, it does not go out the zone, so the outer `await` just hangs (if I wrap it in try/catch, that doesn't do anything).

In flutter 3.7.12 the same code works, test fails immediately. So maybe this was changed or bugged in dart 3, not sure.

**Comment by felangel** [comment]
Hi @slaci 👋 
Thanks for opening an issue!

I was able to narrow this down to a change in behavior introduced in `package:test >=1.22.2`. As a temporary workaround, you should be able to adjust your `package:test` constraint to:

```yaml
dev_dependencies:
  test: ">=1.0.0 <=1.22.1"
```

I filed https://github.com/dart-lang/test/issues/2020.

Let me know if that helps!

**Comment by slaci** [comment]
Thanks @felangel nice catch. I investigated a bit and commented my findings to your issue. Until its fixed I will just try to keep my tests green 😄 

I just had a problem (like emitter already closed exception) in my code and the test hanged and of course I thought I'm doing something very wrong, I don't close something. Took some time to find out it's the test library itself, but hopefully we are on track.

**Comment by slaci** [comment]
We got a response in the new issue. After investigating a bit more, the culprit is that the event handler rethrows the exceptions here: https://github.com/felangel/bloc/blob/flutter_bloc-v8.1.3/packages/bloc/lib/src/bloc.dart#L232

Is it really neccessary? It is only possible to catch that with `runZonedGuarded` which does not let you extract the error. If I replace `runZonedGuarded` by a `try/catch` (in bloc_test) and remove that `rethrow` then only 1 test fails. So it seems to be somewhat safe to remove that rethrow. Errors can be "catched" or gathered with the `onError` observer, as `blocTest` does it.

The test which fails:
https://github.com/felangel/bloc/blob/flutter_bloc-v8.1.3/packages/bloc_test/test/bloc_bloc_test_test.dart#L132

In that test `actualError` is assigned in the error callback, but from my tests that's not possible when the body of the zone is async. Trying with this code:

```dart
import 'dart:async';

void main() async {
  try {
    Object? err;
    final res = runZonedGuarded(
      () => throw Exception('oops'),
      (error, stack) => err = error,
    );
    print('Res: $res');
    print('Err: $err');
  } catch (e) {
    print('Error: $e');
  }
}
```

This code as is captures the error and will print `Res: null` and `Err: Exception: oops`. But if you make the body `async`, then `err` will be null. If you `await` the `runZonedGuarded` when the body is `async` then it just does not output anything. So I don't know why that test works when `blocTest` uses `runZoneGuarded`, but it looks very suspicious.

I have found this issue which seems to be related: https://github.com/dart-lang/sdk/issues/49457

**Comment by felangel** [comment]
@slaci I spent a bit of time refactoring the implementation to work around the change in behavior in `package:test`. Can you try the changes in #3854:

```yaml
dependency_overrides:
  bloc_test:
    git:
      url: https://github.com/felangel/bloc
      path: packages/bloc_test
      ref: ae87e30eb7091d31627f5e09338797c543653b42
```

And let me know if that behaves as expected?
Thanks! 🙏

**Comment by slaci** [comment]
@felangel thanks it seems to be working. Futures cannot cross the zones, but it looks like completer can workaround this. I thought about this before, but didn't try out before. From my testings it seems to be reliable.

**Comment by felangel** [comment]
@definitelyokay @wolfenrain @renancaraujo @KyleFin @cmc5788 if you’re able to test the changes in some larger projects that would be awesome!

**Comment by erickzanardo** [comment]
Tested and all working fine too!!!

**Comment by Kahoulam** [comment]
I'm currently experiencing the same issue described in #3848 while using Flutter 3.22.1. 

### Environment
Flutter version: 3.22.1
Dart version: 3.4.1
bloc version: 9.1.7
bloc_test version: 8.1.4
