### ISSUE TITLE
fix: whenListen returns type 'Null' is not a subtype of type 'MyState' in flutter 3.10

### ISSUE THREAD

**Issue by nerder** [felangel/bloc#3849]
**Description**
When running previously working tests, since the migration to null-safety and 3.10, now running the same test I receive an error like the following:

`type 'Null' is not a subtype of type 'MyStateState'`

**Expected Behavior**
The test to run correctly

**Comment by nerder** [comment]
I can also reproduce the issue reported here: https://github.com/felangel/bloc/issues/3848

**Comment by nerder** [comment]
Hey @felangel my bad, it was actually something to do with my test code when migrated to null-safety! Sorry for bothering

**Comment by nerder** [comment]
Hey Felix,

Sorry, it took me some time to actually reproduce it given that my app is quite complex, but here you have it: https://github.com/nerder/null-not-subtype-repro/blob/master/test/widget_test.dart

It seems to me that the problem is with `whenListen`, before null-safety it was not mandatory to specify an `initialState` as it was using `null` instead, but now as the error is stating:  `'Null' is not a subtype of type 'MyState'` so it's mandatory to set up an initial state when using `whenListen`.

This breaking change might require a new version of `bloc_test`, but let me know if I'm out of my way.

**Comment by felangel** [comment]
Hi @nerder 👋 
Thanks for the repro, I'll take a look tomorrow. In the meantime, `initialState` is still not mandatory even with sound null-safety so long as the test doesn't involve access the bloc's state.

**Comment by nerder** [comment]
Ok then, it might be that than. My tests were not fully migrated to null-safety, so I never noticed.

Might be interesting to add an explicit message that says that tho, it took me quite a while to figure it out.

When you have sometime please confirm if it's like you are supposing to, and then if you agree on a better error message I'll PR myself.

**Comment by paul-doherty** [comment]
Not sure where this issue is but I also had to add initialState for my test of a BlocConsumer after my upgrade to 3.10

**Comment by paul-doherty** [comment]
@nerder shouldn't initialState be mandatory then? Currently it is optional

**Comment by NicolasDionB** [comment]
It may be a noob question but how can I specify / pass an initialState? I'm struggling with this.

**Comment by paul-doherty** [comment]
It's an optional param on whenListen

**Comment by NicolasDionB** [comment]
Ok. I realize my issue is a bit different as I get the following message when creating my `MockBloc`:

`_TypeError (type 'Null' is not a subtype of type 'Stream<ManagerBaseState>')`

The error seems to be coming from the first line in this constructor:

```dart
_MockBlocBase() {
   when(() => stream).thenAnswer((_) => Stream<S>.empty());
   when(close).thenAnswer((_) => Future<void>.value());
}
```

I should probably create a new issue with that, unless someone has an idea!

**Comment by felangel** [comment]
> Ok. I realize my issue is a bit different as I get the following message when creating my `MockBloc` (_ManagerBaseState_ is my custom state for my bloc):
> 
> `_TypeError (type 'Null' is not a subtype of type 'Stream<ManagerBaseState>')`
> 
> The error seems to be coming from the first line in this constructor:
> 
> ```dart
> _MockBlocBase() {
>    when(() => stream).thenAnswer((_) => Stream<S>.empty());
>    when(close).thenAnswer((_) => Future<void>.value());
> }
> ```
> 
> I should probably create a new issue with that, unless someone has an idea!

If you're testing code that subscribes to a bloc's stream then you need to stub the stream using `whenListen`.

**Comment by NicolasDionB** [comment]
> > Ok. I realize my issue is a bit different as I get the following message when creating my `MockBloc` (_ManagerBaseState_ is my custom state for my bloc):
> > `_TypeError (type 'Null' is not a subtype of type 'Stream<ManagerBaseState>')`
> > The error seems to be coming from the first line in this constructor:
> > ```dart
> > _MockBlocBase() {
> >    when(() => stream).thenAnswer((_) => Stream<S>.empty());
> >    when(close).thenAnswer((_) => Future<void>.value());
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I should probably create a new issue with that, unless someone has an idea!
> 
> If you're testing code that subscribes to a bloc's stream then you need to stub the stream using `whenListen`.

Actually I'm just creating the bloc and I get the error. I'm really having a hard time understanding why. It's really the first line in _MockBlocBase() that fails:
```dart
when(() => stream).thenAnswer((_) => Stream<S>.empty());
```
It throws the following exception on creation:
`_TypeError (type 'Null' is not a subtype of type 'Stream<ManagerBaseState>')`

**Comment by felangel** [comment]
> > > Ok. I realize my issue is a bit different as I get the following message when creating my `MockBloc` (_ManagerBaseState_ is my custom state for my bloc):
> > > `_TypeError (type 'Null' is not a subtype of type 'Stream<ManagerBaseState>')`
> > > The error seems to be coming from the first line in this constructor:
> > > ```
> > > _MockBlocBase() {
> > >    when(() => stream).thenAnswer((_) => Stream<S>.empty());
> > >    when(close).thenAnswer((_) => Future<void>.value());
> > > }
> > > ```
> > > 
> > > 
> > > I should probably create a new issue with that, unless someone has an idea!
> > 
> > 
> > If you're testing code that subscribes to a bloc's stream then you need to stub the stream using `whenListen`.
> 
> Actually I'm just creating the bloc and I get the error. I'm really having a hard time understanding why. It's really the first line in _MockBlocBase() that fails:
> 
> ```dart
> when(() => stream).thenAnswer((_) => Stream<S>.empty());
> ```
> 
> It throws the following exception on creation: `_TypeError (type 'Null' is not a subtype of type 'Stream<ManagerBaseState>')`

Can you open a new issue for this with a minimal reproduction sample? Closing this issue as this appears to be working as expected. Thanks!
