### ISSUE TITLE
How to prevent printing errors in the console of the web when catch block executed  

### ISSUE THREAD

**Issue by mamaly12** [felangel/bloc#3855]
Hi there,
I used the BloC login to write my login. In the login_Bloc, for login submission, there's the following code which is called after the user clicks on the login button:

```
Future<void> _onSubmitted(
    LoginSubmitted event,
    Emitter<LoginState> emit,
  ) async {
      emit(state.copyWith(status: FormzSubmissionStatus.inProgress));
      try {
        await _authenticationRepository.logIn(
            username: state.username.value,
            password: state.password.value,
            organizationKey: state.organizationKey.value);
        emit(state.copyWith(status: FormzSubmissionStatus.success));
      } catch (_) {
        emit(state.copyWith(status: FormzSubmissionStatus.failure));
      }
    }
```

When I enter a wrong password or username, the code in the catch block is executed. After this emit, I will display the Snack bar in my screen according to the following code:

```
 listener: (context, state) {
        if (state.status.isFailure) {
          ScaffoldMessenger.of(context)
            ..hideCurrentSnackBar()
            ..showSnackBar(
              const SnackBar(content: Text('Authentication Failure')),
            );

        }
      },
      .
      .
```

The problem is, each time my application executed the catch block, an error is displayed in the console of the web browser:

![image](https://github.com/felangel/bloc/assets/7683251/9b4036b1-6ef2-4cc7-85a2-2fd0acf88397)

How can I prevent printing the catch errors in the console? Did I do anything wrong?
Thank you for your time and consideration,

Best,
Mohammad

**Comment by felangel** [comment]
Hi @mamaly12 👋 
That's working as expected because the console is logging networking errors. In your case it looks like you made an HTTP request which returned a 400 response and that's what the console is showing you. Hope that helps 👍

**Comment by mamaly12** [comment]
@felangel So I don't need to worry about the error logs. Thank you so much!
