### ISSUE TITLE
feat: State Mapper.

### ISSUE THREAD

**Issue by dylan-kwon** [felangel/bloc#3856]
**Description**

When exposing the state in a widget from Bloc or Cubit, I want to expose a mapped state object. For example, when displaying a LocalDate object as a formatted string on the screen, the widget may not need the LocalDate. Also, since both the LocalDate object and the `formatted String` object have to be managed simultaneously, there can be inconsistencies between the two values due to developer mistakes.

The date formatted as a string is a kind of derived state from the LocalDate object, so it should automatically change according to modifications in the LocalDate object, and it should not be editable arbitrarily.

**Desired Solution**

Currently, Bloc is exposing the state as a stream.
Allow the developer to expose a new stream arbitrarily mapped, and the widget reconstructs the screen with the mapped stream.

**Comment by Mohamed-Shalabi** [comment]
I think you can make the LocalData object private, and make a public getter for the formatted String (in the state class).

**Comment by felangel** [comment]
Closing this for now since there doesn't appear to be any actionable next steps. Feel free to provide additional context or questions if this is still an issue and I'm happy to continue the conversation 👍
