### ISSUE TITLE
docs: fluttercountertutorial Doesn't talk about counter/view/view.dart

### ISSUE THREAD

**Issue by tnmkr** [felangel/bloc#3857]
**Description**

https://bloclibrary.dev/#/fluttercountertutorial does not mention `lib/counter/view/view.dart` anywhere except in the last section where it is exported without any explanation. 

Its [repository](https://github.com/felangel/Bloc/tree/master/examples/flutter_counter) has the [file](https://github.com/felangel/bloc/blob/master/examples/flutter_counter/lib/counter/view/view.dart).

**Comment by felangel** [comment]
There is now a mention of the barrel file at https://bloclibrary.dev/#/fluttercountertutorial?id=barrel 👍
