### ISSUE TITLE
question: how to handle nested hydrated_blocs/hydrated_cubits 

### ISSUE THREAD

**Issue by novas1r1** [felangel/bloc#3868]
Hello,
I'm using hydrated_bloc/hydrated_cubit for the first time and for simple cubits everything worked fine. I do have a special case now, where I have a parent cubit (CubitA), which holds a List<CubitB> in its state. So it looks sth like:

```
class CubitA extends HydratedCubit<CubitStateA> {
  @override
  CubitAState? fromJson(Map<String, dynamic> json) {
    return CubitAState.fromJson(json);
  }

  @override
  Map<String, dynamic>? toJson(CubitAState state) {
    return state.toJson();
  }
}

class CubitB extends HydratedCubit<CubitStateB> { 
  @override
  CubitBState? fromJson(Map<String, dynamic> json) {
    return CubitBState.fromJson(json);
  }

  @override
  Map<String, dynamic>? toJson(CubitBState state) {
    return state.toJson();
  }
}

class CubitAState extends Equatable {
  final List<CubitB> cubitBList;
  ...
}
```

How am I supposed to handle this? Is it even possible? Sorry if that's a stupid question but I somehow can't figure out how to solve this. I'm working with json_serializable.

Thanks in advance

**Comment by novas1r1** [comment]
Hey @felangel,
I have a quite complex app which has multiple pgaes. Each page contains a custom painted flow chart which can change its state and sets, based on the state, variables for the flowcharts on other pages. CubitA holds all those flow chart cubits (CubitB) because it has to make a communication between them possible. Because everything kind of affects everything, I put all flowchart cubits as a list in the "master" CubitA and emit a new state with differently initiated CubitBs. I'm really sorry if this is more confusing now :D! It's very hard to explain and I couldn't find any other way to do it than to put the Cubits in a List in another Cubits state.

My goal is to kind of "cache" everything. So every flow chart state as well as the general state. It might be the case that the hydrated bloc is not the best option here but I thought if I could somehow cache the List<CubitB>, I could check if it works.

To make the base-problem easier to understand, I broke it down to the basics. So I think any example with just a CubitA (hydrated), which has a CubitB (also hydrated) in its state would generate the same question.

Please let me know if that in any way helped. If not I'm happy to build a small example.

**Comment by felangel** [comment]
Sorry for the delay! If `CubitB` is hydrated, then why do you need `CubitA` to be hydrated? I think it would be super helpful if you could create a minimal reproduction sample to better illustrate why you have this setup and what you're trying achieve. I feel like there is probably a better way to structure things so that you don't have a Cubit as part of the state of another Cubit 😅

**Comment by felangel** [comment]
@novas1r1 is this still an issue? If so can you provide anymore context? Thanks!

**Comment by novas1r1** [comment]
@felangel sorry for the late response. I'm currently trying to move my Cubits out of the state. It feels wrong and I hope I can find a better way. Therefore this can be closed for now. If I can't find any other way to do it, I will come back and provide the promised example.  Thanks for your help!
