### ISSUE TITLE
Question about "Flutter Timer Tutorial" and BLoC dispose()

### ISSUE THREAD

**Issue by antonkrasov** [felangel/bloc#387]
Hello,

First of all thanks a lot for the awesome project and support! I'm new to flutter and going through BLoC tutorials, and I have a question about Timer one - [https://felangel.github.io/bloc/#/fluttertimertutorial](https://felangel.github.io/bloc/#/fluttertimertutorial).

Why do we need to dispose TimerBloc inside `_MyAppState`:
```
@override
  void dispose() {
    _timerBloc.dispose();
    super.dispose();
  }
```

 if we use 

```
BlocProvider(
        bloc: _timerBloc,
        child: Timer(),
      )
```

and from my understanding it should be disposed automatically right now? Because we have 
```
BlocProvider({
    Key key,
    @required this.builder,
    this.child,
    this.dispose = true,
  })  : assert(builder != null),
        super(key: key);
```
automatic dispose enabled. 

Am I missing something?

Thanks a lot!

**Comment by felangel** [comment]
Hi @antonkrasov 👋 
Thanks for opening an issue!

You're completely right! I must've forgotten to update the tutorial docs.

I'll try to update the docs later this evening but in the meantime you can see the correct example code [here](https://github.com/felangel/bloc/blob/master/examples/flutter_timer/lib/main.dart).

Thanks again for pointing that out 💯

**Comment by felangel** [comment]
Just updated the tutorial in https://github.com/felangel/bloc/commit/804a1aee04320deb4b4195d5c5c18fe499024f08. You should be able to refresh the docs and see the latest version 👍 

Thanks again!
