### ISSUE TITLE
feat: discriminate same type of blocs

### ISSUE THREAD

**Issue by Jaew00Shin** [felangel/bloc#3872]
**Description**

```
final first = BlocA();
final second = BlocA();
return MultiBlocProvider(
  providers: [
    BlocProvider(create: (_) => first),
    BlocProvider(create: (_) => second),
  ],
  child: ...,
);
```

When we try to provide same type but different two blocs, 
we can only find onlly second object and cannot find first object 
from BlocListener or BlocBuilder at child.

**Desired Solution**

I want to discriminate them by naming as well as just type.

```
final first = BlocA();
final second = BlocA();
return MultiBlocProvider(
  providers: [
    BlocProvider(create: (_) => first, name: 'first',),
    BlocProvider(create: (_) => second, name: 'second'),
  ],
  child: ...,
);
```

```
return BlocBuilder<BlocA, StateA>(
    name: 'first'
    builder: ...
  );
```

**Comment by felangel** [comment]
Hi @Jaew00Shin 👋 
Thanks for opening an issue!

Can you please provide more context regarding why you would want to provide multiple instances of the same bloc to the same sub-tree? Thanks!

**Comment by felangel** [comment]
Closing for now since there is no reproduction sample. Feel free to provide a link to a minimal reproduction sample and I'm happy to take a closer look 👍
