### ISSUE TITLE
Question: Rebuild a large widget at the screen level using BlocBuilder

### ISSUE THREAD

**Issue by dylan-kwon** [felangel/bloc#3874]
For example, let's say we have a large widget called `MyPage` that constitutes the screen. Is it okay to wrap MyPage with BlocBuilder? Or should we use BlocBuilder or BlocSelector for the specific parts of the widget that require updates?

If a any other library provides a heavy widget and it is not possible to apply BlocBuilder on a per-part basis, how can we optimize performance?

**Comment by codesculpture** [comment]
My suggestion is to use Blocbuilder for the certain parts which require re render, and using bloc builder for entire widget is like re rendering the whole widget again so its not a good thing when it comes to performance

**Comment by Gene-Dana** [comment]
https://github.com/felangel/bloc/blob/master/examples/flutter_todos/lib/edit_todo/view/edit_todo_page.dart

**Comment by rbharath99** [comment]
If you have a very large widget I would first is break that down into smaller sized widgets. From there, the widgets that need to be rebuilt can be wrapped with a `BlocBuilder`.

**Comment by codesculpture** [comment]
This can be closed i guess @felangel
