### ISSUE TITLE
feat: Multiple BlocConsumer used with one  widget class

### ISSUE THREAD

**Issue by adnan-branch** [felangel/bloc#3877]
**Description**

Right now i am using blocConsumer which only hold specific 1 bloc 

 ```
BlocConsumer<BlocA, BlocAState>(
  listener: (context, state) {
    // do stuff here based on BlocA's state
  },
  builder: (context, state) {
    // return widget here based on BlocA's state
  }
)
```

**Desired Solution**

in a simple provider where we have an option we use consumer upto 6 change-notifier classes 

```
Consumer2<AppTheme, AppStatus>(
builder: (context, appTheme, appStatus, child) {
return Text(
'The current theme is ${appTheme.themeName}. The current status is ${appStatus.status}.',
);
},
),

```
or any idea if it already implemented kindly share with me about it, thanks

**Comment by felangel** [comment]
Hi @adnan-branch 👋 
Thanks for opening an issue!

If you only need to listen to multiple blocs, you can use `MultiBlocListener`. If you need to rebuild UI in response to multiple bloc states, you can use `context.watch` or `context.select`:

```dart
MultiBlocListener(
  listeners: [
    BlocListener<BlocA, StateA>(listener: ...),
    BlocListener<BlocB, StateB>(listener: ...),
  ],
  child: Builder(
    builder: (context) {
      final stateA = context.watch<BlocA>().state;
      final stateB = context.watch<BlocB>().state;

      // TODO: return a Widget based on the states of `BlocA` and `BlocB`.
    },
  ),
);
```

Hope that helps 👍
