### ISSUE TITLE
Error in testing example

### ISSUE THREAD

**Issue by tapizquent** [felangel/bloc#388]
I was trying to learn some testing for this pattern and by trying out the code in the examples for testing the counter, I get the following error: 

    00:02 +0 -1: loading test/counter_test.dart [E]                                                                          
        Failed to load "test/counter_test.dart":
        Unable to spawn isolate: 
        file:///Users/tapizquent/Projects/tools/flutter/packages/flutter/lib/src/services
        /binary_messenger.dart:7:8: Error: Not found: 'dart:ui'
        import 'dart:ui' as ui;

I noticed that this happens when I import the 'counter_bloc.dart'.

If I import only 'test/test.dart' and try to test let's say, that 2 + 2 = 4, it works perfect.

Any idea what could be causing this?
I really want to be able to start using this for real projects but testing is vital.

**Comment by felangel** [comment]
Hi @tapizquent 👋 
Thanks for opening an issue!

Can you please provide the steps to reproduce the problem as well as the output from
`flutter doctor`

Thanks!

**Comment by tapizquent** [comment]
Hey! I am actually getting this error when trying to test the Firebase Login Example. 
I am simply trying to test the initial state of RegistrationBloc if I import my registration_bloc.dart it gives me that error.

Steps to reproduce:
- Using files for Firebase Login Example
- Create file registration_test.dart in folder test/ outside of lib/
- import 'package:test/test.dart';
- import '../registration_bloc.dart';
- Just type this in: 
`main() {
  group('RegistrationBloc', () {
    RegistrationBloc _registrationBloc;
  });
}`

by trying to just run that, it gives me the error:
```
Failed to load "test/registration_test.dart":
  Unable to spawn isolate: file:///Users/tapizquent/Projects/tools/flutter/packages/flutter/lib/src/services/font_loader.dart:7:8: Error: Not found: 'dart:ui'
  import 'dart:ui';
```
If i write a simple test such as expect(2+2, 4); it gives me the same error.

BUT, if I delete the import to RegistrationBloc, basic sum test passes.

For some reason when I import that Bloc, it gives me the error.

My flutter doctor -v

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/tapizquent/Projects/tools/flutter
    • Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/tapizquent/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by tapizquent** [comment]
I realized that you don't even have to type anything in the group.
If you just do the import to registrationBloc, it throws that error telling me about dart:ui

**Comment by tapizquent** [comment]
When trying to test for authentication_bloc.dart instead, it gives me a similar error but now it talks about the google_sign_in

`Failed to load "test/auth_bloc_test.dart":
  Unable to spawn isolate: file:///Users/tapizquent/Projects/tools/flutter/.pub-cache/hosted/pub.dartlang.org/google_sign_in-4.0.2/lib/google_sign_in.dart:6:8: Error: Not found: 'dart:ui'
  import 'dart:ui' show hashValues;`

**Comment by felangel** [comment]
I think you should be using flutter_test instead of the test package.

In your pubspec.yaml

dev_dependencies:
  flutter_test
    sdk: flutter

Let me know if that helps.

**Comment by tapizquent** [comment]
That was it! Thank you so much!

I was just getting confused since in the tutorial it says to use test: instead of flutter_test. And it was causing that error.

Please try to make those updates to the examples.

Instead of

```test:```

you need
```
flutter_test:
    sdk: flutter
```

and also you run the tests with 

`flutter test` instead of `pub run test`

Thank you for responding so quickly.

**Comment by felangel** [comment]
@tapizquent awesome! Glad you got it working.

In the counter tutorial, I was just using a pure dart project for simplicity in which case you need to use test and `pub run test`; however, in a flutter project you need to use `flutter_test` and `flutter test` as you mentioned.

I'll update the docs to be more clear 👍

**Comment by vaibhav7a** [comment]
I am facing the same issue. Can you help me to resolve this error.
