### ISSUE TITLE
feat: BlocTest allow custom runZoned effect like package:clock withClock

### ISSUE THREAD

**Issue by EArminjon** [felangel/bloc#3883]
**Description**

I would like to mock inside a blocTest the clock package to able to mock clock.now(), used to mock DateTime.now().

**Desired Solution**

A solution to mock system using runZoned like DateTime override.

**Alternatives Considered**

Use simple test and stop using BlocTest :'(

**Additional Context**

https://github.com/dart-lang/clock
https://stackoverflow.com/questions/53816067/how-to-test-code-that-uses-datetime-now-in-flutter

**Comment by felangel** [comment]
Hi @EArminjon 👋 
Thanks for opening an issue!

You can use the `testBloc` function in a normal test and wrap it with `withClock` like you normally would:

```dart
test('...', () {
  withClock(clock, () {
    testBloc(...);
  });
});
```

Hope that helps!

**Comment by kodypeterson** [comment]
@felangel This does not seem to work if the Bloc event does an `add` within the handler. The next event handler does not have the DateTime overridden.

**Comment by felangel** [comment]
> @felangel This does not seem to work if the Bloc event does an `add` within the handler. The next event handler does not have the DateTime overridden.

Can you provide a link to a minimal reproduction sample?

**Comment by kodypeterson** [comment]
Interestingly in my test I can't get bloc to have the DateTime overwritten. https://github.com/kodypeterson/bloc-clock-test/blob/main/test/text_bloc_spec.dart

Maybe I have missed something. But, this would be a good test to have passing to validate the withClock functionality.

**Comment by kodypeterson** [comment]
@felangel Any thoughts on this?

**Comment by felangel** [comment]
> @felangel Any thoughts on this?

I’ll take a closer look shortly, apologies for the delay!

**Comment by felangel** [comment]
> @felangel Just wanted to check back in on this. Let me know if I can provide any additional insights as well!

Sorry for the delay! I’m out of town until tomorrow but will look asap.

**Comment by felangel** [comment]
@kodypeterson I finally had time and took a look. There were a couple of issues with the code you shared:

1. The bloc wasn't using `package:clock`
2. In your test, the `build` must actually `build` the bloc instance

The following should work:

**Bloc Code**
```dart
import 'package:bloc/bloc.dart';
import 'package:clock/clock.dart';
import 'package:equatable/equatable.dart';

part 'test_event.dart';
part 'test_state.dart';

class TestBloc extends Bloc<TestEvent, TestState> {
  TestBloc() : super(const TestState()) {
    on<TestEventDateAUpdated>(_onTestEventDateAUpdated);
    on<TestEventDateBUpdated>(_onTestEventDateBUpdated);
  }

  _onTestEventDateAUpdated(
      TestEventDateAUpdated event, Emitter<TestState> emit) async {
    emit(TestState(dateA: clock.now()));
    add(const TestEventDateBUpdated());
  }

  _onTestEventDateBUpdated(
      TestEventDateBUpdated event, Emitter<TestState> emit) async {
    emit(TestState(dateA: state.dateA, dateB: clock.now()));
  }
}
```

**Test**
```dart
import 'package:bloc_test/bloc_test.dart';
import 'package:clock/clock.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:pinseeker/test_bloc.dart';

void main() {
  group('TestBloc', () {
    test('uses fixed date', () async {
      final clock = Clock.fixed(DateTime(2023));
      await withClock(clock, () async {
        await testBloc(
          build: () => TestBloc(),
          act: (bloc) => bloc.add(const TestEventDateAUpdated()),
          expect: () => [
            TestState(dateA: clock.now()),
            TestState(dateA: clock.now(), dateB: clock.now()),
          ],
        );
      });
    });
  });
}
```

Hope that helps 👍 

Closing for now but feel free to comment with any additional questions.

**Comment by kodypeterson** [comment]
@felangel Can confirm!

Some additional notes in the event other still want to use `setUp`:

You would need to wrap your `setUp` in the `withClock` as well. This ensures that the bloc is using the correct clock zone. I have updated my test repo in the event it can help someone in the future!

Thanks again for reviewing this.
