### ISSUE TITLE
fix:  onError Bloc-- AddAddressBloc, Bad state: on<CityChanged> was called multiple times. There should only be a single event handler per event type.

### ISSUE THREAD

**Issue by alisabry22** [felangel/bloc#3885]
**Description**
i know how to use bloc thanks to @felangel for this ,, okay the situation is when iam trying to make my custom object and this custom object has it's own properties i want the my defined state to be like this (state.copyWith(customObject:state.customObject.somevalue))
i want to update some value base specific event and iam having copyWith in both (Model and State) but the thing is iam having this 
Error :(Bad state: on<CityChanged> was called multiple times ) once i start typing in textfield iam calling this event (CityChanged) to trigger state to update specfic property in this customObject .

I Hope my point is clear.

**Steps To Reproduce**

1. Define Custom Object like (MyAddress) and it has some properties city,street,name....etc,
2. Iam having equatble for both custom object and state with copyWith methods on Both,
3. in the state i have only one variable which is intance of (MyAddress) which has it's on properties.
4. trying to trigger in each textFormField in Form it's specific event to update this property.
5. error: once start typing in textField of City ,, onError Bloc-- AddAddressBloc, Bad state: on<CityChanged> was called multiple times;

**Expected Behavior**
iam expecting that bloc updates MyAddressModel each time i type in city textfield which also rebuilds this textField.
the point is when i put the whole properties in the state it works but i need to make it clean because defining 10 properties in state is too long.

**Screenshots**
![model](https://github.com/felangel/bloc/assets/52348575/0db0f59c-7c39-479b-bd29-0b461dfa4f38)
![bloc](https://github.com/felangel/bloc/assets/52348575/4826fe29-c051-41b0-9912-bc8333ff37a2)
![form](https://github.com/felangel/bloc/assets/52348575/63c7c233-f827-4567-9455-9e2342dcd118)

**Additional Context**

**Comment by codesculpture** [comment]
I mean you are doing somethin wrong,

That is u are having

```dart 
super(initialState) {
on<AddressEvent>(){ 
       on<Event1>()
       on<Event2>()
  } 
}

```
You are doing it wrong, instead it supposed to be

```dart 
super(initialState) {
       on<Event1>()
       on<Event2>()
}

```

or 

```dart 
super(initialState) {
on<AddressEvent>(event, emit){ 
       if (event is Event1) doSomething()
      else if (event is Event2) doSomethigElse()
}

```

The on method is used to listen for events each time it if it defines, it will register and start to listen, so here whenever an event triggered to u are trying to register 3 on methods, so that can lead to bad State

**Comment by alisabry22** [comment]
ohhh thank you i didn't saw it :D you know what is fells when u spend more than 2 hours and i didn't see this line of code :D 

really appreciate your help.

**Comment by alisabry22** [comment]
it works now but i can't see that the model holds this new data of city it represent mymodel as empty

**Comment by codesculpture** [comment]
Can u share the code for that

**Comment by alisabry22** [comment]
![error](https://github.com/felangel/bloc/assets/52348575/109e00e5-30ac-4cd8-83ae-b2caff08daf3)
as u can see in the yellow line i typed single char but model is not updating with this char

**Comment by alisabry22** [comment]
![error](https://github.com/felangel/bloc/assets/52348575/103b3587-bf7f-4c4b-8282-99c1e80e40f1)
as u can see iam having now in my physical mobile in textField (aaaa) but when iam printing it is what u see in the screenshoot.

**Comment by alisabry22** [comment]
@codesculpture but i print the event.city it gets the text as i typed it which means it is good. but why state is not updating

**Comment by codesculpture** [comment]
Can u just share me the copyWith methods u have both for events and states

**Comment by alisabry22** [comment]
i don't have a link for this discord server . i don't have copyWith method on events i have it only for myObject and state only ..

if u share with me this link i appreciate it .
![error](https://github.com/felangel/bloc/assets/52348575/45193c1c-1d7a-482d-8493-07c307550e47)
![error](https://github.com/felangel/bloc/assets/52348575/55e01e0a-200f-4957-9042-640666a0f353)

**Comment by alisabry22** [comment]
and this is for when event called to update state 
![error](https://github.com/felangel/bloc/assets/52348575/7e9d3ab1-49d1-4041-ba16-1cb97acff663)

**Comment by codesculpture** [comment]
Sorry my bad, i just wanted models and states copyWiths. Here is the discord https://discord.gg/bloc

**Comment by codesculpture** [comment]
Is it that correct why ur event.city is always printing 'a', it supposed to print the whole word isnt it?

**Comment by codesculpture** [comment]
Are u sure that event.city is being full text, just to clarify

**Comment by codesculpture** [comment]
Can u do this
```dart
 final model = state.addressModel.copyWith(city: event.city)
print(model.city)
```

**Comment by alisabry22** [comment]
i think u are a life save really when i rolled back for a moment before u typed in that props? i realized it is the issue too. i will give it a try i think props is the issue

**Comment by alisabry22** [comment]
missing props in the model caused this issue really thanks <3 also iam in the discord channel i will keep in touch with you.

**Comment by codesculpture** [comment]
Glad that to you figured out make sure close the issue
