### ISSUE TITLE
Question: What is the correct way to pass events and request statuses to state

### ISSUE THREAD

**Issue by zombie6888** [felangel/bloc#3892]
I have code like this and I want to shorten it:

```dart
class` SomeBloc extends Bloc<Event, SomeState> {
  SomeBloc(super.initialState) {
    on<SomeEvent>((event, emit) async {
      emit(state.copyWith(status: Status.loading, event: event));
      try {
        final data = await request();
        emit(state.copyWith(status: Status.success, event: event, data: data));
      } catch (e) {
        emit(state.copyWith(status: Status.error, event: event));
      }
    });
  }
}
```

it's a common case for api requests. I want state subscribers to know what event was fired and also be able to get current request state. And I want my data to be kept in state while other events occurs. I've tried to use observers but i think it's not a correct way to use it like this:

```dart
class SomeBloc extends Bloc<Event, SomeState> {
  SomeBloc(super.initialState) {
    on<SomeEvent>((event, emit) async {
      final data = await request();
      emit(state.copyWith(status: Status.success, event: event, data: data));
    });
  }

  @override
  void onEvent(Event event) {
    super.onEvent(event);
    //can't emit state here
  }

 @override
  void onError(Object error, StackTrace stackTrace) {    
    super.onError(error, stackTrace);
    //can't get event and emit state here
  }
}
```

What is the best approach to handle this case?

**Comment by codesculpture** [comment]
I dont have any idea to shorten this, btw i think u dont need to add "bug" label since its nothing relates to bug .

**Comment by zombie6888** [comment]
>  i think u dont need to add "bug" label since its nothing relates to bug .
How to change it?

**Comment by felangel** [comment]
Hi @zombie6888 👋 
If you want to know the event you can track the event as part of the state. Hope that helps!
