### ISSUE TITLE
docs: the output doesn't as expected

### ISSUE THREAD

**Issue by shinelikeamillion** [felangel/bloc#3894]
**Description**
I did some tests, and I think onChange in BlocObserver is called first,
and the onError method is the same (the onError method in BlocObserver is called first)

[I did some tests, and I think onChange in BlocObserver is called first](https://bloclibrary.dev/#/coreconcepts:~:text=would%20then%20output%3A-,Change%20%7B%20currentState%3A%200%2C%20nextState%3A%201%20%7D%0ACounterCubit%20Change%20%7B%20currentState%3A%200%2C%20nextState%3A%201%20%7D,-Copy%20to%20clipboard)

```dart
class SimpleBlocObserver extends BlocObserver {
  @override
  void onChange(BlocBase bloc, Change change) {
    super.onChange(bloc, change);
    print('== ${bloc.runtimeType} $change');
  }
}

// output
// == CounterCubit Change { currentState: 0, nextState: 1 }
// Change { currentState: 0, nextState: 1 }]
void main() {
  Bloc.observer = SimpleBlocObserver();
  CounterCubit()
    ..increment()
    ..close();
}

class CounterCubit extends Cubit<int> {
  CounterCubit() : super(0);

  void increment() => emit(state + 1);

  @override
  void onChange(Change<int> change) {
    super.onChange(change);
    print(change);
  }
}
```
```yaml
environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.0.0
  bloc: ^8.0.0

dev_dependencies:
  test: ^1.16.0
  bloc_test: ^9.0.0
```

**Comment by felangel** [comment]
Hi @shinelikeamillion 👋 
Thanks for opening an issue!

The internal `onChange` is called first but because you're calling `super.onChange` before printing, the `onChange` of the `BlocObserver` is fired before your print. This is working as expected, closing for now 👍
