### ISSUE TITLE
feat: Allow `BlocBase._stateController` to be synchronous

### ISSUE THREAD

**Issue by maRci002** [felangel/bloc#3896]
**Description**

In some cases, `BlocBase._stateController` should be synchronous, for instance, when interacting with `ReorderableListView`. This is because a new state will be emitted in a later frame, which leads to flickering on the screen.

**Desired Solution**

`BlocBase` / `Cubit` should accept a new parameter called `syncStateController`, which is `false` by default.

**Additional Context**

Example code:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

/// Flutter code sample for [ReorderableListView].

void main() => runApp(const ReorderableApp());

class ReorderableApp extends StatelessWidget {
  const ReorderableApp({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider<ColorCubit>(
      create: (context) => ColorCubit(),
      child: MaterialApp(
        home: Scaffold(
          appBar: AppBar(title: const Text('ReorderableListView Sample')),
          body: const ReorderableExample(),
        ),
      ),
    );
  }
}

class ColorCubit extends Cubit<List<Color>> {
  ColorCubit() : super(Colors.primaries);

  void reorderColors(int oldIndex, int newIndex) {
    final colors = [...state];
    final color = colors.removeAt(oldIndex);
    colors.insert(oldIndex < newIndex ? newIndex - 1 : newIndex, color);
    emit(colors);
  }
}

class ReorderableExample extends StatefulWidget {
  const ReorderableExample({super.key});

  @override
  State<ReorderableExample> createState() => _ReorderableListViewExampleState();
}

class _ReorderableListViewExampleState extends State<ReorderableExample> {
  @override
  Widget build(BuildContext context) {
    final cubit = context.watch<ColorCubit>();

    return ReorderableListView(
      children: cubit.state.map((color) {
        return ListTile(
          key: ValueKey(color),
          tileColor: color,
          title: Text('$color'),
        );
      }).toList(),
      onReorder: (int oldIndex, int newIndex) {
        context.read<ColorCubit>().reorderColors(oldIndex, newIndex);
        // TODO(bloc team): add setState call to apply workaround
        // setState(() {});
      },
    );
  }
}
```

Actual behaviour:

https://github.com/felangel/bloc/assets/8436039/3d08dd58-182e-4231-af38-87e5ea916819

Expected behavior (currently, a workaround is applied by calling `setState` manually):

https://github.com/felangel/bloc/assets/8436039/263c1ef9-d5b2-4833-a2e0-d89e8a2f47f7

**Comment by felangel** [comment]
Hi @maRci002 👋
Thanks for opening an issue!

I’ll take a closer look later today but I don’t know that allowing a synchronous state controller is a good idea since it’s fairly error-prone as described in the [docs](https://api.dart.dev/stable/3.0.5/dart-async/SynchronousStreamController-class.html). I need to take a closer look to see if bloc can support this case safely otherwise we may be solving one problem and introducing other problems with a change like this 😅

**Comment by maRci002** [comment]
I believe these changes should be applied only to Cubit, given that the Bloc's event controller is complex and should remain asynchronous. Therefore, converting the state stream of Bloc to synchronous doesn't seem logical.

In the documentation, we should specify that when one Bloc/Cubit listens to the states of a synchronous Cubit, one shouldn't invoke the synchronous Cubit's method within the listener. If it's essential to do so, then it should be executed in the next event loop to avoid violating the Stream contract.

**Comment by iandis** [comment]
IMO, it's better to use the workaround because I don't think there are any more use cases besides this that needs sync Stream. We can't even conditionally dispatch each data synchronously/asynchronously to a stream controller. So it's not worth the headache, but it's just my opinion.

**Comment by felangel** [comment]
I agree with @iandis and am going to close this for now but if anyone feels very strongly feel free to comment and I'm happy to continue the conversation 👍
