### ISSUE TITLE
feat: Multiple instances from the same bloc

### ISSUE THREAD

**Issue by Linaks** [felangel/bloc#3903]
**Description**

Hello, I try to solve a specific problem with flutter bloc.
I got an explore page with post cards, where every post card has a bloc.
Sometimes there are two or three identical posts on the page at the same time, because there are different categories.
Let's say there is "Science", "General" and "Hot". It's possible that the post is in the three categories.
What happens is, that every time I change the state of the post bloc, it doesn't change it on the other ones.
My question is: Is it possible to create the PostBloc once inside the PostCard widget and use it in the other ones if there's a PostBloc created already?

**Desired Solution**

Alternative to "BlocProvider<PostBloc>.value" => "BlocProvider<PostBloc>.key":

If I could find the BlocProvider by key instead of value, then I could give every PostCard widget a key with a post_id and if there's already a provider for this post, it will be used instead of creating a new one.

```dart
BlocProvider<PostCardBloc>.key(
      key: key,
      create: (context) => PostCardBloc(),
      child: Container(),
    )
``` 

If there's a BlocProvider for a PostCardBloc with the given key => Use it.
If not => Create the first PostCardBloc.

**Alternatives Considered**

...

**Additional Context**

...

**Comment by Linaks** [comment]
I just came across this issue: #2402 
[The solution](https://github.com/felangel/bloc/issues/2402#issuecomment-822119456) provided from @felangel could help me to realize my goals, thank you a lot!

**Comment by felangel** [comment]
Hi @Linaks 👋 
It sounds like you were able to resolve the issue? If so can the issue be closed? Thanks!

**Comment by felangel** [comment]
Closing for now since there appear to be no actionable steps 👍
