### ISSUE TITLE
refactor: Do not rethrow an error

### ISSUE THREAD

**Issue by hawkkiller** [felangel/bloc#3906]
**Description**

Basically, we usually have bloc observer and a logger of errors in the zone. So, it an error occurs in bloc it gets thrown again therefore getting into both zone callback and bloc observer onError. Looks like, it is not the desired behavior as onError callback becomes useless and destructive.

**Comment by felangel** [comment]
Hi @hawkkiller 👋
Thanks for opening an issue!

I’m guessing you’re not handling exceptions in your bloc which results in this behavior. The recommended approach is to handle all exceptions and call addError within the bloc when you want to report the error to BlocObserver without having an uncaught exception propagate. Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now since this is working as expected and there are no actionable next steps. Feel free to comment with additional thoughts/feedback if you disagree and I'm happy to continue the discussion 👍
