### ISSUE TITLE
bug: existing examples for flutter ecosystem are unreachable through Bloc official site

### ISSUE THREAD

**Issue by dk-a-dev** [felangel/bloc#3908]
**Description**
All the links that redirect to Bloc's website stating flutter examples are unreachable

**Steps To Reproduce**

1. Go to [Bloc's Get Started](https://bloclibrary.dev/#/gettingstarted)
2. Under *Tutorials* Section
3. Try reaching any example
4. See how the website redirects to Blocs web main page/does not redirect at all.

**Expected Behavior**
all the examples open

**Screenshots**
None

**Additional Context**
None

**Comment by marcossevilla** [comment]
hey @dk-a-dev! can you share a screenshot or screen recording to see the issue you're experimenting, I just tried and redirecting works fine for each example

**Comment by marcossevilla** [comment]
https://github.com/felangel/bloc/assets/31174242/cddba72b-1af0-4df3-913f-03404dacae73

@dk-a-dev I think you need to let the page load since I'm reproducing by tapping on both the text with the link and the asset, but they work fine

**Comment by felangel** [comment]
@dk-a-dev it could also be your ISP. Are you able to load other parts of the bloc library docs?

**Comment by dk-a-dev** [comment]
I had checked changing the ISP and the device yes changing the ISP solves the issue.
But is there a way to fix this with my ISP
