### ISSUE TITLE
feat: (IntelliJ Plugin) Make use of Dart 3 class modifiers

### ISSUE THREAD

**Issue by kputh** [felangel/bloc#3911]
**Description**

Dart 3 introduced new [class modifiers](https://dart.dev/language/class-modifiers), and the examples in the [bloc naming conventions](https://bloclibrary.dev/#/blocnamingconventions) make use of the `sealed` and `final` class modifiers. The event and state classes generated by the bloc plugin for IntelliJ IDEA deviate from the official documentation by not using these new class modifiers.

**Desired Solution**

Offer the option to have the bloc plugin for IntelliJ IDEA generate events and states for Dart 3 using the `sealed` and `final` class modifiers.

**Comment by felangel** [comment]
Hi 👋
I’m working on this atm. I’m wrapping up the bricks (#3907) and will adjust the plugins next 👍

**Comment by 8thgencore** [comment]
@felangel Good afternoon, when to wait for the update?

**Comment by felangel** [comment]
@8thgencore sorry for the delay! Planning to get to this in the next few days 👍

**Comment by donghyeon** [comment]
Are there plans to modify the way handlers are registered in Bloc, particularly in light of the recent updates regarding exhaustive searches on sealed classes? Of course, the current on<Event> method works flawlessly. However, I believe integrating the registration process with the basic Dart 3 syntax might be more intuitive and familiar to newcomers to the Bloc library, compared to using a custom method.
