### ISSUE TITLE
Log output of the Transition class

### ISSUE THREAD

**Issue by mrchenmo** [felangel/bloc#3915]
**Description**

Clearly describe what needs to be refactored any why. Please provide links to related issues (bugs or upcoming features) in order to help prioritize.
Transition class in bloc, the following method should increase whether it is under ReleaseMode, under ReleaseMode I don’t want logcat to output what my Transition is
`  @override
  String toString() {
    return '''Transition { currentState: $currentState, event: $event, nextState: $nextState }''';
  }`

**Comment by felangel** [comment]
Hi @mrchenmo 👋 
Thanks for opening an issue!

I'm guessing you're referring to `BlocObserver` when it comes to logging transitions to logcat. In that case, you're in full control over what gets logged:

```dart
class MyBlocObserver extends BlocObserver {
  @override
  void onTransition(
    Bloc<dynamic, dynamic> bloc,
    Transition<dynamic, dynamic> transition,
  ) {
    super.onTransition(bloc, transition);
    // Only log in debug mode
    if (kDebugMode) log('onTransition $transition');
  }
}
```

Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now since there are no actionable next steps but feel free to reply with any additional concerns/thoughts and I'm happy to continue the conversation 👍
