### ISSUE TITLE
Should I create many blocs when a page has many widgets?

### ISSUE THREAD

**Issue by longdw** [felangel/bloc#392]
<img width="335" alt="WX20190704-170435@2x" src="https://user-images.githubusercontent.com/4987178/60654173-0b0d4e00-9e7e-11e9-8ba5-a30d75fc268b.png">

a page has these functions.when have a default value, the border may show a default value. when I click one of border, show a dialog then click the item inside of dialog, the value inside border will change, and the bottom border's value will change accord to section1,2,3. Should I create three states, three events and three blocs? Please give me some comments and tips. Thank you very much!!!

**Comment by felangel** [comment]
Hi @longdw 👋 
Thanks for opening an issue!

I would recommend having a single bloc to manage the state of the form. You can have different events for when users tap on the individual section inputs and the state of the bloc can drive the entire form. If you haven't already, I would recommend checking out the [form validation](https://github.com/felangel/bloc/tree/master/examples/flutter_form_validation) example app.

Hope that helps and let me know if you have additional questions 👍

**Comment by longdw** [comment]
thank you for your reply @felangel 
I found a bloc must set a initialState, I don't know what initialState should I set to control all widget's default value at the same time if I create a single bloc to manage the state.

**Comment by felangel** [comment]
You could have something like:
```dart
class FormState extends Equatable {
  final String section1Value;
  final String section2Value;
  final String section3Value;
  final String section4Value;

  FormState({
    this.section1Value, 
    this.section2Value,
    this.section3Value,
    this.section4Value
  }) : super([section1Value, section2Value, section3Value, section4Value]);

  factory FormState.initial() {
    return FormState(
      section1Value: '',
      section2Value: '',
      section3Value: '',
      section4Value: '',
    );
  }
}
```

Hope that helps 👍
