### ISSUE TITLE
feat: CombineLatestBlocListener2, CombineLatestBlocListener3, ... N

### ISSUE THREAD

**Issue by IlyaMax** [felangel/bloc#3926]
**Description**

I have two cases in my app which needs this and in both cases I need to manually create subscription and cancel it which is not very useful.

**Desired Solution**

CombineLatestBlocListener2, CombineLatestBlocListener3 and so on so we could combine blocs' states and do something if blocA.state changes or blocB.state changes

**Alternatives Considered**

I've seen in another issue which proposed the same feature and you proposed to create another bloc which contains two blocs, but this as you say in another best practise should be avoided so we don't have bloc which depend on other blocs.(or something which depends on classes of the same layer).

**Comment by IlyaMax** [comment]
Possible code for dart 3.0.0
```
class CombineLatest2Streamable<B1 extends StateStreamable<S1>,
    B2 extends StateStreamable<S2>, S1, S2> extends StateStreamable<(S1, S2)> {
  final B1 bloc1;
  final B2 bloc2;

  CombineLatest2Streamable(this.bloc1, this.bloc2);
  @override
  Stream<(S1, S2)> get stream => CombineLatestStream.combine2(
        bloc1.stream,
        bloc2.stream,
        (a, b) => (a, b),
      );

  @override
  (S1, S2) get state => (bloc1.state, bloc2.state);
}

class CombineLatest2BlocsListener<B1 extends StateStreamable<S1>,
        B2 extends StateStreamable<S2>, S1, S2>
    extends BlocListener<CombineLatest2Streamable<B1, B2, S1, S2>, (S1, S2)> {
  const CombineLatest2BlocsListener(
      {super.key, required super.listener, super.child});
}

```

**Comment by IlyaMax** [comment]
Possible case: two data to load in two different blocs which could be loaded in any time. We have to call method when both data is loaded and condition on that data

**Comment by felangel** [comment]
Hi @IlyaMax 👋 
Thanks for opening an issue! As there is nothing preventing you from implementing this widget outside of the library I'd prefer to avoid increasing the API surface unless there's a very compelling reason. Closing for now but if you feel strongly about this feel free to comment and I'm happy to continue the conversation 👍
