### ISSUE TITLE
Bloc not updating using GetIt

### ISSUE THREAD

**Issue by ravindra6596** [felangel/bloc#3929]
Hello @felangel , hope you are good and well
My Question is when I update bloc using [GetIt ](https://pub.dev/packages/get_it)its not working

If I am use below method for update the bloc it successfully work 

```
 ElevatedButton(
   onPressed: () { BlocProvider.of<MovieListBloc>(context).add(LoadMovieList('10-08-2023'));  },
    child: Text('Submit'),
  ),
```
If I am use below method for update the bloc its not working why?
```
 ElevatedButton(
   onPressed: () {GetIt.I<MovieListBloc>()..add(LoadMovieList('10-08-2023'));  },
    child: Text('Submit'),
  ),
```

Can you please help me how we update the Bloc using GetIt

**Comment by vgtle** [comment]
Can you provide more information about how your bloc looks like and also your getIt di?

**Comment by ravindra6596** [comment]
@vgtle The code is to much large. will inform you If am click button then 1st method is working well and good and bloc load successfully `BlocProvider.of<MovieListBloc>(context).add(LoadMovieList('10-08-2023'))` 

but instead of this I'm using/load BLOC using GetIt this not working. `GetIt.I<MovieListBloc>()..add(LoadMovieList('10-08-2023'))`

**Comment by ravindra6596** [comment]
**Movie Bloc Code:**
```

@injectable
class MovieListBloc extends Bloc<MovieListEvents, MovieListState> {
  final MovieListRepositoryUseCase? movieListRepositoryUseCase;

  MovieListBloc({this.movieListRepositoryUseCase})
      : super(MovieListLoadingState()) {
    on<LoadMovieList>(getMovieListAPIData);
  }

  getMovieListAPIData(LoadMovieList event, emit) async {
    emit(MovieListLoadingState());
    final movieList = await movieListRepositoryUseCase!
        .callMovieList(event.date); //event.date

    movieList.fold((failure) => emit(MovieListErrorState(failure.error)),
        (model) {
      if (model.statusCode == 200) {
        emit(MovieListLoadedState(model));
      } else {
        emit(MovieListErrorState(model.message.toString()));
      }
    });
  }
}

```

**Movie Event Code:**

```
//get movie list by events
abstract class MovieListEvents extends Equatable {
  const MovieListEvents();
}
//load movie list by date
class LoadMovieList extends MovieListEvents {
  final String date;

  LoadMovieList(this.date);

  @override
  List<Object> get props => [];
}
```
**Movie State Code**

```
abstract class MovieListState extends Equatable {
  const MovieListState();
}

//movie data loading or initial state
class MovieListLoadingState extends MovieListState {
  @override
  List<Object> get props => [];
}
// movie data loaded state
class MovieListLoadedState extends MovieListState {
  final  GetMovieListByDateModel  getMovieListByDateModel;

  const MovieListLoadedState(this.getMovieListByDateModel);

  @override
  List<Object> get props => [getMovieListByDateModel];
}
// movie data error state
class MovieListErrorState extends MovieListState {
  const MovieListErrorState(this.error);

  final String error;

  @override
  List<Object> get props => [error];
}
```

**Movie Repository**

```
@factoryParam
abstract class MovieListRepository {
  Future<Either<MovieListErrorState, GetMovieListByDateModel>> getMovieListRepo(
      String date);
}
```

**Movie UseCase**

```
@injectable
class MovieListRepositoryUseCase {
  MovieListRepository movieListRepository;

  MovieListRepositoryUseCase(this.movieListRepository);

  Future<Either<MovieListErrorState, GetMovieListByDateModel>> callMovieList(
      String movieDate) {
    return movieListRepository.getMovieListRepo(movieDate);
  }
}
```

**Movie Impl**

```
@injectable
class MovieListRepositoryImpl implements MovieListRepository {
  @override
  Future<Either<MovieListErrorState, GetMovieListByDateModel>> getMovieListRepo(
      String movieDate) async {
    final queryParameters = {'date': movieDate};
  
    Uri finalUrl = Uri.parse('My URL Here')
        .replace(queryParameters: queryParameters);
    print(finalUrl);
    final response = await http.get(
        Uri.parse('My URL Here').replace(queryParameters: queryParameters),
        );
    final jsonResponse = jsonDecode(response.body) as Map<String, dynamic>;
    if (jsonResponse['StatusCode'] == 200) {
      var successResponse = GetMovieListByDateModel.fromJson(jsonResponse);
      print(successResponse);
      return Right(successResponse.toEntity());
    } else if (jsonResponse.isNotEmpty &&
        (jsonResponse['StatusCode'] == 404 ||
            jsonResponse['StatusCode'] == 400)) {
      var successResponse = GetMovieListByDateModel.fromJson(jsonResponse);
      return Right(successResponse.toEntity());
    } else {
      throw Exception('Failed to load API response');
    }
  }
}
```

**Configure Class using GetIt**

```
final getIt = GetIt.instance;

@InjectableInit()
void configureDependencies(){
  getIt.init();
  getIt.registerSingleton<AppRouter>(AppRouter());
}
```

**Injection Class**

```
final locator = GetIt.instance;
void initialization() {
   locator.registerLazySingleton<MovieListRepository>(() => MovieListRepositoryImpl());
}
```

**Comment by ravindra6596** [comment]
@tenhobi and @vgtle I have update my Code and all classes please check it and let me know where I am wrong or what I Forgot.

**Comment by vgtle** [comment]
`gh.factory<_i138.MovieListBloc>(() => _i138.MovieListBloc(
        movieListRepositoryUseCase: gh<_i139.MovieListRepositoryUseCase>())); `

Since you are using a factory here, each time you try to access your MovieListBloc, you will always receive a new instance of the bloc, which is not the one that you pass to your BlocProvider. You should try to change your code to switch from a factory to a singleton

**Comment by ravindra6596** [comment]
@vgtle How can I achieve this as per your suggestion and what changes I implement in my code? can you help me in that.

**Comment by vgtle** [comment]
`@singleton
class MovieListBloc extends Bloc<MovieListEvents, MovieListState> {
  final MovieListRepositoryUseCase? movieListRepositoryUseCase;

  MovieListBloc({this.movieListRepositoryUseCase})
      : super(MovieListLoadingState()) {
    on<LoadMovieList>(getMovieListAPIData);
  }

  getMovieListAPIData(LoadMovieList event, emit) async {
    emit(MovieListLoadingState());
    final movieList = await movieListRepositoryUseCase!
        .callMovieList(event.date); //event.date

    movieList.fold((failure) => emit(MovieListErrorState(failure.error)),
        (model) {
      if (model.statusCode == 200) {
        emit(MovieListLoadedState(model));
      } else {
        emit(MovieListErrorState(model.message.toString()));
      }
    });
  }
}`

This might help. Remember to use BlocProvider.value in this case in your page. The downside is that if the page is created more than once, this will not work. In that case only `context.watch<MovieListBloc>()/context.read<MovieListBloc>()` will work. Also i would consider to stay away from getIt and injectable and use the service locator from flutter_bloc directly, which is RepositoryProvider (See https://pub.dev/packages/flutter_bloc).

**Comment by ravindra6596** [comment]
@vgtle _**Thank you so much**_  for your answer I understood what you say will try to above code.

**Comment by felangel** [comment]
Closing for now since this issue is quite old and there doesn't appear to be any actionable next steps 👍
