### ISSUE TITLE
question: is this the right way?

### ISSUE THREAD

**Issue by longa78** [felangel/bloc#393]
Hi Felix, great job! My first issue, so if it's not the right place to ask a question please forgive me.

I'm using flutter_bloc for my app and I want to know if there's a better way to develop this:
I have items and every item have a "I like it" property.
Items are displayed in a list and when a user tap an item a new page is displayed with the detail of the item.
The "like" property is handled both in list than in the detail page, so when a user like an item in the detail page, the related like property in the list must be updated too.

This is the way I did, this is the main.dart where my bloc will envelope the entire application
```
    Future<void> main() async {
        return runApp(BlocProviderTree(
            blocProviders: [
                BlocProvider<ActionLikeBloc>(
                    builder: (context) => ActionLikeBloc(),
                ),
            ],
            child: MyApp(),
        ));
    }
```

The list of items is done with a ListView.builder where the widget that handle the like status is the same used in the detail page and this is:

```
class ActionLikeWidget extends StatelessWidget {
  final MyItem item;

  ActionLikeWidget({this.item});

  @override
  Widget build(BuildContext context) {
    ActionLikeBloc _bloc = BlocProvider.of<ActionLikeBloc>(context);

    return BlocBuilder(
        bloc: _bloc,  
        builder: (BuildContext context, ActionLikeState state) {
          if (state.isSuccessful() && state.itemId== this.item.id) 
          {
            this.item.liked = state.liked;
          }

          return Row(
            children: <Widget>[
              --- here the UI with the Like / UNlike event dispatch like:
                    if (this.item.liked) {
                      _bloc.dispatch(Unlike(item.id));
                    } else {
                      _bloc.dispatch(Like(item.id));
                    }
              ],
          );
        });
  }
}
```

Like/Unlike event trigger an API call and change the state.
Is in the builder the right place to check if the tapped "like" is the displayed item and in that case update the local item ? In this way the builder is always invoked...
How about it?
Thanks

**Comment by felangel** [comment]
Hi @longa78 👋 
Thanks for opening an issue!

I would recommend restructuring your code to look more like:
```dart
ActionLikeBloc bloc = BlocProvider.of<ActionLikeBloc>(context);
return BlocBuilder(
  bloc: bloc,  
  builder: (BuildContext context, ActionLikeState state) {
    if (state is Success) {
      return ListView.builder(
        itemBuilder: (BuildContext context, int index) {
          return ListTile(
            ...
            onTap: () {
              bloc.dispatch(LikeTapped(id: id));
            },
          );
        },
        itemCount: state.items.length,
      );
    }
  }
);
```
You shouldn't be updating the item in the UI layer like:
```dart
this.item.liked = state.liked;
```

Instead, you should just be dispatching events to the bloc and letting the bloc tell the UI what state to be in.

You can check out the [flutter complex list](https://github.com/felangel/bloc/tree/master/examples/flutter_complex_list) example app because it's very similar (instead of liking, it supports deleting items).

Hope that helps and let me know if you have additional questions! 👍
