### ISSUE TITLE
refactor: move onEmit to emit in Bloc class

### ISSUE THREAD

**Issue by shovelmn12** [felangel/bloc#3930]
**Description**

https://github.com/felangel/bloc/blob/7ed85d8ffa6c64a144728a7a26fb4277d36a61b2/packages/bloc/lib/src/bloc.dart#L201

Should be moved to:

https://github.com/felangel/bloc/blob/7ed85d8ffa6c64a144728a7a26fb4277d36a61b2/packages/bloc/lib/src/bloc.dart#L154

The only way to emit new state is through `onEmit` function that is created on each `Event` but does not use any local params. It would make it easier to just move that code to `emit` function so `onEmit` does not need to be recreated on every `Event`.
Also making it easier to add features later on as there would be no need to recreate `onEvent` for each different use, just call `emit`.

**Comment by felangel** [comment]
Hi @shovelmn12 👋
Thanks for opening an issue!

I’m not sure I fully understand (feel free to open a draft PR to illustrate your suggestion). onEmit does use the event for reporting the transition so I’m not sure how it would have access to the event if it’s moved to emit.

**Comment by tenhobi** [comment]
Closing since no additional info was provided. Feel free to reopen.
