### ISSUE TITLE
feat: Enable complex event handlers

### ISSUE THREAD

**Issue by shovelmn12** [felangel/bloc#3931]
**Description**

I'd like to have complex event handlers, as I am working in a divide and conquer way it is imposible to implement with only 1 event handler per event.

```dart
on<Event1>(writeToDB, restartable) // write only latest
on<Event1>(notifyUser, concurrent) // notify user on any change
on<Event1 | Event2>(doSomething)
```

**Desired Solution**

Refactor to use all dart `Stream` classes (e.g. [`Sink`](https://api.flutter.dev/flutter/dart-core/Sink-class.html) instead of [`_Emitter`](https://github.com/felangel/bloc/blob/master/packages/bloc/lib/src/emitter.dart#L64), [`StreamTransformerBase`](https://api.flutter.dev/flutter/dart-async/StreamTransformerBase-class.html) instead of [`EventTransformer`](https://github.com/felangel/bloc/blob/7ed85d8ffa6c64a144728a7a26fb4277d36a61b2/packages/bloc/lib/src/bloc.dart#L34) and so on) so we can expose a low level API to manipulate `Stream`s however you need.

```dart
void subscribe(Stream<S> Function(Stream<Event>) handler) => _subscriptions.add(handler(_eventController.stream));
```

another option is:

```dart
void subscribe(Stream<S> Function(Stream<Event> stream, void Function(S state) emitter) handler) => _subscriptions.add(handler(_eventController.stream, _createEmitter()));
```

with this function we can manipulate and react to complex events:

```dart
subscribe((stream) => Rx.merge([stream.whereType<A>().transform(const Restartable()), stream.whereType<B>().transform(const Concurrent())]).do(action));

subscribe((stream) => Rx.race([stream.whereType<A>(), stream.whereType<B>()]).take(1).do(action));
```

This way `Emitter` can be dropped as `Stream` pipeline will manage is being emitted and how, same goes for `_handlers`.

**Alternatives Considered**

Make [_handler](https://github.com/felangel/bloc/blob/7ed85d8ffa6c64a144728a7a26fb4277d36a61b2/packages/bloc/lib/src/bloc.dart#L70) a `Map<Event, List<_Handler>>` so we can add multiple handlers for each `Event`.

But with this change we still can't have complex handlers, but at least we can have multiple handlers per Event

**Additional Context**

The idea is to support `Stream` API for more complex use cases, also supporting that API will reduce LoC and complexity of BLoC.

It's possible to keep supporting the current API:
```dart
void onlyOneHandler(params) {
        assert(() {
      final handlerExists = _handlers[event.runtimeType]?.isNotEmpty ?? true;
      if (!handlerExists) {
        final eventType = event.runtimeType;
        throw StateError(
          '''add($eventType) was called without a registered event handler.\n'''
          '''Make sure to register a handler via on<$eventType>((event, emit) {...})''',
        );
      }
      return true;
    }());
    
    on<Event>(params) // or subscribe
}
```

I opened another issue [refactor: move onEmit to emit in Bloc class #3930](https://github.com/felangel/bloc/issues/3930) that will help manage that.

Side note: I went thrught the code but I can't say that I understand all the code and the reasoning behind why is it written that way, I might given a wrong solution. I get that the solution is short lived instances, e.g. use -> done -> remove.

**Comment by felangel** [comment]
Hi @shovelmn12 👋
Thanks for opening an issue!

Are you able to provide a minimal sample that illustrates the problem you are trying to solve? It’s not entirely clear to me from the snippets you shared what problem you’re trying to solve. Based on my understanding, you should be able to achieve what you’re asking for by writing your own custom transformer since the transformer API allows you to have low level access and use Rx etc.

Hope that helps 👍

**Comment by shovelmn12** [comment]
Hi

I'll try to explain again.

1. Can't create multiple event handlers for the same event, example:

```dart
on<Event1>(writeToDB, restartable) // write only latest
on<Event1>(notifyUser, concurrent) // notify user on any change
```
As the comments at the end of each line suggest what's the functionality I want to achieve.
I'd like to notify user on EVERY `Event1` but write to db only the lastest.

2. I'd like to be able to react to a more complex event, for example using `Rx.race` or `take(1)` etc...
Do something when first between `Event1` or `Event2` happens and do that for the first N events. Basically bring back the power of `Stream` and `Rx` into play, as we no longer have access to stream

Does this makes sense?

**Comment by c0pp1ce** [comment]
You could separate the ``writeToDB`` from the basic ``Event1``. 

So something like:
```dart
on<Event1>((event, emit) {
    notifyUser();
    add(_Event1.from(event));
});
on<_Event1>((event, emit) async {
    await writeToDB();
}, transformer: restartable());
```

**Comment by shovelmn12** [comment]
Yeah, it is possible but we want to reduce the amount of boilerplate (I would need to write `_EventX` for each different wanted behaviour). There is always a way around right? but then we are playing around the concepts of the framework and misusing it.

I really dont get the idea behind forcing only 1 event handler per event, care to explain? Maybe I am missing something.

I'd like to have access to the underling event stream so I can manipulate the events however I want and not be forced by design/concepts that does not fit mine, when giving that access users can choose the way they want to write their code. Once that's done we can have package which forces only 1 event handler (`single_handler_bloc` or whatever). The idea is to divide and counqer right? we give the basic thing, stream of events, we dont force usage, but we can have extra pckage that is opinionated and forces users to follow those concepts.

Does this make sense?

**Comment by c0pp1ce** [comment]
Generally I would say that the bloc pattern is a pattern that requires quite some boilerplate, simply because it is very expressive when it comes to declaring events and states. Declaring different events for different purposes is also not misusing the framework - it is actually what the framework requires. 

I do think that finding a fitting event and state structure can be tough for complex scenarios - but I am unsure how that can be adressed without introducing a rather complex API that you mostly have no need for.

In your case, I would revisit the problem. If you have an event that should reflect changes in the UI immediately, while only persisting the most recent value you could probably outsource the "local" value to simple local state (``StatefulWidget``) to keep your UI up-to-date while also reducing the amounts of interactions with your backend.

**Comment by shovelmn12** [comment]
Yeah I totally get you, as said I get the ideas and that's why I am saying it's always possible to have a opinionated wrapper package.

And because bloc is boilerplate heavy I am trying to steer away from even more boilerplate.

The example I gave was a classic one that hits locally and server side.

The idea is at the end of the day make a core package that exposes the event stream and have other packages forcing different patterns.

bloc_core
bloc (forces 1 event handler)
blocify (exposes event stream freely)
bloc_async (uses async*)
Etc....

That way you give users the flexibility to create whatever they want without changing much (copy core functionality to bloc_core and depend on that inside bloc)

**Comment by shovelmn12** [comment]
I dont think that such approach will work as it's combinig 2 solutions that are different in their core .... What I am saying is that it might be confusing or let people make mistakes easily (if I understand what you offered correctly)

Also if you just split the code to different packages it shouldn't be a problem, again as you can see there are already bloc "plugins" so why not make it fully modular and let users use it however they see fit... At the end of the day it will bring more creativity (hopefully haha)

**Comment by c0pp1ce** [comment]
I have yet to fully understand how streams work/what you can do with them in Dart - might very well be that I got something wrong there. We might as well scratch my last comment regarding streams.

Anyway, I dont think further splitting the code into packages would create problems, I am just not a huge fan of this - it can make things inconvenient. I already dont get why ``bloc_concurrency`` is its own package (with a rather misleading name given that the default event processing already is concurrent).

**Comment by shovelmn12** [comment]
I am not a `Stream` guru but I think I have good enough understanding of how it works, I am a big supporter of FRP (Functional Reactive Programming) using`Stream`/`Rx`/`Pub/Sub`/whatever implementation.

I really like modularity, so users can always choose what they "install".
This does not have to be done with splitting to another package but rather give a base class with exposed `eventsStream`.

```dart
class BaseBloc<E, S> {
 Stream<E> get events => _eventController.stream;
}
```

This will give you a general case solution, if you get what I mean, the only one function handler per `Event` is a specific use case of the general case which is react to events.

**Comment by felangel** [comment]
@shovelmn12 bloc attempts to abstract rx in order to provide a safer and simpler API for developers to consume streams without the complexity of rx. If you prefer to use rx you' re more than welcome since everything blocs expose streams.

The event transformer API is based on the `StreamTransformer` API which is built into Dart and exposes a stream:

For example:

```dart
EventTransformer<Event> debounce<Event>(Duration duration) {
  return (events, mapper) => events.debounce(duration).switchMap(mapper);
}
```

In this case `events` is a `Stream` and you can use whatever rx operators you'd like.

Hope that helps! Closing for now since there doesn't appear to be any actionable next step but I'm more than happy to continue the discussion 👍
