### ISSUE TITLE
Question: Different instances of the same Bloc

### ISSUE THREAD

**Issue by HoangKimToi** [felangel/bloc#3932]
I have an abstract class 
```dart
abstract class BlocExample extends Bloc<Event, State> {
  BlocExample(super.initialState);
}
```
I have 2 classes that extend from an abstract class which are:
```dart
class BlocA extends BlocExample {
  BlocA({required this.repositoryA,});
}
```
```dart
class BlocB extends BlocExample {
  BlocB({required this.repositoryB,});
}
```

- How can I initialize 2 blocks A and B together?
- Or any other?

**My end goal is to use `context.read<BlocExample>().add(Event())` I can decide which block to use.**

**Comment by tenhobi** [comment]
That is Provider related issue. Basically, you can only listen to one thing using `context.read<>` and it will be to most close one. You can probably do some magic to make it work using Riverpod https://pub.dev/packages/riverpod ? Not sure.

Another option is to redesign your code to not rely on such code. It is definitely not needed.
