### ISSUE TITLE
docs: sorry in advance

### ISSUE THREAD

**Issue by axroromonov** [felangel/bloc#3935]
I want to kill the Flutter Bloc when it leaves the page. My request takes a long time (it goes to several services), the user can back it up without a response, and even before it reaches some services, is there another way for me to dispose? thanks in advance for the reply

**Comment by elianortega** [comment]
@axroromonov regarding  the `Bloc` disposal, the `BlocProvider` will automatically handle closing, so whenever the `BlocProvider` widget gets disposed it will call `bloc.close` too. So if you are intending to close the bloc whenever the page is popped, you can add the `BlocProvider` inside that same page. 

Regarding the canceling of the call to the several services, you should think of some logic to cancel those request independently and then handling the canceling on the close function of the bloc. 

There is a feature request from 2021 talking about canceling all pending asynchronous operation on bloc close, you can read more about it in #3069.

**Comment by axroromonov** [comment]
> regarding the `Bloc` disposal, the `BlocProvider` will automatically handle closing, so whenever the `BlocProvider` widget gets disposed it will call `bloc.close` too. So if you are intending to close the bloc whenever the page is popped, you can add the `BlocProvider` inside that same page.
> 
> Regarding the canceling of the call to the several services, you should think of some logic to cancel those request independently and then handling the canceling on the close function of the bloc.
> 
> There is a feature request from 2021 talking about canceling all pending asynchronous operation on bloc close, you can read more about it in #3069.

I'm just looking for a way to exit the page other than dispose via block , or block.close(); is it enough for me?

**Comment by felangel** [comment]
@axroromonov when you pop a page (unmount a widget) that contains a `BlocProvider` it'll automatically close the bloc.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
