### ISSUE TITLE
question: add bloc event before navigation safe?

### ISSUE THREAD

**Issue by elianortega** [felangel/bloc#3936]
**Description**

Is it safe to add an event to a bloc and then navigate to another page?

**Context:**

Let's say we have 1 bloc `BlocA`. Defined at the top level of the app, so there won't be any provider not found exception. 

This `BlocA` is used in some pages, let's say `Page1` and `Page2`. On `Page1` we have a button that when pressed is going to navigate to `Page2` but before navigating is going to add an event to `BlocA` to prep some things that will be used on `Page2`.

```dart
ElevatedButton(
  onPressed: () {
    context.read<BlocA>().add(BlocAEvent());
    context.push(Page2.path);
  },
  child: Text('Next'),
),
```

- Is adding this event and immediately, then navigating safe? 
- Can I assume that the event will always be added? 

If so, I understand that event addition is not the same as event processing completion, so even if the event is added I know the processing could take some time and if so loading states should be considered. But that's why I want to ask if the event being added could be guaranteed?

**Comment by felangel** [comment]
Hi @elianortega 👋 
Thanks for opening an issue!

In the snippet you provided, you can be sure the event will always be added since it is added synchronously. The event will be processed asynchronously however. 

> If so, I understand that event addition is not the same as event processing completion, so even if the event is added I know the processing could take some time and if so loading states should be considered.

Correct, you can be sure the event has been added but not that it has been processed. Hope that helps!
