### ISSUE TITLE
feat: asyncronous Repository and Bloc Provider prevent ui jank during creating instances

### ISSUE THREAD

**Issue by erlangparasu** [felangel/bloc#3937]
**Description**

asyncronous Repository and Bloc Provider prevent ui jank during creating instances

**Desired Solution**

-

**Alternatives Considered**

-

**Additional Context**

-

**Comment by elianortega** [comment]
@erlangparasu could you provide some context to understand what you are requesting/asking?

**Comment by erlangparasu** [comment]
oh ya. first i want to ask is RepositoryProvider blocking the UI during creating instance of T class?

**Comment by elianortega** [comment]
As you can see [here](https://github.com/felangel/bloc/blob/7ed85d8ffa6c64a144728a7a26fb4277d36a61b2/packages/flutter_bloc/lib/src/repository_provider.dart#L28), `RepositoryProvider` is just a wrapper of `Provider` and the `create` function is an synchronous operation, so **no**, it shouldn't block UI during creation of instance `T`.

I would recommend checking for other sources of jank UI or adding a reproduction sample.

**Comment by erlangparasu** [comment]
Thank you for the advice.  i wonder if `lazy: false` parameter makes RepositoryProvider blocking the ui during build

**Comment by elianortega** [comment]
Lazy just creates the provider immediately when the widget is inserted in the widget tree, From the docs:
>It is worth noting that the create callback is lazily called. It is called the first time the value is read, instead of the first time [Provider](https://pub.dev/documentation/provider/latest/provider/Provider-class.html) is inserted in the widget tree.
This behavior can be disabled by passing lazy: false to [Provider](https://pub.dev/documentation/provider/latest/provider/Provider-class.html).
