### ISSUE TITLE
feat: Add previousState object to builder callback in BlocBuilder (like buildWhen callback)

### ISSUE THREAD

**Issue by erlangparasu** [felangel/bloc#3942]
**Description**

Add previousState object to builder callback in BlocBuilder (like buildWhen callback)

**Desired Solution**

`builder: (context, prevState, currentState) {}`

**Alternatives Considered**

-

**Additional Context**

-

**Comment by felangel** [comment]
Hi @erlangparasu 👋 
Thanks for opening an issue!

Since you are in full control of the `state` you can keep track of the previous state as part of the state itself. Hope that helps 👍

**Comment by erlangparasu** [comment]
@felangel  Thanks for the suggestion!
