### ISSUE TITLE
Question: how to properly trigger inital event 

### ISSUE THREAD

**Issue by chedwin41** [felangel/bloc#3946]
Hello,

We are using Bloc in a large scale app with a lot of blocs. Most of them are used to fetch data. In order to start fetching the data when the bloc is created, I need to add an init event. My question is : what is the best way to add this init event and why ?

I have seen [this example](https://github.com/felangel/bloc/blob/master/examples/flutter_shopping_cart/lib/app.dart#L19) and [this question ](https://stackoverflow.com/questions/62648103/triggering-initial-event-in-bloc) which makes me think that the best way is to add the event within the BlocProvider but I'm not sure why 

My prefered way would be to add it in the constructor of the BlocInstance creation. As said in the SO response, `this way has drawbacks when testing because first event is implicit` but I dont really understand the point made in the SO response. 

Can someone enlighten me on this subject.

Thanks for your time.

**Comment by felangel** [comment]
Hi @chedwin41 👋 
Thanks for opening an issue!

I recommend avoiding adding events from within the bloc constructor for reasons I described in https://github.com/felangel/bloc/issues/3944. Hope that helps 👍
