### ISSUE TITLE
Flutter/Web:  BlocBuilder called with `state` undocumented internal flutter type '

### ISSUE THREAD

**Issue by WorikQCI** [felangel/bloc#3947]
**Description**
When `BlocBuilder` is called the `state` argument is `minified:jC`

`minified:Jc` is not a state I have defined nor can recognise. 

**Steps To Reproduce**

Run in Flutter/Web

My question is:  Is Bloc usable with Flutter/Web?

**Comment by felangel** [comment]
Hi @WorikQCI 👋
Thanks for opening an issue!

Yes, bloc works on Flutter/Web. Can you provide a minimal reproduction sample and I’m happy to take a closer look? Thanks!

**Comment by WorikQCI** [comment]
Turns out this is a problem with the way Dart sets RTTI.  It is not derived from the type but a variable that must be set, explicitly, in the compiler.

The dart2js authors have not bothered, so RTTI has no meaning, or use, in the context of dart2js.

**Comment by WorikQCI** [comment]
So I will click (should have clicked)  "Close with comment"
