### ISSUE TITLE
fix(vscode): do not show context menu contributions when not in a Bloc project 

### ISSUE THREAD

**Issue by alestiago** [felangel/bloc#3948]
**Description**

Currently, the Bloc visual studio code extension always shows the options "Bloc: New Bloc" and "Bloc: New Cubit". This violates the [VS Code's UX recommendation](https://code.visualstudio.com/api/ux-guidelines/context-menus).

I would like these options to only show when the project (workspace) currently being worked on is a Dart project and it has a bloc dependency on the _pubspec.yaml_.

**Steps To Reproduce**

1. [Install the Bloc VS Code extension](https://marketplace.visualstudio.com/items?itemName=FelixAngelov.bloc).
2. Right click on a directory within the VS Code file explorer.
3. The options "Bloc: New Bloc" and "Bloc: New Cubit" are shown.

**Expected Behavior**
The options "Bloc: New Bloc" and "Bloc: New Cubit" should only be shown when project is a Dart project and has a bloc dependency on the _pubspec.yaml_.

**Video**

<details> 

<summary> Showing in a Dart project without a `bloc` dependency </summary>

https://github.com/felangel/bloc/assets/44524995/2aa2012c-c076-419e-8739-26248521d419

</details>

<details> 

<summary> Showing in a Node project </summary>

https://github.com/felangel/bloc/assets/44524995/8cd1bb66-0bae-4d71-bf84-dd91effdab25

</details>

**Additional Context**

- [VS Code's UX Context Menu recommendation](https://code.visualstudio.com/api/ux-guidelines/context-menus)

**Comment by alestiago** [comment]
I still plan to work on this, sorry for the delay.

**Comment by tenhobi** [comment]
Good idea. Btw. it should also probably work correctly with monorepos, or at least if one of the packages has the dependency on the Bloc, it should work.

**Comment by alestiago** [comment]
Thanks @tenhobi for showing interest,I might resume work on this during the weekend.
