### ISSUE TITLE
Widget not updated every time.

### ISSUE THREAD

**Issue by omuomugin** [felangel/bloc#395]
**Describe the bug**
for example when I got this code in `post_bloc#mapEventToState`.

```
yield PostLoading();

final postsResponse = await _fetchPosts();
yield PostLoaded(posts: postsResponse.posts);
          
yield Normal();
```

Build method is not called when `yield PostLoaded(posts: postsResponse.posts)`.

**Expected behavior**
I expected to run build method 3times since there are 3 `yield <SOME-STATE>`.
But actually it only run build method when `yield PostLoading()` and  `yield Normal()`.
I guess because between `yield PostLoaded` and `yield Normal` have no waiting time `yield Normal()` execute before build method runs.

**Additional context**
Question is
1. Is this expected behavior?
2. Are there any different tricks to do this.

Thanks.

**Comment by omuomugin** [comment]
Perhaps, the version I am using is 

```
 # bloc
bloc: ^0.9.3
flutter_bloc: ^0.7.0
```

If maybe something to do with version.

**Comment by abinvp** [comment]
If you comment out the `yield Normal()`, are you able to see the `PostLoaded` state? In that case, it is normal behavior. You can also test this by adding a `await Future.delayed(Duration(seconds: 5));` before your `yield Normal()` to see what is happening between the state changes.

**Comment by omuomugin** [comment]
> If you comment out the yield Normal(), are you able to see the PostLoaded state?

Yes.

> In that case, it is normal behavior.

When this is normal behavior, it means `the state might be skipped` and is that good behavior to have? Or is there any other trick to get build every time.

**Comment by abinvp** [comment]
The state isn't skipped but it isn't getting enough time to appear on the screen. Can you share a mockup or the code to demonstrate what you are trying to achieve?

**Comment by felangel** [comment]
Hi @omuomugin 👋 
Thank for opening an issue!

Regarding your question, as @abinvp said, this is normal behavior and is happening because you're yielding back-to-back states before flutter has a chance to rebuild. The same thing happens if you change the state of a widget multiple times using `setState`.

In what case would you want to yield back-to-back states?

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I’m happy to continue the conversation 👍
