### ISSUE TITLE
docs: Exposing Public Methods in bloc

### ISSUE THREAD

**Issue by lsaudon** [felangel/bloc#3954]
**Description**

Why ` void start() => add(const EventStarted());` in bloc is not a good pratice cf. [Exposing Public Methods](https://bloclibrary.dev/#/faqs?id=exposing-public-methods)

**Comment by felangel** [comment]
It's just a recommendation so feel free to ignore it if you feel strongly but the reason for the recommendation is to avoid the extra indirection and make the fact that you're adding events to the bloc explicit.

Hope that helps 👍
