### ISSUE TITLE
docs: I want to know the mechanism of the BlocProvider create method

### ISSUE THREAD

**Issue by jackwill99** [felangel/bloc#3963]
As you described, [Create] function provides to multiple widgets within a subtree by creating the [Bloc] and it can be used as a dependency injection (DI). 

So, I want to know the mechanism of the BlocProvider create method.

**Questions**
Whenever I navigate to widget provided by Bloc create function, will it create a new instance of [Bloc] even I have created this bloc another widgets?
And, how can I check that this [Bloc] is cleared on memory when we close this widget ?

**Comment by felangel** [comment]
Hi @jackwill99 👋 
The mechanism is identical to that of `package:provider`. By default `create` is called lazily (only when the bloc is accessed) unless `lazy: false` is used. When you navigate away and the `BlocProvider` is removed from the widget tree it will automatically close (dispose) the bloc that it was providing. Hope that helps 👍
