### ISSUE TITLE
feat: Add support of hydrated_bloc to web using local storage

### ISSUE THREAD

**Issue by freshtechtips** [felangel/bloc#3968]
**Description**

It's possible to store the state easily using local storage in js in Flutter web, so is it possible for the plugin to add implementation only for the web?? I could do it myself if I have time, but if it is possible and no one does it then I will try to send a pull request with custom implementation so everyone can use the `hydrated_bloc` package even for web

So we can save the state and when the user visits the web app again it will load for the previous state last time just like how it works on other platforms

I'm sure that I have missed something since if it is that easy to implement then there should be someone who already did it, can you explain why it's not possible if it is??

Since the **hydrated bloc** is already built on top of `hive` then I think it already should support the web. is there additional platform-specific logic??

**Desired Solution**

Web local storage or Sqflite experimental support for web

Thank you for your time and efforts to the community

**Comment by felangel** [comment]
Hi @freshtechtips 
Hydrated Bloc already supports the web. Please refer to the [example](https://github.com/felangel/bloc/blob/master/packages/hydrated_bloc/example/lib/main.dart). Hope that helps 👍

**Comment by freshtechtips** [comment]
> Hi @freshtechtips 
> Hydrated Bloc already supports the web. Please refer to the [example](https://github.com/felangel/bloc/blob/master/packages/hydrated_bloc/example/lib/main.dart).
> 
> Hope that helps 👍

Oh, thank you, but it doesn't mention that in the official documentation and even in the supported platforms
