### ISSUE TITLE
fix: async `expect` using `blocTest`

### ISSUE THREAD

**Issue by gallottino** [felangel/bloc#3975]
**Description**
I found a problem during a test using `blocTest`. I declared `expect` as an `async` closure and i encoutered some problem during asserts.

**Steps To Reproduce**

1. Create a BugBloc Example
```dart
import 'package:bloc/bloc.dart';

sealed class BugEvent {
  const BugEvent();
}

class BugEventOne extends BugEvent {
  const BugEventOne();
}

class BugEventTwo extends BugEvent {
  const BugEventTwo();
}

class BugBloc extends Bloc<BugEvent, int> {
  BugBloc() : super(0) {
    on<BugEventOne>((event, emit) {
      emit(1);
    });
    on<BugEventTwo>((event, emit) {
      emit(2);
    });
  }
}
```
2. Create a test to reproduce the bug
```dart
blocTest("Test bug bloc",
    build: () {
      return BugBloc();
    },
    act: (bloc) {
      bloc.add(BugEventOne());
      bloc.add(BugEventTwo());
    },
    expect: () async {
      await Future.delayed(Duration(seconds: 1));
      return [1, 2];
    });
```
3. See error
```
Expected: <Instance of 'Future<List<int>>'>
  Actual: [1, 2]
```

**Expected Behavior**
Test is ok.

**Additional Context**
I found that it can be resolved just puttig an await before expect 
```dart
line 216: bloc_test.dart
if (expect != null) {
        final dynamic expected = await expect();
```

**Comment by felangel** [comment]
Hi @gallottino 👋 
Thanks for opening an issue!

Can you please provide some more context regarding why you'd want your expectation to be `async`? I just want to make sure I understand the use-case, thanks!

**Comment by gallottino** [comment]
> Hi @gallottino 👋 Thanks for opening an issue!
> 
> Can you please provide some more context regarding why you'd want your expectation to be `async`? I just want to make sure I understand the use-case, thanks!

Hi @felangel thank you for your answer 😄 
`expect()` is a `dynamic Function?` and it' isn't just an array of states. This means (and i like it), that you can do some calculations to obtain your states.  You can do them in `setUp()`, but you can do calculations also in `expect` directly. In some projects, i have the habit to use some text files to test behavior. Assume for example that you have some methods that fill some html templates with parameterized data, i want to load my assert filled file from test_asset and test it with the new state. Of course, loading file is a async calculations and i need `await` for this.

**Comment by 08109165220** [comment]
• Analyze the issue and understand the problem
• Identify the root cause of the problem
• Implement the fix by adding 'await' before 'expect'
• Test the fix to ensure it resolves the issue
• Submit the code changes as a pull request

**Comment by 08109165220** [comment]
EVERY thing is perfectly ok but i think this is the problem


line 216: bloc_test.dart
if (expect != null) {
        final dynamic expected = await expect();

**Comment by 08109165220** [comment]
i think putting or adding a final dynamic to make it dynamic in order to contain any variable will solve the problem

**Comment by gallottino** [comment]
@08109165220 `final dynamic` is already present. The problem is that the function with a `Future.delayed` returns a `Future` and in this way `expect()` doesn't work as expected.

**Comment by 08109165220** [comment]
this is the right code     blocTest(
  "Test bug bloc (Future method)",
  build: () {
    // Create your BugBloc instance here
    return BugBloc();
  },
  act: (bloc) => bloc.add(BugEventOne()).then((_) =>
bloc.add(BugEventTwo())),
  expect: () async => Future.delayed(Duration(seconds: 1), () => [1, 2]),
// Corrected delay usage
);
