### ISSUE TITLE
Force transition in the same state

### ISSUE THREAD

**Issue by quantosapplications** [felangel/bloc#398]
hi @felangel I'm still using your library and I'm finding myself very well using it!

I'm writing a bloc that manage a form and I took the bloc you used in the firebase_login sample https://felangel.github.io/bloc/#/flutterfirebaselogintutorial?id=login-states

and this is my implementation

`
@immutable
class CreateTitleState extends Equatable {

  final String title;
  final bool isTitleValid;

  final String description;
  final bool isDescriptionValid;

  bool get isFormValid => isDescriptionValid && isTitleValid;

  final List<Category> categories;
  final Category category;

  final List<Hashtag> hashTags;
  final List<User> userTags;

  final bool isSubmitting;
  final bool isSuccess;
  final bool isFailure;

  final Post savedPost;
  final String error;

  CreateTitleState({@required this.title, @required this.description, @required this.category, @required this.isDescriptionValid, @required this.isTitleValid, @required this.categories, @required this.hashTags, @required this.userTags, @required this.isSubmitting, @required this.isSuccess, @required this.isFailure, @required this.savedPost, @required this.error})
    : super([title, description, category, isDescriptionValid, isTitleValid, categories, hashTags, userTags, isSubmitting, isSuccess, isFailure, savedPost, error]);

  factory CreateTitleState.empty() {
    return CreateTitleState(
      title: null,
      description: null,
      category: null,
      isDescriptionValid: false,
      isTitleValid: false,
      hashTags: [],
      userTags: [],
      categories: [],
      isSubmitting: false,
      isSuccess: false,
      isFailure: false,
      savedPost: null,
      error: null,
    );
  }

  factory CreateTitleState.submitting() {
    return CreateTitleState.empty().copyWith(isSubmitting: true);
  }

  factory CreateTitleState.failure() {
    return CreateTitleState.empty().copyWith(isFailure: true);
  }

  factory CreateTitleState.success() {
    return CreateTitleState.empty().copyWith(isSuccess: true);
  }

  CreateTitleState copyWith({
    String title,
    String description,
    Category category,
    bool isDescriptionValid,
    bool isTitleValid,
    List<Category> categories,
    List<HashtagDetail> hashTags,
    List<User> userTags,
    bool isSubmitting,
    bool isSuccess,
    bool isFailure,
    Post savedPost,
    String error,
  }) {
    return CreateTitleState(
      title: title ?? this.title,
      description: description ?? this.description,
      category: category != null ? category.id == 0 ? null : category : this.category,
      isDescriptionValid: isDescriptionValid ?? this.isDescriptionValid,
      isTitleValid: isTitleValid ?? this.isTitleValid,
      hashTags: hashTags ?? this.hashTags,
      userTags: userTags ?? this.userTags,
      categories: categories ?? this.categories,
      isSubmitting: isSubmitting ?? this.isSubmitting,
      isSuccess: isSuccess ?? this.isSuccess,
      isFailure: isFailure ?? this.isFailure,
      savedPost: savedPost ?? this.savedPost,
      error: error ?? this.error
    );
  }
}
`

I also have an event that dispatch a Category Change event, when the user select a category.

When I'm switching from `category = null` to `category = SomeCategory()` the state change and the transition occur.
When instead I'm switching from `category = SomeCategory()` to `category = AnotherCategory()` nothing happens because it compare the two states as they are the same.

Indeed if I use `int categoryId` instead of `category` it works.

The Category class extend Equatable so that it should be able to compare two different categories.

is there a way to force state change and transition?

Thank you!!

**Comment by felangel** [comment]
Hi @quantosapplications 👋 
Thanks for opening an issue and for the positive feedback! Glad you’re still enjoying the library 😄

Regarding your question, if you want two instances of the same state to be considered different and to trigger a state change, then I would recommend not having that class extend Equatable.

Hope that helps and great question 👍
