### ISSUE TITLE
fix: calling create with an existing bloc leads to bad state

### ISSUE THREAD

**Issue by becjit** [felangel/bloc#3981]
**Description**
@felangel @narcodico and others 
Firstly, I am not sure if this is a bug. I am confused between BlocProvider.value and BlocProvider create.

In this particular scenario I am creating and closing a bloc in a stateful widgets init and close method

What is the expected behaviour if I call BlocProvider.create multiple times with the previously defined bloc instance

in short
What is difference between
Scenario 1. 

_bloc = NewBloc()

once in scaffold
BlocProvider<SomeBloc>(
**// using the previously created bloc here**
        create: (context) =>_bloc,

and once in onTap of FAB to open a dialog

**BlocProvider<SomeBloc>(
**// using the previously created bloc here**
        create: (context) =>_bloc,**

and Scenario 2

_bloc = NewBloc()

once in scaffold
BlocProvider<SomeBloc>(
        create: (context) =>_bloc,

and once in onTap of FAB to open a dialog

**BlocProvider<SomeBloc>.value(
        value: (context) =>BlocProvider.of<SomeBloc>(pageContext),**

```
class ParentScreen extends StatefulWidget {
...
final _bloc;

init(){
_bloc = SomeBloc();
..
}

dispose(){
bloc.close;
}

@override
  Widget build(BuildContext context) {
return  child: BlocProvider<SomeBloc>(
**// using the previously created bloc here**
        create: (context) =>_bloc,
        child: BlocBuilder<SomeBloc, SomeState>(
          builder: (pagecontext, state) {
            return Scaffold(
              appBar: AppBar(
                title:
                    Text('Growth Chart', style: theme.textTheme.headlineSmall),
                bottom: TabBar(
                  tabs: <Widget>[
                    Tab(
                      text: weightLabel,
                      icon: Icon(PhosphorIcons.regular.barbell),
                    ),
                  ],
                ),
              ),
              floatingActionButtonLocation:
                  FloatingActionButtonLocation.endFloat,
              floatingActionButton: _getSpeedDial(pagecontext),
              body: const TabBarView(
                children: [
                  WeightChartTab()
                ],
              ),
            );
          },
        ),
      );

SpeedDial _getSpeedDial(BuildContext pageContext) {
    return SpeedDial(
      
      children: [
        SpeedDialChild(
 ..
          onTap: () {

            WoltModalSheet.show<void>(
              context: context,
              decorator: (child) {
                return MultiBlocProvider(
                  providers: [
 ....
**// This is working fine**
                    BlocProvider.value(
                        value: BlocProvider.of<SomeBloc>(pageContext))
**// this is giving bad state in some later flow**
                    // BlocProvider<GrowthBloc>(
                    //   create: (context) => _bloc,
                    // )
                  ],
                  child: child,
                );
              },
            ....
            ).then((value) {
              pageContext.read<GrowthBloc>().add(const GetAllWeightEvent());
            });
          },
        ),
        
      ],
    );
  }
```

Can add the the entire flow in detail. But I want to understand the expected behaviour first

**Comment by felangel** [comment]
Hi @becjit 👋 
Thanks for opening an issue!

The big thing to remember is `BlocProvider.value` will not automatically close the bloc whereas using `BlocProvider` with `create` will. The general recommendation is for whoever creates the bloc to be responsible for disposing it therefore it's important to make sure that if you're using `BlocProvider.value` you're either doing that because:

- You've used a `BlocProvider` (with `create`) originally and are re-providing the bloc to a new route for example
- You're manually managing the bloc and will handle disposing the bloc in a `StatefulWidget`'s `State` for example

Hope that helps! Closing for now but feel free to comment with any follow up questions and I'm happy to continue the conversation 👍
