### ISSUE TITLE
app not installed as package appears to be invalid

### ISSUE THREAD

**Issue by gullchurkina9** [felangel/bloc#3985]
hi, i copied the code from https://github.com/felangel/bloc/tree/master/examples/flutter_todos
application runs perfectly on the web and on the android emulator. BUT does not launch via APK on a physical device. Gives the error: "app not installed as package appears to be invalid". How to fix?
Tried to run on Android 8 and 12

my code https://github.com/gullchurkina9/aaaaaaaaaaaaaaa-help

**Comment by eduardscript** [comment]
Have you tried `flutter run -d **<your_device_name>** --flavor development --target lib/main_development.dart`

**Comment by felangel** [comment]
This looks like https://stackoverflow.com/questions/76251146/flutter-apk-package-appears-to-be-invalid. Closing for now since it seems unrelated to bloc but feel free to comment with any follow ups 👍
