### ISSUE TITLE
fix: 

### ISSUE THREAD

**Issue by naveenkmavoor** [felangel/bloc#3991]
**Description**
Circular progress indicator keep on showing when there are few list of item(for eg: 3-4 )in the official flutter bloc example of flutter_infinite_list

**Steps To Reproduce**

1. Go to Github flutter bloc examples
2. Clone the repository  [https://github.com/felangel/Bloc/tree/master/examples/flutter_infinite_list](url)
3. Run the project and if the list is having only a few list of item(for eg: 3-4)  then the circular progress indicator keep on showing  

**Expected Behavior**
When there are only few items on the list then the circular progress is not required to show all the time

**Screenshots**
![Screenshot from 2023-11-07 22-23-50](https://github.com/felangel/bloc/assets/37239028/663e22ae-8ccd-49a4-8c43-4e551c8f3b5a)

I've limit the list item to 4 
![Screenshot from 2023-11-07 22-07-53](https://github.com/felangel/bloc/assets/37239028/580315fb-3e7d-4a58-8c14-2b38385930f9)

**Additional Context**
I've took inspiration from this fluttter infinite list in my project and found out there is an issue. Can anyone suggest how to fix this issue?

**Comment by naveenkmavoor** [comment]
@felangel can you please help to solve this issue

**Comment by tenhobi** [comment]
The issue in your case when you liit the number of items would probably be that if you only do 1 (initial) request, the `hasReachedMax` property is set to `false`, and therefore the loading is shown. Since another event is triggered only on scroll, a new request might result with "end of stream" (no more posts) and the loading would not be shown.

```dart
void _onScroll() {
    if (_isBottom) context.read<PostBloc>().add(PostFetched());
  }
```

Note that this example is just a simple showcase of how infinite loading can work and shows a loading indicator when more posts can be loaded. If you wish to modify this behavior and, e.g., show something else when you haven't reached the "end of stream" and more items can be loaded (aka not showing the loading indicator in this case), you are free to do so in your own project.

**Comment by naveenkmavoor** [comment]
It's working fine if there is more than enough items that requires scrolling, but the thing is the _onScroll() won't get triggered when there are only few items(not enough item which requires scrolling) in the listview so the hasReachedMax is still true thus causing the progress indicator to show all the time. How can that case be handled?

The issue i'm facing can be reproduced by simply limiting the item count to 4 in the http response(mentioned above).

I've tried some workaround  by refering to stackoverflow that check if scrolling is required or not, but ended up getting error
[https://stackoverflow.com/questions/63270853/detect-if-a-singlechildscrollview-listview-can-be-scrolled](url)

**Comment by naveenkmavoor** [comment]
> The issue in your case when you limit the number of items would probably be that if you only do 1 (initial) request, the `hasReachedMax` property is set to `false`, and therefore the loading is shown. Since another event is triggered only on scroll, a new request might result with "end of stream" (no more posts) and the loading would not be shown.
> 
> ```dart
> void _onScroll() {
>     if (_isBottom) context.read<PostBloc>().add(PostFetched());
>   }
> ```
> 
> Note that this example is just a simple showcase of how infinite loading can work and shows a loading indicator when more posts can be loaded. If you wish to modify this behavior and, e.g., show something else when you haven't reached the "end of stream" and more items can be loaded (aka not showing the loading indicator in this case), you are free to do so in your own project.

It's working fine if there is more than enough items that requires scrolling, but the thing is the _onScroll() won't get triggered when there are only few items(not enough item which requires scrolling) in the listview so the hasReachedMax is still true thus causing the progress indicator to show all the time. How can that case be handled?

The issue i'm facing can be reproduced by simply limiting the item count to 4 in the http response(mentioned above).

I've tried some workaround  by refering to stackoverflow that check if scrolling is required or not, but ended up getting error
[https://stackoverflow.com/questions/63270853/detect-if-a-singlechildscrollview-listview-can-be-scrolled](url)

**Comment by felangel** [comment]
@naveenkmavoor you should be able to hook into when the ScrollController has a listener attached and perform some logic like:

```dart
  late final ScrollController _scrollController;

  void _onAttach(ScrollPosition position) {
    if (!context.mounted) return;
    // Compare the maxScrollExtent to the controller position offset and if needed trigger an additional fetch.
  }

  @override
  void initState() {
    super.initState();
    _scrollController = ScrollController(onAttach: _onAttach);
    _scrollController.addListener(_onScroll);
  }
```

Hope that helps! Closing for now but if you're still having trouble feel free to ask any clarifying questions on [Discord](https://discord.gg/bloc) and I'm more than happy to help 👍
