### ISSUE TITLE
docs: Possible mistake in "Observing a bloc" section

### ISSUE THREAD

**Issue by GraSim** [felangel/bloc#3992]
In the **Observing a Bloc** section it says the output of overriding the `onTransition` method is:

```
Transition { currentState: 0, event: Increment, nextState: 1 }
Change { currentState: 0, nextState: 1 }
```

Is this a mistake? Should this be `event: CounterIncrementPressed` instead? If not, can you clarify how the code got `Increment` as the event name? 

Link to docs: https://bloclibrary.dev/#/coreconcepts?id=observing-a-bloc

**Comment by codesculpture** [comment]
Technically it would print Instance of 'CounterIncrementPressed', and @felangel  can we print event.runTimeType than just event

**Comment by codesculpture** [comment]
I guess its not a better idea to print event.runtimeType since some may prefered to use toString.

**Comment by codesculpture** [comment]
@GraSim Raised a PR for this (see above)
