### ISSUE TITLE
docs: Blocs should never directly emit new states

### ISSUE THREAD

**Issue by yerzhant** [felangel/bloc#3994]
As blocs _are directly emitting_ in event handlers I believe that the warning [here](https://bloclibrary.dev/#/coreconcepts?id=state-changes-1)  (at the bottom):

> Blocs should never directly emit new states...

should sound like this "Blocs' **users (clients)** should never directly **call** emit **on it**...".

**Comment by felangel** [comment]
The copy is now:

> Blocs should never directly emit new states. Instead every state change must be output in response to an incoming event within an EventHandler.

Hopefully that clears things up, closing for now 👍
