### ISSUE TITLE
How to add a dialog with the result to a сubit

### ISSUE THREAD

**Issue by saucelooker** [felangel/bloc#3997]
Hello. I have a screen for loading all application modules on startup and a сubit for this screen. This screen has a progress bar that I update after each module is loaded. And one of the modules requires user participation. For this I use dialog. And I can't figure out how to return the user's response to cubit and continue loading modules. 
My cubit code looks something like this

    class PreloaderCubit extends Cubit<PreloaderState> {
  
      PreloaderCubit(super(PreloaderState.init()) {
          _init();
        }
    
        Future<void> _init() async {
           await loadingFirstModule();
           emit(PreloaderState.progressChanged());
           await loadingTwoModule();
           emit(PreloaderState.progressChanged());
            .
            .
            .
            .
            .
           Here I need to show the dialog, wait for the user to respond and continue loading
           emit(PreloaderState.progressChanged());
        }
    }

Thank you!

**Comment by saucelooker** [comment]
Do you mean something like that?

    class PreloaderCubit extends Cubit<PreloaderState> {
  
    PreloaderCubit(super(PreloaderState.init()) {
        _init();
      }
  
      Future<void> _init() async {
         await loadingFirstModule();
         emit(PreloaderState.progressChanged());
         await loadingTwoModule();
         emit(PreloaderState.progressChanged());
          .
          .
          .
          .
          .
         emit(PreloaderState.showDialog());
      }
  
      userClickedOk(){
         emit(PreloaderState.progressChanged());
        .
        .
        .
        .
        .
        Loading other modules...
      }
  }

**Comment by codesculpture** [comment]
Exactly

**Comment by saucelooker** [comment]
Thank you. This looks like a solution in a specific case. But I thought there was something like this: 

     Future<void> _init() async {
         await loadingFirstModule();
         emit(PreloaderState.progressChanged());
         await loadingTwoModule();
         emit(PreloaderState.progressChanged());
          .
          .
          .
          .
          .
         var result = await DialogManager.showDialog<bool>(some data);
         if(result){
           do something
         }
      }
    
I have seen several such solutions, but they seem to contradict the BLoC concept. I just thought there was some BLoC solution that could take me back from the dialog to the same place in the code.

**Comment by codesculpture** [comment]
Yeah as u said, this can contradict bloc concept since involving UI controller in bloc. But i guess u can make the previous (proper) solution to more elegant i guess am not in laptop right now.
