### ISSUE TITLE
fix: blocTest fails to check errors when bloc is instanciated in setUp

### ISSUE THREAD

**Issue by B0berman** [felangel/bloc#3999]
**Description**
When building a blocTest that checks for errors, if the bloc is built in the "setUp" function (of the group) the test fails, whereas calling the bloc's constructor directly from the build method of the testBloc makes it succeed.

I have two questions:
- Which way should be used?
- How is it that building the bloc in the setUp results in the test failing?

**Steps To Reproduce**

1. Create a bloc with a method that calls "addError" when handling an event.
2. Create a test that builds the bloc in the "setUp" function of the group
3. Create a test that builds the bloc in the "build" function of the testBloc

**Expected Behavior**
The first test will fail, the second test will succeed

**Additional Context**

At the bottom of the [Bloc Documentation](https://bloclibrary.dev/#/testing), the bloc is built in the "setUp" function, which is confusing when considering the problem I just described.

Thank you!

**Comment by MichalStaszkiewicz** [comment]
Hello 

You should build blocs in the build function, not the setUp function.

This ensures that each test starts with a fresh bloc instance and avoids state leakage
and conflicting expectations between tests.

**Comment by B0berman** [comment]
Thanks a lot for the answer, it would be great to reflect that in the documentation
