### ISSUE TITLE
build: Update bloc dependency version in flutter_bloc

### ISSUE THREAD

**Issue by SamuelGadiel** [felangel/bloc#4000]
**Description**
The flutter_bloc package still uses bloc 8.1.1
VSCode shows a popup asking to update it to 8.1.2 every time it launches
Can we update it in the pubspec?

![image](https://github.com/felangel/bloc/assets/22757108/3064755c-4987-4224-85b1-43360c93e7ff)

**Comment by felangel** [comment]
Hi @SamuelGadiel 👋
I believe this is happening because your pubspec.lock does not contain the latest version of bloc. You can update that by running flutter packages upgrade. Hope that helps 👍
