### ISSUE TITLE
Why shouldn't blocs reference other blocs?

### ISSUE THREAD

**Issue by bw-flagship** [felangel/bloc#4002]
First of all: Thanks for this great package!

**Description**

We have a medium to large-sized codebase with hundreds of cubits.
Many cubits reference each other.

My colleagues started to do some refactorings because they read in the bloc documentation that blocs should not reference each other. 

Source in the docs:
https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication

I am wondering if is a good rule.
When cubits reference each other, I feel like the code is easy to read and easy to maintain.
Instead, if Cubit A and Cubit B logically depend on each other, it's very complicated code because you route the information through at least one other layer, just to avoid the reference.

The only reason I can see in the docs it this:

> Generally, sibling dependencies between two entities in the same architectural layer should be avoided at all costs, as it creates tight-coupling which is hard to maintain. Since blocs reside in the business logic architectural layer, no bloc should know about any other bloc.

In all architecture patterns that crossed my way, it was allowed (and common) that entities inside the same architectural layer reference each other.
One very obvious example is that in frontend frameworks, ui elements get referenced by other ui elements.

Am I missing something?
Looking forward to hearing different opinions :)

**Comment by MrIceman** [comment]
That's because a Cubit is similar to a ViewModel and manages the state for one View. Coupling Cubits to each other will indirectly couple the state management of multiple views, which can easily lead to side effects and bugs. If you want to share logic then use a pattern such as Clean-Architecture and create "Use-Case" classes in your domain layer, which you can then use within your Cubits

**Comment by bw-flagship** [comment]
@MrIceman Thanks for your reply.

I try to create an example to make it clearer:

![image](https://github.com/felangel/bloc/assets/89379862/efae038a-1764-4bbb-b82a-411addbbedb5)

Here, the ToDosCubit needs to reference the dataPreferenceCubit to know if the data should be synced.

Would you say there needs to be some kind if "usecase"-class which keeps the state of the data preferences, so the todosCubit can access it?

**Comment by bw-flagship** [comment]
@esDotDev Thanks for sharing your insights— I thoroughly agree.
After working with both architectures, I find that the one where cubits reference other cubits is significantly easier to read, maintain, and debug.

That said, I do recognize the advantages of extreme decoupling, and I appreciate your explanation of them.

In my current practice, I recommend allowing cubits to reference other cubits in smaller to medium-sized teams (1-5 developers). For larger teams (6 or more developers), I suggest adopting extreme decoupling.

However, I still believe it's a mistake for the documentation to rigidly state that blocs should not reference other blocs.

**Comment by blackchineykh** [comment]
@bw-flagship i believe your `DataPreferencesCubit` should instead be some kind of service or repository that is injected into your `TodosCubit` so that it can be properly mocked for testing and re-used from other areas of your app where it may be useful to know about some other preferences that the user has.

**Comment by bw-flagship** [comment]
@blackchineykh Yes, this would work, even though it adds just another component with redundant information.
(and I can mock the DataPreferencesCubit as well as any other class)

**Comment by wujek-srujek** [comment]
Had the exact same question months ago, see #3316.
