### ISSUE TITLE
feat: Maybe let's use not only states, and add messages bloc  ? also make all events with completer 

### ISSUE THREAD

**Issue by Hellomik2002** [felangel/bloc#4003]
I think the case is when I need to listen to the bloc but don't hurt my View layer by the logic process. 
It may maybe a little bit complicated, but I am thinking about adding messages from the bloc, and also making all events, listenable by complete.
I will do the pull request to show how I see it

**Comment by felangel** [comment]
Closing this as a duplicate of #4008
