### ISSUE TITLE
bloc_concurrency - sequential() only works with the same event

### ISSUE THREAD

**Issue by StefanoV1989** [felangel/bloc#4004]
**Description**
I was searching for a way to get a sequential run of my bloc events, and i tried out bloc_concurrency.
But i notice it works only if you fire the same event.

**Steps To Reproduce**

1. Download the example counter from the bloc_concurrency folder.
2. Add a new event (for example **CounterIncrementPressed2**).
3. Copy the bloc code for the new event (don't forget the sequential() as transformer).
4. Edit the code adding the new event as second.
```
bloc.add(CounterIncrementPressed());
await tick();
bloc.add(CounterIncrementPressed2());
await tick();
bloc.add(CounterIncrementPressed());
await tick();
```
5. Run the code.

**Behavior**
If you use the same event, the counter run every 1 second. But if you have this new event, the counters 1 and 2 run concurrentially and after 1 second you get the 3.

**Expected Behavior**
The expected behavior would be a sequential executions of all the events, not just the same if repeated.

**Additional Context**
I wonder if this is a bug, or a normal behavior for this package.
But imagine i have a bank bloc, an amount of 100 and an event "pay". If i call it 2 times with sequential() i can get the sequential behavior, but if i have another event (for example sendAmountToFriend), that call is not sequential anymore potencially hitting a negative value.

**Comment by felangel** [comment]
Hi @StefanoV1989 👋 
Thanks for opening an issue!

Transformers only apply to the event handlers you add them to. if you want all events to be handled sequentially then you need to apply `sequential` to a single event handler for all events like:

```dart
class CounterBloc extends Bloc<CounterEvent, int> {
  CounterBloc() : super(0) {
    on<CounterEvent>(
      (event, emit) {
        if (event is CounterIncrementPressed) {
          emit(state + 1);
        }
        if (event is CounterDecrementPressed) {
          emit(state - 1);
        }
      },
      transformer: sequential(),
    );
  }
}
```

Hope that helps 👍
