### ISSUE TITLE
fix: Unable to use bloc consumer and go router together in flutter web, site get redirected to "/" automatically.

### ISSUE THREAD

**Issue by asifakhtar98** [felangel/bloc#4010]
**Steps To Reproduce**

1. Create a project with go router and bloc
2. Use bloc consumer on a nested page
3. Access the nested page directly by changing url in browser 
4. You will see the error 

**Expected Behavior**
It should stay on the same page which I am typing in url

**Comment by felangel** [comment]
Hi @asifakhtar98 👋
Can you please share a link to a minimal reproduction sample? I don’t have enough information to help based on the info you’ve provided.

**Comment by felangel** [comment]
Closing for now since there aren't any actionable steps without a reproduction sample.
