### ISSUE TITLE
Question: Cancel running streams with another event 

### ISSUE THREAD

**Issue by IntCleastwood** [felangel/bloc#4011]
I have a problem with bloc and don't know how to solve it. Imagine a BLOC with a use case returning a stream. For each event on the stream, i wanna emit a state:

```
on<MyBlocStartEvent>((event, emit) async {
    Stream stream = useCaseResponse.stream;
    
    await stream.forEach((MyModel streamEvent) {
        emit(state(property: streamEvent.property ...));
    })
}
```
If the use presses the cancel button in frontend, i wanna fire another event and cancel this process (and introduce a canceled or init state again) ... 

```
on<MyBlocCancelEvent>((event, emit) async {
    //should cancel all the stream stuff etc. 
    //also emit the "init" state so that we can start over again when the user press the button
}
```

Since it seems, that this stream.foreach can't be canceled (?), there is no way to interrupt the running process from the outside ... how to solve it the bloc way?

I also tried to convert the stream.foreach into stream.listen, but then i get other issues with any emits in the bloc:

`emit was called after an event handler completed normally. This is usually due to an unawaited future in an event handler. Please make sure to await all asynchronous operations with event handlers and use emit.isDone after asynchronous operations before calling emit() to ensure the event handler has not completed.` 
Tried to add "await" whereever it was possible, but no luck ...

I am not that much into async stuff yet but it seems that any async code, that can not be awaited (like stream.listen), will throw an error ... 

Any idea?

**Comment by jacobtipp** [comment]
@IntCleastwood, one thing I can think of is maybe trying something like this:

Add a `canceled: boolean` property to your `MyBlocStartEvent`. Then you can add a `restartable()` event transformer from the `bloc_concurrency` package to your event handler

```dart
on<MyBlocStartEvent>((event, emit) async {
    if (event.canceled) {
      emit(....) // emit your init state or canceled state
    } else {
       Stream stream = useCaseResponse.stream;
    
       // use emit.forEach to listen to your stream
       await emit.forEach(
         stream, 
         onData: (MyModel streamEvent) => state(property: streamEvent.property ...)
       })
    }
}, restartable())
```

and your cancel event handler

```dart
on<MyBlocCancelEvent>((event, emit) {
    // just add your event with canceled property set to true
    add(MyBlocStartEvent(canceled: true))
}
```

Restartable should always cancel the previous handler which closes any streams `emit.forEach` was listening to.

**Comment by IntCleastwood** [comment]
Hello and thanks for your response. I had a look at the timer example and i saw, that the bloc holds the stream as a member variable. While indeed this would work, isn't this something violating the bloc pattern? The bloc itself should handle the logic and represent everything statefful via states(?) Or do i miss something here? What would prevent me put everything stateful on the bloc itself? Where is the limit?

Best

**Comment by dmiedev** [comment]
I think it would be good to have some direct control of that subscription though some interface, although I have no idea whether it's good from architecture point of view.
