### ISSUE TITLE
fix: ReorderableListView flickers with Flutter BLoC

### ISSUE THREAD

**Issue by JDVila** [felangel/bloc#4013]
**Description**

First off - Thank you so much for maintaining the Flutter BLoC Library! This is an amazing resource, and I'm grateful for it every day!!!

As for the issue, when creating a Flutter Web App, items in a `ReorderableListView` flicker with old values before they are updated with the correct items from the BLoC. This does not occur when using `setState(( ) { })` on the `state` parameter provided by the `BlocBuilder`. I'm assuming this is due to some sort of race condition where the widget rebuilds based on the reordering of the items before the Bloc emits a new value, then the widget rebuilds again. However, it is odd that this isn't the case with the `state` parameter, and although I could just use `setState(( ) { })` here, it feels like an anti-pattern since the BLoC already manages state.

Additionally, it looks like this issue has been encountered by other developers as well: https://github.com/felangel/bloc/issues/3896

Please see a snippet of my code below:

```
BlocBuilder<ListBloc, ListState>(
        builder: (context, state) {
          switch (state) {
            case ListInitial():
              BlocProvider.of<ListBloc>(context).add(
                ListPageLoaded(),
              );
              return Container();
            case ListLoading():
              return Container();
            case ListLoadedSuccess():
              return ReorderableListView(
                scrollDirection: Axis.horizontal,
                onReorder: (int oldIndex, int newIndex) {
                  BlocProvider.of<ListBloc>(context).add(
                    ListReordered(oldIndex, newIndex),
                  );
                },
                children: state.list
                    .map(
                      (e) => ListColumn(
                        key: GlobalKey(),
                        id: e.id,
                        title: e.title
                      ),
                    )
                    .toList(),
              );
            case ListLoadedError():
              return Container();
            default:
              return Container();
          }
        },
      ),
```
**Steps To Reproduce**

1. Place a `ReorderableListView` within a BlocBuilder
2. Reorder the list with a drag and drop swipe
3. Update the Bloc in the `onReorder` callback function 

**Expected Behavior**
Items should not flicker with old values, but they do.

**Screenshots**
n/a

**Additional Context**
Thank you again - open-source contributors are a gift to humanity!!!

**Comment by felangel** [comment]
Hi @JDVila 👋 
Thanks for opening an issue!

Are you able to provide a link to a minimal reproduction sample? I'm happy to take a closer look 👍

**Comment by KrisBraun** [comment]
The core issue is that `bloc` updates asynchronously. `ReorderableListView` re-renders after calling `onReorder` but before `BlocBuilder` has updated.

I found the simplest solution is to wrap `ReorderableListView` with a stateful component that caches the list, allowing it to be updated in `onReorder` and then overwritten when `BlocBuilder` updates.

```dart
import 'package:flutter/material.dart';

typedef ListItemWidgetBuilder<T> = Widget Function(
    BuildContext context, T item);

class CachedReorderableListView<T> extends StatefulWidget {
  const CachedReorderableListView(
      {required this.list,
      required this.itemBuilder,
      required this.onReorder,
      super.key});

  final List<T> list;
  final ListItemWidgetBuilder<T> itemBuilder;
  final ReorderCallback onReorder;

  @override
  CachedReorderableListViewState<T> createState() =>
      CachedReorderableListViewState<T>();
}

class CachedReorderableListViewState<T>
    extends State<CachedReorderableListView<T>> {
  late List<T> list;

  @override
  void initState() {
    list = [...widget.list];
    super.initState();
  }

  @override
  void didUpdateWidget(covariant CachedReorderableListView<T> oldWidget) {
    if (widget.list != oldWidget.list) {
      list = [...widget.list];
    }
    super.didUpdateWidget(oldWidget);
  }

  void updateList(List<T> value) {
    setState(() {
      list = value;
    });
  }

  @override
  Widget build(BuildContext context) {
    return ReorderableListView.builder(
      itemCount: list.length,
      itemBuilder: (context, index) => widget.itemBuilder(context, list[index]),
      onReorder: (int oldIndex, int newIndex) {
        setState(() {
          if (oldIndex < newIndex) {
            newIndex -= 1;
          }
          final item = list.removeAt(oldIndex);
          list.insert(newIndex, item);
        });
        widget.onReorder(oldIndex, newIndex);
      },
    );
  }
}

// Then in your widget
CachedReorderableListView(
  onReorder: (int oldIndex, int newIndex) async {
    // Generate a bloc event
  },
  list: yourList,
  itemBuilder: (context, item) {
    // render a list item
  },
);
```
