### ISSUE TITLE
Getting Assertion error when emit a state in aysnc function

### ISSUE THREAD

**Issue by MS-Drip** [felangel/bloc#4018]
Hi @felangel 

`Future<void> fetchInitialData(FetchInitialDataEvent event, Emitter<WalletState> emit) async {
    if (wallets != null) {
      emit(WalletListState(wallets: wallets!));
    } else {
      walletsModel = await getWallets();
      assetsModel = await getSupportedAssets();
      cmc = await getCmc();
      currencies = await getCurrencies();

      fetchAddress();

      wallets = walletEngine.buildWallet(assetsModel, walletsModel, cmc);
      if (wallets != null && configEngine.filteredMarkets == null && configEngine.orgMarkets != null) {
        configEngine.filteredMarkets = walletEngine.filterMarket(wallets!, configEngine.orgMarkets!);
        openSocket.init(configEngine.filteredMarkets!);
      }
      emit(WalletListState(wallets: wallets!));
    }

    if (currencies != null) {
      listenTickerStream(currencies!, coins);
    }
    startWalletScheduler(emit);
  }

  startWalletScheduler(Emitter<WalletState> emit) {
    if (walletScheduler?.isActive != true) {
      Duration interval = Duration(seconds: walletIntervalSeconds);
      walletScheduler = Timer.periodic(interval, (timer) async {
        await periodicFetch(emit);
      });
    }
  }

  Future<void> periodicFetch(Emitter<WalletState> emit) async {
    walletsModel = await getWallets();
    wallets = walletEngine.buildWallet(assetsModel, walletsModel, cmc);
    emit(WalletListState(wallets: wallets!));
  }
  
  Future<WalletsResponse?> getWallets() async {
    final result = await repo.wallets(cancelToken: cancelToken);

    return result.fold((error) {
      return Future.value(null);
    }, (resp) {
      return resp;
    });
  }
  `
  
  getCmc and getCurrencies are in the same structure as getWallets(). When i execute this code, I am getting the below error
  
  _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
[        ] I/flutter ( 8440): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
[        ] I/flutter ( 8440): #2      _Emitter.call (package:bloc/src/emitter.dart:114:7)
[        ] I/flutter ( 8440): #3      WalletBloc.periodicFetch (package:drip_mobile/src/core/wallet/biz/wallet_bloc.dart:122:9)
[        ] I/flutter ( 8440): <asynchronous suspension>
[        ] I/flutter ( 8440): #4      WalletBloc.startWalletScheduler.<anonymous closure> (package:drip_mobile/src/core/wallet/biz/wallet_bloc.dart:114:9)
[        ] I/flutter ( 8440): <asynchronous suspension>

This error is happening during emit(WalletListState(wallets: wallets!)); inside periodicFetch(). What am i doing wrong here? How to efficiently use emit in async functions?

**Comment by notAravind** [comment]
Rather than passing emit to handler and invoking after certain interval (through Timer.periodic), can u create a new seperate event and trigger the event after this Timer.periodic. And when the event trigger u can continue the periodicFetch functionality. By this u need not require emit as a param, but u have emit by urself since u are in the new event itself.

**Comment by codesculpture** [comment]
Rather than passing emit to handler and invoking after certain interval (through Timer.periodic), can u create a new seperate event and trigger the event after this Timer.periodic. And when the event trigger u can continue the periodicFetch functionality. By this u need not require emit as a param, but u have emit by urself since u are in the new event itself.

**Comment by MS-Drip** [comment]
@codesculpture to do your suggestion, i should emit a state inside timer.periodic which will trigger another event from the widget to perform the periodicFetch method. but the timer will be still in bloc that need an emit.

**Comment by codesculpture** [comment]
Do like this, Create a new event Called PeriodicFetch which can be triggered through Timer.periodic

```dart
fetchInitialData(Emitter emit) {
   ....
   Timer.periodic(interval, () => add(PeriodicFetch()):
   ...
}

on<PeriodicFetch>((event, emit) => {
     // Perform ur periodicfetch logic here
     emit() // u can use this emit
}

```

**Comment by MS-Drip** [comment]
Nice, It worked. Thanks for the suggestion. @codesculpture

**Comment by MS-Drip** [comment]
Worked and closing this.
