### ISSUE TITLE
fix: hydrated_bloc is not working like it should

### ISSUE THREAD

**Issue by ellet0** [felangel/bloc#4024]
**Description**

**Steps To Reproduce**

1. `git clone https://github.com/singerdmx/flutter-quill.git`
2. Go to the example and run it, go to the settings of the app, change some stuff and hot restart, go back and see if they are saved
3. Now stop the app and upgrade to hydrated_bloc to `9.1.3` or the latest version in the `pubspec.yaml` of the example
4. Run the app again and repeat step 2
5. Compare the results

I'm not sure yet but I can confirm there is an issue, I tried an old project that uses 9.1.2 and it was fine but once I upgraded to 9.1.3 the issue happened again and it still reverted to 9.1.2

deleting the cached 9.1.3 doesn't help

which is interesting

**Expected Behavior**
Hydrated bloc might have a bug, it should save and load the data as expected just like in version `9.1.2` and older versions

**Screenshots**

**Additional Context**
Possible commits that caused the bug

[#4005](https://github.com/felangel/bloc/pull/4005)
[#3919](https://github.com/felangel/bloc/pull/3919)

**Comment by felangel** [comment]
Hi @freshtechtips 👋 
Thanks for opening an issue!

Can you please share more information including the error that you're observing as well as a link to a minimal reproduction sample? Thanks!

**Comment by freshtechtips** [comment]
> Hi @freshtechtips 👋 
> Thanks for opening an issue!
> 
> Can you please share more information, including the error that you're observing, as well as a link to a minimal reproduction sample? Thanks!

My apologies 
I already mentioned I don't have more info for now

Once I have, I will

But I have a public repo that's already has the issue 

But it will require you to set up a firebase using firebase cli (flutterfire)

Are you interested?

**Comment by freshtechtips** [comment]
> Hi @freshtechtips 👋 Thanks for opening an issue!
> 
> Can you please share more information including the error that you're observing as well as a link to a minimal reproduction sample? Thanks!

Just updated the report, you can take a look now

**Comment by freshtechtips** [comment]
> Hi @freshtechtips 👋 Thanks for opening an issue!
> 
> Can you please share more information including the error that you're observing as well as a link to a minimal reproduction sample? Thanks!

So is there are any other info that I should provide?

**Comment by freshtechtips** [comment]
I tried 
![image](https://github.com/felangel/bloc/assets/73608287/c2bc59b2-4d0b-4aa6-865b-ca666961bb9f)
hive and it works as expected, I also tried manually generating the toJson and fromJson and it doesn't help, the thing is I don't understand, every project that used 9.1.2 and then upgraded to 9.1.3 then the issue will remain even after downgrade to 9.1.2

**Comment by felangel** [comment]
@freshtechtips thanks! I'll take a look this weekend 🙏

**Comment by jabransiddiqui** [comment]
@ellet0 
you need to call `hydrate(); ` see the attach screenshot 
<img width="695" alt="Screenshot 2023-12-27 at 11 15 56 PM" src="https://github.com/felangel/bloc/assets/23705554/537dbd8c-f31a-4e75-96f0-565b0a493b1f">

**Comment by ellet0** [comment]
> @ellet0 
> you need to call `hydrate(); ` see the attach screenshot 
> <img width="695" alt="Screenshot 2023-12-27 at 11 15 56 PM" src="https://github.com/felangel/bloc/assets/23705554/537dbd8c-f31a-4e75-96f0-565b0a493b1f">
> 

We are using HydratedCubit

**Comment by ellet0** [comment]
Thanks, the issue has been solved on the project I attached in the steps to reproduce thanks to @jabransiddiqui, even though it didn't got fixed in the other project but that's probably because of a bug on my side
