### ISSUE TITLE
docs: I need help understanding Bloc-to-Bloc Communication 

### ISSUE THREAD

**Issue by bensonarafat** [felangel/bloc#4025]
**Description**

Hi, @felangel  
I am communicating between two blocs on my app, i use the best practices on the online docs but something seems to be wrong somewhere...

When I launched the app the first time.. the event was triggered but the second time I was on that page, this event will not trigger. 
NOTE: I added the event on my `initState`. 

But if i add a button on that page to trigger the event it works fine. 

This is how i structured it. 
Bloc A -> Listen for user location change and send the lat and long to Bloc B which then sent to the backend 
Bloc B ->  Update the UI & send the update to the backend 

This is a sample 

```
void main(){
 WidgetsBinding widgetsBinding = WidgetsFlutterBinding.ensureInitialized();

  runApp(const App());
}

class App extends StatelessWidget{
 const App({super.key});

 @override 
 Wiget build(BuildContext context) {
   return MultBlocProvider(
     providers: [
        BlocProvider<BlocA>( create: (_) => BlocA() ), 
        ....
        ....
      ],
    child: MaterialApp.router(
      title: 'App', 
      routerConfig: router, 
      debugShowCheckedModeBanner: false,
      ),
   );
 }
}
```
 router 

```
final GoRouter router = GoRouter(
   initialLocation: "/",
  routes: [
    GoRoute(
     path: '/',
     name: 'pageA',
     builder: (context, state) => const PageA(),
    ), 
   GoRoute(
    path: '/pageB' , 
    name: 'pageB', 
    builder: (context, state) => const PageB(),
),
   ]
);
```

Page A 

```
class PageA extends StatefulWidget {
  const PageA ({super.key});

  @override
  State<PageA> createState() => _PageAState();
}

class _PageAState extends State<Home> {
  
  @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
         context.read<BlocA>().add(Event());
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MultBlocProvider(
           providers: [
                BlocProvider<BlocB>(
                  create: (BuildContext context) => BlocB(),
                ),
      ],
     child: BlocListener<BlocA, BlocAState>(
              listener: (context, state) {
          if (state is BlocAFetch) {
            context.read<BlocB>().add(
                  BlocBUpdate(
                    latitude: state.latitude,
                    longitude: state.longitude,
                  ),
                );
          }
        },
     ),
    );
  }

```

**Comment by felangel** [comment]
Hi @bensonarafat 👋 
Thanks for opening an issue!

Have you tried providing a `BlocObserver` and overriding `onEvent` and `onChange` to verify whether or not the event is received and whether the new state is emitted? I'd also recommend checking out [the FAQs](https://bloclibrary.dev/#/faqs?id=state-not-updating).

If that doesn't help, please provide a link to a minimal reproduction sample and I'm happy to take a closer look.

**Comment by bensonarafat** [comment]
Thanks. 
Just discovered it was not emitting.
