### ISSUE TITLE
discussion: Implementing Dynamic Bloc Switching

### ISSUE THREAD

**Issue by MobiliteDev** [felangel/bloc#4027]
Hello, 

I'm currently working with a library that employs bloc across my entire application. This library is directly utilized by several applications. However, in one specific app, I face the need to substitute a particular bloc (for instance, bloc A) with a different implementation (let's call it speA), which is defined at the application level. Is there a strategy to seamlessly switch out bloc A for speA in this scenario without the necessity of duplicating the entire library and manually replacing A with speA throughout?

**Comment by felangel** [comment]
Hi @MobiliteDev 👋 
Thanks for opening an issue!

Are you able to provide more context regarding what you're trying to achieve? It would be great if you could elaborate on your specific use-case and provide a link to a minimal reproduction sample, thanks! 🙏

**Comment by lucasshiva** [comment]
> Hi @MobiliteDev 👋 Thanks for opening an issue!
> 
> Are you able to provide more context regarding what you're trying to achieve? It would be great if you could elaborate on your specific use-case and provide a link to a minimal reproduction sample, thanks! 🙏

I guess @MobiliteDev means something similar to Riverpod's `overrideWithValue`?

This is taken from Riverpod's official documentation.
```dart
// We don't have an actual instance of SharedPreferences, and we can't get one except asynchronously
final sharedPreferencesProvider =
    Provider<SharedPreferences>((ref) => throw UnimplementedError());

Future<void> main() async {
  // Show a loading indicator before running the full app (optional)
  // The platform's loading screen will be used while awaiting if you omit this.
  runApp(const LoadingScreen());

  // Get the instance of shared preferences
  final prefs = await SharedPreferences.getInstance();
  return runApp(
    ProviderScope(
      overrides: [
        // Override the unimplemented provider with the value gotten from the plugin
        sharedPreferencesProvider.overrideWithValue(prefs),
      ],
      child: const MyApp(),
    ),
  );
}
```
That's what I understood when they said "substitute a particular bloc instance with a different implementation." So, instead of having to fork the entire library in order to replace a single bloc, they can just override it with a custom implementation instead.

**Comment by tenhobi** [comment]
I would just want to say this is not something Bloc should do. That is rather a DI responsibility.

Cannot you just use `ProviderScope` from `provider` package like in river pod example? Is is that in riverpod only?

Another option, depending on a usecase, might be changing a strategy for handling events (or maybe only one of them) depending on a state inside of that one Bloc. You can for example ad an enum of types to the state and switch that in each handler. 

That depends on the usecase tho of course.

**Comment by felangel** [comment]
I agree with @tenhobi. In addition, you can override an existing bloc by providing a different instance lower in the widget tree.

Closing for now but feel free to comment with additional questions/thoughts and I'm happy to continue the discussion 👍
