### ISSUE TITLE
fix: In Flutter v3.16.4 stable the fromJson method stopped working

### ISSUE THREAD

**Issue by Rupam-Shil** [felangel/bloc#4029]
**Description**
Yesterday we upgraded our app from flutter v3.13 to v3.16, and saw an issue that the `fromJson` method is not getting triggered for any bloc that has a `HydratedMixin`. 

**Steps To Reproduce**

1. Update to flutter v.3.16 stable
2. Add HydratedMixin to bloc
3. override fromJson method

**Expected Behavior**
`fromJson` should trigger like any other version.

**Screenshots**
<img width="401" alt="image" src="https://github.com/felangel/bloc/assets/68724228/f56e0d14-289a-4ec2-aa1f-6ef520a0f90f">

**Additional Context**
lutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (4 days ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4

**Comment by jabransiddiqui** [comment]
Its because you need to call `hydrate();` , see the attached screenshot
<img width="695" alt="Screenshot 2023-12-27 at 11 15 56 PM" src="https://github.com/felangel/bloc/assets/23705554/5ec82c94-90ce-47a9-ac8b-582f0e425f80">
