### ISSUE TITLE
Pattern Question

### ISSUE THREAD

**Issue by bobwiller** [felangel/bloc#403]
I have an AuthBloc at the top of my app that holds a reference to an authenticated (Cognito) user.

Then most of my blocs below that in my app need a reference to that user (those blocs call aws resources that require the cognito token stored on the user object).  So I find myself doing this a lot:

`class _MyWidgetState extends State<MyWidget> {
  AuthBloc _authBloc;
  OtherBloc _otherBloc;
  User user = User();
  
  @override
  void initState() {
    _authBloc = BlocProvider.of<AuthBloc>(context);
    user = (_appBloc.currentState as ApplicationAuthenticated).user;
    _otherBloc = OtherBloc(user: user)..dispath(InitializBloc());
  }
--- rest of class ----
}`

Is there a better way to do this?
Thanks,
Bob

**Comment by felangel** [comment]
Hey @bobwiller 👋 
Thanks for opening an issue!

Regarding your question you can just provide the AuthBloc using BlocProvider like so:

```dart
BlocProvider(
  builder: (context) => AuthBloc(),
  child: ChildA(),
)
```

Then in other parts of your app you can initialize blocs that need the user you can access it like so:

```dart
BlocProvider(
  builder: (context) {
    final authBloc = BlocProvider.of<AuthBloc>(context);
    final authBlocState = authBloc.currentState;
    final user = authBlocState is ApplicationAuthenticated ? authBlocState.user : User();
    return OtherBloc(user: user)..dispatch(InitializeBloc());
  },
  child: OtherChild(),
)
```

Alternatively, I'd recommend not keeping the user reference in the AuthBloc and instead have each bloc that needs access to the user have a dependency on the UserRepository and retrieve the user from the repository as needed.

Hope that helps! 👍
