### ISSUE TITLE
why my code will result in error?

### ISSUE THREAD

**Issue by caibimiaokong** [felangel/bloc#4033]
![image](https://github.com/felangel/bloc/assets/90626136/aa5a710d-5574-400c-bf27-f6829595c45c)
I use this method to provieder MapBloc,but I recive below error:
![image](https://github.com/felangel/bloc/assets/90626136/1363fef3-e3d7-470e-b713-85f4fe5e948f)
code in github [here](https://github.com/caibimiaokong/map/blob/3cfcfb60b0f62160af9ff12baa75e9293e70eec9/lib/feature/map_feature/view/map_view.dart#L10)

 Looking forward to hearing from you

**Comment by codesculpture** [comment]
The source file seems changed (i looked through the source code), Also dont use the context (for ReposityProvider.of) from BlocProvider(create: (context){...}) instead  use context from build method 
Widget build(BuildContext context)

**Comment by caibimiaokong** [comment]
thanks for your response,my code can run now!
