### ISSUE TITLE
BlocBuilder not getting called after creating new task, ListView still displays old data

### ISSUE THREAD

**Issue by laggedskapari** [felangel/bloc#4034]
### **SOMEBODY HELP ME!!!!!!**

https://github.com/laggedskapari/minimalistics/blob/nexus/cross/cross_f/lib/widgets/tasks_list_view.dart

**Comment by codesculpture** [comment]
What help u need ?

**Comment by laggedskapari** [comment]
Found my mistake. Sorry guys.
