### ISSUE TITLE
feat: Use with Freezed

### ISSUE THREAD

**Issue by biancashouse** [felangel/bloc#4036]
If I change

    class SnippetBloC extends Bloc<SnippetEvent, SnippetState> {...

to
   class SnippetBloC extends ReplayBloc<SnippetEvent, SnippetState> {...

I then have an issue with my Events:

    class SnippetEvent with _$SnippetEvent {...

My bloc events use Freezed, so I cannot extend ReplayEvent ?

**Comment by felangel** [comment]
Seems related to https://github.com/rrousselGit/freezed/issues/907. Closing this since I don't think there's anything that can be done in the bloc library as it seems this needs to be addressed in freezed.
