### ISSUE TITLE
BlocBuilder only build once and stop rebuild with subsequent emit

### ISSUE THREAD

**Issue by TENX-S** [felangel/bloc#4037]
I have an IconButton that click on it will pin/unpin the window, and the icon will change according to pinned or not. The first click on the button will trigger a rebuild event, but subsequent click does not. And I have absolutely no idea on it.

I created a minimal example here: https://gist.github.com/TENX-S/7a811cb23b3b0ed220b75f4b2cda7fd3, for repo: https://github.com/TENX-S/miniexample

I tried to read documentation on https://bloclibrary.dev/, but I'm not getting the answer to it.

![Screen Recording 2024-01-08 at 10 39 18](https://github.com/felangel/bloc/assets/40336192/f5a63a6a-56bc-4af3-b0ba-6881bd867f3d)

Extra info:
```sh
Flutter 3.18.0-18.0.pre.25 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 02d1d64e7f (2 weeks ago) • 2023-12-23 10:02:06 -0500
Engine • revision 8b839eda79
Tools • Dart 3.3.0 (build 3.3.0-260.0.dev) • DevTools 2.31.0-dev.0
```

**Comment by codesculpture** [comment]
Can u provide the output of the logs, build $alwaysonTop with screen recording @TENX-S

**Comment by TENX-S** [comment]
Yes @codesculpture 

https://github.com/felangel/bloc/assets/40336192/5edd8c51-dc1d-422b-9e91-eb92aa8b47ea

**Comment by codesculpture** [comment]
Seems u made a hot-restart, can u share the log without doing it

**Comment by TENX-S** [comment]
If you do not hot-restart, there's only one log no matter how many times you click that button:
```
flutter: build true
```

**Comment by TENX-S** [comment]
FWIW, here's the video without hot-restart:

https://github.com/felangel/bloc/assets/40336192/d156f2c6-8797-4eac-8e1c-9dd6689c7c35

**Comment by TENX-S** [comment]
So it turns out there is something to understanding; I shouldn't mutate the state but instead, I need to create a new one for emitting. (I learned this from somewhere else)

Sorry for the noise!
