### ISSUE TITLE
fix:  The "New Bloc/Cubit" option is not showing in VSCode Extensions

### ISSUE THREAD

**Issue by luisgustavoo** [felangel/bloc#4040]
**Description**

The "New Bloc/Cubit" option is not showing

**Steps To Reproduce**

1. Right click on the directory in which you want to create the bloc/cubit

**Expected Behavior**
The "New Bloc/Cubit" option

**Screenshots**
<img width="1524" alt="image" src="https://github.com/felangel/bloc/assets/59834387/6442f5fa-f273-4098-8868-acef82cdcd34">

**Comment by felangel** [comment]
@luisgustavoo can you share your `pubspec.yaml`? I'm guessing you don't have bloc as a dependency, thanks!

**Comment by luisgustavoo** [comment]
After I added the dependencies, the options appear. Sorry, I didn't know that there would have to be dependencies in pubspec.yaml for the options to appear.

**Comment by luisgustavoo** [comment]
After I added the dependencies, the options appear. Sorry, I didn't know that there would have to be dependencies in pubspec.yaml for the options to appear.
