### ISSUE TITLE
feat: why not fusion bloc_concurrency package into bloc

### ISSUE THREAD

**Issue by baptistesx** [felangel/bloc#4042]
I am wondering why not fusion bloc_concurrency and bloc packages ? The transformer param feature is quite essential in any common app no? Or i miss something?

Maybe you have already answered this question, sorry if it's the case eI didn't find anything related in the issues.

**Comment by felangel** [comment]
Mainly because it's not much effort to add it as a dependency when needed but not all projects need it. Some build their own custom transformers. Hope that helps 👍

**Comment by EArminjon** [comment]
For me it's a basic feature, it give out of the box a reason to use bloc over cubit without 'custom dev'. Also, the lib code is around 100 lines :')
