### ISSUE TITLE
feat: BlocListener that trigger once but with return specific prop like BlocSelector

### ISSUE THREAD

**Issue by erlangparasu** [felangel/bloc#4043]
**Description**

I'm always frustrated when using BlocListener with call some property in `listenWhen:`, but wrong calling propertiy on `listener:`.

**Desired Solution**

BlocListener that **trigger once** but with return specific prop like BlocSelector does.

**Alternatives Considered**

~

**Additional Context**

~

**Comment by elianortega** [comment]
Hello @erlangparasu, could you expand more on what the expected behavior should look like, or can you share the particular use case you are having trouble with?

**Comment by erlangparasu** [comment]
```dart
BlocListener<DashboardCubit, DashboardState>(
  listenWhen: (previous, current) {
    return previous.saveEvent != current.saveEvent;
  },
  listener: (context, state) {
    final event = state.saveEvent;
    // check event
    // todo show snackbar
  },
),
```

Here are the features I expected
```dart
BlocListener<DashboardCubit, DashboardState>(
  selector: (state) {
    return state.saveEvent;
  },
  selectListener: (context, event) {
    // check event
    // todo show snackbar
  },
),
```

**Comment by felangel** [comment]
Sounds like you resolved this so I'm closing this for now. If this is still an issue let us know and I'm happy to take a closer look 👍
