### ISSUE TITLE
docs: Multiple cubits in single page

### ISSUE THREAD

**Issue by kaj777** [felangel/bloc#4047]
**Description**
This example shows a simple scenario where the page uses a cubit to get information.
https://github.com/felangel/bloc/blob/master/examples/flutter_weather/lib/weather/cubit/weather_cubit.dart
Based on this example, the weather page uses weather cubit for getting weather and toggle units.
On view widget, the progress loading and content display is straightforward.
```
 builder: (context, state) {
            switch (state.status) {
              case WeatherStatus.initial:
                return const WeatherEmpty();
              case WeatherStatus.loading:
                return const WeatherLoading();
              case WeatherStatus.success:
                return WeatherPopulated(
                  weather: state.weather,
                  units: state.temperatureUnits,
                  onRefresh: () {
                    return context.read<WeatherCubit>().refreshWeather();
                  },
                );
              case WeatherStatus.failure:
                return const WeatherError();
            }
```

In real use cases, a page does more than just get, there can be CRUD actions based on the information we get from weather_cubit.

**Use Case 1**
An additional calculate method in weather cubit
-> Weather page first gets information from weather cubit to display weather listing.
-> The page also allows user to input some number values 
-> Click calculate to perform calculation for a result (using input from both weather cubit get and user manual input)

Question:
1.Is it correct for us to emit status success on all updateInput1(), updateInput2() and calculate() methods? Since we need the WeatherPopulated to be shown at all times? My initial assumption was just to emit success for getWeather but not for updating the inputs. It needs to be added so to clear previous error status if any.
Example for updateInput1():
emit(
  state.copyWith(
    status: () => WeatherStatus.success,
    note: () => event.text,
  ),
);

2. The current example shows loading indicator in bloc builder instead of dialog. If I wish to change status to in progress during calculate, it would replace the WeatherPopulated to WeatherLoading, but I wish to remain the WeatherPopulated content. Making this into a bloc listener results in unintended pop dialog since some method might not call inProgress in the first place.

**Use Case 2**
Multiple cubits per page
Weather page -> Click save button to save to save a calculation record to database so that we can view the history listing from profile.
Since it has nothing to do with getting weather, I’ve created a save_calculation_cubit.

How do we deal with the view layer for progress loading, result/ error displaying since there is already a builder specifically for weather cubit only ? 

Overall what is the practice for creating cubit/ bloc, 1 bloc per page or by feature? Such as get_weather_cubit, calculate_weather_cubit, log_weather_result_cubit? Or the above is correct? 

Kindly advice.

**Comment by kaj777** [comment]
@felangel Appreciate your input.

**Comment by felangel** [comment]
Hi @kaj777 👋 
Thanks for opening an issue!

In general, I recommend creating a single bloc/cubit per feature. If you find your "feature" is becoming very broad in scope then it might be a sign that you need to split the bloated feature into multiple smaller features. I highly recommend checking out the [flutter_bloc_feature brick](https://brickhub.dev/bricks/flutter_bloc_feature/0.3.0) to make generating features quick/easy.

Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now since there aren't any actionable next steps.

**Comment by kaj777** [comment]
@felangel For a meal page for example

Should i create feature like the following?
Option A:
-> add_meal
->update_meal
->delete_meal
-> get_meal

Option B
Just a single meal_bloc in general that contains all CRUD for meal.

For option A, the meal page needs to handle the progress bar display handling based on the in_progress state transition from 4 different cubits/bloc.

For optionB, meal page needs to handle only 1 in_progress state, but all CRUD method needs to reset the state to initial again on each trigger to start with a clean state.

Other than the above, there could be situation when I needed meal_bloc (getmeal) and setting_bloc(getsetting) to populate the information needed to display the meal page on loaded. This involve get calls from 2 different cubits, how do we handle the show and hide of the progress bar as one can finishes faster than the other? Or there should be a meal_page bloc to init the information needed to display the page, then for other actions such as create we use create bloc/cubit?

 Appreciate your feedback, thanks.
