### ISSUE TITLE
Implementation of bloc for jaspr 

### ISSUE THREAD

**Issue by DanielCardona** [felangel/bloc#4057]
Can I expect a Implementation of bloc for jaspr: https://github.com/schultek/jaspr.

Thank you very much for your time and work.

**Comment by felangel** [comment]
Hi @DanielCardona 👋 
Thanks for opening an issue!

I haven't used `jaspr` much and I'm not familiar with what it would entail to support jaspr. I assume only a port of `package:flutter_bloc` would be needed as all other packages are pure dart and should be compatible. Is that correct?

**Comment by DanielCardona** [comment]
Hello **@felangel** , from what I understand it is as you describe.

Anyway, I was researching the best way to share code between a Flutter project and its web version (SEO is important).

I was investigating AngularDart, **I loved the structure of your github_search project!!**, but unfortunately AngularDart's SSR support is non-existent and Google has distanced itself from it.

Yesterday, almost by chance since there is not much information available I discovered https://dartfrog.vgv.dev/ and the tutorial https://verygood.ventures/blog/dart-frog-full-stack-tutorial.

So I think that in my case, the need for that port is not necessary as I'm considering to use the last.

From your knowledge and according to my needs, do you think that the dartfrog route is a good option?


Thank you very much once again for your time, the knowledge you share and the inspiration you provide.

**Comment by felangel** [comment]
> Hello **@felangel** , from what I understand it is as you describe.
> 
> Anyway, I was researching the best way to share code between a Flutter project and its web version (SEO is important).
> 
> I was investigating AngularDart, **I loved the structure of your github_search project!!**, but unfortunately AngularDart's SSR support is non-existent and Google has distanced itself from it.
> 
> Yesterday, almost by chance since there is not much information available I discovered https://dartfrog.vgv.dev/ and the tutorial https://verygood.ventures/blog/dart-frog-full-stack-tutorial.
> 
> So I think that in my case, the need for that port is not necessary as I'm considering to use the last.
> 
> From your knowledge and according to my needs, do you think that the dartfrog route is a good option?
> 
> Thank you very much once again for your time, the knowledge you share and the inspiration you provide.

Thanks! I think `dart_frog` is a great solution for writing your backend in dart and sharing code 👍 

Closing this for now since it sounds like there's nothing else to do, thanks!

**Comment by DanielCardona** [comment]
Hi again @felangel 👋, I'm reopening this post because I'm now in the real-world scenario and I see that Frog isn't suitable for my scenario. I need to create a web page, not a backend. 
Jaspr does everything I need, with SSR and is easy to use. I even can share my domain and use Flutter for my app and Jaspr for my web needs. The only missing part is the Bloc implementation.
On the other hand, Jaspr is gaining a lot of traction in the Dart community, and I have no doubt that many people would use Bloc if it were available.

Thank you very much for your time and patience.

**Comment by felangel** [comment]
> Hi again [@felangel](https://github.com/felangel) 👋, I'm reopening this post because I'm now in the real-world scenario and I see that Frog isn't suitable for my needs. I need to create a web page, not a backend. Jaspr does everything I need, with SSR and is easy to use. I even can share my domain and use Flutter for my app and Jaspr for my web needs. The only missing part is the Bloc implementation. On the other hand, Jaspr is gaining a lot of traction in the Dart community, and I have no doubt that many people would use Bloc if it were available.
> 
> Thank you very much for your time and patience.

Bloc is available for jaspr (it’s pure dart) and there’s a port of flutter_bloc at https://github.com/f-person/jaspr_bloc

Hope that helps 👍

**Comment by DanielCardona** [comment]
I was aware of this package, but it's 3 years old, then I understand that will keep working with latest versions of bloc? 

Thank so much again.

**Comment by felangel** [comment]
> I was aware of this package, but it's 3 years old, then I understand that will keep working with latest versions of bloc?
> 
> Thank so much again.

The API has been fairly stable so it should still work. I'll see if I can automate generating the flutter_bloc bindings for jaspr and publish 1st party support. Will get back to you in the next few days 👍

**Comment by DanielCardona** [comment]
This would be wonderful 🤗, thank you so much once again for your generosity 🤩.

**Comment by DanielCardona** [comment]
Hello @felangel , have you had time to make some progress?  😄🎈
