### ISSUE TITLE
Mock a bloc for unit tests

### ISSUE THREAD

**Issue by jkyon** [felangel/bloc#409]
Hi

It is there a way to create a mock of a bloc for unit tests? I tried to create a mock but its current state is null.

Thank you in advance

**Comment by felangel** [comment]
Hi @jkyon 👋 
Thanks for opening an issue!

Regarding your question you can create a mock bloc using `mockito` like so:

```dart
class MockBlocA extends Mock implements BlocA {}
```

you can then create an instance like so

```dart
void main() {
  group('Tests', () {
    BlocA blocA;
    
    setUp(() {
        blocA = MockBlocA();
    });
  });
}
```

Then you can make the `currentState` in your tests like so:

```dart
when(blocA.currentState).thenAnswer((_) => BlocAState());
```

Hope that helps and great question! 👍

**Comment by jkyon** [comment]
thank you!
It works perfect!
