### ISSUE TITLE
feat: listen method in BuildContext extension as functioning BlocListener

### ISSUE THREAD

**Issue by Jaew00Shin** [felangel/bloc#4090]
**Description**

I usually use context.watch, context.select, context.read instead of BlocBuilder, BlocSelector. Because, it makes widget tree more clear to use extension method in BuildContext than class widgets.

But there is no context.listen. So I should use BlocListener.
I want to use context.listen method instead of BlocListener.

**Desired Solution**

context.listen<AppBloc, AppState>((context, state) {}, listenWhen: (prev, curr) => true);

The first positional parameter is a function which has two parameters, BuildContext and the state of Bloc respectively.
listenWhen is the named parameter and it functions like listenWhen in BlocListener class.

**Comment by fernan542** [comment]
That's `context.select` in a long form.
Can you give more explanation about your use-case?

**Comment by felangel** [comment]
Closing for now as there's not enough information to take any actionable next steps. If this is still an issue please feel free to provide additional context and I'm happy to continue the discussion 👍

**Comment by Jaew00Shin** [comment]
Sorry for late response.

BlocListener is different with BlocSelector & BlocBuilder. BlocListener just listens when listenWhen condition is satisfied and just handle some event logic, not returning any vlaue.

There is ref.listen method in riverpod.
https://riverpod.dev/ko/docs/essentials/websockets_sync#%EC%8A%A4%ED%8A%B8%EB%A6%BC-%EC%88%98%EC%8B%A0%ED%95%98%EA%B8%B0listening

And I want to use 
context.listen<SomeBloc, SomeState>((BuildContext context,SomeState state) {
// event logic;
}, listenWhen: (SomeState prev, SomeState curr) => true);

listener works only if listenWhen returns true.

I want to simplify my widget tree. I think it could be a solution to replace BlocListener to context.listen extension.
