### ISSUE TITLE
docs: replay bloc with multi bloc

### ISSUE THREAD

**Issue by onism0106** [felangel/bloc#4116]
Hello, thank you very much for this library first.

 I am currently migrating my project to Bloc. During this process, I encountered an issue regarding replay. 

Following clean architecture principles, I have divided my application into multiple blocs. My application is a large desktop application that requires redo and undo functionality. For example, a certain page has two sub-modules, A and B, each with their respective blocs, blocA and blocB. The user performs actions such as adding an event in blocA and another in blocB. My undo and redo functionality need to listen to the entire page's blocs rather than specific ones. For instance, when the user presses cmd Z, I need to undo blocB events followed by blocA events in the order of the user's actions, rather than undoing events for a specific bloc. How can I implement this? 

Thank you very much.

**Comment by warioddly** [comment]
`Streams` actually work under the hood of a `BLoC`, so you can subscribe to other `BLoC's` events via `StreamSubscription` and listen to their states

```dart

final blocA = BlocA();

blocA.stream.listen((state) {
    /// BlocB implements
});
```

**Comment by felangel** [comment]
Closing for now but if this is still an issue please feel free to provide additional context as well as a reproduction sample and I'm happy to take a closer look, thanks!
