### ISSUE TITLE
Can I put 'BlocBuilder' in customScrollView's Slivers

### ISSUE THREAD

**Issue by NetFly-VPN** [felangel/bloc#412]
I want to put BlocBuilder in to customScrollView's sliver to control widget state's, how can I do

**Comment by felangel** [comment]
Hi @NetFly-VPN 👋 
Thanks for opening an issue!

You can definitely put `BlocBuilder` inside a `CustomScrollView's sliver 👍 
I created a [gist](https://gist.github.com/felangel/a7dfebd482bcb4a792f71c679bbf8df4) that you can check out for an example.

Hope that helps!

**Comment by payam-zahedi** [comment]
hi @felangel,   I have the same issue. but I can't read this gist. it's probably deleted or disabled.

**Comment by tenhobi** [comment]
@payam-zahedi it's visible for me. https://gist.github.com/felangel/a7dfebd482bcb4a792f71c679bbf8df4
