### ISSUE TITLE
Bloc-to-Bloc Communication can't listen BlocState changed

### ISSUE THREAD

**Issue by Huai-Dc** [felangel/bloc#414]
hey @felangel 
i want chang the state file
@immutable
class RegisterState {
  final bool isEmailValid;
  final bool isPasswordValid;

  bool get isFormValid => isEmailValid && isPasswordValid;

  RegisterState({
    @required this.isEmailValid,
    @required this.isPasswordValid,
  });

   factory RegisterState.empty(){
       isEmailValid: false,
       isPasswordValid: false
   }
}

to

abstract class RegisterState extends Equatable{
    RegisterState([List props = const []]):super(props);
}
class EmptyState extends RegisterState {
}

Because when i try Bloc-to-Bloc Communication  the first way of writing can't listen the RegisterState change  can you  show me  how to solve it tks！

**Comment by felangel** [comment]
Hi @Huai-Dc 👋 
Thanks for opening an issue!

Can you please provide the bloc to bloc communication code that isn’t working? Whether or not you extend Equatable should not have an impact on that.

Thanks!

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional info and I’m happy to continue the conversation 👍

**Comment by visual-velocity** [comment]
I'm also facing this issue
