### ISSUE TITLE
feat: Privacy manifest file for iOS is missing

### ISSUE THREAD

**Issue by oremlawi** [felangel/bloc#4140]
**Description**

Privacy manifest file for iOS is missing

**Desired Solution**

Kindly consider adding a privacy manifest to your library following the new apple policy by adding `PrivacyInfo.xcprivacy` file to your project.

**Additional Context**

For more information, please check [Apple's documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files).

**Comment by felangel** [comment]
Hi @oremlawi 👋

According to the docs:

> Apps and third-party SDKs — distributed as XCFrameworks, Swift packages, or Xcode projects — can contain a privacy manifest file, named PrivacyInfo.xcprivacy.

The bloc library is not distributed as an XCFramework, Swift package, or Xcode project therefore I don’t think a privacy manifest applies. Bloc is a collection of dart and flutter packages with no direct native dependencies.

Closing for now but if you feel I missed something feel free to leave a reply and I’m happy to continue the discussion 👍

**Comment by frederikstonge** [comment]
Just to rebound on this, hydrated_bloc uses hive, which uses apple apis. the maintainer of hive is not contributing to the project anymore. Maybe we should consider changing hive for another package, like objectbox : https://pub.dev/packages/objectbox

**Comment by felangel** [comment]
> Just to rebound on this, hydrated_bloc uses hive, which uses apple apis. the maintainer of hive is not contributing to the project anymore. Maybe we should consider changing hive for another package, like objectbox : https://pub.dev/packages/objectbox

Which apple APIs does hive use? Can you share a link?

**Comment by frederikstonge** [comment]
> > Just to rebound on this, hydrated_bloc uses hive, which uses apple apis. the maintainer of hive is not contributing to the project anymore. Maybe we should consider changing hive for another package, like objectbox : https://pub.dev/packages/objectbox
> 
> Which apple APIs does hive use? Can you share a link?

Nvm I thought hive was built on top of isar, which requires three apis.
