### ISSUE TITLE
Why user_repository is outside the lib folder in examples/flutter_login?

### ISSUE THREAD

**Issue by 2000calories** [felangel/bloc#417]
Just wonder why user_repository is outside the lib folder in examples/flutter_login.

**Comment by felangel** [comment]
Hi @2000calories 👋 
Thanks for opening an issue and great question!

The repository is outside the lib folder to demonstrate that the repository can be a separate package entirely (with no dependency on flutter) and can theoretically be reused across different applications. You can even create separate git repositories for each of your repositories or publish them in a private pub server if you'd like for further modularity/reuse.

Hope that helps! 👍
