### ISSUE TITLE
question: is this considered a anti pattern if a repository depends on another bloc. 

### ISSUE THREAD

**Issue by talpx0** [felangel/bloc#4173]
**Description**

```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<ThemeCubit>(create: (context) => ThemeCubit()),
        BlocProvider<WeatherProviderCubit>(create: (context) => WeatherProviderCubit()),
      ],
      child: BlocBuilder<WeatherProviderCubit, WeatherProviderState>(
        builder: (context, state) {
          return MultiRepositoryProvider(
            providers: [
              RepositoryProvider<WeatherRepository>(create: (context) => WeatherRepository(state.provider)),
            ],
            child: Container(
              child: Center(child: Text('Weather App')),
            ),
          );
        },
      ),
    );
  }
}
```
here  WeatherRepository  is depending on weather bloc , later another bloc gonna use  WeatherRepository ? is this considered as anit pattern or not ?

**Comment by felangel** [comment]
Hi @talpx0 👋 
Thanks for opening an issue!

While there are always exceptions, I generally would consider it an anti-pattern to have a repository depend on a bloc because repositories (as described in the [architecture docs](https://bloclibrary.dev/architecture)) are part of the domain layer whereas blocs are part of the application layer and the application layer should depend on the domain layer not the other way around.

<img width="700" alt="Screenshot 2024-05-22 at 10 24 05 PM" src="https://github.com/felangel/bloc/assets/8855632/0f36febe-b798-4ff4-be79-99cbb052bde0">

Hope that helps!

**Comment by talpx0** [comment]
> Hi @talpx0 👋 Thanks for opening an issue!
> 
> While there are always exceptions, I generally would consider it an anti-pattern to have a repository depend on a bloc because repositories (as described in the [architecture docs](https://bloclibrary.dev/architecture)) are part of the domain layer whereas blocs are part of the application layer and the application layer should depend on the domain layer not the other way around.
> 
> <img alt="Screenshot 2024-05-22 at 10 24 05 PM" width="700" src="https://private-user-images.githubusercontent.com/8855632/333022796-0f36febe-b798-4ff4-be79-99cbb052bde0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjY0NzQsIm5iZiI6MTcxNjQ2NjE3NCwicGF0aCI6Ii84ODU1NjMyLzMzMzAyMjc5Ni0wZjM2ZmViZS1iNzk4LTRmZjQtYmU3OS05OWNiYjA1MmJkZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjNUMTIwOTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQ4Yzg1MTc3MDAwMzliZGZkZTIzMmY4ZWU3ZjBlOWIzZDhkMDg1Y2ExOGU5Y2JmODk0ODQ4ZWQwMWY1MjZiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vPM1Qwc-h6ZsswEWghhaGnUqIRrofcbJkFaEQWjBRdI">
> Hope that helps!

Thanks for replying. I actually can't find a better way than this. Let's say you have three repositories, each with an enum relationship, but their underlying models are not the same. For example, AModel uses "Fahrenheit", BModel uses "Celsius", and CModel uses "Kelvin". I have to choose one of them based on the provider (as the user can switch the provider they want). No matter if I try to use listeners or repository injection, I can't avoid letting the state determine the repository. Furthermore, this wouldn't cause any performance issues or other problems, right?
