### ISSUE TITLE
feat: Translation of menu and prev, next, note title in the document

### ISSUE THREAD

**Issue by mbfakourii** [felangel/bloc#4180]
**Description**

The menu and prev, next and note title sections do not have the ability to translate
I suggest adding this option.

![Screenshot 2024-05-24 100121](https://github.com/felangel/bloc/assets/20955005/7624e7fb-e478-42bc-b4cc-2f98b9b267b4)

![image](https://github.com/felangel/bloc/assets/20955005/f39a8a5d-417f-44b4-974b-c6bbcad07acb)

**Comment by felangel** [comment]
Thanks! I'll take a closer look at configuring this in the next few days 👍

**Comment by felangel** [comment]
This is now supported and you can refer to https://github.com/felangel/bloc/commit/f2fa27ef0e46bed98e9ac0f1a8151cab48617a2c#diff-8093fd52e3174c122757b47959fa9539848a76a450f2366300bf421f31c7a09fR113 for an example 🎉
