### ISSUE TITLE
feat: can we rename copyWith to replaceWith

### ISSUE THREAD

**Issue by ysumiit005** [felangel/bloc#4192]
**Description**

Replace copyWith to replaceWith as it's more easy to understand while reading 

copyWith means like my data is copied and 2 instance of things exist 

While replaceWith means like my data is replaced with new data similar to setState. 
replaceWith is more clear

**Desired Solution**

rename copyWith to replaceWith

**Alternatives Considered**
setState or change notifier is more simple to understand each time I read it. but copyWith always tricks me and lot of developer 

Thanks 😊👍

**Comment by felangel** [comment]
Hi @ysumiit005 👋 
Thanks for opening an issue!

Bloc does not explicitly provide a `copyWith` API, this is just a convention used in the documentation and example. `copyWith` is used throughout the [Dart SDK](https://github.com/search?q=repo%3Adart-lang%2Fsdk%20copyWith&type=code)  as well as [Flutter](https://github.com/search?q=repo%3Aflutter%2Fflutter+copyWith&type=code) so I recommend sticking to the convention but bloc does not have an opinions about how you name your `copyWith` so you can use `replaceWith` in your own code if you prefer.

Hope that helps!
