### ISSUE TITLE
fix: BlocBuilder doesn't receive state when emitted from async loop

### ISSUE THREAD

**Issue by Seferi** [felangel/bloc#4197]
**Description**
Hi there, I'm facing this issue where the state (RefreshedContactCount) is emitted but for some reason not being received by the BlocBuilder. All the other states are received and updating the UI just fine but RefreshedContactCount. Here is the method in the cubit which emits the state: 
```

Future<void> refreshAllContacts() async {
    bool hasInternet = await InternetConnection().hasInternetAccess;
    if (!hasInternet) {
      emit(RefreshAllContactsFailure());
    } else {
      int refreshedContactsCount = 0;
      List<ProfileModel> contacts = getIt<UserCubit>().keyoxideUser.contacts;

      await Future.forEach(contacts, (contact) async {

        emit(RefreshingAllContacts());
        bool isContactRefreshed = await refreshContact(contact: contact, isRefreshingAllContacts: true);
        if (isContactRefreshed) {
          refreshedContactsCount++;

          emit(RefreshedContactCount(successfulRefreshCount: refreshedContactsCount));
        }
      });
      emit(RefreshAllContactsSuccess());
    }
  }
```

And this is the BlocBuilder which is suppose to receive the state:

```
BlocBuilder<ContactsCubit, ContactsState>(
  bloc: getIt<ContactsCubit>(),
  builder: (context, state) {
    if (state is RefreshingAllContacts) {

    }
    if (state is RefreshedContactCount) {
      refreshedContactCount = state.successfulRefreshCount;
    }
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20.0),
      child: Center(
        child: Container(
            width: double.infinity,
            height: 200,
            decoration: BoxDecoration(
                color: Theme.of(context).brightness == Brightness.dark
                    ? Colors.black.withOpacity(0.9)
                    : Colors.white.withOpacity(0.9),
                borderRadius: const BorderRadius.all(Radius.circular(20))),
            child: Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        const CircularProgressIndicator(),
                        const SizedBox(height: 10),
                        Text("contacts_refresh_all_count".localizeWithPlaceholders(
                              [refreshedContactCount.toString(), totalContactCount.toString()])!,
                          textAlign: TextAlign.center,
                        ),
                      ],
                    )
            )),
      ),
    );
  },
);
```

**Expected Behavior**
State gets received by the BlocBuilder or Consumer and updates the UI.

**Additional Context**
I have been using Bloc for years now and never faced this kind of issue, I'm guessing the loop might be causing the issue, causing some kind of race condition. I'd very much appreciate if someone could help or take a look. Thanks.

**Comment by FarisArmoush** [comment]
Where is the variable `refreshedContactCount` coming from?

**Comment by Seferi** [comment]
First method line 6, if isContactRefreshed true, it increases the refreshedContactCount and UI should update the text in the dialog like ' 1 of 5 contacts are refreshed' to show the progress.

**Comment by felangel** [comment]
Hi @Seferi 👋
Thanks for opening an issue!

Are you able to create a simple, minimal reproduction sample? It would be much easier to help if you could isolate the issue and provide a super simple, example with minimal dependencies, thanks!

**Comment by felangel** [comment]
Closing for now but if this is still an issue feel free to provide a minimal reproduction sample and I'm happy to take a closer look 👍
