### ISSUE TITLE
[Question] One BlocListener in nested page

### ISSUE THREAD

**Issue by tovidd** [felangel/bloc#4213]
Hi @felangel i want to ask a help, i have Product Screen that have a button to verify the availability of the product, after verified complete, the bloc listener helps redirect to Checkout Screen. Product Screen can be nested, so the BlocListener is also stacked. And the redirect function triggered multiple times according to the number of stacks. Did you have any idea how to trigger the function only once ? Thanks.

Notes:
- The BLoC provide in global scope (singleton)
- Product Screen can be nested

**Comment by felangel** [comment]
Hi @tovidd 👋 
It's hard to say without seeing some sample code (a minimal reproduction sample would be great). In general, if you can have multiple nested product screens, then I'd recommend not having a singleton bloc and instead having multiple nested bloc instances each scoped to their respective pages.

Closing for now but if that doesn't help please feel free to provide additional context as well as a minimal reproduction sample and I'm happy to take a closer look 👍
