### ISSUE TITLE
feat: Add `updateShouldNotify` or similar to set the equality behavior to emit states.

### ISSUE THREAD

**Issue by MiniSuperDev** [felangel/bloc#4227]
@felangel Hi, I want to be able to customize this behavior by adding a property to override like `updateShouldNotify` form riverpod.

For example riverpod use identical instead of equality behavior by default, but allow to change it.

Similar to #4136 but instead of adding force prop allow to override it.

This would not be a breaking change, and would give the user more control and the ability to choose what they prefer, as some consider that they can increase performance.

Thanks

If you plan to add it, it would be nice to maybe have a global setting for this.

https://riverpod.dev/docs/essentials/faq#why-does-riverpod-use-identical-instead-of--to-filter-updates-in-some-cases

> **Why does Riverpod use identical instead of == to filter updates in some cases?**
> Notifiers use identical instead of == to filter updates.
> 
> This is because it is quite common for Riverpod users to also use a code-generator such as Freezed/built_value for the sake of a copyWith implementation. Those packages override == to deeply compare objects. A deep object comparison is quite costly. "Business logic" models tend to have lots of properties. Worse, they also have collections such as lists, maps, and so on.
> 
> At the same time, when using complex "business" objects, most state = newState invocations always result in a notification (otherwise there is no point in calling the setter). Generally, the main case where we call state = newState when the current state and new states are equal is for primitive objects (ints, enums, strings, but not lists/classes/...). These objects are "canonicalized by default". If such objects are equal, they generally are also "identical".
> 
> Riverpod using identical to filter updates is therefore an attempt at having a good default for both worlds. For complex objects where we don't really care about filtering objects and where == may be expensive due to code-generators generating an == override by default, using identical provides an efficient way of notifying listeners. At the same time, for simple objects, identical does correctly filter redundant notifications.
> 
> Last but not least, you can change this behavior by overriding the method updateShouldNotify on Notifiers.

**Comment by felangel** [comment]
Hi @MiniSuperDev 👋 
Thanks for opening an issue!

I prefer not to add this capability for reasons described in https://github.com/felangel/bloc/issues/4136#issuecomment-2081169797. Closing this for now but feel free to comment if you disagree and I'm happy to continue the discussion 👍
