### ISSUE TITLE
fix: Url path

### ISSUE THREAD

**Issue by B1loliddin** [felangel/bloc#4228]
**Description**
You have forgotten to add "/" in url path.

**Steps To Reproduce**

1. Go to: bloc/examples/flutter_weather/packages/open_meteo_api/lib/src/open_meteo_api_client.dart
3. Scroll down to: 62 line
4. See error: 'v1/forecast' needs to be -> '/v1/forecast'

**Expected Behavior**
When I firstly saw the error, I thought that it will not request anything from anything because of the missing "/". 

**Screenshots**
<img width="516" alt="Screenshot 2024-08-14 at 18 38 19" src="https://github.com/user-attachments/assets/5b3e82e1-d86c-41b9-a3e9-4981d7328833">

**Additional Context**
That's all.

**Comment by chadtomkiss** [comment]
@B1loliddin The `Uri.https` function should prepend the `/` automatically if it's missing. Likewise if the `https://` protocol hasn't been set in `_baseUrlWeather`

See https://github.com/dart-lang/sdk/blob/3217fb1590e098a4a59059c82c914152f64a8593/tests/corelib/uri_http_test.dart#L60

Were you getting a specific error returned from the request?

**Comment by B1loliddin** [comment]
> @B1loliddin The `Uri.https` function should prepend the `/` automatically if it's missing. Likewise if the `https://` protocol is missing in `_baseUrlWeather`
> 
> See https://github.com/dart-lang/sdk/blob/3217fb1590e098a4a59059c82c914152f64a8593/tests/corelib/uri_http_test.dart#L60
> 
> Were you getting a specific error returned from the request?

Oh,Thank you.
I have just seen that the sign '/' was missing and thought that it should be fixed.
