### ISSUE TITLE
feat(hydrated_bloc): support wasm 

### ISSUE THREAD

**Issue by LukasMirbt** [felangel/bloc#4230]
**Description**

The default `HydratedStorage` currently does not support WebAssembly compilation.

Reproduction steps:

1. Create an empty Flutter application
2. Add `hydrated_bloc: ^9.1.5` to `pubspec.yaml`

3. Replace `main.dart` with:
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  HydratedBloc.storage = await HydratedStorage.build(
    storageDirectory: HydratedStorage.webStorageDirectory
  );
  runApp(App());
}
```

4. Run  `flutter run -d chrome --wasm --debug`

**Desired Solution**

Support WebAssembly compilation with the default `HydratedStorage`.

**Alternatives Considered**

- Using a custom `HydratedStorage`

**Additional Context**

Relevant GitHub conversation about wasm support in the Hive repo: https://github.com/isar/hive/pull/1291

**Comment by alexandrim0** [comment]
May be it is much easier to use `hive_ce` (drop in replacement which already supports wasm)?
But also it needs cut out using of `dart:io`.
I had an experiment and it works!

**Comment by alexandrim0** [comment]
@felangel would you move HydratedStorage class to new package to make this one independent of hive?

**Comment by felangel** [comment]
> @felangel would you move HydratedStorage class to new package to make this one independent of hive?

What would be the benefit of a separate package? You can already swap out the storage.

**Comment by alexandrim0** [comment]
File `hydrated_storage.dart` contains both classes `Storage` and `HydratedStorage`, so it imports `hive` and `dart:io`.
That is why it wont works in wasm runtime, as wrote topic starter.

**Comment by quoc-huynh-cosee** [comment]
@felangel One benefit would be that if people don't use `Hive` as `HydratedStorage`, the license won't be listed. Currently even if a user opts not to use `Hive`, the license is still displayed using [showLicensePage()](https://api.flutter.dev/flutter/material/showLicensePage.html).

**Comment by felangel** [comment]
We'd still need to ship a default `HydratedStorage` implementation if we decouple the package from hive. Are you all suggesting that we implement a custom key/value storage instead of using hive as the default?

**Comment by alexandrim0** [comment]
`hive_ce` could be as default storage to resolve this issue, except dependency on `dart:io`.
I can not see if it is simple for you to drop it or not.

But `hydrated_bloc` is a core package and should not dependent on any other specific packages, IMHO.
I still vote for separate packages for any specific storage.

Thank you!

**Comment by felangel** [comment]
Looks like the latest version of `hydrated_bloc` (on the master channel) supports wasm (using `package:hive_ce`).
This will likely ship in the next few weeks (wrapping up some changes for bloc v9.0.0 first).

Closing this for now but if you all have a chance please test using the version on `master` and let me know if you run into any issues, thanks! 🙏
