### ISSUE TITLE
BLoC builder with bloc argument is executed every navigate in or out screen

### ISSUE THREAD

**Issue by IqroNegoro** [felangel/bloc#4238]
**Description**
Hello, before that i new in flutter

so the issue is i have a bloc builder like this

```js
BlocBuilder<PostBloc, PostState>(
    bloc: PostBloc()..add(const PostEvent.loadPost()),
    builder: (context, state) {
         log(state.toString());
          return state.maybeWhen(
               postLoading: () => const PostSkeleton(),
               postError: (errors) => const Center(
                      child: Text("Post cannot be loaded"),
               ),
              postLoaded: (posts) => ListView.builder(
                            physics: const NeverScrollableScrollPhysics(),
                            shrinkWrap: true,
                            itemCount: posts.length,
                            itemBuilder: (context, index) =>
                                Post(post: posts[index])),
              orElse: () => const PostSkeleton(),
        );
    },
),
```
and a ElevatedButton that navigate using go_router
```js
ElevatedButton(
    onPressed: () => context.pushNamed("CreatePost"),
    style: ElevatedButton.styleFrom(
    backgroundColor: Colors.black12),
    child: Text("Write your thinking now", style: const TextStyle(color: Colors.black54),
    ),
),
```

every time i navigate to route CreatePost (screen 2), bloc at BlocBuilder main page (screen 1) is executed every go in screen 1 (when user open app), or when i navigate from create post (screen 2) to main page (screen 1)

**Steps To Reproduce**

1. User open app
2. Check authenticating, if have credentials, then go on
3. User go to main page (screen 1), and load post
4. User navigating to screen 2 (create post)
5. Back to screen 1

**Expected Behavior**
what i expected is
bloc just executed once when user go in screen 1, and when navigate to screen 2, the bloc not executed (or idk if bloc is used by that way), and not executed when back from screen 2, just once at go in screen 1

**Screenshots**

![image](https://github.com/user-attachments/assets/7f4dea28-0033-4cbf-9c43-810656fbe1b4)
when click the button, they navigate push to CreatePost page (screen 2), but when you see the log down after navigating, the state get changed to initial, try make a request so emit loading, and therefore requested to endpoint, and response, anyway i used dio as requester and freezed as code-generator

**Additional Context**
this is the github : [github](https://github.com/IqroNegoro/swappes-mobile) 
### sry the api is in local so this is just for more code to see, just focus in lib/main/views/main.dart and create_post.dart in CUBIT BRANCH
i have tried [this](https://github.com/felangel/bloc/issues/356#issuecomment-503405474) but it seems not resolving my issues

this is my event bloc
```js
on<_LoadPost>((event, emit) async {
      log(state.toString());
      emit(const PostState.postLoading());
      try {
        List<PostModel> lists = [];
        var posts = await Api.dio.get("posts");

        for (var x in posts.data['data']) {
          lists.add(PostModel.fromJson(x));
        }

        emit(PostState.postLoaded(lists));
      } on DioException catch (e) {
        log(e.toString());
        emit(PostState.postError(e.error));
      }
    });
```

my state 
```js
@freezed
class PostState with _$PostState {
  const factory PostState.initial() = _Initial;
  const factory PostState.postLoading() = _PostLoading;
  const factory PostState.postLoaded(final List<PostModel> posts) = _PostLoaded;
  const factory PostState.postError(final dynamic errors) = _PostError;
  const factory PostState.postLiking(final String? id) = _PostLiking;
  const factory PostState.postLiked(final String? id) = _PostLiked;
  const factory PostState.postComments(final String id) = _PostComments;
  const factory PostState.creatingPost() = _CreatingPost;
  const factory PostState.postCreated() = _PostCreated;
  const factory PostState.createPostError(final dynamic errors) = _CreatePostError;
}
```

my event
```js
@freezed
class PostEvent with _$PostEvent {
  const factory PostEvent.loadPost() = _LoadPost;
  const factory PostEvent.likePost(String id) = _LikePost;
  const factory PostEvent.createPost({String? description, List<File>? images}) = _CreatePost;
  const factory PostEvent.showComments(String id) = _ShowComments;
}
```

**Comment by felangel** [comment]
Hi @IqroNegoro 👋 
Thanks for opening an issue!

This is working as expected, `BlocBuilder` is just like any other widget, if the parent rebuilds, the `BlocBuilder` itself is rebuilt and since you're always adding events to the bloc those will happen on each rebuild. This is equivalent to writing the `add` directly in your `build` method:

```dart
BlocBuilder<PostBloc, PostState>(
    bloc: PostBloc()..add(const PostEvent.loadPost()),
    builder: (context, state) {...},
);
```

Is the same as:

```dart
final bloc = PostBloc();
bloc.add(const PostEvent.loadPost());

return BlocBuilder(
  bloc: bloc,
  builder: (context, state) {...},
);
```

Instead of having side-effects in your `build` method you should either use `BlocProvider` to create the bloc and add the event:

```dart
BlocProvider<PostBloc, PostState>(
  create: (context) => PostBloc()..add(const PostEvent.loadPost()),
  child: MyChild(),
);
```

Or you should refactor your widget to be a `StatefulWidget` and only create and add the event on `initState`:

```dart
final bloc = PostBloc();

@override
void initState() {
  super.initState();
  bloc.add(const PostEvent.loadPost());
}

@override
void dispose() {
  bloc.close();
  super.dispose();
}

@override
Widget build(BuildContext context) {
  return BlocBuilder(
    bloc: bloc,
    builder: (context, state) {...},
  );
}
```

Hope that helps!

**Comment by IqroNegoro** [comment]
> Hi @IqroNegoro 👋 Thanks for opening an issue!
> 
> This is working as expected, `BlocBuilder` is just like any other widget, if the parent rebuilds, the `BlocBuilder` itself is rebuilt and since you're always adding events to the bloc those will happen on each rebuild. This is equivalent to writing the `add` directly in your `build` method:
> 
> ```dart
> BlocBuilder<PostBloc, PostState>(
>     bloc: PostBloc()..add(const PostEvent.loadPost()),
>     builder: (context, state) {...},
> );
> ```
> 
> Is the same as:
> 
> ```dart
> final bloc = PostBloc();
> bloc.add(const PostEvent.loadPost());
> 
> return BlocBuilder(
>   bloc: bloc,
>   builder: (context, state) {...},
> );
> ```
> 
> Instead of having side-effects in your `build` method you should either use `BlocProvider` to create the bloc and add the event:
> 
> ```dart
> BlocProvider<PostBloc, PostState>(
>   create: (context) => PostBloc()..add(const PostEvent.loadPost()),
>   child: MyChild(),
> );
> ```
> 
> Or you should refactor your widget to be a `StatefulWidget` and only create and add the event on `initState`:
> 
> ```dart
> final bloc = PostBloc();
> 
> @override
> void initState() {
>   super.initState();
>   bloc.add(const PostEvent.loadPost());
> }
> 
> @override
> void dispose() {
>   bloc.close();
>   super.dispose();
> }
> 
> @override
> Widget build(BuildContext context) {
>   return BlocBuilder(
>     bloc: bloc,
>     builder: (context, state) {...},
>   );
> }
> ```
> 
> Hope that helps!

Hi,
Thank you for the reply!, if bloc is used that way, I'll learn it more and find workaround for this, again, thank you!
