### ISSUE TITLE
feat: Add a builder parameter on BlocProvider.

### ISSUE THREAD

**Issue by lsaudon** [felangel/bloc#4245]
**Description**

Add a builder parameter on BlocProvider.

**Desired Solution**

```dart
BlocProvider<CounterBloc>(
  create: (context) => CounterBloc(),
  builder: (context, child) {
    final state = context.watch<CounterBloc>();
    return Text('$state');
  }
)
```

**Additional Context**

Equivalent of https://github.com/rrousselGit/provider/blob/64745784fcef9e3ebc6e6dea0d5f82d1ac20c797/packages/provider/lib/src/inherited_provider.dart#L111

**Comment by felangel** [comment]
Hi @lsaudon 👋 
That’s undesired because it makes it impossible to unit test the widget since you’re providing and consuming the bloc in the same component. Let me know what you think? Thanks!

**Comment by lsaudon** [comment]
Hi @felangel,
When I run tests, I mock the repository rather than the bloc.
I don't want any dependency on the bloc in my tests.
The repository was placed in the provider when the application was launched, so I can easily mock it.

```dart
class MyApp extends StatelessWidget {
  const MyApp({super.key, this.myRepository});

  final MyRepository myRepository;

  @override
  Widget build(BuildContext context) {
    return RepositoryProvider.value(
      value: myRepository,
      child: const MyPage(),
    );
  }
}

class MyPage extends StatelessWidget {
  const MyPage({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => MyBloc(context.read()),
      builder: (context, child) => const EditTodoPage(),
    );
  }
}
```

**Comment by felangel** [comment]
> Hi @felangel, When I run tests, I mock the repository rather than the bloc. I don't want any dependency on the bloc in my tests. The repository was placed in the provider when the application was launched, so I can easily mock it.
> 
> ```dart
> class MyApp extends StatelessWidget {
>   const MyApp({super.key, this.myRepository});
> 
>   final MyRepository myRepository;
> 
>   @override
>   Widget build(BuildContext context) {
>     return RepositoryProvider.value(
>       value: myRepository,
>       child: const MyPage(),
>     );
>   }
> }
> 
> class MyPage extends StatelessWidget {
>   const MyPage({super.key});
> 
>   @override
>   Widget build(BuildContext context) {
>     return BlocProvider(
>       create: (context) => MyBloc(context.read()),
>       builder: (context, child) => const EditTodoPage(),
>     );
>   }
> }
> ```

In that case your widget test is both testing your bloc's logic and your presentation logic (in the widget). Since it's already possible to write your own generic version of this widget, I'd prefer not to add something like this to the library since it encourages tightly coupling the widget to the bloc.

```dart
import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class NewBlocProvider<T extends StateStreamableSource<Object?>>
    extends StatelessWidget {
  const NewBlocProvider({
    required this.create,
    required this.builder,
    super.key,
  });

  final T Function(BuildContext context) create;
  final Widget Function(BuildContext context) builder;

  @override
  Widget build(BuildContext context) {
    return BlocProvider<T>(
      create: create,
      child: Builder(
        builder: (context) => builder(context),
      ),
    );
  }
}
```

Hope that helps! 👍
