### ISSUE TITLE
Future of the package? (Migration of Getx)

### ISSUE THREAD

**Issue by ruanmax** [felangel/bloc#4252]
I'm exited of package Getx and wanting migrate to the flutter_bloc and bloc. But I have some questions:

This package is development by one or various people?

Have updates and good support? 

Congrulations by work, I learned the concept bloc by cause of the package.

**Comment by felangel** [comment]
Hey 👋 

I’m the main maintainer but the library receives updates from hundreds of contributors all over the world.

If you have any questions or would like to join the community you can hop onto the [Discord server](https://discord.gg/bloc).

If something isn’t working please file an issue and we’re all happy to help!

Cheers! 💙
