### ISSUE TITLE
How to update an item in List but not rebuild all items

### ISSUE THREAD

**Issue by Trung15010802** [felangel/bloc#4255]
I wanna do like this video but I don't know how can i achieve this with flutter_bloc. 
Hope someone help me. 

**Problem**
https://www.youtube.com/watch?v=mCR53N83ySM&embeds_referring_euri=https%3A%2F%2Fwww.dbestech.com%2F&source_ve_path=Mjg2NjY

**Expected**
https://www.youtube.com/watch?v=vnh7rMg8hqU

**Comment by felangel** [comment]
Hi @Trung15010802 👋 
Can you please share a link to a minimal reproduction sample and I'm happy to take a closer look, thanks!

**Comment by Trung15010802** [comment]
> Hi @Trung15010802 👋 Can you please share a link to a minimal reproduction sample and I'm happy to take a closer look, thanks!

Hi @felangel , here it is
https://github.com/rei-codes/advanced_list_riverpod

**Comment by felangel** [comment]
@Trung15010802 I finally had some time and put together an example https://gist.github.com/felangel/aa9b0ee2d5306a35b14643565d1bcccc.

Hope that helps! Closing for now but if you still have questions I'm happy to continue the conversation either here or on [Discord](https://discord.gg/bloc).

**Comment by felangel** [comment]
I also created a simpler example that can be run directly in DartPad [here](https://dartpad.dev/?id=7d6031caef1aab30e6826e82ca11d756) in case it's useful for anyone else.
