### ISSUE TITLE
feat: State persistence for the widgets that are frequently in use.

### ISSUE THREAD

**Issue by sidharth-epi** [felangel/bloc#4256]
**Description**

Like in a bottom navigation tabs, widgets that hold data once they have state, should persist no matter how many times i navigation through. So we need to keep their bloc in main file. So when we logout session and log-in to another account, what is the best way to make sure that all bloc instance are with initial state .

**Desired Solution**

When user is in Session and navigation through bottom navigation options the data state fetched should persist but when session is logged off, all the bloc kept in main should be disposed off or set to initial state.

**Alternatives Considered**

**Additional Context**

Add any other context or screenshots about the feature request go here.

**Comment by felangel** [comment]
Hi @sidharth-epi 👋 
Thanks for opening an issue!

I highly recommend taking a look at the [firebase_login](https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login) example and you can check out the corresponding [tutorial](https://bloclibrary.dev/tutorials/flutter-firebase-login/).

Hope that helps and if you still have questions I recommend joining the community on [Discord](https://discord.gg/bloc), thanks!
