### ISSUE TITLE
chore: support Intellij 2024.2.*

### ISSUE THREAD

**Issue by podcharles** [felangel/bloc#4257]
**Description**

I'm running IntelliJ Ultimate 2024.2.3 and notice I can only download v3.4.0 of the IntelliJ plugin as that is the most recent version with an open ended `until-build` value. The current latest version of the plugin (v4.0.1) only supports up to IntelliJ 2024.1.*.

Would be great if that could be updated. Happy to submit a pull request if that helps based on #4168 but I'm not setup to test plugins so would be speculative.

**Comment by felangel** [comment]
This should be addressed in [v4.0.2](https://github.com/felangel/bloc/releases/tag/intellij_bloc-v4.0.2) (pending review)

**Comment by podcharles** [comment]
Great, thanks very much! ❤️
