### ISSUE TITLE
question: Inquiry regarding removeListener in PostsList disposal process

### ISSUE THREAD

**Issue by sports7744** [felangel/bloc#4260]
Hi @felangel!

While working on a component inspired by the `PostsList` class from the **Infinite list project**, I noticed something that prompted a question. In the [`dispose`](https://github.com/felangel/bloc/blob/d1abf0f277d525a3da62d7cf953d032596429a00/examples/flutter_infinite_list/lib/posts/view/posts_list.dart#L51) method, there's an explicit call to `removeListener` for the `_scrollController`:

```dart
@override
void dispose() {
  _scrollController
    ..removeListener(_onScroll)
    ..dispose();
  super.dispose();
}
```

Could you provide some insight into why `removeListener` is used explicitly here? My understanding is that calling `dispose()` should typically take care of cleaning up listeners. I want to ensure that I'm following best practices, so any guidance on this decision would be greatly appreciated.

Thanks!

**Comment by felangel** [comment]
Hi @sports7744 👋 
Thanks for opening an issue and good catch -- the call to `removeListener` is not necessary since the `dispose` call will remove the listeners. I fixed this in https://github.com/felangel/bloc/commit/41d232b0c5ed96050ed9fd2490c5a713b9a688a0, thanks again!
