### ISSUE TITLE
feat: `saveWhen` in `HydratedBloc`.

### ISSUE THREAD

**Issue by xuxiaocheng0201** [felangel/bloc#4283]
**Description**

Currently, whenever the state changes, `stoarge.write` is called. [code](https://github.com/felangel/bloc/blob/841651f6901d3f7817ac8a47d4a2162606dd794c/packages/hydrated_bloc/lib/src/hydrated_bloc.dart#L151-L154)
(Although it doesn't write when `toJson` returns null, I actually don't know when to return null.)
But sometimes, certain fields in the state are not stored and these fields change very frequently, such as loading progress. In this case, saving every state change would result in a significant amount of unnecessary duplicate writes.

**Desired Solution**

A `saveWhen` method should be provided. Such as `buildWhen` in `BlocBuilder`.

**Alternatives Considered**

Or provide both `currentState` and `nextState` parameters in `toJson` method.

**Comment by ElsayedDev** [comment]
are you tried to return the old state instead?

**Comment by felangel** [comment]
Hi @xuxiaocheng0201 👋 
Thanks for opening an issue!

What are you trying to achieve? Are you encountering performance issues? Are you trying to avoid caching intermediate states? If it's the latter you can always either return `null` and nothing will be written to storage.

You can also write your own storage class by implementing the `Storage` interface.

Closing for now but if this is still an issue please feel free to provide additional context and I'm happy to continue the conversation 👍

**Comment by xuxiaocheng0201** [comment]
In my previous code, progress was a state in HydratedBloc that changed almost every frame. There frequent calls to `toJson` can result in less smooth changes to the view.
But now I have created a separate Bloc for the progress section. This issue has been resolved.

**Comment by xuxiaocheng0201** [comment]
But I still hope to add this method, because sometimes not all states need to be saved. A `saveWhen` method can accurately save changes when the state that need to be saved changed.
