### ISSUE TITLE
feat: hydrated_bloc migrations

### ISSUE THREAD

**Issue by codakkk** [felangel/bloc#4292]
**Description**

Sometimes, the data model of a Bloc/Cubit changes, which can lead to issues with Hydrated Bloc: data might be lost, or worse, the app could crash if not handled properly.

**Desired Solution**

One potential solution is to allow developers to migrate their data using a procedure similar to [Redux's migrations](https://github.com/rt2zz/redux-persist/blob/master/docs/migrations.md).

Given that Dart is a strongly typed language, implementing Redux-like migrations can be challenging, but we might still find a good solution. My initial idea was to use "versioned" classes, such as:

```dart
class MyDataV1 {}
class MyDataV2 {}
```
Each class would represent a version of the data model, based on the previous version. However, the challenge arises from how a Cubit/Bloc class is written:

```dart
class MyCubit extends HydratedCubit<MyDataV1> { ... }
```

Another approach could involve extending from a BaseClass and type-checking between the old and new data types. However, this introduces other issues.

A different idea is to treat models as dynamic during the migration process, similar to Redux:

```dart
dynamic migration(dynamic currentData) {
  if (currentData is MyDataV1) {
    // Migrate to v2
  } else if (currentData is MyDataV2) {
    // Migrate to v3
  }
  // And so on
}
```
Alternatively, we could explore using code generation, though I haven’t fully developed this idea yet.

**Alternatives Considered**

Another option is to handle this manually, such as using try-catch during JSON parsing and recursively attempting to parse the data.

I’d like to contribute by potentially creating a pull request, but I don’t have a clear solution yet. Let’s discuss and brainstorm ideas!

**Comment by felangel** [comment]
You should already be able to handle migrations by comparing the current state scheme to the stored state scheme (in `fromJson`). Can you provide a bit more context regarding your specific use-case?

**Comment by codakkk** [comment]
> You should already be able to handle migrations by comparing the current state scheme to the stored state scheme (in `fromJson`). Can you provide a bit more context regarding your specific use-case?

Do you mean by checking the differences between the json representations?
