### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by kieth1205** [felangel/bloc#431]
this repo use firebase but U cann't see firebase in your repo. So I cann't run this app

**Comment by felangel** [comment]
Hi @kieth1205 👋 
Thanks for opening an issue!

Can you please be more specific about what isn’t working? It would be great if you can provide detailed steps to reproduce the problem you’re having.

Thanks!

**Comment by kieth1205** [comment]
ERROR: [TAG] Failed to resolve variable '${animal.sniffer.version}'
D8: Cannot fit requested classes in a single dex file (# methods: 79809 > 65536)

**Comment by kieth1205** [comment]
and "Gradle task assembleDebug failed with exit code 1"

**Comment by felangel** [comment]
What project is this in? I don't believe the error has anything to do with the bloc library.

**Comment by kieth1205** [comment]
I just run firebase login with all code on that

**Comment by felangel** [comment]
@kieth1205 thanks for reporting this! I was able to reproduce the issue and fixed it on master. All you should need to do is use latest master and copy the contents of your own `google-services.json` [here](https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/android/app/google-services.json).

Closing now but feel free to comment if you have additional issues 👍

**Comment by kieth1205** [comment]
thank you
