### ISSUE TITLE
VSCode refactor menu

### ISSUE THREAD

**Issue by amreniouinnovent** [felangel/bloc#433]
I just wonder if VSCode refactors menu is flutter default items only or we could modify it for adding wrap with a new BlocBuilder?
Or we should ask in flutter repo itself?

![image](https://user-images.githubusercontent.com/52191652/61766416-d2fc8980-adf1-11e9-8da3-341e93120fe0.png)

**Comment by amreniouinnovent** [comment]
I open an issue on flutter repo
https://github.com/flutter/flutter/issues/36803

**Comment by felangel** [comment]
Hey @amreniouinnovent 👋 
Thanks for opening an issue!

I've been thinking about adding this for a while but I believe the right place to add this would be in the [dart vscode extension](https://github.com/Dart-Code/Dart-Code). Might be a good idea to open an issue there for starters.

**Comment by amreniouinnovent** [comment]
@felangel I didn't know about that repo 
I opened an issue there
https://github.com/Dart-Code/Dart-Code/issues/1890

**Comment by felangel** [comment]
@amreniouinnovent thanks! It's likely the maintainers will say that the functionality doesn't belong there because it isn't part of core Dart/Flutter so if that's the case, I'll add it to the bloc vscode extension 👍

**Comment by DanTup** [comment]
> It's likely the maintainers will say the functionality doesn't belong there because it isn't part of core Dart/Flutter so if that's the case, I'll add it to the bloc VSCode extension 👍

It's kinda tricky.. I like the idea, but it does feel a bit specific (even in a generic JSON form). However I'm not sure other extensions have a great way to know when it's the correct place to show the item in the menu (or fetch the edits) without making assumptions about how the Dart extension works.

I added a question at https://github.com/Dart-Code/Dart-Code/issues/1890#issuecomment-514512417 asking for a little more clarification on how this works (I'm not very familiar with what the code you want to insert looks like).

**Comment by amreniouinnovent** [comment]
I will close this issue as it is now opened in  https://github.com/Dart-Code/Dart-Code/issues/1890

**Comment by felangel** [comment]
This is now supported in v5.1.0 of the bloc extension 🎉
