### ISSUE TITLE
in app bugs

### ISSUE THREAD

**Issue by kieth1205** [felangel/bloc#435]
**Describe the bug**
I think sign in with google in firebase_login example has issue. Bloc state return false inspite of real google account.

**To Reproduce**
1. Run app
2. Click on 'sign in with google'
3. State "isSuccess" always give false back.

**Expected behavior**

**Screenshots**

**Logs **
I/flutter (12949): LoginWithGooglePressed
I/zygote64(12949): Do full code cache collection, code=124KB, data=82KB
I/zygote64(12949): After code cache collection, code=106KB, data=61KB
I/flutter (12949): PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
I/flutter (12949): Transition { currentState: LoginState {
I/flutter (12949):       isEmailValid: true,
I/flutter (12949):       isPasswordValid: true,
I/flutter (12949):       isSubmitting: false,
I/flutter (12949):       isSuccess: false,
I/flutter (12949):       isFailure: true,
I/flutter (12949):     }, event: LoginWithGooglePressed, nextState: LoginState {
I/flutter (12949):       isEmailValid: true,
I/flutter (12949):       isPasswordValid: true,
I/flutter (12949):       isSubmitting: false,
I/flutter (12949):       isSuccess: false,
I/flutter (12949):       isFailure: true,
I/flutter (12949):     } }

and here is my output when run 'flutter doctor -v'. I use VSCode to run my code.

• Flutter version 1.7.8+hotfix.3 at C:\flutter
    • Framework revision b712a172f9 (2 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\thang\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\thang\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • SO 04H • CB512AVGJ3 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

**Comment by amreniouinnovent** [comment]
@kieth1205 did you add the google API keys?

**Comment by felangel** [comment]
Hi @kieth1205 👋 
Thanks for opening an issue!

I'm guessing you didn't include your own `google-services.json`.  You can follow the directions [here](https://firebase.google.com/docs/flutter/setup#create_firebase_project).

Closing for now but feel free to comment with any additional information/questions 👍
