### ISSUE TITLE
Is it possible to make devtools like redux with this library?

### ISSUE THREAD

**Issue by Feelthewind** [felangel/bloc#440]
I know that with logging i can check the state of a bloc, but i think it would be much better if there's a devtools like redux. I wonder if it's possible. Thanks!

**Comment by felangel** [comment]
Hey @Feelthewind 👋 
Thanks for opening an issue!

It is possible and I was working on it a while ago on the [bloc-dev-tools](https://github.com/felangel/bloc/tree/bloc-dev-tools) branch. I'm planning to pick it back up as soon as I wrap up a couple of minor updates. 👍

**Comment by Feelthewind** [comment]
wow awesoe! looking forward to the devtool!

**Comment by timrijckaert** [comment]
Currently we do this ourselves like said with the help of a `BlocDelegate` we wire it to our logger which writes all `BlocState`s to a log file during production. In debug we just log it to the console.
