### ISSUE TITLE
wrapping dispatch in a function

### ISSUE THREAD

**Issue by amreniouinnovent** [felangel/bloc#441]
I just wonder if wrapping dispatch and events in a function inside the bloc is it **a good practice or not?**

So instead of using `bloc.distpatch(LoginEvent())` I could just use `bloc.login()`

![image](https://user-images.githubusercontent.com/52191652/62003181-2e958280-b124-11e9-9441-965f41334f7a.png)

**Comment by MichelMelhem** [comment]
I will be interresed to know if it a good practice beacause i do that too.

**Comment by amreniouinnovent** [comment]
@MichelMelhem I saw it in Reso Coder channel on youtube

**Comment by felangel** [comment]
Hey @amreniouinnovent 👋 
Thanks for opening an issue!

Regarding your question, it comes down to personal preference. If you like to have helper functions that wrap dispatch that’s totally fine 😄
