### ISSUE TITLE
form validation from server

### ISSUE THREAD

**Issue by rizalashidiq97** [felangel/bloc#443]
Please , can you provide an example when I want to validate email form if the regex is true . And after that I want to check the email if it's exist in my server. (Add the debounce transform after the email is valid)

Thank you

**Comment by amreniouinnovent** [comment]
@rizalashidiq97 check this maybe could help https://github.com/felangel/bloc/issues/382

**Comment by felangel** [comment]
Hi @rizalashidiq97 👋 
Thanks for opening an issue!

Have you checked out the [form validation example](https://github.com/felangel/bloc/tree/master/examples/flutter_form_validation)? Regarding the debounce are you trying to debounce the states (as @amreniouinnovent mentioned) or are you trying to debounce the events?

Thanks!

**Comment by rizalashidiq97** [comment]
I've checked out your example but I want to add a feature where I want to check the email form to server if it's still exist .

**Scenario is :** 

1. Validate the email form (with Regex)
2. After validation return true , Check the email if it's exist the server (when the user typed a valid email ,the textchanged event wait milliseconds to prevent calling api many times)

thanks

**Comment by felangel** [comment]
Hi @rizalashidiq97 thanks for providing the additional details. I would highly recommend taking a look at the forms in the [firebase login](https://felangel.github.io/bloc/#/flutterfirebaselogintutorial) example app. They are validating the input locally, debouncing, as well as hitting the firebase api.

Hope that helps!

**Comment by cuongloveit** [comment]
Hi @felangel , I'm very like RxDart, can you show me the approach to use RxDart for form validation.

**Comment by felangel** [comment]
Hi @cuongloveit 👋 
I don't think this is the right place for that. You might want to open an issue on [rxdart](https://github.com/ReactiveX/rxdart) to add an example but you can take a look at the [form validation](https://github.com/felangel/bloc/tree/master/examples/flutter_form_validation) example for how to use the bloc library to handle form validation 👍
