### ISSUE TITLE
bug in example of infinite_list 

### ISSUE THREAD

**Issue by sephrouse** [felangel/bloc#444]
**Describe the bug**
https://github.com/felangel/bloc/blob/master/examples/flutter_infinite_list/lib/main.dart

Line 52:

`return BlocBuilder<PostBloc, PostState>(`

The <PostBloc, PostState> should be <PostEvent, PostState>, and add bloc parameter in the BlocBuilder.

**To Reproduce**
1. download the example of infinite_list.
2. flutter run

**Expected behavior**
app should be run normally.

**Screenshots**
none

**Logs **
none

**Additional context**
none

**Comment by mancem72** [comment]
Update your flutter bloc to 0.20.0 version

**Comment by sephrouse** [comment]
ok. thanks.
