### ISSUE TITLE
Add projection function to BlocBuilder

### ISSUE THREAD

**Issue by leoneparise** [felangel/bloc#445]
**Is your feature request related to a problem? Please describe.**
One reason to use bloc it to improve the app performance and not update the whole widget screen when a state changes. We should have `BlocBuilders` that reacts to each part of the screen when the state changes. But most of the time it should update only when part of the data is changed.

**Describe the solution you'd like**
[flutter_bloc_extensions](https://pub.dev/packages/flutter_bloc_extensions#blocProjectionBuilder) has a widget called `BlocProjectionBuilder` when you can define a projection function that project the state data and react only to changes in that specific data. This feature is really useful when you implement the bloc patter with `built_value`.

I propose to add a constructor parameter called `projection`, which is a function that accept a state `S` and transform to a data `T` to the `BlocBuilder` widget and call the `build` function only when `T` changes. If `projection` function is `null`, then is should behave as it is today.

**Comment by felangel** [comment]
Hi @leoneparise 👋 
Thanks for opening an issue!

Regarding your question, `BlocBuilder` (and `BlocListener`) currently support implementing an optional condition function which determines whether or not the builder/listener functions should be triggered.

You can check out the [flutter timer tutorial](https://felangel.github.io/bloc/#/fluttertimertutorial) for an example.

Please let me know if that helps 👍

**Comment by leoneparise** [comment]
That could work. But I believe that having a component to make a projection of the state is really useful. The extension stores the current projection value and updates the component only when that value changes. It's different than having a condition function that get's only the current and past states to make that decision.

I think I'll stick with bloc_extensions for now.

Thank you for your answer.

**Comment by felangel** [comment]
@leoneparise can you please provide some more details around your use-case and why you'd prefer the projection over the condition? It would be really helpful to get more context. Thanks!
