### ISSUE TITLE
How to stop Bloc computation in between?

### ISSUE THREAD

**Issue by RaviKavaiya** [felangel/bloc#446]
Hello, I just started using this package and I have some confusion. Imaging below bloc file:

```dart
  Stream<BlocState> mapEventToState(BlocEvent event) async* {
    if (event is Event1) {
      yield* _func1();
    } else if (event is Event2) {
      yield* _func2();
    }
  }

  Stream<BlocState> _func1() async* {
    yield BlocStateLoading();

    // Some long computation
    // Maybe a network call
    String result = 'something';

    yield BlocStateLoaded(param:result);
  }

  Stream<BlocState> _func2() async* {
    yield AnotherState();
  }
```

Now, everything works fine. But imagine that 'Event2' is used to STOP this computation (done by 'Event1' in '_func1()'.)

**What I mean:** Suppose, 'Event1' is dispatched, it is in between 'BlocStateLoading' and 'BlocStateLoaded', now I want to stop this process in between by dispatching 'Event2'.

**What happens:** After dispatching 'Event2', the Bloc STILL waits for the previous process to complete, then it yields 'BlocStateComplete' and then 'AnotherState'.
But, I want 'AnotherState' to be yielded instantly and STOP 'BlocStateLoaded' to be yielded.

**NOTE:** I use this thing as like this, because 'Event2' is dispatched sometimes only, in order to stop above process.

Sorry, if I made a misuse of this Bloc pattern and any suggestion would be helpful.
Thanks.

**Comment by felangel** [comment]
Hi @RaviKavaiya 👋 
Thanks for opening an issue!

You should be able to override `transform` in your bloc and use `switchMap` to achieve the functionality you're asking for.

```dart
@override
Stream<int> transform(events, next) {
  return (events as Observable<Event>).switchMap(next);
}
```
https://github.com/felangel/bloc/issues/2232

Hope that helps! 👍
