### ISSUE TITLE
Casting error on LoginEvent

### ISSUE THREAD

**Issue by zmabies** [felangel/bloc#449]
Hello, 

...BlocBuilder<**LoginEvent**, LoginState>(
        **bloc: _loginBloc**,
        builder: (
            BuildContext context,
            LoginState state,
            )...

The error given is as follows:
LoginEvent does not extend Bloc<dynamic, LoginState>
The argument type LoginBloc cannot be assigned to the parameter type LoginEvent

I've checked everything and I'm really stumped as to why I'm getting this error.

**Comment by amreniouinnovent** [comment]
@zmabies your syntax is not very correct
You should use
```
BlocBuilder<LoginBloc, LoginState>(
            builder: (BuildContext context, LoginState loginState) {
```

**Comment by zmabies** [comment]
@amreniouinnovent thanks!

**Comment by Kurtoid** [comment]
Can you update https://gist.github.com/felangel/b55d31066ad85195b1205f6b90ec605e#file-login_form-dart-L30 so the change is reflected in https://medium.com/flutter-community/flutter-login-tutorial-with-flutter-bloc-ea606ef701ad ?
