### ISSUE TITLE
I have a question about this plugin

### ISSUE THREAD

**Issue by WillianNightray** [felangel/bloc#451]
Hi, 
I would like to know if there is a difference between the Bloc(felangel) and Bloc_pattern(jacobaraujo) plugins?
Or do the two work the same way?
And what would be the best decision to implement in a large scale project.?

Thanks.

ps: Sorry for my English.

**Comment by felangel** [comment]
Hi @WillianNightray 👋 
Thanks for opening an issue!

I cannot speak on behalf of the bloc_pattern package but this package is an interpretation of the BLoC pattern which abstracts the reactive components (RxDart) in an attempt to be a simple, scalable, and powerful state management library.

You can check out the [docs](https://felangel.github.io/bloc/#/whybloc) for more information. My team and I use this library every day at BMW so it should work well in a large scale project 👍 

Hope that helps.
