### ISSUE TITLE
Dispose is not working

### ISSUE THREAD

**Issue by bharatsood10** [felangel/bloc#454]
**Dispose is not closing events**
i called a dispose method in stateful widget. I'm getting print statement in Debug Console(That dispose is called). So when i click again to open that state it opens last event **Response**. but it needs repeat from 1st event.. have a look to code

**Code**
`final attendanceBloc = AttendanceBloc();`
`BlocListener<AttendanceBloc, AttendanceState>(`
            `listener: (context, state) {`
              `if (state is ClassLoaded) {`
                `print("Loaded: ${state.attendance.classes[1].class_name}");`
              `}`
           ` },`
            `child: BlocBuilder<AttendanceBloc, AttendanceState>(`
              `builder: (context, state) {`
                `if (state is InitialAttendanceState) {`
                  `Future.delayed(Duration(milliseconds: 1000), () {`
                    `attendanceBloc.dispatch(GetClass({"teacher_id": "1"}));`
                    `print("Call to network after 1 seconds");`
                  `});`
                  `return loadingScreen();`
                `} else if (state is ClassLoaded) {`
                 ` if (state.attendance != null) {`
                   ` return ClassList(`
                     ` items: state.attendance,`
                   ` );`
                  `} else {`
                    `return failedToLoadUI();`
                 ` }`
                `}`
               ` return null;`
              `},`

**dispose Method**
  ` @override `
  ` void dispose() { `
     `super.dispose(); `
     `attendanceBloc.dispose(); `
     `print("Disposed"); `
  `}`
`}`

**Comment by felangel** [comment]
Hi @bharatsood10 👋 
Thanks for opening an issue!

I'm not sure I fully understand the issue. When you call dispose you are closing the bloc's stream so it will not process anymore events. With the flutter_bloc 0.19.0+ BlocProvider automatically disposes the bloc by default so you shouldn't have to.

Can you please provide a link to a sample app which illustrates the problem you're having and include the version of flutter_bloc that you're using? Thanks!

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional information and I'm happy to continue the conversation 👍
