### ISSUE TITLE
[Question] Cancelling subscription in BLoC with Stream example

### ISSUE THREAD

**Issue by agmontpetit** [felangel/bloc#456]
I was looking into the [BLoC with Stream example](https://github.com/felangel/bloc/tree/master/examples/flutter_bloc_with_stream) and was curious why you are [cancelling](https://github.com/felangel/bloc/blob/master/examples/flutter_bloc_with_stream/lib/bloc/ticker_bloc.dart#L18) the subscription when the `StartTicker` event is received if you are also [doing it](https://github.com/felangel/bloc/blob/master/examples/flutter_bloc_with_stream/lib/bloc/ticker_bloc.dart#L28) in the `dispose` method.

Thanks in advance!

**Comment by felangel** [comment]
Hi @agmontpetit 👋 
Thanks for opening an issue!

Regarding your question, the subscription was cancelled when the `StartTicker` event is received in order to clean up the old subscription before creating the new subscription for the new ticker.

Hope that help! 👍

**Comment by agmontpetit** [comment]
Makes sense! Should have realized since the event is being fired on each user click 🤦‍♂
