### ISSUE TITLE
[Good practice question] Business Logic inside the State class

### ISSUE THREAD

**Issue by fabryx92** [felangel/bloc#458]
I have the following situation.
I have a `CheckoutState` class with a `Request` field. To make the UI clearer I have to split the `Request` content into some subclasses, like ViewModel classes. The data need some preprocessing.
One example is the `PricesDetail` of the `Request`.

Is it ok to have something like 

```dart
 final Request request;

CheckoutPricesDetailModel get pricesDetail {
...
}
```
where inside the `pricesDetail` block I will do all the transformation need to be nicely presented, directly inside the State class?

Or is better to do this kind of things inside the Bloc class and add a field in the State class?

**Comment by felangel** [comment]
Hi @fabryx92 👋 
Thanks for opening an issue!

In general, I would recommend keeping your business logic in the bloc as that's where developers would likely expect to find it. The state class should ideally just include the different state models. This makes it easier for new developers to quickly look at the bloc events and states and have good understanding what the bloc does without having to worry about how it works.

Hope that helps 👍

**Comment by fabryx92** [comment]
Thank you for the answer and sorry for the reply even if you flag the issue as closed, but I have one more question.

What about combining bloc with ViewModels? 
Can business logic related to fields manipulation be put inside a ViewModel class? I'm talking about DateTime formatting, String manipulation, and stuff that a "Presenter" class usually do.

Something like

```dart
class CheckoutState {
    final Request request;

    CheckoutPricesDetailViewModel get pricesDetail => CheckoutPricesDetailViewModel.fromRequest(request);
}
```
where the `Request` is the actual state and the ViewModels classes are derived from the `request` field and used for presentation purpose only in order to have a clean interface that the specific UI subtree can directly use to retrieve its own piece of state.

Is it good to put the manipulation business logic inside the `CheckoutPricesDetailViewModel.fromRequest` factory method? Or is your advice to put all in the bloc still valid?

**Comment by felangel** [comment]
@fabryx92 no problem and regarding your second question, converting the request/raw data into a model should be handled by the repository layer and not by the bloc layer. The bloc should simply interface with one or more repositories and convert events into different application states.

Hope that helps 👍

**Comment by fabryx92** [comment]
@felangel the `ChechoutBloc` already uses a `RequestsRepository` to send the `Request` to the backend. 
The `Request` field in the `CheckoutState` class, however, is built locally through some steps in the previous pages. I have something like "Products step", "PersonalInfo step", "AdditionalInfo step" and after that a `Request` is created. The entire `Request` construction process is handled by an orchestrator bloc (the `RequestBloc`) that communicates with the `ProductsBloc`, the `PersonalInfoBloc` and the `AdditionalInfoBloc`. Only after all the steps, the `RequestBloc` will pass the `Request` to the `CheckoutBloc`.

Do you mean that I have to use the repository layer even if the request is built through the described process?

**Comment by felangel** [comment]
@fabryx92 Sorry I misunderstood I thought you meant http request haha. If the `Request` is an application level model then what you're doing is fine 👍
