### ISSUE TITLE
UI Freezes when doing heavy computations

### ISSUE THREAD

**Issue by Darklod** [felangel/bloc#460]
```dart
class WordBloc extends Bloc<WordEvent, WordState> {
  final _repository = Repository.get();

  @override
  WordState get initialState => WordsEmpty();

  @override
  Stream<WordState> mapEventToState(WordEvent event) async* {
    if (event is FetchWords) {
      yield WordsLoading();
      try {
        final List<Word> words = await _repository.getWords(term: event.search);
        if (words == null || words.isEmpty)
          yield event.search.isEmpty ? WordsEmpty() : WordsLoaded([]);
        else
          yield WordsLoaded(words);
      } catch (e) {
        print(e);
        yield WordsError();
      }
    }
  }
```
`getWords` is the heavy operation

The UI freeze when passing from Loading state to Loaded state. Could it be the listview that needs to render a lots of elements.

I was thinking to execute things on another thread with the `compute` method. 
Something like this, but I got an error.
```dart
static Repository _repository = Repository.get();

static Future<List<Word>> getWords(String search) async {
    return await _repository.getWords(term: search);
}

@override
Stream<WordState> mapEventToState(WordEvent event) async* {
    ...
    yield WordsLoading();
    ...
    final List<Word> words = await compute(getWords, event.search);
    ...
    yield WordsLoaded(words);
    ...
}
```
Anyway, how to handle this? Is there a practice to follow?

**Comment by felangel** [comment]
Hi @Darklod 👋 
Thanks for opening an issue!

Can you please share a sample app which illustrates the problem you're having? It would be much easier for me to help if I can run the app locally and debug the issue.

Thanks 👍

**Comment by Darklod** [comment]
I created an example code, but this problem is not very visible. When passing from loading to the listview's rendering the loader freezes for a while. 
In my project I get data from sqlite and when the results are a lot the loader freezes for much more time. 

I put here the link of both projects:
- [Sample](https://github.com/Darklod/flutter_sample)
- [Project](https://github.com/Darklod/jisho)

**Comment by felangel** [comment]
@Darklod I took a look at the sample and couldn't really see any freezing. I then took a look at your actual project but it's missing the db file as mentioned in https://github.com/Darklod/jisho/issues/1. As a result, I couldn't run it to reproduce the issue. Can you provide the db and api credentials needed to run the app or provide a different sample that demonstrates the issue?

Also, can you elaborate on what you mean when you say the loader freezes? Do you mean the loader stops spinning or it's just shown for a longer time?

Thanks!

**Comment by Darklod** [comment]
The issue was old. I moved to sqflite, so credentials are no more required.
 
This is what I mean:
<img src="https://user-images.githubusercontent.com/19750893/62686216-8c4b8980-b9c4-11e9-8be0-fe330d6d3dc1.gif" width="300" height="500">

**Comment by felangel** [comment]
Hi @Darklod I just ran it and took a look. It looks like it's just the volume of search results that is causing the lag.

<img width="1674" alt="Screen Shot 2019-08-08 at 9 49 30 PM" src="https://user-images.githubusercontent.com/8855632/62750786-f6951600-ba26-11e9-9f07-510527fa89f9.png">

I don't think this has anything to do with the bloc library. You might want to paginate your search results so that you only process them in smaller chunks instead of having everything come back at once.

I would also recommend running the app in release mode on a device to see what the actual performance looks like.

Hope that helps! 👍
