### ISSUE TITLE
Duplicate Empty Classes

### ISSUE THREAD

**Issue by Habib23me** [felangel/bloc#462]
Hi @felangel , just a question rather than an issue here. I am using the bloc package quite often for my projects and am noticing that I have to write an empty state class that just notifies the UI that the data is changed and am doing it for all my bloc. Is this the right way or am I missing something? Also if there is any suggestion not to duplicate classes it's very helpful. Take a look at one of my bloc states for example.

```
  @override
   Stream<CategoryState> mapEventToState(
        CategoryEvent event ) async* {
        if (event is FetchCategories)
             yield* _fetchListMTS();
        }
      Stream<CategoryState> _fetchListMTS() async* {
         this.categories = await  EcommerceApiRepository.instance.fetchCategories();
         yield CategoryStateChanged();  
       }
```
This piece of code only does one thing fetches categories from an api, update my list and notify the UI.

```
@immutable
abstract class CategoryState {}

class InitialCategoryState extends CategoryState {}

class CategoryStateChanged extends CategoryState{}
```
But I had to implement an extra empty class "CategoryStateChanged" just notify the UI that the data is changed.

Thanks in advance,

**Comment by RaviKavaiya** [comment]
@Habib23me hello, I think you should parameterize the InitialState class. Something like isLoaded field in class. When you call fetchList(), just yield InitialState again with field changed. (isLoaded = true). This way, all the bloc builders and listeners will be called again.

I hope this helps. @felangel please correct me if I am wrong.

**Comment by Habib23me** [comment]
@RaviKavaiya thanks, that actually makes sense. I think it's better if I give parameters to one base class and then invoke an update to create a new state by copying the behaviors and updating the one that needs to be updated.
Thanks for the help!

**Comment by RaviKavaiya** [comment]
@Habib23me I got even a better solution.
This implies ONLY if you are talking about empty classes to represent your state.

Create `enum` of all your states, like
`enum states {initial, loaded, failed}`
Then just yield one of the enum entry, like
`yield states.loaded, yield states.failed`....
This is very handy in your case, only if you don't have any additional parameters to be passed to the new state.

**Comment by felangel** [comment]
HI @Habib23me 👋 
Thanks for opening an issue!

Regarding your question, as @RaviKavaiya mentioned, if you don't have any data you need to pass around then it's probably best to just use an `enum` to represent your states.

If you do find yourself having to pass data around, then I think having an abstract base class with subclasses for each individual state is best. Having empty subclasses, isn't a bad thing; it's just a way to represent a unique state that your bloc can be in 👍 

Hope that helps and great question!
