### ISSUE TITLE
BlocBuilder unable to find bloc 

### ISSUE THREAD

**Issue by natintosh** [felangel/bloc#466]
I'm new to flutter_bloc, I don't know if I am doing something wrong or if this is a bug. While I was developing I ran into this (screenshot below) issue but BlocBuilder works on other instances. I downgraded from version v0.20.0 to v0.19.1 the issue seems to have gone but it was requesting for a bloc and also ran a new issue (second screenshot below). Please is there any walk through for fixing this or did I do something wrong 

![Screenshot from 2019-08-08 17-06-07](https://user-images.githubusercontent.com/27495055/62750513-58ba3f00-ba58-11e9-9669-c42dbf8f63d4.png)

![Screenshot from 2019-08-09 03-55-38](https://user-images.githubusercontent.com/27495055/62750905-9b304b80-ba59-11e9-87d9-d163ff23d1d1.png)

**Comment by felangel** [comment]
Hi @natintosh 👋 
Thanks for opening an issue!

Are you able to share a link to the project? Thanks 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional details and I'm happy to continue the conversation 👍

**Comment by natintosh** [comment]
@felangel  Thanks for the response it was a mistake at my end it should have been Blocbuilder<bloc, state> not BlocBuilder<bloc, event>, thanks for this package. I also have some recommendation please could you make a tutorial for flutter_bloc that uses nestednavigator thanks
