### ISSUE TITLE
Login is not working with bloc

### ISSUE THREAD

**Issue by pardipbhatti8791** [felangel/bloc#469]
Hi, I am having login n logout issue with bloc, While I am logging in it is not changing the screen on main.dart, I debug it, main.dart bloc builder not updating the state there. While i do hard restart then it changes the screen. here is my code https://github.com/pardipbhatti8791/login-issue . Please help me out with this.

**Comment by felangel** [comment]
Hi @pardipbhatti8791 👋 
Thanks for opening an issue!

Can you please provide instructions for how I can login? I cannot debug this locally without having valid credentials. Thanks!

**Comment by felangel** [comment]
I opened a [pull request](https://github.com/pardipbhatti8791/login-issue/pull/1) with the fix 👍 
You were using multiple instances of the `AuthenticationBloc` and were also using `pushNamedAndRemoveUntil` which was removing the underlying widgets containing the bloc.
