### ISSUE TITLE
bloc.dispatch(), BlocListener and BlocBuilder can't execute.

### ISSUE THREAD

**Issue by longdw** [felangel/bloc#470]
when I call `bloc.dispatch(WarrantyActionEvent(actionBean));`, BlocListener and BlocBuilder can't trigger.
this is my project.
[https://github.com/longdw/testbloc](https://github.com/longdw/testbloc)

**Comment by felangel** [comment]
Hi @longdw I opened a [pull request](https://github.com/longdw/testbloc/pull/1) to fix your sample app. You need to make sure that you use `Equatable` properly and that all of your bloc states should be immutable.

Hope that helps 👍
