### ISSUE TITLE
SearchDelegate Items Persists

### ISSUE THREAD

**Issue by kirkcharlesniv** [felangel/bloc#471]
**Describe the bug**
While using SearchDelegate, when you submit a query for the second time, the first time result items still persists.

**To Reproduce**
1. Open the application, then click the search icon.
2. Enter your first query and wait for the result items to show.
3. Search again with a new query. _This time, the items wouldn't show as the first time items still persists_

**Expected behavior**
ListView items would be cleared, then show the new query result items.

**Screenshots**
![gif1](https://user-images.githubusercontent.com/19856377/62862834-9f9a8400-bd39-11e9-8098-186aff5efcec.gif)

**Logs**
![image](https://user-images.githubusercontent.com/19856377/62862843-a9bc8280-bd39-11e9-8f76-d98de6919b59.png)
![image](https://user-images.githubusercontent.com/19856377/62862860-b80a9e80-bd39-11e9-9589-f9ae346907aa.png)

**Additional context**
App use updated bloc, hydrated_bloc, and other related dependencies.
[**Code** that dispatches the query](https://github.com/kirkcharlesniv/viva_aranzazu_rework/blob/master/lib/widgets/dashboard_page.dart#L62-L63l)

**Comment by felangel** [comment]
Hi @kirkcharlesniv 👋 
Thanks for opening an issue!

I took a look and I believe it's because in your bloc you are yielding a new state and appending the new results to the end of the existing results
```dart
SearchLoaded(
  posts: (currentState as SearchLoaded).posts + posts,
  hasReachedMax: false);
```

If you scroll down you will see the new search results appended to the previous results 👍 

Hope that helps!
