### ISSUE TITLE
[Question] Why using factory instead of constructor in flutter_firebase_login?

### ISSUE THREAD

**Issue by agmontpetit** [felangel/bloc#472]
Since you are returning a new object for each `factory` ([example](https://github.com/felangel/bloc/blob/master/examples/flutter_firebase_login/lib/login/bloc/login_state.dart#L31)), I was wondering why not using constructors instead?

**Comment by felangel** [comment]
Hi @agmontpetit 👋 
Thanks for opening an issue!

Factories were used to make the bloc implementation easier to read/understand. You can accomplish the same thing without factories but I chose to used them due to personal preference.

Hope that helps 👍

**Comment by agmontpetit** [comment]
Makes sense! Thanks for your reply
