### ISSUE TITLE
SimpleDialog selection is not updated on screen using BLOC pattern

### ISSUE THREAD

**Issue by guybashan** [felangel/bloc#473]
I have a popup (SimpleDialog) showing a selection of few texts. I am trying to update a text on the screen with the selected text. When selecting the one of the texts the window closes, but the selected text is not updated on the screen. I am using BLOC pattern.

I have another dialog based on AlertDialog showing a text field. Once pressing OK the same text is updated on the screen properly and the dialog closes.

Here is the code showing the SimpleDialog:
```
_selectGoal(BuildContext context) async {
  final choice = await showDialog<String>(
      context: context,
      builder: (_) {
        return SimpleDialog(
            title: const Text('Select a Goal'),
            children: BehavioralDesignGoalOptions.goals
                .map((o) =>
                SimpleDialogOption(
                  onPressed: () {
                    Navigator.pop(context, o);
                  },
                  child: Text(o),
                ))
                .toList());
      });

  if (choice != null) {
    print("choice: " + choice);
    BlocProvider.of<BehavioralDesignBloc>(context).dispatch(
        BehavioralDesignSetGoalEvent(choice));
    }
}
```

Anything I am missing?

**Comment by felangel** [comment]
Hi @guybashan 👋 
Thanks for opening an issue!

Can you please provide a link to an example app? It would be much easier for me to help/understand the issue if you could share a sample app that illustrates the problem 👍 

Thanks!

**Comment by guybashan** [comment]
Hi @felangel,
I added a sample project showing the issue.
Sorry for the mess, it is kinda playground phase..

**Scenario:**
* Run the app
* Press on Behavioral design
* On the top right menu select "Select a Goal"
* A popup will be open - select an item
* The value will not be updated as the title instead of "Select a goal..."
* If you choose the second option: "Custom Goal" and enter some value, it will be set properly.


Here is a download link:
[parents_aid - test.zip](https://github.com/felangel/bloc/files/3503277/parents_aid.-.test.zip)

**Comment by felangel** [comment]
@guybashan I took a look and the problem is you're mutating state. When using the bloc library you should never mutate `currentState`. Instead, you should yield a brand new instance of your state.

If you update `behavioral_design_session.dart` to be:
```dart
class BehavioralDesignSession {
  final String goal;

  final DateTime dateStart;
  final DateTime dateEnd;

  final List<bool> checked = List<bool>.filled(10, false, growable: false);

  BehavioralDesignSession({
    String goal,
    this.dateStart,
    this.dateEnd,
  }) : this.goal = goal ?? "Set a goal...";

  factory BehavioralDesignSession.initial(DateTime dateStart) {
    return BehavioralDesignSession();
  }

  BehavioralDesignSession copyWith(
      {String goal, DateTime dateStart, DateTime dateEnd}) {
    return BehavioralDesignSession(
      goal: goal ?? this.goal,
      dateStart: dateStart ?? this.dateStart,
      dateEnd: dateEnd ?? this.dateEnd,
    );
  }
}
```

and then modify `behavioral_design_bloc.dart` to be:
```dart
import 'dart:async';
import 'package:bloc/bloc.dart';
import 'package:parentsaid/model/behavioral_design_session.dart';

import 'BehavioralDesginEvent.dart';

class BehavioralDesignBloc
    extends Bloc<BehavioralDesignEvent, BehavioralDesignSession> {
  @override
  BehavioralDesignSession get initialState =>
      BehavioralDesignSession.initial(DateTime.now());

  @override
  Stream<BehavioralDesignSession> mapEventToState(
    BehavioralDesignEvent event,
  ) async* {
    if (event is BehavioralDesignSetGoalEvent) {
      yield currentState.copyWith(goal: event.goal);
    }
  }
}
```

then you should be good to go 👍 

Hope that helps and please refer to the [core concepts](https://felangel.github.io/bloc/#/coreconcepts) for more details.

**Comment by guybashan** [comment]
Thanks @felangel. Working with immutable states seems to be working fine, but I was also able to fix this issue by wrapping the bloc dispatch with "setState". Is it legit?
Handling immutability is going to require more code for copying the state. Probably a special treatment should be also given to the "checked" array..
