### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by jiharal** [felangel/bloc#479]
https://felangel.github.io/bloc/#/flutterlogintutorial

![image](https://user-images.githubusercontent.com/21150538/63229537-dd187900-c233-11e9-90f4-e909b9d15578.png)

**Comment by jiharal** [comment]
```
 return MaterialApp(
      home: BlocBuilder<AuthenticationBloc, AuthenticationState>(
        builder: (BuildContext context, AuthenticationState state) {
          if (state is AuthenticationUninitialized) {
            return SplashPage();
          }
          if (state is AuthenticationAuthenticated) {
            return HomePage();
          }
          if (state is AuthenticationUnauthenticated) {
            return LoginPage(userRepository: userRepository);
          }
          if (state is AuthenticationLoading) {
            return Center(
              child: CircularProgressIndicator(),
            );
          }
        },
      ), return MaterialApp(
      home: BlocBuilder<AuthenticationBloc, AuthenticationState>(
        builder: (BuildContext context, AuthenticationState state) {
          if (state is AuthenticationUninitialized) {
            return SplashPage();
          }
          if (state is AuthenticationAuthenticated) {
            return HomePage();
          }
          if (state is AuthenticationUnauthenticated) {
            return LoginPage(userRepository: userRepository);
          }
          if (state is AuthenticationLoading) {
            return Center(
              child: CircularProgressIndicator(),
            );
          }
        },
      ),
```

**Comment by felangel** [comment]
@jiharal thanks for catching this. I just fixed it in https://github.com/felangel/bloc/commit/0fdb972deeda3c282cae7cc77b62aee29e82abf4.

You should be able to refresh the page and see the updated syntax 👍

**Comment by rajeshpatil95** [comment]
Solved my issue only if I make my Bloc Strictly non-nullable type...It resolves the above-typecast issue

**Comment by felangel** [comment]
@rajeshpatil95 can you please share a reproduction sample, thanks!

**Comment by nonik1017** [comment]
maybe you add another CreateUpiPinScreenState, check yourself

> @felangel i am using flutter_bloc: ^7.0.0 environment: sdk: '>=2.12.0 <3.0.0'
> 
> @felangel Sorry no luck tried above: flutter pub cache repair flutter clean
> 
> This issue started to occur after updating project to null safety
> 
> State: ![Screenshot from 2021-04-08 00-38-28](https://user-images.githubusercontent.com/41562370/113920763-d8d31200-9802-11eb-8819-06635dfc6e3e.png) Event: ![Screenshot from 2021-04-08 00-39-57](https://user-images.githubusercontent.com/41562370/113920878-fb652b00-9802-11eb-8b3e-f92a2e918fd2.png) Bloc: ![Screenshot from 2021-04-08 00-40-29](https://user-images.githubusercontent.com/41562370/113920935-0f109180-9803-11eb-8ef3-525a1b1cd431.png)

**Comment by thecoder-co** [comment]
> Solved my issue only if I make my Bloc Strictly non-nullable type...It resolves the above-typecast issue. But I think BlocConusmer should able to handle the nullable Bloc...with null as an initial state in super({null}) contructor

Please can you share the implemented solution?

**Comment by MahdiGharooni** [comment]
I had the same problem and finally fixed it. My fault is in the **bloc file**. When I add null safety to my codes, my bloc file automatically changed but in the wrong way. When I check, it has a **nullable state** as an argument by **?** sign.

I had this :
`class AuthenticationBloc
    extends Bloc<AuthenticationEvent, AuthenticationState?>` 

and change it to this manually:
`class AuthenticationBloc
    extends Bloc<AuthenticationEvent, AuthenticationState>`
