### ISSUE TITLE
Is there any way not to override == and hashCode?

### ISSUE THREAD

**Issue by Feelthewind** [felangel/bloc#48]
Hi, author.
Do i have to override == and hashcode everytime i write state and event files?
If it's possible, could you give us some example for this too?
Thank you.

**Comment by felangel** [comment]
@Feelthewind the default behavior for `==` in Dart is to return true if and only if the two objects are the same instance. So for this reason if you ever want to be able to write tests for equality of two events/states or use distinct/debounce in the transform method you will need to override == and hashcode.

https://www.dartlang.org/guides/language/effective-dart/design#do-override-hashcode-if-you-override-

Does that help? Please let me know if you still have questions.

**Comment by felangel** [comment]
Closing for now. Let me know if you have more questions and I’ll reopen it.

**Comment by Feelthewind** [comment]
Oh Thank you for updating the login tutorial with equatable. I thought it was tedious to write code to compare objects and equatable seems to be good.

**Comment by felangel** [comment]
No problem and thanks for bringing this up!
