### ISSUE TITLE
Rebuild bloc with the same state

### ISSUE THREAD

**Issue by semutnest** [felangel/bloc#481]
Hello MR Felix,

I just want to ask, is there a way to rebuild bloc but the next state that we send is the same as the current state but with different data ?

Thank you.

**Comment by felangel** [comment]
Hi @semutnest 👋 
Thanks for opening an issue!

Regarding your question, yes 👍 you just need to make sure you’re never mutating currentState. Instead, create a new instance and everything should work as you’d expect.

Are you having trouble getting the expected results? If so, it would be great if you could share a link to a sample app which illustrates the problem you’re having. 

Hope that helps 👍

**Comment by semutnest** [comment]
Ok sir, Thank you I will give it a try.

**Comment by semutnest** [comment]
Sorry, Sir

I have not understood what you mean '**create a new instance**'
I have a simple example.

//BLOC
class MyBloc extends Bloc<MyFormEvent, MyFormState> {
  @override
  MyFormState get initialState => InitialState();

  @override
  void onTransition(Transition<MyFormEvent, MyFormState> transition) {
    print(transition);
  }

  @override
  Stream<MyFormState> mapEventToState(
    MyFormEvent event,
  ) async* **{
    if (event is TestEvent) {
      if (currentState is TestState) {
        if ((currentState as TestState).status)
          yield TestState(status: !(currentState as TestState).status);
        else
          yield TestState(status: (currentState as TestState).status);
      }  
      else  yield TestState(status: true);   
    }
  }
}**

//EVENT
abstract class MyFormEvent extends Equatable {
  MyFormEvent([List props = const []]) : super(props);
}

class TestEvent extends MyFormEvent {  
  @override
  String toString() => 'TestEvent';
}

//STATE
abstract class MyFormState extends Equatable {
  MyFormState([List props = const []]) : super(props);
}

class InitialState extends MyFormState {
  @override
  String toString() => 'InitialState';
}

class TestState extends MyFormState {
  final bool status;
  TestState({@required this.status}) : super([status]);
  @override
  String toString() => 'TestState';
}

class OtherState extends MyFormState {
  @override
  String toString() => 'OtherState';
}

//MAIN
void main() {
  runApp(
    BlocProvider<MyBloc>(
      builder: (context) => MyBloc(),
      child: App(),
    ),
  );
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final MyBloc myBloc = BlocProvider.of<MyBloc>(context);
    return MaterialApp(
      home: Scaffold(
          appBar: AppBar(title: Text('Flutter')),
          body: BlocBuilder<MyBloc, MyFormState>(builder: (context, state) {
            print("REBUILD BLOC");
            if (state is TestState) {
              if (state.status)
                return Center(child: Text("SUCCSES"));
              else
                return Center(child: Text("NO SUCCSES"));
            } 
            return Center(child: Text("NO DATA"));           
          }),
          floatingActionButton: FloatingActionButton(
              child: Icon(Icons.remove),
              onPressed: () {
                myBloc.dispatch(TestEvent());
              },
            ),
          ),
    );
  }
}

From this example, the first push button rebuildthe block but not the next press.
can you provide hints for this;

Thanks a lot.

**Comment by felangel** [comment]
Hi @semutnest the problem in your example is when `status == false` you always yield TestState(status: (currentState as TestState).status);

By default, if you yield a state where `state == currentState`, then no transition will occur ([docs](https://felangel.github.io/bloc/#/coreconcepts?id=blocs)).

If you update your example to:
```dart
import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:bloc/bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class MyBloc extends Bloc<MyEvent, MyState> {
  @override
  MyState get initialState => InitialState();

  @override
  void onTransition(Transition transition) {
    print(transition);
  }

  @override
  Stream<MyState> mapEventToState(MyEvent event) async* {
    final state = currentState;
    if (event is TestEvent) {
      if (state is TestState) {
        yield TestState(status: !state.status);
      } else
        yield TestState(status: true);
    }
  }
}

//EVENT
abstract class MyEvent extends Equatable {
  MyEvent([List props = const []]) : super(props);
}

class TestEvent extends MyEvent {
  @override
  String toString() => 'TestEvent';
}

//STATE
abstract class MyState extends Equatable {
  MyState([List props = const []]) : super(props);
}

class InitialState extends MyState {
  @override
  String toString() => 'InitialState';
}

class TestState extends MyState {
  final bool status;
  TestState({@required this.status}) : super([status]);
  @override
  String toString() => 'TestState { status: $status }';
}

class OtherState extends MyState {
  @override
  String toString() => 'OtherState';
}

//MAIN
void main() {
  runApp(
    BlocProvider(
      builder: (context) => MyBloc(),
      child: App(),
    ),
  );
}

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final MyBloc myBloc = BlocProvider.of<MyBloc>(context);
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(title: Text('Flutter')),
        body: BlocBuilder<MyBloc, MyState>(
          builder: (context, state) {
            print("REBUILD BLOC");
            if (state is TestState) {
              if (state.status)
                return Center(child: Text("TRUE"));
              else
                return Center(child: Text("NOT TRUE"));
            }
            return Center(child: Text("NO DATA"));
          },
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(Icons.account_circle),
          onPressed: () {
            myBloc.dispatch(TestEvent());
          },
        ),
      ),
    );
  }
}
```

Then everything will work as expected.

Hope that helps 👍

**Comment by semutnest** [comment]
Ok Thank you @felangel

**Comment by manhDat0301** [comment]
@felangel Hi sir! I'm having the same problem with version 6.0.1. Can you give me an example on how to rebuild with the same State when i triggered events?

**Comment by felangel** [comment]
@manhDat0301 hey you can just avoid extending Equatable and yield a new instance of your state -- that hasn't changed for v6.0.1.

**Comment by hardik-kumbhani** [comment]
Hello Everyone, If we want to rebuild same state again and again then we have to keep one timestamp field in state class
and whenever you yeild or emit your state at that time just put latest timeStamp in it.
```
class YourState extends YourMainState {
  List<AttachFileModel> attachFileList = [];
  int timeStamp;

  YourState({this.attachFileList,this.timeStamp});

  @override
  List<Object> get props => [timeStamp];
}
```

**Comment by om-ha** [comment]
In addition to @hardik-kumbhani , I just came up with this:

```dart
class MyState extends Equatable {
  // ...
  // state properties & constructor go here
  // ...

  @override
  bool operator ==(Object other) => false;

  @override
  // ignore: unnecessary_overrides
  int get hashCode => super.hashCode;
}
```

I have no idea how `BlocListener` is toted to be used for navigation purposes (according to state changes that are purposefully designed with navigation). This is a problem if you subclass a base state that subclasses Equatable. Point being, navigation states should be different form business-logic states as they should trigger BlocListener every time they are emitted, and not only once per state change (same state emitted twice should trigger BlocListener twice, not once)


Yet if you want user to navigation to same page they navigated to previously, `BlocListener` will not be fired. As per the docs:
```dart
/// The [listener] is guaranteed to only be called once for each `state` change
/// unlike the `builder` in `BlocBuilder`.
```

However, in the same breath BlocListener it's recommended to be used for navigation (weirdly enough):
```dart
/// Takes a [BlocWidgetListener] and an optional [bloc] and invokes
/// the [listener] in response to `state` changes in the [bloc].
/// It should be used for functionality that needs to occur only in response to
/// a `state` change such as navigation, showing a `SnackBar`, showing
/// a `Dialog`, etc...
```

**Comment by om-ha** [comment]
@felangel 🙏

**Comment by felangel** [comment]
@om-ha if you want to have the same state trigger a rebuild, just do not override `==` and do not extend `Equatable`. The two states will automatically be treated as different because they are different instances.

**Comment by om-ha** [comment]
Thanks for your response Felix, this is a challenge when Feature Bloc's `FeatureBaseState` extends `Equatable`. Then when other concrete states extend this `FeatureBaseState`, they will be treated as Equatable with the [behavior above](https://github.com/felangel/bloc/issues/481#issuecomment-1245000961).

So I believe a workaround I have in mind is to use `Equatable` as mixin on the leaf concrete classes. So it is used optionally within them. Rather than extending Equatable on the `BaseState` class
