### ISSUE TITLE
Is type checking a good practice?

### ISSUE THREAD

**Issue by durduman** [felangel/bloc#482]
I am using bloc architecture based this repo.

It seems that it is based a lot on type checking such as:

>     if (event is FooEvent) { 
>      // ...
>     }
>      //.. or
>     if (state is BarState) { 
>      // ...
>     }

Is type checking a good practice?
Are flutter & dart oriented towards this way coding or is this just a shortcut for this bloc implementation.

**Comment by felangel** [comment]
Hi @durduman 👋 
Thanks for opening an issue!

Bloc does not have an opinion about how you model your states. In some cases, you can get away with using enums so you can simply switch on the event (see [counter example](https://felangel.github.io/bloc/#/coreconcepts?id=blocs)).

In more complex cases, it's common to use classes to model your events and states. If you choose to go that route, you'll need a way to identify which type of state you are processing; type checking is one of the most easy/straightforward ways and there's nothing wrong with checking an object's type.

Hope that helps 👍

**Comment by durduman** [comment]
Thank you for your answer.
