### ISSUE TITLE
Request to update TODO firestore application:  Stream todo details if changed via Cloud Firestore Console

### ISSUE THREAD

**Issue by pratikpparikh** [felangel/bloc#484]
**Describe the bug**
I have a list of events to display on calendar and stream updates as they might happen (update, delete, add) and i use firestore to store and retrieve the events.  Below 1 is what my code structure needs to be, the code works but problem is it only listener to stream once for populateEvents and then does not get called on every change.  It stops listening to update or deletes or add.  The only way I can make it work is I change it to 2.  But 2 won't work for me as i need to do setState is using BlocListener. How can I keep listing to the stream using BlocListener? 

1.

```
BlocProvider<EventBloc>(
        builder: (context) => _eventBloc
          ..dispatch(FetchEvents()),
        child: Scaffold(
            body:
                BlocListener<EventBloc, EventState>(
                bloc: _eventBloc,
                listener: (BuildContext context, EventState state) {
                  if (state is EventSuccess) {
                    populateEvents();
                  }
                },
                child: BlocBuilder<EventBloc, EventState>(
                    bloc: _activityBloc,
                    builder: (context, state) {
                     if (state is EventSuccess) {
                        return Column(); // display events
                      } else {
                        return Container();
                      }
                    }))));
```

2. 					
```
BlocProvider<EventBloc>(
        builder: (context) => _eventBloc
          ..dispatch(FetchEvents()),
        child: Scaffold(
            body:BlocBuilder<EventBloc, EventState>(
                    bloc: _activityBloc,
                    builder: (context, state) {
                     if (state is EventSuccess) {
                        return Column(); // display events
                      } else {
                        return Container();
                      }
                    })));
```

**Comment by pratikpparikh** [comment]
This is a non issue, 1 works for me i just needed more breakpoints

**Comment by pratikpparikh** [comment]
@felangel a quick question for you though, now my structure looks like 1. First time when EventSuccess comes it gets listened by both BlocListener and BlocBuilder every other update only BlocBuilder is notified and listening.  If i have to remove or update or add new event in UI what would be a good way to tackle that?

**Comment by felangel** [comment]
Hi @pratikpparikh 👋 
Thanks for opening an issue!

What you're describing is how the current [flutter_firestore_todos example](https://github.com/felangel/bloc/tree/master/examples/flutter_firestore_todos) works. You can either make changes in the app or directly in firebase console and everything will update in real-time.
