### ISSUE TITLE
BlocBuilder and BlocListener questions

### ISSUE THREAD

**Issue by vungocnamhust** [felangel/bloc#486]
In initstate() I dispatch an event to Bloc 
Although I dispatch this event successfully and every data updated, My  BlocBuilder and BlocListener I can not receive the state 
Can you answer for me it is my fail whether your rule ?

**Comment by felangel** [comment]
Hi @vungocnamhust 👋 
Thanks for opening an issue!

Can you provide a sample app that illustrates the problem you're having? I'm guessing that you're either mutating the currentState or if you're using `Equatable` you've forgotten to pass the class properties to the super class.

**Comment by vungocnamhust** [comment]
My subject is make a infinite list and I have read your code about infinite list  
My issue is my bloc builder can not realize the changing of object so when I using transform with debounce time, everything can be solved. 
However I think it is the same as the trick because it depend on the internet speed 
Do you have a better solution? Thanks

**Comment by vungocnamhust** [comment]
Sorry I forgot :)))))
Here is my code for this page
https://github.com/vungocnamhust/Flutter/tree/master/Flutter%20Project/notify

**Comment by felangel** [comment]
I took a look and the project you shared didn't seem like a complete flutter project so I wasn't able to run it. I still took a look at the code and created a [pull request](https://github.com/vungocnamhust/Flutter/pull/1) with a few fixes. Hope that helps! 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation.

**Comment by vungocnamhust** [comment]
Thank you very much <3 I have fixed successfully
