### ISSUE TITLE
what's BlocDelegate and what's its use

### ISSUE THREAD

**Issue by MahdiPishguy** [felangel/bloc#487]
could you help me to understand what's `BlocDelegate` and what's its use. documentation of that is not clear for me because i can't find any implementation of that in samples

**Comment by felangel** [comment]
Hey @MahdiPishguy 👋 
Thanks for opening an issue!

You can check out the [core bloc concepts](https://felangel.github.io/bloc/#/coreconcepts?id=blocdelegate) for information about what `BlocDelegate` is and how to use it.

Hope that helps 👍

**Comment by Joaopacheco25** [comment]
Hey @felangel 
Could you tell me if the core bloc concepts link is down ?

**Comment by felangel** [comment]
@Joaopacheco25 just checked and it's not down but it's really slow so try refreshing a few times. The site is hosted by github so hopefully it's back to normal soon 👍

**Comment by Joaopacheco25** [comment]
@felangel  Ok thanks 🙏
