### ISSUE TITLE
flutter_infinite_list with GridView.builder or CustomScrollView

### ISSUE THREAD

**Issue by Ponraj-Paulraj** [felangel/bloc#488]
Hi @felangel, We tried to achieve "flutter_infinite_list" with GridView.builder and CustomScrollView, But not able to place "BottomLoader" at the bottom of the screen. And we are not able to handle `state.hasReachedMax` outside of `ListView.builder`. Any idea how to achieve this?

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional details and I'm happy to continue the conversation 👍

**Comment by Ponraj-Paulraj** [comment]
Hi @felangel ,

`return CustomScrollView(
            controller: _scrollController,
            slivers: <Widget>[
            new SliverGrid(
              gridDelegate: new SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 2,
                crossAxisSpacing: 8.0,
                childAspectRatio: (itemWidth / itemHeight * 4 / 5),
              ),
              delegate: SliverChildBuilderDelegate(
                (c, i) {
                  return i >= state.posts.length ? Container() : PostWidget(post: state.posts[i]);
                },
                childCount: state.hasReachedMax ? state.posts.length : state.posts.length + 1,
              ),
            ),
            new SliverToBoxAdapter(
              child: BottomLoader(),
            ),
          ]);`

Here, how to show  BottomLoader() only when its actually hitting new paging data?

**Comment by felangel** [comment]
@adsonpleal you can add a property `loadingAdditionalResults` to the state and only show the `BottomLoader` if `loadingAdditionalResults` is true.

In the bloc you'd just need to yield an extra state with `loadingAdditionalResults = true` while fetching and `loadingAdditionalResults = false` when you have results.

Then your UI could look like

```dart
    return CustomScrollView(
      controller: _scrollController,
      slivers: <Widget>[
        SliverGrid(
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 2,
            crossAxisSpacing: 8.0,
            childAspectRatio: (itemWidth / itemHeight * 4 / 5),
          ),
          delegate: SliverChildBuilderDelegate(
            (c, i) {
              return i >= state.posts.length
                  ? Container()
                  : PostWidget(post: state.posts[i]);
            },
            childCount: state.hasReachedMax
                ? state.posts.length
                : state.posts.length + 1,
          ),
        ),
        if (state.loadingAdditionalResults)
          SliverToBoxAdapter(
            child: BottomLoader(),
          ),
      ],
    );
```

Hope that helps 👍

**Comment by Ponraj-Paulraj** [comment]
Thanks a lot @felangel , I will try this :)

**Comment by Ponraj-Paulraj** [comment]
@felangel , it works great bro. Thanks for your support. :)
