### ISSUE TITLE
Blocprovider.of() called with a context that does not contain a block of type

### ISSUE THREAD

**Issue by mariaszek9003** [felangel/bloc#497]
I had a problem with getting Bloc from child widget and I have no idea what I'm doing wrong.
I'm using flutter_bloc v.0.21.0.
 
Here is my main.dart:
```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import './pages/splashPage.dart';
import './pages/loginPage.dart';
import './pages/homePage.dart';

import "./blocs/authenticationBloc.dart";

void main() => runApp(WeatherApp());

class WeatherApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _WeatherAppState();
}

class _WeatherAppState extends State<WeatherApp> {
  AuthenticationBloc _authenticationBloc;

  @override
  void initState() {
    _authenticationBloc = AuthenticationBloc();
    _authenticationBloc.dispatch(AppStarted());

    super.initState();
  }

  @override
  void dispose() {
    _authenticationBloc.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return BlocProvider<AuthenticationBloc>(
      builder: (context) => _authenticationBloc,
      child: MaterialApp(
        debugShowCheckedModeBanner: true,
        home: BlocBuilder(
          bloc: _authenticationBloc,
          builder: (context, state) {
            if (state is AuthenticationUninitialized) {
              return SplashPage();
            } else if (state is AuthenticationAuthenticated) {
              return HomePage();
            } else if (state is AuthenticationUnauthenticated) {
              return LoginPage();
            }
          },
        ),
      ),
    );
  }
}

```
And here in LoginPage widget I'm getting my authenticationBloc using BlocProvider.of method (in initState method):
```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import "../blocs//authenticationBloc.dart";

class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  AuthenticationBloc _authenticationBloc;

  @override
  void initState() {
    _authenticationBloc = BlocProvider.of<AuthenticationBloc>(context);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text('This is login page'),
            RaisedButton(
              child: Text('Login'),
              onPressed: () => {},
            )
          ],
        ),
      ),
    );
  }
}
```

but instead of receiving bloc I got this error:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building BlocBuilder<AuthenticationBloc, dynamic>(state:
flutter: _BlocBuilderBaseState<AuthenticationBloc, dynamic>#5b9f4):
flutter:         BlocProvider.of() called with a context that does not contain a Bloc of type
flutter: AuthenticationBloc.
flutter:         No ancestor could be found starting from the context that was passed to
flutter: BlocProvider.of<AuthenticationBloc>().
flutter:
flutter:         This can happen if:
flutter:         1. The context you used comes from a widget above the BlocProvider.
flutter:         2. You used MultiBlocProvider and didn't explicity provide the BlocProvider types.
flutter:
flutter:         Good: BlocProvider<AuthenticationBloc>(builder: (context) => AuthenticationBloc())
flutter:         Bad: BlocProvider(builder: (context) => AuthenticationBloc()).
flutter:
flutter:         The context used was: LoginPage(dirty, state: _LoginPageState#2cea8(lifecycle state:
flutter: created))
```

Can someone tell me what I'm doing wrong?

Here is my Flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.6 18G95, locale
    en-PL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by felangel** [comment]
Hi @mariaszek9003 👋 
Thanks for opening an issue!

Can you please share the link to an example app which illustrates the issue you're having so I can run and debug it locally?

Also, you can eliminate a lot of boilerplate code by refactoring your `StatefulWidgets` into `StatelessWidgets`. This is because `BlocProvider` will automatically dispose the blocs for you and `BlocBuilder` will automatically do the bloc lookup for you.

I've put together a [gist](https://gist.github.com/felangel/65f295f798beb0d14a5912ce947b2b63) with an updated version of the code you've provided. Let me know if that helps and if you're still having trouble please provide a link to a sample app 👍 

Thanks!

**Comment by mariaszek9003** [comment]
Hi @felangel, thank you for response.

Here is the repo: https://github.com/mariaszek9003/WeatherApp

**Comment by felangel** [comment]
Hi @mariaszek9003 thanks for the link! I took a look and opened 2 pull requests.

- [fix imports](https://github.com/mariaszek9003/WeatherApp/pull/1) - fixes the issue you were seeing
- [other improvements](https://github.com/mariaszek9003/WeatherApp/pull/2) - other things I noticed that you might want to improve

Hope that helps and sorry for the delayed response! 👍

**Comment by mariaszek9003** [comment]
Hi @felangel thank you for fixing the issue - that was stupid mistake. Also thank you for code improvement suggestions.

**Comment by ViktorJasch** [comment]
Hello! Can you please explain what was that mistake? Or share code of this project. Project page is currently unavailable, but it interesting)

**Comment by mariaszek9003** [comment]
@ViktorJasch Hi! Sorry for late response. The cause of the problem was double slash that I made in importing statement in LoginPage file:
```
import "../blocs//authenticationBloc.dart";
```

**Comment by Rodrigossff91** [comment]
Ola tenho um problema, esta aparecendo essa mensagem quando vou prover uma estancia 
BlocProvider.of() called with a context that does not contain a Bloc of type ProcessoBloc.

import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:legale/blocs/processo/processo.dart';
import 'package:legale/core/config/style.dart';
import 'package:legale/core/models/processo-model.dart';


// void main() {
//   runApp(new MaterialApp(
//     home: 
//     new ProcessoCardsScreen(),
//   ));
// }

class ProcessoCardsScreen extends StatefulWidget {
  final Processo processo;
  
  

  const ProcessoCardsScreen({Key key, this.processo}) : super(key: key);
  @override
  _ProcessoCardsScreen createState() => _ProcessoCardsScreen();
  
}


class _ProcessoCardsScreen extends State<ProcessoCardsScreen> {
  ProcessoBloc _processoBloc;

 @override
 void initialState(){
  _processoBloc = BlocProvider.of<ProcessoBloc>(context);
   super.initState();
 }
  
  @override
  Widget build(BuildContext context) {
    BlocProvider.of<ProcessoBloc>(context); // linha do erro 
      return BlocBuilder<ProcessoBloc, ProcessoState>(
       bloc: _processoBloc,
        condition: (previousState, state) {
          return previousState is DetalhesProcessoCarregado ||
              state is DetalhesProcessoCarregado;
        },
        builder: (context, state) {
          DetalhesProcessoCarregado currentState =
              (state as DetalhesProcessoCarregado);
          return new Scaffold(
            appBar: AppBar(
              title: Text('Processo'),
              backgroundColor: LegaleStyle.colorPrimary,
            ),
            body: ListView(
              children: <Widget>[

**Comment by felangel** [comment]
@Rodrigossff91 you need to provide the `ProcessoBloc` using `BlocProvider` somewhere in the widget tree

```dart
void main() {
  runApp(
    BlocProvider<ProcessoBloc>(
      builder: (_) => ProcessoBloc(),
      child: MaterialApp(
        home: ProcessoCardsScreen(),
      ),
    ),
  );
}
```

Then when you use `BlocProvider.of` you need to provide the bloc type so instead of
```dart
_processoBloc = BlocProvider.of(context);
```

you should do

```dart
_processoBloc = BlocProvider.of<ProcessoBloc>(context);
```

Hope that helps 👍

**Comment by Rodrigossff91** [comment]
tnks

**Comment by areejmayadeh** [comment]
Hi, I have the same issue @felangel ,
here is my code : 
`import 'dart:async';

import 'package:meta/meta.dart';
import 'package:bloc/bloc.dart';

import '../repositories/user_repository.dart';
import './authentication.dart';

class AuthenticationBloc
    extends Bloc<AuthenticationEvent, AuthenticationState> {
  final UserRepository userRepository;

  AuthenticationBloc({@required this.userRepository})
      : assert(userRepository != null);

  @override
  AuthenticationState get initialState => AuthenticationUninitialized();

  @override
  Stream<AuthenticationState> mapEventToState(
    AuthenticationEvent event,
  ) async* {
    if (event is AppStarted) {
      final bool hasToken = await userRepository.hasToken();

      if (hasToken) {
        yield AuthenticationAuthenticated();
      } else {
        yield AuthenticationUnauthenticated();
      }
    }

    if (event is LoggedIn) {
      yield AuthenticationLoading();
      await userRepository.persistToken(event.token);
      yield AuthenticationAuthenticated();
    }

    if (event is LoggedOut) {
      yield AuthenticationLoading();
      await userRepository.logout();
      yield AuthenticationUnauthenticated();
    }
  }
}`

and i called it like this : 
            InkWell(child: Text('logout'),onTap: ()=> BlocProvider.of<AuthenticationBloc>(context).mapEventToState(LoggedOut()))

**Comment by RollyPeres** [comment]
@areejmayadeh you need to add an event to the bloc:

`InkWell(child: Text('logout'),onTap: ()=> BlocProvider.of<AuthenticationBloc>(context).add(LoggedOut())`

**Comment by areejmayadeh** [comment]
@RollyPeres 
`BlocProvider.of<AuthenticationBloc>(context).mapEventToState(LoggedOut())`
I have tried above, mapEventToState function add event but nothing happens

**Comment by areejmayadeh** [comment]
@RollyPeres when try using add function it keeps tell me undefined

**Comment by RollyPeres** [comment]
You should not be using `mapEventToState` but instead use the way I suggested above.
Also make sure you have the latest version of `bloc` and `flutter_bloc` which is `4.0.0`

**Comment by areejmayadeh** [comment]
I used it same as example

**Comment by RollyPeres** [comment]
Can you share a full repo/gist with your code?

**Comment by areejmayadeh** [comment]
- [ ] 
[authentication_event.txt](https://github.com/felangel/bloc/files/4713337/authentication_event.txt)
[authentication_bloc.txt](https://github.com/felangel/bloc/files/4713340/authentication_bloc.txt)
[authentication_state.txt](https://github.com/felangel/bloc/files/4713341/authentication_state.txt)
[TBHome.txt](https://github.com/felangel/bloc/files/4713355/TBHome.txt)
 @RollyPeres

**Comment by areejmayadeh** [comment]
@RollyPeres 
I was having an issue with provider package I upgraded and the problem of add resolved 
but when I try to call ` authenticationBloc.add(AuthenticationLoggedIn(token: token));`
token: token gives this error : 
This expression has a type of 'void' so its value can't be used.
Try checking to see if you're using the correct API; there might be a function or call that returns void you didn't expect. Also check type parameters and variables which might also be void

**Comment by areejmayadeh** [comment]
@felangel Could you please check my issue, i did it same way as you did in your example flutter_login

**Comment by felangel** [comment]
@areejmayadeh can you please share a link to the full repository rather than individual files?

**Comment by RollyPeres** [comment]
@areejmayadeh

Please remove the red line 👎 and replace it with green line 👍

```diff
onPressed: () {
   BlocProvider.of<AuthenticationBloc>(context)
- .mapEventToState(LoggedOut());
+ .add(LoggedOut());
 },
```

**Comment by areejmayadeh** [comment]
@felangel I send it by email for you

**Comment by rnagar3434** [comment]
i also have same issue

error is

The following assertion was thrown building BlocConsumer<BillingBloc, BillingState>(dirty):
        BlocProvider.of() called with a context that does not contain a Bloc of type BillingBloc.

        No ancestor could be found starting from the context that was passed to BlocProvider.of<BillingBloc>().

        This can happen if the context you used comes from a widget above the BlocProvider.

        The context used was: BlocConsumer<BillingBloc, BillingState>(dirty)
        
The relevant error-causing widget was: 
  BlocConsumer<BillingBloc, BillingState> file:///D:/flutter/za/lib/presentation/features/billing/billing_screen.dart:52:13
When the exception was thrown, this was the stack: 
#0      BlocProvider.of (package:flutter_bloc/src/bloc_provider.dart:106:7)
#1      BlocConsumer.build (package:flutter_bloc/src/bloc_consumer.dart:102:44)
#2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4585:28)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4511:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════


CODE

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:primedeal/config/routes.dart';
import 'package:primedeal/config/theme.dart';
import 'package:primedeal/domain/entities/validator.dart';
import 'package:primedeal/presentation/features/billing/billing.dart';
import 'package:primedeal/presentation/widgets/widgets.dart';
import 'package:primedeal/presentation/features/billing/billing_state.dart';


class BillingScreen extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _BillingScreenState();
  }
}

class _BillingScreenState extends State<BillingScreen> {
  final TextEditingController stateController = TextEditingController();
  final TextEditingController  mobController = TextEditingController();
  final TextEditingController cityController = TextEditingController();
  final TextEditingController zipController = TextEditingController();
  final TextEditingController nameController = TextEditingController();
  final TextEditingController cnameController = TextEditingController();
  final TextEditingController addController = TextEditingController();

  final GlobalKey<OpenFlutterInputFieldState> addKey = GlobalKey();
  final GlobalKey<OpenFlutterInputFieldState> stateKey = GlobalKey();
  final GlobalKey<OpenFlutterInputFieldState> nameKey = GlobalKey();
  final GlobalKey<OpenFlutterInputFieldState> cnameKey = GlobalKey();
  final GlobalKey<OpenFlutterInputFieldState> zipKey = GlobalKey();

  final GlobalKey<OpenFlutterInputFieldState> mobKey = GlobalKey();
  final GlobalKey<OpenFlutterInputFieldState> cityKey = GlobalKey();

  double sizeBetween;

  @override
  Widget build(BuildContext context) {
    var height = MediaQuery.of(context).size.height;
    var width = MediaQuery.of(context).size.width;
    sizeBetween = height / 20;
    return Scaffold(
      appBar: AppBar(
        backgroundColor: AppColors.transparent,
        brightness: Brightness.light,
        elevation: 0,
        iconTheme: IconThemeData(color: AppColors.black),
      ),
      backgroundColor: AppColors.background,
      body: BlocConsumer<BillingBloc, BillingState>(
        listener: (context, state) {
          // on success delete navigator stack and push to home
          if (state is BillingFinishedState) {
            Scaffold.of(context).showSnackBar(

             SnackBar(
              content: Text(' ${state.message}'),
              backgroundColor: Colors.green, // TODO use app colors
              duration: Duration(seconds: 8),),

            );



          }
          // on failure show a snackbar
          if (state is BillingErrorState) {
            Scaffold.of(context).showSnackBar(
              SnackBar(
                content: Text('${state.error}'),
                backgroundColor: Colors.red,
                duration: Duration(seconds: 3),
              ),
            );
          }
        },
        builder: (context, state) {
          // show loading screen while processing
          if (state is BillingProcessingState) {
            return Center(
              child: CircularProgressIndicator(),
            );
          }
          return SingleChildScrollView(
            child: Container(
              height: height * 0.9,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  OpenFlutterBlockHeader(title: 'Sign up', width: width),
                  SizedBox(
                    height: sizeBetween,
                  ),
                  OpenFlutterInputField(
                    key: nameKey,
                    controller: nameController,
                    hint: 'Name',
                    validator: Validator.valueExists,
                  ),
                  OpenFlutterInputField(
                    key: cnameKey,
                    controller: cnameController,
                    hint: 'Company Name (optional)',
                    validator: Validator.valueExists,
                  ),

                  OpenFlutterInputField(
                    key: mobKey,
                    controller: mobController,
                    hint: 'Mobile number',
                    keyboard:TextInputType.number ,
                    validator: Validator.valueExists,
                  ),
                  OpenFlutterInputField(
                    key: addKey,
                    controller: addController,
                    hint: 'Address',
                    validator: Validator.valueExists,
                  ),

                  OpenFlutterInputField(
                    key: cityKey,
                    controller: cityController,
                    hint: 'City',
                    validator: Validator.valueExists,
                  ),

                  OpenFlutterInputField(
                    key: stateKey,
                    controller: stateController,
                    hint: 'State',
                    validator: Validator.validateEmail,
                    keyboard: TextInputType.emailAddress,
                  ),
                  OpenFlutterInputField(
                    key: zipKey,
                    controller: zipController,
                    hint: 'Password',
                    validator: Validator.passwordCorrect,
                    keyboard: TextInputType.visiblePassword,
                    isPassword: true,
                  ),
                  OpenFlutterButton(
                      title: 'Update', onPressed: _validateAndSend),
                  SizedBox(
                    height: sizeBetween,
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }


  void _validateAndSend() {
    BlocProvider.of<BillingBloc>(context).add(
      BillingPressed(
        name:nameController.text.toString(),
        cname:cnameController.text.toString(),
          state:stateController.text.toString(),
          city:cityController.text.toString(),
          add:addController.text.toString(),
          phone:mobController.text.toString(),
          zip:zipController.text.toString(),
 ),
    );
  }

}

**Comment by RollyPeres** [comment]
@rnagar3434  you need to ensure you have provided a `BillingBloc` above your screen via 
```
BlocProvider<BillingBloc>(create: (context) => BillingBloc())
```

**Comment by umidshox99** [comment]
Hi i have same error but i didnt find it  here is my code 


import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:wallpaper_app/data/models/photos_data.dart';
import 'package:wallpaper_app/presentation/blocs/search/search_bloc.dart';
import 'package:wallpaper_app/presentation/widgets/widgets.dart';

class Categories extends StatefulWidget {
  final String name;

  Categories(this.name);

  @override
  _CategoriesState createState() => _CategoriesState();
}

class _CategoriesState extends State<Categories> {
  PhotosData data = PhotosData();
  TextEditingController controller = TextEditingController();
  SearchBloc bloc;

  @override
  void initState() {
    controller.text = widget.name;
    bloc = BlocProvider.of<SearchBloc>(context)..add(SearchEvent(widget.name));
    super.initState();
  }

  @override
  void deactivate() {
    super.deactivate();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        centerTitle: true,
        title: brandName(),
        elevation: 0.0,
      ),
      body: SingleChildScrollView(
        child: Container(
          child: BlocBuilder<SearchBloc, SearchState>(
            cubit: bloc,
            builder: (BuildContext context, state) {
              if (state is LoadedSearchState)
                return getCard(state.list ?? [], context);
              else if (state is ErrorSearchState)
                return Center(
                  child: Text("error"),
                );
              else
                return CircularProgressIndicator();
            },
          ),
        ),
      ),
    );
  }
}

**Comment by RollyPeres** [comment]
Hi @umidshox99 👋

You need to actually provide your bloc above your `Categories` widget.

```
BlocProvider<SearchBloc>(create: (_) => SearchBloc(), child: ...);
```

**Comment by umidshox99** [comment]
@RollyPeres Hi thank u for your answer but  I use MultiBlocProvider there is my code
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'WallpaperHub',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: Colors.white,
      ),
      home: MultiBlocProvider(providers: [
        BlocProvider<SearchBloc>(
            create: (context) =>
                SearchBloc(PhotosRepositoryImpl(APIProvider()))),
        BlocProvider<FetchTrendsBloc>(
            create: (context) =>
                FetchTrendsBloc(PhotosRepositoryImpl(APIProvider()))),
      ], child: Home()),
    );
  }
}

**Comment by umidshox99** [comment]
@RollyPeres  Hello thank u 4 r answer but I use MultiBlocProvider there is my code 
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'WallpaperHub',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: Colors.white,
      ),
      home: MultiBlocProvider(providers: [
        BlocProvider<SearchBloc>(
            create: (context) =>
                SearchBloc(PhotosRepositoryImpl(APIProvider()))),
        BlocProvider<FetchTrendsBloc>(
            create: (context) =>
                FetchTrendsBloc(PhotosRepositoryImpl(APIProvider()))),
      ], child: Home()),
    );
  }
}

**Comment by RollyPeres** [comment]
You might be doing some navigation, so try and lift up your `MultiBlocProvider` above `MaterialApp` to make sure you have access to your bloc  from any route.

**Comment by umidshox99** [comment]
@RollyPeres  thank u bro it works erfectly
