### ISSUE TITLE
Question: Could I use pageController in bloc,not in UI layer?

### ISSUE THREAD

**Issue by huang12zheng** [felangel/bloc#499]
Describe:
---
question1:
I code a widget about menu bar which could control page.So, I use a function 
```dart
pageController.animateToPage(...)
```

But it looks like that I should use `animateToPage` at UI layer by #18 . I am at loss.

Moreover
---
I also would code page which could control menu.So, I use 
```dart
onPageChanged
```

some code below:
---

mapEventToState in Bloc is like :
```dart
Stream<MenuState> mapEventToState(
    MenuEvent event,
  ) async* {
    if (event is SelectButton) {
      yield MenuChanging(selectId: event.id);
      if (pageController != null) await pageController.animateToPage(event.id,
          duration: Duration(milliseconds: 500), curve: Curves.decelerate);
      // changing end;
      int preSelectId = selectId;
      selectId = event.id;
      if (preSelectId != selectId) yield MenuChanged(preSelectId: preSelectId,selectId: selectId,other: this.hashCode);
    }
  }
```
construct of menuBloc is like:
```dart
MenuBloc({this.pageController});
```
PageView is like:
```dart
PageView(
          controller: pageController,
          onPageChanged: (i) {
            final bloc = BlocProvider.of<MenuBloc>(context);
            if (bloc.currentState is! MenuChanging) {
              print('currentState:  ** ${bloc.currentState}');
              bloc.dispatch(SelectButton(i));
            }
          },
          children: <Widget>[
```

------------------------------------------------------------------

**Comment by huang12zheng** [comment]
Other Info:
---
If I use `animateToPage` in UI layer like below:
```dart
BlocListener<MenuBloc, MenuState>(listener: (context, state) async {
      if (state is MenuChanging) {
        await pageController.animateToPage(state.selectId,
           duration: Duration(milliseconds: 500), curve: Curves.decelerate);
        
      }
    }
```
When I call a SelectButton, it would call SelectButton two time. due to
```dart
onPageChanged: (i)
```
call a SelectButton.
For example:
I am at page 0, being Select to page 3,  // SelectButton(3)
It is expected that animateToPage would jump to page1,page2,page3.But When jump to page1, it call SelectButton(1). Then it stop at page 1.
```dart
if (state is MenuChanging) {
```
it is no working,due to  MenuBloc.mapEventToState wouldn't await `animateToPage` being over

**Comment by felangel** [comment]
Hi @huang12zheng 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which illustrates the problem you're running into? Also, in general you should only use blocs for business logic. If you are simply trying to use a `PageController` to control a menu then you probably don't need to use a bloc since there is no business logic involved.

Let me know if that helps 👍

**Comment by nehal076** [comment]
Why was this closed? I have the same doubt. How can I use PageController with a bloc
