### ISSUE TITLE
BlocProvider can not be used in children's children

### ISSUE THREAD

**Issue by Liuzhiyang94** [felangel/bloc#500]
`
BlocProvider.of<BlocA>(context)
`
Its a common way to get a bloc instance of parent's BlocA.

But if i want to use in this way.
```
 BlocProvider<BlocA>(
      child: Child1(),
      builder: (context){
        return _blocAInstance;
      },
    )

class Child1 extends statelesswidget{
Container(child: Child2());
}

class Child2 extends statelesswidget{
@override
build(context){
var _blocAInstance = BlocProvider.of<BlocA>(context);
}
}
```

This will throw Exception. 

Is there anyway to let `Child2` get the top BlocA instance?

**Comment by felangel** [comment]
Hi @Liuzhiyang94 👋 
Thanks for opening an issue!

This should work just fine. Can you please provide a link to a sample project which illustrates the problem you’re having? Thanks 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with a sample app and I'm more than happy to help 👍

**Comment by Liuzhiyang94** [comment]
@felangel  Thanks for reply. I found a bug in my code, `BlocProvider.of` works fine . Thanks.
