### ISSUE TITLE
Is there some kind of schedule / roadmap?

### ISSUE THREAD

**Issue by djuelg** [felangel/bloc#505]
Is there some kind of schedule / roadmap?

I wondered, since there is no stable 1.X release, yet. Is there one coming soon?
What is currently missing in the lib, so that it is currently not considered stable?

Greetings,
Domi

**Comment by felangel** [comment]
Hi @djuelg 👋 
Thanks for opening an issue!

I'm planning to release v1.0.0 very soon. I haven't been great about a roadmap but I think the main thing missing is dev tools which are currently in progress. I'll try put together a formal roadmap over the next few days 👍

**Comment by felangel** [comment]
**Update**: I'm going to start putting together a roadmap on the [wiki](https://github.com/felangel/bloc/wiki/Roadmap) over the next few days.

**Comment by zengzhengrong** [comment]
I love this bloc, I'm looking forward to stable version ,It‘s frequently upgrade :)

**Comment by felangel** [comment]
v1.0.0 is here 🎉and the roadmap is still in progress 👍

**Comment by felangel** [comment]
Closing for now since 1.0.0 is out and there is a `Roadmap` which I will keep adding to 👍

**Comment by maurobotta** [comment]
@felangel 
Are Dev tools available, now ?

**Comment by felangel** [comment]
@maurobotta they are currently still a WIP. You can keep an eye on #1423 for updates 👍
