### ISSUE TITLE
[Discussion : Can we use Bloc as a singleton so it is easy to share across blocs]

### ISSUE THREAD

**Issue by imaffe** [felangel/bloc#507]
1. Why can't we implement BLoC as a singleton so it can be accessed from everywhere in the app. Sometimes I found BLoC provider is a bit awkward when navigating to a new page.

2. Also, I want to know what is the proper way to solve cyclic reference. For example, blocA wants to send event to blocB and blocB wants to send to blocA as well. In such situation, do we have a general design for solving all these ?

Thanks so much, I'd be happy if there were already discussion about this : )

**Comment by bigworld12** [comment]
1. you can implement it as a singleton using bloc provider, just place it as a parent to MaterialApp widget
2. bloc A can dispatch an event to bloc B (carrying whatever data you want) , and bloc B can dispatch an event to bloc A (carrying whatever data you want)

**Comment by felangel** [comment]
Hi @imaffe 👋 
Thanks for opening an issue!

As @bigworld12 pointed out you can use `BlocProvider` to provide a global instance of a bloc by providing the bloc above `MaterialApp`.

```dart
BlocProvider(
  builder: (context) => MyGlobalBloc(),
  child: MaterialApp(...),
)
```

Regarding circular dependencies, in general you want to avoid them. If you provide additional information around why you need a circular dependency between two blocs I'd be more than happy to suggest alternative approaches 👍 

Hope that helps and thanks @bigworld12!

**Comment by MauScheff** [comment]
@felangel How much impact on performance does injecting an app-wide bloc has vs only on the branch that uses it?
