### ISSUE TITLE
Is there any way to get access to other state in mapEventToState method?

### ISSUE THREAD

**Issue by Feelthewind** [felangel/bloc#51]
Hi, I wonder if it's possible to access state of one bloc from another.
Redux has getState() and redux-thunk to get this to work. Thanks.

**Comment by felangel** [comment]
@Feelthewind can you describe why you need to do this so I can better understand the use case?

Bloc has a property called `state` which returns a stream of states and it also has a `currentState`.

You can inject a bloc into another bloc if you really want to be able to do this but I can’t recommend any particular solution without more information about what you’re trying to accomplish.

**Comment by Feelthewind** [comment]
> @Feelthewind can you describe why you need to do this so I can better understand the use case?
> 
> Bloc has a property called `state` which returns a stream of states and it also has a `currentState`.
> 
> You can inject a bloc into another bloc if you really want to be able to do this but I can’t recommend any particular solution without more information about what you’re trying to accomplish.

Let's say i want to make an http request in one bloc using some state of another bloc. Actually i just wondered if it's possible like redux for now. Thank you for the reply.

**Comment by felangel** [comment]
No problem 👍
