### ISSUE TITLE
Cancel current operation on every event received. A generic approach.

### ISSUE THREAD

**Issue by bernaferrari** [felangel/bloc#517]
Hi, I'm having a hard time trying to figure out how to cancel a stream when there is a new input/value changed/state changed. I understand this is a problem (probably) for dart.async, not bloc. But since I'm using blocs and blocs use them.. I ran into so many issues that I thought this might be a somehow frequent scenario and whatever you answer can help other people in the same situation in the `future`. 

For example, I have a TextField that dispatches a bloc event for every input. Consider that bloc/repository takes some one second to deliver the result. If I type 3 letters, it will update the first, then the second, then the third, really laggy. 3 seconds in total. I just want to stop whatever it is doing and focus on the current task. I wanted this to complete in ~1 or <2 seconds. This is kind of similar to [how you deal with Ticker](https://github.com/felangel/bloc/blob/17c7048ad26ffb4332ccc7b584db0014599e6a92/examples/flutter_bloc_with_stream/lib/bloc/ticker_bloc.dart#L18), always cancelling before setting it again. I am dealing, however, with anything.. any future, so I need a generic approach. I don't know what to do. I don't know what is the 'official' approach. I don't even understand if this is something trivial or no one ever tried to do it, because the amount of resources is minimum. 

I tried [this solution from StackOverflow](https://stackoverflow.com/a/54905898/4418073) but I can't use `yield` inside `whenComplete` (or any function), so I don't know how to make it work.

Any ideas? The image below is my situation, the closest I've got.

![image](https://user-images.githubusercontent.com/351125/64916178-00f5ae80-d74f-11e9-8443-30d434c435f1.png)

**Comment by felangel** [comment]
Hi @bernaferrari 👋 
Thanks for opening an issue!

Have you tried overriding the `transformEvents` to force the bloc to use `switchMap`? This will tell the bloc to stop processing old events whenever a new event is received.

```dart
@override
Stream<State> transformEvents(events, next) {
  return (events as Observable<Event>).switchMap(next);
}
```

Let me know if that helps 👍

**Comment by bernaferrari** [comment]
Wow, that is fantastic. I completely missed this operator. Solved my issue. Even simpler than I imagined. Thanks a lot!! I've been using bloc since your BMW presentation and I'm loving it!

**Comment by firatcetiner** [comment]
> Hi @bernaferrari 👋
> Thanks for opening an issue!
> 
> Have you tried overriding `transformEvents` to force the bloc to use `switchMap`? This will tell the bloc to stop processing old events whenever a new event is received.
> 
> ```dart
> @override
> Stream<State> transformEvents(events, next) {
>   return (events as Observable<Event>).switchMap(next);
> }
> ```
> 
> or with rxdart >=0.23.0
> 
> ```dart
> @override
> Stream<State> transformEvents(events, next) {
>   return events.switchMap(next);
> }
> ```
> 
> Let me know if that helps 👍

Just looking for this

> Hi @bernaferrari 👋
> Thanks for opening an issue!
> 
> Have you tried overriding `transformEvents` to force the bloc to use `switchMap`? This will tell the bloc to stop processing old events whenever a new event is received.
> 
> ```dart
> @override
> Stream<State> transformEvents(events, next) {
>   return (events as Observable<Event>).switchMap(next);
> }
> ```
> 
> or with rxdart >=0.23.0
> 
> ```dart
> @override
> Stream<State> transformEvents(events, next) {
>   return events.switchMap(next);
> }
> ```
> 
> Let me know if that helps 👍

This is a good approach but it does not seem to work properly. In my case the events are still mapped to relevant states. The transformEvents(events, next) method is called before mapping the next event to the state, am I correct?

**Comment by felangel** [comment]
Hi @firatcetiner yup, that's correct. Can you provide a link to a sample app which illustrates the problem you're having?

**Comment by firatcetiner** [comment]
I created a small example, turns out it actually works as expected (big oof) 😄 .  I can't reproduce the issue on this example but it exists in my "main" app, which I can't show anything from it. Anyway, here is the sample: 
https://github.com/firatcetiner/bloc_sample

I will search for the anomaly that cause this bug on my "main" application in case of me doing something wrong. I will definitely write another comment to this issue if it isn't solved.

**Comment by majdkz97** [comment]
> Hi @bernaferrari 👋
> Thanks for opening an issue!
> 
> Have you tried overriding `transformEvents` to force the bloc to use `switchMap`? This will tell the bloc to stop processing old events whenever a new event is received.
> 
> ```dart
> @override
> Stream<State> transformEvents(events, next) {
>   return (events as Observable<Event>).switchMap(next);
> }
> ```
> 
> or with rxdart >=0.23.0
> 
> ```dart
> @override
> Stream<State> transformEvents(events, next) {
>   return events.switchMap(next);
> }
> ```
> 
> Let me know if that helps 👍

Thank's a lot, that's save my life

**Comment by cuongloveit** [comment]
Hi @felangel 

```dart
@override
Stream<Transition<Event, State>> transformEvents(events, transitionFn) {
  return events.switchMap(transitionFn);
}
```
if override `transformEvents()`, how I can use switchMap to a special event?

**Comment by RollyPeres** [comment]
Hi @cuongloveit 👋

Please have a look at this https://github.com/felangel/bloc/issues/1107#issuecomment-621176290 for a detailed example.

**Comment by cuongloveit** [comment]
Thank @RollyPeres . It's work perfectly :D

**Comment by nguyencse** [comment]
![image](https://user-images.githubusercontent.com/23445876/135704337-d281509a-752b-4e2a-abf0-b750630bf058.png)
I cannot use switchMap on rxdart 0.18.0 and bloc 6.1.3.
It gives me error: `type '_BroadcastStream<CheckoutEvent>' is not a subtype of type 'Observable<CheckoutEvent>' in type cast`
Any idea for this case? Thanks all :(
