### ISSUE TITLE
Can I Use Multiple BlocBuilder in same class 

### ISSUE THREAD

**Issue by gtxgat** [felangel/bloc#525]
**Describe the bug**
I used `Flutter_bloc for authentication with firebaseAuth `
. And now I used `Flutter_bloc for Changing Theme at run-time` 
and these two blocBuilder exists in main class as shown bellow:

Code:
```
  @override
  Widget build(BuildContext context) {
    return BlocBuilder(
      bloc: changeThemeBloc,
      builder: (BuildContext context, ChangeThemeState state) {
        return MaterialApp(
          theme: state.themeData,
          home: BlocBuilder<AuthenticationBloc, AuthenticationState>(
            builder: (context, state) {
              if (state is Uninitialized) {
                return SplashScreen();
              }
              if (state is Unauthenticated) {
                return LoginScreen(userRepository: _userRepository);
              }
              if (state is Authenticated) {
                return HomeBase(name: state.displayName);
              }
              return null;
            },
          ),
        );
      },
    );
  }
```

As shown I used bloc inside another bloc is there any problem ?
And thanks for your efforts.

**Comment by bigworld12** [comment]
it's ok I think, since they are different streams, but be aware that when the Theme bloc changes state, it will rebuild the entire widget tree (which is the intended behavior I guess? )

**Comment by felangel** [comment]
Hi @gtxgat 👋 
Thanks for opening an issue!

As @bigworld12 mentioned, it's perfectly fine to nest `BlocBuilders` so long as you are intending the child of each `BlocBuilder` to re-render on each state change 👍

**Comment by georgek1991** [comment]
Any update on this?

**Comment by felangel** [comment]
> @felangel Any update on this?

What do you mean?

**Comment by georgek1991** [comment]
Any chance that the library might include Multiple BlocBuilder or is the nested BlocBuilder still the way to go ahead?

**Comment by felangel** [comment]
> Any chance that the library might include Multiple BlocBuilder or is the nested BlocBuilder still the way to go ahead? @felangel

You can use `context.watch` to handle rebuilding in response to multiple bloc states:

```dart
@override
Widget build(BuildContext context) {
  final stateA = context.watch<BlocA>().state;
  final stateB = context.watch<BlocB>().state;

  // Return widget based on stateA and stateB
}
```

Hope that helps 👍

**Comment by georgek1991** [comment]
> **Describe the bug**
> I used `Flutter_bloc for authentication with firebaseAuth `
> . And now I used `Flutter_bloc for Changing Theme at run-time`
> and these two blocBuilder exists in main class as shown bellow:
> 
> Code:
> 
> ```
>   @override
>   Widget build(BuildContext context) {
>     return BlocBuilder(
>       bloc: changeThemeBloc,
>       builder: (BuildContext context, ChangeThemeState state) {
>         return MaterialApp(
>           theme: state.themeData,
>           home: BlocBuilder<AuthenticationBloc, AuthenticationState>(
>             builder: (context, state) {
>               if (state is Uninitialized) {
>                 return SplashScreen();
>               }
>               if (state is Unauthenticated) {
>                 return LoginScreen(userRepository: _userRepository);
>               }
>               if (state is Authenticated) {
>                 return HomeBase(name: state.displayName);
>               }
>               return null;
>             },
>           ),
>         );
>       },
>     );
>   }
> ```
> 
> As shown I used bloc inside another bloc is there any problem ?
> And thanks for your efforts.

@felangel can you please show how it will work in above example?

**Comment by felangel** [comment]
```dart
@override
Widget build(BuildContext context) {
  final theme =
      context.select((ChangeThemeBloc bloc) => bloc.state.themeData);
  final authenticationState = context.watch<AuthenticationBloc>().state;
  final home = authenticationState is Authenticated
      ? HomeBase(name: state.displayName)
      : state is Unauthenticated
          ? LoginScreen(userRepository: _userRepository)
          : SplashScreen();

  return MaterialApp(theme: theme, home: home);
}
```

**Comment by georgek1991** [comment]
> @georgek1991 sure 👍 
> 
> ```dart
> @override
> Widget build(BuildContext context) {
>   final theme = context.select((ChangeThemeBloc bloc) => bloc.state.themeData);
>   return MaterialApp(
>     theme: theme,
>     home: Builder(
>       builder: (context) {
>         final authenticationState = context.watch<AuthenticationBloc>().state;
>         if (state is Authenticated) {
>           return HomeBase(name: state.displayName);
>         }
>         if (state is Unauthenticated) {
>           return LoginScreen(userRepository: _userRepository);
>         }
>         return SplashScreen();
>       },
>     ),
>   );
> }
> ```
> 
> Another option is:
> 
> ```dart
> @override
> Widget build(BuildContext context) {
>   final theme = context.select((ChangeThemeBloc bloc) => bloc.state.themeData);
>   final authenticationState = context.watch<AuthenticationBloc>().state;
>   final home = authenticationState is Authenticated
>       ? HomeBase(name: state.displayName)
>       : state is Unauthenticated
>           ? LoginScreen(userRepository: _userRepository)
>           : SplashScreen();
> 
>   return MaterialApp(theme: theme, home: home);
> }
> ```

Thank you @felangel

**Comment by georgek1991** [comment]
> @georgek1991 sure 👍
> 
> ```dart
> @override
> Widget build(BuildContext context) {
>   final theme = context.select((ChangeThemeBloc bloc) => bloc.state.themeData);
>   return MaterialApp(
>     theme: theme,
>     home: Builder(
>       builder: (context) {
>         final authenticationState = context.watch<AuthenticationBloc>().state;
>         if (state is Authenticated) {
>           return HomeBase(name: state.displayName);
>         }
>         if (state is Unauthenticated) {
>           return LoginScreen(userRepository: _userRepository);
>         }
>         return SplashScreen();
>       },
>     ),
>   );
> }
> ```
> 
> Another option is:
> 
> ```dart
> @override
> Widget build(BuildContext context) {
>   final theme = context.select((ChangeThemeBloc bloc) => bloc.state.themeData);
>   final authenticationState = context.watch<AuthenticationBloc>().state;
>   final home = authenticationState is Authenticated
>       ? HomeBase(name: state.displayName)
>       : state is Unauthenticated
>           ? LoginScreen(userRepository: _userRepository)
>           : SplashScreen();
> 
>   return MaterialApp(theme: theme, home: home);
> }
> ```

@felangel I tried this method and it works, But now when I try to logout from the app, it does not go to the sign in page. In logout I am making the state unauthorized. Then I tried the official doc for login and there I saw using navigator and pushuntil method. But somehow I am not able to use that in the above example. Something I am missing?

Logout function is inside my profile page which is opened as follows from my home page:

```
Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => ProfilePage(),
                  fullscreenDialog: true,
                ),
              );
```

Can you please help.

**Comment by dittombek** [comment]
Please take a look of this flutter bloc documents [https://bloclibrary.dev/#/flutterbloccoreconcepts?id=usage-2](url)

For safe implementation of multiple blocbuilder, use Builder and context.watch.

```
@override
Widget build(BuildContext context) {
  return Builder(
    builder: (context) {
      final stateA = context.watch<BlocA>().state;
      final stateB = context.watch<BlocB>().state;
      final stateC = context.watch<BlocC>().state;

      return const Text('Hello World');
    },
  );
}
```
