### ISSUE TITLE
Complete State reloading when using Flutter Navigation

### ISSUE THREAD

**Issue by reignierleo** [felangel/bloc#536]
Hey everyone;
I hope anyone can help me, my problem is the following:
I build an Application based on the flutter_bloc package. 
My "TOP State" is the authentification State. And I then have multiple States under this one. When I am using the Flutter Navigation feature anywhere in the app, so I am calling:
```
Navigator.push(
                    context,
                    MaterialPageRoute(
                        builder: (context) => SomeNewScreen()));
              },
            ),
```
So I am pushing a new route on the top of the stack, the complete Tree under the authentification State (The Top state) is rebuilding. This causes pretty much the complete App to rebuild.  The same happens when I remove the page from the stack with "Navigator.pop(context)".
This happens also when the Screen to which I navigate is not based on Blocs, and It really happens each time I add or remove a screen from the stack.
What could be the Issue?

Thank you very much in advance for your help

**Comment by bigworld12** [comment]
are you using BlocBuilder at the top of the tree?

**Comment by reignierleo** [comment]
Yes I am, at least the one for the Authentification State.

**Comment by felangel** [comment]
Hi @reignierleo 👋 
Thanks for opening an issue!

Can you please provide a link to a sample app which illustrates the problem you're having as well as what you would like to happen. It will make it much easier for us to help 👍 

Thanks!

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional information and I'm happy to continue the conversation 👍
