### ISSUE TITLE
type '_TypeError' is not a subtype of type 'Exception'

### ISSUE THREAD

**Issue by mpivchev** [felangel/bloc#541]
I have an Error being thrown somewhere in my code, however it seems like it's getting handled by Bloc which only works with Exceptions and not Errors, so I can't see the Error stacktrace.

![image](https://user-images.githubusercontent.com/6960329/65814277-ee17bb00-e1df-11e9-9f73-0d6787f294b9.png)

**Comment by felangel** [comment]
Hi @mpivchev 👋 
Thanks for opening an issue!

I tried reproducing this but was unsuccessful. Can you please provide the link to a sample app which reproduces the problem you're having?

Thanks!

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional information/reproduction steps and I'm happy to continue the conversation 👍
