### ISSUE TITLE
What design patter BLoC abstracts ?

### ISSUE THREAD

**Issue by youssef-md** [felangel/bloc#543]
Good afternoon, I'm taking a class in Architecture and Software Design and we are building an app with Flutter and we decided to use BLoC for the rich and nicely done structure. When I was studying it I realized that the concepts and some of the code written is very similar to Flux pattern. 
For this class we have to use some of the known design patterns, so since we are using BLoC I wanted to know if there is a design pattern that BLoC uses behind the scenes or BLoC would be a new design pattern, or both.
Thank you for your attention :heart:

**Comment by bigworld12** [comment]
bloc, mvvm, flux, and many more, are patterns that separate ui from business logic.
so there is bound to be similarities between them, but each has its own way of doing things

**Comment by youssef-md** [comment]
So BLoC is pattern of its own or is an abstraction of some of the known design patterns, or both?
btw, thanks for the answer

**Comment by bigworld12** [comment]
if i had to pick one, i would say bloc is an implementation of MVVM

**Comment by felangel** [comment]
Hi @youssef-md 👋 
Thanks for opening an issue!

The bloc library is an interpretation of the BLoC design pattern and shares characteristics with MVVM, Flux, and Redux 👍
