### ISSUE TITLE
ListView animations with BlocBuilder

### ISSUE THREAD

**Issue by guybashan** [felangel/bloc#546]
Hi Alex,
I am not sure if this is a feature directly related with flutter_bloc or there is some other way of achieving it: is there any way showing add/remove animations for ListView used with BlocBuilder?

Thanks,
Guy

**Comment by felangel** [comment]
Hi @guybashan 👋 
Thanks for opening an issue!

I don't think this question is bloc-specific. You can check out this [medium article](https://medium.com/@wiltonrcn/flutter-animation-in-listview-207070e58b6) on one way to achieve this. The only thing you'd need to do to wire up the animation to a bloc is use `BlocListener` to listen for state changes and the interact with your `AnimationController` accordingly.

Hope that helps 👍
