### ISSUE TITLE
TabBar sample

### ISSUE THREAD

**Issue by prasant10050** [felangel/bloc#549]
How can we do handle state management with tabBar in flutter?Please upload a simple basic example where there are two tabs one tab showing seven days and seconds tab is showing 1 to 30 date's value,
it's urgent for my production app

**Comment by felangel** [comment]
Hi @prasant10050 👋 
Thanks for opening an issue!

Can you please provide some more information/example of what you're trying to build? I'm not sure why you need a bloc for a TabBar. You can have a bloc manage the state of each tab and wrap the tab in `BlocProvider` like so:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

void main() {
  runApp(TabBarSample());
}

class TabBarSample extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 2,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(icon: Icon(Icons.directions_car)),
                Tab(icon: Icon(Icons.directions_transit)),
              ],
            ),
            title: Text('Tabs Demo'),
          ),
          body: TabBarView(
            children: [
              BlocProvider(
                builder: (context) => BlocA(),
                child: TabA(),
              ),
              BlocProvider(
                builder: (context) => BlocB(),
                child: TabB(),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```

Hope that helps 👍

**Comment by prasant10050** [comment]
Hi,
First of all thank you that you have given me the reply. I liked your
package very much and I am using it but sometimes I have been facing issue
like this issue and am using your package at my own risk in production app
of company,
 Now I test that only what you have answered can solve my issue.i will
reply you.

Again thank you.

**Comment by prasant10050** [comment]
HI,
In your example i have added on icon button on app bar which call a dialog
box where I go from a dialog box with a radio button to another screen, and
then come again from that screen Then the dialog box is not opening again.
I am opening the dialog box with Schedule Binding and all naviagtion and
pop method is called under Schedule Binding.Please fix my issue.

**Comment by felangel** [comment]
@prasant10050 can you please share a the complete code which isn’t working for you?

**Comment by prasant10050** [comment]
I haven't share the code because it's completely against company protocol,
I have only share the situation what am I facing

**Comment by felangel** [comment]
@prasant10050 can you create a simple example? I don't need to see the company code, I just want to see a super app which illustrates the same problem you're facing. Thanks!

**Comment by prasant10050** [comment]
Sure!

**Comment by prasant10050** [comment]
The first screen has two, and each tab has a list of data.The list of data has two parts, the first header and the second its child inside that header,There is an add and delete button in the header section, a dialog box opens upon pressing the add button,The dialog box has two or three testfields and a submit button, after pressing the submit button, the data of the text field becomes the child of the header.You can also take a text field.But the issue is that the child is created, but the screen does not show immediate reflection, when I come from the second tab to the first tab, the result is visible.
In the same way, if you press the delete button from the header section, the child does not see any effect,
But if I work in a single screen, the effect of add and delete operation is seen, but the same screen not effect in tab bar view.I  will thank you very much if you give me the solution for my issue

**Comment by felangel** [comment]
@prasant10050 thanks for the explanation but can you please create a sample flutter app that reproduces the issue and share the link with me? It's very hard to help without that.

**Comment by fluttercorner** [comment]
[How to Create TabBar in Flutter Complete Guide To Make TabBar](https://fluttercorner.com/how-to-create-tabbar-in-flutter-complete-guide-to-make-tabbar/)

**Comment by gutisalex** [comment]
I might have a case it would be convenient but I am not sure if I need a cubit/bloc for that.. I have a TabBar and some views. Inside of a view somewhere in the depth of the widget tree I have a button and want to change the currentIndex of the tabBar. Either I would use a cubit to save the currentIndex or I could probably use a GlobalKey for that?! But what if I want to change tab styles according to the currentIndex:

```dart
borderRadius: BorderRadius.only(
                topLeft: Radius.circular(_tabController.index == 0 ? 9 : 0),
                topRight: Radius.circular(_tabController.index == 3 ? 9 : 0),
              ),
```

What do you think?

**Comment by whysetiawan** [comment]
Hi @felangel i wonder how can i use the same bloc with the `TabBar` not the `TabBarView`. i have problem when use BlocProvider at the top with of `TabBar` and cannot use it inside the `TabBarView`. It said that the `no bloc/cubit found in the context`

**Comment by xErik** [comment]
The example above helped me figuring out using **TabBarView** and **Bloc**.

It should be noted that the child-widget accesses the returned state-value like this

```
class TabA extends StatelessWidget {
  const TabA({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    var state = context.read<BlocA>().state;
    var payload = state.your_payload;
  }
}
```
