### ISSUE TITLE
[Feature Request] Add eventStream to bloc

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [felangel/bloc#550]
There are many potential uses for this. If I'm being lazy and need to describe one, let me know :D

**Comment by felangel** [comment]
Hey @ThinkDigitalSoftware 👋 
Thanks for opening an issue!

This was intentionally removed from bloc. You can check out https://github.com/felangel/bloc/issues/326 for more details.

Closing for now but feel free to comment with additional info if you feel strongly about adding it back 👍
