### ISSUE TITLE
New Bloc Logo

### ISSUE THREAD

**Issue by felangel** [felangel/bloc#551]
If there are any designers out there who are willing to put out some proposals for a shiny new bloc logo it would be much appreciated!

**Comment by Sach97** [comment]
What do you think of that [one](https://app.brandmark.io/v2/?name=logo-icon-replacement&iconId=2498305&iconColor%5Bhex%5D=%23184473&title=Bloc&tagline=Predictable+state+management+library&nthChar=2&titleFamily=Phenomena&titleVariant=200&taglineFamily=Fira+Sans+Condensed&taglineVariant=400&titleScale=4.232481069007509&taglineScale=0.75&titleColor%5Bhex%5D=%23ffffff&taglineColor%5Bhex%5D=%23ffffff&backgroundColor%5Bhex%5D=%23fc5a4a&titleLetterSpace=5&titleLineSpace=1.1&taglineLetterSpace=0&taglineLineSpace=1.1&iconScale=1&score=2.0859857762526&autoScale=false&hideIcon=false&palette%5B%5D=%23fc5a4a&palette%5B%5D=%23ffffff&palette%5B%5D=%23184473&palette%5B%5D=%235a9fea&palette%5B%5D=%235a9fea&keywords%5B%5D=Dart&keywords%5B%5D=Flutter&keywords%5B%5D=state+management&keywords%5B%5D=streams&color_styles%5B%5D=vibrant&color_styles%5B%5D=default)? I could vectorize it

**Comment by jorgecoca** [comment]
@felangel do you have a vision for it? To me, `bloc` inspires building blocks, like Legos or something, and since this library is a fundamental piece of your puzzle (aka, your app), I think something going in that direction might be interesting...

**Comment by Sach97** [comment]
@jorgecoca [something](https://www.figma.com/file/bHwrTnNSaq2lzcgBik4AxD/Untitled?node-id=1%3A2) along those lines ?

**Comment by felangel** [comment]
@jorgecoca I think something along those lines makes sense but I'm also open to anything. Ideally, I was envisioning that various people could submit their proposals and then I could pick the top 3 and have the community vote.

**Comment by shamnex** [comment]
I'll see what I can come up with during the week...

**Comment by lsaudon** [comment]
I was thinking about the origami of a cube with the colors of flutter but I'm not good at drawing.

![image](https://user-images.githubusercontent.com/25029876/66398484-1e303c80-e9de-11e9-9de3-94904e01e63a.png)

**Comment by tenhobi** [comment]
This is just a concept, what about puzzles? Someone could do a more effort, make it look cool with colors and overall feeling:

![image](https://user-images.githubusercontent.com/5287596/66472455-90ac2580-ea8d-11e9-8c9a-c70014ba63e4.png)

or


![image](https://user-images.githubusercontent.com/5287596/66472475-999cf700-ea8d-11e9-9178-517f0dcce047.png)

**Comment by shamnex** [comment]
@tenhobi @lsaudon I'll work with both your concepts plus the ideas I have in mind and come up with something tomorrow.

**Comment by shamnex** [comment]
Hello Guy! Sorry for the latesome reply. I just published my first Flutter App so things were a bit hectic at the office.
Here are some ideas I was able to come up with.
I'll still explore some more options during the week.

![Group 1 copy 2](https://user-images.githubusercontent.com/20919546/66818760-ba55c880-ef35-11e9-9f9f-52a1ef4325b4.png)
![Group 1 copy 3](https://user-images.githubusercontent.com/20919546/66818764-bb86f580-ef35-11e9-8741-bec681392c71.png)
![Group 1 copy 4](https://user-images.githubusercontent.com/20919546/66818765-bb86f580-ef35-11e9-8256-1e52ef82dced.png)
![Group 1 copy 5](https://user-images.githubusercontent.com/20919546/66818766-bc1f8c00-ef35-11e9-9c6e-dd5f7e8e5ef0.png)
![Group 1 copy 6](https://user-images.githubusercontent.com/20919546/66818768-bc1f8c00-ef35-11e9-8d7a-796754c64ed0.png)
![Group 1 copy 7](https://user-images.githubusercontent.com/20919546/66818769-bc1f8c00-ef35-11e9-8862-3de99952b4d0.png)
![Group 1 copy](https://user-images.githubusercontent.com/20919546/66818771-bcb82280-ef35-11e9-95be-8f5e76bc5095.png)
![Group 1](https://user-images.githubusercontent.com/20919546/66818772-bcb82280-ef35-11e9-8e4e-69afe0bafaea.png)
![Group 2](https://user-images.githubusercontent.com/20919546/66818774-bd50b900-ef35-11e9-999c-9599aeff8334.png)

**Comment by lsaudon** [comment]
I like ![image](https://user-images.githubusercontent.com/25029876/66831115-41676880-ef57-11e9-9ae5-ee5c333ff8d9.png)

**Comment by tenhobi** [comment]
1st, 2nd are super cool!

**Comment by felangel** [comment]
@shamnex thanks for the submission! I'm thinking of holding off on the new logo for now because there hasn't been a lot of activity around it and for the most part everyone I talked to has been pretty happy with the existing logo. If you disagree feel free to comment and we can explore the options but I'd rather hold off an avoid making more jarring changes for a bit since a lot has changed with the library over the past few weeks.

Thanks everyone!
