### ISSUE TITLE
Question: Is it well maintained? Good for production?

### ISSUE THREAD

**Issue by maheshkumar2150** [felangel/bloc#556]
I saw the documentation. I am currently not using any dependencies on my app.
But this bloc is really awesome and i want to use it on my app.

But, How long will it be supported and maintained?
Is it really good idea to convert my app with this bloc pattern?

If the developer suddenly stopped working on this project, then i have to rewrite everything again to custom bloc.

Please suggest your opinions

**Comment by jorgecoca** [comment]
Hey @maheshkumar2150 thanks for the question. I guess @felangel can give you more details about this, but I will do also my best:

@felangel and myself work for BMW, and we are the Flutter leads of the BMW practices. We use this library in our BMW applications, and as you can see from the documentation, the answers in issues, and the different improvements, this project is actively maintained and kept up to date.

We are incredibly happy at BMW with Bloc, and our goal is to keep making it even better. @felangel  is working on a roadmap (coming soon https://github.com/felangel/bloc/wiki/Roadmap) but plans include plenty of things, like developer tools and things like that...

So if you are worry about support, I'd say you won't have any problems with this project. 

And if you have any questions, we are more than happy to help and provide support ;)

**Comment by felangel** [comment]
Hi @maheshkumar2150 👋 

As @jorgecoca mentioned, we use this library every day at BMW so we will definitely continue to maintain it. I will try to build a roadmap as soon as I can so that you can have a good sense of what's coming next 👍 

If you need any help/support you can reference the [docs](https://felangel.github.io/bloc/#/) as well as join the community on [gitter](gitter.im/bloc_package/Lobby). We also do our best to respond to new issues within 24 hours (usually much less) 😄

**Comment by timrijckaert** [comment]
@maheshkumar2150 We are currently using it in production for the National Belgian TV broadcaster.

@felangel  @jorgecoca  Out of curiosity which apps from BMW are made with Flutter?
Did you guys speak in public somewhere, if so is there a Vimeo/YouTube link?

**Comment by jorgecoca** [comment]
@timrijckaert I did speak at Droidcon NYC about how we use Flutter at BMW. The talk can be found here: https://www.droidcon.com/media-detail?video=362740965

I also talked at AndroidSummit about why we use Flutter, but I only have the slides of that talk: https://speakerdeck.com/jorgecoca/our-journey-to-flutter

Probably in the future you will see more talks just focused on Bloc.
