### ISSUE TITLE
Why does BlocProvider extend StatefulWidget instead of StatelessWidget?

### ISSUE THREAD

**Issue by 5turman** [felangel/bloc#56]
*_BlocProviderState* doesn't dispose BLoC in *dispose* method, so I don't see the reason why BlocProvider does extend StatefulWidget.

**Comment by felangel** [comment]
@5turman thanks for bringing this up and it used to be a StatelessWidget but must have accidentally been changed at some point. I’ll try to have this change in by the end of the day.

**Comment by felangel** [comment]
Merged in #57 and published as flutter_bloc v0.5.1
