### ISSUE TITLE
[Proposal] new BLOC pattern to better testing

### ISSUE THREAD

**Issue by christopher2012** [felangel/bloc#567]
Hello to all,

We have big problem in our company with bloc pattern because is hard to test. 

In some cases we have to execute some events and check multiple states before reach the ones wchich we want to test after dispatch specific event. 
e.g.
```
dispatch(SomeEvent.initial());
dispatch(SomeEvent.downloadData());
dispatch(SomeEvent.calculate());
```

Can you see our solution and tell if it makes sense?

**new block and event pattern**
```
import 'package:bloc/bloc.dart';
import 'package:meta/meta.dart';

typedef StateGetter<S> = S Function();

abstract class BlocPattern<E extends BlocEventPattern<S>, S> extends Bloc<E, S> {
  @override
  Stream<S> mapEventToState(E event) {
    return event.generateStates(() => currentState);
  }
}

abstract class BlocEventPattern<S> {
  @protected
  Stream<S> generateStates(StateGetter<S> currentState);
}
```

**example of event**
```
class _Refresh extends SomeEvent{
  @override
  Stream<TransfersPackState> generateStates(currentState) async* {
    if (!currentState().loading) {
      yield currentState().copyWith(loading: true);
      yield currentState().copyWith(
          download new data
      );
      yield currentState().copyWith(loading: false);
    }
  }
}
```
**tests**
```  
test('', (){
    Details details = Details(id:1, data:[]);
    when(mockRepository.getDetails('1')).thenAnswer((1) => Future.value(details));

    SomeState state = SomeState.initial().copyWith(id:1);

    Stream<SomeState> states = SomeEvent.refresh().generateStates(() => state);

    expect(states, emitsInOrder([
      state.copyWith(loading: true),
      state.copyWith(details : details),
      state.copyWith(loading: false),
    ]));
  });
```

We use abstraction so we don't need to mapEventToState(). We hide implementation of events. And it is nice to read what specific event do. We don't need to put all logic inside mapEventToState() method or using another methods. 

What do you think?

**Comment by felangel** [comment]
Hi @christopher2012 👋 
Thanks for opening an issue!

Unless I'm misunderstanding, this is an anti-pattern. The logic that used to be in the bloc is now moved into the event class. Doing this violates the single responsibility principle because the event now has logic for how to convert itself to a state. Events should not know or care about states and it is the bloc's responsibility to convert events to states.

If you're concerned about keeping `mapEventToState` clean then you should create private mappers:

```dart
  @override
  Stream<S> mapEventToState(E event) async* {
    if (event is EventA) {
      yield* _mapEventAToState(event);
    }
    ...
  }
  
  Stream<S> mapEventAToState(EventA event) async* {
    ...
  }
```
