### ISSUE TITLE
Update Docs according to the updated equatable library.

### ISSUE THREAD

**Issue by Himujjal** [felangel/bloc#570]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I read the doc and use equatable outdated library implementation

**Describe the solution you'd like**
Update docs according to the updates in the equatable library.

**Comment by felangel** [comment]
Hi @Himujjal 👋 
Thanks for opening an issue!

I haven't had the time lately but I will make sure to update the docs to all use the latest `equatable` version/syntax 👍

**Comment by felangel** [comment]
I've updated all of the examples and docs to use the latest version of `equatable` 👍 Thanks again for bringing this up!

**Comment by Himujjal** [comment]
Man you are damn fast in resolving issues. Thank you for such a wonderful library again.
