### ISSUE TITLE
Question: [Not an Issue] : Can i use flutter_bloc along with Flutter provider?

### ISSUE THREAD

**Issue by maheshkumar2150** [felangel/bloc#577]
Hi

I am using MOOR database with Flutter Provider Package.
https://github.com/rrousselGit/provider

Can i use this package along with Provider package?
Will it cause any problems or performance issues?

Or should i use only one of them?
I am really confused. Please help

**Comment by felangel** [comment]
Hi @maheshkumar2150 👋
Thanks for opening an issue!

Of course you can use the two together. In fact, flutter_bloc uses provider internally in its BlocProvider and RepositoryProvider implementations. 

Hope that helps 👍
