### ISSUE TITLE
@override Transfom with different debounce

### ISSUE THREAD

**Issue by AlexandreRoba** [felangel/bloc#58]
Hi all, Thanks for this framwork. It is clear and simple :)

I have a question. how would you recommend to implement different Debounce on the stream input in the transform bloc method. immagine A have a input test field for search -> debounce 500ms but a submit button -> No debounce?

Again thanks for this great work.

**Comment by felangel** [comment]
Hey, thanks so much!

Have you had a chance to look at https://github.com/felangel/bloc/issues/19?

Let me know if that helps. 👍
