### ISSUE TITLE
Add Sponsors

### ISSUE THREAD

**Issue by lsaudon** [felangel/bloc#585]
Add a way to [buy a coffee](https://www.buymeacoffee.com/) or [GitHub Sponsors](https://github.com/sponsors).

**Comment by felangel** [comment]
Hey @lsaudon 👋 
Thanks for bringing this up! I really appreciate it 😄 

I have applied for Github Sponsors but have not heard back unfortunately 😞 
Not sure if there's anything we can do about that though... I haven't checked out "buy a coffee" though so I'll take a look haha 👍 

Thanks again ❤️

**Comment by felangel** [comment]
I was just accepted into GitHub Sponsors! 🎉

**Comment by lsaudon** [comment]
Perfect timing
