### ISSUE TITLE
mapEventToState not called if dispatched events quickly

### ISSUE THREAD

**Issue by QoLTech** [felangel/bloc#59]
Just wondering if anyone has run into an issue where calling dispatch multiple times in quick succession results in mapEventToState not being called?

I have a listener on a socket and when it gets fired, it does _messageBloc.dispatch(MessageReceived(name: name, body: body));

I can print the contents of the message in the listener, but my print statement in mapEventToState only usually gets called for the last message.

If I send a single message after waiting, it makes it to mapEventToState every time.

No exceptions are thrown, I'm on the latest versions of everything.

If you need more info, let me know.

**Comment by felangel** [comment]
@QoLTech thanks for reporting this!

Can you please put together a super simple app that exhibits this behavior?

**Comment by QoLTech** [comment]
I've got my code that I'm currently working on here. It's slightly more complicated than a sample app, but I can easily reproduce the error.

After building and running, just hit connect and after connecting, you'll be on the messaging page. You'll have to use https://worldviewsignalrmessaging.azurewebsites.net/ to send messages. To reproduce, I just rapidly send messages with a single digit (1-9). When I do this, I see 1-9 printed to the console which is from the listener for messages and I only see an extra 9 which is from the Bloc mapEventToState.

Let me know if you need anything else.

**Comment by felangel** [comment]
@QoLTech I finally had a chance to take a look and the reason why this is happening is because you are overriding `transform` in the `MessageBloc` and debouncing. If you remove the `transform` override it will work as you expect.

**Comment by felangel** [comment]
In addition, I noticed that you have your own `bloc_builder` and `bloc_provider`. I'm not sure if this is intentional but if you want you can add `flutter_bloc` to your dependencies and you'll have access to `BlocBuilder` and `BlocProvider` without needed to copy the code into your own project.

**Comment by QoLTech** [comment]
> @QoLTech I finally had a chance to take a look and the reason why this is happening is because you are overriding `transform` in the `MessageBloc` and debouncing. If you remove the `transform` override it will work as you expect.

That's great, thank you. Could you explain or link me to an explanation of how debouncing works?



> In addition, I noticed that you have your own `bloc_builder` and `bloc_provider`. I'm not sure if this is intentional but if you want you can add `flutter_bloc` to your dependencies and you'll have access to `BlocBuilder` and `BlocProvider` without needed to copy the code into your own project.

Yes, I didn't realize that package was also on pub. I will make sure to add it as a dependency, rather than copy it into my own projects.

**Comment by felangel** [comment]
@QoLTech you can learn about denounce [here](
http://reactivex.io/documentation/operators/debounce.html).

Let me know if you have any other questions. 👍

**Comment by QoLTech** [comment]
> @QoLTech you can learn about denounce [here](http://reactivex.io/documentation/operators/debounce.html).
> 
> Let me know if you have any other questions.

At first I thought the time had something to do with it, but couldn't figure out what exactly. Can I ask what the benfit of something like this is? If a button gets tapped in quick succession? If so, why do it this way rather than checking the dispatched events for equality?

**Comment by felangel** [comment]
@QoLTech it’s useful if you’re implementing something like a search and you don’t want to make a network request after every key press because it will put unnecessary load on the backend. 

You can debounce with a duration of something like 500 milliseconds and events that are dispatched less than 500 milliseconds apart won’t be processed. This allows you to only hit your backend after a user has stopped typing.

**Comment by QoLTech** [comment]
> @QoLTech it’s useful if you’re implementing something like a search and you don’t want to make a network request after every key press because it will put unnecessary load on the backend.
> 
> You can debounce with a duration of something like 500 milliseconds and events that are dispatched less than 500 milliseconds apart won’t be processed. This allows you to only hit your backend after a user has stopped typing.

That's great, thank you.
