### ISSUE TITLE
Unexpected behavior when using yield* inside async*

### ISSUE THREAD

**Issue by Mishanya840** [felangel/bloc#594]
**Describe the bug**
When using yield* inside async* bloc does not have time to process new states and update the latest to actual

**To Reproduce**
1. Create new flutter project
2. Add equatable: ^0.6.1 and bloc: 1.0.0 dependecies
3. Add code from **Code** below
4. See console logs

**Code**
data_bloc.dart
```
import "dart:async";

import "package:bloc/bloc.dart";
import "package:equatable/equatable.dart";

class DataEvent {}

class DataState implements EquatableMixin {
  final int value;
  DataState(this.value);

  @override List<Object> get props => [value];
  @override String toString() => "DataState{value: $value}";
}

class DataBloc extends Bloc<DataEvent, DataState> {
  DataBloc() {
    dispatch(DataEvent());
  }

  @override
  DataState get initialState => DataState(0);

  @override
  Stream<DataState> mapEventToState(
    DataEvent event,
  ) async* {
    if (event is DataEvent) {
      print("state value:[main] #1 ${currentState.value}");
      yield DataState(currentState.value + 1);
      print("state value:[main] #2 ${currentState.value}");
      yield DataState(currentState.value + 1);
      print("state value:[main] #3 ${currentState.value}");
      yield DataState(currentState.value + 1);
      print("state value:[main] #4 ${currentState.value}");
      yield* _handleNewDataEvent(1);
      yield* _handleNewDataEvent(2);
    }
  }

  Stream<DataState> _handleNewDataEvent(int i) async* {
    print("state value:[$i] #1 ${currentState.value}");
    yield DataState(currentState.value + 1);
    print("state value:[$i] #2 ${currentState.value}");
    yield DataState(currentState.value + 1);
    print("state value:[$i] #3 ${currentState.value}");
    yield DataState(currentState.value + 1);
    print("state value:[$i] #4 ${currentState.value}");
  }
}
```

main.dart
```

void main() {
  DataBloc();
  runApp(MyApp());
}
```

**Expected logs**

> I/flutter (22598): state value:[main] #1 0
> I/flutter (22598): state value:[main] #2 1
> I/flutter (22598): state value:[main] #3 2
> I/flutter (22598): state value:[main] #4 3
> I/flutter (22598): state value:[1] #1 3
> I/flutter (22598): state value:[1] #2 4
> I/flutter (22598): state value:[1] #3 5
> I/flutter (22598): state value:[1] #4 6
> I/flutter (22598): state value:[2] #1 6
> I/flutter (22598): state value:[2] #2 7
> I/flutter (22598): state value:[2] #3 8
> I/flutter (22598): state value:[2] #4 9

**Actual logs**

> 
> I/flutter (22598): state value:[main] #1 0
> I/flutter (22598): state value:[main] #2 1
> I/flutter (22598): state value:[main] #3 2
> I/flutter (22598): state value:[main] #4 3
> I/flutter (22598): state value:[1] #1 3
> I/flutter (22598): state value:[1] #2 3
> I/flutter (22598): state value:[1] #3 4
> I/flutter (22598): state value:[1] #4 4
> I/flutter (22598): state value:[2] #1 5
> I/flutter (22598): state value:[2] #2 5
> I/flutter (22598): state value:[2] #3 6

**Comment by felangel** [comment]
Hi @Mishanya840 👋 
Thanks for opening an issue!

This is because when you have a nested async generator (`yield*`) within `mapEventToState` and you are yielding back to back states, the states are emitted from the nested async generator (`_handleNewDataEvent`) faster than they are processed by the bloc.

In general I would not recommend having consecutive, synchronous yields that individually depend on `state` because state is a computed property and is not guaranteed to be updated between `yield` statements.

Let me know if that helps 👍

**Comment by Mishanya840** [comment]
https://dartpad.dartlang.org/fc18279df881cc829494c7399ae4ef62
This is what it is now (and here everything is asynchronous and correspondingly the order of operations is lost when the stream is embedded in the stream)

https://gist.github.com/Mishanya840/ffdd8c4f79c83ed526b6eb86ff2338d2
Here I want to transfer it, so all operations are performed synchronously
Thus, we will have a guaranteed `state` update after each `yield`?!

**Comment by felangel** [comment]
@Mishanya840 thoughts?

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional information and I'm happy to continue the conversation 👍
