### ISSUE TITLE
bloc and navigation

### ISSUE THREAD

**Issue by farrokhpey** [felangel/bloc#595]
Hi,
I started a project for managing some stores,
my project structure is like this:
i'v a home page that contains a list of stores and a button for creating new store
when user click on button we navigate him to second screen (with Navigator.push method)
and there he/she will create the store and after submitting the form we will redirect him to first page with (Navigator.pop method)
I've a bloc named as StoreBloc in first screen, i passed it to second screen with constructor argument
now the problem is, when i navigate back to the first screen and click on button and navigate to second screen, i cant create new store, it seems bloc dismissed, and no event fired and no state is changed,
can anybody help me what's the problem?
and another question is :
I need to refresh list of stores in first page after creating new store in second page(just after navigator.pop method), how can i achieve this?

**Comment by tenhobi** [comment]
Can you show us an example of your code?

**Comment by farrokhpey** [comment]
> Can you show us an example of your code?

it's too dirty :'(

**Comment by farrokhpey** [comment]
first screen wdget definition:
![image](https://user-images.githubusercontent.com/5526403/67210284-af170700-f425-11e9-831b-d8a566ee57b7.png)

widget definition:
![image](https://user-images.githubusercontent.com/5526403/67210419-ea193a80-f425-11e9-88f9-80088f08c413.png)


second screen definition:
![image](https://user-images.githubusercontent.com/5526403/67210479-0917cc80-f426-11e9-9f9f-411a464cd3cb.png)

second screen form:
![image](https://user-images.githubusercontent.com/5526403/67210570-2cdb1280-f426-11e9-9faa-8327cf9c9ff2.png)

**Comment by felangel** [comment]
Hi @farrokhpey 👋 
Thanks for opening an issue!

The problem is BlocProvider automatically disposes/closes the bloc when BlocProvider itself is disposed. In your setup, when the second screen is disposed, it will also call dispose/close on the store bloc which makes it unusable on the first screen.

You should use BlocProvider.value everywhere where you are providing an existing bloc because BlocProvider.value does not automatically close the bloc. You can read more about this in the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=route-access). 

Hope that helps 👍

**Comment by farrokhpey** [comment]
@felangel  thank you for your response
but still there was another question
I need to refresh list of stores in first page after creating new store in second page(just after navigate back to first page with navigator.pop method), how can i achieve this?

**Comment by felangel** [comment]
@farrokhpey you just need to change your nested BlocProvider to use `BlocProvider.value` and make sure that only the top-most `BlocProvider` is using a builder to create a new instance of the bloc. That way you avoid having the bloc automatically be closed by BlocProviders even when it is still needed. Hope that helps 👍

**Comment by farrokhpey** [comment]
@felangel ,my problem is: i need to change state of main storeBlock in first page from second page, do you understand what i need?i need to access first page block from second page :(

**Comment by felangel** [comment]
@farrokhpey yes I understand. You just need to use BlocProvider(builder: (context) => StoreBloc()..dispatch(FetchStoreData(), child: StoreListWidget())

Then in your second screen use BlocProvider.value(value: BlocProvider.of<StoreBloc>(context), child: CreateStoreForm()).

Like I mentioned above please refer to the bloc access recipe for more information.
