### ISSUE TITLE
StreamSubscription not listen on dispatched event

### ISSUE THREAD

**Issue by alvarofvr** [felangel/bloc#597]
**Describe the bug**
I'm using the Flutter BLoC package for manage the state of my app, but since last package update (v0.22.1) I have a strange behavior.

In simple I have a StreamSubscription listener on PositionBloc's state in EventsBloc but when I add an event from PositionBloc the listener not work. The strangest thing is that the first time I add the event from EventsBloc the listener work, but after seems to be completely ignored.

**Code**
This is my build tree:

`main.dart`: Here I show home page or the login page based on authentication. `AuthenticationBloc` and `MoviesBloc` aren't important or `LocalsBloc` the focus is on `PositionBloc`. 

    class App extends StatelessWidget {
      ...
      @override
      Widget build(BuildContext context) {
        return BlocProvider(
          builder: (context) => MoviesBloc()..add(LoadMovies()),
          child: MaterialApp(
            home: BlocBuilder<AuthenticationBloc, AuthenticationState>(
              builder: (context, state) {
                if (state is Unauthenticated) {
                  return Login(
                    authenticationRepository: _authenticationRepository,
                  );
                }
                if (state is Authenticated) {
                  return MultiBlocProvider(
                    providers: [
                      BlocProvider<LocalsBloc>(
                        builder: (context) => LocalsBloc()..add(LoadLocals()),
                      ),
                      BlocProvider<PositionBloc>(
                        builder: (context) => PositionBloc(
                          localsBloc: BlocProvider.of<LocalsBloc>(context),
                        ),
                      )
                    ],
                    child: Home(),
                  );
                }
                return Splash();
              },
            ),
          ),
        );
      }
    }

`home.dart`: This is a `StatefulWidget` for manage `TabBarView` and here I provide `EventsBloc` to the widget `EventsCarousel`. In `SearchBar` widget I have the trigger for dispatch event and so rebuild the `EventsCarousel` based on selected position.
    
    class _HomeState extends State<Home> with SingleTickerProviderStateMixin {
      ...
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          body: SafeArea(
            child: TabBarView(
              children: <Widget>[
                Stack(
                  alignment: Alignment.topCenter,
                  children: <Widget>[
                    BlocProvider<EventsBloc>(
                      builder: (context) => EventsBloc(),
                      child: EventsCarousel(),
                    ),
                    Positioned(
                      child: SearchBar(),
                    ),
                  ],
                ),
                MoviesList(),
                Settings(),
              ],
              controller: _tabController,
            ),
          ),
          bottomNavigationBar: Material(
            child: TabBar(
              indicatorColor: Colors.deepOrange,
              tabs: <Tab>[
                Tab(
                  icon: Icon(
                    FontAwesomeIcons.home
                  ),
                ),
                Tab(
                  icon: Icon(
                    FontAwesomeIcons.bullhorn,
                  ),
                ),
                Tab(
                  icon: Icon(
                    FontAwesomeIcons.cogs,
                  ),
                ),
              ],
              controller: _tabController,
            ),
          ),
        );
      }

`search_bar.dart`: This is a `StatefulWidget` for manage `_textController` and `_focusNode`. Here I have my app state changer. I use Flutter TypeAhead package for build the search bar and the entries of my search bar is provided from `LocalsBloc` that we see in main.dart. When I tap on an entry I add the event `UpdatePosition`(local) to `PositionBloc`.

    class _SearchBarState extends State<SearchBar> {
      ...
      @override
      Widget build(BuildContext context) {
        return BlocBuilder<PositionBloc, PositionState>(
          builder: (context, state) {
            if (state is PositionUpdated) {
              if (!_focusNode.hasFocus) {
                _textController.text = state.position.local.description;
              }
    
              return Container(
                decoration: BoxDecoration(
                  color: Colors.white,
                ),
                width: MediaQuery.of(context).size.width * 0.75,
                child: TypeAheadField<Local>(
                    getImmediateSuggestions: true,
                    textFieldConfiguration: TextFieldConfiguration(
                      decoration: InputDecoration(
                        border: OutlineInputBorder(
                          borderRadius: BorderRadius.all(
                            Radius.circular(10.0),
                          ),
                        ),
                        hintText: "Inserisci una posizione",
                        contentPadding: EdgeInsets.all(15),
                      ),
                      focusNode: _focusNode,
                      controller: _textController,
                    ),
                    suggestionsCallback: (String pattern) {
                      return (BlocProvider.of<LocalsBloc>(context).state as LocalsLoaded)
                          .locals
                          .where(
                            (local) =>
                                local.description
                                    .toLowerCase()
                                    .contains(pattern.toLowerCase()),
                          )
                          .toList();
                    },
                    noItemsFoundBuilder: (context) {
                      return Text('Nessun risultato trovato');
                    },
                    itemBuilder: (context, Local suggestion) {
                      return Card(
                        child: ListTile(
                          title: Text(suggestion.description),
                          subtitle: Text(suggestion.town),
                          trailing: Icon(Icons.gps_not_fixed),
                        ),
                      );
                    },
                    onSuggestionSelected: (Local suggestionSelected) {
                      BlocProvider.of<PositionBloc>(context).add(
                        UpdatePosition(suggestionSelected),
                      );
                    }),
              );
            } else {
              return Container();
            }
          },
        );
      }

I have standards Bloc boilerplate for events and states and in particular for EventsBloc as I said I have this subscription:   

```
    EventsBloc({@required PositionBloc positionBloc})
      : assert(PositionBloc != null),
        _positionBloc = positionBloc {
    positionSubscription = positionBloc.listen((state) {
      if (state is PositionUpdated) {
        add(LoadEvents(state.local));
      }
    });
```

This listener not work after the first widgets tree build, but when I add event UpdatePosition from selection of an entry in the search bar the state of PositionBloc change and the event is correctly mapped to PositionUpdated. This is a very strange situation, can help me?

**Comment by alvarofvr** [comment]
I just noticed that I had missed a super-call in the CTORs initializer for my PositionUpdated state so the listener was not invoked. This is my mistake and I had been following it for three days in debug.
But I take this opportunity for ask you. 
Why hasn't the listener been invoked even if the state has not changed?

**Comment by felangel** [comment]
Hi @alvarofvr 👋 
Glad you resolved the issue! Listener is only invoked on state changes by definition. This is because  invoking the listener on an initial state would have serious side-effects. For example, if you wanted to navigate in response to StateA, then once the bloc emits StateA, every time the BlocListener widget is rebuilt it will trigger the navigation, etc... Furthermore, if you want to do something in response to the initial state you can simply just do it when you instantiate the bloc. Hope that helps 👍
