### ISSUE TITLE
When using BlocProvider or other Bloc widgets as the app's root widget, the context doesn't include a MediaQuery

### ISSUE THREAD

**Issue by WinkMeter** [felangel/bloc#601]
**Describe the bug**

**To Reproduce**
1. Create an app with a MaterialApp widget
2. Wrap the MaterialApp with a BlocProvider
3. Create a function to build the theme (e.g _buildAppTheme()) and assign this to the "theme" property of the MaterialApp widget.
4.  Access the MediaQuery.of(context) within the the _buildAppTheme()
5.  An error will be reported saying that the context is not the right type of context for accessing MediaQuery

**Expected behavior**

**Screenshots**

**Logs **
Run `flutter analyze` and attach any output of that command below.
If there are any analysis errors, try resolving them before filing this issue.

Paste the output of running `flutter doctor -v` here.

**Additional context**

**Comment by felangel** [comment]
Hi @WinkMeter 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the issue? Thanks!

**Comment by felangel** [comment]
Closing this because after revisiting it I don't think it has anything to do with the bloc library.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    ThemeData _buildAppTheme() {
      print(MediaQuery.of(context).size.width);
      return ThemeData.dark();
    }

    return MaterialApp(
      theme: _buildAppTheme(),
      home: Scaffold(
        body: Center(
          child: Text('Home'),
        ),
      ),
    );
  }
}
```

Will result in the same exception because you're accessing the context outside of `MaterialApp` so there is no `MediaQuery`. You can see https://stackoverflow.com/questions/50214338/flutter-error-mediaquery-of-called-with-a-context-that-does-not-contain-a-med for more information.
