### ISSUE TITLE
BlocSupervisor.delegate not printing anything to the console

### ISSUE THREAD

**Issue by tapizquent** [felangel/bloc#602]
**Describe the bug**
For some reason the SimpleBlocDelegate is not printing anything to the console. I haven't changed anything from my codebase and my BlocDelegate is exactly as SimpleBlocDelegate from docs.
It just suddenly stopped printing out to the console.

**To Reproduce**
Regular program with `BlocSupervisor.delegate = SimpleBlocDelegate();` set in main method.

**Expected behavior**
When any event is triggered, it should print out to the console.

**Logs **
Run `flutter analyze` and attach any output of that command below.

```No issues found! (ran in 5.1s)```

Paste the output of running `flutter doctor -v` here.

```
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.15 19A602, locale en-US)
    • Flutter version 1.10.14 at /Users/tapizquent/Projects/tools/flutter
    • Framework revision 1946fc4da0 (2 weeks ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/tapizquent/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • iPhone • e75fc710ec1404ac1c323311b0ba25049db7e7d4 • ios • iOS 13.1.3

• No issues found!
```

**Additional context**
No idea why is stopped printing out. Nothing prints. No events, no transitions, it's like it doesn't even have a BlocDelegate.

**Comment by tenhobi** [comment]
Hi. Can you provide some example, on GitHub for example, so we can investigate further and not guess? :)

**Comment by felangel** [comment]
Hi @tapizquent 👋 
Thanks for opening an issue!

As @tenhobi mentioned, it would be most helpful if you can provide a link to a sample app which illustrates the problem. Thanks!

**Comment by tapizquent** [comment]
I am trying to get a working demo to show the behavior but when creating a new app it seems to work fine. I don't want to make you look through all of my app to identify what could be causing this. I will try to reproduce the problem. Last resort, I will give you access to the repo for the app. It's mostly organized and shouldn't be that bad too identify where blocs are, etc.

**Comment by felangel** [comment]
Sounds good! I don't mind taking a look at your app if you're okay with that. It probably wouldn't take too long to debug the issue 👍

**Comment by tapizquent** [comment]
Ok, so update. I did run some tests and figured out that it works when we run it in the simulator but not when running it on my device. iOS Simulator works fine but iOS device does not print anything.

I have made you @felangel a collaborator to the repo so you can take a look.

Latest branch you should look at: feature/pet_creation/#231ga302_allow_user_to_view_pets

**Comment by felangel** [comment]
Where are you looking for the prints? Are others showing up when you run on a real device? Are you running in debug or release mode?

**Comment by tapizquent** [comment]
I run app through VSCode and usually just hit 'Start Without Debugging' or ^F5. Running the same way, it runs fine in simulator. I run in debug mode not release nor profile.

**Comment by felangel** [comment]
That’s strange do other prints show up?

**Comment by felangel** [comment]
Looks like this might be a known flutter issue on iOS 13. https://stackoverflow.com/questions/58201578/print-statement-not-printing-to-console-in-flutter-ios-app-within-android-stud

**Comment by tapizquent** [comment]
You are totally right. No other print statement is working either.

Apparently the Flutter team is aware of this: https://github.com/flutter/flutter/issues/41133

I guess it is okay to close now. I will have to use Simulator for logging meanwhile.

Thank you!
