### ISSUE TITLE
[Document For 1.0] New changes for 1.0

### ISSUE THREAD

**Issue by nguyenhuutinh** [felangel/bloc#605]
Hi @felangel ,
Do you have any post / note for new changes on 1.0

After upgraded from 0.21, my project cannot work anymore.

Cannot find dispatch and dispose anymore

Thanks

**Comment by nguyenhuutinh** [comment]
found on another issue's comment. thanks

**Comment by tenhobi** [comment]
There are also Changelogs for [bloc](https://github.com/felangel/bloc/blob/master/packages/bloc/CHANGELOG.md) and [flutter_bloc](https://github.com/felangel/bloc/blob/master/packages/flutter_bloc/CHANGELOG.md).

**Comment by felangel** [comment]
You can also check out the [medium article](https://link.medium.com/a3rdFuBH20) 👍

**Comment by nguyenhuutinh** [comment]
yes actually I found the changes in your medium article :)

Thanks alot
