### ISSUE TITLE
Enum is not supported in states

### ISSUE THREAD

**Issue by michaldev** [felangel/bloc#612]
**Describe the bug**
If state has enum field, view not refresh and not detect changes.

**To Reproduce**
```
enum Pages { quizPage, myProfilePage, settingsPage }

@immutable
class NavigationState {
  final Pages page;
  final bool isOpenedBottomBar;
  final bool isVisibilityBottomBar;
  final bool isOpenCropPage;
}
```

**Expected results**
All fields except enum work correctly. The enum field is read correctly in the view, but does not detect changes.

**Comment by felangel** [comment]
Hi @michaldev 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the problem you’re having? There should be no issue with using enums. Thanks!

**Comment by michaldev** [comment]
Ok, nothing. while creating an example for you, i realized that it works. The problem was my fault.
