### ISSUE TITLE
Sorting of my state

### ISSUE THREAD

**Issue by prasant10050** [felangel/bloc#614]
How do i do if i need to sort current state or model when we have added Equtable and extend model with it

**Comment by felangel** [comment]
Hi @prasant10050 👋 
Thanks for opening an issue!

Can you please provide a sample app which illustrates the problem you're having? I'm not sure I fully understand the question.

Thanks 👍

**Comment by felangel** [comment]
Closing for now as there is not enough information in this issue. Feel free to comment with additional information and I’m happy to continue the conversation.
