### ISSUE TITLE
BLoC add same event again but no state (same previous state persists)

### ISSUE THREAD

**Issue by abdulmuaz97** [felangel/bloc#615]
**Can't add same event.. only one time.. and same previous state persists**
hey all, I'm having a little problem with dealing with bloc 
so I have to blocs [appBloc, FirebaseBloc] and in the [appBloc] when I add an event after absolutely get the initial state.. I get result, but when I add the same event with different data..can't get anything it's like [adding once event only]

**Here is the events file**

![1](https://user-images.githubusercontent.com/17835497/67625633-41197800-f849-11e9-9c7b-4f668e65dd8a.png)

**Here is the states file**

![2](https://user-images.githubusercontent.com/17835497/67625645-60180a00-f849-11e9-8f34-bb64e23d6c26.png)

**Here is the bloc file**

![3](https://user-images.githubusercontent.com/17835497/67625663-a2d9e200-f849-11e9-8686-c65bc6a0fc65.png)

**NOTE: I'm using the bloc extension in VSCode and it generates these files by default except the ChangeAppTheme class and other methods**

any solutions??

**Comment by felangel** [comment]
Hi @abdulmuaz97 👋 
Thanks for opening an issue!

When you extend `Equatable` you need to provide all properties which you want to be considered when doing the equality comparison to the `props` override otherwise different instances of those classes will be considered equal and the bloc will ignore the transitions.

```dart
class AppStatus extends AppState {
  final String status;
  const AppStatus(this.status);
  @override
  List<Object> get props => [status];
}
```

```dart
class ChangeAppTheme extends AppEvent {
  final ThemeData themeData;
  const ChangeAppTheme(this.themeData);
  @override
  List<Object> get props => [themeData];
}
```

**Comment by abdulmuaz97** [comment]
@felangel  ok thank you so much for replying to me.. I'll see it right now ❤️

**Comment by abdulmuaz97** [comment]
@felangel it worked just fine.. THANK YOU

**Comment by DDDrop** [comment]
@felangel How to deal with none property even, like:
```
abstract class AppEvent extends Equatable {
  const AppEvent();
}

class AppLoadEvent extends AppEvent {
  const AppLoadEvent();

  @override
  List<Object> get props => [];
}
```

**Comment by felangel** [comment]
@DDDrop if you have no properties on any of your subclasses you can do

```dart
abstract class AppEvent extends Equatable {}

class AppLoadEvent extends AppEvent {}
```
