### ISSUE TITLE
BlocListener .skip(1)

### ISSUE THREAD

**Issue by orsenkucher** [felangel/bloc#625]
**Describe the bug**
flutter_bloc: ^1.0.0
You are using .skip(1) in BlocListener and I'm wondering is it intentional, or is it a bug?

You can find .skip(1) invocation on ln: 184 of bloc_listener.dart (_BlocListenerBaseState class, _subscribe() method)

Also you @felangel have mentioned there should not be .skip(1) for BlocListener in this comment:
https://github.com/felangel/bloc/issues/278#issuecomment-491552253

**Expected behavior**
use _bloc.skip(0).listen( ... ) or remove skip() completely,

_Arseniy_

**Comment by felangel** [comment]
Hi @orsenkucher 👋 
Thanks for opening an issue!

This is intentional because BlocListener should only be called on state changes. Without the skip(1), listener will be called with initialState which leads to undesirable behavior (https://github.com/felangel/bloc/issues/368). Hope that helps 👍
