### ISSUE TITLE
Tests are crashing after switching to 1.0.0 from 0.19.0

### ISSUE THREAD

**Issue by Den-Ree** [felangel/bloc#627]
**Describe the bug**
The tests are failed with the following error when I'm testing widget with MultiBlocListener on v1.0.0. 

```
Exception has occurred.
TestFailure (Expected: exactly one matching node in the widget tree
  Actual: ?:<zero widgets with key [<'EMAIL_LOGIN_EMAIL_TEXT_FIELD'>] (ignoring offstage widgets)>
   Which: means none were found but one was expected
)
```

**To Reproduce**
1. Mock block and run tests 
2. Widget is build but during run it doesn't go to `builder: (BuildContext context, LoginState loginState)`
3. As result widget is not build correctly
4. The error occurs. 

**Expected behavior**
In version 0.19.0 it goes to the `builder: (BuildContext context, LoginState loginState)` and build the widget.

**Test**

```
setUp(() {
    authBloc = MockAuthenticationBloc();
    loginBloc = MockLoginBloc();

    testWidget = wrapWidget(Scaffold(
        body: BlocProvider.value(
          value: loginBloc,
          child: EmailLoginForm(authBloc: authBloc, loginBloc: loginBloc),
        )
    ), null);
  });

testWidgets('form is initially displayed', (WidgetTester tester) async {
    when(loginBloc.state).thenAnswer((_) => LoginState.loading());

    await tester.pumpWidget(testWidget);
    await tester.pumpAndSettle(); // to wait for localization

    expect(find.byKey(EMAIL_LOGIN_EMAIL_TEXT_FIELD), findsOneWidget);
    expect(find.byKey(EMAIL_LOGIN_PASSWORD_TEXT_FIELD), findsOneWidget);
    expect(find.byKey(EMAIL_LOGIN_SUBMIT_BUTTON), findsOneWidget);
  });
```

**Widget**

```
@override
  Widget build(BuildContext context) {
    return MultiBlocListener(
      listeners: [
        BlocListener<LoginBloc, LoginState>(
          bloc: _loginBloc,
          listener: (context, state) {
            if (_loginSucceeded(state)) {
              widget.tracker.trackEvent(event: Events.LOGIN_SUCCESS);
              _authBloc.onLogin(token: state.token);
            }
          },
        ),
        BlocListener<AuthenticationBloc, AuthenticationState>(
          bloc: _authBloc,
          listener: (context, state) {
            if (state.isAuthenticated) {
              Navigator.pushReplacementNamed(context, Constants.ROUTE_HOME);
            }
          },
        ),
      ],
      child: BlocBuilder<LoginBloc, LoginState>(
        bloc: _loginBloc,
        builder: (BuildContext context, LoginState loginState) {
          if (_loginFailed(loginState)) {
            buttonEnabled = true;
            widget.tracker.trackEvent(event: Events.LOGIN_FAILED);

            onWidgetDidBuild(() {
              final String errorMessage = _isNetworkError(loginState.error)
                  ? AppLocalizations.of(context).loginNetworkErrorMessage
                  : AppLocalizations.of(context).loginErrorMessage;
              _displayLoginErrorDialog(errorMessage);
            });
          }

          return _form(loginState);
        },
      ),
    );
  }
```

**Logs **
There is no errors in `flutter analyze` and `flutter doctor`

**Comment by felangel** [comment]
Hi @Den-Ree 👋 
Thanks for opening an issue!

The problem is in 1.0.0 you no longer access the state stream via bloc.state because the bloc itself extends Stream. 

You need to change `when(loginBloc.state).thenAnswer((_) => LoginState.loading());`

to

`whenListen(loginBloc, Stream<LoginState>.fromIterable([LoginState.loading()));`

whenListen comes from the [bloc_test](https://pub.dev/packages/bloc_test#-readme-tab-) package.

Hope that helps and sorry for any inconvenience!

**Comment by Den-Ree** [comment]
@felangel thanks for the answer. But the problem is still happens. When I debug the test then code never go to inside. If I correctly understand that it should be called during building the widget or not?
```
builder: (BuildContext context, LoginState loginState) {
....
}
```

**Comment by felangel** [comment]
To trigger the initial build just mock the state of the bloc via:

when(bloc.state).thenReturn(LoginState.loading())

**Comment by Den-Ree** [comment]
@felangel thanks a lot for the help, it works as you suggested. But I noticed the following thing, which is not clear for me. 

During running the test, the first time state are null in 
`builder: (BuildContext context, LoginState loginState)`

and only for the second time I get the needed state.

**Comment by felangel** [comment]
@Den-Ree can you please provide a link to a sample app which illustrates the issue you're seeing? If you're initially seeing a null state that means that the bloc's state has not been properly stubbed. Are you using `when(loginBloc.state).thenReturn(LoginState.loading());`?
