### ISSUE TITLE
How bloc communicate in a Flutter flutter_bloc tree structure?

### ISSUE THREAD

**Issue by cosinus84** [felangel/bloc#630]
I have some dilemma: I have a AuthBloc(lift state up) witch is on top of the tree, down comes other blocs for profile, products, etc. When an event is launched to ProfileBloc/PostBlocs... some usecase is executed, that uses the repositories. The problem is that if I get back from repository/usecase an 401 error how do you think is the best way to "tell" this to AuthBloc (because it handles the authentication state)?

1. Any sub blocs is getting e reference to AuthBloc, when 401 comes call auth.logoutEvent()
2. Creating a AppEventsService (injected using get_it) that is listen by AuthBloc, and then calls logoutEvent()
3. Adding an interceptor to Dio (http) with AppEventsService that is listen by AuthBloc (somehow I think this breaks the clean architecture)

Any other suggestion ?

**Comment by felangel** [comment]
Hi @cosinus84 👋 
Thanks for opening an issue!

In this case, I would recommend structuring your initialization like:

```dart
final ApiClient = ApiClient(onRevoke: () => authBloc.add(Logout()));
```

That way your ApiClient can handle the token management internally and surface a 401 to the caller. From the caller's context you can add the `Logout` event to the `AuthBloc`.

Hope that helps 👍

**Comment by cosinus84** [comment]
Thank you for your quick answer, I am trying to understand how to connect all the pieces.

1. By saying "From the caller's context you can add the Logout event to the AuthBloc" you mean that on return 401, the caller(XYZBloc) can "call"(mapEventToState) the apiClient.onRevoke(). 

2. final apiClient = ApiClient(onRevoke: () => authBloc.add(Logout())); means that authBloc comes from XYZBloc constructor, and apiClient is a property inside XYZBloc.

**Comment by felangel** [comment]
@cosinus84 no problem! I was referring to doing it at your initialization stage of your application.

```dart
// main.dart

void main() {
  var AuthBloc authBloc;
  final ApiClient apiClient = ApiClient(onRevoke: () => authBloc.add(Logout()));
  final Repository repo = Repository(apiClient);
  authBloc = AuthBloc(repo);
  ...
  runApp(
    BlocProvider.value(
      value: authBloc,
      child: MyApp(),
    );
);
}
```

Let me know if that helps 👍

**Comment by cosinus84** [comment]
All is clear now, thank you for the quick and concise answer :).
