### ISSUE TITLE
Can we reuse event during bloc?

### ISSUE THREAD

**Issue by nguyenhuutinh** [felangel/bloc#632]
Hi @felangel ,
any chance to reuse the event during the blocs?

**Comment by felangel** [comment]
Hi @nguyenhuutinh 👋 
Thanks for opening an issue!

I’m not sure what you mean? Can you provide more information and ideally some example code? Thanks 👍

**Comment by felangel** [comment]
Closing for now as there isn’t enough information in the issue. Feel free to comment with additional information and I’m happy to continue the conversation 👍

**Comment by nguyenhuutinh** [comment]
Hi @felangel ,
for example
Home screen and the full product list screen also have the load product event.
I want to use 1 event for both bloc.
 is it posible?

**Comment by felangel** [comment]
@nguyenhuutinh sure you can make both blocs accept the same event type. Is there something in particular that isn’t working?
