### ISSUE TITLE
 'focusScopeNode' null.

### ISSUE THREAD

**Issue by prasant10050** [felangel/bloc#635]
When i navigate from one screen to another that time in console i am getting this issue The getter 'focusScopeNode' was called on null.
Please suggest me how do i solve this issue

**Comment by tenhobi** [comment]
Hey, could you provide more information? Maybe some small example where it fails?

**Comment by felangel** [comment]
Hi @prasant10050 👋 
Thanks for opening an issue!

Can you please provide a sample app which illustrates the problem you’re having? Thanks!

**Comment by felangel** [comment]
Closing for now since there is not enough information. Feel free to comment with additional info and I’m happy to continue the conversation.
