### ISSUE TITLE
 Cannot access parent bloc on the same route

### ISSUE THREAD

**Issue by MonNguyen2502** [felangel/bloc#637]
![image](https://user-images.githubusercontent.com/35995330/68079855-0e601880-fe23-11e9-8ef1-c502afe3c669.png)

Take a look at the image, I can not access NewFeedDetailBloc from ItemFeedDetailView. I was wondering, whether ListView created a new route for its children, or did I not fully understand the meaning of bloc?
Please explain to me, thank you very much

**Comment by felangel** [comment]
Hi @MonNguyen2502 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the problem you’re having? It’s hard to help without seeing any code. 

Thanks!

**Comment by MonNguyen2502** [comment]
ok, I will create a new code

**Comment by MonNguyen2502** [comment]
@felangel 
```
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:sam_sam/pages/parent_page/parent_page_bloc.dart';

class ParentPage extends StatefulWidget {
  @override
  _ParentPageState createState() => _ParentPageState();
}

class _ParentPageState extends State<ParentPage> {
  ParentPageBloc _bloc;

  @override
  void initState() {
    _bloc = ParentPageBloc();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Demo Bloc'),
      ),
      body: ListView.builder(
          itemBuilder: (context, index) => ItemWidget(index: index),
          itemCount: 1000),
    );
  }
}

class ItemWidget extends StatelessWidget {
  final int index;

  ItemWidget({this.index});

  @override
  Widget build(BuildContext context) {

    //BlocProvider.of() called with a context that does not contain a Bloc of type ParentPageBloc.
    ParentPageBloc _bloc = BlocProvider.of<ParentPageBloc>(context);
    return ListTile(
      title: Text('$index'),
    );
  }
}

```

**Comment by MonNguyen2502** [comment]
@felangel I still don't really understand it, it seems like a crazy question, but I hope you can explain it to me.

**Comment by felangel** [comment]
You need to use `BlocProvider` to wrap the child otherwise there is nothing "providing" the bloc.

```dart
BlocProvider(
  builder: (context) => MyBloc(),
  child: MyChild(),
)
```

Then from `MyChild` or any of `MyChild's` children you can access `MyBloc` via
```dart
BlocProvider.of<MyBloc>(context);
```

Hope that helps 👍

**Comment by MonNguyen2502** [comment]
@felangel Thanks for the reply, I often overlook the core @@.
Let me ask one more question. Can I use MultiBloc this way? At Child I do not receive BlocB

```
                    MultiBlocProvider(
                        providers: [
                          BlocProvider<CommentFeedDetailBloc>(
                            builder: (context) => BlocA(),
                          BlocProvider.value(value: _blocB),
                        ],
                        child: Child())
```

**Comment by felangel** [comment]
No problem! If you’re using MultiBlocProvider you need to make sure you explicitly provide the bloc type:

BlocProvider.value<BlocB>(value: _blocB)

**Comment by MonNguyen2502** [comment]
@felangel The Constructor BlocProvider.value doesn't have type parameters
