### ISSUE TITLE
[Question] 1 Event with multiple update on State

### ISSUE THREAD

**Issue by omuomugin** [felangel/bloc#64]
Hi, 
thanks for the great work on this bloc library (or maybe framework).

I'm now trying to follow the instruction on [your tutorial](https://felangel.github.io/bloc/#/flutterinfinitelisttutorial) and I had a question.

So , is there way to update state multiple time with single event?
In other words is there way to behave as hot stream (or Observable) ? 

For example on tutorial, I was wondering how to manage "Loading State".
Simple way which I came up was first update with `PostLoading` and whenever the data was fetched update with `PostLoaded` from single `Fetch` event. Is this possible with current API ?

code example

```
@override
  Stream<PostState> mapEventToState(
    PostState currentState,
    PostEvent event,
  ) async* {
    if (event is Fetch && !_hasReachedMax(currentState)) {
      try {
        if (currentState is PostUninitialized) {
          final posts = await _fetchPosts(0, 20);
          // want to return PostLoading();
          yield PostLoaded(posts: posts, hasReachedMax: false);
        }
        if (currentState is PostLoaded) {
          // want to return PostLoading();
          final posts = await _fetchPosts(currentState.posts.length, 20);
          yield posts.isEmpty ? currentState.copyWith(hasReachedMax: true) : PostLoaded(posts: currentState.posts + posts, hasReachedMax: false);
        }
      } catch (_) {
        yield PostError();
      }
    }
  }
```

Anyway thanks for the awesome work.

**Comment by omuomugin** [comment]
After opening this issue, I kind a understood how to do this so I will comment my opinion.
I'm pleased to have comment from @felangel. 

I guess this framework is inspired by redux and redux has middleware to do this kind of things.
But not for bloc. 
But the basis is state management with incoming event and current state (just like Reducer), so the transition like  `(Fetch, PostLoaded) -> (Fetch, PostLoading) -> (Fetch, PostLoaded)`  will work and code sample will be below.

```
  @override
  Stream<PostState> mapEventToState(
    PostState currentState,
    PostEvent event,
  ) async* {

    // already reached max
    if(event is Fetch && currentState is PostLoaded && _hasReachedMax(currentState)){
      yield currentState;
    }

    if(event is Fetch){
      if(currentState is PostLoaded) {
        new PostLoading(currentState.posts);
      }
      if(currentState is PostLoading){
        if (!_hasReachedMax(currentState)) {
          try {
            if (currentState is PostUninitialized) {
              final posts = await _fetchPosts(0, 20);
              yield PostLoaded(posts: posts, hasReachedMax: false);
            }
            if (currentState is PostLoaded) {
              final posts = await _fetchPosts(currentState.posts.length, 20);
              yield posts.isEmpty ? PostLoaded(posts: currentState.posts, hasReachedMax: true) : PostLoaded(posts: currentState.posts + posts, hasReachedMax: false);
            }
          } catch (_) {
            yield PostError();
          }
        }
      }
    }
  }
```

Thank you

**Comment by omuomugin** [comment]
I managed to this by using 2 bloc from 1 widget.
1 for managing the state `network loading ` and another for managing the `post`

The problem was kind of solved but in case if you have any comments on this I'll let this issue open.

**Comment by felangel** [comment]
@omuomugin you can do this with a single bloc by yielding a loading state before making a network request. 

```dart
@override
  Stream<LoginState> mapEventToState(
    LoginState currentState,
    LoginEvent event,
  ) async* {
    if (event is LoginButtonPressed) {
      yield LoginLoading();

      try {
        final token = await userRepository.authenticate(
          username: event.username,
          password: event.password,
        );

        authenticationBloc.dispatch(LoggedIn(token: token));
        yield LoginInitial();
      } catch (error) {
        yield LoginFailure(error: error.toString());
      }
    }
  }
```

This code snippet is taken directly from the login tutorial which can be found at 
https://felangel.github.io/bloc/#/flutterlogintutorial?id=login-bloc. 

Hope that helps!

**Comment by omuomugin** [comment]
Oh, this is what exactly what I wanted :)
Thanks
