### ISSUE TITLE
object oriented block coding

### ISSUE THREAD

**Issue by farrokhpey** [felangel/bloc#640]
Hi @felangel 
i am developing a big project that contains too many blocs
i ant to define some base classes such as BaseEvent, BaseState, BaseBloc
i did this
but now there is a problem with my code, 
it said: 
![image](https://user-images.githubusercontent.com/5526403/68115048-b7367280-ff0c-11e9-9751-34e3b48a08ca.png)

can u tell me how should i resolve this problem?
these are my class definition and bloc usage:

![image](https://user-images.githubusercontent.com/5526403/68114205-b8ff3680-ff0a-11e9-9f9f-7c7b6bed3f4d.png)

**Comment by felangel** [comment]
Hi @farrokhpey 👋 
Thanks for opening an issue!

Can you please share a link to a sample app which illustrates the problem? Thanks!

**Comment by farrokhpey** [comment]
sorry @felangel ,i cant share it, i haven't access to do this, it's on office github account and i can't change access
what did you need, ask me to explain it, sorry

**Comment by felangel** [comment]
Can you create a simplified version just to illustrate the issue?

**Comment by farrokhpey** [comment]
OK, but can u explain how can i use Base Bloc Classes, i mean that we have 3 class for bloc, event and state and then extend other blocs from them, override needed methods, add additional events and states and more.
I'll create a repository

**Comment by felangel** [comment]
It's likely because your base class isn't providing the specific generics so the types resolve to `dynamic`. I would be able to better assist if you provide a sample repo though, thanks!

**Comment by felangel** [comment]
@farrokhpey closing for now but feel free to comment with additional information and I'm happy to continue the conversation 👍
