### ISSUE TITLE
The example of flutter_dynamic_form typos

### ISSUE THREAD

**Issue by zengzhengrong** [felangel/bloc#647]
**Describe the bug**
new_car_repository.dart
```
Future<List<String>> fetchYears({String brand, String model}) async {
```
```
case 'Toyota':
        switch (model) {
          case 'Corrolla':
            return ['2015', '2014'];
```
The ```Corrolla``` should be  ``` Corolla```

**Comment by felangel** [comment]
Hi @zengzhengrong 👋 
Thanks for opening an issue!

I'll make the fix shortly, thanks for catching this 👍

**Comment by felangel** [comment]
Fixed in https://github.com/felangel/bloc/commit/6ed9ddbc459689f8d2e930b47d3c04d2d89eae18 👍
