### ISSUE TITLE
Reuse the view for different screens

### ISSUE THREAD

**Issue by hahai96** [felangel/bloc#651]
Hi. I have 2 screens that use ItemWidget. I provide the bloc through blocProvider, but when I open screen A, I will get an error without the context of screen B.
I can pass the bloc as a parameter, or use inheritFromWidgetOfExactType, but don't know if that's the best way?
What is the best way to solve this problem? Thank you very much.

```
class ClassA extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider.value(value: BlocA(), child: ItemWidget(index: 0));
  }
}

class ClassB extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider.value(value: BlocB(), child: ItemWidget(index: 0));
  }
}

class ItemWidget extends StatelessWidget {
  final int index;

  ItemWidget({this.index});

  @override
  Widget build(BuildContext context) {
    //get Error
    BlocA _blocA = BlocProvider.of<BlocA>(context);
    BlocB _blocB = BlocProvider.of<BlocB>(context);

    return ListTile(
      title: Text('$index'),
    );
  }
}
```

**Comment by felangel** [comment]
Hi @hahai96 👋 
Thanks for opening an issue!

You need to provide your bloc at the closest common ancestor of the widgets that need access. In this case you probably need to lift blocs A and B up in the widget tree.

If that doesn’t help can you please share a link to a sample app which illustrates the problem you’re having? Thanks!
