### ISSUE TITLE
More robust type-checking mechanism in Timer example

### ISSUE THREAD

**Issue by imckl** [felangel/bloc#652]
**Is your feature request related to a problem? Please describe.**
I'm learning to use bloc flutter step by step and type code while reading [Timer Tutorial](https://bloclibrary.dev/#/fluttertimertutorial).
Unfortunately, I've made a typo in timer_bloc.dart -> _mapResumeToState, 
on which: `if (state is Paused)` - typo as: `if (state is Pause)`

This makes resume not work as expected. I admit this is failed by me and it's rare to had this typo, but it does happened :(

**Describe the solution you'd like**
I didn't find this typo when checking my code until do a diff onto sample code, finally finding it types as 'Pause' instead of 'Paused' (In my mind, when checking my code it is in 'Pause' state and it's right, there is no typo here, lol)

For further testing, this if-condition accept any class/enum object.
This tiny typo is really hard to notice, without obvious warning by IDE.

**Describe alternatives you've considered**
Is there a better approach to check state, with strong type-checking mechanism?
For example, when using switch-case for enum, Android Studio will warn about "Missing case clause for 'enum_elem'"
![image](https://user-images.githubusercontent.com/20377660/68208417-0dd6a600-000c-11ea-8d17-a0abd4ce3c8e.png)

**Additional context**
Further thought, by naming state/event with prefix State, such as StatePaused, EventPause could nearly eliminate all typos like this. But it seems too verbose and trivia.

**Comment by imckl** [comment]
Duplicate of #482

**Comment by felangel** [comment]
Hey @imckl 👋
Thanks for opening an issue!

Unfortunately, dart doesn’t natively support sealed classes (yet) but you can take a look at [sealed_flutter_bloc](https://pub.dev/packages/sealed_flutter_bloc#-readme-tab-) and the [sealed_flutter_bloc_samples](https://github.com/felangel/sealed_flutter_bloc_samples) for one way to solve this currently.

The code you’re probably interested in is:
https://github.com/felangel/sealed_flutter_bloc_samples/blob/cd5d24c02a08b525bdc84b9b35b9feebf9a524f9/sealed_flutter_infinite_list/lib/bloc/post_bloc.dart#L33

Hope that helps 👍

**Comment by imckl** [comment]
Thanks! I'll walk through to the sample code.
