### ISSUE TITLE
Listen to other BLOC events

### ISSUE THREAD

**Issue by hahai96** [felangel/bloc#653]
I have 2 items ChildA and ChildB are children of ParentX. Because they are equal, it is difficult to exchange bloc with each other. So I use BlocParent as an intermediary, to exchange data between childA and childB. But blocParent always has to convert ChildB events into state before childA can listen. 
I feel that in this case changing the event to ParentBloc's state is quite redundant, can we listen to the change of events? Listening to status changes is still a great feature on a case by case basis.
Thank you very much. Sorry for my bad english.

![image](https://user-images.githubusercontent.com/23280338/68211839-ec28ef00-000a-11ea-924f-d0c816c27bcf.png)

**Comment by felangel** [comment]
Hi @hahai96 👋 
Thanks for opening an issue!

Since events are the input to the bloc and states are the output, this would be an anti-pattern. Can you share a link to a sample app which illustrates your problem and I can take a closer look and provide feedback? Thanks!

**Comment by hahai96** [comment]
@felangel I want when I click the reply button in childA, childB is focused. I would have to create a focusChildA state at the parent bloc to forward them. I think that's superfluous, because I don't need to handle anything, I just need to call yield focusChildA
I don't want to put all of them in one bloc, which will make the bloc bloated and difficult to maintain
![image](https://user-images.githubusercontent.com/23280338/68214816-bb4bb880-0010-11ea-9fba-cb6676336e5f.png)

**Comment by felangel** [comment]
@hahai96 I would need to see a sample app with your setup in order to better assist. In the screenshot, I'm not sure why ChildB would need to know about ChildA.

**Comment by anticafe** [comment]
@felangel As my understanding, in ChildA there is a Reply button. When touch on it, then the TextField in ChildB will be focus.

**Comment by felangel** [comment]
@anticafe if it's just about changing focus you probably don't need bloc for this since there is no business logic. Let me know if that helps and thanks for the clarification 👍

**Comment by felangel** [comment]
Closing for now as I don't have enough information to help. Feel free to comment with additional info and I'm more than happy to continue the conversation 👍

**Comment by hahai96** [comment]
@felangel Focus is just a simple example.In fact, when I press the reply button, I want to pass the comment owner information to childB.

**Comment by felangel** [comment]
@hahai96 you should then have a shared bloc at the common ancestor of the widgets so that the children can all access the same bloc's state.
