### ISSUE TITLE
 BlocProvider.of() called with a context that does not contain a Bloc of type ItemBloc.

### ISSUE THREAD

**Issue by tobitoi** [felangel/bloc#656]
Hello sir,

I have issue with edit data form when i try submit the data always 
Exception caught by gesture ═══════════════════════════════════════════
        BlocProvider.of() called with a context that does not contain a Bloc of type ItemBloc.

 button edit come from inifitie list and navigate to form [https://github.com/tobitoi/mobile_version/blob/master/lib/ui/item/item_list.dart](url)

and in form i try like Todo Example
[https://github.com/tobitoi/mobile_version/blob/master/lib/ui/widgets/form_item.dart](url)

username and password check the email

tobitoii08@gmail.com

**Comment by felangel** [comment]
Hi @tobitoi 👋 
Thanks for opening an issue!

The problem is you're pushing a new page route which does not have access to the `ItemBloc` because `BuildContext` is not shared across different routes.

```dart
onPressed: () =>  Navigator.push(context,
        MaterialPageRoute(builder: (context) {
          return 
          FormAddItem(
            key: ArchSampleKeys.addItemScreen,
            onSave: (itemName, serialNumber, ip, status,category, location, date, desc ) {
              bloc.add(AddItem(
                Item(
                  itemName: itemName, 
                  serialNumber: serialNumber,
                  ipAddress: ip,
                  status: status,
                  category: category ,
                  location: location,
                  dateCreation: date,
                  description: desc
                )
              ),
            );
          },
          isEditing: false,
          );
        })
      ),
```

You should wrap your new route in a `BlocProvider` in order to make the existing bloc available to the new route

```dart
onPressed: () =>  Navigator.push(context,
    MaterialPageRoute(builder: (_) {
        return BlocProvider.value(
            value: BlocProvider.of<ItemBloc>(context),
            child: FormAddItem(...),
        );
    })
),
```

You can read more about this in the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess) 👍

**Comment by tobitoi** [comment]
thank you its work

**Comment by tobitoi** [comment]
sir i have one question how better to handle token expired ?

in recent repository im expected can direct to login page

**Comment by felangel** [comment]
I would recommend having your http client automatically handle refreshing expired tokens. You can use dio + interceptors or implement our own wrapper around the dart http client. Then you can expose a token refresh failure callback and add a TokenRevoked event to your AuthenticationBloc in order to force logout the user. Hope that helps 👍

**Comment by tobitoi** [comment]
I already try add interceptors like that
 dio.interceptors
        .add(InterceptorsWrapper(onRequest: (RequestOptions options) async {
      SharedPreferences prefs = await SharedPreferences.getInstance();

      String token = prefs.getString('access_token');

      if (token != null) {
        options.headers['Authorization'] = 'Bearer $token';
      }

      options.headers['Accept'] = 'application/json';

      return options; //continue
    }, onError: (DioError e) async {
      final r = e.response;
      if (r.statusCode == 401) {
        AuthStore().unauthorize(prefs: _sharedPreferences);
      }

      if (r != null) {
        return {"has_error": true, ...r.data};
      }
      // Do something with response error
      return e;
    }));

And next step i dont know how to revoke the token. Any suggestion?

**Comment by tobitoi** [comment]
one question more i tried implement feature search in infinite list.
now its working but i have bug the CircularProgressIndicatorindicator always show. and if i clear the search text the item not loading again 
![Capture](https://user-images.githubusercontent.com/20135081/68390922-4e1b5d00-01a1-11ea-8fe0-58b995bb903f.PNG)

link directory bloc => https://github.com/tobitoi/mobile_version/blob/master/lib/bloc/item/item_bloc.dart

link ui =>https://github.com/tobitoi/mobile_version/blob/master/lib/ui/item/item.dart

**Comment by zeucxb** [comment]
If do you have multiple blocs that are shared. You should check `GetIt`.

> And use something like:
```dart
BlocBuilder<AppBloc, AppState>(
    bloc: GetIt.I<AppBloc>(),
    builder: (BuildContext context, AppState state) =>
        state.isLoggedIn ? TabControllerWidget() : InitialScreen(),
),
```

```dart
GetIt.I<AuthService>().saveToken('teste');

GetIt.I<AppBloc>().add(RefreshLoginEvent());

Navigator.pop(context);
```

**Comment by tobitoi** [comment]
Yea i 

> If do you have multiple blocs that are shared. You should check `GetIt`.
> 
> > And use something like:
> 
> ```dart
> BlocBuilder<AppBloc, AppState>(
>     bloc: GetIt.I<AppBloc>(),
>     builder: (BuildContext context, AppState state) =>
>         state.isLoggedIn ? TabControllerWidget() : InitialScreen(),
> ),
> ```
> 
> ```dart
> GetIt.I<AuthService>().saveToken('teste');
> 
> GetIt.I<AppBloc>().add(RefreshLoginEvent());
> 
> Navigator.pop(context);
> ```

Yea im using multi bloc to

**Comment by tobitoi** [comment]
> If do you have multiple blocs that are shared. You should check `GetIt`.
> 
> > And use something like:
> 
> ```dart
> BlocBuilder<AppBloc, AppState>(
>     bloc: GetIt.I<AppBloc>(),
>     builder: (BuildContext context, AppState state) =>
>         state.isLoggedIn ? TabControllerWidget() : InitialScreen(),
> ),
> ```
> 
> ```dart
> GetIt.I<AuthService>().saveToken('teste');
> 
> GetIt.I<AppBloc>().add(RefreshLoginEvent());
> 
> Navigator.pop(context);
> ```

Do you have spesifik referense? 🙏🙏

**Comment by dkobia** [comment]
@felangel I'm finding that wrapping the new route with an existing Bloc, seems to dispose the Bloc when the route is popped, leading to `Bad state: Cannot add new events after calling close` when you try to navigate back to that route again.

```
onPressed: () =>  Navigator.push(context,
    MaterialPageRoute(builder: (_) {
        return BlocProvider.value(
            value: BlocProvider.of<ItemBloc>(context),
            child: FormAddItem(...),
        );
    })
),
```

**Comment by dkobia** [comment]
nm - `BlocProvider<BlocX>.value` provides the necessary fix for the above

**Comment by tobitoi** [comment]
hello @felangel can you take a look my interceptors always error => see image 
=> link intercepstors https://gist.github.com/tobitoi/d6f6d26a7d9398c1046df18d804ff895
![Capture](https://user-images.githubusercontent.com/20135081/69466356-c21f4d00-0dbe-11ea-97a2-6302b23c45d8.PNG)

**Comment by felangel** [comment]
Hi @tobitoi you don't have access to `BuildContext` in your interceptor and you're trying to do a lookup using a null context. You shouldn't be trying to do the lookup outside of the widget tree. Instead, you should inject the bloc into the interceptor via constructor. Hope that helps 👍

**Comment by tobitoi** [comment]
thank you for respon, now im already update my interceptor to inject the auth bloc but always link => https://gist.github.com/tobitoi/d6f6d26a7d9398c1046df18d804ff895 

> Failed assertion: line 11 pos 58: 'userRepo != null': is not true. 

can you help how to make it userRepo not null, @felangel

**Comment by felangel** [comment]
@tobitoi can you share the code where you create the interceptor?

**Comment by tobitoi** [comment]
here the link @felangel 
 
>  https://gist.github.com/tobitoi/d6f6d26a7d9398c1046df18d804ff895

**Comment by felangel** [comment]
@tobitoi sorry I meant can you share where you create `BaseApi`?

**Comment by tobitoi** [comment]
here link my repo base_api 

> https://github.com/tobitoi/mobile_version/blob/master/lib/data/config/base_api.dart

**Comment by tobitoi** [comment]
im already push the new base api @felangel

**Comment by felangel** [comment]
@tobitoi but where do you create an instance of `BaseApi`?

```dart
final baseApi = BaseApi(...);
```

**Comment by tobitoi** [comment]
im already try like this 

> import 'package:mobile_version/data/response/login_response.dart';
import 'package:mobile_version/repository/repo.dart';
import '../config.dart';
import '../constant.dart';

> > class LoginApi {
> 
>   BaseApi _baseApi = BaseApi();
>   final userRepo = UserRepo();
> 
>   Future<LoginResponse> login(String username, String password) async {
>     final response = await _baseApi.dio
>         .post(loginUrl, data: {"username": username, "password": password});
>     if (response.statusCode == 200) {
>       return LoginResponse.fromJson(response.data);
>     }
>      throw response.statusMessage;
>   }
> }
but some error like the pict. i don't know whats wrong 
![Capture](https://user-images.githubusercontent.com/20135081/69507772-9f339b00-0f6e-11ea-8069-92797c7bc1fe.PNG)

**Comment by felangel** [comment]
You need to actually inject the repository like:
```dart
BaseApi _baseApi = BaseApi(UserRepository());
```

**Comment by tobitoi** [comment]
i tried like this `BaseApi _baseApi = BaseApi(UserRepository());`

but the errror still same @felangel

**Comment by felangel** [comment]
@tobitoi can you please provide steps to reproduce the issue? Do i have to login? If so what credentials can I use?

**Comment by tobitoi** [comment]
im already email username and password please check it  @felangel 

tobitoii08@gmail.com

**Comment by felangel** [comment]
@tobitoi thanks but once I login what do I need to do to reproduce the error?

**Comment by tobitoi** [comment]
@felangel basically i want if token expired direct to login form and delete the token expired  just change the 401(expired) to 403(access denied and redirec to login again) to test it  in interceptors => https://github.com/tobitoi/mobile_version/blob/master/lib/data/config/base_api.dart

**Comment by felangel** [comment]
@tobitoi thanks for clarifying. I took a look and you are not using dependency injection at all (you're instantiating empty `BaseApi()` instances all over the place and also have a circular dependency:

UseRepository -> LoginApi -> BaseApi -> UserRepository

This doesn't make sense; BaseApi should not have a dependency on UserRepository.

Sorry I'm not able to give a quick fix because I think you need to refactor a significant amount of your code in order to resolve the two issues I mentioned above. Hope that helps 👍

**Comment by felangel** [comment]
@tobitoi I created https://github.com/tobitoi/mobile_version/pull/1 as a temporary fix but you need to read about dependency injection and either use `RepositoryProvider` or some other DI to clean up the dependency graph in your project.

**Comment by tobitoi** [comment]
thank you alot @felangel. do you have reference for DI

**Comment by tobitoi** [comment]
thank you alot @felangel. do you have reference for DI

**Comment by felangel** [comment]
@tobitoi check out [dependency injection](https://en.wikipedia.org/wiki/Dependency_injection) for an overview and once you have a good understanding then I'd recommend looking at [RepositoryProvider](https://github.com/felangel/bloc/issues/519#issuecomment-532031164) 👍

**Comment by tobitoi** [comment]
Base on my understanding in #519 better to inject all repository in root of app ? Or just userRepository? Correct me if im wrong @felangel
