### ISSUE TITLE
Bloc dependency on multiple blocs

### ISSUE THREAD

**Issue by FilipKvestak** [felangel/bloc#658]
Hello,

I'm stuck with something, still learning dart/flutter.

How would You use 2+ blocs, INSIDE of 1 bloc?

e.g in Your todos app, filtered_todos_bloc.dart:

```
class FilteredTodosBloc extends Bloc<FilteredTodosEvent, FilteredTodosState> {
  final TodosBloc _todosBloc;
  StreamSubscription _todosSubscription;

  FilteredTodosBloc({@required TodosBloc todosBloc})
      : assert(todosBloc != null),
        _todosBloc = todosBloc {
    _todosSubscription = todosBloc.listen((state) {
      if (state is TodosLoaded) {
        add(UpdateTodos((todosBloc.state as TodosLoaded).todos));
      }
    });
  }

  @override
  FilteredTodosState get initialState {
    final currentState = _todosBloc.state;
    return currentState is TodosLoaded
        ? FilteredTodosLoaded(currentState.todos, VisibilityFilter.all)
        : FilteredTodosLoading();
  }
}
```
I was thinking about something like this:

```
class FilteredTodosBloc extends Bloc<FilteredTodosEvent, FilteredTodosState> {
  final TodosBloc _todosBloc;
  StreamSubscription _todosSubscription;

  final AnotherBloc _anotherBloc;
  StreamSubscription _anotherSubscription;

  FilteredTodosBloc({@required TodosBloc todosBloc, @required AnotherBloc anotherBloc})
      : assert(todosBloc != null, anotherBloc != null),
        _todosBloc = todosBloc, _anotherBloc = anotherBloc {
    _todosSubscription = todosBloc.listen((state) {
      if (state is TodosLoaded) {
        //add(UpdateTodos((todosBloc.state as TodosLoaded).todos));
        _anotherSubscription = _anotherBloc.listen((state) {
          if (state is AnotherStateLoaded) {
            doSomething()
          }
        });
      }
    });
  }
}
```
But I feel that it is just bad practice, and wouldn't work as expected.

To be specific, in my database (firestore) let's say I have 3 tables:

'user' table //each user has name, email, phoneNumber, etc.
'car' table //each car has brand, model, year, etc.
'user_car' table //represents cars for user, where each entry (document) is user's id, and under that document is plain list of strings (whole table could be fetched as Map<String, List>, where key is user's id, value is list of car id's)
On home screen I wan't to show all cars for user, so logically I need to fetch all 3 tables, but 'user-car' table needs 'users' and 'cars' first, so I could provide any data from those tables, based on data from 'user-car' table.

I know I could simply put list of car id's inside user table (same hierarchy as name, email, etc), but I like the idea of decoupling everything I can. I have bad history with older firebase database, because I had to restructure whole database/backend when app grew in production :)

How would You do it?

Thanks in advance.

**Comment by felangel** [comment]
Hi @FilipKvestak 👋 
Thanks for opening an issue!

I would not necessarily recommend having a bloc to manage each data source. Instead, I would recommend that your repository layer handles subscribing to the individual raw data sources and uses [combineLatest](https://pub.dev/documentation/stream_transform/latest/stream_transform/combineLatest.html) to handle reacting to the latest data from each stream. This will allow you to transform/normalize the data from your data sources and expose a single stream with the data model your bloc can consume.

Hope that helps 👍
