### ISSUE TITLE
How to keep index from ListViewBuilder using BlocBuilder

### ISSUE THREAD

**Issue by Milansu** [felangel/bloc#662]
So I have a few TabBar's with TabBarView's, I'm using BLoC like intended,
```dart
 if (state is RequestLoaded) {
        return state.request[i] == null
            ? Center()
            : ListView.builder(
            controller: _scrollController,
            itemCount: state.hasReachedMax ? state.request[i].length : state
                .request[i].length + 1,
            itemBuilder: (context, index) {
              return index >= state.request[i].length ? BottomLoader() : listViews(
                  context, state.request[i][index], index);
            });
      } else if (state is RequestLoading) {
        return Center(child: CircularProgressIndicator());
      }

      else if (state is RequestError) {
        return Center(
            child: Container(
              child: Text(state.message),
            ));
      }
```
I'm returning content per state, the issue I have is that when I switch tab's, the widget returns the `CircularProgressIndicator` and then the widget is rebuilt, so the state is reset and I lose my `index` from `ListView.builder`.

If I don't `yield RequestLoading` in my Bloc, the widget won't rebuild and I keep my indexes, but if I swipe too fast I will make too much http requests in little time which returns null. If it's null then I can't show that request... That's where I'm stuck, therefore the `state.request[i] == null`. I need a way to try to make a request again or something... I'm not sure.

I'm also using `AutomaticKeepAliveClientMixin` with `keepAlive => true`, which works fine until I load the indicator which rebuilts the state ?

```dart
 if (!visitedList.contains(currentIndexCategory)) {
              yield RequestLoading();
              pageNumber = 0;
              final currentRequest = await fetchRequest(
                  currentIndexCategory, pageNumber);
              final previousRequest = currentListOfRequest[previousIndex] == null
                  ? await fetchRequest(previousIndexCategory, pageNumber)
                  : currentListOfRequest[currentIndex - 1];
              final nextRequest = currentListOfRequest[nextIndex] == null
                  ? await fetchRequest(nextIndexCategory, pageNumber)
                  : currentListOfRequest[currentIndex + 1];


              visitedList[nextIndex] = nextIndexCategory;
              visitedList[previousIndex] = previousIndexCategory;
              visitedList[currentIndex] = currentIndexCategory;

              currentListOfRequest[currentIndex] = currentRequest;
              currentListOfRequest[nextIndex] = nextRequest;
              currentListOfRequest[previousIndex] = previousRequest;

              yield RequestLoaded(currentListOfRequest, false, false, false);
            }
          }
```
I'm loading the adjecent Tab's in my Bloc, and keep a visited list so I don't load again.

I had it working with `FutureBuilder` where it worked fine, simply using `AsyncSnapshot` to check if `ConnectionStatus == Connectivity.waiting`.

**Comment by felangel** [comment]
Hi @Milansu 👋 
Thanks for opening an issue!

I'm not sure I completely understand but if you only want the UI to update for certain state changes then you can add a `condition` to your `BlocBuilder`. This would allow you to avoid rebuilding while still fetching more information asynchronously.

```dart
BlocBuilder<BlocA, BlocAState>(
  condition: (previousState, state) {
    // return true/false to determine whether or not
    // to rebuild the widget with state
  },
  builder: (context, state) {
    // return widget here based on BlocA's state
  }
)
```

**Comment by Milansu** [comment]
Each tab should remember remember it's ListviewBuilders index, so if I scrolled down in Tab1, and I load Tab3 if i visit Tab1 once again, I want to be at the index I last visited in that Tab1 (to save its state).

Problem is when I yield RequestLoading() that returns a CircularProgressIndicator which resets the state.
If I don't use it, I will sometimes get a null response because the http request didn't load yet.

Hope i explained it a bit better this time.
In your condition above is there a way to wait for the response, (without yielding RequestLoading()), and then show the Listview.builder?

**Comment by felangel** [comment]
Why not have a separate bloc to manage the index of each tab?

**Comment by Milansu** [comment]
Ugh, that sounds like a good idea. Would i add event on each index change? How would I manage between the two blocs...bloc that shows content and manges indexes?

**Comment by felangel** [comment]
You would just create the IndexBloc above the ContentBloc and it would have an `initialState => 0`. 

```dart
BlocBuilder<IndexBloc, IndexState>(
  builder: (context, index) {
    ...
  },
)
```

Then you can add an event each time the index has changed

```dart
BlocProvider.of<IndexBloc>(context).add(IndexChanged(index: newIndex));
```

**Comment by RollyPeres** [comment]
@Milansu I'm pretty sure you're not approaching this the right way. You should be fine with using `AutomaticKeepAliveClientMixin` but have the full page loading indicator only show for the first request, but when loading more then show that indicator at the bottom of your list. Have this load more flag be part of your state. Your scroll position will be saved while switching tabs. Showing a full page loading indicator for each request in a specific tab doesn't make sense when there's already some data there.

**Comment by Milansu** [comment]
@RollyPeres If you switch a tab it will fetch a new http request, and it will be null. If i dont show a full page loading indicator Im left with a null list.

**Comment by RollyPeres** [comment]
@Milansu You haven't described what you want to achieve very well, but from what I understood you're trying to handle pagination on multiple tabs within a single bloc. This is why I don't see why you want to show a full screen loading indicator when you go back to a page which already has some data already loaded. If you keep your tabs alive then data will be there.

**Comment by Milansu** [comment]
@RollyPeres You understood it , I shouldn't load a whole page indicator when there is data in previous tabs. But what do I show when I switch the tabs? It takes a bit time to load the data, and in that time I want to show the new content in the Listview.builder... That's where i will get a null return, unless I yield the Loading state :/

**Comment by RollyPeres** [comment]
@Milansu It's perfectly fine to show a full screen loading indicator when you first time land on a tab, since you've got no data there yet. But the second time you land there it should have some data already present or a message that there's no data for this tab. When you use keep alive mixin it will make sure your page states are not disposed, therefore you will not need to reload the existing data(the data will be present in your bloc state). When you go back to a certain already visited tab, it will be exactly how you left it. Also, your bloc state should have multiple lists of data, one for each tab. You might even have a `List<List<Model>>` if your model is the same on each tab, maybe the only difference being let's say a category type, even though I would suggest something like having a `Map<CategoryType, List<Model>>` in this situation.

**Comment by Milansu** [comment]
@RollyPeres I do have `List<List<Model>>` where I track the already visited categories. When I load tab1 I also load tab2 and so on, but if i do it too quickly i will get null once again. I have initial state `InitialRequest()` when it's done it yields a `RequestLoaded()` and that state stays. So when I switch the tabs really quickly the state stays the same `RequestLoaded()` and tries to show the data that's not yet loaded in the listview.builder.

**Comment by felangel** [comment]
@Milansu it would be much easier to help if you could put together a sample app which illustrates the project structure and issues you are having.

**Comment by Milansu** [comment]
Here's a sample project [https://gitlab.com/Milansu/jsonplaceholder]

**Comment by felangel** [comment]
@Milansu thanks! I’ll take a look shortly 👍

**Comment by Milansu** [comment]
Fixed it, i guess xD

**Comment by felangel** [comment]
@Milansu thats awesome! Are you happy with your solution or did you still want me to take a look?

**Comment by Milansu** [comment]
@felangel No it's fine, this will do! Thanks
