### ISSUE TITLE
How can i help with the translation?

### ISSUE THREAD

**Issue by rodriguesJeff** [felangel/bloc#667]
Hello, I am a Brazilian flutter developer and I want to know if this is an open source project. At the moment, I'm learning bloc and found this repository. I saw the pt-br option, but dn't have content. So I want to contribute to the project. Can I do a PR and help with translation?

**Comment by felangel** [comment]
Hey @rodriguesJeff 👋 
Thanks for opening an issue!

There’s a draft pull request that has some of the translations in progress and it was being worked on by two developers. I think we can close this issue and continue the conversation on the pull request to have them add you as a collaborator. If you have time you can just start translating the docs locally and then hopefully within a few hours you will be added and can push your updates. Thanks so much for reaching out and offering to help. I really appreciate it 🙏
