### ISSUE TITLE
mysterious bug

### ISSUE THREAD

**Issue by bernaferrari** [felangel/bloc#669]
Hello. I am having a really really weird bug in a project and I was able to replicate into a simpler project. Basically, when changing screen (with `maintainState = false`) one bloc is still saved.. so I get two instances of the same bloc triggering BlocBuilder twice and considerably slowing down my project!

I'm not even sure if I explained correctly (therefore, mysterious bug!), but here is a sample, and in that sample, when you run, you should tap to change screen and tap to update the counter.

You should see:

```
I/flutter (25496): BLOC CHANGED V: 7 INDEX: 1
I/flutter (25496): BLOC CHANGED V: 7 INDEX: 5
```
Which means both bloc 1 and 5 are awake. I don't know if this is a common bug or etc, but I don't even know what to search. Thanks!

[flutter_counter.zip](https://github.com/felangel/bloc/files/3842835/flutter_counter.zip)

**Comment by felangel** [comment]
Hi @bernaferrari 👋 
Thanks for opening an issue!

Are you able to create a gist or github repo instead of a zip? Thanks! 👍

**Comment by bernaferrari** [comment]
I am, but do you really want that? It is almost a one-file project. Everything else is just so you can build it.

**Comment by felangel** [comment]
yeah if you can just share the one file as a gist it would be great, thanks!

**Comment by bernaferrari** [comment]
Here it goes: https://gist.github.com/bernaferrari/ec57ce07ffcd59cbb85f1b01f9d8fef5

**Comment by felangel** [comment]
@bernaferrari when you use `Navigator.push` it does not remove the underlying widget. This is expected behavior and it doesn't have anything to do with the bloc library. If you want to dispose the underlying widget when you push then you can use `pushReplacement`. Let me know if that helps 👍

**Comment by bernaferrari** [comment]
Uh, thanks!
![image](https://user-images.githubusercontent.com/351125/68793818-7802d280-062c-11ea-8e51-b82fc596f866.png)
Ok... I thought `maintainState = false` was supposed to do this. PushReplacement doesn't keep anything, push keeps everything, push with maintainstate = false only keeps the first one. Really tricky.
