### ISSUE TITLE
[Proposal] New Communication Channel

### ISSUE THREAD

**Issue by warriorCoder** [felangel/bloc#670]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated... when I try to use gitter and the app just work on my desktop or phone. 

**Describe the solution you'd like**
I suggest moving to slack. 

**Describe alternatives you've considered**
Discord seems like a decent alternative but I think slack would be a better option in the long run.

**Comment by tenhobi** [comment]
I am also frustrated by Gitter, for sure.

Actually, a lot of open source projects use Discord for its ease-of-use and the price and overall feeling (it's open, easy to join, easy to modify, no limitations). For example /r/FlutterDev uses it.

Slack always seems very focused on corporations etc. Which is ok, but it is a bit off than what we need. If we should move, I would vote for Discord. More info at https://discordapp.com/open-source.

And I know there are also some/many projects using Slack, but I just see the opportunities in user roles, text & voice channels for free etc.

**Comment by jorgecoca** [comment]
This is all based on my personal preference, not in which one is better or not, but I'd prefer to use Slack simply because I have many other communities embedded in there as well

**Comment by KingDarBoja** [comment]
I do recommend Discord over Slack as you can make your own bots for free, have several cool features that Slack keeps on their premium tier and also, it has better code formatting :)

**Comment by anticafe** [comment]
Discord is good. But I realize it doesn't allow to reply in thread (and it seems Slack is the only chat app which allows to reply in thread). Only one thing I don't like Slack is its 10k message limit.

**Comment by felangel** [comment]
Hey everyone after careful consideration, we've decided to go with Discord as our new communication channel 🎉 

We can continue to evaluate the communication platform moving forward and if you have any concerns don't hesitate to let us know.

You can [join the server](https://discord.gg/Hc5KD3g) now and we'll try to slowly migrate everyone off of gitter over the next few weeks 👍 

Thanks to everyone who provided feedback and voted! 🙏
