### ISSUE TITLE
Example Flutter project that uses InheritedWidget with Blocs

### ISSUE THREAD

**Issue by ChristianKleineidam** [felangel/bloc#672]
I'm planning to build a bigger app with Flutter. At [Google I/O '18 ](https://youtu.be/RS36gBEp8OI)there was a talk that suggest that it's good to setup Blocs with InheritedWidget as that's supposed to scale better. 
Unfortunately, none of the current example projects for bloc show such a setup. It would be great to have an example project that shows the best practice.

**Comment by felangel** [comment]
Hi @ChristianKleineidam 👋 
Thanks for opening an issue!

`BlocProvider` uses `Provider` which is a wrapper around `InheritedWidget` so by using `BlocProvider`/`RepositoryProvider` you're already using `InheritedWidget`.

You can check out the [bloc access](https://bloclibrary.dev/#/recipesflutterblocaccess) recipe for more details and look at any of the [tutorials](https://bloclibrary.dev/#/fluttercountertutorial) for complete projects. Hope that helps 👍
