### ISSUE TITLE
Question: using bloc between multiple pages

### ISSUE THREAD

**Issue by petrnymsa** [felangel/bloc#673]
Hi
sorry if this not belong here but I could not find any forum. 

Let's say I have the application with movies and I can each movie mark as 'favourite'. And we have 3 pages:
- movie list page
- detail page of the movie
- favourites list page 

From each page, I can directly mark/unmark movie as favourited.  What is properly setup/architecture for this? 

- Having for each page own Bloc? (I am coming from MVC / MVVM world and this make 'sense' to me)
- Having top-level MoviesBloc and share this bloc on every page?

Data are stored in some abstract 'repository' layer. 
In case of having for each page its own bloc how can i orchestrate them? (e.g from detail movie was marked, how to propagate this change to another bloc..)

Also what we want to achieve
- rebuild movie widget within list only that change its state (marked/unmarked as a favorite), not the whole list
- when for example I mark as favourite within detail page, after I return (pop up the stack) back to list, change must be propagated. 

![bloc](https://user-images.githubusercontent.com/21087414/68981676-886da580-0804-11ea-9dca-037c846b91d1.png)

These are questions which I am a bit confused about. 
Thank you for any help!

**Comment by tenhobi** [comment]
Creating bloc per page is a good option, but you might want rather create one bloc per big enough functionality.

You would like to, probably, have one main Bloc for movie list, and some other Bloc to handle showing the individual movie, etc. 

Check `TodosBloc` and `FilteredTodosBloc` bloc-to-bloc communication at https://bloclibrary.dev/#/fluttertodostutorial

**Comment by felangel** [comment]
Hi @petrnymsa 👋 
Thanks for opening an issue!

As @tenhobi mentioned, I would recommend having a single bloc which manages the state of the movie list for the entire application. Each movie can include a property for whether it is a favorite. Changes in the favorites bloc can then update the movies bloc (analogous to how you can update a todo as done). Hope that helps and I'd definitely recommend looking at the [todos tutorial](https://bloclibrary.dev/#/fluttertodostutorial) for inspiration.

Hope that helps and feel free to ask any additional questions on [gitter](https://gitter.im/bloc_package/Lobby) 👍
