### ISSUE TITLE
[bloc_test] Add documentation for testing other than for State types

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [felangel/bloc#680]
I don't emit individual classes for different state changes because it adds a lot of unnecessary complexity in my use case. I just use properties of the state and use copyWith, like in Redux.
**Describe the solution you'd like**
Include documentation for how to test for things other than what class type the bloc emits.

**Describe alternatives you've considered**
I'm assuming we just use expect for this use case, right? 
If so, I expected to see a solution for that in the docs for bloc_test, even though it doesn't use the package.

**Additional context**

**Comment by felangel** [comment]
Hi @ThinkDigitalSoftware 👋 
Thanks for opening an issue!

Can you please provide a link/gist to a sample bloc which you'd like to test with bloc_test? I'll try to put together some tests for your sample bloc 👍

**Comment by felangel** [comment]
@ThinkDigitalSoftware closing this based on our conversations in gitter. Feel free to comment with additional info/questions and I'm happy to continue the conversation 👍
