### ISSUE TITLE
A bug in portuguese doc

### ISSUE THREAD

**Issue by rodriguesJeff** [felangel/bloc#687]
**Describe the bug**
When i translated i left a bug

In my repo i fixed this bug, so can i open a pull request for fix this in official site? 

**Expected behavior**
Image is expected to be below text. 
Is expected a link, but the page don't receives it

**Screenshots**
here
![image](https://user-images.githubusercontent.com/32440959/69340092-77c69080-0c45-11ea-9dd9-e1574fa1b3ed.png)
and here too
![image](https://user-images.githubusercontent.com/32440959/69340323-f7ecf600-0c45-11ea-854c-e25cdc4ed6de.png)

**Comment by felangel** [comment]
Hi @rodriguesJeff, thanks for bringing this up! Yeah you can definitely open a pull request to fix the issues you described! Thanks 😄

**Comment by felangel** [comment]
Fixed in https://github.com/felangel/bloc/commit/1379880c8e4c6bfe71ec3f36cef7ee6a325e55a4. Thanks for reporting this 👍
