### ISSUE TITLE
Bloc newbie question

### ISSUE THREAD

**Issue by ctippur** [felangel/bloc#688]
Hello,
We have a main.dart file and we are referencing video control code in a separate materialcontrol.dart file. 
We have a submit button in the materialcontrol.dart file and when the button is pressed, we add an event. 
We need to capture this event in the main.dart file. We have a bloc listener in main.dart and materialcontrol.dart files. We are able to listen to the event on only materialcontrol.dart but not on main.dart file. 
What am  I missing? I need to be able to listen to this event change in main.dart file.

**Comment by tenhobi** [comment]
@ctippur hello, can you show us some example of code, so we can look at it directly? Maybe create some small gist?

**Comment by felangel** [comment]
Hi @ctippur 👋 
Thanks for opening an issue!

As @tenhobi said, it would be great if you could share the link to a sample app which illustrates the problem you're having. Thanks!

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional information/link to a sample app and I'm happy to reopen the issue 👍
