### ISSUE TITLE
The method 'add' isn't defined for the class 'AuthenticationBloc' on the flutter login tutorial

### ISSUE THREAD

**Issue by sqrg** [felangel/bloc#689]
**Describe the bug**
The method 'add' isn't defined for the class 'AuthenticationBloc'.
Try correcting the name to the name of an existing method, or defining a method named 'add'.

**To Reproduce**
1. Follow the [flutter_login tutorial
](https://bloclibrary.dev/#/flutterlogintutorial)

**Comment by felangel** [comment]
Hi @sqrg 👋 
Thanks for opening an issue. 

Most likely the problem is you’re not using the latest versions of bloc and flutter_bloc. Can you please share your pubspec.yaml?

**Comment by sqrg** [comment]
Yup, that was exactly the problem! Thanks

**Comment by felangel** [comment]
Hi @jain-aayush1123 are you sure `flutter packages get` is running successfully?
You might also want to try `flutter clean` before `flutter packages get`.

**Comment by jain-aayush1123** [comment]
yeah thanks for the response. flutter packages get was working, there was some other problem. 
Btw love the library and have been using it for some time so was a bit surprised to see it fail. Thanks for the time
