### ISSUE TITLE
Only last yield is being received at BlocBuilder

### ISSUE THREAD

**Issue by pazhut** [felangel/bloc#691]
Considering the following code:

@override
  Stream<AuthenticationState> mapEventToState(
    AuthenticationEvent event
  ) async* {
    print("event $event");
    if (event is ScreenEntered) {
      yield* mapScreenEnteredToState();
    } else if (event is ClickedGoogleSignIn) {
      yield* mapClickedGoogleLoginToState();
    }
  }

  Stream<AuthenticationState> mapScreenEnteredToState() async* {

  }

  Stream<AuthenticationState> mapClickedGoogleLoginToState () async* {

    yield AuthInProgress(); //show progress bar

    try {

      FirebaseUser firebaseUser = await authenticationRepository.signInWithGoogle();
      //ToDo - do we need to check about profile data or this purely handled by next screen

      yield Authenticated(firebaseUser);

      add(LoggedIn(firebaseUser));

    } catch (_,stacktrace) {
      print(stacktrace);
      yield UnAuthenticated();
    }

  }

the first yield of AuthInProgress is never being received by the bloc builder, only the last yield is, i wonder if this is a normal behaviour  of i had run into an issue? 

if more information is needed please let me know

Thanks much

Paz

**Comment by felangel** [comment]
Hi @pazhut 👋 
Thanks for opening an issue!

Can you please share a link to a sample app that illustrates the issue? It would be much easier for me to take a look and offer feedback/recommendations. Thanks 👍

**Comment by pazhut** [comment]
Hi 

thanks for quick response, attached is the lib part of my project, i kept just the relevant files (so i am not sure if this will compile) it have all the Bloc related code, you should click the Google sign in button to kick start the process, note the difference between first click on the button 
[lib.zip](https://github.com/felangel/bloc/files/3879963/lib.zip)
and any other following it

Paz

**Comment by felangel** [comment]
@pazhut it's possible that `authenticationRepository.signInWithGoogle()` happens so fast and `AuthInProgress` and `Authenticated` are emitted back-to-back so `BlocBuilder` only processes `Authenticated`. You can confirm this by override `onTransition` in your bloc and printing each transition. If you see two transitions (`AuthInProgress`, followed by `Authenticated`) then it's most likely what I described above. If you're not seeing the `AuthInProgress` occur, however, then something is going wrong and you would need to share a fully functioning sample app in order for me to help.

Closing for now but feel free to comment with additional questions/feedback and I'm happy to continue the conversation 👍
