### ISSUE TITLE
blocTest 'Couldn't infer type' when only expecting one or more of the same type

### ISSUE THREAD

**Issue by arnemolland** [felangel/bloc#692]
I'm experiencing an issue where Dart complains when expecting one or more states of the same type in a `blocTest`. I'm normally using a linter, but I can confirm this occurs with the default rules as well.

My setup looks like this:
```dart
 setUp(() {
  repository = MockProfileRepository();
  bloc = ProfileBloc(repository: repository);
});
```
An example of what works:
```dart
blocTest(
  'emits [x, y]',
  build: () => bloc,
  expect: [
    InitialProfileState(),
    ProfileLoading(),
  ],
);
```
An example of what does not work:
```dart
blocTest(
  'emits [x, y]',
  build: () => bloc,
  expect: [
    InitialProfileState(),
    InitialProfileState(),
  ],
);
```
The error message I'm getting from Dart:
```
Couldn't infer type parameter 'B'.

Tried to infer 'ProfileBloc' for 'B' which doesn't work:
  Type parameter 'B' declared to extend 'Bloc<?, InitialProfileState>'.
The type 'ProfileBloc' was inferred from:
  Parameter 'build' declared as     'B Function()'
                    but argument is 'ProfileBloc Function()'.

Consider passing explicit type argument(s) to the generic.

dart(could_not_infer)
```
Does this issue lie within the library or am I maybe missing something?

**Comment by felangel** [comment]
Hi @arnemolland 👋 
Thanks for opening an issue!

The problem in the second scenario is that Dart infers the type of the states as `InitialProfileState` instead of `ProfileState`.

You should be able to fix this by just specifying the type of the `expect` like:

```dart
blocTest(
  'emits [x, y]',
  build: () => bloc,
  expect: <ProfileState>[
    InitialProfileState(),
    InitialProfileState(),
  ],
);
```

Let me know if that helps and in the meantime I'll see if there's anything I can do to improve the developer experience 👍

**Comment by arnemolland** [comment]
Ah, of course! Thanks for pointng that out 🙌 In this case I think the Dart warning itself was a little unclear compared to most type mismatch cases, even though I should’ve been able to catch it myself. 

If this is a common issue, it could be mentioned in the blocTest documentation. However, it’s not really up to each library to warn users about Dart’s own type system imo.

**Comment by felangel** [comment]
Awesome! Thanks for the feedback, I'll definitely update the docs to mention this 👍

**Comment by felangel** [comment]
Updated the docs in https://github.com/felangel/bloc/commit/2f2a9a0f014e41c0b5089e0c15838d093a58a2ce.
