### ISSUE TITLE
v0.* to v2 Migration guide?

### ISSUE THREAD

**Issue by nerder** [felangel/bloc#693]
**Is your feature request related to a problem? Please describe.**
I think a migration guide from `v1` to `v2` would be very handy and useful and even incentivize the upgrade.

**Describe the solution you'd like**
A migration guide

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by felangel** [comment]
Hi @nerder 👋 
Thanks for opening an issue. The migrations steps can usually be found by going through the [changelog](https://github.com/felangel/bloc/blob/master/packages/bloc/CHANGELOG.md). In this case, v2.0.0 links to https://github.com/felangel/bloc/issues/639 which has migration steps listed (https://github.com/felangel/bloc/issues/639#issuecomment-549497003).

I've also updated the README to include a link to a [migration guide](https://dev.to/mhadaily/upgrade-to-bloc-library-v1-0-0-for-flutter-and-angular-dart-2np0) put together by a member of the community (https://github.com/felangel/bloc/commit/ea76f318105e91f473c6b01cd126dac004b6dcd6). Hope that helps 👍
