### ISSUE TITLE
It is need a blocDelegate Union

### ISSUE THREAD

**Issue by huang12zheng** [felangel/bloc#697]
I need to a lot of delegate, maybe. it is ugly to use extends. Since that, I code as follow:
```dart
import 'package:bloc/bloc.dart';
class DelegateBuilder extends BlocDelegate{
  List<BlocDelegate> lists=[];

  @override
  onEvent(Bloc bloc, Object event) {
    super.onEvent(bloc, event);
    lists.forEach((delegate)=>{
      delegate.onEvent(bloc, event)
    });
  }

  @override
  void onTransition(Bloc bloc, Transition transition) {
    super.onTransition(bloc, transition);
    lists.forEach((delegate)=>{
      delegate.onTransition(bloc, transition)
    });
  }

  @override
  void onError(Bloc bloc, Object error, StackTrace stacktrace) {
    super.onError(bloc, error, stacktrace);
    lists.forEach((delegate)=>{
      delegate.onError(bloc, error, stacktrace)
    });
  }

  add(List<BlocDelegate> delegates) {
    if (delegates != null)
      lists.addAll(delegates);
  }
}
```
```dart
void startup() async {
  FlutterError.onError = (FlutterErrorDetails details) {
    Zone.current.handleUncaughtError(details.exception, details.stack);
  };
  BlocSupervisor.delegate = DelegateBuilder()
    ..add([PassportDelegate(),SimpleBlocDelegate(), GroupRoleDelegate()])  ;
  // HydratedBlocDelegate.build() 

  runZoned(
```
And, use Case:
```dart
class PassportDelegate extends BlocDelegate{
  @override
  void onEvent(Bloc bloc, Object event) {
    // TODO: implement onEvent
    super.onEvent(bloc, event);
      if (event is IsLoginEvent) {
        throw '未登陆';
      }
      
    
  }
  @override
  void onError(Bloc bloc, Object error, StackTrace stacktrace) {
    super.onError(bloc, error, stacktrace);
    // print(error);
    Toast.show(msg: error);
  }
}
```

is It any suggestion?

**Comment by felangel** [comment]
Hi @huang12zheng 👋 
Thanks for opening an issue!

Can you please provide more information regarding what the different delegates are used for? You should generally prefer wrapping your bloc code in try/catch and handle custom error logic within each bloc.

**Comment by huang12zheng** [comment]
when I click like button, I would check that is user login.&nbsp;
or when&nbsp;I click like button in some page (group page) .&nbsp;I would check that is user is a member.&nbsp;
in this example I give ,&nbsp; I think a delegate is a good solution.&nbsp; &nbsp; do something I&nbsp; not find?&nbsp;



---Original---

**Comment by felangel** [comment]
@huang12zheng I think you should handle checking if the user is a member within the bloc that  cares rather than making that logic global. The delegate should ideally be reserved for global handling of errors/events/transitions for things like logging/analytics.

**Comment by huang12zheng** [comment]
For Like, favorites, comment button, click it, it sends a LikeEvent,UnLikeEvent, FavoriteEvent,UnFavoriteEvent...
In my logic, these buttons are only related to its events. But because of some of the scenarios above, I need to intercept these events and toast error for them.
----
On my understanding, you suggested that I put this judgment in Bloc.
If I put it on LikeEvent, it's not very good, because I think the judgment of the callback is independent of the code for the button.[Maybe just to make a small piece of code]
If I put it on LikeBloc.OnEvnet, there may be a lot of code (judgment of login, judgment of member, and judgment of something in future), which may accumulate a lot of code
If I put it on a new Bloc, like UserGroupStateBloc, UserLoginStateBloc, it's hard to know the event name LikeEvent.

**Comment by huang12zheng** [comment]
Just Thank you very much.

**Comment by felangel** [comment]
@huang12zheng I think if you have a FavoritesBloc which can emit a FavoriteFailure state (in the case of some network error) you can have a BlocListener to show a toast like:

```dart
BlocListener<FavoritesBloc, FavoritesState>(
  listener: (context, state) {
    if (state is FavoritesFailure) {
      Scaffold.of(context)
        ..hideSnackBar()
        ..showSnackBar(FailureSnackBar());
    }
  },
  child: MyChild(),
),
```

You can also check out the [SnackBar Recipe](https://bloclibrary.dev/#/recipesfluttershowsnackbar) for more information.

Let me know if that helps.

**Comment by huang12zheng** [comment]
thank for reply.&nbsp;
checking and getting a&nbsp;eventResult in backend. it is a good idea.&nbsp; but I need to do some review.&nbsp; it is help for me.&nbsp;



---Original---

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
