### ISSUE TITLE
2.1.0 doesn't compile

### ISSUE THREAD

**Issue by omarbelkhodja** [felangel/bloc#699]
After upgrading to the latest version 2.1.0, I was not able to compile my project again, because of the following error :

```
packages/flutter_bloc/src/repository_provider.dart:27:11: Error: No named parameter with the name 'create'.
          create: create ?? builder,
          ^^^^^^
```

**To Reproduce**
Add the following to your project

```
dependencies:
  flutter_bloc: ^2.1.0
```

**Comment by felangel** [comment]
Hi @omarbelkhodja 👋 
Thanks for opening an issue!

This is my fault, I didn't enforce `provider >= 3.2.0`.
It has been fixed in flutter_bloc v2.1.1 👍
