### ISSUE TITLE
Do I need to create 2 Widgets? (Login example)

### ISSUE THREAD

**Issue by joaogalli** [felangel/bloc#701]
Hi, I am following the Login example, and noticed that I need to have the LoginPage and the LoginForm widgets for bloc to work.
Of course I tried to do both on the same Widget (LoginPage), but the BlocListener doesn't work.

Is there a way, or the example is the only right way?

**Comment by felangel** [comment]
Hi @joaogalli 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the problem you’re having? Thanks!

**Comment by joaogalli** [comment]
Thanks for your response, I don't have a different code from yours, I was just trying to do everything in the same Widget, like this:
`class LoginPage extends StatelessWidget {
  final UserRepository userRepository;

  LoginPage({Key key, @required this.userRepository})
      : assert(userRepository != null),
        super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Login'),
      ),
      body: BlocProvider(
        create: (context) {
          return LoginBloc(
            authenticationBloc: BlocProvider.of<AuthenticationBloc>(context),
            userRepository: userRepository,
          );
        },
        child: return BlocListener<LoginBloc, LoginState>(
      listener: (context, state) {
        if (state is LoginFailure) {
          Scaffold.of(context).showSnackBar(
            SnackBar(
              content: Text('${state.error}'),
              backgroundColor: Colors.red,
            ),
          );
        }
      },
      child: BlocBuilder<LoginBloc, LoginState>(
        builder: (context, state) {
          return Form(
            child: Column(
              children: [
                TextFormField(
                  decoration: InputDecoration(labelText: 'username'),
                  controller: _usernameController,
                ),
                TextFormField(
                  decoration: InputDecoration(labelText: 'password'),
                  controller: _passwordController,
                  obscureText: true,
                ),
                RaisedButton(
                  onPressed:
                      state is! LoginLoading ? _onLoginButtonPressed : null,
                  child: Text('Login'),
                ),
                Container(
                  child: state is LoginLoading
                      ? CircularProgressIndicator()
                      : null,
                ),
              ],
            ),
          );
        },
      ),
    );,
      ),
    );
  }
}`

**Comment by joaogalli** [comment]
Thanks for your response, I don't have a different code from yours (Login Example), I was just trying to do everything in the same Widget.
In [LoginPage](https://github.com/felangel/bloc/blob/master/examples/flutter_login/lib/login/login_page.dart) there is the creation of LoginForm at line 29.
I just tried to return the blocListener of [LoginForm](https://github.com/felangel/bloc/blob/master/examples/flutter_login/lib/login/login_form.dart) at line 25.
But it never get called, like it would if they are in separate widgets.

**Comment by felangel** [comment]
@joaogalli so you just have one StatefulWidget? It should work the same way. Are you able to share a link to your GitHub repository? I can take a look and create a pull request to fix any issue I find.

**Comment by joaogalli** [comment]
Sorry, I don't have it on a repository, I will try some more and return with what I find.

**Comment by felangel** [comment]
Sounds good. If it’s easier you can also create a [gist](https://gist.github.com) and share the link 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions or comments and I'm happy to continue the conversation
