### ISSUE TITLE
refresh part of screen can be done with Bloc?

### ISSUE THREAD

**Issue by MahdiPishguy** [felangel/bloc#706]
i have a simple question. how can i refresh part of screen with bloc? for example you suppose we have weather sample as you put in github,

in that we suppose we have a listview below of city name, and thats get some other cities list to show temperatures. when we scrolling down and we want to reload again this list, can be doable with Bloc pattern?

i guess i can introduce  [`StateRebuild`](https://pub.dev/packages/states_rebuilder) pattern which we can refresh simple part of our UI

**Comment by RollyPeres** [comment]
You should use `BlocBuilder`'s as deeply as possible in your widget tree as well as utilize it's `condition` parameter. In your example you would probably have a single bloc where you would handle all cities. `ListView` would handle lazy loading of items for you from bloc state.

**Comment by felangel** [comment]
Hi @MahdiPishguy 👋 
Thanks for opening an issue!

As @RollyPeres mentioned you can just wrap the part of your ui that you want to change in BlocBuilder and add a condition to optionally have more control over how often it rebuilds. You can check out the [timer tutorial](https://bloclibrary.dev/#/fluttertimertutorial) for an example.

Hope that helps! 👍

**Comment by MahdiPishguy** [comment]
@felangel Thanks a lot, but i'm not sure to understand how ca i do that, could you help me more please?

**Comment by felangel** [comment]
@MahdiPishguy can you share a sample app or something concrete that you’re having issues with? It’s hard to help without having any context.

**Comment by MahdiPishguy** [comment]
> 
> 
> @MahdiPishguy can you share a sample app or something concrete that you’re having issues with? It’s hard to help without having any context.

yes. sure, i'll made a simple product for this issue and let me notify you to describe more about that, Thanks
