### ISSUE TITLE
google sign in does not work, flutter firebase login

### ISSUE THREAD

**Issue by gogreen42** [felangel/bloc#716]
**Describe the bug**

I can register and login by email.
when I choose an account from google sigh in I stay on Login page.
And I get 'int android.view.View.getVisibility()' on a null object reference 

**To Reproduce**

1. Click on Sigh in Google button
2. Choose your account
3. See error
![Screenshot_24](https://user-images.githubusercontent.com/19793832/70551714-b84c6680-1b80-11ea-9744-8b8474ca55c7.png)

**Comment by felangel** [comment]
Hi @gogreen42 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the issue? Also, have you tried running the [firebase login example](https://github.com/felangel/bloc/tree/master/examples/flutter_firebase_login)? You need to make sure you follow the [instructions](https://pub.dev/packages/google_sign_in#-readme-tab-) to setup Google Sign-In on Firebase. Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now as there isn't enough information here to reproduce the problem. Feel free to comment with additional information and I'm happy to continue the conversation 👍
