### ISSUE TITLE
Nested listener, how to stop state event bubble up?

### ISSUE THREAD

**Issue by wyxcoder** [felangel/bloc#719]
Wrap component in bloc listener A, when user click a button, a popup wrapped in listener B will be created.  Now both listener get state event, is there a way when the event handled in listener B, stop it to the listener A?

**Comment by felangel** [comment]
Hi @wyxcoder 👋 
Thanks for opening an issue!

I'm not sure I understand why you have multiple `BlocListeners` listening to the same bloc. Can you please provide some more context? Thanks! 👍

**Comment by wyxcoder** [comment]
> Hi @wyxcoder 👋
> Thanks for opening an issue!
> 
> I'm not sure I understand why you have multiple `BlocListeners` listening to the same bloc. Can you please provide some more context? Thanks! 👍

Thanks for help.

Here is what I am trying to do.

From main screen, click menu, I open screen A, and on screen A, click a button, it shows a popup screen B. Click close button on screen B, it shows a message on snackbar of screen B and then close screen B, back to screen A.

I have one bloc for both screen A and B.  like

RepositoryProvider.value(
      value: repo,
      child: BlocProvider.value(
          value: bloc,
          child: BlocListener<DynaBloc, DynaState>(
              bloc: bloc,
              listener: blocListener,
              child: Builder(builder: (context) {
                return screenA();
              })
          )
      )
  )

and blockListener like

Function blocListener(context, state){
  if (state.state == 'showmessage'){
    if(state.params['message']!=null)
      Scaffold.of(context).showSnackBar(new SnackBar(
        content: new Text(state.params['message']),
      )).closed
          .then((reason) {
        if(state.params['close'])
          Navigator.pop(context);
      });
    else if(state.params['close'])
      Navigator.pop(context);
  }
  if (state.state == 'showform'){
    showForm(context, state.params['params'], state.params['template']);
 }
}

showForm like

Function showForm(context, Map<String, dynamic> params, dynamic template) {
  var repo = RepositoryProvider.of<DynaRepository>(context);
  var bloc = BlocProvider.of<DynaBloc>(context);
  Navigator.of(context).push(PageRouteBuilder(
      opaque: false,
      pageBuilder: (BuildContext context, _, __) {
        return new Scaffold(
            body: RepositoryProvider.value(
      value: repo,
      child: BlocProvider.value(
          value: bloc,
          child: BlocListener<DynaBloc, DynaState>(
              bloc: bloc,
              listener: blocListener,
              child: Builder(builder: (context) {
                return screenB();
              })
          )
      )
  )

        );
      }
  ));
}

so it is like root -> blocListener -> screenA -> blocListener -> screenB.

What I expected is when close button on screenB is clicked, 'showmessage' event sent, it should only show snackbar on screenB and close screenB. That means the blocListener be called only once with context of screenB. But my test shows the blocListener be called twice with context of screenA and screenB. And even strange is the calls with context of screenA is the first.

**Comment by felangel** [comment]
Hi @wyxcoder thanks for providing extra context. This is actually working as expected because `BlocListener` on ScreenA subscribed to the bloc first so it will be notified before the `BlocListener` on ScreenB. I would recommend that you either have separate blocs for the two screens or remove the second `BlocListener` on ScreenB and handle all of the logic within the top-most `BlocListener`. Let me know if that helps and thanks again for the extra information 👍

**Comment by wyxcoder** [comment]
> Hi @wyxcoder thanks for providing extra context. This is actually working as expected because `BlocListener` on ScreenA subscribed to the bloc first so it will be notified before the `BlocListener` on ScreenB. I would recommend that you either have separate blocs for the two screens or remove the second `BlocListener` on ScreenB and handle all of the logic within the top-most `BlocListener`. Let me know if that helps and thanks again for the extra information 👍
Right, at the beginning I only has the first listener, but I don't know how to get context of the screenB, when listener get called, the context is always the listener, and its child is the screenA, how do I get context of screenB when event comes from screenB?
Thanks!

**Comment by felangel** [comment]
@wyxcoder why do you need the context of ScreenB? Shouldn't you be able to display a `SnackBar` or pop from the navigation stack using either context?

**Comment by wyxcoder** [comment]
> @wyxcoder why do you need the context of ScreenB? Shouldn't you be able to display a `SnackBar` or pop from the navigation stack using either context?

I need display snackbar on screenB , not screenA, also, when message sent from screenB, I need close screenB, not screenA.

**Comment by felangel** [comment]
@wyxcoder in that case, I would recommend providing two blocs: one scoped to ScreenA and the other scoped to ScreenB.

```dart
import 'package:flutter/material.dart';
import 'package:bloc/bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:meta/meta.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: BlocProvider(
        create: (context) => DataBloc(),
        child: Home(),
      ),
    );
  }
}

class Home extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _HomeState();
}

class _HomeState extends State<Home> {
  GlobalKey scaffoldKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Home')),
      body: BlocListener<DataBloc, DataState>(
        listener: (context, state) {
          if (state is Success) {
            Scaffold.of(context).showSnackBar(
              SnackBar(
                backgroundColor: Colors.green,
                content: Text('Success on Home'),
              ),
            );
          }
        },
        child: BlocBuilder<DataBloc, DataState>(
          builder: (context, state) {
            if (state is Initial) {
              return Center(child: Text('Press the Button'));
            }
            if (state is Success) {
              return Center(child: Text('Success'));
            }
            return Center(child: CircularProgressIndicator());
          },
        ),
      ),
      floatingActionButton: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          FloatingActionButton(
            heroTag: '0',
            child: Icon(Icons.play_arrow),
            onPressed: () {
              BlocProvider.of<DataBloc>(context).add(FetchData());
            },
          ),
          FloatingActionButton(
            heroTag: '1',
            child: Icon(Icons.skip_next),
            onPressed: () {
              Navigator.of(context).push(
                MaterialPageRoute(
                  builder: (_) => BlocProvider<DataBloc>(
                    create: (_) => DataBloc(),
                    child: Page(),
                  ),
                ),
              );
            },
          ),
        ],
      ),
    );
  }
}

class Page extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Page')),
      body: BlocListener<DataBloc, DataState>(
        listener: (context, state) {
          if (state is Success) {
            Scaffold.of(context).showSnackBar(
              SnackBar(
                backgroundColor: Colors.green,
                content: Text('Success on Page'),
              ),
            );
          }
        },
        child: BlocBuilder<DataBloc, DataState>(
          builder: (context, state) {
            if (state is Initial) {
              return Center(child: Text('Press the Button'));
            }
            if (state is Success) {
              return Center(child: Text('Success'));
            }
            return Center(child: CircularProgressIndicator());
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        heroTag: '2',
        child: Icon(Icons.play_arrow),
        onPressed: () {
          BlocProvider.of<DataBloc>(context).add(FetchData());
        },
      ),
    );
  }
}

@immutable
abstract class DataEvent {}

class FetchData extends DataEvent {}

@immutable
abstract class DataState {}

class Initial extends DataState {}

class Loading extends DataState {}

class Success extends DataState {}

class DataBloc extends Bloc<DataEvent, DataState> {
  @override
  DataState get initialState => Initial();

  @override
  Stream<DataState> mapEventToState(
    DataEvent event,
  ) async* {
    if (event is FetchData) {
      yield Loading();
      await Future.delayed(Duration(seconds: 2));
      yield Success();
    }
  }
}
```

Let me know if that helps 👍

**Comment by wyxcoder** [comment]
That can solve the problem, but I am not sure if that is the right way to go, what if I have many level, and each level are similar, not quite a good idea to write same code in each level.
For now, I solve the problem by passing context through the event.

Another thing popup, see my showform function, I wonder why I have to include RepositoryProvider, for example, the below code doesn't work
`
Function showForm(context, Map<String, dynamic> params, dynamic template) {
  Navigator.of(context).push(PageRouteBuilder(
      opaque: false,
      pageBuilder: (BuildContext context, _, __) {
         return screenB(); 
        );
      }
  ));
}
`
it complains the context doesn't have RepositoryProvider and BLocProvider. But why event can be captured by top level listener while it cannot get blocprovider from top level?

**Comment by felangel** [comment]
@wyxcoder I think the issue you're having with the context is that the context provided within the `pageBuilder` is detached from the parent context so you need to use the parent context to do the Repository/Bloc lookup. 

```dart
Function showForm(context, Map<String, dynamic> params, dynamic template) {
  Navigator.of(context).push(PageRouteBuilder(
      opaque: false,
      pageBuilder: (_, __, ___) {
         // use parent context instead of pageBuilder context to lookup blocs/repos
         return screenB(); 
        );
      }
  ));
}
```

Regarding the larger question, I think this problem is a sign of one bloc having too many responsibilities. I would strongly recommend having separate blocs for each feature/use-case because if you have multiple bloc listeners subscribed to the bloc at the same time, they will all be triggered. It's not a bubbling up because the blocs aren't layered; rather each listener is subscribed to the same bloc independently.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
