### ISSUE TITLE
[question] How to share and close item around lists

### ISSUE THREAD

**Issue by huang12zheng** [felangel/bloc#728]
There is a List of articles - ArticleListBloc has the attribute Map<Aritlce.id, Aritlce>
It can filter to generate multiple listwidgets about trends, highlights, and popularity.
Item is all from List<Aritlce>.
But no I know how to close the article item

>listwidgets is like BlocProvider.value( filer(List<Aritlce>) )
> loadmore item would insert into Map<Aritlce.id, Aritlce>.

> ArticleItem could Eidtable

```
|          items             |
-----------------------------
| list1    |     list2    |...
```

**Comment by huang12zheng** [comment]
```dart
class ArticleBloc extends ItemBloc<ArticleListBean>{
  factory ArticleBloc(String id) {
    if (_cache.containsKey(id)) {
        print('id is call $id');
      return _cache[id];
    } else {
      final bloc = ArticleBloc._internal(id);
      _cache[id] = bloc;
      dependeds[id] = 0;
      return bloc;
    }
  }
  static final Map<String, ItemBloc> _cache =
      <String, ItemBloc>{};
  static final  Map<String,int> dependeds = <String,int> {};
  ArticleBloc._internal(id):super(id);
  
  @override
  Future<void> close() async{
    dependeds[id]-=1;
    debugPrint('close $id count: ${dependeds[id]}');
    if (dependeds[id] == 0)
    {
      _cache.remove(id); /// check index
      super.close();
    }
  }
  static get cache=> _cache;
  @override
  fromJson(Map<String, dynamic> json){
    ArticleListBean bean = emitOBJ(json);
    return InArticleState(0,bean);
  }

  onProvider(){
    dependeds[id]+=1;
    debugPrint('onProvider $id count: ${dependeds[id]}');
  }
}
```
I wanted to register it with a counter as above

**Comment by felangel** [comment]
Hi @huang12zheng 👋
Thanks for opening an issue!

Can you please describe why you need to maintain a map of ItemBlocs? I'm not sure I understand what you're trying to accomplish. It would be really helpful if you could link to a sample app which illustrates the problem you're having. Thanks!

**Comment by huang12zheng** [comment]
https://github.com/huang12zheng/share_list/tree/master/lib
Map is for sample.

**Comment by huang12zheng** [comment]
I update sample, and it is for 
* requirement：

1.  item change is sync, including navigation page.
2. list refresh(no implement in sample) or loadMore would refresh items.
3. close item in a right way.

-----

>  2. list refresh(no implement in sample) or loadMore would refresh items.
I click right item (id=10)  to 5, and scroll left to 10. Then, right item(id 10) to 0

Map is just for requirement.

----
PS:  I really think a map in bloc is not a good thing though it is work.

**Comment by felangel** [comment]
Hi @huang12zheng I tried taking a look but I don't fully understand the requirements and I wasn't able to run the application since it's missing a `pubspec.yaml`.

Closing for now since I don't have enough information to help but feel free to add additional information or update the sample so that it can be run and I'm happy to continue helping 👍
