### ISSUE TITLE
Typo in the Weather Tutorial "nad" -> "and"

### ISSUE THREAD

**Issue by jesserwright** [felangel/bloc#736]
See second paragraph under [**Add getLocationId Method**(https://bloclibrary.dev/#/flutterweathertutorial?id=add-getlocationid-method)

"So let's go ahead nad do that now."

**Comment by felangel** [comment]
Hi @jesserwright 👋 
Thanks for opening an issue!

Fixed in https://github.com/felangel/bloc/commit/51c50d92fef2d83b832dd4d1040c6a96a8f6bccb 👍
