### ISSUE TITLE
[Docs] Set TextInputType in Email form fields

### ISSUE THREAD

**Issue by mikaelmello** [felangel/bloc#738]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

All tutorials that include forms and email fields (I'm only aware of the Firebase Login one) could include `keyboardType: TextInputType.emailAddress` when creating a `TextFormField`

**Describe alternatives you've considered**

None

**Additional context**

![image](https://user-images.githubusercontent.com/17488630/71332680-dc5f5e80-2515-11ea-87f8-6dda4a07cc6e.png)

**Comment by felangel** [comment]
Hi @mikaelmello 👋 
Thanks for opening an issue!

Fixed in https://github.com/felangel/bloc/commit/4e790345052e875c6998268a50765ef144d2bad6 👍
