### ISSUE TITLE
Doc request: How to use bloc across pages?

### ISSUE THREAD

**Issue by realtebo** [felangel/bloc#74]
Let's extended counter example, where all is working well. 

Imagine I add a thir fab action that uses navigator.pushReplacement to navigate a different page.

The destination page needs to see counter value.

How to?

**Comment by felangel** [comment]
@realtebo you can achieve that by using `BlocProvider` to access the `CounterBloc` using the `BuildContext.

```dart
class ThirdPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final CounterBloc _counterBloc = BlocProvider.of<CounterBloc>(context);
    return BlocBuilder(
      bloc: _counterBloc,
      builder: (BuildContext context, int count) {
        return Text('$count');
      }
  }
}
```

Does that help?

**Comment by realtebo** [comment]
I was following this approach by myself, but I get

> I/flutter ( 6351): The following assertion was thrown building OtherPage(dirty):
> I/flutter ( 6351): BlocProvider.of() called with a context that does not contain a Bloc of type CounterBloc.
> I/flutter ( 6351): No ancestor could be found starting from the context that was passed to
> I/flutter ( 6351): BlocProvider.of<CounterBloc>(). This can happen if the context you use comes from a widget above the
> I/flutter ( 6351): BlocProvider.
> I/flutter ( 6351): The context used was:
> I/flutter ( 6351):   OtherPage(dirty)
> 

```
This my target page code

import '../counter_bloc.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class OtherPage extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    
    final CounterBloc _counterBloc = BlocProvider.of<CounterBloc>(context);

    return MaterialApp(
      title: 'Other Page',
      home: BlocProvider<CounterBloc>(
        bloc: _counterBloc,
        child: Center(
          child: Text(
            _counterBloc.currentState.toString(),
            style: TextStyle(fontSize: 24.0),
          ),
        ),
      ),
    );
  }

}
```

**Comment by felangel** [comment]
If you want your Bloc to be accessible globally (across different routes) you need to make sure that the `BlocProvider` is an ancestor of the `MaterialApp` widget.

```dart
class App extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _AppState();
}

class _AppState extends State<App> {
  final CounterBloc _counterBloc = CounterBloc();

  @override
  Widget build(BuildContext context) {
    return BlocProvider<CounterBloc>(
      bloc: _counterBloc,
      child: MaterialApp(
        title: 'Flutter Demo',
        home: CounterPage(),
      ),
    );
  }

  @override
  void dispose() {
    _counterBloc.dispose();
    super.dispose();
  }
}
```

**Comment by felangel** [comment]
You need to provide a `heroTag` for each of the `FloatingActionButton` widgets.

Change `counter_page.dart` to:

```dart
class CounterPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final CounterBloc _counterBloc = BlocProvider.of<CounterBloc>(context);

    return Scaffold(
      appBar: AppBar(title: Text('Counter')),
      body: BlocBuilder<CounterEvent, int>(
        bloc: _counterBloc,
        builder: (BuildContext context, int count) {
          return Center(
            child: Text(
              '$count',
              style: TextStyle(fontSize: 24.0),
            ),
          );
        },
      ),
      floatingActionButton: Column(
        crossAxisAlignment: CrossAxisAlignment.end,
        mainAxisAlignment: MainAxisAlignment.end,
        children: <Widget>[
          Padding(
            padding: EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              heroTag: 0,
              child: Icon(Icons.add),
              onPressed: () {
                _counterBloc.dispatch(CounterEvent.increment);
              },
            ),
          ),
          Padding(
            padding: EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              heroTag: 1,
              child: Icon(Icons.remove),
              onPressed: () {
                _counterBloc.dispatch(CounterEvent.decrement);
              },
            ),
          ),
          Padding(
            padding: EdgeInsets.symmetric(vertical: 5.0),
            child: FloatingActionButton(
              heroTag: 2,
              child: Icon(Icons.pageview),
              onPressed: () {
                Navigator.of(context).push(
                  MaterialPageRoute<OtherPage>(
                    builder: (BuildContext context) {
                      return OtherPage();
                    },
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
```

**Comment by realtebo** [comment]
Oh yes, now it works. A final question, I hope:

In the other page I need block builder only If I must dispatch events, right?

So I can simply have

```
class OtherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final CounterBloc _counterBloc = BlocProvider.of<CounterBloc>(context);

    return Scaffold(
      appBar: AppBar(title: Text('Other page')),
      body: Center(
        child: Text(
          _counterBloc.currentState.toString(),
          style: TextStyle(fontSize: 24.0),
        ),
      ),
    );
  }
}
```

Right? 

If this is almost all, your plugin is the most flexible at the minor code rows cost.

**Comment by felangel** [comment]
You only need `BlocBuilder` if you want to be able to render different widgets in response to different states.

Think of `BlocBuilder` like `StreamBuilder`; whenever the Bloc's state changes, the builder function will be called with the new state (in this case the integer) and you can render whatever you want.

You don't need `BlocBuilder` to dispatch events; in order to dispatch you just need to have access to the bloc itself and call dispatch (`_counterBloc.dispatch(CounterEvent.increment)`).

In this case you can just print `currentState` but I would recommend using `BlocBuilder` for most cases instead of directly accessing the bloc's state because it makes the UI code a bit cleaner (especially in more complex examples).

Haha yeah definitely check out the documentation 👍 
I am still making lots of updates to the documentation so they should have even more details and examples over the next few weeks.

Did I answer all of your questions?

**Comment by felangel** [comment]
Closing this for now. Feel free to comment if you have any more questions!

**Comment by realtebo** [comment]
Sorry, I'm here again. I'm playing with your plugins !

I understand that I can have a BlockProvider as ancestor of MaterialApp, so I can share the bloc between pages without loosing states.

My question now is how to use a bloc provider wth 2 blocs, should I nest it?

**Comment by realtebo** [comment]
Could it be a good solution ?
https://medium.com/@danaya/multiple-blocs-in-flutter-and-how-to-communicate-between-them-e441282dc62a

Combine multiple blocs?  Like in react, combining reducers, where it allows me to splice state but with ease of handling.

**Comment by felangel** [comment]
@realtebo you can do either one. Nesting `BlocProviders` is perfectly fine and if you want for convenience you can combine Blocs. I would slightly advise against combining blocs because it is less flexible but it's totally up to you.

**Comment by basketball-ico** [comment]
@felangel Hello again :D.

I have some `GlobalBlocs` above `MaterialApp`, and I can access to this bloc in any route.

Then in a nested `Route` I created a `BlocProvider`, And I want to use in a Pages that this Screen Push.
But I have the error `BlocProvider.of() called with a context that does not contain a Bloc of type ...`.

I read this:
> If you want your Bloc to be accessible globally (across different routes) you need to make sure that the `BlocProvider` is an ancestor of the `MaterialApp` widget.

So If my bloc need to be access, when push via Navigator, Is necessary to convert this `Bloc` a `GlobalBloc`?

I don't like this idea because is a `NestedBloc` so i don't like to see at the top haha, and also a have a lot of `Blocs` like this, and the MaterialApp will be `crazy" with a lot of a lot of blocs above...

How can I solve this?

Thanks

**Comment by felangel** [comment]
Hey 👋 

You can just pass the Blocs via constructor in that case. Let me know if that helps!

**Comment by basketball-ico** [comment]
Yes, thanks.
but I use `pushNamed` and I pass the bloc like argument, but i don't know if this pass a reference or a copy :(
```dart
Navigator.of(context).pushNamed(
                            'SomeRouteName',
                            arguments: _someBloc);
``` 
and then in the pushed page
```dart
_someBloc = ModalRoute.of(context).settings.arguments;
```

**Comment by felangel** [comment]
Primitives are passed by value and objects are passed by reference. 👍

**Comment by yang-f** [comment]
> Hey 👋
> 
> You can just pass the Blocs via constructor in that case. Let me know if that helps!

I don't think it's a good solution, but i not have a better one. 😃

**Comment by felangel** [comment]
@yang-f I’ll update the docs later today with more information on that topic. You have 3 options though:
- wrap your MaterialApp with a BlocProvider for global access
- use names routes and setup the BlocProvider to be scoped for the named route
- pass the bloc via constructor into the new page and then use BlocProvider to make it available in the remaining subtree
- use your another DI library to provide the blocs 

Imo it’s not a big deal to pass the bloc via constructor into the new page and then provide it again but like I said, I’ll add a new recipe for how to pass a bloc throughout the widget tree later today 👍

**Comment by yang-f** [comment]
> @yang-f I’ll update the docs later today with more information on that topic. You have 3 options though:
> 
> * wrap your MaterialApp with a BlocProvider for global access
> * use named routes and setup the BlocProvider to be scoped for the named route
> * pass the bloc via constructor into the new page and then use BlocProvider to make it available in the remaining subtree
> * use your another DI library to provide the blocs
> 
> Imo it’s not a big deal to pass the bloc via constructor into the new page and then provide it again but like I said, I’ll add a new recipe for how to pass a bloc throughout the widget tree later today 👍

Now we suppose have 3 pages: A,B,C(all they depend anyBloc) and A hold a anyBloc instance.
page A -> page B(anyBloc) -> page C(anyBloc form B);
then we nav back form C -> B(anyBloc from C)?
the lifecycle‘s complexity of bloc will grow exponentially。

**Comment by lingster** [comment]
@felangel : thanks for creating this really useful library/framework, which I'm just getting my head around. One question: is it better to have your blocs defined at MaterialApp level then use `BlocProvider.of<MyBloc>(context);` 
or are there advantages or disadvantages to passing blocs to widgets via the constructor? 
Are there any performance considerations?

**Comment by luandedeng** [comment]
> @yang-f I’ll update the docs later today with more information on that topic. You have 3 options though:
> 
> * wrap your MaterialApp with a BlocProvider for global access
> * use named routes and setup the BlocProvider to be scoped for the named route
> * pass the bloc via constructor into the new page and then use BlocProvider to make it available in the remaining subtree
> * use your another DI library to provide the blocs
> 
> Imo it’s not a big deal to pass the bloc via constructor into the new page and then provide it again but like I said, I’ll add a new recipe for how to pass a bloc throughout the widget tree later today 👍

@felangel , I am using Bloc pattern and named routes in my project. 
I am also facing problem about access bloc across routes. I read the recipe about bloc access[https://felangel.github.io/bloc/#/recipesflutterblocaccess?id=route-access](url), but I still have no idea on how to use route access with named routes.
Could you please give more explain on "use named routes and setup the BlocProvider to be scoped for the named route"? It will be great if you can also give a code example.

**Comment by felangel** [comment]
@luandedeng I'll update the recipe sometime tomorrow with a section on named routes. Thanks for bringing that up 👍

**Comment by FilipKvestak** [comment]
Hello,

I'm stuck with something, still learning dart/flutter. 

How would You use 2+ blocs, INSIDE of 1 bloc? 
e.g in Your todos app, filtered_todos_bloc.dart:

`class FilteredTodosBloc extends Bloc<FilteredTodosEvent, FilteredTodosState> {
  final TodosBloc _todosBloc;
  StreamSubscription _todosSubscription;

  FilteredTodosBloc({@required TodosBloc todosBloc})
      : assert(todosBloc != null),
        _todosBloc = todosBloc {
    _todosSubscription = todosBloc.listen((state) {
      if (state is TodosLoaded) {
        add(UpdateTodos((todosBloc.state as TodosLoaded).todos));
      }
    });
  }

  @override
  FilteredTodosState get initialState {
    final currentState = _todosBloc.state;
    return currentState is TodosLoaded
        ? FilteredTodosLoaded(currentState.todos, VisibilityFilter.all)
        : FilteredTodosLoading();
  }
}`

I was thinking about something like this:
`class FilteredTodosBloc extends Bloc<FilteredTodosEvent, FilteredTodosState> {
  final TodosBloc _todosBloc;
  StreamSubscription _todosSubscription;

  final AnotherBloc _anotherBloc;
  StreamSubscription _anotherSubscription;

  FilteredTodosBloc({@required TodosBloc todosBloc, @required AnotherBloc anotherBloc})
      : assert(todosBloc != null, anotherBloc != null),
        _todosBloc = todosBloc, _anotherBloc = anotherBloc {
    _todosSubscription = todosBloc.listen((state) {
      if (state is TodosLoaded) {
        //add(UpdateTodos((todosBloc.state as TodosLoaded).todos));
        _anotherSubscription = _anotherBloc.listen((state) {
          if (state is AnotherStateLoaded) {
            doSomething()
          }
        });
      }
    });
  }
}`

But I feel that it is just bad practice, and wouldn't work as expected.

To be specific, in my database (firestore) let's say I have 3 tables:
1. 'user' table //each user has name, email, phoneNumber, etc.
2. 'car' table //each car has brand, model, year, etc.
3. 'user_car' table //represents cars for user, where each entry (document) is user's id, and under that document is plain list of strings (whole table could be fetched as Map<String, List<String>>, where key is user's id, value is list of car id's)

On home screen I wan't to show all cars for user, so logically I need to fetch all 3 tables, but 'user-car' table needs 'users' and 'cars' first, so I could provide any data from those tables, based on data from 'user-car' table.

I know I could simply put list of car id's inside user table (same hierarchy as name, email, etc), but I like the idea of decoupling everything I can. I have bad history with older firebase database, because I had to restructure whole database/backend when app grew in production :)

How would You do it?

Thanks in advance.

**Comment by barzansaeedpour** [comment]
> @luandedeng I'll update the recipe sometime tomorrow with a section on named routes. Thanks for bringing that up 👍

Lets say i have several blocs defined above my materialApp. now when i use them in different pages
and use navigator.of(context), they work fine. but how can i clear all data of those blocs when i dispose a specific page and make user enter the data once more?
i mean since i defined them above materialApp, i cant dispose them.
the other option here is not define them above materialApp, but then i can not use
navigator.of(context) to route a new page and use blocProvider there and retrieve bloc's data (dose not have the same context).

i am really disappointed with bloc.
help me pls. thanks in advance.

**Comment by felangel** [comment]
Hi @barzansaeedpour 👋
You should only ever provide a bloc to the subtree that needs it. If a bloc is only needed for a certain page or pages, then you should not provide it above MaterialApp. Hope that helps.

**Comment by barzansaeedpour** [comment]
> Hi @barzansaeedpour 👋
> You should only ever provide a bloc to the subtree that needs it. If a bloc is only needed for a certain page or pages, then you should not provide it above MaterialApp. Hope that helps.

thanks for quick answer.
Is there any advanced example of using several bloc and exchange data between them?
how can i use a blocs data in another bloc?

**Comment by barzansaeedpour** [comment]
> Hi @barzansaeedpour 👋
> You should only ever provide a bloc to the subtree that needs it. If a bloc is only needed for a certain page or pages, then you should not provide it above MaterialApp. Hope that helps.

Is there any example of not provide blocProvider above MaterialApp and use one bloc for several pages?

**Comment by felangel** [comment]
@barzansaeedpour check out the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=route-access).

**Comment by luandedeng** [comment]
> > Hi @barzansaeedpour 👋
> > You should only ever provide a bloc to the subtree that needs it. If a bloc is only needed for a certain page or pages, then you should not provide it above MaterialApp. Hope that helps.
> 
> Is there any example of not provide blocProvider above MaterialApp and use one bloc for several pages?

I don't know a good solution for scoped bloc in my app so far. In my practice, BLOC framework is easy to use in single page; for global usage, it' s also OK. But I don't find any good solution to share a BLOC in different pages with BlocProvider. BlocProvider shares bloc only in subtree. But when we navigate to another page from origin page, the another page is not in subtree of origin page. In this case, BlocProvider doesn't work.
Is it correct? @felangel

**Comment by felangel** [comment]
@luandedeng please refer to the recipe linked above https://github.com/felangel/bloc/issues/74#issuecomment-572043525. It covers how to pass an existing bloc to a new route.

**Comment by hunght** [comment]
@felangel i have same issues when using named route, and follow your suggestion.
* use named routes and setup the BlocProvider to be scoped for the named route
But i still don't know how to apply this in code, could you show the example ?

**Comment by hunght** [comment]
@felangel , in our project we are using use named routes and your suggestion, is:
* use named routes and set up the BlocProvider to be scoped for the named route
but 
but i'm still can't figure how to apply this, and about the recipe in your link it not for named routes, as i see. pls help thanks

**Comment by JonFir** [comment]
Hi @felangel 

https://github.com/felangel/bloc/issues/74#issuecomment-516684320

I can't find this recipe. Could I have link? Or could you answer, why my example do not working?

```
class Router {
  static const words = '/';
  static const wordNew = '/word_new';

  static Route<dynamic> routerFactory(RouteSettings settings) {
    switch (settings.name) {
      case words:
        return makeWordsRoute();
      case wordNew:
        return makeWordsNewRouter();
      default:
        return MaterialPageRoute(
          builder: (_) => Scaffold(
            body: Center(child: Text('No route defined for ${settings.name}')),
          ),
        );
    }
  }

  static MaterialPageRoute makeWordsRoute() =>
      MaterialPageRoute(builder: (context) {
        return BlocProvider(
          create: (context) => WordsBloc(),
          child: WordsScreen(),
        );
      });

  static MaterialPageRoute makeWordsNewRouter() =>
      MaterialPageRoute(builder: (context) {
        return BlocProvider.value(
          value: BlocProvider.of<WordsBloc>(context), // block not fount in this context
          child: WordNew(),
        );
      });
}
```

**Comment by felangel** [comment]
@JonFir I'll update the recipe later today and will let you know 👍

**Comment by tony123S** [comment]
Why it not working?

https://stackoverflow.com/questions/60682296/stream-not-update-in-page

**Comment by andreddie81** [comment]
@felangel  Following the topic on this question, and, after reading you last comment to JonFir, I was wondering, once we push to the new route, how do we get the same instance of the bloc in this new route??

I am doing like this: 

my main.dart:

```
class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return BlocProvider<StatusBloc>(
        create: (context) => StatusBloc(),
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          home: HomeRoute(),
        ),
      );
  }
}

```

in my home_route.dart I have a method to go to a new route like this:

```
void _pushToDetails() async {
    final result = await Navigator.of(context).push(
      MaterialPageRoute(
        builder: (_) => BlocProvider.value(
          value: BlocProvider.of<StatusBloc>(context),
          child: DetailsRoute(),
        ),
      ),
    );
    print("---------------------> Result is $result");
    
  }

```

Not sure if I am getting the StatusBloc correctly in my DetailsRoute(), I do like this:

```
class DetailsRoute extends StatelessWidget {
  DetailsRoute();

  StatusBloc statusBloc;

  @override
  Widget build(BuildContext context) {
    print("Build Add Cards");
    statusBloc = BlocProvider.of<StatusBloc>(context)..add(DetailsListEvent());

    return Scaffold(...........)
```

**Comment by felangel** [comment]
@andreddie81 yup, the snippets you provided will result in the same bloc instance because you're using `BlocProvider.value` and performing a lookup for the existing bloc instance.

A minor comment about the last snippet: you shouldn't define non-final variables in a `StatelessWidget`.

```dart
class DetailsRoute extends StatelessWidget {
  DetailsRoute();

  @override
  Widget build(BuildContext context) {
    final statusBloc = BlocProvider.of<StatusBloc>(context)..add(DetailsListEvent());

    return Scaffold(...........)
```

Hope that helps 👍

**Comment by ricpar11** [comment]
> @yang-f I’ll update the docs later today with more information on that topic. You have 3 options though:
> 
> * wrap your MaterialApp with a BlocProvider for global access
> * use named routes and setup the BlocProvider to be scoped for the named route
> * pass the bloc via constructor into the new page and then use BlocProvider to make it available in the remaining subtree
> * use your another DI library to provide the blocs
> 
> Imo it’s not a big deal to pass the bloc via constructor into the new page and then provide it again but like I said, I’ll add a new recipe for how to pass a bloc throughout the widget tree later today 👍

For those who dislikes  wrapping the material app widget, or using  named routes, go and try using a DI library and then just use `BlocProvider.value` wherever you want to provide the bloc, I think this is the best option in terms of clean code.

**Comment by karanianandkumar** [comment]
Is it a better idea to create Singleton of Bloc object in DI call wherever we need?

**Comment by felangel** [comment]
@karanianandkumar I would recommend using BlocProvider to provide the bloc to the part of the widget tree that needs it.

**Comment by chethanjkulkarni** [comment]
I have an app, which has 3 pages that communicate with each other. I have wrapped the first widget with MultiBlocProvider 
![Screen Shot 2020-08-03 at 1 25 43 AM](https://user-images.githubusercontent.com/30331156/89131150-44543980-d528-11ea-9e0a-b188b9dbed41.png)

I have also wrapped the first widget with BlocConsumer and it works fine.

![Screen Shot 2020-08-03 at 1 27 31 AM](https://user-images.githubusercontent.com/30331156/89131187-841b2100-d528-11ea-9512-618efa769809.png)

In my second screen ```details.dart```, I have wrapped it using a ```MultiBlocListener``` as your [Counter and Random example](https://github.com/tadaspetra/bloc_examples/tree/master/003_multiple_blocs)

![Screen Shot 2020-08-03 at 1 29 48 AM](https://user-images.githubusercontent.com/30331156/89131237-d4927e80-d528-11ea-97b7-a7daf80976ca.png)


When I move to this page using ```Navigator.push( ... )``` from my first page, I get the following error

![Screen Shot 2020-08-03 at 1 34 14 AM](https://user-images.githubusercontent.com/30331156/89131311-72864900-d529-11ea-926f-68758373a93d.png)

**Comment by chethanjkulkarni** [comment]
> I have an app, which has 3 pages that communicate with each other. I have wrapped the first widget with MultiBlocProvider
> ![Screen Shot 2020-08-03 at 1 25 43 AM](https://user-images.githubusercontent.com/30331156/89131150-44543980-d528-11ea-9e0a-b188b9dbed41.png)
> 
> I have also wrapped the first widget with BlocConsumer and it works fine.
> 
> ![Screen Shot 2020-08-03 at 1 27 31 AM](https://user-images.githubusercontent.com/30331156/89131187-841b2100-d528-11ea-9512-618efa769809.png)
> 
> In my second screen `details.dart`, I have wrapped it using a `MultiBlocListener` as your [Counter and Random example](https://github.com/tadaspetra/bloc_examples/tree/master/003_multiple_blocs)
> 
> ![Screen Shot 2020-08-03 at 1 29 48 AM](https://user-images.githubusercontent.com/30331156/89131237-d4927e80-d528-11ea-97b7-a7daf80976ca.png)
> 
> When I move to this page using `Navigator.push( ... )` from my first page, I get the following error
> 
> ![Screen Shot 2020-08-03 at 1 34 14 AM](https://user-images.githubusercontent.com/30331156/89131311-72864900-d529-11ea-926f-68758373a93d.png)
None of the above solutions worked. Please help me out

**Comment by chethanjkulkarni** [comment]
None of the above solutions worked. Please help me out

**Comment by heqingbao** [comment]
> I was following this approach by myself, but I get
> 
> > I/flutter ( 6351): The following assertion was thrown building OtherPage(dirty):
> > I/flutter ( 6351): BlocProvider.of() called with a context that does not contain a Bloc of type CounterBloc.
> > I/flutter ( 6351): No ancestor could be found starting from the context that was passed to
> > I/flutter ( 6351): BlocProvider.of(). This can happen if the context you use comes from a widget above the
> > I/flutter ( 6351): BlocProvider.
> > I/flutter ( 6351): The context used was:
> > I/flutter ( 6351):   OtherPage(dirty)
> 
> ```
> This my target page code
> 
> import '../counter_bloc.dart';
> import 'package:flutter/material.dart';
> import 'package:flutter_bloc/flutter_bloc.dart';
> 
> class OtherPage extends StatelessWidget {
> 
>   @override
>   Widget build(BuildContext context) {
>     
>     final CounterBloc _counterBloc = BlocProvider.of<CounterBloc>(context);
> 
>     return MaterialApp(
>       title: 'Other Page',
>       home: BlocProvider<CounterBloc>(
>         bloc: _counterBloc,
>         child: Center(
>           child: Text(
>             _counterBloc.currentState.toString(),
>             style: TextStyle(fontSize: 24.0),
>           ),
>         ),
>       ),
>     );
>   }
> 
> }
> ```

The named parameter 'bloc' isn't defined.  Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'bloc'.

**Comment by chethanjkulkarni** [comment]
> > I was following this approach by myself, but I get
> > > I/flutter ( 6351): The following assertion was thrown building OtherPage(dirty):
> > > I/flutter ( 6351): BlocProvider.of() called with a context that does not contain a Bloc of type CounterBloc.
> > > I/flutter ( 6351): No ancestor could be found starting from the context that was passed to
> > > I/flutter ( 6351): BlocProvider.of(). This can happen if the context you use comes from a widget above the
> > > I/flutter ( 6351): BlocProvider.
> > > I/flutter ( 6351): The context used was:
> > > I/flutter ( 6351):   OtherPage(dirty)
> > 
> > 
> > ```
> > This my target page code
> > 
> > import '../counter_bloc.dart';
> > import 'package:flutter/material.dart';
> > import 'package:flutter_bloc/flutter_bloc.dart';
> > 
> > class OtherPage extends StatelessWidget {
> > 
> >   @override
> >   Widget build(BuildContext context) {
> >     
> >     final CounterBloc _counterBloc = BlocProvider.of<CounterBloc>(context);
> > 
> >     return MaterialApp(
> >       title: 'Other Page',
> >       home: BlocProvider<CounterBloc>(
> >         bloc: _counterBloc,
> >         child: Center(
> >           child: Text(
> >             _counterBloc.currentState.toString(),
> >             style: TextStyle(fontSize: 24.0),
> >           ),
> >         ),
> >       ),
> >     );
> >   }
> > 
> > }
> > ```
> 
> The named parameter 'bloc' isn't defined. Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'bloc'.

It means your context is missing the bloc that you are trying to access
You should pass an instance of ```CounterBloc``` either using
```
BlocProvider(
  create: (context) => CounterBloc(...),
  child: ... )
```
or, if you already have an existing instance of ```CounterBloc```, you can pass using
```
BlocProvider.value(
  value: BlocProvider.of<CounterBloc>(context),
  child: ... )

**Comment by phyueimon162** [comment]
I have problem in changing value between pages. 
Lets say, 
1) Page 1 have counter. I counted to 3 and go to Page 2. 
2) In page2, I multiply 3 with 2. Then I want to change value in page 1 to 6. 
In bloc state it changed to 6. But not refresh in page one's Bloc builder. Why?

**Comment by chethanjkulkarni** [comment]
I hope you are creating a new instance of global bloc on your second page. You need to use the existing global bloc that is referenced in your Page 1.

**Comment by dgaedcke** [comment]
I recommend people switch from Provider to Riverpod (also by Remi) as it solves all these problems

**Comment by RaulUrtecho** [comment]
> Yes, thanks.
> but I use `pushNamed` and I pass the bloc like argument, but i don't know if this pass a reference or a copy :(
> 
> ```dart
> Navigator.of(context).pushNamed(
>                             'SomeRouteName',
>                             arguments: _someBloc);
> ```
> 
> and then in the pushed page
> 
> ```dart
> _someBloc = ModalRoute.of(context).settings.arguments;
> ```

Thanks this is doub I had if it would work since I need to fire an event of the bloc of the page from which it is navigated but it is named navigation.
Now I know that I can pass the bloc as a navigation argument, **it is not the cleanest but at least between two screens it works**.

**Comment by Enzodtz** [comment]
@felangel extending this discussion a little bit further, is there a way to use blocs with `auto_route` package? Thanks

**Comment by lei-cao** [comment]
found this thread from `auto_route` to be very useful. https://github.com/Milad-Akarie/auto_route_library/issues/632

**Comment by Chaitanyabsprip** [comment]
what are you thoughts about using a singleton class for a bloc. That way I can put a blocprovider down a tree where I need it and not allocate the memory to that stream for the life of the application.

**Comment by Muhammad-Hammad** [comment]
Hi @felangel! would you be kind to tell me an easy way of migrating from getX to Flutter_bloc? something like a comparison in between them? 
for example, getX has  "this" while in bloc, instead of "this" we use "that". so that migration might become understandable. 
Thank you in advance.

**Comment by DongNQFinizy** [comment]
hi @felangel  i have a problem with navigator
I have 3 page: A, B, C
I used 1 bloc for all 3 pages
from page A -B, i used navigator.push with blocprovider.value : Worked ok
from page B-C, i used navigator.pushReplacement with blocprovider.value : not work.
on page C : it said that can't find context of bloc. 
I thank the problem was because of pushReplacement. It replace page B with page C -> So it can't find the bloc with context.
How can i solve this ? Thanks :))

Navigator.pushReplacement(context,
                MaterialPageRoute(
                    builder: (_) => BlocProvider.value(
                      value: context.read<ForgotPasswordBlocNew>(),
                      child: OTPForgotPassScreen(),
                    )
                )
            );

- ERROR : on OTPForgotPassScreen couldn't find context contain bloc

**Comment by Gene-Dana** [comment]
Hi there ! Have you seen flowbuilder? Run the examples and see if this is what you are looking for !
https://github.com/felangel/flow_builder

**Comment by mahamedh** [comment]
how to pass 2 existing bloc at once to another page

**Comment by Gene-Dana** [comment]
Ideally, you would not need to do that. Rather, if your provide the blocs above the widget tree, you can just read it from `context.read`

[Give this a read](https://epb.bibl.th-koeln.de/frontdoor/deliver/index/docId/1498/file/flutter-for-the-dev-of-large-scale-ref-app.pdf) and you can see how this works

![image](https://user-images.githubusercontent.com/45580241/147852254-94f58d62-ee12-4a4c-9268-c90917bc8dd5.png)

**Comment by mahamedh** [comment]
if i mistaking please correct me @Gene-Dana,
i have use case regarding continues flow of bloc as search bloc,hotel bloc & room bloc
i need current state(if user select new city, state is new city unless its not a initial state) state of search bloc to both other bloc,simply hotel and room bloc depends on current state of search bloc. if i access context.read<SearchBloc>().state.selectedCity inside hotel bloc of hotel views it will always give initial state of search bloc 
 return MultiBlocProvider(
      providers: <BlocProvider>[
        BlocProvider<HotelBloc>(
          create: (context) => HotelBloc(context),
        ),
        BlocProvider<SearchBloc>(
          create: (context) => SearchBloc(context),
        ),
      ],
      child: HotelSearchReasult(),

    );
so here i have found i am again creating a new instance of search bloc that's why its always showing new initial state. i  have change is multibloc provider to 

MultiBlocProvider(
      providers: <BlocProvider>[
        BlocProvider<HotelBloc>(
          create: (context) => HotelBloc(context),
        ),
        BlocProvider.value(value:  BlocProvider.of<SearchBloc>(context))

      ],
      child: HotelSearchReasult(),

    );

now its throw error 
"
   BlocProvider.of() called with a context that does not contain a SearchBloc.

        No ancestor could be found starting from the context that was passed to BlocProvider.of<SearchBloc>().

        This can happen if the context you used comes from a widget above the BlocProvider.

        The context used was: HotelProvider(dirty, state: _HotelProviderState#b1116)
        
"
now i need to how to know how to provide existing instance as  it   BlocProvider.value(value:  BlocProvider.of<SearchBloc>(context)) in separate class any one please let me know

**Comment by narcodico** [comment]
Hi @mahamedh 👋

Please strong type the retrieval of your bloc providers `BlocProvider.of<SearchBloc>(context)`.
I'd also strongly recommend you don't pass in the context to your blocs, like `SearchBloc(context)`.

**Comment by mkappworks** [comment]
I have two screens in my flutter application `Screen1` and `Screen2`. `Screen1` is the home screen. I navigate from `Screen1` to `Screen2` via

` Navigator.of(context).push(PageRouteBuilder<void>(pageBuilder: (context, animation, secondaryAnimation) => Screen2()); `

and `Screen2` to `Screen1` via 

`Navigator.pop(context); `

`Screen1` is statelesswidget: 

```
class Screen1 extends StatelessWidget { 

   @override Widget build(BuildContext context) {
    return MultiBlocProvider( 
            providers: [ 
                   BlocProvider<BlocA>(create: (_) => BlocA()), 
                   BlocProvider<BlocB>(create: (_) => BlocB()), ] 
            child: RaisedButton( 
                           child: Text('Goto Screen 2'),  
                          onPressed: Navigator.of(context).push(PageRouteBuilder<void>(pageBuilder: (context, animation, secondaryAnimation) => Screen2()); 
                    ), 
              )
        } 
} 

```
I would appreciate anyone can provide an answer that will satisfy the following : 

1. Want to access the two bloc initialised in the `Screen1` from `Screen2` using BlocProvider<BlocA>.value(value: 

`BlocProvider.of<BlocA>(context), child: ...) `

without bring the initialisation of blocs upto the `MaterialApp` widget. 
 
2.Also when popped from `Screen2` to `Screen1`, the blocs should not be disposed. Hence, continue to maintain state when popped from `Screen2` 
 
3.Should not pass the bloc via constructor or as arguments in `Navigator` 

`Currently getting following error: flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════ flutter: The following assertion was thrown building Screen2(dirty): flutter:         BlocProvider.of() called with a context that does not contain a BlocA. flutter:         No ancestor could be found starting from the context that was passed to flutter: BlocProvider.of<BlocA>(). flutter: flutter:         This can happen if the context you used comes from a widget above the BlocProvider. flutter: flutter:         The context used was: Screen2(dirty)`

**Comment by mazud21** [comment]
This post has a lot of solution, for every  conversation I've read and understanding, thank you all. 

I want to make refresh list on page A and I refresh trigger on page B, that use parameter to carry(a BLoC) from page A and use parameter to make relation from before page, I use trigger below Navigator.pop(context) and familyBloc.add(GetFamilyList()), when I back to page A, the list is update now.

Page A

```
showModalBottomSheet(){
...
AddFamily(familyBloc: _familyBloc)
...
}
```


Page B
```
final FamilyBloc familyBloc;
AddFamily({required this.familyBloc});
```

Function/Method
`Navigator.pop(context);        widget.familyBloc.add(GetFamilyList());`

maybe can help someone
