### ISSUE TITLE
How do I get the state of Bloc in different screens on the Angular Dart

### ISSUE THREAD

**Issue by mranhtu** [felangel/bloc#741]
Flutter there will be BlocBuilder to help listen to the changes of the Bloc. So in Angular Dart i want to get the state of Bloc in different screens, how can I do it.
Thank you.

**Comment by felangel** [comment]
Hi @mranhtu 👋 
Thanks for opening an issue!

You can use the bloc pipe in angular dart which will handle updating your template whenever the bloc's state changes. Please refer to the [counter example](https://github.com/felangel/bloc/tree/master/examples/angular_counter) specifically https://github.com/felangel/bloc/blob/4e790345052e875c6998268a50765ef144d2bad6/examples/angular_counter/lib/src/counter_page/counter_page_component.html#L3.

Hope that helps!
