### ISSUE TITLE
Hi , I found It's hard to use

### ISSUE THREAD

**Issue by JamesBondPc** [felangel/bloc#743]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by felangel** [comment]
Hi @JamesBondPc 👋
Thanks for opening an issue!

Unfortunately there is not enough information in this issue for me to help. Please avoid opening an issue without filling out the template or providing specific examples/reproduction steps.
