### ISSUE TITLE
Update the version of plugin on Intellij idea

### ISSUE THREAD

**Issue by prasant10050** [felangel/bloc#747]
https://plugins.jetbrains.com/plugin/12129-bloc-code-generator

**Comment by felangel** [comment]
Hi @prasant10050 👋 
Thanks for opening an issue!

Unfortunately for some reason I have submitted an update and it is still "pending". Will try to resolve this asap 👍

**Comment by prasant10050** [comment]
Can I add updated plugin on my intellij idea without approval from Intellij
idea

**Comment by felangel** [comment]
@prasant10050 I've submitted the update and it is pending approval but in the meantime you can download and install it from the [releases](https://github.com/felangel/bloc/releases/tag/intellij_bloc-v1.7.0).
