### ISSUE TITLE
BloC instance for each list view item

### ISSUE THREAD

**Issue by mustafa96m** [felangel/bloc#751]
Hey Everyone!

Is it a good idea to instantiate a BloC for each ListView item? And if so, is having BlocBuilder with BlocProvider together to handle the disposal of blocs as the list view recycles, is a good idea as well?

I'm doing this because I need the ListView Item (Individually) to react upon a state that can take time per list view item.

Such as I want to display a loading indicator until the request completes, and handle cases such as failure due to internet connection, etc.

The reason I don't want to do this in a single BloC is that the states (Items Loaded, Items Loading..) will be tightly coupled with the action logic (Item Updated, Item Updating, or Item Failed Updating) that I want to separate for each BloC.

The UI Skeleton,
```
ListView
-- ListViewTile (BlocA: Item1)
--- Button
.
.
-- ListViewTile (BlocA: ItemN)
--- Button
```

**Comment by felangel** [comment]
Hi @mustafa96m 👋
Thanks for opening an issue!

Have you taken a look at the [complex list example](https://github.com/felangel/bloc/tree/master/examples/flutter_complex_list)?

**Comment by mustafa96m** [comment]
Hi Felix,

Thanks for sharing this example. This is exactly what I was looking for!

I mostly learned the BloC pattern from the rest of the examples you authored, yet I don't know how I missed this one! Sorry for disturbing you and Happy Holidays.

**Comment by RobertHeim** [comment]
@felangel: I wonder why the `isDeleting` state is part of the item-model rather than part of the bloc's state? To me this feels wrong because it requires me to pollute the model. I would consider a wrapper class `ItemMeta` that handles the meta data per item and might hold a reference to a specific item (model).

Could you also give an answer to the original question whether it is an anti-pattern to create a bloc per item?

**Comment by dragonkhoi** [comment]
> @felangel: I wonder why the `isDeleting` state is part of the item-model rather than part of the bloc's state? To me this feels wrong because it requires me to pollute the model. I would consider a wrapper class `ItemMeta` that handles the meta data per item and might hold a reference to a specific item (model). What are your thoughts regarding the model-separation?
> 
> Could you also give an answer to the original question whether it is an anti-pattern to create a bloc per item?

Agree, I have a fairly complex list of items and am having trouble with creating cubits inside of a ListView.builder itemBuilder callback. Are cubits not designed to be created in ListViews?

**Comment by Sultandi** [comment]
Hi @felangel,
after seeing ur sample pattern with listview: 
[https://github.com/felangel/bloc/blob/master/examples/flutter_complex_list/lib/complex_list/view/complex_list_page.dart](url)

i got this problem too, how can i achieve each bloc item on list view.
(since the itemCount must reload and also with the itemView.)
**is this bad think?**
```
ListView.separated(
      physics: const BouncingScrollPhysics(),
      itemCount: items.length,
      itemBuilder: (context, index) => BlocProvider<ItemBloc>(
        create: (context) => ItemBloc(),
        child: _ItemWithBuilderView(),
      ),
      separatorBuilder: (BuildContext context, int index) {
        return const Divider(height: 10);
      },
    );
```

**Comment by PatrickGeyer** [comment]
Would like to +1 as would like to create Blocs in a listview as well.

**Comment by bambinoua** [comment]
Hello, @felangel.

Could you please to explain why this code
```dart
Future<void> deleteItem(String id) async {
    final deleteInProgress = state.items.map((item) {
      return item.id == id ? item.copyWith(isDeleting: true) : item;
    }).toList();

    emit(ComplexListState.success(deleteInProgress));

    unawaited(
      repository.deleteItem(id).then((_) {
        final deleteSuccess = List.of(state.items)
          ..removeWhere((element) => element.id == id);
        emit(ComplexListState.success(deleteSuccess));
      }),
    );
  }
```
is looks like it is? I mean why do you send a list with one item containing `isDeleting = true` then remove it and send the list without deleted item? Why do not skip first emission and just use last one where item is deleted? What is the sense?
