### ISSUE TITLE
How to build a widget only first time? 

### ISSUE THREAD

**Issue by klaszlo8207** [felangel/bloc#759]
I have some Events and States, I am using BlocBuilder

Is there any way to build my BlocBuilder only once when my state is **GotRepositoryAndDownloadedFilesState** and then never when the state becomes else state? 

What I want is:

BlocBuilder<RenderBloc, BaseState>(builder: (context, state) {
  if (state is GotRepositoryAndDownloadedFilesState) {
    return _buildLogoWidget();
  } else {
    return Container();
  }
}),

I don't want to return the new Container, but I don't want to rebuild the _buildLogoWidget because that is an animated widget.

Update:

I ended up with this thing:

        BlocBuilder<RenderBloc, BaseState>(builder: (context, state) {
          if (state is GotRepositoryAndDownloadedFilesState) {
            if (_logoWidget == null) _logoWidget = _buildLogoWidget();
            return _logoWidget;
          } else {
            return _logoWidget ?? Container();
          }
        }),

`Widget _logoWidget;`

**Can somebody help in this? What is the better solution for my probleme?**

**Comment by felangel** [comment]
Hi @klaszlo8207 👋 
Thanks for opening an issue!

Can't you just have an `Initial` and a `Loaded` state? then your `BlocBuilder` would look something like:

```dart
BlocBuilder<MyBloc, MyState>(
  builder: (context, state) {
    return state is Loaded
      ? LoadedWidget()
      : InitialWidget();
  },
)
```

Closing for now but feel free to add additional information/comments and I'm happy to continue the conversation 👍

**Comment by tenhobi** [comment]
@klaszlo8207 

Either way, the `BlocBuilder` (and  `StreamBuilder` in general) can rebuild at any time, ergo you cannot prevent it from rebuilding. 

The Animated widget should not care about this, because it uses some State and therefore it would work fine (you cannot tell the difference) even with some rebuilds.
