### ISSUE TITLE
Doc bug:  Constant constructor can't call non-constant super constructor of 'Equatable

### ISSUE THREAD

**Issue by realtebo** [felangel/bloc#76]
At page: 

https://felangel.github.io/bloc/#/flutterinfinitelisttutorial?id=data-model

The syntax 

      const Post({this.id, this.title, this.body}) : super([id, title, body]);

looks like no more valid, it throws 2 errors

> Constant constructor can't call non-constant super constructor of 'Equatable'.

and

> Initializer expressions in constant constructors must be constants.

It seems fixable as 

    Post({this.id, this.title, this.body}) : super([id, title, body]);

But I don't know if removing leading `const` changes the behaviours. If add

**Comment by felangel** [comment]
Good catch! I must’ve missed it. The correct syntax is without the const and I’ll update the docs shortly. 👍
