### ISSUE TITLE
Waiting for multiple blocs

### ISSUE THREAD

**Issue by payam-zahedi** [felangel/bloc#762]
Hi @felangel , thanks for this awesome library.
I have the below situation:
 imagine I have a Splash screen that waited for cart bloc and the favorite bloc.

- cart bloc is for taking user cart information.
- and the favorite bloc is about getting user favorite products.

I just want to get the cart information and the favorite products and if everything was ok push the user to the next screen. if some error received I want to show error and retry button.

I think MultiBlocBuilder would be great for this situation. but there is no MultiBlocBuilder.

can u give me a solution for that?

**Comment by felangel** [comment]
Hi @payam-zahedi 👋 
Thanks for opening an issue!

Regarding `MultiBlocBuilder`, there was [an issue](https://github.com/felangel/bloc/issues/538) for it and after multiple discussions we decided not to include it.

In your case you have several options:
- Nest `BlocBuilders`
- Create a new bloc which combines states from the other two
- Combine the states of the blocs using `combineLatest` and use a `StreamBuilder` to handle building the UI.

Hope that helps 👍

**Comment by payam-zahedi** [comment]
dear @felangel , thanks for your useful response.
if you have any resource or tutorial link, it would be very helpful for me.
thanks

**Comment by urusai88** [comment]
> * Create a new bloc which combines states from the other two
> * Combine the states of the blocs using `combineLatest` and use a `StreamBuilder` to handle building the UI.

Can we have some examples please?

**Comment by felangel** [comment]
@urusai88 I've created a [sample gist](https://gist.github.com/felangel/ce3ed5b80bb2445e16f4bb7115205d1c). Please let me know if that helps 👍

**Comment by urusai88** [comment]
@felangel thanks you very much!

**Comment by felangel** [comment]
@urusai88 no problem here's a [sample gist](https://gist.github.com/felangel/3523917c36480068f1574416efab998b) which shows how you can composed streams within a bloc. In this case it's obviously a bit weird because the bloc is just a proxy but normally you'd execute some sort of logic/processing on the data from the streams and output a normalized view model for the UI to consume.

Hope that helps!
