### ISSUE TITLE
[Discussion] Improve Bloc to Bloc/Stream Integration

### ISSUE THREAD

**Issue by felangel** [felangel/bloc#765]
**Is your feature request related to a problem? Please describe.**
When using bloc, it is fairly common to have blocs which need to react to other blocs or `Streams`. The current recommended approach involves directly subscribing to the `Stream` within the bloc:

```dart
class MyBloc extends Bloc {
  final OtherBloc otherBloc;
  StreamSubscription otherBlocSubscription;

  MyBloc(this.otherBloc) {
    otherBlocSubscription = otherBloc.listen((state) {
        // React to state changes here.
        // Add events here to trigger changes in MyBloc.
    });
  }

  @override
  Future<void> close() {
    otherBlocSubscription.cancel();
    return super.close();
  }
}
```

This is not ideal because it requires one or more subscriptions to be managed manually and introduces additional complexity which increases with the number of consumed `Streams`.

**Describe the solution you'd like**

**UPDATED PROPOSAL**: https://github.com/felangel/bloc/issues/765#issuecomment-573368016

~~It might be better to potentially introduce a new widget -- something like `BlocSink` which handles the subscription to the desired `Stream` and exposes callbacks which allow developers to conveniently `add` an `event` to the desired bloc.~~

```dart
BlocSink<int, TickerBloc, TickerEvent>( // stream data type, bloc type, event type
  stream: Stream.periodic(Duration(seconds: 1), (x) => x).take(10),
  bloc: BlocProvider.of<TickerBloc>(context), // optional - will look up bloc via context by default
  onData: (tick, add) => add(Tick(tick)),
  onError: (error, add) => add(TickError(error)), // optional
  onDone: (add) => add(TickFinished()), // optional
  child: MyChild(),
)
```

~~In the above example, `BlocSink` would subscribe to the `Stream.periodic` and each time data is emitted, it would add a `Tick` event to the `TickerBloc` with the current `tick`. If an error is emitted, it would add a `TickError` with the current error and once the `Stream` has completed, it will add a `TickFinished` event.~~

**Comment by ThinkDigitalSoftware** [comment]
Why a widget? Does it need to be processed In the widget layer? Since blocs are Dart classes, I don't see why it should be a widget

**Comment by felangel** [comment]
@ThinkDigitalSoftware by using a widget we can intelligently subscribe and cancel the subscription if it is based on the current widget tree. I'm totally open to other suggestions if you have any 😄

**Comment by ThinkDigitalSoftware** [comment]
I think the subscription should be destroyed when the receiving bloc is destroyed, whenever that may be

**Comment by ThinkDigitalSoftware** [comment]
It can be a mixin or an extendable class, the dependency can be passed in and subscribed to and canceled when the bloc is

**Comment by felangel** [comment]
In that case you could make the BlocSink the child of the BlocProvider which created the bloc. There may be cases where you only want to subscribe to a stream for a subset of the lifecycle of the bloc. Thoughts?

**Comment by ThinkDigitalSoftware** [comment]
I don't understand why this needs to be a widget. Since we're trying to keep from doing logic inside a widget. I don't see any benefits

**Comment by felangel** [comment]
> It can be a mixin or an extendable class, the dependency can be passed in and subscribed to and canceled when the bloc is

That's definitely another option I've considered but I haven't been happy with the APIs that I've brainstormed. Mind sharing some code snippets of what you're envisioning?

> I don't understand why this needs to be a widget. Since we're trying to keep from doing logic inside a widget. I don't see any benefits

It wouldn't be for logic, it's just a way to notify the bloc based on data from a different stream.

**Comment by vshashi01** [comment]
I like the idea of being able to simplify the bloc subscriptions, but I dont quite understand the need for it to be a widget. More of than not.. I do some kinda processing on the states emitted by the subscribed bloc (BlocA) to decide if I should emit a new state on the reacting bloc (BlocB). 

With the BlocSink, I would need to create a separate event class that the takes the State from BlocA as a variable, and then process this in the bloc, yes?

**Comment by ThinkDigitalSoftware** [comment]
Then I think the bloc can accept an optional property that can be of type Bloc where it can subscribe to its stream, and have an onEvent callback

**Comment by andesappal** [comment]
How do we use logic to solve this issue?

**Comment by tenhobi** [comment]
I can see why the BLoC to BLoC communication might be an issue for some people, but that can be solved with some proper architecture and using Blocs only as it is a presentation layer thing which holds the current state and direction the logic to other layers which are independent of used presentation dependencies. And I still use the most powerful thing this library offers, the state management.

I really like the idea of Clean Architecture; you can see an idea of that in @ResoDev amazing tutorial. But I also understand that many people may choose to do different and need to be able to mix Blocs or even streams. 

Maybe also some additional documentation how you can avoid BLoC to BLoC communication might be welcomed, for those of us, who conciser BLoC a presentation thing.

**Comment by baylessj** [comment]
I'm a little confused on how this would interact with a current setup with BlocProviders. I put together the following example of how I would hope the API could look:

## Current structure:

TodosBloc
```dart
class TodosBloc extends Bloc {
  final CarsBloc carsBloc;
  final RepeatsBloc repeatsBloc;
  final StreamSubscription _carsSubscription, _repeatsSubscription;

  TodosBloc({this.carsBloc, this.repeatsBloc}) {
    _carsSubscription = carsBloc.listen((state) { add(CarsUpdated(); });
    _repeatsSubscription = repeatsBloc.listen((state) { add(RepeatsUpdated(); });  
  }

  @override 
  close() {
    _carsSubscription?.cancel();
    _repeatsSubscription?.cancel();
   super.close();
  }
```

main.dart
```dart
runApp(
  MultiBlocProvider(
    providers: [
      BlocProvider<CarsBloc>(
        create: (context) => CarsBloc()
      ),
      BlocProvider<RepeatsBloc>(
        create: (context) => RepeatsBloc()
      )
    ],
    child: BlocProvider<TodosBloc>(
      create: (context) => TodosBloc(
         carsBloc: BlocProvider.of<CarsBloc>(context),
         repeatsBloc: BlocProvider.of<RepeatsBloc>(context)
      ),
      child: MaterialApp()   
    )
  )
)
```

## Proposed Structure

No other blocs passed to TodosBloc.

main.dart
```dart
runApp(
  MultiBlocProvider(
    providers: [
      BlocProvider<CarsBloc>(
        create: (context) => CarsBloc()
      ),
      BlocProvider<RepeatsBloc>(
        create: (context) => RepeatsBloc()
      )
    ],
    child: MultiBlocSinkProvider<TodosBloc>(
      sinks: [
        BlocSink<CarsBloc>(
           onData: (data, add) => add(CarsUpdated(data)),
           onError: (error, add) => add(CarsError(error))
        ),
        BlocSink<RepeatsBloc>(
          onData: (data, add) => add(RepeatsUpdated(data)),
          onError: (error, add) => add(RepeatsError(error))
        ),
      ],
      create: (context) => TodosBloc(),
      child: MaterialApp()
    )
  )
)
```

I would definitely be open to other options for the `MultiBlocSinkProvider` name, that was just the first thing I thought of to name it.

**Comment by RollyPeres** [comment]
Hey @felangel , nice to see this feature discussed. I've put together a quick prototype for a flexible approach. I believe taking advantage of existing widgets could help. Also, allowing users to be able to add events to multiple blocs depending on their needs might be helpful for some.

```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        BlocProvider(create: (_) => ABloc()),
        BlocProvider(create: (_) => BBloc()),
      ],
      child: MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: const HomePage(),
      ),
    );
  }
}

class HomePage extends StatelessWidget {
  const HomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Colors.blue,
        child: StreamListener<String>(
          stream: () async* {
            yield 'first item';
            yield 'second item';
          }(),
          onData: (data) {
            BlocProvider.of<ABloc>(context).add(ADataLoadedEvent('A-$data'));
            BlocProvider.of<BBloc>(context).add(BDataLoadedEvent('B-$data'));
          },
          onError: (error) {
            BlocProvider.of<ABloc>(context).add(AErrorEvent(error));
            BlocProvider.of<BBloc>(context).add(BErrorEvent(error));
            return error.toString();
          },
          child: Center(
            child: Text('Hello'),
          ),
        ),
      ),
    );
  }
}

class StreamListener<T> extends StatelessWidget {
  const StreamListener({
    Key key,
    this.stream,
    this.onData,
    this.onError,
    this.child,
  }) : super(key: key);

  final Stream<T> stream;
  final Widget child;

  final void Function(T) onData;
  final T Function(Object) onError;

  @override
  Widget build(BuildContext context) {
    return StreamProvider<T>(
      create: (_) => stream,
      catchError: (context, error) => onError(error),
      child: Consumer<T>(
        builder: (BuildContext context, T value, Widget child) {
          onData(value);
          return child;
        },
        child: child,
      ),
    );
  }
}
```

**Comment by felangel** [comment]
@tenhobi thanks for the feedback! I think that even with clean architecture you will have valid cases where blocs need to consume a `Stream` of data and react appropriately. Thoughts?

@baylessj thanks for the feedback! I'm a bit confused by the naming though. If I'm understanding it correctly, you are subscribing to the `TodosBloc` and want to update the `CarsBloc` and `RepeatsBloc` in response to changes in the `TodosBloc`? If that's the case, I think calling it `onData` and `onError` for the `CarsBloc` and `RepeatsBloc` is confusing because it makes it seem like the subscription is on those `Streams` rather than the `TodosBloc` state stream. Let me know if that makes sense or if I misunderstood and thanks again!

@RollyPeres thanks for your feedback! I considered that approach as well and believe it is definitely reasonable but I don't know if it would make sense to include it in the bloc library. It might be better to publish `StreamListener` as a separate package. Thoughts?

**Comment by RollyPeres** [comment]
@felangel Agree, it is too generic to include it in the bloc library. But maybe some wrapper on top of it, to abstract the `.add` on bloc(s) could be helpful for people. Something pretty close to what you've initially suggested, but maybe just pass in the event(s) you want the data/error to be added to.

**Comment by felangel** [comment]
@RollyPeres mind providing a small snippet of how you'd modify the proposal? Thanks!

**Comment by tenhobi** [comment]
@felangel as I am thinking about it, there might actually be some stuff you wanna keep in the presentation layer and then it would be ok. Well, it seems like a valid feature after all. 😄

**Comment by RollyPeres** [comment]
Sure, a sleepy one @felangel  🤞. This clearly has a couple of problems like needing to explicitly pass in the bloc, but just as an ideea.
```
class BlocSink<T, E, S> extends StatelessWidget {
  BlocSink({
    Key key,
    this.stream,
    this.bloc,
    this.child,
    this.dataEvent,
    this.errorEvent,
    this.valueOnError,
  }) : super(key: key);

  final Stream<T> stream;
  final Bloc<E, S> bloc;
  final Widget child;

  final E Function(T) dataEvent;
  final E Function(Object) errorEvent;
  final T valueOnError;

  @override
  Widget build(BuildContext context) {
    return StreamListener<T>(
      stream: stream,
      child: child,
      onData: (data) =>
          (bloc ?? BlocProvider.of<Bloc<S, E>>(context)).add(dataEvent(data)),
      onError: (error) {
        (bloc ?? BlocProvider.of<Bloc<S, E>>(context)).add(errorEvent(error));
        return valueOnError;
      },
    );
  }
}
```
And consumed like: 

```
child: BlocSink<String, AEvent, AState>(
            stream: () async* {
              yield 'first item';
              yield 'second item';
            }(),
            bloc: ABloc(),
            dataEvent: (data) => ADataLoadedEvent(data),
            errorEvent: (error) => AErrorEvent(error),
            child: Container(),
          )
```

**Comment by warriorCoder** [comment]
I like the idea of being able to consume a stream in the UI layer, but then I'm also wondering if that isn't convoluting the UI with data that would be better suited for some state, which the bloc captures and then presents to the dumb UI.

Now if we're talking about bloc to bloc communication, I have several cases in my app, I don't think a widget should be involved but the communication needs to happen in the bloc. So if you could make it easier to setup and consume streams from within a bloc from another bloc I'd be all over that.

**Comment by baylessj** [comment]
> @baylessj thanks for the feedback! I'm a bit confused by the naming though. If I'm understanding it correctly, you are subscribing to the `TodosBloc` and want to update the `CarsBloc` and `RepeatsBloc` in response to changes in the `TodosBloc`? If that's the case, I think calling it `onData` and `onError` for the `CarsBloc` and `RepeatsBloc` is confusing because it makes it seem like the subscription is on those `Streams` rather than the `TodosBloc` state stream. Let me know if that makes sense or if I misunderstood and thanks again!

@felangel My naming was a bit vague there, my apologies. The goal was to make it so that `TodosBloc` would listen to the `RepeatsBloc` and `CarsBloc`. I agree that the subscription should be owned by the stream that is doing the listening (the `TodosBloc`).

My `MultiBlocSinkProvider` was meant to be a `BlocProvider` with the addition of a list of "sinks" or subscriptions that the created bloc would be given. In the example, the `MultiBlocSinkProvider` would create a `TodosBloc` in the same manner as a `BlocProvider` in the current API and, upon creating of the `TodosBloc`, create the subscriptions to the `CarsBloc` and `RepeatsBloc` that are specified in the `sinks` parameter. The intent with the "Multi" part of the name was to signify that there can be multiple sinks given to this provider, similar to how a `MultiBlocProvider`  can be given multiple blocs. Each of the sinks would represent one subscription in a manner similar to the `BlocSink` class that you described in the OP.

I hope that clears up my intent a bit, I'm still a bit new to using this library so using the right terminology to articulate this is tricky :smile:

**Comment by felangel** [comment]
I'm been messing around with this some more and have landed on another solution which is pure Dart.

```dart
class MyBloc extends Bloc with BlocStreamListenerMixin {
  MyBloc(OtherBloc otherBloc) {
    subscribe(otherBloc);
  }

  @override
  onStreamData(Stream stream, dynamic data) {
    // React to state changes here.
    // Add events here to trigger changes in MyBloc.
  }
}
```

Would love to hear everyone's thoughts and thanks for the awesome feedback!

**Comment by ThinkDigitalSoftware** [comment]
Yess, I'm onboard with this 100%!

**Comment by vshashi01** [comment]
> I'm been messing around with this some more and have landed on another solution which is pure Dart.
> 
> ```dart
> class MyBloc extends Bloc with BlocStreamListenerMixin {
>   MyBloc(OtherBloc otherBloc, Stream otherStream) {
>     // subscribe comes from the `BlocStreamListenerMixin`
>     // and can be called multiple times on various streams
>     // in order to react to changes in the stream.
>     subscribe(otherBloc);
>     subscribe(otherStream);
>   }
> 
>   @override
>   onStreamData(Stream stream, dynamic data) {
>     // React to data emitted from subscribed streams here.
>     // Add events here to trigger changes in MyBloc.
>   }
> 
>   @override
>   onStreamError(Stream stream, dynamic error, StackTrace stackTrace) {
>     // React to streams being closed
>     // Add events here to trigger changes in MyBloc.
>   }
> 
>   @override
>   onStreamDone(Stream stream) {
>     // React to errors emitted from one or more streams
>     // Add events here to trigger changes in MyBloc.
>   }
>   
>   @override
>   bool cancelStreamOnError(Stream stream) {
>     // Determine whether an error in the stream should cancel the subscription
>   }
> }
> ```
> 
> Would love to hear everyone's thoughts and thanks for the awesome feedback!

I love this approach alot more and it feels much more cleaner than the widget approach.

**Comment by RollyPeres** [comment]
@vshashi01 I wouldn't go as far as saying a lot cleaner, since what @felangel showcased is how you would consume it, and not how it's also implemented. I threw in a possible solution using the widget tree, because it goes along perfectly with existing implementations from `provider`. 

Although I find @felangel 's solution feasible, I personally don't like this part:
```
MyBloc(OtherBloc otherBloc, Stream otherStream) {
    // subscribe comes from the `BlocStreamListenerMixin`
    // and can be called multiple times on various streams
    // in order to react to changes in the stream.
    subscribe(otherBloc);
    subscribe(otherStream);
  }
``` 
I believe the main idea of this discussion was to get rid of manually subscribing to a stream, which your proposed solution doesn't really do. Your users would still have to remember to manually call subscribe in constructor and we both know how that went last time they had to remember doing something(`props` caugh).

**Comment by felangel** [comment]
@RollyPeres how would you specify which stream you'd like to listen to without something like the subscribe? Isn't it equivalent to passing a stream to the BlocSink widget?

**Comment by vshashi01** [comment]
> @vshashi01 I wouldn't go as far as saying a lot cleaner, since what @felangel showcased is how you would consume it, and not how it's also implemented. I threw in a possible solution using the widget tree, because it goes along perfectly with existing implementations from `provider`.
> 
> Although I find @felangel 's solution feasible, I personally don't like this part:
> 
> ```
> MyBloc(OtherBloc otherBloc, Stream otherStream) {
>     // subscribe comes from the `BlocStreamListenerMixin`
>     // and can be called multiple times on various streams
>     // in order to react to changes in the stream.
>     subscribe(otherBloc);
>     subscribe(otherStream);
>   }
> ```
> 
> I believe the main idea of this discussion was to get rid of manually subscribing to a stream, which your proposed solution doesn't really do. Your users would still have to remember to manually call subscribe in constructor and we both know how that went last time they had to remember doing something(`props` caugh).

I disagree with you, the problem we were trying to work around was manually managing the stream subscriptions. If you want to go the BlocSink way, I dont see why you cant already do it already by add events based on stream changes from the UI. 

The cleaner here I meant to say was to avoid having this logic in the UI layer. When a bloc relies on another bloc or stream for correctness and functionality it makes sense that their logic and dependency is reflected in the bloc class rather than elsewhere in the widget tree. This approach unifies the best of the both world for me. 
1. No invisible dependency in the Widget tree to process streams and add events. 
2. A structured way to subscribe and process streams directly in the bloc class.

**Comment by ThinkDigitalSoftware** [comment]
I agree with @vhashi01 about the invisible dependencies in the widget tree. Actually his whole argument, lol

**Comment by RollyPeres** [comment]
> @RollyPeres how would you specify which stream you'd like to listen to without something like the subscribe? Isn't it equivalent to passing a stream to the BlocSink widget?

You could force the user to override an abstract method from your mixin instead of letting him do it in constructor, or just have an abstract method on the bloc itself that the user can override and pass in a list of streams.

And it's not equivalent since you can mark the stream as `@required` which tells the user it needs to pass in a stream. It's easier than having to remember to call a method from a mixin inside bloc constructor.



> I disagree with you, the problem we were trying to work around was manually managing the stream subscriptions.

@vshashi01, that's exactly what I said, but with other words. Disagreement is constructive but it's based on somewhat different opinions/visions if not completely opposite.

 Again, I just proposed a possible solution based on existing implementations from `provider`, which is a package based on making good use of the power that widgets bring to the table. There's plenty of so called "invisible" widgets, it doesn't mean they're bad. Surely you can agree `InheritedWidget` is somewhat helpful, although it's "invisible". 

At this point in time both solutions have pluses and minuses. I don't really care if this gets implemented as a widget or using pure dart, things can already be done with or without this feature being available in bloc package anyways.

**Comment by ThinkDigitalSoftware** [comment]
+1 for the overrideable method

**Comment by vshashi01** [comment]
> > @RollyPeres how would you specify which stream you'd like to listen to without something like the subscribe? Isn't it equivalent to passing a stream to the BlocSink widget?
> 
> You could force the user to override an abstract method from your mixin instead of letting him do it in constructor, or just have an abstract method on the bloc itself that the user can override and pass in a list of streams.
> 
> And it's not equivalent since you can mark the stream as `@required` which tells the user it needs to pass in a stream. It's easier than having to remember to call a method from a mixin inside bloc constructor.
> 
> > I disagree with you, the problem we were trying to work around was manually managing the stream subscriptions.
> 
> @vshashi01, that's exactly what I said, but with other words. Disagreement is constructive but it's based on somewhat different opinions/visions if not completely opposite.
> 
> Again, I just proposed a possible solution based on existing implementations from `provider`, which is a package based on making good use of the power that widgets bring to the table. There's plenty of so called "invisible" widgets, it doesn't mean they're bad. Surely you can agree `InheritedWidget` is somewhat helpful, although it's "invisible".
> 
> At this point in time both solutions have pluses and minuses. I don't really care if this gets implemented as a widget or using pure dart, things can already be done with or without this feature being available in bloc package anyways.

Ah so what you are suggesting is just making a compulsory method to override the streams. I am okay with that. 



P.S
While Inherited Widgets are “invisible” widgets, their affect on the UI is not. You cant rebuild the UI unless you explicitly listen to the Inherited Widgets, ie BlocBuilders or Consumers.

**Comment by felangel** [comment]
@RollyPeres I'm not sure I understand your concern. If people forget to call `subscribe` then nothing will happen. I thought it made sense that you'd need to call `subscribe` with a stream in order to start listening to it. Also, you don't have to `subscribe` in the bloc's constructor; you can `subscribe` to whatever stream you want, wherever you want, and whenever you want.

```dart
mapEventToState(event) async* {
  if (event is EventA) {
    subscribe(someStream);
    ...
  }
}
```

The idea of having to override a `List<Stream>` getter  seems a bit awkward because then it isn't as easy to `subscribe` to a stream any time after bloc initialization. Also, if you dynamically change the `List<Stream>` I'm not sure what the expected behavior should be (do you automatically cancel all pending subscriptions that no longer exist?).

I have published [flutter_stream_listener](https://pub.dev/packages/flutter_stream_listener) which already exposes a widget to manage streams and subscriptions so you can use both approaches as you'd like. What do you think? Thanks again for everyone's feedback, I really appreciate it!

**Comment by tenhobi** [comment]
I like the idea behind `package:stream_listener` and `package:flutter_stream_listener`. Seems very easy to handle and work with. Like that!

Another question of mine is that if we have `package:stream_listener`, why would we force Bloc to use it? Why don't we transfer responsibility to the programmer? So they can then decide if they want to use `package:stream_listener` or `package:flutter_stream_listener` or some other approach, if needed at all.

**Comment by larssn** [comment]
I might be missing something here, came into this discussion late. So apologies if I'm stating the obvious (or something stupid).

> I'm been messing around with this some more and have landed on another solution which is pure Dart.
> 
> ```dart
> class MyBloc extends Bloc with BlocStreamListenerMixin {
>   MyBloc(OtherBloc otherBloc, Stream otherStream) {
>     // subscribe comes from the `BlocStreamListenerMixin`
>     // and can be called multiple times on various streams
>     // in order to react to changes in the stream.
>     subscribe(otherBloc);
>     subscribe(otherStream);
>   }
> 
>   @override
>   onStreamData(Stream stream, dynamic data) {
>     // React to data emitted from subscribed streams here.
>     // Add events here to trigger changes in MyBloc.
>   }
> 
>   @override
>   onStreamError(Stream stream, dynamic error, StackTrace stackTrace) {
>     // React to errors emitted from one or more streams
>     // Add events here to trigger changes in MyBloc.
>   }
> 
>   @override
>   onStreamDone(Stream stream) {
>     // React to streams being closed
>     // Add events here to trigger changes in MyBloc.
>   }
>   
>   @override
>   bool cancelStreamOnError(Stream stream) {
>     // Determine whether an error in the stream should cancel the subscription
>   }
> }
> ```
> 
> Would love to hear everyone's thoughts and thanks for the awesome feedback!

So how would this work in practise? (as the Streams would be dynamic)

```
onStreamData(Stream stream, dynamic data) {
// Why is the stream here?

  if (data instanceof OtherBlocState) {
    // Do business logic related to MyBloc.
  } else if (data instanceof OtherStreamType) {
    // Do business logic related to otherStream.
  }
}
```

If we're simply trying to make people remember to do a simple `.listen()`, then this is overengineering. Most of these functions already exist on `Stream`. You have `.handleError` (vanilla), the `.onErrorX` methods (Rx), `.doOnData` (Rx), `.doOnDone` (Rx), so why do we need to wrap this functionality in a new class?

My initial concerns about blocs consuming blocs, is simply it can quickly get out of hand, as you a basically building a tree of blocs. So if you feed events into the top of the tree, it can get increasingly difficult to figure out how the other blocs react. Especially if they're also depending on each other. The exact same statement can be applied to plain streams: it's easy to go overboard.

Now I'm not saying one shouldn't do that, ever. We are, in a few places, where it makes sense.

But there are many options of consuming and composing streams, especially with Rx, so I agree with @tenhobi that this is a problem you can generally architect your way out of.

**Comment by RollyPeres** [comment]
> If we're simply trying to make people remember to do a simple `.listen()`, then this is overengineering. Most of these functions already exist on `Stream`. You have `.handleError` (vanilla), the `.onErrorX` methods (Rx), `.doOnData` (Rx), `.doOnDone` (Rx), so why do we need to wrap this functionality in a new class?

That's pretty much what I was trying to avoid. What @felangel proposed is basically a `subscribe` instead of a `listen`, but instead of passing the callbacks directly to the listen method, you'd have to override some methods. The difference is insignificant, as long as we don't get rid of that subscribe. The subscribe needs to happen under the hood, cause if someone is passing a stream into the bloc, it does that so it would be listened to and be available to potentially alter bloc's state.

**Comment by jerryzhoujw** [comment]
> I'm been messing around with this some more and have landed on another solution which is pure Dart.
> 
> ```dart
> class MyBloc extends Bloc with BlocStreamListenerMixin {
>   MyBloc(OtherBloc otherBloc, Stream otherStream) {
>     // subscribe comes from the `BlocStreamListenerMixin`
>     // and can be called multiple times on various streams
>     // in order to react to changes in the stream.
>     subscribe(otherBloc);
>     subscribe(otherStream);
>   }
> 
>   @override
>   onStreamData(Stream stream, dynamic data) {
>     // React to data emitted from subscribed streams here.
>     // Add events here to trigger changes in MyBloc.
>   }
> 
>   @override
>   onStreamError(Stream stream, dynamic error, StackTrace stackTrace) {
>     // React to errors emitted from one or more streams
>     // Add events here to trigger changes in MyBloc.
>   }
> 
>   @override
>   onStreamDone(Stream stream) {
>     // React to streams being closed
>     // Add events here to trigger changes in MyBloc.
>   }
>   
>   @override
>   bool cancelStreamOnError(Stream stream) {
>     // Determine whether an error in the stream should cancel the subscription
>   }
> }
> ```
> 
> Would love to hear everyone's thoughts and thanks for the awesome feedback!

Will you consider output stream in this case ? because I think sometimes stream output will benefit for animations.

**Comment by jaripekkala** [comment]
Here's my two cents to the issue: extending the delegate pattern to allow registering them per bloc as well

```dart
class OtherBlocDelegate implements SingleBlocDelegate<OtherEvent, OtherState> {
  final MyBloc myBloc;

  OtherBlocDelegate(this.myBloc);

  @override
  onTransition(transition) {
    myBloc.add(MyParamChanged(transition.nextState.param));
  }

  // onEvent, onError
}
```

Of course, this would need to be registered when creating the `MyBloc` and unregistered on dispose.

**Comment by jerryzhoujw** [comment]
```dart
class MyBloc extends Bloc {
  final OtherBloc otherBloc;
  StreamSubscription otherBlocSubscription;

  MyBloc(this.otherBloc) {
    otherBlocSubscription = otherBloc.listen((state) {
        // React to state changes here.
        // Add events here to trigger changes in MyBloc.
    });
  }

  @override
  Future<void> close() {
    otherBlocSubscription.cancel();
    return super.close();
  }
}
```

When I meet a case that need to include a `countdown logic` into a bloc, should I include the countdown as stream and pass in bloc as a `StreamSubscription`, or I should create a `countdown ticker inside bloc` self ?

**Comment by ResoDev** [comment]
Have we come to the conclusion that managing the `StreamSubscription` ourselves is still the best option? I definitely don't like what [stream_listener](https://pub.dev/packages/stream_listener) does - even more boilerplate than before IMO.

**Comment by felangel** [comment]
@ResoDev Agreed. The more I played around with different solutions the better the existing approach looks 😄 

Closing for now but happy to reopen this if others have suggestions on how to improve 👍

**Comment by RollyPeres** [comment]
I sometimes use my version of `StreamListener`, e.g:
```
StreamListener<UserModel>(
      stream: context.repository<UserRepository>().currentUser$,
      onData: (user) => context.bloc<AuthBloc>().add(AuthStateChanged(user)),
      onError: (error) {
        context.bloc<AuthBloc>().add(AuthFailed(error));
        return null;
      },
      child: ...
    );
```

But there are times when manually subbing is still the preferred way, like when you don't always want to add events to bloc as a result of the incoming stream data or when you don't want to express your business logic as a series of stream operators since it's just not feasible.

**Comment by felangel** [comment]
@RollyPeres there's [flutter_stream_listener](https://pub.dev/packages/flutter_stream_listener) for that if you want to contribute to it 👍

**Comment by RollyPeres** [comment]
My approach uses `provider` under the hood, so it's a bit different than yours. A bit more limited on a couple of aspects(`StreamProvider` doesn't allow for `onDone` and `cancelOnError` to be explicitly handled) but has other stuff which yours doesn't(lazy, emit a value when an error occurs, specify initial value). I took a look at your package and came up with a small feature proposal which might be of help.

**Comment by pradt** [comment]
> @ResoDev Agreed. The more I played around with different solutions the better the existing approach looks 😄
> 
> Closing for now but happy to reopen this if others have suggestions on how to improve 👍

Came across this because I'm trying to do bloc to bloc communication. What is the existing approach ?

**Comment by felangel** [comment]
@pradt the current recommendation is documented [here](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication).

**Comment by pradt** [comment]
> @pradt the current recommendation is documented [here](https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication).

Ahh excellent, thank you very much.

**Comment by aytunch** [comment]
The package owner for [momentum](https://pub.dev/packages/momentum) said in reddit: 

> I made my own state management called momentum . It covers all basically.The strongest point of this that, you can easily access other logic class inside another logic class with almost zero setup. If you are familiar with flutter_bloc package, the logic class there is called "Bloc", in momentum, it's called "Controller". Now, let's take login and session bloc/controller as example here. Can you easily access "SessionBloc" inside "LoginBloc"? the answer is NO.With momentum, you can easily access and manipulate "SessionController" inside "LoginController" (and vice versa even) using only 1 line of code at all.
```

// "dependOn" is the magic here. It is a built in method inside MomentumController base class. I can say this is a game changing feature for this library.
    var sessionController = dependOn<SessionController>();
```

I shared hoping this could maybe be an inspiration for an alternate solution?

**Comment by visual-velocity** [comment]
i'm trying to implement or get the state of  second bloc state from first  bloc and trigger the event of first bloc. But the first is not getting second bloc state. I follow up with example- https://bloclibrary.dev/#/architecture?id=bloc-to-bloc-communication .
Can you tell me why this is happening?

**Comment by JulianSwales** [comment]
@visual-velocity  I've also tried to follow that example and it does not work due to the changes with the bloc versions.. 
I also tried to follow this project: 
https://github.com/kkogut95/flutter_bloc_lyrics/blob/master/lib/feature/song/search/bloc/songs_search_bloc.dart

Which has this: 
`class SongsSearchBloc extends Bloc<SongSearchEvent, SongsSearchState> {
  final LyricsRepository lyricsRepository;
  final SongAddEditBloc songAddEditBloc;

  StreamSubscription addEditBlocSubscription;

  SongsSearchBloc(
      {@required this.lyricsRepository, @required this.songAddEditBloc}) {
    addEditBlocSubscription = songAddEditBloc.listen((songAddEditState) {
      if (state is SearchStateSuccess) {
        if (songAddEditState is EditSongStateSuccess) {
          add(SongUpdated(song: songAddEditState.song));
        } else if (songAddEditState is AddSongStateSuccess) {
          add(SongAdded(song: songAddEditState.song));
        }
      }
    });
  }

  @override
  SongsSearchState get initialState => SearchStateEmpty();`

Which is the old format, and I can't seem to figure out how to migrate to the new format.. This project does what I want to do, updates the list when a new item is added on a second screen.  

I have yet to find an example of how to do this using the new 6.0 bloc specification.. It seems so simple, yet so far I have been unable to get it to work..

**Comment by JulianSwales** [comment]
@visual-velocity I just got this to work... I doubt it's the best or most elegant, but it is working for me.. 
Following the code I have a above, from that project I changed it to the following: 
```
class SongsSearchBloc extends Bloc<SongSearchEvent, SongsSearchState> {
  final LyricsRepository _lyricsRepository;
  final SongAddEditBloc _songAddEditBloc;

  StreamSubscription _addEditBlocSubscription;

  SongsSearchBloc(
      {@required LyricsRepository lyricsRepository, @required SongAddEditBloc songAddEditBloc}) 
    : assert(lyricsRepository != null),
       _lyricsRepository = lyricsRepository, 
     assert(songAddEditBloc != null),
       _songAddEditBloc = songAddEditBloc,
     super(SongSearchBloc());

    @override
  Stream<SongsSearchState> mapEventToState(SongSearchEvent event) async* {
    if (event is SongSearchInitial) {
        _addEditBlocSubscription?.cancel();
       _addEditBlocSubscription = _songAddEditBlock.listen(songAddEditState) {
        if (songAddEditState is EditSongStateSuccess) {
          add(SongUpdated(song: songAddEditState.song));
        } else if (songAddEditState is AddSongStateSuccess) {
          add(SongAdded(song: songAddEditState.song));
        }
      }

    }
    if (event is TextChanged) {
      yield* _mapSongSearchTextChangedToState(event);
    }
    if (event is RemoveSong) {
      yield* _mapSongRemoveToState(event);
    }
    if (event is SongUpdated) {
      yield* _mapSongUpdateToState(event);
    }
    if (event is SongAdded) {
      yield* _mapSongAddedToState(event);
    }
  }

 }

```

Something like the above should work for you... Hope this helps...

**Comment by visual-velocity** [comment]
Thank you JulianSwales.
It's working fine.☺

**Comment by misterfourtytwo** [comment]
the real nasty is when u get to listen to more than one stream, you need to throw them into bloc constructor args, add checks on changes, not forget to add every subscription cancel() into close(). especially when u have to add/remove dependency.

maybe better solution would be to add something like an externalSubscriptionBucket, which could be a `List|Map<StreamSubscription|Bloc|Cubit>` and run close on all values of it on bloc close, and in some way expose it in the bloc constructor, e.g. add optional named parameter like `List<StreamSubscription> createSubscriptions(Bloc bloc)`.

**Comment by webnickell** [comment]
@felangel what about add "addStream" method in Bloc? Is is possible?
