### ISSUE TITLE
[Question] testing navigation issue

### ISSUE THREAD

**Issue by rodrigobastosv** [felangel/bloc#767]
First of all, thanks for the effort in creating and maintaining such a great package.

My question is this, suppose i have the following widget (the code is just to give an idea, i writed fast, just want to give an idea)

```
class SigninPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        color: Theme.of(context).primaryColor,
        child: BlocProvider<SigninBloc>(
          create: (_) => SigninBloc(SigninRepository())),
          child: BlocListener<SigninBloc, SigninState>(
            listener: (context, state) {
              if (state is UserSignedSuccessfullyState) {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => NextPage()))
              }
            },
            child: Container(),
          ),
        ),
      ),
    );
  }
}
```

I want to unit test this line `Navigator.of(context).push(MaterialPageRoute(builder: (_) => NextPage()))`

So i made this test case:

```
testWidgets(
        'shows NextPage when UserSignedSuccessfullyState yielded',
        (WidgetTester tester) async {
      when(mockHomeBloc.state).thenReturn(UserSignedSuccessfullyState());
      await tester.pumpWidget(
        MaterialApp(
          home: Scaffold(
            body: Container(
              child: BlocProvider<SigninBloc>(
                  create: (_) => mockSigninBloc,
              child: BlocListener<SigninBloc, SigninState>(
                listener: (context, state) {
                  if (state is UserSignedSuccessfullyState) {
                    Navigator.of(context).push(MaterialPageRoute(builder: (_) => NextPage()))
                  }
                },
                child: Container(),
              ),
            ),
          ),
        ),
      );

      expect(find.byType(NextPage), findsOneWidget);
    });
```

What i would expect is to have the navigator line executed since i mocked the state of the bloc to the exact state i'm checking on BlocListener.

Am i messing something up? Or i just misunderstood some concepts?

Thanks!

**Comment by rodrigobastosv** [comment]
After more analysis i think i know the problem. I guess BlocListener is only executed after the state changes. So i guess mocking isn't gonna work

**Comment by felangel** [comment]
Hey @rodrigobastosv 👋 
Thanks for opening an issue and for the positive feedback!

If you want to mock the BlocListener you should create a `MockBloc` instance and then use `whenListen` from the `bloc_test` package to stub the state stream.

```dart
      whenListen(mockHomeBloc, Stream<HomeState>.fromIterable([InitialHomeState(), UserSignedSuccessfullyState()]);
```

Hope that helps 👍

**Comment by rodrigobastosv** [comment]
Thanks @felangel , i closes the issue because i solved my problem in a diferent way. But i'll refactor to use this. Thanks again!
