### ISSUE TITLE
Graphics on overwiew outdated

### ISSUE THREAD

**Issue by rasmk** [felangel/bloc#771]
Block architecture image is outdated on overview page. It still refers to `dispatch` for dispatching events, while it is `add` now.

I mean this one:
![Bloc acrhitecture](https://raw.githubusercontent.com/felangel/bloc/master/docs/assets/bloc_architecture.png)

Nothing urgent. This is my first point of reference though, so would be nice to fix. I felt `dispatch` more natural and keep forgetting `add`.

**Comment by felangel** [comment]
Hey @rasmk 👋
Thanks for opening an issue!

Great point, thanks for bringing that up! I'll be sure to update the graphic asap 👍
