### ISSUE TITLE
debounceTime and mergeWith not working

### ISSUE THREAD

**Issue by jjoao07** [felangel/bloc#772]
Hi @felangel 

I'm trying to get validation working with Firebase Login example,
but for somehow, I can't get it working with the streams from `transformEvents` like in the screenshot below.

![image](https://user-images.githubusercontent.com/19816874/72203704-ba535f00-3477-11ea-9d8d-3b39b32e8a27.png)

I also have defined observable, as you have done on your medium post, but still not working.

`final observableStream = events as Observable<LoginEvent>;`

![image](https://user-images.githubusercontent.com/19816874/72203747-79a81580-3478-11ea-9deb-57614b393688.png)

Can you please help out the best way to do form validation with the login, or I should go have a look the old Form validation example, which I'm not sure that is updated with the latest version of the library.

Thanks

**Comment by felangel** [comment]
Hi @jjoao07 👋
Thanks for opening an issue!

You need to make sure you import the RxDart package. With bloc v3.0.0 and above you no longer need to cast to Observable because RxDart uses extensions on Stream. Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with a link to a sample app or additional info if you're still running into problems 👍

**Comment by jjoao07** [comment]
> Closing for now but feel free to comment with a link to a sample app or additional info if you're still running into problems 👍

Worked, thanks
