### ISSUE TITLE
[counter-bloc] how to preload counter init state

### ISSUE THREAD

**Issue by jerryzhoujw** [felangel/bloc#779]
[CounterBloc](https://bloclibrary.dev/#/fluttercountertutorial?id=counter-bloc) is very easy and good to understand in this case.

```dart
class CounterBloc extends Bloc<CounterEvent, int> {
  @override
  int get initialState => 0;

  @override
  Stream<int> mapEventToState(CounterEvent event) async* {
    switch (event) {
      case CounterEvent.decrement:
        yield state - 1;
        break;
      case CounterEvent.increment:
        yield state + 1;
        break;
    }
  }
}
```

I have a question on this, what should I do if I want to `save & preload` the counter number into & from plist.

In this case, I'm not sure **how to preload counter init state**. Because `initialState is not an async value`. When reading from plist, it's an async action.

>  **int get initialState => ?;**

**Comment by felangel** [comment]
Hi @jerryzhoujw 👋 
Thanks for opening an issue!

If you want to preload data I would highly recommend taking a look at [hydrated_bloc](https://pub.dev/packages/hydrated_bloc). Hope that helps 👍

**Comment by jerryzhoujw** [comment]
@felangel  Thank you.  

Before receive your message I just implement an extra  `Future preload()` in bloc, and call it when bloc init, which looks ok for me I think.

```dart
BlocProvider(
  create: CounterBloc bloc = CounterBloc()..preload(),
  child: SomeChild(),
);
```

**Comment by felangel** [comment]
If you want to have custom logic in preload that works fine. If you just want the bloc to pick up where it left off I would recommend `hydrated_bloc`. Glad you figured it out 🎉
