### ISSUE TITLE
Adjust IDE code generators to match the naming convention docs

### ISSUE THREAD

**Issue by jorgecoca** [felangel/bloc#780]
**Is your feature request related to a problem? Please describe.**

When using the IDE pluings to generate boilerplate code, the code it generates does not follow the naming convention described [here](https://bloclibrary.dev/#/blocnamingconventions). 

**Describe the solution you'd like**

Adjust the generators to create code that matches that expectation. That would be a great first step to add a bloc linter/enforcer that works out of the box.

**Comment by felangel** [comment]
This was already done in https://github.com/felangel/bloc/pull/774 and just needs to be published. I could use some help publishing the IntelliJ plugin though ;)

**Comment by felangel** [comment]
Closing this as it's already done and I will publish this weekend 👍
