### ISSUE TITLE
Each child must be laid out exactly once.

### ISSUE THREAD

**Issue by flowcharterappowner** [felangel/bloc#784]
git cloned your repo.
open the example weather app in android studio.
ran the app on my ipad.
get the above error message.

**Comment by felangel** [comment]
Hi @flowcharterappowner 👋
Thanks for opening an issue!

Are you able to provide any more detail? Was there a stacktrace or other errors? It would be great if you could maybe provide a screenshot of the debug console. Thanks!

**Comment by felangel** [comment]
Sorry about this! I was able to reproduce and fixed it in https://github.com/felangel/bloc/commit/0be0a53bada9dc37d67d7bf653044a77a1f00422
