### ISSUE TITLE
[Question] Infinite List Tutorial: Should I create `ItemBloc` for each Item in `ListBloc` when business expanded.

### ISSUE THREAD

**Issue by jerryzhoujw** [felangel/bloc#788]
I have read the [Infinite List](https://bloclibrary.dev/#/flutterinfinitelisttutorial?id=presentation-layer)  

I just think about a user case:

### Should have ItemBloc in ListBloc ?

if the post can be `upvote`, and there's a `upvote count`  in the Post

- Should I create a `PostItemBloc` for each `Post`
- Or should I create the extra Event & logic in original bloc [`PostBloc`](https://bloclibrary.dev/#/flutterinfinitelisttutorial?id=post-bloc) which include a post list

I think the previous option would be better, what's your idea ?

### How to setup ItemBloc initialState ?

if use the way of create `ItemBloc` for each item in `ListBloc`, how to setup the initial state will be a question

What I plan to do is this bellow:

```dart
class ItemBloc extends Bloc<ItemEvent, ItemState> {
  ItemBloc(this.initState);

  ItemState initState;

  @override
  ItemState get initialState => initState;

  @override
  Stream<TranslationState> mapEventToState(
    TranslationEvent event,
  ) async* {
    ...
  }
}
```

**Comment by felangel** [comment]
Hi @jerryzhoujw 👋 
Thanks for opening an issue!

Have you taken a look at the [complex list example](https://github.com/felangel/bloc/tree/master/examples/flutter_complex_list)? I would recommend starting with a single bloc and just updating your model to include the `upvoteCount` but if over time the requirements change and you find yourself having to add more complex logic to the `PostsBloc` then re-consider refactoring to multiple blocs. Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
