### ISSUE TITLE
Add FAQ to docs

### ISSUE THREAD

**Issue by tenhobi** [felangel/bloc#789]
It would be nice to add FAQ to docs. We already have something on Discord, but it would be better to add/move it to docs as well.

- [ ] Add FAQs which already are on Discord
- [ ] Add context issue https://github.com/felangel/bloc/issues/776#issuecomment-573571929
- [ ] Add something about structuring a project, some links like https://github.com/ResoCoder/flutter-tdd-clean-architecture-course would be awesome
- etc.

**Comment by felangel** [comment]
Merged in #803 👍
