### ISSUE TITLE
Working with abstract / base blocs

### ISSUE THREAD

**Issue by AshleyDeng** [felangel/bloc#790]
**Is your feature request related to a problem? Please describe.**
I am wondering if Bloc Widgets (BlocProvider, BlocBuilder, BlocListener, BlocConsumer) can work with abstract / base blocs. I want to abstract the pattern in order to handle some common features, e.g. show loading indicator for loading states for any blocs. 

However, I get errors like `BlocProvider.of() called with a context that does not contain a Bloc of type BaseBloc<BaseEvent, BaseState>.` It seems like we are expecting a concrete and exact bloc type instead of a abstract / base bloc type.

**Describe the solution you'd like**
Both BlocA and BlocB extend BaseBloc. Both ALoadingState and BLoadingState extends BaseState and implements LoadingState. 

So I want to have a utility function where it handling the loading state for BlocA & BlocB.

```
class BaseScreen {
  static Widget buildWith(Widget screen) {
    return Stack(children: <Widget>[screen, _handleLoadingAndErrorStates()]);
  }

  static Widget _handleLoadingAndErrorStates() {
    return Align(
      child: BlocBuilder<BaseBloc, BaseState>(
        builder: (context, state) {
          if (state is LoadingState) {
            return CircularProgressIndicator();
          }
          return Container();
        },
      ),
      alignment: FractionalOffset.center,
    );
  }
}
```

**Describe alternatives you've considered**
I've tried with BlocProvider, BlocBuilder, BlocListener and BlocConsumer. But all of them expect a concrete and exactly bloc type to work.

Is there any way we can abstract it? Thanks!

**Comment by tenhobi** [comment]
This is way how `package:provider` works, https://github.com/rrousselGit/provider/blob/master/lib/src/provider.dart#L181-L232

**Comment by felangel** [comment]
Hi @AshleyDeng 👋 
Thanks for opening an issue!

Are you able to share a link to a sample implementation/application which illustrates the problem you're having?

**Comment by felangel** [comment]
Closing for now as there isn't enough information for me to provide suggestions. Feel free to comment with additional information and a link to a sample application and I'm happy to continue the conversation 👍
