### ISSUE TITLE
BlocBuilder passes (context,state), but what about also passing the found bloc ?

### ISSUE THREAD

**Issue by flowcharterappowner** [felangel/bloc#791]
Perhaps I'm missing the point, but the idea of enclosing your widget inside a BlocBuilder is so that you can act on the state and add events to bloc.

But in order to do that I have to use the BlocProvider.of(context) to get the bloc, which seems wasteful, since the BlocBuilder already has it, right ?

**Comment by felangel** [comment]
Hi @flowcharterappowner 👋 
Thanks for opening an issue!

The goal of `BlocBuilder` is to allow you to re-render a widget in response to state changes in a bloc. There are many cases in which the widget being rebuilt does not need to add events to the bloc so we didn't feel it made sense to make that assumption. There was a discussion about this in https://github.com/felangel/bloc/issues/447 and ultimately we decided it was best to allow developers to add an extra `BlocProvider.of<Bloc>(context)` if they need to add events. The lookup is O(1) and if you want to further optimize you can perform the lookup once in your build and pass the bloc instance yourself like:

```dart
@override
Widget build(BuildContext context) {
  final myBloc = BlocProvider.of<MyBloc>(context);
  return BlocBuilder(
    bloc: myBloc,
    builder: (context, state) {
      return MaterialButton(
        onPressed: () => myBloc.add(MyEvent()),
      );
    }
  );
}
```

I also think it's a bit strange to rely on a BlocBuilder's builder method to give you access to a bloc. I personally don't think it's very intuitive and if we make that change for `BlocBuilder` it would probably be necessary to make the same change to `BlocListener` and `BlocConsumer`. Let me know what you think and thanks again!

**Comment by felangel** [comment]
Closing for now but I'm happy to continue the conversation if you feel strongly against the current functionality.
