### ISSUE TITLE
VSCode Intellisense won't suggest Bloc States 

### ISSUE THREAD

**Issue by TheWCKD** [felangel/bloc#793]
**Describing the bug**
Hello, Felangel!

Huge thanks for all the support you give everyone here!  

I've been dealing with an error with the Intellisense during the last days and I don't know if it is a dart/vscode issue or it may be caused by the bloc extension of yours. I remember a couple of days ago when I created another bloc manually (without the extension) it worked completely. However, now it doesn't work, I don't know if it's related to it.

**Reproducing the bug**
1. As you can see down below, when I'm trying to yield the WeatherLoaded() state, there's no suggestion popping out of Intellisense.

![vscode autocomplete error](https://user-images.githubusercontent.com/37099416/72816232-8397f880-3c70-11ea-9e4a-4b89080300fd.png)

2. However, after I write the complete name, it succesfully recognises the class.

![vscode autocomplete error 2](https://user-images.githubusercontent.com/37099416/72816427-c9ed5780-3c70-11ea-84f6-1e81808acf68.png)

Here's my flutter doctor -v if it may help.

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on  
    Microsoft Windows [Version 10.0.18362.535],     
    locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter    • Framework revision 27321ebbad (6 weeks ago),  
      2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices 
    (Android SDK version 28.0.3)
    • Android SDK at
      C:\Users\Tibi\AppData\Local\Android\sdk       
    • Android NDK location not configured (optional;      useful for native profiling support)
    • Platform android-29, build-tools 28.0.3       
    • Java binary at: C:\Program
      Files\Android\Android Studio\jre\bin\java     
    • Java version OpenJDK Runtime Environment      
      (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program
      Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment      
      (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at
      C:\Users\Tibi\AppData\Local\Programs\Microsoft      VS Code
    • Flutter extension version 3.7.1
```

**Comment by tenhobi** [comment]
I have also had some issues with autocompleting both in VS Code and IntelliJ, in the last couple of days. So maybe there is some issue?

**Comment by felangel** [comment]
Hi @TheWCKD 👋 
Thanks for opening an issue!

I was able to reproduce the issue and it seems the problem is either in the Dart Code VSCode Extension or the Dart Analysis server (more likely) and isn't able to autocomplete in certain cases. I'm noticing the issue happens after the `yield` keyword but without `yield` it seems to work fine. I don't believe this has anything to do with the bloc vscode extension but I would recommend opening an issue in [Dart Code](https://github.com/Dart-Code/Dart-Code/issues) and referencing this one 👍
