### ISSUE TITLE
Is it possible to add a Event to bloc in TOP-LEVEL function ?

### ISSUE THREAD

**Issue by semutnest** [felangel/bloc#795]
Hello @felangel,

"Is it possible to add a Event to bloc in TOP-LEVEL function ?"
This might be an unusual question, I am using FCM Notification  in which its onBackgroundMessage handler requires to define a TOP-LEVEL function to handle background messages.

Or Is there any way to handle the callback of that handler using your bloc pattern ?

Thank you for your attention.

**Comment by felangel** [comment]
Hi @semutnest 👋 
Thanks for opening an issue!

You should be able to create a bloc which initializes the firebase messaging configuration and then you can call add as you are within the bloc itself. Alternatively, you can create an instance of the bloc and inject it into the class which is managing the fcm notifications. Hope that helps!

Closing for now but feel free to comment with additional information and I'm more than happy to continue the conversation 👍

**Comment by flyingnobita** [comment]
Hello Felix,

Firstly I want to thank you for writing this library.  I tried a few other state management techniques but found yours to be the cleanest and most versatile.  So now I'm using bloc for all my projects.  

I'm having a similar problem as the OP.  I'm trying to do a periodic background task that is triggered by a bloc add event call.

I found a few packages (https://pub.dev/packages/workmanager & https://pub.dev/packages/background_fetch) that help with this but they both need a "top-level" function as an entry point for when the app gets terminated.

> "You should be able to create a bloc which initializes the firebase messaging configuration and then you can call add as you are within the bloc itself. Alternatively, you can create an instance of the bloc and inject it into the class which is managing the fcm notifications. Hope that helps!"

I don't quite understand what you mean by this.  Can you please give a brief example?

Thank you.
