### ISSUE TITLE
How to add events for each list item and update their states chronologically?

### ISSUE THREAD

**Issue by TheWCKD** [felangel/bloc#797]
Hello, @felangel .

I've been having some issues for the past 24 hours with some further implementation of your Bloc Weather App example, which I cannot seem to solve. 

Here's what I added to your existing working project, which I also built from zero. 
[Here's the link to the Github Project.](https://github.com/TheWCKD/bloc_weather_app_advanced)

I want to explain what features I added and what issues I have encountered with some of them.

**Feature No.1** -> In the search page, whenever the textinputfield value changes, a new event (GetPartialMinimalWeatherList) telling the MinimalWeatherBloc to get the list of possible locations from the repository, respectively from the datasource(the Api). Then, when the list is loaded, the bloc yields the MinimalWeatherLoaded state which contains the actual list of the possible locations. 

This works pretty much as expected with one minor question.

- **Question 1.1** -> I noticed that if I write for example into the textfield "bu", then the GetPartialMinimalWeatherList is emitted and starts fetching the possible locations, but if I immediately write "buc", another GetPartialMinimalWeatherList  event is emitted, but the previous one if it had like 100 entries would still run. Is there a way to cancel the previous event when a new character is entered in this case for example?

![image](https://user-images.githubusercontent.com/37099416/72925229-05645080-3d5b-11ea-9acb-1c61867645c7.png)

**Feature No.2** -> Along with this list, I wanted to show a little weatherinfo into the trailing section of the ListView of each location. However, here I started to have some issues. 

- **Approach 2.1** -> The first approach I tried was to incorporate the weatherinfo into the MinimalWeather model, with 2 extra fields, the current temperature and current Image. However, due to how the Api works, for each location in the PartialLocationList received from the Bloc, I had to await for the repository to get the specific weather data. Everything worked perfectly, but unfortunately, fetching data and then updating the lists for more than 2 locations would take a lot of time. 

- **Question 2.1** -> Here the question for this approach would be if there could be a way to load and display the weatherinfo for each location one by one, for example, if I have a list of 2 locations, is there a way I could display both of them, and then sequentially load the weather info for the 1st one, while displaying a loading indicator for the second one, and then get to load the second one after the 1st one finished?

- **Approach 2.2** -> Due to the question 2.1, I started to think how I could implement that functionality, but this time, with a new BLoC. So I created a new model called ShortWeather with the same structure as the other models, fromJson method etc. In this model I have only 2 fields, the currentTemperature and the Image of a specific location. So, after implementing the states, events and the bloc itself, I thought I should emit the GetShortWeatherForLocation event for each location in the location list into the ListView.builder and then, I thought that each event will be queued in the order it enteres like this: 

      0. GetShortWeatherForLocation(list[0].locationId), 
      1. GetShortWeatherForLocation(list[1].locationId), 
      2. GetShortWeatherForLocation(list[2].locationId),  etc

And this is the way they're emitted. I also added a blocbuilder into the trailing widget so that I could update each location item with it's specific weatherinfo as I described into Question 2.1. I was hoping that the following flow would start.

     0. Set all weatherInfo widgets in the trailing widget to loading (since all of them were swichted to that state from the GetShortWeatherForLocation event.
     1. Then load each one at the time, and progressively set the weatherInfo for each location from top to bottom, as the queue of the dispatched events.
     2. At the end, have them properly loaded with their respective weatherInfo.

However, this isn't working how I wanted to, but instead it does like this.

     0. Set all weatherInfo widgets in the trailing widget to loading (since all of them were swichted to that state from the GetShortWeatherForLocation event.
     1. Then, even though the events are solved one by one, the UI will still remain with the loading animation on until the last event finished.
     2. At the end, all the locations have the same weather info, which is the one which shoudl've been corespondent to the first location as you can see below.

![image](https://user-images.githubusercontent.com/37099416/72927371-ba4c3c80-3d5e-11ea-8142-b985f38ee176.png)

- **Question 2.2** -> Here the question for this approach would be how could I have the expected behaviour, I can't really understand what I'm doing wrong here and I'm stuck. I tried other approaches like injecting the ShortWeatherBloc into the MinimalWeatherBloc and dispatch the events from there, but I still get the same results.

- **Question 2.3** -> I hope you can take a look on my code and tell me what are your suggestions on how can I simplify these approaches. I've started learning flutter from zero about 2 months ago and it's pretty difficult to get it done all by myself.

Thank you once again, @felangel !

**Comment by felangel** [comment]
Hi @TheWCKD 👋 
Thanks for opening an issue and for providing such an awesome amount of detail!

Question 1.1:
You can override `transformEvents` to use `switchMap` - https://github.com/felangel/bloc/issues/517#issuecomment-531531738

Regarding your questions around feature 2; I will take a look at your current implementation and provide feedback. Unfortunately, I'm at Flutter Europe right now so I will probably not have time to look until Saturday/Sunday. Hope my answer for your first feature is helpful it might also be good for you (if you haven't already) to join the [bloc discord server](https://discord.gg/Hc5KD3g). That way we can chat and potentially even do a call to discuss some of the issues you're having. Let me know what you think and thanks!

**Comment by TheWCKD** [comment]
@felangel Thank you for that tip, it was what I was looking for! Yes, I know you are at Flutter Europe, I heard that from ResoCoder. :smile: I'll try my best to solve the second issue I'm encountering until Saturday/Sunday. Thanks a ton for your help! :+1:

**Comment by felangel** [comment]
Hey just cloned and ran your project and it looks like you've resolved both issues. Is there anything left that you're still having trouble with or is it ok to close this issue?

**Comment by TheWCKD** [comment]
@felangel Hello, mate. Thank you for looking over my project. No, it's not ready, since I'm stuck for the implementation number 2. As I said, I would like to know how to implement the loading weather one by one after the location list is displayed. Currently, I have setup that the all the weather info is loaded before displaying the location list if the list.lenght is <=5, otherwise it will display only the list without the weather.

However, i would like the implementation to look like this:

Search for location, display all possible location lists, then show a loading indication for each weather info on the trailing section, then one by one from top to down of the list, I would like the weather to load up.

Thank you for all the help. Hope you can give me some tips with what I want to achieve. I already have the small Weather bloc implemented.

Thanks again!

**Comment by felangel** [comment]
Ah sounds good! Will take a look today and try to open a PR with my recommendation.

**Comment by TheWCKD** [comment]
@felangel Thank you, mate, I really appreciate it! :smile:

**Comment by felangel** [comment]
@TheWCKD just created a [pull request](https://github.com/TheWCKD/bloc_weather_app_advanced/pull/1) to handle number 2 👍 

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 😄

**Comment by TheWCKD** [comment]
@felangel Thank you, mate. Will surely take a look at the implementation! Cheers!
