### ISSUE TITLE
BlockProvider.of method

### ISSUE THREAD

**Issue by arathiShankri** [felangel/bloc#798]
Hi Felix,

This is the 1st time I am using BlocProvider or MultiBlocProvider and can use your expertise/advice on the below issue/question.

1. I am getting the error "BlocProvider.of() called with a context that does not contain a Bloc of type CounterBloc." on the line where I am creating the FAB. 
```
 return BlocProvider<CounterBloc>(
      create: (context) => CounterBloc(),
      child: Scaffold(
        appBar: AppBar(
          title: Text('title'),
        ),
        floatingActionButton: _fab(context, BlocProvider.of<CounterBloc>(context)),
        body: BlocBuilder<CounterBloc, int>(builder: (context, count) {
          return Center(`
```
I want to send my CounterBloc to my "_fab" method so that I can take action on click of the FAB.

2. Of course, all of this works fine, when I use BlocProvider/MultiBlocProvider in main.dart, wrapping my "home" widget.
```
return MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: BlocProvider<CounterBloc>(
          create: (context) => CounterBloc(),
          child: CounterScreenProvider(title: 'Flutter Demo Home Page'),
        ));
```
3. I tried sending the bloc using BlocProvider.value (as below) so that I can pass my Bloc to a different widget tree, but I am still getting the same error. 
```
return BlocProvider<CounterBloc>(
        create: (context) => CounterBloc(),
        child: BlocProvider.value(
          value: BlocProvider.of<CounterBloc>(context),
          child: Scaffold(
            appBar: AppBar(
              title: Text('title'),
            ),
            floatingActionButton: _fab(context, BlocProvider.of<CounterBloc>(context)),
            body: BlocBuilder<CounterBloc, int>(builder: (context, count) {
              return Center(
```

Can you please help me with this? 
1. Why am I not getting the instance of the Bloc downstream in my child widgets? 
2. Is my understanding of using BlocProvider.value correct? I couldn't find an example of the same.

Thank you,
Arathi

**Comment by rodrigobastosv** [comment]
Hi @arathiShankri , with your current setup, the fab is not a child of the BlocProvider, so the bloc can't be provided.

One quick solution to your question is wraping your fab in a Builder widget (https://api.flutter.dev/flutter/widgets/Builder-class.html).

Doing that will make you fab be a child in the widget tree.

**Comment by arathiShankri** [comment]
@rodrigobastosv Thank for your reply, I had it working creating a new context using Builder class. 

But, in my code above, since Scaffold is a child of BlocProvider, I thought I can look up for Bloc and send it to the _fab method that returns a FloatingActionButton widget. Isn't that correct?

Thanks again!

**Comment by tenhobi** [comment]
@arathiShankri yes, but the problem is you are using the same context from the current widget, therefore you are not in a child widget and cannot access it.

**Comment by arathiShankri** [comment]
@tenhobi Thank you! I think I get it now. 
FAB is in Scaffold and to grab the context of the Scaffold, I need to use Builder class. The context that I was using was really of that of the parent i.e the MaterialApp, thus was not finding the Bloc which was in turn created as a child of BlocProvider.

Closing the issue now. Thanks for helping!
