### ISSUE TITLE
Using RxDart with bloc 

### ISSUE THREAD

**Issue by mhnowak** [felangel/bloc#801]
Hi, thanks for the presentation at Flutter Europe in Warsaw. I remember you said that you can use RxDart with it and I wonder if there is an actual example. Can you maybe direct me there?

**Comment by felangel** [comment]
Hey @mhnowak 👋 

Yeah I believe your question was regarding how to cancel old events and only process the latest? You can refer to https://github.com/felangel/bloc/issues/517#issuecomment-531531738 and see an example in https://github.com/felangel/bloc/blob/7c804df9dbd9c2e88a5790ee35aba395e05fc249/examples/github_search/common_github_search/lib/src/github_search_bloc/github_search_bloc.dart#L15. Hope that helps 👍

**Comment by mhnowak** [comment]
Thanks @felangel it wasn’t my question and I don’t wanna take credit for it. And yes, that answer helps!

**Comment by felangel** [comment]
Haha no worries! Glad I was able to help 😄 
Closing for now but feel free to comment with any additional questions and/or join the [Discord Server](https://discord.gg/Hc5KD3g) if you want to chat about any other bloc-related topics 👍
