### ISSUE TITLE
[Feature request] Extend BlocDelegate with regards to logging

### ISSUE THREAD

**Issue by RollyPeres** [felangel/bloc#802]
**Is your feature request related to a problem? Please describe.**
Would like to be able to log additional context through `BlocDelegate`, not only the error itself and the stacktrace, a good example being firebase crashlytics where you can do `Crashlytics.instance.recordError(dynamic exception, StackTrace stack, {dynamic context})`.

**Describe the solution you'd like**
Would like to be able to pass additional context to the bloc delegate, or even better, be able to register a logger function, something like `BlocSupervisor.delegate = AppBlocDelegate()..logger(Crashlytics.instance.recordError);`

**Describe alternatives you've considered**
Maybe have `Bloc` expose an `addError` method similar to `EventSink<T>`, but with an additional `dynamic context` optinal parameter. That way after catching an error and yielding a failure state with data we need on the UI we could push the error and optional stacktrace+context into the bloc for logging.

**Comment by felangel** [comment]
Hi @RollyPeres 👋 
Thanks for opening an issue!

I agree this would be a nice improvement but I just want to clarify a few things.

1. Wouldn't an additional, optional context be required regardless of the approach?
2. I personally think I prefer adding the optional `context` to `onError` and exposing an `addError` on bloc. This would be a backward compatible change and would also

**Comment by RollyPeres** [comment]
A basic implementation would look something like: 

```
class BlocDelegate {
  @mustCallSuper
  Future<void> Function(dynamic error, StackTrace stack, {dynamic context})
      logger;

  /// Called whenever an [event] is `added` to any [bloc] with the given [bloc] and [event].
  /// A great spot to add universal logging/analytics.
  @mustCallSuper
  void onEvent(Bloc bloc, Object event) => null;

  /// Called whenever a transition occurs in any [bloc] with the given [bloc] and [transition].
  /// A [transition] occurs when a new `event` is `added` and `mapEventToState` executed.
  /// [onTransition] is called before a [bloc]'s state has been updated.
  /// A great spot to add universal logging/analytics.
  @mustCallSuper
  void onTransition(Bloc bloc, Transition transition) => null;

  /// Called whenever an [error] is thrown in any [bloc]
  /// with the given [bloc], [error], and [stacktrace].
  /// The [stacktrace] argument may be `null` if the state stream received an error without a [stacktrace].
  /// A great spot to add universal error handling.
  @mustCallSuper
  void onError(
    Bloc bloc,
    Object error,
    StackTrace stacktrace, {
    dynamic context,
  }) =>
      logger == null
          ? null
          : logger(error, stacktrace, context: context).catchError(null);
}
```

This would allow me to use my own delegate like:

```
class AppDelegate extends BlocDelegate {
  @override
  void onError(
    Bloc bloc,
    Object error,
    StackTrace stacktrace, {
    dynamic context,
  }) {
    if (error is AppException) {
      logger(error.error, error.stack,
              context: '${bloc.runtimeType}/${error.code}')
          .catchError(null);
      return;
    }

    super.onError(bloc, error, stacktrace, context: context);
  }
}
```

And register it like: 
```
BlocSupervisor.delegate = AppDelegate()
    ..logger = Crashlytics.instance.recordError;
```

**Comment by tenhobi** [comment]
I like the idea of adding additional context 👍, which might be used by some tools; but I feel like not forcing logger API (and logger itself) would be better. You can easily add a logger to your own delegate.

**Comment by RollyPeres** [comment]
@tenhobi That's true, was just throwing that idea in there. Many might find not having to write their own logger hook a bonus. I don't mind either way, as long as there's some additional context and we get like a `.addError` on the bloc 😉

**Comment by felangel** [comment]
@RollyPeres now that we've got `addError` I think adding a `context` or `extras` makes sense (just need to align on naming). I also don't love making it dynamic and feel like it might suffice to type it `Map<String, dynamic>.

I agree with @tenhobi that adding a logger might be too much. I think we can have a `LoggingBlocObserver` that is a separate package potentially but I don't feel it needs to be in the bloc package itself.

Let me know what you all think 👍

**Comment by RollyPeres** [comment]
Yeah, definitely leave the logger up to the user, as an implementation detail. 👍

As for the naming add `details` to the list.

I personally like `dynamic` more, simply because most of the time people will probably pass a simple type like `String`; so `dynamic` can be a `String` but `Map<String, dynamic>` cannot be a `String`. Basically `dynamic` can be `Map<String, dynamic>` but `Map<String, dynamic>` cannot be dynamic.
It would make for less typing when a `Map` is not actually needed. `'authentication_failure'` instead of `{ 'reason': 'authentication_failure' }`

Let me know @felangel if you had something else in mind when opting for `Map<String, dynamic>` that I might've missed. 😃

**Comment by felangel** [comment]
Aftering discussing this further with @RollyPeres, we've decided to close this since adding `context` to the `addError` api would break the `EventSink` interface. In addition, ideally the error object should contain all relevant contextual information.
