### ISSUE TITLE
Unable to retrieve Bloc from context in child widget

### ISSUE THREAD

**Issue by franagu** [felangel/bloc#805]
**Describe the bug**
I may be missing something here, but my understanding is that declaring a Bloc in a parent widget's context should make it available to the subt tree. It does not seem to be working for me. I get the error 

> BlocProvider.of() called with a context that does not contain a Bloc of type CreateFormBloc

**Parent Class:**
`class ScreenWrapper extends StatelessWidget {
  ScreenWrapper({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<SomeBloc, SomeState>(
      builder: (context, state) {
        if (state is LoadingState || state is InitialState || state is SavingState) {
          return Center(child: CircularProgressIndicator());
        }
        if (state is LoadedState) {
          return AScreen();
        }
        if (state is CreateRequestedState) {
         return  BlocProvider<CreateFormBloc>(
              create:(BuildContext context) =>
                CreateFormBloc(repository: RepositoryProvider.of<MyRepository>(context)),
              child:  CreateScreen(),
         );
        }
        if (state is SearchState) {
          return SearchScreen();
        }
}
}
`
In the CreateScreen, using BlocProvider.of fails with the error. BlocProvider.of() called with a context that does not contain a Bloc of type CreateFormBloc

I'm not sure what I'm missing here.

**Comment by felangel** [comment]
Hi @franagu 👋 
Thanks for opening an issue!

Are you sure you're providing the bloc type `BlocProvider.of<CreateFormBloc>(context)`?

**Comment by franagu** [comment]
Thank you! Was missing the proper declaration of the Repo Provider, also nested the CreateScreen in another widget.
