### ISSUE TITLE
First emission of state is null in BlocBuilder

### ISSUE THREAD

**Issue by reinaldomoreira** [felangel/bloc#811]
**Describe the bug**
While testing, first emission of `BlocBuilder` is null (only when testing). This force me to do a check-up in my widget like `if(state == null) return Container()` in my code. Please, check the code attached for better understanding while reproducing it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the code sent attached or in the end of this issue
2. Just run the test, it will throw a exception by this code in the widget (lines 21 to 24)
`          if (state == null) {
//            return Container();
            throw Exception('state is null');
          }`

**Logs **
`❯ flutter analyze
Analyzing fluttebloc...                                                 
No issues found! (ran in 2.2s)
`

Paste the output of running `flutter doctor -v` here.
`❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.10.14, on Mac OS X 10.14.6 18G103, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
[✓] Android Studio (version 3.6)
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2019.3)
[✓] Connected device (1 available)

• No issues found!
`

**Additional context**

Code:

[Gist](https://gist.github.com/reinaldomoreira/98e6d8ce1c296defe66fb064bbc2733b
)
or

[fb.zip](https://github.com/felangel/bloc/files/4097757/fb.zip)

**Comment by rodrigobastosv** [comment]
I guess this line is not needed when(testBloc.initialState).thenReturn(TestState('Initial mocked'));

You can pass your initialState to whenListen, like that:

    whenListen<TestEvent, TestState>(
      testBloc,
      Stream.fromIterable([
        TestState('Initial mocked')
        TestState('First emission'),
        TestState('Second emission'),
      ]),
    );

**Comment by reinaldomoreira** [comment]
> I guess this line is not needed `when(testBloc.initialState).thenReturn(TestState('Initial mocked'));`
> 
> You can pass your initialState to whenListen, like that:
> 
> ```
> whenListen<TestEvent, TestState>(
>   testBloc,
>   Stream.fromIterable([
>     TestState('Initial mocked')
>     TestState('First emission'),
>     TestState('Second emission'),
>   ]),
> );
> ```

Thanks for the reply! I understand it is not needed and I don't mock the initialState, it's there just for exhausting all the possible problems

**Comment by felangel** [comment]
Hi @reinaldonomoreira 👋 
Thanks for opening an issue!

This is happening because you are stubbing `initialState` rather than `state`. Check out https://gist.github.com/reinaldomoreira/98e6d8ce1c296defe66fb064bbc2733b#gistcomment-3157637 for the updated test code.

Hope that helps and sorry for the inconvenience!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
