### ISSUE TITLE
Cannot catch exceptions in mapEventToState

### ISSUE THREAD

**Issue by barapa** [felangel/bloc#815]
I am trying to catch exceptions in mapEventToState in order to yield an ErrorState when one occurs. The code looks like this:

```
@override
Stream<MyState> mapEventToState(MyEvent event) async* {
  try {
    if (event is MyEvent) {
      yield* _handleMyEvent();
    }
  } catch (e) {
    print('in mapEventToState: $e');
    yield ErrorState(message: e.message);
  }
}

Stream<MyState> _handleMyEvent() async* {
  try {
    final id = await repo.getId();
  } catch (e) {
    print('in _handleMyEvent: $e');
    rethrow;
  }
}
```

When I run the code in a situation that will trigger the exception, I see the print from inside _handleMyEvent, but I do not see the one in mapEventToState, and the ErrorState is never yielded.

**Comment by barapa** [comment]
I can work around this by overriding the blocs `onError` method:

```
@override
void onError(Object error, StackTrace stacktrace) {
  add(InternalError(error: error));
}
```

And then just handling the InternalError event normally. But it seems like it shouldn't be necessary,

**Comment by felangel** [comment]
Hi @barapa 👋 
Thanks for opening an issue!

If you have an async* (async-generator) then you should always handle exceptions internally and yield states. In your case I would recommend refactoring like:

```dart
@override
Stream<MyState> mapEventToState(MyEvent event) async* {
  try {
    if (event is MyEvent) {
      yield await _handleMyEvent();
    }
  } catch (e) {
    print('in mapEventToState: $e');
    yield ErrorState(message: e.message);
  }
}

Future<MyState> _handleMyEvent() async {
  try {
    final id = await repo.getId();
    return MyState(id: id);
  } catch (e) {
    print('in _handleMyEvent: $e');
    rethrow;
  }
}
```

Let me know if that helps 👍

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by lunaticcoding** [comment]
@felangel what if I want to throw exception for invalid states? I want to test whether the exception was thrown. :S It should never occur in the actual app though. 

https://stackoverflow.com/questions/62626632/bloc-handleerror-does-not-catch-error-in-dart?noredirect=1#comment110750993_62626632

**Comment by felangel** [comment]
@lunaticcoding you can just let the exception bubble up by not wrapping the code in a try/catch and then you can use `blocTest` with `errors` to verify an error occurred.

```dart
blocTest(
  'CounterBloc throws Exception when null is added',
  build: () async => CounterBloc(),
  act: (bloc) => bloc.add(null),
  errors: [
    isA<Exception>(),
  ]
);
```

Hope that helps 👍

**Comment by lunaticcoding** [comment]
@felangel Thank you so much :) it is exactly what I was looking for :)
