### ISSUE TITLE
Misleading Error Message

### ISSUE THREAD

**Issue by ahawlitschek** [felangel/bloc#817]
Hi Felix,

today I encountered a really strange behaviour. 
Within a project that uses several blocs the `No BlocProvider found for context...` appears for the new bloc. 
Exactly same View Tree. No import issues. 
After some hours I discovered, that an error within my initial state getter had occured. 

This error was catched by the provider try catch block. Resulting in no other error message than provider error. 

Maybe it would be a good idea to forward the original exception. 

Greetings from Germany
Adrian

**Comment by felangel** [comment]
Hi @ahawlitschek 👋 
Thanks for opening an issue!

This is currently being addressed by #816 and will be fixed in v3.2.0 of flutter_bloc 👍
