### ISSUE TITLE
[Question] Customize "User" model on "Login Firestore Tutorial".

### ISSUE THREAD

**Issue by alvarofvr** [felangel/bloc#847]
Hi @felangel, I am continuing to use your fantastic library for the development of my application and I have a question for you. In example [Flutter Firebase Login Tutorial](https://bloclibrary.dev/#/flutterfirebaselogintutorial) in `UserRepository` class you have implemented `getUser()` method and you added a note:

> Note: getUser is only returning the current user's email address for the sake of simplicity but we can define our own User model and populate it with a lot more information about the user in more complex applications.

For implement this part first I created my model `User` then I proceeded to add the user collection to the `UserRepository` class and then in the method `getUser()` I added the "retrieve or create" logic.

```
  Future<User> getUser() async {
    final firebaseUser = await _firebaseAuth.currentUser();
    var userDocument = await usersCollection.document(firebaseUser.uid).get();
    if(!userDocument.exists) {
      final user = User(userId: firebaseUser.uid); // sample custom model
      usersCollection.addNewUser(user);
      userDocument = await usersCollection.document(firebaseUser.uid).get();
    }

    return User.fromEntity(UsersEntity.fromSnapshot(userDocument));
  }
```
This is my approach, but I feel there is something wrong becouse imagine there is a page for user settings if we used the `AuthenticationBloc` for manage user info we need to reauthenticate the user when settings change?

I wanted to have your opinion but not feel compelled to respond.

Thanks for your work!

**Comment by warriorCoder** [comment]
I think the purpose was to add extra info about the user other than their id, email address etc and keep track of said info in your app with a user object. The sign in/out or authentication part is a little separate from the details of what's stored in your user class.

Also allowing the user to update their info in a settings page or user profile page isn't the same as authenticating said user. I'd also think you would store your user info in your database which again isn't affected by the authentication part. 

Hope that helps.

**Comment by felangel** [comment]
Hi @alvarofvr 👋 
Thanks for opening an issue and for the positive feedback!

Can you provide a sample app which illustrates the issue you're having? I'm not sure I understand why changing user settings would require re-authenticating.

**Comment by alvarofvr** [comment]
> I think the purpose was to add extra info about the user other than their id, email address etc and keep track of said info in your app with a user object. The sign in/out or authentication part is a little separate from the details of what's stored in your user class.
> 
> Also allowing the user to update their info in a settings page or user profile page isn't the same as authenticating said user. I'd also think you would store your user info in your database which again isn't affected by the authentication part.
> 
> Hope that helps.

Are you suggesting to detach the authentication logic from the user's profile logic? For example use a different Bloc for manage user profile logic? 
But I think that having the user's profile information directly into the authentication block would be better for several reasons.

**Comment by alvarofvr** [comment]
> Hi @alvarofvr 👋
> Thanks for opening an issue and for the positive feedback!
> 
> Can you provide a sample app which illustrates the issue you're having? I'm not sure I understand why changing user settings would require re-authenticating.

When a user logs in, the state of authentication bloc is `Authenticated(FirebaseUser user)`.
If I use a custom user model the state is `Authenticated(User user)`, then I use the authentication bloc in the settings user profile page. When I update the user fields must be dispatched an event that updates the Authenticated(user) state and this causes the authentication bloc to change state.

**Comment by alvarofvr** [comment]
It's not an issue it's just a question to understand if `AuthenticationBloc` logic can coexist with a user profile logic.

**Comment by felangel** [comment]
@alvarofvr I would not recommend conflating profiles/preferences with Authentication because those are two independent features/use-cases in my opinion. I would recommend the `AuthenticationBloc` just manage whether or not a user is authenticated (and the optionally the identity). You can have a `ProfileBloc` which pulls user profile data from the UserRepository and manages that state independently of the `AuthenticationBloc`.

Hope that helps! Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
