### ISSUE TITLE
Generator

### ISSUE THREAD

**Issue by gedw99** [felangel/bloc#85]
**Is your feature request related to a problem? Please describe.**
The way this works is pretty cool.
For large apps you end up with alot of code to maintain and i was thinking about a generator to help.

**Describe the solution you'd like**
There is a bloc generator here and its pretty nice.
https://github.com/CallumIddon/bloc_generator

**Describe alternatives you've considered**

Have a looksie and see what you think.

**Comment by felangel** [comment]
@gedw99 thanks for bringing this up! I’m curious to understand what boilerplate you are referring to because I have been working on a number of things to reduce boilerplate without the need for a generator (extensions and equatable).

**Comment by felangel** [comment]
Closing this for now but I would love to hear more details if you have time.

**Comment by gedw99** [comment]
hey @felangel 
You might be totally right in that no boiler plate ( or not much ) is needed with your bloc.
I can see its merits thats for sure, compare to redux mania..

I have started looking into hydration of the bloc and other things to extend from the current functionality. 
https://github.com/lukepighetti/hydrated
This would mean that if the user opens the app with no internet then everything works because the data is stored.  Then once they go online, everything catches up from the server that is only sending updates for each ViewModel in the form of CRUD events, so that the Bloc either adds, removes or changes a row of data. Hope this makes sense as not everyone uses Event Storming patterns on the server. Happy to explain if needed.
Very clean approach i feel.

If you look, into the issues they are talking about making it work for web and flutter just like your bloc.
Pretty cool..
Am really curious to hear your thoughts

If you have time, please write your future direction in some markdown file, so we can work synergistically. is that ok ?

**Comment by felangel** [comment]
Hey @gedw99 thanks for the positive feedback!

I'll try to put together a roadmap for the library and will link to it as soon as it's done 👍(hopefully later today) 

In terms of hydration and supporting offline, I don't think doing it at the bloc level is the right place. I think caching/offline support should be done by the data/repository layer of the application and the blocs would have no clue if the data they are given is from cache or from the backend. Thoughts?
