### ISSUE TITLE
Approaches to navigation on notification clicks (via firebase messaging)

### ISSUE THREAD

**Issue by barapa** [felangel/bloc#854]
I am using [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging) to receive messages and in turn display notifications. I am trying to determine a good pattern for navigating to a specific page within the app when a user clicks on a notification in their notification bar.

As currently architected, I configure the firebase cloud messaging client and my message callbacks in a bloc (firebase_messaging_bloc). Because of this, I do not have access to the context with which I could, for instance, navigate to a named route (given the data in the message).

I came across [an approach of creating a bloc that just handled navigation via a global key](https://dev.to/pedromassango/flutter-bloc-a-better-way-to-handle-navigation-4fig), but was curious if anyone had any superior or alternative approaches.

**Comment by felangel** [comment]
Hi @barapa 👋 
Thanks for opening an issue!

I would recommend having a `MessageReceived` event which emits a state containing the normalized data from FCM. You can then have a `BlocListener` which listens for state changes in the `NotificationBloc` and handle navigation in the `listener`.

Let me know if that helps! 👍

**Comment by barapa** [comment]
That does not appear to work. Let me add more details.

This is the example config from firebase messaging:
```
 _firebaseMessaging.configure(
       onMessage: (Map<String, dynamic> message) async {
         print("onMessage: $message");
         _showItemDialog(message);
       },
       onBackgroundMessage: myBackgroundMessageHandler,
       onLaunch: (Map<String, dynamic> message) async {
         print("onLaunch: $message");
         _navigateToItemDetail(message);
       },
       onResume: (Map<String, dynamic> message) async {
         print("onResume: $message");
         _navigateToItemDetail(message);
       },
     );
```

The `onLaunch` and `onResume` callbacks I define are triggered when the user clicks the notification. When I set these up as suggested, where they add an Event that is handled by yielding a State that a Listener (somewhere in my widget tree) is listening to to trigger the navigation, the listener code is never called, though my `onResume` callback is. I think the issue is, if that widget is not being rendered when that callback is triggered then its listener is not called.

Is there a place where a listener is guaranteed to be called, regardless of the state of the app?

**Comment by barapa** [comment]
`onMessage` is called if the notification comes in while the app is open. If I trigger a notification, my print statement in `onMessage` is shows up in the logs. However, the event I add after the print statement does not show up in the logs, even though my bloc delegate prints every event.

I have registered the BlocListener for the notification bloc at the top level of the app, and it's child is the MaterialApp widget itself.

**Comment by felangel** [comment]
Are you able to share a link to your app or a sample app which illustrates the problem? I'm happy to try to open a pull request with suggestions.

**Comment by barapa** [comment]
Turns out there was a type error in my handling of these messages which was not getting logged in any way. Your approach works!

In general, does it matter where in the widget tree the listener for these notifications lives?

**Comment by felangel** [comment]
Awesome! I would recommend keeping the listener in the widget which needs to be mounted in order for the notifications to be handled. In this case, I think it would make sense to have the BlocListener above your MaterialApp since you likely want to be listening for messages regardless of what part of the app a user is on. Hope that helps!

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍
