### ISSUE TITLE
Codecov fails to upload sometimes

### ISSUE THREAD

**Issue by tenhobi** [felangel/bloc#856]
This is an issue to track Codecov Action's issues.

- [x] Sometimes randomly fails (even for projects with coverage !); see https://github.com/codecov/codecov-action/issues/54
- [x] Doesn't work for forks, because the token is from this repository; see https://github.com/codecov/codecov-action/issues/29

**Comment by felangel** [comment]
Closing for now since it seems these issues have been addressed https://github.com/codecov/codecov-action/issues/29
