### ISSUE TITLE
Scaffold inside BlocBuilder - floatingActionButton issues

### ISSUE THREAD

**Issue by Dinosane2** [felangel/bloc#857]
I´m not sure if it is a bloc issue or not. 

I wish to show floatingActionButton depending on states. A CRUD page with a PLUS button will change the state to ADDING and a proper form will show up, with a different floatingActionButton set (SAVE and CANCEL).

To achieve this I´m using BlocBuilder > Scaffold> FAB (depending on state)
But doing so I´m got an error :

"Unhandled Exception: Scaffold.of() called with a context that does not contain a Scaffold."

This is an error of concept? Can anyone point me to the proper way?

**Comment by felangel** [comment]
Hi @Dinosane2 👋
Thanks for opening an issue!

I'm guessing you're calling Scaffold.of(context) with a context that does not have a scaffold (above the Scaffold widget). Can you please share a link to a sample app which illustrates your issue? Thanks!

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional information and I'm happy to continue the conversation 👍
