### ISSUE TITLE
RefreshIndicator with bloc example

### ISSUE THREAD

**Issue by ScrivNetwork** [felangel/bloc#86]
Can you show how it use with RefreshIndicator?

**Comment by ScrivNetwork** [comment]
1

**Comment by felangel** [comment]
Sure ill put together an example this weekend. 👍

**Comment by felangel** [comment]
I created a Flutter Weather app and used the `RefreshIndicator` to address your request.
You can check it out [here](https://github.com/felangel/bloc/tree/master/examples/flutter_weather). 👍

**Comment by sm2017** [comment]
@felangel it is too cumbersome, is there any alternative way? In my application I must refresh multiple blocs, So I must create multiple listener and multiple `Completer` , it is just boilerplate!

**Comment by felangel** [comment]
@sm2017 the weather app has been updated and is no longer using a Completer. Let me know what you think 👍

**Comment by sm2017** [comment]
Can you pleae send me link of new document, I see it now and still using Completer

**Comment by felangel** [comment]
https://github.com/felangel/bloc/blob/e9f4e02d5c3c795ea975b7b3ac312829f9fff13b/examples/flutter_weather/lib/weather/view/weather_page.dart#L51

**Comment by sm2017** [comment]
Wow!! it is much more better!!
What if I use `Bloc` instead of `Cubit`

**Comment by felangel** [comment]
If you want to use a bloc you can return `bloc.first` which is a future that resolves when the bloc emits a new state. You can also use `bloc.firstWhere(...)` to specify the type of state to wait for.

**Comment by sm2017** [comment]
Wow!! Wow!!
Your two latest comments is more valuable than whole documentation, you save me, thank you

I don't see in document, is documentation imperfect?

**Comment by bukenov** [comment]
> I created a Flutter Weather app and used the `RefreshIndicator` to address your request.
> You can check it out [here](https://github.com/felangel/bloc/tree/master/examples/flutter_weather). 👍
> ![flutter_weather](https://user-images.githubusercontent.com/8855632/52183142-8634e000-27ca-11e9-82f3-b5512291947a.gif)

 **[emit] should never be used outside of tests

**Comment by caseyryan** [comment]
> > I created a Flutter Weather app and used the `RefreshIndicator` to address your request.
> > You can check it out [here](https://github.com/felangel/bloc/tree/master/examples/flutter_weather). 👍
> > ![flutter_weather](https://user-images.githubusercontent.com/8855632/52183142-8634e000-27ca-11e9-82f3-b5512291947a.gif)
> 
> **[emit] should never be used outside of tests

why?

**Comment by caseyryan** [comment]
> @sm2017 the weather app has been updated and is no longer using a Completer. Let me know what you think 👍

That's great! Bloc really rocks. Thanks for your brilliant work

**Comment by II11II** [comment]
> If you want to use a bloc you can return `bloc.first` which is a future that resolves when the bloc emits a new state. You can also use `bloc.firstWhere(...)` to specify the type of state to wait for.

@felangel  Could you show how to call with context?
My example gives error:
```
onRefresh: () async {
var bloc = context.read<HomePaymentCardBloc>()
          ..add(HomePaymentCardEvent.getBalance(
              context.watch<AppBloc>().state.userToken));
        var future= bloc.first;
        return await future ;
        }
```

**Comment by II11II** [comment]
```

flutter: #0      Provider._inheritedElementOf
package:provider/src/provider.dart:329
#1      Provider.of
package:provider/src/provider.dart:281
#2      ReadContext.read
package:provider/src/provider.dart:614
#3      Body.build.<anonymous closure>
package:davrpay/…/pages/home_page.dart:60
#4      RefreshIndicatorState._show.<anonymous closure>
package:flutter/…/material/refresh_indicator.dart:370
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#11     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#12     _rootRun (dart:async/zone.dart:1190:13)
```

**Comment by II11II** [comment]
My fault i gave Bloc provider in child tree not in where I am calling

**Comment by aumb** [comment]
> If you want to use a bloc you can return `bloc.first` which is a future that resolves when the bloc emits a new state. You can also use `bloc.firstWhere(...)` to specify the type of state to wait for.

Is there any way to still have the same implementation after ^7.0.0? firstWhere is no longer defined for blocs, and there doesn't seem to be any future method to use @felangel

**Comment by aumb** [comment]
Upon reviewing the older bloc version i saw that the `firstWhere` function belongs to the `Stream` so just use the stream getter of the bloc

```dart
_bloc.stream.firstWhere(
            (val) => val is HomeLoaded || val is LocationError,
          );
 ```
