### ISSUE TITLE
Unable to call dispatch on parent bloc

### ISSUE THREAD

**Issue by niteshgrg** [felangel/bloc#860]
**Describe the bug**
I have 2 blocs one as parent and another defined as child of that. Now i would like to dispatch event to parent if it isn't handled in child. super.dispatch(event) doesn't work. Tried both super.dispatch and super.mapEventToState

**To Reproduce**
-- Parent Class
```
class ApiBloc extends WidgetBloc {

  @override
  WidgetStates get initialState => ApiUninitializedState();

  @override
  Stream<WidgetStates> mapEventToState(WidgetEvents event) async* {
    print(event);
    try {
      if (event is ApiBlocClearEvent) {
        yield ApiUninitializedState();
      }
    } catch (err) {
      yield ApiFailureState();
      showErrorSnackbar('test);
    }
  }
}

```

-- Child class
```
class FABBloc extends ApiBloc {
  @override
  void onTransition(Transition<WidgetEvents, WidgetStates> transition) {
    super.onTransition(transition);
  }

  @override
  FABWidgetState get initialState => FABWidgetState();

  @override
  Stream<WidgetStates> mapEventToState(WidgetEvents event) async* {
      super.dispatch(event);
  }
}
```

**Comment by felangel** [comment]
Hi @niteshgrg 👋 
Thanks for opening an issue!

Are you able to share the link to a sample app which illustrates the issue you're facing? Thanks!

**Comment by felangel** [comment]
Closing for now as there is no sample app which I can run to reproduce the issue. Feel free to add one and I'm happy to continue the conversation 👍

**Comment by niteshgrg** [comment]
I have modified todo sample app for my example.

https://github.com/niteshgrg/fluttr_sample/blob/master/lib/blocs/todos/todos_bloc.dart#L21
This now where i try to add in super instance. Which never goes to super as you can see.

Also if you will check super.toString() at this point you will see that its a instance of todos_bloc itself which is weird as its extending widgetBloc so super should be an instance of WidgetBloc.

**Comment by felangel** [comment]
@niteshgrg I'm a bit confused. Can you provide some more context/information around what you're trying to achieve with this approach? I don't think it makes sense to call `super.add(...)` within `mapEventToState`. Sorry if I'm misunderstanding, thanks!

**Comment by niteshgrg** [comment]
Ahh ok so Basically i have some general events which i would like to be available to all blocs. Lets say i want the ability to call post api's in all of my blocs. Now calling an POST api can be very generic logic and generic states. So if that actions come in i would like to dispatch that action to my parent Widget bloc.

Basically make this generic bloc which has these common events and all blocs can inherit them. 
I am bit new to OOPS paradigm have mostly worked in functional so i might be missing something very silly here. 

But if i i have extended a bloc then super should anyhow point to parent while printing super and getting bloc of child only is very confusing to me.

**Comment by felangel** [comment]
@niteshgrg I would love to discuss this on [discord](https://discord.gg/Hc5KD3g). I think there are some misconceptions we can clear up (like you ideally shouldn't be making `POST requests` directly from your bloc (that should be handled by the http layer). The blocs should generally only be interfacing with `repositories`.
