### ISSUE TITLE
No ancestor could be found starting from the context that was passed to BlocProvider.of<LoginBloc>().

### ISSUE THREAD

**Issue by samsheldin** [felangel/bloc#864]
The following assertion was thrown building BlocBuilder<AuthenticationBloc, AuthenticationState>(state: _BlocBuilderBaseState<AuthenticationBloc, AuthenticationState>#1c4cd):
        BlocProvider.of() called with a context that does not contain a Bloc of type LoginBloc.

        No ancestor could be found starting from the context that was passed to BlocProvider.of<LoginBloc>().

        This can happen if the context you used comes from a widget above the BlocProvider.

        The context used was: LoginScreen(dirty, state: _LoginScreenState#346c7(lifecycle state: created))

The relevant error-causing widget was
    BlocBuilder<AuthenticationBloc, AuthenticationState> 
lib\src\app.dart:32
When the exception was thrown, this was the stack
#0      BlocProvider.of 
package:flutter_bloc/src/bloc_provider.dart:106
#1      _LoginScreenState.initState 
package:DPOD/…/login_screen/login_screen.dart:55
#2      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4355

import 'dart:convert';

import 'package:DPOD/src/blocs/authentication_bloc/bloc.dart';
import 'package:DPOD/src/blocs/login_bloc/bloc.dart';
import 'package:DPOD/src/repository/user_repository.dart';
import 'package:DPOD/src/utilities/constants/colors.dart';
import 'package:DPOD/src/utilities/constants/string.dart';
import 'package:DPOD/src/utilities/constants/values.dart';
import 'package:amazon_cognito_identity_dart/cognito.dart';
import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:country_code_picker/country_code_picker.dart';
import 'package:jaguar_jwt/jaguar_jwt.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../../../main.dart';
import 'loginCommonWidgets/loginTextWidgets.dart';
import 'loginScreenComponents/dpod_banner.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class LoginScreen extends StatefulWidget {
  final UserRepository _userRepository;

  LoginScreen({Key key, @required UserRepository userRepository})
      : assert(userRepository != null),
        _userRepository = userRepository,
        super(key: key);

  @override
  _LoginScreenState createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final phonenumberController = TextEditingController();
  final pinController = TextEditingController();
  final scaffoldKey = GlobalKey<ScaffoldState>();
  String code = '+91';
  moveToMainScreen() {
    Navigator.of(context).pushNamed(HOME_SCREEN);
  }

  static final _formKey = GlobalKey<FormState>();
  UserRepository get _userRepository => widget._userRepository;
  LoginBloc _loginBloc;

  bool get isPopulated =>
      phonenumberController.text.isNotEmpty && pinController.text.isNotEmpty;
  bool isLoginButtonEnabled(LoginState state) {
    return state.isFormValid && isPopulated && !state.isSubmitting;
  }

  @override
  void initState() {
    super.initState();
    _loginBloc = BlocProvider.of<LoginBloc>(context);
    phonenumberController.addListener(_onPhonenumberChanged);
    pinController.addListener(_onPinChanged);
  }

  @override
  void dispose() {
    phonenumberController.dispose();
    pinController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    String name = '';
    return BlocListener<LoginBloc, LoginState>(bloc: _loginBloc,
      listener: (context, state) {
      if (state.isFailure) {
        Scaffold.of(context)
          ..hideCurrentSnackBar()
          ..showSnackBar(
            SnackBar(
              content: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [Text('Login Failure'), Icon(Icons.error)],
              ),
              backgroundColor: Colors.red,
            ),
          );
      }
      if (state.isSubmitting) {
        Scaffold.of(context)
          ..hideCurrentSnackBar()
          ..showSnackBar(
            SnackBar(
              content: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('Logging In...'),
                  CircularProgressIndicator(),
                ],
              ),
            ),
          );
      }
      if (state.isSuccess) {
        BlocProvider.of<AuthenticationBloc>(context).add(LoggedIn());
      }
    }, child: BlocBuilder<LoginBloc, LoginState>(builder: (context, state) {
      
      return Scaffold(
          key: scaffoldKey,
          body: Stack(fit: StackFit.expand, children: <Widget>[
            Positioned(
              top: 0,
              child: Image(
                image: AssetImage("assets/images/app_wallpaper.png"),
                fit: BoxFit.fill,
                width: MediaQuery.of(context).size.width,
                height: MediaQuery.of(context).size.height,
              ),
            ),
            Align(
              alignment: Alignment.topCenter,
              child: Padding(
                padding: const EdgeInsets.only(top: 80.0),
                child: Image(
                  image: AssetImage('assets/images/dpod_logo_black.png'),
                  height: 40,
                ),
              ),
            ),
            Form(
              key: _formKey,
              child: Padding(
                padding: EdgeInsets.fromLTRB(40, 260, 40, 0),
                child: ListView(
                  children: <Widget>[
                    Row(
                      children: <Widget>[
                        Container(
                          child: CountryCodePicker(
                            onChanged: (CountryCode countryCode) {
                              code = countryCode.toString();
                            },

                            // Initial selection and favorite can be one of code ('IT') OR dial_code('+39')
                            initialSelection: code,
                            textStyle: BODYTEXTWHITE,
                            favorite: ['+39', 'FR'], showFlag: false,
                            // optional. Shows only country name and flag
                            showCountryOnly: false,
                            // optional. Shows only country name and flag when popup is closed.
                            showOnlyCountryWhenClosed: false,
                            // optional. aligns the flag and the Text left
                            alignLeft: false,
                          ),
                          decoration: BoxDecoration(
                            color: BLACK_COLOR.withOpacity(0.6),
                            border: Border.all(color: BLACK_COLOR, width: 1),
                            borderRadius: BorderRadius.all(Radius.circular(10)),
                          ),
                          height: 58,
                          margin: EdgeInsets.fromLTRB(0, 0, 10, 0),
                        ),
                        Flexible(
                          child: inputTexts(
                            'phone_number',
                            false,
                            Icons.contact_phone,
                            name,
                            textEditingController: phonenumberController,
                          ),
                        ),
                      ],
                    ),
                    SizedBox(height: 10),
                    inputTexts(
                      'pin_number',
                      true,
                      Icons.lock,
                      name,
                      textEditingController: pinController,
                    ),
                    Row(
                      children: <Widget>[
                        Spacer(),
                        FlatButton(
                          child: Text('Lost Pin? ', style: TEXTINPUTWHITE),
                          onPressed: () {},
                        ),
                      ],
                    ),
                    SizedBox(
                      width: double.infinity,
                      height: 40,
                      child: RaisedButton(
                        elevation: CARD_ELEVATION,
                        disabledColor: RED_COLOR,
                        color: RED_COLOR.withOpacity(0.6),
                        child: Text(translator.getTextForKey("sign_in"),
                            style: H5_WHITE),
                        onPressed: isLoginButtonEnabled(state)
                              ? _onFormSubmitted
                              : null,
                        /* () async {
                           if (phoneController.text.trim().isEmpty) {
                            scaffolKey.currentState.showSnackBar(SnackBar(
                              content: Text("Phone cannot be empty"),
                            ));
                            return;
                          } 
                           if (_formKey.currentState.validate()) {
                            String phoneNumber = code + phoneController.text;
                            final user = CognitoUser(phoneNumber, userPool);
                            CognitoUserSession response;
                            String error;

                            try {
                              //  accountWebServices();
                              response = await user.authenticateUser(
                                  AuthenticationDetails(
                                      username: phoneNumber,
                                      password: passwordController.text));

                              final String token =
                                  response.getIdToken().jwtToken;
                              saveToken(token);
                              moveToMainScreen();
                              // getToken();

                               final parts = token.split('.');
                                                                final payload = parts[1];
                                                                final String decoded =
                                                                    B64urlEncRfc7515.decodeUtf8(payload);
                                                                String subject = json.decode(decoded)['sub'];                             } catch (e) {
                              error = e.message;
                              scaffolKey.currentState.showSnackBar(SnackBar(
                                content: Text(error ?? "Unknown Error"),
                              ));
                            }
                          }  
                        }, */
                      ),
                    ),
                    Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        Text(
                          translator.getTextForKey('no_account'),
                          style: H5_WHITE,
                        ),
                        ButtonTheme(
                          padding: new EdgeInsets.only(left: 4.0),
                          minWidth: 30,
                          child: FlatButton(
                            child: Text(
                              translator.getTextForKey("sign_up"),
                              style: H5_WHITE,
                            ),
                            onPressed: () {
                              Navigator.of(context).pushNamed(SIGNUP_SCREEN);
                            },
                          ),
                        ),
                      ],
                    ),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: <Widget>[
                        Icon(Icons.language, color: WHITE_COLOR),
                        SizedBox(width: 5),
                        DropdownButton(
                          items: translator.supportedLanguages.keys
                              .map(
                                (value) => DropdownMenuItem(
                                  child: Text(
                                      translator.getReadableLanguageKey(value)),
                                  value: value,
                                ),
                              )
                              .toList(),
                          isExpanded: false,
                          underline: SizedBox(),
                          value: null,
                          hint: Text(
                            translator.getTextForKey("language"),
                            style: BODYTEXTWHITE,
                          ),
                          iconDisabledColor: WHITE_COLOR,
                          iconEnabledColor: WHITE_COLOR,
                          onChanged: (newvalue) {
                            translator
                                .updateLanguagePref(newvalue)
                                .then((done) {
                              setState(() {});
                            });
                          },
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ),
            DpodBanner(),
          ]));
    }));
  }

  void accountWebServices() async {
    try {
      Dio dio = Dio();
      // dio.options.headers['accept'] = 'application/json';
      Response<String> response = await dio.get(
          "http://w1uwly472h.execute-api.us-east-1.amazonaws.com/dev/api/saas/user/a3831501-3fb8-4448-8f5d-1c212f4a0f57/account",
          options: Options(headers: {"accept": "application/json"}));
      print(response);
      List responseJson = json.decode(response.data);
      print(responseJson.length);
      if (response.statusCode == 200) {
        /* List<String> list =
            (json.decode(response.data) as List).map((data) => LoginAccounts.fromJson(data)).toList(); */

      } else {
        throw Exception('Failed to load');
      }
    } catch (e) {
      print(e);
    }
  }

  Future<void> saveToken(String token) async {
    final pref = await SharedPreferences.getInstance();
    await pref.setString('token', token);
  }

  Future<void> getToken() async {
    final pref = await SharedPreferences.getInstance();
    pref.getString('token');
    print("Token  =" + pref.getString('token'));
  }

  void _onPhonenumberChanged() {
    _loginBloc.add(
      PhoneNumberChanged(phonenumber: phonenumberController.text),
    );
  }

  void _onPinChanged() {
    _loginBloc.add(
      PinChanged(pin: pinController.text),
    );
  }

  void _onFormSubmitted() {
   String phonenumber=code+phonenumberController.text;
    _loginBloc.add(
      LoginWithCredentialsPressed(
        phonenumber: phonenumber,
        pin: pinController.text,
      ),
    );
  }
}

import 'package:DPOD/src/repository/user_repository.dart';
import 'package:DPOD/src/ui/main_screen/home_sceen.dart';
import 'package:DPOD/src/utilities/constants/string.dart';
import 'package:flutter/material.dart';

import 'blocs/authentication_bloc/bloc.dart';
import 'ui/login_screen/login_screen.dart';
import 'ui/main_screen/me_screen/me_screen_subscreens/treatment/report/upload_test_report.dart';
import 'ui/main_screen/me_screen/me_screen_subscreens/vitals/bloodglucose/record_blood_glucose.dart';
import 'ui/main_screen/me_screen/me_screen_subscreens/vitals/bp/record_blood_pressure.dart';
import 'ui/main_screen/plans_screen/explore/recommended_plans_screen.dart';
import 'ui/signup_screens/signup_screen.dart';
import 'ui/signup_screens/welcome_pageviews/hi.dart';
import 'ui/signup_screens/welcome_screen.dart';
import 'utilities/constants/string.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class App extends StatelessWidget {
  final UserRepository _userRepository;

  App({Key key, @required UserRepository userRepository})
      : assert(userRepository != null),
        _userRepository = userRepository,
        super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      navigatorKey: mainNavigatorKey,
      debugShowCheckedModeBanner: true,
      theme: ThemeData(primarySwatch: Colors.orange, fontFamily: 'Roboto'),
      home: BlocBuilder<AuthenticationBloc, AuthenticationState>(
        builder: (context, state) {
          if (state is Unauthenticated) {
            return LoginScreen();
          }
          if (state is Authenticated) {
            return HomeScreen();
          }
          return CircularProgressIndicator();
        },
      ),
      routes: <String, WidgetBuilder>{
        LOGIN_SCREEN: (context) => LoginScreen(),
        HOME_SCREEN: (context) => HomeScreen(),
        SIGNUP_SCREEN: (context) => SignupScreen(),
        WELCOME_SCREEN: (context) => WelcomeScreen(),
        HI_SCREEN: (context) => Hi(),
        RECOMMENDED_PLANS_SCREEN: (context) => RecommendedPlansScreen(),
        RECORD_BLOOD_PRESSURE: (context) => RecordBloodPressure(),
        RECORD_BLOOD_GLUCOSE: (context) => RecordBloodGlucose(),
        UPLOAD_TEST_REPORT: (context) => UploadTestReport()
      },
    );
  }
}

**Comment by samsheldin** [comment]
@felangel  pls help

**Comment by tenhobi** [comment]
Format your comment if you wanna help. How can you expect someone will help you if you don't even take a minute to prepare the stuff?

Anyway, it might be related to this https://bloclibrary.dev/#/faqs?id=blocproviderof-fails-to-find-bloc

**Comment by samsheldin** [comment]
@tenhobi  sorry

**Comment by samsheldin** [comment]
@tenhobi  thanks for the insight i didnt knew how to organize things ,,, thanks for the help... god bless u man

**Comment by DanGerHOGGISH** [comment]
> Format your comment if you wanna help. How can you expect someone will help you if you don't even take a minute to prepare the stuff?
> 
> Anyway, it might be related to this https://bloclibrary.dev/#/faqs?id=blocproviderof-fails-to-find-bloc

+)

**Comment by samsheldin** [comment]
@DanGerHOGGISH etremly grateful for your help thanks
