### ISSUE TITLE
Ignore states in builder that should only be used in listener

### ISSUE THREAD

**Issue by Limbou** [felangel/bloc#866]
**Is your feature request related to a problem? Please describe.**
Let's say we have 3 states: A, B and C. We want to perform build on states A, B and we want to perform some specific actions (not build) on state C. Perfect solution here would be BlocConsumer. The problem is, even though we only want to react to state C in listener, it will also be handled in builder. To avoid that we have to use the `buildWhen` condition, like this: 

```
buildWhen: (previous, current) => current is! StateC
```

For two states it would look like this:

```
buildWhen: (previous, current) => current is! StateC && current is! StateD
```

As you can see it doesn't look very clean and we have to remember about adding new states to `buildWhen` condition.

**Describe the solution you'd like**
I would like to create a new class called NotBuildable which all the states that I don't want to be caught by builder would implement. NotBuildable would not have any properties or methods, it would just work as an indicator for the builder not to rebuild a view.
This is how currently the content of `_subscribe` method in BlocBuilderBase I want to change looks like:
```
if (widget.condition?.call(_previousState, state) ?? true) {
    setState(() {
       _state = state;
    });
}
```

After my solution it would look like: 
```
if (_shouldUpdateState(state)) {
    setState(() {
       _state = state;
    });
}

bool _shouldUpdateState(S state) {
    final result = (widget.condition?.call(_previousState, state) ?? true);
    return result && state is! NotBuildable;
}
```

**Describe alternatives you've considered**
I have also considered a possibility to add a new parameter to BlocBuilder widget called `ignoredStates`. Developer could then pass an array of states that should be ignored by the builder. The former seems to be easier to use in my opinion.

**Comment by RollyPeres** [comment]
Rather have a `mixin` for that like `SkipBuildMixin`, since having something like `abstract class SomeState implements NotBuildable {}` with nothing to implement is shady.

**Comment by felangel** [comment]
Hi @Limbou 👋 
Thanks for opening an issue!

Would it be possible for you to share a link to a sample project with a concrete use case? It would be really helpful for me, thanks!

**Comment by Limbou** [comment]
@RollyPeres I haven't thought about using `mixin`, but it sound even better. Thanks for the suggestion!

@felangel Here is the link to a simple use case scenario. Let me know if anything is unclear. [https://github.com/Limbou/bloc_not_buildable_example](url)

**Comment by felangel** [comment]
@Limbou thanks! I opened a [pull request](https://github.com/Limbou/bloc_not_buildable_example/pull/1) with some suggestions. At the end of the day, I'd like to try to keep things as simple as possible and avoid adding more "features" unless they are critical. Let me know what you think, thanks! 👍

**Comment by felangel** [comment]
@Limbou, @RollyPeres what are you thoughts on the PR?

**Comment by Limbou** [comment]
@felangel Thanks for your pull request. I have a feeling that you slightly misunderstood my point. I will try to come up with more complex example for you soon to better understand what problem I am encountering.

**Comment by RollyPeres** [comment]
@felangel This is probably overkill to implement. This could easily be implemented by the developer by having it's own abstract class/mixin that he could implement/mix in and then adding a condition like `buildWhen: (previous, current) => current is! NotBuildable`

**Comment by Limbou** [comment]
@RollyPeres That is true, you would have to implement the `buildWhen` in every BlocBuilder you want to use it in though.

**Comment by felangel** [comment]
@Limbou how often is this coming up for you? I personally almost never encounter this case and very rarely use buildWhen. Maybe if you can share a more realistic example we can walk through it and see if there’s anything we can change.

**Comment by felangel** [comment]
Closing for now since there doesn’t seem to be any actionable items. Feel free to comment with a more concrete example that you feel can’t be solved with the approach I presented in the PR above and I’m happy to continue the discussion 👍
