### ISSUE TITLE
Clarify README section regarding extensions usage

### ISSUE THREAD

**Issue by nvma** [felangel/bloc#874]
Hey! I've been using bloc library extensively by now and today I went back to consult [README](https://github.com/felangel/bloc/blob/master/packages/flutter_bloc/README.md) section where I found this snippet:

```
// with extensions
context.bloc<BlocA>();

// without extensions
BlocProvider.of<BlocA>(context)
```

I'm using your superb VSCode extension for snippets and bloc scaffolding but I can't figure out how or where `context.bloc<BlocA>();` works?

**Comment by felangel** [comment]
Hi @nvma 👋 
Thanks for opening an issue and for the positive feedback!

With `flutter_bloc v3.2.0` you can now use the extensions on `BuildContext`. Just make sure you're using v3.2.0 and that you have `import 'package:flutter_bloc/flutter_bloc.dart';` at the top of your file and you should be good to go.

Hope that helps 👍

**Comment by nvma** [comment]
Oh, now I see it! Should've looked at the change log and followed on #608, that's a very convenient improvement, thanks a lot for your tireless and fruitful labour. Cheers!

**Comment by Kedar-27** [comment]
Not working in 7.0.0 null safety

**Comment by felangel** [comment]
> Not working in 7.0.0 null safety

@Kedar-27  can you elaborate? Is there a reproduction sample that you can share?

**Comment by Kedar-27** [comment]
I am not using any intellij extension, currently working on flutter beta branch and using flutter bloc 7.0.0 null safety.
It gives this error . 
`The getter 'bloc' isn't defined for the type 'BuildContext'.  Try importing the library that defines 'bloc', correcting the name to the name of an existing getter, or defining a getter or field named 'bloc'.`

**Comment by felangel** [comment]
@Kedar-27 do you have the `flutter_bloc` import?

```dart
import 'package:flutter_bloc/flutter_bloc.dart';
```

**Comment by Kedar-27** [comment]
> @Kedar-27 do you have the `flutter_bloc` import?
> 
> ```dart
> import 'package:flutter_bloc/flutter_bloc.dart';
> ```
> 
> Also, `context.bloc` was removed (it was deprecated in v6.0.0). Please use `context.read` and `context.watch` instead.

Opps, my bad
