### ISSUE TITLE
Widget Tree growing endlessy

### ISSUE THREAD

**Issue by skvie** [felangel/bloc#879]
**Describe the bug**
When using multiple BlocProvider in combination with BlocBuilder the widget tree is growing endlessy.

**To Reproduce**

**Expected behavior**
When Navigating back from GameView to Initial View don't save states. 

Saved states from earlier calls:

`flutter: State of GameSelectionState GameSelectionInitial
flutter: State of GameSelectionState GameSelectionStart
flutter: State of QuestionState StopQuestion
flutter: OK?
flutter: State of GameSelectionState GameSelectionStart
flutter: State of QuestionState StopQuestion
flutter: OK?
flutter: State of GameSelectionState GameSelectionInitial`

**Screenshots**
<img width="826" alt="Bildschirmfoto 2020-02-16 um 00 28 42" src="https://user-images.githubusercontent.com/10911394/74597628-c1ffb800-5062-11ea-99df-22070990396c.png">
(Depending on how often I navigate back to Initial View I got N nested Views and it's calling state multiple times with previous states till it actually gets to the latest one...)

**Logs **
Run `flutter analyze` and attach any output of that command below.
`info • Unused import: 'package:booze/model/GameConstructor.dart' • lib/bloc/game_bloc.dart:4:8 • unused_import
   info • Unused import: 'package:booze/repository/question_repository.dart' • lib/bloc/game_bloc.dart:6:8 •
          unused_import
   info • Unused import: 'package:booze/util/question_helper.dart' • lib/bloc/game_bloc.dart:7:8 • unused_import
   info • Unused import: 'dart:math' • lib/bloc/question_bloc.dart:2:8 • unused_import
   info • Unused import: 'package:booze/util/question_helper.dart' • lib/bloc/question_bloc.dart:7:8 • unused_import
   info • This class (or a class that this class inherits from) is marked as '@immutable', but one or more of its
          instance fields aren't final: NextQuestion.subtask • lib/bloc/question_event.dart:7:7 • must_be_immutable
   info • Unused import: 'package:booze/bloc/question_bloc.dart' • lib/main.dart:2:8 • unused_import
   info • This function has a return type of 'Widget', but doesn't end with a return statement •
          lib/pages/game_view.dart:41:10 • missing_return
   info • The value of the field 'replyBlue800' isn't used • lib/pages/initial_view.dart:25:20 • unused_field
   info • The value of the field 'borderColor' isn't used • lib/pages/initial_view.dart:28:22 • unused_field
   info • The value of the local variable 'snackBar' isn't used • lib/pages/initial_view.dart:61:15 •
          unused_local_variable
   info • The declaration '_onCreate' isn't referenced • lib/repository/question_repository.dart:68:10 •
          unused_element
   info • Unused import: 'package:flutter/material.dart' • test/question_model_test.dart:3:8 • unused_import
`

Paste the output of running `flutter doctor -v` here.
[✓] Flutter (Channel master, v1.14.7-pre.118, on Mac OS X 10.15.3 19D76, locale de-DE)
    • Flutter version 1.14.7-pre.118 at /Users/hendrikheim/dev/flutter
    • Framework revision 94c7e823be (vor 11 Tagen), 2020-02-05 08:00:32 +0100
    • Engine revision 81dffd1241
    • Dart version 2.8.0 (build 2.8.0-dev.7.0 c8ed304e97)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (2 available)

**Additional context**

**Comment by skvie** [comment]
What a shame... I fixed it myself using Navigator.of(context) 

`onGenerateRoute: (settings) {
        // If you push the PassArguments route
        if (settings.name == InitialView.routeName) { 
... 
}`

**Comment by felangel** [comment]
@skvie glad you were able to resolve this. Can this issue be closed?

**Comment by skvie** [comment]
@felangel , yeah :)
Sorry for inconvenience.
