### ISSUE TITLE
[Translations] Examples/Weather

### ISSUE THREAD

**Issue by felangel** [felangel/bloc#888]
Update Translations to include https://github.com/felangel/bloc/pull/887

- [x] cs (@tenhobi)
- [x] pt-br (@rodrigobastosv)
- [x] ru (@basilex)

**Comment by basilex** [comment]
RU docs update is ready for the PR:
https://github.com/felangel/bloc/pull/887/commits/6bd34afb262c30e11117c4709ebc0a4e6abe3e6f
:)

**Comment by felangel** [comment]
@rodrigobastosv do you have any time to update the `pt-br` translations? Thanks!

**Comment by rodrigobastosv** [comment]
Sure @felangel , give me a couple of days! :)

**Comment by rodrigobastosv** [comment]
@felangel #921

Felix, please don't hesitate to mark me when you have updates to the documentation. I can't keep up with the changes, but it will be a pleasure to update whenever possible :)
