### ISSUE TITLE
Need Help on MaterialApp routes with bloc

### ISSUE THREAD

**Issue by Sandesh-Solabannavar** [felangel/bloc#898]
Kindly help me out how can a pass the parameter to HomeScreen when the state is Authenticated.
 Its the same code as Login With Firebase, just need to make it with MaterialApp routes.

![image](https://user-images.githubusercontent.com/23529429/74796370-647f9b80-52ee-11ea-9e52-0214643c35b7.png)

**Comment by basilex** [comment]
> Kindly help me out how can a pass the parameter to HomeScreen when the state is Authenticated.
Hi! Just check the tutorials, described below:
Reso Coder: https://www.youtube.com/watch?v=nyvwx7o277U&t=195s
Dane Mackier : https://medium.com/flutter-community/flutter-navigation-cheatsheet-a-guide-to-named-routing-dc642702b98c

**Comment by Sandesh-Solabannavar** [comment]
The given tutorial is just about Navigation i need with Flutter Bloc.

**Comment by felangel** [comment]
Hi @Sandesh-Solabannavar 👋 
Thanks for opening an issue!

Have you taken a look at the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess)?

**Comment by Sandesh-Solabannavar** [comment]
i found only how to go from one page to other.
i need help to declare the routes for MaretialApp.

**Comment by mateuszmatyszkowicz** [comment]
What do you think about use `onGenerateRoute` create base class which will handle it. Through DI add AuthenticationBloc and use it within this class?

**Comment by felangel** [comment]
[Named Routes Recipe](https://gist.github.com/felangel/8d143cf3b7da38d80de4bcc6f65e9831). Will add one for `onGenerateRoute` as well shortly 👍
