### ISSUE TITLE
[QUESTION] Best approach to handle multiple widget in one page with bloc

### ISSUE THREAD

**Issue by bontew** [felangel/bloc#903]
**Question**
I know this is basic question. I want to ask what best approach if i have a page with multiple independent widget using bloc pattern?

**Example**
- report page
-- Widget1: a card for today report
-- Widget2: a card for monthly report
-- Widget3: a card for range date report

Should i create a bloc to each widget or i can handle all widget with one bloc? since user can change spesific input for each widget

**Comment by felangel** [comment]
Hi @bontew 👋 
Thanks for opening an issue!

It's hard for me to provide a specific recommendation without additional information/context but I would recommend starting to model that page with a single state and if it starts to feel awkward or bloated then it's usually a sign you should break it up into smaller blocs with independent states.

Hope that helps!
