### ISSUE TITLE
[Question] - Block state change 

### ISSUE THREAD

**Issue by IsaNascimento** [felangel/bloc#908]
I have a page with a loadingState and other buttons that can change that page's state (for example back button, tabs, etc). Is there a way/best way for me to block state change when in a specific state? Ie: If my bloc is in the loadingState then clicking on the back button won't work/change state. I know I can have a conditional in the onPressed function but I didn't want to have to do it for each widget that can affect the bloc's state. What is the best way for me to centralize this on the bloc itself?

**Comment by felangel** [comment]
Hi @IsaNascimento 👋 
Thanks for opening an issue!

I think whether or not a UI element is disabled belongs in the widget itself so maybe having a getter

```dart
bool get _isInteractive => state is! Loading;
```

and then in your buttons or other interactive widgets you can do something like:

```dart
MaterialButton(
  onPressed: _isInteractive ? _onPressed : null,
  ...
),
```

Hope that helps!
