### ISSUE TITLE
[Translation] Chinese(Simplified) Docs Translation in Progress

### ISSUE THREAD

**Issue by jakecastelli** [felangel/bloc#909]
If anyone is interested in contributing to **Chinese (Simplified)** Docs  with me, please let me know, so that we can work together and speed things up! I will mainly follow the order to continue, if you are willing to contributing, you are always welcome to pick up any page you like!

**The remaining parts are:**
- Tutorials
  - Flutter
    - [x] Counter       
    - [ ] Timer <-- @jakecastelli currently working on it 👋 
    - [x] Infinite List  
    - [ ] Login <-- @xloc 👋
    - [ ] Weather <-- @jakecastelli currently working on it 👋 
    - [ ] Todos
    - [ ] Firebase Login
    - [ ] Firestore Todos
  - AngularDart
    - [ ] Counter
  - Flutter + AngularDart
    - [ ] Github Search
- Recipes
  - Flutter
    - [x] Show SnackBar 
    - [ ] Navigation <-- @lakerszhy👋
    - [ ] Bloc Access
- Tools
  - Extensions
    - [ ] IntelliJ
    - [ ] VSCode

**Comment by xloc** [comment]
Hi, I'd like to contribute to the Bloc Chinese(Simplified) translation. How can I start?

**Comment by felangel** [comment]
Hi @xloc 👋 
Thanks so much for offering to help!

To get started you just need to fork the repo, and start translating the content in docs/zh-cn 👍 
Let me know if you run into any issues and thanks again 😄

**Comment by xloc** [comment]
Happy to be able to help you and this project  :D

Thank you for your help. I'll start translating `Tutorials > Flutter > InfinityList` and get back here when finished.

**Comment by jakecastelli** [comment]
> Happy to be able to help you and this project :D
> 
> Thank you for your help. I'll start translating `Tutorials > Flutter > InfinityList` and get back here when finished.

Hi @xloc 👋 

That's fantastic!
To start with, you may need to have a look at [here](https://github.com/felangel/bloc/blob/master/CONTRIBUTING.md#contributing-to-documentation) where mentioned in detail how to contribute to the docs, I will put your name next to the page you are working on, in this case, people who wanna contribute to the zh-ch docs won't conflict to each other!

If you have any other question, please feel free to ask.

Welcome onboard!

**Comment by xloc** [comment]
Hey guys

I've completed the InfinityList tutorial translation and initiated a pull request. Please just let me know if I did anything wrong(this is the first time that I try to contribute to an open-source project. I have no idea what is the correct procedure). Thank you for your help.

Besides, can I then work on `Tutorials > Flutter > Login`? @jakecastelli

**Comment by felangel** [comment]
Thanks so much @xloc! I just approved and merged your changes. It would be amazing if you could work on login next 💙

**Comment by xloc** [comment]
Great!! Thanks a lot. Let me do that~

**Comment by jakecastelli** [comment]
@xloc 
I have updated the issue, thanks for you contribution!

**Comment by lakerszhy** [comment]
Hi guys, I want to translate Recipes -> Flutter,  can I ?

**Comment by jakecastelli** [comment]
> Hi guys, I want to translate Recipes -> Flutter, can I ?

Awesome, thank you for contributing! 

I will put your name next to the item your are about to translate.
Cheers.

**Comment by lakerszhy** [comment]
> > Hi guys, I want to translate Recipes -> Flutter, can I ?
> 
> Awesome, thank you for contributing!
> 
> I will put your name next to the item your are about to translate.
> Cheers.
> 
> UPDATE:
> Could you please start from Show SnackBar Page first?

OK，I'll start from Show SnackBar.

**Comment by lakerszhy** [comment]
@jakecastelli Hi, I have done with Show SnackBar, can I continue with Navigation?

**Comment by jakecastelli** [comment]
> @jakecastelli Hi, I have done with Show SnackBar, can I continue with Navigation?

Sure!

**Comment by felangel** [comment]
Closing this for now since it's been a while since there has been any activity and there have been significant documentation changes so the checklist is outdated. If anyone is still working on translations or would like to help please either create a new issue for the specific part you are working on or refer to https://github.com/felangel/bloc/issues/1196 for all outdated docs. Thanks! 🙏
