### ISSUE TITLE
Providing repository bellow MaterialApp and Navigation

### ISSUE THREAD

**Issue by VadimOsovsky** [felangel/bloc#912]
hey Felix! thanks for the awesome library!
I have repo providers that are bellow MaterialApp, and I have a hard time retrieving them on screens I navigate to. After some research here are the solutions I've found so far:
1) Adding duplicating providers in MaterialPageRoute's builder by wrapping a screen widget in provider.
2) Putting providers above material app, which doesn't work for me, since most repos need some data, received during app usage
3) Creating multiple MaterialApps which is a pretty bad idea

Are there any elegant solutions to this?

**Comment by felangel** [comment]
Hi @VadimOsovsky 👋 
Thanks for opening an issue!

The general rule of thumb is you should provide the object (in this case `Repository`) at the lowest common ancestor of all widgets that need it. If you need it to be accessible across multiple routes, then your two options are to provide above the `MaterialApp` or to wrap your new pages in `RepositoryProvider.value`.

You can check out the [bloc access recipe](https://bloclibrary.dev/#/recipesflutterblocaccess?id=route-access) for more details.

Closing for now but feel free to comment with additional questions and I'm happy to continue the conversation 👍

**Comment by VadimOsovsky** [comment]
Basically no other way, ok, thanks for the response!

**Comment by felangel** [comment]
@VadimOsovsky this is how Flutter and `InheritedWidget` work and it doesn't have anything to do with bloc. You would have the same problem providing anything via `BuildContext`. If this behavior is undesired it might make sense to look into other DI alternatives.
