### ISSUE TITLE
[Document] need migration doc for upgrade 2.x to 3.x for flutter_bloc & bloc_test

### ISSUE THREAD

**Issue by hunght** [felangel/bloc#914]
I can't find any document relate to this. Does this mean we don't need any action after upgrade from 2.x to 3.x?

**Comment by felangel** [comment]
You can check out the [bloc changelog](https://github.com/felangel/bloc/blob/master/packages/bloc/CHANGELOG.md#300) and [flutter_bloc changelog](https://github.com/felangel/bloc/blob/master/packages/flutter_bloc/CHANGELOG.md#300) but there aren't many major API changes. The big one was the upgrade to `provider v4.0.0`.

Hope that helps 👍
