### ISSUE TITLE
Trouble using multiple bloc providers for same type.

### ISSUE THREAD

**Issue by barapa** [felangel/bloc#919]
I have a widget that displays a list of cards from a list of games.

In order to create these cards, I call the following method in a loop in order to create the cards:

```
Widget _card({
  @required BuildContext context,
  @required String roomId,
  @required String gameId,
  @required String puzzleId,
}) {
  print('~~~creating a card with gameId: ${gameId}');
  return BlocProvider<GameRoomGameCardBloc>(
    create: (BuildContext context) => GameRoomGameCardBloc(
      roomId: roomId,
      gameId: gameId,
      puzzleId: puzzleId,
      authenticationBloc: BlocProvider.of<AuthenticationBloc>(context),
      puzzleRepository: RepositoryProvider.of<PuzzleRepository>(context),
      gameRepository: RepositoryProvider.of<GameRepository>(context),
      progressRepository:
          RepositoryProvider.of<UserGameProgressRepository>(context),
    ),
    child: GameCard(),
  );
}
```

However, while I can confirm that I do call this method to create each `GameCard` widget as expected for each passed in gameId, the constructor for the `GameRoomGameCardBloc` is not necessarily called each time. The behavior manifests itself as cards showing the same data as one another, apparently because they are sharing a bloc.

When I load the page for the first time, the cards load as expected. But, if I create a new game via a dialog popup, and via firestore, trigger an event / state update to load the new game cards, I get the duplicates. If I exit the screen and then re-enter, all of the cards are loaded as expected.

Am I making an error in how I am trying to construct the blocs?

**Comment by barapa** [comment]
I have been able to avoid the issue by setting a key on the BlocProvider. Is this the right approach?

**Comment by felangel** [comment]
Hi @barapa 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the issue you're having?
The way BlocProvider works is it will make a bloc available to a subtree and if you provide multiple blocs to the same subtree, the widgets will access the nearest bloc.

**Comment by felangel** [comment]
Closing for now but feel free to comment with additional questions/details and I'm happy to continue the conversation 👍

**Comment by tgbarker** [comment]
> 
> 
> I have been able to avoid the issue by setting a key on the BlocProvider. Is this the right approach?

I used this approach and it worked for me too. Thank you for this. I would presume it is an appropriate approach.
