### ISSUE TITLE
bloc_test 4.0.0 documentation update

### ISSUE THREAD

**Issue by srombs** [felangel/bloc#922]
I am trying the bloc_test 4.0.0 release. I like the updates, but the documentation was out of date regarding `verify` and using `bloc` as a parameter now. It is documented in https://github.com/felangel/bloc/pull/913 but not for the Readme.md at (https://github.com/felangel/bloc/tree/master/packages/bloc_test). Thanks.

**Comment by felangel** [comment]
Hi @srombs 👋 
Thanks for opening an issue!

Just addressed this in https://github.com/felangel/bloc/commit/6c961cf39a7fee61f9b8bb585476196a79470cda 👍 

Thanks again for pointing it out!
