### ISSUE TITLE
Examples/Tutorials don't follow the naming convention

### ISSUE THREAD

**Issue by danielfpedro** [felangel/bloc#934]
At [Todos Tutorial](https://bloclibrary.dev/#/fluttertodostutorial) an event is named as **LoadTodos** when it should be **TodosLoadedSuccess** based on [Naming Conventions](https://bloclibrary.dev/#/blocnamingconventions) of the docs.

That is just one example. The whole tutorials documentation is not following the naming convention.

**Comment by felangel** [comment]
Hi @danielfpedro 👋 
Thanks for opening an issue!

I called that out at the top of the naming conventions

> You may find some of the examples/documentation do not follow the naming conventions mainly for simplicity/conciseness. These conventions are strongly recommended for large projects with multiple developers.

Any PRs to update the examples are welcome 😄

**Comment by lsaudon** [comment]
I'll take care of it.
