### ISSUE TITLE
I'm having trouble defining base MultiBlocProvider

### ISSUE THREAD

**Issue by dungnv2602** [felangel/bloc#935]
I'm trying to define a BaseMultiBlocProvider class which gives me more control to invoke bloc on widget init & rebuild and helps reduce boilerplate code. But doing this compiler keeps complaining about `BlocProvider.of() called with a context that does not contain a Bloc of type ...` down on the widget tree.
```
import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class BaseMultiBlocView extends StatefulWidget {
  const BaseMultiBlocView({
    Key key,
    @required this.items,
    this.child,
  })  : assert(items != null),
        super(key: key);

  final List<MultiBlocViewItem> items;
  final Widget child;

  @override
  _BaseMultiBlocViewState createState() => _BaseMultiBlocViewState();
}

class _BaseMultiBlocViewState extends State<BaseMultiBlocView> {
  @override
  void initState() {
    super.initState();
    widget.items.map((item) {
      if (item.onBlocReady != null && !item.isExisting) {
        item.onBlocReady(item.bloc);
      }
    });
  }

  @override
  void didUpdateWidget(BaseMultiBlocView oldWidget) {
    super.didUpdateWidget(oldWidget);
    widget.items.map((item) {
      if (item.onRebuild != null) {
        item.onRebuild(item.bloc);
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: widget.items
          .map(
            (item) => item.isExisting
                ? BlocProvider.value(
                    value: item.bloc,
                  )
                : BlocProvider(
                    create: (_) => item.bloc,
                  ),
          )
          .toList(growable: false),
      child: widget.child,
    );
  }
}

class MultiBlocViewItem<T extends Bloc<dynamic, dynamic>> {
  const MultiBlocViewItem({
    @required this.bloc,
    this.onBlocReady,
    this.onRebuild,
    this.isExisting = false,
  }) : assert(bloc != null);

  final bool isExisting;
  final T bloc;
  final void Function(T) onBlocReady;
  final void Function(T) onRebuild;
}
```
Can you help me clarify what did I do wrong about the code?

**Comment by felangel** [comment]
Hi @dungnv2602 👋
Thanks for opening an issue!

The problem is you’re mapping a List<MultiBlocViewItem> which has a dynamic bloc. If you look at the type of BlocProvider when you call create it will likely be BlocProvider<Bloc<dynamic, dynamic>> which means if you try to lookup the bloc later by type it will fail.

This is the same reason why MultiBlocProvider takes a List<BlocProvider> and not a List<Bloc>.

Hope that helps 👍

**Comment by dungnv2602** [comment]
My problem is I want more fine control over when bloc invokes event. As you can see from my code above, what I'm trying to do is invoking bloc only in initState. Because if I don't do that, normally in situations which I want to invoke bloc on create, I will implement bloc and then use cascade like this.
```
MultiBlocProvider(
            providers: [
              BlocProvider(
                create: (_) => TmdbBloc<MovieAccountStatus>(locator<TmdbRepo>())
                  ..add( // cascade 
                    BlocLoad(...),
                    ),
                  ),
              ),
              BlocProvider(
                create: (_) =>
                    TmdbBloc<List<UserListItemStatus>>(locator<TmdbRepo>())
                      ..add(  // cascade 
                        BlocLoad(...),
                      ),
              ),
            ],
),
```
I feel this approach is somewhat wrong as I scare whether or not it will reinvoke when widget rebuild or maybe this is not a good practice.
Can you help me clarify this?

**Comment by felangel** [comment]
@dungnv2602 `create` will only be called once so I would recommend using the cascade approach rather than the custom `MultiBlocView`.

**Comment by dungnv2602** [comment]
I'm clear now, thank you so much @felangel.
