### ISSUE TITLE
listen to state out of build

### ISSUE THREAD

**Issue by DJafari** [felangel/bloc#94]
i have a question

i want listen to state, and doing something with new state
for example i want listen to `AuthenticationState`, when is `AuthenticationAuthenticated` i want after 3 seconds push to new page, how can achieve to this ?

thanks

**Comment by felangel** [comment]
Hello! 👋 

You can either use a BlocBuilder in flutter_bloc or in pure dart you can do bloc.state.listen to react to state changes. 

Does that help answer your question?

**Comment by DJafari** [comment]
@felangel oh thanks,
just another question
i use `dio` to http requests, is possible use interceptor to catch 403 errors, if occurred, dispatch `LoggedOut` event to app that push my route to login route ?

(sorry for my bad english, I hope you understand my conversation(

**Comment by felangel** [comment]
Yeah you can definitely do that! You’ll just need to inject the bloc into your http interceptor and dispatch the event (like you said). If you have a code snippet that isn’t working I’d be happy to take a look but you have the right idea 👍

**Comment by DJafari** [comment]
i think because i don't have context in interceptor, i can't inject AuthenticationBloc

**Comment by felangel** [comment]
You can directly inject the bloc via the constructor. You’re right that you can’t use BlocProvider without a BuildContext.

**Comment by DJafari** [comment]
i found that

```

**Comment by felangel** [comment]
I think you can override the behavior of the hardware back button on android. I’m pretty sure there are some plugins that help with that.

**Comment by DJafari** [comment]
@felangel i faced with a problem

where does i must listen to authentication state ?
i have something :

```
authenticationBloc.state.listen((state) {
	if(state is AuthenticationUnauthenticated) {
	  Navigator.pushNamedAndRemoveUntil(context, '/', ((Route<dynamic> route) => false));
	}
});
```

but when state is `AuthenticationUnauthenticated`, i give this error :

```
The context used to push or pop routes from the Navigator must be that of a widget that is a descendant of a Navigator widget.
```

i tested it inside `BlocProvider` but any success

**Comment by felangel** [comment]
You need to do that within your `MaterialApp` widget. I would try moving that logic to the onInit override in your primary app component under `MaterialApp`.

**Comment by DJafari** [comment]
sorry my application not exist in git

currently i have this app :

```dart
BlocProvider<AuthenticationBloc>(
  bloc: _application.authenticationBloc,
  child: BlocBuilder(
    bloc: _application.authenticationBloc,
    builder: (BuildContext context, AuthenticationState state) {
      return new MaterialApp(
        title: Env.value.appName,
        debugShowCheckedModeBanner: false,
        theme: new ThemeData(
          fontFamily: 'IranYekan',
          primarySwatch: Colors.orange,
          primaryColorBrightness: Brightness.dark,
          backgroundColor: const Color(0xffEAE9EA),
          accentColor: const Color(0xff8e24aa)
        ),
        builder: (BuildContext context, Widget child) {
          return new Directionality(
            textDirection: TextDirection.rtl,
            child: new Builder(
              builder: (BuildContext context) {
                return new MediaQuery(
                  data: MediaQuery.of(context),
                  child: child,
                );
              },
            ),
          );
        },
        initialRoute: '/',
        routes: {
          '/': (context) => SplashPage(),
          '/home': (context) => HomePage(),
        },
      );
    }
  )
)
```

my login page is `SplashPage()` i want listen state in app, when state is `AuthenticationUnauthenticated` push `/`

**Comment by felangel** [comment]
Out of curiosity have you looked at the Login Flow example [here](https://felangel.github.io/bloc/#/flutterlogintutorial)?

**Comment by DJafari** [comment]
yeah, but my design is different
in my splash page, i have 2 button
login with email
login with phone number

if token set, buttons hides, and waiting for fetch user from api, when fetch successful i pushed route to `/home`

**Comment by felangel** [comment]
that's very similar except in your example you are pushing a new route as opposed to in the example I sent we use `BlocBuilder` and rebuild based on the `AuthenticationState`. Is there a reason you don't take a similar approach instead of pushing a route?

**Comment by DJafari** [comment]
on of biggest problem is `animating` 😁
for example changing home page with login page is not smooth

**Comment by felangel** [comment]
Ah okay. Have you checked this out? https://github.com/felangel/bloc/issues/18

**Comment by DJafari** [comment]
@felangel i will look into
big thanks
