### ISSUE TITLE
proper use of bloc: parameter in BlocBuilder/BlocListener

### ISSUE THREAD

**Issue by vinnytwice** [felangel/bloc#943]
@felangel.
Hi, can you please explain what `bloc:`  in `BlocBuilder` and `BlocListener` actually does?

I initially understood that it is a reference to a `Bloc X` that is not present in the widget tree, avoiding the need to provide `Bloc` X with `BlocProvider`  if you just need to react to its states but not sending events to it. And I can thing using it to create dependancies between blocs.

Then after (https://github.com/felangel/bloc/issues/930#issuecomment-593790702 that you confirmed in https://github.com/felangel/bloc/issues/930#issuecomment-593807651), thinking that it actually provides `Bloc X` as a `BlocProvider` would so you can send events to it, but  I tried to use it that way but when adding an event to Bloc X passed in `bloc:` I got an `BlocProvider.of() called with a context that does not contain a Bloc of type TrackingBloc` error. That means that `Bloc X` passed in `bloc:` wasn't available hence `bloc:` doesn't provide a bloc to the widget tree.

Now I'm back to my initial understanding of it being just a "reference" to a Bloc.

Can you please confirm what actually does?

Option 1:

Provides to to widget tree child `Bloc X`  as a `BlocProvider` does and from that point in the widget tree downward you can use the add()`method to send events to it. 

Option 2:

Provides to widget tree a "reference" to `Bloc X` which is outside the widget tree, so that widget tree can react to the `Bloc X` states from that point downward.

Option 3:

None of the above.. so I'm very lost lol.

Thank you very much.

**Comment by felangel** [comment]
Hi @vinnytwice 👋 
Thanks for opening an issue!

The bloc parameter on `BlocListener`/`BlocBuilder` is there for cases where you want to manually give `BlocListener`/`BlocBuilder` the bloc instance (if it isn't coming from the `BuildContext`.

The way it works is if you have provided the bloc instance via the bloc parameter manually, then that bloc will be used by `BlocBuilder`/`BlocListener` otherwise if no bloc is passed manually, `BlocListener`/`BlocBuilder` internally perform the lookup using the `BuildContext` via 
`context.bloc<MyBloc>()`.

As a result, the follow snippets are identical:

```dart
BlocBuilder<MyBloc, MyState>(
  builder: (context, state) {...}
)
```

```dart
BlocBuilder(
  bloc: context.bloc<MyBloc>(),
  builder: (context, state) {...}
)
```

Hope that helps! 👍

**Comment by vinnytwice** [comment]
Hi @felangel Ok it's now clear, so basically is option 2.

Would this be possible?

```
BlocBuilder<MyBloc, MyState>(
  bloc: context.bloc<MyBloc2>(),
  builder: (context, state) {...}
)
```

**Comment by RollyPeres** [comment]
@vinnytwice `BlocBuilder` works with a single type of bloc. Assuming you meant `MyBloc2` is just a different instance of `MyBloc`, then your `BlocBuilder` will use your explicitly passed in instance aka `MyBloc2`.

**Comment by vinnytwice** [comment]
@RollyPeres ok, got it. Thanks.

**Comment by felangel** [comment]
@vinnytwice that should not be possible because you will get an error saying `MyBloc2` is not assignable to type `MyBloc`.
