### ISSUE TITLE
Can we combined this package with Pagination?

### ISSUE THREAD

**Issue by rrifafauzikomara** [felangel/bloc#946]
Hi @felangel 

I have a question and want a discussion with you. Can I use this package with implemented `Pagination`?

For example, we can handle to show data first is `10`. Then if we scroll down, it will add `10` data again, and etc. Like `Pagination` in `Android Native (AndroidX component)`.

If it's possible, do you have an example to implement it with this package? Because this package it's so amazing to separate the logic with the UI.

Thank you very much!

**Comment by felangel** [comment]
Hi @rrifafauzikomara 👋 
Thanks for opening an issue!

You can check out the [infinite list tutorial](https://bloclibrary.dev/#/flutterinfinitelisttutorial) 👍
