### ISSUE TITLE
Enhancement and help on MultiBlocProvider

### ISSUE THREAD

**Issue by haraldkofler** [felangel/bloc#951]
**Is your feature request related to a problem? Please describe.**
I'm not able to understand the solution of the MultiBlocProvider

**Describe the solution you'd like**
If possible I'd like get some hint on how to use MultiBlocProvider and maybe some additional examples in the docu.

**Additional context**
As far as I understood so far, MultiBlocProvider can be used to provide a list of BlocProvider. I'm not able to catch how we should then consume those BlocProvider in the chile:

```
MultiBlocProvider(
      providers: [
        BlocProvider<BlocA>(
          create: (BuildContext context) => BlocA(),
        ),
        BlocProvider<BlocB>(
          create: (BuildContext context) => BlocB(),
        ),
      ], 
    
      child: Scaffold(
          body:() {
             if (BlocA.state is BlocAState.Loading || BlocB.state is BlocBStateLoading) {
               return CircularProgressIndicator(),
             }

          }
       )
),
)
```

Can you please guide me in the right direction?

Thanks!

**Comment by felangel** [comment]
Hi @haraldkofler 👋 
Thanks for opening an issue!

You would access your bloc's state via `BlocBuilder` like so:

```dart
MultiBlocProvider(
  providers: [
    BlocProvider(create: (_) => BlocA()),
    BlocProvider(create: (_) => BlocB()),
  ],
  child: Scaffold(
    body: BlocBuilder<BlocA, StateA>(
      builder: (context, state) {
        if (state is Loading) {...}
        ...
      },
    ),
  ),
);
```

Hope that helps! 👍

**Comment by haraldkofler** [comment]
Hi @felangel ,

thank you very much for your answer.
Just to be sure: Does this mean that I have to nest BlocBuilders, at the end I can then access the state like this:

MultiBlocProvider(
  providers: [
    BlocProvider(create: (_) => BlocA()),
    BlocProvider(create: (_) => BlocB()),
  ],
  child: Scaffold(
    body: BlocBuilder<BlocA, StateA>(
      builder: (contextA, stateA) {
        BlocBuilder<BlocB, StateB> (
        builder:
          if((stateA is StateALoading) && (stateB is StateBFinishedLoading)){
              ...
          }
        )
        );
    ),
  ),
);

Thanks again

**Comment by felangel** [comment]
@haraldkofler no problem and yes that's correct if your UI depends on both states 👍
