### ISSUE TITLE
[Best practice] Release resource with RepositoryProvider

### ISSUE THREAD

**Issue by marklureal** [felangel/bloc#952]
Hi, @felangel 

I release resources in the bloc which is provided by BlocProvider.

```
@override
  Future<void> close() async {
    super.close();
  }
```

What's the best practice to release resources in the repository which is provided by RepositoryProvider?

Thanks

**Comment by felangel** [comment]
Hi @marklureal 👋 
Thanks for opening an issue!

If you have this use case you can use a `StatefulWidget` to create the repository and handle releasing resources in the `dispose` like:

```dart
class MyWidget extends StatefulWidget {
  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget> {
  Repository _repository;

  @override
  void initState() {
    super.initState();
    repository = Repository(...);
  }

  @override
  void dispose() {
    _repository.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return RepositoryProvider.value(
      value: _repository,
      child: OtherWidget(),
    );
  }
}
```

I am planning to create a `Repository` interface in the future which has a `dispose` in order to follow the same pattern as `BlocProvider`. Let me know if that helps 👍

**Comment by marklureal** [comment]
Thanks. It will be a good feature.

So release resources with a StatefulWidget is just an alternative choice, not the best practice. Right?
[Is a good practice to have Repository in the presentation layer?](https://github.com/felangel/bloc/issues/491)

**Comment by CurrySenpai** [comment]
I don't think it's good create a repository interface, I've worked and seen various Monorepo apps and you would be forcing to add the bloc dependency in the data repository.

**Comment by felangel** [comment]
@CurrySenpai that's a valid point 👍 
@marklureal `StatefulWidget` is completely fine and would be my recommendation.

**Comment by marklureal** [comment]
OK. Thanks!

**Comment by CurrySenpai** [comment]
Although why not add the parameter dispose as in previous versions of provider / flutter_bloc?

**Comment by felangel** [comment]
@CurrySenpai that's what I was planning to do 😄 Will have a PR shortly 👍

**Comment by felangel** [comment]
@marklureal @CurrySenpai a valid point about not needing to maintain state and react to lifecycle hooks was brought up. Can you please provide some more context regarding why you feel this change is necessary?

**Comment by marklureal** [comment]
@felangel  Sorry， I'm new to flutter development and have no idea whether this change is necessary. I just wonder what's the best practice. This [discussion](https://github.com/felangel/bloc/pull/965) is meaningful.  

An example would like this:

There is a repository provides data from the camera with [this camera package](https://pub.dev/packages/camera#-readme-tab-).  There is a camera controller inside the CameraRepository. Two blocs use this repository. I will code them like this.

```
return RepositoryProvider<CameraRepository>(
    create: (context) => CameraRepository(),
    child: MultiBlocProvider(
      providers:[
        BlocProvider<Bloc1>(
          cameraRepository: RepositoryProvider.of<CameraRepository>(context),
        ),
        BlocProvider<Bloc2>(
          cameraRepository: RepositoryProvider.of<CameraRepository>(context),
        ),
      ]
      child: SomeUIWidget(),
    ),
  ),

```

I just want that the camera controller initials when the repository creates and is released when the widget dispose of.  Now I add a close method to the CameraRepository and call the close method in Bloc1's dispose method.

**Comment by felangel** [comment]
@marklureal thanks for the quick response! In your case, I would not recommend having a CameraRepository because that is UI-specific logic. Instead, I would recommend having a bloc to manage the feature-logic and state while managing/interacting with the `CameraController` from within your UI (via a `StatefulWidget`). Let me know if that helps 👍

**Comment by marklureal** [comment]
@felangel Thanks for the quick response too. Let's change the CameraRepository to some SqlDatabaseRepository.there are still two blocs that share the SqlDatabaseRepository. The database connection is created when the SqlDatabaseRepositoy creates and I want the database connection is closed when UI dispose of.  How about this situation?

**Comment by felangel** [comment]
@marklureal in that case you could have your feature blocs calling `connect`/`disconnect` on the repository.

**Comment by marklureal** [comment]
Thanks! I’m clear now.

Felix Angelov <notifications@github.com>于2020年3月17日 周二上午12:20写道：
