### ISSUE TITLE
change to inital state when event is dispatched

### ISSUE THREAD

**Issue by maheshbhattaraai** [felangel/bloc#956]
While using bottom navigation bar . When main page loaded, dispatch event in init state and I pass down bloc to child page using bloc provider. When i access bloc state from child page , state changes to initial state. How can i figure out this error.(PS event dispatch works fine value changes perfectly ). Thank You.

**Comment by felangel** [comment]
Hi @maheshbhattaraai 👋 
Thanks for opening an issue!

Are you able to share a link to a sample app which illustrates the issue you're having? Thanks!

**Comment by maheshbhattaraai** [comment]
Its Fixed. Thank you for quick response.
`
               children: pages .map(
(page) => BlocProvider(create: (context)=>_itemBloc,child: page,),
                ).toList(),
`
In this way we provide bloc for all pages.But i want to pass on bloc on specific page so how can i make avilable bloc for specific page only.

**Comment by felangel** [comment]
@maheshbhattaraai no problem! You should just wrap the one page with a `BlocProvider`.
