### ISSUE TITLE
Deference in event handling functionality between V2.0.1 and v3.2.0

### ISSUE THREAD

**Issue by pazhut** [felangel/bloc#979]
My main app screen include a MAP object that needs to be centralized base on GPS location. i had implemented the following strategy:
- at main.drat i an using a MultiBlocProvider to create all the blocs, for the bloc (MainMapBloc) that match the map screen i am adding an event:
runApp(MultiBlocProvider(
    providers: [
      BlocProvider<AuthenticationBloc>(
        create: (context) => AuthenticationBloc(
          authenticationRepository: authenticationRepository,
          consumerRestApiRepository: consumerRestApiRepository,
          storageRepository: storageRepository
        ),
      ),
      BlocProvider<InitializationBloc> (
        create: (context) => InitializationBloc(
          authenticationRepository: authenticationRepository,
          consumerRestApiRepository: consumerRestApiRepository
        ),
      ),
      BlocProvider<MainMapBloc>(
        create: (context) => MainMapBloc(
          provideRestApiRepository: provideRestApiRepository,
          geolocatorRepository: geolocatorRepository
        )..add(GetCurrentLocation())
      ),
      BlocProvider<ProviderProfileBloc>(
        create: (context) => ProviderProfileBloc(
          provideRestApiRepository: provideRestApiRepository
        ),
      ),
      BlocProvider<TasksMngrBloc>(
        create: (context) => TasksMngrBloc(
          taskRestApiRepository: taskRestApiRepository
        ),
      )
    ],

- my expectation is that the event will get processed while my app going via the init process, this is long enough so the GPS location will have time to be read

- when i get to to map screen, at the initState function i check for the current bloc status and if it indicates the GPS location was received i initialize the map object correctly:
mainMapBloc = BlocProvider.of<MainMapBloc>(context);
    if (mainMapBloc.state is CurrentLocationReceived) {
      CurrentLocationReceived state = mainMapBloc.state;
      _center = LatLng(state.latLng.latitude,state.latLng.longitude);
      _cameraPosition = CameraPosition(target: _center,zoom: _zoom);
      _SaveObjectState();
    }

this is working perfectly good using flutter_bloc 2.0.1, but when i am updating to the latest release - 3.2.0 the venet is not processed and when i get to the map screen the bloc is not in the expected state

 i will appreciate is someone can help as i would like to keep with the latest version

**Comment by felangel** [comment]
Hi @pazhut 👋 
Thanks for opening an issue!

Have you tried setting the `lazy` property to `false` on your `BlocProvider`?

```dart
BlocProvider(
  lazy: false,
  create: (context) => TasksMngrBloc(
  taskRestApiRepository: taskRestApiRepository
),
```

Let me know if that helps 👍

**Comment by pazhut** [comment]
Hi Felix

that did the trick

Thanks much

Paz
