### ISSUE TITLE
How to Pass object in BlocProvider.of

### ISSUE THREAD

**Issue by sathya4code** [felangel/bloc#982]
Hi,
I want to pass some object/data while calling particular event using the BlocProvider.of.

For example BlocProvider.of<AuthenticationBloc(**data:data**)>(context).add(SomeEvent());

Is this possible?

Thanks,
Sathya.

**Comment by Ahmzyjazzy** [comment]
If your custom event expect an object/data you can pass it using the snippet below

`BlocProvider.of<AuthenticationBloc>(context).add(SomeEvent(data: data));`

The above applicable if your Event is using a name param. Otherwise you can perform same operation like this.

`BlocProvider.of<AuthenticationBloc>(context).add(SomeEvent(data));`

**Comment by sathya4code** [comment]
> AuthenticationBloc

Hi @Ahmzyjazzy ,

I want to pass the param to AuthenticationBloc.

example BlocProvider.of<AuthenticationBloc(**data:data**)>(context).add(SomeEvent());

**Comment by felangel** [comment]
Hi @sathya4code 👋 
Thanks for opening an issue!

You can pass arguments to the bloc via the constructor when it's created

```dart
BlocProvider(
  create:(_) => AuthenticationBloc(data: data),
  child: ...
),
```

Or if the data is more dynamic as @Ahmzyjazzy mentioned you should pass the data to the bloc via an event

```dart
BlocProvider.of<AuthenticationBloc>(context).add(SomethingHappened(data:data));
```

Hope that helps 👍

**Comment by Ahmzyjazzy** [comment]
> Hi @Ahmzyjazzy ,
> 
> I want to pass the param to AuthenticationBloc.
> 
> example BlocProvider.of<AuthenticationBloc(**data:data**)>(context).add(SomeEvent());

@sathya4code you can implement this as mentioned by @felangel above. Bloc dependency arguments are passed through the constructor.

**Comment by sathya4code** [comment]
> Hi @sathya4code 👋
> Thanks for opening an issue!
> 
> You can pass arguments to the bloc via the constructor when it's created
> 
> ```dart
> BlocProvider(
>   create:(_) => AuthenticationBloc(data: data),
>   child: ...
> ),
> ```
> 
> Or if the data is more dynamic as @Ahmzyjazzy mentioned you should pass the data to the bloc via an event
> 
> ```dart
> BlocProvider.of<AuthenticationBloc>(context).add(SomethingHappened(data:data));
> ```
> 
> Hope that helps 👍

@felangel, thank you. I will try this.
