### ISSUE TITLE
Having UI states and data states in the same bloc best practice

### ISSUE THREAD

**Issue by SandroMaglione** [felangel/bloc#983]
I often implement multiple blocs in which I make a remote request, where the states are for example `Loading`, `Error`, `Success`, etc.

After the remote request is complete, I get the result from this call and I need to provide the resulting object to the UI. The UI states (Loading, Error, Success) are strictly related to the data states (a bloc containing as state the deserialized object from the remote request result) because the object is available right after a Success state is yielded.

What is the best practice in this situation? Is it better to create a unique bloc for both UI and data states (which requires me to pass the object as null until a Success state is reached) or to decouple them in two different blocs and having the UI bloc call a data bloc event to create the object once the Success state is reached?

**Comment by felangel** [comment]
Hi @SandroMaglione 👋 
Thanks for opening an issue!

I would structure the blocs to handle application/feature logic and would think of the states being emitted as view models. I generally wouldn't recommend having "data" blocs and instead would recommend your bloc request the data and convert it into a view model for the UI layer to consume.

How you represent your states will vary based on the feature/use-case but in general if properties are exclusive (A and B cannot be possible at the same time) then I would represent them as subclasses:

```dart
abstract class MyState {}

class A extends MyState {}

class B extends MyState {}
```

Alternatively if A and B are possible at the same time, then I find it makes it easier to have a single class with properties for both A and B like:

```dart
class MyState {
  final propertyA;
  final propertyB;

  const MyState({@required this.propertyA, @required this.propertyB});
}
```

Hope that helps 👍

**Comment by SandroMaglione** [comment]
Could you explain your idea with an example?

Let's say I need to fetch some data about the user. The user is modeled in a `User` class and has some required properties.
```dart
class User {
   final String name;
   final String email;
   final int age;
}
```


**Option 1**: I implement a `RequestBloc` which manages the remote request to fetch the user data.
```dart
class RequestBloc extends Bloc<RequestEvent, RequestState> 
```
`RequestState` contains a `Loading` state that runs while the request is processed while showing to the user a loading indicator. It then has a `Success` state that is yielded when the data is received successfully. 

What would happen in this case? Should the `Success` state contain a `User` object as a parameter?
```dart
class Success extends RequestState {
   final User user;
}
```
In such a case, what would happen if I then need to switch to other states while keeping a reference to the same user instance? Would I need to carry the `User` instance between each state?
```dart
User user = null;
if (state is Success) {
   final user = state.user;
} else { ...?... }
yield Loading();
...
yield Success(user);
```
Furthermore, in this situation, I would need to check the exact state before being able to access the user object.
```dart
if (state is Success) { ... }
```

**Option 2**: Another solution would be to make all the `RequestState` extended states to have the `User` as shared property. However, this would require the user to be `null` until a Success state is reached.
```dart
abstract class RequestState extends Equatable {
   final User user;
}
```

**Option 3**: The last option I thought was to have the `User` as a state in a separate bloc and use the `RequestBloc` to pass the user to this new bloc.
```dart
class UserBloc extends Bloc<UserEvent, User> 
```
In this situation, there would be an `InitUserEvent` which will be called on `Success` from the `RequestBloc` to initialize the `User` state.
```dart
class RequestBloc extends Bloc<RequestEvent, RequestState> {
   final UserBloc user;
   ...
   Stream<RequestState> _mapRequest() async* {
      ...
      userBloc.add(InitUserEvent(user));
   }
}
```

What do you think about those solutions? Is there another option?
Thanks for your help and for the discussion :smile:

**Comment by felangel** [comment]
I would recommend having a `UserBloc` which manages the logic for requesting the current user. Whether or not you go with option 1 or option 2 depends on whether you want to have access to a user in all states. In this case, I would probably only include the user in the success state because it doesn't make sense to have a user in a loading/error state. If you'd like to discuss this further it would probably be easier to do via [discord](https://discord.gg/Hc5KD3g). Closing for now but feel free to comment with additional questions and again feel free to message me on discord and I'm happy to setup a call to talk through your use case in more detail 👍
