### ISSUE TITLE
[Question] Right way to inject repository into bloc

### ISSUE THREAD

**Issue by ZeBrody** [felangel/bloc#984]
Hello.
I'm using a layered architecture split into Repository, Bloc and UI. Bloc depend on repository and the ui depend on the bloc. The UI should know nothing about the repository.

```
class MyBloc extends Bloc<MyEvent,MyState> {
    final MyRepository _repository;

    MyBloc(this._repository);

   ....
}
```

I provide the repository globaly at the base with Repository Provider:

```
runApp(RepositoryProvider<MyRepository>(
    create: (_) => MyRepositoryImplementation(),
    child: MyApp(),
));
```

And later, in a page, i use the repository provider to inject it into my bloc like this:

```
return BlocProvider<MyBloc>(
    create: (context) => MyBloc(RepositoryProvider.of<MyRepository>(context)), //dependency on repository here
    child: MyWidget(), //widget that uses MyBloc
);
```

My problem with this approach is, that it stills add a dependency to the repository in the widget, so i guess the approach is wrong.

How should i tackle this issue? Do i need  to make some sort of BlocFactory? I could use some global injector like get_it, but i would rather not and if thats the way, what is the point of RepositoryProvider?

**Comment by felangel** [comment]
Hi @ZeBrody 👋 
Thanks for opening an issue!

I would recommend differentiating between "container" widgets and "presentation" widgets. Container widgets would provide the necessary dependencies to the presentation widgets and presentation widgets would consume these dependencies and handle rendering the proper UI.

```dart
class HomeScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => HomeBloc(myRepository: context.repository<MyRepository>()),
      child: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return BlocBuilder<HomeBloc, HomeState>(
      builder: (context, state) {
        ...
      }
    );
  }
}
```
This allows you to keep your features/screens self-contained while enabling you to easily test your widgets. Hope that helps 👍

**Comment by ZeBrody** [comment]
Thank you for the quick response! I feel like this is a concept worth mentioning in the recipes section of the docs.

And thank you for this library, it's great :)
