### ISSUE TITLE
Bloc for local state management, and the use of redux for global state management. Is this true?

### ISSUE THREAD

**Issue by jet10000** [felangel/bloc#987]
https://medium.com/flutter-community/let-me-help-you-to-understand-and-choose-a-state-management-solution-for-your-app-9ffeac834ee3

I read an article today about the use of bloc for local state management, and the use of redux for global state management. Is this true? I recently learned about svelte, which is also based on reflective state management, but there have stores for global state management.

**Comment by felangel** [comment]
Hi @jet10000 👋 
Thanks for opening an issue!

That article was written by my teammate @jorgecoca a long time ago and is out-dated. We tried early on to use redux + BLoC as described in the article but after a while we decided it wasn't the right combination for us. @jorgecoca maybe we should write a follow-up 😛

**Comment by jorgecoca** [comment]
@jet10000 that article is outdated. If you want to learn more about how we use BLoC, this might help you:

https://www.droidcon.com/media-detail?video=362740965
