### ISSUE TITLE
BlocBuilder not returning HomePage after authentication transition

### ISSUE THREAD

**Issue by Addeuz** [felangel/bloc#988]
Hello,

I have implemented your login example in my worked perfectly up until recently..

From the beginning I had this problem that when I authenticate myself and the state changes to `AuthenticationAuthenticated` the app doesn't return the HomePage widget..

This is my BlocBuilder that handles the authentication state:
```
BlocBuilder<AuthenticationBloc, AuthenticationState>(
  builder: (context, authState) {
    if (authState is AuthenticationAuthenticated) {
      print("Authenticated");
      return HomePage();
    }
    if (authState is AuthenticationUnauthenticated) {
      print("LoginPage loading");
      return LoginPage(userRepository: userRepository);
    }
    if (authState is AuthenticationLoading) {
      return CircularProgressIndicator()      
    }

    print("SplashPage");
    return SplashPage();
  },
),
```

I know that the code enters the first if statement because `Authenticated` is printed out in the debug console..
And I know that the state updates correctly. Because my BlocDelegate prints out the correct state. And when I restart the app from VS Code, the next time the app loads I'm logged in..

But all of this I fixed a month ago by using this code:
```
...
if (authState is AuthenticationAuthenticated) {
  print("Authenticated");
  WidgetsBinding.instance.addPostFrameCallback((_) {
    Navigator.of(context).push(
      MaterialPageRoute(
        builder: (context) => HomePage(),
      ),
    );
  });
  // return HomePage();
}
...
```

So I wait for the build to finish then I use a `Navigator` to push the `HomePage` instead

This solution worked perfectly up until this week..

Now when I use that solution I get this result:
![Skärminspelning-2020-03-25-kl -09 40 03](https://user-images.githubusercontent.com/12641358/77517711-e37f6b00-6e7c-11ea-89cf-bed97a557831.gif)

This behaviour is not what I expect and it seems like the builder can't decide what to do. Because in the debug console I get this output:
![image](https://user-images.githubusercontent.com/12641358/77518115-791afa80-6e7d-11ea-804d-606ca57a8bb3.png)
It seems to go between the `AuthenticationAuthenticated` state and `AuthenticationUninitialized` state. But my BlocDelegate doesn't output anything. So I don't really know what is happening.

And it is extra annoying because this solution has worked for almost 2 month.. And I started getting this behaviour when just this week.

So I want to go back to the original solution of returning the `HomePage`. But as I said earlier that doesn't work either..

I don't think I can share the repository for the public because I'm doing this work for a client. But if it is necessary maybe we can figure something out..

Would love to find the solution for this issue..

**Comment by felangel** [comment]
Hi @Addeuz 👋 
Thanks for opening an issue!

This is happening because you are pushing your `Home` on top of the current page so when you logout you must also call `Navigator.of(context).pop()`.

You could make this automatic by using a `BlocConsumer` in your root widget like

```dart
BlocConsumer<AuthenticationBloc, AuthenticationState>(
  listener: (context, authState) {
    if (authState is AuthenticationUnauthenticated) {
      Navigator.of(context).popUntil((route) => false);
    }
  },
  builder: (context, authState) {
    if (authState is AuthenticationAuthenticated) {
      print("Authenticated");
      return HomePage();
    }
    if (authState is AuthenticationUnauthenticated) {
      print("LoginPage loading");
      return LoginPage(userRepository: userRepository);
    }
    if (authState is AuthenticationLoading) {
      return CircularProgressIndicator()      
    }

    print("SplashPage");
    return SplashPage();
  },
),
```

Hope that helps 👍

**Comment by Addeuz** [comment]
Thank you @felangel, it worked!

But I want to refactor the way that I use the `Navigator..`. What would be the best way to navigate in an app with your login example? I have experienced and found issues when using `pushNamed...`. So what is the best way of handling navigation then??
